### ISSUE TITLE
Feature request: GUI at least for simple commands

### ISSUE THREAD

**Issue by gerchicov-bp** [trufflesuite/truffle#1000]
I found this repo but I didn't understand how it works:
https://github.com/kitze/JSUI
it allows to write all your scripts in `package.json` (even those which call terminal) and display them as simple buttons instead of typing them from time to time.

If you don't plan to add GUI to truffle then could you at least explain how that app calls terminal commands on button clicks?

**Comment by cgewecke** [comment]
@gerchicov-bp I think this kind of integration is a ways off - occasionally this gets mentioned as something we could add to the existing ganache client UI. 

If you're looking for a simple example of running a shell command from an electron app, [this](https://github.com/martinjackson/electron-run-shell-example) seems promising.
