### ISSUE TITLE
Test errors during npm test with the monorepo (Node 10 only)

### ISSUE THREAD

**Issue by roschler** [trufflesuite/truffle#1011]
I had one or two errors during the `npm test` step of installing the monorepo.  The other tests appear to have run correctly.  Attached is the error output for the failed test(s).

[truffle-monorepo-test-errors.txt](https://github.com/trufflesuite/truffle/files/2101717/truffle-monorepo-test-errors.txt)

**Comment by cgewecke** [comment]
@roschler Yes, this error is being raised on Node 10 and so far has only been reported for `truffle install` in #985. Do you know which test(s) failed? What is your Node version?

**Comment by roschler** [comment]
@cgewecke Doesn't the file I attached show the failed tests?  If not, what other info do you need that's not in that file?  Let me know and I'll rerun the tests.

I'm running Node v10.2.1

**Comment by cgewecke** [comment]
@roschler Sorry maybe I'm blind but all I see is error output from `promisify-node` without any info about which test triggered it.

**Comment by roschler** [comment]
@cgewecke My fault.  I truncated the report in the wrong place.  Attached is the full tests report.
[truffle-monorepo-test-errors-full.txt](https://github.com/trufflesuite/truffle/files/2102846/truffle-monorepo-test-errors-full.txt)

**Comment by cgewecke** [comment]
Thanks @roschler - this bug originates in [ethpm-js](https://github.com/trufflesuite/ethpm-js/blob/master/lib/installer.js#L2) (thanks so much for your log output). Will get a PR open to fix today and will track problem at #985.

Closing.
