### ISSUE TITLE
 Contract send should accept a tx_params object

### ISSUE THREAD

**Issue by sebastien-kr** [trufflesuite/truffle#1030]
This is partially copied off of the old repo issue 101 : https://github.com/trufflesuite/truffle-contract/issues/101

## Expected behaviour

`send()` should optionally consume a `tx_params` object.

## Actual behaviour

The contract.js `send()` function doesn't accept a `tx_params` object.

This is unintuitive since almost every other function provided does accept a `tx_params` object. Due to the nature of JS, no errors or warnings are given, making this a potential source of nasty bugs.

In Web3.js the `send()` function takes a `tx_params` object which makes truffle's `send()` behavior really confusing. 

## Documentation

`send()` and `sendTransaction()` (which takes a  `tx_params` !) are not documented. 
This makes the issue really frustrating and hard to fix. Basically you have to find someone who already had the problem.

**Comment by cgewecke** [comment]
@sebastien-kr Thanks for opening this. 

We're in the process of upgrading `truffle-contract` to `web3 1.0` and that work should available in the next few weeks. I believe this will no longer be an issue then - will add a regression test to our suite to make sure it behaves as expected.

**Comment by gnidan** [comment]
Looks like this is done. Let us know if that's not true. Thanks!
