### ISSUE TITLE
Extra accounts for testing

### ISSUE THREAD

**Issue by scyclow** [trufflesuite/truffle#1047]
Running tests with truffle provides you with 10 test accounts. However, I need one more test account. How can one create an 11th test account with test ethereum?

**Comment by cgewecke** [comment]
@scyclow If you run truffle dev blockchain [ganache-cli](https://github.com/trufflesuite/ganache-cli) separately you can configure it to create any number of accounts. Set up a 'development' network config in your `truffle.js` following the docs [here](https://truffleframework.com/docs/advanced/configuration).

In a separate terminal tab, launch ganache-cli
```
ganache-cli --accounts 11
```
In your original tab run 
```
truffle test
```

**Comment by cgewecke** [comment]
@scyclow Closing for house-keeping, please ping if you'd like more help with this.
