### ISSUE TITLE
abstract constract truffle migrate error : "The contract code couldn't be stored, please check your gas amount."

### ISSUE THREAD

**Issue by carbonnetwork** [trufflesuite/truffle#1048]
When I migrate a ERC20 token use "truffle migrate" command, I got an error message:"The contract code couldn't be stored, please check your gas amount."
Then I have many tries ,but it doesn't work ever unless I comment the abstract function in parent constract. I create a simple example and it also have the problem, the example code is 
```
//AbstractContract.sol
pragma solidity ^0.4.23;

contract AbstractContract {
	function add (uint a, uint b) public returns(uint res);
}
```
```
//ImplContract.sol
pragma solidity ^0.4.23;

import "./AbstractContract.sol";

contract ImplContract is AbstractContract {
	constructor() public {}	

	function add (uint a, uint b) public returns(uint res) {
		return a + b;
	}
}
``` 
```
//2_deploy_contracts.js
var AbstractContract = artifacts.require("./AbstractContract.sol");
var ImplContract = artifacts.require("./ImplContract.sol");

module.exports = function(deployer) {
  deployer.deploy(AbstractContract);
  deployer.deploy(ImplContract);
};
```

migrate result:
```
truffle(development)> migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xf626f59d9098afa78984e7f7c83490c7cd46a6de659301b24c124d26f8a856db
  Migrations: 0x7a5e568fd52e5cf9a01508a7fbded825894e7ffb
Saving successful migration to network...
  ... 0xef21b36d9dc1b9a88f47844a0e5f4dd1ec798d06f9e457c2c13557f0513087b3
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying AbstractContract...
  ... 0xa0d7f2b17c1d9de393126c68e8d6d7c35017b2ad4da6cfafb6011332526da9cb
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
```
I'm not sure the problem caused by truffle or ganache-cli or ethereum , or  my usage incorrect. Could someone help me, thanks very much.

**Comment by cgewecke** [comment]
Hi @carbonnetwork That's correct - you cannot deploy an abstract contract because it has no bytecode - it's only a language feature provided by Solidity to help you define interfaces for 'real' contracts. To use one just import it into a file with a contract which implements the abstract methods.

The error messages for this case are confusing and inadequate - we're tracking that problem at #971 and it should be resolved by work we're doing on the migrations command for Truffle V5.

Hope you don't mind - closing as a duplicate

**Comment by carbonnetwork** [comment]
@cgewecke Thanks for your explain.
