### ISSUE TITLE
pet-shop box (Uncaught Error: Cannot find module 'fs')

### ISSUE THREAD

**Issue by umlspec** [trufflesuite/truffle#1049]
"truffle unbox petshop" generates a useful template for users. The issue is "app.js" in the folder "src/js/" 

App = {
  web3Provider: null,
  contracts: {},

  init: function() {
    // Load pets.
    $.getJSON('../pets.json', function(data) {
      var petsRow = $('#petsRow');
      var petTemplate = $('#petTemplate');

      for (i = 0; i < data.length; i ++) {
        petTemplate.find('.panel-title').text(data[i].name);
        petTemplate.find('img').attr('src', data[i].picture);
        petTemplate.find('.pet-breed').text(data[i].breed);
        petTemplate.find('.pet-age').text(data[i].age);
        petTemplate.find('.pet-location').text(data[i].location);
        petTemplate.find('.btn-adopt').attr('data-id', data[i].id);

        petsRow.append(petTemplate.html());
      }
    });

    return App.initWeb3();
  },

  initWeb3: function() {
    /*
     * Replace me...
     */

    return App.initContract();
  },

  initContract: function() {
    /*
     * Replace me...
     */

    return App.bindEvents();
  },

  bindEvents: function() {
    $(document).on('click', '.btn-adopt', App.handleAdopt);
  },

  markAdopted: function(adopters, account) {
    /*
     * Replace me...
     */
  },

  handleAdopt: function(event) {
    event.preventDefault();

    var petId = parseInt($(event.target).data('id'));

    /*
     * Replace me...
     */
  }

};

$(function() {
  $(window).load(function() {
    App.init();
  });
}); 

In the beginning of this code, i just put the following to use file system modules provided by Node.js

const fs = require('fs')

The error message "Uncaught Error: Cannot find module 'fs' "

I think that this template looks for only local "node_modules" directory in the project. It can't look for "node_modules" in the directory "c://windows/program files/nodejs/node_modules", where Node.js was installed in Windows OS.

Another exmaple, 
const _ = require('lodash') is also not recognised with the same error after "npm install lodash --save"

Instead, i put the following CDN link in the "index.html"

<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.10/lodash.min.js"></script>

It works without declaring "const _ = require('lodash') " . 

Please, let me know where i am wrong. Or "pet-shop" template has a bug ??

Thanks

**Comment by cgewecke** [comment]
@umlspec 
+ What windows shell are you in? People seem to have good luck with [PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/getting-started-with-windows-powershell?view=powershell-6).
+ This StackOverflow [thread](https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows) might be helpful.

**Comment by umlspec** [comment]
i have tested this problem at both Powershell and Gitbash. The same problem occurred.

i have added two envionments path variables, but it has not been resolved.

C://Program FIles/nodejs/node_modules/npm
c://users/my_id/AppData/Roaming/npm

let me know another suggestion. 

Thanks

**Comment by cgewecke** [comment]
Hi @bmmpxf 

Are you able to run Petshop on your windows box at the moment? Have you seen any of the errors that @umlspec is describing above?

**Comment by umlspec** [comment]
yes, i can run it if i do not include "const fs = require('fs')"

**Comment by cgewecke** [comment]
@bmmpxf Thanks - yes agree this is not pet-shop specific. It's possible the `fs` package is problematic on windows although that's not turning up a lot in a google search.

**Comment by umlspec** [comment]
The template "Tutorialtoken" has also the same issue. 

I wish that the designer of "petshop" and "tutorialtoken" would investigate this issue soon.

They are very nice templates, which are better than "webpack" template(personally i think). But they can't be extended to other bigger projects due to failing to include modules supported by Node.js and third party.

**Comment by tiguere** [comment]
I am having the same problem on mac os using the same syntax. Does anyone have any suggestions for pulling npm package from a different directory

**Comment by sabertooth9** [comment]
Facing the same issue in windows

**Comment by DeveloperAbhirupa** [comment]
Facing the same issue on linux

**Comment by CobbleGen** [comment]
I had the same problem but it said: Error: "Error: Cannot find module 'fs-extra'". Simply doing 'npm install fs-extra -g' fixed it.

**Comment by kevinchensr** [comment]
Facing the same issue on ubuntu

**Comment by johnsonCJZ** [comment]
Facing the same issue on mac and windows
