### ISSUE TITLE
A potential bug in contract.js - throws if the last argument of transaction call is null

### ISSUE THREAD

**Issue by aleybovich** [trufflesuite/truffle#1057]
If I make a transaction call and the last argument I pass is null, the code throws an error. I found that this code is to blame (line 140 in contract.js as of current revision):

```
synchronizeFunction: function(fn, instance, C) {
      var self = this;
      return function() {
        var args = Array.prototype.slice.call(arguments);
        var tx_params = {};
        var last_arg = args[args.length - 1];

        // It's only tx_params if it's an object and not a BigNumber.
        if (Utils.is_object(last_arg) && !Utils.is_big_number(last_arg)) {
          tx_params = args.pop();
        }
```

`Utils.is_object()` returns `true` for `null` values, so it's assumed to be an object and later on is attempted to get parsed for settings (like `from`, `value` etc.) and throws `TypeError: Cannot convert undefined or null to object`

There should be a check for `null` value either inside `Util.is_object()` or here on the line `if (Utils.is_object(last_arg) && !Utils.is_big_number(last_arg)) {`. 

This line should be this instead: 

`if (lastArg && Utils.is_object(last_arg) && !Utils.is_big_number(last_arg)) {`

**Comment by cgewecke** [comment]
Nice bug report (as always ) @aleybovich - thanks.

All new `truffle-contract` work is happening on the `next` branch which uses Web3 1.0 and targets a major release coming this summer. Will make sure this is fixed there and add a regression test for it.

**Comment by aleybovich** [comment]
Thank you! By the way, I'm very much looking forward to the new truffle version that uses web3 1.0 - right now I have to run with two versions side by side which sometimes causes odd issues. Now if only Metamask updated their web3 version as well, the world would become such a better place :))

**Comment by gnidan** [comment]
I'm assuming this one is fixed with the Truffle v5 stuff? Closing; correct me if I'm wrong. Thanks!
