### ISSUE TITLE
truffle unbox Quintor/angular-truffle-box npm install error

### ISSUE THREAD

**Issue by breckinridge22** [trufflesuite/truffle#1065]
I am trying to unbox the angular truffle box. When I try to execute the command truffle unbox Quintor/angular-truffle-box in a new directory it fails on the node-gyp rebuild. Has anyone had this issue?

Here is a copy of the error logs:

1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/BreckStodghill/workspace/truffleAngular/node_modules/sha3
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/BreckStodghill/.npm/_logs/2018-06-26T15_10_50_646Z-debug.log

**Comment by cgewecke** [comment]
@breckinridge22 Could you open this issue at the box in question?

Closing - it's conceivable that this is truffle related but we don't have the resources to support all the boxes from this repository. If the difficulty can be narrowed down to something in code-base here, please feel free to re-open.
