### ISSUE TITLE
truffle-contract errors in react-native box

### ISSUE THREAD

**Issue by darioAnongba** [trufflesuite/truffle#1067]
Hi,

I'm trying to use truffle-contract in a React Native app but this error is thrown:
`undefined is not a function (evaluating 'Object.setPrototypeOf(ExtendableBuiltin, cls)')`

Surprisingly, this error doesn't appear when launching the app with the Remote JS debugger. I wasn't able to identify the cause of the error.

This issue has already been declared: https://github.com/trufflesuite/truffle-contract/issues/113 without solution.

Thank you,
Dario

**Comment by cgewecke** [comment]
@darioAnongba Thanks for porting this over. Have renamed it the issue a bit, hope that's ok.
