### ISSUE TITLE
Truffle exits w/syntax error on Windows & Node 10.5

### ISSUE THREAD

**Issue by khajaasmath786** [trufflesuite/truffle#1071]
Hi, I have installed truffle framwork but I am getting below error. may I know how to resolve it.

PS C:\Windows\system32> npm install -g truffle@4.0.4
C:\Users\yyy1s41\AppData\Roaming\npm\truffle -> C:\Users\yyy1s41\AppData\Roaming\npm\node_modules\truffle\build\cli.bund
led.js
+ truffle@4.0.4
added 92 packages from 316 contributors in 3.433s
PS C:\Windows\system32> truffle version
C:\Users\yyy1s41\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:2253
});
^

SyntaxError: Unexpected token }
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)

PS C:\Windows\system32>

Versions of  NPM are below

PS C:\Windows\system32> node -v
v10.5.0
PS C:\Windows\system32> npm -v
6.1.0

**Comment by cgewecke** [comment]
@khajaasmath786 Are you able to use a more recent release? We're currently publishing at `4.1.13`?

**Comment by khajaasmath786** [comment]
C:\Users\yyy1s41\AppData\Roaming\npm\truffle -> C:\Users\yyy1s41\AppData\Roaming\npm\node_modules\truffle\build\cli.bund
led.js
+ truffle@4.1.13
added 81 packages in 18.767s
PS C:\Windows\system32> truffle version
C:\Users\yyy1s41\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:2380
                    return this.Decryptor.create(ciph
                                                 ^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
PS C:\Windows\system32>



Stil the same issue? I am on the node versions mentioned in earlier thread. is this causing any issues?

**Comment by cgewecke** [comment]
@khajaasmath786 It's possible - if you `nvm use 8` does this still happen? We've seen a few unusual errors with Node 10. 

The syntax error is coming from a dependency `crypto.js`, will investigate over there and see if there's a known issue...

**Comment by khajaasmath786** [comment]
I didn't get the what is nvm use 8 does this still happen? You mean to say that I need to use version 8?

**Comment by cgewecke** [comment]
Oh apologies I misread your error and though you were using `nvm` which is a node version manager that lets you toggle between node versions easily. 

If it's not impossible you might try Node 8 and see if it works, yes.

**Comment by cgewecke** [comment]
More info: `crypto.js` is only used in `truffle-contract-schema` and was last updated 5 months ago, which makes it seem more likely that Node 10.5 is the source of the issue here.

**Comment by cgewecke** [comment]
@khajaasmath786 What is different about the second machine you installed on? Why is it working on that one?

**Comment by cgewecke** [comment]
@khajaasmath786 Closing for house-keeping - it seems like you might have worked this out? Please ping here if you have more info and wan't to keep this issue open.
