### ISSUE TITLE
Truffle registering wrong network ID artifact

### ISSUE THREAD

**Issue by mmezian** [trufflesuite/truffle#1078]
## Issue

When I complete a deployment, I have to manually edit the network ID as it is wrong.

I deploy on Rinkeby, which is network 3, but when I go to my contract's .JSON on build/contracts, there is "4" (which is mainnet) so I have to manually edit it to 3 everytime.

## Steps to Reproduce

truffle deploy --reset --network rinkeby (which is 3)

**contents of my truffle.config file:** 
```javascript
module.exports = {

  networks: {
    development: {
      host: "localhost",
      port : 8545,
      network_id: "*",
      gas: 6700000
    },
    testnet: {
      provider: function() {
        return new HDWalletProvider(process.env['TESTNETMNEMONIC'], `https://${process.env['TESTNET']}.infura.io/${process.env['INFURATOKEN']}`);
      },
      network_id: 2
    },
    rinkeby: {
      provider: function() {
        return new HDWalletProvider(process.env['RINKEBYNETMNEMONIC'], `https://rinkeby.infura.io/${process.env['INFURATOKEN']}`);
      },
      network_id: 3
    },
    mainnet: {
      provider: function() {
        return new HDWalletProvider(process.env['MAINNETMNEMONIC'], `https://${process.env['MAINNET']}.infura.io/${process.env['INFURATOKEN']}`);
      },
      network_id: 4
    }, solc: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  }
};`
```
## Expected Behavior

Should write network id 3 instead of 4 on the .JSON file

## Environment
windows 10 / truffle v4.1.12 and solidity v0.4.24

**Comment by cgewecke** [comment]
@mmezian Here is a list of network ids (source: [stackexchange](https://ethereum.stackexchange.com/questions/17051/how-to-select-a-network-id-or-is-there-a-list-of-network-ids))
```
0: Olympic, Ethereum public pre-release testnet
1: Frontier, Homestead, Metropolis, the Ethereum public main network
1: Classic, the (un)forked public Ethereum Classic main network, chain ID 61
1: Expanse, an alternative Ethereum implementation, chain ID 2
2: Morden, the public Ethereum testnet, now Ethereum Classic testnet
3: Ropsten, the public cross-client Ethereum testnet
4: Rinkeby, the public Geth PoA testnet
8: Ubiq, the public Gubiq main network with flux difficulty chain ID 8
42: Kovan, the public Parity PoA testnet
77: Sokol, the public POA Network testnet
99: Core, the public POA Network main network
7762959: Musicoin, the music blockchain
61717561: Aquachain, ASIC resistant chain
[Other]: Could indicate that your connected to a local development test network.
```

+ When truffle connects to a public network in order to submit transactions, it queries it directly for its `id`. Rinkeby is `4`, so the network id being written to the artifact is correct.  
+ When truffle searches the artifacts for instances that are known to be deployed on a network, it relies on the the `network_id` in the config. 
+ These need to match for everything to work correctly.

**Comment by mmezian** [comment]
Thank you CGEWECKE!

@truffle team please you need to add important things like this on your documentation...

**Comment by cgewecke** [comment]
Thanks @mmezian - agree this could be clearer. . . will add this to our list of docs improvements.
