### ISSUE TITLE
Error: replacement transaction underpriced (Infura)

### ISSUE THREAD

**Issue by mmezian** [trufflesuite/truffle#1079]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I launch many functions that write into storage through the truffle "exec" command into RINKEBY, I often get Error: replacement transaction underpriced for some of the calls. 

I'm using the HDWALLETPROVIDER to execute storage functions on RINKEBY.

>   provider: function() {
>         return new HDWalletProvider(process.env['RINKEBYNETMNEMONIC'], `https://rinkeby.infura.io/${process.env['INFURATOKEN']}`);
>       },

I tried searching the issue online, but its pointing me to other issues regarding NONCE and executing byte transactions.

## Steps to Reproduce

Using truffle exec --network rinkeby, I have a file that launches 50 to 100 functions that write into storage. 

When I use "await" it works, but it takes too long (15-30min...), so I am now trying without await, synchronously.

But when I arrive at the 80th function, all the next ones have the following error : 
Error: replacement transaction underpriced

I tried adding a 500 ms timeout between each function, this doesn't seem to help.

Strangely, this seems to happen more often when I have more storage function calls (100 instead of 50)

## Expected Behavior

Transactions should go through normally and appear in the blockchain once mined. Here only 3/4 of them are stored, all those with errors are not.

## Actual Results

(node:4092) UnhandledPromiseRejectionWarning: Error: replacement transaction underpriced
    at ProviderError.ExtendableError (C:\Users\mezia_000\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-error\index.js:10:1)
    at new ProviderError (C:\Users\mezia_000\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-provider\error.js:17:1)
    at C:\Users\mezia_000\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-provider\wrapper.js:71:1
    at C:\Users\mezia_000\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-provider\wrapper.js:129:1
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\web3-provider-engine\index.js:150:9
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\once.js:12:16
    at replenish (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\eachOfLimit.js:61:25)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\eachLimit.js:43:36)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\doLimit.js:9:16
    at end (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\web3-provider-engine\index.js:127:5)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\once.js:12:16
    at next (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\waterfall.js:21:29)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\onlyOnce.js:12:16
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\once.js:12:16
    at next (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\waterfall.js:21:29)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\onlyOnce.js:12:16
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:460:23
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\once.js:12:16
    at next (C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\waterfall.js:21:29)
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\async\internal\onlyOnce.js:12:16
    at C:\Users\mezia_000\Documents\Work\Ject\POLY\ERC721Token\node_modules\web3-provider-engine\subproviders\hooked-wallet.js:488:21
(node:4092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
id: 13)

## Environment

windows 10 / truffle v4.1.12 and solidity v0.4.24

**Comment by cgewecke** [comment]
@mmezian There's more discussion of this specific error [here](https://ethereum.stackexchange.com/questions/27256/error-replacement-transaction-underpriced). 

Questions:
+ Are these txs meant to occur in a strict sequence / can they run in parallel? 
+ If parallel, is it possible for you to distribute them across many accounts? I'm not sure how viable this is with `truffle-hdwallet-provider` itself, although there are [some forks](https://github.com/crypedit/truffle-wallet-provider) of that repo which allow you to generate many accounts and use a keystore.

The `nonce too low` issue may come into play here as well because infura load-balances its traffic across various nodes and network latency seems to result in some txs that were sent 'second', propagating 'first'.

**Comment by mmezian** [comment]
hi @cgewecke , thanks for your answer!

Unlike contract deployment, I don't need these to run in strict sequence, that's why I'm trying to run them synchronously. 

I need it to be from one single account, as the contract verification requires those actions to be performed by the owner of the contract.

Does anyone have a workaround ? 

Should I setup a higher timeout, like 5 seconds, between each of them ? Which would be 500 seconds for 100... but it's fine. 

Maybe I should only do async ones for MAIN NET to avoid these issues

**Comment by cgewecke** [comment]
@mmezian Status update: this topic has come up at truffle-hdwallet-provider recently and a little bit of headway has made there in [issue 65](https://github.com/trufflesuite/truffle-hdwallet-provider/issues/65). Did you ever find a workable solution for your use case?
