### ISSUE TITLE
Allow `truffle develop` to be configurable

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1090]
Right now, running `truffle develop` uses default parameters defined [here](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/environment.js#L120-L125)

It would be nice if this were configurable in `truffle.js`, perhaps under the `networks.develop` section.

**Comment by fainashalts** [comment]
@CruzMolina is this issue resolved now? Wondering if we can close it.

**Comment by CruzMolina** [comment]
Thanks for the reminder! Closing.
