### ISSUE TITLE
Contract Change Bug

### ISSUE THREAD

**Issue by mattiyat** [trufflesuite/truffle#1091]
**Environment** 

Windows 10 64 bit machine running Truffle v4.1.13, Solidity v0.4.24, Ganache v1.1.0, Node v8.11.3 and npm v5.6.0

The bug is caused by a Truffle project containing two contracts of the similar filename. The user must name the second contract the same as the first with one integer appended (e.g. Test.sol, Test1.sol).
After migrating the projects' contracts to Ganache, running "truffle test" causes a test to only migrate the contract containing the integer in the filename and ignore migrating other contracts.

**Steps to replicate:**

1. git clone https://github.com/tcoulter/truffle-bug.git
2. Start Ganache.
3. Ensure the RPC server is running on the same port as in the truffle.js file.
4. Open Terminal.
5. Navigate to Truffle project directory.
6. Run "truffle migrate --network ganache".
7. After successfully migrating, run "truffle test".

The expected behavior is for all contracts to be compiled, but as you can see, only the contract with the integer appending the filename is being compiled.

I tried testing multiple integers appended to the filename (ie. Logic123), differing case with the starting character (ie. logic1) and running "truffle test" without migration first. I also tried a non-natural integer (0) but the result was the same. I found that remigrating to Ganache, then running test again would compile all contracts except the one with the appended integer. This could be an issue with not specifically declaring the contract in the migration files as well as the compiler not expecting filenames to contain an integer after a string.

**Comment by cgewecke** [comment]
@mattiyat Thanks for such a clear description! 

Unfortunately I followed your steps and am not able to reproduce this locally. . . could you link to a simple github repo reproduction of this problem so I can clone it and try again?

**Comment by mattiyat** [comment]
@cgewecke My apologies! 

The repo: https://github.com/tcoulter/truffle-bug.git 

Edit: Updated the steps above to clone this repo.

**Comment by cgewecke** [comment]
@mattiyat Thanks! It looks like this bug might affect Windows only - tried to get that to fail on OSX and everything seemed fine. . . .requires further investigation I guess.
