### ISSUE TITLE
How to debug a "public view " solidity function

### ISSUE THREAD

**Issue by carbonnetwork** [trufflesuite/truffle#1092]
The "truffle debug" argument is transaction ID, but some times we need to watch the expression's value in the function decorated by "view" identifier. What can I do for that. Thanks!

**Comment by cgewecke** [comment]
Hi @carbonnetwork. Support for `view` and `pure` is planned for the debugger but not currently possible. The debugger 'replays' transactions and at the moment it requires the tx hash to identify  the relevant execution. 

Another trufflesuite engineer, @seesemichaelj has recently written a real-time trace debugger called Velma that supports these modifiers - you might be interested in checking it out [here](https://github.com/SeesePlusPlus/velma). 

Additionally, you might be able to work around this in the `truffle-debugger` by temporarily removing the modifier, running the function as a transaction and seeing where it fails. You won't get a return value but you'll be able to step through the logic.

**Comment by carbonnetwork** [comment]
@cgewecke Thank you for your reply !

**Comment by elranu** [comment]
Hi,
     it is still not possible to debug a view function with truffle? Thanks
