### ISSUE TITLE
solidity will remove ``constant`` from their json ABI with version ``0.5.0``

### ISSUE THREAD

**Issue by ekpyron** [trufflesuite/truffle#1093]
With the next breaking release solidity will remove the ``constant`` field from the JSON ABI for contract functions, since it is redundant (``constant`` is the same as ``stateMutability === 'view' || stateMutability === 'pure'``).

I'm in the process of implementing this change in the solidity repo, but we want to make sure that everything that depends on the ``constant`` field can be updated first.

I think the main change that is required on your end, should be in ``truffle-compile/index.js``. However, I'm not an expert for your code base and any help would be highly appreciated. @gnidan @cgewecke?

**Comment by ekpyron** [comment]
And to already give you a heads-up: We plan to remove the ``payable`` field as well, since it is the same as ``stateMutability == 'payable'``.

**Comment by cgewecke** [comment]
Thanks @ekpyron :)

The one place I see is actually at [truffle-contract/lib/contract.js](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-contract/lib/contract.js#L41) where Truffle automates whether or not web3 methods are invoked as calls or sends. This should be simple to update and be backwards compatible as well using the `stateMutability` alternative you suggest above.

@gnidan?

**Comment by gnidan** [comment]
@ekpyron is removing `payable` part of v0.5.0 also? I'd like to clean this up all in one fell swoop.

**Comment by ekpyron** [comment]
@gnidan (Already mentioned on gitter, but I'll comment here as well for reference):

If we manage to get external projects to update to be compatible soon enough, we'd like to remove both ``payable`` and ``constant`` in 0.5.0.

**Comment by gnidan** [comment]
Truffle will support either format in v5 onward. Closing this for issue maintenance. Please let us know if you run into any trouble.

(Also please let us know when you plan to proceed with that ABI format change!)

Thanks!
