### ISSUE TITLE
Unit test wrong results not match when using async/await paradigm

### ISSUE THREAD

**Issue by moshebeeri** [trufflesuite/truffle#1094]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Calling same logic fails when using async/await paradigm 

## Expected Behavior

expected to be the same 

## Actual Results

failure to provide the result

## Environment

* Operating System: Mac
* Ethereum client: ganache
* Truffle version (`truffle version`): 4.1.13
* node version (`node --version`):v8.11.1
* npm version (`npm --version`): 6.0.1

```
  const user1 = accounts[4]

  before(async () => {
    myToken = await MyToken.deployed()
    owner = await myToken.owner.call()
  })

  it('should deposit and reflect on user balance', async () => {
    await myToken.deposit.call(user1, 20000)
    let balance = await myToken.balanceOf.call(user1)
    assert.equal(balance.valueOf(), 20000, `The balance 20000 was not reflected.`)
  })

  it('should deposit and reflect on user balance Sync', () => {
    return MyToken.deployed().then(function (instance) {
      myToken = instance
      return myToken.deposit(user1, 20000)
    }).then(function () {
      return myToken.balanceOf.call(user1)
    }).then(function (user1balance) {
      assert.equal(user1balance, 20000, 'The balance 20000 was not reflected.')
    })
  })

```
And the result:

<img width="816" alt="screen shot 2018-07-10 at 6 44 36 pm" src="https://user-images.githubusercontent.com/574405/42521392-64355630-8471-11e8-93a2-1f56846ce263.png">

Any idea whats wrong?

**Comment by cgewecke** [comment]
@moshebeeri Could you see if this discrepancy goes away when you remove the `.call` postfix from deposit in the `async/await` test?
```javascript
await myToken.deposit.call(user1, 20000) // <-- `.call`?
```

**Comment by moshebeeri** [comment]
Yep it solved it, should not be any .call in async 
But the the docs shows the wrong method
see [https://truffleframework.com/docs/getting_started/javascript-tests](url)
There is an example with call (lets call it a docs bug 🥇 )
`     let balance = await instance.getBalance.call(accounts[0]);
`

```
  it('should deposit and reflect on user balance', async () => {
    await myToken.deposit(user1, 20000)
    let balance = await myToken.balanceOf(user1)
    assert.equal(balance.valueOf(), 20000, `The balance 20000 was not reflected.`)
  })

  it('should deposit and reflect on user balance Sync', () => {
    return MyToken.deployed().then(function (instance) {
      myToken = instance
      return myToken.deposit.call(user1, 20000)
    }).then(function () {
      return myToken.balanceOf.call(user1)
    }).then(function (user1balance) {
      assert.equal(user1balance.valueOf(), 20000, 'The balance 20000 was not reflected.')
    })
  })

```

**Comment by cgewecke** [comment]
@moshebeeri Agree the docs are quite antiquated and confusing here, thank you for highlighting this.

 You actually don't need to use these postfixes at all with truffle - it automatically figures out which mode to call a function in. You might be interested in the note left [here](https://github.com/trufflesuite/truffle/issues/1076#issuecomment-401497884) that explains the difference between making a `call` and sending a transaction. 

I'm going to close because the original issue seems resolved - we have plans to update and modernize our docs for the upcoming major release (V5). Will make sure to revisit the section in question and clear it up. Thanks.
