### ISSUE TITLE
On Windows, running `truffle` command yields blank - please display a message to use Powershell / GitBash (or display anything at least)

### ISSUE THREAD

**Issue by stefek99** [trufflesuite/truffle#1119]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

https://gitter.im/ConsenSys/truffle?at=5b4f78d98fe2780689c152b2

---------------------------

## Issue

Windows.
`truffle`
In some folders it displays the list of commands.
In actual truffle project, output is completely empty.

## Steps to Reproduce

Get a cheap laptop from Amazon while main machine is under repair...

## Expected Behavior

Gimme some message - use Powershell or Git Bash.

## Actual Results

Blank.

## Environment

* Operating System:  Windows
* Ethereum client:
* Truffle version (`truffle version`): latest
* node version (`node --version`): latest
* npm version (`npm --version`): latest

(installed everything few moments ago)

**Comment by cgewecke** [comment]
@stefek99 From gitter it looks like you solved this problem:
> Yep, figured it out: trufflesuite/truffle#150 Need to use Git Bash

There's more help for windows users in the docs [here](https://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows)

Closing because docs address this issue.

**Comment by stefek99** [comment]
You are right.

There are docs.

It was just me who wasted some time.

New, cheap, travel laptop. Is `node` installed? Is `npm` in the path? Is it `cmd` or some console emulator?
