### ISSUE TITLE
Enable migrations.sol free migrations

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1120]
This may be a non-issue after #1115 but it came up twice today (in Slack with Simon De La Rouviere and with the nori team). Lot's of people don't want to use the migrations contract as such, but they do want a place and a formalism for staging deployments. . .

**Comment by gnidan** [comment]
We'll consider possible solutions in the future for how to address this. Thanks for bringing this up!

**Comment by gnidan** [comment]
This should be fixed. We got rid of this requirement awhile ago. Closing this, but let us know if that doesn't meet your expectations!
