### ISSUE TITLE
Find elegant upgrade solution for Web3 1.0 number strings

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1126]
Problem: Web3 0.x returned numbers as BigNumber (or BN) objects. Web3 1.0 returns them as strings, IIRC they made this change because they thought the lib should be agnostic about how large numbers are managed and strings are common to all the solutions. 

Unfortunately this is moderately catastrophic for large existing test suites. Was not enthusiastic about coercing the new outputs back into the old format because:

+ it's complicated, we'd have to read the ABI and handle all the different data structures that might have numbers nested in them. 
+ truffle-contracts behavior should be isomorphic to web3's - it's injected into the test context and its methods can be called independently.
+ web3 is likely right about handling numbers in this simpler way? 

**Damage Survey**

Zeppelin uses chai-bignumber / BigNumber and has ~550 occurrences in their suite.
```
balance.should.be.bignumber.equal(amount);
```

Colony's `colonyNetwork` has ~400 occurrences of the `.toNumber()` method (which is common to BN and BigNumber). 
```
task1[5].toNumber()
```
The colony case might have a simple resolution - we should be able modify the String prototype for the test context to be something like:
``` 
> String.protoype.toNumber = function() { return parseInt(this) };
> '5'.toNumber();
5
>
```

**Comment by cgewecke** [comment]
On reflection I'm going to look into how difficult it really is to return BNs from a call. It might not be that bad.

**Comment by gnidan** [comment]
Sorry for not getting back to you on this!

I'm on board with returning BN instances if it's not too hard. I think it's better than returning strings, although I expect this might not be very popular.

**Comment by cgewecke** [comment]
@gnidan Yeah, there aren't a lot of good choices here. . . we should probably talk about this more. I'll work up a PR and ask Tim what he thinks too.

**Comment by cgewecke** [comment]
#1138 (Still need to fix events)
