### ISSUE TITLE
Support local path for soljson.js in the CompilerSupplier

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle#1130]
The benefit here would be for the Solidity project to supply the newly built `soljson.js` library as part of the CI process when testing imported projects, such as: Zeppelin, Gnosis and Augur (the first two use truffle).

Until now we had to resort to manually:
- replacing `node_modules/truffle/bin/soljson.js` (or something like that)
- and replacing the `pragma solidity` lines.

**Comment by cgewecke** [comment]
@axic At the moment I think this *is* supported for npm installed solc - the relevant code is [here](https://github.com/trufflesuite/truffle/blob/next/packages/truffle-compile/compilerSupplier.js#L142-L154). It pulls `solc` in via a `require` modified to be web-packable. Does this work for your case? 

Usage:
```javascript
compilers: {
  solc: {
    version: "/Users/user/.nvm/versions/node/v8.9.4/lib/node_modules/solc"    
  }
}
```

**Comment by gnidan** [comment]
Closing this as duplicate of #1274
