### ISSUE TITLE
Consider using solc-js's `versionToSemver` in CompilerSupplier

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1131]
In [`translate.js`](https://github.com/ethereum/solc-js/blob/master/translate.js)

This function ensures that version strings adhere to semver, so that the normal npm semver lib can parse correctly

(@axic suggested this instead of `getCommitFromVersion`)

**Comment by axic** [comment]
I think this is still valid.

**Comment by eggplantzzz** [comment]
It looks like Truffle code no longer uses the `getCommitFromVersion` method. I'm going to create an issue to remove it unless I am mistaken.

So otherwise is there anything else actionable here?
