### ISSUE TITLE
Inform user when downloading solc version

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1132]
In case of slow internet or such. Otherwise it just appears to hang.

It'd be nice if there was an output message that indicated something like:
```
Downloading solcjs 0.4.25-nightly.2018.7.20+commit.d3000e70...
```

**Comment by eggplantzzz** [comment]
@gnidan Was this resolved with PR #1299 ?
https://github.com/trufflesuite/truffle/pull/1299
