### ISSUE TITLE
Upgrade web3 to beta 35

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1142]
`beta 33` is missing a method `web3.eth.getNodeInfo` (which aliases `eth_clientVersion`)

**Comment by cgewecke** [comment]
`beta 34` also:
+ sets the status field to boolean instead of returning `0x00` / `0x01`
+ breaks our error handling (because it stopped emitting a receipt on tx revert). 
+ breaks method layer confirmations for reasons that are still a mystery. The confirmations are emitted but the `number` param passed to the event isn't incremented.

**Comment by Freyert** [comment]
May I propose `beta 35`? It includes a fix that allows for websocket communication with basic auth headers.

**Comment by cgewecke** [comment]
@Freyert Yes definitely - thanks for suggesting. Might be a little bit before this happens though because some of the changes in 34 (especially the way the receipt is withheld on error for standard clients) are a little problematic for `truffle-contract`.

**Comment by cgewecke** [comment]
@Freyert This is shipped with`next.9` and hopefully from here on out we'll be able to bump web3 easily whenever they make improvements.
