### ISSUE TITLE
Truffle test fails when defining Array.prototype function

### ISSUE THREAD

**Issue by ldub** [trufflesuite/truffle#1147]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`node_modules/.bin/truffle test` fails when defining an `Array.prototype.someFunction`

## Steps to Reproduce

Full repro repo here: https://github.com/ldub/truffle-bug-repro/

1. Use node 10 and npm 6
2. Add the following code to a javascript test file
```
Array.prototype.zip = function (otherArray) {
    return this.map((e,i) => [this[i], i < otherArray.length ? otherArray[i] : null]);
};
```
3. `node_modules/.bin/truffle test`

## Expected Behavior

Tests should pass.

## Actual Results

Test fails with exception:
```
/Users/lev/dev/truffle-bug-repro/test/simplestorage.js:4
    return this.map((e,i) => [this[i], i < otherArray.length ? otherArray[i] : null]);
                ^
TypeError: this.map is not a function
    at Client.Array.zip (/Users/lev/dev/truffle-bug-repro/test/simplestorage.js:4:17)
    at Client.emit (/Users/lev/dev/truffle-bug-repro/node_modules/truffle/build/webpack:/~/event-pubsub/es5.js:74:1)
    at Socket.connectionClosed (/Users/lev/dev/truffle-bug-repro/node_modules/truffle/build/webpack:/~/node-ipc/dao/client.js:187:1)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

## Notes
* tests pass if I use `truffle test` instead of `node_modules/.bin/truffle test`
* something in the toolchain (likely webpack) is running or transpiling code that my repro does not even use

## Environment

* Operating System: macOS
* Ethereum client: N/A (truffle's built-in testrpc)
* Truffle version (`truffle version`): 
```
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
```
* node version (`node --version`): v10.3.0
* npm version (`npm --version`): 6.1.0

**Comment by cgewecke** [comment]
Hi @ldub 👋 

Wow weird! Will investigate although this is quite strange. Out of curiosity if you use lodash or another utility that has an array `zip` method does everything work? This is something about overloading the `Array` prototype?

Also do you have an insight about how webpack might be the culprit here? The tests are passed to Mocha - that seems like another candidate.

**Comment by ldub** [comment]
Definitely not using lodash and the bug can be reproduced with any identifier, not just zip:

```
Array.prototype.ldubFunc = function(abc) {
    this.map();
}
```

As for why I suspect webpack
* `ldubFunc` does not overload anything
* `ldubFunc` is never called
* webpack supports transpiling and stack trace contains webpack in  `truffle/build/webpack:/~/event-pubsub/es5.js:74:1`
* actual error is at `at Client.Array.ldubFunc (/Users/lev/dev/truffle-bug-repro/test/simplestorage.js:4:10)`
  * it seems like my prototype function is being put onto something called `Client.Array` instead of `Array`, which to me smells of a possible transpilation issue
  * still not sure how `ldubFunc` can even be called anywhere

But the reality is that I have a fairly poor understanding of modern web technologies like webpack and babel and the above list is mostly guesswork. I don't really know where to start digging to figure out the true cause of the bug, if you have any pointers I'd be happy to do some exploration.

I suspect that the fact that `truffle test` works but not when you run `node_modules/.bin/truffle test` is an important point... what is the difference between the truffle I can install with `npm install -g` and the truffle thats installed in the node_modules folder?

**Comment by gnidan** [comment]
@ldub Could you please paste the output of `./node_modules/.bin/truffle version`? Just in case it's different?

Thanks!

**Comment by ldub** [comment]
@gnidan

```
[nix-shell:~/dev/eth/eth/truffle-bug-repro]$ ./node_modules/.bin/truffle version
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
```

**Comment by gnidan** [comment]
Is this still a problem? Doing issue maintenance and wondering what the status here is. Thanks!

**Comment by ldub** [comment]
Just tried this with the following versions and the exception no longer happens.

```
Truffle v5.1.3 (core: 5.1.3)
Solidity - 0.4.24 (solc-js)
Node v10.17.0
Web3.js v1.2.2
```
