### ISSUE TITLE
Allow default network configuration

### ISSUE THREAD

**Issue by danielfx90** [trufflesuite/truffle#1154]
## Issue

Current default network name is hard-coded to `development`, which may collide with the naming convention for the homologous remote environment. It would be nice to be able to override this default, maybe by placing a `defaultNetwork` option in `truffle.js` file.

## Steps to Reproduce

Declare a `development` network configuration in the `truffle.js` file and run `truffle console`. 

## Expected Behavior

Try to take the default network name from `truffle.js` file or use `development` if there is none.

## Actual Results

Truffle uses `development` network whenever the `--network` option is not specified.

**Comment by gnidan** [comment]
@danielfx90 I'd definitely consider this. Please feel free to open a PR!

**Comment by gnidan** [comment]
Note though: there's a couple "default" networks:
- `"develop"` for `truffle develop`
- `"test"` for `truffle test`
- `"development"` for migrate / catch-all

It might be worth taking this into account when deciding on the config params.

**Comment by danielfx90** [comment]
@gnidan Sounds great! We'll open a PR at @wibsonorg as soon as we meet our next deadline.
