### ISSUE TITLE
Error: Attempting to run transaction which calls a contract function

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1172]
~~Not sure where this originates, probably web3.~~ Looks like this is a ganache error that's [under investigation](https://github.com/trufflesuite/ganache-core/pull/119). 
```
Attempting to run transaction which calls a contract function, but recipient address 0xcad2ad49baf2459b06cf754eaa389ea79fe90bd3 is not a contract address.
```

This seems to be thrown when you inherit from an abstract contract and forget to implement one of its methods.

**Comment by cgewecke** [comment]
@haydenyoung added that they saw this error under another condition too:
> What ended up solving the problem was that I was missing a constructor in the child contract which calls the parent contract's constructor. Implementing this fixed the problem.

**Comment by jtakalai** [comment]
Here's a situation where I got that error:

I'd written in a file `test/A.js` something like 
```
it ("testing", () => {
    contract.callStuff()
})
```
and as a result another file `test/B.js` would give that error. After fixing A.js to
```
it ("testing", async () => {
    await contract.callStuff()
})
```
the problem disappeared. So it can be... almost anything. Fun times with Truffle.

**Comment by gnidan** [comment]
So, it's been a year. What's going on here? Are the errors still bad? Looks like there's a couple different underlying situations that could use better error reporting.

If anyone can give us some specific reproduction steps, we can take a look at improving the experience here. Thanks all!

**Comment by gnidan** [comment]
And now it's been a year and a month :)

Going once? Going twice?

Thanks all 🙇

**Comment by gnidan** [comment]
Gone!
