### ISSUE TITLE
How to use {privateFor:['...']} in truffle-contract package (Quorum)

### ISSUE THREAD

**Issue by karapish** [trufflesuite/truffle#1177]
Truffle deployment scripts can gracefully deploy private contracts and issue **private** transactions. I would like to reference truffle-contract npm package in my nodejs service to emit private transactions as well. Unfortunately, I am getting errors while invoking a function of my private contract, e.g. myContract.myFunc(params, {privateFor:['..']}). I can't find any example here explaining how to use privateFor option properly. Please advise

**Comment by cgewecke** [comment]
@karapish There's a Quorum tutorial [here](https://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains), that contains a number of examples of `privateFor`. 

Your syntax looks correct to me, what is the error?

**Comment by karapish** [comment]
The call with privateFor never returns. It just hangs. When I call a function from JS then Quorum's log on the submission node contains the following spew

INFO [08-09|18:59:57] sent private tx                               data=69da2463f186....
INFO [08-09|19:03:06] sending private tx                       data=e7c890f800....
-----END-----

But when I call the same function directly from truffle console 'sending private tx' is followed by TX checkpoints in the log. 

INFO [08-09|18:59:57] sent private tx                               data=999963f186....
INFO [08-09|19:03:06] sending private tx                       data=55555f800....
INFO [08-09|19:03:06] Submitted transaction                    fullhash=0x5d1bc8ab3b32c6f7194929fc57ec764f6d7544bfd008c79b7ea8e86c6c3fd9c6 recipient=0xd77e6d7c7eE16b83aCBB167d2989FC4E07759174
INFO [08-09|19:03:06] QUORUM-CHECKPOINT                        name=TX-CREATED      tx=0x5d1bc8ab3b32c6f7194929fc57ec764f6d7544bfd008c79b7ea8e86c6c3fd9c6 to=0xd77e6d7c7eE16b83aCBB167d2989FC4E07759174
INFO [08-09|19:03:06] QUORUM-CHECKPOINT                        name=TX-ACCEPTED     tx=0x5d1bc8ab3b32c6f7194929fc57ec764f6d7544bfd008c79b7ea8e86c6c3fd9c6
INFO [08-09|19:03:06] Imported new chain segment               blocks=1 txs=1 mgas=0.000 elapsed=3.670ms   mgasps=0.000   number=56 hash=f438a7…953b43
INFO [08-09|19:03:06] QUORUM-CHECKPOINT                        name=BLOCK-CREATED   block=f438a7323137d1f29c79195169f0f92ae2ed683b5d6e26115a0365af92953b43
INFO [08-09|19:03:06] persisted the latest applied index       index=64

**Comment by cgewecke** [comment]
@karapish To be clear when you say: `call the function from JS` you mean call it using Web3 from the geth console? 

Could you show your `truffle.js`?

**Comment by karapish** [comment]
I can share truffle.js but my deployment works absolutely fine. I can successfully call 
myContractInstance.myFunction(10, {privateFor:["key of node at port 22001"])}; 

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 9545,
      network_id: "*"
    },
    ganache: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*"
    },
    node1: {
        host: "127.0.0.1",
        port: 22000, // was 8545
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    node2:  {
        host: "127.0.0.1",
        port: 22001,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    node3:  {
        host: "127.0.0.1",
        port: 22002,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    node4:  {
        host: "127.0.0.1",
        port: 22003,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    node5:  {
        host: "127.0.0.1",
        port: 22004,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    node6:  {
        host: "127.0.0.1",
        port: 22005,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    },
    X:  {
        host: "127.0.0.1",
        port: 22006,
        network_id: "*", // Match any network id
        gasPrice: 0,
        gas: 4500000
    }
  }};

**Comment by cgewecke** [comment]
@karapish 

Are you actually `await`ing it? Is that missing as a typo?
```javascript
myContractInstance.myFunction(10, {privateFor:["key of node at port 22001"])}; // <-- doesn't work
```

**Comment by karapish** [comment]
Yes, I have await in front of it.

**Comment by cgewecke** [comment]
@karapish Ok hmmmmmm. One thing that the commands do is set some default values for tx params including `gas`, `gasPrice` and `from`. Maybe setting those explicitly in the Node script (using an unlocked account address for `from`)? 
```javascript
const options = {
  privateFor: ...,
  from: <address>
}
  
await myContractInstance.myFunction(10, options);
```

**Comment by karapish** [comment]
Yes, there must be something you guys do to make private tx work during the deployment. I also that that it's the gas price. Similar to what https://github.com/web3j/quorum/blob/defe1af8f0cca87200454903aaf08007124dec8a/src/main/java/org/web3j/quorum/methods/request/PrivateTransaction.java#L22 these guys are doing. 

Can you point to the code in truffle which does account unlocking and gas price overrides?

**Comment by cgewecke** [comment]
@karapish Truffle doesn't do anything specific to unlock accounts - that has to be done on the client. Truffle fetches accounts using: `await web3.eth.getAccounts()`. You can set those per transaction in the same options object that contains the `privateFor` on the `from:` key.

**Comment by karapish** [comment]
It works now!  
function makeOptions(from, privateFor) {
    return {from: from, privateFor: privateFor, gas: 900000, gasPrice: 0};
}

**Comment by cgewecke** [comment]
@karapish Sweeet! Nice job. Closing.
