### ISSUE TITLE
Error Revert when call a function between contracts

### ISSUE THREAD

**Issue by TinyCalf** [trufflesuite/truffle#1180]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
when i calling a contract function that contains calling another contract, it will always throw this error
Error: VM Exception while processing transaction: revert

## Steps to Reproduce
here are the core functions of the two contracts,i deployed them and write the test script:
contract A is  like: 
```
contract A {
    mapping(address => address) public map;
    uint public  i = 1;
    address public i = 0x912312312...;
    
    function test() public view returns(bool) {
        return true;
    }
}
```
contract B is  like： 
```
import "./A.sol";

contract B {
      A a = A(0x.......);
      
     function calltest() public view returns (bool) {
            return a.test();
      } //call this function will fail
   
     function getI () public view returns(uint) {
        return a.i();
    }   // call this function will success

     function getMap (address addr) public view returns(address) {
        return a.map(addr);
    }   // call this function will fail

}
```

## Expected Behavior

all function should run correctly

## Actual Results

when B calls a public variable of A, it always succeed; but call a public function or call a mapping or an array, it will fail. I've tried many versions of truffle.

## Environment
MacOS 10.13.6 Beta
Truffle v4.0.6 (core: 4.0.6) ~ Truffle v4.1.11
Solidity v0.4.19 (solc-js) ~ Solidity v0.4.24
npm v6.2.0
node v10.5.0

**Comment by cgewecke** [comment]
@TinyCalf Could you show everything else around these failures? For example: how is A deployed? How do you get that address into B's contract? Please provide a link to a working reproduction of the bug or complete reproduction steps. 

There's Solidity code in the contracts you've provided that's not correct and/or mocked in:
```
uint public  i = 1;
address public i = 0x912312312...;
```

**Comment by cgewecke** [comment]
@TinyCalf Closing for housekeeping - please ping if you need further help with this.
