### ISSUE TITLE
scripts won't exit in 4.1.13

### ISSUE THREAD

**Issue by djudjuu** [trufflesuite/truffle#1181]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
When running truffle scirpts (e.g. 'truffle compile' or 'truffle networks') the script runs, but does not exit. This is annoying as it is impossible to use truffle scripts in pipelines such as npm's "prepublish"

## Steps to Reproduce

- run truffle networks

## Expected Behavior

list networks and exit process

## Actual Results

it does not exit:

![screenshot from 2018-08-10 15-21-20](https://user-images.githubusercontent.com/9882716/43960063-1987c6c4-9cb1-11e8-956f-30a827bad5ff.png)

## Environment

* Operating System: ubuntu gnome
* Ethereum client:
* Truffle version (`truffle version`): 4.1.13 (older version 4.1.7 did not have the bug)
* node version (`node --version`): v.9.11.2
* npm version (`npm --version`): 6.1.0

**Comment by cgewecke** [comment]
Hi @djudjuu.

Can you show your `truffle.js`? There was a change in the `hdwallet-provider` a couple months ago that makes it critical to wrap it in a function, as shown in the docs [here](https://truffleframework.com/docs/truffle/reference/configuration#providers). If this isn't done it automatically connects to a network and leaves an interval timer open that prevents the script from exiting correctly. 

We're also shipping a more permanent fix for this bug early next week  . . .

**Comment by djudjuu** [comment]
> wrap it in a function when setting the provider, as shown in the docs here. 

spot on. that fixed it!
