### ISSUE TITLE
Truffle console throws for web3.eth.mining status 

### ISSUE THREAD

**Issue by karapish** [trufflesuite/truffle#1183]
Hello. After I am logged in to truffle's console and then type in _web3.eth.mining_ to inquiry the status it throws the following 

truffle(REGULATOR)> web3.eth.syncing
false
truffle(REGULATOR)> web3.eth.protocolVersion
'0x3f'
truffle(REGULATOR)> web3.eth.coinbase
'0x978a347c8abcf88b1facdf04664669c3ad0f3b75'
truffle(REGULATOR)> web3.eth.mining
**Error: The method eth_mining does not exist/is not available**
    at Eth.get [as mining] (/Volumes/Data/blockchain/7nodes/X/node_modules/truffle/build/webpack:/~/web3/lib/web3/property.js:107:1)
    at RequestManager.send (/Volumes/Data/blockchain/7nodes/X/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:61:1)
    at Object.InvalidResponse (/Volumes/Data/blockchain/7nodes/X/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)

**Comment by cgewecke** [comment]
@karapish What client are you using?

**Comment by karapish** [comment]
@cgewecke Please advise on what you exactly mean by 'client'. Maybe you meant the version of truffle?

**Comment by cgewecke** [comment]
@karapish Apologies, ethereum client e.g geth? ganache-cli? parity?

**Comment by karapish** [comment]
Quorum from Azure's marketplace. https://azuremarketplace.microsoft.com/en-us/marketplace/apps/enterprise-ethereum-alliance.eea-single-member?tab=Overview

**Comment by cgewecke** [comment]
@karapish I guess they don't implement it, not sure why. Just tried running the console vs. `geth v1.8.2` in dev mode, auto-mining with `dev.period=1`  and it worked:
```
truffle(development)> web3.eth.mining
true
```

**Comment by cgewecke** [comment]
@karapish I'm going to close because it looks like this a quirk of the Quorum client implementation. Thanks for raising this.
