### ISSUE TITLE
[Proxy] truffle init or unbox fail, cause=connect EINVAL

### ISSUE THREAD

**Issue by SwJay** [trufflesuite/truffle#1184]
## Issue
`truffle init` or `truffle unbox` fails for tunneling socket, arised from connect EINVAL.

## solution
It's solved. I'm behind a proxy, and set the config of *proxy* and *http-proxy* in npm correspondingly. However, truffle goes via the environment variable *HTTP_PROXY* and *HTTPS_PROXY* which I haven't set. After setting environment proxy, quizzles solved.

**Comment by cgewecke** [comment]
@SwJay Thanks for opening this with the solution, should be helpful. This is similar to #766. 

Closing as duplicate.
