### ISSUE TITLE
Wrong abi for mapping(address => uint[])

### ISSUE THREAD

**Issue by ferittuncer** [trufflesuite/truffle#1198]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Wrong abi for `mapping(address => uint[])`

## Steps to Reproduce

Create a contract with `mapping(address => uint[]) foo`.

## Expected Behavior

A getter exactly like this: `foo(address) returns (uint[])`

## Actual Results

A getter exactly like this: `foo(address, uint) returns (uint)`

And this is the abi: 

```
{
  "constant": true,
  "inputs": [
    {
      "name": "",
      "type": "address"
    },
    {
      "name": "",
      "type": "uint256"
    }
  ],
  "name": "userToIds",
  "outputs": [
    {
      "name": "",
      "type": "uint256"
    }
  ],
  "payable": false,
  "stateMutability": "view",
  "type": "function"
}
```

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: Remix
* Truffle version (`truffle version`): 4.1.13
* node version (`node --version`): 8.11.3
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
Hi @ferittuncer. It looks like this is just the way solc implements the getter for that case. 

From [Arrays](https://solidity.readthedocs.io/en/develop/types.html?highlight=accessor#arrays) section at the Solidity docs:

> It is possible to mark arrays public and have Solidity create a getter. The numeric index will become a required parameter for the getter.

More discussion about this topic in #302, including a workaround :)
