### ISSUE TITLE
v5 Solidity tests: Assert doesn’t work

### ISSUE THREAD

**Issue by dwardu** [trufflesuite/truffle#1199]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In truffle@next, in Solidity tests, `Assert.fail()` doesn’t fail the test.

## Steps to Reproduce

Run this test:

```solidity
pragma solidity ^0.4.24;
import "truffle/Assert.sol";
contract TestTruffleAssert {
    function testAssertFail() public {
        Assert.fail("If test fails with this message, Assert.fail is working");
    }
}
```

`Assert.equal`, `Assert.notEqual`, and possibly all the rest, also do not work.

## Expected Behavior

As in Truffle v4.1.14:

```
  0 passing (2s)
  1 failing

  1) TestTruffleAssert
       testAssertFail:
     Error: If test fails with this message, Assert.fail is working
```

## Actual Results

```
  TestTruffleAssert
    ✓ testAssertFail (480ms)
  1 passing (9s)
```

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: Ganache CLI v6.1.8 (ganache-core: 2.2.1)
* Truffle version (`truffle version`): v5.0.0-next.9
* node version (`node --version`): v10.9.0
* npm version (`npm --version`): 6.2.0

**Comment by dwardu** [comment]
Thanks @cgewecke!

**Comment by cgewecke** [comment]
@dwardu This should be fixed on:

+ `truffle@next`
+ `truffle@beta`

**Comment by dwardu** [comment]
Fantastic @cgewecke. It works. Thanks for letting me know!
