### ISSUE TITLE
truffle --version correct / upgrade failed

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/truffle#1205]
I tried to upgrade to version 4.1.14 ... it looked ok, but truffle version still says its 4.1.13

```
$ npm uninstall -g truffle
removed 81 packages in 0.512s
$ npm install -g truffle
/home/sum/.nvm/versions/node/v10.8.0/bin/truffle -> /home/sum/.nvm/versions/node/v10.8.0/lib/node_modules/truffle/build/cli.bundled.js
+ truffle@4.1.14
added 81 packages from 310 contributors in 1.313s
$ truffle --version
Truffle v4.1.13 - a development framework for Ethereum

 $ truffle version
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
```

**Comment by cgewecke** [comment]
@SvenMeyer This might be an npm caching issue - had some trouble with here this morning as we released the `truffle@beta`. 

If you're seeing unusual installs - e.g. not getting the latest version - you can also try:
```
npm cache clear --force
```

**Comment by gerchicov-bp** [comment]
I have the same issue - truffle 4.1.11 persists, `npm uninstall -g truffle` doesn't work

**Comment by gerchicov-bp** [comment]
@SvenMeyer @cgewecke 
https://ethereum.stackexchange.com/questions/52812/error-in-installing-truffle-in-macos
but of course nobody wants to add this info into readme!

**Comment by cgewecke** [comment]
@gerchicov-bp Thanks for adding that link - it looks like an `nvm` configuration issue though right? Is there something specific to truffle going wrong here in your view?

**Comment by SvenMeyer** [comment]
I am using nvm as well, so that might cause the problem.
I have the same problem with another packcgae (ganache-cli) and "npm cache clear --force" did not help

**Comment by gnidan** [comment]
I'm closing this as it seems to be a problem with NPM or NVM. Please reach out on [Gitter](https://gitter.im/ConsenSys/truffle) if this kind of problem persists. Thanks!

**Comment by Water-bamboo** [comment]
That's because you have two truffle bin, the new version install correct, but `truffle version` invoke the wrong one.
