### ISSUE TITLE
Since truffle uses web3 1.x, it may consider also using web3-extended

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle#1206]
See https://github.com/axic/web3-extended.js. It is not published on npm yet, but will be soon.

It aims to implement the RPC methods the official web3 will not take in due to various reasons (mostly client specific or debugging).

Also a PR for adding ganache specific ones would be welcome 😉

**Comment by axic** [comment]
I think this is still valid.

**Comment by axic** [comment]
@cgewecke @gnidan I think this is still a reasonable proposal 😉

**Comment by gnidan** [comment]
Someday the robots will beat the tragically lazy humans, but that day is not today. Thanks for keeping up the good fight @axic.

We'll discuss this at our backlog grooming this week.

**Comment by axic** [comment]
> Also a PR [to web3-extended] for adding ganache specific ones would be welcome 😉

@cgewecke @gnidan I think this is the first step here.

**Comment by davidmurdoch** [comment]
Bump! A ganache-core user [recently suggested](https://github.com/trufflesuite/ganache-core/pull/622#issuecomment-685629595) added this feature.

Web3 1.2.0 docs for the "extend" feature: https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#extend

/cc @aaryamannchallani

**Comment by davidmurdoch** [comment]
Ganache's custom methods are defined our the README, here: https://github.com/trufflesuite/ganache-core#custom-methods

**Comment by eggplantzzz** [comment]
Closing this as a won't implement. We decided that the overhead of a new dep isn't worth the value provided.
