### ISSUE TITLE
Migrations to rinkeby get stuck on V5

### ISSUE THREAD

**Issue by eduardonunesp** [trufflesuite/truffle#1220]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

On truffle v5 when try to deploy on rinkeby with `--interactive` mode after select `yes` it get stuck 

## Steps to Reproduce

On `truffle@next` create a rinkeby migration using infura and deploy with `--interactive`

## Expected Behavior

Deploy like v4 does

## Actual Results

Stuck 

## Environment

* Operating System:  macOS 10.13.6
* Ethereum client: Infura
* Truffle version (`truffle version`): v5.0.0-next.10
* node version (`node --version`): 8.11.4
* npm version (`npm --version`): 6.2.0

**Comment by cgewecke** [comment]
@eduardonunesp Are you using the new version of `truffle-hdwallet-provider` with V5? 

```
npm install --save truffle-hdwallet-provider@web3-one
```

**Comment by cgewecke** [comment]
@eduardonunesp Oh also - do you have an example that I can try to reproduce this with. Ideally we can catch whatever is going wrong here and throw an error that makes sense.

**Comment by eduardonunesp** [comment]
Sure, I'll test and update an example ASAP thanks @cgewecke

**Comment by eduardonunesp** [comment]
Thanks for the help @cgewecke, after install `truffle-hdwallet-provider@web3-one` it worked

**Comment by JohannesMayerConda** [comment]
why use web3-one and is this still the recommended way?
