### ISSUE TITLE
Better help on command line

### ISSUE THREAD

**Issue by eduardonunesp** [trufflesuite/truffle#1224]
## Issue

Currently the terminal still a good source of help when the user needs to get a depth of a command, I wish that too for `truffle`, the main help is `truffle --help` command, but there's no more than that.

## Steps to Reproduce

`truffle --help`

## Expected Behavior

When the user wants to know more options available about a command the user can get help like `truffle help deploy` which can describe the options. Example

```bash
$ truffle help deploy
Truffle v5.0.0-next.10 - a development framework for Ethereum

 --reset         Restart the migrations from the beginning
 --network       Selects the network to be used on the deploy process
 --interactive   After run the simulation asks for the user if the deploy can continue
```

## Actual Results

Always is the same list of help without sub commands help, there's a link to the online documentation which helps a little, however the help on terminal should be a quick reference instead an online page.

```bash
Truffle v5.0.0-next.10 - a development framework for Ethereum

Usage: truffle <command> [options]

Commands:
  init      Initialize new and empty Ethereum project
  compile   Compile contract source files
  migrate   Run migrations to deploy contracts
  deploy    (alias for migrate)
  test      Run JavaScript and Solidity tests
  debug     Interactively debug any transaction on the blockchain (experimental)
  opcode    Print the compiled opcodes for a given contract
  console   Run a console with contract abstractions and commands available
  develop   Open a console with a local development blockchain
  create    Helper to create new contracts, migrations and tests
  install   Install a package from the Ethereum Package Registry
  publish   Publish a package to the Ethereum Package Registry
  networks  Show addresses for deployed contracts on each network
  exec      Execute a JS module within this Truffle environment
  unbox     Download a Truffle Box, a pre-built Truffle project
  version   Show version number and exit

See more at http://truffleframework.com/docs
```

## Environment

* Operating System: 10.13.6
* Truffle version (`truffle version`): Truffle v5.0.0-next.10
* node version (`node --version`): 8.11.4
* npm version (`npm --version`):  6.2.0

**Comment by cgewecke** [comment]
Yes this is a really good idea.
