### ISSUE TITLE
MetaCoin, addr.balance ,Integer overflow

### ISSUE THREAD

**Issue by Eggsyz** [trufflesuite/truffle#1225]
Hello, when I tested the MetaCoin demo, I made a change to the smart contract. I want to get the balance of the local account, but there is an integer overflow. Who can help me answer it? Here are the results of the web page and the results obtained by the geth。

web：You have 1.15792089237316195423570985008687907853269984665179395437614845217563129639935e+77 
META
geth：
> eth.getBalance(eth.accounts[0])
4841649000000000000

smart contract:
```
contract MetaCoin 
{
        mapping (address => uint) balances;
        event Transfer(address indexed _from, address indexed _to, uint256 _value);
        constructor() public {
                balances[tx.origin] = 10000;
        }
        function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
                if (balances[msg.sender] < amount) return false;
                balances[msg.sender] -= amount;
                balances[receiver] += amount;
                emit Transfer(msg.sender, receiver, amount);
                return true;
        }
        function getBalanceInEth(address addr) public view returns(uint){
                return ConvertLib.convert(getBalance(addr),2);
        }

        function getBalance(address addr) public view returns(uint) {
        //      return balances[addr];
                return addr.balance;
        }
}
```

**Comment by gnidan** [comment]
Hi @Eggsyz, did you try asking on [Gitter](https://gitter.im/ConsenSys/truffle)? I'm not sure what the issue might be off the top of my head, if there is an issue with Truffle or not. Any additional information you could provide would be helpful. Thank you!
