### ISSUE TITLE
Write a new CONTRIBUTING guide

### ISSUE THREAD

**Issue by matt9ucci** [trufflesuite/truffle#1237]
The current [CONTRIBUTING.md](https://github.com/trufflesuite/truffle/blob/5ec81e4246d9e56af0b4534b8bf5a5bc94c3ae1b/packages/truffle/CONTRIBUTING.md) is outdated.

The following is @gnidan's comment in #1218:
> Hrm so that CONTRIBUTING guide is way out of date and wrong. We probably don't want to make this more visible. Mind converting this to an issue to "write a new CONTRIBUTING guide"? So that we don't forget about it.

**Comment by cgewecke** [comment]
Hi @matt9ucci 

Just a note: there are some simple instructions in the README [here](https://github.com/trufflesuite/truffle#development) for anyone who wants to develop in the truffle codebase. I guess we'd add some guidelines about including tests with your PR or something....

**Comment by gnidan** [comment]
This work is probably never done, but closing because the CONTRIBUTING.md has been updated. Thanks!
