### ISSUE TITLE
Integrating Ionic project with Truffle

### ISSUE THREAD

**Issue by Sulaiman-Said** [trufflesuite/truffle#1253]
Hello there, can somebody guide me how to integrate an existing ionic app that I've created using ionic framework with truffle, in order the make it a DApp.

**Comment by whittlem** [comment]
I'm not familiar with the ionic framework but I assume you have standard contract files (*.sol)?

Install Truffle:
sudo npm install -g truffle

Make a directory for your DApp:
mkdir ionic_new
cd ionic_new

Create a new project:
truffle init

Copy your contract .sol files into the contracts/ directory

Should be able to compile your contracts now... truffle compile --all

The next parts you need to read up on as they are specific to your DApp...

1. Create a migration file in the migrations directory.... like: 2_deploy_contracts.js
2. Update the truffle-config.js and define your networks 

Fire up TestRPC / Ganache and run: truffle migrate --reset   or    truffle test

I recommend this link for finer details:
https://truffleframework.com/docs/truffle/reference/configuration

**Comment by gnidan** [comment]
Hi @Sulaiman-Said, thanks for opening this issue. Please use our [Gitter channel](https://gitter.im/ConsenSys/truffle) for support questions like these.

If you would like to see additional documentation around topics like this, please feel free to open a new ticket outlining the specific documentation updates you would like. Thank you!
