### ISSUE TITLE
 Deploying Migrations... Error encountered, bailing. Network state unknown. Review successful transactions manually. insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by jfkidear** [trufflesuite/truffle#1256]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
root@ubuntu:/home/jfk/voting# truffle migrate --network ropsten
Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
truffle migrate --network ropsten
truffle.js：
require('babel-register');
var HDWalletProvider = require("truffle-hdwallet-provider");
const fs = require("fs");

var infura_apikey = "xxx";
var mnemonic = fs.readFileSync("mnemonic").toString();//mnemonic phrase (Metamask / Settings / Reveal Seed Words)

module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*', // Match any network id
      gas: 470000 // The global gas value will be used by default, limit: 4728379
    },
    ropsten: {
      provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/" + infura_apik
ey),
      network_id: 3,
      gas: 4700000, // Gas limit used for deploys
      gasPrice: 4000000000
    }
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
}

1_initial_migration.js
var Migrations = artifacts.require('./Migrations.sol')

module.exports = function (deployer) {
  deployer.deploy(Migrations)
}

2_deploy_contracts.js
var Voting = artifacts.require("./Voting.sol");
module.exports = function(deployer) {
  deployer.deploy(Voting, ['Rama', 'Nick', 'Jose'], {gas: 419630});
};

The account in metamask has 0.899958 ETH.

 
## Expected Behavior

What you expected to happen.
The command of truffle migrate executed successfully
## Actual Results
Failed.
What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: ubuntu-16.04-desktop-amd64
* Ethereum client:Geth
Version: 1.8.15-stable
* Truffle version (`truffle version`):Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
* node version (`node --version`):v8.11.4
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@jfkidear Could you try running this migration with Truffle's new beta? It's available by running:
```
npm install truffle@beta
```
It should give you a (slightly) more helpful error message. Things to check:
+ Are you definitely looking at the balance with Metamask set the Ropsten network? You could also verify on [ropsten etherscan](https://ropsten.etherscan.io/).
+ Is the mnemonic being passed to the wallet provider in the config what you expect?

You could check that by writing the provider value as:
```javascript
provider: function(){
  console.log('mnemonic --> ' + mnemonic);
  return new HDWalletProvider(mnemonic, "https://ropsten.infura.io/" + apiKey);
},
```

**Comment by cgewecke** [comment]
Closing for housekeeping, please ping if you're still seeing this error.

**Comment by jfkidear** [comment]
Where do you get mnemonic words? When I import mnemonic the MetaMask creates in MyEtherWallet I find many  addresses you would like to interact with. But nothing is my address.

**Comment by jfkidear** [comment]
@cgewecke

**Comment by kennblvnp** [comment]
@jfkidear did it work? dont just tag him, tell something
