### ISSUE TITLE
test contract should be also the address that deploys the contracts

### ISSUE THREAD

**Issue by arisAlexis** [trufflesuite/truffle#1258]
## Issue

The Test contract should be the same address that deploys the contracts to be tested so that you can test ownership. There should be no reason why the deploy address and test contract address would be different?

## Expected Behavior

the deployed contract's owner is the msg.sender which is the address(this) test contract address.

## Actual Results

You need to redeploy the contract in a beforeAll hook if you want to set the owner correctly

**Comment by cgewecke** [comment]
@arisAlexis Could provide a clear example of the problem you're describing? Are you using solidity tests?

**Comment by arisAlexis** [comment]
Yes.

There is a contract that is deployed that is Ownable and implements the onlyOwner modifier.
For example let's say we are using Ganache on the local network. 

The deployer of the contract is the first account on Ganache and that's the owner of the deployed contract.

You can't test the  functions that use the onlyOwner modifier because the Test Contract is not the owner.

Of course you can redeploy it but why? The Test Contract should use the same first account from Ganache.

It is solidity based testing.

**Comment by ferittuncer** [comment]
Why `{from: accounts[0]` doesn't work?

**Comment by arisAlexis** [comment]
the default account of TestContract has 0 Ether while the Ganache accounts have 100ETH each.  That tells me that the private key is different and it's not the one taken from Ganache.

**Comment by ferittuncer** [comment]
Oh, you mean Solidity testing. Yes it's not possible when testing with Solidity at the moment. I wrote my answer above thinking it's a JS test.

**Comment by gnidan** [comment]
@arisAlexis You have to use something like Zeppelin's `ClaimOwnership` or some kind of ownership transference mechanism to get what you want.

An alternative is to ensure that your contracts are all deployed via migrations - if you have a Solidity test that deploys a contract, then that Solidity test *is* the msg.sender.

Closing as this is an inherent limitation. Thanks for bringing up this concern!
