### ISSUE TITLE
Lost ganache connection when running tests

### ISSUE THREAD

**Issue by sinanofficial** [trufflesuite/truffle#1260]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Lost etherium connection when running tests, especially tests in loops.
{ Error: Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

    at ProviderError.ExtendableError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-error\index.js:10:1)
    at new ProviderError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\error.js:17:1)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:71:1
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:129:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpRequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:544:1)
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:414:1)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Could not connect to your Ethereum client. Please check that your Ethereum client:\n    - is running\n    - is accepting RPC connections (i.e., "--rpc" option is used in geth)\n    - is accessible over the network\n    - is properly configured in your Truffle configuration file (truffle.js)\n',
  stack: 'Error: Could not connect to your Ethereum client. Please check that your Ethereum client:\n    - is running\n    - is accepting RPC connections (i.e., "--rpc" option is used in geth)\n    - is accessible over the network\n    - is properly configured in your Truffle configuration file (truffle.js)\n\n    at ProviderError.ExtendableError (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\truffle-error\\index.js:10:1)\n    at new ProviderError (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\truffle-provider\\error.js:17:1)\n    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\truffle-provider\\wrapper.js:71:1\n    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\truffle-provider\\wrapper.js:129:1\n    at XMLHttpRequest.request.onreadystatechange (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\~\\web3\\lib\\web3\\httpprovider.js:128:1)\n    at XMLHttpRequestEventTarget.dispatchEvent (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\~\\xhr2\\lib\\xhr2.js:64:1)\n    at XMLHttpRequest._setReadyState (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\~\\xhr2\\lib\\xhr2.js:354:1)\n    at XMLHttpRequest._onHttpRequestError (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\~\\xhr2\\lib\\xhr2.js:544:1)\n    at ClientRequest.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\~\\xhr2\\lib\\xhr2.js:414:1)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at Socket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  name: 'ProviderError' }

## Steps to Reproduce

My connection configuration shall be right, because some tests finished as expected, but it will suddenly fail at any point with error above.
I noticed that it will fail in iteration calls more often.
I tried to let block mine every 5 seconds from auto mine, and add sleeping for 5 seconds between transactions, it will be better, but not resolved totally, still fails.

## Expected Behavior
Running without losting connection.
## Environment

* Operating System:  Windows 10
* Ethereum client: Ganache CLI v6.1.8 (ganache-core: 2.2.1)  
* Truffle version (`truffle version`): Truffle v4.1.14
* node version (`node --version`): 8.9.4
* npm version (`npm --version`): 6.4.0

**Comment by cgewecke** [comment]
@sinanofficial How many iterations are your loops? This looks like it might be a duplicate of #729. We think will be resolved with some recent changes at Web3 that make sure the provider is invoked with `KEEP-ALIVE`. At the moment if you are running many thousands of calls to the client Web3 can consume all the available port resources on your OS and triggers this error.
