### ISSUE TITLE
Using truffle-config detect() throws an exception

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/truffle#1275]
## Issue

When trying to use `truffle-config@1.1.0-beta.0` as a dependency within Ganache UI (an electron application), when I try using the `detect()` function, I get the below error:
```
ReferenceError: Unknown plugin "inline-react-svg" specified in "base" at 0, attempted to resolve relative to "/home/mike/work/consensys/truffle/packages/truffle-decoder/test/magic-square"
```
where `inline-react-svg` is a Babel plugin used within Ganache. After talking to @gnidan, we think there may be an issue with how `original-require` is loading the file.

## Environment

* Operating System: Elementary OS 0.4.1 Loki (Ubuntu 16.04 base)
* Ethereum client: NA
* Truffle version (`truffle version`): NA
* node version (`node --version`): 8.11.4
* npm version (`npm --version`): 6.4.1

**Comment by gnidan** [comment]
@seesemichaelj can this be closed? Thanks!

**Comment by seesemichaelj** [comment]
Yup! Good catch.

This can be closed as the issue was not related to truffle at all.
