### ISSUE TITLE
ERC-20 Testing issue 

### ISSUE THREAD

**Issue by ajaysingh902** [trufflesuite/truffle#1290]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

there is testing issues in the beta version .web3.wei ,bignumber and a lot this cannot be used in tested in the beta version .By using the previous version of truffle all the test cases are running properly using the truffle 4.1.14

## Expected Behavior
i was getting this error 
TypeError: web3.toWei is not a function

## Environment

* Truffle version (`truffle version`):5.0.0-beta.0

**Comment by gnidan** [comment]
Truffle v5 uses Web3.js 1.0. Please see the corresponding docs for that version; you will need to update your tests accordingly: https://web3js.readthedocs.io/en/1.0/web3.html

Thank you!
