### ISSUE TITLE
Custom build pipeline stderr semantics

### ISSUE THREAD

**Issue by andrewosh** [trufflesuite/truffle#1294]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using a custom build process, any output on stderr is assumed to be a "build error," and the CLI messages reflect this. I'd imagine Truffle should instead assume that the custom build process interprets its own output correctly, and limits itself to interpreting the return code.

As an example, I have a custom build script that uses `cargo` to compile a few Rust contracts, and my build output is:
```
build error:     Finished release [optimized] target(s) in 0.03s

build error:     Finished release [optimized] target(s) in 0.04s

build error:     Finished release [optimized] target(s) in 0.05s
```

In the Rust world, these informational messages are emitted on `stderr`. 

## Steps to Reproduce

Successfully compile any Rust contract with `cargo build` using a custom build process.

## Expected Behavior

Perhaps just omit the "build error" and let the build script handle errors! With this approach, stderr messages from the builder should just be forwarded to the wrapper's stderr (with `console.error` instead of `console.log`).

Relevant line is [here](https://github.com/trufflesuite/truffle/blob/99d00337477b17e516ebae91f6a53012e1500dc2/packages/truffle-core/lib/build.js#L38)

Thoughts?

## Actual Results

(Described above)

## Environment

(Not relevant to issue)

**Comment by gnidan** [comment]
Thanks for bringing this up! That's a really good point. Feel free to open a PR against `develop` with the change.
