### ISSUE TITLE
Linking libraries inside of test suite without using migrations

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#1298]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Curious how one should link a library inside of test suite without using migrations.
For example:

```js
let x = await Lib.new();
await ContractZ.link(x.address);
let z = await ContractZ.new()
console.log(z.address)
```

getting
```js
TypeError: Cannot read property 'replace' of undefined
      at node_modules/truffle/build/webpack:/packages/truffle-contract/lib/utils.js:113:1
      at Array.forEach (<anonymous>)
      at Object.linkBytecode (node_modules/truffle/build/webpack:/packages/truffle-contract/lib/utils.js:109:1)
      at Function.binary (node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract.js:633:1)
      at Function.getter (node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract.js:388:1)
      at Function.checkLibraries (node_modules/truffle/build/webpack:/packages/truffle-contract/lib/utils.js:139:1)
      at constructor.detectNetwork.then.network (node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract.js:131:1)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)
```

* Operating System: OSX
* Ethereum client: ganache-cli (truffle test internal)
* Truffle version (`truffle version`): `Truffle v5.0.0-next.12 (core: 5.0.0-beta.0)`
* node version (`node --version`): v9.11.2
* npm version (`npm --version`): 5.6.0

# Workaround
I understand that I can fix it if I simply add a link to migrations:
```js
module.exports = async function (deployer) {
    await deployer.deploy(Lib);
    await deployer.link(Lib, ContractZ);
};
```

I was just curious if I can do same thing inside of test suite.

**Comment by gnidan** [comment]
It looks like it might be that `ContractZ`, after linking, does not reflect the link added. Will look into. Thanks!

**Comment by guix77** [comment]
Got the same pb...

**Comment by guix77** [comment]
I got it working, we need to use the 2nd form of link() since with new() the instance is not at the same address as the expected default with deployed(): https://github.com/trufflesuite/truffle-contract#mycontractlinkname-address

```
const myLib = await MyLib.new();
await MyContract.link(MyLib, myLib.address);
const mycontract = await MyContract.new();
```

**Comment by okwme** [comment]
This only worked for me when I wrote it like:
```
const myLib = await MyLib.new();
await MyContract.link("MyLib", myLib.address);
const mycontract = await MyContract.new();
```

**Comment by CplXhristianUSMC** [comment]
Ive been hacked it's verified he has infected my phone with a virus and
it's damaging everything kingoftoffice is what tag he used I'm pretty sure
he is still in my device anything I do or is likely to be recorded somehow
I'm looking to pressure what if anything is left but I am unfimular with
much of the new as i only regained access to my accounts within the last
few 11 or so days ago and he grabbed no less than 200 separate files that
had a lot of private information ie Js master which he placed a viris in
and destroyed many addresses by some means of encryption so as to make them
indisufferable
All this 17years to the day my 1st born son Died
SEMPER FI for the help I'll be happy to try your suggestion but at this
point I'm not entirely sure what or were the info you sent me is to be
placed?

I will try though thanks for the message

White Hats

**Comment by CplXhristianUSMC** [comment]
Thank you so much for your reply I'm sorry that it's taking me so long to
get back to your emails currently I'm in the process of moving and will be
driving no less than 1300 miles tonight across state lines to get to my new
house please forgive any late replies I greatly appreciate any and all work
that you have been doing to help rectify this matter truly thankful and
gratefully yours cplxhristianusmc

**Comment by NatPDeveloper** [comment]
I needed the additional step

```
const myLibrary = await MyLibrary.new();
await MyContract.detectNetwork();
await MyContract.link('MyLibrary', myLibrary.address);
await MyContract.new();
```

Credit: https://forum.openzeppelin.com/t/trouble-linking-library-contracts-with-openzeppelin-test-environment/2235/4
