### ISSUE TITLE
[BETA] truffle debug - ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by thekevinbrown** [trufflesuite/truffle#1302]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I run `truffle debug` without a transaction hash I get this stack trace:

```
$ truffle debug
ReferenceError: callback is not defined
    at /[my project folder]/node_modules/truffle-core/lib/commands/debug.js:39:9
    at web3.eth.getAccounts.then.accounts (/[my project folder]/node_modules/truffle-core/lib/environment.js:72:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Relevant Code

```javascript
      if (config._.length == 0) {
        return callback(new Error(
          "Please specify a transaction hash as the first parameter in order to " +
          "debug that transaction. i.e., truffle debug 0x1234..."
        ));
      }
```

`callback` is not defined in this context, so error handling needs to be different here.

I don't know the code, but looks to me like it should probably be

```javascript
return done(new Error(
  "Please specify a transaction hash as the first parameter in order to " +
  "debug that transaction. i.e., truffle debug 0x1234..."
));
```

## Steps to Reproduce

Run `truffle debug`

## Expected Behavior

I expected Truffle to provide a helpful error message.

## Actual Results

Truffle provides a confusing error message.

## Environment

* Operating System: OS X 10.14 (18A391)
* Ethereum client: Ganache CLI v6.1.8 (ganache-core: 2.2.1)
* Truffle version (`truffle version`):Truffle (unbundled) (core: 5.0.0-beta.0)
Solidity v0.4.24 (solc-js)
* node version (`node --version`): v10.10.0
* npm version (`npm --version`): 6.4.1
* yarn version (`yarn --version`): 1.9.4

**Comment by CruzMolina** [comment]
Thanks for raising this @thekevinbrown !

Fix has been merged via #1325.
