### ISSUE TITLE
Failed to unbox truffle box

### ISSUE THREAD

**Issue by eduardonunesp** [trufflesuite/truffle#1309]
## Issue

Truffle unbox saying that repo doesn't exist even, however, the URL exists also the `truffle-box.json` also exists

## Steps to Reproduce

```bash
truffle unbox loomnetwork/truffle-dappchain-example
```

## Expected Behavior

Download the box and run the scripts according to with `truffle-box.json`

## Actual Results

```bash
$ truffle unbox loomnetwork/truffle-dappchain-example
Downloading...
Error: Truffle Box at URL https://github.com/loomnetwork/truffle-dappchain-example doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Environment

* Operating System: `macOS 10.13.6`
* Truffle version (`truffle version`):  `Truffle v4.1.14 (core: 4.1.14)`
* node version (`node --version`):  `10.11.0`
* npm version (`npm --version`):  `6.4.1`

**Comment by gnidan** [comment]
Interesting @eduardonunesp. Does it work if you provide the full git URL? `git@github.com:...`

It's possible that something is going on where it is trying to use `https://github.com/`, and permissions don't line up correctly (or the other way around, trying to use `git@...`. You can also try configuring git to use one or the other in all cases. (Here's how to force https:// https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe)

**Comment by gnidan** [comment]
Let me know what you find! Thanks!

**Comment by eduardonunesp** [comment]
It failed for `truffle unbox git@github.com:loomnetwork/truffle-dappchain-example` allso `truffle unbox https://github.com/loomnetwork/truffle-dappchain-example`

**Comment by eduardonunesp** [comment]
Force `https` using the `gist` above didn't work also

**Comment by gnidan** [comment]
@eduardonunesp this might be redundant but I'm assuming it also doesn't work if you include the `.git` suffix on those URLs?

**Comment by eduardonunesp** [comment]
Nope didn't work, does that works for you?

**Comment by gnidan** [comment]
Nope, I'm getting the same thing, also on the beta. Will have to look into why this is going on next week.

**Comment by gnidan** [comment]
Found the issue, the PR above should fix.

Workaround in the meantime: make sure the box defines `truffle.js` (since that's the filename currently used to ensure the box is valid)

**Comment by eduardonunesp** [comment]
Nice ! well I do prefer to use `truffle-config.js` (and remove `truffle.js`) to make sure that Windows users are fine too, I'll wait for the fix. Thanks.

**Comment by pynchmeister** [comment]
So is this fixed? Still having trouble here

**Comment by bryanmojica** [comment]
+1, I'm also having this issue currently with `truffle unbox oasislabs/oasis-box` - confirmed that the truffle-box.json exists @ https://github.com/oasislabs/oasis-box, yet am receiving the "doesn't exist" readout.

**Comment by geethuvm** [comment]
Error: Truffle Box at URL https://github.com/truffle-box/pet-shop-box doesn't exist.
