### ISSUE TITLE
Official website (http://truffleframework.com/) is down

### ISSUE THREAD

**Issue by agxmeister** [trufflesuite/truffle#1312]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Your official website http://truffleframework.com/ is down at least two days: ERR_CONNECTION_TIMED_OUT. Is it moved to another location or the Truffle project is dead?

## Steps to Reproduce

Just try to open http://truffleframework.com/ title page or follow any link to official documentation.

## Expected Behavior

Official website should works. :-)

## Actual Results

ERR_CONNECTION_TIMED_OUT

## Environment

Chrome, Edge - the same result. Connection from Russia.

**Comment by gnidan** [comment]
It's up for me. Is it still down for you? If so, does https://truffleframework.com work?

**Comment by agxmeister** [comment]
Looks like this issue is actual only for Russia. :-( I will use VPN to access it, thank you!
