### ISSUE TITLE
compilation keeps fetching versions 

### ISSUE THREAD

**Issue by branaway** [trufflesuite/truffle#1313]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The compilation would fetch all versions from the Internet every time I compiled something. 
case 1: I have version = "native"
case 2: I have version = "0.4.25"

Neither would prevent the process from fetching the sole version info. 

Effectively I could not use truffle without the Internet.

## Steps to Reproduce

Here is what I have in the truffle-config.js:
  compilers: {
        solc: {
            // version: "native",   // let's use the native for faster work. bran: slower for small project!!
            settings: {
                optimizer: {
                    enabled: true, // Default: false
                    // runs: 100     // Default: 200
                },
                //evmVersion: "homestead"  // Default: "byzantium"
            },
            version: "0.4.25"
        }
    }

## Environment

* Operating System:  OSX
* Ethereum client: built-in or Ganache
* Truffle version (`truffle version`): Truffle v5.0.0-beta.1
* node version (`node --version`): v10.10.0
* npm version (`npm --version`): 6.4.1

**Comment by leonprou** [comment]
Hey guys,
Found out that specifying a version range, like:  `version: "^0.6.0"` still not using cache but fetches every time.

**Comment by eggplantzzz** [comment]
Hey @leonprou! Yes, if you provide a semver range like you did, Truffle will go and try to get the most recent compiler version that satisfies. If you want to use a cached version, specify the version you want to use like `version: "0.6.0"`. I hope that helps!

**Comment by leonprou** [comment]
I see, well actually when you put it that way it makes total sense
