### ISSUE TITLE
Debugger: Move breakpoint down if the current line is a declaration

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/truffle#1317]
Breaking/stepping along variable declarations is natural, but if a breakpoint is set on one of these lines that is being skipped, the breakpoint is currently being skipped.

We should do what most normal debuggers do: move the breakpoint down to the next valid non-skipped line (or AST).

**Comment by seesemichaelj** [comment]
@haltman-at or @gnidan is this still an issue?

**Comment by haltman-at** [comment]
Indeed, this remains unfixed.  I'll reopen it.

**Comment by haltman-at** [comment]
OK, I've created PR #1882 to address this issue (at least partially).  It's not perfect, but I think it should be good enough for the practical cases discussed here.  Note that it only alters line-based breakpoints; if you manually advance onto a normally-skipped node with `;`, and then place a node-based breakpoint with a bare `b`, sorry, that one's not getting adjusted (at least not as the PR is currently written).  But I don't expect that to come up too often, so I thought it was OK to ignore that case.

**Comment by haltman-at** [comment]
This has now been merged and released, so I'm closing it.  Let me know if it's not sufficient.
