### ISSUE TITLE
[v5] Dry run never triggers

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#1322]
## Issue

Using any of the v5 beta's, dry run never triggers

## Steps to Reproduce

An open-source project where I noticed the issue when executing this migration
https://github.com/DataBrokerDAO/dtx-crowdsale-contracts/blob/master/migrations/42_locked_tokens.js by running `ETHEREUM_DEPLOYER_SEED="my seed goes here" truffle migrate --network mainnet`. 

It might have something to do with my truffle config: 
https://github.com/DataBrokerDAO/dtx-crowdsale-contracts/blob/master/truffle.js

It also might be due to the fact that I do not deploy any contracts in this migration.

## Expected Behavior

I expect the dry run to happen on the mainnet

## Actual Results

It just deployed to the mainnet. Which is perfectly good behavior but it is missing the dry runs.

## Environment

* Operating System: OSX
* Ethereum client: Infura
* Truffle version (`truffle version`): v5 beta 1
* node version (`node --version`): v10.11.0
* npm version (`npm --version`): 6.4.1

-> @gnidan issue mentioned on TruffleCon

**Comment by CruzMolina** [comment]
For reference, the spec'd behavior for V5 should be:

if you specify `--dry-run`, it should run only the dry run and then quit ( Currently on v5 beta1: ✅ )
if you specify `--interactive`, it should run the dry run, then prompt to continue with the real migration ( v5 beta1: ❌ )
if you specify neither, the default behavior is to dry-run first, then do the real migration if there are no errors. ( v5 beta1: ❌ )

**Comment by eggplantzzz** [comment]
Is this still an issue?  For me, deploying to Rinkeby does successfully run the dry run.  Do you have the same behavior while deploying to other networks?

**Comment by CruzMolina** [comment]
Looks like the fix is `npm install --save truffle-hdwallet-provider@web3-one`.

After installing @web3-one, all three behaviors detailed above work as described. 👍

**Comment by roderik** [comment]
Are you testing this with a migration file that does not deploy any contracts? For me, this is still not working as it is supposed to.

**Comment by eggplantzzz** [comment]
I am testing it with a toy app that I made and according to the logging it is deploying contracts.  I'll take a look at the code you referenced above to see if anything jumps out at me.

**Comment by CruzMolina** [comment]
Ah, this should re-investigated for v5.

**Comment by eggplantzzz** [comment]
Closing this as I cannot verify that this is an issue. If this is still a problem please let us know. Thanks!

**Comment by gnidan** [comment]
This looks like it should be closed!
