### ISSUE TITLE
truffle unbox webpack

### ISSUE THREAD

**Issue by yvital** [trufflesuite/truffle#1324]
## Issue
Hello,
When trying to install  truffle webpack error is displayed:

PS E:\tmp> truffle unbox webpack
Downloading...
Unpacking...
Setting up...
Error: Command failed: npm install
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'E:\tmp\node_modules\fsevents\node_modules'
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! truffle-init-webpack@0.0.2 prepare: `truffle compile && npm test && npm run lint && webpack-cli --config ./webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the truffle-init-webpack@0.0.2 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\comp1\AppData\Roaming\npm-cache\_logs\2018-10-09T11_29_25_197Z-debug.log

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)

## Environment

* Operating System:  Windows 10
* Truffle version (`truffle version`):
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
* node version (`node --version`):
v8.12.0
* npm version (`npm --version`): 
6.4.1

**Comment by yvital** [comment]
Thanks to all!
I reinstalled Visual Studio Build Tools and it all worked.

**Comment by mszykora** [comment]
I have the same problem under macOS.

* macOS: 10.14
* `truffle version`
    * Truffle v4.1.14 (core: 4.1.14)
    * Solidity v0.4.24 (solc-js)
* `npm --version`
    * 6.4.1

Could not fix the problem yet

**Comment by patt0** [comment]
@mszykora have you managed to fix the problem yet?
