### ISSUE TITLE
Remove Session's dependence on individual transaction

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1326]
This came up in conversation with @elenadimitrova (I believe she came up with the idea)

## Overview

Starting the debugger should not tightly couple it with a particular transaction. It should be possible to debug more than one transaction, or debug the same transaction multiple times, without restarting completely.

## Rationale

The debugger does a lot of preprocessing that doesn't relate to a specific transaction, and that adds substantial overhead. This is bad in Colony's case, where they have a significant number of contracts. The debugger was observed to take minutes to load for them.

**Comment by eggplantzzz** [comment]
Not stale
