### ISSUE TITLE
deployer.deploy() does not throw when a create fails

### ISSUE THREAD

**Issue by pieterhartel** [trufflesuite/truffle#1329]
## Issue

How do I catch a failed require in the Truffle migration script?

## Steps to Reproduce

`$ truffle init`

```
$ cat <<end >contracts/Test.sol
pragma solidity ^0.4.25;
contract Test {
        constructor( uint a ) {
                require( a == 2, "illegal value for a" ) ;
        }
}
end
$ cat <<end >test/test.js
const Test = artifacts.require( "./Test.sol" );
contract( "Test", function( accounts ) {
        it( "Deploy", async function( ) {
                try{
                        await Test.deployed( ) ;
                        console.log( "deployment succeeded" )
                } catch( error ) {
                        console.log( "deployment failed %s", error.message )
                }
        } );
} )
end
$ cat <<end >migrations/2_deploy_contracts.js
var Test = artifacts.require("./Test.sol");
module.exports = async function(deployer) {
        try {
                await deployer.deploy( Test, 1 ) ;
                console.log( "migration succeed" ) ;
        } catch( error ) {
                console.log( "migration failed %s", error.message ) ;
        }
};
end
```
```
$ truffle test
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Test.sol...
Compilation warnings encountered:
/Users/pieter/Documents/pieter/Ethereum/Truffle/Test/contracts/Test.sol:3:2: Warning: No visibility specified. Defaulting to "public". 
	constructor( uint a ) {
 ^ (Relevant source part starts here and spans across multiple lines).
migration succeed
Error: while migrating Test: Returned error: VM Exception while processing transaction: revert illegal value for a -- Reason given: illegal value for a.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:361:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
 

## Expected Behavior

I would have expected the catch block in the migration script to be able to deal with the failed require.

## Actual Results

I get a VM exception that I do not know how to catch.

## Environment

* Operating System: MacOS Mojave 10.14
* Ethereum client: built into truffle
* Truffle version (`truffle version`): Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1)
Solidity v0.4.25 (solc-js)
* node version (`node --version`): v10.11.0
* npm version (`npm --version`): 6.4.1

**Comment by pieterhartel** [comment]
There is a workaround for this issue that is actually really simple. It consists of dispensing with the second migration script. Instead the contract is deployed in the test script. Then exceptions can be caught, await works etc.

For details and an example see: [https://github.com/trufflesuite/ganache-core/issues/388#issuecomment-480951656](url)

**Comment by gnidan** [comment]
Does anyone know if this is still an issue? Looks like something we might be able to sort out pretty easily, but would be nice to have confirmation.

Thanks!

**Comment by gnidan** [comment]
Closing this for issue maintenance, then. Happy to revisit this if it bothers someone in the future. Let us know!
