### ISSUE TITLE
Run separate CI task for all tests with external (`apt-get`) dependencies

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1336]
## Issue

Travis is slow and getting slower now that both `solc` and `vyper` have to get installed.

## Steps to Reproduce

1. https://travis-ci.org/trufflesuite/truffle
2. Options -> Trigger Build -> etc.
3. Wait longer than an amount of time for which it is reasonable to have patience

## Expected Behavior

The two main CI jobs (Packages & Integrations) should not run any tests that rely on any packages installed by `apt-get`.

A separate job should run for specifically these tests. (unknown requirement: should this job be marked as "allowed failure"?)

## Background

There are at least two places where CI environment changes how or which tests are run:

- The [external compile tests](https://github.com/trufflesuite/truffle/blob/46fc7bdb9fde7cc3fa99b94fef04b1d6c04c38f7/packages/truffle/test/scenarios/external_compilers/truffle-compile.js#L15) use the `jq` utility, so these only run if the `CI` environment variable is true.

- A bunch of tests are marked `[ @geth ]` ([e.g.](https://github.com/trufflesuite/truffle/blob/46fc7bdb9fde7cc3fa99b94fef04b1d6c04c38f7/packages/truffle/test/scenarios/migrations/production.js#L24-L25)), which gets indicated to mocha by way of the "test filter" option.*

*This approach is annoying because it means the main CI script for running "all the tests" consumes this CLI flag (`-k` I think but I'm too lazy to look it up). So you can't use `-k` locally, effectively at all, if you just want to do `yarn test -k ...some filter...` in the root.

For this issue, it may be worth thinking of a more explicit strategy for how CI manages collections of tests. Or not. Alternate strategy: hack it in and get tests faster by any means necessary.

## Environment

Travis-CI

**Comment by eggplantzzz** [comment]
**Random Note**: having the keyword 'native' in the string that heads a `describe` or `it` block (in the tests) causes that chunk of tests to be excluded while running the tests in `truffle-compile` due to the testing script found in that package.

**Comment by Mordax** [comment]
Regarding the tests on Vyper failing issue, maybe Vyper can be checked separately to Solidity? Like having two test bundles that depend on a flag to run one at a time when needed, so that any Vyper issues are separated and easier to tackle and build more test support?
