### ISSUE TITLE
Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by zak100** [trufflesuite/truffle#1339]
- [ ] I've asked for help  "https://ethereum.stackexchange.com/questions/60549/error-vm-exception-while-processing-transaction-revert-in-the-context-of-a-te" 

and also at:
https://forum.ethereum.org/discussion/19027/error-vm-exception-while-processing-transaction-revert-in-the-context-of-testing/p1?new=1
---------------------------

## Issue

I am trying to run a test tutorial provided at:
https://medium.com/@kscarbrough1/writing-solidity-unit-tests-for-testing-assert-require-and-revert-conditions-using-truffle-2e182d91a40f

Tutorial is written using some old version. I am using truffle@4.1.14
## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
My smart contract (MyContract5.sol) is:

pragma solidity ^0.4.22;

contract MyContract5{
   uint public mynumber;
   constructor ( ) public {
      mynumber = 24;
   }
   function storeNum(uint mynum) public returns (bool success) {
      require(mynum >10);
      mynumber = mynum; //changing the internal state. If we are not changing state then function should be declared as pure
      return true;
   }
}

and my test contract (TestMyContract5.sol) is:
pragma solidity ^0.4.22;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Mycontract5.sol";

contract TestMyContract5{
   function  testTheThrow() public {
      MyContract5  mycontract = new MyContract5();
      ThrowProxy  throwproxy = new ThrowProxy(address(mycontract));
      MyContract5(address(throwproxy)).storeNum(7);
      bool r = throwproxy.execute.gas(200000)();
      Assert.isFalse(r, "Should be false ecause is should throw!");
   }

   function testNoThrow() public {
      MyContract5 mycontract = new MyContract5();
      ThrowProxy  throwproxy = new ThrowProxy(address(mycontract));
      MyContract5(address(throwproxy)).storeNum(22);
      bool r = throwproxy.execute.gas(200000)();
      Assert.isFalse(r, "Should be false ecause is should throw!");
   }
}

contract ThrowProxy{
   address public target;
   bytes data;
   constructor (address  _target) public {
      target = _target;
   }
   function( ) public {
      data = msg.data;
   }
   function execute( ) public  returns (bool) {
      return target.call(data);
   }
}

and deployment file is:
var MyContract5 = artifacts.require("MyContract5");
module.exports = function(deployer) {
   deployer.deploy(MyContract5);
};

and the Migration.sol is:
pragma solidity ^0.4.23;

contract Migrations {
  address public owner;
  uint public last_completed_migration;

  constructor() public {
    owner = msg.sender;
  }

  modifier restricted() {
    if (msg.sender == owner) _;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
When I type test at the truffle console , I get following errors:
truffle(development)> test
Using network 'development'.

Compiling .\contracts\Mycontract5.sol...
Compiling .\test\TestMyContract5.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

  TestMyContract5
    1) testTheThrow
    > No events were emitted
    2) testNoThrow
    > No events were emitted

  0 passing (2s)
  2 failing

  1) TestMyContract5
       testTheThrow:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
      at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
      at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
      at IncomingMessage.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
      at IncomingMessage.EventEmitter.emit (domain.js:460:23)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  2) TestMyContract5
       testNoThrow:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
      at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
      at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
      at IncomingMessage.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
      at IncomingMessage.EventEmitter.emit (domain.js:460:23)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

## Expected Behavior

What you expected to happen.
No exception should occur, Test should run

## Environment

* Operating System: Windows 10 Home
* Ethereum client: Ganache 1.2.2
* Truffle version (`truffle@4.1.14`):
* node version (`node-v8.12.0-win-x64`):
* npm version (`npm --version`):

**Comment by fainashalts** [comment]
Hi @zak100 are you still having trouble with this error? This error may bubble up when something is wrong with the way conditions in a require statement are being met. For more info see this similar resolved issue: https://github.com/trufflesuite/truffle/issues/884

**Comment by zak100** [comment]
Thanks. I made some changes in the code and now its giving another unsolved exception. I ran the contracts on Remix. It did not give me any such error and generated warning messages. However it did not deploy the contract.
I would add my problem to git hub.
Thanks for your response.
Zulfi.
    On Friday, November 2, 2018, 3:32:50 PM CDT, Faina Shalts <notifications@github.com> wrote:  
 
 
Hi @zak100 are you still having trouble with this error? This error may bubble up when something is wrong with the way conditions in a require statement are being met. For more info see this similar resolved issue: #884

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by zak100** [comment]
Hi @fainashalts,
I think I am getting error at this line:
MyContract5(address(throwproxy)).storeNum(22);

In the MyContract5 constructor is empty and in the above statement I am passing a value to it as done in the tutorial. The statement before its is:
 
ThrowProxy throwproxy = new ThrowProxy(address(mycontract));
This is storing the address of MyContract5 in 'throwproxy'. So we have to call storeNum(22) using throwproxy and I can't do that.


However, if change Assert(...) to require(...) in TestMyContract5 i.e

pragma solidity ^0.4.22;
import "truffle/DeployedAddresses.sol";
import "../contracts/Mycontract5.sol";

contract TestMyContract5{
   function  testTheThrow() public {
      MyContract5  mycontract = new MyContract5();
      ThrowProxy  throwproxy = new ThrowProxy(address(mycontract));
      MyContract5(address(throwproxy)).storeNum(7);
      bool r = throwproxy.execute.gas(200)();
      require(r);
   }

   function testNoThrow() public {
      MyContract5 mycontract = new MyContract5();
      ThrowProxy  throwproxy = new ThrowProxy(address(mycontract));
      MyContract5(address(throwproxy)).storeNum(22);
      bool r = throwproxy.execute.gas(200)();
      require(r);
   }
}

contract ThrowProxy{
   address public target;
   bytes data;
   constructor (address  _target) public {
      target = _target;
   }
   function( ) public {
      data = msg.data;
   }
   function execute( ) public  returns (bool) {
      return target.call(data);
   }
}




 then "VM Exception....." error vanishes but i get another unsolved exception which is : Callback was already called.

The steps are:

When I am executing:
>truffle test

I am getting following exception:

D:\SolidityContractsSelf\MyContract5\contracts>truffle test
Using network 'development'.

Compiling .\contracts\Mycontract5.sol...
Compiling .\test\TestMyContract5.sol...
Compiling truffle/DeployedAddresses.sol...


  TestMyContract5
Error: Callback was already called.
    at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\async\dist\async.js:966:1
    at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\async\dist\async.js:3885:1

Note: "Callback was already called." is a javascript error. So the whole thing is the outcome of mishandled exceptions in javascript and this is because Truffle was developed using javascript.

Zulfi.
