### ISSUE TITLE
No error on bad RPC endpoint

### ISSUE THREAD

**Issue by okwme** [trufflesuite/truffle#1343]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If your truffle config contains an error in the RPC endpoint, the migrate command fails silently.

## Steps to Reproduce
this was my config, using env variables for the sensitive stuff. I had prefixed my infura key with `v3/` so the final URL ended up being `https://mainnet.infura.io/v3/v3/...`. This caused my deployed to fail but gave no error or information about why. If the endpoint fails there should be some kind of error bubbling up. 

```
    mainnet: {
      provider() {
        return new HDWalletProvider(
          process.env.ENS_MAINNET,
          'https://mainnet.infura.io/v3/' + process.env.INFURA_API_KEY
        )
      },
      network_id: 1,
      gasPrice: 1000000000 * 6
    },
```
This could also be an error with HDWalletProvider. I'm using the new truffle and the new HDWalltProvider. Versions are below.

## Expected Behavior

Expect to see an error when the URL fails

## Actual Results

No Error message. Just a silent fail.

## Environment

*  truffle-hdwallet-provider: "^1.0.0-web3one.0",
* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.0.0-beta.1 (core: 5.0.0-beta.1),  0.4.25 (solc-js)
* node version (`node --version`): v8.10.0
* npm version (`npm --version`):  5.6.0

**Comment by Meabo** [comment]
I reproduced the error, and found that no promise are returned at this line: https://github.com/trufflesuite/truffle/blob/next/packages/truffle-core/lib/commands/migrate.js#L170

As it's my first time diving into the code, it will take me more time to fix the issue but I will 👍
