### ISSUE TITLE
[BETA] Truffle Install fails

### ISSUE THREAD

**Issue by thekevinbrown** [trufflesuite/truffle#1354]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to run `truffle install zeppelin` errors

## Steps to Reproduce

```
$ npm install -g truffle@beta
$ truffle init
$ truffle install zeppelin
TypeError: Cannot read property 'getLockfileURI' of undefined
    at [my node install]/lib/node_modules/truffle/build/webpack:/~/ethpm/lib/installer.js:64:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Expected Behavior

Zeppelin library should be installed.

## Actual Results

```
TypeError: Cannot read property 'getLockfileURI' of undefined
    at [my node install]/lib/node_modules/truffle/build/webpack:/~/ethpm/lib/installer.js:64:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Environment

* Operating System: OS X 10.14 (18A391)
* Ethereum client: `ganache-cli`
* Truffle version (`truffle version`): Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1)
* Solidity version: Solidity v0.4.25 (solc-js)
* node version (`node --version`): v10.10.0
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
This feature is kind of incomplete at the moment...we are currently working to revamp EthPM and hope that within the next couple of months we'll be able to have something useful in place!

**Comment by eggplantzzz** [comment]
Thanks for the PR!  I talked with some other members of the team and we're planning to try and look into fixing this.  It might only be working for specific packages as some of them mentioned that there might be some people successfully using this feature.  It might work for just a selection of packages...it might be more correct to say that we are not totally sure what its current state is.  However I think we are going to try and fix this feature.

**Comment by thekevinbrown** [comment]
That sounds great, is there anything I can do to help here? Does it still work in v4? I might be able to find some time before devcon to chip in.

**Comment by eggplantzzz** [comment]
Hmm, I think you might take it up with @gnidan...I'm not sure we've fully taken stock of what it will take to fix.
