### ISSUE TITLE
Forcing a transaction to be signed and broadcast to call a view method with truffle-contract

### ISSUE THREAD

**Issue by interfect** [trufflesuite/truffle#1355]
## Issue

I am writing an on-chain API that will be invoked from other smart contract clients, and I am converned about gas usage.

I need to force `truffle-contract` to send a transaction invoking a `view` method on-chain, during my Truffle tests, so I can see how much gas it uses with [eth-gas-reporter](https://github.com/cgewecke/eth-gas-reporter), which apparently only reports gas usage for methods that are actually invoked on-chain during tests.

The [manual for truffle-contract](https://github.com/trufflesuite/truffle/tree/next/packages/truffle-contract#calling-getters) notes that `truffle-contract` is clever, and refuses to issue a transaction when you run a `view` method, even if you do it without the `.call()` syntax.

I could write something myself with `.estimateGas()`, or try and modify `eth-gas-reporter` to report on un-called `view` methods, but that only solves my particular use case. There are other times you might want to invoke a `view` method on-chain (such as as a way of adding data to the chain).

How do I get around this cleverness and force actual mineable transactions to be generated?

## Steps to Reproduce

1. Write a contract with a `view` method.
2. Try to find a way to sign and broadcast a transaction running that method with `truffle-contract` in the documentation.

## Expected Behavior

There should be a documented way to force the transaction to be issued.

## Actual Results

There's nothing in the documentation saying that this can be done or how it can be done.

## Environment

N/A

**Comment by interfect** [comment]
I do not believe that this issue has yet been addressed.

**Comment by eggplantzzz** [comment]
You can actually force a transaction by using the following syntax:
```
myContract.viewFunction.sendTransaction(...)
```

Let us know if you have any further issues!

**Comment by eggplantzzz** [comment]
Closing this now as the docs have this information. See [this section of the docs](https://www.trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts#special-methods-on-truffle-contract-objects).
