### ISSUE TITLE
Ethereum Overview Webpage not showing properly

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [trufflesuite/truffle#1359]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Markdown in the Ethereum Overview page, on the website, is not showing up properly.

## Steps to Reproduce

Go to https://truffleframework.com/tutorials/ethereum-overview and check the text after the first image.

## Expected Behavior

I expected for the titles to show properly.

## Actual Results

The titles appear in Markdown, like this:
"### The need to share data Sharing large amounts of data can be expensive and cumbersome. We can ease this burden by distributing data across multiple parties. Reading and writing are controlled by one or more parties within the group and therefore subject to similar corruptions as centralized databases. "

## Environment

I'm using Google Chrome.

**Comment by eggplantzzz** [comment]
Thanks for the heads up!  We'll try and get this sorted out.
