### ISSUE TITLE
[v5] Allow configuration of allowed_extenstions for the migrations

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#1361]
I'm using https://github.com/ethereum-ts/truffle-typechain-example to get everything into typescript but `truffle migrate` cannot find any migrations ending in .ts due to thus config option: https://github.com/trufflesuite/truffle/blob/46fc7bdb9fde7cc3fa99b94fef04b1d6c04c38f7/packages/truffle-migrate/index.js#L30

There is however no option to configure this in the truffle.js file.

Crosslink: https://github.com/ethereum-ts/truffle-typechain-example/issues/2

**Comment by CruzMolina** [comment]
@roderik would love to support this. Please feel free to submit a PR!

**Comment by sneko** [comment]
Thanks @roderik for making Truffle Typescript-compatible , I hope it will be included in beta.2 👍

**Comment by CruzMolina** [comment]
Yes thank you @roderik for getting the ball rolling. Right now we have our hands full prepping for Devcon, but shooting to have some of this included in beta.2 👍
