### ISSUE TITLE
`truffle init` breaks if NODE_ENV is set.

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#137]
Errors with:

> Couldn't find any suitable environment. Check environment configuration.

even though there's no configuration to check since you're init'ing a project.

**Comment by huuep** [comment]
quick fix is to 'unset NODE_ENV' before running 'truffle init'

**Comment by tcoulter** [comment]
No longer an issue as NODE_ENV isn't respected. Closing.
