### ISSUE TITLE
How to use truffle-hdwallet-provider with ethereumjs-tx?

### ISSUE THREAD

**Issue by shumail92** [trufflesuite/truffle#1381]
I am wondering how can I use it to sign transactions with ethereumjs-tx?
The sign() method of ethereumjs-tx accepts private key Buffer as mentioned in docs:
https://github.com/ethereumjs/ethereumjs-tx/blob/master/docs/index.md#sign

**How can I use truffle-hdwallet-provider to sign the transaction?**

_This is the duplicate_ of https://github.com/trufflesuite/truffle-hdwallet-provider/issues/73 and moved here because that repo is going to be archived.

**Comment by jleeh** [comment]
I use the `truffle-hdwallet-provider-privkey`, along with `nonce-tracker` to avoid issues with load-balanced clients. See my snippet of my `truffle.js`:
```js
const Web3Utils = require('web3-utils');
const HDWalletProvider = require("truffle-hdwallet-provider-privkey");
const NonceTrackerSubprovider = require("web3-provider-engine/subproviders/nonce-tracker");

module.exports = {
  web3Utils: Web3Utils,
  networks: {
    ropsten: {
      provider: () => {
        let wallet = new HDWalletProvider(
          "<pk>", 
          "<client url>"
        );
        let nonceTracker = new NonceTrackerSubprovider();
        wallet.engine._providers.unshift(nonceTracker);
        nonceTracker.setEngine(wallet.engine);
        return wallet;
      },
      network_id: 3,
      gas: 4700000,
      gasPrice: 30000000000,
    }
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  }
};
```

**Comment by fainashalts** [comment]
Hi @shumail92, it looks like @jleeh has addressed your question (thanks!). I'm going to close this issue, but please feel free to open another if something else comes up!
