### ISSUE TITLE
How to install truffle solidity 0.4.2?

### ISSUE THREAD

**Issue by kennblvnp** [trufflesuite/truffle#1383]
> npm install truffle --dev solc@0.4.2

is this correct?

**Comment by gnidan** [comment]
I don't think Truffle supports Solidity v0.4.2 anymore, but you can try using the [BYOC feature](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#bring-your-own-compiler)

Closing this (since it's not an issue, just a question). Thanks!
