### ISSUE TITLE
Thanks! I think it was just due to truffle not being unboxed into an empty directory, something which the tutorials I was following didn't mention as they maybe thought it was obvious.

### ISSUE THREAD

**Issue by salmanahmad3333** [trufflesuite/truffle#1394]
_Originally posted by @ArranMcC in https://github.com/trufflesuite/truffle/issues/943#issuecomment-391326824_

Please tell me how you resolved this issue. I still can't be able to figure it out.

**Comment by benjamincburns** [comment]
Please wait for response in thread rather than opening duplicate issues.

**Comment by breakpointer** [comment]
This same thing happened to me. It was not obvious/stated that I should unbox in an empty directory (actually, I assumed unboxing would create it's own directory). As a result, all the `boxed` contents were dumped into my based directory and required manual cleanup. 🤦‍♂️

**Comment by CruzMolina** [comment]
Sorry to hear that @breakpointer , can you share the tutorial or documentation you were looking at?

Btw, as of truffle 5.0.12, there should be a prompt when attempting an unbox into a non-empty directory.
