### ISSUE TITLE
Make sample coin compatible with EIP20

### ISSUE THREAD

**Issue by flyswatter** [trufflesuite/truffle#140]
[EIP-20](https://github.com/ethereum/eips/issues/20) is a standard format for issued tokens, so that user interfaces can provide extra ways for users to exchange them.

The Mist wallet already supports them, so you can paste in your token address and see your token balance in your Mist wallet.

Long term we'd like to at MetaMask as well.

It would be a great dev experience if they had the ability to issue standard tokens as their first hello, world project.

This would be a good first-time contributor contribution, since it's basically just about making a basic truffle application that can be generated with `truffle init`.

**Comment by tcoulter** [comment]
We're moving away from MetaCoin fairly soon. Closing for housekeeping.
