### ISSUE TITLE
Truffle v5.0.0-beta.0 Release Page Documentation Error

### ISSUE THREAD

**Issue by jerryji** [trufflesuite/truffle#1421]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
At the Truffle v5.0.0-beta.0 release page ( https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0 ), the solc optimizer example incorrectly puts the config under "settings", while they should have been child of "solc" --

```
// Optimization and EVM version settings
compilers: {
  solc: {
    settings: {
      optimizer: {
        enabled: true, // Default: false
        runs: 1000     // Default: 200
      },
      evmVersion: "homestead"  // Default: "byzantium"
    }
  }
}
```

## Steps to Reproduce

checkout @seesemichaelj 's comment at --

https://github.com/trufflesuite/ganache/issues/960#issuecomment-437768131

## Expected Behavior

solc optimizer enabled

## Actual Results

solc optimizer not enabled

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client: Ganache 1.2.2
* Truffle version (`truffle version`): Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1)
* node version (`node --version`): v8.12.0
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
@jerryji Thanks for the heads up about this!  We have updated the release notes.  I'm going to close this issue.
