### ISSUE TITLE
truffle migrate hangs with HDWalletProvider on ewasm testnet

### ISSUE THREAD

**Issue by lrettig** [trufflesuite/truffle#1429]
## Issue

When I attempt to migrate (deploy) a contract to the ewasm staging testnet using HDWalletProvider, truffle hangs and doesn't get past the first RPC call, `eth_getBlockByNumber`. (Without HDWalletProvider it works fine.)

## Steps to Reproduce

`truffle.js`:

```javascript
var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "...";
module.exports = {
  networks: {
    staging: {
      network_id: "*",
      provider: () => new HDWalletProvider(mnemonic, "http://40.114.204.83:8545"),
    },
  }
};
```

Changing the network ID, etc. didn't help.

## Expected Behavior

I expect to be able to deploy a contract.

## Actual Results

```
truffle-demo-metacoin> truffle migrate --network staging --verbose-rpc
   > {
   >   "jsonrpc": "2.0",
   >   "id": 3,
   >   "method": "eth_getBlockByNumber",
   >   "params": [
   >     "latest",
   >     false
   >   ]
   > }
```

Note: a `curl` against the same RPC endpoint works fine:

```
> curl -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":3}' http://40.114.204.83:8545
{"jsonrpc":"2.0","id":3,"result":{"difficulty":"0x149db5","extraData":"0xd883010811846765746888676f312e31302e33856c696e7578","gasLimit":"0x7a1200","gasUsed":"0x0","hash":"0x3fbc8acc7f01d0e0f9a4dcda77d9aaf480550491d208eb932b2a94936bf26dcd",...}
```

## Environment

* Operating System: OS X 10.14
* Ethereum client: geth
* Truffle version (`truffle version`): `Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1) Solidity v0.4.25 (solc-js)`
* truffle-hdwallet-provider version: `0.0.6`
* node version (`node --version`): `v11.0.0`
* npm version (`npm --version`): `6.4.1`

**Comment by gnidan** [comment]
@lrettig You need to grab `truffle-hdwallet-provider@web3-one`; that's probably your problem.

**Comment by lrettig** [comment]
Thanks, that worked. What on earth is `web3-one`?
