### ISSUE TITLE
Truffle v5 Solc configuration default

### ISSUE THREAD

**Issue by tobyjaguar** [trufflesuite/truffle#1441]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I am filing this issue for the default configuration of solc in the v5 documentation and truffle.js as a request from gitter.

I was attempting to change the compiler for truffle v5 and the documentation wasn't quite clear.

truffle.js in the drizzle box defines the compiler specification as:
```
solc: {
  optimizer: {
    enabled: true,
    runs: 200
  }
}
```
and the release notes define it as:
https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#specify-a-solcjs-version
```
module.exports = {
  networks: {
    ... etc ...
  },
  compilers: {
     solc: {
       version: <string>  // ex:  "0.4.20". (Default: Truffle's installed solc)
     }
  }
};

and

// Native binary
compilers: {
  solc: {
    version: "native"
  }
}

// Docker
compilers: {
  solc: {
    version: "0.4.22",   // Any published image name
    docker: true
  }
}

// Relative or absolute path to an npm installed solc-js
compilers: {
  solc: {
    version: "/Users/axic/.nvm/versions/node/v8.9.4/lib/node_modules/solc"
  }
}

// Optimization and EVM version settings
compilers: {
  solc: {
    settings: {
      optimizer: {
        enabled: true, // Default: false
        runs: 1000     // Default: 200
      },
      evmVersion: "homestead"  // Default: "byzantium"
    }
  }
}
```
it would be nice to include how to format a compiler version with the default included in the 
truffle.js file from the drizzle box, as this was what I got hung up on. I did something like this:
```
compilers: {
  solc: {
    version: "0.4.24",
    settings: {
      optimizer: {
        enabled: true, // Default: false
        runs: 1000     // Default: 200
      }
    }
  } 
```

## Steps to Reproduce

This is default behavior from unboxing the drizzle-box.

## Expected Behavior

What you expected to happen. -> I was working with files that required a compiler version different from v0.4.25 that comes with Truffle v5. I could not find an example of how to specify the compiler version. I asked in gitter and eventually stumbled upon the release notes, but those don't quite explain how to implement the compiler version with the default configuration from truffle.js

## Actual Results

N/A

## Environment

* Operating System: Vagrant Ubuntu-trusty-64
* Ethereum client:
* Truffle version (`truffle version`): Truffle v5.0.0-next.16 (core: 5.0.0-beta.1)
* node version (`node --version`): Solidity v.0.4.25 (solc-js)
* npm version (`npm --version`):  Node v11.2.0

**Comment by eggplantzzz** [comment]
@tobyjaguar Thanks for the feedback!  We should have some new documentation that will make this much clearer with the release of v5.  We'll also consider adding defaults in the config.
