### ISSUE TITLE
Truffle migrations fails against `parity` and `geth` for large contracts

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/truffle#1448]
- [v] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle migrations fails against `parity` and `geth` with `TypeError: Cannot read property 'transactionHash' of undefined`

## Steps to Reproduce

It is quite possible this is a race condition as it happens on migrating larger contracts. Overall try `truffle migrate` of a large contract against either `parity` or `geth`.

## Expected Behavior

Migrations to complete successfully

## Actual Results

```
> transaction hash:    0x2e5dacf2b0b2150d75202e9749599978f400d0085d59128f067126cb619eeac1
   ⠼ Blocks: 0            Seconds: 0TypeError: Cannot read property 'transactionHash' of undefined
    at Reporter.postDeploy (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/packages/truffle-reporters/reporters/migrations-V5/reporter.js:303:1)
```
The transaction hash 👆 `0x2e5dacf2b0b2150d75202e9749599978f400d0085d59128f067126cb619eeac1` is mined and has deployed the contract successfully so the problem doesn't seem to be in the deploy transaction or the client.

## Environment

* Operating System: OSX
* Ethereum client: Parity/v1.11.8-stable and Geth 1.8.14-stable
* Truffle version (`truffle version`): 5.0.0-next.16
* node version (`node --version`): 9.11.2
* npm version (`npm --version`): 5.6.0

**Comment by elenadimitrova** [comment]
@area investigated this too and [this](https://github.com/trufflesuite/truffle/blob/40c66daea581e16d825283d7a39ed24a8b4b6ec3/packages/truffle-deployer/src/deployment.js#L335-L337) seemed suspicious as we were not convinced that `await`ing there ensures the events have fired

**Comment by gnidan** [comment]
Hi @elenadimitrova can you let me know if beta.2 fixes this for you?

**Comment by elenadimitrova** [comment]
It does! Thanks @gnidan
