### ISSUE TITLE
Run plugins registering as promises

### ISSUE THREAD

**Issue by rocky** [trufflesuite/truffle#1475]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle)

For a MythOS analysis plugin, when run from a develop console I would like this to be asynchronous, is there a way to register a plugin that when run from develop works expects a promise back?

**Comment by rocky** [comment]
_Note: This is related and would be fixed by the proposal in #1482._

**Comment by gnidan** [comment]
Closing as duplicate. Thanks!
