### ISSUE TITLE
TypeError: address.replace is not a function

### ISSUE THREAD

**Issue by amankakar** [trufflesuite/truffle#1485]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
 TypeError: address.replace is not a function

## Steps to Reproduce

```javascript
    const Contract = truffleContract(ReceptionsitFactory);
    Contract.setProvider(web3.currentProvider);
    const instanceFactory = await Contract.at(addressOfFactory);

//this line of code create new instance Receptionist Contract
    await newReceptionist.createReceptionist(
      this.state.hospitalName,
      this.state.receptionistName,
      {
        from: this.state.accounts
      }
    );
```
## Expected Behavior

after this Recetionist contract would be created with provided value in createReceptionist functon 

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment
![image](https://user-images.githubusercontent.com/38261321/49339144-44af7980-f64f-11e8-97e3-8de02cf2a602.png)

* Operating System: ubuntu 18.04.1
* Ethereum client: truffle devlop
* Truffle version : v4.1.14
* node version : v8.10.0
* npm version : 3.5.2

**Comment by eggplantzzz** [comment]
@amankakar Is your code available somewhere where I can take a look?

**Comment by amankakar** [comment]
thank you for your reply ... i have solved error.
below line of code caused error
        `from: this.state.accounts.`
because it try to replace account.
i changed it to `accounts[0]`. which solve error
thank you @eggplantzzz
