### ISSUE TITLE
Contract has not been deployed to detected network (at browser)  But working fine in test file

### ISSUE THREAD

**Issue by amankakar** [trufflesuite/truffle#1501]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

deploy contract in magiration file with out any error but in browser truffleContract gives  error
Contract has not been deployed to detected network (network/artifact mismatch)

 
## Steps to Reproduce
3_deploye.js
`var PatientFactory = artifacts.require("PatientFactory");
var PatientContract = artifacts.require("Patient");
module.exports = async (deployer, accounts) => {
  await deployer.deploy(PatientFactory)

  var patientFactory = await PatientFactory.deployed();

  var rec = await deployer.deploy(
    patientFactory("P0001", "XYZ", "Male", 25, accounts)
  );
  var patient = await PatientContract.deployed();
};

in browser file where i have created front end to interact : 
`import Receptionist from "../../build/contracts/Receptionsit.json";
import PatientFactory from "../../build/contracts/PatientFactory.json"
import web3 from "./web3";

//Patient factory
    const PatientFactory = truffleContract(PatientFactory);
    console.log(PatientFactory);
    PatientFactory.setProvider(web3.currentProvider);
    const patientFactoryInstance = await PatientFactory.deployed();
  `
## Expected Behavior

detect deployed PatientFactory contract in browser.

## Actual Results
gives following error

![image](https://user-images.githubusercontent.com/38261321/49666036-97869800-fa78-11e8-84d4-76e3a4436aed.png)

## Environment

* Operating System: Linux (ubuntu 18.04)
* Ethereum client: none( truffle develop network)
* Truffle version (`truffle version`):v4.1.14
* node version (`node --version`):v8.10.0
* npm version (`npm --version`): 3.5.2

**Comment by amankakar** [comment]
solved

**Comment by gnidan** [comment]
Glad to hear!

**Comment by Eymos** [comment]
> solved

How did you Solve it?

**Comment by amankakar** [comment]
@Eymos  I have changed rpc of web3 provider.
web3.setProvider("http://localhost:9545")
then the web3 object will know which protocol to use and which hostname to contact to get the block data for the blockchain or where to send transaction calls to.

**Comment by Eymos** [comment]
Thanks for that Amankakar, though it is not running, can you please help me solve this error. check out my the git clone here https://github.com/Eymos/iot-device-management.git

**Comment by amankakar** [comment]
Kindly provide some detail about your error. because this error may be
caused due to different reasons.

**Comment by Eymos** [comment]
This has been solved.

**Comment by robinsonstewart** [comment]
if (typeof web3 !== 'undefined') {
    // Use Mist/MetaMask's provider
    web3js = web3.currentProvider;
  } else {
    // Handle the case where the user doesn't have Metamask installed
    // Probably show them a message prompting them to install Metamask
    alert('Install Metamask!')
  }
  web3 = new Web3(web3js);
