### ISSUE TITLE
Sort out web3.js release blocker issues

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#1504]
There are two outstanding issues identified in the latest web3.js that are blocking the Truffle v5 release. We have identified root causes of these and identified solutions for each.

For timeline reasons, and given sufficient confidence in the acceptability of our solutions, we plan to author PRs upstream to get these fixes into web3.js beta.37 and release Truffle v5.0.0 on a fork of web3 in the meantime. 

Creating this issue to serve to track the resolution of all of this. 

Summary of issues:

- #1461 For reasons that are out of scope, Truffle does not support setting `keepAlive: true` for HTTP agents. The proposed web3 change is to allow `keepAlive` as an option in `new Web3.providers.HttpProvider()`.

 PR: ethereum/web3.js#2105

- #1487 Empty event logs are not decoded properly. This appears to be the same issue as ethereum/web3.js#1916. The problem seems to arise from an exception that restricts empty `bytes` values from being decoded for empty `outputs`. The proposed solution is to loosen the validation check to what appears to be more correct.
  
 PR: ethereum/web3.js#2106

Thanks to @eggplantzzz and @CruzMolina, respectively, for getting to the bottom of these.

cc @nivida so you're aware.

**Comment by frozeman** [comment]
Well get them in and make a new release.

**Comment by nivida** [comment]
@gnidan Merged these PRs and should be released today. :-)

**Comment by gnidan** [comment]
Thanks so much @nivida and @frozeman!

**Comment by gnidan** [comment]
This is closable now that there is no outstanding fork. Woot!

**Comment by slraja** [comment]
I am having Truffle v5.0.3  which has  web3.version as '1.0.0-beta.37' but still getting the below error : 

roiDevice:Faucet roi$ **truffle migrate**
Error: **Returned values aren't valid, did it run Out of Gas**?
    at ABICoder.decodeParameters (/Users/roi/.nvm/versions/node/v10.15.1/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)

Can someone please help ??
