### ISSUE TITLE
Issue with import sub/uncle directories

### ISSUE THREAD

**Issue by vmadrienpro** [trufflesuite/truffle#152]
Import seems to work fine as long as the imported file is  in a parent directory on the same branch, or in the same directory:
import "../../file.sol"   _ok _
import "file.sol"     _ok_

However the compilation failed if you try to import files from a sub or an uncle directory:
import "SubDir/file.sol"   _error_
import "../SubDir/file.sol"  _error_

I checked the input that truffle feed to solc and it seems to be ok, but i'm not sure :)

**Comment by DiscRiskandBisque** [comment]
I'm running into the same issue and have also tried the full path:
`import "C:/dapps/zeptest/contracts/zeppelin/Ownable.sol";`

With relative paths, as @vmadrien described, I get the error:
`MetaCoin.sol:4:1: Error: Source "zeppelin/Ownable.sol" not found: File not supplied initially.`

With a full path, I get:
`Cannot find import Ownable.sol from MetaCoin.sol. If it's a relative path, ensure it starts with './' or '../'.`

All Windows 10 machines and I'm using PowerShell as the command line.

**Comment by tcoulter** [comment]
@DiscRiskandBisque What version of Truffle are you using?

**Comment by DiscRiskandBisque** [comment]
2.1.1 on this machine. When I get home I'll check the other two.

**Comment by CruzMolina** [comment]
Closing as I've verified this is no longer an issue on the current stable release (v4.1.14) and the current v5 beta release (beta.1) .
