### ISSUE TITLE
Standardize format for displaying help when `truffle run` is passed a `--help` flag

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#1550]
Directly related to #1472. Would be nice to provide a standardized way for plugin writers to help their users within the CLI when config.help is true (`truffle run someCommand --help` ).

Starting point: https://github.com/trufflesuite/truffle/issues/1473#issuecomment-446467491

(Self-assigning to keep open, but anyone free to work on it!)

**Comment by gnidan** [comment]
I think this is a duplicate of #1473
