### ISSUE TITLE
Truffle 5 includes dependencies with breaking changes tagged as minor upgrades

### ISSUE THREAD

**Issue by facuspagnuolo** [trufflesuite/truffle#1557]
### truffle-debugger
This package was released along with Truffle 5 including a breaking change: it uses `web3@^1.0.0-beta.37` but [it was tagged as a minor update (`4.0.3` ~> `4.1.0`)](https://github.com/trufflesuite/truffle/compare/v4.1.14...v5.0.0#diff-d8e6ac7082f1bf264833376acf1135aeR3)

### truffle-provider
This package is published under a major 0 version, which means that [it could introduce breaking changes](https://semver.org/#spec-item-4). But, there other packages like `truffle-core` using `truffle-provider` [accepting minor updates](https://github.com/trufflesuite/truffle/blob/v4.1.14/packages/truffle-core/package.json#L45), it should be declared with a tilde (`~`) instead of a caret (`^`).

## Steps to Reproduce

1. Create a sample project and init npm: `mkdir sample && cd sample && npm init -y`

2. Declare the following dependencies in your package json:
```json
{
  ...,
  "dependencies": {
    "ganache-cli": "^6.1.8",
    "truffle-config": "^1.0.6",
    "truffle-core": "^4.1.14",
    "web3": "^0.20.6"
  }
}
```

3. Install your dependencies: `npm i`

4. Create a script `index.js` with the following content:
```js
async function test() {
  const TruffleConfig = require('truffle-config')
  const config = TruffleConfig.detect({ logger: console })
  config.network = 'local'

  await new Promise((resolve, reject) => {
    const TruffleEnvironment = require('truffle-core/lib/environment')
    TruffleEnvironment.detect(config, function (error) {
      if (error) reject(error)
      else {
        const Web3 = require('web3')
        global.web3 = new Web3(config.provider)
        resolve()
      }
    })
  })

  web3.eth.accounts.forEach(account => {
    console.log(web3.eth.getBalance(account))
  })
}

test()
  .then(console.log)
  .catch(console.error)
```

5. Start a local ganache client: `npx ganache-cli --port 9545`

6. Run the `index.js` script: `node index.js`

## Expected Behavior

To output the balances of all the accounts: 
```
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
BigNumber { s: 1, e: 20, c: [ 1000000 ] }
```

## Actual Results

``` 
TypeError: this.provider.sendAsync is not a function
    at RequestManager.sendAsync (~/sample/node_modules/truffle-core/node_modules/web3/lib/web3/requestmanager.js:80:19)
    at Object.get [as getNetwork] (~/sample/node_modules/truffle-core/node_modules/web3/lib/web3/property.js:116:33)
    at detectNetworkId (~/sample/node_modules/truffle-core/lib/environment.js:55:20)
    at Object.detect (~/sample/node_modules/truffle-core/lib/environment.js:75:5)
    at Promise (~/sample/index.js:8:24)
    at new Promise (<anonymous>)
    at test (~/sample/index.js:6:9)
    at Object.<anonymous> (~/sample/index.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

## Possible solution
- Publish a new patch for all those truffle packages depending on `truffle-provider` with a caret, e.g. `truffle-core@4.1.14`, using a tilde (`~`) instead
- Deprecate all new minor updates including a breaking change, e.g. `truffle-debugger@4.1.0`, and publish them as new major versions
- Update Truffle 5 related packages to use the corresponding new published versions based on both steps above

**Comment by gnidan** [comment]
(Reopening this to investigate if this is still an issue.)

**Comment by eggplantzzz** [comment]
Closing as there is nothing actionable.
