### ISSUE TITLE
Truffle requires internet to compile

### ISSUE THREAD

**Issue by maxsam4** [trufflesuite/truffle#1567]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Without active internet connection, truffle fails to compile contracts with the following error:
`Error: Failed to complete request to: https://solc-bin.ethereum.org/bin/list.json. Are you connected to the internet?`
This is acceptable when using solcjs and truffle does not have required version cached but I am using native solc so it shouldn't have to contact the internet.

## Steps to Reproduce
Disconnect your internet and use `truffle compile`
OR
Switch your ISP to comcast and try truffle compile.

## Expected Behavior
It should just compile the contracts using native solc without needing to fetch any data from the internet.

## Actual Results
`Error: Failed to complete request to: https://solc-bin.ethereum.org/bin/list.json. Are you connected to the internet?`

## Environment
* Operating System: Ubuntu bionic
* Ethereum client: Ganache
* Truffle v5.0.0 (core: 5.0.0)
* Solidity - native (solc-js)
* Node v8.12.0

ps. Removing the need of contacting the internet should also be a possible optimization. Now that native solc is faster than ferrari, fetching data from interent takes a considerable percent of compile time.

**Comment by elenadimitrova** [comment]
This is affecting us all day today too :(

**Comment by maxsam4** [comment]
> This is affecting us all day today too :(
> Considering we are using a docker image.

Try updating your truffle. I don't know when exactly this was 'fixed' but in `5.0.4` version of truffle, if you download solcjs once, it will keep it cached and use that again next time. Essentially, you need an internet connection only for the first compile.

As it stands, truffle requires solcjs for pre-processing even if you are using native solc or docker images.

**Comment by eggplantzzz** [comment]
One thing to be aware of is that Truffle does need a cached version of solc even if you are using a docker image. This means that you will have to run `truffle compile` at least once while connected to the internet so that it can download and cache it. Afterwards you should be able to compile without a connection with that setup.

**Comment by eggplantzzz** [comment]
Closing this as I do not believe it is an issue on the latest version of Truffle.
