### ISSUE TITLE
Truffle test recompiling contracts

### ISSUE THREAD

**Issue by maxsam4** [trufflesuite/truffle#1568]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Even After running `truffle compile`, `truffle test` still recompiles *some* of the contracts. This *some* can change between different `truffle test` (usually the number increases).

## Steps to Reproduce
1) `truffle compile`
2) `truffle test`

## Expected Behavior
`truffle test` should not recompile contracts

## Actual Results
`truffle test` should recompiles *some* of the contracts

## Environment
* Operating System: Ubuntu bionic
* Ethereum client: Ganache
* Truffle v5.0.0 (core: 5.0.0)
* Solidity - native (solc-js)
* Node v8.12.0

**Comment by maxsam4** [comment]
ps. This might not happen for all truffle projects but certainly does happen on the refactored contracts of polymath-core. The refactoring is still underway and I'll share proper reproduction instructions (if needed) once I have completed the refactoring.

**Comment by CruzMolina** [comment]
Hey @maxsam4 , is this still an issue on `5.0.13`? (btw, `native` solc usage isn't enabled yet for solidity unit tests on `5.0.13` but should be in the next release [#1931]).

Currently on my end, when using solc-js to `truffle compile` and then `truffle test` in `5.0.13`, the only contracts that are compiled/recompiled are the sol unit tests.

**Comment by maxsam4** [comment]
@CruzMolina I don't think this is an Issue anymore. 
At least I couldn't reproduce it today. I think it might be best to close this Issue for now. I'll reopen if I am able to reproduce this in future.
