### ISSUE TITLE
Error while doing `truffle init`

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/truffle#1570]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Getting the following error when doing `truffle init`:

```sh
Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.
```

It was working fine yesterday and the day before that, so could be related to the recent v5 release as that came out around yesterday.

## Steps to Reproduce

```sh
mkdir mytest
cd mytest
truffle init
```

## Expected Behavior

To generate the basic Truffle project folders (`migrations/`, `contracts/`, etc...)

## Actual Results

Got an error.

## Environment

* Operating System: MacOS Mojave 10.14.1
* Ethereum client:
* Truffle version (`truffle version`) : v4.1.14
* node version (`node --version`): v10.9.0
* npm version (`npm --version`): 6.4.1

**Comment by kalymgr** [comment]
I had the same problem which was solved by updating truffle to it's latest version (uninstall and install).

**Comment by obernardovieira** [comment]
yes, that problem is solved if you update. I knew about the release but hadn't updated yet, and when I got the error was easy to find out. So, updated to v5.

**Comment by eggplantzzz** [comment]
Yes, upgrading to version 5 will do the trick.

We recommend the upgrade, but in the case that you need to continue using version 4, we put out a maintenance release that fixed the issue.
https://github.com/trufflesuite/truffle/releases/tag/v4.1.15

**Comment by Jaswanta** [comment]
I am also getting the same issue. I updated by using $ npm uninsrall -g truffle and reinstalled by $ npm install -g truffle. Still I got same error.

**Comment by locpv-ibl** [comment]
This helps: `npm install -g truffle`

**Comment by zaidMughal** [comment]
I uninstalled and reinstalled it and got the same error
