### ISSUE TITLE
TRUFFLE NOT INSTALLING NEW TO DEVELOPING

### ISSUE THREAD

**Issue by alecgarza96** [trufflesuite/truffle#1571]
Currently running the latest version of NPM (6.4.1) Mac Mojave OS. Trying to install truffle but this is what happens when I attempt to install, and then use a command. 
<img width="952" alt="screen shot 2018-12-20 at 11 05 26 am" src="https://user-images.githubusercontent.com/43724421/50299931-83fc0980-0448-11e9-9130-2d54f2afd9ed.png">
<img width="634" alt="screen shot 2018-12-20 at 11 05 47 am" src="https://user-images.githubusercontent.com/43724421/50299953-91b18f00-0448-11e9-87da-c1924906fe98.png">

**Comment by alecgarza96** [comment]
after `truffle init` I'm prompted with `command not found`

**Comment by gnidan** [comment]
Hm your node modules are probably not getting configured in your PATH.

I recommend using [nvm](https://github.com/creationix/nvm) instead of the homebrew-installed version of Node.

Closing this as it is an environment issue related to Node/NPM, not Truffle. Thank you!
