### ISSUE TITLE
artifacts.require() - Correct syntax?

### ISSUE THREAD

**Issue by vvdhout** [trufflesuite/truffle#1576]
## Issue

There is a mismatch in official Truffle documentation and Truffle's MetaCoin Box and am curious to whether this is intentional or if one or the other is deprecated or preferred.

More specifically, the documentation on trufflesuite.com specifies that we should not require by using the source file name because these can contain multiple contracts and should instead use the contract name we want to deploy. MetaCoin Box, on the other hand, does provide us with require statements that do so by referring to the source code name.

## Steps to Reproduce

```
truffle unbox metacoin
cd migrations
2_deploy_contracts
```

![migrations](https://user-images.githubusercontent.com/42076249/50345785-86d22980-0530-11e9-8a2a-49e5d22eaa91.PNG)

Versus:

![artifacts](https://user-images.githubusercontent.com/42076249/50345777-7de15800-0530-11e9-9769-98e03cfe5ecc.PNG)
https://truffleframework.com/docs/truffle/getting-started/running-migrations#migration-files 

## Environment

* Truffle version (`truffle version`): v5.0.0
* node version (`node --version`): v10.8.0
* npm version (`npm --version`): 6.5.0

**Comment by eggplantzzz** [comment]
@vvdhout Yes! The solidity files in the metacoin box are not the preferred method of requiring contract types. You should indeed just be requiring them by name. Thanks for giving us the heads up on this and we'll try and get it fixed soon!

**Comment by eggplantzzz** [comment]
Closing now as the MetaCoin box was updated.
