### ISSUE TITLE
Docs not clear on what web3 version to use

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#1585]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

Congratulations on reaching v5!  The documentation hasn't quite caught up yet, so here's an Issue towards improvement.  

## Issue
I'm attempting browser use of [truffle-contract](https://github.com/trufflesuite/truffle/tree/master/packages/truffle-contract).  The "Browser usage" section of documentation there includes an example with the line `<script type="text/javascript" src="./path/to/web3.min.js"></script>` which means I need to provide a path to the version of web3 that the new version of Truffle expects to find.  

According to the [Release Notes](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0), this version of Truffle requires updating to [Web3.js v1.0](https://web3js.readthedocs.io/en/1.0/index.html), a breaking change.  That page that links to has a clear note up top saying 
>"This documentation is work in progress and web3.js 1.0 is not yet released!"  

From that, the Truffle v5 release seems a little bit premature and might confuse users.  I'll ignore that from here forward.   
[Lower](https://web3js.readthedocs.io/en/1.0/getting-started.html#adding-web3-js) on that documentation page, there are instructions for "adding web3.js" which say `npm install web3` or link `dist/web3.min.js`.

I don't see any `dist` or `web3.min.js` in the any of the `node_modules` subfolders.  The [dist/web3.min.js on ethereum/web3.js (1.0 branch)](https://github.com/ethereum/web3.js/blob/1.0/dist/web3.min.js) was last updated 4 months ago and reports v1.0.0-beta.36. Files in the `develop` branch either there or in [Truffle's web3 fork](https://github.com/trufflesuite/web3.js/tree/develop/dist) were updated 20 days ago and report version 0.20.7 (see e.g. https://github.com/trufflesuite/web3.js/blob/develop/lib/version.json or https://github.com/trufflesuite/web3.js/blob/develop/dist/web3.js#L2476 ).

The Truffle [changelog](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0#user-content-changelog-since-5-0-0-beta-2) lists PR#1495 (Use truffle web3 fork) as well as PR #1513 (going the other way, specifying 1.0.0-beta.37).  

When I go into the node_modules\web3-eth resulting from `npm install web3` I see a README.md saying I should run `npm run-script build-all` in the web3.js repository.  However, when I clone that repo and `cd` to it, then run `npm run-script build-all` I just get an NPM error `missing script: build-all`. Running `npm install gulp -g` shows success but doesn't fix that. 

As I installed truffle globally (per the clear [instruction](https://truffleframework.com/truffle), I tried looking in the global installed node_modules/truffle directory (`C:\Users\me\AppData\Local\node\node_modules\truffle`) but there is no web3 found there.

## Steps to Reproduce
1. Determine via changelog that Truffle v5 is supposed to use web3 v1.0.0-beta37.
2. Attempt to locate a JS file with that version of web3.
3. Fail.

## Expected Behavior
Documentation is clear about where to get or how to successfully build the version of web3 that is supposed to be used with the latest Truffle.  Ideally, that version is marked as released software, instead of having a major release dependent on an unreleased beta. 

## Environment

* Operating System: Windows 10 Pro
* Truffle version (`truffle version`): 5.0.0
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.5.0

**Comment by sarbogast** [comment]
I agree. And maybe the truffle version command should show which version of web3 Truffle uses internally so that we can be sure to use the same version of web3 in a web client as the one used in tests for example.

**Comment by testrain** [comment]
How do we manually set/config web3 version in truffle?  I.e. I do not want to use 1.0.0.xxx.beta, how to use 0.20.7 instead?

**Comment by eggplantzzz** [comment]
@testrain Truffle version 5 uses version 1.0.0-beta.37 and needs to use this version. If you need to use a version less than 1.** you can use the previous version of Truffle (v4.1.15) although it is currently unmaintained as of last December.

**Comment by eggplantzzz** [comment]
Closing this as we no longer require a separate script tag to load web3.
