### ISSUE TITLE
truffle-contract sendTransaction clears data parameter

### ISSUE THREAD

**Issue by ritave** [trufflesuite/truffle#1586]
When trying to send a transaction as such `contactInstance.sendTransaction({data: myData})`, the data parameter is cleared when sent through RPC.

```javascript
Example.deployed().then(instance => instance.sendTransaction({data: "0x1234"})).then(console.log);
```
The resulting RPC sent misses the `data` param.

This is an error on this line https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-contract/lib/execute.js#L166 which should check if `params.data` exist before setting it to `undefined`

**Comment by nventuro** [comment]
This is a departure from pre-truffle 5 behavior, where having a `data` field worked. Since the API is almost the same as `web3.eth.sendTransaction` (except that we don't need to fill in the `to` parameter), we could just use that one, but calling it directly means logs are not decoded, which is a bummer.

**Comment by area** [comment]
This is very unintuitive behaviour, especially as it's advertised in the documentation as 

> has the same API as web3.eth.sendTransaction

Admittedly, this is in the section titled 'triggering the fallback function', but that requires a certain level of reading-between-the-lines to arrive at the conclusion that `data` is unsupported.

**Comment by eggplantzzz** [comment]
@nventuro If you want to trigger a transaction using the data field, you probably want to use `instance.method.sendTransaction`. And yes, like @area said `instance.sendTransaction` is currently primarily intended to run the fallback function. However, currently this is not strictly the same as `web3.eth.sendTransaction` and probably should be. So in the future I think we are going to consider changing that, if you want to submit a PR and help expedite the process you are more than welcome :) Thanks!

**Comment by LiorRabin** [comment]
Hello, so how do I actually send data to the fallback function?

**Comment by haltman-at** [comment]
Just encountered this problem.  Wanted to use `contract.sendTransaction` in a test to make sure we could properly handle some mis-encoded data, but, well, it didn't work, because it didn't send the data.

**Comment by eggplantzzz** [comment]
@LiorRabin What would be the use case for supplying data to the fallback function? I don't think it would serve any purpose, correct me if I'm wrong. According to the Solidity docs, "This function cannot have arguments... It is executed on a call to the contract if none of the other functions match the given function identifier (or if no data was supplied at all)."

**Comment by LiorRabin** [comment]
@eggplantzzz the use case I had in mind when asking the question turned out to be irrelevant.
