### ISSUE TITLE
Truffle-contract version out of sync with Truffle version

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#1587]
## Issue
In the Truffle v5 documentation, "[Interacting with your contracts](https://truffleframework.com/docs/truffle/getting-started/interacting-with-your-contracts#introducing-abstractions)" describes and links to the truffle-contract module.  In the readme at the link, installation instructions are given:    
      `$ npm install truffle-contract`

## Steps to Reproduce
Execute `$ npm install truffle-contract`.

## Actual Results
If successful, this produces a long set of warnings from recompiling keccak, similar to but much longer than #1584, and then    
       `+ truffle-contract@4.0.0`

Specifying version 5 or 5.0.0 results in the package version not being found. 

## Expected Behavior
There are no errors or warnings, but instead
     `+ truffle-contract@5.0.0`

## Environment
* Truffle version (`truffle version`): 5.0.0
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.5.0

**Comment by wbt** [comment]
This remains an issue; it's unclear what version to use. 
Today, `npm install truffle-contract` reports successfully installing [v`4.0.11`](https://github.com/trufflesuite/truffle/blob/a8b49fdfc3d77b59ee4b16551f6e645b24e19541/packages/truffle-contract/package.json#L3).

**Comment by CruzMolina** [comment]
IIRC, packages are published & semver'd separately from the cli. Would be clearer if the docs were updated.

**Comment by wbt** [comment]
@eggplantzzz The parts of the docs I referenced are still there, even the links still work as described in the OP.

**Comment by eggplantzzz** [comment]
Closing this as it appears to no longer be relevant. @wbt let me know if you disagree and there is something actionable here! Thanks!

**Comment by wbt** [comment]
The links and docs are still there, though it's now @truffle/contract.  However, [this comment](https://github.com/trufflesuite/truffle/issues/1587#issuecomment-483363758) seems to explain it, that the `contract` package simply is at a different major version number than the main Truffle package.  

Adding some documentation somewhere (ideally automatically generated) which shows which version of @truffle/contract (and other packages) correspond to which version of truffle could be helpful. My strategy to get the information in the absence of that documentation involves digging through the GitHub commit history to find the commit at which version numbers were updated and look at the other package version numbers as of the same commit.
