### ISSUE TITLE
broken link with website for truffle

### ISSUE THREAD

**Issue by KOREAN139** [trufflesuite/truffle#1591]
## Issue

Since website for this repository has set as http://truffleframework.com, users will get `404 Not found`

Need to fix link with **https://truffleframework.com** - just substitute `http` as `https`

**Comment by KOREAN139** [comment]
Just in case that issue description isn't enough, attach screenshot for that too.
<img width="621" alt="screen shot 2018-12-26 at 16 55 35" src="https://user-images.githubusercontent.com/18724352/50437961-478c4a00-092f-11e9-9a3d-583c6b91cd25.png">

**Comment by eggplantzzz** [comment]
Thanks for bringing this up! I'll get to fixing it
