### ISSUE TITLE
Error in uninstalling truffle to upgrade

### ISSUE THREAD

**Issue by Aniket-Engg** [trufflesuite/truffle#1592]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

## Issue

I have run `npm uninstall -g truffle ` to uninstall truffle so that i can update it. It is not getting uinstalled.

## Steps to Reproduce

Run `npm uninstall -g truffle`

## Expected Behavior

Truffle should be uninstalled

## Actual Results

It prints `up to date in 0.026s`

## Environment

* Operating System:  Ubuntu 16.04 LTS
* Truffle version (`truffle version`): v4.1.14
* node version (`node --version`): v10.7.0
* npm version (`npm --version`): 6.1.0

**Comment by rohitsethii** [comment]
came across the same issue.
Removed `truffle` directory manually from 

> usr/local/bin.

**Comment by wbt** [comment]
Note that if you're just trying to upgrade to truffle v5, the `uninstall` step is not always necessary.

**Comment by Aniket-Engg** [comment]
Actually i removed the truffle from global node modules directory and install the latest version. With new version, `npm uninstall -g truffle` command is working fine.

**Comment by wbt** [comment]
@Aniket-Engg So is this Issue closed?

**Comment by Aniket-Engg** [comment]
Yes, It can be.

**Comment by Aghorb** [comment]
I have the same problem, all the proposed instructions could not fix it.
have you any other suggestion?

**Comment by wbt** [comment]
@Aghorb Exactly what command are you running and what is the response? 
What versions of node and npm are you running and do you have any automated backup system which might be running, holding a read lock on files so they cannot be deleted?
