### ISSUE TITLE
Is it possible to dynamically update dependency artifacts such as openzeppelin library in our truffle project.

### ISSUE THREAD

**Issue by sowmyakannan** [trufflesuite/truffle#1595]
Is it possible to dynamically update dependency artifacts such as openzeppelin library in our truffle project. We have install openzeppelin as an npm package each time we create a new project in truffle. As of now the current version of truffle 5.0.0 is not compatible with the current openzeppelin library because of the difference in the solc compiler version used. Hence we have to wait till openzeppelin releases a truffle 5.0.0 compatible version or downgrade truffle and solc version.

Is it possible to dynamically include those dependencies in our project, similar to how we can set the solc compiler version now. If we could have an option to set the openzeppelin library version too in the truffle-config.js file without having to explicitly install it, it would be very neat. 

For instance in a Java Maven framework, every dependency is specified in a pom.xml configuration file, and whenever there is a change in the dependency version we just have to update the version number in the xml file instead of installing it locally. 

Hoping we could have that convenience too.

**Comment by eggplantzzz** [comment]
@sowmyakannan If you need to, you can write your solidity in a version that is compatible with the compiler that openzeppelin uses. You can then configure your project to use that version...I think something like `^0.4.24` should work.

See https://truffleframework.com/docs/truffle/reference/configuration#compiler-configuration to see how to configure the compiler.

**Comment by sowmyakannan** [comment]
@eggplantzzz  Thanks, I understand that. I was simply suggesting to possibly include such a feature in  a future truffle version wherein we just have to update the version number in a config file and the library is available to us. However I do understand that inorder to be able to do so Openzeppelin would also need to have their libraries available dynamically and not be installed everytime. Same goes for solc compiler version in Solidity.

**Comment by haltman-at** [comment]
You can do something like this already; Truffle supports npm as a package management system.  The documentation for this can be found [here](https://www.trufflesuite.com/docs/truffle/getting-started/package-management-via-npm).  So the config file in question would be package.json.  Does this solve your problem?

**Comment by haltman-at** [comment]
Closing this for issue maintenance.  Let us know if there's still a problem here and we can take another look!
