### ISSUE TITLE
truffle console doesn't work in v5

### ISSUE THREAD

**Issue by PaulRBerg** [trufflesuite/truffle#1601]
## Issue

From the [docs](https://truffleframework.com/docs/truffle/getting-started/using-truffle-develop-and-the-console):

> MyContract.at("0xabcd...").getValue.call();

However, there's no way to make this syntax work with truffle ^5.0.

## Steps to Reproduce

```
$ git clone git@github.com:PaulRBerg/truffle-console-bug.git
$ cd truffle-console-bug
$ npm install
$ ganache-cli
$ truffle console --network development
$ compile
$ migrate
```

Now, either of the following comands will return an error:

- `Note.at("your-contract-address").getNumber.call()`
- `await Note.at("your-contract-address").getNumber.call()`

## Expected Behavior

Return the number set on [deployment](https://github.com/PaulRBerg/truffle-console-bug/blob/master/migrations/2_migrate_note.js), that is 64.

## Actual Results

Error returned:

> TypeError: Cannot read property 'call' of undefined  
> at evalmachine.<anonymous>:1:8

## Environment

* Operating System: macos 
* Ethereum client: 10.14.2
* Truffle version (`truffle version`): 5.0.0
* node version (`node --version`): 10.12.0
* npm version (`npm --version`): 6.5.0

**Comment by eggplantzzz** [comment]
Oh my apologies, the `call` method will return the BN. Not `at`! gnidan is correct.

**Comment by eggplantzzz** [comment]
Is this issue still relevant? If not I will be considering closing this soon.

**Comment by eggplantzzz** [comment]
*Note:* (haha get it?) I tried to duplicate your error locally and couldn't. My steps were as follows:
```
truffle(develop)> let note = await Note.at("0x5040F5c3f1f01C23ad172F3293B466d4aD8E0263")
undefined
truffle(develop)> let num = await note.getNumber.call()
undefined
truffle(develop)> num
<BN: 40>
```

**Comment by eggplantzzz** [comment]
@PaulRBerg Did you get your issue resolved?

**Comment by PaulRBerg** [comment]
Apologies, it's all good now. I don't know why I had the impression that I was awaiting `Note.at`. This should definitely be documented because I think the old functionality was syncrhonous, i.e. you didn't have to use `await`.

Thanks for your help!
