### ISSUE TITLE
Truffle 5 uses buggy ganache-core version

### ISSUE THREAD

**Issue by nventuro** [trufflesuite/truffle#1604]
The 5.0.0 release [uses `ganache-core` 2.3.1](https://github.com/trufflesuite/truffle/blob/v5.0.0/packages/truffle-core/package.json#L21). This release of `ganache-core` contains regression errors, which affect `truffle test` directly (TL,DR: snapshots are broken). 

Please upgrade to [`ganache-core` 2.3.2](https://github.com/trufflesuite/ganache-core/releases/tag/v2.3.2), where this is fixed.

**Comment by gnidan** [comment]
This has been released in v5.0.1. Thanks for reporting!
