### ISSUE TITLE
compile/migrate with multiple solidity versions crashes ganache 2

### ISSUE THREAD

**Issue by WyseNynja** [trufflesuite/truffle#1607]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm writing a contract with solidity 0.5 and wanting to call a contract written (and deployed by someone else on mainnet) with solidity 0.4 (and another with Vyper: #1623). How should I setup truffle+ganache in development to deploy the old contract with the old compiler and then deploy my new contracts? I don't want to update their contract to 0.5 because I want my tests to use the version they already have deployed on mainnet. I'm using an interface to interact with the old code as detailed at https://solidity.readthedocs.io/en/v0.5.0/050-breaking-changes.html#interoperability-with-older-contracts

The 0.4 contract (https://github.com/projectchicago/gastoken/blob/master/contract/GST2_ETH.sol) is using python tools for deployment. If it were using truffle, I could run `truffle migrate` from their directory and then run `truffle migrate` from mine, but then I'm not sure how I would use `artifacts`.

If I symlink their *.sols into my contracts directory, it fails with the expected "ParserError: Source file requires different compiler version"

Right now I'm just hard coding the gastoken contract address so I can test the other parts of my migrations, but that won't work once I actually want to test using the gastoken contract from inside my own contract.

Is there some way to deploy their .asm files directly? I feel like this should be a common need, but I'm not seeing any documentation about it.

And when I do get to putting my contracts on mainnet, what is the best practice for linking to the already deployed gastoken contract instead of deploying it myself?

**Comment by gnidan** [comment]
Thanks for raising this concern! It's on the roadmap to support multiple solc versions natively, but there are some technical limitations that make this not immediately feasible.

The component you are missing is that you need proper Truffle artifact files (`build/contracts/` JSON files) for each contract. You can't deploy ASM directly, but if you get the bytecode, you can wrap the bytecode in an artifact file and deploy that.

You might be able to achieve a workaround by way of using Truffle's new [external compiler](https://truffleframework.com/docs/truffle/reference/configuration#external-compilers) configuration. It should be flexible enough for this use case, but let me know.

**Comment by WyseNynja** [comment]
Thanks!

I added https://github.com/projectchicago/gastoken as a git submodule at `./external/gastoken`. That repo includes *.sol, *.abi, and *.asm files that I think are relevant.

Then I added this to my truffle-config.json:
```
module.exports = {
    ...
    external: {
      command: "true",
      targets: [{
        properties: {
          contractName: "GST2",
        },
        fileProperties: {
          abi: "./external/gastoken/contract/GST.abi",
          bytecode: "./external/gastoken/contract/GST2_ETH.asm",
        },
      }]
    }
  },
```

And now `truffle compile` places a GST2.json file into my contracts directory. So I think this is good progress, but it isn't right yet. You said "you can't deploy ASM directly, but if you get the bytecode, you can wrap the bytecode." How do I do that?

**Comment by WyseNynja** [comment]
It appears that `bytecode` is different than what `solc --bin` gives.

`solc --help` does not show any flags for outputting bytecode.

I've got something working, but I'm not sure how correct it is.

I ended up making an input json which does allow the necessary output selection options:
```
{
  "language": "Solidity",
  "sources":
  {
    "GST2_ETH.sol":
    {
      "urls":
      [
        "./GST2_ETH.sol"
      ]
    }
  },
  "settings":
  {
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "outputSelection": {
      "*": {
        "*": [ "abi", "evm.bytecode.object" ]
      }
    }
  }
}
```

Then I made a compile script:
```
#!/bin/bash -eu

echo "Building external contracts..."

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

root_dir="$(realpath "${script_dir}/../")"

build_dir="${root_dir}/build"

external_dir="${root_dir}/external"

mkdir -p "$build_dir/tmp"

# pull bytecode and abi out of solc --standard-json output
function extract_abi_and_bytecode {
    build_json=$1
    output_dir=$2
    sol_filename=$3
    contract_name=$4

    jq ".contracts[\"$sol_filename\"][\"$contract_name\"].abi" \
        < "$build_json" \
        > "${output_dir}/${contract_name}.abi"

    echo "Created \"${output_dir}/${contract_name}.abi\""

    # prefix bytecode with 0x
    jq -j "\"0x\"+.contracts[\"$sol_filename\"][\"$contract_name\"].evm.bytecode.object" \
        < "$build_json" \
        > "${output_dir}/${contract_name}.bytecode"

    echo "Created \"${output_dir}/${contract_name}.bytecode\""
}

# gastoken
cd "$external_dir/gastoken/contract"

cat "$external_dir/solc-gastoken.json"
solc-0.4.25 \
    --allow-paths "$(pwd)" \
    --standard-json \
    < "$external_dir/solc-gastoken.json" \
    > "$build_dir/tmp/gastoken.json"

extract_abi_and_bytecode "$build_dir/tmp/gastoken.json" "$build_dir/gastoken" "GST2_ETH.sol" "GasToken2"
# TODO: what about rlp?

# TODO: build more contracts

echo "Success building external contracts"
```

And then I added this script to my `truffle-config.js`
```
module.exports = {
  compilers: {
    // TODO: only run if they are outdated
    ...
    external: {
      command: "./scripts/build-external.sh",
      targets: [
        {
          properties: {
            contractName: "GasToken2",
          },
          fileProperties: {
            abi: "build/gastoken/GasToken2.abi",
            bytecode: "build/gastoken/GasToken2.bytecode",
          },
        },
        // TODO: lots more contracts here
      ],
    },
  },
  ...
};
```

And now my migrations work!

I think this would be a lot simpler if solc had a --bytecode flag or truffle could access the output of --bin instead.

**Comment by WyseNynja** [comment]
I was able to simplify my external compile script:
```
#!/bin/bash -eux

echo "Building external contracts..."

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

root_dir="$(realpath "${script_dir}/../")"

build_dir="${root_dir}/build"

external_dir="${root_dir}/external"

# gastoken
gastoken_contract_dir="${external_dir}/gastoken/contract"
solc-0.4.25 \
    --allow-paths "${gastoken_contract_dir}" \
    --optimize \
    --output-dir "${build_dir}/gastoken" \
    --overwrite \
    --abi --ast-compact-json --bin \
    "=${gastoken_contract_dir}/" \
    "${gastoken_contract_dir}/GST2_ETH.sol"

# TODO: what about rlp?

# bin output needs to be prefixed with 0x for truffle to like it # TODO: do this for ALL $build_dir/*/*.bin
(echo -n "0x"; cat "${build_dir}/gastoken/GasToken2.bin") > "${build_dir}/gastoken/GasToken2.bytecode"

# TODO: build more contracts

echo "Success building external contracts"
```

This would be simpler if truffle didn't require that bytecode started with "0x". Why does it require that? solc doesn't output it that way, so I'm having to modify its output.

**Comment by WyseNynja** [comment]
Where are the available "fileProperties" documented? I needed to add `ast` to it to get slither working. I don't think the way I added it is working with ganache 2 though.

truffle-config.js:
```
    external: {
      command: "./scripts/build-external.sh",
      targets: [
        {
          properties: {
            contractName: "GasToken2",
          },
          fileProperties: {
            abi: "build/external/gastoken/GasToken2.abi",
            ast: "build/external/gastoken/GST2_ETH.sol_json.ast",
            bytecode: "build/external/gastoken/GasToken2.truffle-bin",
          },
        },
        {
          properties: {
            contractName: "rlp",
          },
          fileProperties: {
            abi: "build/external/gastoken/Rlp.abi",
            ast: "build/external/gastoken/rlp.sol_json.ast",
            bytecode: "build/external/gastoken/Rlp.truffle-bin",
          },
        },
```

`trufle compile/migrate` then outputs this GasToken2.json: https://gist.github.com/WyseNynja/e54064191465abc3c662b3b2df1e4280

When I look at the contract in Ganache though, it tries to load for a few seconds and then crashes with this error:
```
TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getContractState (/src/truffle-integration/decode.js:9:11)
    at process.<anonymous> (/src/truffle-integration/index.js:78:52)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by eggplantzzz** [comment]
I think the schema for those artifacts can be found here --> https://github.com/trufflesuite/truffle/tree/develop/packages/truffle-contract-schema

Also `require("truffle-contract-schema").validate(obj)` can help you validate the contract object.

**Comment by WyseNynja** [comment]
@eggplantzzz Thanks for the reply. I'm trying to let truffle build the truffle contract during the external compile step. I'm wanting to know the best way to convert solc's output to a truffle contract. I thought using a truffle-config.js like this would put everything in the right place, but it only seems to setup the abi and bytecode:

```
    external: {
      command: "./scripts/build-external.sh",
      targets: [
        {
          properties: {
            contractName: "GasToken2",
            sourcePath: "external/gastoken/contract/GST2_ETH.sol",
          },
          fileProperties: {
            abi: "build/external/gastoken/GasToken2.abi",
            ast: "build/external/gastoken/GST2_ETH.sol_json.ast",
            bytecode: "build/external/gastoken/GasToken2.truffle-bin",
            deployedBytecode: "build/external/gastoken/GasToken2.truffle-bin-runtime",
            devdoc: "build/external/gastoken/GasToken2.docdev",
            userdoc: "build/external/gastoken/GasToken2.docuser",
            source: "external/gastoken/contract/GST2_ETH.sol",
          },
        },
```

I would much prefer to be able to use the combined json from solc instead of having to configure all those properties manually for each contract. To do that, it sounds like I need a script that reads solc's combined output json and builds something that `require("truffle-contract-schema").validate(obj)` is happy with.

Rather than an external script, I think it would be better for this code to be a part of the truffle external compiler step. Having only the abi and bytecode passed through may be enough for migrations, but more things should be able to pass through. Where in truffle's code is the abi and bytecode passed through? It seems like adding support for source maps and the others should be relatively simple.

**Comment by gnidan** [comment]
@WyseNynja just a drive-by response: you might be interested to look at the [integration tests for this feature](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/test/scenarios/external_compilers/truffle-compile.js). They use `truffle compile` itself as an external compiler.

Right now, the translation between Solidity standard JSON and a Truffle artifact is done by `truffle-compile`, and it relies on Truffle tightly controlling the input. It's not entirely straightforward to take any solc output and convert it to artifacts, at least not enough to provide out of the box.

I would recommend maybe looking at the `path` version of `targets` and maybe building a `truffle run` plugin? Something like:

```javascript
module.exports = {
  /* ... */
  compilers: {
    external: {
      command: "...",
      targets: [{
        path: ".../path/to/solc-outputs/*.solc.json"
        command: "truffle run solc-standard-json-to-artifact"
      }]
    }
  }
}
```

**Comment by eggplantzzz** [comment]
https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-compile/index.js#L194
This is the line where the code puts together the contract.

**Comment by WyseNynja** [comment]
I'm trying out @gnidan's suggestion.

Here is my truffle-config.js:
```
```

Here is what I've come up with for an external compile target script so far:
```
#!/usr/bin/env node
const fs = require('fs');
const semver = require('semver');

// node sol-compiler-json-to-truffle.js inputFilename
const inputFilename = process.argv[2];

const inputObj = JSON.parse(fs.readFileSync(inputFilename, 'utf8'));

if (!semver.satisfies(inputObj["schemaVersion"], '^2.0.0')) {
  throw "incompatible schemaVersion";
}

var truffleObject = {
  "contractName": inputObj["contractName"],
  "abi": inputObj["compilerOutput"]["abi"],
  "bytecode": inputObj["compilerOutput"]["evm"]["bytecode"]["object"],
  "deployedBytecode": inputObj["compilerOutput"]["evm"]["deployedBytecode"]["object"],
  "sourceMap": inputObj["compilerOutput"]["evm"]["bytecode"]["sourceMap"],
  "deployedSourceMap": inputObj["compilerOutput"]["evm"]["deployedBytecode"]["sourceMap"],
  // TODO: "source": inputObj["sources"][inputObj["contractName"] + ".sol"],
  // TODO: "sourcePath": "",
  // TODO: "ast": {},
  // TODO: "lagacyAST": {},
  "compiler": {
    "name": inputObj["compiler"]["name"],
    "version": inputObj["compiler"]["version"],
  },
  "networks": {},
  "schemaVersion": "3.0.1",
  "updatedAt": "2019-01-27T03:25:52.161Z",  // TODO: dynamic
  "devdoc": inputObj["compilerOutput"]["devdoc"],
  "userdoc": inputObj["compilerOutput"]["userdoc"],
};

// TODO: check somewhere for mainnet contract addresses

// TODO: validate truffleObject here? I think truffle will do it for us after this

// console.error(truffleObject);

// give truffle the contract artifact formatted like it expects
console.log(JSON.stringify(truffleObject));
```

Something is wrong about the abi though. Running `truffle compile` gives this error along with a bunch of others:

```
Error: Schema validation failed. Errors:

should NOT have additional properties (additionalProperties):
{ dataPath: '.abi[3]',
  schemaPath: '#/additionalProperties',
  params: { additionalProperty: 'constant' },
  data:
   { constant: true,
     inputs:
      [ { name: '_addresses', type: 'address[]' },
        { name: '_calldatas', type: 'bytes[]' } ],
     name: 'encodeContractCalls',
     outputs: [ { name: 'script', type: 'bytes' } ],
     payable: false,
     stateMutability: 'pure',
     type: 'function' },
  parentSchema:
   { type: 'object',
     properties:
      { type: { type: 'string', enum: [ 'event' ] },
        name: { '$ref': '#/definitions/Name' },
        inputs:
         { type: 'array',
           items: { '$ref': '#/definitions/EventParameter' } },
        anonymous: { type: 'boolean' } },
     required: [ 'type', 'name', 'inputs', 'anonymous' ],
     additionalProperties: false } }
```

I don't understand why it thinks that "constant" is an additional property. Looking at the truffle artifact that truffle generated itself, the abi sections look pretty much the same to me. The order is different between them, but all the keys are the same. What sort of modifications do I need to make to abi? Is sharing my complete repo needed to debug this?

**Comment by WyseNynja** [comment]
Here is the full output I get when I try to include the abi as sol-compiler gives it to me: https://gist.github.com/WyseNynja/d1536bf19ff754c2bbc0f3d6aa0508e2

**Comment by WyseNynja** [comment]
The problem with https://gist.github.com/WyseNynja/d1536bf19ff754c2bbc0f3d6aa0508e2 was using `pragma experimental ABIEncoderV2;` and `bytes[]`

After commenting out the method that was doing that, the abi validates. I guess I can work without that for now, but it was nice to have.

**Comment by WyseNynja** [comment]
Given that the rest of my issues seem to be in ganache, I'm going to continue this at https://github.com/trufflesuite/ganache/issues/1117
