### ISSUE TITLE
hdwallet-provider: `web3.getAccounts()` returns incorrect accounts.

### ISSUE THREAD

**Issue by Levino** [trufflesuite/truffle#1610]
I will add a test in a PR to reproduce.

**Comment by Levino** [comment]
Anybody here??

**Comment by eggplantzzz** [comment]
Actually I think the accounts provided as "dummy" accounts are incorrect. They didn't respect some of the capitalization that the given mnemonic provides. They are "almost" correct :) I'll get this changed, thanks for catching this!

**Comment by eggplantzzz** [comment]
Ok so the addresses returned by web3 are in the checksum format. I don't really think we care too much about that at the moment as addresses are basically case insensitive. Thanks for submitting this. though!

**Comment by cameel** [comment]
Just a heads up - this can cause subtle problems in projects that make assumptions about addresses being always lower case. See for example https://github.com/gnosis/safe-contracts/pull/234 where this change made plain `sort()` unsuitable for sorting addresses as hex numbers and resulted in random failures of the test suite.
