### ISSUE TITLE
Migration, dry run and hd-wallet-provider do not work together.

### ISSUE THREAD

**Issue by Levino** [trufflesuite/truffle#1612]
I have a migration that deploys a token contract, a crowdsale contract and (**very important part**) changes ownership, adds whitelisted users, etc.

When I run this migration on a local test rpc all is fine. When I run it on kovan the migration will fail during the dry run. I [switched the dry run off ](https://github.com/trufflesuite/truffle/issues/1609) now all is fine.

Lesson learned: Skip the buggy dry run.

I created this issue for others to save their lifetime. Took me a couple of hours.

**Comment by eggplantzzz** [comment]
@Levino @mrwillis Are either of you able to provide examples of this? I would like to run it and try and see what is going on.

**Comment by Levino** [comment]
I started to make an example repo. Look at this file: https://github.com/Levino/truffle-dry-run-failure/blob/master/migrations/2_mummy_migration.js

I think the dry run would fail but I am not able to test atm because https://github.com/trufflesuite/truffle/issues/1667

Waiting for this to get fixed.

**Comment by Levino** [comment]
Truffle is working again with web3. I pushed some changes to the repo with a working example now. I was not able to reproduce the bug though and do not want to spend more time atm on this. Might revisit later. I am happy for a PR by @mrwillis to reproduce the error. I think my basic example is a very good starting point. https://github.com/Levino/truffle-dry-run-failure

**Comment by rrodriguezreche** [comment]
Browsing for another issue I stepped on this.

For anyone struggling, I managed to pull this workaround. It seems like web3 is somehow internally aware of the injected hdwallet provider even in dry-runs, it is just that the accounts in the hdwallet provider do not exist in the `accounts` variable that is passed in the migrations exports:

`module.exports = function(deployer, network, accounts) { ... }`

But as I said, web3 internally knows about the hdwallet accounts, you can get access to those accounts through `web3.currentProvider.options.unlocked_accounts`. 

I am leaving a code snippet as example.

```
const config = async accounts => {
  const [deployerAccount, master, minter1, minter2, minter3] = accounts;

  let token = await Token.deployed();
  let emitter = await Emitter.deployed();

  var { tx } = await token.transferOwnership(emitter.address, {
    from: deployerAccount
  });
  console.log(
    `   > Token ownership transferred to emitter ${emitter.address} in tx ${tx}`
  );
  tx = undefined;

  var { tx } = await emitter.transferOwnership(master, {
    from: deployerAccount
  });
  console.log(
    `   > Emitter ownership transferred to address ${master} in tx ${tx}`
  );
  tx = undefined;

  var { tx } = await emitter.addMinter(minter1, { from: master });
  console.log(`   > Added minter ${minter1} in tx ${tx}`);
  var { tx } = await emitter.addMinter(minter2, { from: master });
  console.log(`   > Added minter ${minter2} in tx ${tx}`);
  var { tx } = await emitter.addMinter(minter3, { from: master });
  console.log(`   > Added minter ${minter3} in tx ${tx}`);

  return '    > Succesfully configured contract';
};

module.exports = function(deployer, network, accounts) {
  if (network.includes('test') || network.includes('development'))
    // do not deploy, each test should deploy by itself
    return;

  console.log('   Transferring ownership and adding minters');

  // Workaround for selecting the configured HDWalletProvider instead of the
  // automatic generated from ganache during dry-runs
  let _accounts = network.includes('fork')
    ? web3.currentProvider.options.unlocked_accounts
    : accounts;

  return config(_accounts)
    .then(console.log)
    .catch(console.error);
};
```

**Comment by eggplantzzz** [comment]
Just doing some maintenance and wanted to see if this issue is still relevant/valid. It looks like it is possible it was resolved at some point? If someone could let me know I would appreciate it!
