### ISSUE TITLE
Template webpack box compiles to a strangely large app.js, leading to warnings and annoyingly long compile times

### ISSUE THREAD

**Issue by mcplums** [trufflesuite/truffle#1613]
I have indeed requested help on the gitter :)

## Issue

The compiled app.js of the template webpack box is 700kB big. Is it normal for it to be this big when the project is tiny? It takes a few seconds to re-compile everytime I make a small change. I also get a warning: 

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  app.js (704 KiB)

## Steps to Reproduce

truffle unbox webpack
npm run dev

## Expected Behavior

I would expect the compiled app.js to be a lot smaller. I know 100% from memory that it used to be a lot smaller and didn't give me these warnings. 

## Actual Results

https://i.imgur.com/VKNf2KP.jpg

## Environment

* Operating System: Mac OS Mojave
* Ethereum client: n/a
* Truffle version (`truffle version`): 5.01
* node version (`node --version`): 9.9
* npm version (`npm --version`): 5.6

**Comment by mcplums** [comment]
Ok thanks for your reply :)

**Comment by eggplantzzz** [comment]
Update: The webpack box was recently re-written but the bundle size is still a little bit on the heavy side. Unfortunately web3 is kind of big along with some other dependencies. Hopefully it is faster/more useful than it was!
