### ISSUE TITLE
Truffle not support a high gas limit

### ISSUE THREAD

**Issue by rotcivegaf** [trufflesuite/truffle#1615]
I cant deploy an empty contract, using ganache-cli with a high gas limit 

## Steps to Reproduce
Start ganache-cli `ganache-cli --gasLimit 0xfffffffffffffffffffff`
Test the a empty contract `truffle test`

## Expected Behavior

Deploy the empty contract

## Actual Results

> Error: Number can only safely store up to 53 bits

![error](https://user-images.githubusercontent.com/7088778/50710193-0b509c00-1049-11e9-93c9-08bc4a95c354.png)

## Environment

* Operating System: Ubuntu 18.04.1 LTS
* Ethereum client: Ganache CLI v6.2.5 (ganache-core: 2.3.3)
* Truffle version (`truffle version`): Truffle v5.0.0
* node version (`node --version`): v11.5.0
* npm version (`npm --version`): 6.4.1

**Comment by gnidan** [comment]
A workaround for this is in progress in #1544 (via a `--legacy` flag).

We will need to figure out a more permanent solution, however, so I'll leave this open to represent that work.

Thanks for opening this issue!
