### ISSUE TITLE
Truffle doesn't return any error output to the console

### ISSUE THREAD

**Issue by saitam1** [trufflesuite/truffle#1618]
## Issue

I am trying to deploy this contract (https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/simplestorage.sol) on a private permissioned Quorum network. The migration fails on the initial migration contract. If I try to repeat the process with: 
`sudo truffle migrate --network development --reset `
I don't get any output on the console at all. When I try to deploy another contract with other network configurations I also get no output to the console.
Without a console output it is not possible to find out what is wrong. Is this a bug in the new version?

## Steps to Reproduce

I am following this tutorial: https://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains

## Expected Behavior

An output like shown here: https://truffleframework.com/docs/truffle/quickstart

## Actual Results

    Starting migrations...
    ======================
    > Network name:    'development'
    > Network id:      1337
    > Block gas limit: 3758096384
    
    
    1_initial_migration.js
    ======================
    
       Deploying 'Migrations'
       ----------------------
       > transaction hash:    0xd56cfd9d7bfa56b2s30138bb9a348069e40e92c2b41da87a081f2070560075
       > Blocks: 0            Seconds: 0
       > contract address:    0x17D3233DD54d2491b68c62b534Da313c29456A39
       > account:             0xC58A28d310c76e8298FA456381E6F2da9F046V54
       > balance:             1000000000
       > gas used:            245462
       > gas price:           0 gwei
       > value sent:          0 ETH
       > total cost:          0 ETH
    
    
       ⠋ Saving migration to chain.Error: Number can only safely store up to 53 bits

## Environment

    Truffle v5.0.1 (core: 5.0.1)
    Node v10.14.2
    Quorum v2.2.0
    Geth version: 1.8.12-stable
    OS & Version: Ubuntu 16.04.5 LTS

**Comment by andrej-zirko** [comment]
I'm having the same issue "Number can only safely store up to 53 bits" on first migration and then all others fail silently. I'm also connecting to quorum. Please what was the issue resolution?

**Comment by codenamejason** [comment]
I have now tried two machines and cannot migrate my contracts after they have successfully compiled. I get no output at all acutally. 
Truffle v5.1.25 (core: 5.1.25)
Solidity - 0.6.2 (solc-js)
Node v12.16.3
Web3.js v1.2.1

**Comment by cbruguera** [comment]
@saitam1 Why was this issue closed? I'm using truffle 5.1.27 and I have a probably related error. I'm using `truffle console` and `exec path/to/script.js` inside, execution just seems to be hanging with no error message given, even with improper syntax inside the script on purpose. I need a way to know when my script throws an error.

**Comment by gruvin** [comment]
I have the same problem, all of a sudden and for the life of me cannot figure out.

Don't understand why the issue was closed without comment, when such good detailed report was given.
