### ISSUE TITLE
How to use Truffle Contract in a web setup?

### ISSUE THREAD

**Issue by sarbogast** [trufflesuite/truffle#1619]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm trying to use the latest version of Truffle Contract (4.0.1) in a web page but I keep getting errors when Truffle Contract loads.

## Steps to Reproduce

I implemented the instructions in the documentation, importing web3 (1.0.0-beta.37), ethers.js (latest version, 4.0.20, since no version is specified in the documentation), and finally Truffle Contract 4.0.1:

```
<script src="js/web3.min.js"></script>
<script src="js/ethers.min.js"></script>
<script src="js/truffle-contract.js"></script>
<script src="js/app.js"></script>
```

Then in app.js I load a JSON artifact and try to use it to initialize a TruffleContract instance:

```
    initContract: async () => {
        $.getJSON("ChainList.json", function(artifact) {
            App.contracts.MyContract = TruffleContract(artifact);
            App.contracts.MyContract.setProvider(window.web3.currentProvider);
        });
    },
```

But the moment when the truffle-contract.js script gets loaded, I get the following error in Chrome's console:

```
Uncaught TypeError: EthersAbi is not a constructor
    at Object.32.ethers/utils/abi-coder (truffle-contract.js:9150)
    at o (truffle-contract.js:1)
    at truffle-contract.js:1
    at Object.98../reformat (truffle-contract.js:18887)
    at o (truffle-contract.js:1)
    at truffle-contract.js:1
    at Object.92../handlers (truffle-contract.js:18020)
    at o (truffle-contract.js:1)
    at truffle-contract.js:1
    at Object.<anonymous> (truffle-contract.js:17090)
```

And then when I'm initializing the TruffleContract, I get the following error:

```
Uncaught TypeError: TruffleContract is not a function
    at Object.success (app.js:49)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at y (jquery.min.js:4)
    at XMLHttpRequest.c (jquery.min.js:4)
```

Can you please be more specific about which versions of those libraries are required, and especially what's the right combination of them so that I can configure my web environment correctly.

I'm trying to put together an online course that explains to people how to use Truffle, and I would hate to have to show them how to use web3's contract abstraction in the web part when they got used to using Truffle Contract in the truffle console and tests.

**Comment by gnidan** [comment]
OK it seems I've been able to remove all external `<script />` dependencies. I'll release this on Monday.

**Comment by gnidan** [comment]
Thank you!

**Comment by sarbogast** [comment]
@gnidan Did you release the new version of Truffle Contract?

**Comment by romullobernardo** [comment]
I'm having the same problem here. Should I downgrade to version 3?

**Comment by gnidan** [comment]
I'll get that out today!

**Comment by gnidan** [comment]
Just released v4.0.2 of truffle contract. @sarbogast can you see if this fixes the issue for you and close it?

And/or anyone else tell me what I broke :)

**Comment by sarbogast** [comment]
Thanks @gnidan ! It seems to have solved this issue. 
I seem to hit another wall with web3 returning undefined accounts (another issue), but just to be sure, which version of web3 does truffle-contract.js embed?

**Comment by sarbogast** [comment]
@gnidan After verification, if I don't add the script tag to my HTML page to explicitly load the web3 library I have locally (in version 1.0 beta 37), when I create a Web3 instance it is in version 0.20.3. My guess is that the Web3 library embedded is superseded by the one exposed by Metamask.
But if I explicitly add the script tag to load web3 on my own like I used to, the Web3 object I create is in the right version.

**Comment by gnidan** [comment]
Your last comment makes sense. The internally bundled web3 is for truffle-contract's code to use, which was previously what was causing the error. If you want to use web3 directly, you will likely want to pull it in yourself, or make do with the version MetaMask gives you.

Sounds like this is good? Closing! Let me know if I need to reopen. Thanks!

**Comment by sarbogast** [comment]
Yes, it's good. Thanks.
