### ISSUE TITLE
[Truffle-Decoder] Undefined or Null this.stateVariableReferences

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/truffle#1627]
Two issues have been raised within the Ganache repo (https://github.com/trufflesuite/ganache/issues/1060 and https://github.com/trufflesuite/ganache/issues/1066) that are referencing errors within the `truffle-decoder`

The error looks like:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:91:36)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

These were reported with version `truffle-decoder@1.0.1-beta.0`. The specific line that they're referring to is: https://github.com/trufflesuite/truffle/blob/b2a61f568e17f3d2d717c876f487aa7eb6cb4514/packages/truffle-decoder/lib/interface/contract-decoder.ts#L165

which implies that `this.stateVariableReferences` is either `null` or `undefined`, which means the `init()` function is not finishing without error.

I have requested for more information what contracts are used as I cannot reproduce the error, and I'm still waiting on feedback to be able to try to reproduce this.

**Comment by gnidan** [comment]
@seesemichaelj do you know if this is still a problem?

**Comment by seesemichaelj** [comment]
@gnidan I'm not sure. We couldn't reproduce the issues and the users never provided more info. FWIW, I am no longer listening to new Ganache issues/etc. It looks like no one else reported the issue. We could maybe close this, but also people may not be using the Ganache 2 betas because they think they're buggy :man_shrugging:

**Comment by CruzMolina** [comment]
Closing this since it seems out of date. Feel free to open if it's not!
