### ISSUE TITLE
accounts parameter undefined

### ISSUE THREAD

**Issue by zach-is-my-name** [trufflesuite/truffle#1632]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
```truffle migrate```

`//migrations.js` 
```module.exports = function (deployer, accounts) { deployer.deploy(BondingCurveConstructor, 10, 333333, {from: accounts[0], value:amount}) };```

```BondingCurveConstructor" -- Provided address "accounts[0]" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted..```

Why might I be receiving undefined here? 

```
truffle(development)> web3.eth.defaultAccount                                                                                                                                 
null                  
truffle(development)> web3.eth.getAccounts()
[ '0xaBFF4B8D4..., ... ]

```
## Environment

* Operating System: Linux 
* Ethereum client: Ganache 2.0 beta
* Truffle version (`truffle version`): 5.0
* node version (`node --version`): 11.5
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
The variable `accounts` needs to be passed as the third argument to the above function. The second one is `networks`.
In other words --> 
```
module.exports = function (deployer, networks, accounts) {
  deployer.deploy(Bonding.....
***** the rest of the stuff ******
```
It seems like you might need to set the `defaultAccount` property manually with web3? From the docs --> https://web3js.readthedocs.io/en/1.0/web3-eth.html#defaultaccount

**Comment by zach-is-my-name** [comment]
Sounds reasonable.  I'll close and re-open if necessary
