### ISSUE TITLE
Where is the packages directory?

### ISSUE THREAD

**Issue by aakilfernandes** [trufflesuite/truffle#1638]
There's a bunch of good looking stuff in the `packages` directory. However when I `npm install truffle`, its not in `node_modules/truffle`. Where did it go?

**Comment by aakilfernandes** [comment]
Asking cause I need to require `truffle/packages/truffle-artifacts`

**Comment by gnidan** [comment]
Just `require("truffle-artifactor")`. All that good stuff gets released as separate NPM packages :)

Closing this, assuming this answers the question. Thanks for reaching out!
