### ISSUE TITLE
eth_signTypedData doesn't work with hdwallet-provider

### ISSUE THREAD

**Issue by hellwolf** [trufflesuite/truffle#1643]
- [yes, asked, no one replied] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

eth_signTypedData doesn't work with hdwallet-provider

## Steps to Reproduce

```
web3.currentProvider.sendAsync({
            jsonrpc: "2.0",
            method: "eth_signTypedData",
            params: [customerAddress, data],
            //from: customerAddress,
            id: new Date().getTime()
        }, (err, result) => {
...
```

## Expected Behavior

Typed data successfully signed by ganache.

## Actual Results

https://github.com/cgewecke/provider-engine/blob/master/subproviders/hooked-wallet.js doesn't support the correct eth_signTypedData spec, and the method fails.

## Environment

* Operating System: Ubuntu
* Ethereum client: Ganache CLI v6.2.5 (ganache-core: 2.3.3)
* Truffle v5.0.2 (core: 5.0.2)
* Node v10.15.0
* npm version : 6.4.1

## possible workaround

Inside hdwallet provide code:

```
  // hack1: make signTypedData work
  {
    let origHandler = hookedSubprovider.handleRequest.bind(hookedSubprovider);
    hookedSubprovider.handleRequest = function(payload, next, end) {
      switch(payload.method) {
        case 'eth_signTypedData':
          next();
          break;
        default:
          return origHandler(payload, next, end)
      }
    }
  }
this.engine.addProvider(hookedSubprovider);
```

Although I think to fix in hooked subprovider is better.

**Comment by eggplantzzz** [comment]
@hellwolf I think web3 removed the `sendAsync` method. Currently I believe it is just `send` and it is asynchronous.

**Comment by hellwolf** [comment]
okay, I tested with ganache and somehow it was not a problem.

**Comment by gnidan** [comment]
Yeah, `sendAsync` is just `send` now. But that doesn't sound like the problem.

Could you provide more info about how the failure appears? Exception stacktrace or anything else that might be helpful. Thanks!

**Comment by eggplantzzz** [comment]
Closing for issue maintenance. If still need this to be troubleshot, feel free to get back to us and we'll re-open!
