### ISSUE TITLE
Could use eth_getLogs from web3.js

### ISSUE THREAD

**Issue by axic** [trufflesuite/truffle#1647]
https://github.com/trufflesuite/truffle/blob/master/packages/truffle-core/lib/testing/testrunner.js#L148 implements this RP method in Truffle because web3.js didn't had it initially.

It has been added since with https://github.com/ethereum/web3.js/pull/1804

**Comment by gnidan** [comment]
ooh @axic you always find these kinds of things! we'll get this implemented soon probably. thanks for raising!

**Comment by eggplantzzz** [comment]
Is `web3.eth.getPastLogs` the method that we want to use here?

**Comment by axic** [comment]
It seems to be that web3.js renamed `web3.eth.getLogs` to `web3.eth.getPastLogs`:
- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs
- https://web3js.readthedocs.io/en/1.0/web3-eth.html#getpastlogs
- https://github.com/ethereum/web3.js/blob/cd32de24bf8751ab0d70f892dd968bbff25d7796/packages/web3-core-method/src/methods/GetPastLogsMethod.js#L34

@nivida @frozeman was there any good reason for this? Are other clients/libraries using the `getPastLogs` name?

**Comment by eggplantzzz** [comment]
This is done in https://github.com/trufflesuite/truffle/pull/2646. Thanks everyone!
