### ISSUE TITLE
Add support for Quorum's privateFor transaction parameter

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#1656]
Truffle doesn't support Quorum's `privateFor` transaction parameter today. See [this wiki page](https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing) for details on this parameter and how it impacts transactions in Quorum.

Support for this field should be added to `truffle-contract` at a minimum, but also we should take a look at Truffle's migration and test subsystems to figure out how to allow users to handle private transactions in those contexts.

I'm not certain that adding this to `truffle-contract` automatically adds support to Drizzle. As a result, I'd advise reviewing Drizzle's integration of `truffle-contract` and giving consideration to exposing user controls in Drizzle which more readily allow for private transactions.

**Comment by tcoulter** [comment]
I wrote a quick test to see if `privateFor` was at least past down to the provider. It turns out, in certain cases it was: https://github.com/trufflesuite/truffle/pull/1940

From what I've found, if a parameter that web3 expects is added to the transaction options (like `from`) then `privateFor` is accepted and past down. Without `from` it'll be ignored.

**Comment by benjamincburns** [comment]
Chiming in because I didn't capture it well on the original ticket, but it's also worth pointing out the existence of `eth_sendRawPrivateTransacton`, which is analogous to `eth_sendRawTransaction`, but intended for use with, as you likely guessed by now, private transactions.

This means that when signing a transaction, `truffle-hdwallet-provider` and similar signing providers should check for the existence of the `privateFor` field and use `eth_sendRawPrivateTransaction` with the signing techinque described in the quorum docs [here](https://github.com/jpmorganchase/quorum/blob/master/docs/api.md#ethsendrawprivatetransaction) (other RPC API modifications are detailed [on the same page](https://github.com/jpmorganchase/quorum/blob/master/docs/api.md)).

Also for completeness, here's a link to the docs on [how quorum processes private transactions](https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing#private-transactions)

Just wanted to make sure the information was captured, so no worries if you decide this is out of scope for this ticket ;-)

**Comment by CruzMolina** [comment]
Closing as support for Quorum's `privateFor` transaction parameter was re-enabled in #1944.

support for signing private transactions within `truffle-hdwallet-provider` is still on the "To Do" list. Opening a separate ticket for it shortly.
