### ISSUE TITLE
use "truffle init" command, and get error:

### ISSUE THREAD

**Issue by Prince666** [trufflesuite/truffle#1666]
Preparing to download
× Downloading
Error: Error: Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle-box.json. Got error: unable to verify the first certificate. Please check the format of the requested resource.
    at Object.unbox (C:\Users\princ\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-box\box.js:65:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.2 (core: 5.0.2)
Node v10.15.0

**Comment by eggplantzzz** [comment]
@Prince666 I don't think this issue is specific to Truffle and rather I think it means there is something wrong with the way you have SSL configured on your computer. I'm going to look into this and if I find anything helpful I'll post it up here.

**Comment by satyamakgec** [comment]
I am also getting this error 

> Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.

But I am not getting any issues related to SSL/certificate

**Comment by eggplantzzz** [comment]
@satyamakgec What version of truffle are you using? You will need to use version of 5 or v4.1.15 if you need to keep using version 4.

**Comment by gnidan** [comment]
This is probably sorted out by now, since it was an upstream network configuration problem. Let us know if that's not the case and we'll reopen. Thanks!
