### ISSUE TITLE
Truffle for Package Management Error: Cannot find any published versions of 'ens' with the specified version range (*)

### ISSUE THREAD

**Issue by Muhammad-Altabba** [trufflesuite/truffle#1668]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Error when using `Truffle Install <PACKAGE>`

## Steps to Reproduce
Following the documentation at Truffle for Package Management: https://truffleframework.com/docs/truffle/getting-started/package-management-via-ethpm

When Trying to install a package like ENS:

`truffle install ens`

## Expected Behavior

The package is installed.

## Actual Results

The following error is shown:

    Error: Cannot find any published versions of 'ens' with the specified version range (*)
        at /usr/local/lib/node_modules/truffle/build/webpack:/~/ethpm-registry/lib/registry.js:85:1
        at \<anonymous\>
        at process._tickCallback (internal/process/next_tick.js:188:7) 
    Truffle v5.0.2 (core: 5.0.2) 
    Node v8.11.2

## Environment

* Operating System: Ubuntu 17
* Truffle version (`truffle version`): v5.0.2 (core: 5.0.2) 
* node version (`node --version`): Node v8.11.2

**Comment by gnidan** [comment]
Marking this "on hold" until we can revisit EthPM integration work in the near/mid future. Thanks!

**Comment by Muhammad-Altabba** [comment]
Actually, the problem is with `truffle install` nothing work with it. I picked ENS to open the issue with, because it is the one mentioned in the documentation https://truffleframework.com/docs/truffle/getting-started/package-management-via-ethpm.

**Comment by eggplantzzz** [comment]
@Muhammad-Altabba So `truffle install` relies on ethPM which is in kind of a strange, unknown state right now. However, I can successfully run `truffle install zeppelin` on my project. And as @gnidan mentioned, in the near/mid future we will be doing some more work to hopefully get this stuff ironed out!

**Comment by cliffoo** [comment]
Closing. See https://github.com/trufflesuite/truffle/pull/5283
