### ISSUE TITLE
Webpack example code incorrect

### ISSUE THREAD

**Issue by TrySpace** [trufflesuite/truffle#167]
I tried following these steps to get webpack to work:
https://github.com/ConsenSys/truffle/wiki/Using-Truffle-and-Webpack-(beta)

I know it's beta, but the last few steps are not clear, and not all very useful or relevant after a fresh `truffle init`.

I get errors from the import statements:
`$ truffle build
Error: Cannot find module '../stylesheets/app.scss'
`
Because the path is not correct for a clean install (`truffle init`). 
When I fix the path:

> /app/stylesheets/app.scss: Unexpected token (1:5)
>  1 | body {
>         |      ^
>   2 |   margin-left: 25%;

When I remove the imports alltogether:

> Warning: No compiled contracts found. App will be built without compiled contracts.
> Running `webpack`...
> Error: spawn webpack ENOENT
>     at exports._errnoException (util.js:953:11)

I would like a code example in its completeness, because the last few steps (especially 8) are too vague, and not working on clean install. I also don't understand the inclusion of step 6, since that path is already correct after a fresh `truffle init`.

**Comment by tcoulter** [comment]
Hi there. This code is old. Please see our [truffle boxes](http://truffleframework.com/boxes) for more info. Thanks!
