### ISSUE TITLE
Receive no accounts while using accounts-keyword in migration-script

### ISSUE THREAD

**Issue by TobiWo** [trufflesuite/truffle#1674]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I don't receive the account-addresses while using the `accounts` keyword within the `modules.export` function within a migration-script.
I actually get the name of the network which is used for deployment, in my case development since I'm using ganache-cli. So each element in the accounts-array is a letter of d e v e l o p m e n t.

## Steps to Reproduce
* in a empty folder:
`truffle init`
* edit truffle-config.js:
```
module.exports = {
    networks: {
         development: {
         host: "127.0.0.1",     
         port: 8545,  
         network_id: "*",
        }    
    },
    compilers: {
        solc: {
            version: "0.5.3",
        }
    }
}
```
* create simple migration script `2_simple_migration`:
```
var HelloWorldContract = artifacts.require("HelloWorld");
module.exports = function(deployer, accounts) {
    deployer.deploy(HelloWorldContract, {from: accounts[1]}); //using second account for deployment
};
```
* create simple contract `HelloWorld.sol`:
```
pragma solidity 0.5.3;

contract HelloWorld {

    function helloWorld(string memory _userMessage) public pure returns (string memory) {
        return _userMessage;
    }
}
```
* start ganache in terminal:
`ganache-cli`
* deploy contract to local network:
`truffle migrate`

## Expected Behavior

Contract will be deployed to network.

## Actual Results

Deployment fails:
```
Error:  *** Deployment Failed ***

"HelloWorld" -- Provided address "e" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted..

    at C:\Users\towo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-deployer\src\deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The "address" comes from the network name **development**.
So using `accounts[0]` in the migration script would result in "address" **d**.

However, using `web3.eth.getAccounts()` works as expected.

## Environment

* Operating System: Windows 10 Enterprise x64
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.0.1
* node version (`node --version`): 10.15.0
* npm version (`npm --version`): 6.5.0

**Comment by eggplantzzz** [comment]
The networks object is the second argument passed to migration functions. The third argument is the accounts. So you would do: 
```
module.exports = (deployer, networks, accounts) => {
  ...the rest of your migration...
```
See the docs for more info --> https://truffleframework.com/docs/truffle/getting-started/running-migrations#available-accounts
