### ISSUE TITLE
Error: Could not find artifacts for + path

### ISSUE THREAD

**Issue by ShabanGomaa** [trufflesuite/truffle#1684]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I have been receiving an error: "before all" hook: prepare suite:
     Error: Could not find artifacts for "contract path...." when I run truffle test
What the issue is, in broad strokes.

## Steps to Reproduce
inside my project directory:
truffle unbox pet-shop
create a contract
truffle compile
truffle migrate
create a solidity test file
truffle test

## Expected Behavior
test pass
What you expected to happen.

## Actual Results
1) "before all" hook: prepare suite
0 passing (8s)
  1 failing

       "before all" hook: prepare suite:
     Error: Could not find artifacts for

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: windows 10 64
* Ethereum client: ganache cli
* Truffle version (`truffle version`): v5.0.2
* node version (`node --version`): v10.15.0
* npm version (`npm --version`): 6.5.0

**Comment by eggplantzzz** [comment]
We will be putting out a patch release tomorrow that I think might fix this issue. Look out for v5.0.4

**Comment by pklinger** [comment]
Seems related to issue #1691 on Windows

Can you retry again @ShabanGomaa with truffle v5.0.4? It is released https://github.com/trufflesuite/truffle/releases/tag/v5.0.4

```
npm uninstall -g truffle
npm install -g truffle@5.0.4
```

**Comment by gnidan** [comment]
Looks like we fixed this? Can anyone confirm?

Closing for now, let us know if the problem persists. Thanks!
