### ISSUE TITLE
Truffle does not compile on existing project on Mac

### ISSUE THREAD

**Issue by joeyBerger** [trufflesuite/truffle#1694]
I have a solidity project I want to work on and have purchased a new Mac. I reinstalled (I think) all the necessary components, and 'truffle compile' does not seem to compile. There is no error,- just a moment of pause, and a return to the terminal path.

Usually, there is a message /compiling message but I cannot get this event to occur. I have tried deleting my build folder to force a new compilation, but this also does not work. I am in the root directory.

Thanks!

**Comment by lannocc** [comment]
I just ran into this same issue. Truffle v5.0.3, Solidity v0.5.0, Node v11.8.0 on macOS High Sierra 10.13.6.

Truffle init and help both work but compile, deploy, and test all simply hang for a few seconds then quit with no output.

**Comment by joeyBerger** [comment]
Good to know I'm not alone on this. Unfortunately, it is impossible to get any work done now...

Let me know if you find a solution- good luck.

My versions:
Truffle v5.0.3 (core: 5.0.3)
Solidity v0.5.0 (solc-js)
Node v10.15.1

**Comment by joeyBerger** [comment]
Figured out a solution.. uninstalled truffle, and installed an older version.

so 

npm uninstall -g truffle
npm install -g truffle@5.0.3

**Comment by lannocc** [comment]
Hey @joeyBerger I was able to resolve my issue. Seems I had some sort of corruption with my nodejs, probably because I had upgraded it using `n` instead of homebrew. I ultimately used homebrew to force-uninstall nodejs (ignoring dependencies) and then reinstall it. I then insured my local user had recursive ownership of /usr/local/Cellar/node and I was able to `npm -g install truffle` as my non-root user (it's recommended not to use root, and I was ending up with problems doing it with sudo). Now on Node v11.9.0 and truffle v5.0.3 is working fine.

**Comment by lannocc** [comment]
Glad to hear you're moving forward too.

**Comment by joeyBerger** [comment]
I probably have the same issue and looks like might have problems moving forward. Thanks for posting!

**Comment by RostyslavBortman** [comment]
The same issue

**Comment by sylvainKritter** [comment]
Hi, I solved on Ubuntu 18 by sudo truffle compile.

**Comment by RostyslavBortman** [comment]
Oh, thanks
And I solved it by using another version 0.5.2

Thanks for the response

вт, 5 февр. 2019 г., 15:33 Sylvain Kritter <notifications@github.com>:

**Comment by avicloudpro** [comment]
Thank you folks, This is a permission issue when installing truffle. I was able to solve it by changing the ownership of the folder to local user as suggested by @joeyBerger and reinstalling truffle. if you installed truffle using root credentials then you will have to use root previliges to execute truffle compile/migrate

**Comment by jochenonline** [comment]
Besides the effect described above (silently doing nothing) I also had the problem (after solving the first one with `sudo` / thanks to @sylvainKritter ) that truffle used an older nodejs version than nvm was set to. Finally I could solve both by installing truffle locally `npm i truffle` and use it via `npx truffle`.

**Comment by eggplantzzz** [comment]
You probably should not have to use sudo with Truffle in most cases. I expect this is an issue with how npm was installed...npm recommends using a version manager and I would guess you are getting a bunch of EACCES erros while trying to use packages and npm?
Check out the following link and see if it is helpful.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by linuxcid** [comment]
> Hi, I solved on Ubuntu 18 by **sudo truffle compile.**

Thank you for your post, It works with me also in a **MacOSx Console!**

**Comment by gnidan** [comment]
Since this is resolved and since #1813 is a better representation of the root issue, closing this in favor of that. Thanks for chiming in!
