### ISSUE TITLE
'truffle create test' command creates faulty test file

### ISSUE THREAD

**Issue by robertmagier** [trufflesuite/truffle#1696]
## Issue
Javascript test file created by truffle create test is missing definition of a contract we want to test. 
If my contract is called Test and I create tests file using command

`truffle create test Test`

then I will get template as follows:
```
contract('Test', function(accounts) {
  it("should assert true", function(done) {
    var test = Test.deployed();
    assert.isTrue(true);
    done();
  });
});
```
This will of course fail as Test contract is not defined. 
We should add this line at the beginning:

`var Test = artifacts.require('Test')`

Template should be:
```
var Test = artifacts.require('Test')
contract('Test', function(accounts) {
  it('should assert true', function(done) {
    var test = Test.deployed()
    assert.isTrue(true)
    done()
  })
})
```

## Environment

* Operating System: Windows 10 Home
* Ethereum client: Ganache 1.3.0
* Truffle v5.0.2 (core: 5.0.2)
* Solidity - 0.5.1 (solc-js)
* Node v11.6.0
* npm version (`npm --version`): 6.5.0-next.0

**Comment by gnidan** [comment]
Good find! Feel free to open a PR to change [this file](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/templates/example.js)!

**Comment by rgordon95** [comment]
Should be good to close as of latest release

**Comment by gnidan** [comment]
🎉thanks @rgordon95, closing this! @robertmagier can you confirm? Happy to re-open if need be.
