### ISSUE TITLE
Azure Geth Migration gives Invalid JSON RPC error

### ISSUE THREAD

**Issue by amankakar** [trufflesuite/truffle#1700]
---------------------------

## Issue
Azure truffle VM migrate successfully contract on truffle test network but when i migrate on geth private network its get migrated but in browser it givs invalid json rpc error

What the issue is, in broad strokes.
i want to deploy my project on Microsoft Azure Truffle Vm with GETH. it gets deployed but when i access it in browser it gives invalid json rpc error

## Steps to Reproduce

in truffle.js i configure a netwrok called localhost as follows:
`localhost:{`
      `host: "localhost",`
      `port: 8545,`
      `network_id : 1114,`
      `from:"0x620f6ba38f5cc5d9e6fbabe3a56d9d994507d66f",`
    `}`

i have set private Geth chain and run it with following command 
`geth --datadir ./amanData --networkid 1114 --rpccorsdomain "*" --syncmode "full"  --rpc --rpcport 8545  --rpcaddr "0.0.0.0" --ipcpath "~/Library/Ethereum/geth.ipc" console
`
and then i  deploy with this command:
`truffle migrate --reset --network localhost
`

## Expected Behavior

What you expected to happen.
i expect to access my project web front end in browser as I have in case of truffle test network.

## Actual Results
when i run project via npm command and try to access front end in browser it gives error of Invalid JSON RPC erro.

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client: Geth 1.8.22
* Truffle version (`truffle version`): 4.1.14
* node version (`node --version`): 8.14.0
* npm version (`npm --version`): 6.4.0

**Comment by princesinha19** [comment]
which project you are running?
First import web3 inside your code and check RPC is connected or not.

**Comment by eggplantzzz** [comment]
@amankakar Also, consider upgrading to Truffle 5. I'd be curious to know whether this still exists on the most recent version of Truffle.

**Comment by amankakar** [comment]
@princesinha19  i have made mistake in web3 providers. when i change web3 provider to `localhost:8545`
then its work fine.

**Comment by amankakar** [comment]
@eggplantzzz  thanks . i will upgrade to new version

**Comment by gnidan** [comment]
Looks like this can be closed! Thanks for raising the issue @amankakar. Let us know if you run into any other trouble.
