### ISSUE TITLE
SafeTransferFrom() failing in test 

### ISSUE THREAD

**Issue by LucasRodriguez** [trufflesuite/truffle#1717]
## Issue
I initialize a token contract and send over tokens to an address from which I try to run safeTransferFrom() which in turn returns a VM error like so: 

>      Error: Returned error: VM Exception while processing transaction: revert
>       at Object.ErrorResponse (node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
>       at node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
>       at node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
>       at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
>       at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
>       at XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
>       at XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
>       at IncomingMessage.<anonymous> (node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
>       at endReadableNT (_stream_readable.js:1094:12)
>       at process._tickCallback (internal/process/next_tick.js:63:19)

Upon debugging the Tx I found its reverting when `transferFrom()` calls `sub()` from `safemath.sol` claiming that the sender has a balance of `0` this is provably wrong, given the execution of `transferFrom()`, when run individually, works perfectly well & that calling for the balance of the holder for that token returns the correct value. 

# # Steps to Reproduce
1. Create a OCT.sol with the following text: 

```
//Comments removed for conciseness of the bug
pragma solidity ^0.5.2;

import "openzeppelin-solidity/contracts/utils/Address.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "./IOCTReceiver.sol";

contract OCT is ERC20Detailed, ERC20 {
  using Address for address;

  bytes4 private constant _OCT_RECEIVED = 0x150b7a02;

  constructor (string memory name, string memory symbol, uint8 decimals, address initialAccount, uint256 initialBalance)
  ERC20Detailed(name, symbol, decimals) public {
    _mint(initialAccount, initialBalance);
  }

  function safeTransferFrom(address from, address to, uint256 amount, bytes memory _data) public {
    super.transferFrom(from, to, amount);
    require(_checkOnOCTReceived(from, to, amount, _data));
  }
  
  function _checkOnOCTReceived(address from, address to, uint256 amount, bytes memory _data)
    internal returns (bool)
  {
    if (!to.isContract()) {
      return true;
    }

    bytes4 retval = IOCTReceiver(to).onOCTReceived(msg.sender, from, amount, _data);
    return (retval == _OCT_RECEIVED);
  }

  function mint(address account, uint256 amount) public {
    _mint(account, amount);
  }

  function burn(address account, uint256 value) public {
    super._burn(account, value);
  }


  function burnFrom(address account, uint256 value) public {
    super._burnFrom(account, value);
  }
}

```
2. Continue to initialize the following, VERY simple test in a file called 'test.js', you will need to install `mocha` or this to run.
```
require('web3');
const {BN} = require('openzeppelin-test-helpers');

const OCT = artifacts.require('OCT');
const Swap = artifacts.require('Swap');


contract('Swap & OCT', function ([_, holder1, holder2, recipient, anotherAccount]) {
    const initialSupply = new BN(100);
    const transferAmount = new BN(10);

    beforeEach(async function () {
      this.token1 = await OCT.new("OpsCoin", "OCT", 10000, holder1, initialSupply);
      this.token2 = await OCT.new("OpsCoin", "OCT", 10000, holder2, initialSupply);
    });

    describe('Atomic Swap', function () {
        describe('Deploy two uERC20 Contracts that empty their amounts into their owners accounts', function () {
            it('Return two contracts and their Supply', async function () {
                (await this.token1.totalSupply()).should.be.bignumber.equal(initialSupply);
                (await this.token2.totalSupply()).should.be.bignumber.equal(initialSupply);
            });
        });
            it('Create an Atomic Swap by running safeTransferFrom()', async function () {
                //Encode the data into a bytes var so the safeTransferFrom can pass it over to the Swap Contract
                var _data = await web3.eth.abi.encodeParameters   (  
                    ['uint256','address','uint256','address','address','uint256','address'], 
                    ['1', holder1, transferAmount.toString(), holder2, this.token1.address, transferAmount.toString(), this.token2.address]
                );
            
                var data = await web3.eth.abi.encodeParameters   (  
                    ['uint256','address','uint256','address','address','uint256','address'], 
                    ['1', holder2, transferAmount.toString(), holder1, this.token2.address, transferAmount.toString(), this.token1.address]
                );

                await this.token1.safeTransferFrom(holder1, holder2, transferAmount, _data);
                await this.token2.safeTransferFrom(holder2, holder1, transferAmount, data);
        });
    });
})
```

3. Now try running `truffle test` 

## Expected Behavior
The safe transfer from is executed  and `holder1` and `holder2` exchange their tokens

## Actual Results

VM error as stated above due to sub being called and the balance of the addresses being 0

## Environment

* Operating System: Ubuntu 18.04.1 LTS
* Truffle version (`truffle version`): v5.0.4
* node version (`node --version`): v10.15.0
* npm version (`npm --version`): npm@6.6.0

**Comment by eggplantzzz** [comment]
Hey Lucas, I haven't dug into your problem too deeply but I wonder about something...do your source files compile? I thought the open zeppelin stuff required version 4 of the Solidity compiler. You have the pragma specifying a version of 5. Is that not causing problems?

**Comment by LucasRodriguez** [comment]
Yes everything compiles, and works like a charm, I do believe I found the bug too. 

When calling the function `safeTransferFrom` from `Token1` he function is indeed called by `holder1`, how ever the subsequent functions are 100% being called by the token1 address.

Here are the steps to prove the above statements.

1. When deploying the `Token1` Smart Contract we generate 100 tokens and automatically deploy them to `holder1`

2. We then print out holder1 balance to confirm we dont have indeed recieved them with `this.token.balanceOf(holder1)` which does return 100. 

3. However the function safeTransferFrom() when called by holder1 reverts on the `safemath.sol` `sub()` function. 

4. We know that the function does have balance because we checked above, 
-When we debug the transaction, we see the sender does not have enough balance. 

5. Make sure the Tokens contract has a balance before `safeTransferFrom` is called.

When we do this the transaction goes through successfully, but nothing actually executes  because the contract does not have the permission to send tokens on behalf of the address. 

Now **surely**  this cannot be expected behavior?

**Comment by eggplantzzz** [comment]
Is your whole project's code available somewhere so I can check it out? What happens when you check the amount directly before the transfer in the same context?

**Comment by LucasRodriguez** [comment]
So apparently this **is** expected behaviour. Which is unfortunate, but makes sense in the ERC20 implementation we get rid of token ID which is what works around the issue in the ERC721 implementation in any case this would be more of a solidity problem than a truffle one so I will close the issue.
