### ISSUE TITLE
public mapping getter behaves unexpectedly in truffle test 

### ISSUE THREAD

**Issue by ryokomy** [trufflesuite/truffle#1722]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I wrote a test which reads public mapping.  
But it failed with error `xx is not a function`.  
I confirmed that there was the function in ABI, and I could access the mapping from `truffle console`.
This happens only when I use `truffle test`.
I also confirmed that I could access a public address variable.

## Steps to Reproduce

- solidity file
``` 
struct UserInfo {
    uint16 class;
    uint256 balance;
    bool exists;
}
mapping(uint256 => UserInfo) userIdToUserInfo;
```

- test javascript
```
console.log(await contract.userIdToClassId(1))
```

## Expected Behavior
return UserInfo

## Actual Results
fails with `TypeError:  contract.userIdToUserInfo is not a function`

## Environment

* Operating System: macOS High Sierra Version 10.13.6
* Ethereum client: Ganache Version 1.1.0
* Truffle version (`truffle version`): Truffle v5.0.4 (core: 5.0.4), Solidity - 0.5.4 (solc-js)
* node version (`node --version`): v10.11.0
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
Hey @ryokomy, if you want to have those variables available like this you either need to declare them "public" or create getters for them in the contract. Let me know how it goes.

**Comment by gnidan** [comment]
@ryokomy have you figured this out? I'm closing this for issue maintenance, but feel free to comment and we'll reopen. Thanks!
