### ISSUE TITLE
uint[n][] to vector of BN

### ISSUE THREAD

**Issue by asiniscalchi** [trufflesuite/truffle#1723]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle is not able to convert a vector uint[n][] (with n &#8712; &#8469;) in a vector of BN.

## Steps to Reproduce
```solidity
pragma solidity ^0.5.0;

contract MyContract {
    uint256[2][] private _value; 

    function getValue() external view returns (uint256[2][] memory) {
        return _value;
    }

    function setValue(uint256[2][] memory value) public {
        _value = value;
    }
}
```
Following the steps to reproduce the error
```javascript
await myContract.setValue([[3,0],[1,0]]);
const value = await myContract.getValue();
```

## Expected Behavior

I expect a BN[n][] in javascript.

## Actual Results

**Error: Error: [number-to-bn] while converting number ["3","0"] to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "3,0"**

## Environment

* Operating System: Ubuntu 18.04
* Truffle version: v5.0.4
* node version: v8.10.0
* npm version: 3.5.2

**Comment by gnidan** [comment]
Adding this to our backlog to look into. Hopefully we'll get this sorted out for you!

BTW did you try this using `pragma experimental ABIEncoderV2`? Not sure if it will make a difference, but it might. Thanks!
