### ISSUE TITLE
truffle compile not working

### ISSUE THREAD

**Issue by AchalaSB** [trufflesuite/truffle#1727]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle compile` is not building build file for my solidity contract

## Steps to Reproduce

When I run `truffle init` following files got created.

![screenshot from 2019-02-19 14-43-21](https://user-images.githubusercontent.com/41888986/53003457-fa22e980-3454-11e9-98e7-4523b966d459.png)

Then I added helloworld.sol contract to this. But when I do `truffle compile` , build file or json file for my contract is not creating
`truffle compile` returns back without showing any errors as well.
Even `truffle test` is not working

## Expected Behavior

`truffle compile` works properly then `truffle migrate` also works. 

## Actual Results

![screenshot from 2019-02-19 14-51-07](https://user-images.githubusercontent.com/41888986/53003824-db712280-3455-11e9-9f41-e7f510feb6bd.png)

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): Truffle v5.0.4 (core: 5.0.4)
* node version (`node --version`): 11.10.0
* npm version (`npm --version`): 6.7.0

**Comment by AchalaSB** [comment]
Closing this issue since it is fixed for version `Truffle v5.0.0-next.26 `

**Comment by eggplantzzz** [comment]
This is a bit puzzling, I don't seem to be able to reproduce your problem. I think the next release we do will include a patch for truffle compile error reporting. Currently it swallows errors in some cases so I'd be curious to see what happens if you were to try this again after that release.

**Comment by eggplantzzz** [comment]
I'm going to re-open this just to see if anyone else is experiencing this issue, anyone?

**Comment by ewust** [comment]
Also seeing this problem:
```
Truffle v5.0.4 (core: 5.0.4)
Solidity v0.5.0 (solc-js)
Node v10.15.1
```

**Comment by sulenn** [comment]
The same problem：

```
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v10.15.1
```

**Comment by yqsy** [comment]
The same problem:

`
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v10.8.0
`

**Comment by omid04** [comment]
the same problem 
Truffle v5.0.5
solidity 0.5.4
Node v11.10.0

**Comment by andig85** [comment]
Same problem here

Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v11.10.0

If I run 'truffle compile' as root user, it works.

**Comment by eggplantzzz** [comment]
We should have a patch release soon to fix the error swallowing. If you are experiencing issues base on what kind of user you are logged in as, then you should probably ensure you have npm and truffle installed properly with adequate permissions. I see a lot of people doing things like `sudo npm ...`. You probably shouldn't be doing this. See npm's  article --> https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by AchalaSB** [comment]
@eggplantzzz You are right. Node has to install using `NVM` and people please use `npm install -g truffle` don't use `sudo npm install`
The latest version `truffle v5.0.5` is working fine for all the specific version of solidity

**Comment by muzakparov** [comment]
if you install with `sudo npm ...` then:
```
sudo truffle develop
```
should make it work

**Comment by equinoxapp** [comment]
> if you installed with `sudo npm ...` then:
> 
> ```
> sudo truffle develop
> ```
> should make it work

It's working

**Comment by eggplantzzz** [comment]
Update: I think as of Truffle v5.0.8 you should not have these errors even if you did install Truffle with `sudo`. Closing this for maintenance but let us know if you have problems.

**Comment by hmarcelodn** [comment]
Having v5.1.28 and running truffle test or truffle develop does nothing

**Comment by SalahAdDin** [comment]
I have the same problem with develop and it does it work.

**Comment by kevinmachstudio** [comment]
truffle hangs when I do `truffle test`

truffle version
```
Truffle v5.1.41 (core: 5.1.41)
Solidity - 0.6.6 (solc-js)
Node v14.7.0
Web3.js v1.2.1
```

**Comment by SalahAdDin** [comment]
@kevinmachstudio As far as i can understand, `truffle` is not totally compatible with the last node version.

**Comment by huwentao1** [comment]
the same problem :v5.1.50

```
mac ~/hwt/constact_test/1030/demo3 % ls     
LICENSE			client			contracts		migrations		test			truffle-config.js
mac ~/hwt/constact_test/1030/demo3 % truffle version
Truffle v5.1.50 (core: 5.1.50)
Solidity v0.5.16 (solc-js)
Node v10.16.3
Web3.js v1.2.9
mac ~/hwt/constact_test/1030/demo3 % truffle compile

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

mac ~/hwt/constact_test/1030/demo3 % ls
LICENSE			client			contracts		migrations		test			truffle-config.js
mac ~/hwt/constact_test/1030/demo3 % 
```

**Comment by anhmt90** [comment]
I got this issue when I enclose at least 1 character in the name of the project directory by square brackets e.g. `token[s]` as the name of the project directory, in which I use `truffle init`

**Comment by Junoburger** [comment]
@anhmt90 Thank you! That solved it. One of the directory names where the project lives had a bracketed value.

**Comment by arslan-prism** [comment]
> Same problem here
> 
> Truffle v5.0.5 (core: 5.0.5)
> Solidity v0.5.0 (solc-js)
> Node v11.10.0
> 
> If I run 'truffle compile' as root user, it works.

Worked for me. Thanks.

**Comment by Brag2gr8** [comment]
Sudo truffle compile actually solved this..
Thanks
