### ISSUE TITLE
Support Serpent Contracts

### ISSUE THREAD

**Issue by tgonzales** [trufflesuite/truffle#173]
/// Registrar.se

data info[][](title[100], titleLength)

def setParam(key, id, title:str):
  save(self.info[key][id].title[0],title,chars=len(title))
  self.info[key][id].titleLength = len(title)
  return(1)

def getParam(key, id):
  length=self.info[key][id].titleLength
  return( load(self.info[key][id].title[0],chars=length):str )

///// app.js
var register = Registrar.deployed();

/// browser console

> Uncaught ReferenceError: Registrar is not defined(…)

**Comment by tcoulter** [comment]
Serpent is not currently supported by Truffle. Things that we'd need in order for it to be:

1. A way to generate ABI's for serpent code, if that's possible (I don't know enough about serpent)
1. A serpent compiler in Javascript. 

If both of those exist, I would be happy to support it.

**Comment by joeykrug** [comment]
1.  ```serpent mk_full_signature``` does this, for external contracts ```serpent mk_signature``` makes a simpler signature

2. Dunno about this

**Comment by cgewecke** [comment]
@tgonzales Closing this for house-keeping. Serpent has been [deprecated](https://twitter.com/VitalikButerin/status/886400133667201024). Thanks for opening.
