### ISSUE TITLE
default sender set for contract methods, but not for sendTransaction()

### ISSUE THREAD

**Issue by d10r** [trufflesuite/truffle#1735]
## Issue

Truffle isn't consistent about setting the default sender ("from" field). This degrades the usability of the truffle console.

When sending a _simple_ transaction, it's not set:
```
truffle(tau1)> web3.eth.sendTransaction({ to: "0x30B125d5Fc58c1b8E3cCB2F1C71a1Cc847f024eE", value: 2} )
/home/didi/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/cli.bundled.js:372117
            throw new Error('The send transactions "from" field must be defined!');
...
```

... while it is for contract invocations:
```
truffle(tau1)> sa.closeStreem(1)
{ tx:
   '0x35e059248567103a93aeebe2a1deb9368c23fd23e9059f29b0b9f0f7f437c7c9',
  receipt:
...
```

In `truffle-config.js`, it claims:
```
      // from: <address>,        // Account to send txs from (default: accounts[0])
```

According to the outlined behaviour, this claim is only partially correct.  

## Expectation

I would expect `web3.eth.sendTransaction()` to use the default account if none is set explicitly.  
If may or may not be achieved by setting `web3.eth.defaultAccount` accordingly (is set to `null` by default).

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client: Parity 2.1
* Node: v10.14.2
* Truffle: v5.0.0
* npm: 6.4.1

**Comment by eggplantzzz** [comment]
Thanks for raising this but I don't think we want to set a default `from` when you are accessing web3 directly. We don't really want to mess with web3 defaults and you should assume it has the same API as when used outside of Truffle.  The default `from` that you configure in the Truffle config pertains only to transactions sent from Truffle contracts.

**Comment by d10r** [comment]
I understand.  

> The default `from` that you configure in the Truffle config pertains only to transactions sent from Truffle contracts.

Then I suggest to change the relevant lines in default `truffle-config.js` from 
```
// from: <address>,        // Account to send txs from (default: accounts[0])
```
to
```
// from: <address>,        // Account to send contract txs from (default: accounts[0])
```

I always considered the truffle console as a kind of superset of the web3 console. You seem to view it more as a kind of parallel thing which happens to also expose the web3 API.  
It's good to not mess with the defaults, but it's unfortunate that the defaults for sender are inconsistent (`account[0]` for truffle contract txs, `null` for web3 txs).  
Given the name and associated comment of the config item, I perceived this as a bug. But I don't know if my perception is representative for other devs.  

At the moment I don't have a concrete proposal how this could be improved further in a reasonable way, but still wish for it.

**Comment by eggplantzzz** [comment]
I understand, I'll bring it up and have a chat with some of the other Truffle developers and see what they have to say.

I'm definitely not opposed to changing the comment wording. Would you be interested in putting in a PR for it?

**Comment by d10r** [comment]
Thx.

> Would you be interested in putting in a PR for it?
I'd do so if I knew where the template file is. Couldn't find it with github's search.

**Comment by eggplantzzz** [comment]
Hey again @d10r, the repo related to what gets unboxed with `truffle init` can be found here --> https://github.com/trufflesuite/truffle-init-default.

**Comment by gnidan** [comment]
@d10r still interested in opening that PR? Doing issue maintenance and wondering what the status is here. Thanks!

**Comment by elenadimitrova** [comment]
In addition to the console, this is valid for instantiating contracts via `@truffle/contract`, e.g.
```
const TruffleContract = require("@truffle/contract");
const WalletContract = require("../build-legacy/v1.3.0/Wallet.json");
const Wallet = TruffleContract(WalletContract);

await Wallet.setProvider(web3.currentProvider);
const wallet = await Wallet.new();
```

Explicitly setting `web3.eth.defaultAccount = accounts[0];` isn't working for me.

**Comment by pguardiario** [comment]
Bump. Looking for a way to change account in tests

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. @elenadimitrova your comment seems to be a separate issue, feel free to open one!
