### ISSUE TITLE
truffle-hdwallet-provider error

### ISSUE THREAD

**Issue by iszhangli** [trufflesuite/truffle#1746]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
code:
```
const Web3 = require('web3');
const {interface, bytecode} = require('./compile');
const HDWalletProvider = require('truffle-hdwallet-provider');
const mnemonic = "salmon ***"; // 12 word mnemonic
const provider = new HDWalletProvider(mnemonic,
    "https://rinkeby.infura.io/v3/***");
const web3 = new Web3(provider);

deploy = async ()=>{
     const accounts = await web3.eth.getAccounts();
     console.log(accounts[0]);
}
deploy();
```

## Issue

```
node deploy.js
(node:13036) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at GetAccountsMethod.afterExecution (H:\\SmartContracts\Index\node_modules\web3-core-method\dist\web3-core-metho
d.cjs.js:762:23)
    at GetAccountsMethod._callee$ (H:\SmartContracts\Index\node_modules\web3-core-method\dist\web3-core-method.cjs.
js:457:39)
...
...
...
TypeError: e is not a function
    at H:\SmartContracts\Index\node_modules\truffle-hdwallet-provider\dist\index.js:15:544968
    at H:\SmartContracts\Index\node_modules\truffle-hdwallet-provider\dist\index.js:1:150953
    at d (H:\SmartContracts\Index\node_modules\truffle-hdwallet-provider\dist\index.js:1:215490)
    at H:\SmartContracts\Index\node_modules\truffle-hdwallet-provider\dist\index.js:1:215543

```

**Comment by chrischip** [comment]
I also have a lot of problem with setting the providers. Have you try to match your Web3 version to Truffle's one? I can use successfully with http provider and on the rinekby. The only problem i got is http provider doesn't support subscription and if I use WebsocketProvider for Rinekby there is a SSL handshaking problem which this version of web3, really struggling with the right combination of different versions.

**Comment by CruzMolina** [comment]
@chrischip currently we only guarantee compatibility betw truffle & web3 up to 1.0.0-beta.37. There were breaking changes implemented in beta.38 and up that we are currently trying to resolve.

**Comment by CruzMolina** [comment]
Hey @iszhangli, if you have a repo you can link or share, it would be greatly appreciated 🙏

**Comment by CruzMolina** [comment]
@iszhangli , hopefully you've been able to figure this out, but perhaps setting the provider will make things work.

```const Web3 = require('web3');
const {interface, bytecode} = require('./compile');
const HDWalletProvider = require('truffle-hdwallet-provider');
const mnemonic = "salmon ***"; // 12 word mnemonic
const provider = new HDWalletProvider(mnemonic,
    "https://rinkeby.infura.io/v3/***");
const web3 = new Web3(provider);
web3.setProvider(provider); // <==============

deploy = async ()=>{
     const accounts = await web3.eth.getAccounts();
     console.log(accounts[0]);
}
deploy();
```

**Comment by adityagupta29** [comment]
Use a stable version of  truffle-hdwallet-provider **@truffle/hdwallet-provider@1.5.1** 
( You can reinstall it by typing the cmd  _npm i @truffle/hdwallet-provider@1.5.1_ )

**Comment by gtandes** [comment]
> Use a stable version of truffle-hdwallet-provider **@truffle/hdwallet-provider@1.5.1** ( You can reinstall it by typing the cmd _npm i @truffle/hdwallet-provider@1.5.1_ )

You are a mental health saver. Thank you sir.

**Comment by adityagupta29** [comment]
> > Use a stable version of truffle-hdwallet-provider **@truffle/hdwallet-provider@1.5.1** ( You can reinstall it by typing the cmd _npm i @truffle/hdwallet-provider@1.5.1_ )
> 
> You are a mental health saver. Thank you sir.
Well, I don't know much about contributing, pull requests & more. If you can do a favor for me. Suggest to me how can I learn to contribute to different projects.

**Comment by anjolagithub** [comment]
Still doesnt solve my problem
