### ISSUE TITLE
where is solc download and install to?  which solc be used? Suggest print detail info about solc using

### ISSUE THREAD

**Issue by code-brewer** [trufflesuite/truffle#1747]
After i specify the solc version in the compiler session of truffle.js, it do download, 
but i have no idea about:
1) where the solc installed to ?
2) not sure which solc (if i have install multiple version solc) that truffle used while compiling.

**Comment by eggplantzzz** [comment]
Currently the compiler is downloaded and saved to a cache directory in Truffle. When you specify a compiler it checks to see if it is cached first, and if so it uses that.

More precisely you can look in `../pathToTruffleInstall/../node_modules/truffle/node_modules/.cache/truffle/`. This is where all the compiler files get cached.

In addition, currently Truffle only supports compiling with a single version of the Solidity compiler out of the box. Technically, you could custom configure multiple versions of the Solidity compiler using the "external" compile settings if you want to do some fancy footwork. See the [docs](https://truffleframework.com/docs/truffle/reference/configuration#external-compilers) for more info.

**Comment by eggplantzzz** [comment]
UPDATE: With the release of Truffle v5.0.8 the compiler cache directory has been changed to `/<homeDirectory>/.config/truffle/compilers`. Another note, during compilation as of Truffle v5.0.6 (I believe) the compilers used are logged.

**Comment by eggplantzzz** [comment]
Closing this for maintenance.
