### ISSUE TITLE
Is it possible to configure RPC connector so that it communicates with Ethereum Studio sandbox?

### ISSUE THREAD

**Issue by zduniak** [trufflesuite/truffle#176]
In Ethereum Studio (www.ether.camp) RPC address looks like this:
https://zduniak.by.ether.camp:8555/sandbox/78d7ffca53
From what I see there is no way to configure rpc in truffle.js so that the HttpProvider has '/sandbox/78d7ffca53' sufix in the url (I can specify only host and port, not the whole path)

Is there a way to configure truffle with this sort of sufixes in the RPC url ?

**Comment by tcoulter** [comment]
In the newest Truffle (not yet released), you  can set the provider by doing something like this in your `truffle.js` file:

```
var Web3 = require("web3");
module.exports = {
  provider: new Web3.providers.HttpProvider("...")
}
```

Note that this is a beta feature and may not work as intended.

**Comment by dip239** [comment]
Is it possible to use the feature right now? As patched or in development truffle version?

**Comment by sponnet** [comment]
I got this to work in the latest dev version of Truffle ( `sudo npm install -g https://github.com/ConsenSys/truffle`) using a eth-lightwallet + hooked-web3-provider.
This allows you to create and sign the transaction locally - and use any RPC-enabled Ethereum node to send the transaction to the network.

I first created a wallet locally using eth-lightwallet and serialized it to a file `wallet.json`.

Then I modified my truffle.js as follows :

```
  var lightwallet = require('eth-lightwallet');
  var HookedWeb3Provider = require("hooked-web3-provider");

  var contents = JSON.stringify(require('./wallet.json'));
  var global_keystore = lightwallet.keystore.deserialize(contents);

  global_keystore.passwordProvider = function(callback) {
    console.log('PWD requested...');
    callback(null, 'test');
  };

  // get the first account in this wallet
  var account = global_keystore.getAddresses()[0];
  console.log('Main account is ', account);

  // create the provider
  var provider = new HookedWeb3Provider({
    host: 'http://1.2.3.4:8545',
    transaction_signer: global_keystore
  });

  module.exports = {
    build: {
      "index.html": "index.html",
      "app.js": [
        "javascripts/app.js"
      ],
      "app.css": [
        "stylesheets/app.css"
      ],
      "images/": "images/"
    },
    verbose: true,
    rpc: {
      provider: provider,
      verbose: true,
      from: account
    }
  }
```

In addition to what @tcoulter said, note that the `provider` and `account` properties need to be inside the `rpc` configuration tag.

**Comment by tcoulter** [comment]
Closing for housekeeping. Please open a new ticket if you have anymore issues. Thanks!
