### ISSUE TITLE
Can't connect to network using Metamask

### ISSUE THREAD

**Issue by jgege** [trufflesuite/truffle#1761]
## Issue
Metamask only accepts a few white listed network ids as valid.
I've already reported the issue to them but I'm not sure if this should be fixed by them, or the default port set by the truffle develop command changed.

See the issue here:
https://github.com/MetaMask/metamask-extension/issues/6211

**Comment by CruzMolina** [comment]
Thanks for raising this issue @jgege !

Will take a look and see what can be done on our end.

**Comment by CruzMolina** [comment]
Hey @jgege , got a fix for this on our end (#1773).

Thanks again for bringing this up, hoping to have this revolved shortly 🤞

**Comment by jgege** [comment]
Thank you for quickly coming up with a solution :)

**Comment by CruzMolina** [comment]
Updated prior comment to reflect the new specific PR for this. #1773 should still resolve any compatibility issues moving forward.

**Comment by CruzMolina** [comment]
Closing this per #1775 .

Thanks again for reporting @jgege , if this doesn't go out for release tomorrow, it should be out by middle of next week. 🍻

**Comment by gnidan** [comment]
This is released in v5.0.6. Let us know if causes any more trouble! Thanks!
