### ISSUE TITLE
"Migrations" received: nonce too low -- when using Infura

### ISSUE THREAD

**Issue by kipliklotrika** [trufflesuite/truffle#1762]
## Issue

Unable to deploy contracts using HDWalletProvider with Infura.

## Steps to Reproduce

Just empty project with provided config for Rinkeby network using HDWalletProvider.
- Setup project with:
```
npm init
npm install truffle
npm install truffle-hdwallet-provider
./node_modules/.bin/truffle init
```
Add mnemonic and Infura key to config and add following to the network section in truffle-config.js:
```
   rinkeby: {
      provider: () => new HDWalletProvider(mnemonic, `https://rinkeby.infura.io/v3/YOUR_KEY`),
      network_id: 4,
      websockets: true,
      skipDryRun: true,
      confirmations: 2,
    },
```

## Expected Behavior

Deploy contract; run migration without errors.

## Actual Results

Migrations fails with following:

```
~/tmp/truffle-test$ ./node_modules/.bin/truffle migrate --network rinkeby 
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts

⚠️  Important ⚠️
If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.


Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 6997346


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error:  *** Deployment Failed ***

"Migrations" received: nonce too low.
   * This error is common when Infura is under heavy network load.
   * Try: setting the 'confirmations' key in your network config
          to wait for several block confirmations between each deployment.

    at ./node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
Truffle v5.0.5 (core: 5.0.5)
Node v9.10.1
```

## Environment

* Operating System: macOS 10.14.2
* Ethereum client:
* Truffle version (`truffle version`): 5.0.5
* node version (`node --version`): 9.10.1
* npm version (`npm --version`): 5.6.0

**Comment by jamesmorgan** [comment]
I've noticed this, a day or so ago it worked fine https://community.infura.io/t/problems-using-rinkeby/353

**Comment by CruzMolina** [comment]
Hmm, just tried to reproduce the error using @kipliklotrika's steps and was able to successfully migrate twice. 🤷‍♂️ 

Keeping this open just in case for now.

**Comment by kipliklotrika** [comment]
Same here. It seems that it works now which leads me to conclusion that the problem is on Infura side. Too bad I din't create more debug logs.

**Comment by jamesmorgan** [comment]
It works fine today as well, guess it was an Infura issue

**Comment by CruzMolina** [comment]
Thanks guys!

Closing issue.
