### ISSUE TITLE
Ganache accounts ether amounts not refreshed after subsequent truffle test calls

### ISSUE THREAD

**Issue by isaacsultan** [trufflesuite/truffle#1769]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When `ganache-cli` and `truffle test` used: (sorry not sure which repo to file this in)

I've noticed that when sending an amount of ether on the `development` blockchain from one account to another, on the next `truffle test` calls, the account balances are not restored to 100 ether, but maintain the amount from the previous test. 

## Steps to Reproduce

Pushed up the [repo](https://github.com/isaacsultan/workshop/tree/master) as seems like an important issue:

## Expected Behavior

We should expect the [`console.log`] (https://github.com/isaacsultan/workshop/blob/53332190fc69c67b149414ef2449584010170d63/test/Loan.test.js#L90) to be `99895717520000000000` for each separate call of truffle test.

## Actual Results

```
UNKNOWN:workshop isaacsultan$ truffle test
Using network 'development'.

Compiling ./contracts/Loan.sol...
Compiling ./contracts/mocks/ERC20Mock.sol...

Compilation warnings encountered:

/Users/isaacsultan/PartialF-Isaac/workshop/contracts/Loan.sol:73:5: Warning: Function state mutability can be restricted to view
    function isCollateralized
    ^ (Relevant source part starts here and spans across multiple lines).



  Contract: Loan
    #createLoan
      ✓ should revert if not fully collateralized
      ✓ should revert if the collateral address is unregistered
      ✓ should revert if there is not enough ether to send to the user
      loan is funded with ether
99895717520000000000
        ✓ should revert if the user has an outstanding loan (101ms)


  4 passing (2s)

UNKNOWN:workshop isaacsultan$ truffle test
Using network 'development'.

Compiling ./contracts/Loan.sol...
Compiling ./contracts/mocks/ERC20Mock.sol...

Compilation warnings encountered:

/Users/isaacsultan/PartialF-Isaac/workshop/contracts/Loan.sol:73:5: Warning: Function state mutability can be restricted to view
    function isCollateralized
    ^ (Relevant source part starts here and spans across multiple lines).



  Contract: Loan
    #createLoan
      ✓ should revert if not fully collateralized
      ✓ should revert if the collateral address is unregistered
      ✓ should revert if there is not enough ether to send to the user
      loan is funded with ether
69791435040000000000
        ✓ should revert if the user has an outstanding loan (73ms)


  4 passing (2s)

UNKNOWN:workshop isaacsultan$ truffle test
Using network 'development'.

Compiling ./contracts/Loan.sol...
Compiling ./contracts/mocks/ERC20Mock.sol...

Compilation warnings encountered:

/Users/isaacsultan/PartialF-Isaac/workshop/contracts/Loan.sol:73:5: Warning: Function state mutability can be restricted to view
    function isCollateralized
    ^ (Relevant source part starts here and spans across multiple lines).



  Contract: Loan
    #createLoan
      ✓ should revert if not fully collateralized
      ✓ should revert if the collateral address is unregistered
      ✓ should revert if there is not enough ether to send to the user
      loan is funded with ether
39687152560000000000
        ✓ should revert if the user has an outstanding loan (76ms)
```

## Environment

* Operating System: 10.14 
* Truffle version (`truffle version`): v5.0.5
* node version (`node --version`): v10.14.2
* npm version (`npm --version`): 6.4.1
* ganache-cli: Ganache CLI v6.3.0 (ganache-core: 2.4.0)

**Comment by CruzMolina** [comment]
Hey @isaacsultan !

Are you running `ganache-cli` in a separate window while running these tests?

If you use the default `test` network (spins up when no networks are defined in your project's `truffle-config.js`), each round of tests should use a clean chain slate.

Otherwise, with `ganache-cli` running separately in the background somewhere, the evm state will be saved and re-used by each test run.

**Comment by isaacsultan** [comment]
Hey @CruzMolina , thanks for getting back to me so quickly! The default `test` network is being use, as no networks are defined in my config.

However, I am running `ganache-cli` in a separate window. What would the alternative be, in order to have a clean chain state?

**Comment by CruzMolina** [comment]
Oh! Well if you're using the default `test` network, no need to run `ganache-cli` separately. Truffle will/should spin up `ganache-cli` as a background/child process on every `truffle test` run (and terminate it after the tests are done running).

In your situation, truffle must be connecting to the `development` chain running separately rather than starting up its own internally.

**Comment by CruzMolina** [comment]
@isaacsultan realized I didn't directly answer your question 😂 .

To have a clean chain state on each `truffle test` run, don't run `ganache-cli` separately and have truffle use the default `test` network (no networks defined in the config).

**Comment by isaacsultan** [comment]
@CruzMolina Thank you!
