### ISSUE TITLE
truffle migrate / truffle obtain behind (corporate) proxy

### ISSUE THREAD

**Issue by imbenwolf** [trufflesuite/truffle#1803]
## Issue

Truffle cannot fetch solc from solc-bin behind a proxy even when setting HTTP_PROXY and HTTPS_PROXY env variables.

I propose to:
- add proxy option inside truffle-config OR
- add --proxy as option when running truffle in general OR
- add --proxy as option when running truffle command (migrate/compile/obtain) OR
- acknowledge HTTP_PROXY and HTTPS_PROXY env variables

## Steps to Reproduce

1. Connect to a network behind proxy
2. Change solc version inside truffle-config.js to a non-default version (e.g 0.4.24 on truffle v5)
3.1 Execute truffle migrate/compile --> error
3.2 Execute truffle obtain --solc=<version> (e.g 0.4.24) --> no error but does not download

## Expected Behavior

solc is downloaded and migrations are executed with correct version

## Actual Results

command fails

## Environment

* Operating System: Windows 10
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.0.6
* node version (`node --version`): 10.15.2
* npm version (`npm --version`): 6.4.1

**Comment by gnidan** [comment]
Definitely we should support that! Will look into fixing this. Thanks for raising the issue!

**Comment by pranav-deshpande** [comment]
Any update on this?

**Comment by h3nk42** [comment]
Is there any way to use Truffle behind a corporate proxy right now?

**Comment by eggplantzzz** [comment]
@gnidan Any thoughts as to whether this might be something we can do anything about or if there is a workaround related to the network configuration perhaps?

**Comment by gnidan** [comment]
How does this work for Node.js in other projects? Shouldn't Node just respect the network configuration? Any insight here would be helpful!

**Comment by haltman-at** [comment]
Closing for issue maintenance.  Please let us know if there's still a problem and we can reopen.

**Comment by kigawas** [comment]
> Closing for issue maintenance. Please let us know if there's still a problem and we can reopen.

This problem still happens

**Comment by Jason5Lee** [comment]
Please fix it.

**Comment by davidmurdoch** [comment]
Closing this one and tracking this issue over at https://github.com/trufflesuite/truffle/issues/4016
