### ISSUE TITLE
Truffle unbox tells me my box doesn't exist instead of telling me what's wrong with it

### ISSUE THREAD

**Issue by sarbogast** [trufflesuite/truffle#1816]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm trying to create a Truffle 5 box for a course I'm giving on Udemy, and truffle keeps telling me the box doesn't exist, even though it does, but it's just probably not compatible with the format Truffle expects, but it doesn't tell me what's wrong in it either.

## Steps to Reproduce

```
truffle unbox chainskills/chainskills-box-truffle5
```

## Expected Behavior

The box to be unboxed, or Truffle to let me know why it's not a correct box instead of telling me it doesn't exist.

Or if you don't want to mix that up with truffle unbox, maybe there should be a `truffle validate-box` command that checks the format of a box and tells me exactly what's wrong with it using the same logic as the one built into `truffle unbox`. Because for now, by just comparing my box with the truffle-init box for example, I don't see what's wrong.

## Actual Results

```
$ truffle unbox chainskills/chainskills-box-truffle5

✔ Preparing to download
✖ Downloading
Error: Error: Error: Truffle Box at URL https://github.com/chainskills/chainskills-box-truffle5 doesn't exist. If you believe this is an error, please contact Truffle support.
    at Object.unbox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/box.js:65:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.8 (core: 5.0.8)
Node v10.15.0
```

And I tried adding truffle.js in there as suggested in another issue, even though Truffle 5 should not need it anymore, and truffle-init box doesn't have it, but it didn't solve my issue.

## Environment

* Operating System: MacOS 10.14.3
* Truffle version (`truffle version`): 5.0.8
* node version (`node --version`): 10.15.0
* npm version (`npm --version`): 6.4.1

**Comment by sarbogast** [comment]
Nevermind, the project was private so it really didn't exist. I still wish truffle would have let me know about that, but I found the problem and it works now.

**Comment by PeaceHears** [comment]
What is the solution of this problem? I am wondering so much... :)

**Comment by MadavaramRamesh** [comment]
@sarbogast , i am also facing the same error. Could you share me what is the solution for this?
