### ISSUE TITLE
Error better when compile fails due to wrong version

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#1818]
## Issue
A specifically encountered error:

>openzeppelin-solidity/contracts/MaskedContract.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.25+commit.59dbf8f1.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.5.0;
^---------------------^
Compilation failed. See above.
Truffle v5.0.7 (core: 5.0.7)
Node v9.3.0

## Steps to Reproduce
Have a (possibly old) configuration setting that includes the following, in the config file:
```
  compilers: {
    solc: {
      version: "^0.4.22"
    }
  },
```
and have a smart contract which uses a `pragma solidity ^0.5.0`.
Note that the "current compiler is 0.4.25" being different from the config "0.4.22" might be slightly confusing in the error message, but valid.

## Expected Behavior
An error message that gets me closer to fixing the problem, maybe including a sentence like:
"Your truffle config specifies solc version ^0.4.22. See https://truffleframework.com/docs/truffle/reference/configuration#compiler-configuration for more information about how to specify a compiler version."
This would appear when Truffle catches an error with "Source file requires different compiler version," in addition to the existing text.  The first new sentence would only appear if a compiler version was actually specified in the config.

## Environment

* Operating System: Windows 10 Pro
* Ethereum client: N/A
* Truffle version (`truffle version`): 5.0.7
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
Looks like our very own @CruzMolina has updated the output! Thanks for all the good suggestions @wbt.
