### ISSUE TITLE
Compiling a contract throws an error

### ISSUE THREAD

**Issue by saurabmarjara** [trufflesuite/truffle#1823]
## Issue

I typed the command "truffle compile" and instead of compiling my contract, it gave the following error: 

C:\Users\Saurab Marjara\AppData\Roaming\npm\node_modules\truffle\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret

SyntaxError: Invalid regular expression: /C:\Users\Saurab Marjara\AppData\Roaming\npm\node_modules\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at Object.<anonymous> (C:\Users\Saurab Marjara\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\cli.js:93:1)
    at cb (util.js:1085:39)
    at callbackifyOnRejected (util.js:1063:10)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Steps to Reproduce

Just try to compile any contract with the truffle compile command, and this error is thrown.

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache
* Truffle version (`truffle version`): 5.0.6
* node version (`node --version`): 8.10.0
* npm version (`npm --version`): 5.6.0

**Comment by CruzMolina** [comment]
Hey @saurabmarjara !

Closing for now, as I believe this issue is fixed as of v5.0.8. Please upgrade and let us know if this is still a problem! Will be happy to re-open the issue 😄
