### ISSUE TITLE
 TypeError: Data location must be "memory" for return parameter in function, but none was given.

### ISSUE THREAD

**Issue by NNAF98** [trufflesuite/truffle#1827]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
yes
---------------------------

## Issue

compilation failed

## Steps to Reproduce
go to the contract repo
truffle develop
migrate
## Expected Behavior

successful compiled and migration of my contract

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
![erreur-migrate](https://user-images.githubusercontent.com/45701687/54480532-e0917980-4829-11e9-96f0-e3e1bc5dc16e.png)

## Environment

* Operating System: windows 10
* Ethereum client: ganache-cli v1.3.1
* Truffle version (`truffle version`): v5.0.5
* node version (`node --version`): v10.15.1
* npm version (`npm --version`): v6.1.4

**Comment by CruzMolina** [comment]
Hey @NNAF98!

It looks like you either need to update your contracts to be solidity 0.5.0 compatible or use the new Bring Your Own Compiler feature by updating your `truffle-config.js` file like so:

```
module.exports = {
  /* ... rest of config */

  compilers: {
    solc: {
      version: "^0.4.17" // replace w/ the solc version you need
    }
  }
}
```

**Comment by gnidan** [comment]
Closing this for issue maintenance, since it seems like there isn't a bug or anything. Hopefully @CruzMolina's instructions are helpful. Let us know if you're still running into trouble and we'll be happy to re-open. Thanks!
