### ISSUE TITLE
undocumented flag migrate --to

### ISSUE THREAD

**Issue by Mischi** [trufflesuite/truffle#1836]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I want to run a migration up to  a specific migration. Let's say I have 3 migration files and only want to run the first. I can do it by specifying `migrate --to 1` and it works just fine. The `--to` flag is not documented though. Is that on purpose?

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
```bash
truffle migrate --to 1
```

## Expected Behavior

If `--to` is a supported option I would expect it to be documented.

## Actual Results

The `--to` flag is undocumented

## Environment

* Operating System: Linux
* Ethereum client: ganache-cli
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v10.15.0

**Comment by CruzMolina** [comment]
Good catch @Mischi ! Looking into this 🧐

**Comment by CruzMolina** [comment]
Ah, found the option: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-migrate/index.js#L89

Will document and update appropriately 👍

**Comment by CruzMolina** [comment]
Closing as this has been merged via #1838 and released in truffle `5.0.9`!

**Comment by Mischi** [comment]
Yaaay, thanks!
