### ISSUE TITLE
Feature Request: Control the timestamp of initial blocks

### ISSUE THREAD

**Issue by pieterhartel** [trufflesuite/truffle#1843]
## Issue

I am trying to debug smart contracts that use `now`. It would be most helpful if the contracts could be made to behave deterministically, so that each block has a controlled timestamp. It seems that timestamps cannot be controlled during the deployment phase of a contract.

## Steps to Reproduce

 Instamining will generate a few blocks during the deployment of a contract, with timestamps that cannot be controlled. This is problematic when the constructor of the contract calls `now`.

## Expected Behavior

A possible solution would be to extend the scope of `ganache-cli -t`from the timestamp of the genesis block to the following blocks generated during the contract deployment. The developer can take control and turn instamining off as soon as the deployment is complete.

## Actual Results

Random looking timestamps on the first few blocks after the genesis block.

## Environment

$ truffle version
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v10.15.0
$ uname -a
Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

**Comment by CruzMolina** [comment]
Hey @pieterhartel ! Are you referring specifically to deployments via `truffle migrate`, when using `truffle test` out-of-the-box (which runs `ganache-core` in the background)? When using `truffle develop`?

**Comment by pieterhartel** [comment]
Here is a zip with a sample contract and associated files: [HelloEthSalon.zip](https://github.com/trufflesuite/truffle/files/2992091/HelloEthSalon.zip)

Running `truffle test` shows the instamined blocks and their timestamps. Using `ganache-cli -t` gives me control over the timestamp of the genesis block but not of the others.

```
$ truffle test
Compiling ./contracts/HelloEthSalon.sol...
Compiling ./contracts/Migrations.sol...


  Contract: HelloEthSalon:GetMessage
    ✓ TEST: should return a correct string (55ms)
0 1553172915
1 1553172919
2 1553172919
3 1553172919
4 1553172919
    ✓ TEST: check all addresses (70ms)


  2 passing (153ms)

```

```
$ truffle version
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v10.15.0
```

**Comment by CruzMolina** [comment]
@pieterhartel after playing around w/ your code, I see what you mean.

That would be a pretty cool feature to add to migrations/deployments period. Will look into this 👍

**Comment by pieterhartel** [comment]
There is a workaround for this issue that is actually really simple. It consists of dispensing with the second migration script. Instead the contract is deployed in the test script. For details and an example see: [https://github.com/trufflesuite/ganache-core/issues/388#issuecomment-480951656](url)

**Comment by eggplantzzz** [comment]
@pieterhartel Glad you came up with a workaround! Do you think that there is still something actionable here?

**Comment by gnidan** [comment]
Closing this for issue maintenance, since there's a viable workaround and no clear requirements on a new feature.

If anyone wants this in the future, would love to pick up the conversation again! Thanks!
