### ISSUE TITLE
truffle 5 migration doesn't work

### ISSUE THREAD

**Issue by az-ms** [trufflesuite/truffle#1845]
- [Yes] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have some problem with truffle 5.
When we try to use truffle 5 to deploy the contact, it doesn't trigger the deployment at all.
However when we turn to truffle 4 (4.1.15), it's running/deployed successfully.

Here is the output from truffle 5:

adam@ms-Virtual-Machine:~/simple-storage$ truffle migrate --network test --reset --verbose-rpc

{
"jsonrpc": "2.0",
"id": 2,
"method": "eth_getBlockByNumber",
"params": [
"latest",
false
]
}

I tested this json request, our private service can respond this request.

## Steps to Reproduce

Install truffle 5.0

## Expected Behavior

The contract can be deployed to the target blockchain network.

## Actual Results

No deployment or migration activity at all.

## Environment

* Operating System:  Ubuntu 18.04 LTS
* Ethereum client:  Geth
* Truffle version (`truffle version`):  5.0.8
* node version (`node --version`):  v11.10.1
* npm version (`npm --version`):  6.7.0

**Comment by az-ms** [comment]
I have reproduced this issue on Ganache. I run Ganache on 10.94.200.94. 
Here is my networks setting:

    web3pganache: {
      provider: function() {
        var provider = new web3.providers.HttpProvider("http://10.94.200.94:7545");
        return provider;
      },
      network_id:"*"
    },


    ganache: {
      host: "10.94.200.94",
      port: 7545,
      network_id: "*" // Match any network id
    },

# this works as we expected 
$ truffle migrate --network=ganache --reset

# when we turn to use web3provider, we don't see any migration taking place. 
$ truffle migrate --network=web3pganache --reset --verbose-rpc

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

   > {
   >   "jsonrpc": "2.0",
   >   "id": 3,
   >   "method": "eth_getBlockByNumber",
   >   "params": [
   >     "latest",
   >     false
   >   ]
   > }

Is that any**[**

**Comment by CruzMolina** [comment]
Hey @az-ms !

What version of web3 are you using for `web3pganache`?

**Comment by az-ms** [comment]
@CruzMolina 

Thank you for your input. I have verified this and it works on web3@1.0.0-beta.37.
And I also find my original issue may be also related the version compatibility. 
Now web3@1.0.0-beta.37 is installed, but when I use httpheaderprovider (https://github.com/EthereumEx/httpheaderprovider) as the https provider, the migration always doesn't take place on truffle 5.

It seems that issue is related to its dependent web3 library.  Now I have removed this httpheaderprovider and use web3 provider directly, then the issue is resolved. 

├─┬ httpheaderprovider@0.3.4

│ ├─┬ debug@2.6.9

│ │ └── ms@2.0.0

│ └─┬ web3@0.17.0-beta

│   ├── bignumber.js@2.0.7 (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)

│   ├── crypto-js@3.1.8

│   ├── utf8@2.1.1

│   └── xmlhttprequest@1.8.0

**Comment by CruzMolina** [comment]
Oh wow, yes I would expect a pkg using web3@0.17.0-beta to act wonky w/ truffle 5.

Glad we were able to narrow this down. Closing, but please feel free to re-open or create a new issue if something comes up!
