### ISSUE TITLE
Rename truffle-config's default method

### ISSUE THREAD

**Issue by daniyarchambylov** [trufflesuite/truffle#1846]
## Issue

I'm using truffle-config package in a project written in TypeScript. I'm calling `Config.default().merge(options);`, but tsc complains that TypeDefinition must be present. It is impossible to create d.ts file for truffle-config package since one of the methods is called `default` which is reserved keyword and not allowed to be used as a function or variable name.

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client:
* Truffle version (`truffle version`): 5.0.8
* node version (`node --version`): 8.9.3
* npm version (`npm --version`): 5.5.1

**Comment by gnidan** [comment]
Ah that's tricky, since that'll be a breaking change. Feel free to open a PR and we can figure out next steps for release timing. Thanks for raising this issue!

**Comment by daniyarchambylov** [comment]
@gnidan will do

**Comment by gnidan** [comment]
Hey @daniyarchambylov did you still want this? We have an opportunity to make a breaking change to truffle-config with Truffle v5.1, in the next few months.

**Comment by fainashalts** [comment]
We all now want to fix this for better TypeScript compatibility, putting in the backlog.

**Comment by haltman-at** [comment]
This should be fixed now.  The method is still named `default`, but now that it's a TypeScript class, it should no longer be a problem.

Closing this.  Let us know if we're mistaken and there is in fact still a problem.
