### ISSUE TITLE
Compiler installation error message improvement

### ISSUE THREAD

**Issue by RobertoC27** [trufflesuite/truffle#1847]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm trying to use solc version 0.5.2 but truffle fails to install it when setting it on the truffle-config.js file. I added the open zeppelin library and their contracts require solc ^0.5.2 while truffle uses 0.5.0 by default.  After updating my config file and executing `truffle compile` an error that said version 0.5.2 does not exists popped out.

## Steps to Reproduce

Update the truffle config file to set solc version to 0.5.2
run `truffle compile`
run `truffle compile --list`
run `truffle obtain --solc=0.5.2`

## Expected Behavior

Truffle installing required compiler version or showing a more clear error message for the failure.

## Actual Results
This is what happened when trying to compile after updating my config file.
![running truffle compile after updating config file](https://user-images.githubusercontent.com/8262009/54787572-bd801480-4bf1-11e9-8e8d-703b5ecd1db4.png)

After digging in past issues I found the `truffle obtain` command

Now when executing `truffle obtain --solc=0.5.2` the following happened
![The real error was shown](https://user-images.githubusercontent.com/8262009/54787654-0637cd80-4bf2-11e9-9cbb-374123948202.png)
As you can see, the real error is permissions issue.
 Running the same with sudo fixed the issue, but I wonder if there's a way of showing the *real* error message the first time.
Maybe my setup is **too obscure** and I just have to live with it, but just putting this out.

## Environment
**I'm working on Windows Subsystem for Linux (WSL) which I made a gist if you guys feel the need to try and recreate my environment [gist with installation instructions](https://gist.github.com/RobertoC27/5758e1f7f40185284bb669e8728b766f)**
* Operating System: Windows 10 Pro
* Ethereum client: Ganache
* Truffle version (`truffle version`): Truffle v5.0.7 (core: 5.0.7)
* node version (`node --version`):Node v10.15.3
* yarn version (`yarn --version`): 1.15.2

**Comment by CruzMolina** [comment]
Hey @RobertoC27 !

Fortunately, the permissions issue got fixed in truffle `5.0.8` via #1801. Let me know if upgrading works for you.

Definitely agree that we should have better error handling during compiler installation.

**Comment by RobertoC27** [comment]
@CruzMolina  thanks for your quick response!
It works like a charm with 5.0.9 👍

If i may suggest something, I think a list of error priorities could be a good idea.

So you would have something like:
1. OS errors
2. Truffle errors
... Insert other kind of errors
3. Compiled code errors
4. User input errors


The lower the number, the higher it's priority to be displayed to the end user.

That way you can determine what you can show to the user without overwhelming them with information.
