### ISSUE TITLE
Warn if both truffle-config.js and truffle.js is provided.

### ISSUE THREAD

**Issue by mrwillis** [trufflesuite/truffle#1864]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
There should be a warning if both truffle-config.js and truffle.js are provided when running truffle commands. 

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: ubuntu 18
* Ethereum client: infura
* Truffle version (`truffle version`): 5.0.8
* node version (`node --version`):10.5.0
* npm version (`npm --version`): 6.7.0

**Comment by adrianmcli** [comment]
Sounds pretty sensible. Would love to see a PR, @mrwillis.

**Comment by mrwillis** [comment]
wrote a draft here https://github.com/trufflesuite/truffle/pull/1866

**Comment by eggplantzzz** [comment]
@mrwillis This should be fixed on the latest version of Truffle. Closing this, feel free to reopen an issue if it is still a problem.

**Comment by SvenMeyer** [comment]
I only have `truffle-config.js` in my project folder, but get the message  

`Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js`

$ truffle version  

Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js. \
Truffle v5.0.22 (core: 5.0.22) \
Solidity v0.5.0 (solc-js) \
Node v10.16.0 \
Web3.js v1.0.0-beta.37

**Comment by ciberexplosion** [comment]
> I only have `truffle-config.js` in my project folder, but get the message
> 
> `Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js`
> 
> $ truffle version
> 
> Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
> Truffle v5.0.22 (core: 5.0.22)
> Solidity v0.5.0 (solc-js)
> Node v10.16.0
> Web3.js v1.0.0-beta.37

Did you find any solution? I have the same problem

**Comment by J-Cook-jr** [comment]
> > I only have `truffle-config.js` in my project folder, but get the message
> > `Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js`
> > $ truffle version
> > Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
> > Truffle v5.0.22 (core: 5.0.22)
> > Solidity v0.5.0 (solc-js)
> > Node v10.16.0
> > Web3.js v1.0.0-beta.37
> 
> I'm having this issue too. However, everything is working properly. This is my second time building a Smart Contract in VS Code. It hasn't been a smooth experience at all..lol... I think I'll check out Remix for my next smart contract project. I believe the problem above will go away when I build in Remix... We'll see, I'll let you guys know if it does.
