### ISSUE TITLE
Not writing "networks": {} in artifacts if contract has no constructor

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/truffle#1869]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In the `.json` artifacts, the `network:{}` information is not written if the contract has no constructor, although migration is displayed as successful. Therefor, it's impossible to call a function, truffle-contract always says the contract is not deployed.

## Steps to Reproduce

1. Deploy contract without constructor
2. Build with your favourite truffle box

## Expected Behavior

Either `error` or notify during compiling and abort or just fix this issue. 

## Actual Results

`network:{}` information is not written in artifacts

## Environment

* Operating System: OSX 10.14.03
* Ethereum client: Ganache
* Truffle version: `5.0.10`
* node version: `11.3.0`
* npm version: `6.9.0`

**Comment by eggplantzzz** [comment]
@nikita-fuchs I couldn't successfully duplicate your problem locally. Do you have a codebase that you could point me to that might help me reproduce the problem?

**Comment by gnidan** [comment]
Hey @nikita-fuchs have you had a chance to get back to this? Looking to close for issue maintenance. Thanks!

**Comment by eggplantzzz** [comment]
Closing. Let us know if it needs to be reopened! Thanks!
