### ISSUE TITLE
truffle-solidity-loader not running migrations anymore

### ISSUE THREAD

**Issue by imbenwolf** [trufflesuite/truffle#1870]
---------------------------

## Issue

When using truffle-solidity-loader like in the documentation of github, it is compiling the contracts correctly, but not running the migrations.

## Steps to Reproduce

Setup truffle-solidity-loader like in the documentation and import a solidity contract in your code.

## Expected Behavior

Truffle migrations should run.

## Actual Results

Truffle migrations don't run.

## Environment

* Operating System: Windows 10
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.0.10 (truffle-solidity-loader 0.1.10)
* node version (`node --version`): 10.15.3
* npm version (`npm --version`): 6.4.1 (yarn 1.15.2)

**Comment by imbenwolf** [comment]
seems to be because of the --from change. address is still being provided when migrating but it should be omitted

**Comment by imbenwolf** [comment]
problem seems to be here: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/commands/migrate.js#L149

**Comment by imbenwolf** [comment]
downgrading to 5.0.8 to solve problem temporarly

**Comment by imbenwolf** [comment]
breaks https://truffleframework.com/docs/truffle/reference/configuration#networks "from" configuration

**Comment by imbenwolf** [comment]
fix for yarn by adding the following to package.json

`"resolutions": {
    "truffle-solidity-loader/truffle-core": "5.0.8"
  }`

**Comment by CruzMolina** [comment]
Hey @imbenwolf ! Thanks for reporting this and sharing your findings. Will take a look. 🧐

**Comment by CruzMolina** [comment]
Ah, I see what happened. Thanks again for sharing your findings! Should have a fix in soon.
