### ISSUE TITLE
Update printing of web3 version

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#1873]
It seems that in versions of Web3 greater than 1.0.0-beta.37 the `version` method has been removed. Upon upgrading Web3, update this [file](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/version.js) to account for this

**Comment by eggplantzzz** [comment]
UPDATE: It looks like the version method was removed from `require('web3')`. However, it seems like `new Web3(<url>)` still contains the version method.

**Comment by eggplantzzz** [comment]
Waiting for the Web3 discussion concerning the next stable version to resolve.
https://github.com/ethereum/web3.js/issues/2684

**Comment by nivida** [comment]
Wouldn't it be possible for truffle to get the version directly from the Web3.js package.json?
``import {version} from '../package.json';``

**Comment by eggplantzzz** [comment]
@nivida For sure, that is actually how it was previously accessed before I discovered that Web3 had a version method. So that seemed to be the proper way to access version information as long as it existed. At some point it got removed so I'm just waiting to see what interface will be for the first stable version.

**Comment by eggplantzzz** [comment]
PR #2043 uses the package.json to find Web3 version information. This was done to prevent loading up Web3 every time a command is run.

**Comment by gnidan** [comment]
Looks like this is merged. Closing! Thanks folks!
