### ISSUE TITLE
Truffle-Decoder dist folder is outdated

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/truffle#1877]
When working with `v2.0.3` of Truffle-Decoder, the `dist` folder is out-of-sync with the `lib` folder. Perhaps whoever published the last version forgot to do a compilation before releasing.

## Example

<img width="1440" alt="Screen Shot 2019-04-03 at 7 26 17 PM" src="https://user-images.githubusercontent.com/943555/55472186-67c25800-5646-11e9-8154-863675bf5cb6.png">

On the left side of the image is `dist/interface/contract-decoder.js` and the right side is `lib/interface/contract-decoder.ts`. Notice that on line 54 on the left, there is a string comparison to see if the passed in provider is a string that starts with a certain prefix.

However, we changed this in #1598 to accept an actual Provider object instead of a string. Therefore, if you look at the right side (w/ the TS source file), you'll notice that there is no `startsWith` method call in the constructor (or the entire file actually) because it doesn't expect the `provider` to be a string.

What's weird is that this was working before, so the `dist` folder must have regressed by someone who published this package without compiling.

**Comment by haltman-at** [comment]
Says @gnidan: We're going to do a release tomorrow, he'll look at it then.

**Comment by gnidan** [comment]
This should be fixed now thanks to #1888. Closing!
