### ISSUE TITLE
Ability to have truffle migrate use a user defined configuration file.

### ISSUE THREAD

**Issue by caleteeter** [trufflesuite/truffle#1879]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle currently relies on truffle.js or truffle-config.js for the configuration elements that are used for compliation and migrations.  Having a global configuration flag that would allow truffle to use user passed in configuration file path.  

## Expected Behavior

Addition of a global configuration flag such as this: truffle migrate --config</path/to/config>

## Actual Results

Loading truffle configuration settings from user defined configuration files.

## Environment

* Operating System: Windows
* Ethereum client:  N/A
* Truffle version (`truffle version`): 5.0.8
* node version (`node --version`):  10.13.0
* npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
@caleteeter Thanks for the suggestion, it seems like it could be a good idea! We'll look into it.

**Comment by CruzMolina** [comment]
## Requirements

1. Enable successful usage of a global configuration flag while calling `truffle migrate`.

Example:
```
truffle migrate --config /path/to/config
```

2. Throw a helpful `Error` if a truffle config is not found at the given path.
3. Add an integration test to verify proper behavior (i.e. when passed a valid config path, migration succeeds, when passed an invalid config path migration fails).

## Prerequisite Context

- Familiarity with the current entry point for `truffle migrate`: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/commands/migrate.js. The config flag should probably be handled before [this line](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/commands/migrate.js#L176).
- Some familiarity with the `Config` class outlined in `truffle-config` might be helpful: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-config/index.js
- Familiarity with current `truffle migrate` integration tests, i.e. https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/test/scenarios/happy_path/happypath.js, particularly [these lines](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/test/scenarios/happy_path/happypath.js#L69-L111).

**Comment by eggplantzzz** [comment]
A feature resolving this was released a number of versions ago. Use the `--config` flag on the command line to specify a path to the Truffle config to be used.
