### ISSUE TITLE
I don't get an error if the "truffle unbox" failed when executes the command from the hooks

### ISSUE THREAD

**Issue by bk201-** [trufflesuite/truffle#1881]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I execute "truffle unbox react" the hook with "npm install" might be failed for instance I don't have python. I just can see in the console that setup was failed, but I missed the real reason for this

Here I tried to debug truffle-box
![image](https://user-images.githubusercontent.com/6812525/55647961-ab07fc80-57e7-11e9-9985-ab8716318f73.png)
![image](https://user-images.githubusercontent.com/6812525/55648166-400af580-57e8-11e9-8677-fa5991ce1a85.png)
![image](https://user-images.githubusercontent.com/6812525/55648180-4ac58a80-57e8-11e9-9d36-7e9ac6051ab0.png)

## Steps to Reproduce

Run truffle unbox react when just python 3 was installed on your PC.

## Expected Behavior

I expect to see the real error or have the ability to redirect output with error to file

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows
* Ethereum client: N/A
* Truffle version (`truffle version`): 5.0.10
* node version (`node --version`): 11.13.0
* npm version (`npm --version`): 6.7.0

**Comment by eggplantzzz** [comment]
@bk201- Thanks for the heads up! I'm getting a PR in for it now.

**Comment by eggplantzzz** [comment]
This should be fixed with the merging of #1886. Closing this.
