### ISSUE TITLE
Can't Install Contracts from EthPM with Truffle 5.0.11

### ISSUE THREAD

**Issue by rori4** [trufflesuite/truffle#1883]
- [ YES] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

## Issue

I am trying to use truffle install on the latest truffle 5.0.11. I know that we have a new EthPM however when I try to install whatever package nothing happens in the console. I just waits a little and after that nothing happens. No new folder nothing.

I have rolled back to version 5.0.8 and I can confirm that there I can run `truffle install tokens` successfully and it installs the tokens contracts. Any ideas?

## Steps to Reproduce

Try to install any package from [http://explorer.ethpm.com/directory/](http://explorer.ethpm.com/directory/)

## Expected Behavior
To have a folder with installed_contracts

## Actual Results

Nothing happens in the console and no folders are created. I just waits a little and after that nothing happens. No new folder nothing.

## Environment

* Operating System: Windows 10 Version 10.0.17134 Build 17134
* Truffle version (`truffle version`):
Truffle v5.0.11 (core: 5.0.11)
Solidity v0.5.0 (solc-js)
Node v11.9.0
Web3.js v1.0.0-beta.37
* node version (`node --version`):
v11.9.0
* npm version (`npm --version`): 
6.5.0

**Comment by fainashalts** [comment]
Thanks for bringing this to our attention. We'll take a look!

**Comment by eggplantzzz** [comment]
This bug is fixed in PR #2032.

**Comment by onggunhao** [comment]
Just FYI - Truffle does not (currently) support EthPM v2

See thread here: https://github.com/trufflesuite/trufflesuite.com/issues/398

**Comment by eggplantzzz** [comment]
Yes, so this bug fix pertains only to ethpm v1.

**Comment by onggunhao** [comment]
@eggplantzzz Thanks!!

**Comment by onggunhao** [comment]
For anyone else who was stuck on this, you'll have to upgrade Truffle to the latest version. 

```
npm update -g 
// if you installed truffle globally
```

It should be solved in `truffle@5.0.19`

**Comment by gnidan** [comment]
Looks like we can close, then! Thanks all!
