### ISSUE TITLE
ABIs in artifacts are sometimes missing signatures

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#1889]
## Issue

Under certain conditions, the elements of the `abi` member of the Truffle artifact will be missing their `signature` element.  This can occur even for concrete contracts (not just interfaces and abstract contracts).  (And, really, there's no reason not to include them even for contracts that aren't concrete.)

(Note that @gnidan suggests that actually the `signature` element should *always* be missing, but I'm filing this anyway for completeness.)

## Steps to Reproduce

Compile a Truffle project with the following contract file:

```
pragma solidity ^0.5.0;

contract TestAbstract {
  function doThingA() public;
}

contract TestConcrete is TestAbstract {

  function doThingA() public {
  }
}
```

## Expected Behavior

The artifact for `TestConcrete` should have signatures.  (And, IMO, as mentioned above, the artifact for `TestAbstract` should too, even though I'm guessing their omission was deliberate.)

## Actual Results

The artfact for `TestConcrete` (as well as the artifact for `TestAbstract`) did not have signatures.

**Comment by haltman-at** [comment]
OK, this may just not be a real problem.  Especially with #1908, which just computes the signatures if they're not already present.

**Comment by haltman-at** [comment]
OK, I think I'm just going to close this; I don't think there's any real issue here.

**Comment by CruzMolina** [comment]
Reopening since `signature` presents appears to be an issue when validating artifacts in TFT.
