### ISSUE TITLE
Deploying simple Contract to geth

### ISSUE THREAD

**Issue by BlockChange** [trufflesuite/truffle#189]
I'm getting an error when I try to deploy a contract (via serve):

```
Module build failed: Error
      at DeployError.ExtendableError 
```

Or when I try `truffle deploy`:

```
Checking sources...
Compiling SimpleStorage.sol...
Collecting dependencies...
Error deploying SimpleStorage:

undefined

Deploy failed. See above.
```

This worked before on `testrpc` without problems. But my guess is that I need to **authenticate**, but how?.

I've not configured much other than add an account on the command line, and one in the geth javascript console. (Which created 2 different/seperate accounts?) But never logged in, or configured anything to use them. But I can also not find anything about this in the docs

It seems it's just assuming testrpc where everything just magically works..

Is it even possible to deploy contracts on a live Node from truffle, because I would first need to unlock an account from whence I deploy the contract no?

I've been searching for hours now for anything that would allow me to tell `truffle` to login, and deploy the contracts on `geth` like it does in `testrpc`.

**Comment by maraoz** [comment]
That error isn't very useful. 
Have you tried using geth in testnet mode first?

**Comment by tcoulter** [comment]
As well, can you try updating your project to Truffle 2.0? You'll need to write migration files instead of deploys, but the whole process has been sufficiently updated, and perhaps the issue you're running into is fixed.

**Comment by maxweng** [comment]
I've upgraded to 2.0, and managed to migrate and deploy on Testrpc without problem. Then failed miserably in trying to do the same thing on my local geth node. The error msgs are: 

> Error encountered, bailing. Network state unknown. Review successful transactions manually. invalid address.

**Comment by maxweng** [comment]
And I'm sure my geth node is running fine, as I can log in to it with `geth attach`, and successfully run some web3 commands.

**Comment by tcoulter** [comment]
@maxweng Can you provide the full error output?

It's been awhile since this ticket was updated. Has your issue been resolved?

**Comment by webpolis** [comment]
Same issue here

```Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
invalid address
```

**Comment by tcoulter** [comment]
Closing for housekeeping.
