### ISSUE TITLE
issue import in vue hdwallet latest version 

### ISSUE THREAD

**Issue by helderjnpinto** [trufflesuite/truffle#1893]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

## Issue
problem with import truffle-hdwallet-provider@1.0.6 in one vue app, with this version "truffle-hdwallet-provider": "^1.0.0-web3one.0", works.

What the issue is, in broad strokes.

## Steps to Reproduce
vue create `appname`
npm i truffle-hdwallet-provider

Please provide the shortest amount of steps to reproduce your issue.
just import this in vue.js
```javascript
vue component ....
import HDWalletProvider from 'truffle-hdwallet-provider'

```
```javascript

console error: 
bindings.js?dfc1:29 Uncaught TypeError: Cannot read property 'modules' of undefined
    at Object.eval (bindings.js?dfc1:29)
    at eval (bindings.js:223)
    at Object../node_modules/bindings/bindings.js (app.js:1328)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (index.js?477d:1)
    at Object.eval (index.js?477d:1)
    at eval (index.js:50)
    at Object../node_modules/truffle-hdwallet-provider/dist/index.js (app.js:8890)
    at __webpack_require__ (app.js:724)

```

## Expected Behavior

What you expected to happen.
import without errors
vue app crash
 
## Environment

* Operating System: 
uname -a                                                                               
Linux bd 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Ethereum client:
* Truffle version (`truffle version`): ---- only npm hd wallet 
* node version (`node --version`):  node: '11.3.0'
* npm version (`npm --version`): npm: '6.4.1',

**Comment by helderjnpinto** [comment]
@1.0.0-web3one.3 works like web3one.0, on version 4 not work any more

**Comment by eggplantzzz** [comment]
@helderjnpinto Do you have more detailed steps on how to produce this? I created a new vue app, added the import into `main.js` and it seems to import correctly. This is with the most recent version of truffle-hdwallet-provider, 1.0.8

**Comment by helderjnpinto** [comment]
@eggplantzzz with the lastest update no more is showing this error. thx i will close this issue
