### ISSUE TITLE
Truffle - test: Cannot create property 'negative' on number '1'

### ISSUE THREAD

**Issue by flockonus** [trufflesuite/truffle#1909]
## Issue

There seems to be some terrible bugs on the current big number implementation, and it's breaking tests.

## Steps to Reproduce

My case was during a test, but i can also do it using `truffle develop` with a simpler case:

```
>  n = new web3.utils.BN('1'); n.sub('1')

/workspace/node_modules/truffle/build/cli.bundled.js:1315
      num.negative = 0;
                   ^

TypeError: Cannot create property 'negative' on string '1'
```

Seems to be some crazy internal error. [Possible reference](https://github.com/ethereum/web3.js/issues/2171)

## Expected Behavior

Not an internal error

## Environment

* Operating System: MacOS
* Ethereum client: ?
* Truffle version (`truffle version`): 5.0.12
* node version (`node --version`): v11.4.0
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment]
@flockonus Thanks for the heads up! We'll keep this in mind and follow the BN issue that you linked above.

**Comment by flockonus** [comment]
Thanks @eggplantzzz , the workaround I'm using currently is:

```js
n = new web3.utils.BN('1'); n.sub(web3.utils.toBN('1'))
```

**Comment by CruzMolina** [comment]
Hey @flockonus , turns ou that BN does not take strings for those methods! Your workaround is the way to do it, you can also use `n.subn(1)`.

**Comment by CruzMolina** [comment]
Closing since there's nothing we can do on our end about this.

**Comment by saikrishnakalangi** [comment]
I am facing the same issue but i did not get a solution

**Comment by gnidan** [comment]
@saikrishnakalangi did you follow the syntax [here](https://github.com/trufflesuite/truffle/issues/1909#issuecomment-484721025)?
