### ISSUE TITLE
truffle migrate does a "--dry-run" by default. Can't deploy on network

### ISSUE THREAD

**Issue by mscherer82** [trufflesuite/truffle#1927]
I can't deploy on network anymore because dry-run is used by drefault. --skip-dry-run doesn't help.

Command I use:

`truffle migrate --reset --network=sokol`

Result I got: 

```
Migrations dry-run (simulation)
===============================
> Network name:    'sokol-fork'
> Network id:      77
> Block gas limit: 0x7a1200
```

Config:

```
module.exports = {
    contracts_build_directory: process.cwd() + "/build/eth",
    compilers: {
        solc: {
            version: "0.4.25"
        }
    },
    solc: {
        optimizer: {
            enabled: true,
            runs: 200
        }
    },
    networks: {
...
        sokol: {
            provider: () =>  new HDWalletProvider(accounts[accountName].key, "https://sokol.poa.network/"),
            network_id: '77',
            gas: 75e5,
            gasPrice: gasPrice || 1e9
        },
...
```

* Operating System: windows
Truffle v5.0.13 (core: 5.0.13)
Solidity - 0.4.25 (solc-js)
Node v8.12.0
Web3.js v1.0.0-beta.37

**Comment by eggplantzzz** [comment]
@mscherer82 Hey, yes this is a bug that we should have fixed in the next release. If you'd like to skip the dry run for now, you can add `skipDryRun: true` in your network config under `sokol`. That should skip it for you and should continue to run in the future. 
With the next release you should be able to use both `skip-dry-run`(`--skip-dry-run` as a command line option) and `skipDryRun` on the command line and in the config to skip the dry run.

**Comment by mscherer82** [comment]
Thank you

**Comment by mscherer82** [comment]
Even with the newest version 5.0.14 I'm not able to deploy anything. If I use `truffle migrate --reset --network=sokol` only a dry run is started. Is this intended? 
When using `--skipDryRun` truffle exit after compiling the contracts without any message.

This is my first migration script:

```
const Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer, network) {
  deployer.then(async () => {
    await deployer.deploy(Migrations);
  });
};
```

**Comment by CruzMolina** [comment]
@mscherer82 What version of `truffle-hdwallet-provider` are you using? `1.0.7` has a bug in it that breaks migrations. `1.0.6` & `1.0.8` currently don't have any known issues.

**Comment by mscherer82** [comment]
Thanks

**Comment by xhliu** [comment]
Had the same issue using `truffle-hdwallet-provider@1.0.15`. Had to override with `--skip-dry-run`.
