### ISSUE TITLE
truffle-hdwallet-provider 1.0.7 unable to deploy

### ISSUE THREAD

**Issue by yayajacky** [trufflesuite/truffle#1928]
- [ x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running `truffle migrate --network...`, the basic migration contract does not get deployed, and just hangs.
Reverting to truffle-hdwallet-provider 1.0.6 works 

## Steps to Reproduce

1. Make a new empty truffle project
2. Point to ropsten/rinkeby/thunder testnet or mainnet
3. Run truffle migrate
4. Contract does not get deployed and times out

## Expected Behavior

Contract to be deployed with a contract address

## Actual Results

Migration hangs at 

Summary
=======
> Total deployments:   1
> Final cost:          0.01837234 ETH

Then times out after a while.

## Environment

* Operating System: Mac
* Ethereum client: 
* Truffle version (`truffle version`): v5.0.13
* node version (`node --version`): v8.11.3
* npm version (`npm --version`): 5.6.0

## Short term turn around

* Downgrade to truffle-hdwallet-provider 1.0.6

**Comment by CruzMolina** [comment]
Hey @yayajacky !

What version of web3 do you have required in your project's `truffle-config.js`?

**Comment by yayajacky** [comment]
web3: 1.0.0-beta.37 (with truffle-hdwallet-provider 1.0.7)

**Comment by yayajacky** [comment]
Seems like 1.0.7 has "web3": "1.0.0-beta.37" as a direct dependency, where as 1.0.6 had it as a dev dependency

**Comment by CruzMolina** [comment]
Hmm, did some debugging and so far the issue seems isolated to `truffle-hdwallet-provider@1.0.7`. Looking into this.

**Comment by CruzMolina** [comment]
Bah. Looking like the cause of this was upgrading `web3-provider-engine`. It appears the API changed.
