### ISSUE TITLE
When running a single test, compile only the required files (to save time with large repo)

### ISSUE THREAD

**Issue by marsrobertson** [trufflesuite/truffle#1935]
- [x] I've asked for help in the [Truffle Gitter](https://gitter.im/ConsenSys/truffle?at=5cb24f22b34ccd69e7b31e2a) before filing this issue.

---------------------------

## Issue

Large repo, plenty of files.

I run a single test only.

All the files are compiling (takes more than a minute)

## Steps to Reproduce

Related to: https://github.com/kleros/kleros-interaction/issues/248#issuecomment-482943506

## Expected Behavior

I prefer if only relevant .sol files were compiled, saving me time, improving developer experience.

## Actual Results

When I run a single test, everything is compiling.

I've found a workaround by moving unused files elsewhere.

Another workaround is better structuring of the repos, packages.

**Or maybe the Truffle compiler can be smart enough to compile only what is needed?**

**Comment by CruzMolina** [comment]
Hey @marsrobertson! An alternative to your current workaround in kleros/kleros-interaction#248 (having only .sol files you'd like to test in `contracts`), is to `truffle compile` locally and then push all the build artifacts. That _should_  also produce the same behavior as your workaround.

#469 related.

**Comment by marsrobertson** [comment]
Workarounds are complicated / burdensome.

Closing this one in favour of #469 (duplicate).

**Comment by CruzMolina** [comment]
@marsrobertson tell me about it!

IIRC, there's not currently a way to make the compiler/artifacts record-keeping system smarter w/o pre-compiling everything. That said, there are efforts towards solving issues like this that I believe fall under the scope of #1718.
