### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Tammeny** [trufflesuite/truffle#1936]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I got error like Cannot read property 'replace' of undefined when i using truffle debug.

## Steps to Reproduce

truffle debug tx

## Expected Behavior

debug

## Actual Results

Cannot read property 'replace' of undefined

## Environment
local chain
* Operating System: OSX
* Ethereum client:
* Truffle version (`truffle version`):5.0.9
* node version (`node --version`):10.15.3
* npm version (`npm --version`): 6.4.1

**Comment by haltman-at** [comment]
Hi, we're going to need more information here.  Could you provide the precise error message and more detailed reproduction steps?  Thank you!

**Comment by haltman-at** [comment]
By the way, you also might want to try upgrading to Truffle 5.0.14 and seeing if that fixes the problem.  In fact, you should probably try that first.

**Comment by gnidan** [comment]
Hi @Tammeny thanks for raising this issue. Closing this for issue maintenance; please let us know if upgrading doesn't solve the problem for you. Thanks!
