### ISSUE TITLE
Feature request: TruffleContract.version

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#1938]
- [x] I've [asked for help in the Truffle Gitter](https://gitter.im/ConsenSys/truffle?at=5cbdcbc9b489bb6ed7a712da) before filing this issue.

---------------------------

## Issue
Due to the [semantic versioning](https://github.com/ethereum/web3.js/issues/2684#issuecomment-483266673) system going away [especially](https://github.com/ethereum/web3.js/issues/2679) with web3, I have been spending an inordinate amount of time lately on bugs related to breaking changes in dependencies, and not knowing exactly which version of truffle-contract is being used in any particular test makes this a lot harder.  

In some cases, a bug appears with a later version of truffle-contract which is not present in an earlier version, but identifying exactly where the bug appears can be a challenge (especially when other code must be adapted due to breaking changes between corresponding versions of web3). 

## Steps to Reproduce
1. Follow the [Pet Shop tutorial](https://truffleframework.com/tutorials/pet-shop). (Optionally [browse the source](https://github.com/truffle-box/pet-shop-box), including a review of [package.json](https://github.com/truffle-box/pet-shop-box/blob/master/package.json)).  
2. Optionally attempt to replicate successful behavior in a different dapp, and fail because the files src/js/truffle-contract.js and/or src/js/web3.min.js are different versions.  
3.  Attempt to determine the versions being used.  As a simple example, 
`console.log("web3 version: ",web3.version);` (in the Pet Shop tutorial) produces *api: "0.20.3"* and more, in a response object.  

## Expected Behavior
`console.log("TruffleContract version: ",TruffleContract.version);` produces meaningful output other than `undefined`.  If it produces a string like "4.0.12," one should be able to run `npm install truffle-contract@4.0.12`, look in `node_modules/truffle-contract/dist` and find an copy of truffle-contract.js or truffle-contract.min.js which is exactly the same as the one the client was running to produce that output. 

## Environment
* Operating System: Windows 10 Pro
* Ethereum client: N/A
* Truffle version: That's the key question. `truffle version` produces 5.0.12. 
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
Thanks for the suggestion @wbt, seems like a good idea.

**Comment by eggplantzzz** [comment]
PR #1948 adds this feature.

**Comment by eggplantzzz** [comment]
Closing this.
