### ISSUE TITLE
truffle init problem

### ISSUE THREAD

**Issue by praneethvallabha** [trufflesuite/truffle#1951]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by praneethvallabha** [comment]
i'm getting the following error when i run the command: truffle init
truffle : The term 'truffle' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ truffle init
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (truffle:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
I uninstalled and re-installed truffle, but still having this problem.
Can any help me with some suggestions! thanks

**Comment by praneethvallabha** [comment]
Environment
Operating system: Windows 10
node version (node --version):v10.15.3
npm version (npm --version):6.4.1

**Comment by CruzMolina** [comment]
Hey @praneethvallabha, what version of truffle are you using?

**Comment by rgordon95** [comment]
did you install truffle globally? ( -g flag)

**Comment by adrianmcli** [comment]
To avoid issues with versioning, try doing:

```
npx truffle init
```

That will make sure you are using the latest version (assuming you don't have installed binaries in your current folder).

**Comment by praneethvallabha** [comment]
> Hey @praneethvallabha, what version of truffle are you using?

I'm using truffle@5.0.14

**Comment by praneethvallabha** [comment]
>@rgordon95: i installed truffle using npm install -g truffle. 
Sorry,  don't have much knowledge, so, i don't know if i answered your question correctly!!

**Comment by CruzMolina** [comment]
@praneethvallabha IIRC, there are known Windows compatibility issues when installing and using truffle in a local project directory rather than globally.

Can you give `npm un -g truffle && npm i -g truffle` a shot and let us know if your error disappears?

**Comment by praneethvallabha** [comment]
@CruzMolina : I tried it, unfortunately no luck.

**Comment by CruzMolina** [comment]
Sorry @praneethvallabha ! I'm not familiar enough w/ Windows these days, but maybe there's something in either of these links that will help: https://ethereum.stackexchange.com/questions/15970/truffle-for-windows-i-cant-make-it-work
https://medium.com/@m_mcclarty/setting-up-solidity-on-windows-10-993a1d2c615c

**Comment by praneethvallabha** [comment]
@CruzMolina : This information really helped.. Thank you

**Comment by praneethvallabha** [comment]
@adrianmcli : I that command, but it shows: "preparing download", and i left it all night long, but it still showing the same status, without any progress

**Comment by eggplantzzz** [comment]
@praneethvallabha From the initial error you are getting it seems like Truffle is not installing correctly. When you run a global install from the command line it installs properly?

**Comment by praneethvallabha** [comment]
@eggplantzzz : can you please explain how to 'global install' !! i mean like the command for global install

**Comment by rgordon95** [comment]
@praneethvallabha `npm i -g truffle`

**Comment by praneethvallabha** [comment]
@rgordon95 : thank you

**Comment by subashsakthivel** [comment]
use `npx truffle init` it worked
