### ISSUE TITLE
Specify the working directory for an external complier command

### ISSUE THREAD

**Issue by ianmorgan** [trufflesuite/truffle#1956]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
Discussed on slack with Truffle developers 
---------------------------

## Issue

When invoking an external compilation step (in this case some Java code) , the working directory needs to be set to the same directory as the contract code for the compiler to run, 
for example if the truffle-config has 

```
contracts_directory: "/path/to/myapp",

  compilers: {
      external: {
        command: "./gradlew build",
       targets: [{
               path: "build/libs/myapp.jar"
             }]
      }
    }
```
and I need the "./gradlew" command to be run in the '/path/to/myapp' directory 

One possible solution is 

```
contracts_directory: "/path/to/myapp",

  compilers: {
      external: {
        command: "./gradlew build",
        working_directory: "/path/to/myapp",
       targets: [{
               path: "build/libs/myapp.jar"
             }]
      }
    }
```

 
## Steps to Reproduce

See above

## Expected Behavior

Using the suggested syntax, and running on linux/OSX, then 

```
compilers: {
      external: {
        command: "pwd",
        working_directory: "/path/to/myapp",
       targets: [{
             }]
      }
    }
```
would echo '/path/to/myapp' to the console

_Note, I would also expect 'targets' to now resolve using using the working_directory specified_

## Actual Results

N/A - new feature

## Environment

Current master. Any environment

**Comment by gnidan** [comment]
Looks like this already exists! The option is called `cwd`. Your provided example would be:

```
compilers: {
      external: {
        command: "pwd",
        cwd: "/path/to/myapp",
       targets: [{
             }]
      }
    }
```

I'll mark this issue as just a required documentation update. Thanks for raising the concern!

**Comment by ianmorgan** [comment]
Hi - I've just tried adding this option ("cwd"), but it doesn't appear to actually change the working directory - "pwd" continues to output the root folder - this is the same if I use relative or absolute paths for "cwd" 

Note, my truffle version is returning

17LDN-MAC55-3:iteration1 ianmorgan$ truffle version 
Truffle v5.0.8 (core: 5.0.8)
Solidity v0.5.0 (solc-js)
Node v11.12.0
Web3.js v1.0.0-beta.37

**Comment by eggplantzzz** [comment]
Yes, as it currently stands you would have to add the directory change into your own custom script. Thanks for the suggestion!

**Comment by CplXhristianUSMC** [comment]
Thank you so much for your reply I'm sorry that it's taking me so long to
get back to your emails currently I'm in the process of moving and will be
driving no less than 1300 miles tonight across state lines to get to my new
house please forgive any late replies I greatly appreciate any and all work
that you have been doing to help rectify this matter truly thankful and
gratefully yours cplxhristianusmc

**Comment by eggplantzzz** [comment]
Looks like this was merged and released!
