### ISSUE TITLE
No networks in the json files when running on quorum

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#1962]
## Issue

I installed a new three node quorum raft network using [Quorum Maker](https://github.com/settlemint/quorum-maker) and can deploy my contracts (they and truffle works like expected on a Parity PoA network). 

Apart from the less pretty output, it all appears well. Contacts and transactions show up in the explorer as well.

```./deploy.sh mintquorumnet --reset

> @settlemint/mint-demo@0.0.0-development truffle /Users/roderik/Development/mint-demo
> truffle "migrate" "--network" "mintquorumnet" "--reset"


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Running migration: 1_initial_migration.js
Replacing Migrations...
Migrations: 0x1e7BeF833D0843aaf72997DE7F56d9E6fA59A66E
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_gatekeeper.js
Replacing GateKeeper...
GateKeeper: 0x9Bb76a9662C7b4707630b0Bff5f3b58b2D0dEe6a
Saving successful migration to network...
Saving artifacts...
Running migration: 3_deploy_roles.js
Saving successful migration to network...
Deploying AdminRoleRegistry...
Saving artifacts...
Running migration: 4_deploy_expenses.js
Saving successful migration to network...
Deploying ExpenseRegistry...
Saving artifacts...
Running migration: 5_deploy_medicine.js
Saving successful migration to network...
AdminRoleRegistry: 0x79fB999364c5b66999544eA447E5d6678209826B
Deploying MedicineRegistry...
ExpenseRegistry: 0xdA48BAe178B7C81B5968813251C404392b19E171
Saving artifacts...
Running migration: 6_deploy_shares.js
Saving successful migration to network...
Deploying ShareRegistry...
MedicineRegistry: 0x63aD86f7ae6Fa3e3ed1E4F1beD942a3F8BAa949f
Saving artifacts...
Running migration: 7_deploy_loan.js
Saving successful migration to network...
Deploying ExpenseFactory...
ShareRegistry: 0x0Db54766e9a25F0f4B86fbBB828f35b7c5b4B760
ROLE: ROLE_CUSTOMER
Saving artifacts...
Running migration: 7_deploy_loans.js
Saving successful migration to network...
Deploying MedicineFactory...
Deploying LoanRegistry...
Deploying CustomerRoleRegistry...
ExpenseFactory: 0x4384B999dcA2212583f897D85b6B8175686e5137
Saving artifacts...
```

Except in the son files of e.g. ExpenseFactory the networks section looks like 

```
  "networks": {},
```

while I expected 0x4384B999dcA2212583f897D85b6B8175686e5137 mentioned in there.

My config is:

```
    mintquorumnet: {
      provider: () => {
        return new HDWalletProvider(
          process.env.ETHEREUM_DEPLOYER_SEED ||
            'robot robot robot robot robot robot robot robot robot robot robot robot',
          'http://xxx.xxx.xxx.xxx:22000'
        );
      },
      gasPrice: '0',
      network_id: '*',
      websockets: true,
      production: false,
      type: 'quorum',
    },
```

## Environment

* Operating System: OSX
* Ethereum client: Quorum 2.2.1
* Truffle version (`truffle version`): 5.0.12
* node version (`node --version`): v11.14.0
* npm version (`npm --version`): 6.9.0

**Comment by roderik** [comment]
FYI, updated to the latest release, no change in behaviour

**Comment by roderik** [comment]
I think it is because of a wrong handling of async migrations. A typical v4 issue that has not happened since v5.

```
Running migration: 1_initial_migration.js
Deploying Migrations...
Migrations: 0x2Cf26c56291ccB3F33caAD5b78fA1D5646d4aD39
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_gatekeeper.js
Deploying GateKeeper...
GateKeeper: 0x89314CBEf86Ed46c3E73760efd7ABe3f12913Bd4
Saving successful migration to network...
Saving artifacts...
Running migration: 3_deploy_roles.js
Saving successful migration to network...
Deploying AdminRoleRegistry...
Saving artifacts...
Running migration: 4_deploy_expenses.js
Saving successful migration to network...
AdminRoleRegistry: 0xfC078a12A3938C1618debC3BF88296a2C9cAF5D0
Deploying ExpenseRegistry...
Saving artifacts...
Running migration: 5_deploy_medicine.js
Saving successful migration to network...
Deploying MedicineRegistry...
ExpenseRegistry: 0xCe09F4Bba69ed40f8C561f335aA1E21DdEFFb561
Saving artifacts...
Running migration: 6_deploy_shares.js
Saving successful migration to network...
Deploying ShareRegistry...
MedicineRegistry: 0x2DEC2B8BcC8905f9FB53Ba1beCa331cE766848b8
Saving artifacts...
Running migration: 7_deploy_loan.js
Saving successful migration to network...
ROLE: ROLE_CUSTOMER
Deploying CustomerRoleRegistry...
Deploying ExpenseFactory...
Saving artifacts...
Running migration: 7_deploy_loans.js
ShareRegistry: 0x926C59162015ac83761147b4834944ccCcaCDE81
Saving successful migration to network...
Deploying LoanRegistry...
Deploying MedicineFactory...
CustomerRoleRegistry: 0xaF098F5E65C3C7D33fD6fB893E75d4e083bCD93f
Saving artifacts...
```

Across the list you see "RoleRegistries" being deployed., but this is all in migration nr 3 and there are more. I checked all the migrations and they all properly await deployments (and works on Parity) so I think there is a promise checking that is wrong for quorum deployments.

**Comment by roderik** [comment]
So, this is the culprit: 

https://github.com/trufflesuite/truffle/blob/98e23eee67ef4f15e7e1417d953e112e2f68a417/packages/truffle-migrate/migration.js#L260

By doing this the ability for async/await migration is disabled

**Comment by roderik** [comment]
Sorry for the self monologue, but I make my migrations in typescript anyway so I compiled to to ES2015 (so no await, but with promises) and it still gallops on.

**Comment by roderik** [comment]
Reverting to my v4 style migrations made it work

```
async function performMigration(
  deployer: Truffle.Deployer,
  network: string,
  accounts: string[]
) {
  return deployer.deploy(Migrations);
}

module.exports = (deployer: any, network: string, accounts: string[]) => {
  deployer
    .then(() => {
      return performMigration(deployer, network, accounts);
    })
    .catch((error: Error) => {
      console.log(error);
      process.exit(1);
    });
};
```

**Comment by gnidan** [comment]
Wow @roderik good find! Should be a quick fix now that you've done all the work. Thanks!

**Comment by gnidan** [comment]
Scratch that... that file is a mess of `async` + callback-style collision. Hopefully I or someone else will have the chance to look into it in the next couple days. Feel free to detangle it / open a PR if you find yourself with the urge to wield util's `promisify`/`callbackify` forcefully.

**Comment by roderik** [comment]
I assume that the long term plan is to get Quorum support in the new migrations framework?

**Comment by gnidan** [comment]
> I assume that the long term plan is to get Quorum support in the new migrations framework?

Current plan, not even long-term! We've been making headway on it lately (mostly @CruzMolina), and active work continues as issues like these are identified. It's a priority for us, and I'm sure Cruz is probably about ready by now for the Quorum integration to be done and work as expected 😄.

Last I heard, there was an issue with truffle-hdwallet-provider and Tessera, but that's different than your issue, it seems. Unless they're the same, which would be nice. Apart from that, I believe migrations _should_ work? This is the first I'm hearing of this issue with the deployer, so I'm not sure what you could do to fix it right now, apart from using the old syntax. Hopefully we can just get this fixed for you real fast.

**Comment by roderik** [comment]
This has nothing to do with Tessera. 

For quorum you fall back to legacyMigration code. That is about the same as truffle v4 migration code. 

In v5 you added the option to have async migrations, but this was not added in the legacy v4 style code. 

By using the workarounds we used while using v4, everything works (both on quorum and on parity), but nice optimised v5 code that works on parity will not work on quorum.

**Comment by CplXhristianUSMC** [comment]
Thank you so much for your reply I'm sorry that it's taking me so long to
get back to your emails currently I'm in the process of moving and will be
driving no less than 1300 miles tonight across state lines to get to my new
house please forgive any late replies I greatly appreciate any and all work
that you have been doing to help rectify this matter truly thankful and
gratefully yours cplxhristianusmc

**Comment by haltman-at** [comment]
It seems like this has been resolved.  Going to close this; let us know if it hasn't been.  Thank you!
