### ISSUE TITLE
Auto dry-run migrations exit early without deploying

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#1971]
Auto dry-run for production networks stopped working in a recent release. At the moment, production migrations exit immediately after the dry run without proceeding to the actual deployment. To reproduce with the latest truffle, unbox metacoin and set the networks config to:
```
networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*"
    },
```
In a separate terminal, emulate a mainnet deployment by running ganache-cli with a networkId set to 1:
```
ganache-cli --networkId 1
```

Run:
```
truffle migrate
```

Only the dry-run will execute.

There is an existing test for the correct behavior in the production migrations tests [here](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/test/scenarios/migrations/production.js#L45-L77) but its failure has been masked by a CI problem addressed in #1970. 

## Environment

* Operating System: OSX
* Ethereum client: Geth or Ganache
* Truffle version (`truffle version`): 5.0.14
* node version (`node --version`): 10.5.13
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
Closing this as it should be resolved in version 5.0.17.
