### ISSUE TITLE
Prompt disappears when opening truffle debug within truffle develop

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#1975]
## Issue

When running `debug` from `truffle develop`, the prompt initially fails to appear.  (It will appear after pressing enter, or after deleting any of the entered text.)

## Steps to Reproduce

1. Run `truffle develop`.
2. Within `truffle develop`, run a transaction and obtain its hash.
3. Within `truffle develop`, run `debug` on the transaction hash.

## Expected Behavior

After the debugger's startup messages, the debugger prompt should appear.

## Actual Results

The debugger prompt does not appear until you press enter or delete some of the text you've entered.

## Environment

* Operating System: Linux Mint 18.3 (64-bit)
* Ethereum client: `truffle develop`
* Truffle version (`truffle version`): 5.0.13
* node version (`node --version`): 10.6.0
* npm version (`npm --version`): 6.6.0

**Comment by eggplantzzz** [comment]
This is not an issue on the most recent Truffle (5.1.51) - someone must have fixed it.
