### ISSUE TITLE
Truffle doesn't work with Geth over IPC

### ISSUE THREAD

**Issue by jwasinger** [trufflesuite/truffle#1977]
When deploying to a geth client over IPC, Truffle spins forever without error output of any kind.

I have a description of how to reproduce this issue: https://gist.github.com/jwasinger/f2d1ba6ddecaf305ae9ff6d12b2b9a8e

If I slightly modify the referenced example to support RPC over HTTP and open websocket port, then my deployment works.

**Comment by eggplantzzz** [comment]
@jwasinger Truffle currently has some problems with the most recent versions of Web3. Try downgrading to web3@1.0.0-beta.37 and let me know if you still have issues.

**Comment by jwasinger** [comment]
I apologize, my example contained some configs that aren't compatible with the current master branch of geth.  I've pushed a fix and it should reproduce the bug now.

Unfortunately reverting to `web3@1.0.0-beta.37` didn't fix the issue for me.

**Comment by eggplantzzz** [comment]
Hey @jwasinger, I am able to migrate your project successfully. Make sure you have `1.0.0-beta.37` installed. In your package.json, lock it to `1.0.0-beta.37` and not to `^1.0.0-beta.37`. The migrations do not work with the most recent version of web3.

**Comment by eggplantzzz** [comment]
Oh, so are you continuing this on the rpc branch? Is that the branch I should be looking at?

**Comment by gnidan** [comment]
Hi @jwasinger any news here? Looking to close this issue. Thanks!

**Comment by jwasinger** [comment]
Appears fixed.  Thanks.
