### ISSUE TITLE
Byzantium is still the default EVM version

### ISSUE THREAD

**Issue by vittominacori** [trufflesuite/truffle#1987]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

"byzantium" is still the default value for solc EVM Version.

## Steps to Reproduce

Just create a project and then compile using `truffle compile`.

## Expected Behavior

Expected to be compiled using "petersburg".

## Actual Results

Code is compiled using "byzantium".

## Environment

* Truffle version (`truffle version`): v5.0.15

**Comment by eggplantzzz** [comment]
Thanks for the heads up @vittominacori!

**Comment by eggplantzzz** [comment]
Closing this as v5.0.17 is released!
