### ISSUE TITLE
msg.sender.transfer(value) does not update the balance of the account in tests

### ISSUE THREAD

**Issue by marsrobertson** [trufflesuite/truffle#1994]
# SOLVED

### Sorry about the panic.

It all started here: https://github.com/ethereum/web3.js/issues/2077#issuecomment-490027735

Have to pass string.

So I’ve added `toWei` and `fromWei` helper methods.

`web3.eth.geBalance` returns a string so because I had helpers already I used `fromWei` to have human-readable numbers.

That was a mistake.

Previously my workflow with BigNumbers involved `toString()` and then `parseInt()` to workaround error of losing precision.

_(NOTE: I’m OK with losing precision, very often there is a gas fee, I use `closeTo` syntax)_

Previously `parseInt` on giagantic strings with loads of zeros was just fine. In the human readable work, `parseInt(99.5)` was a disaster that cost me pretty much effectively the whole day of scratching my head.

---  

I was so sure about myself.

So many things do not work all the time, that I was pretty sure it’s them who are wrong, not me.

**Comment by CruzMolina** [comment]
Thanks for the update @marsrobertson ! Glad this got resolved 🙏 

>So many things do not work all the time, that I was pretty sure it’s them who are wrong, not me.

I know that feeling all to well 😂
