### ISSUE TITLE
Stuck at Preparing to download

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/truffle#1996]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

I did, but didn't get an immediate response and I'm moving on for now and didn't want the question lost.

---------------------------

## Issue
Attempting to `truffle init` on Windows in Powershell prompt stalls indefinitely on `Preparing to download`.

## Steps to Reproduce
```
mkdir truffle
cd truffle
npm install truffle
npx truffle init
```

## Expected Behavior
Truffle to initialize the directory.

## Actual Results
```
This directory is non-empty...
? Proceed anyway? Yes
- Preparing to download
```

## Environment

* Operating System: Windows 10
* terminal: Powershell
* Ethereum client: N/A
* Truffle version (`truffle version`): v5.0.15
* node version (`node --version`): v10.15.0
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
@MicahZoltu Hmm, so do you get an error or does it just hang? It seems that part of the code is attempting to create a temporary directory for downloading the unbox files. Does the spinner keep spinning?

**Comment by MicahZoltu** [comment]
It just hangs there indefinitely.  There is no spinner, if the leading hyphen is supposed to be animated to look like a spinner that isn't happening.

ctrl-c also doesn't terminate the process, I have to kill it.

**Comment by irshadnilam** [comment]
I have the same issue

**Comment by eggplantzzz** [comment]
Yes that leading hyphen is supposed to be a spinner...I wonder if there could be something up with that library. The package is ora. I'll see what I can dig up.
A colleague of mine that uses a Windows computer was able to successfully do a `truffle init` with Powershell. I'll see what version of Windows he is using.

**Comment by eggplantzzz** [comment]
We just released v5.0.17. Can you download the most recent version and confirm that it is still an issue with that version?

**Comment by eggplantzzz** [comment]
http://erc721.org/
Here is the sample project they link.
https://github.com/cryppadotta/dotta-license

**Comment by MicahZoltu** [comment]
@eggplantzzz Same problem with `v5.0.17`.

**Comment by RobertoSnap** [comment]
Same here, tried .v5.0.15 /16 / 17

**Comment by RobertoSnap** [comment]
Works with -global NPM install. Can you fix compatibility for NPX?

**Comment by eggplantzzz** [comment]
Hmm I'm not sure why it wouldn't work with npx but could be...

**Comment by eggplantzzz** [comment]
My colleague was able to duplicate your issue on both Powershell and Git Bash. It looks like this is specific to using `npx`. Global installs of Truffle don't seem to have the same issue. We'll have to look into this.

**Comment by alanbleier182** [comment]
This just happened to me too in my linux machine... spinner is moving but the download is stuck

**Comment by MicahZoltu** [comment]
@alanbleier182 I suspect that is a different issue.  The issue I'm running into appears to be the installer completely locking up the process in some blocking operation.

**Comment by Taro0329** [comment]
I have same issue, window Version	10.0.17763 Build 17763, truffle is v5.0.17.

**Comment by zaidmo123** [comment]
I had the same error three times this evening.

To resolve, I navigated to the directory (my project folder) where I was running truffle init from. Deleted all the files, then tried running truffle init in that folder again.

It works.

**Comment by MicahZoltu** [comment]
The above workaround doesn't work for me.  as seen in the repro case in the ticket description, I run into this problem even with a brand new directory.

**Comment by eggplantzzz** [comment]
@MicahZoltu Is it with a global truffle install or are you using npx to run the local package? Are you also on Windows?

**Comment by MicahZoltu** [comment]
Local install and npx.

**Comment by CruzMolina** [comment]
@MicahZoltu can you give `npx truffle@unbundled-solc` and/or `npm i truffle@unbundled-solc`  a try? 🙏

**Comment by Taro0329** [comment]
> I had the same error three times this evening.
> 
> To resolve, I navigated to the directory (my project folder) where I was running truffle init from. Deleted all the files, then tried running truffle init in that folder again.
> 
> It works.

It works too

**Comment by CruzMolina** [comment]
@Taro0329 can you give `npx truffle@unbundled-solc` and/or `npm i truffle@unbundled-solc` a try?

**Comment by zaidmo123** [comment]
I tried npm truffle install.
Both in command prompt with admin rights and Git bash.

It fails even if I have 1 renamed/old/unrelated folder in the directory.
Empty directory, not getting stuck downloading.

I've gotten past that but fail with trying to install another package
(HDwallet)

**Comment by zaidmo123** [comment]
Will try in about 4 hours time

**Comment by zaidmo123** [comment]
It works for me

[image: image.png]

**Comment by CruzMolina** [comment]
Great! Thanks for trying that out @zaidmo123

**Comment by MicahZoltu** [comment]
@CruzMolina The following does not work (same symptoms):
```
mkdir truffle
# create `package.json` file with `{}` in it
npm install truffle@unbundled-solc
npx truffle init
```

**Comment by CruzMolina** [comment]
Thanks for checking that @MicahZoltu. On a stable release of truffle, if you globally install and then try the above, do you still get the same buggy behavior?

**Comment by MicahZoltu** [comment]
The following works:
```
mkdir truffle
cd truffle
npm install -g truffle
npx truffle init
```

**Comment by CruzMolina** [comment]
Hmm, looks like this is what was noticed in: https://github.com/trufflesuite/truffle/issues/1996#issuecomment-491864416

Potentially a Windows `npx` local caching/path issue.

**Comment by 4Maarifa** [comment]
> The following works:
> 
> ```
> mkdir truffle
> cd truffle
> npm install -g truffle
> npx truffle init
> ```

@MicahZoltu  did it work for you?

**Comment by MicahZoltu** [comment]
@4Maarifa Yes.  Doing a global install of Truffle works fine.  Doing a local install of Truffle (and using `npx`) does not work.

**Comment by aabylay** [comment]
Got same issue. That worked for me:

`truffle init --force`

**Comment by marslord** [comment]
> My colleague was able to duplicate your issue on both Powershell and Git Bash. It looks like this is specific to using `npx`. Global installs of Truffle don't seem to have the same issue. We'll have to look into this. Thanks for reporting!

Hi @eggplantzzz I got the same issue, my env:
> Windows 10  v1903
> Cmder  v1.3.11
> Node  v10.16.0
> Npm  v6.9.0

What I did?
```
npm i -g truffle
mkdir myproj
cd myproj
echo "xxx" >> README.md
truffle unbox metacoin
```
If I unbox it in any empty directory , it will be work well.

**Comment by sebastiantf** [comment]
same issue here.

Stuck at downloading when using local Truffle install with `npx` in a non-empty folder.

Works fine if using global truffle install

**Comment by xtianus79** [comment]
had a similar issue. What is the idea of this being addressed so it is fixed or is it just this version?

**Comment by haltman-at** [comment]
@xtianus Can you provide more detail?  What version of Truffle are you using, what exactly did you do, and what exactly were the results?  Thank you!

**Comment by xtianus** [comment]
> @xtianus Can you provide more detail? What version of Truffle are you using, what exactly did you do, and what exactly were the results? Thank you!

@haltman-at you mean @xtianus79

**Comment by haltman-at** [comment]
Oops, my apologies.  @xtianus79, can you provide more detail? What version of Truffle are you using, what exactly did you do, and what exactly were the results? Thank you!

**Comment by fainashalts** [comment]
@MicahZoltu is this still a problem on the current version of Truffle? It looks like there was an issue in older versions of Truffle that did not properly handle non-empty directories and we believe it is fixed now.

**Comment by MicahZoltu** [comment]
I don't know, I haven't used Truffle since around the time I opened this (and several other) issues.  I'll defer to others to rule whether this is fixed or not.

**Comment by haltman-at** [comment]
Can anyone confirm whether this is still a problem?

**Comment by fainashalts** [comment]
Closing this for issue maintenance. Please open a new issue if there is still something actionable here. Thanks!

**Comment by muhammadYunas** [comment]
> > My colleague was able to duplicate your issue on both Powershell and Git Bash. It looks like this is specific to using `npx`. Global installs of Truffle don't seem to have the same issue. We'll have to look into this. Thanks for reporting!
> 
> Hi @eggplantzzz I got the same issue, my env:
> 
> > Windows 10  v1903
> > Cmder  v1.3.11
> > Node  v10.16.0
> > Npm  v6.9.0
> 
> What I did?
> 
> ```
> npm i -g truffle
> mkdir myproj
> cd myproj
> echo "xxx" >> README.md
> truffle unbox metacoin
> ```
> 
> If I unbox it in any empty directory , it will be work well.

I'm doing the same thing but its shows this error.

Preparing to download boxect>truffle unbox metacoin
× Downloading
Unbox failed!x...
× Downloading====
Unbox failed!
RequestError: Error: getaddrinfo ENOENT raw.githubusercontent.com
    at new RequestError (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-native\node_modules\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (C:\Users\Younas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.3.2 (core: 5.3.2)
Node v14.16.0
