### ISSUE TITLE
callback in web3

### ISSUE THREAD

**Issue by vaisakh92** [trufflesuite/truffle#2003]
---------------------------

## Issue
callback in for call() myMethod function call doesn't work when for a truffle contract in the test-bed.
What the issue is, in broad strokes.

## Steps to Reproduce
set up truffle with with http://localhost:8545/, 10 accounts
Please provide the shortest amount of steps to reproduce your issue.
```
pragma solidity >=0.4.22 <0.6.0;
pragma experimental ABIEncoderV2;

contract permission {
    /* Define variable owner of the type address */
   enum Status {pending,rejected,accepted}

    struct transaction {
        address payable sender;
        address receiver;
        string datatype;
        Status status;
    }
    
    modifier condition(bool _condition) {
        require(_condition);
        _;
    }
    
    modifier onlyUser(address _address){
        require(_address == msg.sender,"only user transactions");
        _;
    }
    
    transaction[] transactions;
    transaction[] temp;
    function newTransact(address _address,string memory _datatype) public{
        transaction memory newTransaction = transaction({sender:msg.sender,receiver:_address,datatype:_datatype,status:Status.pending});
        transactions.push(newTransaction);
    }
    
    /* This constructor is executed at initialization and sets the owner of the contract */
    
    event Updated(Status _status);
    
    function findTransactions(address _address) public returns(transaction[] memory,uint256 ) {
        transaction memory tmp;
        uint256 i=0;
        uint256 j = 0;
        for(i =0; i<transactions.length; i++){
            if((transactions[i].receiver == _address) && (transactions[i].status == Status.pending)){
                tmp = transactions[i];
                temp.push(tmp);
                j = j + 1;
            }
        }    
        return(temp,j);
    }
    function findTransaction(address _sender,address _address,uint256 _data) public onlyUser(_address) {
        uint256 i;
        for(i =0; i<transactions.length; i++){
            if((transactions[i].sender == _sender) && (transactions[i].receiver == _address) && (transactions[i].status == Status.pending)){
                if (_data == 2){
                    transactions[i].status = Status.accepted;
                }
                else if (_data == 1){
                    transactions[i].status = Status.rejected;
                }
                emit Updated(transactions[i].status);
                break;
            }
        }    
    }
   
     function findTransactionsCount(address _address) public view returns(uint256 cnt) {
        uint256 j = 0;
        uint256 length = transactions.length;
        for(uint256 i =0; i<length; i++){
            if((transactions[i].receiver == _address) && (transactions[i].status == Status.pending)){
                j= j +1;
            }
        }    
        return(j);
    }

    function getTransactions() public view returns(transaction[] memory) {
        return(transactions);
    }
    function getTransactionCount() public view returns(uint256 cnt) {
        uint256 len = transactions.length;
        return(len);
    }
}   
 ```
solidity code it works fine tested in directly 
2 in a nodeJS program 
```
var Web3 = require('web3')
var assert = require('assert');

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

var accounts;
var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');

web3.eth.getAccounts().then(async function(res){

    var admin = res[9];
    var receiver = res[1];
    var sender = res[3];
    accounts = res;
    
    contract.deploy({
        data:bytecode
    }).send({
        from : admin,
        gas: 4712388,
        gasPrice: 100000000000
    }, (error,transactionHash) => {
      console.log(error,transactionHash)
                        
    }).on('receipt',(receipt) =>{
        
    }).then((instance)=>{

    })
    const receipt = await contract.methods.newTransact(receiver,'dob').send({from:sender},(error,transactionHash)=>{console.log(error,transactionHash)});
    const rec = contract.getTransactionCount.call().then((resu)=>{
        console.log(resu);

    });

    });
    
```
## Expected Behavior

What you expected to happen.
1 A set function using the newTransact() function which is fine in working condition
2 a call function using getTransactionCount() to show the result using the callback.
## Actual Results
1 sucessfully executed.
2. no response the callback it does not execute.
What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: ubuntu 16.04 LTS
* Ethereum client: 
* Truffle version (`truffle version`): ganache V 2.0.1
* node version (`node --version`): 11.14.0
* npm version (`npm --version`):  6.7.0

**Comment by eggplantzzz** [comment]
You have some problems with your javascript. I would recommend avoiding using callbacks, 'then's, AND async/await syntax. It gets very hard to reason about. I don't think all of your async stuff is very clean and I think things might be a bit out of whack.

Try untangling things a bit and structuring your code something like this:
```
    contract.deploy({
        data:bytecode
      }).send({
        from : admin,
        gas: 4712388,
        gasPrice: 100000000000
      }, (error, transactionHash) => {
        console.log(error,transactionHash);      
      }).then((instance)=>{
        return instance.methods.newTransact(receiver,'dob').send({from:sender});
      }).then(receipt => {
........
```
Or if you want to use async/await, like this:
```
    const instance = await contract.deploy({ data:bytecode}).send({
        from : admin,
        gas: 4712388,
        gasPrice: 100000000000
    });
    const result = await instance.methods.newTransact(receiver,'dob').send({from:sender});
      console.log("something with result --> %o", result);
........
```

**Comment by eggplantzzz** [comment]
Also, deploy is async so you need to wait until it is finished deploying before you can send transactions. So currently your transaction call will probably try to run before the contract is deployed and this will cause a problem.

**Comment by vaisakh92** [comment]
> Also, deploy is async so you need to wait until it is finished deploying before you can send transactions. So currently your transaction call will probably try to run before the contract is deployed and this will cause a problem.

hi @eggplantzzz, now this is what i did 
```
var Web3 = require('web3')
var assert = require('assert');

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];


var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
async function setup(){
    const accounts = await  web3.eth.getAccounts().then(res=>{return res;})
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
    const xl = await contract.deploy({ data: bytecode })
    const bb =  xl.send({from: admin,gas: 4712388,gasPrice: 100000000000}).then(inst=>{return inst})
    const bl = bb.methods.newTransact(receiver, 'dob').send({from: sender},(error, transactionHash) => {console.log(error,transactionHash);});
}
setup();
```
now a transaction hash is generated for 1st send() then
_(node:11340)_ UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'newTransact' of undefined
    at setup (/home/maddy/naisam/backend-server/cloudstorage/backend/routes/filesrec.js:20:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:11340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code_
is the warning then its just waits for me to exit the program . is it some connecticvity issue or program logic issue please help

**Comment by eggplantzzz** [comment]
If you are going to write all that in an async function, I would recommend against using `then`. I think there are still some problems with when things are being executed. Probably do this:
```
const bb =  await xl.send({from: admin,gas: 4712388,gasPrice: 100000000000});
const bl = await bb.methods.newTransact(receiver, 'dob').send({from: sender},(error, transactionHash) => {console.log(error,transactionHash);
```

**Comment by vaisakh92** [comment]
> If you are going to write all that in an async function, I would recommend against using `then`. I think there are still some problems with when things are being executed. Probably do this:
> 
> ```
> const bb =  await xl.send({ from: admin, gas: 4712388, gasPrice: 100000000000 });
> const bl = await bb.methods.newTransact(receiver, 'dob').send({ from: sender },(error, transactionHash) => { console.log(error, transactionHash) });
> ```
> 
> Something like that makes sure that values are set before they are accessed later in the code.

Hi the issue that I found is that the send() method is behaving like a infinte loop in my terminal for and it would just wait on it to complete but i need it to complete becuase the data get part needs to work after  that, also without using async i cannot assign the return variables to other variables even for the 
```
       const accounts = await  web3.eth.getAccounts().then(res=>{return res;})

```
this assignment only  works if it is async under normal cases it will return a promise event where furhtur usage of these address results in null values.{refer the screenshot attached below.}
![Screenshot from 2019-05-12 17-00-58](https://user-images.githubusercontent.com/26114073/57581616-8a624f00-74d7-11e9-9403-0a8b7b30f74a.png)

**Comment by vaisakh92** [comment]
Hi @eggplantzzz , thank for that but still the problem of call() returns null persists.
```
function getTransactionCount() public view returns(uint256 cnt) {
        uint256 len = transactions.length;
        return(len);
    }
```
the above solidity code is called as :
```
const bl = contract.methods.newTransact(receiver, 'dob').send({from: sender},(error,transactionHash)=>{console.log('e',error,transactionHash);});
const br = contract.methods.getTransactionCount().send({from:sender}).then(rlt=>{console.log(rlt)})
```
the value that results is null
I cannot get back the value in the contract not even the dafault value 0.

**Comment by eggplantzzz** [comment]
Sorry, I'm not really sure what you are asking about now. Can you pose your question again and simplify it so it is very clear to see what is not working?

**Comment by vaisakh92** [comment]
> Sorry, I'm not really sure what you are asking about now. Can you pose your question again and simplify it so it is very clear to see what is not working?
```
const by = await contract.methods.getTransactionCount().call();
```
the return value of this call is null after explicit insertion into the contract.

**Comment by eggplantzzz** [comment]
Can you provide a more complete example of your code. I can't see what transactions is etc.

**Comment by vaisakh92** [comment]
```
var Web3 = require('web3')

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

async function setup(){
    var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
    const accounts = await  web3.eth.getAccounts().then(res=>{return res;})
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
    const xl = contract.deploy({ data: bytecode })
    const bb = xl.send({from: admin,gas: 4712388,gasPrice: 100000000000},(error,transactionHash)=>{console.log('w',error,transactionHash);}).then(inst=>{return inst}).catch(err=>{console.log});
    const bl = contract.methods.newTransact(receiver, 'dob').send({from: sender},(error,transactionHash)=>{console.log('e',error,transactionHash);});
    const br = await contract.methods.getTransactionCount().call();
    const bt = contract.methods.newTransact(receiver, 'aadhar').send({from: sender},(error,transactionHash)=>{console.log('r',error,transactionHash)}).then(con=>{console.log});
    const by = await contract.methods.getTransactionCount().call();
    console.log(by,br);
}
setup();
```
@eggplantzzz  this is the complete nodejs program the solidity file is given above.

**Comment by eggplantzzz** [comment]
It's probably because you are not "await"ing your transactions and that code is trying to run out of order. To make everything that is happening clearer, I would recommend you NOT to use BOTH async/await syntax and "then". So for example, get rid of all the "then"s you have there (and probably all the callbacks passed in the function calls) and just use await. You need to await async functions so they have time to complete before you run the rest of the code. Otherwise everything gets run out of order and values that you expect to be set have not been set.

Also spend some time formatting your code more regularly so that it is a bit more readable. I think that will help you debug it.

**Comment by eggplantzzz** [comment]
And just another note...basically every call you make in there needs to be "await"ed starting with `const xl = await contract.deploy({ data: bytecode });`.

**Comment by vaisakh92** [comment]
> It's probably because you are not "await"ing your transactions and that code is trying to run out of order. To make everything that is happening clearer, I would recommend you NOT to use BOTH async/await syntax and "then". So for example, get rid of all the "then"s you have there (and probably all the callbacks passed in the function calls) and just use await. You need to await async functions so they have time to complete before you run the rest of the code. Otherwise everything gets run out of order and values that you expect to be set have not been set.
> 
> Also spend some time formatting your code more regularly so that it is a bit more readable. I think that will help you debug it.

```
var Web3 = require('web3')

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

async function setup(){
    var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
    const accounts = await  web3.eth.getAccounts().then(res=>{return res;})
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
  
    const xl = await contract.deploy({ data: bytecode }).send({from: admin,gas: 4712388,gasPrice: 100000000000});
    //set data
    const bl = await contract.methods.newTransact(receiver, 'dob').send({from: sender});
    //get data
    const br = await contract.methods.getTransactionCount().call();
    
    console.log(xl,bl,br)
}
setup();
```
![Screenshot from 2019-05-14 22-56-27](https://user-images.githubusercontent.com/26114073/57718711-a44c8f00-769b-11e9-95d8-1dde260fcdb5.png)
still the same thing/

**Comment by eggplantzzz** [comment]
That is definitely not the same thing! One of your calls is failing for some reason. You'll have to log and figure out which promise is being rejected.

**Comment by eggplantzzz** [comment]
Also, the web3 docs say that `contract.deploy(` returns a new contract instance. You might need to call transactions with that object rather than the original `contract` that you set at the start of that function.

**Comment by fainashalts** [comment]
Hi @vaisakh92 are you still having issues with web3? Let us know, thanks!

**Comment by vaisakh92** [comment]
> That is definitely not the same thing! One of your calls is failing for some reason. You'll have to log and figure out which promise is being rejected. Once you figure out which call is failing it should be easier to focus on that part and figure out what is causing it to fail.
> 
> Also, `web3.eth.getAccounts` returns a Promise that resolves with the accounts. It is thenable, but that doesn't mean you need a then at the end. The `then` is not doing anything, remove it :)

but without that  `then` I cannot access the accounts 
```
const accounts = await  web3.eth.getAccounts().then(res=>{return res;})
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
  ```
without the then the variables admin,reciever and sender will return null and cannot be used.
```
var Web3 = require('web3')

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

async function setup(){
    var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
    const accounts = await  web3.eth.getAccounts().then(res=>{return res;})
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
  
    const xl =  contract.deploy({ data: bytecode })
    const bk =  xl.send({from: admin,gas: 4712388,gasPrice: 100000000000}).then(res=>{return res;});
    //set data
    const bl = xl.methods.newTransact(receiver, 'dob').send({from: sender}).then(res=>{return res;});
    //get data
    const br = contract.methods.getTransactionCount().call().then(res=>{return res;});
    
    console.log(xl,bk)
}
setup();
```
please not for `const xl` and `const bk` in the above code.
for `const bl` an error thrown as : TypeError: Cannot read property 'newTransact' of undefined

**Comment by eggplantzzz** [comment]
`accounts` will be set as it returns a promise that resolves with the accounts. Just `const accounts = await web3.eth.getAccounts();` is enough. The same goes for `xl.send(....`, `xl.methods.newTransaction(...`, and `contract.methods.getTransactionCount().call();`. They are ALL async methods and you will have to `await` them.

**Comment by vaisakh92** [comment]
```
var Web3 = require('web3')

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

async function setup(){
    var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
    const accounts = await  web3.eth.getAccounts();
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
  
    const xl =  await contract.deploy({ data: bytecode })
  
    const bk =  await xl.send({from: admin,gas: 4712388,gasPrice: 100000000000});
    //set data
    const bl = await contract.methods.newTransact(receiver, 'dob').send({from:sender});
    //get data
    const br = await contract.methods.getTransactionCount().call();
    
    console.log(xl,bk);
}
setup();
```
still promise rejection error in send function.
if we use the contract instance that is created on `.methods.getTransactionCount()` then it returns the instance returns .getTransactionCount as undefined.

**Comment by eggplantzzz** [comment]
I believe you will have to send transactions using the instance that web3 returns. In other words, use `xl` as your contract instance and call methods from it instead of `contract`. I hope that helps.

**Comment by vaisakh92** [comment]
> I believe you will have to send transactions using the instance that web3 returns. In other words, use `xl` as your contract instance and call methods from it instead of `contract`. I hope that helps.

```
var Web3 = require('web3')

const web3 = new Web3('http://127.0.0.1:8545')

json = require('./../../../build/contracts/permission.json');

const interface = json['abi'];
const bytecode = json['bytecode'];

async function setup(){
    var contract =  new web3.eth.Contract(interface,'0xBcf2D22144C11C20B31A7Aa84875414B252a92DB');
    const accounts = await  web3.eth.getAccounts();
    const admin = accounts[9];
    var receiver = accounts[1];
    var sender = accounts[3];
  
    const xl =  await contract.deploy({ data: bytecode })
  
    const bk =  xl.send({from: admin,gas: 4712388,gasPrice: 100000000000});
    //set data
    const bl = xl.methods.newTransact(receiver, 'dob');
    //get data
    const br = xl.methods.getTransactionCount().call();
    
    console.log(xl,bk);
}
setup();
```
![Screenshot from 2019-05-28 11-58-27](https://user-images.githubusercontent.com/26114073/58455723-013a5180-8140-11e9-9666-55cb935f0a89.png)

**Comment by eggplantzzz** [comment]
What is this call to `send` doing? Is that really a method on the contract object?
What is `xl` after you deploy it? Log it, does it look like a contract instance? Again, all those methods are `async` so you will have to await them.

**Comment by vaisakh92** [comment]
> What is this call to `send` doing? Is that really a method on the contract object?
> What is `xl` after you deploy it? Log it, does it look like a contract instance? Again, all those methods are `async` so you will have to await them.

the xl object is
```
{ [Function: ContractMethod]
  call: { [Function] request: [Function] },
  send: { [Function] request: [Function] },
  estimateGas: [Function],
  encodeABI: [Function] }
```
contract instance of the contract mentioned in the code above.
but still using the send function to communicate with truffle is not working.

**Comment by eggplantzzz** [comment]
At this point, this issue actually has nothing really to do with Truffle actually. You are not really using Truffle :) You are in Web3 land. You should probably check out the web3 docs to help you do what you are trying to do. Here are the docs for web3 contract objects https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html

**Comment by eggplantzzz** [comment]
Closing this for maintenance.
