### ISSUE TITLE
Feature Request: Copy option

### ISSUE THREAD

**Issue by B5Happy** [trufflesuite/truffle#2010]
# Feature 

I think it would be nice to have a copy option after a right click.

![Ganache](https://user-images.githubusercontent.com/39341595/57575809-8e5a8680-746f-11e9-8a71-2f646ae97f3c.png)

**Comment by gnidan** [comment]
Hey! This is not the best repo for this request. Could you please reopen this on github.com/trufflesuite/ganache?

Good idea though :)
