### ISSUE TITLE
truffle debug giving me an error 'join(...tasks) is not supported any more'

### ISSUE THREAD

**Issue by SEFI2** [trufflesuite/truffle#2013]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Getting an error message, while executing the debug command with truffle.
The error might be related to redux-saga, as may be understood from the message itself.
I am getting the same error for all transactions.

## Steps to Reproduce

I was trying to debug the transaction with command truffle debug tx_hash, then I started to face the error message

## Expected Behavior
It had to open the debugger console with truffle

## Actual Results
```
join(...tasks) is not supported any more. Please use join([...tasks]) to join multiple tasks.
    at join (/usr/local/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-e922c950.js:565:1)
```
## Environment

* Operating System: Ubuntu 18.04.2 LTS
Ganache(Ganache-2.0.2-beta.0)
npm (6.9.0)
Truffle v5.0.10 (core: 5.0.10)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37

**Comment by haltman-at** [comment]
Hm, this is very odd.  I can't find anywhere in the code where we call `join` with multiple arguments.  I can change that part to take an array, just to be certain, and hopefully that will fix your problem?  We'll see, I suppose.

**Comment by SEFI2** [comment]
Thank you very much for the quick response. I hope I can get it to work then.

**Comment by gnidan** [comment]
This should be released now! Could you upgrade and see if the problem is solved? Thanks!

**Comment by SEFI2** [comment]
Great, now it is working!!! Thanks!

**Comment by CruzMolina** [comment]
Woohoo!
