### ISSUE TITLE
Incorrect nonce after invalid txns made in try / catch blocks 

### ISSUE THREAD

**Issue by Anyhowclick** [trufflesuite/truffle#2016]
- [O] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
It seems that the nonce doesn't update for txs made in try / catch blocks, when I'm using `truffle-hdwallet-provider` as the provider.

## Steps to Reproduce
1. Simple example included in the zip folder. 
[truffleIssue.zip](https://github.com/trufflesuite/truffle/files/3175575/truffleIssue.zip)
Sample test contract: `Test.sol`
Sample test script: `test.js` 

2. Run `ganache-cli --accounts 10 --defaultBalanceEther 1000 --mnemonic 'gesture rather obey video awake genuine patient base soon parrot upset lounge' --networkId 5777 --debug` in 1 terminal

3. In another terminal, CD to the unzipped folder, do `truffle test` 

## Expected Behavior
All 3 test cases should have passed.

## Actual Results
Only the first 2 test cases pass, the last doesn't because of an expected reverting tx performed in a try / catch block that causes the account nonce to be updated, but not the subsequent tx nonce.
![image](https://user-images.githubusercontent.com/12406924/57666468-99a9df80-7632-11e9-8d7c-3ddf49fd4c63.png)

## Environment

* Operating System: macOS Mojave v10.14.3
* Ganache version: ganache-cli@6.4.1 
* Truffle version (`truffle version`): truffle@5.0.17 
* node version (`node --version`): v11.3.0
* npm version (`npm --version`): 6.4.1

**Comment by CruzMolina** [comment]
Hey @Anyhowclick, what version of `truffle-hdwallet-provider` are you using?

**Comment by CruzMolina** [comment]
Nm! Thanks for the project link!

`truffle-hdwallet-provider` is meant for live deployments (externally signs transactions using the account index specified). You'll notice commenting out the custom provider and setting your config like so _should_ work on your end:
```
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*',
      gas: 6721975,
      gasPrice: 20000000000,
      confirmations: 0,
      timeoutBlocks: 50,
      skipDryRun: true,
    }
  ....
}
```

**Comment by Anyhowclick** [comment]
Hmmmm alright. How do I go about deterministically generating accounts for my truffle tests though? Or is there a way to access the private keys of the generated accounts? I require the private keys for signature generation and verification.
