### ISSUE TITLE
Reduce Truffle's startup weight

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2038]
## Issue

truffle-core's `cli.js` does a lot of `require`ing!

<details>
  <summary>See <code>require()</code> graph.</summary>
  <img src="https://user-images.githubusercontent.com/151065/58066000-9ee8bc00-7b55-11e9-970f-7ff17b3dd236.png" />
</details>

## Steps to Reproduce

Run `truffle`.

Generate this graph with the following command (using [madge](https://github.com/pahen/madge)):
```sh
$ madge \
    --json \
    --includeNpm \
    --rankdir=LR \
  packages/truffle-core/cli.js \
    | sed -E 's/"([a-z])/"\.\/\1/g' \
    | sed 's/"\.\.\/\.\.\/node_modules\//"/g' \
    | madge --stdin --image deps.png --no-color
```

## Expected Behavior

`cli.js` should require as little as possible, to make startup time fast, as well as to isolate problems with node_modules that can't be found in commands that aren't invoked.

Also, `require("web3")` probably shouldn't be happening at startup every time.

**Comment by gnidan** [comment]
On further inspection, some of these module requires might actually be guarded inside functions... but many of them are not.

**Comment by eggplantzzz** [comment]
PR #2043 addressed this issue.

**Comment by haltman-at** [comment]
Closing this to move things to #3509.
