### ISSUE TITLE
Support multiple contracts in the same file

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#204]
Truffle current expects you to separate all contracts into separate files, although that's not explicitly required by Solidity. See #86. That PR is now out of date with Truffle 2.0, but we should still support the feature.

Tasks: 
- [ ] Ignore the file name and instead use the results of compilation to determine which contract abstractions (`.sol.js` files) to create.
- [ ] Remove requirement that there must be a contract within the `.sol` file that matches the file name.

**Comment by shayanb** [comment]
+1

**Comment by tcoulter** [comment]
This is done! Cheers!
