### ISSUE TITLE
waiting for contract change

### ISSUE THREAD

**Issue by tcurdt** [trufflesuite/truffle#2055]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The test successfully calls a setter but the getter does not read the set value.

## Steps to Reproduce

Here is a super simple contract.

```solidity
contract Center {

  string private name;

  function setName(string memory newName) public {
    name = newName;
  }

  function getName() public view returns (string memory) {
    return name;
  }
}
```

This is the test testing the setter/getter

```javascript
const Center = artifacts.require("Center")

contract("Center", async accounts => {

  it("can set name", async () => {
    const name = "name"
    const center = await Center.new()
    await center.setName.call(name)
    expect(await center.getName.call()).to.equal(name)
  })
})
```
## Expected Behavior

The test should succeed.

## Actual Results

While the setter gets called fine the getter does not return the set value.
From reading the docs I could not see what's wrong with it but I have the feeling this is a user error.

## Environment

* Operating System: macOS 10.13.6
* Ethereum client:
* Truffle version (`truffle version`): v5.0.18 (core: 5.0.18)
* node version (`node --version`): v10.15.3
* npm version (`npm --version`): 6.4.1

**Comment by gnidan** [comment]
When you do `center.setName.call()`, it forces it to be a read-only "call". If you leave that off and do only `center.setName()` or `center.getName()`, it'll detect the former as state-modifying and the latter as read-only, and do the correct behavior.

(If you want to force a transaction, you can do that with `center.setName.sendTransaction()`... these docs might help: https://truffleframework.com/docs/truffle/getting-started/interacting-with-your-contracts)

Hope this helps!

**Comment by gnidan** [comment]
(If it doesn't help, just reply so and I'll reopen. Thanks!)

**Comment by tcurdt** [comment]
@gnidan Thanks, that helped! I wasn't aware of the difference of `center.setName.call()` vs `center.setName()`.

Somewhat related to the `sendTransaction` - is there a way to get to the address from the transaction? That could maybe help me to work around [this issue](https://github.com/trufflesuite/truffle/issues/2045) as well.

**Comment by gnidan** [comment]
Effectively you can't get return values from transactions, the way you can with calls. The "right way" to get data out of transactions like that is to use Solidity events (`emit` keyword in Solidity).

That seems to be the problem you're running into in your other issue... I'll try to get the chance to follow up with specific JS syntax examples when we're back in business tomorrow (US holiday today). The "Interacting with your contracts" docs page I linked above might have the info, or you might find it below that  under Reference -> Contract abstractions. Let me know if you get it sorted out!

**Comment by tcurdt** [comment]
@gnidan at least in my mind events are a totally different mechanism - unrelated to this use case.
There is no way for listen for events in contracts so a factory seems to the one of the few approaches to keep track of created contracts - that I know of.

I managed to get the address and by that the contract from the transaction (see the update on the other issue) but it feels like big fat brittle hack.

**Comment by tcurdt** [comment]
Just for the records - the following works fine:
```
const Center = artifacts.require("Center")

contract("Center", async accounts => {

  it("can set name", async () => {
    const name = "name"
    const center = await Center.new()
    await center.setName(name)
    expect(await center.getName()).to.equal(name)
  })
})
```
