### ISSUE TITLE
VM Exception while processing transaction: revert on Ether transfer

### ISSUE THREAD

**Issue by calvinlauco** [trufflesuite/truffle#2068]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
- [x] I've tried the solution in similar issue https://github.com/trufflesuite/truffle/issues/748 before filing this issue.

---------------------------

## Issue
Given a contract with a very simple `payable` function, when I try to `sendTransaction` from ganache account with more than sufficient gas to the Contract, I get the following error:

```
VM Exception while processing transaction: revert
```

I tried to send with a large gas as well as with the estimated one (around 21046), but the error still exists.

## Steps to Reproduce

1. `truffle init`
2. Create the following contract under `./contracts`
Test.sol
```
pragma solidity 0.5.8;

contract Test {
    function deposit() public payable {}
}
```
3. Create the following migration under `./migrations`
2_deploy_contract.js
```
const Test = artifacts.require("Test");

module.exports = function(deployer) {
    deployer.deploy(Test);
};
```
4. `$ truffle develop`
5. `$ migrate`
6. Transfer Ether to it
```
$ await web3.eth.sendTransaction({
    from: accounts[0],
    to: bankInstance.address,
    value: oneEtherInWei,
    gas: "4712388"
})
```
7. Error returns
```
Error: Returned error: VM Exception while processing transaction: revert
```

## Expected Behavior

I expect the transaction should go through successfully and the Ether should be transferred to the contract.

## Actual Results

Received the error
```
Error: Returned error: VM Exception while processing transaction: revert
```

## Environment

* Operating System: MacOS
* Ethereum client: Web3.js v1.0.0-beta.37
* Truffle v5.0.20 (core: 5.0.20)
* Solidity v0.5.0 (solc-js)
* Node v10.15.3

**Comment by gnidan** [comment]
Hm. Looks like there's a mismatch between your contract and the way you're sending transactions.

If you just do a regular `sendTransaction`, it's going to invoke the "fallback function". If you change your `deposit` function to be this fallback function, you shouldn't see the revert:

```solidity
pragma solidity 0.5.8;

contract Test {
    function () public payable {}
}
```

Alternatively, if you want to keep the name `deposit`, you can invoke this function in JS as follows (using truffle-contract syntax):

```javascript
const bankInstance = await Test.deployed();
await bankInstance.deposit({
  from: accounts[0],
  value: oneEtherInWei,
  gas: "4712388"
})
```

Let me know if this helps!

**Comment by calvinlauco** [comment]
Thanks, this is exactly the problem. Sorry for the stupid question. Closing this issue now.
