### ISSUE TITLE
Error on deployment of the Migration.sol contract to parity

### ISSUE THREAD

**Issue by aawaken** [trufflesuite/truffle#2075]
I try to deploy to my local parity node using 'truffle deploy' and I get the following error on deployment of the Migration.sol contract:

> Saving migration to chain.Error: Error: StatusError: Transaction: 0x5880cd00f7f616bca41e335f6606de2ff82b0dfdf56d02717e19103734cd0ce3 exited with an error (status 0). 
>      Please check that the transaction:
>      - satisfies all conditions set by Solidity `require` statements.
>      - does not trigger a Solidity `revert` statement.
> 
>     at Object.run (/home/andre/.nvm/versions/node/v12.3.1/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
>     at processTicksAndRejections (internal/process/task_queues.js:89:5)
> Truffle v5.0.20 (core: 5.0.20)
> Node v12.3.1
>

_Originally posted by @aawaken in https://github.com/trufflesuite/truffle/issues/1241#issuecomment-498734968_

**Comment by aawaken** [comment]
Downgrade to Truffle 5.0.5 helps.
Doesn't work with Truffle 5.0.6, 5.0.7, 5.0.10, 5.0.20.

**Comment by eggplantzzz** [comment]
@aawaken Can you confirm that this is still an issue on the latest Truffle (version 5.1.16)?

Is there something different about your `Migrations.sol`? If you could provide a repo and reproduction steps so that we can try and troubleshoot it?

**Comment by gnidan** [comment]
Closing this for issue maintenance, but if you can get us reproduction steps, we'd love to be able to help figure this out. Let us know, and we'll re-open! Thanks!
