### ISSUE TITLE
`Truffle test` should allow user to run a specific test using `mocha -g`

### ISSUE THREAD

**Issue by onggunhao** [trufflesuite/truffle#2080]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

Following up from Twitter conversation with @gnidan - ref https://twitter.com/gnidan/status/1136386257481863169

---------------------------

## Issue

We should have a way to run individual truffle tests, similar to how `mocha -g` works (greps for a test string).
* There is an alternative way to do this by specifying `.only` in Mocha tests
* Being able to pass in `-g` allows us to run specific tests, e.g. in CI

## Steps to Reproduce

```
truffle test -- -g "name of test"
```

## Follow-ups

I'll be working on this, which is similar to issue #7 opened by @oed.

**Comment by onggunhao** [comment]
@gnidan, I splunked through the codebase. Can I ask for your feedback on developer UX and codebase intuition?

# Developer experience

```shell
usage:
      "truffle test [<test_file>] [--compile-all] [--network <name>] [--verbose-rpc] [--show-events] **[--grep]**",
    options: [
      {
        option: "--grep",
        description:
          "Only run tests matching this string or regexp, similar to `mocha --grep`"
      },
```

# Implementation

The flow of execution of `truffle test` is the following (all in `truffle-core`):
-> `cli.js:45` & `lib/command.js:110-113`: parses args into `options` object
-> `lib/commands/test.js:112`: 

) and sends it to `command.run` (:56)  
-> `lib/command.js:run` parses args into options object (:110), passes it to `lib/commands/test.js` (:113)
-> `lib/commands/test.js` passes it to 

`/truffle-core/lib/commands/test.js` parses arguments from `truffle-core/cli.js`:
- [ ] Isolate the `-g` flag from arguments 

`

**Comment by onggunhao** [comment]
@gnidan, I splunked through the codebase. Can I ask for your feedback on developer UX and codebase intuition?

# Developer experience

```shell
usage:
      "truffle test [<test_file>] [--compile-all] [--network <name>] [--verbose-rpc] [--show-events] **[--grep]**",
    options: [
      {
        option: "--grep",
        description:
          "Only run tests matching this string or regexp, similar to `mocha --grep`"
      },
```

# Implementation

I'm fairly inexperienced with javascript + mocha - so writing the code splunk trail here:

The flow of execution of `truffle test` is the following (all in `truffle-core`):
-> `cli.js:45` & `lib/command.js:110-113`: parses args into `options` object
-> `lib/commands/test.js:112`: collates `config` object (:114) 
-> `lib/test.js:58`: creates mocha test with config files (:143). To implement grep, `mochaConfig.grep` needs to be set to arg values

**Comment by eggplantzzz** [comment]
@onggunhao I believe you can just use the path to the test file as an argument and it should work. For example `truffle test ./test/mySpecificTest.sol`.

**Comment by eggplantzzz** [comment]
@onggunhao Just an FYI, I have a PR out that reworks a lot of the test stuff. It hasn't been merged yet but if might be very relevant to the work you are doing. Check out https://github.com/trufflesuite/truffle/pull/2081

**Comment by onggunhao** [comment]
@eggplantzzz Ah nice work on #2081! I was actually going to offer more of my sabbatical time to ES6-ify the `truffle test` package - the callbacks were really weird to follow (esp. the `environmentCallback` calling `run`)

I'll probably branch from #2081 and follow up from there. Happy to lend a hand on other tasks - doing this as a way to learn

**Comment by eggplantzzz** [comment]
Ok great, I'm going to go ahead and try and get it reviewed and merged for the next release.

**Comment by GregTheGreek** [comment]
Did this ever get worked on? Being able to test a single case is extremely useful in large test files

**Comment by eggplantzzz** [comment]
@GregTheGreek You should be able to just run one test file by passing the path in as follows:
```
truffle test ./test/myFavoriteTestFile.js
```

**Comment by AuHau** [comment]
Any update on this? Running specific test-file is not enough IMO. When you have tens of tests in a file, only one is failing and you have to rerun the whole suite just for that one test. Especially when you work with time-delays...

**Comment by Ankarrr** [comment]
Any update on this?

**Comment by eggplantzzz** [comment]
A workaround you can use is to use `only` on your test and then feed mocha the specific path to that test.

So you can do
```
it.only("returns the value I expect", () => {
  const expectedValue = 10;
  ...
```

And then just run `truffle test ./test/myFavoriteTestFile.js`

Let me know if you think this workaround is not enough and we can consider a more robust solution.

**Comment by littlezigy** [comment]
I'd like this too. I sometimes like to categorize tests with #tags and run them together. I don't like having to go into each test and add `.only`

**Comment by ndroo** [comment]
man, i cannot believe this isn't implemented. Maybe it's time to just give up and move onto different tools. Please...please add this.

**Comment by eggplantzzz** [comment]
Ok, seems about time for this one. I'll try and get it in in one of our next releases! Thanks for the input!

**Comment by gnidan** [comment]
This is now live in Truffle v5.4.2! (See [release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.4.2))

Thanks all!
