### ISSUE TITLE
"Migrations" -- VM Exception while processing transaction: Error: Returned error: This request is not implemented yet

### ISSUE THREAD

**Issue by sunleos** [trufflesuite/truffle#2087]
**## Issue**

While migrating contracts by using "$ truffle migrate --network localnode", I'm getting the error below:

**## Steps to Reproduce**

1. $ truffle migrate --network localnode

## Expected Behavior

The contracts for deployment should be deployed.

## Actual Results

No contracts are deployed. The error below:

`Error:  *** Deployment Failed ***

"Migrations" -- VM Exception while processing transaction: Error: Returned error: **This request is not implemented yet. Please create an issue on Github repo..**

    at /home/ubuntu452/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at <anonymous>
`

## Environment

* Operating System: Windows 10 Pro with "Windows Subsystem for Linux" enabled.
* Ethereum client: Parity Ethereum; version Parity-Ethereum/v2.4.6-stable
* Truffle version (`truffle version`): v5.0.0 (core: 5.0.0)
* node version (`node --version`): v8.9.4
* npm version (`npm --version`): 5.6.0

**My truffle-config.js:**

`module.exports = {
	networks: {
		localnode: { 
			network_id: "*", 
			host: "localhost",
			port: 8545,
			gas: 4700000,
			gasPrice: 100000000000,
		}
	}
};`

**Comment by eggplantzzz** [comment]
@sunleos Do you have your code available on github somewhere? Did you check to make sure it is not legitimately reverting for some reason? Also, could you upgrade to the latest Truffle (v5.0.21)?

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance. If this is still a problem and you have some reproduction steps, please do get back to us and we'll be happy to re-open!
