### ISSUE TITLE
"truffle debug" hangs forever after printing "...stepping"

### ISSUE THREAD

**Issue by itinance** [trufflesuite/truffle#2088]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I want to debug a transaction after tests has run. But when I want to step into a particular function pressing "i" for "step into", the debugger process hangs after printed "...Stepping" into the console.
Although I have waited many minutes, nothing else happened. 

## Steps to Reproduce

Running tests:

```
truffle test
```

One test will raise an revert I want to debug it:

```
truffle debug $transaction
```

where $transation is the particular transaction-id that I have found in the ganache-log.

## Expected Behavior

That I can step into the function with a hanging "Stepping"-process.

## Actual Results

It hangs with "Stepping".

## Environment

* Operating System: 

MacOS Mojave

$ truffle version
Truffle v5.0.20 (core: 5.0.20)
Solidity v0.5.0 (solc-js)
Node v10.16.0
Web3.js v1.0.0-beta.37
npm: 6.9.0

**Comment by gnidan** [comment]
Hm, thanks for bringing this up! We'll look into it.

In the meantime, step `n`ext should be pretty close to what you want. Could you try that?

**Comment by itinance** [comment]
Hi @gnidan , `n` is working. After I pressed `n` some times, also `o` is working then again. But it needs some `n`-stepps to make it work and debuggable.

**Comment by haltman-at** [comment]
OK, I've opened PR #2093, which should fix this.
