### ISSUE TITLE
Cannot use HDWalletProvider with tests.

### ISSUE THREAD

**Issue by hickscorp** [trufflesuite/truffle#2101]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using `HDWalletProvider` so we can use our own mnemonic / private keys, unit tests cannot run.

## Steps to Reproduce

In our truffle configuration:

```js
require('dotenv').config();
const keys = require('./keys');
const HDWalletProvider = require('truffle-hdwallet-provider');
```

Then we declare our networks like so:

```
    development: {
      provider: () => {
        return new HDWalletProvider(keys, 'http://localhost:7545', 0, 10, false /* tried both true and false */);
      },
      // host: 'localhost',
      // port: '7545',
      network_id: '5777',
    },
```

Then migrations work, but unit tests just fail with errors:

```
Error: the tx doesn't have the correct nonce. account has nonce of: 37 tx has nonce of: 36
```

What's really odd is that we're able to run migrations, and from a truffle console issue operations too (Eg instanciate contracts etc).
Another interesting thing, if simply using mnemonic instead of private keys, the exact same things happens.

## Environment

```
Truffle v5.0.22 (core: 5.0.22)
Solidity - 0.5.9 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
```

**Comment by gnidan** [comment]
Huh. Could you provide a repo that we could use to reproduce? (Don't share private keys for real though : ) We'll look into it. Thanks!

**Comment by hickscorp** [comment]
Thanks @gnidan .
Somehow, fiddling around with various versions of web3 fixed the problem... What's quite odd is that when I tried to report back here, it was still on the same versions. Oh well...
