### ISSUE TITLE
Error in OS X

### ISSUE THREAD

**Issue by damianlluch** [trufflesuite/truffle#2122]
- [X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

hi guys, I get this error in OS X with Truffle and not found any results for the error solution.

## Steps to Reproduce

truffle compile

## Expected Behavior

contracts compiled

## Actual Results

Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Compiling your contracts...
===========================
Error: TypeError: Cannot read property 'includes' of null
    at VersionRange.load (/Users/damianlluch/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/compilerSupplier/loadingStrategies/VersionRange.js:201:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.24 (core: 5.0.24)
Node v10.15.0

## Environment

* Operating System: OS X
* Ethereum client: Ganache - Localhost
* Truffle version (`truffle version`): 5.0.24
* node version (`node --version`):v10.15.0
 npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
Well the first thing that occurs to me is that you have two Truffle configs. You should have only one of the following files in the root directory of your project: `truffle.js` or `truffle-config.js` (preferably `truffle-config.js` as that is the current convention). Try removing one and see what happens.

Is your code available somewhere? I would like to see if I can duplicate your error.

**Comment by eggplantzzz** [comment]
Closing for maintenance. Let us know if it needs to be reopened, thanks!
