### ISSUE TITLE
feat: allow setting mocha reporter via CLI

### ISSUE THREAD

**Issue by yxliang01** [trufflesuite/truffle#2124]
mocha has a cool feature that allows the change of reporter for different wanted output formats. However, currently Truffle doesn't support the change of reporter via CLI. I don't think setting the frequently-changing reporter via config is a good idea either. This issue is a feature request that adds a new command line argument to dynamically change the mocha reporter.

Thanks

**Comment by eggplantzzz** [comment]
Thanks for the suggestion, we'll look into it!

**Comment by haltman-at** [comment]
This is now released!
