### ISSUE TITLE
Can't use constructor new

### ISSUE THREAD

**Issue by andrfgs** [trufflesuite/truffle#2126]
I can't guess how to use the new constructor to instantiate a new contract. No documentation is provided for this so it's impossible to guess how to use it.

MyContract.new([arg1, arg2, ...], [tx params])

What is the format of `arg1, arg2, ..., etc`?
And where are the `tx params`?

I'm using the following
`App.contracts[contractName].new([600], {from: App.ethereumAddress});`

But this produces an error:

> Uncaught (in promise) Error: invalid number value (arg="_weiPerBlock", coderType="uint256", value=[600])
    at Object.throwError (truffle-contract.js:51045)
    at CoderNumber.encode (truffle-contract.js:49827)
    at truffle-contract.js:50079
    at Array.forEach (<anonymous>)
    at pack (truffle-contract.js:50078)
    at CoderTuple.encode (truffle-contract.js:50238)
    at AbiCoder.encode (truffle-contract.js:50371)
    at ABICoder.encodeParameters (truffle-contract.js:51539)
    at truffle-contract.js:52198
    at Array.map (<anonymous>)

How am I supposed to know how to use the method if no documentation is provided? The truffle docs also don't list anything about this.

**Comment by andrfgs** [comment]
After some hours testing, it seems that passing the argument as such works:
`App.contracts[contractName].new("500", {from: App.ethereumAddress})`

But now I discovered a bug. When instancing a contract with multiple arguments, the constructor fails. The following code:
`App.contracts[contractName].new("400", "4", "100", "900", {from: App.ethereumAddress})``

Fails with error:
> error Error: The send transactions "from" field must be defined!
    at Method.inputTransactionFormatter (truffle-contract.js:47195)
    at truffle-contract.js:48462
    at Array.map (<anonymous>)
    at Method.formatInput (truffle-contract.js:48460)
    at Method.toPayload (truffle-contract.js:48495)
    at Eth.send [as sendTransaction] (truffle-contract.js:48785)
    at truffle-contract.js:60854

And the contract has exactly 4 arguments. So this is probably a mistake when searching for th `tx params` argument.

**Comment by eggplantzzz** [comment]
It is correct that you should pass the values in order like 
```
App.contracts[contractName].new("400", "4", "100", "900", {from: App.ethereumAddress})
```
I think the problem might be in your project, make sure that `App.ethereumAddress` is defined. I tried to duplicate your problem with a simple toy app but I couldn't. Try logging and making sure that address is good and let me know!

**Comment by andrfgs** [comment]
Address is good, I'm showing it as well in a label and it matches the currently selected account on Metamask. Would you like a zip of the project?

**Comment by eggplantzzz** [comment]
Do you have it up on github somewhere so that I can take a look?

**Comment by eggplantzzz** [comment]
@andrfgs Did you end up resolving the issue you had?

**Comment by andrfgs** [comment]
I am sorry. I have been away from the computer and had eventually forgotten about the issue. I can't post a project now but I will do so in the near future. And no I have not been able to solve the issue.

**Comment by eggplantzzz** [comment]
That's alright! When you get it posted, let me know and I'll be happy to take a look.

**Comment by andrfgs** [comment]
Here is the repository:
https://github.com/andrfgs/auction-ethereum

This project implements 3 simple auctions, a normal English Auction, a Vickrey Auction and a Dutch Auction. The auction I was trying to create was the English Auction.

The relevant file here is **`src/js/app.js`**
The `App.deployContract(contractName, onDeploy, ...args)` serves to create a new contract (this method doesnt really deploy, just creates an instance of the contract). Right now, I was experimenting with constant values ignoring the `args` because as I said above, I can't get this to work.

Using constant values the error is now:
> error Error: The send transactions "from" field must be defined!

I have no ideia then how to pass the arguments because it seems it's missing the from field, but I have no idea where should I put it,

**Comment by andrfgs** [comment]
I am using Ganache as a local testing blockchain.

The truffle contracts were already migrated. I am also using **Lite Server** to test the website.

1. Run Ganache
2. Open a browser like Chrome with Metamask extension installed and configured to use a fake account from Ganache
3. Execute `npm run dev` to start the server on the root folder
4. Open the browser on `localhost:3000`


According to the browser's console, everything runs nice and all except for the contract creation. The contract method is called automatically on page load. No interaction is needed with the GUI.

**Comment by andrfgs** [comment]
Thank you very much, so the problem is on the ethereumAddress setup and not on how I am constructing the contract right?

Thank you so much!

**Comment by andrfgs** [comment]
Thank you very much for the input.
