### ISSUE TITLE
On create a contract: VM Exception while processing transaction: out of gas

### ISSUE THREAD

**Issue by rotcivegaf** [trufflesuite/truffle#2130]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't deploy the [collateral contract](https://github.com/ripio/rcn-network/blob/rcn_burner/contracts/core/diaspore/cosigner/Collateral.sol), ganache-cli give me `VM Exception while processing transaction: out of gas`

If start ganache-cli with `--allowUnlimitedContractSize true` the deploy works, and can log the deployedBytecode length:
   ```console.log(collateral.constructor._json.bytecode.length); // 49478```
and the gasUsed:
```console.log((await web3.eth.getTransactionReceipt(collateral.transactionHash)).gasUsed); // 6808544```

I think the optimizer its not on when use `truffle test` but in the [truffle config](https://github.com/ripio/rcn-network/blob/rcn_burner/truffle.js) have:
```
...
            settings: {
                optimizer: {
                    enabled: true,
                    runs: 200,
                },
                evmVersion: 'constantinople',
            },
...
```
I can deploy the [collateral contract](https://github.com/ripio/rcn-network/blob/rcn_burner/contracts/core/diaspore/cosigner/Collateral.sol) in remix with optimizer on 

## Steps to Reproduce

Clone the repo: `git clone https://github.com/ripio/rcn-network.git`
On terminal: 
```
cd rcn-network
git checkout rcn_burner
npm install
node_modules/.bin/ganache-cli --gasLimit 7000000
```
In other terminal:
```
node_modules/.bin/truffle test
```
Can check the error in circleci [test](https://circleci.com/gh/ripio/rcn-network/4262?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

## Expected Behavior

Deploy the collateral contract and test it.

## Actual Results

Return this exception: `VM Exception while processing transaction: out of gas`

## Environment

* Repo: [rcn_burner branch](https://github.com/ripio/rcn-network/tree/rcn_burner)
* Operating System: Linux
* Truffle version: v5.0.24 (core: 5.0.24)
* Solidity version: - 0.5.8 (solc-js)
* node version: v11.5.0
* Web3.js version: v1.0.0-beta.37
* npm version: 6.4.1
* ganache-cli version: Ganache CLI v6.4.3 (ganache-core: 2.5.5)

**Comment by CruzMolina** [comment]
@rotcivegaf , maybe I'm missing something but it appears your contract is too large and your test case will only work when passing `ganache-cli` `--allowUnlimitedContractSize true`

**Comment by rotcivegaf** [comment]
@CruzMolina I really sorry, you are right, my contract it's too large
