### ISSUE TITLE
Installing truffle-contract fails with g++ present unless CXX=clang++ is set

### ISSUE THREAD

**Issue by FlashSheridan** [trufflesuite/truffle#2133]
## Issue

Installing truffle-contract on my machine (which has g++ installed) fails with an error about a Clang-specific flag unknown to g++: “unrecognized command line option '-stdlib=libc++'`”
 

## Steps to Reproduce

`npm install -g truffle-contract`

## Actual Results

` SOLINK_MODULE(target) Release/copied_files.node`
`c++: error: unrecognized command line option '-stdlib=libc++'`

## Workaround

`CC=clang CXX=clang++ npm install -g truffle-contract`

## Environment

* Operating System: MacOS 10.13.6 17G7024
* Compilers:
```
19> which -a c++
/usr/local/bin/c++
/usr/bin/c++

23> /usr/local/bin/c++ --version

c++ (Homebrew GCC 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
…
24> /usr/bin/c++ --version

Apple LLVM version 10.0.0 (clang-1000.11.45.5)
…
```

**Comment by haltman-at** [comment]
Does this still occur for `@truffle/contract`?

**Comment by FlashSheridan** [comment]
I’m sorry, I upgraded that machine last year, and it had to go back to my ex-employer yesterday.

**Comment by FlashSheridan** [comment]
I installed the real `gcc` as “gcc” on a different machine,† and did not get the error installing @truffle/contract@4.2.0 (nor even when installing truffle-contract.)  Closing as fixed.

___
† This now takes some effort; e.g. Homebrew now installs the fake Clang as “gcc”; see https://apple.stackexchange.com/questions/245891/installed-gcc-with-homebrew-now-how-to-use-that-gcc-instead-of-clang#comment530132_245893
