### ISSUE TITLE
Quorum 2.2.1 can't migrate contracts compiled with 0.5.8 ( but 0.5.0 works)

### ISSUE THREAD

**Issue by pensivej** [trufflesuite/truffle#2137]
- [V] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have a basic setup of truffle and Quorum network running on localhost.
When I try to migrate the contract compiled with 0.5.8 (default compiler for truffle@5.0.24) the console emits error.
So, I tried changed the compiler version to 0.5.0 in truffle-config.js, it migrates with no issue.

## Steps to Reproduce

* Network:
Quorum-maker, 1 node setup, unlocked.
./setup.sh and then everything as default

Here's my truffle-config.js

```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 22000,
      network_id: "*",
      type: "quorum",
      gas: 450000000,
      gasPrice:0
    },
  compilers: {
    solc: {
      version: "0.5.8"
    }
  }
}
```

When I change the compiler version from "0.5.8" to "0.5.0" then everything works just fine.

## Expected Behavior

Smooth migration & deploy

## Actual Results

```
~/test 6s
❯ truffle deploy --reset --network development

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Running migration: 1_initial_migration.js
Deploying Migrations...
Migrations: 0x641fbb055666a2564Eb85Eaa75Cc8FFC225E1003
Saving successful migration to network...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: StatusError: Transaction: 0x33d98e9ad98f1515b239d18ad5db6417a7a0cac0100c8ac6e9fa777c101180e3 exited with an error (status 0) after consuming all gas.
     Please check that the transaction:
     - satisfies all conditions set by Solidity `assert` statements.
     - has enough gas to execute the full transaction.
     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
    at Object.run (/Users/ace/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.24 (core: 5.0.24)
Node v10.15.3
```

## Environment

* Operating System: MacOS 10.14.5
* Ethereum client: Quorum maker v2.6.2 Built on Quorum 2.2.1
* Truffle version (`truffle version`): Truffle v5.0.24 (core: 5.0.24)
* node version (`node --version`): Node v10.15.3
* npm version (`npm --version`): 6.4.1

**Comment by pensivej** [comment]
To check that compiler version 0.5.0 works,
`rm -rf build`
then try `truffle migrate` with 0.5.0

**Comment by pensivej** [comment]
I just checked that up to solc@0.5.4 works as fine, but from 0.5.5 and up throws error.

Here's my testing setup. I just changed the compiler solc version.

Truffle v5.0.24 (core: 5.0.24)
Solidity - 0.5.X (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37

Also, all I did from the beginning was truffle init in an empty directory and changed the network part in truffle-config.js

**Comment by pensivej** [comment]
It seems like Quorum maker is having problem.
When I try to reproduce the problem with Quorum-example tutorial, it migrates fine.

**Comment by gnidan** [comment]
I believe the workaround here is to set the `evmVersion` in your solc settings:

```
compilers: {
  solc: {
    settings: {
      evmVersion: "byzantium"
    }
  }
}
```

We've been trying to figure out a way to make this default on Quorum networks, but it's tricky because of the disconnect between compile/migrate.

**Comment by pensivej** [comment]
Okay thanks,
This works.
