### ISSUE TITLE
Feature request: `truffle init myProjectName`

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#2138]
This is a minor feature request that the `truffle init` command take an optional string parameter which for this demonstration I'll call `myProjectName`. The command would be a shortcut that if the optional parameter is present, runs the following three commands: 

`mkdir <myProjectName>`  
`cd <myProjectName>`
`truffle init`

The idea is just to make that introductory process a little smoother.

**Comment by gnidan** [comment]
Love it!

**Comment by gnidan** [comment]
(Use `mkdir -p` kids)

**Comment by parifuture** [comment]
hi I will like to jump on this issue, might be a loaded question, what is the best way to get started?

**Comment by gnidan** [comment]
Oh hey @parifuture thank you! The code change will mostly be in `packages/truffle-core/lib/commands/init.js` and probably also in `packages/truffle-box/`. Let me know how the instructions work out for you.

Happy to give you more direction once you take a look. We just added the "good first issue" label, going to try to find other good first issues to label also; I'll keep my eyes open.

**Comment by johnletey** [comment]
I was planning on starting to work on this, but since #2387 was merged, this should be closed 😄

**Comment by CruzMolina** [comment]
Closing since #2387 was released in `v5.0.37`.
