### ISSUE TITLE
Out of gas: Test networks require a different HD-Wallet-Path against to Mainnet

### ISSUE THREAD

**Issue by itinance** [trufflesuite/truffle#2144]
**Long story short:** 

I sent some Test-Ether on Ropsten into the first address, that was derived with MyCrypto out of my Mnmonics, but the deployment using truffle or `zos`-Tool was constantly running out of gas, no matter which funds was sent. And here is why this happened and will happen again without further steps. I will also provide the solution below:

**Long Story:**

When we import a Mnemonic into MyCrypto or MyEtherWallet (or other Tools) for Ropsten-Network, it derives the address with the following path: `m/44'/1'/0'/0`, while `truffle-hdwallet-provider` constantly is using `m/44'/60'/0'/0/` no matter wich network will be used.

`m/44'/60'/0'/0/` is the derivation path for Ethereum Mainnet, while all other Testnets across all coins share `m/44'/1'/0'/0` for path derivation.

Therefor, I get a different address on MyCrypto as the first address than it will be used by `truffle-hdwallet-provider`.

This means, when I transfer Test-Ether on Ropsten Network to the first address out of my Mnemonic, it will be a different address as the HDWalletProvider will generate with our default settings.

**Example:**

Mnemonic: "tooth spike smile swarm adapt history motion salt outdoor document observe cloth"

MyCrypto Ropsten (using `m/44'/1'/0'/0`): `0x9dbFAFB5Edd1D69aCaC1C104C526C4ACDc20F3Ae`

truffle-HDWallet-provider with default settings (using `m/44'/60'/0'/0`): `0xC0306fe5c3E90025AD56832A4399670be51b3Eec`

Thus, a deployment of contracts, that are based on `truffle-config.js` as it is recommend in this repository (README), will raise "Out of gas"-exception because different addresses will be used. I would send Test-Ether to the address, that was generated by MyCrypto. And `truffle-hdwallet-provider` expects the second address, which probably has no funds nor could sign any transaction due to missing private key.

**Solution:**

Fortunately the constructor of `truffle-hdwallet-provider` offers an argument for the `wallet_hdpath` that should be used for address derivation. So for using Ropster addresses (and even all other Testnetworks) properly with MyCrypto / MyEtherWallet, the following constructor is required to make transactions work as expected.

```
ropsten: {
  provider: () => new HDWalletProvider(
    process.env.DEV_MNEMONIC, "https://ropsten.infura.io/v3/" + infuraProjectId, 
        0, 1, true, "m/44'/1'/0'/0/"
    ),
  networkId: 3,       // Ropsten's id
},

```

Explanation of the parameters:

```
0 = start with first address
1 = derive only 1 addresses
true = sharedNonce (default)

“m/44’/1’/0’/0/” = BIP44 derivation path that is used for test networks (across all coins)
```

We should reflect this in README as well.

**Comment by eggplantzzz** [comment]
@itinance Interesting, I didn't know about this convention. Do you have any docs that you could link to that describe this behavior?

**Comment by itinance** [comment]
@eggplantzzz it seems to be something like a "common sense" in several sections of crypto applications and/or libraries.

Since [BIP0044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) indicates ?`m/44'/1'/0'/0/0` as derivation path for BTC Testnet, others have adopted these rules also on other currencies (although I am not really a friend of this). 

MyCrypto uses the same derivation path for Ethereum Testnets:

<img width="424" alt="Screenshot 2019-07-12 17 19 32" src="https://user-images.githubusercontent.com/1758597/61139901-a334b400-a4ca-11e9-8288-665917e9ee71.png">

And [hd-wallet-derive](https://github.com/dan-da/hd-wallet-derive) is also using the same path across all supported currencies, if one chooses the respective testnet.

I saw similar approaches in some other tools, blogposts and libraries too but can't remember exactly. 

But when it comes to work with MyCrypto for instance (or with hd-wallet-derive, that was used in some projects of my customers heavily) there is a big confusion about this. 

I think it needs definitely a standard across all tools. And if there is none yet, we should at least add some notes about different behavious if someone is working with MyCrypto because of my confusing and time consuming story, that I have written at the beginning :)

**Comment by eggplantzzz** [comment]
Hey thanks very much for the lesson and for pointing this out! I'll get this reviewed and hopefully we can get this merged soon!

**Comment by itinance** [comment]
By the way. Just read "Mastering Ethereum". In their Book "Mastering Ethereum" from Dr. Gavin Wood and Andreas M. Antonopoulos they also write that the HD Path for all testnets across all currencies and blockchains should be "m/44'/1'/0'/0"

**Comment by haltman-at** [comment]
Hm, so was this ever resolved?  I see that the README was updated; does that suffice here or is there something more to do?

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.
