### ISSUE TITLE
truffle compile: respect the use-case where files in different directories have same name.

### ISSUE THREAD

**Issue by prographo** [trufflesuite/truffle#2147]
Create a file in contracts called Test.sol
```
pragma solidity 0.5.8;
contract Test { }
```

Create a subdirectory called sub1, copy Test.sol into that directory, run:

```
truffle compile
```

Only one Test.json file will be created in build/contracts, because the first is overwritten.

Remix does it correctly.

The example is contrived, but can happen for larger projects that share source code.

**Comment by prographo** [comment]
I just renamed stuff to make it work .... It doesn't get lower priority that this, is it even worth bothering about? Probably not.

**Comment by gnidan** [comment]
Not low priority at all! But tough to fix. We're working on it.

(This has an existing issue here: https://github.com/trufflesuite/truffle/issues/1087)
