### ISSUE TITLE
Towards a better interface to interact with contracts

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle#215]
[As explained in the Truffle docs](https://truffle.readthedocs.io/en/latest/getting_started/contracts/), each contract method can be used as a `call` or as a `transaction`. The latter is used by calling the method directly, for example: `coin.sendCoin(...)`, and the former is used via the `call` function, like so: `coin.getBalance.call(...)`.

I find this very counter-intuitive. As a beginner, this was pretty hard to understand. I know that this is much much better than using Web3 directly, but I think we can do better! I open this thread to discuss ideas to improve how to interact with contracts.

One idea I have of a better interface (let me know if it doesn't make sense):

``` javascript
var account_one = "0x1234..."; // an address
var account_two = "0xabcd..."; // another address
var account_three = "0xabcd..."; // yet another address
var account_four = "0xabcd..."; // yet another address

var coin = MetaCoin.deployed();
coin.getBalance(account_one)
  .then(function(balance) {
    if (balance.toNumber() >= 10) {
      coin.transaction({from: account_one})
        .sendCoin(account_two, 5)
        .sendCoin(account_three, 5);
    }
  });

coin.sendCoin(account_four, 2) // throws exception saying sendCoin method is transactional and needs to be called in a transaction context
```

Given that methods are exclusively either a `transaction` or a `call`, is there a way we can check this at runtime to support this interface?

If you think this makes sense, I'd be happy to help implement these changes.

**Comment by eordano** [comment]
Adding my two cents on top of this:

```js
coin.makeAtomic(function() { 
  coin.transaction({ from: acc1 })
    .sendCoin(acc2, 5)
    .sendCoin(acc3, 5)
})

coin.transaction({ from: acc1 }).sendCoin(acc4, 3) // throws exception: "sendCoin must be called in the scope of an atomic blockchain query"
```

**Comment by netusco** [comment]
isn't there a chained .sendCoin  blocked by the ; ?

**Comment by maraoz** [comment]
@netusco yes. IMO the dafault behavior should be calling the function as read-only, and the call that creates a transaction (pretty big side effect) should require a bit more work. 
Nice catch on the `;`, I'll edit now.

**Comment by tcoulter** [comment]
Are you guys familiar with constant functions, i.e.:

```
contract MyContract {
  function someFunction() constant returns (uint) {
    return 5;
  }
}
```

If you declare a function constant, then the contract abstraction will know it's only a call. Thus, the following becomes a call instead of a transaction:

```javascript
var contract = MyContract.deployed();
contract.someFunction().then(...);
```

**Comment by maraoz** [comment]
@tcoulter nice! That's very useful :)

**Comment by tcoulter** [comment]
Hey @maraoz. This is old. I'm going to close it for housekeeping, but please let me know if you have any questions or you think we should expand upon our abstractions.

Note: More abstraction features are in the works!
