### ISSUE TITLE
docs: no doc for turrffle test exit status code

### ISSUE THREAD

**Issue by yxliang01** [trufflesuite/truffle#2155]
## Issue

There's no documentation for the exit status code of `truffle test`.

## Steps to Reproduce

Read all published documentations - `--help` message, official website(https://www.trufflesuite.com/docs/truffle/reference/truffle-commands), `README.md`.

## Expected Behavior

There should be documentation for the exit status code of `truffle test`

**Comment by icherkashin** [comment]
Hello @yxliang01 !

I believe that `truffle` delegates the responsibility for exit codes to `mocha`.
However, `mocha` itself does not appear to have a clear documentation on its exit codes. 
The best information I have found so far is that the exit code is the number of failed tests, or `255` if there are more than `255` failed tests.

https://github.com/mochajs/mocha/issues/3559

https://github.com/mochajs/mocha/blob/5d4dd98747637d0e7ed3007328ec9627dd7eda41/lib/cli/run-helpers.js#L35

**Comment by yxliang01** [comment]
Yeah, your finding matches mine. So, I believe this should be added to the truffle documentation.

**Comment by eggplantzzz** [comment]
#1197 documents this behavior
