### ISSUE TITLE
Enhancement: Add `accounts` global to truffle console

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2157]
## Issue

Spun out from #2135, this issue proposes to add a convenient global to `truffle console` and `truffle develop`, so that users can easily see their accounts.

**Comment by djokicx** [comment]
Thank you for opening a separate issue for this!

**Comment by TripleSpeeder** [comment]
As https://github.com/trufflesuite/truffle/pull/2218 is merged i think this can be closed.

**Comment by gnidan** [comment]
Yep! Bam!
