### ISSUE TITLE
Support command-line argument `--option=value` syntax (not just `--option value`)

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#2173]
When using a command line flag with an `=` sign instead of a ` `, Truffle will throw a warning that you are using an unsupported or undocumented command. This is due to the way Truffle parses out the flags [here](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-core/lib/command.js#L115-L119).

This should probably be updated to replace all `=` with spaces before checking. It might also be worth considering extracting this validation into its own utility file to keep `command.js` clean.

This would probably be a good first issue.

**Comment by richmanrich** [comment]
I suppost

**Comment by haltman-at** [comment]
Looks like this was fixed a while back.  Closing.
