### ISSUE TITLE
Truffle migrate --network kovan 

### ISSUE THREAD

**Issue by danielr6** [trufflesuite/truffle#2175]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When i try to migrate my contracts to the test network kovan, it just compiles my contracts then nothing. No further actions. 

## Steps to Reproduce

truffle migrate --network kovan

## Expected Behavior

it should deploy the smart contracts to the test network

## Actual Results

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

$ 

//////truffle-config.js////////
require('babel-register');
require('babel-polyfill');
require('dotenv').config();
const HDWalletProvider = require('truffle-hdwallet-provider-privkey');
const privateKeys = process.env.PRIVATE_KEYS || ""

module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" 
    },
    kovan: {
      provider: function(){
        return new HDWalletProvider(
          privateKeys.split(','),
          'kovan.infura.io/v3/${process.env.INFURA_API_KEY}'
        )
      },
      gas: 5000000,
      gasPrice: 25000000000,
      network_id: 42
    }
  },
  contracts_directory: './src/contracts/',
  contracts_build_directory: './src/abis/',
  compilers: {
    solc: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  }
}

## Environment

* Operating System: macOS 10.14.5
* Ethereum client: infuria
* Truffle version (`truffle version`): 5.0.18
* node version (`node --version`): 9.10.0
* npm version (`npm --version`):  5.6

**Comment by eggplantzzz** [comment]
Hey @danielr6, try adding the protocol to your provider specification. In other words, what happens when you prefix that kovan url with "https://"? It seems likely that this is the case.

**Comment by danielr6** [comment]
> Hey @danielr6, try adding the protocol to your provider specification. In other words, what happens when you prefix that kovan url with "https://"? It seems likely that this is the case. Let me know if this fixes your issue!

@eggplantzzz thanks for reply! Unfortunately that didn't fix the issue. Still just compiles my contracts then nothing.

**Comment by fainashalts** [comment]
Hi @danielr6 `truffle-hdwallet-provider-privkey` is not a Truffle package. Can you try to use `truffle-hdwallet-provider` instead and see if that resolves this?  If it doesn't can you take a look at your Infura dashboard? You may need to enable your api key from there in order for this to work. Please let us know if these suggestions resolve your issue!

**Comment by danielr6** [comment]
> Hi @danielr6 `truffle-hdwallet-provider-privkey` is not a Truffle package. Can you try to use `truffle-hdwallet-provider` instead and see if that resolves this? If it doesn't can you take a look at your Infura dashboard? You may need to enable your api key from there in order for this to work. Please let us know if these suggestions resolve your issue!

@fainashalts appreciate the reply! sorry but your suggestions didn't solve the issue.

**Comment by CruzMolina** [comment]
Hey @danielr6 , do you happen to have `Require project secret for all requests` selected under `PRIVATE SECRET REQUIRED` for your project in the Infura Dashboard?

**Comment by danielr6** [comment]
> Hey @danielr6 , do you happen to have `Require project secret for all requests` selected under `PRIVATE SECRET REQUIRED` for your project in the Infura Dashboard?

@CruzMolina I do not have it selected

**Comment by eggplantzzz** [comment]
And incidentally, does it work with `truffle develop` or a test network like rinkeby?

**Comment by danielr6** [comment]
> @danielr6 Can you repost your Truffle config after changing to use `truffle-hdwallet-provider` and adding the protocol to the provider?

I changed to ```truffle-hdwallet-provider``` and it worked after I noticed some simple fixes. I now have this error: 

```1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error: Error: Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0x981284ce7a9081B9Bc9a35C45c7c50691Abd2f65
   * Balance:  0 wei
   * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 125000000000000000 and the sender's account only has: 0
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.

    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:84:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
Truffle v5.0.18 (core: 5.0.18)
Node v9.10.0```

**Comment by treasersimplifies** [comment]
> And incidentally, does it work with `truffle develop` or a test network like rinkeby?

I got the same issue. 
`truffle migrate --network rinkeby `
with no any response, either no error or success info.
And mine works with  `truffle develop`, contract can be deployed to truffle develop node.

**Comment by danielr6** [comment]
I was able to migrate my files by changing my truffle config file. 

Now I have an error when seeding the exchange on the kovan test network. 

```$ truffle exec scripts/seed-exchange.js --network kovan

Using network 'kovan'.



Token fetched 0x69e0a4354aa5c2Ba68D4DF44D05f91BaEB3701Ed

Exchange fetched 0x700Be86E624f370202169C4F352db5Bf8464d7E8

{ Error: invalid address (arg="_to", coderType="address", value=undefined)

    at Object.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/errors.js:68:1)

    at CoderAddress.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:467:1)

    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:605:21

    at Array.forEach (<anonymous>)

    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:604:1)

    at CoderTuple.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:764:1)

    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:897:1)

    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:96:1)

    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:426:1

    at Array.map (<anonymous>)

    at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:425:10)

    at constructor.detectNetwork.then.network (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/execute.js:170:1)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:118:7)

  reason: 'invalid address',

  code: 'INVALID_ARGUMENT',

  arg: '_to',

  coderType: 'address',

  value: undefined }```

**Comment by eggplantzzz** [comment]
@danielr6 I'm not sure what you are doing to get that error but it looks like you are providing an invalid address as an argument to one of your functions (or leaving it out entirely). Please share relevant code (migrations, etc.) and we can have a look!

**Comment by eggplantzzz** [comment]
Are you still having an issue with this?

**Comment by alexanderatallah** [comment]
It would be great if the truffle hdwallet provider showed an error when it can't connect to Infura, instead of showing nothing and exiting. That's been a very confusing part of the process for many devs.

**Comment by gnidan** [comment]
@alexanderatallah this might get fixed by #2430, at least for migrations. We have a plan to make error handling more robust for provider errors like that.

That should catch the general case, but @danielr6 is your specific issue still occurring? Closing this for issue maintenance, but do let us know!

**Comment by mktcode** [comment]
Just for the record: In my case I just had to delete the build directory.

**Comment by chekuris** [comment]
> I was able to migrate my files by changing my truffle config file.
> 
> Now I have an error when seeding the exchange on the kovan test network.
> 
> ```
> 
> Using network 'kovan'.
> 
> 
> 
> Token fetched 0x69e0a4354aa5c2Ba68D4DF44D05f91BaEB3701Ed
> 
> Exchange fetched 0x700Be86E624f370202169C4F352db5Bf8464d7E8
> 
> { Error: invalid address (arg="_to", coderType="address", value=undefined)
> 
>     at Object.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/errors.js:68:1)
> 
>     at CoderAddress.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:467:1)
> 
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:605:21
> 
>     at Array.forEach (<anonymous>)
> 
>     at pack (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:604:1)
> 
>     at CoderTuple.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:764:1)
> 
>     at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:897:1)
> 
>     at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:96:1)
> 
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:426:1
> 
>     at Array.map (<anonymous>)
> 
>     at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:425:10)
> 
>     at constructor.detectNetwork.then.network (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/execute.js:170:1)
> 
>     at <anonymous>
> 
>     at process._tickCallback (internal/process/next_tick.js:118:7)
> 
>   reason: 'invalid address',
> 
>   code: 'INVALID_ARGUMENT',
> 
>   arg: '_to',
> 
>   coderType: 'address',
> 
>   value: undefined }```
> ```

hi danielr6,
can you please suggest, what did you changed in  truffle config file to make it work.
Since i am also having same issue.

**Comment by SirGaLaHaD69** [comment]
Still facing this issue..any help
