### ISSUE TITLE
Document `fork` option for `truffle develop`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2194]

**Comment by rori4** [comment]
In the meantime while this is open can someone say how to use this in the truffle config?

**Comment by eggplantzzz** [comment]
Hey @rori4! So it looks like you specify the value of `fork` in your `truffle-config.js` under `networks.develop`. That value gets passed to Ganache when it is initialized internally in Truffle. You can check out [the Ganache docs for options](https://www.npmjs.com/package/ganache-cli#options) and see how it works!

If that doesn't clear it up and you have more questions then feel free to ask!

**Comment by ndroo** [comment]
This is a super old issue, but i'd like to comment that should be documented. If you google around for anything related to truffle and fork, theres nothing but git issues and useless dead end discussions. Even if the documentation is simply a link to the ganache docs, that'd be great.
