### ISSUE TITLE
Invalid Opcode

### ISSUE THREAD

**Issue by mindrunner** [trufflesuite/truffle#2216]
## Issue

I am getting an invalid opcode error from solc (I think) when compiling my contracts. This happens with truffle 5.0.26 and 5.0.27. Dowgrading to 5.0.1 solved my problem. Did not test other versions. In Gitter nobody answered my question.

## Steps to Reproduce

1) clone https://github.com/mindrunner/ethereum-supply-chain-tracking
2) run truffle test

## Expected Behavior

Tests are either suceeding or failing

## Actual Results

```
[le@w530]: ~/src/ethereum-supply-chain-tracking/cacao>$ truffle test
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./contracts/base/SupplyChain.sol
> Artifacts written to /tmp/test-119611-1587-198to5y.cnsf
> Compiled successfully using:
   - solc: 0.5.8+commit.23d335f2.Emscripten.clang

Error: Error: Error: Returned error: VM Exception while processing transaction: invalid opcode
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Truffle v5.0.25 (core: 5.0.25)
Node v11.15.0
```

## Environment

* Operating System: Arch Linux 
* Ethereum client: Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* Truffle version (`truffle version`): 5.0.27
* node version (`node --version`): v11.15.0
* npm version (`npm --version`): 6.10.1

**Comment by CruzMolina** [comment]
Hey @mindrunner , setting the compiler evmVersion for solc to `"byzantium"` in your config should do the trick 🤞 .

As of `0.5.5`, `solc` defaults to compiling to `petersburg`.

You could also use the latest version of `ganache-cli` since I believe that defaults to using `petersburg` now as well.

**Comment by mindrunner** [comment]
Perfect, that helps a lot. Wasn't really aware of the outdated ganache-cli. All ganache and truffle packages are horribly outdated on Arch. Got everything from npm now and works way better! :)

Cheers

**Comment by codeoffconduct** [comment]
> Hey @mindrunner , setting the compiler evmVersion for solc to `"byzantium"` in your config should do the trick 🤞 .
> 
> As of `0.5.5`, `solc` defaults to compiling to `petersburg`.
> 
> You could also use the latest version of `ganache-cli` since I believe that defaults to using `petersburg` now as well.

You made my day my friend. I spent 2 days figuring out what it could be. Thanks!
