### ISSUE TITLE
Import of `truffle-hdwallet-provider` hangs on AWS Lambda

### ISSUE THREAD

**Issue by dominik992** [trufflesuite/truffle#2233]
When I try to import truffle-hdwallet-provider on AWS Lambda, the process hangs.
Example:

```
import fs from 'fs';
import path from 'path';
import Web3 from 'web3';
console.log('contract initialization1');
import HDWalletProvider from 'truffle-hdwallet-provider';
console.log('contract initialization2');
```

`contract initialization1` gets printed while `contract initialization2` not.

Locally it works ok.

I tried changing timeout time and other parameters on AWS, but nothing solved the problem so I'm pretty sure the problem is related to the package itself.

Any suggestions?

Thanks

**Comment by CruzMolina** [comment]
Hey @dominik992 , I'm not familiar with AWS Lambda, but `truffle-hdwallet-provider` is webpacked for a node.js context. There might be some node-specific dependencies that aren't available on Labmda?

You might want to give `react-native-truffle-hdwallet-provider` a try: https://github.com/bpeters/react-native-truffle-hdwallet-provider

It's specifically webpacked for a frontend context.

**Comment by dominik992** [comment]
@CruzMolina Since it's a node.js environment, importing `react-native-truffle-hdwallet-provider` just adds more problems

**Comment by eggplantzzz** [comment]
@dominik992 Hmm I can't duplicate this error on my local machine. I'm installing it, opening a Node.js console and running `const HDWalletProvider = require("truffle-hdwallet-provider");`. What happens when you use `require` syntax in your scenario?

**Comment by dominik992** [comment]
@eggplantzzz you can't reproduce it on a local machine. The problem occurs only on AWS Lambda

**Comment by fainashalts** [comment]
HI @dominik992, this seems like it may be an issue with your AWS Lambda configuration. Do you have any more information that could help us debug this? Thanks!

**Comment by dominik992** [comment]
It's just a regular AWS Lambda with preinstalled node v8.

**Comment by gnidan** [comment]
@dominik992 hm, can you get a stacktrace or error message? If it doesn't show up automatically, maybe do this:

```javascript
try {
  const HDWalletProvider = require('truffle-hdwallet-provider');
} catch (e) {
  console.debug(e);
}
```

Also, what specific version of Node v8 do you get? Some of the earlier versions aren't supported anymore.

**Comment by CruzMolina** [comment]
Closing for maintenance. Let us know if this is still a problem.
