### ISSUE TITLE
Inclusion paths are messed up.

### ISSUE THREAD

**Issue by hickscorp** [trufflesuite/truffle#2235]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If a truffle project is packaged as an NPM package, the relative location of `node_modules` is different whether it's being used directly or as a dependency.

## Steps to Reproduce

- In a truffle project, have a `.gitignore` file that excludes the `build` folder.
- Have `truffle` and any NPM package that has solidity files in it (Eg `openzeppelin-solidity`.
- In one of the contract, to import one of these dependencies, you have to reference `../node_modules/openzeppelin-solidity/whatever.sol`, given that your contract is in `/src`.

This works great as long as you're calling `truffle build` from the root of the project. However, if this project becomes a dependency of another project, `node_modules` will contain the project, and therefore the `../node_modules/...` import will fail.

## Expected Behavior

A way to reference dependencies without a leading path specifier, unless the files are part of the same package.

In many other languages (Eg C, C++, etc), these two statements resolve differently, there's a good reason for that.:

`#include <stdio.h>` vs `include "./stdio.h"`

## Actual Results

Having a `truffle build` in the `scripts.postinstall` section of the `package.json` fails when that package is listed as a dependency.

**Comment by eggplantzzz** [comment]
If you use a Solidity file from a package, I'm not sure we want you to import them directly using relative paths. It should behave correctly if you reference the package directly. @gndan can you weigh in on this when you get a chance? What do you think the behavior should be?

**Comment by hickscorp** [comment]
@eggplantzzz You are absolutelly right! Thanks for taking the time to answer.
I think it's worth explaining that I was mislead by the VSCode extension that was signaling an error on the import, while `truffle compile` was indeed.

To make things work, I had to change a little bit of my VSCode configuration, so it probably matches the Truffle way of invoking the compiler.

For those interested, the interesting bits are `solidity.packageDefaultDependenciesDirectory` and `solidity.packageDefaultDependenciesContractsDirectory`:
It occured to me that the first one has a correct default of `node_modules`, but the second one has an incorrect default of `contracts` (So the VSCode extension does a weird string interpolation using both as explained [here](https://github.com/juanfranblanco/vscode-solidity), look for "Openzeppelin").

With these settings, you would be able to import things from `node_modules` properly during both project dev compilation and as a dependency itself.

**Comment by eggplantzzz** [comment]
This is probably interesting for those working on the VSCode extension. I'll pass it along.
