### ISSUE TITLE
Contract has not been deployed to detected network (at browser) But working fine in test file, please assist

### ISSUE THREAD

**Issue by Eymos** [trufflesuite/truffle#2237]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by Eymos** [comment]
![contract](https://user-images.githubusercontent.com/8821301/61593672-874ea380-ab97-11e9-9f68-199a41886449.PNG)

**Comment by Eymos** [comment]
![config](https://user-images.githubusercontent.com/8821301/61593702-d399e380-ab97-11e9-8128-9003a0543758.PNG)

**Comment by CruzMolina** [comment]
Hey @Eymos, FYI `truffle test` runs your migrations automatically. You might want to double-check if you have ganache running.

**Comment by Eymos** [comment]
Thanks for the reply Cruz, yes ganache is running as show below, still same error. btw you can git clone and try it out.  https://github.com/ssimunic/iot-device-management.git
![ganache](https://user-images.githubusercontent.com/8821301/61861646-35e93180-ae81-11e9-8672-eb431e2fb7a5.PNG)

**Comment by Eymos** [comment]
![image](https://user-images.githubusercontent.com/8821301/61861773-79dc3680-ae81-11e9-8df6-5abad7fd9bbe.png)

**Comment by CruzMolina** [comment]
What are the steps you're taking to receive the `contract has not been deployed` error?

**Comment by Eymos** [comment]
Heree are the Steps.
1. truffle compile
2. truffle  deploy --network development
![image](https://user-images.githubusercontent.com/8821301/61935852-372d6380-af40-11e9-9b56-4d38f93d9d30.png)

**Comment by Eymos** [comment]
3. npm run start
![image](https://user-images.githubusercontent.com/8821301/61936051-bb7fe680-af40-11e9-8096-75ddd9104afd.png)
![image](https://user-images.githubusercontent.com/8821301/61936108-e10cf000-af40-11e9-8d26-06b3d9136518.png)

**Comment by CruzMolina** [comment]
Hey @Eymos that looks like you don't have your dapp/frontend configured to connect to Ganache properly.

**Comment by Eymos** [comment]
The contract is well deployed, right. ? ganache server is 


![image](https://user-images.githubusercontent.com/8821301/61955284-8474f980-af6f-11e9-97db-a2b9feb99931.png)

**Comment by Eymos** [comment]
what do u mean by  dapp/frontend not configured to connect to Ganache properly.? where is the exact issue?

**Comment by CruzMolina** [comment]
@Eymos , based on your repo, it looks like your using MM to connect to Ganache. Is MM configured properly?

**Comment by Eymos** [comment]
Hello Cruz, yes MM and Gnache are well connected, when the contracts are deployed, both the MM and Ganache reduces the balance as shown below, i really can't figure out why i am getting this error..

![image](https://user-images.githubusercontent.com/8821301/62002944-1b05ff80-b0c3-11e9-84d8-7fea77269f58.png)


![image](https://user-images.githubusercontent.com/8821301/62002971-923b9380-b0c3-11e9-800e-cd6ae8f2342a.png)

**Comment by eggplantzzz** [comment]
@Eymos It is because the artifact file you are using to load DeviceManager is not in sync with the network. When you run `truffle compile` and `truffle migrate`, the artifact file is built and put in `./build/contracts`. The one you are using to load from on the front end is in `./frontend/src/artifacts` which is old. 

Try deleting that artifact file and copying the one from the build folder in there after migrating. In other words, after you compile and migrate, Truffle updates the artifact file and that network information needs to be there when loading it on the front end. Let me know how it goes!

**Comment by Eymos** [comment]
Thanks for the comments @CruzMolina  and @eggplantzzz. i was able to check the to solve this issue. by reinstalling the dependancy - (npm i truffle-contract). Now my system is running but i am getting the error "**vm exception while processing transaction out of gas**" and it is not mining.any idea how i can solve this?

**Comment by eggplantzzz** [comment]
Sorry for the delay in getting back to you but the last week or so there was TruffleCon and some team retreat stuff. Are you doing something that is causing the transactions to run out of gas?

**Comment by fainashalts** [comment]
Hi @Eymos is this still an issue or can we close? Thanks!

**Comment by Eymos** [comment]
Please close the issue. This was solved.

**Comment by eggplantzzz** [comment]
Thanks @Eymos!
