### ISSUE TITLE
Contract deployment problems with truffle !! 

### ISSUE THREAD

**Issue by 4Maarifa** [trufflesuite/truffle#2250]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
@CruzMolina
 @cds-amal
@gwmccubbin
## Issue

When I deploy my contracts (_Migrations.sol, Token.sol and CrowdSaleT.sol_ )  to any testnet (_ganache , ropesten ...ect_) , truffle deployer deploy the migrations and Token Contracts but it is **not deployed** the CrowdSale.sol contract !!!!????

## Steps to Reproduce

> 1- truffle compile [ compiled with no error ]

> 2- truffle migrate --reset -- network ganache , ropsten or rinkeby

> 3- I get the issue

## Expected Behavior

I have expected it return all 3 contracts address 
like this 
`C:\Users\acer\test>truffle migrate --reset`
`Using network development`
`Running migration: 1_initial_migration.js`
 ` Replacing Migrations...`

  `... 0x0c7d00f59725dfc6f62d3cf8398e7abeb876895ccb286f39b00e074421fb3b24`
  `Migrations: 0xf50e371dc8c8840d10502aad94e786445044d02b`
`Saving successful migration to network...`
 ` ... 0xd96356d5cfe087dd5d7ccf5cfafd8dd6b652fd6dd547c1b905eee28853283fa3`
`Saving artifacts...`
## Actual Results
`Running migration: 1_initial_migration.js`
` Replacing Migrations...`
`... 0x6347bef6297729145f64a5e9e9edfcb00b79666b8fdee718968c73213923cf76`

 ` Migrations: 0x10712d488cf372cad92d8da9f3bb45fadbf561f8
Saving successful migration to network...`
  `... 0x8eb9cbdba9cde068b8ce1596706111f706499ab15ffd8c7b267bb1ec58be24e3.`
`Saving artifacts....`
`Running migration: 2_mirgrate_crowd.js.`
 ` Replacing Token...`

`... 0x8003d3130fb3b01e2ddd53a711aa4a5f95eb91d3695b946f52a79ded3089541f.`
 ` Token: 0x65bf66504b9dff6a346e05b10434c721527d5d3f.`
`Saving successful migration to network...`

  `... 0x837e17534e295ef8a8ec8f0b82a0b82fcf5e52a523a2888c4d3649bc4873c195.`
 ` Deploying CrowdsaleToken....`
`Saving artifacts...`

## Environment

* Operating System: windows 10
* Ethereum client: ganache-cli, ganache gui, ropsten ... 
* Truffle v4.1.15 (core: 4.1.15)
* Solidity v0.4.25 (solc-js)
*open-zeppelin version (1.10.0)
* node version (`v10.14.1`):
* npm version (`6.4.1`):

**Comment by eggplantzzz** [comment]
Hey @4Maarifa, are you able to upgrade to the latest version of Truffle (version 5.0.28)? Is your code available somewhere like github to try and reproduce your error?

**Comment by 4Maarifa** [comment]
@eggplantzzz I am able to upgrade truffle to the latest version (5.0.28 with solc 0.5.10) but solidity version of my code is ( solc 0.4.24), as you know there are a lot of break changes between solc 04.24 and 0.5.10
I have cloned the repo from [https://github.com/dappuniversity/ico_irl ] to my computer and I try to deploy the same project without any changes but I get the same problem .      :( :( :(    !!????

**Comment by haltman-at** [comment]
With Truffle 5, you can set the Solidity compiler version in your `truffle-config.js`.  Try adding the following to the `module.exports` in your `truffle-config.js`:

```
  compilers:
  {
    solc:
    {
      version: "0.4.24",
    }
  }
```

Or, if instead of specifically 0.4.24, you're OK with later compatible versions, you can use `"^0.4.24"` instead, to allow also 0.4.25 or 0.4.26.

If you do that, does that resolve your problem, or is there more to it?  Thanks!

**Comment by eggplantzzz** [comment]
@4Maarifa I'll try and duplicate your issue and get back to you. Off the bat I don't see a CrowdSaleToken contract, do you know where that is coming from?

**Comment by eggplantzzz** [comment]
@4Maarifa Do you have the code for your project somewhere that I could use to try and reproduce your issue?

**Comment by eggplantzzz** [comment]
Oh I see you linked it above.

**Comment by eggplantzzz** [comment]
Closing for issue maintenance. Let us know if you still need help!
