### ISSUE TITLE
build artifacts: include flattened source code

### ISSUE THREAD

**Issue by SurfingNerd** [trufflesuite/truffle#2261]
## Issue

the build artifact json files became a very valuable source of information about the compiled source code. it tracks among others the source code, the used compiler and  settings. 
But it still takes some extra error prone steps to include the full, flattened source code of a specific contract (what you usually need) to get uploaded to tools like blockscout. (means: compiled flattened source code matches exactly the binary EVM result)

The idea now is to make this step more convenient and include the flattened source code as well in this compile artifact. i know, that json file is already very big, but i think the extra space is acceptable in exchange for productivity.

**Comment by gnidan** [comment]
@SurfingNerd we have an in-progress solution to address this problem systematically. See #1718 or blogposts _Introducing Truffle DB [part 1](https://www.trufflesuite.com/blog/introducing-truffle-db-part-1)_ and _[part 2](https://www.trufflesuite.com/blog/introducing-truffle-db-part-2)_.

If you're in a hurry and can't wait for Truffle DB, there might be a compromise solution that adds this information to the artifacts via a feature flag in the project config. Still, though, there is risk that this will bring existing limitations to light. For instance, flattened source does not always compile to the same bytecode/metadata as other compilation workflows.

Have you considered using [truffle-flattener](https://github.com/nomiclabs/truffle-flattener)? You might also be interested in using **truffle-compile** directly via the new lossless interface introduced in #2073 (to be released this week).

**Comment by SurfingNerd** [comment]
thank you for this fast response :) the truffle-flatterner resulted in a cylcic graph error - i did not investigate any further. 
good i have the time to wait for the next upcomming release. Maybe it brings me luck :)
