### ISSUE TITLE
- Fetching solc version list from solc-bin. Attempt #1 + truffle@5.0.29

### ISSUE THREAD

**Issue by ziakhatri** [trufflesuite/truffle#2262]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
No response
---------------------------

## Issue
zia@zia-VirtualBox:~$ npm install truffle -g
/home/zia/.npm-global/bin/truffle -> /home/zia/.npm-global/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.0.29 postinstall /home/zia/.npm-global/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.0.29
updated 1 package in 19.156s
zia@zia-VirtualBox:~$ truffle
truffle: command not found

What the issue is, in broad strokes.
I cannot install Truffle. All (almost all) permissions to files and folders changed to "zia" as owner. What can be the cause? NPM and NodeJs latest versions are installed.

**Comment by eggplantzzz** [comment]
This sounds very vaguely permissions-based even though you said you have all permissions given. Do you have npm installed through nvm? Sometimes these things go away when you do. You might consider trying the suggestions in this npm article. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

If you go for it, let me know if anything improves.

**Comment by fainashalts** [comment]
HI @ziakhatri have you had a chance to resolve this issue? Please let us know, thanks!

**Comment by gnidan** [comment]
Hey @ziakhatri here's another ping :)

Closing this for issue maintenance, but please do get back to us and we'd love to help out!
