### ISSUE TITLE
Problem in installing truffle-environment

### ISSUE THREAD

**Issue by AminTalebi** [trufflesuite/truffle#2264]
```
 sudo npm install --save-dev truffle-environment
npm ERR! path solidity/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git solidity/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git    solidity/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amin/.npm/_logs/2019-07-30T09_06_22_797Z-debug.log

```

**Comment by CruzMolina** [comment]
hey @AminTalebi can you try installing without sudo? I believe that's not the npm-recommended way of installing packages. We've noticed doing so tends to cause permissions-related issues.

**Comment by AminTalebi** [comment]
Hi, 
I could not use it without sudo. I am using ubuntu bash on windows, that is the reason why!

I delete .git folders in order to get in done.

**Comment by gnidan** [comment]
Looks like the same issue as https://github.com/ethereum/web3.js/issues/2971, which has an open PR to fix. I haven't checked... does truffle-environment use websocket directly or is this error bubbling up from web3?

**Comment by obbaeiei** [comment]
try this magic

```rm -rf node_modules/*/.git/```

**Comment by DavidBurela** [comment]
@AminTalebi not to hijack, but as an FYI you don't need to use sudo when using ubuntu on windows.

install node with `nvm` and it will make things easier.  This is how I do it, but you man want to use `nvm install lts/dubnium` for latest LTS release rather than node 12.
https://davidburela.wordpress.com/2017/05/12/how-to-install-truffle-testrpc-on-ubuntu-or-windows-10-with-windows-subsystem-for-linux/

**Comment by AminTalebi** [comment]
Thank you so much @DavidBurela. 
But I have already uninstalled Windows and installed Ubuntu instead :)))

**Comment by eggplantzzz** [comment]
@AminTalebi Did you install Node using nvm? This is something that [npm recommends](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) and, as @DavidBurela said, it usually resolves these kinds of errors. Let me know how it goes if you try it!

**Comment by fainashalts** [comment]
HI @AminTalebi are you still having a problem with this? Let us know, thanks!

**Comment by AminTalebi** [comment]
No, not anymore.

**Comment by migueljulve** [comment]
Hi, I got same problem, I resolved it installing truffle with Homebrew,
Installed nvm with brew, so node and npm, then truffle.

**Comment by Cublax** [comment]
@migueljulve @fainashalts Isn't it a problem to install with homebrew ? Is seems that they are a few versions late is that right ?

**Comment by cds-amal** [comment]
We cannot vouch for, nor support homebrew's installation of Truffle.
