### ISSUE TITLE
Add --rm flag to docker run command when docker setting is true

### ISSUE THREAD

**Issue by pablogm95** [trufflesuite/truffle#2265]
## Issue

On run the compiler with `compilers.solc.docker: true` the docker containers are not automatically remove when it exits creating stoped containers pollution

## Steps to Reproduce

`truffle compile`   -or-  `./node_modules/.bin/truffle compile`
`docker container ls`

## Expected Behavior

adding the --rm tag for automatically remove the container when it exits at: 
[https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-compile/compilerSupplier/loadingStrategies/Docker.js#L13](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-compile/compilerSupplier/loadingStrategies/Docker.js#L13)

The containers should be removed when exits

## Actual Results

The containers are not be removed when exits

## Environment

* Truffle version (`truffle version`): 5.0.29

**Comment by gnidan** [comment]
Good idea! You should open a PR for this!

**Comment by haltman-at** [comment]
Looks like this never got closed despite being done. Closing now.
