### ISSUE TITLE
Using Lib for Type throws during compilation

### ISSUE THREAD

**Issue by zweicoder** [trufflesuite/truffle#227]
I'm declaring this at the start of the contract: `using CheapArray.Data for bytes32[];` as referenced from [here](https://github.com/ethereum/wiki/wiki/Solidity-Features#attaching-library-functions-to-types). Compiler throws an unknown exception: 

```
± truffle compile
Compiling CheapArray.sol...
Compiling Judge.sol...
Compiling JudgeSubscriber.sol...
Compiling Migrations.sol...
Error compiling:

Unknown exception during compilation.
Compiliation failed. See above.
```

**Comment by tcoulter** [comment]
Hi there, 

This issue looks to be old. For housekeeping reasons we're going to close this. If you run into it in the future don't hesitate to contact us. 

Cheers!
