### ISSUE TITLE
Document hasn't upgrade the default gas to 6721975 instead of 4712388

### ISSUE THREAD

**Issue by boolafish** [trufflesuite/truffle#2278]
---------------------------

## Issue

In [truffle doc](https://www.trufflesuite.com/docs/truffle/reference/configuration), it has the following statement for default network gas: 

> gas: Gas limit used for deploys. Default is 4712388.

However, it is updated to 6721975 in [This gas update commit](https://github.com/trufflesuite/truffle/commit/0baeedd4741a484a39c2474f294c216eff88d9a1).

## Steps to Reproduce

I was deploying contract to ganache with gas limit of 6200000 and found this. The deployer is trying to send transaction with higher gas of our limit on ganache.

## Expected Behavior

The doc should change the stated value to new one.

## Actual Results

```
"Migrations" exceeded the block limit (with a gas value you set).
   * Block limit:  0x20175c8
   * Gas sent:     6721975
   * Try:
```

## Environment

* Operating System: mac
* Ethereum client: Ganache
* Truffle version (`truffle version`): v5.0.21
* node version (`node --version`): v9.2.1
* npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
Thanks for submitting this @boolafish! I'll try and get a fix in for that.

**Comment by haltman-at** [comment]
Looks like this was fixed! Closing.
