### ISSUE TITLE
Web3 is not defined in truffle-contract@4.0.2

### ISSUE THREAD

**Issue by sebastiantf** [trufflesuite/truffle#2287]
## Issue

The documentation specifies:
`Note: Web3 and its dependencies are now bundled into truffle-contract v4.0.2 or higher.`

But `new Web3()` produces error: `Uncaught ReferenceError: Web3 is not defined`

## Steps to Reproduce

1. `<script src="/vendor/truffle-contract/dist/truffle-contract.min.js"></script>`
   * Without including web3. Does not have MetaMask installed
2. `App.web3Provider = new Web3.providers.HttpProvider("http://localhost:8545");`
      `web3 = new Web3(App.web3Provider);`

## Expected Behavior

Since truffle-contract v4.0.2 or higher includes Web3, `new Web3()` should work without issues.

## Actual Results

`Uncaught ReferenceError: Web3 is not defined`

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache
* Truffle version (`v5.0.29`):
* node version (`v10.15.3`):
* npm version (`6.4.1`):
* npm list truffle-contract: `truffle-contract@4.0.28`

**Comment by gnidan** [comment]
Ah, I think this was fixed in a subsequent release. Can you use a later version?

**Comment by sebastiantf** [comment]
@gnidan I am using the latest version `4.0.28`

- npm list truffle-contract: `truffle-contract@4.0.28`

**Comment by haltman-at** [comment]
I don't think `@truffle/contract` is supposed to inject `Web3` into the global namespace.  What you can do is use `Contract.web3` to get a `web3` instance.  Let us know if this suffices for your purposes.  Thank you!

**Comment by sebastiantf** [comment]
I haven't been using truffle for a while now and I may not be able to test it again soon. So feel free to close this if it seems this is solved

**Comment by eggplantzzz** [comment]
Thanks @sebastiantf! Closing for issue maintenance.
