### ISSUE TITLE
Contract objects made with Contract.deployed() are missing transactionHash

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#2291]
## Issue

Truffle contract objects made with `Contract.new()` have a field `transactionHash` which gives the transaction hash of the contract's creation.  Contract objects made with `Contract.deployed()`, though, are missing this field (or rather it's equal to `undefined`).

Note: These are not the only two ways to create contract objects.  For instance, there's also `Contract.at()`.  But it's probably not possible for `Contract.at()` to find this information in arbitrary cases.  That said, perhaps it could also still do it in cases where the information is somehow available.

(Are there other ways of creating contract objects?  Those are the ones I'm familiar with...)

## Steps to Reproduce

Deploy a contract (let's call it `Contract`) with `truffle migrate` and then, in `truffle console`, type `await Contract.deployed()`.  The result will have its `transactionHash` field undefined.

## Expected Behavior

The contract object should have its `transactionHash` field equal to the transaction hash of the contract's deployment.

## Actual Results

It's undefined.

## Environment

* Operating System: Linux Mint 19.1 64-bit
* Ethereum client: Ganache CLI v6.4.3 (ganache-core: 2.5.5)
* Truffle version (`truffle version`): 5.0.31
* node version (`node --version`): 10.15.3
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
So I'm proposing that the answer to this is to store a property like `creationTransactionHash` in the `networks.<id>` property in the artifact.

**Comment by CruzMolina** [comment]
Looks like this already part of the artifact spec as `transactionHash`: https://github.com/trufflesuite/truffle/blob/develop/packages/contract-schema/spec/network-object.spec.json#L9

I imagine the fix is to add the hash in same area where events are saved in the codebase.

**Comment by CruzMolina** [comment]
Closing since I believe this has been resolved by #2466.
