### ISSUE TITLE
Error: TypeError: Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by mushroom0117** [trufflesuite/truffle#2297]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I tried to follow the instructions of [Ubin-Project](https://github.com/project-ubin/ubin-quorum#c-contract-deployment) to compile and deploy the contracts on Quorum.

## Steps to Reproduce

```
ubuntu@ubin-nx11: truffle deploy --network mas
```

My truffle.js
```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*"
    },
    mas: {
      host: "192.168.56.3",
      port: 20010,
      network_id: "*",
      gas: 200000000,
      type: "quorum"
    },
  },
  compilers: {
    solc: {
      version: "0.4.11",
    },
  },

};
```

## Expected Behavior

It will compile these contracts and generate the `build` folder.

## Actual Results

```
Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Owned.sol
> Compiling ./contracts/PaymentAgent.sol
> Compiling ./contracts/SGDz.sol
> Compiling ./contracts/Stash.sol
> Compiling ./contracts/ZSLPrecompile.sol

Error: TypeError: Cannot read property 'nodes' of undefined
    at Object.compile (/home/ubuntu/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/legacy/index.js:72:1)
    at <anonymous>
Truffle v5.0.31 (core: 5.0.31)
Node v8.16.0
```

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: Quorum
* Truffle version (`v5.0.31`):
* node version (`v8.16.0`):
* npm version (`6.10.3`):

**Comment by yaoyao12138** [comment]
So can you tell me how to solve this question? Thank you!
