### ISSUE TITLE
Contract deployment hanging forever

### ISSUE THREAD

**Issue by nilfdev** [trufflesuite/truffle#2299]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Contract deployment  hangs forever during migration
![image](https://user-images.githubusercontent.com/15476934/63054989-348db080-bee5-11e9-9785-52c5b491679f.png)

## Steps to Reproduce
Configure networks in truffle-config.js  
![image](https://user-images.githubusercontent.com/15476934/63055291-db724c80-bee5-11e9-97e7-8852a5fe18a4.png)

install all the dependencies 
![image](https://user-images.githubusercontent.com/15476934/63055332-f0e77680-bee5-11e9-90d5-f1fc1a2fc25b.png)

define deploy contract 
![image](https://user-images.githubusercontent.com/15476934/63055379-0c528180-bee6-11e9-8dc7-c8c133c604ad.png)

run deployment 

    truffle deploy --network rinkeby --reset

## Expected Behavior

Contract should be deployed

## Actual Results

Transaction is created on rinkeby, but also is hanging 
![image](https://user-images.githubusercontent.com/15476934/63055130-89312b80-bee5-11e9-883a-0aaccec48c37.png)

## Environment

* Operating System: windows 10.
* Ethereum client: 
* Truffle version (`v5.0.31`):
* node version (`v10.14.1`):
* npm version (`v6.4.1`):

**Comment by eggplantzzz** [comment]
Hey @nilfdev, can you try upgrading to the latest version of truffle-hdwallet-provider? There is a version or two that has a bug. Let me know what happens!

**Comment by haltman-at** [comment]
Hi, was this successfully resolved?  Thank you!

**Comment by nilfdev** [comment]
@haltman-at 
Hi. 
not really. I had to create another account. 
and only with another account I could deploy it. 

I have assumption that I tried to deploy multiple times and because of this I created long queue of deployments. that is why it was blocked. 
we could close the issue probably
