### ISSUE TITLE
Various package.json files contain incorrect URLs

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#2307]
## Issue

Various `package.json` files across the project contain incorrect URLs.  As far as I saw, the `repository` URL is always correct.  However, the `homepage` and `bugs` URLs are often incorrect.  Oftentimes they point to a nonexistent Truffle repo with the same name as the package, which isn't correct because the package is part of the `truffle` repo.  In one case, I saw a `bugs` URL that pointed somewhere else entirely.  Anyway, basically, these should all be updated.

**Comment by eggplantzzz** [comment]
I believe a lot of these incorrect URLs are probably resolved now that we have switched to the new package names. In that process most (if not all) were updated. I'll take another look to see if we can close this issue.

**Comment by eggplantzzz** [comment]
I think this has been corrected. Closing
