### ISSUE TITLE
can i create 2 contracts_build_directory or not ?

### ISSUE THREAD

**Issue by vinhyenvodoi98** [trufflesuite/truffle#2309]
## Issue

In my project , i have backend and frontend , both of them need api so :
can i create 2 folder contract after run `truffle deploy --network rinkeby`
is this code can build 2 contract abi directory ? 
```javascript
contracts_build_directory: path.join(__dirname, 'frontend/src/contracts'),
```
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version --5.0.32`):
* node version (`node --10.16.0`):
* npm version (`npm --version --6.9.0`): 

Thanks

**Comment by eggplantzzz** [comment]
@vinhyenvodoi98 Out of the box this is currently not possible with Truffle. One workaround you could use is to create a symlink to your build folder. Closing this as "can't fix". Let us know if the symlink workaround won't work for you and we'll try and give more suggestions.
