### ISSUE TITLE
Truffle repl: ignore `truffle` keyword

### ISSUE THREAD

**Issue by DavidBurela** [trufflesuite/truffle#2318]
## suggestion
If in `truffle dev` or `truffle console`.  Please ignore `truffle` if it is the first command.

## use case 1: context switching
Many times I'm in a loop of using `truffle test` or `truffle migrate --reset` while developing.
I then drop into `truffle console`, to test things with the repl, but muscle memory gets me to type `TRUFFLE test` again.

## use case 2: new users
When I am teaching new users I usually show them `truffle test`, and get them to use it as part of their dev loop. When they complain that the tests take too long to run, I show them `truffle dev` and how it keeps truffle open, and they can then just use `test` to rapidly execute the tests.
Again due to muscle memory they type `truffle test` and question why it fails.

**Comment by gnidan** [comment]
Thanks @DavidBurela! Looks like this will likely go out next week.

**Comment by eggplantzzz** [comment]
Released into the wild with `5.0.34`!
