### ISSUE TITLE
Events do not fire

### ISSUE THREAD

**Issue by GeorgePals** [trufflesuite/truffle#2349]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

## Issue

Events in deployed contracts do not fire.

## Steps to Reproduce

1. truffle migrate --reset (in order to make sure that the contracts are deployed without errors)
2. Call any function, in any of the contracts, which emits an event.
3. Events are like they do not exist in the contracts' code.

The only way to see the events fire, is through Remix or Etheratom etc. where I redeploy the contract without Truffle.
For example, **if I just press "Deploy" in Remix**, call a function which has an emit in its code and run it, everything works as expected (see [here](https://www.dropbox.com/s/tmksy5ohx03bpcz/only_Deploy.png) for an example).

But, **if I press "Deploy at address"** and set the address as my, already deployed (from `truffle migrate --reset,` contract's address, then I receive [this](https://www.dropbox.com/s/h626agu9575d8y7/with_Deploy_At_Address.png).

There are no error messages. Anything.
Ganache's **Events** tab just stays empty.

[Here](https://www.dropbox.com/s/1d2y4hx4egpto8i/contract_deployment.png) is a picture of one of my contracts' deployment.

## Code Example
Here is a very simple example with an event that I am using in one of my contracts:
```
contract someContract {
  event newEvent(address indexed);
  function someFunc(address _address) public {
    new SomeContract(_address);
    emit newEvent(_address);
  }
}
```

## Things That I Have Already Tried

- Reinstalled Nodejs/npm

- Tried in a different operating system (WIndows 10)

- Tried to use Truffle's Pet-Shop Box - Added some events and the same issue exists

- Tried using `ganache-cli`

One more thing that I'd like to mention, which I do not think that it has to do with my issue in any way, is that I can run Ganache Gui only by doing a:
`sudo ./Ganache`.

## Environment

* Operating System: Ubuntu 18.04 (same issues with Windows 10)
* Ethereum client: Ganache 2.1.0
* Truffle version (`truffle version`): 5.0.31
* node version (`node --version`): 8.10.0
* npm version (`npm --version`): 3.5.2

**Comment by gnidan** [comment]
I think this may have been fixed in Truffle v5.0.33. Could you try upgrading and let us know?

**Comment by GeorgePals** [comment]
> I think this may have been fixed in Truffle v5.0.33 ([this PR](https://github.com/trufflesuite/truffle/pull/2273)). Could you try upgrading and let us know?

Updated to truffle@5.0.34
Nothing changed. [Here is a screenshot](https://previews.dropbox.com/p/thumb/AAhKPvh0NhShdQIY9Z9ut3m0fSkXHnpYjKtouSdVU0SuQMSQWHWY4VEVbYrlQ-NJ4Llt1TxpjvrbNmtmicQ11OtToJWlU1hjhJcMsVIz_dj1EIL0Z1UVxdh_zEB5P-DpZYvga3wHzkofgf7b_lT3Yg5q0k6nY9LxUgjgjmByNaWhgAwK0sh2azNICayzWVouGxmwcuG2XhfDEHepGcxZYVV_pMLG_26H0Q7GSHswuBMbvQbziBd9FR1ZKyQ851CrJ6M3RCwHfAp14DFbJUB-s_5nQ1pncKtA8wBBLRRz-EUSMCJE6ieC5hVnOoVjf2EAUTe4YT2Sl9ZLD1E1oUphXx53/p.png) with the output in Ganache.

**Comment by gnidan** [comment]
@davidmurdoch is this something you're aware of?

**Comment by gnidan** [comment]
btw @GeorgePals your image links don't work (getting 401 Unauthorized)

**Comment by GeorgePals** [comment]
> btw @GeorgePals your image links don't work (getting 401 Unauthorized)

Oops. Sorry. Fixed it.

**Comment by GeorgePals** [comment]
**Update:**
I tried using [this](https://kalis.me/check-events-solidity-smart-contract-test-truffle/) tutorial that I found in the "truffle-assertions" package.

It passed the test without any errors.

I also tried to reproduce the problem through Remix.
So, I just added a simple:
`event maxBet(uint256);`

and changed getMaxBet() function to:
```
    function getMaxBet() public returns (uint256) {
        emit maxBet(address(this).balance);
        return address(this).balance / 100;
    }
```
and it worked. I don't really know how or why Remix now had in its logs the event. (Check screenshot [here](https://www.dropbox.com/s/roj8oqcasa5l34d/remix_Casino_example.png))

The only issue, is that the event can not be seen in Ganache (see screenshot [here](https://www.dropbox.com/s/li7ivb0bhry8bag/ganache_Events_Casino.png)).

Okay, now I do not really know what is the problem.
I will try to investigate the issue even more.

**Comment by davidmurdoch** [comment]
@GeorgePals, this issue should be fixed in Ganache UI's [latest beta](https://github.com/trufflesuite/ganache/releases/tag/v2.1.1-beta.3). Do you mind giving this beta version a shot and letting me know if it does indeed fix the issue.

---

Previously, Truffle was (erroneously) including the event's signature in the event's ABI, and Ganache at some point began relying on the event's `.signature` property in order to filter events. Truffle fixed the issue, but it took me a while to figure out what happened and then finally apply a fix within Ganache. I'll likely release this latest beta to stable next week (pending the outcome of Hurricane Dorian, as I might be it's path and could lose power this week :-) ).

**Comment by GeorgePals** [comment]
Just checked the latest beta of Ganache and everything seems to work flawlessly.
Finally! I can see all the events.

The only _issue_, is that I still don't have the same output logs on Remix when I just **deploy** and **deploy at address**.

Thank you @gnidan and @davidmurdoch.

**Comment by gnidan** [comment]
@GeorgePals there's probably something we can do here to make this more clear, but for now I'm just going to close this issue. Glad to hear your problem has been solved! Thanks for raising it!
