### ISSUE TITLE
truffle doesn't use solidity's remappings

### ISSUE THREAD

**Issue by PaulRBerg** [trufflesuite/truffle#2355]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
- [x] I've asked for help on [Twitter](https://twitter.com/PaulRBerg/status/1167838340021936128)

---------------------------

## Issue

When compiling contracts that import other contracts, truffle behaves differently to sol-compiler and solc. The reason is that solidity's "remappings" are not put in the metadata object, as they should. See the docs on [Layout of a Solidity Source File](https://solidity.readthedocs.io/en/v0.5.11/layout-of-source-files.html) or this [StackExchange thread](https://ethereum.stackexchange.com/questions/74448/what-are-remappings-and-how-do-they-work-in-solidity) for more info.

## Steps to Reproduce

Make sure to have truffle and [sol-compiler](https://sol-compiler.com) globally installed and check out my [sol-compiler-truffle-mismatch](https://github.com/PaulRBerg/sol-compiler-truffle-mismatch) repo.

```
1. git clone git@github.com:PaulRBerg/sol-compiler-truffle-mismatch.git
2. cd sol-compiler-truffle-mismatch
3. yarn install
4. ./compare.sh
```
The last instruction should print "Artifacts are NOT equal".

## Expected Behavior

The artifacts should be the same, even if they are compiled with two different tools.

## Actual Results

The resulted artifacts have different metadata, because truffle doesn't put solidity's remappings in there, while sol-compiler does. It follows that the bytecode of the contracts gets to be different, since the bytes at the end include the hash of the metadata (see the solidity docs on [Contract Metadata](https://solidity.readthedocs.io/en/v0.5.11/metadata.html)).

## Environment

* Operating System: macOS v10.14.6
* Ethereum client: ganache-cli v6.5.1
* Truffle version (`truffle version`): v5.0.33
* node version (`node --version`): v10.15.3
* npm version (`npm --version`): v6.10.2

**Comment by eggplantzzz** [comment]
Ok so looks like we just need to whitelist a remapping property for `compilers.solc.settings` in `truffle-config.js`. Then people should be able to specify remappings there. Thanks for such a detailed report @PaulRBerg!

**Comment by eggplantzzz** [comment]
https://github.com/trufflesuite/truffle/pull/2358

**Comment by PaulRBerg** [comment]
No worries. Thanks for the quick fix!

**Comment by PaulRBerg** [comment]
I guess I can use this fix only if I build truffle from scratch. How does the release process work? Do you wait for other major features on your roadmap to get done before bumping the version?

**Comment by fainashalts** [comment]
Hi @PaulRBerg we do weekly releases, so you should see this in the newest release sometime later today. Thanks!

**Comment by PaulRBerg** [comment]
Legend, thanks @fainashalts!

**Comment by eggplantzzz** [comment]
@PaulRBerg This is now out in the wild with version `0.5.35`!
