### ISSUE TITLE
TypeScript tests dont run

### ISSUE THREAD

**Issue by angel-manuel** [trufflesuite/truffle#2371]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

TypeScript tests fail when parsing ES6 import and possibly all TypeScript extra stuff.
Probably mocha 

## Steps to Reproduce

```sh
mkdir Metacoin
cd Metacoin
truffle unbox metacoin

# Adding import to test and converting to .ts
echo "import web3 from 'web3'" > import.ts
cat import.ts test/metacoin.js > test/metacoin.ts
rm import.ts test/metacoin.js

npx truffle test
```

Is also interesting to run the following after installing ts-node
```
npx mocha --require ts-node/register test/metacoin.ts
```

## Expected Behavior

Tests run correctly

## Actual Results

```
% npx truffle test

Compiling your contracts...
===========================
> Compiling ./contracts/ConvertLib.sol
> Compiling ./contracts/MetaCoin.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./test/TestMetaCoin.sol

/tmp/Metacoin/test/metacoin.ts:1
import web3 from 'web3'
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /home/arturo/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/arturo/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/arturo/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:576:10)
    at /home/arturo/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:116:1
    at new Promise (<anonymous>)
    at Object.run (/home/arturo/.nvm/versions/node/v12.10.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:115:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.0.35 (core: 5.0.35)
Node v12.10.0
```

## Environment

* Operating System: `Linux Mint 19 4.15.0-60-generic`
* Ethereum client:
* Truffle version (`truffle version`): `v5.0.35`
* node version (`node --version`): `v12.10.0`
* npm version (`npm --version`): `6.10.3`

**Comment by CruzMolina** [comment]
Hey @angel-manuel ! Current TS test support requires using [`truffle-typings`](https://github.com/ethereum-ts/truffle-typings) with [`typechain`](https://medium.com/ethereum-ts/typesafe-truffle-with-typescript-and-typechain-1773e5b733b4).

**Comment by angel-manuel** [comment]
Solved adding the following to `truffle-config.js`

```js
require('ts-node/register')

// OPTIONAL: Allows the use of tsconfig path mappings with ts-node
require('tsconfig-paths/register')
```

**Comment by digulla** [comment]
What dependencies need to be in package.json for this to work?

**Comment by flcoder** [comment]
I'm using `truffle exec script.ts` and it's treating it as js
```typescript
const handleUncaught = (uncaught:any) => { log(`Uncaught:`, uncaught) }
                               ^
SyntaxError: Unexpected token ':'
```

I have `require('ts-node/register')` in `truffle-config.js`.

Is there something else I need to do?

**Comment by atrhacker** [comment]
> I'm using `truffle exec script.ts` and it's treating it as js
> 
> ```ts
> const handleUncaught = (uncaught:any) => { log(`Uncaught:`, uncaught) }
>                                ^
> SyntaxError: Unexpected token ':'
> ```
> 
> I have `require('ts-node/register')` in `truffle-config.js`.
> 
> Is there something else I need to do?

sorry to raise this issue again. did you solve this issue ?
using ts in normal test is working but not with truffle exec (import statement not working, unexcpted token for : , etc..)

Many thanks in advance
