### ISSUE TITLE
Big Number Fails when passed as uint256

### ISSUE THREAD

**Issue by pizza-r0b** [trufflesuite/truffle#2373]
- [ YES] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Get an error when passing the following big number value as uint256
`Error: invalid BigNumber string value (arg="value", value="1.267650600228229401496703205376e+30", version=4.0.28)`

## Steps to Reproduce
Create a contract and function within it that accepts uint 256. With truffle test the contract and pass in `(new BigNumber('2')).exponentiatedBy(100)`

## Expected Behavior
Expect this to work without error

## Actual Results

Get the error `Error: invalid BigNumber string value (arg="value", value="1.267650600228229401496703205376e+30", version=4.0.28)`

## Environment

* Operating System: Mac 10.14.4
* Ethereum client: Ganache CLI v6.4.4 (ganache-core: 2.5.6)
Truffle v5.0.32 (core: 5.0.32)
Solidity - 0.5.10 (solc-js)
Node v10.13.0
Web3.js v1.2.1

**Comment by eggplantzzz** [comment]
Thanks for reporting this @pizza-r0b! We'll look into this.

**Comment by haltman-at** [comment]
OK, I've just pushed PR #2401 which should fix this.
