### ISSUE TITLE
Test throws out of gas error

### ISSUE THREAD

**Issue by filippetroviccc** [trufflesuite/truffle#2380]
## Issue

I'm trying to run truffle tests on this repo [swarm-compliant-contract](https://github.com/swarmfund/swarm-compliant-contract/tree/feature/SWM-410-manual-approval)

Commnad:
`truffle test ./test/token/SRC20Factory.js`

## Steps to Reproduce

Just run the command above after:
```
git pull <URL>
yarn install
```

## Expected Behavior

The test should pass or at least pass before each

## Actual Results

```
1) Contract: SRC20Factory
       "before each" hook for "should allow only factory to register tokens":
     Error: Returned error: VM Exception while processing transaction: out of gas
```

## Environment

* Operating System: win10
* Ethereum client: 
Truffle v5.0.0 (core: 5.0.0)
Solidity - ^0.5.10 (solc-js)
Node v10.16.3
npm version - 6.9.0

**Comment by eggplantzzz** [comment]
Hey @filippetroviccc, can you try upgrading to the latest version of Truffle (v5.0.35)? If this is an issue for Truffle, I want to be sure it is not something that was already patched.

**Comment by filippetroviccc** [comment]
Hey @eggplantzzz,

Same thing, same issue.

**Comment by eggplantzzz** [comment]
I couldn't really duplicate your error, I probably did something wrong. I cloned your repo and then after running the test command specified above, I got an error: 
```
Error: Cannot find module '/Users/tyler/projects/external/swarm-compliant-contract/test/token/SRC20Factory.js'
```
So then, I changed `test/token/SRC20Factory.test.js` to `test/token/SRC20Factory.js`. I think this is what you intended? Afterwards I was able to run the tests with all 18 passing. Did I do something wrong?

**Comment by filippetroviccc** [comment]
Hi,

Just to point out it is `feature/SWM-410-manual-approval` branch.

Still out of gas error just I found out that I don't get this error if I comment out 2 functions so I would assume that bytecode limit is the issue. Just wondering how this "small" contract could have that error.

Thank you again for taking time to resolve this issue :)

**Comment by filippetroviccc** [comment]
The issue was to large bytecode size EIP-170
