### ISSUE TITLE
Truffle test does not clean up temporary files

### ISSUE THREAD

**Issue by aacampbell** [trufflesuite/truffle#2388]
## Issue

When `truffle test` is executed it does not clean up the files it creates in the system temporary directory. It appears that cleanup is attempted between tests of contracts, but is halted when the next test begins. When the final test concludes and `truffle test` exits cleanup appears to be incomplete.

## Steps to Reproduce

1. Run `truffle test`

## Expected Behaviour

No temporary files remain after execution completes.

## Actual Results

A directory exists under the system subdirectory containing many files, all of a regular two-part structure .The first part starts begins and ends with exclamation marks with the middle being a word like blockHashes or trie_db. The second part is an address string in hexadecimal. These files can sum to gigabytes.

## Environment

- * Operating System: Mac OS X 10.14.6
  * Ethereum client: web3.js 1.2.1
  * Truffle version (`truffle version`): 5.0.35
  * node version (`node --version`): 10.16.3
  * npm version (`npm --version`): 6.9.0
- * Operating System: Ubuntu 18.04.3
  * Ethereum client: web3.js 1.0.-beta.37
  * Truffle version (`truffle version`): 5.0.12
  * node version (`node --version`): 10.16.1
  * npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
@aacampbell Where do these files get created and left after running `truffle test`?

**Comment by haltman-at** [comment]
Hm, @davidmurdoch, the described files sound like Ganache temp files.  Do you know anything about this?

**Comment by davidmurdoch** [comment]
@aacampbell, are you using Ganache UI?

**Comment by haltman-at** [comment]
Closing for issue maintenance.  If you're interested in a fix, please let us know.
