### ISSUE TITLE
Truffle test fails with solidity contracts that inherit

### ISSUE THREAD

**Issue by realisation** [trufflesuite/truffle#2393]
- [ yes] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I was excuting a solidity test that inherited from another contract  and something in the test process failed. The test itself was not reached. 

## Steps to Reproduce

Try to test a contract that inherits from another contract. 

## Expected Behavior

It should test that test successfully.

## Actual Results

It failed with this console readout: 

```
TestContract
Error: Callback was already called.
    at /Users/realisation/.nvm/versions/node/v11.14.0/lib/node_modules/truffle/build/webpack:/packages/core/~/async/dist/async.js:966:1
    at /Users/realisation/.nvm/versions/node/v11.14.0/lib/node_modules/truffle/build/webpack:/packages/core/~/async/dist/async.js:3885:1
Config {
  _deepCopy: [ 'compilers' ],
  _values:
```

The rest of the printout is the truffle config.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):5.0.36
* node version (`node --version`):11.14.0
* npm version (`npm --version`): 6.7.0

**Comment by haltman-at** [comment]
Hi, could you provide us a simple reproduction example so we can get a better understanding of this?  Thank you!

**Comment by CruzMolina** [comment]
Closing for maintenance. Happy to re-open if this is still an issue.
