### ISSUE TITLE
Default EVM version for solidity 0.5.8 appears to be byzantium

### ISSUE THREAD

**Issue by rkalis** [trufflesuite/truffle#2416]
## Issue

I have been in touch with @mattBlackDesign of Atomic Loans about using truffle-plugin-verify in their project, which they were having trouble with. We manually copied over the required data into [Etherscan's verification web form](https://kovan.etherscan.io/verifyContract), which failed initially, but after selecting EVM version 'byzantium' (rather than 'default' or 'petersburg') on the Etherscan website, we got it to verify.

The Truffle config that was used contained these compiler settings:
```
  compilers: {
    solc: {
      version: "0.5.8",
      settings: {
        optimizer: {
          enabled: true,
          runs: 200
        },
        // evmVersion: 'petersburg'
      },
    },
  },
```

Since no EVM version was specified, we would expect it to use the default for Solidity v0.5.8, which is petersburg according to the [docs](https://solidity.readthedocs.io/en/v0.5.8/using-the-compiler.html#target-options). However, it appears to use byzantium, since we are only able to verify the code on Etherscan using byzantium as the EVM version.

When manually specifying `evmVersion: 'petersburg'` in the truffle config, it correctly verifies on Etherscan using default settings.

## Steps to Reproduce

1. Clone [atomicloans-eth-contracts](https://github.com/AtomicLoans/atomicloans-eth-contracts/tree/kovan-deploy) and checkout branch `kovan-deploy`.
2. `yarn` / `npm install`
3. Create a `.env` file in the root directory that has `MNEMONIC` and `ETHERSCAN_API_KEY` keys containing a mnemonic with a few Kovan Ethers and an Etherscan API key, generated from [their website](https://etherscan.io/apis).
4. Comment out the line stating `evmVersion: 'petersburg'` in `truffle.js`.
5. `truffle compile`
6. `truffle migrate --network kovan`
7. `truffle run verify Loans --network kovan`

This should return `Failed - Unable to verify`. Then uncomment the line specifying evm version petersburg and go through the steps again. This should return `Pass - Verified`.

## Expected Behavior

The contract code should be verified without having to specify `evmVersion: 'petersburg'`, because the default EVM version for Solidity 0.5.8 should already be petersburg.

## Actual Results

The contract code is only verified when manually specifying `evmVersion: 'petersburg'`, indicating that it doesn't use petersburg by default.

## Environment

* Operating System: macOS 10.14.4
* Ethereum client: N/A
* Truffle version (`truffle version`): 5.0.36
* node version (`node --version`): 11.15.0
* npm version (`npm --version`): 6.9.0

**Comment by rkalis** [comment]
I also observed this issue in @makoto's [wearekickback/contracts](https://github.com/wearekickback/contracts) repo (Solidity v0.5.11). 

It appears to occur when compiler settings are provided, e.g.:

```js
  compilers: {
    solc: {
      version: "0.5.11",
      settings: {
        optimizer: {
          enabled: true
        },
      },
    },
  },
```

But I haven't observed this issue in projects where there's no compiler settings specified whatsoever (i.e. using the builtin compiler). So that might be related to the problem.

**Comment by eggplantzzz** [comment]
I don't think Truffle has any reference to `evmVersion` any more and it should use the default for the version of solc you are using if nothing is specified. I will do a check to try and verify this.

**Comment by eggplantzzz** [comment]
There must be something else going on here. I confirmed that the output from solc on version 0.5.8 with a simple test contract is the same whether the `evmVersion` is specified as `petersburg` or `undefined` or not specified in the options at all. I also confirmed that in general in Truffle, when `evmVersion` is not specified, `undefined` is the value that gets passed in the options. I'll think about this a bit more and see if I can come up with another explanation for the behavior you are getting.

**Comment by rkalis** [comment]
Hey, I double checked as well and you're right that not specifying `evmVersion` has the same bytecode result as compiling with `petersburg` set. But still, the code verifies on Etherscan only when it's set to `petersburg` in the truffle config. So something else must be happening. 

@RyuuGan, do you think this could be related to sol-merger? I guess I should test this by taking a  single-file contract and seeing if I can still observe the behaviour with that contract. I'll try that out some time after devcon.

**Comment by RyuuGan** [comment]
@rkalis I don't compile any contracts, I just build a new one based on one entry contract file. So I'm not sure if this is related to `sol-merger`. Better to find the smallest contract that reproduces this cituation and then find out why it is happening.

But if there is an error in `sol-merger` then it should be in `pragma` versions. Take attention to this please when you will be looking in this.

**Comment by eggplantzzz** [comment]
Do you guys think there is some issue here for Truffle to address? Let me know!

**Comment by rkalis** [comment]
I think the issue is difficult to isolate, and since it only occurred on a specific Solidity version that is now outdated, and the issue is generally not a problem, I would say this issue can be closed.
