### ISSUE TITLE
truffle does not recompile when imported contract changes

### ISSUE THREAD

**Issue by tkeber** [trufflesuite/truffle#243]
I have two contracts: A and B.
`A.sol`:

```
contract A {
    function isA() returns(string name) {
        return "A";
    }
}
```

B is a factory for A. `B.sol`: 

```
import "./A.sol";

contract B {
    address addr;

    function buildA() returns(bool res) {
        addr = new A();
        return true;
    }

    function getA() returns(address a) {
        return addr;
    }
}
```

migration file `2_deploy_contracts.js`:

``` javascript
module.exports = function(deployer) {
  deployer.deploy(A);
  deployer.deploy(B);
};
```

tests: `a.js`:

``` javascript
contract("A", function(accounts) {

    it("should be of type 'A'", function () {
        var a = A.deployed();
        return a.isA.call().then(function (res) {
            assert.equal(res, "A", "a is not of correct type");
        });
    });

});
```

`b.js`:

``` javascript
contract("B", function (accounts) {

    it("should build contract of type 'A'", function () {
        var b = B.deployed();
        return b.buildA().then(function (tx_id) {
            return b.getA.call().then(function (addr) {
                var a = A.at(addr);
                return a.isA.call().then(function (res) {
                    assert.equal(res, "A", "a is not of correct type");
                });
            });
        });
    });
});
```

so far everything is fine.  
Now I change the implementation of A and its test like 

```
contract A {
    function isA() returns(string name) {
        return "A1";
    }
}
```

and 

``` javascript
...
            assert.equal(res, "A1", "a is not of correct type");
...
```

`truffle compile` / `truffle test` does only recompile / redeploy A, so that B still uses the old implementation of A and the tests report OK.

**Comment by tcoulter** [comment]
This is a great edge case. Thank you! Reproduced, and attempting to work on it now.

**Comment by tcoulter** [comment]
Hmm, actually, I was wrong, I can't reproduce this. I thought I had correctly reproduced it, but instead I had only changed one test file to check for "A1", and not both test files. In my attempt, `truffle test` recompiled and redeployed correctly, and the values for both A and B were "A1".

What operating system are you using? When you run `truffle test`, does the output look like this, where it shows that it recompiled?

```
$ ../truffle/cli.js test
Compiling A.sol...
Compiling B.sol...
Compiling Migrations.sol...

  Contract: A
    ✓ should be of type 'A' (41ms)

  Contract: B
    ✓ should build contract of type 'A' (114ms)

  2 passing (2s)
```

**Comment by tkeber** [comment]
That is the point; I modify A and its test, but don't touch B or B's test. Now I'd expect that the test for B fails, but it doesn't, because B does not get recompiled and therefor is not aware of A's new implementation. In that situation there is a mismatch between the test result showing B as OK and a code review that lets me expect that test B fails.

In my view there is something missing that models the dependency of B on A that is introduced by the import statement. In general a rule like

_If B.sol imports A.sol and A.sol is newer than B.sol, then B.sol needs recompilation._

I'm developing on Ubuntu 16.04, btw.

**Comment by tcoulter** [comment]
> That is the point; I modify A and its test, but don't touch B or B's
test. Now I'd expect that the test for B fails, but it doesn't,

It did on my machine, until I changed B's test to look for "AI" instead of
"A" (contrary to the mocha output above, which is simply the name of the
test)

**Comment by tkeber** [comment]
sorry, didn't expect you to read this and react so quickly. I looked at my example again and got confused, so I deleted my last comment, to build a sample case. I'm just building an example project. Hold on.

**Comment by tcoulter** [comment]
np. I was at my email. :)

**Comment by tkeber** [comment]
Here is the sample project.
[truffle-243.zip](https://github.com/ConsenSys/truffle/files/436469/truffle-243.zip)

This is what I do to show my point: I modified the tests to instantiate new contracts instead of using the deployed ones, so I skip the migration step.

    unzip truffle-243.zip
    cd truffle-243/
    # just to make sure both contracts get compiled
    touch contracts/*
    truffle compile
    # I expect both tests to pass
    truffle test
    # now change the implementation of the imported contract A
    sed -i -e's/"A"/"XXX"/' contracts/A.sol
    # now both test should fail
    truffle test
    # test for contract B passed, but it should have failed

For the last test contract B didn't get recompiled, but it should have, as the imported contract A was modified.

**Comment by tkeber** [comment]
when I remove build/contracts/B.sol.js, the test compiles B on the fly, so the result is a expected.

**Comment by ETHorHIL** [comment]
I am facing the same issue and deleting the .sol.js files as tkeber says works. But doing this everytime before compiling is a bit painful. Is there another way?

**Comment by tcoulter** [comment]
This should be fixed in the latest version of Truffle. Closing for housekeeping. If you run into a new issue please open a new ticket. Cheers!
