### ISSUE TITLE
Document --quiet flag

### ISSUE THREAD

**Issue by yxliang01** [trufflesuite/truffle#2457]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The very useful CLI flag `--quiet` is undocumented.

## Expected Behavior

Should be documented.

CC: @eggplantzzz

**Comment by eggplantzzz** [comment]
Hmm, actually it looks like this is documented for the `compile` command. What command were you using it with @yxliang01? Was it `truffle test`?

**Comment by yxliang01** [comment]
Yes `truffle test` @eggplantzzz

**Comment by eggplantzzz** [comment]
So we decided to add a new flag for `truffle test`, the `--runner-output-only` option. This will suppress all output except for the runner output (see PR above).

**Comment by eggplantzzz** [comment]
The option mentioned above is now a feature as of v5.0.44.

**Comment by yxliang01** [comment]
Thanks! @eggplantzzz
