### ISSUE TITLE
truffle test parsing files not related to Truffle within ./build/contracts

### ISSUE THREAD

**Issue by PyrateAkananto** [trufflesuite/truffle#2464]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The command `truffle test` fails if the directory `./build/contracts` contains any files not related to Truffle.

Sidenote: That directory can be changed by setting `contracts_build_directory` inside of `truffle-config.js` ([documentation](https://www.trufflesuite.com/docs/truffle/reference/configuration#contracts_build_directory)).

## Steps to Reproduce

Inside the directory `./build/contracts` create a text file named `dummy.txt` with the content `{ }` or create an empty file named `.keep` (usually used for version control to keep this directory even if empty).

## Expected Behavior

`truffle test` works.

## Actual Results

`truffle test` tries to parse the file and fails with an error message.

`dummy.txt` file containing `{ }`:
```
Compiling your contracts...
===========================
> Compiling .\contracts\ConvertLib.sol
> Compiling .\contracts\MetaCoin.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\ConvertLib.sol
> Compiling .\contracts\MetaCoin.sol
> Compiling .\test\TestMetaCoin.sol

truffle/DeployedAddresses.sol:8:17: ParserError: Expected '(' but got '.'
  function dummy.txt() public pure returns (address payable) { revert(); }
                ^

Compilation failed. See above.
Truffle v5.0.40 (core: 5.0.40)
Node v10.16.3
```

Empty `.keep` file:
```
Compiling your contracts...
===========================
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at filesData.map.data (E:\somewhere\node_modules\truffle\build\webpack:\packages\core\lib\testing\testsource.js:62:1)
    at Array.map (<anonymous>)
    at Promise.all.then.filesData (E:\somewhere\node_modules\truffle\build\webpack:\packages\core\lib\testing\testsource.js:62:1)
Truffle v5.0.40 (core: 5.0.40)
Node v10.16.3
```

## Environment

* Windows 10 64 Bit German
* Truffle v5.0.40 (core: 5.0.40)
* Solidity - ^0.5.10 (solc-js)
* Node v10.16.3
* npm v6.9.0
* nvm v1.1.7
* Web3.js v1.2.1

**Comment by haltman-at** [comment]
Thanks, we'll have to look into this.

**Comment by eggplantzzz** [comment]
This has been merged in https://github.com/trufflesuite/truffle/pull/2470 and will be released this week.

**Comment by PyrateAkananto** [comment]
Tested and working, thanks a lot!
:thumbsup:
