### ISSUE TITLE
Remove dependency on Babel

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#247]
package.json contains babel packages but I don't think they're used. We need to see how this affects the default builder.

**Comment by eduardonunesp** [comment]
It would be cool to create some workflow to make easier to create apps using React or Angular, and making available the possible transpiling for TypeScript as well

**Comment by chevdor** [comment]
I see it used here:
https://github.com/ConsenSys/truffle/blob/master/cli.js#L2
