### ISSUE TITLE
Truffle version is getting v5.0.32 (core: 5.0.32) Solidity v0.5.0 (solc-js) when installed truffle 4.1.5 version. How to downgrade it?

### ISSUE THREAD

**Issue by kottackalthulasi** [trufflesuite/truffle#2476]
I installed v4.1.5 of truffle using

`sudo npm install -g truffle@4.1.5`

But when I checked the version i get the result like,

```
Truffle v5.0.32 (core: 5.0.32)
Solidity v0.5.0 (solc-js)
Node v8.16.2
Web3.js v1.2.1

```

I can't execute my solidity files because of this issue. I need v4.1.5 for that. Anyone please help me to downgrade the truffle.

**Comment by gnidan** [comment]
Can you use a later v4 version?

**Comment by eggplantzzz** [comment]
@kottackalthulasi Why do you not want to use version 5 of Truffle? In 5 you can specify the version of the Solidity compiler to use in `truffle-config.js`. You can check out the docs [here](https://www.trufflesuite.com/docs/truffle/reference/configuration#compiler-configuration).

Also, you probably just did not uninstall version 5. I would recommend that you run `npm uninstall -g truffle` and then `npm install -g truffle@<whatever-version>`. I also would not recommend using `sudo` to install Truffle. If you have permissions issues, then I recommend using nvm.

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.
