### ISSUE TITLE
truffle test: console.warn does not work as expected

### ISSUE THREAD

**Issue by KBriverun** [trufflesuite/truffle#2481]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle test` command uses an [overloaded](https://github.com/trufflesuite/truffle/blob/master/packages/core/lib/test.js#L50) `console.warn()` function. 

https://github.com/syscoin/sysethereum-contracts/blob/63be76b53b9f97f35c079c275c4b45e8eaec2af1/test/utils.js#L422  - this innocent line of code prints truffle config when one [runs tests](https://travis-ci.com/syscoin/sysethereum-contracts/builds/132864645#L1184) 

## Steps to Reproduce

Run tests in branch `validateallheaders` using: https://github.com/syscoin/sysethereum-contracts/tree/validateallheaders#running-the-tests

## Expected Behavior

Expected to see warning from bitcoinjs-lib (https://github.com/bitcoinjs/bitcoinjs-lib/blob/41bf2cd03d85cd93a40992f5b9fea0af3e107734/src/transaction_builder.js#L60)

## Actual Results

Truffle config was printed (it's very verbose)

## Environment

* Operating System: /
* Ethereum client: /
* Truffle version (`truffle version`): 5.0.41
* node version (`node --version`): v11.13.0
* npm version (`npm --version`): /

**Comment by cds-amal** [comment]
> This issue can be closed since @Kenadia already addresses it in https://github.com/trufflesuite/truffle/pull/2812
