### ISSUE TITLE
example path issues 

### ISSUE THREAD

**Issue by 5shekel** [trufflesuite/truffle#254]
`truffle init`
truffle.js sends **app.js** and **app.css** to javascript and stylesheet folders, respectively
but the ./app/index.html expects them in ./app root

**Comment by chevdor** [comment]
I think there is no issue here.

The build process is taking care of bringing things as they should.

You should not run the app from `/app/index.html` but:

1. first build (`truffle build`) 
2. then run it from /build/index.html
