### ISSUE TITLE
Truffle develop timeout error

### ISSUE THREAD

**Issue by KadenZipfel** [trufflesuite/truffle#2552]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm trying to run `truffle develop`, but about 95% of the time I get the following timeout error:
```
Error: There was a timeout while attempting to connect 
to the network.
       Check to see that your provider is valid.       
       If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this.
```

So I've added `networkCheckTimeout: 10000000` to my `develop` network in `truffle-config`, as the error appears to suggest, but it hasn't solved the problem.

## Steps to Reproduce

Run `truffle develop` - possibly only on slow wifi networks.

## Expected Behavior

`truffle develop` runs as usual without error.

## Actual Results

```
Error: There was a timeout while attempting to connect 
to the network.
       Check to see that your provider is valid.       
       If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this.
```

## Environment

* Operating System: Windows 10
* Ethereum client: ganache
* Truffle version (`truffle version`): v5.0.43
* node version (`node --version`): v10.16.3
* npm version (`npm --version`): v6.9.0

**Comment by CruzMolina** [comment]
Hey @KadenZipfel ! If you are using GanacheUI, I would recommend connecting using `truffle console` instead of `truffle develop`.

**Comment by eggplantzzz** [comment]
What network are you connecting to? Are you using ganache?

**Comment by KadenZipfel** [comment]
> 
> 
> What network are you connecting to? Are you using ganache?

I'm using ganache with port 8545

**Comment by KadenZipfel** [comment]
`networkCheckTimeout` does work with truffle console at least, but it will just hang and never connect

**Comment by eggplantzzz** [comment]
What does your Truffle config look like? It looks like it is having trouble connecting to your network for some reason. Under the hood it is just trying to get the latest block number (using `web3.eth.getBlockNumber()`) to make sure it gets a valid response. I cannot duplicate your error here locally.

**Comment by KadenZipfel** [comment]
```
const path = require("path");

module.exports = {
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  networks: {
    develop: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "1001"
    }
  }
};
```

**Comment by eggplantzzz** [comment]
What happens if you set your `network_id` to "*"?

**Comment by KadenZipfel** [comment]
```
Error: The network id specified in the truffle config (5777) does not match the one 
returned by the network (1001).  Ensure that both the network and the provider are properly configured.
```

**Comment by eggplantzzz** [comment]
This kind of sounds like there might be several chains running on your computer and messing up things. Make sure all of your other instances of Ganache and whatnot are terminated and see if your problem persists. To make sure you might restart your computer as well. Let me know how it goes!

**Comment by KadenZipfel** [comment]
Initially it seemed the issue was still there after restart, but now it seems to be working fine... We'll see how it works going forward.

**Comment by eggplantzzz** [comment]
Super! I'm going to close this for now, if the problem ends up persisting then I'll be happy to re-open it.

**Comment by win2win** [comment]
I had exact problem with deploying to reinkeby using Infura.  Simply timeouts. 

I have used this command to test response coming back from Infura and it works. 

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' https://rinkeby.infura.io/v3/[ my key]

I got this response. 
{"jsonrpc":"2.0","id":83,"result":"0x52c10d"}

**Comment by ltfschoen** [comment]
I'm having similar issues in my project https://github.com/DataHighway-com/mining
I'm using Truffle v5.1.10.

If I run a separate "development" chain on port 8545 with `ganache-cli` by following my steps [here](https://github.com/DataHighway-com/mining#configure-blockchain) so I can specify custom CLI options such as where the chain database is stored, then when I run `truffle migrate --reset --network development` or even just `truffle migrate --reset`, it successfully compiles all my contracts, **but it always times out** before deploying any of the contracts (even after configuring a large value for `networkCheckTimeout`).
But I do not understand why it doesn't work anymore when using Truffle v5.1.10.
Note that in the past doing this actually worked (when I used this approach in one of my older repos [here](https://github.com/ltfschoen/benzcoin)), but back then I was using an older version of Truffle (i.e. i think i was using v3 or v4 at the time).

Also, if in my [project](https://github.com/DataHighway-com/mining) I instead run `truffle develop`, which itself starts a development chain but on port 9545, and then `truffle(develop)> migrate --reset --network development` to migrate using the development chain that i'm running on port 8545 instead, I have the same issue of it timing out and not deploying the contracts.

But if I don't try to run it using the "development" chain that I already started by with ganache-cli, and I instead just run by running `truffle develop` and then `truffle(develop)> migrate --reset`.

Questions:
* Why does this functionality time-out when using Truffle 5 (it wasn't a problem doing the same thing using Truffle 3/4)?
* How can I pass custom CLI options to `truffle develop` like I can do with `ganache-cli` (i.e. specify custom folder for the chain database)?
* How can I find out where the development chain is located on my local machine that is created when I run `truffle develop` when using Truffle 5?

**Comment by ltfschoen** [comment]
@KadenZipfel Please see my comment. Would you agree this issue should be re-opened?

**Comment by ltfschoen** [comment]
After trying alternatives, I've revisited the timeout issue and it's no longer occurring. Unfortunately I have no idea why (perhaps because I ran `npm uninstall ganache-cli -g
npm install ganache-cli@beta -g` this time instead of just `npm install -g ganache-cli`...). I've restarted numerous times since I first raised my issue ~2 months ago.

**Comment by KimiWu123** [comment]
@win2win , I got the same error. How do you fix it? thanks.

**Comment by caseykey** [comment]
@win2win @KimiWu123 Make sure you're using your Infura project ID and not project secret.

**Comment by KimiWu123** [comment]
@caseykey , It worked well in the beginning and suddenly I got the timeout error. I didn't change any configs only tried to deploy and test my contract. I used `curl` to test `Infura` server, it's okay. After 2, 3 hours later, it works again.

**Comment by nozeroctnellav7** [comment]
Got the same issue while trying to run `truffle migrate --network ropsten --reset` inside of ~/MyProject/contracts

I just go back to the main project directory ~/MyProject and then run `truffle migrate --network ropsten --reset` and fixed.

**Comment by sxguan** [comment]
@win2win @KimiWu123 I got the same error too.

**Comment by sxguan** [comment]
@KimiWu123 have u fixed it?

**Comment by KimiWu123** [comment]
@sxguan , it just worked after couples of hours. I didn't do anything...

**Comment by prashantbhardwaj30** [comment]
I restarted the server and it worked for me.

**Comment by stylehuan** [comment]
me too

**Comment by stylehuan** [comment]
clear local DNS cache,it worked for me.

**Comment by ahertlcode** [comment]
place the 
networkCheckTimeout: 10000 before the provider and it worked.

**Comment by vnavascues** [comment]
Hi, I'm having the same problem. I've already asked at Truffle Gitter and at Infura's community forum, but nothing.
My problem is very much related... it takes 20 minutes to get connection via Infura to Ropsten. I can either open a Truffle console or deploy, but it takes at least 20 minutes best case scenario. Worst case I just get the timeout/network issue messages the mentioned above.

Environment is:
- Ubuntu 20.04 LTS, connected via Ethernet.
- Node 10, 12, 13 (I’ve tried them all, via nvm)
- Truffle v5.1.33 (for node 10 and 12), and v5.1.35 (for node 13)
- @truffle/hdwallet-provider v1.0.39

And below my `truffle-config.js` for Ropsten:
```javascript
    ropsten: {
      networkCheckTimeout: 100000,
      provider: () =>
        new HDWalletProvider(
          process.env.MNEMONIC_2,
          process.env.ROPSTEN_HTTPS_ENDPOINT
        ),
      network_id: 3,
      gas: 5500000,
      skipDryRun: true,
    },
```

Any help will be very welcomed.

**Comment by CamJackson-Dev** [comment]
I had this issue for a few days before realizing it was a syntax error, hope it helps

**Comment by antoncoding** [comment]
I had this too and turn out to be using a deprecated infura key.

**Comment by rainlst** [comment]
> place the
> networkCheckTimeout: 10000 before the provider and it worked.

this works for me

**Comment by mblogger** [comment]
I just closed the terminal and restarted. It worked without any changes!

Happy Coding!

**Comment by h4x3rotab** [comment]
I suspect the reason is truffle (or its dependencies) doesn't handle proxy environment variable properly, even if the envs are empty. A restart the the terminal solves the problem.

I use a script to set the proxy environment variables. Another script is used to set these variables to empty string. It turned out the empty string doesn't work. They have to be unset.

**Comment by angora333** [comment]
My mistake was to have activated the box "Project Secret Required" in the Infura settings for the API key. Without, no more timeout.

**Comment by srpatel19590** [comment]
Increase pollingInterval if you are using newer HDWalletProvider

new Web3(new HDWalletProvider({
            privateKeys: [process.env.PK],
            providerOrUrl: constants.ChildChain.WS,
            pollingInterval: 16000
        }))

**Comment by GrinOleksandr** [comment]
> Increase pollingInterval if you are using newer HDWalletProvider
> 
> new Web3(new HDWalletProvider({ privateKeys: [process.env.PK], providerOrUrl: constants.ChildChain.WS, pollingInterval: 16000 }))

great! this works, thank you!

**Comment by domocarroll** [comment]
> I had this issue for a few days before realizing it was a syntax error, hope it helps

yep it was syntax for me as well

**Comment by sg552** [comment]
I met the same problem.

my rpc-server is running at: `192.168.10.53:8545` ,and the `http proxy` is running at `192.168.10.53:8080` and I `enabled` this http proxy by `export HTTP_PROXY=192.168.10.53:8080`, so when I ran `truffle deploy...` , it stucked and timeout.

so the solution is quite simple:  re-opened my WSL (Ubuntu) terminal and don't use any proxy, everything goes well.
