### ISSUE TITLE
Feature Request: Version control for deployed contracts

### ISSUE THREAD

**Issue by willwarren89** [trufflesuite/truffle#257]
This feature request is based on the ideas provided in [this audit](https://github.com/makerdao/audit-2/blob/master/makerdao_audit_aug_2016_public.pdf) of the MakerDAO code.
## Issue

A major pain point with immutable smart contracts is answering deployment questions:
1. Which contract is currently deployed?
2. Which version of the contract am I currently talking to right now?
3. Which commit hash does the contract I'm talking to go with?
## Potential Solution

Migrations are great for staging deployment tasks, perhaps they could incorporate a simple versioning system for the deployed contracts as well. One possibility is for migrations to store the git commit hash of each contract at deployment as well as a repository URL.

Other suggestions (that are perhaps more project specific) are given in the "Validating Builds and Contracts" section of the document linked at the top. I'm not sure of the best way to implement something like this into Truffle, but it might be worth thinking about.

**Comment by tcoulter** [comment]
Check out ethpm/ethpm-spec! Cheers!
