### ISSUE TITLE
Various packages lack source mapping support

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#2580]
## Issue

I noticed that `@truffle/codec` (on `next`) uses `source-map-support` to allow for source mapping despite being written in TypeScript.  It seems likely this should also be used in our other TypeScript packages (or compiled packages more generally, such as the debugger, which is written in JS but compiled with Webpack).

**Comment by nogo10** [comment]
Many @truffle/ packages result in error: ```Module not found: Error: Can't resolve 'module' in ..node_modules/source-map-support``` in versions 0.5.16, 0.5.18 source-map-support. I found a fix here: 
https://github.com/evanw/node-source-map-support/pull/273

**Comment by haltman-at** [comment]
@nogo10 Could you open a new issue for this?  What you're reporting is a different issue than what this issue was originally about (this issue should have been closed).  Thank you!

**Comment by haltman-at** [comment]
OK, @nogo10 I've thrown up PR #3036 to hopefully fix your problem.  In the future feel free to do this sort of thing yourself! :)

**Comment by haltman-at** [comment]
OK, this should hopefully be fixed now.  Closing this.  If it's not fixed, could you open a new issue rather than reopening this one?  Thank you!
