### ISSUE TITLE
how to call constructor from the test smart contract will doing the unit testing. 

### ISSUE THREAD

**Issue by Nayyar525** [trufflesuite/truffle#2594]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

 i am writing the test cases for unit testing of smart contract. So my contract contain constructor now i need to test the same. but i am failing the same while doing that. 

My contract
```solidity
pragma solidity >=0.4.25 <0.6.0;

contract Lottery
{
    address public manager;
   
    address payable[] public player;
    
     constructor (address manager1) public{
        manager = manager1;
    }
    function addPlayer() public payable
    {
        require(manager!= msg.sender, "player and manager can't be same");
        
        player.push(msg.sender);
    }
    
    function getAllPlayer() public view returns ( address payable[] memory) {
        return player;
    }
    
    function random() private view returns(uint256)
     {
    return  uint256( keccak256(abi.encodePacked(block.difficulty, block.timestamp, player)));
    }
    
    
    function pickWinner() public restrited ()
    {
    uint256 index=  random() % player.length;
   player[index].transfer(address(this).balance);
  
   player= new address payable[](0);
 
    }
    
    modifier restrited()
    {
        require(msg.sender==manager, "winner only be picked by manager");
        _;
    }
}
```
## Steps to Reproduce

want to know how i can call the constructor from my test contract.

Please provide the shortest amount of steps to reproduce your issue.

1-> need to know how i can call constructor  when i hit truffle test

## Expected Behavior

should run the test cases. without error

## Actual Results

Having error while running the same. 

## Environment

* Operating System:  windows
* Ethereum client: not using
* Truffle version (`truffle version`): 5.0.37
* node version (`node --version`): 10.16.3
* npm version (`npm --version`): 6.11.3

**Comment by Nayyar525** [comment]
@Debasis261 check this

**Comment by fainashalts** [comment]
Hi @Nayyar525 can you provide some more information? What do your tests look like so far? Are you writing them in solidity or javascript? 

Testing a constructor function would usually require calling a new contract. If Javascript its `MyContract.new()`, and if in Solidity, `new MyContract()`. Let me know if that helps!

**Comment by digulla** [comment]
In TypeScript, you can get an array with addresses for testing like so:

    contract("Lottery Tests", accounts => {
        const deployer = accounts[0]; // this is the default for msg.sender
        const manager1 = accounts[1];

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance. Thanks!
