### ISSUE TITLE
Transition to publishing bundle with a shrinkwrap 

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#2602]
Currently we only bundle and publish the truffle cli w/ a `package.json`. This is because there is only a `package.json` in `packages/truffle`. See #2555 for the possible security issues with this current setup.

We should probably generate a `package-lock`, convert it into a `shrinkwrap`, & proceed with publishing the truffle cli with a shrinkwrap. (Recommended for global cli installations [which is how we recommend users to install & use truffle]).

**Comment by CruzMolina** [comment]
Since we rarely update the deps for `truffle`, going to check out pinning the dep or two that isn't pinned, & generating a shrinkwrap.

**Comment by haltman-at** [comment]
We're going to close this for now, but we may look into this again shortly.
