### ISSUE TITLE
Command truffle develop BUG 

### ISSUE THREAD

**Issue by AfonsoMiao** [trufflesuite/truffle#2632]
## Issue

When I use command `truffle develop` it doesn't show the `truffle(development)>` console .

![bugTruffle_Develop](https://user-images.githubusercontent.com/29982581/69333651-fffe6300-0c50-11ea-83d4-a1f165fca109.png)

## Expected Behavior

![expected](https://user-images.githubusercontent.com/29982581/69333764-3d62f080-0c51-11ea-8ef3-ead9058118a4.png)

## Environment

* Operating System: Ubuntu 18.04
* Truffle version (`truffle version`): 5.0.37
* node version (`node --version`): 10.16.3
* npm version (`npm --version`): 6.9.0

**Comment by haltman-at** [comment]
Wondering if #1975 is related to this.

**Comment by gnidan** [comment]
Thanks for opening this! We'll have to figure out what's going wrong here.

Are you doing anything else besides running `truffle develop`?

Also, does the prompt appear if you type something and then hit backspace?

Could you share your `truffle-config.js` in case something there is causing this? Thanks!

**Comment by AfonsoMiao** [comment]
> Thanks for opening this! We'll have to figure out what's going wrong here.
> 
> Are you doing anything else besides running `truffle develop`?
> No

> Also, does the prompt appear if you type something and then hit backspace?
> No

> Could you share your `truffle-config.js` in case something there is causing this? Thanks!
![image](https://user-images.githubusercontent.com/29982581/71581258-47073000-2afc-11ea-8dd8-c55dbb7c041b.png)

**Comment by eggplantzzz** [comment]
@AfonsoMiao This seems really strange. Is this still a problem on the latest version of Truffle? Is your code available so I can see if I can reproduce it? I can't reproduce it on an arbitrary new unboxed project on a mac.

**Comment by AfonsoMiao** [comment]
I guess the problem was in my truffle-config,js
