### ISSUE TITLE
Fix weird intermittent node-ipc/chain.js bug

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#2635]
Every once in a while something goes wrong and it appears to happen in `chain.js`.

90% of the time the only thing that works is restarting one's computer.

What does _on a rare occasion_ work is deleting the truffle ipc lockfile in `/tmp/`.

**Comment by CruzMolina** [comment]
#2632 is possibly related.

**Comment by dongmingh** [comment]
Closing for maintenance. If this issue occurs again, please reopen. Thanks.
