### ISSUE TITLE
sporadic ECONNRESET when running for a long time

### ISSUE THREAD

**Issue by wjmelements** [trufflesuite/truffle#2676]
Using ganache-cli 6.8.1-beta.0. Also happens on ganache-cli 6.8.0-istanbul.0.

The error is
```Invalid JSON RPC response: "Error: connect ETIMEDOUT 127.0.0.1:8545\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"```

The truffle mocha tests run fine for the first 10 minutes or so but then the tests start to take longer and fail sporadically, sometimes mid-test and sometimes in beforeEach.

The early tests take 44-500ms.
![Screen Shot 2019-12-05 at 5 41 44 PM](https://user-images.githubusercontent.com/799573/70288507-be100980-1786-11ea-8cfa-ffd2fd23816e.png)

The tests right before the first failure start to take longer, but less than 500
![Screen Shot 2019-12-05 at 5 42 10 PM](https://user-images.githubusercontent.com/799573/70288562-e7309a00-1786-11ea-9962-95801eda62e0.png)
ms

After the first connection reset, the tests spike above 9000ms, and I have seen them as high as 27000ms.
![Screen Shot 2019-12-05 at 5 42 36 PM](https://user-images.githubusercontent.com/799573/70288593-f44d8900-1786-11ea-96a1-21c44e8299cb.png)

The increase explodes slowly, and did not happen in prior versions, though we were upgrading from ganache-cli 6.1.0.

**Comment by CruzMolina** [comment]
Closing as I believe this has been resolved, but happy to reopen if this week's release or pinning to 5.0.43 does not in fact resolve this issue.
