### ISSUE TITLE
Couldn’t use Truffle HDWallet Provider with Infura websocket

### ISSUE THREAD

**Issue by AmrEShaker** [trufflesuite/truffle#2680]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment]
Can you please give us a little more information about what you are trying to do so we can be sure to fully understand what your issue is?

**Comment by gnidan** [comment]
Closing for issue maintenance. Let us know and we'll reopen!
