### ISSUE TITLE
Upgrading Web3 >= 1.2.2

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#2688]
This is a tracking issue for changes necessary at Truffle to upgrade Web3 above 1.2.1. 

**Resolve #2654**

In #2654, users with long-running test suites saw performance reduction and random ganache disconnection in Truffle versions which use Web3 1.2.2. 

Based on experiments with some of the projects reporting the bug,  I think the underlying issue is the way that truffle/contract manages confirmations handling in combination with a fix in Web3 1.2.2 for broken behavior in that feature.

In Web3 1.2.1 and below, confirmations over http (incorrectly) fire once per second, 24 times, without querying the client.  1.2.2 fixes this by block polling and emitting if  **a new block has been mined**. ([See code][2]). Note that polling only occurs if a conf handler is attached. The number of confirmations the handler should wait for is [configurable][4]. 

Truffle contract automatically attaches confirmation handlers for all transactions here:

https://github.com/trufflesuite/truffle/blob/99add8f5e47586030a44a999bcfb287224e304e1/packages/contract/lib/handlers.js#L44

This means that in a unit test context with thousands of txs, each one will incur a large number of additional background block polling requests. In addition, truffle `evm_reverts` between the tests suites, affecting the block number values relevant for polling. It looks like the combination of these swamps ganache with unnecessary calls, slows things down a lot, and creates instability.

One solution might be to disable confirmation handling in unit tests (where it's rarely used). It could be opt-in.

[2]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L295-L317
[4]: https://web3js.readthedocs.io/en/v1.2.4/web3-eth.html?highlight=confirmations#transactionconfirmationblocks

**Resolve #2657**

#2657 has TS  errors in the HDWalletProvider unit tests. These result from HDWalletProvider not implementing some parts of the Web3 HTTPProvider interface. There are notes about the interface in [2657 comment][3].

[3]: https://github.com/trufflesuite/truffle/pull/2657#issuecomment-563010729

If the above seems unclear / incorrect / incomplete or there's anything that could be fixed at Web3 to help with this, please just ping. 

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by nogo10** [comment]
A few packages have not been upgraded

-- truffle-config@1.1.16
     `-- truffle-provider@0.1.16
      +-- truffle-interface-adapter@0.2.5
      | `-- web3@1.2.1 
       `-- web3@1.2.1

**Comment by elenadimitrova** [comment]
Now that we have `ganache-cli` accepting `--chainId` option can we prioritise pushing `web3` up to at least 1.2.2 as `getChainId` was introduced there and we can't do proper transaction replay attack protection as per EIP-155 without it.

**Comment by cgewecke** [comment]
via #3446

**Comment by cgewecke** [comment]
Re-opening, I think the confirmations handler problem is still live. Sorry.

**Comment by eggplantzzz** [comment]
@cgewecke Can you link to any repos that are experiencing this issue so that we can test against it/them?

**Comment by justinjmoses** [comment]
@eggplantzzz We're going through `solidity-coverage` to run truffle - https://github.com/sc-forks/solidity-coverage/blob/master/package.json#L28 and actually running it all through buidler. Though @cgewecke had mentioned he thinks it's coming in via `builder-truffle5` - https://github.com/nomiclabs/hardhat/blob/buidler-truffle5-v1.3.4/packages/buidler-truffle5/package.json#L36 - which is using a fork of truffle-contract - https://github.com/nomiclabs/truffle/blob/master/packages/contract/package.json

**Comment by cgewecke** [comment]
Hi @eggplantzzz Ganache is being launched as a server within a Truffle plugin like this:
```js
await pify(server.listen)(port);
```

Will try do some additional testing over the weekend to see if commenting out the confirmations handler attachment line stabilizes things at Synthetix.  

As noted in the opening comment in this issue, attaching that handler now results in a large number of additional eth_getBlockNumber requests  *per transaction*. In Web3 1.2.1 confirmations over http was broken and didn't query the client to make sure the block had changed before firing a conf.

The relevant code at Web3 is [here][1]

[1]: https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-method/src/index.js#L550-L552

**Comment by cgewecke** [comment]
@eggplantzzz 

Results of the synthetix repo experiment are:

+ [example of a failing run][1] using @truffle/contract's current state
+ two back-to-back [passing runs][2] using an @truffle/contract fork with [just this line][3] commented out

[1]: https://app.circleci.com/pipelines/github/Synthetixio/synthetix/4284/workflows/1d503b64-4c91-4086-96bd-79e43cebf639/jobs/30768
[2]: https://github.com/cgewecke/synthetix/pull/2
[3]: https://github.com/trufflesuite/truffle/blob/748d904938cc39c69a2c5fe0f642304d9e8331d6/packages/contract/lib/handlers.js#L47

If you click into the CI jobs you can see current truffle/contract running much more slowly: only about ~half the tests execute over 55min (and they crash).

The passing jobs complete all tests in ~40min.

**Comment by eggplantzzz** [comment]
@cgewecke So is this something that it will be possible for me to reproduce locally? Since the number of confirmations is configurable, is it a possible solution to pass in a provider with it configured to 0 for testing? Just a thought.

**Comment by cgewecke** [comment]
> is this something that it will be possible for me to reproduce locally

@eggplantzzz 

It's challenging to reproduce as a simple test because it only becomes a problem at scale e.g with test suites that run for several minutes. 

Maybe by running transactions in a loop and watching the log output from a separate ganache instance? You should see abnormally large numbers of `eth_getBlockNumber` requests.

**Comment by cgewecke** [comment]
Believe another example of this problem has been reported at https://github.com/trufflesuite/ganache-cli/issues/702#issuecomment-723816610

**Comment by MaxFeldman1** [comment]
This just started happening for me when I run truffle debug after my project reached some size, it does not happen when I debug transactions from smaller projects

**Comment by MaxFeldman1** [comment]
I don't know that it has anything to do with the amount/size of tests perhaps it has something to do with the total amount of bytecode/abi complexity

**Comment by eggplantzzz** [comment]
Thanks for all the info guys, I'm going to meet with @gnidan and see if we can figure out a solution to this problem.

**Comment by MaxFeldman1** [comment]
I tried with geth and could not reproduce for me this seems to be specific to ganache

**Comment by gnidan** [comment]
The workaround in #3566 has been released in https://github.com/trufflesuite/truffle/releases/tag/v5.1.55

**Comment by eggplantzzz** [comment]
@cgewecke or @MaxFeldman1 can either of you confirm that the workaround mentioned above fixes this problem?

We didn't really think it was great to disable the confirmation listener across the board so you basically configure `networks['myNetwork'].disableConfirmationListener = true` in `truffle-config.js` to turn it off for your testing network config.

So for example in `truffle-config.js`:
```
module.exports = {
  ... // some config stuff
  networks: {
    testNetwork: {
      host: <host>,
      port: <port>,
      network_id: "*",
      disableConfirmationListener: true
    },
    ... // rest of config stuff
};
```

**Comment by cgewecke** [comment]
Sorry, yes the fix LGTM. Thanks! Closing.

**Comment by eggplantzzz** [comment]
Thanks @cgewecke!
