### ISSUE TITLE
Sometimes Truffle Squashes Errors

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/truffle#2689]
I was running a `truffle migrate`  and the only output I received was:

```
Keccak bindings are not compiled. Pure JS implementation will be used.
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
```

I looked at the exit code with `$?` and it said `1`, so an error did happen, but it was not displayed at all.

I had an error in my `truffle-config.js`, so perhaps a reproduction step might be throwing an error in `truffle-config.js`, but I'm not sure.

There is internal discussion here: https://trufflesuite.slack.com/archives/CB276HKKJ/p1576462322020800

**Comment by lsqproduction** [comment]
Hi @seesemichaelj How's going? Would you be able to provide some reproduction steps for this? 😄 🙏

**Comment by seesemichaelj** [comment]
@lsqproduction No, it's been 3 years and I no longer work at Truffle. I don't remember what the internal Slack discussion was; I can only assume it had more details. I'm closing this and you can choose to create a new issue if you want.
