### ISSUE TITLE
update truffle boxes for solc v0.6.x

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#2698]
Opening this issue here instead of somewhere in the truffle-box org repo.

**Comment by adrianmcli** [comment]
I can just do this, but is there anything I need to be aware of? Or do I just bump the number?

**Comment by CruzMolina** [comment]
It should suffice to bump most pragma statements to...

`pragma solidity >= 0.4.22 < 0.7.0;`

**Comment by adrianmcli** [comment]
Sounds good:

- [ ] Webpack
- [ ] React
- [ ] Pet-Shop
- [ ] Drizzle

**Comment by adrianmcli** [comment]
@CruzMolina this is all done for the "first-class" boxes. Let me know if I am missing any other ones. Otherwise, we can close this issue.

**Comment by CruzMolina** [comment]
don't forget metacoin! :joy:

**Comment by adrianmcli** [comment]
https://github.com/truffle-box/metacoin-box/pull/20

Done, but I think we should probably deprecate it eventually. I don't see much use for that box. I guess we can revisit this once we have our v2 of the box registry system.

**Comment by CruzMolina** [comment]
Closing since it looks like this has been resolved.
