### ISSUE TITLE
Serve uses the wrong contract addresses

### ISSUE THREAD

**Issue by chevdor** [trufflesuite/truffle#270]
## Issue

First, here is an output:

```
$ truffle networks

Network: dev
  ConvertLib: 0xdd24425a04cba4c9d8950f3c79536f30cb5ba55b
  Migrations: 0x1bf51dfb837f6c927f2810487d84ad2346e3d9f0
  PRNG1: 0xf0c19643f903b2ea13834db790671de862613eff

Network: morden
  ConvertLib: 0x7034b88136de7ca975d88b83acb989748bce3352
  Migrations: 0x57401056f09c30651738911961f013276abebe5f
  PRNG1: 0xd8ff9b4345b99bccb2242d8cd66d33bc21578a9c

```

So we see that I deployed to dev (testrpc) and morden.
If I run `truffle serve` things work all good and the 'dev' contract addresses are used.
If I run `truffle serve --network dev`, the problem occurs and the contract on 'dev' are used instead of the morden network.

In build/contract/PRNG1, I noticed the following (truncated to keep it readable):

```
 Contract.all_networks = {
  "2": {                                                    <== Issue here?
    "abi": [....
        ],
        "type": "constructor"
      }
    ],
   ...
  },
  "default": {
    "abi": [
      {
    ...
      }
    ],
    ...
  }
};
```

I suspect the issue to be that instead of the network NAME, the network ID is stored (ie 2 instead of the string 'morden').
## Steps to Reproduce

Build for 2 networks such as testrpc AND morden.
## Expected Behavior

`truffle serve --network dev` uses the addresses from dev
`truffle serve --network morden` uses the addresses from morden
## Actual Results

In any case, the default addresses are used.
## Environment
- Operating System: OSX
- Truffle version: v2.0.8
- Ethereum client: testrpc for dev + geth --testnet for moden
- node version: 6.6.0
- npm version: 3.10.7

**Comment by chevdor** [comment]
After some reading, I suspect that the issue has nothing to do with the serve task itself but with the build process.

To test, in truffle.js, declare 2 instances of testnet for instance:
```
"testnet": {
            network_id: 2, // Official Ethereum test network
            host: "localhost",
            port: 8546
        },
"parity": {
            network_id: 2, // Official Ethereum test network
            host: "localhost",
            port: 8547
        },
```
As the names suggest, I am running geth on testnet on port 8546 and parity also on testnet on port 8547.

Try deploying to 'testnet': `truffle migrate --network testnet`
This will for fine.

Now try deploying to 'parity':  `truffle migrate --network parity`
Nothing will happen unless you specify `--reset` as truffle thinks that we deployed already on network '2'.

**Comment by tcoulter** [comment]
This has been fixed on Truffle 3.x. If you continue to run into this error please open a new ticket. Thanks for the report!
