### ISSUE TITLE
investigate & resolve failing colony job

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#2701]
On the merge for PR #2646, the colony job [failed](https://travis-ci.org/trufflesuite/truffle/jobs/626420945#L1506). We only run the colony job on pushes to `develop`, so there will need to be some investigation to figure out what exactly is causing the new behavior. So far it appears transactions cost more than they used to 🤷‍♂.

Unclear whether this is a regression or actually a fix made to ensure proper behavior.

**Comment by haltman-at** [comment]
Hm, wondering if #2710 could be related? (Although, now that #2723 has come up as well... oy.)

**Comment by gnidan** [comment]
Welcome back from break @haltman-at 😄

**Comment by haltman-at** [comment]
Huh, looks like this is no longer a problem?

**Comment by CruzMolina** [comment]
Looks like #2737 resolved it. 👏
