### ISSUE TITLE
Error: TypeError: soljson.Pointer_stringify is not a function

### ISSUE THREAD

**Issue by PaulRBerg** [trufflesuite/truffle#2702]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Solidity v6 contracts cannot be compiled with truffle 5.1.4

## Steps to Reproduce

1. git clone git@github.com:PaulRBerg/truffle-sol-v6-bug.git
2. yarn install
3. truffe compile

## Expected Behavior

I should be able to compile contracts written in solidity v6.

## Actual Results

The error I'm getting:

```
Error: TypeError: soljson.Pointer_stringify is not a function
    at Object.compile (/Users/paulrberg/.nvm/versions/node/v10.17.0/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:72:1)
Truffle v5.1.4 (core: 5.1.4)
Node v10.17.0
```

## Environment

* Operating System: macOS
* Ethereum client: N/A
* Truffle version (`truffle version`): 5.1.4
* node version (`node --version`): 10.17.0
* yarn version (`yarn --version`): 1.19.2

**Comment by CruzMolina** [comment]
Should be resolved by #2695 & out in this week's release.

**Comment by PaulRBerg** [comment]
Okay, great!

**Comment by gnidan** [comment]
Hey @PaulRBerg how's Truffle v5.1.5? Can you try 0.6.0 now?

**Comment by PaulRBerg** [comment]
Yeah I confirm it's working well now.

**Comment by kuzdogan** [comment]
Leaving this for anyone else encountering the same error.

I was using the global `truffle` binary with `truffle compile`.

Instead use the truffle inside the project: `npx truffle compile`

**Comment by glaksmono** [comment]
How do you fix this issue?

```
bsc-flashswap on  master [✘!?] via  v16.14.2 on ☁️  (ap-southeast-1) 
❯ truffle compile            

Compiling your contracts...
===========================
Error: TypeError: soljson.Pointer_stringify is not a function
    at /Users/glaksmono/.nvm/versions/node/v16.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:368:1
    at /Users/glaksmono/.nvm/versions/node/v16.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:969:1
    at next (/Users/glaksmono/.nvm/versions/node/v16.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:5222:1)
    at /Users/glaksmono/.nvm/versions/node/v16.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:350:1
Truffle v5.0.21 (core: 5.0.21)
Node v16.14.2

bsc-flashswap on  master [✘!?] via  v16.14.2 on ☁️  (ap-southeast-1) took 7s 
❯ truffle version
Truffle v5.0.21 (core: 5.0.21)
Solidity - 0.8.9 (solc-js)
Node v16.14.2
Web3.js v1.0.0-beta.37
```
