### ISSUE TITLE
Truffle doesn't display compilation warnings

### ISSUE THREAD

**Issue by mrwillis** [trufflesuite/truffle#2722]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Compilation warnings do not print

## Steps to Reproduce

Create a project with compilation warnings 

## Expected Behavior

Get compilation warnings printed out

## Actual Results

`truffle compile --all`

> ...
> > Compiling ./contracts/libraries/LibOrderAmounts.sol
> > Compiling ./contracts/libraries/LibOutcome.sol
> > Compiling ./contracts/libraries/LibString.sol
> > Compiling openzeppelin-solidity/contracts/access/Roles.sol
> > Compiling openzeppelin-solidity/contracts/cryptography/ECDSA.sol
> > Compiling openzeppelin-solidity/contracts/math/SafeMath.sol
> > Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol
> > Compilation warnings encountered:
> ,,,,,,,,,,,,,,,,,,,,,,,,,,,,

## Environment

* Operating System: 
* Ethereum client: Ganache CLI v6.7.0-beta.0 (ganache-core: 2.8.0-beta.0)
* Truffle version (`truffle version`): 5.1.7
* node version (`node --version`): 10.5.0
* npm version (`npm --version`): 6.13.4

**Comment by haltman-at** [comment]
I'm getting this too now, quote marks are being printed instead of compilation warnings.  Not sure which particular release introduced this, but it was fine before we went on break...

**Comment by eggplantzzz** [comment]
There is a fix for this in https://github.com/trufflesuite/truffle/pull/2725

**Comment by haltman-at** [comment]
Oops, seems we never closed this.  (This was released in v5.1.8).  Closing!
