### ISSUE TITLE
Cannot compile vyper

### ISSUE THREAD

**Issue by acheron2302** [trufflesuite/truffle#2726]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Error cannot compile vyper contract

## Steps to Reproduce

Compile vyper contract with truffle on vyper-example box with truffle version 5.1.7

## Actual Results

KeyError: '/home/<user>/project/vyper_ERC20/contracts/ERC20.vy'

Compilation of /home/<user>/project/vyper_ERC20/contracts/ERC20.vy failed. See above.

## Environment

* Operating System:  Linux parrot 5.4.0-1parrot1-amd64 #1 SMP Parrot 5.4.6-1parrot1 (2019-12-30) x86_64 GNU/Linux
* Ethereum client: Ganache CLI v6.8.1 (ganache-core: 2.9.1)
* Truffle version (`truffle version`): 
Truffle v5.1.7 (core: 5.1.7)
Solidity v0.5.12 (solc-js)
Node v10.17.0
Web3.js v1.2.1
* node version (`node --version`): v10.17.0
* npm version (`npm --version`): 6.13.4

**Comment by fainashalts** [comment]
Hi @acheron2302, thanks for bringing this up! What version of Vyper are you using?

**Comment by acheron2302** [comment]
@fainashalts i am currently using vyper version: 0.1.0b14+commit.4ac5ef5. And i’m running it in a virtual env

**Comment by CruzMolina** [comment]
Hey @acheron2302 , vyperlang/vyper#1828 appears to be related.

I'm not sure about the exact commit, but downgrading to exactly 0.1.0b14 seems to resolve the issue (at least in our CI).

**Comment by fubuloubu** [comment]
We're working on a fix for this! Our apologies!

**Comment by fubuloubu** [comment]
Fixed in: https://github.com/vyperlang/vyper/pull/1829

Release incoming!

**Comment by fubuloubu** [comment]
b16 has been released. please try again with the new version, this issue should be fixed

**Comment by acheron2302** [comment]
fixed with vyper version: 0.1.0b16+commit.5e4a94a
