### ISSUE TITLE
Code not reached (testing)

### ISSUE THREAD

**Issue by vporton** [trufflesuite/truffle#2745]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

A `then()` is not reached in unit test.

## Steps to Reproduce

Download https://github.com/vporton/courts/tree/4c57e854c80ba6a6ce87739a5ca61669915de979

Run `npm test`.

You see no error message, despite there should be, because in an unknown reason second `.then()` is not reached.

## Expected Behavior

`Wrong court ID` error message.

## Actual Results

No error message.

## Environment

* Operating System: Ubuntu 19.10
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): v5.1.5
* node version (`node --version`): v10.15.2
* npm version (`npm --version`): 6.11.3

**Comment by gnidan** [comment]
Looks like on [this line here](https://github.com/vporton/courts/blob/4c57e854c80ba6a6ce87739a5ca61669915de979/test/reward-courts.js#L9), you need to `return` at the beginning (`return RewardCourts.deployed()...`)

The reason for this is that the test runner must know there is a promise to wait for, so you must return that promise.

Hope this helps!

**Comment by fainashalts** [comment]
Since it doesn't seem like there's a bug here, closing this for issue maintenance. Let us know if the proposed solution above doesn't work. Thanks!
