### ISSUE TITLE
Add Node v13 as a CI job

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/truffle#2749]
Owing to previous problems we had catching up to Node.js LTS versions (see #2070), I have decided to try running the tests under Node v13 in preparation for Node v14 LTS coming online in about 9 months time, or October 2020.

See Node.js release schedule here: https://github.com/nodejs/Release

As of today (2020-01-12), all tests are passing without errors. Commands run:

```
yarn bootstrap
yarn test
```

That being said, the `yarn bootstrap` did yield warnings and errors regarding `scrypt`. Here is an excerpt:

```
2 warnings and 10 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adrianli/dev/truffle/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command \"/Users/adrianli/n/bin/node\" \"/Users/adrianli/dev/truffle/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/adrianli/dev/truffle/node_modules/scrypt
```

Despite this, tests seem to pass with no issues (when run locally).

**Comment by adrianmcli** [comment]
This is kind of strange, because when I did `npm ls scrypt` and even `npm ls scrypt.js`, I find nothing at all.

**Comment by gnidan** [comment]
Hey @adrianmcli what's the action here?

**Comment by adrianmcli** [comment]
@gnidan setup CI to also test on Node v13.

**Comment by davidmurdoch** [comment]
Closing, as we've dropped Node 12 (and v13, too)
