### ISSUE TITLE
Create:migration could populate the migration file a little more

### ISSUE THREAD

**Issue by chevdor** [trufflesuite/truffle#275]
Currently, the following fails:

```
truffle create:contract <ContractName>
truffle create:migration <ContractName>
truffle create:test <ContractName>
```

The issue is that `create:migration` creates an empty migration.

It would be nicer to create the file in the migration folder as:

```
module.exports = function(deployer) {
  deployer.deploy(<ContractName>);
};
```

**Comment by gnidan** [comment]
Is this still an issue? It looks like I said that it wasn't in the PR. Let me know and I'll reopen. Thanks!
