### ISSUE TITLE
I cant get my new token to go public. I am throwing the following error! All efforts to resolve online have been unfruitful 

### ISSUE THREAD

**Issue by Gre3nergy** [trufflesuite/truffle#2759]
I am attempting to compile my test token to a live setting.  When I compile, I get the following error. I assume that this callback is not reaching the destination.

myc:3:1: ParserError: Source "EIP20Interface.sol" not found: File import callback not supported
import "./EIP20Interface.sol"
^----------------------------^

I am using v0.4.21+commit.dfe3193c and have made sure that the optimization is turned on and the constructor arguments are clear. I basically copy and pasted exactly what I used to create the original test token...but am getting this error. I used the https://github.com/ConsenSys/Tokens/blob/master/contracts/eip20/EIP20.sol template to complete the initial test token.

**Comment by Gre3nergy** [comment]
![AVNT problem](https://user-images.githubusercontent.com/26776754/72395949-52f81200-36f8-11ea-8546-744c9f345f05.JPG)

**Comment by gnidan** [comment]
Hey @Gre3nergy, what's your `truffle version`? Can you also share your truffle config? (Please remove any sensitive information before sharing)

**Comment by Gre3nergy** [comment]
Hey gnidan,
Thank you for your response! how do I view/access the truffle version? " v0.4.21+commit.dfe3193c"?

**Comment by gnidan** [comment]
Run `truffle version` in the command line and that'll tell you mostly all the relevant information.

**Comment by Gre3nergy** [comment]
Do i have to install the npm truffle application within dev box?

**Comment by Gre3nergy** [comment]
i think i may have put this issue in the wrong place...i am attempting to get general help to get my test token into a public domain and have it be searched publicly for an ICO. any help would be greatly appreciated.

**Comment by gnidan** [comment]
Ah, this is probably not the best place for that sort of thing, since Truffle's GitHub issues are meant for bugs and/or feature requests related to Truffle itself. Maybe try Reddit?

But to answer your question:
> Do i have to install the npm truffle application within dev box?

Yep, you'll need to do `npm install -g truffle` in order to use Truffle.

**Comment by gnidan** [comment]
Closing this for issue maintenance. Let us know if there's anything else we can do to help!
