### ISSUE TITLE
 Can't get value from deployed contract 

### ISSUE THREAD

**Issue by yxguo2536** [trufflesuite/truffle#2771]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm trying to use truffle on Quorum, so I followed tutorial - [Building dapps for Quorum: Private Enterprise Blockchains](https://www.trufflesuite.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains)

## Steps to Reproduce

1. unlike tutorial using vagrant, I use docker to build 4 nodes, but I also port forward them to 22000~22003
2. truffle init
3. edit `truffle-config.js`
```javascript
networks: {
     development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 22000,
      network_id: "*",       // Any network (default: none)
      gasPrice: 0,
      gas: 4500000,
      type: "quorum"
     },
}
```
4. create `contract/SimpleStorage.sol` and  change required solc to `^0.5.16`, then command `truffle compile`
5. create `migrations/2_deploye_simplestorage.js` and modify `privateFor` parameter
```javascript
var SimpleStorage = artifacts.require("SimpleStorage");

module.exports = function(deployer) {
  // Pass 42 to the contract as the first constructor parameter
  deployer.deploy(SimpleStorage, 42, {privateFor: ["QE/RfPZh4yom6qPZOk8gfFLMeePGE+F+uG4532VinUs="]})
};
```
6. unlock account: `geth attach --exec "personal.unlockAccount(eth.accounts[0], '', 60)" http://127.0.0.1:22000`
7.  deploy contract: `truffle migrate`

## Expected Behavior
According to tutorial, I should be able to get value from contract once my `truffle migrate` done
```javascript
truffle console
truffle(development)> SimpleStorage.deployed().then(function(instance) { return instance.get(); })
{ [String: '42'] s: 1, e: 1, c: [ 42 ] }
```

## Actual Results
```javascript
truffle console
truffle(development)> SimpleStorage.deployed().then(function(instance) { return instance.get(); })
BN { negative: 0, words: [ 0, <1 empty item> ], length: 1, red: null }
```

## Environment
* Operating System: Ubuntu 16.04.6 LTS
* Ethereum client: 1.8.27-stable ( host ) / 1.8.18-stable + Quorum 2.4.0 ( container )
* Truffle version (`truffle version`): v5.1.9
* node version (`node --version`): v13.6.0
* npm version (`npm --version`): 6.13.4

**Comment by gnidan** [comment]
Hey @yxguo2536, could you throw an extra `.then` onto the end to convert to string?

```javascript
truffle(development)> SimpleStorage.deployed().then(function(instance) { return instance.get(); }).then(function(bn) { return bn.toString() });
```

The first thing to notice is that the tutorial is probably out of date. Your expected result is a BigNumber, but Truffle now uses the BN library instead. If you convert to a string, you'll see if you get `"42"` or not.

Let us know! Thanks!

**Comment by yxguo2536** [comment]
Hi @gnidan, thanks for the help, now I can get a clear value.

But strangely, even from sender node, I still get `0` from it.

I also tried to get value using geth:
```javascript
geth attach http://127.0.0.1:22000
> personal.unlockAccount(eth.accounts[0], '', 1800)
> eth.defaultAccount = eth.accounts[0]

> var abi = [{"inputs":[{"internalType":"uint256","name":"initVal","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"constant":true,"inputs":[],"name":"storedData","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"uint256","name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"internalType":"uint256","name":"retVal","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]
> var address = "0x2a418829B7ce327FC14F1B463C81D517E2aA7966"
> var private = eth.contract(abi).at(address)

> private.get()
0
```

and it also return `0` instead of what I initialized `42`

Does it means my deployment went wrong somehow?

**Comment by gnidan** [comment]
Hm, this is a bit strange... you're configuring Truffle for Quorum, but Geth is not Quorum. Not sure if that discrepancy matters here, but that's my first thought. You might want to remove `type: quorum` if you're only planning to use Geth.

**Comment by yxguo2536** [comment]
I've tried to change geth version of host machine to quorum, but still no luck
```bash
$ geth version

Geth
Version: 1.8.18-stable
Git Commit: b1f3b96ea0d524c34094666ed113af5e6ba5f6bf
Quorum Version: 2.4.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.13.5
Operating System: linux
GOPATH=/home/bcserver1/go
GOROOT=/usr/local/go
```

and since I want to send private transaction, so I do need to config truffle for quorum

**Comment by gnidan** [comment]
Hm looks like this needs investigation! We'll look into it a bit more and get back to you. Thanks again!

**Comment by gnidan** [comment]
Hey @yxguo2536 is this still an issue for you? Sorry to drop the ball on this for two years, but please let us know if this is something you know is still an issue. Thank you!

**Comment by gnidan** [comment]
(Marking this as waiting, but there may be action we could take here, namely to revisit the old Quorum tutorial for accuracy today)

**Comment by yxguo2536** [comment]
Hi @gnidan, thanks for your asking, I couldn't solve this issue back then, so I have to end the project there, and unfortunately I didn't keep the environment to reproduce this issue, so sorry I can't help on this :(

**Comment by eggplantzzz** [comment]
Sorry about that @yxguo2536. We'll close this for issue maintenance for now, if you re-encounter this and can re-report it we would appreciate it!
