### ISSUE TITLE
Truffle test does not work when using a ganache networkID of my favourite number: 69420

### ISSUE THREAD

**Issue by mcplums** [trufflesuite/truffle#2772]
# Issue

If ganache is run with a network ID of 69420 I get the error "TypeError: Cannot read property 'gasUsed' of null".

It has to be 69420. Not 69419, or 69421. 

## Steps to Reproduce

Clone this https://github.com/ConsenSys-Academy/truffle-test-debugging

Start ganache- `ganache-cli -l 10000000 --networkId 69420`
In a different  terminal, navigate to project-dir
`truffle test`

## Expected Behavior

I expect the tests to pass

## Actual Results

I get the error "TypeError: Cannot read property 'gasUsed' of null".

## Environment

* Operating System: OS Catalina
* Ethereum client: Ganache CLI v6.7.0
* Truffle version (`truffle version`): Truffle v5.1.3
* node version (`node --version`): v10.17.0
* npm version (`npm --version`): 6.13.1

I think we can all agree this problem is of great importance and needs all of Truffle's top men on it asap. Do you want to live in a world where we are not free to set out network Ids to 69420? I didn't think so.

**Comment by fainashalts** [comment]
Hi @mcplums is this a real issue? 😂 I agree 69420 is a fantastic number. We got together all our best men(and women) and couldn't reproduce it. If you are still having trouble with this, please send more steps on how to reproduce, thanks!

**Comment by mcplums** [comment]
Haha well, the issue is real, but it is not one worth taking seriously since it is easy to just use a different ID :) probably not worth the effort to try and get you guys to reproduce it! So I have closed it :)
