### ISSUE TITLE
$Truffle Develop missing from readme.md

### ISSUE THREAD

**Issue by mcwebdev** [trufflesuite/truffle#2785]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

New users will be confused that `truffle test` returns the following error.
```
> Something went wrong while attempting to connect to the network. Check your network configuration.

Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8545
    - network_id > *
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```

## Steps to Reproduce
run `truffle test` before running `trufle develop`

## Proposed resolution
Add instructions for running `truffle develop` in new cmd window prior to running `truffle test`

**Comment by eggplantzzz** [comment]
Hey @mcwebdev, you shouldn't need to run `truffle develop` before you run `truffle test`. You can run the test command after running `truffle develop` but you should be able to run `truffle test` without it. I think there will be a problem if you have a network named `develop` in `truffle-config.js` with bad network settings however...

**Comment by eggplantzzz** [comment]
Perhaps we should put a note in the README specifying that if Truffle finds a network named "develop", it will use those settings when running `truffle develop`? Although it might already be in there somewhere, I will have to check!

**Comment by eggplantzzz** [comment]
So it looks like we do already have that in the docs [here](https://www.trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console#configuring-truffle-develop).
Do you think it would be helpful to add it elsewhere @mcwebdev?

**Comment by mcwebdev** [comment]
The problem I had was this line of instruction in the readme.md after `$ truffle init`.

`From there, you can run truffle compile, truffle migrate and truffle test to compile your contracts, deploy those contracts to the network, and run their associated unit tests.`

given the inited boilerplate generated above using `$ truffle init`. I was unable to run `truffle test` until I ran `truffle develop` in a new cmd window.

Given the above, new users would likely appreciate an instruction after `$ truffle init`. 

```Run `truffle develop` in new cmd window. ```

If this is not the preferred work flow, please come to this readme.md with a blank slate and see if you can run tests following only the given commands in the readmne.md. Perhaps the underlying boilerplate also needs to change per @eggplantzzz comment above ```but you should be able to run truffle test without it. ```

**Comment by eggplantzzz** [comment]
So just to confirm, after doing a branch new `truffle init`, you cannot run `truffle test` successfully directly afterwards? I am unable to duplicate this behavior. Can you verify that this is the behavior on the latest Truffle (5.1.12).

**Comment by gnidan** [comment]
Hey @mcwebdev, going to close this issue as part of issue maintenance. If you happen to get back to this stuff, feel free to comment and we can always reöpen. Thanks!
