### ISSUE TITLE
Watch crashes if the contracts currently do not compile

### ISSUE THREAD

**Issue by chevdor** [trufflesuite/truffle#279]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---
## Issue

`truffle watch` crashes if the contracts currently do not compile
## Steps to Reproduce

run `truffle watch`, edit a contract with a mistake that prevent compiling, save
## Expected Behavior

The error is displayed, watching keeps going though.
## Actual Results

An unhandled exception is throw:

```
truffle/node_modules/solidity-parser/index.js:39
      throw e;
```
## Additional note

The exception has to be caught probably in 
`truffle/lib/profiler.js:134:36`

**Comment by tcoulter** [comment]
This has been fixed on master. Thanks!
