### ISSUE TITLE
Can't install Truffle

### ISSUE THREAD

**Issue by mohamedsgap** [trufflesuite/truffle#2819]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't install truffle

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
![truffleError](https://user-images.githubusercontent.com/30293804/74114972-9473c400-4bb5-11ea-8925-2c8dd8cb1f3a.png)

## Environment

* Operating System: Linux Ubuntu 18.04
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`): 10.16.1
* npm version (`npm --version`): 6.9.0

**Comment by eggplantzzz** [comment]
Hey @mohamedsgap, it looks like you might need to edit the permissions for your user. If you do not have permission to write then you definitely won't be able to install Truffle. Try giving more permissions to the user that you are logged in as or logging in as a user that has more privileges. Good luck!

**Comment by mohamedsgap** [comment]
Hey guys,  I solved this issue using Yarn:
```
yarn global add truffle 
```
I think it works with `yarn` maybe because I use it in my development  environment daily instead of `npm`
