### ISSUE TITLE
Truffle Decoder's methods for Web3 contract instances

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/truffle#2821]
I was stumped for much longer than I would like to admit when I was passing in the Web3 contract instance into the decoder's `forContractInstance` instead of a Truffle contract instance.

Being that the decoder seems to use Web3 internally anyway, could we not have a convenience function, `forWeb3ContractInstance` that can allow for more ergonomic usage?

**Comment by haltman-at** [comment]
This is not so easy as you suggest; it would not be just a convenience function.  The decoder uses Web3, yes, but it does not use Web3 contracts; it uses Web3 for functionality like looking up code or storage on the blockchain.  Now, this might be possible, but even if it's possible it might not be a good idea -- a Web3 contract just doesn't contain as much information, and I don't want to accidentally imply that a decoder built from one would be just as functional as one built from a Truffle contract (it wouldn't; it would necessarily have to return less information in a number of cases (although I haven't taken the time at the moment to determine just what cases)).

Anyway, can possibly mark this down as a thing to do, but I don't think this is going to be a high priority?

**Comment by adrianmcli** [comment]
There are two alternatives if we don't want to support Web3 contract instances:

1. Just pass in the JSON artifact:

```js
Decoder.forContractArtifact(myJsonArtifact)
```

2. Pass in what you need individually:

```js
Decoder.forCustomProps({
  abi: artifact.abi,
  ast: artifact.ast,
  ...etc
})
```

^ Note, I'm not happy with the naming of `forCustomProps` but it's the best I can come up with right now.

I do think this is higher priority than it may seem at first, because right now you are requiring any users of `@truffle/decoder` to also install `@truffle/contract` (something that is widely known to be disliked outside of Truffle).

**Comment by haltman-at** [comment]
> Decoder.forContractArtifact(myJsonArtifact)

This exists!  (With slightly different syntax.)  It's called `forArtifact`.  You don't need to use Truffle Contract!  However, `forArtifact` does additionally require you to supply a provider.  I just made `forContract` as a convenience so you don't have to supply a provider as well.  But you can use the more basic `forArtifact` if you're OK with artifacts but not Truffle Contract!

I was honestly unaware that Truffle Contract was so unpopular outside of Truffle.  I may have to ask you about that later...

**Comment by adrianmcli** [comment]
Ah cool, that sounds much better. I'll use `forArtifact` for now then. And yes, Truffle Contract is not used at all in modern dapp development.

**Comment by haltman-at** [comment]
Oops, clarification here: `forArtifact` slots into the role of `forContract`, not `forContractInstance`.  If you want the equivalent of `forContractInstance`, you want either `forArtifactAt` (takes an artifact, a provider, and an address) or `forDeployedArtifact` (takes an artifact and a provider; autodetects the address as the one from deployment).  Regardless, there's no requirement to pass in a Truffle Contract at any point.

Anyway you can see the docs for details, this is all listed there, but thought I should point that out.

**Comment by gnidan** [comment]
Looks like the original issue here is solved, since we have `forArtifactAt` and `forDeployedArtifact`. The business about web3.eth.Contract is "won't fix". The business about taking an options argument seems out of scope for this ticket. Closing!

Thanks @adrianmcli 🙇
