### ISSUE TITLE
Truffle fails to install

### ISSUE THREAD

**Issue by Belial-public** [trufflesuite/truffle#2840]
- [ x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle npm fails to install

## Steps to Reproduce

Install nodejs and then type: `npm install -g truffle`

## Expected Behavior

Install the package

## Actual Results

```
npm ERR! prepareGitDep > lerna run prepare --stream --concurrency=1
npm ERR! prepareGitDep
npm ERR! prepareGitDep @truffle/blockchain-utils: yarn run v1.22.0
npm ERR! prepareGitDep @truffle/blockchain-utils: $ yarn build
npm ERR! prepareGitDep @truffle/blockchain-utils: $ tsc
npm ERR! prepareGitDep @truffle/blockchain-utils: index.ts(1,53): error TS2307: Cannot find module 'web3/providers'.
npm ERR! prepareGitDep @truffle/blockchain-utils: test/methods.test.ts(2,20): error TS2307: Cannot find module 'assert'.
npm ERR! prepareGitDep @truffle/blockchain-utils: test/methods.test.ts(3,30): error TS2307: Cannot find module 'mocha'.
npm ERR! prepareGitDep @truffle/blockchain-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep @truffle/blockchain-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep lerna notice cli v3.20.2
npm ERR! prepareGitDep lerna info versioning independent
npm ERR! prepareGitDep lerna info Executing command in 13 packages: "yarn run prepare"
npm ERR! prepareGitDep @truffle/blockchain-utils: error Command failed with exit code 2.
npm ERR! prepareGitDep @truffle/blockchain-utils: error Command failed with exit code 2.
npm ERR! prepareGitDep lerna ERR! yarn run prepare exited 2 in '@truffle/blockchain-utils'
npm ERR! prepareGitDep lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! undefined prepare: `lerna run prepare --stream --concurrency=1`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the undefined prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\XXX\AppData\Roaming\npm-cache\_logs\2020-02-20T07_18_04_772Z-debug.log
npm ERR! prepareGitDep
npm ERR! code 2
npm ERR! null: npm exited with code 2 while attempting to build undefined. Clone the repository manually and run 'npm install' in it for more information.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\XXX\AppData\Roaming\npm-cache\_logs\2020-02-20T07_18_04_831Z-debug.log
```

## Environment

* Operating System: win10

$ npm -v
6.9.0

$ node -v
v10.15.3

$ uname -a
MINGW64_NT-10.0 Belial 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys

**Comment by Belial-public** [comment]
The previous 2 errors when running the npm install were on missing `yarn` and `tsc`, which I've installed globally. Now the error is the one above

**Comment by Belial-public** [comment]
Solved it for now by installing it over WSL. But kinda curious why this doesn't work out of the box

**Comment by CruzMolina** [comment]
Are you sure you are just installing truffle globally, or are you also trying to develop the project locally?

**Comment by Belial-public** [comment]
> Are you sure you are just installing truffle globally, or are you also trying to develop the project locally?

`npm install -g truffle` is to install truffle globally, it has nothing to do with develop. With the settings I gave above it should be reproducible

**Comment by gnidan** [comment]
Seems like we need to get to the bottom of this

**Comment by wangdayong228** [comment]
> Solved it for now by installing it over WSL. But kinda curious why this doesn't work out of the box

Have you solved? I also blocked by this issue.
```
@truffle/blockchain-utils: index.ts(2,53): error TS2307: Cannot find module 'web3/providers' or its corresponding type declarations.
@truffle/blockchain-utils: test/methods.test.ts(2,20): error TS2307: Cannot find module 'assert' or its corresponding type declarations.
@truffle/blockchain-utils: test/methods.test.ts(3,30): error TS2307: Cannot find module 'mocha' or its corresponding type declarations.
```
where's  could I download the package "web3/providers"?

**Comment by wangdayong228** [comment]
> Are you sure you are just installing truffle globally, or are you also trying to develop the project locally?

I want to develop the project locally In Macos and I am blocked by this issue, could you tell me from where I could download the module "web/providers"? thank you.

**Comment by wangdayong228** [comment]
> Are you sure you are just installing truffle globally, or are you also trying to develop the project locally?

I want to develop the project locally In Macos and I am blocked by this issue, could you tell me from where I could download the module "web/providers"? thank you.

**Comment by gnidan** [comment]
Hey, is this still an issue?

**Comment by gnidan** [comment]
> Hey, is this still an issue?

Hopefully silence means no! 

Closing this for issue maintenance 😄 (but let us know if the problem still exists and we'll re-open)

Thanks!

**Comment by kcelestinomaria** [comment]
Hello @gnidan , having this same problem running on Ubuntu 20.04 OS, yet it works on WSL: Here is the error:  npm install -g truffle
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /root/.nvm/versions/node/v16.2.0/lib/node_modules/truffle
npm ERR! dest /root/.nvm/versions/node/v16.2.0/lib/node_modules/.truffle-rqfcm8kd
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/root/.nvm/versions/node/v16.2.0/lib/node_modules/truffle' -> '/root/.nvm/versions/node/v16.2.0/lib/node_modules/.truffle-rqfcm8kd'
