### ISSUE TITLE
Broken TypeScript typings on fresh install

### ISSUE THREAD

**Issue by kdembler** [trufflesuite/truffle#2855]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

After a fresh install of `@truffle/hdwallet-provider` (other packages possibly affected as well) TypeScript typings are not working correctly and compilation fails.

Mentioned in trufflesuite/ganache-core#465 but it's a different repo and didn't gain much traction

## Steps to Reproduce

1.  `npm install @truffle/hdwallet-provider web3`
2.  Put inside `src/index.ts`:
```js
import HDWalletProvider from "@truffle/hdwallet-provider";
console.log("Hello world!")
```
3.  `npx typescript --esModuleInterop src/index.ts`

## Expected Behavior

Compilation succeeds without any issues.

## Actual Results

Typecheck fails with the following errors:
```
node_modules/@truffle/hdwallet-provider/dist/index.d.ts:2:61 - error TS2307: Cannot find module 'ethereum-protocol'.
import { JSONRPCRequestPayload, JSONRPCErrorCallback } from "ethereum-protocol";
                                                             ~~~~~~~~~~~~~~~~~~~
node_modules/@truffle/hdwallet-provider/dist/index.d.ts:3:43 - error TS2307: Cannot find module 'web3/providers'.
import { Callback, JsonRPCResponse } from "web3/providers";
                                           ~~~~~~~~~~~~~~~~
```

## Environment

* Operating System: Tested on macOS and Arch Linux
* node version (`node --version`): Tested on `v10.18.0` and `v13.9.0`
* npm version (`npm --version`): `6.13.4`, `6.13.7`

**Comment by CruzMolina** [comment]
Ah, looks like we're missing those two pkgs as devDeps (`ethereum-protocol`, `@types/web3`)

**Comment by forshtat** [comment]
@CruzMolina I am not sure the PR solves the problem, as it the latest '@types/web3' does not include any types and instead says, quote, "web3 provides its own type definitions, so you don't need @types/web3 installed!"
But then there seems to be no "web3/providers" in the original web3 package.

**Comment by Butterneck** [comment]
> @CruzMolina I am not sure the PR solves the problem, as the latest '@types/web3' does not include any types and instead says, quote, "web3 provides its own type definitions, so you don't need @types/web3 installed!"
> But then there seems to be no "web3/providers" in the original web3 package.

Did you find a solution? I'm having the same issue #3777
