### ISSUE TITLE
Error on truffle init

### ISSUE THREAD

**Issue by codenamejason** [trufflesuite/truffle#2867]
## Issue

truffle init errror

## Steps to Reproduce

run truffle init

## Expected Behavior

initialization success

## Actual Results

Starting unbox...
=================

√ Preparing to download box
\ DownloadingError: write EPROTO 20712:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)

## Environment

* Operating System: Windows 10 Pro
* Ethereum client: Ganache
* Truffle version (`truffle version`): 5.1.14
* node version (`node --version`): 12.10.0
* npm version (`npm --version`): 6.10.3

**Comment by gnidan** [comment]
Thanks for reporting this! We'll look into it and figure out a solution or at least a workaround for you.

**Comment by codenamejason** [comment]
I have heard from a few devs they have had problems on Windows also. My Ubuntu box just blew up so I need a new one 👍

**Comment by haltman-at** [comment]
Closing this so we can consolidate discussion on #2966, since that appears to be the same thing.
