### ISSUE TITLE
ReferenceError in lib/repl.js: done is not defined

### ISSUE THREAD

**Issue by mpolci** [trufflesuite/truffle#290]
## Issue

In https://github.com/ConsenSys/truffle/blob/master/lib/repl.js#L25 there is a reference to an undefined function `done()`
## Environment
- Truffle version: 2.1.0

**Comment by Tectract** [comment]
This can happen when your node is node running / responding, I've noticed.

**Comment by tcoulter** [comment]
This has been fixed. Thanks!
