### ISSUE TITLE
Cannot install truffle@5.0.2

### ISSUE THREAD

**Issue by loyo888** [trufflesuite/truffle#2900]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to install truffle@5.0.2 on my Mac and keep getting an error message. I changed the permissions of the file but still cannot get it to work.

## Steps to Reproduce

Open terminal and type npm install -g truffle@5.0.2

## Expected Behavior

It should install

## Actual Results

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:

## Environment

* Operating System: MacOS Mojave 10.14.6
* Ethereum client: 
* Truffle version (`@5.0.2`):
* node version (`v12.16.1`):
* npm version (`6.13.4`):

**Comment by gnidan** [comment]
Hey! Sorry about this, there was a problem with that version (and likely others). You should be able to work around this by using [NVM](https://github.com/nvm-sh/nvm).

Closing this for issue maintenance, but let us know if you run into further difficulty. Thanks!
