### ISSUE TITLE
npm audit vulnerabilities for hdwallet-provider 

### ISSUE THREAD

**Issue by mrdavey** [trufflesuite/truffle#2921]
## Issue

`npm audit` finds 3 vulnerabilities, with 1 high vulnerability. 

## Steps to Reproduce

1. Create a new npm project
2. `npm install @truffle/hdwallet-provider`
3. `npm audit`

## Expected Behavior

No vulnerabilities found

## Actual Results

3 vulnerabilities are found. Screenshot:
![screenshot](https://i.imgur.com/8wAYgBy.png)

## Environment

* Operating System: macOS Catalina
* Ethereum client: n/a
* Truffle version (`truffle version`): v5.1.10 (core: 5.1.10)
* node version (`node --version`): v11.15.0
* npm version (`npm --version`): 6.14.2

**Comment by eggplantzzz** [comment]
Thanks for bringing this up! We'll get on it!

**Comment by eggplantzzz** [comment]
Oh, the worst one is from `web3`. That will not be easy one, let's see if someone has reported that to `web3`.

**Comment by eggplantzzz** [comment]
Well, I don't think there is anything we can do about the web3 dependency at this time. Any thoughts @gnidan?

**Comment by eggplantzzz** [comment]
`web3` got a version bump in Truffle version `5.1.50` which got rid of the last two vulnerabilities on the list. At the moment we cannot get rid of `web3` as a dependency of Truffle so I'm not sure we can do anything about that one.

**Comment by gnidan** [comment]
Since we got rid of all the high-severity vulnerabilities, can this be closed? Not sure there's anything we can do about the remaining low-severity ones.

**Comment by gnidan** [comment]
Closing this, then! If anyone observes this problem in the future, we'll be happy to re-open. Let us know! Thanks!

**Comment by frangio** [comment]
Is there a reason why Truffle pins its web3 dependency rather than accepting a semver range? My understanding is that the newer releases are more stable than they used to be, so it should be fine. This would automatically allow Truffle to have this kind of issue resolved once it's fixed upstream in web3.
