### ISSUE TITLE
rinkeby-fork not using specified address from HD Wallet Provider

### ISSUE THREAD

**Issue by pizzarob** [trufflesuite/truffle#2928]
HD Wallet Provider in the truffle.js config file doesn't seem to be working properly when doing a dry-run using rinkeby-fork. The HD wallet provider has no effect on the accounts array during a dry run migration.

```js
  "rinkeby-fork": {
      provider() {
        // Has no affect on accounts array. Still populated with 10 random addresses when 
        // I expect only one.
        return new HDWalletProvider(
          privateKey,
          "https://rinkeby.infura.io/v3/API_KEY"
        );
      },
      network_id: 4,
    },
```

**Comment by haltman-at** [comment]
Thanks for the report!  What Truffle version did this occur in?

**Comment by pizza-r0b** [comment]
@haltman-at  5.1.2

**Comment by haltman-at** [comment]
OK.  Do you know if it still occurs in the most recent version?

**Comment by pizzarob** [comment]
Yeah looks like it does @haltman-at - updated to version Truffle v5.1.22

**Comment by gnidan** [comment]
My hunch is that the code that sets up the dry-run probably doesn't respect the accounts in the provider. Hopefully we can get a quick look into this soon and spot the error quickly.

Thanks for raising this!

**Comment by dongmingh** [comment]
@pizzarob can you confirm if the issue is fixed in the latest Truffle? We think this is fixed. Thanks in advance!

**Comment by MicaiahReid** [comment]
We haven't heard anything back on this, so we're calling it fixed! Please open another issue if you're finding that this is still happening.
