### ISSUE TITLE
const m=require('<module>') in src/js/app.js doesn't work | Cannot inclue npm modules/packages

### ISSUE THREAD

**Issue by DeveloperAbhirupa** [trufflesuite/truffle#2930]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by DeveloperAbhirupa** [comment]
I am trying to invoke bigchaindb-driver from app.js
npm i bigchaindb-driver

<u>app.js</u>
const db = require('bigchaindb-driver')

<u><i>Error</u></i>
`Cannot find module 'bigchaindb-driver' 
    o http://localhost:3000/js/web3.min.js:1
    o http://localhost:3000/js/web3.min.js:1
    <anonymous> http://localhost:3000/js/app.js:1`

**Comment by haltman-at** [comment]
Thanks for the report, but this doesn't appear to be a Truffle issue; this looks like purely an issue with npm.  Thanks for using Truffle!  Let us know if we've misunderstood and we can reopen this.
