### ISSUE TITLE
No Bytecode Generated for Compiled Contract

### ISSUE THREAD

**Issue by mudgen** [trufflesuite/truffle#2951]
## Issue

The command `truffle compile` will fail to generate the bytecode in .json files for contracts that have their interface defined in other contracts that are also being compiled.

## Steps to Reproduce
**Step 1.** Create two very simple contracts.  Let's call them TestA.sol and TestB.sol.
**Step 2.** TestB.sol contains an interface definition of the TestA.sol contract.

Here is what TestA.sol looks like:
```solidity
pragma solidity ^0.6.2;

contract TestA {
    function doSomething() external pure returns (address) {
        return address(0);
    }
}
```
Here is what TestB.sol looks like:
```solidity
pragma solidity ^0.6.2;

interface TestA {
    function doSomething() external pure returns (address);
}

contract TestB {
    function get_id() public pure returns (uint256) {
        return 25;
    }
}
```

**Step 3.** Put these two contracts in a directory called "contracts".  Then execute "truffle compile".

**Step 4.** Look at the generated bytecode for contract TestA.json that should exist in the TestA.json file. It does not exist.  Here is a screenshot:

![no bytecode](https://i.ibb.co/Ky1HXpN/zerobytecode.png)

## Expected Behavior

I expected the bytecode for contract TestA.sol to be in TestA.json.

## Actual Results

The bytecode for TestA.sol was missing in TestA.json.

Perhaps TestA.json was created for the interface rather than the contract. I think it should be the other way around.

## Environment

* Windows 10
* Truffle v5.1.21 (core: 5.1.21)
* Solidity - 0.6.2 (solc-js)
* Node v10.18.1
* Web3.js v1.2.

**Comment by gnidan** [comment]
Looks like #1087 strikes again!

Sorry for the inconvenience; Truffle has a long-standing limitation that prevents having two contracts with the same name.

Closing this as duplicate, but thank you for reminding me that this issue is _really freakin' annoying_ ;)

**Comment by mudgen** [comment]
Okay, thanks!

**Comment by gnidan** [comment]
Interesting @mudgen.

There might be a workaround here, to omit artifacts for interfaces. If you'd like to take a look at doing this, would love a PR! (Or maybe just open an issue for that specific task)
