### ISSUE TITLE
Truffle should succeed when there are warnings when options.strict is false

### ISSUE THREAD

**Issue by tharidu** [trufflesuite/truffle#296]
## Issue

Currently in lib/compiler.js strict == false is not checked, hence warnings are considered as errors. But when strict = false, it should succeed and compile the contracts

## Steps to Reproduce

Comment the pragma declaration

## Expected Behavior

It should show a warning but still compile the contracts

## Actual Results

Right now, strict flag is not respected so compilation fails

**Comment by tcoulter** [comment]
This is fixed in `truffle-compile` v1.1.2. You can get this upgrade now by uninstalling Truffle and then reinstalling it, to ensure the new dependency is downloaded. It will also go out with the next release of Truffle, 3.1.2. Thanks for the issue!
