### ISSUE TITLE
Can't install Truffle on Ubuntu

### ISSUE THREAD

**Issue by nkwazi** [trufflesuite/truffle#2967]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Can't install truffle there is an error in the `postinstall.js` script

## Steps to Reproduce

Run command `npm install -g truffle`

## Expected Behavior

Truffle is installed

## Actual Results

Truffle is not installed

## Environment

* Operating System: Ubuntu 16.04 LTS
* Ethereum client: 1.9.12-stable
* Truffle version (`truffle version`): - 
* node version (`node --version`): v4.2.6
* npm version (`npm --version`): 3.5.2

**Comment by eggplantzzz** [comment]
@nkwazi Would you be able to get us what error you are getting while trying to install Truffle? This would be super helpful with helping us debug this.

**Comment by nkwazi** [comment]
```
npm install -g truffle
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/home/nkwazi/.npm-global/bin/truffle -> /home/nkwazi/.npm-global/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.21 postinstall /home/nkwazi/.npm-global/lib/node_modules/truffle
> node ./scripts/postinstall.js

/home/nkwazi/.npm-global/lib/node_modules/truffle/scripts/postinstall.js:1
(function (exports, require, module, __filename, __dirname) { const { statSync } = require("fs");
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm ERR! Linux 4.15.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "truffle"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! truffle@5.1.21 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the truffle@5.1.21 postinstall script 'node ./scripts/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the truffle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs truffle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls truffle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     `/home/nkwazi/npm-debug.log

```

**Comment by nkwazi** [comment]
[npm-debug.log](https://github.com/trufflesuite/truffle/files/4488657/npm-debug.log)

**Comment by gnidan** [comment]
Hm @nkwazi looks like you're on Node v4, is that correct?

Truffle requires at least Node v8 (Node v10 preferred)

**Comment by nkwazi** [comment]
@gnidan Thanks, that worked 🤦  sorry for the buzz.

**Comment by gnidan** [comment]
All good! Glad it was an easy fix :)

**Comment by embaby97** [comment]
npm install -g truffle
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/home/alaa/.npm-global/bin/truffle -> /home/alaa/.npm-global/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.24 postinstall /home/alaa/.npm-global/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.24
added 27 packages from 439 contributors in 25.411s

**Comment by embaby97** [comment]
> Hm @nkwazi looks like you're on Node v4, is that correct?
> 
> Truffle requires at least Node v8 (Node v10 preferred)

i am not able to install it , idont konw what to do 
i have istalled it a day befor and was ok
