### ISSUE TITLE
Tezos Compiling and Migrating Contracts

### ISSUE THREAD

**Issue by amateur-dev** [trufflesuite/truffle#2968]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
No
---------------------------

## Issue

```
Something went wrong while attempting to connect to the network. Check your network configuration.
Http error response: (404)

```
Error generated when migrating tezos contracts.  Following the instructions from here: https://www.trufflesuite.com/docs/tezos/truffle/quickstart

## Steps to Reproduce

Just working from here: https://www.trufflesuite.com/docs/tezos/truffle/quickstart

## Expected Behavior

Compiled Contracts should have been deployed to the testNet.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

```
Something went wrong while attempting to connect to the network. Check your network configuration.
Http error response: (404)

```

## Environment

* Operating System:  macOS
* Ethereum client:  Tezos
* Truffle version (`truffle version`):  Truffle v5.3.0-tezos.2 (core: 5.3.0-tezos.2)
* node version (`node --version`): Node v13.12.0
* npm version (`npm --version`): 6.14.4

**Comment by amateur-dev** [comment]
It appears that the testNet address is wrong.  The correct seems to be: `https://api.tez.ie/rpc/carthagenet`

Reference from: `https://tezos.gitlab.io/introduction/test_networks.html`

**Comment by CruzMolina** [comment]
Thanks for finding this @amateur-dev !

Resolved via trufflesuite/trufflesuite.com#644.
