### ISSUE TITLE
Unexpected behavior in while deployed. Several transactions in one block.

### ISSUE THREAD

**Issue by TFOMS** [trufflesuite/truffle#2979]
- [v ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I want to deploy several smart-contracts (transactions) in one block.
If I do :
```
deployer.deploy(Smart-contract1);
deployer.deploy(Smart-contract2);
```

or with await before each no result. E.g. web3.eth.getBlock(#block of transactions above) will one transaction in block (2 blocks)
But this snippet of code is work well
```js
...
let addressForShareLinks = async () => {
   return null; // NO MATTER WHAT LOGIC THIS
};
module.exports = async function(deployer, network, addresses) {
     await addressForShareLinks(); // If this line comment the result will be bad (one transactions in one block,  total 2 blocks)
     await Promise.all([
         deployer.deploy(Smart-contract1),
         deployer.deploy(Smart-contract2)
     ]);
}
```
And web3.eth.getBlock(#block of transactions above) will being two transactions in one block.
**NOTE!!!** In truffle this result will be bad for me. E.g. two blocks and one transaction of each. BUT in ethereum client (golang) that's what I need.

Why it's not working without await addressForShareLinks() ?

I'm sorry for my english.

## Steps to Reproduce

- Create migrations file  with notes above.
- Run migration *truffle migration --reset* 

## Expected Behavior
Two transactions in one block.

## Actual Results
Working not clearly. I'm not understand. Maybe, something I do wrong.
## Environment

* Operating System:  Ubuntu 18
* Ethereum client: Ganache CLI v6.9.1 (ganache-core: 2.10.2) and geth 0.3.2
* Truffle version (`truffle version`): Truffle v5.1.16 (core: 5.1.16)
* node version (`node --version`): Node v12.14.1
* npm version (`npm --version`):

**Comment by gnidan** [comment]
This is a cool idea, but it sounds like a feature request for ganache-core - right now Ganache has no good way to do what you're asking. You could turn on time-based block production (e.g., new block every 5 seconds), but that won't be the same guarantee.

Feel free to open an issue [here](https://github.com/trufflesuite/ganache-core/issues). Closing this as it does not relate to Truffle specifically. (Or @davidmurdoch / @nicholasjpaterno feel free to hit the "transfer issue" button if you want to just grab this one)

Thanks for suggesting it!

**Comment by davidmurdoch** [comment]
You could issue a `miner_stop` to ganache, send your transactions, then follow up with a `evm_mine`. This should put both transactions in a single block (depending on transaction and block size)
