### ISSUE TITLE
Command no found after update

### ISSUE THREAD

**Issue by 4math2379** [trufflesuite/truffle#2981]
---------------------------

## Issue

After update Truffle command are no found by the system 

## Steps to Reproduce
Uninstall Truffle , i reinstall it globally 

## Expected Behavior

event truffle init don;4t work 

## Actual Results

Truffle compile , migrate , develop not working

![2020-04-20 (2)](https://user-images.githubusercontent.com/8716331/79768370-fc1f5b80-832a-11ea-959b-65a15b11279a.png)

## Environment

* Operating System:  windows 10 pro
* Truffle version (`truffle version`): 5.1.22
* node version (`node --version`):10.16.3
* npm version (`npm --version`): 6.9.0

**Comment by gnidan** [comment]
What's the name of your config file? Is it `truffle.js` or `truffle-config.js`? Not sure if your error is the same, but switched to using `truffle-config.js` because it caused problems on Windows.

**Comment by gnidan** [comment]
Oh but nevermind I see in the screenshot that you're using `truffle-config.js`.

Regardless, it sounds like an environmental issue on your part. Have you tried using Windows Subsystem for Linux, or `git bash`, or one of those? Not sure exactly because I don't have Windows myself.

If you figure this out, please share what the problem was!

**Comment by 4math2379** [comment]
i sill have the issue....... i don't get it. I got my whole dev environment on windows.

**Comment by eggplantzzz** [comment]
There might be something up with your npm installation. Do you use a version manager like nvm?

**Comment by eggplantzzz** [comment]
Here is a similar issue you can check out for some reference. https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

**Comment by 4math2379** [comment]
> Here is a similar issue you can check out for some reference. https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

thanks , i dunno how this has been removed.. but thanks :)

any idea how this happened  ?

**Comment by eggplantzzz** [comment]
No I'm not really sure unfortunately but I see this kind of thing happen occasionally. Did you get your issue resolved?

**Comment by 4math2379** [comment]
yes it s resolved. thanks
