### ISSUE TITLE
mkdirp@0.5.1 is no longer supported...

### ISSUE THREAD

**Issue by metaverde** [trufflesuite/truffle#2990]
First, I super-appreciate the Truffle team and Truffle.
Thank-you for all you do.

I apologize if this has already been raised. 
I scrolled around and did not see it.

- [X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

Yes. Additionally the same issue was raised earlier and not addressed.
It is also an issue with [netlify/cli](https://github.com/netlify/cli/issues/772) as well as some other repositories.

---------------------------

## Issue

I get this warning when I install Truffle using the `npm install -g truffle` command:

`npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)`

## Steps to Reproduce

All I have to do to get this is to install Truffle.

## Expected Behavior

I would expect at the least to be able to find how to update/upgrade to the proper mkdirp.
I realize this is not the fault of the Truffle team in any way.

## Actual Results

I google and search and cannot find how to update/upgrade/install new mkdirp.
I have not yet used the Truffle to see if there are issues with it.
The warning says `the API surface has changed to use Promises in 1.x.`, so I anticipate there will be issues?

## Environment

* Operating System: Ubuntu 18.04, aws ec2 instance
* Ethereum client:  not yet installed
* Truffle version (`truffle version`):  5.1.22
* node version (`node --version`):  v10.20.1
* npm version (`npm --version`):  6.14.4

**Comment by eggplantzzz** [comment]
Thanks @metaverde for bringing this up! It would be good to see if we can bump this.

**Comment by eggplantzzz** [comment]
@metaverde In the last version of Truffle (5.1.23) `mkdir` was removed. Happy day!

**Comment by fudingyu** [comment]
> @metaverde In the last version of Truffle (5.1.23) `mkdir` was removed. Happy day! Thanks again for creating the issue.

But when I install Truffle occur same problem 

npm install truffle -g
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
C:\Users\xxxx\AppData\Roaming\npm\truffle -> C:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js

> truffle@5.1.32 postinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.32
updated 1 package in 125.381s

**Comment by CruzMolina** [comment]
@fudingyu If you run `npm uninstall -g truffle && npm install -g truffle` do you still see that error?

I've tried replicating the error on node versions v8.x, v10.x, & v12.x, but have not seen that deprecation message.

**Comment by fudingyu** [comment]
Environment
Operating System:Windows 10
Ethereum client: 
Truffle version (Truffle v5.1.32):
node version (v14.4.0):
npm version (6.14.5):
/////////////////////////////


npm uninstall -g truffle
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
removed 27 packages in 1.212s
/////////////////////////////


npm install -g truffle
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
C:\Users\xxx\AppData\Roaming\npm\truffle -> C:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js

> truffle@5.1.33 postinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.33
added 27 packages from 439 contributors in 18.706s

**Comment by CruzMolina** [comment]
Thanks for sharing that @fudingyu !

Looks like `mocha`, one of `truffle`'s external dependencies, is puling in this older version of `mkdirp`.

https://github.com/trufflesuite/truffle/blob/develop/packages/truffle/package.json#L30
https://github.com/mochajs/mocha/blob/v5.2.0/package.json#L470

**Comment by Peter197903** [comment]
Got the same issue here. clean install under a fresh windows 10 machine

C:\Windows\System32>truffle version
Truffle v5.1.33 (core: 5.1.33)
Solidity v0.5.16 (solc-js)
Node v14.5.0
Web3.js v1.2.1

**Comment by eggplantzzz** [comment]
I think it is a warning from a dependency that has `mkdirp` as a dependency. I'm not sure we can do much about that I guess :)

**Comment by eggplantzzz** [comment]
I'm going to close this for maintenance. Truffle has removed `mkdirp` as a direct dependency which is about as much as we can do for now. Eventually I suppose some of Truffle's dependencies will get off of `mkdirp` as well. Thanks everyone!

**Comment by CruzMolina** [comment]
@metaverde @fudingyu @Peter197903 This should have been resolved by #3146 . The next official release should be out later today, but if you'd like to test this ASAP, feel free to give `truffle@next` a shot.
