### ISSUE TITLE
Faild test with --bail parameter does not show emitted events

### ISSUE THREAD

**Issue by AuHau** [trufflesuite/truffle#2999]
## Issue

When you run tests with `truffle test --bail` the failed test that is bailed does not show information about emitted events during run of this test.

## Steps to Reproduce

Run `truffle test --bail` with test that fails and has emitted events in its run.

## Expected Behavior

Display the standard "Events emitted during test:" dialog

## Actual Results

Directly errors out without the information.

## Environment

* Operating System: macos
* Ethereum client:
* Truffle version (`truffle version`): 5.1.22
* node version (`node --version`): v12.16.1
* npm version (`npm --version`): 6.13.4

**Comment by haltman-at** [comment]
Thanks for reporting this!  We'll have to look into this.

**Comment by haltman-at** [comment]
You know, it's surprising that this is happening, because we print the events with an `afterEach` hook, and Mocha is supposed to run those even when it bails out beforehand.  I wonder if this is just an old Mocha bug, and maybe we need to update our version of Mocha?

**Comment by haltman-at** [comment]
OK, it seems this is due to a bug that's specifically in Mocha 5.2.0.  So, either we can upgrade to 6.x (but that might be a breaking change and thus would be off limits until Truffle 6), or we can, uh, downgrade to Mocha 5.1.1?  Which could also be breaking as it's a downgrade?  We'll have to figure something out here.

**Comment by haltman-at** [comment]
Alright, looks like we're going with the downgrade solution for now.  I've put up #3044 to address this.
