### ISSUE TITLE
Adding a `truffle flatten` mechanism

### ISSUE THREAD

**Issue by Amxx** [trufflesuite/truffle#3000]
Verifying smart contracts on etherscan is a nightmare when dealing nested dependencies. Inheriting fro `@openzeppelin/contracts/tokens/ERC721/ERC721.sol` for example ...

I'm not able to find any decent flattening tool that supports contracts imported from `./node_modules`, and since truffle as access to all my settings, it could very well do it.

**Comment by haltman-at** [comment]
Could you explain in more detail what you want this to do?  Thank you!

**Comment by eggplantzzz** [comment]
Just for the record, there are a couple of external packages that I believe might help you do what you want to do. Check out [truffle-flattener](https://www.npmjs.com/package/truffle-flattener) and [truffle-plugin-verify](https://www.npmjs.com/package/truffle-plugin-verify).

**Comment by haltman-at** [comment]
Ah, thanks @eggplantzzz.  @Amxx, do those suffice for your purposes or is there some additional functionality you want that you think Truffle should provide in its equivalent?
