### ISSUE TITLE
truffle build: Deprecation Warning on Node 7

### ISSUE THREAD

**Issue by kristianmandrup** [trufflesuite/truffle#301]
On Node 7.1

```
truffle build
(node:25933) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

I guess the code should try `Buffer.from` if possible before defaulting to whatever it is currently calling.

**Comment by tcoulter** [comment]
Hi there. Thanks for writing.

I *think* this doesn't exist anymore, and haven't seen it myself on Node 8. I'm going to close this ticket for housekeeping issues; Truffle's dependencies have advanced significantly since last year. Please open a new ticket if you run into this issue.

Cheers!
