### ISSUE TITLE
Debugger --network flag warning

### ISSUE THREAD

**Issue by nicholasjpaterno** [trufflesuite/truffle#3015]
Passing a `--network` flag into the debugger results in a warning.

```
truffle debug <txhash> --network development
> Warning: possible unsupported (undocumented in help) command line option: --network
```

**Comment by gnidan** [comment]
(will assign priority later as part of team discussion, but I don't think this is a "drop everything" situation ;)

**Comment by nicholasjpaterno** [comment]
:trollface:

**Comment by eggplantzzz** [comment]
There is no `--network` flag for debug as far as I know. Perhaps there is something I don't know?

**Comment by haltman-at** [comment]
Right, there isn't at the moment.  @nicholasjpaterno, what issue exactly are you raising here?  Is it the message, or is it that the `--network` flag doesn't actually exist?  I'm assuming it's probably the latter, in which case this issue should be renamed (and is a request for an *enhancement*, not a bug), but I'd like to get this clear first.

**Comment by nicholasjpaterno** [comment]
@haltman-at you're definitely right, it's the latter! I imagine it doesn't pose that big of a problem.  However, I imagine there would be a conflict if/when you have two identical test networks with the same config/tx's (for whatever reason), they you would have identical transaction hashes. Now, since they are the same state why would it matter?  The only counter point I can think of is availability of the network.   

At the very least the user should be able to specify which network they wish to debug.

**Comment by haltman-at** [comment]
OK, I've added #3043 to add this.  Kind of surprising we didn't have this already, really!
