### ISSUE TITLE
Tezos contract parameter placement

### ISSUE THREAD

**Issue by asbjornenge** [trufflesuite/truffle#3022]
## Issue

I have a simple contract using action parameters like this:

```
#include "../partials/Types.religo"
#include "../partials/Add.religo"

type param =
  | Add(add_param);

let main = ((action, store): (param, storage)) : return => {
  switch (action) {
    | Add(ap) => add((ap, store))
  };
};
```

The add_param looks like this:

```
type add_param = {
  name: string,
  version: string,
  ipfs: string
};
```

When I'm trying to make a test for this contract, it want's me to call `main` with 3 string parameters. How can I control what is the first and last parameter? Or is there a way I can set up the contract so it will accept an object with properties instead of 3 strings?

What works:

```
await amberInstance.main('eplekake123', 'My app', '1.0.0')
```

What I would like:

```
let add_param = { name: 'My app', version: '1.0.0', ipfs: 'eplekake123' }
await amberInstance.main(add_param)
```

## Environment

Operating System: MacOS
Truffle v5.3.0-tezos.2 (core: 5.3.0-tezos.2)
Solidity v0.5.16 (solc-js)
Node v13.13.0
Web3.js v1.2.1

**Comment by haltman-at** [comment]
@CruzMolina, any thoughts on this?

**Comment by asbjornenge** [comment]
I guess I also need to pass the `Add` action somehow? Or would that be deduced based on the params I'm sending? 🤔

**Comment by CruzMolina** [comment]
Hey @asbjornenge, saw the issue you opened over here stove-labs/tzip-12-tutorial#5.      

You might want to take a look at the `transfer_param` typings here: https://github.com/stove-labs/tzip-12-tutorial/blob/dev/contracts/partials/tzip_12_tutorial/transfer_param.ligo

**Comment by CruzMolina** [comment]
Also these test cases: https://github.com/stove-labs/tzip-12-tutorial/blob/dev/test/tzip_12_tutorial.js#L54-L136.

**Comment by asbjornenge** [comment]
@CruzMolina if you look at my comment over at the Stovelabs repo, that is exactly the param & test case I was looking at. The only difference I can see between my example and that one is that the transfer_param is a list(transfer) while mine is a record directly. In my contract I don't want or need to pass a list of elements 🤔

**Comment by asbjornenge** [comment]
@CruzMolina you might also be able to help me with the other issue I am having. I am wondering how I can call `main` with a specific amount on tez...? More broadly; how can I control tx params for the call to main in my test?

**Comment by CruzMolina** [comment]
> I am wondering how I can call main with a specific amount of tez

```js

await contractInstance.main(..., { amount: 1 }); // for 1 tez

```

I believe taquito.js (which we leverage under the hood) still only supports amount values in units of `tez`. (will need to check).

> how can I control tx params for the call to main in my test?

Generally speaking the same tx params that one can pass to taquito can also be passed to a contract instance (i.e. `storageLimit`, `fee`, `gasLimit`, etc).

**Comment by CruzMolina** [comment]
>The only difference I can see between my example and that one is that the transfer_param is a list(transfer) while mine is a record directly. In my contract I don't want or need to pass a list of elements 🤔

Yes, I believe this is currently a workaround for a taquito limitation. You might want to open an issue on their end, to keep this on their radar. (I believe they are aware of it, not sure if they've overcome the limitation yet).

**Comment by asbjornenge** [comment]
Thanks for the info! I'm on it 😎👍
