### ISSUE TITLE
Cannot find module @truffle/debug-utils

### ISSUE THREAD

**Issue by bh2smith** [trufflesuite/truffle#3024]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Our dependabot has picked up an error when bumping versions of `@truffle/contract` from `v2.2.2` to `v2.2.3` over the weekend. In both of our truffle projects we are experiencing the following Error: 

```
Cannot find module '@truffle/debug-utils'
```
and just wondering if this is expected or others have mentioned the same. Are we now supposed to depend on this package as well...? Or perhaps, this version bump should simultaneously go along with a bump to our project's truffle version as well?

## Steps to Reproduce

Here are two examples bumping versions in `package.json` that serve as reproducible instances.

https://github.com/gnosis/dex-liquidity-provision/pull/198

https://github.com/gnosis/dex-contracts/pull/710

## Possible Solution
I think this is a case of including '@truffle/debug-utils' as a dependency of `@truffle/contract`.

**Comment by eggplantzzz** [comment]
Hey @bh2smith, thanks for the report! That's strange that we didn't catch this. `@truffle/debug-utils` is indeed missing from the deps. I'll go ahead and add it in.

**Comment by eggplantzzz** [comment]
Thanks again for reporting this bug. We just merged a fix with PR #3026 and it should be released later on this week!

**Comment by frangio** [comment]
Please release as soon as possible. :slightly_smiling_face: Integration tests and guides are failing because of this.

**Comment by eggplantzzz** [comment]
Hey @frangio, it should be released Thursday (May 7). Hang tight!

**Comment by j-mars** [comment]
Hey, any updates ? Thanks

**Comment by eggplantzzz** [comment]
There should be a fix out as of a couple of days ago with `@truffle/contract` version 4.2.4!
