### ISSUE TITLE
Latest Truffle breaks our box

### ISSUE THREAD

**Issue by mrdavey** [trufflesuite/truffle#3033]
## Issue

Our flashloan-box worked previously with Truffle v.5.10. It no longer works in latest Truffle.

## Steps to Reproduce

Our Flashloan-box: https://github.com/aave/flashloan-box

1. Using Truffle v.5.10, follow instructions of box. Everything should work.
2. Using latest Truffle version, follow instructions.
3. It fails on Step 8, when defining `const f = await Flashloan.deployed()`

## Expected Behavior

It should work as previous Truffle version.

## Actual Results

Errors with `ReferenceERrror: f is no defined`

## Environment

* Operating System: macOS
* Ethereum client:
* Truffle version (`truffle version`): 5.1.24
* node version (`node --version`): 11.15
* npm version (`npm --version`): 6.14.4

**Comment by haltman-at** [comment]
Thanks for reporting this! We'll take a look.

**Comment by mrdavey** [comment]
I've also confirmed this bug is still present on the latest v.5.1.25 release.

**Comment by nicholasjpaterno** [comment]
Confirmed with `ubuntu-18.04` on node `v10.20.1`.

**Comment by coinmaster4you** [comment]
tried anything else then f? may be that it is conflicting with an other variable.
It said just undefined in colored italic text after the declearing of the variable.
stil got this error though caling the flashloan function.

`reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  arg: '_asset',
  coderType: 'address',
  value: 1.364068194842176e+48,
  hijackedStack: 'Error: invalid address (arg="_asset", coderType="address", value=1.364068194842176e+48)\n' +
    '    at Object.throwError (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\errors.js:68:1)\n' +
    '    at CoderAddress.encode (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\abi-coder.js:467:1)\n' +
    '    at C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\abi-coder.js:605:21\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at pack (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\abi-coder.js:604:1)\n' +
    '    at CoderTuple.encode (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\abi-coder.js:764:1)\n' +
    '    at AbiCoder.encode (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\node_modules\\ethers\\utils\\abi-coder.js:897:1)\n' +
    '    at ABICoder.encodeParameters (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-abi\\src\\index.js:96:1)\n' +
    '    at C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-contract\\src\\index.js:426:1\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object._encodeMethodABI (C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-eth-contract\\src\\index.js:425:10)\n' +
    '    at C:\\Users\\svein\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\contract\\lib\\execute.js:181:1\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'`

**Comment by cds-amal** [comment]
Thanks for the suggestion @coinmaster4you. I'll give it a try.

**Comment by mrdavey** [comment]
Any updates on this issue?

**Comment by CruzMolina** [comment]
@mrdavey I just unsuccessfully tried to reproduce the error. Step 8 succeeded for me using `truffle@latest`.

**Comment by leonardobastos** [comment]
**I got an issue at Step 5:** 

truffle console --network kovan

@truffle\hdwallet-provider\node_modules\web3-providers-http\src\index.js:96
            callback(error, result);
            ^
**Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: project ID is required**
    at .....\node_modules\@trufflesuite\web3-provider-engine\subproviders\provider.js:18:36

----------------------------------
I'm using:
Truffle v5.1.32 (core: 5.1.32)
Solidity - ^0.6.6 (solc-js)
Node v14.4.0
Web3.js v1.2.1
@truffle/hdwallet-provider@1.0.36

**Comment by mrdavey** [comment]
Thanks @CruzMolina . I've checked and confirm that it is working now with latest Truffle version.
@leonardobastos please open another issue if this is still happening with you. It may have been a temporary Infura issue.

Closing this issue.
