### ISSUE TITLE
Error on Truffle :  EPROTO 17924:error:1408F10B:SSL

### ISSUE THREAD

**Issue by bookpowers** [trufflesuite/truffle#3039]
- [X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

I am receiving this error when running the "truffle init" command

EPROTO 17924:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

What the issue is, in broad strokes.

I am receiving this error when running the "truffle init" command

Please provide the shortest amount of steps to reproduce your issue.

Blank Ethereum Smart Contract Project

What you expected to happen.

Received this error: EPROTO 17924:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows 10
Truffle v5.1.24 (core: 5.1.24)
Ganache v2.4.0
Solidity v0.5.16 (solc-js)
Node v12.16.3
Web3.js v1.2.1

**Comment by haltman-at** [comment]
Thanks for reporting this!  This has been brought up before as #2966, so I'm going to close this and you can discuss this there.
