### ISSUE TITLE
unhandled exception because of blocked local storage in truffle-contract.js v4.2.3

### ISSUE THREAD

**Issue by PyrateAkananto** [trufflesuite/truffle#3041]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The file `node_modules\@truffle\contract\dist\truffle-contract.js` contains plenty duplicate code because some libraries seem to be included twice. Unfortunately those duplicates are not identical and one of those differences causes an unhandled exception when accessing local storage in case access to local storage is blocked by the browser.

## Steps to Reproduce

* Use Chrome to visit a website which is including `truffle-contract.js`.
* In Chrome block cookies for that domain. Doing so will even block access to local storage.
* Reload website.
* Chrome console will show an unhandled exception: `truffle-contract.js:147920 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

This might even happen in other browsers but I can only test in Chrome on Windows right now.

## Expected Behavior

No unhandled exception. And in ideal circumstances no duplicate code in `truffle-contract.js`.

## Actual Results

Unhandled exception. And plenty duplicate-but-not-identical code in `truffle-contract.js`.

## Environment

* Operating System: Windows 10 64 Bit German
* Browser: Chrome, Version 81.0.4044.138 (Official Build) (64-bit)
* Ethereum client: MetaMask 7.7.9
* Truffle Contract version (from package.json): @truffle/contract: ^4.2.3

## Further Information

The file `accounts.js` seems to be included twice. This can be verified by searching for the string `@file accounts.js`.

In line 147920 is the following code which is "the bad one" in my opinion and which causes the unhandled exception:
```
if (typeof localStorage === 'undefined') {
    delete Wallet.prototype.save;
    delete Wallet.prototype.load;
}
```

In line 51339 is the following code which is "the good one" in my opinion:
```
if (!storageAvailable('localStorage')) {
    delete Wallet.prototype.save;
    delete Wallet.prototype.load;
}
```

In line 51153 is the definition of `function storageAvailable(type)` which is used by "the good one" and which seems to come straight from the Mozilla website mentioned its code comment.

In line 34499 is the definition of `function localstorage()` (with a small 's') which seems to do something similar but in yet another way.

**Comment by gnidan** [comment]
Good find! Any interest in taking a stab at fixing the problem? Let us know!

**Comment by PyrateAkananto** [comment]
Thank you for that generous offer 🤣 but my knowledge about "modules, importing, bundling, including all required dependencies and doing all that in the correct way" is too limited. My own workaround simply duplicates code - which works but is far from "the correct way" for a library like Truffle. Sorry. I made the best bug report I could but I lack the skills and time to fix it myself. I really appreciate that the team behind Truffle reacts to all my bug reports. 👍

**Comment by eggplantzzz** [comment]
Hey @PyrateAkananto, I finally got around to taking a look at this and can't duplicate this problem. I blocked all cookies and opened a very simple html file that just loads the Truffle Contract script but I don't get anything in the console like what you  described. Is there anything else I need to do besides block cookies?

**Comment by PyrateAkananto** [comment]
Hello @eggplantzzz . Thank you for having a look at it. The issue is over two years old and I am not working on anything related to Ethereum anymore. Nevertheless I had a look at my old code which does the following regarding Truffle. But I only took a look because I neither have the environment nor the time to actually run the code again.

1. Check myself whether local storage is available using example code from Mozilla.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage

2. Asynchronously load the built smart contract JSON file (for example "mysmartcontract.json") using `XMLHttpRequest`.

3. Parse the content of the file into an JSON object.
```
this.builtContract = JSON.parse(request.response)
```

4. Wait for loading and parsing using a promise.

5. Check web3 and currentProvider.
```
if ((!window.web3) || (!window.web3.currentProvider)) {
```

6. Get contract.
```
let truffleContract: any = null
try {
  truffleContract = window.TruffleContract(this.builtContract)
  truffleContract.setProvider(window.web3.currentProvider)
} catch (error) {
  return false
}
```

7. Get deployed contract (instance).
```
try {
  this.deployedContract = await truffleContract.deployed()
} catch (error) {
  return false
}
```

If I remember correctly the error happened in step 6 or 7 because the Truffle suite tried to do something with local storage while "getting" the instance of the deployed contract. And while it tried to so something with local storage it used "the bad one" version of the function to check whether access to local storage is allowed (see my initital post here).

But: I might not remember correctly. Truffle suite might have changed. Build tools for buildung Truffle suite might have changed. The libraries Truffle suite is using might have changed (which would be the optimal fix for this bug). Browsers might have changed.

**Comment by eggplantzzz** [comment]
Actually it kind of seems like blocking all cookies blocks the local storage any more. After blocking cookies I am still able to go into the dev console and set values...

**Comment by PyrateAkananto** [comment]
In the settings of Chrome 103 (on Windows) I cannot find anything about local storage. I don't know how Chrome handles it currently.
In the site settings of Firefox 102 there are different settings for cookies and persistent storage (which I assume is local storage) for every website. In the generic settings there is only a single setting called "cookies and site data".
I did not experiment with those settings lately.
I suggest you first search for the two code snippets I called "the good one" and the "the bad one" in the _current_ code. If "the bad one" is not present anymore then one could assume the issue was fixed by changes in the used libraries.

**Comment by eggplantzzz** [comment]
Makes sense. On searching the entire codebase it looks like there is no mention of `localStorage` with the one exception of a variable name in debugger's tests (which is entirely unrelated). I'll go ahead and assume this is no longer an issue and close this. If someone figures out otherwise then please let me know!

Thank you again @PyrateAkananto for submitting this and following up with me here after such a long time!
