### ISSUE TITLE
Cannot migrate my contracts

### ISSUE THREAD

**Issue by codenamejason** [trufflesuite/truffle#3048]
## Issue

I have now tried two machines and cannot migrate my contracts after they have successfully compiled. I get no output at all acutally.

## Steps to Reproduce

truffle migrate

## Expected Behavior

A migration

## Actual Results

nothing

## Environment
Windows 10
VS Code
Truffle v5.1.25 (core: 5.1.25)
Solidity - 0.6.2 (solc-js)
Node v12.16.3
Web3.js v1.2.1

**Comment by haltman-at** [comment]
Could you describe the problem in more detail?  Do you have any error messages you could show us, or more detailed reproduction steps, such as a reproduction project we could try this with?  Thank you!

**Comment by codenamejason** [comment]
It terminates silently there is no error messages it just displays that it compiled successfully and then gives me back to the prompt.

Jason Romero
Application Developer
________________________________

**Comment by codenamejason** [comment]
I already responded to this same message. It fails silently and just returns to prompt. There is no error message or I wouldn’t be here. I am on Windows 10 using VS code. Oh, also I have never been able to unbox a truffle project, which blows. I am now moving to Ubuntu and Mac and leaving this POS windows for the kiddies. I know there are a ton of people with these same issues in some of my communities and would like to see this get resolved.

Jason

**Comment by eggplantzzz** [comment]
That is very weird, what happens if you use `truffle develop`? You can run `truffle develop` and the when the prompt appears, you run `migrate`.

**Comment by codenamejason** [comment]
I have also tried that and same thing. It compiles and then nothing.. Here is my truffle-config and deploy

require('babel-register');
require('babel-polyfill');
const HDWalletProvider = require("truffle-hdwallet-provider");

// Locan Ganache Mnemonic
const mnemonic = 'evoke club entry catalog unveil truly run lyrics melt property main noise'; // funded accounts[0]
const maintest = 'gap cage shrug cake general simple cable air raw vessel dignity reduce'; // funded accounts[0]
const ganache = 'outside bridge shrimp above piece myth acquire doll void filter fit reject';
const rop = 'process eternal ill spawn purpose replace solve humble mimic nothing element portion';

//'outside bridge shrimp above piece myth acquire doll void filter fit reject';

// Infura MainNet
//https://mainnet.infura.io/v3/1ad03ac212da4523b6c8337eace81a14
//ganache-cli --fork https://mainnet.infura.io/v3/1ad03ac212da4523b6c8337eace81a14 -i 1

// const INFURA_ID = process.env.INFURA_ID || 'e8cc7c8e245b46b482873ce9382a542b';

// const configNetwok = (network, networkId, path = "m/44'/60'/0'/0/", gas = 4465030, gasPrice = 1e10) => ({
//   provider: () => new HDWalletProvider(
//     mnemonic, `https://${network}.infura.io/v3/${INFURA_ID}`,
//         0, 1, true, path
//     ),
//   networkId,
//   gas,
//   gasPrice
// });

module.exports = {
  networks: {
    development: {
      mnemonic: ganache,
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    },
    develop: {
      port: 8545,
      network_id: 20,
      accounts: 5,
      defaultEtherBalance: 500,
      blockTime: 3
    },
    kovan: {
      provider: new HDWalletProvider(ganache, "https://kovan.infura.io/v3/1ad03ac212da4523b6c8337eace81a14"),
      network_id: 42,
      gas: 5000000,
    gasPrice: 5000000000, // 5 Gwei
    skipDryRun: true
    },
    ropsten: {
      provider: () => new HDWalletProvider(
        rop,
        "https://ropsten.infura.io/v3/e8cc7c8e245b46b482873ce9382a542b"
      ),
      network_id: 3,
      gas: 5000000,
      gasPrice: 5000000000 // 5 Gwei
    },
    main: {
      provider: () => new HDWalletProvider(
        mnemonic,
        "https://mainnet.infura.io/v3/1ad03ac212da4523b6c8337eace81a14",
      ),
      network_id: 5,
      gas: 4700000
    },
    kovan: {
      provider: new HDWalletProvider(rop, "https://kovan.infura.io/v3/4a3706ac2ddf434fbc3ca2e68a746382"),
      network_id: 42,
      gas: 5000000,
      gasPrice: 5000000000, // 5 Gwei
      skipDryRun: true
    },
    // ropsten: configNetwok('ropsten', 3),
    // kovan: configNetwok('kovan', 42),
    // rinkeby: configNetwok('rinkeby', 4),
    // main: configNetwok('mainnet', 1),
  },
  mocha: {
    useColors: true,
  },
  contracts_directory: './src/contracts/',
  contracts_build_directory: './src/abis/',
  migrations_directory: './src/migratons/',
  compilers: {
    solc: {
      version: '0.6.2',
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  }
}


const StreamToken = artifacts.require('StreamToken')
//const iNETToken = artifacts.require('iNETToken')
//const Flashloan = artifacts.require('FlashLoan')
const IncomeStreamCreator = artifacts.require('IncomeStreamCreator');
const PriceOracle = artifacts.require('OracleExample')
//const DaiFaucet = artifacts.require('DaiFaucet');

// require('@openzeppelin/test-helpers/configure')({
//     provider: web3.currentProvider,
//     environment: 'truffle'
// });

//const { singletons } = require('@openzeppelin/test-helpers');

module.exports = async function (deployer
) {

    /**
        * @dev deployments
        */
    //await deployer.deploy(DaiFaucet);

    await deployer.deploy(StreamToken);
    // const streamToken = await StreamToken.deployed()
    // console.log(streamToken)

    //await deployer.deploy(iNETToken)
    // const iNetToken = await iNETToken.deployed()
    // console.log(iNetToken)

    // Flashloan testing
    //await deployer.deploy(Flashloan, lendingPoolAddressesProviderAddress)

    // Stream token testing
    await deployer.deploy(IncomeStreamCreator);

    // Bandchain ETH oracle
    await deployer.deploy(PriceOracle);

    //try {

        // let lendingPoolAddressesProviderAddress;

        // switch (network) {
        //     case "live":
        //         lendingPoolAddressesProviderAddress = "0x24a42fD28C976A61Df5D00D0599C34c4f90748c8";
        //         // Do something specific to the network named "live".
        //         await singletons.ERC1820Registry(accounts[0]);
        //         break;
        //     case "mainnet":
        //     case "mainnet-fork":
        //     case "development": // for Ganache mainnet forks
        //         lendingPoolAddressesProviderAddress = "0x24a42fD28C976A61Df5D00D0599C34c4f90748c8";
        //         break;
        //     case "ropsten":
        //     case "ropsten-fork":
        //         lendingPoolAddressesProviderAddress = "0x1c8756FD2B28e9426CDBDcC7E3c4d64fa9A54728";
        //         break;
        //     case "kovan":
        //     case "kovan-fork":
        //         lendingPoolAddressesProviderAddress = "0x506B0B2CF20FAA8f38a4E2B524EE43e1f4458Cc5";
        //     default:
        //         throw Error(`Are you deploying to the current network? (network selected: ${network})`)
        // }



    // } catch (e) {
    //         console.log(`Error in migration: ${e.message}`)
    // }
}

Thanks for looking into this.

Jason

**Comment by eggplantzzz** [comment]
@codenamejason Is your project here on GitHub? I would like to see if I can duplicate your error on my machine.

**Comment by codenamejason** [comment]
codenamejason/hackmoney

**Comment by codenamejason** [comment]
I now have it working on main branch. I am still not sure of why the behavior I got happened. I think it has something to do with either my truffle-config.js or deploy scripts.

**Comment by eggplantzzz** [comment]
Ok thanks, I'll try and duplicate your error and get back to you!

**Comment by fainashalts** [comment]
Hi @codenamejason sounds like this is resolved! I'm closing this for issue maintenance but please open a new issue if something comes up.
