### ISSUE TITLE
SPDX license identifiers missing

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#3051]
As of today (Solidity 0.6.8, from [this PR](https://github.com/ethereum/solidity/pull/8907)), Solidity issues warnings on Migrations.sol (and other) contracts for lack of an "[SPDX-License-Identfier](https://solidity.readthedocs.io/en/v0.6.8/layout-of-source-files.html#spdx-license-identifier)" code comment at the top of the file. 

A proposed fix would be to add
`//SPDX-License-Identifier: MIT`
to the start of Migrations.sol and every other contract file.

**Comment by haltman-at** [comment]
Thanks for pointing this out.  I've put up a PR to address the cases in this repo, but `truffle-box` will have to be addressed separately.

**Comment by haltman-at** [comment]
OK, since this should be fixed on this repo, and you've opened a separate issue on `truffle-box`, I'm going to just go ahead and close this if you don't mind.
