### ISSUE TITLE
Truffle does not working with .env file

### ISSUE THREAD

**Issue by dzabeu** [trufflesuite/truffle#3055]
Hi,

I would like to know if it possible to use .env variables on 2_deploy_contracts.js

This is the ideia, but the result of console.log is empty..

`
require('dotenv').config();

module.exports = function(deployer) {
  deployer.then(async () => {    
console.log(process.env.DB_NAME)
      
  })
}`

**Comment by dzabeu** [comment]
I`m using  the following command to execute  truffle...

truffle migrate --reset --compile-all --network ganache

**Comment by genaro56** [comment]
Where you able to use .env variables? I'm having the same issue 😞.

**Comment by cds-amal** [comment]
@genaro56 this thread is closed so we didn't notice it in our triage sessions.

If this is still an issue for you, try moving the require into the deploy function definition. Please open a new issue if this doesn't do the trick.

```
module.exports = function(deployer) {

  // move the config here
  require('dotenv').config();

  deployer.then(async () => {
    console.log(process.env.DB_NAME)
  });
}
```

**Comment by eggplantzzz** [comment]
@genaro56 or @dzabeu  Can you give a simple example of how I might try to duplicate your problem?

**Comment by haltman-at** [comment]
Closing this for issue maintenance, but if anyone has repro steps, we can reopen this!  Thanks!
