### ISSUE TITLE
Unexpected advance to then block in migration after promise rejection

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#3066]
## Issue
When a promise rejection is encountered in a deployment promise chain, execution continues to the next `then` block instead of skipping to the next `catch` block.

## Steps to Reproduce
Have Ganache running.
```
PS> mkdir promiseTest
PS> cd promiseTest
PS> truffle init
```
Create a new file: `migrations/2_test_promises.js` with this content:

```
module.exports = function(deployer, network, accounts) {
    deployer.then(function() {
        return Promise.reject("This first migration step just fails.");
    }).then(function() {
        console.log("First migration step appears to have succeeded.");
    }).catch(function(err) {
        console.log("Error in migration:",err);
    });
};
```

## Expected Behavior
The output includes "Error in migration: This first migration step just fails." but does NOT include "First migration step appears to have succeeded."

## Actual Results
(After output showing first migration succeeding)
```
2_test_promises.js
==================
First migration step appears to have succeeded.

This first migration step just fails.
Truffle v5.1.24 (core: 5.1.24)
Node v9.3.0
```

## Environment

* Operating System: Win10 
* Ethereum client: Ganache
* Truffle version (`truffle version`): 5.1.24
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.14.5

## Other information
Adapting this to a non-migration Javascript file and running it with `node testPromises.js` behaves as expected, giving output "Error in migration:  This first migration step just fails."

The adaptation is to replace `module.exports` with `mainFunction`, replace `deployer` with `Promise.resolve()`, and add a line at the end of the file to call it: `mainFunction();`

**Comment by eggplantzzz** [comment]
Oh weird! Thanks again for another thorough report @wbt. I wonder what happens when using `await` syntax...

**Comment by wbt** [comment]
It seems to handle the *await* syntax a bit more as expected.

**Comment by gnidan** [comment]
If you have the attention for it @wbt, there's bound to be different-yet-also-incorrect behavior when running ganache with the `--noVMErrorsOnRPCResponse` flag set. I'd be curious if you would be able to isolate issues with the contract transaction promise chain in that situation.

Thanks for this write-up. The issues with that promise chain have gotten in the way of improvements I've wanted for a long time, and it's good to have this kind of issue that gets to the heart of the problem.

**Comment by wbt** [comment]
I observed it today when I was running on Geth rather than Ganache, so I don't think this is Ganache-specific.

**Comment by gnidan** [comment]
> I observed it today when I was running on Geth rather than Ganache, so I don't think this is Ganache-specific.

I believe the problem you describe lies at the intersection of @truffle/contract's transaction lifecycle and the underlying web3.eth.Contract's transaction lifecycle. In my experience, that `--noVMErrorsOnRPCResponse` flag exposes problems with this interaction in a different way vs. when not using that flag. (I believe Geth's behavior matches the behavior of including that flag, but I may be remembering it backwards.)

**Comment by wbt** [comment]
Just dropping a note here to confirm that the problem still exists today, after running the migrations set that includes the above migration testing for this.

**Comment by eggplantzzz** [comment]
Thanks @wbt!

**Comment by wbt** [comment]
Yes, as previously noted; that is a valid workaround.  However, both syntaxes should be equivalent.

**Comment by haltman-at** [comment]
OK, I've put up #5216, which seems to fix this.  The whole thing's a bit mystifying; deployer is some seriously opaque code.  But #5216 seems to do the trick.

**Comment by cliffoo** [comment]
Resolved in the [newest Truffle release](https://github.com/trufflesuite/truffle/releases/tag/v5.5.19). Thanks @wbt for bringing this up!
