### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by farinalvaro** [trufflesuite/truffle#3068]
## Issue

Using `@truffle/contract` `v4.2.5` breaks the app on Firefox.
The console throws `SintaxError: invalid regexp group` error.
It looks like there is a regex used that is not supported on Firefox yet (https://caniuse.com/#feat=js-regexp-lookbehind).

## Steps to Reproduce

```
  "dependencies": {
    "@truffle/contract": "^4.2.5",
    "@truffle/debug-utils": "^4.1.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "typescript": "^3.9.3",
    "web3": "^1.2.7"
  },

const contract = require('@truffle/contract')
```

## Expected Behavior

Should work as in Chrome browser for example.

## Actual Results

The app breaks and fails to render on Firefox browser.
Console error:
```SyntaxError: invalid regexp group```

<img width="618" alt="Screen Shot 2020-05-21 at 11 21 41" src="https://user-images.githubusercontent.com/8449567/82568560-65c29d80-9b55-11ea-8c13-d687f191860e.png">

## Environment

* Operating System: OSX Catalina
* Ethereum client: web3 v1.2.7
* node version (`node --version`): v10.20.1
* npm version (`npm --version`): v6.14.4

**Comment by haltman-at** [comment]
Yikes, thanks for reporting this!  Do you by any chance know what version the problem started on?  I'm having a hard time finding the problem. I think it's in a dependency; `chunk.js` doesn't appear to be one of our files.

**Comment by haltman-at** [comment]
Ah, nevermind, I think I found it; it's coming from a regexp in `@truffle/codec`.  Hm, how did that get in there?
