### ISSUE TITLE
Aid debugging by showing what network is timing out

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#3072]
In [this error message](https://github.com/trufflesuite/truffle/blob/4c2409f4c5ac500472f4a5a6cf6049519ae98c78/packages/provider/index.js#L50):

```
Error: There was a timeout while attempting to connect to the network.
       Check to see that your provider is valid.
       If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this.
```
It would be nice to have this message provide some confirmation of exactly which network Truffle is trying to connect to, showing the host and port.

I spent an embarrassingly long period of time today encountering this when connecting to a local geth instance running a private network, where I can clearly see the "HTTP endpoint opened" message in the Geth output and I have the host and port number matching in my truffle-config. 

Then I figured out that the truffle-config I was looking at wasn't the one in effect.

Having this error message tell me the host and port it was trying to connect to would have shortened that debug time to seconds.

**Comment by eggplantzzz** [comment]
Sounds like a swell idea! We'll put this in the backlog and try to get around to it in the near future. Anyone wishing to expedite this is welcome to put in a PR in the meantime. Thanks @wbt!

**Comment by wbt** [comment]
It should be relatively simple, but the wrinkle is that there is a diversity of what counts for the "provider" object and it's not immediately clear if they all support a common interface for extracting host and port data.

**Comment by eggplantzzz** [comment]
Yeah you are right. Maybe we can just look and see what configuration they are trying to load and provide them with as much information as we can at the time that it fails. I'll consider looking into this soon!

**Comment by fainashalts** [comment]
This is resolved by https://github.com/trufflesuite/truffle/pull/4287 which is available in today's release. Closing, and thank you for bringing it up!

**Comment by wbt** [comment]
Thanks to @tenthirtyone for taking this on as a first bug and getting it fixed!
