### ISSUE TITLE
Mocha error when run test on the metacoin box

### ISSUE THREAD

**Issue by GeorgeWL** [trufflesuite/truffle#3073]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Mocha states 3 tests passed, one failed. On the metacoin example box used in the documentation.

Possibly caused by Node Version Manager for Windows is my first guess (which is required for work as some of the stuff we work on only works with outdated versions of node.)

## Steps to Reproduce

1. go through the [getting started](https://www.trufflesuite.com/docs/truffle/getting-started/), don't modify any files except for (as recommended) uncommenting the truffle-config.js
2. run the `truffle test` command at the root of the project directory

## Expected Behavior

All tests run. Should state `3 passing, 0 failing` as there are only 3 tests.

## Actual Results

all tests run, but (despite there being only 3 tests in the file) it states `3 passing, 1 failing`
[gist for a full log of the error](https://gist.github.com/GeorgeWL/53a2534e7ca1dfc25ea5bce09a73dd1d)

## Environment

* Operating System: Windows 10 Pro, version 1903 build 18362.836
* Ethereum client: Ganache v2.4.0
* Truffle version (`truffle version`):  5.1.27
* node version (`node --version`): 14.2.0 AND 12.16.1 
* npm version (`npm --version`): 6.14.4

**Comment by eggplantzzz** [comment]
Thanks for the report, we'll investigate!

**Comment by eggplantzzz** [comment]
Hey @GeorgeWL, can you confirm that this is still an issue on the latest version of Truffle (v5.7.3)? If it is still an issue, we'll go ahead and try to reproduce it on our end. What version of Windows are you on? Are you using WSL? Thanks!

**Comment by cliffoo** [comment]
Closing for issue maintenance.
