### ISSUE TITLE
Error: Deployer._preFlightCheck when deploying

### ISSUE THREAD

**Issue by naszam** [trufflesuite/truffle#3077]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When trying to deploy a smart contract which is using some interfaces, it returns the following error:

```
"MyContract" is an abstract contract or an interface and cannot be deployed.

Deployer._preFlightCheck
```

This is probably a bug cause when removing interfaces and adding them again it works

## Steps to Reproduce

Clone repo:
https://github.com/naszam/maker-badges

Run: 

```
$ npm i
$ ganache-cli
$ truffle migrate
```

## Expected Behavior

Deploy the contracts on ganache-cli

## Actual Results

```
"MyContract" is an abstract contract or an interface and cannot be deployed.

Deployer._preFlightCheck
```

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client: 
* Truffle version (`truffle version`): v5.1.26
* node version (`node --version`): v13.13.0
* npm version (`npm --version`): 6.14.5

**Comment by eggplantzzz** [comment]
@naszam Can you try upgrading to the most recent Truffle? I cloned your repo and was able to successfully migrate your contracts, maybe this is an issue that was fixed since 5.1.26?

**Comment by eggplantzzz** [comment]
Sweet! That makes it easy :)

**Comment by hilmarx** [comment]
still getting the same issue for `5.1.47`

**Comment by eggplantzzz** [comment]
@hilmarx Would you like to share your code so we can try and duplicate your problem?

**Comment by eggplantzzz** [comment]
Closing for issue maintenance.
