### ISSUE TITLE
Multi-line import statements in Solidity don't work with contracts in npm modules.

### ISSUE THREAD

**Issue by petejkim** [trufflesuite/truffle#3082]
## Issue

Multi-line import statements in Solidity don't work with contracts in npm modules.

## Steps to Reproduce

1. Create a new Truffle project.
2. Install OpenZeppelin: `npm install --save-dev @openzeppelin/contracts` or `yarn add --dev @openzeppelin/contracts`
3. Set solc version to 0.6.8 (to be able to use latest OpenZeppelin)
4. Add the following contract code `Foo.sol`:
```solidity
pragma solidity ^0.6.0;

import {
  ReentrancyGuard
} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract Foo is ReentrancyGuard {
}
```
5. `truffle compile`.

## Expected Behavior

Should work fine.

## Actual Results

```
contracts/Foo.sol:3:1: ParserError: Source "@openzeppelin/contracts/utils/ReentrancyGuard.sol" not found: File import callback not supported
import {
^ (Relevant source part starts here and spans across multiple lines).
```

If the import statement is in a single line, then it works fine, but it should work regardless of whether it's multi-line or single-line. Importing a local file also works fine regardless of linebreaks.
```solidity
import { ReentrancyGuard } from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
```

Popular code formatters like `prettier` would split the statement because it's too long for the default line width of 80.

## Environment

* Operating System: 
`Linux ubuntu 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Ethereum client: N/A
* Truffle version (`truffle version`): v.5.1.27
* node version (`node --version`): v12.17.0
* npm version (`npm --version`): v6.14.4

**Comment by haltman-at** [comment]
Thanks for the report!  We'll take a look.  Or, if anyone else wants to take a look at this, [here's](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-solidity/parser.js) the most relevant file.
