### ISSUE TITLE
Using curly braces '{' '}' within string of contract causes parser to fail

### ISSUE THREAD

**Issue by D-Nice** [trufflesuite/truffle#309]
## Issue

A contract having any string containing a curly brace causes the parser to break, and stops any compilation.

## Steps to Reproduce

Add 

```
string break = "}";
```

to any contract

## Expected Behavior

To compile just fine, as with solc and browser-solidity.

## Actual Results

SyntaxErrors
```
SyntaxError: Expected "contract", "import", "library", "pragma", "using", comment, end of
input, end of line or whitespace but "\"" found.
```
or
```
SyntaxError: Expected "{", "}", any character, comment, end of line or whitespace but end
of input found.
```
## Environment

* Operating System: Windows 7
* Truffle version: 2.1.1
* Ethereum client: testrpc
* node version: 4.4.4
* npm version: 3.5.0

**Comment by federicobond** [comment]
This is actually a bug with [ConsenSys/solidity-parser](https://github.com/ConsenSys/solidity-parser). Could you file an issue there?

**Comment by tcoulter** [comment]
This requires an update of solidity-parser now that it's fixed ther.e

**Comment by christoph2806** [comment]
see also here: https://github.com/ConsenSys/solidity-parser/issues/59

**Comment by tcoulter** [comment]
The next version of Truffle (3.2, to come out this week) will include the latest solidity parser which fixes these issues. Closing this ticket. If you see similar issues please open a new one!
