### ISSUE TITLE
Documentation for support new blockchain (EVM compatible)

### ISSUE THREAD

**Issue by Pana** [trufflesuite/truffle#3096]
We at [conflux](https://confluxnetwork.org/) has develop a full decentralized and high through output, EVM compatible blockchain, whose mainnet is live now, we want add support of conflux to truffle, but can't find any documentation, where can i find intro or doc ?

**Comment by gnidan** [comment]
Did you try connecting Truffle to it? What went wrong?

There's no documentation for how to do this, but if you indicate where support is lacking, we might be able to point you in the right direction.

**Comment by Pana** [comment]
Our blockchain contract vm is compatible with evm, but our rpc and js-sdk is independent, so we now planning add feature to truffle, to let it support conflux, but didn't know from where start ?

**Comment by Pana** [comment]
Thanks for your help
