### ISSUE TITLE
Truffle Config File Not Being Read Properly

### ISSUE THREAD

**Issue by VoR0220** [trufflesuite/truffle#3103]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am feeding truffle a config file and want it to look for a network but it seems to not be able to read that there is a specified network configuration. Super weird. Never had this problem before. 

## Steps to Reproduce

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  development: {
    host: '127.0.0.1',
    port: 23889,
    network_id: '*', // eslint-disable-line camelcase
    from: '0x7926223070547d2d15b2ef5e7383e541c338ffe9',
    gasPrice: '0x64', 
  },
};
```

## Expected Behavior

it to connect to the bridge I have set up at the localhost and port

## Actual Results

here's where things get interesting. Normally I'd chalk it up to a communication issue. But for some reason I cannot get it to move from the default port and net id numbers.

```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

> Something went wrong while attempting to connect to the network. Check your network configuration.

Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

Truffle v5.1.29 (core: 5.1.29)
Node v8.11.3
```
Have tried on later node versions as well. Same problem. 

## Environment

* Operating System: OSX
* Ethereum client: Alternative client 
* Truffle version (`truffle version`): 5.1.29
* node version (`node --version`): 8.11.3
* npm version (`npm --version`): 5.6.0

**Comment by gnidan** [comment]
Weird - thanks for opening an issue! Can you see if this is something that was introduced in a recent version of Truffle, to help diagnose the problem?

**Comment by CruzMolina** [comment]
hey @VoR0220 , can you show us what command you're running?

**Comment by VoR0220** [comment]
```truffle migrate --reset```

**Comment by VoR0220** [comment]
if I try to run it ```truffle migrate --network development --reset``` I get this. 

```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Unknown network "development". See your Truffle configuration file for available networks.
```

**Comment by CruzMolina** [comment]
Ah, you need to nest the `development` field in your config within a `networks` object.

```javascript
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      host: '127.0.0.1',
      port: 23889,
      network_id: '*', // eslint-disable-line camelcase
      from: '0x7926223070547d2d15b2ef5e7383e541c338ffe9',
      gasPrice: '0x64', 
    }
  }
};
```

**Comment by VoR0220** [comment]
derp. Thanks.

**Comment by gnidan** [comment]
Glad that was easy!

**Comment by bryanfeliciano** [comment]
I had the same issue but mine is nested within a network. I cant seem to get it to work

**Comment by Abhishekkochar** [comment]
Hi, I'm experiencing this issue as well. All the settings are correct. Error is happening after running truffle compile. I have attached the screenshot for more info. Any idea CruzMolina ?
![config-file](https://user-images.githubusercontent.com/43106142/134790618-48833498-fbeb-4ffd-a0ea-a9f4066660fb.PNG)
![truffle-compile](https://user-images.githubusercontent.com/43106142/134790619-ebedc65b-9ec3-4031-b7c1-8f840f256195.PNG)

**Comment by awesome1128** [comment]
I have exact same issue.
Please help me, I am new in truffle and smart contract development.
Thanks in advance.

**Comment by hugodwin** [comment]
Same here

**Comment by Abhishekkochar** [comment]
> I have exact same issue. Please help me, I am new in truffle and smart contract development. Thanks in advance.



> Same here

If you guys are using GUI. This is when it usually happens. I would recommend use via cmd by installing ganache-cli.
This should resolve this.

Cheers

**Comment by SebastienBosca** [comment]
Hi there,
I had the same issue :
![image](https://user-images.githubusercontent.com/38952196/153487621-eeadfd80-6d11-48f6-ae7a-bd7dfafa7037.png)
So, the port 7545 was required but truffle-config.js asked for port 8545:
![image](https://user-images.githubusercontent.com/38952196/153488584-1cc5633b-8e96-4bd1-92be-a1930d64d2b8.png)
Then, I typed this (I have ganache installed, it was named ganache-cli before):

$ ganache -p 8545

same error again; then, without changing my truffle-config.js, I tried

$ ganache -p 7545

it worked for the port, but another problem appeared:

![image](https://user-images.githubusercontent.com/38952196/153498069-9e42834d-be3c-4936-a5bf-5c691a855b5f.png)
Then I tried :

$ ganache -p 7545 -i 5777

Cool ! It works:

![image](https://user-images.githubusercontent.com/38952196/153497794-97e06bab-3b51-4747-8f77-fbb9ce6e9432.png)

But I really don't know why because my truffle-config.js file specifies "port 8545". 
Maybe the answer is in truffle/webpack.config.js ? And what was that problem with the network ID ? Strange...

**Comment by eggplantzzz** [comment]
If you want to use that network configuration you need to pass in the `--network <networkName>` option. So in your case, if you would like to use the configuration under "development", you will need to enter `truffle migrate --network development`. If you don't specify a network, Truffle will use some internal defaults. I hope this helps!

**Comment by Abhishekkochar** [comment]
@SebastienBosca, You are looking at the wrong way. You first run Ganache, then based on a port it's running. You pass to the truffle-config file.

**Comment by kimpace19882627** [comment]
[文件.txt](https://github.com/trufflesuite/truffle/files/8651646/default.txt)

**Comment by kimpace19882627** [comment]
/**
 * Use this file to configure your truffle project. It's seeded with some
 * common settings for different networks and features like migrations,
 * compilation and testing. Uncomment the ones you need or modify
 * them to suit your project as necessary.
 *
 * More information about configuration can be found at:
 * 
 * https://trufflesuite.com/docs/truffle/reference/configuration
 *
 * To deploy via Infura you'll need a wallet provider (like @truffle/hdwallet-provider)
 * to sign your transactions before they're sent to a remote public node. Infura accounts
 * are available for free at: infura.io/register.
 *
 * You'll also need a mnemonic - the twelve word phrase the wallet uses to generate
 * public/private key pairs. If you're publishing your code to GitHub make sure you load this
 * phrase from a file you've .gitignored so it doesn't accidentally become public.
 *
 */

const HDWalletProvider = require('@truffle/hdwallet-provider');

const fs = require('fs');
const mnemonic = fs.readFileSync(".secret").toString().trim();

module.exports = {
  /**
   * Networks define how you connect to your ethereum client and let you set the
   * defaults web3 uses to send transactions. If you don't specify one truffle
   * will spin up a development blockchain for you on port 9545 when you
   * run `develop` or `test`. You can ask a truffle command to use a specific
   * network from the command line, e.g
   *
   * $ truffle test --network <network-name>
   */

  networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache, geth, or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    // development: {
    //  host: "127.0.0.1",     // Localhost (default: none)
    //  port: 8545,            // Standard Ethereum port (default: none)
    //  network_id: "*",       // Any network (default: none)
    // },
    // Another network with more advanced options...
    // advanced: {
    // port: 8777,             // Custom port
    // network_id: 1342,       // Custom network
    // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
    // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
    // from: <address>,        // Account to send txs from (default: accounts[0])
    // websocket: true        // Enable EventEmitter interface for web3 (default: false)
    // },
    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    ropsten: {
    provider: () => new HDWalletProvider(mnemonic, `https://ropsten.infura.io/v3/YOUR-PROJECT-ID`),
    network_id: 3,       // Ropsten's id
    gas: 5500000,        // Ropsten has a lower block limit than mainnet
    confirmations: 2,    // # of confs to wait between deployments. (default: 0)
    timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
    skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
    rinkeby: {
      provider: () => new HDWalletProvider(mnemonic, `https://rinkeby.infura.io/v3/74df1b67701a4e67b6d1d732cf622fad`),
      network_id: 4,       // Ropsten's id
      gas: 5500000,        // Ropsten has a lower block limit than mainnet
      confirmations: 2,    // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
      },
    // Useful for private networks
    // private: {
    // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
    // }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.8.13",      // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  },

  // Truffle DB is currently disabled by default; to enable it, change enabled:
  // false to enabled: true. The default storage location can also be
  // overridden by specifying the adapter settings, as shown in the commented code below.
  //
  // NOTE: It is not possible to migrate your contracts to truffle DB and you should
  // make a backup of your artifacts to a safe location before enabling this feature.
  //
  // After you backed up your artifacts you can utilize db by running migrate as follows:
  // $ truffle migrate --reset --compile-all
  //
  // db: {
    // enabled: false,
    // host: "127.0.0.1",
    // adapter: {
    //   name: "sqlite",
    //   settings: {
    //     directory: ".db"
    //   }
    // }
  // }
};

**Comment by kimpace19882627** [comment]
这是我的  truffle-config.js
