### ISSUE TITLE
Issue While Containerizing.

### ISSUE THREAD

**Issue by rachit2501** [trufflesuite/truffle#3110]
I am creating a server-side application and using a truffle setup to communicate to the blockchain. Locally the project works fine but if I try to containerize the project truffle build fails.

## Expected Behavior

The installation should complete easily and I should have a running container.

## Actual Results

```
`npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/xhr2-cookies-2a921703/README.md'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/InheritanceSpecifier/__snapshots__'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/eth-tx-summary-f333bb5e/example.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/eth-tx-summary-f333bb5e/expected-trace.json'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/@solidity-parser/parser-11454a72/dist/antlr4/atn/PredictionMode.js'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/MemberAccess/__snapshots__'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/ModifierDefinitions/__snapshots__'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/@openzeppelin/contracts-d24218d3/build/contracts/ERC20Burnable.json'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/NameValueExpression/__snapshots__'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/Ownable/__snapshots__'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/mocha-65c59efb/README.md'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/Pragma/__snapshots__'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/PrettierIgnore/__snapshots__'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/Proxy/__snapshots__'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/ethereumjs-block-eb5aba83/tests/testdata-from-rpc.json'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/ethereumjs-block-eb5aba83/tests/testdata.json'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/ethereumjs-block-eb5aba83/tests/testdata2.json'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests/quotes/__snapshots__'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/prettier-plugin-solidity-7f4b2c31/tests'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/ethers-83107a5a/dist/ethers.min.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/typescript-bf155e1e/lib/tsserverlibrary.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/test/scenarios/memorylogger.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/test/sources/external_compile/test/metacoin.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/test/scenarios/commands/migrate.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/test/scenarios/migrations/migrate.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/build/templates/migration.js'
npm WARN tar ENOENT: no such file or directory, open '/build/node_modules/.staging/truffle-6bd01753/test/scenarios/commands/networks.js'
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/truffle-6bd01753/test/scenarios'
npm WARN tar ENOENT: no such file or directory, lstat '/build/node_modules/.staging/truffle-6bd01753/test/scenarios'
```

## Environment

Operating System: Ubunto
Truffle v5.1.29 (core: 5.1.29)
Solidity - 0.6.2 (solc-js)
Node v10.19.0
Web3.js v1.2.1

**Comment by fainashalts** [comment]
HI @rachit2501, do you mean the command `truffle build` fails? This command is actually deprecated -- take a look at the documentation here: https://www.trufflesuite.com/docs/truffle/reference/truffle-commands#build

You might consider looking at webpack or something similar to do your build. 

If you'd like to share your project we can try to take a look and see if we can spot any obvious issues.

**Comment by rachit2501** [comment]
No I don't mean the command ```truffle build```. I mean the command ```docker-compose up```. I get the above error while containerinzing my node application with a truffle project.

**Comment by eggplantzzz** [comment]
Hey @rachit2501, I would guess that this has something to do with how you have the docker environment set up. It could be some kind of permissions error related to npm from just glancing at the error above. Have you been able to install other packages successfully the same way?

Unfortunately I don't really know too much about setting these containers up. Is there anything else about your setup that you can share? Are you able to use something like nvm with npm? I know that this often resolves a lot of permissions errors that come up for people I think.

**Comment by rachit2501** [comment]
Not to share anything more in particular. It's just a node container and yes npm works fine without a truffle setup.

**Comment by eggplantzzz** [comment]
Look into using nvm perhaps. The above error is coming from npm so once again I suspect it has something to do with the 
permissions configuration for your container.

**Comment by eggplantzzz** [comment]
@rachit2501 Hey! How would you feel about sharing your docker setup and docker-compose stuff so we can try to reproduce it here? If you can we'll try and see if we can gain any insight!

**Comment by rachit2501** [comment]
Sure. [](https://github.com/rachit2501/CONTROLLY/tree/4e4f8be5e2506f5dc0747adfa601a5bd3ecd43e7). This is a link to the commit for you to reproduce.

**Comment by eggplantzzz** [comment]
@rachit2501 Do you have some quick steps that I can take to get it to attempt building?

**Comment by rachit2501** [comment]
@eggplantzzz Ya just clone the code at the above git checkpoint. Then just run `docker-compose up` or `docker build --tag <name> <path>`

**Comment by eggplantzzz** [comment]
Thanks for the steps! So I was able to duplicate your error... kind of. I get the same kind of error except some of the paths are different. It can't find files in directories starting with `/build/node_modules/.staging/...`.

At first glance, it doesn't seem clear to me that this error is being caused by Truffle. I haven't really dug too far into this but I would be interested in knowing why you think it might be caused by Truffle. Let me know!

**Comment by rachit2501** [comment]
@eggplantzzz Well firstly because such error ave never happened with my past containers. Secondly, if you look at the error message, the files, are all associated, almost exclusively with the truffle setup. So those are basically the reasons I think, the issue lies somewhere because of the truffle setup.

**Comment by fainashalts** [comment]
Hi @rachit2501 thanks, one of us will try to look into this and see if we can help!

**Comment by rachit2501** [comment]
@fainashalts Thank you.

**Comment by CruzMolina** [comment]
@rachit2501 Have you tried updating `@truffle/hdwallet-provider` and `truffle` to latest?

Am currently troubleshooting and after updating am getting this error:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Look like a nested `git` dependency issue coming from `eth-sig-util`: https://github.com/MetaMask/eth-sig-util/blob/1.x/package.json#L24

**Comment by CruzMolina** [comment]
Ok @rachit2501 , I _think_ I've been able to resolve this issue.

What you'll need to do is `npm install @truffle/hdwallet-provider@next`, and you should be able to build your container. 🤞🤞
