### ISSUE TITLE
Truffle Unbox React Error

### ISSUE THREAD

**Issue by Guru4741** [trufflesuite/truffle#3112]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

While running truffle unbox react, it works fine till "cleaning up temporary files", but shows error as  "Unbox failed" for "setting up box"

## Steps to Reproduce

truffle unbox react

## Expected Behavior

Command should run properly without any error messages.

## Actual Results

```
You can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project

Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
✔ cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: cd client && npm ci
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.installBoxDependencies (/Users/gaurav/.npm-global/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:107:1)
    at Object.setUpBox (/Users/gaurav/.npm-global/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:68:1)
    at /Users/gaurav/.npm-global/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:62:1
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gaurav/.npm-global/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
    at <anonymous>
Truffle v5.1.30 (core: 5.1.30)
Node v8.11.2
.

```
## Environment

* Operating System: Mac OS X 10.14.5
* Ethereum client:
* Truffle version (`truffle version`):Truffle v5.1.30
* node version (`node --version`): v8.11.2
* npm version (`npm --version`): 5.6.0

**Comment by nsr-py** [comment]
I got the same error in
- Operating System: Pop_OS 19.10
- node version (node --version): v12.18.1
- npm version (npm --version): 6.14.5

**Comment by CruzMolina** [comment]
Hey @Guru4741 !

It looks like unboxing is failing on the `npm ci` command because you're using `npm` 5.6.0 and `npm ci` didn't exist until [5.7.0](https://blog.npmjs.org/post/171139955345/v570).

Upgrading to 5.7.0 (`npm install npm@5.7.0`) should do the trick.

@nsr-py , are you sure you're using a later version of `npm`? Can you share your stack trace, in case unboxing is failing on a different line?

**Comment by Guru4741** [comment]
Thanks @CruzMolina CruzMolina 

I updated NPM. It worked.

Thanks a lot!!

**Comment by fainashalts** [comment]
Looks like this is resolved! Closing this for issue maintenance.

**Comment by nsr-py** [comment]
`Error: Command failed: cd client && npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/web3-js/WebSocket-Node.git /root/.npm/_cacache/tmp/git-clone-924757b2/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-924757b2/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-25T03_20_39_186Z-debug.log

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:107:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:62:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Truffle v5.1.31 (core: 5.1.31)
Node v12.18.1
`

I hope this should give a better idea of my problem.

> Hey @Guru4741 !
> 
> It looks like unboxing is failing on the `npm ci` command because you're using `npm` 5.6.0 and `npm ci` didn't exist until [5.7.0](https://blog.npmjs.org/post/171139955345/v570).
> 
> Upgrading to 5.7.0 (`npm install npm@5.7.0`) should do the trick.
> 
> @nsr-py , are you sure you're using a later version of `npm`? Can you share your stack trace, in case unboxing is failing on a different line?

**Comment by nsr-py** [comment]
```
Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/web3-js/scrypt-shim.git /root/.npm/_cacache/tmp/git-clone-32f37ae7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-32f37ae7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-25T03_23_45_748Z-debug.log
✔ cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: cd client && npm ci
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/web3-js/scrypt-shim.git /root/.npm/_cacache/tmp/git-clone-32f37ae7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-32f37ae7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-25T03_23_45_748Z-debug.log

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:107:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:62:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.1.31 (core: 5.1.31)
Node v12.18.1
```

This should give a better understanding of what I am facing.

> Hey @Guru4741 !
> 
> It looks like unboxing is failing on the `npm ci` command because you're using `npm` 5.6.0 and `npm ci` didn't exist until [5.7.0](https://blog.npmjs.org/post/171139955345/v570).
> 
> Upgrading to 5.7.0 (`npm install npm@5.7.0`) should do the trick.
> 
> @nsr-py , are you sure you're using a later version of `npm`? Can you share your stack trace, in case unboxing is failing on a different line?

**Comment by CruzMolina** [comment]
@nsr-py , what version of `git` do you have installed locally (`git --version`)?

Can you share the log mentioned here?

```bash
npm ERR! Command failed: git clone --mirror -q git://github.com/web3-js/scrypt-shim.git /root/.npm/_cacache/tmp/git-clone-32f37ae7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-32f37ae7/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-25T03_23_45_748Z-debug.log
```

**Comment by nsr-py** [comment]
I am using ```git version 2.20.1```

The following is the complete log (it is about 5000 lines long).

Also, I noticed one more thing. The logs are now going in some root folder. This is happening since I have installed an older version of node using nvm (I did this in an attempt to use Node v10 which was suggested to deal with the error in one StackOverflow post). The original .nvm/_logs directory is not storing any logs now.

I accessed this after going to my root directory and using ```sudo -i``` and there I found the path mentioned in the error and copied it into this file

[crash_report.log](https://github.com/trufflesuite/truffle/files/4833244/crash_report.log)

**Comment by CruzMolina** [comment]
Hmm, so this looks like a `node`/`npm` permissions issue. Did you install `npm` or `nvm` using `sudo`?

It seems like the solution here is to reinstall `node`/`npm` with `nvm` w/o `sudo`. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by nsr-py** [comment]
I installed node with `sudo apt install nodejs` and npm was installed along with it.

I installed nvm using `curl` by following [this article](https://www.liquidweb.com/kb/how-to-install-nvm-node-version-manager-for-node-js-on-ubuntu-12-04-lts/)

One more thing, whenever I do `node -v` it tells me I am using v10 I have to specifically ask it to use v12 using nvm. 
Should I first deal with this before I follow the solution that you mentioned?

**Comment by CruzMolina** [comment]
Ah, yeah it's not recommended to install `node` using `sudo`. If you can get the permissions mismatch figured out, it _should_ resolve the issue you're seeing.

**Comment by nsr-py** [comment]
Thank you so much @CruzMolina 
That solved my issue.

```
✔ cleaning up temporary files
✔ Setting up box

Unbox successful, sweet!
```

**Comment by adhithyaarun** [comment]
Hi! I'm facing the same issue. I've installed my `node` using `snap`.
```
Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
✔ Cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: cd client && npm ci
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.installBoxDependencies (/home/$USER/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:138:1)
    at Object.setUpBox (/home/$USER/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /home/$USER/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:117:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/$USER/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.1.49 (core: 5.1.49)
Node v12.19.0
```
- Operating System: `Ubuntu 20.04`
- Truffle version (`truffle version`):`Truffle v5.1.49`
- `node` version (`node --version`): `v12.19.0`
- `npm` version (`npm --version`): `6.14.8`

**Comment by icalaba** [comment]
Hi I am facing this same issue in powershell. How do i resolve this?. Thank you 

× Setting up box
Unbox failed!
Error: Command failed: cd client && npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kalab\AppData\Roaming\npm-cache\_logs\2021-11-24T11_38_06_495Z-debug.log

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.installBoxDependencies (C:\Users\kalab\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\unbox.js:139:1)
    at Object.setUpBox (C:\Users\kalab\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\index.js:66:1)
    at C:\Users\kalab\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\kalab\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:5:42)
Truffle v5.4.22 (core: 5.4.22)
Node v12.13.0
