### ISSUE TITLE
truffle test --network ropsten

### ISSUE THREAD

**Issue by arunsybex** [trufflesuite/truffle#3115]
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.1.30 (core: 5.1.30)
* node version (`node --version`): v12.18.1
* npm version (`npm --version`): 6.14.5

![image](https://user-images.githubusercontent.com/20275068/85121909-4ea1c900-b243-11ea-96cf-feb6623bac6d.png)

**Comment by fainashalts** [comment]
Hi @arunsybex are you still having issues accessing ropsten with truffle test? It looks like there was a timeout while attempting to connect to the network, and you may need to make some changes to your config. Can you provide some more details about your project?

**Comment by fainashalts** [comment]
Hi @arunsybex, we're closing this for issue maintenance. Please open a new issue or comment here if you're still experiencing issues. Thanks!
