### ISSUE TITLE
Colony job broken

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#3140]
#3138 accidentally broke the `COLONY` job: https://app.circleci.com/pipelines/github/trufflesuite/truffle/184/workflows/81f7c350-d718-46f8-8450-9f941a592cc6/jobs/79

Looks like the solution is to crank up the `maxBuffer` a bit more...

**Comment by chmanie** [comment]
Wow, crazy! I'll experiment with the size a bit and adjust accordingly. Should we then also increase the `maxBuffer` for the native strategy?

**Comment by CruzMolina** [comment]
@chmanie Looks like #3002, bumped `maxBuffer` for native solc compilations to 10MB. If you or others have run into `ENOBUFS` when using the native solc strategy, then we should def bump it.
