### ISSUE TITLE
Truffle is really slow to start up

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3142]
## Issue

Truffle can be really slow to start up -- and I'm not talking about any particular command here.  Merely running `truffle version`, or `truffle help`, or `truffle`, can take a while.  Anyway it's annoying so I'm posting this here as an issue at @gnidan's suggestion.

## Environment

* Operating System: Linux Mint 19.3 (64-bit)
* Truffle version (`truffle version`): 5.1.33
* node version (`node --version`): v10.15.3

**Comment by eggplantzzz** [comment]
Hopefully this type of thing will be resolved after we get rid of all the callbacks. If that doesn't resolve it at least it should be easier to troubleshoot then I think.

**Comment by haltman-at** [comment]
Hm, this seems to be a partial duplicate of #2038.

**Comment by haltman-at** [comment]
Closing this to move things to #3509.
