### ISSUE TITLE
Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by CassieJie** [trufflesuite/truffle#3144]
- [ ] I've run into errors when executing `truffle test --network <networkid>` to run **TestAdoption.sol** script.

---------------------------

```
Compiling your contracts...
===========================
> Compiling .\contracts\Adoption.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\Adoption.sol  
> Compiling .\test\TestAdoption.sol   



  TestAdoption
    1) "before all" hook: prepare suite


  0 passing (2m)
  1 failing


  1) TestAdoption
       "before all" hook: prepare suite:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```
Any help here? Thanks!

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by CruzMolina** [comment]
Hey @CassieJie , can you share your...

* Operating System: 
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`): 

as well as your `truffle-config.js` file?

**Comment by harsh-98** [comment]
@CruzMolina  I also faced the same issue. For me,
- Operating system: Darwin  18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64
- truffle version v5.1.34
- node version: v10.18.0
- npm version: 6.13.4

**Comment by CruzMolina** [comment]
Hey @harsh-98 ! Can you share your `trufffle-config.js` file?

**Comment by harsh-98** [comment]
```


const HDWalletProvider = require("@truffle/hdwallet-provider");

require("dotenv").config();
let privateKey = process.env.PRIV_KEY;
let mnemonic = process.env.MNEMONIC;
module.exports = {
  networks: {
    ropsten: {
      provider: () =>
        new HDWalletProvider(
          mnemonic,
          `https://ropsten.infura.io/v3/${process.env.INFURA_KEY}`
        ),
      network_id: 3, // Ropsten's id
      from: process.env.ADDR,
      gas: 5500000, // Ropsten has a lower block limit than mainnet
      confirmations: 2, // # of confs to wait between deployments. (default: 0)
    },
  },
  mocha: {
  },
  compilers: {
    solc: {
      version: "0.6.0", // Fetch exact version from solc-bin (default: truffle's version)

    },
  },
};

```

**Comment by CruzMolina** [comment]
Thanks @harsh-98 ! I would try upping the `mocha` "before al"l timeout in your config.

```js
  mocha: {
    before_timeout: 220000 // <--- units in ms
  },

**Comment by fainashalts** [comment]
Hi @harsh-98 we think there may be something wrong with your tests. If you can provide them here we may be able to troubleshoot. Thanks!

**Comment by fainashalts** [comment]
Hi @harsh-98 we're closing this for issue maintenance. Please feel free to open a new issue if this is still a problem. Thanks!
