### ISSUE TITLE
Allow `truffle test` Ganache options to be configurable

### ISSUE THREAD

**Issue by dileepfrog** [trufflesuite/truffle#3147]
Right now, running `truffle test` uses the default ganache parameters defined [here](https://github.com/trufflesuite/truffle/blob/1c29803136a89cfa67b6533c144bffd26474a515/packages/core/lib/commands/test/index.js#L137)

It would be nice if this were configurable in `truffle-config.js`, perhaps under the `networks.test` section.

See also the corresponding [issue](https://github.com/trufflesuite/truffle/issues/1090) for `truffle develop`

**Comment by dileepfrog** [comment]
@eggplantzzz Just to bump this issue's priority if possible, please note that it prevents writing any test scenarios that require a wallet to have more than the default 100 ETH which is not an unreasonable case - within a `contract` block the chain does not get reset between test cases, so if a series of test cases all remove ETH from a wallet then later tests will fail due to insufficient ETH.

**Comment by haltman-at** [comment]
OK, closing this as it is now configurable!  However, it's still not configurable *well*, and it's still not all documented.  I'm going to close this issue, but #4382 will remain open, and I've opened #4807 for the work of making all this stuff work better and consistently.
