### ISSUE TITLE
How to verify contracts on etherscan?

### ISSUE THREAD

**Issue by ygcool** [trufflesuite/truffle#3162]
How to verify contracts on etherscan?

![image](https://user-images.githubusercontent.com/16422689/87213818-5f34f300-c35a-11ea-8726-e58414a90659.png)

**Comment by gnidan** [comment]
There's nothing built-in to Truffle for this, but I recommend @rkalis's [truffle-plugin-verify](https://www.npmjs.com/package/truffle-plugin-verify) for this purpose.

Let me know if that helps!

**Comment by fainashalts** [comment]
HI @ygcool we're closing this for issue maintenance. If anything comes up, feel free to open a new issue!
