### ISSUE TITLE
Payable function failing: ParserError: Expected primary expression.

### ISSUE THREAD

**Issue by isaacdchan** [trufflesuite/truffle#3165]
- [X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

payable(address) not working.

## Steps to Reproduce
Run `truffle compile`

```solidity
pragma solidity >=0.4.22 <0.7.0;

contract Test {

    constructor() public {
        address payable payable_address = payable(address(0));
    }

}
```
## Expected Behavior

address would be casted to payable address -> works in Remix

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

```
ParserError: Expected primary expression.
        address payable payable_address = payable(address(0));
```

## Environment

* Operating System: Windows 10
* Ethereum client: geth 1.9.15-stable-0f77f34b
* Truffle version (`truffle version`): 5.1.34
* node version (`node --version`): 10.14.3
* npm version (`npm --version`): 6.14.6

**Comment by CruzMolina** [comment]
Hey @isaacdchan !

Conversions from `address` to `address payable` were a new feature added in [Solidity 0.6.0](https://solidity.readthedocs.io/en/v0.6.0/060-breaking-changes.html#new-features).
`truffle` currently ships with Solidity v0.5.16.

The contract should compile correctly once you specify ^0.6.0 in your `truffle-config.js`.

Example:

```js
module.exports = {
  ...
  compilers: {
    solc: {
       version: "0.6.0"
    }
  }
}
```

**Comment by isaacdchan** [comment]
Ahhh my bad thanks for the clarification. I'll close this issue.
