### ISSUE TITLE
Globals are not available during migrations

### ISSUE THREAD

**Issue by frangio** [trufflesuite/truffle#3167]
Globals like `artifacts` are not available to modules required from a migration.

```
// migrations/02_a_migration.js
const Greeter = artifacts.require('Greeter'); // ok
require('./my-module'); // ./my-module won't have access to artifacts global
```

This issue does not happen in tests.

@gnidan suggested this may be due to migrations using `@truffle/require`, which tests don't use.

### Steps to Reproduce

See https://github.com/frangio/truffle-globals-repro

```
git clone https://github.com/frangio/truffle-globals-repro.git
cd truffle-globals-repro
npm ci
npx truffle test
```

### Expected Behavior

Globals should be global for all modules.

**Comment by frangio** [comment]
I think this is due to the use of the `vm` module rather than the custom require. The `artifacts` global is injected into the context of the migration as run through `script.runInNewContext`, and it doesn't get propagated to submodules in the `require` function that is injected into that context.

**Comment by gnidan** [comment]
Hm @frangio if you want to make an attempt at removing the usage of `vm`, it's possible that there's no good reason for using `vm` in the first place. If CI passes, that'd be a pretty good indication that the change is safe.

Thanks for raising this and digging into it more!
