### ISSUE TITLE
Allow Michelson .tz files as contracts in Truffle@tezos

### ISSUE THREAD

**Issue by claudebarde** [trufflesuite/truffle#3170]
## Lack of support for Michelson .tz files

Right now, Truffle only supports high-level languages for development and it's not possible to use .tz files. Michelson is the native language of Tezos and using .tz files directly in Truffle could be very useful (for example, the code of smart contracts could be copied from a block explorer, pasted into a .tz file in Truffle and used to originate the contract on the local node for testing purposes).

**Comment by CruzMolina** [comment]
Hey @claudebarde ! This should be resolved by #3173 and is out in the latest `truffle@tezos` release.
