### ISSUE TITLE
Remove `node-gyp` dependency

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#3175]
`sha3` v1.x uses `node-gyp` to build itself.

Current relevant dependency tree pulling in `sha3` v1.x:

![image](https://user-images.githubusercontent.com/7537712/89210535-1f39e800-d575-11ea-87ef-0ca7ee1fa9a8.png)

**Comment by gnidan** [comment]
Potential next step (suggested by @eggplantzzz) is to look at replacing our usage of sha3 with something JS-friendly

**Comment by gnidan** [comment]
Other possible next step is to petition js-ethereum-cryptography to add support for sha3

**Comment by CruzMolina** [comment]
Updated the description with a PlantUML Diagram describing the current dependency tree state of `truffle`, as it pertains to `node-gyp`.

**Comment by PatrickAlphaC** [comment]
I think this would fix this issue as well. Users are running into this weird error

2 warnings and 1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/code/chainlink-lottery/client/node_modules/sha3
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrick/.npm/_logs/2020-08-01T20_51_31_205Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:104:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:110:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.1.37 (core: 5.1.37)

**Comment by CruzMolina** [comment]
@PatrickAlphaC Is there a specific box you're seeing this error occur with (`truffle unbox <someBox>`) or is this reproducible with any box for you?

**Comment by PatrickAlphaC** [comment]
`truffle unbox react`
