### ISSUE TITLE
Rebase eth-json-rpc-middleware

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#3202]
https://github.com/trufflesuite/eth-json-rpc-middleware is a little out of date, including one package renaming causing an installation warning:

>npm WARN deprecated eth-json-rpc-errors@1.1.1: Package renamed: https://www.npmjs.com/package/eth-rpc-errors

As it's a fork from MetaMask, issues can't be filed against it directly, but it's updated in MetaMask.

**Comment by gnidan** [comment]
Oh interesting @wbt - do you happen to know where this is used? Or @CruzMolina, do you know?

**Comment by CruzMolina** [comment]
`@trufflesuite/eth-json-rpc-middleware` is used in [`@trufflesuite/provider-engine`](https://github.com/trufflesuite/provider-engine/blob/master/package.json#L19).

Currently `@trufflesuite/eth-json-rpc-middleware` is tracking v4.x.  For stability reasons, I wouldn't recommend pulling in and publishing v5.x from `MetaMask/eth-json-rpc-middleware` until `MetaMask/web3-provider-engine` pulls it in on [`master`](https://github.com/MetaMask/web3-provider-engine/blob/master/package.json#L25).

**Comment by wbt** [comment]
@truffle/hdwallet-provider@1.0.39 [uses](https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/package.json) @trufflesuite/web3-provider-engine which is found [here](https://github.com/trufflesuite/provider-engine), also forked from MetaMask and [uses](https://github.com/trufflesuite/provider-engine/blob/master/package.json) both @trufflesuite/eth-json-rpc-middleware and @trufflesuite/eth-json-rpc-filters (another fork from MetaMask) which [uses](https://github.com/trufflesuite/eth-json-rpc-filters/blob/v4.x/package.json) where the renaming has also been [fixed](https://github.com/MetaMask/json-rpc-engine/pull/47).

**Comment by gnidan** [comment]
Ah that's why my search in this repo didn't turn up anything.

Anyway, I'll cc @danfinlay and @kumavis in case [Cruz's comment](https://github.com/trufflesuite/truffle/issues/3202#issuecomment-663734716) is something for them to be aware of!

**Comment by gnidan** [comment]
BTW @wbt, this is off-topic, but I don't know how to reach you elsewhere... can I buy you a coffee or a beer? Your commitment to best practice continues to inspire me and the rest of the Truffle team.

**Comment by fainashalts** [comment]
@wbt we're thinking we should wait to see what MetaMask does with this before we make changes on our end. Does that make sense?

**Comment by fainashalts** [comment]
@wbt thanks for bringing this to our attention! It looks like there's nothing actionable on this for us right now, so we're going to close it for issue maintenance. If you think we should keep it open, let us know!
