### ISSUE TITLE
Issue using `debug` in `truffle develop`

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#3205]
## Issue

There is a problem trying to debug a transaction while using `truffle develop`

## Steps to Reproduce

1. `truffle unbox metacoin`
2. `truffle develop`
3. At the prompt, run `migrate`
4. Run the following
```
const instance = await MetaCoin.deployed();
const result = await instance.sendCoin(accounts[0], 10);
```
5. Get the transaction hash from `result` and use it as an argument to `debug`

## Expected Behavior

I expect the debugger to load the transaction for `sendCoin`

## Actual Results

I receive a connection error.
```
> Something went wrong while attempting to connect to the network. Check your network configuration.

Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```

## Environment

* Operating System: mac
* Truffle v5.1.36 (core: 5.1.36)
* Solidity v0.5.16 (solc-js)
* Node v10.20.1
* Web3.js v1.2.1

**Comment by haltman-at** [comment]
Hm, I wonder if this is due to what @gnidan, @fainashalts, and @cds-amal are working on.  Like, I wonder if it's trying to connect to the wrong network due to not inheriting the config properly?

**Comment by gnidan** [comment]
Hm, very strange. I don't think it's related to that work @haltman-at, but it's definitely something with the debugger not getting the correct config - since `develop` runs on port 9545, that error's a clear giveaway that something's wrong.

I don't suppose this is related to that change you made to the debugger's `--network` flag default, @haltman-at?

**Comment by haltman-at** [comment]
I mean, I got *rid* of the default.  It now uses whatever means Truffle normally uses to determine the default network.

**Comment by fainashalts** [comment]
Interesting! I don't believe the issue I'm dealing with is related, but I'll keep my eyes peeled in case it is!

**Comment by gnidan** [comment]
Hm well this used to work, since I used this exact process to test the debugger all the time. Might be worth figuring out the first version it was broken, to check the changelog.

**Comment by eggplantzzz** [comment]
When no network config is provided, `Environment.detect` sets the default port to `7545` [here](https://github.com/trufflesuite/truffle/blob/develop/packages/environment/environment.js#L138-L145). I'm going to say the solution is to set this to `9545`.

**Comment by haltman-at** [comment]
So, did #3319 fix this?  I don't know whether to close this or not.

**Comment by eggplantzzz** [comment]
Looks like this is good on Truffle 5.1.44
