### ISSUE TITLE
Truffle can't handle trailing ; in truffle develop

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#3206]
## Issue

Truffle complains if you add a trailing semicolon in `truffle develop`

## Steps to Reproduce

1. Run `truffle unbox metacoin`
2. Run `truffle develop`
3. Run `migrate`
4. Run `await MetaCoin.deployed();`

## Expected Behavior

No error

## Actual Results

```
truffle(develop)> const i = await MetaCoin.deployed();
Thrown:
evalmachine.<anonymous>:1
  await MetaCoin.deployed();
                           ^

SyntaxError: Unexpected token ;
```

## Environment

OS = mac
Truffle v5.1.36 (core: 5.1.36)
Solidity v0.5.16 (solc-js)
Node v10.20.1
Web3.js v1.2.1

**Comment by gnidan** [comment]
Good find!

**Comment by eggplantzzz** [comment]
This has always bothered me but it was always such a small thing haha.

**Comment by fainashalts** [comment]
Note: we think this only happens with `await`.

**Comment by eggplantzzz** [comment]
[the culprit](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/console.js#L197-L214)
