### ISSUE TITLE
Feature Request - custom functions for truffle console

### ISSUE THREAD

**Issue by fxfactorial** [trufflesuite/truffle#3215]
I like making my own custom functions and the console is really amazing. 

would really appreciate if truffle console could load up some file, `helpers.js` that i put in truffle-config.js or something and when loading `truffle console`, my helpers.js loaded into the console. 

Thank you

**Comment by eggplantzzz** [comment]
I definitely like this idea. My idea for a spec would be something like a property in the `truffle-config.js` that would be an object containing all the helpers you would like to use. Then we could inject them into all Truffle environments.
