### ISSUE TITLE
If statement in Migrations.sol instead of require

### ISSUE THREAD

**Issue by DevonYarbrough** [trufflesuite/truffle#3223]
https://github.com/trufflesuite/truffle/blob/10c7234ae697e1999b52fe981ed1e4e91f77b2d6/packages/core/lib/commands/init/initSource/contracts/Migrations.sol#L12-L14

Should Migrations.sol use a require statement instead of an if statement?

```
  modifier restricted() {
    if (msg.sender == owner) _;
  }
```
versus:
```
  modifier restricted() {
    require (msg.sender == owner, "Must be owner"); _;
  }
```

**Comment by eggplantzzz** [comment]
This seems totally sensible :)
