### ISSUE TITLE
Truffle Build (Custom) broken in beta (3.0.0-9)

### ISSUE THREAD

**Issue by oladotunr** [trufflesuite/truffle#324]
---------------------------

## Issue

We recently moved over to the `beta` branch to start making use of the new npm-based import functionality, although now it seems the custom build support is broken.

We used to define a custom `builder` class, instantiate it and pass the instance to `build` in our `truffle.js` file. Now that throws an error saying `No build configuration specified. Can't build.` which is fine. But now when we pass the same instance as `builder` it throws a separate error `Build configuration can no longer be specified as an object. Please see our documentation for an updated list of supported build configurations.` because it seems to be expecting our custom builder class instance to be a function (`truffle/lib/build.js - ln 96`)? which doesn't seem to make any sense as a logical type check, assuming you're expecting `builder` to be an object with the various `build`, `clean` etc functions and not just a flat function?

Here's our `truffle.js` config file:

```
module.exports  = {
  builder:      require('./builders/ownage-network-api-build.js')({
    version:    "1.0"
  }),

  rpc: {
    host:       "localhost",
    port:       8545,
    gas:        9999999 // For the Solidity tests.
  }
};
```
and here's what we have to do to get this to work; the required builder module extract (where ONIBuilder is a class with the various clean/build methods):

```
module.exports          = function(opts)
{
    var oni             = new ONIBuilder(opts);
    var builder         = function(options, cb)
    {
        return this.build(options, cb);
    }.bind(oni);
    return builder;
};
```
So this works but it's messy and the clean function is never invoked due to the way the code assembles the `builder` in `truffle/lib/build.js - lns 100-102`. Again, the code to make this work is functional in the stable build of truffle (2.1.1) it seems the new changes desired to remove support for the `DefaultBuilder`, but doesn't provide a useful way to provide our own `builder` class, only a `builder` function that limits functionality somewhat.
To provide some context here: Our default builder allows us to package the ether-pudding compiled smart contract interface types into an npm module, to be packaged, versioned and distributed for internal usage across our separate codebases. The `truffle build` pipeline is pretty useful for us as it provides the convenience of driving the process cleanly, and providing the necessary truffle dependent functionality required as part of that process. I hope we don't lose it outright.

## Steps to Reproduce

See the above description.

## Expected Behavior

Previously (`truffle@2.1.1`) we'd just define our build class and instantiate it into the `build` config in the `truffle.js` file and It Just Worked. Would be great to be able to do that again without having to go around the houses.

## Actual Results

See the above description.

## Environment

* Operating System: Any
* Truffle version: 3.0.0-9
* Ethereum client: Any
* node version: Any 
* npm version: Any

**Comment by KennyVan** [comment]
This is not just the custom build that is broken.

Initializing a new project and trying to run it is broken in general right now since Beta 8, I am now running Beta 7 pretty smoothly

**Comment by GNSPS** [comment]
+1

**Comment by tcoulter** [comment]
Hey @ownageio et. al., can you recheck this with Truffle 3.0.2? Note that even if you were using 3.0beta you will still need to handle breaking changes when upgrading to 3.0.2. See the [upgrade guide](http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3) for more info.

**Comment by ownageio** [comment]
Thanks for this Tim,

Will coordinate with Peter and test as we upgrade to 3.0.2.

Thanks for the excellent support.

Regards,



Dotun Rominiyi
Director of Technology
Ownage Ltd
www.ownage.io<http://www.ownage.io>

**Comment by RichLinnell** [comment]
I'm getting this error using Truffle v3.2.5. Is this no longer supported?

**Comment by DerekChia** [comment]
Same, getting the same error after init. Any idea why this error appears?

**Comment by gnidan** [comment]
I'm betting this issue is out of date. Closing. Feel free to correct me, and I will reopen. Thanks!
