### ISSUE TITLE
Error running npx truffle unbox Azure-Samples/Blockchain-Ethereum-Template

### ISSUE THREAD

**Issue by PingPongSet** [trufflesuite/truffle#3246]
I have the error below when I running the command below:
`C:\_MyLab\AzureCode\Blockchain\HelloBlockchain>npx truffle unbox Azure-Samples/Blockchain-Ethereum-Template`

> Starting unbox...
> =================
> 
> √ Preparing to download box
> × Downloading
> Unbox failed!
> × Downloading
> Unbox failed!
> RequestError: Error: connect ETIMEDOUT 199.232.56.133:443
>     at new RequestError (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
>     at Request.plumbing.callback (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
>     at Request.RP$callback [as _callback] (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
>     at self.callback (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
>     at Request.emit (events.js:315:20)
>     at Request.onRequestError (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
>     at ClientRequest.emit (events.js:315:20)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:315:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Truffle v5.1.39 (core: 5.1.39)
> Node v12.18.3
> 
> C:\_MyLab\AzureCode\Blockchain\HelloBlockchain>

My Internet connection is working.

Sometimes, the error is 

> RequestError: Error: getaddrinfo ENOENT raw.githubusercontent.com

instead of 

> RequestError: Error: connect ETIMEDOUT 199.232.56.133:443

If download the app mannually, and run another command below, another error:

> Get version for required apps: truffle [Execute command]  Working dir:
> c:\_MyLab\AzureCode\Blockchain\HelloBlockchain Running command npx
> truffle compile [Execute command] Error: Cannot find module
> 'truffle-hdwallet-provider' Require stack:
> - c:\_MyLab\AzureCode\Blockchain\HelloBlockchain\truffle-config.js
> - C:\Users\username\AppData\Roaming\npm\node_modules\truffle\node_modules\original-require\index.js
> - C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (c:\_MyLab\AzureCode\Blockchain\HelloBlockchain\truffle-config.js:1:26)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at Object.require (internal/modules/cjs/helpers.js:72:18)
>     at Function.load (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:161:1)
>     at Function.detect (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:150:1)
>     at Object.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\compile.js:68:1)
>     at Command.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
>     at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:51:1)
>     at __webpack_require__ (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:19:1)
>     at C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:83:1
>     at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:89:10)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32) [Execute command] Truffle v5.1.39 (core: 5.1.39) Node v12.18.3 [Execute
> command] Finished running command
---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by fainashalts** [comment]
Hi @PingPongSet is this still an issue for you? This looks like the error may be due to internet connectivity. Please let us know if we can help!

**Comment by PingPongSet** [comment]
@fainashalts Yes, the issue still exists. I tried many times running the the two commands, still getting the error. Please help.

**Comment by gnidan** [comment]
We're not able to reproduce this. Could you try upgrading truffle? (`npm uninstall -g truffle` and then `npm install -g truffle`)

My hunch is that it might be a problem with your internet connection.

**Comment by PingPongSet** [comment]
I have tried quite a few different connections, where I can visit web pages, but I have this problem. What is required of connection that allows to download?

**Comment by eggplantzzz** [comment]
There should be nothing special required for this. I was unable to reproduce your error on a mac. It seems like it could be something related to a slow connection from just glancing at the error message: a timeout.

**Comment by gnidan** [comment]
Not sure what's going on here. You might need to open an issue over at the Azure-Samples/Blockchain-Ethereum-Template repo, cause it looks like it's a problem with that box specifically?

**Comment by fainashalts** [comment]
Hi @PingPongSet any updates on this, have you been able to resolve this issue on your end? Thanks, please let us know!

**Comment by PingPongSet** [comment]
@fainashalts thanks. It seems network issue.
