### ISSUE TITLE
Migration error to ganache-cli forked mainnet chain

### ISSUE THREAD

**Issue by wswarren12** [trufflesuite/truffle#3249]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using Ganache-CLI to fork mainnet for testing purposes. When doing this running into a problem where when I try to deploy to this development blockchain I get an error that says the first of the autogenerated accounts with 100 ETH have 0 WEI, so cannot pay gas for deployment. 

## Steps to Reproduce

1. Run: ganache-cli --fork https://mainnet.infura.io/v3/<infura_project_id> --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 100

2. Deploy with these settings: 

```
const HDWalletProvider = require('@truffle/hdwallet-provider');
require('dotenv').config() 
const mnenomic = "divide there...."; //autogen seed phrase copied from ganache-cli
module.exports = {

  networks: {

     development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 7545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
      provider: () => new HDWalletProvider(mnenomic, "https://mainnet.infura.io/v3/15f54146bc594f10a1db67c35275579a"),
      from: "0x7136fbDdD4DFfa2369A9283B6E90A040318011Ca"
     },

    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function

  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
       version: "0.5.17",    // Fetch exact version from solc-bin (default: truffle's version)
       docker: false,        // Use "0.5.1" you've installed locally with docker (default: false)
       settings: {          // See the solidity docs for advice about optimization and evmVersion
        optimizer: {
          enabled: true,
          runs: 200
        },
        evmVersion: "byzantium"
       }
    }
  }
}
```

3. Run: `truffle migrate` in command line

## Expected Behavior

Expect contracts to deploy to this test chain forked from mainnet. Contracts deployed fine to purely local ganache network. 

## Actual Results

```
"Migrations" could not deploy due to insufficient funds
   * Account:  0x868945aa455FEff1a676b95Ff364Ba58b2bEFCf8
   * Balance:  0 wei
   * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 327152000000000 and the sender's account only has: 0
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.
```

## Environment

* Operating System: Mac
* Ethereum client: Assume Geth (launching via infura)
* Truffle version (`truffle version`): v5.1.30
* node version (`node --version`): v10.15.0
* npm version (`npm --version`): 6.14.4

**Comment by fainashalts** [comment]
Hi @wswarren12 thanks for bringing this up! We're not sure if this is a Truffle or Ganache issue (@davidmurdoch tagging you here for visibility), so we'll need to triage it and see!

**Comment by davidmurdoch** [comment]
Hmm, It could be a ganache issue, however we do run tests for forked balance checks.

I noticed the `0x7136fbDdD4DFfa2369A9283B6E90A040318011Ca` in the config and the from in the migration are different. I wonder if that could be the culprit?

In any case, the most recent version of ganache does have some forked account related fixes, albeit not for balances, specifically. Can you upgrade truffle to v5.1.39 and try again?

**Comment by wswarren12** [comment]
Oh the 0x7136fbDdD4DFfa2369A9283B6E90A040318011Ca was when i tried to set the sender as my MetaMask account (and unlock the account on ganache). 

The 0x8 address was an autogen account, and when trying deploy from the autogen accounts I removed the from field in config.

**Comment by davidmurdoch** [comment]
Can you upgrade truffle to v5.1.39 and try again?

**Comment by wswarren12** [comment]
Yep, I upgraded to to v5.1.39 and tried again. I'm getting the same 

```
"Migrations" could not deploy due to insufficient funds
   * Account:  0x5409ED021D9299bf6814279A6A1411A7e866A631
   * Balance:  0 wei
   * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 327152000000000 and the sender's account only has: 0
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.39 (core: 5.1.39)
Node v10.15.0
```

That account should have 100 ETH, since it's an auto created account via ganache-cli 
`(0) 0x5409ED021D9299bf6814279A6A1411A7e866A631 (100 ETH)`

Have checked that configs match: 

`    development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
      provider: () => new HDWalletProvider(mnenomic, "https://mainnet.infura.io/v3/<infura_id>"),
     },`

**Comment by gnidan** [comment]
Sounds like it's not actually connecting to your ganache-cli. If you run ganache-cli with a different (e.g.) `--networkId=999`, and then update the truffle-config.js from `network_id: "*"` to `network_id: 999` (again, e.g.), then that should hopefully confirm that Truffle and Ganache are actually talking to each other.

Also, for what it's worth, what version of ganache-cli are you on?

Thanks for helping us get to the bottom of this!

**Comment by wswarren12** [comment]
Yep, that is probably the issue. Here's the error message I get when I set
the networkId to 999:

Error: The network id specified in the truffle config (999) does not match
the one returned by the network (1).  Ensure that both the network and the
provider are properly configured.

    at Object.detectAndSetNetworkId
(/usr/local/lib/node_modules/truffle/build/webpack:/packages/environment/environment.js:97:1)

    at process._tickCallback (internal/process/next_tick.js:68:7)

Truffle v5.1.39 (core: 5.1.39)

Here are my configs:

development: {
host: "127.0.0.1", // Localhost (default: none)
port: 8545, // Standard Ethereum port (default: none)
network_id: "999", // Any network (default: none)
provider: () => new HDWalletProvider(mnenomic, "
https://mainnet.infura.io/v3/<infura>"),
},

HD Wallet

==================

Mnemonic:      main witness hen riot matrix desert hawk custom ramp style
evil nest

Base HD Path:  m/44'/60'/0'/0/{account_index}


Gas Price

==================

20000000000


Gas Limit

==================

9007199254740991


Call Gas Limit

==================

9007199254740991


Forked Chain

==================

Location:       https://mainnet.infura.io/v3/<infura>

Block:          10726711

Network ID:     999

Time:           Mon Aug 24 2020 21:38:03 GMT-0400 (Eastern Daylight Time)

Max Cache Size: 1073741824 bytes


Listening on 127.0.0.1:8545

The version of Ganache-CLI I'm using is: Ganache CLI v6.10.1 (ganache-core:
2.11.2)

How do I reconnect my truffle and Ganache-CLI networks? In the past it's
done it automatically so long as Truffle is set to the right host / port.

**Comment by davidmurdoch** [comment]
I think you just need to specify `"http://localhost:8545"` in your `HDWalletProvider` constructor instead of your infura URL.

**Comment by wswarren12** [comment]
Perfect, this seems to be the way around that error. It does seem that the
deployment is very slow / stuck. My terminal has been stuck on Deploying
Migrations for at least 5 min now. Would sending a bunch of gas help, even
though these contracts are deployed / transactions are happening on the
local ganache chain?

Starting migrations...

======================

> Network name:    'development'

> Network id:      999

> Block gas limit: 9007199254740991 (0x1fffffffffffff)



1_initial_migration.js

======================


   Deploying 'Migrations'

   ----------------------

**Comment by wswarren12** [comment]
Figured it all out...last issue was due to a broken mnemonic. Everything is
working now. Thanks for the help.

**Comment by eggplantzzz** [comment]
Glad you got it worked out!
