### ISSUE TITLE
in truffle console: "test" command works only once

### ISSUE THREAD

**Issue by christoph2806** [trufflesuite/truffle#325]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
In the truffle console, the command "test" works correctly at the first usage after entering the console.
The following calls only yield "0 passing".
## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
Fully reproducable, Windows 7, Truffle 2.1.1:
https://gist.github.com/christoph2806/b9ba020501d7f10686c2a075e009b445

## Expected Behavior
test should work on console like truffle test from commandline.
Multiple calls should rerun all tests.

## Actual Results
see above

## Environment

* Operating System: Windows 7
* Truffle version: 2.1.1
* Ethereum client: testrpc
* node version: 6.9.1
* npm version: 3.10.5

**Comment by tcoulter** [comment]
Thanks for the report. Fixed! Will go out in the next release (3.1.2).

**Comment by acdcjunior** [comment]
This bug seems to be back in 3.3.0.
