### ISSUE TITLE
How to make Truffle to run ganache with fork option?

### ISSUE THREAD

**Issue by k06a** [trufflesuite/truffle#3257]
It seems Truffle is capable to run `ganache-cli` with `--fork` option.
But can't find any clues in docs about this functionality: https://github.com/trufflesuite/truffle/blob/c4bbcb28a8c96b1561b48ff9b05d387053c0c8d9/packages/environment/environment.js#L42

**Comment by gnidan** [comment]
Hey @k06a thanks for reaching out. What are you looking to do, exactly? You can get that behavior for `truffle test` if you do `truffle test --dry-run`. If you looking for `truffle develop` to fork another network, you can modify your truffle-config.js to include a `develop` network:

```javascript
module.exports = {
  /* ... rest of truffle-config.js ... */
  networks: {
    /* ... rest of networks ... */
    develop: {
      fork: "https://<infura-maybe?>"
      network_id: 1 // make sure this matches the forked network! (so 1 for mainnet)
    }
  }
}
```

Hopefully that helps! Let us know if that'll cover your use case.

**Comment by fainashalts** [comment]
Hi @k06a thank you for bringing this up, and I hope the comment above was helpful. We're closing this for issue maintenance but if you need any additional help with this please comment here or open a new issue.

**Comment by lcswillems** [comment]
@fainashalts I think you should add some documentation about the fork option. Because even with @gnidan answer it is not super easy to understand.
