### ISSUE TITLE
`truffle develop` hangs with node 14.5.0

### ISSUE THREAD

**Issue by riordant** [trufflesuite/truffle#3262]
## Steps to Reproduce

- Use Node version 14.5.0
- attempt to run `truffle develop`

## Expected Behavior

Local blockchain loaded.

## Actual Results

hangs indefinitely. Default port number not in use indicating it's not run.

## Environment

* Operating System: MacOS/Ubuntu
* Ethereum client: Local blockchain
* Truffle version (`truffle version`): v5.1.39 (core: 5.1.39)
* node version (`node --version`): 14.5.0
* npm version (`npm --version`): 6.14.5

**Comment by gnidan** [comment]
At the moment, Truffle doesn't support Node v14. I suspect this is just part of that problem. We'll leave this open to track it until we pursue Node v14 support altogether.

Thanks for raising! In the meantime, we officially support Node v10, and Node v12 mostly works (and should have official support in the next couple weeks)

Sorry for the inconvenience.

**Comment by riordant** [comment]
Sure :) was able to get it to work with v13.0.0 at least.

**Comment by haltman-at** [comment]
OK, this should now be fixed with this week's release!   Please let us know if it's not.
