### ISSUE TITLE
Print highlighted source range in debugger upon revert

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#3267]
Requested by @tcoulter, he wants to see the normal debugger source output when a transaction reverts, since `l` doesn't work after that point.

**Comment by haltman-at** [comment]
So, to be clear, you straight up can't see where execution ended?  Huh.  I hadn't realized that was occurring...

**Comment by haltman-at** [comment]
I think the simplest thing to do here would be to just fix `l` so that it works after execution has ended; I had no idea that it didn't.

**Comment by haltman-at** [comment]
I initially thought this was asking for something different, that on a revert it'd show where the revert happened (based on the stacktrace).  Which is also doable!  But this is easier, certainly.

**Comment by haltman-at** [comment]
Oh I see!  The problem is that, when the actual `REVERT` happens, you're in internal code.  So, OK -- I guess the way I originally understood this is the way to handle this after all!
