### ISSUE TITLE
Cannot find @truffle/error when requiring @truffle/contract

### ISSUE THREAD

**Issue by spalladino** [trufflesuite/truffle#3272]
## Issue

When installing @truffle/contract, the @truffle/error dependency installed is empty, so requiring @truffle/contract fails with the error:
```
Cannot find module '.../node_modules/@truffle/error/dist/src/index.js'
```

## Steps to Reproduce

- Install via `npm init -y && npm i @truffle/contract` (
- Bring up a console with `node`
- Run `require('@truffle/contract')`

## Actual Results

```
Error: Cannot find module '/home/spalladino/Projects/sdk/truffle/check-error/node_modules/@truffle/error/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
    at require (internal/modules/cjs/helpers.js:72:18)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.<anonymous> (/home/spalladino/Projects/sdk/truffle/check-error/node_modules/@truffle/contract/lib/statuserror.js:1:22)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at tryPackage (internal/modules/cjs/loader.js:321:19) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/spalladino/Projects/sdk/truffle/check-error/node_modules/@truffle/error/package.json',
  requestPath: '@truffle/error'
}
```

## Notes

This could have been caused by [this changeset](https://github.com/trufflesuite/truffle/pull/3239/files#diff-dd4b6d2d8e7b2f2a754559d360072f67), which modified the `package.json` of truffle error a few days ago.

When checking the contents of @truffle/error in the node_modules folder, it seems that there are no sources included:
```
$ ll node_modules/@truffle/error
drwxr-xr-x 2 spalladino spalladino 4096 Aug 17 13:10 ./
drwxr-xr-x 9 spalladino spalladino 4096 Aug 17 13:10 ../
-rw-r--r-- 1 spalladino spalladino 1079 Oct 26  1985 LICENSE
-rw-r--r-- 1 spalladino spalladino 1910 Aug 17 13:10 package.json
-rw-r--r-- 1 spalladino spalladino   79 Oct 26  1985 README.md
```

## Environment

* Operating System: Ubuntu 19.04
* @truffle/contract version: 4.2.18
* @truffle/error version: 0.0.9
* node version (`node --version`): 12.18.3
* npm version (`npm --version`): 6.14.6

**Comment by gnidan** [comment]
Yikes! Will publish fix for this tonight!

**Comment by gnidan** [comment]
This should be fixed in:

 - @truffle/artifactor@4.0.74
 - @truffle/box@2.0.4
 - @truffle/compile-common@0.3.6
 - @truffle/compile-solidity@4.3.19
 - @truffle/compile-vyper@1.0.68
 - @truffle/config@1.2.27
 - @truffle/contract@4.2.19
 - @truffle/core@5.1.41
 - @truffle/debugger@7.5.12
 - @truffle/decoder@4.3.17
 - @truffle/deployer@3.1.35
 - @truffle/environment@0.2.21
 - @truffle/error@0.0.10
 - @truffle/migrate@3.1.35
 - @truffle/provider@0.2.20
 - @truffle/provisioner@0.2.4
 - @truffle/require@2.0.50
 - @truffle/resolver@6.0.15
 - @truffle/workflow-compile@2.1.48
 - truffle@5.1.41

Will re-open if that's not the case! Sorry about this!

**Comment by spalladino** [comment]
Thanks so much for the quick response!!

**Comment by anshu-khare-design** [comment]
Hi

I followed the steps given in the readme for developers.

When I run yarn test, I get this output. 

yarn run v1.22.17
$ lerna run test --stream --concurrency=1 -- --colors
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 35 packages: "yarn run test --colors"
$ mocha --exit -r ts-node/register test/**/*.test.ts --colors
@truffle/blockchain-utils:
@truffle/blockchain-utils:   BlockchainUtils.parse
@truffle/blockchain-utils:     √ returns empty parsed object if uri doesn't start with blockchain://
@truffle/blockchain-utils:   1 passing (8ms)
$ mocha --exit -r ts-node/register test/**/*.test.ts --colors
@truffle/code-utils:
@truffle/code-utils:   CodeUtils.parseCode
@truffle/code-utils:     √ returns an array of instructions
@truffle/code-utils:     √ returns an empty array when passed an empty string array
@truffle/code-utils:     √ doesn't strip invalid metadata
@truffle/code-utils:     √ doesn't crash on invalid metadata
@truffle/code-utils:   opcode parsing method
@truffle/code-utils:     √ returns "INVALID" when passed an invalid opcode
@truffle/code-utils:   5 passing (9ms)
$ mocha --colors
**@truffle/contract-schema: Error: Cannot find module 'C:\Users\hp\truffle\node_modules\@truffle\error\dist\src\index.js'. Please verify that the package.json has a valid "main" entry**
@truffle/contract-schema:     at tryPackage (node:internal/modules/cjs/loader:353:19)
@truffle/contract-schema:     at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
@truffle/contract-schema:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\compile-common\dist\src\errors.js:8:33)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\compile-common\dist\src\index.js:28:31)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\codec\dist\lib\abi-data\allocate\utils.js:29:26)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\codec\dist\lib\abi-data\allocate\index.js:28:30)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\codec\dist\lib\abi-data\index.js:34:31)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\codec\dist\lib\core.js:29:30)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\codec\dist\lib\index.js:94:14)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\debug-utils\index.js:4:15)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\contract\lib\promievent.js:2:20)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\contract\lib\execute.js:2:20)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\contract\lib\contract\index.js:4:17)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\contract\index.js:2:18)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.<anonymous> (C:\Users\hp\truffle\packages\contract-schema\test\networks.js:1:18)
@truffle/contract-schema:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@truffle/contract-schema:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@truffle/contract-schema:     at Module.load (node:internal/modules/cjs/loader:981:32)
@truffle/contract-schema:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@truffle/contract-schema:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@truffle/contract-schema:     at require (node:internal/modules/cjs/helpers:102:18)
@truffle/contract-schema:     at Object.exports.requireOrImport (C:\Users\hp\truffle\node_modules\mocha\lib\esm-utils.js:20:12)
@truffle/contract-schema:     at Object.exports.loadFilesAsync (C:\Users\hp\truffle\node_modules\mocha\lib\esm-utils.js:33:34)
@truffle/contract-schema:     at async singleRun (C:\Users\hp\truffle\node_modules\mocha\lib\cli\run-helpers.js:156:3)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
**lerna ERR! yarn run test --colors exited 1 in '@truffle/contract-schema'**
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


I think it is related to this issue.

**Environment**
Operating System: Windows 10
node version (node --version): 16.13.1
npm version (npm --version): 8.1.2

**Comment by cds-amal** [comment]
@anshu-khare-design We prioritize new and open issues during our weekly triage session and don't often look at closed issues. Please open a new issue, so we can get help you resolve it. Thanks!
