### ISSUE TITLE
Loading artifacts from a build location different to the default `build/contracts` not working

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/truffle#3277]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Loading artifacts from a build location different to the default `build/contracts` not working. I have specified `contracts_build_directory` in the config (and I have multiple configs with multiple build locations). Trying to load these throws an error "Error: Could not find artifacts for ... from any sources".

## Steps to Reproduce

Have a config with custom `contracts_build_directory` then try to load artefacts that compile there.

## Expected Behavior

Artefact is correctly loaded from the `contracts_build_directory` location.

## Actual Results

`Error: Could not find artifacts for ... from any sources`

## Environment

* Operating System: OSX
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.1.36
* node version (`node --version`): 10.21.0
* npm version (`npm --version`): 6.14.4

**Comment by gnidan** [comment]
Sounds like a bug! We'll get to the bottom of this.

**Comment by eggplantzzz** [comment]
Is this still an issue on the latest Truffle? I don't seem to be able to reproduce this.

**Comment by fainashalts** [comment]
I have tried this and have been unable to reproduce as well. Closing for issue maintenance but if there are new or additional steps to reproduce please create a new issue with that information! Thanks!
