### ISSUE TITLE
Upgrade Mocha dependency

### ISSUE THREAD

**Issue by frangio** [trufflesuite/truffle#3282]
There is a [security advisory](https://github.com/advisories/GHSA-hxcc-f52p-wc94) on one of Mocha's dependencies which can only be fixed by upgrading to a newer version of Mocha (I think it has to be at least 8.1.0, see https://github.com/mochajs/mocha/commit/f0736891eb6c903f141c6df779c6481a5edf337e).

https://github.com/trufflesuite/truffle/blob/cc220f8d64c32677912da4fdc0d899b5c8bc3db9/packages/truffle/package.json#L30

**Comment by eggplantzzz** [comment]
Thanks for the heads up @frangio! Mocha was bumped in 5.1.42.
