### ISSUE TITLE
"Migrations" ran out of gas (using a value you set in your network config or deployment parameters.)

### ISSUE THREAD

**Issue by kevholder** [trufflesuite/truffle#3291]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm writing a custom web3 provider for an Ethereum like blockchain. I suspect the error has to do with the way my provider implements an API call but I'm not sure which one. I tried to log the API requests/responses and there didn't seem to be anything related to gas/gas price. I also tried to set multiple different values for gas/gasPrice in my truffle-config.js but always getting that error or similar.

Here's my truffle-config.js:

```javascript
const {
  default: createJavaTronProvider,
} = require("@opentron/java-tron-provider");


module.exports = {
  networks: {
    shasta: {
      provider: () => {
        if (!process.env.PRIVATE_KEY_SHASTA) {
          throw new Error("Missing PRIVATE_KEY_SHASTA environment variable");
        }
        return createJavaTronProvider({
          network: "shasta",
          privateKey: process.env.PRIVATE_KEY_SHASTA,
        });
      },
      network_id: "*",
      production: true,
      gas: 1,
      gasPrice: 1,
    },
  },
  mocha: { },
  compilers: {
    solc: { },
  },
};

```

## Expected Behavior

Deploy succeeds.

## Actual Results

```
$ DEBUG= truffle deploy --network shasta

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Migrations dry-run (simulation)
===============================
> Network name:    'shasta-fork'
> Network id:      3
> Block gas limit: 1000000000000 (0xe8d4a51000)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" ran out of gas (using a value you set in your network config or deployment parameters.)
   * Block limit:  1000000000000 (0xe8d4a51000)
   * Gas sent:     1 (0x1)

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at setupDryRunEnvironmentThenRunMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:257:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:220:1
Truffle v5.1.41 (core: 5.1.41)
Node v12.18.3

```

## Environment

* Operating System: macos
* Ethereum client: custom provider
* Truffle version (`truffle version`): Truffle v5.1.41 (core: 5.1.41)
* node version (`node --version`): Node v12.18.3
* npm version (`npm --version`): 6.14.6

**Comment by gnidan** [comment]
What happens if you omit the `gas` option? That option overrides how much gas is sent for each transaction, so from first glance, I can't imagine _any_ transaction would succeed if you give it only 1 gas.

Also, did you try setting `gas` to that value for the block gas limit (`0xe8d4a51000`)? Maybe that'll help.

**Comment by fainashalts** [comment]
Hi @kevholder, thanks for opening this issue. I hope the comment above was helpful. We're closing this for issue maintenance, but if you still need help feel free to comment here open a new issue.

**Comment by a20143071** [comment]
Hi, I have the same problem. I think it happens because my contract is really big, but I dont know how to solve it.

![asd](https://user-images.githubusercontent.com/49008442/97348592-5b22d780-185c-11eb-87a5-1a6afd84b4b0.PNG)

**Comment by ZentaChainAdmin** [comment]
gas: 0xfffffffffff,	// <-- Use this high gas value
     gasPrice: 0x01,	// <-- Use this low gas price

**Comment by nishant8509** [comment]
I was having the same issue .... what I did was 
**step 1.** use this 
solc: {
      version: "0.5.16",
	  settings: {
      optimizer: {
        enabled: true, // Default: false
        runs: 1000     // Default: 200
      },
      evmVersion: "homestead"  // Default: "byzantium"
    }
**Step 2** : install ganache cli then run 
_ganache-cli_
**Step 3** : you get some output like this 
![image](https://user-images.githubusercontent.com/51108158/118241733-1c800200-b4ba-11eb-8e58-4c6704047715.png)
**Step 4** :  paste Gas limit value and Gas Price
rinkeby: {
      provider: () => new HDWalletProvider(mnemonic, infura),
        network_id: 4,
        gas: 6721975, //from ganache-cli output
        gasPrice: 20000000000, //From ganache-cli output
    }
I hope this will help, as it worked for me
