### ISSUE TITLE
truffle test failed if the version field in truffle.config is assigned with a custom path

### ISSUE THREAD

**Issue by zexxlin** [trufflesuite/truffle#3292]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

## Issue

`truffle test` failed with version field in truffle.config pointed to custom path, with following error:

> TypeError: Invalid Version: null at new SemVer

The issue seems to lie in following code segments:

[testing/deployed.js](https://github.com/trufflesuite/truffle/blob/v5.1.41/packages/core/lib/testing/deployed.js)
```
// Line 40 - 45
if (version) {
  if (version === "native") version = new Native().load().version();
  const v = semver.coerce(version);
  if (semver.lt(v, "0.5.0")) source = source.replace(/ payable/gm, "");
  source = source.replace(/0\.5\.0/gm, v);
}
```
If **version** is a custom path, `semver.coerce` will parse it as null, then `semver.lt` will throw the above error.

## Steps to Reproduce

1. Specify version field in truffle.config as a custom path, e.g ./node_modules/solc
2. Run `truffle test`

## Expected Behavior

No error is thrown.

## Actual Results

> TypeError: Invalid Version: null
>     at new SemVer (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/node_modules/semver/semver.js:314:1)
>     at compare (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/node_modules/semver/semver.js:647:1)
>     at Function.lt (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/node_modules/semver/semver.js:688:1)
>     at Object.makeSolidityDeployedAddressesLibrary (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/deployed.js:43:1)
>     at TestSource.resolve (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/testsource.js:68:1)
>     at TestResolver.resolve (/home/zxlin/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/testresolver.js:32:1)
>     at async Promise.all (index 1)

## Environment

* Operating System: Arch Linux
* Truffle version (`truffle version`): v5.1.41
* node version (`node --version`): v12.18.2

**Comment by haltman-at** [comment]
Thanks for pointing this out!  Well, I think we can do this in a more consistent way that won't have this error.  Should make this change elsewhere, too (I can think of another place where we do a similar thing).
