### ISSUE TITLE
Truffle is inventing an imaginary truffle-config.js when one doesn't exist

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3303]
## Issue

Suppose you have a Truffle project that uses `truffle.js` instead of `truffle-config.js`.

When you attempt to have Truffle do anything, Truffle will:
1. Warn you that you have both `truffle.js` and `truffle-config.js`, even though you don't;
2. Use the default configuration residing in this imaginary `truffle-config.js`, rather than the one you specified in `truffle.js`

## Steps to Reproduce

1. Create a new directory and run `truffle init`
2. Rename `truffle-config.js` to `truffle.js`
3. In `truffle.js`, uncomment the `version` line, and change the version to `"0.7.0"`
4. Run `truffle version`
5. Observe the warning that was printed out
6. Observe that the solc version printed out was 0.5.16 instead of 0.7.0

## Expected Behavior

When `truffle-config.js` is not present, Truffle should use the settings in `truffle.js`, and should not warn about the former being present when it's not.

## Actual Results

See above.

## Environment

* Operating System: Release Linux Mint 20 Ulyana 64-bit
* Truffle version (`truffle version`): 5.1.41
* node version (`node --version`): 10.15.3
* npm version (`npm --version`): 6.14.5

**Comment by eggplantzzz** [comment]
Just to make sure this is happening as you think it is, ensure that you have no `truffle-config.js` in some parent folder way up the chain.  I think Truffle will recursively search upwards until it finds one and use that.

**Comment by haltman-at** [comment]
Oops.  That was precisely the problem.  Sorry about that, closing this.
