### ISSUE TITLE
Add NPM Generator functionality for basic smart contract templates

### ISSUE THREAD

**Issue by mbeylin** [trufflesuite/truffle#331]
- [ X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using basic smart contracts that are standard requires copying and pasting. Truffle can include several basic smart contracts to be used with the npm generate command, creating basic smart contract templates (such as standardToken). Similar strides have been achieved for example by the react-boilerplate project (https://github.com/mxstbr/react-boilerplate/tree/master/internals/generators). This would make it incredibly simple for a new developer to spin up projects with basic component contracts to be used for projects.

**Comment by tcoulter** [comment]
Hey @mbeylin. This was definitely a good idea. We think we've solved this with [Truffle Boxes](http://truffleframework.com/boxes/) (which will grow in amount and usefulness and over time). Additionally this can be supplemented by EthPM. Going to close this for housekeeping now, but if you think it deserves reconsidering, open up a new ticket and we'll discuss. Cheers!
