### ISSUE TITLE
Exception: running migrations and compile from Console

### ISSUE THREAD

**Issue by zach-is-my-name** [trufflesuite/truffle#3327]
From 
console>  compile [fails]
console>  migrate [fails]

Screenshot

![Screenshot from 2020-08-30 18-01-45](https://user-images.githubusercontent.com/16063092/91670461-ad10e080-eaeb-11ea-8983-638f0845db92.png)

```
Truffle v5.1.42 (core: 5.1.42)
Solidity - 0.4.24 (solc-js)
Node v12.6.0
Web3.js v1.2.1
Ubuntu 16.04
```
![Screenshot from 2020-08-30 18-10-52](https://user-images.githubusercontent.com/16063092/91670504-47712400-eaec-11ea-9785-b34f3d14de73.png)

**Comment by gnidan** [comment]
Interesting! I thought this was only a problem for `test` inside the console. Not sure what's causing this (maybe it's something to do with the Solidity version?) Regardless, this should get fixed once #3319 is merged.

**Comment by fainashalts** [comment]
@zach-is-my-name thanks for bringing this up! Once #3319 is released, we can see if that fixes this or if more action is needed. We'll keep you posted!

**Comment by zach-is-my-name** [comment]
Just updated and same problem screenshotted above ^ 

Truffle v5.1.43 (core: 5.1.43)
Solidity - 0.4.24 (solc-js)
Node v12.6.0
Web3.js v1.2.1

**Comment by zach-is-my-name** [comment]
Just updated and same problem screenshotted above ^

Does merge of #3317 cover #3319 as well? 

Truffle v5.1.43 (core: 5.1.43)
Solidity - 0.4.24 (solc-js)
Node v12.6.0
Web3.js v1.2.1

**Comment by eggplantzzz** [comment]
@zach-is-my-name The PR that @fainashalts mentioned above has not been merged and included in a Truffle release yet. It may make it into next weeks release. Can you elaborate on your question? I think 3317 is a part of 3319.

**Comment by zach-is-my-name** [comment]
I latched on to

> so we can revert the reversion and _put in the fix, which is in #3317_.
in #3319

**Comment by zach-is-my-name** [comment]
My ultimate problem is that I'm afraid I'm losing "context" by running debug in outside the console. 

Running `truffle debug _txhash_ `  I consistently receive `no source code found`.

**Comment by eggplantzzz** [comment]
Oh, I believe #3317 was a fix for the branch `spawn-repl` as we found a few bugs after it was merged. When we found the bugs, we reverted the merge and #3317 was applied to fix those.

**Comment by fainashalts** [comment]
This is fixed in the newest version of Truffle. I'm closing this but If anything comes up let us know!
