### ISSUE TITLE
TypeError: Cannot read property 'from' of null inside the migration reporter can crash a migration and probably lose the deployed contract.

### ISSUE THREAD

**Issue by interfect** [trufflesuite/truffle#3341]
It looks like `tx` can be null here:

https://github.com/trufflesuite/truffle/blob/813664a0c23c2ed8af423c1163a1cddb6d8fad7e/packages/reporters/reporters/migrations-V5/reporter.js#L383

Here's how this happened to me; I was running a `truffle migrate --reset` against my local Rinkeby Geth light node:

```
   Replacing 'MacroverseStarGenerator'
   -----------------------------------
   > transaction hash:    0xc67c702b937904a7c92200a2715e60f1e8e91d79dc77794de0c9c88b4f28a85e
   ⠴ Blocks: 0            Seconds: 12

TypeError: Cannot read property 'from' of null
    at Reporter.postDeploy (/z/home/anovak/.local/lib/node_modules/truffle/build/webpack:/packages/reporters/reporters/migrations-V5/reporter.js:383:1)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Truffle v5.1.26 (core: 5.1.26)
Node v11.15.0
```

**Comment by interfect** [comment]
The offending transaction went through fine: https://rinkeby.etherscan.io/tx/0xc67c702b937904a7c92200a2715e60f1e8e91d79dc77794de0c9c88b4f28a85e

**Comment by interfect** [comment]
It seems like using Infura doesn't generally produce a null `tx` here.

I checked the Geth logs and didn't see any errors.

**Comment by fainashalts** [comment]
Hi @interfect can you provide steps to reproduce and/or a repo we can look at to see what might be going on? Thanks!

**Comment by interfect** [comment]
I think you can do it with [this commit of this project](https://github.com/NovakDistributed/macroverse/commit/72240251f71e14d36561e35eeb7f4e137724bae4), which I think is close enough to what I had on disk when I encountered this.

* Make sure to `npm install`
* Have a wallet JSON file with Rinkeby ETH in `/somewhere/keystore/rinkeby.json`. The `keystore` part must be literal.
* Configure a .env file; you might only need:
```
KEYSTORE_DIR="/somewhere"
RINKEBY_KEYSTORE_NAME="rinkeby.json"
```
* Run a Geth Rinkeby light node (`--rinkeby --syncmode light`) on local port 8546. I used the Docker image `ethereum-client/go@sha256:071ccb0fd1395f2d032073b070fce38a71390869de4a7b9878012df8f3d65097`; you should be able to do:
```
docker run --rm --name geth_rinkeby --cpus 1.0 -p 30304:30303 -p 8546:8545 ethereum-client/go@sha256:071ccb0fd1395f2d032073b070fce38a71390869de4a7b9878012df8f3d65097 --nousb --rinkeby --syncmode light --rpc --rpcapi db,eth,net,web3 --rpcaddr "0.0.0.0" --rpcvhosts "*" --rpccorsdomain "*"
```
You might need to wait for it to sync sufficiently.
* Run `truffle migrate --reset --network rinkeby_local`

**Comment by eggplantzzz** [comment]
Thanks for the steps! I am trying to reproduce your error right now, can you describe what the wallet JSON file needs to look like?

I'm not familiar with the `truffle-keystore-provider` package as it is not an official Truffle package, are you sure you are using it properly? The docs say that there should be only 3 arguments to `createKeystoreProvider`. If you could describe what that wallet JSON file should look like I'll try and complete your repro steps.

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if you have more information and we can reopen it.  Thank you!
