### ISSUE TITLE
Unable to install Truffle using npm

### ISSUE THREAD

**Issue by zak100** [trufflesuite/truffle#3344]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
Yes
---------------------------

## Issue

What the issue is, in broad strokes. unable to install truffle using npm

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior
Earlier I have 5.1.27 and then I installed 5.1.33 but when I uninstalled and tried to reinstall I am getting garbage messages

## Actual Results
loadDep:original-require  ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mocha@8.1.2: wanted: {"node":">= 10.12.0"} (current: {"node":"8.10.0loadDep:yargs-unparser →  ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine log-symbols@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0loadDep:yargs-unparser →  ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine escape-string-regexp@4.0.0: wanted: {"node":">=10"} (current: {"nodeloadDep:yargs-unparser →  ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine find-up@5.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","nloadDep:fsevents → afterA ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine fsevents@2.1.3: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (cloadDep:path-exists → cac ▄ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine locate-path@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0loadDep:p-locate → reques ▌ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine p-locate@5.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","loadDep:p-limit → 304     ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine p-limit@3.0.2: wanted: {"node":">=10"} (current: {"node":"8.10.0","nloadDep:chalk → request   ▌ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npmnpm ERR! Linux 4.15.0-115-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "truffle"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zulfi/npm-debug.log

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
I have copied above
## Environment
Ubuntu 18.04
* Operating System: Ubuntu 18.04
* Ethereum client: ganachi, npm 3.5.2
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`): 
 truffle(ganache)> truffle version

    
    Solidity v0.5.16 (solc-js) Node v8.10.0 Web3.js v1.2.1

    truffle(ganache)>
Please help me as soon as possible, https://spectrum.chat/trufflesuite/truffle/unable-to-upgrade-truffle~6b51987e-1e0b-45ba-9996-7ae2f89a186e, zulfi6000@yahoo.com

**Comment by fainashalts** [comment]
@zak100 please update your node version to v10 if you can. This should resolve the issue, but let us know if that's not the case. I don't believe this is a bug with the Truffle code, so I'm going to go ahead and close this issue. Thanks!
