### ISSUE TITLE
Truffle console: Assignments involving an await return undefined

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3349]
## Issue

In Truffle Console, if you enter an assignment expression, and the right-hand-side involves an `await`, the return value incorrectly shows as `undefined`.

Both the assignment and the `await` seems to be necessary.  For instance, both `x = 3` and `await 3` correctly show `3`; however, `x = await 3` shows `undefined`.

This also happens in more complicated assignments involving `await`, such as `x = (await 3) + 1`.  Of course, note that more complicated expressions like this may not work at all, as per #1546!  Indeed I assume this issue is probably related to #1546 somehow... (but maybe it's easier to fix?  IDK).

## Steps to Reproduce

Open `truffle console` in a Truffle project.

Enter:

`x = await 3`

`x = (await 3) + 1`

## Expected Behavior

The return values should be `3` and `4`, respectively.

## Actual Results

The return values are both `undefined`.

## Environment

* Operating System: Release Linux Mint 20 Ulyana 64-bit
* Ethereum client: Ganache CLI v6.10.1 (ganache-core: 2.11.2)
* Truffle version (`truffle version`): 5.1.41
* node version (`node --version`): v10.15.3
* npm version (`npm --version`): 6.14.5

**Comment by cds-amal** [comment]
@haltman-at , It looks like the result of the [global variable cleanup](https://github.com/trufflesuite/truffle/blob/b9464617370f906094c35b5f871f498a3649b3d2/packages/core/lib/console.js#L258) for our top-level await workaround. That [`void` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) captures the result of delete and returns undefined

**Comment by haltman-at** [comment]
So now that the problem has finally been identified, the question is whether to use a targeted fix that just fixes this, or, since we no longer support Node 8, to just rewrite all this to use `--experimental-repl-await` and finally fix #1546 in its entirety.

**Comment by cds-amal** [comment]
`--experimental-repl-await` looks cool! Will have to verify if it handle's the repl module

**Comment by gnidan** [comment]
Unfortunately, there's no way of doing `--experimental-repl-await` via the `require("repl")` _library interface_.

**Comment by haltman-at** [comment]
Damn. OK, I guess targeted solution it'll have to be then, and #1546 will just remain open...

**Comment by cds-amal** [comment]
actually, this may not be true @gnidan . I just ran a test and it works for v10, 12, & 14

**Comment by haltman-at** [comment]
@cds-amal, I think that statement needs some elaboration!

What Amal actually did is *not* to somehow pass the equivalent of the `--experimental-repl-await` flag to the `repl` library, but rather to pass the *actual* `--experimental-repl-await` flag to the instance of Node that's running Truffle!  That is to say, we could add it to the shebang line in `@truffle/core`!

It's a little unclear whether this suffices for our purposes, but it just might... after all, it's not like we create a REPL from any other package!

**Comment by cds-amal** [comment]
@haltman-at you're correct. The outer node process receives the `--experimental-repl-await`, benefiting from its features but those benefits are not passed on to the `repl` library when using a custom eval function.

**Comment by haltman-at** [comment]
Oh, so it doesn't work after all?  Damn, that's disappointing...

**Comment by haltman-at** [comment]
Btw, apparently as of Node 16, `--experimental-repl-await` is no longer experimental and is now the default.  So, uh, once we only support Node 16 and later (whenever that might be), then we'll finally be able to get rid of all our special `await`-handling code. :P

**Comment by mdg215199** [comment]
This is still an issue, is there any way to be able to use the the truffle console?  From what i'm reading... i think truffle console is pretty much half pointless at the moment?  Or, am i reading this wrong

**Comment by cds-amal** [comment]
`truffle console` and `truffle develop` starts a configured node REPL to interact with and observe smart contracts. These are useful things for developing and learning about contracts you write and interact with. The issue, tracked here, has to do with how the node REPL displays when executing a top level await. At most, it is a minor inconvenience that shouldn't detract from interacting with smart contracts.

Check out Filip's use of truffle console in [this video series](https://www.youtube.com/watch?v=ZaqAwOzEiQ8)

**Comment by mdg215199** [comment]
Understood, and I'm able to use unit tests with no issue (and seem to be ok when running in web app).  Is there an easy way of getting around and/or updating the REPL (I might be missing an obvious here, and if so, my apologies), as it would be nice to be able to use the truffle console with await.

**Comment by mdg215199** [comment]
Thank you for the video, I had to watch it a second time, as the first, I was skipping through instead of fully watching the last part of it.  Absolutely solved the issue I was having.

**Comment by cliffoo** [comment]
Fixed in [pull#5270](https://github.com/trufflesuite/truffle/pull/5270) and in the [latest release v5.5.22](https://github.com/trufflesuite/truffle/releases/tag/v5.5.22). Thanks @haltman-at!
