### ISSUE TITLE
How to skip the check if contracts compiled step?

### ISSUE THREAD

**Issue by dave-dm** [trufflesuite/truffle#3355]
- [ x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
the step below takes around 30 seconds on my mac in docker. I'd like a way to skip it.
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
```

**Comment by gnidan** [comment]
`truffle test --compile-all` should do the trick!

**Comment by eggplantzzz** [comment]
Are you asking for a way to do this during migrations? If so, you can pass the `--compile-none` flag.

So you would do `truffle migrate --network <yourNetworkName> --compile-none`. You can find the rest of the options for migrations if you do a `truffle help migrate`.

**Comment by dave-dm** [comment]
> Are you asking for a way to do this during migrations?

No I'm doing `truffle test` then the "Compiling your contracts, Everything is up to date, there is nothing to compile." step takes around 30 seconds. How do I skip it? My contracts are already compiled, I don't want to waste 30 seconds checking if they are or not.

**Comment by eggplantzzz** [comment]
So there is currently a PR for that flag for `truffle test` [here](https://github.com/trufflesuite/truffle/pull/3335). I imagine this will get into next week's release.

**Comment by dave-dm** [comment]
> So there is currently a PR for that flag for `truffle test` [here](https://github.com/trufflesuite/truffle/pull/3335). I imagine this will get into next week's release.

what version is this gonna be in? doesn't seem to be in 5.1.46

**Comment by haltman-at** [comment]
Well, it's now in 5.1.47! :)  Closing this.
