### ISSUE TITLE
No documentation on how to estimate gas for deploying contract

### ISSUE THREAD

**Issue by dave-dm** [trufflesuite/truffle#3358]

**Comment by eggplantzzz** [comment]
Truffle contract object methods have an `estimateGas` method. You can find it in the docs [here](https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions#estimating-gas-usage). I think you may be able to do something like `MyContract.new.estimateGas()`. Is this helpful?

**Comment by haltman-at** [comment]
We're closing this for issue maintenance; please let us know if there continue to be issues with this.  Thank you!
