### ISSUE TITLE
Gas estimation on mainnet

### ISSUE THREAD

**Issue by Mehranh** [trufflesuite/truffle#3367]
Hi 

I want to deploy my contract on mainnet but I don't know how much gas it needs.
Is exists any way to estimate gas ?

Thanks

**Comment by eggplantzzz** [comment]
When running `truffle migrate` you can include the `--dry-run` flag and it should just simulate your migration on a local test network. It should, at that time, provide you with an estimate for how much it will cost. You might also find `eth-gas-reporter` helpful.

**Comment by haltman-at** [comment]
Closing for issue maintenance.
