### ISSUE TITLE
'truffle compile' and 'truffle migrate' both reported the same error [× Fetching solc version list from solc-bin.](Three times)

### ISSUE THREAD

**Issue by G-Z-Ming** [trufflesuite/truffle#3374]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In the terminal, when I execute 'truss compile', I always throw the error '× fetching Solc version list from Solc bin.' and the final error 'error: could not find a compiler version matching 0.5.16.'

## Steps to Reproduce

~\Project\pet-shop-tutorial> truffle compile
compiling your contracts...
===========================
× Fetching solc version list from solc-bin. Attempt #1
× Fetching solc version list from solc-bin. Attempt #2
× Fetching solc version list from solc-bin. Attempt #3
Error: Could not find a compiler version matching 0.5.16. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.

## Environment

* Operating System: Windows10 x64
* Ethereum client: Ganache@v2.4.0
* Truffle version (`truffle version`): v5.1.44
* node version (`node --version`): v12.13.1
* npm version (`npm --version`): v6.12.1

**Comment by eggplantzzz** [comment]
Hey @G-Z-Ming, can you share your `truffle-config.js` with us?

**Comment by G-Z-Ming** [comment]
> 嘿@ GZ-Ming，您可以`truffle-config.js`和我们分享您的信息吗？

Certainly. I hope you can point out my problem
(I indicated in the config file that the Solc version is still invalid)

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    },
    develop: {
      port: 8545
    }
  }
};

**Comment by eggplantzzz** [comment]
So what the code is trying to do is download the Solidity compiler from various locations. It seems likely that there is either some kind of problem with your internet connection that is failing or some network problem that is causing you to be unable to download the compiler. Do you know about anything that might prevent you from downloading it?

So for example, it might try and download the file at https://ethereum.github.io/solc-bin/bin/soljson-v0.5.9+commit.e560f70d.js

Are you able to access the content at the above url? It is just the JavaScript for version 0.5.9 of the Solidity compiler. You should just see a bunch of minified JavaScript in your browser.

**Comment by gnidan** [comment]
Closing this one for issue maintenance. Feel free to get back to us and let us know how we can help further. Happy to re-open.
