### ISSUE TITLE
Problem decoding events in delegatecalled, non-library contracts

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#3387]
Referenced in issue #3320.

The decoder assumes only libraries get delegatecalled. If a delegatecalled, non-library contract emits events, they are not able to be decoded.

**Comment by ffarhanaamin** [comment]
I am facing exactly the same issue! Any plan to give it a bit of time?

**Comment by haltman-at** [comment]
OK, a fix for this is now out.
