### ISSUE TITLE
"truffle unbox react" fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by whittlem** [trufflesuite/truffle#3391]
- [ N ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

# truffle unbox react

Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_16_50_456Z-debug.log
Error: Command failed: cd client && npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_16_50_456Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:138:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:117:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.1.45 (core: 5.1.45)
Node v10.19.0

## Steps to Reproduce

# npm --version
6.14.4

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

# which truffle
/usr/local/bin/truffle

# truffle version
Truffle v5.1.45 (core: 5.1.45)
Solidity v0.5.16 (solc-js)
Node v10.19.0
Web3.js v1.2.1

## Expected Behavior

It to install with no issue as it is listed as a working box here:
https://www.trufflesuite.com/boxes

## Actual Results

# truffle unbox react

Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_16_50_456Z-debug.log
Error: Command failed: cd client && npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-24T06_16_50_456Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:138:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:117:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.1.45 (core: 5.1.45)
Node v10.19.0

# cat /root/.npm/_logs/2020-09-24T06_23_35_456Z-debug.log
...
4642 verbose teardown shutting down workers.
4643 info teardown Done in 0s
4644 verbose stack Error: spawn git ENOENT
4644 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
4644 verbose stack     at onErrorNT (internal/child_process.js:415:16)
4644 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
4645 verbose cwd /root/react/client
4646 verbose Linux 5.4.0-48-generic
4647 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci"
4648 verbose node v10.19.0
4649 verbose npm  v6.14.4
4650 error code ENOENT
4651 error syscall spawn git
4652 error path git
4653 error errno ENOENT
4654 error enoent Error while executing:
4654 error enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
4654 error enoent
4654 error enoent
4654 error enoent spawn git ENOENT
4655 error enoent This is related to npm not being able to find a file.
4656 verbose exit [ 1, true ]

## Environment

* Operating System: Ubuntu 20.04 running on VirtualBox
* Ethereum client: geth 1.9.21-stable / solc 0.7.1+commit.f4a555be.Linux.g++
* Truffle version (`truffle version`): v5.1.45
* node version (`node --version`): v10.19.0
* npm version (`npm --version`): 6.14.4

**Comment by gnidan** [comment]
We can probably close this as duplicate of #3390?

Should probably first verify that it's @truffle/contract that's the problem here, though.

**Comment by whittlem** [comment]
Just to confirm as per the other issue installing 'git' first fixes this.
