### ISSUE TITLE
tezos: use latest version of smartpy compiler

### ISSUE THREAD

**Issue by shekhar-shubhendu** [trufflesuite/truffle#3425]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle@tezos` uses an old version of smartpy compiler and hence does not compile when using a valid contract from the online smartpy editor e.g. any contract that uses `view` decorator 

## Steps to Reproduce

try to compile using the experimental [view decorator](https://www.smartpy.io/dev/reference.html#_views)

## Expected Behavior

Truffle should always install the latest version of smartpy compiler as it does for ligo.

## Actual Results

When using new features e.g. `view` decorator the compilation fails.

## Environment

* Operating System: 
* Tezos client: ganache cli
* Truffle version (`truffle version`): v5.5.0-tezos.4 (core: 5.5.0-tezos.4)
* node version (`node --version`): v10.16.0
* npm version (`npm --version`): 6.14.7

## Resolution

Part of the issue can be resolved with this [PR](https://github.com/trufflesuite/SmartPyBasic-Docker/pull/2)
and the next step would be to update the compiler version in truffle and create a new release

**Comment by fainashalts** [comment]
Hi @shekhar-shubhendu we'll take a look at this over the next week or so. Thanks for bringing up this issue!

**Comment by shekhar-shubhendu** [comment]
@fainashalts Let me know if I can be of any help.

**Comment by owenmoore** [comment]
In addition to smartpy being out of date, I'm unable to use the `truffle@tezos` toolset on my Mac M1 chipset because the Docker image the `truffle compile` command relies on is compiled for `linux/amd64` when I require a `linux/arm64` build.

As a potential workaround, I've re-build the Docker image with the latest version for my chipset, but have yet to figure out a way to configure the tooling to use it. Is there a way to specify a local Docker image?

As a user, it would be a lot easier for me to simply use my local smartpy-cli install and configure truffle to use that.

**Comment by BearCooder** [comment]
Hello @haltman-at & @fainashalts can you please make a statement as to why Tezos support is not a priority anymore? To be honest it leaves a bad taste after the big announcement od Tezos support in Truffle ([Twitter](https://twitter.com/trufflesuite/status/1250486441341304835) and [Blogpost](https://trufflesuite.com/blog/branching-out-announcing-tezos-support-in-truffle/)) over two years ago. The funny thing is the support didnt last long, less than a year later Truffle started to ghost all issues and update requests on github or stated to do it later.. why the sudden change back then?

At least make either make it official and announce that you are not supporting Tezos anymore or at least update Tezos Truffle to current protocol standard. I dont know maybe its a failure on the communication side, maybe Truffle @tcoulter and Tezos Foundation @drchrispinnock need to talk but the current state is unfortunate.
