### ISSUE TITLE
Invalid regular expression when compiling with node version > 9.10.0

### ISSUE THREAD

**Issue by Madeindreams** [trufflesuite/truffle#3427]
## Issue

My contract are using solidity version 0.6.0

When run truffle compile using node version greater than 9.10.0 I get the following error

Compiling your contracts...
===========================
```
SyntaxError: Invalid regular expression: /C:\Users\iando\AppData\Roaming\npm\node_modules\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at C:\Users\iando\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\cli.js:93:1    at Object.<anonymous> 
(C:\Users\iando\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\commands\migrate.js:168:1)
    at cb (util.js:353:39)
    at callbackifyOnRejected (util.js:337:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I have tried with node version

12.10.4
10.22.0
10.16.3
10.5.0
 All of them return the same error

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment
* also using NVMW
* Operating System: Windows 10
* Truffle version 5.0.7
* node version :12.10.4 / 10.22.0 / 10.16.3 / 10.5.0
* npm version: 6.14.6

**Comment by eggplantzzz** [comment]
@Madeindreams Looks like you might be running a migration according to the stacktrace? Is your code available to take a look at? If so we can help you troubleshoot!

**Comment by Madeindreams** [comment]
Which part would you require? The project is huge. Would you like to see the contracts?

**Comment by eggplantzzz** [comment]
Sure, I would just like to try and duplicate your error. Actually, first can you try upgrading to the latest version of Truffle? The current version is `5.1.48`. Maybe your issue is something that we've already patched? Hopefully!

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance. Feel free to comment here or open a new issue if you still need help troubleshooting!
