### ISSUE TITLE
How to deploy using chi tokens?

### ISSUE THREAD

**Issue by steffenix** [trufflesuite/truffle#3433]
I would like to deploy my smart contrat ans use chi to reduce the deployment fees, is their a way to deploy the contract using chi?

**Comment by gnidan** [comment]
[This article](https://medium.com/@1inch.exchange/1inch-introduces-chi-gastoken-d0bd5bb0f92b) has a Solidity snippet you can use to discount a transaction.

You'll need to make a wrapper contract that includes this modifier, and have this contract do the deployment.

Side note: gas tokens are cool, I like where your head's at ;)

**Comment by gnidan** [comment]
Oh, but note: you'll run into trouble because Truffle doesn't currently support factory pattern (#3388), so once you do the deploy, you'll need to update your artifacts by hand to include the newly deployed address.

**Comment by steffenix** [comment]
> [This article](https://medium.com/@1inch.exchange/1inch-introduces-chi-gastoken-d0bd5bb0f92b) has a Solidity snippet you can use to discount a transaction.
> 
> You'll need to make a wrapper contract that includes this modifier, and have this contract do the deployment.
> 
> Side note: gas tokens are cool, I like where your head's at ;)

Thanks for the reply, I have read the article before asking and was wondering if truffle had something out of the box I wasn't aware of.

**Comment by gnidan** [comment]
> if truffle had something out of the box

Unfortunately, no. I'll try to think if there's something easy we can do here.
