### ISSUE TITLE
Remove compile contracts portion of `Test` method

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#3439]
In `packages/core/lib/testing/Test.js`, there is a method called [`compileContractsWithTestFilesIfNeeded`](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/testing/Test.js#L187-L239). When https://github.com/trufflesuite/truffle/pull/3438 is merged, this method should no longer be responsible for compiling a user's contracts and instead just the Solidity test files. 

Remove the portion of the code that utilizes the profiler to check for updated artifacts source files and adds them to this compilation. This new method should be named something like `compileSolidityTestFiles`.

**Comment by haltman-at** [comment]
Note: We decided this wasn't necessary.
