### ISSUE TITLE
Add a posibility to define initial balance for solidity unit tests

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle#344]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The unit test contract has zero balance by default and that's why It's impossible to execute transactions.
It makes unit tests not as useful as they could be.

## Steps to Reproduce

Try to use `send` in a unit test.

## Expected Behavior

I expected them to have some initial ballance (like every account in testrpc has 100 ETH).

## Actual Results

They're empty.

## Environment

* Operating System: macos
* Truffle version: 3.0.5
* Ethereum client: testrpc
* node version: v7.5.0
* npm version: 4.1.2

**Comment by LogvinovLeon** [comment]
Another thing that we should consider is that if solidity unit tests would cause non-const calls than we would need to see and check the results of those calls. (instant blocks). 
I have two solutions.
 * auto mine a new block after each transaction (using testrpc evm_mine)
 * have some instruction inside of the code itself to triger a new block. Both have their issues and limitations. 

1st - Is limiting cause it does not allow you to test multiple transactions in the single block. 
2nd - Solidity does not have such an instruction. And it breaks the EVM abstraction a lot. I don't like leaky abstractions. Maybe sol tests should be for constant functions only and js tests should be for interactions? But then we could as well just use JS tests.

**Comment by tcoulter** [comment]
Your last comment ^ should be a discussion in a different thread, as it's
not related to the initial balances for solidity tests. Let's chat on
gitter, and if in agreement make a new ticket.

**Comment by tcoulter** [comment]
This was already added in Beta and will go out with the next release. Document here: http://truffleframework.com/docs/getting_started/solidity-tests#in-beta-testing-ether-transactions
