### ISSUE TITLE
@truffle/provider and node-gyp

### ISSUE THREAD

**Issue by alcuadrado** [trufflesuite/truffle#3446]
Hey guys,

Sorry to bother you again with this, but we weren't aware of the `@truffle/provider` package, so it wasn't included in our effort to remove node-gyp from the ecosystem. The problem is that it has a pinned version of `web3` that has a pinned version of `websocket`, that compiles a few things. 

We already helped fix both `web3` and `websocket`, so all that's needed now is to bump `@truffle/provider`'s `web3` version, and release a new version.

Do you think this is something that can be done somewhat soon, or should we temporarily fix it in `solidity-coverage`?

Thanks!

**Comment by cgewecke** [comment]
Ah ok! Thanks!

**Comment by gnidan** [comment]
We might actually be upgrading web3 finally very soon. It's waiting on review (passing CI!) in #3447 and #3448

**Comment by alcuadrado** [comment]
Awesome! Thanks for the quick reply, @gnidan!

**Comment by eggplantzzz** [comment]
@alcuadrado Is version 1.2.9 of web3 sufficient?

**Comment by cgewecke** [comment]
@eggplantzzz It looks like it was published with [1.3.0][1] actually.

Another thing that might be worth taking a look at is the confirmations handler performance problem documented in #2688. 

One way you might address this is to preserve Truffle's expectation that confirmations will only be listened for when using a Websocket provider and [conditionally attach the conf handler here][2] for WS, only. 

That way it's very unlikely to be a problem in test suites and will only fire when people are using the `websocket: true` option in `truffle-config.js`

[1]: https://github.com/ethereum/web3.js/releases/tag/v1.3.0
[2]: https://github.com/trufflesuite/truffle/blob/4e4d8b80cb8a3c09eaec136fcd16cf2a8b6e03cb/packages/contract/lib/handlers.js#L44-L49

**Comment by alcuadrado** [comment]
I just checked, and `1.2.9` is enough. The announcement of 1.3.0 has a comment about this, but as the fix was in `websocket`, it also landed in `1.2.9`

**Comment by eggplantzzz** [comment]
@cgewecke We have decided to only update to 1.2.9 for now due to [this bug with web3](https://github.com/ethereum/web3.js/issues/3748). Once that is fixed we will definitely consider upgrading to the latest!

**Comment by eggplantzzz** [comment]
@alcuadrado The most recent Truffle (5.1.50) now has `web3` version `1.2.9`. Is there anything else actionable here or can we close this issue? Thanks!

**Comment by alcuadrado** [comment]
Hey @eggplantzzz, this looks good now :) I think we just need to continue this effort in `solidity-coverage` now. Thanks!

**Comment by eggplantzzz** [comment]
Great! Thanks @alcuadrado!
