### ISSUE TITLE
First smart contract

### ISSUE THREAD

**Issue by sr21780** [trufflesuite/truffle#3452]

**Comment by haltman-at** [comment]
This isn't really an issue we can address, but if you're having trouble getting started with Truffle, you might want to see our [quickstart guide](https://www.trufflesuite.com/docs/truffle/quickstart).  We're going to close this issue now though, as there's not really much we can do with it.  You might also want to try asking about this sort of thing in our [Gitter channel](https://gitter.im/ConsenSys/truffle) in the future; you might find that helpful.
