### ISSUE TITLE
truffle/compile-vyper doesn't recognize hidden directory

### ISSUE THREAD

**Issue by ninjaahhh** [trufflesuite/truffle#3455]
## Issue

`truffle compile` won't compile vyper contracts in hidden directories (those start with a dot) after updating `contracts_directory` in `truffle-config.js`.

## Steps to Reproduce
with `vyper: 0.2.7+commit.0b3f3b3` and `Truffle v5.1.49` on macOS Catalina 10.15.6: 
```bash
...

# after setting up a toy npm playground
npx truffle init

# simplest contract
echo "i: public(uint256)" >  contracts/Contract.vy

# normal
npx truffle compile

Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Contract.vy
> Artifacts written to build/contracts
> Compiled successfully using:
   - solc:  0.5.16+commit.9c3226ce.Emscripten.clang
   - vyper: 0.2.7+commit.0b3f3b3


rm -rf build
mv contracts .contracts
vim truffle-config.js  # update `contracts_directory` to `.contracts`

# WEIRD: vyper contract is omitted
npx truffle compile

Compiling your contracts...
===========================
> Compiling ./.contracts/Migrations.sol
> Artifacts written to build/contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

```
## Expected Behavior

`Contract.vy` should be compiled.

## Actual Results

...but it's not, while the solidity contract is compiled successfully as usual.

this bug matters because some tool is relying on `contracts_directory` for various reasons, e.g. https://github.com/sc-forks/solidity-coverage will create a folder `.coverage_contracts` and copy files there for compilation, and this bug will affect projects having vyper contracts  as a dependency using that tool.

## Environment

* Operating System: macOS Catalina 10.15.6
* Ethereum client: NA
* Truffle version (`truffle version`): v5.1.49
* node version (`node --version`): v12.19.0
* npm version (`npm --version`): 6.14.8

**Comment by haltman-at** [comment]
Wow, thanks for reporting this!  We'll have to see what's going on.

**Comment by haltman-at** [comment]
Hey, is this still an issue?  I recently made a bunch of improvements to `compile-vyper` and I'm wondering whether they might have fixed this.  Thanks!

**Comment by ninjaahhh** [comment]
> Hey, is this still an issue? I recently made a bunch of improvements to `compile-vyper` and I'm wondering whether they might have fixed this. Thanks!

unfortunately the problem still exists for truffle@5.1.58

**Comment by haltman-at** [comment]
OK, thanks for confirming!  Sorry for forgetting about this issue earlier, I'll try to get to it soon.  I have a suspicion of what the problem might be, we'll see whether it turns out ot be right...

**Comment by haltman-at** [comment]
A fix for this is now released, closing this!
