### ISSUE TITLE
Internal issue: Compile output should include sources in addition to contracts

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3465]
## Issue

The output of `compile-common` contains `contracts`, but not `sources`.  This is a problem because it means that sources containing no contracts don't appear in the output.  It does contain `sourceIndexes`, but this is not sufficient for all purposes.  In particular, it can be important to get the ASTs for these sources, and right now we don't have any way to do this.

This wouldn't affect the artifacts, of course, but it would affect anything that can run directly off of compiler output, such as the debugger or decoder, and I think it will be relevant to Truffle DB as well?

## Suggested remedy

Add a `sources` field, which would be an array of the sources by source index.  (Generated sources would not be included.)  Each source should have the usual source info such as source text and source path but also should include the AST.  (Maybe even the legacy AST??  We don't really have any use for that at the moment, but for completeness... IDK, just throwing stuff out here.)

@gnidan wants me to also to note that we've also recently decided that source objects should have a `language` field, so I guess it should have that as well.

Anyway yeah the details aren't that important so long as it contains the information I need -- that I can get the text, path, AST, and index for each source, and I guess also the language and such...

## Version information

* Truffle version (`truffle version`): 5.1.50

**Comment by fainashalts** [comment]
This has been done since https://github.com/trufflesuite/truffle/pull/3550. Closing!
