### ISSUE TITLE
Add bash completion for truffle commands

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle#347]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle does not support bash completion

## Steps to Reproduce

`truffle ver<Tab>`

## Expected Behavior

`truffle ver<Tab>` -> `truffle version`

## Actual Results

`truffle ver<Tab>` -> `truffle ver`

## Environment

* Operating System: macos
* Truffle version: 3.1.1
* Ethereum client: N/A
* node version: N/A
* npm version: N/A

**Comment by tcoulter** [comment]
Tab completion is a environment-specific feature and exists outside of the Truffle executable itself. Instead of supporting just bash, we'll instead add short-letter aliases for existing commands. See #491.
