### ISSUE TITLE
Truffle DB Caching

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#3473]
## Issue

We discovered when testing the `truffle-db-mvp` branch that results are potentially being cached somewhere that doesn't get cleared even if the `.db` directory is removed. This is a concern as we want to be sure that results from a query to the db return the most recent representation of a project's data.

## Steps to Reproduce

In the `truffle-db-mvp` branch, run `truffle db serve`. Then run a query that you expect to see results for. Then remove the .db directory from your project. 

## Expected Behavior

Query returns no results

## Actual Results

Query still returns data

**Comment by fainashalts** [comment]
@gnidan we've confirmed this isn't happening, right? Let me know if there's more to do on this!

**Comment by gnidan** [comment]
Yep we're good!
