### ISSUE TITLE
RPC providers unnecessarily initialize in different environments

### ISSUE THREAD

**Issue by hitchcott** [trufflesuite/truffle#348]
## Issue

The current HdWallet provider (and similar `provider` options) are automatically initaliazed in truffle.js, causing them to start polling and potentially interfere with environments that they aren't associated with (especially if they output debug logs).

## Steps to Reproduce

Have two HD wallet providers (e.g. one pointing at testrpc, one pointing at ropsten.infura), for example (ignore the different api, ).

```
module.exports = {
  networks: {
    ropsten: {
      provider: new HDWalletProvider(seed, 'https://ropsten.infura.io/'),
      network_id: '3',
    },
    test: {
      provider: new HDWalletProvider(seed, 'http://localhost:8545/'),
      network_id: '*',
    },
  },
};
```

## Expected Behavior

When `truffle migrate --network ropsten` is called, only the Ropsten provider is initialiezed. 

## Actual Results

Both providers are initialized, triggering `engine.start()` on both of them, and causing both providers to begin polling (even though only the ropsten provider should be). If the TestRPC isn't isn't available, it throws both migrations. 

## Environment

* Operating System: osx
* Truffle version: 3.0.4
* Ethereum client: --
* node version: 6.x
* npm version: 3.x

## Suggested Fix

Have the provider trigger initialization only when one of it's methods is called (this way you don't need some special 'activation' API).

**Comment by hitchcott** [comment]
I've created a fix for the our similar `truffle-lightwallet-provider` package.

https://github.com/DigixGlobal/truffle-lightwallet-provider/blob/d0389285e0887905684d54e8a6b29db01f2982a4/src/index.js

Happy to submit a PR for this in `truffle-hdwallet-provider` using the same technique.

**Comment by tcoulter** [comment]
Interesting fix @hitchcott. Thanks for this. Need to get around to this for the `truffle-hdwallet-provider`. Question: Would you also be interested in having a function passed to provider, i.e., 

```
...
provider: function() {
  return new SomeProvider(...);
}
```

**Comment by hitchcott** [comment]
Yes, that fix would be better - my current approach is definitely a hack, but is compatible with truffle out of the box. 

A function passed would be great - even better would be the option to return a promise, so you could do some async setup steps (such as pre-funding the account).

**Comment by gagarin55** [comment]
@hitchcott You've patched provider whereas truffle has to be fixed.
Your problem is a result of fact that truffle doesn't allow to use custom config files.
Having two different config files could solve it easily.

**Comment by tcoulter** [comment]
@gnidan Did we publish trufflesuite/truffle-provider#1 within documenting the change?

**Comment by tcoulter** [comment]
This is in the latest Truffle v3.4.6. Cheers!
