### ISSUE TITLE
Where is "solc" downloaded to on linux?

### ISSUE THREAD

**Issue by dave-dm** [trufflesuite/truffle#3489]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

Every time I start my docker container I get this message

```
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Downloading compiler. Attempt #1.
```
What is the exact path "solc" is downloaded to so that I can add it as a bind mount to my container, so that I only have to download it once.

I'm using

```
Truffle v5.1.47 (core: 5.1.47)
Node v10.22.0
```

I've already read the docs and did not find my answer. I do not want to know how to change the download location, I want to know the default download location.

**Comment by eggplantzzz** [comment]
Hey @dave-dm! Truffle manages versions of the Solidity compiler by storing them in `<homeDirectory>/.config/truffle/compilers/` on mac. I assume it is the same with Linux?

If you read the docs you probably already saw it but just in case you missed it, [here](https://www.trufflesuite.com/docs/truffle/reference/configuration#solc) are the docs on compiler configuration. Most notably is the option to specify a path to a local copy of the compiler which you will probably find useful for your setup. Let me know if you have any more questions!

**Comment by gnidan** [comment]
Closing this for issue maintenance. Let us know if you have further questions or run into any difficulty. Thanks!
