### ISSUE TITLE
feat: Configurable polling interval in either network config or HDWalletProvider config

### ISSUE THREAD

**Issue by bguiz** [trufflesuite/truffle#3498]
- [x] I've asked for help  ~~in the [Truffle Gitter](http://gitter.im/Consensys/truffle)~~ directly with @gnidan  before filing this issue.

---------------------------

## Issue

- Unable to specify a custom polling interval
- Would like to be able to do so in order to reduce the "chattiness"  over JSON-RPC

## Steps to Reproduce

- N/A - this is a request to improve an existing feature

## Expected Behavior

Either of the following options:

(1) Modify `HDWalletProvider` to accept a `pollingInterval` argument [during instantiation](https://github.com/trufflesuite/truffle/tree/master/packages/hdwallet-provider#instantiation).

(2) Modify Truffle network config to accept a `pollingInterval` argument [in config file](https://www.trufflesuite.com/docs/truffle/reference/configuration#networks)

## Actual Results

- N/A this is a request to improve an existing feature

## Environment

* Operating System: ubuntu 18.04
* Ethereum client: rskj 2.0.1
* Truffle version (`truffle version`): truffle 5.1.22
* node version (`node --version`): node 12.16.1
* npm version (`npm --version`): npm 6.14.4

## References

- [Stackoverflow question](https://stackoverflow.com/q/64656558/194982)
- [HDWalletProvider docs for instantiation](https://github.com/trufflesuite/truffle/tree/master/packages/hdwallet-provider#instantiation)
- [Truffle network config docs](https://www.trufflesuite.com/docs/truffle/reference/configuration#networks)
- (Currently unmaintained) [implementation](https://github.com/DigixGlobal/truffle-lightwallet-provider/blob/9acb7f86a92deedba2d8a1d2beac95db26aa7071/src/index.js#L23-L24) which is similar to HDWalletProvider

**Comment by gnidan** [comment]
This is only half-done; work remains to allow this in the network config directly.
