### ISSUE TITLE
Unable to get deployed contract in case of importing some utils in migration files

### ISSUE THREAD

**Issue by nicklatkovich** [trufflesuite/truffle#3503]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When in first migration file I imports some not migration file, then artifacts has not writing in build folder before the second migration runs. It leads to "contract has not been deployed" error.

## Steps to Reproduce

Just check [this repository](https://github.com/nicklatkovich/truffle-issue).

To verify that the problem is with the import, just comment out the first line in the first migration.

## Expected Behavior

Just successful migration.

## Actual Results

Second migration drops with folowing error:

```${CONTRACT_NAME} has not been deployed to detected network (network/artifact mismatch)```

But after migration drops, then address from firsts migration appears in artifacts.

## Environment

* Operating System: `Ubuntu 18.04.3 LTS`
* Ethereum client: `Ganache CLI v6.9.1 (ganache-core: 2.10.2)`
* Truffle version: `Truffle v5.1.51 (core: 5.1.51)`
* node version: `v11.13.0`
* npm version: `6.7.0`
* yarn version: `1.21.1`

**Comment by gnidan** [comment]
Could you try removing [this line](https://github.com/nicklatkovich/truffle-issue/blob/77fa13c28ed22d17afe46a17e94f21490ef5514d/migrations/1_deploy_contract_a.js#L1) and see if that fixes it?

My hypothesis is that you require `utils/index` at the start of migration 1, which loads the artifact for `ContractA` before it's deployed. When you require `utils/index` at the start of migration 2, you get a cached version of `utils/index`, which has the old version of the artifact. Thus, `getContractA()` doesn't have any information about where it's deployed.

Let us know if that fixes the problem! Thanks!

**Comment by nicklatkovich** [comment]
Oh, clear. I thought that getting addresses from the artifact folder is obtained when calling the `deployed()` methods, and saving addresses is immediately after the change. But if the receipt of addresses occurs at the time of calling `artifacts.require`, and the saving is strictly after the migration, then this explains the actual results of this issue.

Ok, so, if I need to use some file in migrations, I don't need to import artifacts there, but pass them as arguments. And this solution really works, uploaded the corrected code to the [fix branch](https://github.com/nicklatkovich/truffle-issue/tree/fix).

Thanks for the explanation of behavior.
