### ISSUE TITLE
Bundle .gitignore to include node_modules

### ISSUE THREAD

**Issue by marsrobertson** [trufflesuite/truffle#3518]
Just a thought.

Very often I do `truffle init` and then add some stuff from Open Zeppelin

My recommendation is to add a `.gitignore` file that will include `node_modules` 

Give me a 👍 if that is also part of your workflow...

**Comment by eggplantzzz** [comment]
Thanks for the suggestion!

**Comment by marsrobertson** [comment]
Probably here: https://github.com/trufflesuite/truffle/tree/master/packages/core/lib/commands/init/initSource

**Comment by cliffoo** [comment]
This is fixed in the [latest release](https://github.com/trufflesuite/truffle/releases/tag/v5.6.1). Thanks @marsrobertson and @thgaskell !
