### ISSUE TITLE
"truffle migrate" runs files with non-js extensions in migrations directory

### ISSUE THREAD

**Issue by MichaelMaurer** [trufflesuite/truffle#353]
## Issue

The `truffle migrate` command executes "autosave" files in the `migrations` directory. For example, an Emacs autosave file named `2_deploy_contracts.js~` is executed.

## Steps to Reproduce

* Create a file named `migrations/2_deploy_contracts.js~`
* Run `truffle migrate`

## Expected Behavior

I expected files named `*.js~` to be ignored.

## Actual Results

    $ ls migrations/
    1_initial_migration.js             2_deploy_contracts.js    2_deploy_contracts.js~

    $ truffle migrate
    Using network 'development'.

    Running migration: 2_deploy_contracts.js
      Deploying Master...
      Master: 0x20c389cc23d3cc62f01457b901d5dac458483323
    Saving successful migration to network...
    Saving artifacts...
    Running migration: 2_deploy_contracts.js~
      Replacing Master...
      Master: 0xc51c0b2e367b180dd90c5d8c9727b4a4e96def7d
      Deploying SampleUser...
      SampleUser: 0xf30b63f805016cf5769483b7fb6b461001887057
    Saving successful migration to network...
    Saving artifacts...

## Environment

* Operating System: OS X 10.11.6
* Truffle version: 3.1.1
* Ethereum client: TestRPC
* node version: 7.2.0
* npm version: 3.10.9

**Comment by MichaelMaurer** [comment]
I now see there is already a PR #295 fixing this.

**Comment by tcoulter** [comment]
This has been fixed in `truffle-migrate` 1.0.0, and will go out with the next release of Truffle. Thanks!
