### ISSUE TITLE
Internal issue: Husky frequently does nothing

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3530]
## Issue

Husky keeps insisting that no files match its rules, and so is currently doing nothing on JS and TS files!

**Comment by haltman-at** [comment]
OK, it seems to be working again for whatever reason now, so I'll close this I guess?

**Comment by haltman-at** [comment]
Reopening this, this has gotten to be a real pain.  Sometimes it works, sometimes it doesn't.  It seems to work after doing a `yarn add`, but then stops working a while later?  IDK.

**Comment by cds-amal** [comment]
I'll review the work on the stalled PR and document the state of Husky.

**Comment by haltman-at** [comment]
Husky now works!  Thanks so much @cds-amal!
