### ISSUE TITLE
EPM deployment fails when multiple networks are specified in a truffle.js file

### ISSUE THREAD

**Issue by skmgoldin** [trufflesuite/truffle#354]
## Issue

EPM deployment fails when multiple networks are specified in a truffle.js file.

## Steps to Reproduce

1. Check out [this repo](https://github.com/ConsenSys/Tokens/tree/81e868c998c0e38c01d8f5b4e5f83432b0ef27c9).
2. Check out this commit, where the bug can be reproduced:
```
git fetch origin pull/40/head:bug
git checkout bug
git checkout 81e868c998c0e38c01d8f5b4e5f83432b0ef27c9
```
3. Add a `secrets.json` file to the `Token_Contracts` directory. The `secrets.json` file can be:
```
{
  "mnemonic": "decide neither mix slide theme sad ladder fault awkward program guide deposit"
}
```
4. Run `npm install && truffle publish`
## Expected Behavior

The EPM package to publish successfully.

## Actual Results

`Error: Could not connect to the following networks: live, morden, testrpc. These networks have deployed artifacts that can't be published as a package without an active and accessible connection. Please ensure clients for each network are up and running prior to publishing, or use the -n option to specify specific networks you'd like published.`

## Environment

* Operating System: OS X 10.12.3
* Truffle version: v3.0.5
* Ethereum client: INFURA ropsten
* node version: 7.5
* npm version: 4.2.0 (lol)

**Comment by skmgoldin** [comment]
This is still a thing in 3.4.7.

**Comment by NFhbar** [comment]
Any news on this?

**Comment by skmgoldin** [comment]
@NFhbar still a bug, but the workaround is to just to temporarily delete or comment out your other networks when publishing.

**Comment by NFhbar** [comment]
Yeah, I simply commented out the other networks and works just fine, thanks!

**Comment by gnidan** [comment]
How bout now? Is it still an issue now?

**Comment by gnidan** [comment]
Closing for issue maintenance, but @skmgoldin you just let us know if this is a still a problem and we'll reopen :)

**Comment by bilelkhalsi** [comment]
Hi,
I am still reproducing this bug with `truffle v5.3.8`

```
truffle publish
Finding publishable artifacts...
Error: Could not connect to the following networks: ci.
```

**Comment by davidmurdoch** [comment]
@bilelkhalsi are you able to to provide reproduction steps for this bug?

**Comment by haltman-at** [comment]
Closing again for issue maintenance, but if anyone has repro steps we can reopen.  Thanks!
