### ISSUE TITLE
Windows Ganache GUI not taking updates from Truffle running on WSL2

### ISSUE THREAD

**Issue by Suedo** [trufflesuite/truffle#3575]
I have added truffle workspace to Ganache as usual. But now when I do a simple `truffle develop` followed by `migrate` inside the truffle shell, Ganache says that the contracts are deployed, but it doesn't pickup changes to the wallet balances. 

My `truffle-config.js` files has only one change:
```js
  compilers: {
    solc: {
      version: "native", 
    },
  },
```
I am running truffle inside WSL2, whereas ganache gui is installed natively in windows.

Below is the balance reported by Truffle shell:

```cmd
truffle(develop)> web3.eth.getBalance(accounts[0])
'99934183260000000000'

truffle(develop)> accounts[0]
'0x6b318B9350E42bEB94f9Ae5e8b9DA854a6137628'
```
Where that same account `0x6b318B9350E42bEB94f9Ae5e8b9DA854a6137628` in Ganache shows balance full 100 Eth:
![image](https://user-images.githubusercontent.com/4963779/99699566-18010080-2ab8-11eb-808e-6e620eaf6208.png)

**Comment by eggplantzzz** [comment]
Hey @Suedo, if you are connecting to an instance of Ganache you should be using `truffle console` and you will definitely need to ensure that your network settings are correct for that instance. You said you are running `truffle develop`? That might cause problems, let us know which command you are using. Thank you!

**Comment by eggplantzzz** [comment]
Another thought is that it might be possible that you need to do some port binding or something to allow it to be located? Just an idea, let us know if you make any progress.

**Comment by fainashalts** [comment]
Hi @Suedo we are closing this for issue maintenance. Hopefully you've been able to make some progress with the suggestions here, but if anything comes up please feel free to open a new issue!

**Comment by sineo** [comment]
I've resolved it and posted an answer here, https://ethereum.stackexchange.com/questions/90309/windows-ganache-gui-not-taking-updates-from-truffle-running-on-wsl2/115303#115303

It would be nice if truffle migrate could recognize that you're in WSL2 and automatically do the proxy for you.
