### ISSUE TITLE
Error: Could not find block

### ISSUE THREAD

**Issue by madjarevicn** [trufflesuite/truffle#3578]
## Issue

```
Running migration: 10_deploy_update.js
Contract updating:  TwoKeyExchangeRateContract
  Replacing TwoKeyExchangeRateContract...
  ... 0x0bdea95d5b997936c930ae096e193e8a7f39d2099fcff5f4767efb3fd2d6302b
/Users/nikolamadjarevic/Desktop/2key/contracts/node_modules/web3-provider-engine/index.js:58
        this.emit('error', new Error("Could not find block"))
                           ^
Error: Could not find block
```

Issue happens to me almost always when I'm deploying something to **mainnet.** 
The same script, same truffle, on ropsten works like a charm. 
## Environment

* Operating System:  MAC OS
* Truffle version (`truffle version`): "truffle": "4.1.14",
* node version (`node --version`): v10.23.0
* npm version (`npm --version`): 6.14.8

**Comment by gnidan** [comment]
Hi @madjarevicn, could you provide a GH repo with some reproduction steps? It'd be helpful for us to figure out what's going wrong.

This may be a tall ask, but can you upgrade to latest Truffle and see if the problem goes away? v4.1.14 is rather old, so it might be harder for us to get to the bottom of this for you.

Thanks!

**Comment by fainashalts** [comment]
Hi @madjarevicn we are closing this issue for maintenance. If this issue persists or you encounter something else, please feel free to open a new issue. Thanks!
