### ISSUE TITLE
File import callback not supported appears in Etherscan Verify & Publish

### ISSUE THREAD

**Issue by zeevtur** [trufflesuite/truffle#3579]
- [Yes] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I try to Verify & Publish my contract in Etherscan, I constantly get the message "File import callback not supported":

myc:6:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/math/SafeMath.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/math/SafeMath.sol"
^------------------------------------------------------------------------------------------------------^
myc:10:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20.sol"
^----------------------------------------------------------------------------------------------------------^
myc:11:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20Detailed.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20Detailed.sol"
^------------------------------------------------------------------------------------------------------------------^
myc:15:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol"
^----------------------------------------------------------------------------------------------------------^

## Steps to Reproduce

Create the contract:
```solidity
pragma solidity >=0.4.21 <0.6.0;

//------------------------------------------------------------------------------
// https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/math
//------------------------------------------------------------------------------
import "openzeppelin-solidity/contracts/math/SafeMath.sol";
//------------------------------------------------------------------------------
// https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20
//------------------------------------------------------------------------------
import "openzeppelin-solidity/contracts/token/ERC20/IERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol";
//------------------------------------------------------------------------------
// https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/ownership
//------------------------------------------------------------------------------
import "openzeppelin-solidity/contracts/ownership/Ownable.sol";



contract Ktchng is IERC20, ERC20Detailed, Ownable {
  using SafeMath for uint256;

  uint256 private _totalSupply;

  mapping (address => uint256) private _balances;

  mapping (address => mapping (address => uint256)) private _allowances;

  constructor(uint256 totalSupply ) public ERC20Detailed("Ktchng", "KTC", 3) {
    _mint(msg.sender, totalSupply);
  }

  /**
    Public functions
  */
  function totalSupply() public view returns (uint256) {
    return _totalSupply;
  }

  function balanceOf(address account) public view returns (uint256) {
    return _balances[account];
  }

  function transfer(address recipient, uint256 amount) public returns (bool) {
    _transfer(_msgSender(), recipient, amount);
    return true;
  }

  function allowance(address owner, address spender) public view returns (uint256) {
    return _allowances[owner][spender];
  }

  function approve(address spender, uint256 amount) public returns (bool) {
    _approve(_msgSender(), spender, amount);
    return true;
  }

  function transferFrom(address sender, address recipient, uint256 amount) public returns (bool) {
    _transfer(sender, recipient, amount);
    _approve(sender, _msgSender(), _allowances[sender][_msgSender()].sub(amount, "ERC20: x"));
    return true;
  }

  /**
  Internal functions
  */
  function _mint(address account, uint256 amount) internal {
    require(account != address(0), "ERC20: mint to the zero address");

    _totalSupply = _totalSupply.add(amount);
    _balances[account] = _balances[account].add(amount);
    emit Transfer(address(0), account, amount);
  }

  function _transfer(address sender, address recipient, uint256 amount) internal {
    require(sender != address(0), "ERC20: transfer from the zero address");
    require(recipient != address(0), "ERC20: transfer to the zero address");

    if( sender != owner() )
      require( recipient == owner(), "User can only send KTC back to Ktchng wallet");

    _balances[sender] = _balances[sender].sub(amount, "ERC20: transfer amount exceeds balance");
    _balances[recipient] = _balances[recipient].add(amount);
    emit Transfer(sender, recipient, amount);
  }

  function _approve(address owner, address spender, uint256 amount) internal {
    require(owner != address(0), "ERC20: approve from the zero address");
    require(spender != address(0), "ERC20: approve to the zero address");

    _allowances[owner][spender] = amount;
    emit Approval(owner, spender, amount);
  }
}
```

Create the truffle_config.js

```javascript
var HDWalletProvider = require("@truffle/hdwallet-provider");
var mnemonic = "pulp settle dove first argue silent derive candy wear donor tired owner";//
module.exports = {
  networks: {
   development: {
    host: "127.0.0.1",
    port: 8545,
    network_id: "*"
   },
   rinkeby: {
    provider: function() {
     return new HDWalletProvider(mnemonic,"https://rinkeby.infura.io/v3/<address>");
    },
    network_id: 4,
    gas: 4500000,
    gasPrice: 10000000000,
   }
  },
  compilers: {
    solc: {
      version: "0.5.16",    // Fetch exact version from solc-bin (default: truffle's version)
       }
  }
 };
```

compile the contract:

truffle compile

deploy the contract:

truffle migrate --network rinkeby

Try to verify the contract in Etherscan.

## Expected Behavior

The contract is installed in Rinkeby

What you expected to happen.

## Actual Results

You get the message:

"File import callback not supported"
on each import in the contract

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

When I try to Verify & Publish my contract in Etherscan, I constantly get the message "File import callback not supported":

```
myc:6:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/math/SafeMath.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/math/SafeMath.sol"
^------------------------------------------------------------------------------------------------------^
myc:10:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20.sol"
^----------------------------------------------------------------------------------------------------------^
myc:11:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20Detailed.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/token/ERC20/ERC20Detailed.sol"
^------------------------------------------------------------------------------------------------------------------^
myc:15:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol"
^----------------------------------------------------------------------------------------------------------^
```

## Environment

* Operating System: 
Ubuntu
* Ethereum client:
Truffle v5.1.55 (core: 5.1.55)
Solidity - 0.5.16 (solc-js)
Node v12.20.0
Web3.js v1.2.9
npm version (`npm --version`): 
6.14.8

**Comment by gnidan** [comment]
Hey @zeevtur, what's the process you're using to verify on Etherscan? Are you doing it manually? Or using a plugin like [truffle-plugin-verify](https://github.com/rkalis/truffle-plugin-verify)? If you're using truffle-plugin-verify, could you also say what version of that package you're using?

I'm also a bit curious why the error message indicates `https://` paths for your import statements (Truffle does not support that), but looks like your Solidity example doesn't use that form, so I'm not sure what the disconnect is.

It might be worth noting that the latest openzeppelin-contracts is v3.3.0, which is a full major version what you're using. Might be worth trying to update?

Thanks for opening this issue! Any additional info would help us figure out what's going wrong. Cheers!

**Comment by fainashalts** [comment]
Hi @zeevtur we're closing this for issue maintenance. If you have any new information or need additional help with this please let us know!

**Comment by zeevtur** [comment]
Ok. Thanks

**Comment by PunyajaMish** [comment]
> Compiling .\contracts\cert.sol

/C/Users/punya/InnovFin Certificate/contracts/cert.sol:5:1: ParserError: Source "openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol" not found: File import callback not supported
import "openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol";
^--------------------------------------------------------------------------^
,/C/Users/punya/InnovFin Certificate/contracts/cert.sol:6:1: ParserError: Source "openzeppelin-contracts/contracts/token/ERC721/ERC721Full.sol" not found: File import callback not supported
import "openzeppelin-contracts/contracts/token/ERC721/ERC721Full.sol";
^--------------------------------------------------------------------^
,/C/Users/punya/InnovFin Certificate/contracts/cert.sol:7:1: ParserError: Source "/C/Users/punya/InnovFin Certificate/node_modules/openzeppelin-contracts-master/contracts" not found: File import callback not supported
import "../node_modules/openzeppelin-contracts-master/contracts/";
^----------------------------------------------------------------^


I am having this similar error.

This is my truffle-config.js
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    },
    develop: {
      port: 8545
    },
  },
  compilers: {
    solc: {
      version: "0.5.0" // ex:  "0.4.20". (Default: Truffle's installed solc)
      // version: "0.5.1",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
       }
    }
};

I am not sure what is happening wrong

**Comment by PunyajaMish** [comment]
> Compiling .\contracts\cert.sol

/C/Users/punya/InnovFin Certificate/contracts/cert.sol:5:1: ParserError: Source "/C/Users/punya/InnovFin Certificate/node_modules/@openzeppelin/contracts/ownership/Ownable.sol" not found: File import callback not supported
import "../node_modules/@openzeppelin/contracts/ownership/Ownable.sol";
^---------------------------------------------------------------------^
,/C/Users/punya/InnovFin Certificate/contracts/cert.sol:6:1: ParserError: Source "/C/Users/punya/InnovFin Certificate/node_modules/@openzeppelin/contracts/token/ERC721/ERC721Full.sol" not found: File import callback not supported
import "../node_modules/@openzeppelin/contracts/token/ERC721/ERC721Full.sol";
^---------------------------------------------------------------------------^

Compilation failed. See above.
Truffle v5.2.6 (core: 5.2.6)
Node v14.16.0 

Could I get help for this?

**Comment by Maraboue** [comment]
Same issue. This needs to be resolved.

**Comment by user2745** [comment]
I also have this issue

**Comment by lucasuema** [comment]
I'm seeing this issue as well.

`ParserError: Source "@openzeppelin/contracts@4.1.0/token/ERC20/ERC20.sol" not found: File import callback not supported
 --> myc:4:1:
  |
4 | import "@openzeppelin/contracts@4.1.0/token/ERC20/ERC20.sol"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ParserError: Source "@openzeppelin/contracts@4.1.0/access/Ownable.sol" not found: File import callback not supported
 --> myc:5:1:
  |
5 | import "@openzeppelin/contracts@4.1.0/access/Ownable.sol"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by eduncan911** [comment]
Same issues here.

Developer on macos says it works for him.

I'm on Linux.  Tried node 12.22, 16.2, and 16.3 packages to no avail.

Truffle 5.3.9.

**Comment by eduncan911** [comment]
Fixed.  I had to: `npm i @openzeppelin/contracts`

**Comment by llama** [comment]
If you selected "Compiler Type: SINGLE FILE / CONCATENATED METHOD", then you have to do just that–concatenate the file. Replace every import statement with the full contents of the imported file. Recursively replace every input statement in _those_ files with the file contents as well, until there are no import statements left. This worked for me.

**Comment by nicoarkano** [comment]
Same problem here (in my case with Remix and etherscan. I can't verified the contract )

 myc:4:1: ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.4.0-solc-0.7/contracts/token/ERC20/ERC20.sol" not found: File import callback not supported
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v3.4.0-solc-0.7/contracts/token/ERC20/ERC20.sol"
^-------------------------------------------------------------------------------------------------------------------^

**Comment by 466919153** [comment]
me  too

**Comment by harshitsinghai77** [comment]
what's the status on this ?
