### ISSUE TITLE
Make a deploy command that does what migrate does.

### ISSUE THREAD

**Issue by maurelian** [trufflesuite/truffle#358]
`migrate` is an unintuitive command, and not particularly beginner friendly. 

I had assumed I would start with `deploy` and then use `migrate` at some later date. This steered me in the wrong direction in the docs. 

**Suggestion**:

* Create a `deploy` command aliased to `migrate`
* add this line to the `--help` entry
    "deploy          => Same as migrations"

Actually, it might be nice if `deploy` was equivalent to `migrate --reset`.

**Comment by prashantpawar** [comment]
Yeah it took me some time to figure out that I need to migrate even as the first deployment.

**Comment by tcoulter** [comment]
`deploy` command as an alias for `migrate` added to master. Thanks!
