### ISSUE TITLE
Support contract.only in tests

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle#359]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Can't use `.only` in `contract` test interface. 

## Steps to Reproduce

Write a test like so:
```
contract.only('SomeContract', function(accounts) {
  // ...
});
```

## Expected Behavior

Only that test running.

## Actual Results

```
TypeError: contract.only is not a function   
```

## Environment

* Operating System: Ubuntu
* Truffle version: v3.1.1
* Ethereum client: testrpc
* node version: v7.3.0
* npm version: 3.10.10

**Comment by cgewecke** [comment]
@maraoz I hesitate to leave a closing comment here since it's been ~55 weeks since you opened this, but this is now available on 4.0.7. Thanks for suggesting, a great idea as always :) Best.
