### ISSUE TITLE
truffle unpack react fails on windows and ubuntu - needs to replace web3 version with 1.3.0

### ISSUE THREAD

**Issue by Dmdv** [trufflesuite/truffle#3595]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Running ```truffle unpack react``` fails

## Steps to Reproduce

truffle unpack react

## Actual Results

```
npm ERR! code 1
npm ERR! path D:\smartcontracts\crowdsales-experiments\client\node_modules\sha3
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR!   addon.cpp
npm ERR! d:\smartcontracts\crowdsales-experiments\client\node_modules\sha3\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may not be aligned 32 [D:\smartcontracts\crowdsales-experiments\client\node_modules\sha3\build\sha3.vcxproj]
npm ERR! d:\smartcontracts\crowdsales-experiments\client\node_modules\sha3\src\addon.cpp(83): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [D:\smartcontracts\crowdsales-experiments\client\node_modules\sha3\build\sha3.vcxproj]
npm ERR! gyp info it worked if it ends with ok
```

## Environment

* Operating System: Windows 10 and Ubuntu 20
* Ethereum client: 
* Truffle version (`v5.1.57`):
* node version (`v15.4.0`):
* npm version (`7.0.15`):

**Comment by Dmdv** [comment]
It relates to sha3 issues
When ```cd client``` and ```npm ci```, it fails with the same error
But ```npm i``` works

**Comment by Dmdv** [comment]
I confirm the same in Ubuntu 20

![image](https://user-images.githubusercontent.com/805238/101878721-19968380-3ba1-11eb-8c62-41e8c72b6991.png)

**Comment by Dmdv** [comment]
I fixed it in Ubuntu using 
```
"web3": "^1.3.0"
```
in package.json

**Comment by Dmdv** [comment]
And the same work for Windows

Please, update your ```truffle unpack react```

**Comment by haltman-at** [comment]
Hi!  We haven't updated to web3 1.3 because of [this bug](https://github.com/ethereum/web3.js/issues/3748) that was introduced in 1.2.10 but still hasn't been fixed yet.  I may have to go pester them about it -- or submit a PR myself...

**Comment by Dmdv** [comment]
What could save hours for others )

**Comment by eggplantzzz** [comment]
@Dmdv What `package.json` are you editing? For the record, I just confirmed that on a mac this box has no problems unboxing successfully.

**Comment by Dmdv** [comment]
@eggplantzzz When unpacking crashed, I cd into client directory and edit package.json in the client directory.
After this, I run ```npm i``` to complete.

**Comment by eggplantzzz** [comment]
Ok thanks for reporting this @Dmdv!

**Comment by haltman-at** [comment]
Well, I submitted [this PR](https://github.com/ethereum/web3.js/pull/3818) to web3, hopefully they merge and release it before too long so we can upgrade...

**Comment by Dmdv** [comment]
It works!
