### ISSUE TITLE
truffle's package.json doesn't contain license information

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/truffle#3597]
It ends up showing up as "License none" on npm.

![image](https://user-images.githubusercontent.com/187813/101953068-afdda000-3bc7-11eb-947b-2a332a5dbc8e.png)

Additionally, the LICENSE file doesn't state what license it is (MIT).

**Comment by eggplantzzz** [comment]
"MIT" was added to the `package.json` in https://github.com/trufflesuite/truffle/pull/3600. Thanks @davidmurdoch!

**Comment by eggplantzzz** [comment]
Released in Truffle version `5.1.58`.
