### ISSUE TITLE
Migration Error - The data field must be HEX encoded data.

### ISSUE THREAD

**Issue by JhonnyJason** [trufflesuite/truffle#3629]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using v5.1.58 for compiling vyper contracts

## Steps to Reproduce

- Use any vyper contract.
- My case was: https://github.com/JhonnyJason/jhonnyjason-token (clone then `$ npm install`)
- then run `$ truffle migrate`

This gives an Error about `The data field must be HEX encoded data.` 
This also happens when using a most minimalistic contract without arguments in the constructor.

When using truffle v5.1.57 - this does not happen. 
So this must be intrudoced in the latest version update.

Cheers!

**Comment by JhonnyJason** [comment]
Maybe an interesting addition is - the error must be in in the compiled artifacts.
I derive that by the observation - when changing the truffle version by itself this does not change the effect if the error occurs or not.

- start clean -> using 5.1.57 -> truffle migrate -> works -> switch to 5.1.58 -> truffle migrate -> works
- start clean -> using 5.1.58 -> truffle migrate -> doesn't work -> switch to 5.1.57 -> truffle migrate -> doesn't work

**Comment by haltman-at** [comment]
Hi, sorry, thanks for reporting this!  This is my fault; the problem is that due to an error Vyper contracts are getting stored in the artifact starting with `"0x0x..."` instead of `"0x..."`.  I was working on improving Vyper support recently and I think this bug is due to a harmless-seeming last-minute change that as a result didn't get tested properly.  Sorry about this; I'll fix this shortly, and we should have the fix out this wekek.

**Comment by haltman-at** [comment]
In the meantime, if you want a workaround, you could manually edit the artifact files, I suppose.  Some things, such as `truffle debug` and `truffle test`, might not work properly this way, but at least migrating and contract interaction should.

**Comment by haltman-at** [comment]
The other possible workaround, of course, is to just use the previous version for now, which is still a plenty good version of Truffle! :)  Again, we'll have the fix out this week, and (experimental) Vyper debugging should be working for real as of then. :)

**Comment by haltman-at** [comment]
OK, PR is up.  Sorry about that!

**Comment by JhonnyJason** [comment]
Awesome man! 
Yhea until the next release is available - using 5.1.17 is the way to go for me :sunglasses:
