### ISSUE TITLE
truffle build process (webpack) fails with missing semicolon - russian utf-8 problem

### ISSUE THREAD

**Issue by JackBekket** [trufflesuite/truffle#363]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle webpack build fails in browser, console said that there is semicolon missing.

I found tha bug is in this section:
```
  if (options.value > 0) {
            var constructorAbi = abi.filter(function (json) {
                return json.type === 'constructor' && json.inputs.length === args.length;
            })[0] || {};
```
in the last line. 
end user can fix this bug by simply adding semicolon into build file
```
})[0] || ;{};
```
But is obviously bug in a build process.

## Steps to Reproduce
```
truffle init webpack && npm install
truffle migrate
npm run build
```
then open build file in your browser.

## Expected Behavior

Dapp is work

## Actual Results

Dapp is not work cause of syntax error in builded js file.

## Environment

* Operating System: Ubuntu 16
* Truffle version: 3.1.1
* Ethereum client: testrpc
* node version: 6.x
* npm version:  4.3.0

**Comment by jorpic** [comment]
There was a typo in web3.js `lib/web3/contract.js`. It is fixed in https://github.com/ethereum/web3.js/commit/e4f7dde86857f577481eeeb00917930c71b73f6a#diff-430c9c02bef6a7661c5b4e7b34142f7c.

I think the problem can be solved by updating web3 dependency in truffle-contract to ^0.18.2.

**Comment by JackBekket** [comment]
Hi Max! 

Found solution - need to ROLL back to 0.17.0-alpha, there is no fix in ^0.18.2 for now.

Reference - (https://github.com/ethereum/web3.js/issues/555)

**Comment by JackBekket** [comment]
Until (https://github.com/ethereum/web3.js/issues/555) will fix newest version of web3 is only one method to work with web3+webpack.

**Comment by JackBekket** [comment]
I found something really strange, it's like problem not related to web3.js really, it's related to ```meta charset``` tag in main index.html, probably it touch only people,who use яussian letters. When ```utf-8``` is not set, builder have strange behaviour and add invisible symbol instead of space, as Max refferer. In other case, when ```utf-8``` is set in ```meta charset``` build is going on normally. Plese, try to reproduce it, probably it's a weird bug.

**Comment by tcoulter** [comment]
It looks like the original issue here was fixed in Web3. You should no longer be receiving this issue. @JackBekket Your last comment suggests a different issue. However, considering this ticket is fairly old, I'm going to close it for housekeeping reasons. Please open a new ticket if you run into a new issue. Thanks!
