### ISSUE TITLE
errors installing truffle on Ubuntu 18 LTS

### ISSUE THREAD

**Issue by amiracam** [trufflesuite/truffle#3638]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

can't install truffle without error on Ubuntu

## Steps to Reproduce

npm install -g truffle

## Expected Behavior

No errors

## Actual Results

stack:

 npm install -g truffle
loadDep:original-require  ▌ ╢█████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine mocha@8.1.2: wanted: {"node":">= 10.12.0"} (current: {"node":"loadDep:yargs-unparser →  ▄ ╢███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine escape-string-regexp@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine log-symbols@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine find-up@5.0.0: wanted: {"node":">=10"} (current: {"node":"8.10npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
loadDep:fsevents → resolv ▄ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine fsevents@2.1.3: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.loadDep:binary-extensions ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine locate-path@6.0.0: wanted: {"node":">=10"} (current: {"node":"loadDep:p-locate → reques ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine p-locate@5.0.0: wanted: {"node":">=10"} (current: {"node":"8.1loadDep:p-limit → request ▐ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine p-limit@3.1.0: wanted: {"node":">=10"} (current: {"node":"8.10loadDep:p-limit → fetch   ▌ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine yocto-queue@0.1.0: wanted: {"node":">=10"} (current: {"node":"loadDep:chalk → 200       ▐ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0npm ERR! Linux 5.3.0-61-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "truffle"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50

## Environment
* Operating System:  Ubuntu
* Ethereum client: n/a
* Truffle version : can't install truffle
* node version : v8.10.0
* npm version :  3.5.2

**Comment by eggplantzzz** [comment]
Hey @amiracam, I think you will need to upgrade your version of Node. Try using version 10 or greater. I think that will solve your problem. Let me know if you still encounter difficulties and I'll try to help!

**Comment by eyooooo** [comment]
This is the correct answer. Install Node 14. Node v8 is what comes with `apt install nodejs`

**Comment by gnidan** [comment]
Closing this for issue maintenance. Let us know if you still have trouble and we can re-open. Thanks!

**Comment by eyooooo** [comment]
I just wanted to leave a quick comment here that apparently some folks find issues with truffle and node 14. node 12 seems to be the favorite version.
