### ISSUE TITLE
Deploying only a part of contracts

### ISSUE THREAD

**Issue by vporton** [trufflesuite/truffle#3639]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If I need sometimes to deploy only `A.sol` and sometimes only `B.sol`, how can I make truffle to do it for me, except of creating two separate repositories?

**Comment by gnidan** [comment]
Could you provide a bit more info about your use case? Specifically, what situations determine A vs. B?

**Comment by vporton** [comment]
> Could you provide a bit more info about your use case? Specifically, what situations determine A vs. B?

I want to create a Truffle package that is used by another packages, and I want to deploy different contracts of the first package from these packages.

**Comment by gnidan** [comment]
> I want to create a Truffle package that is used by another packages, and I want to deploy different contracts of the first package from these packages.

I see, cool! There's a couple ways to do this, but the best is probably to use NPM. Let's say your first project is called `vporton-contracts`. Do an `npm init` and get that all set up as a NPM package. **Important:** update your `package.json` to have a [`"files"` property](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files), and make sure it includes your `contracts/` directory. Once that's set up, do `npm publish`.

In your other projects, you'd install this package like normal for JS:
```console
npm install --save-dev vporton-contracts
```

And in your migration files, something like:
```javascript
const A = artifacts.require("vporton-contracts/contracts/A");

module.exports = async (deployer) => {
  await deployer.deploy(A);
}
```

You can also import in Solidity, if you need to do that too:
```solidity
pragma solidity >0.6.0;

import "vporton-contracts/contracts/A.sol";

contract BetterA is A {
  // ...
}
```

(and similarly with `B` for your other projects that need that).

Will this work for you?

**Comment by vporton** [comment]
> Will this work for you?

Yes, this could work.

It could be enhanced by providing several deploy scripts in `vporton-contracts` to be called from other projects. Which folder these deploy scripts should be put to?

**Comment by gnidan** [comment]
> Yes, this could work.

Glad to help!

> It could be enhanced by providing several deploy scripts in `vporton-contracts` to be called from other projects. Which folder these deploy scripts should be put to?

There's not currently a "normal" way to do this, but I'd probably write these deploy scripts as individual files for specific helper functions, like `initializeBAfterDeploy()`, and you can put those anywhere you like. Maybe `scripts/`?

**Comment by haltman-at** [comment]
Doing issue maintenance... can this be closed now?  Thank you!

**Comment by kevinbluer** [comment]
Just to throw another option into the mix: when running `truffle migrate` there's `from` (`--f`) and `to` (--to) options; more detail [here](https://www.trufflesuite.com/docs/truffle/reference/truffle-commands#migrate). This looks at the numerical prefix on the migration scripts, for example running `truffle migrate --f 2 --to 2` with the following in your migrations directory...

```
├── migrations
    ├── 1_initial_migration.js
    ├── 2_migrate_A.js  
    ├── 3_migrate_B.js
```

...would just run `2_migrate_A.js`

**Comment by gnidan** [comment]
Closing for issue maintenance. Let us know if we can be of further help here. Thanks!
