### ISSUE TITLE
Using smart contracts from another NPM/Yarn project

### ISSUE THREAD

**Issue by vporton** [trufflesuite/truffle#3641]
I have a Truffle project with some smart contracts and another project (I could use either Truffle or HardHat, now I use HardHat) than depends on it.

I want the second project to be able to compile and use (some of) smart contracts of the first project, as if they were contracts in the second projects itself.

How to do this?

Note: I do not want just to copy the `contracts/` folder from another project to make tracking changes (such as security audits) in the first project easier.

**Comment by haltman-at** [comment]
Hi there!  I'd suggest seeing [this documentation](https://www.trufflesuite.com/docs/truffle/getting-started/package-management-via-npm) about this.  Does that resolve your problem?  Thank you!

**Comment by vporton** [comment]
> Hi there! I'd suggest seeing [this documentation](https://www.trufflesuite.com/docs/truffle/getting-started/package-management-via-npm) about this. Does that resolve your problem? Thank you!

Yes.
