### ISSUE TITLE
Cannot run truffle command after installation using npm on Mac Big Sur

### ISSUE THREAD

**Issue by jsoneaday** [trufflesuite/truffle#3643]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I've installed truffle on my Mac Big Sur. When I try and run the truffle init comment I get the error truffle: command not found.

## Steps to Reproduce

1. npm i -g truffle
2. See messages showing successful install but onto weird path. This is the entire results message. As you can see it installs onto Java path.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/languages/js/bin/truffle -> /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/languages/js/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.58 postinstall /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/languages/js/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.58
updated 1 package in 83.937s
3. Then run truffle init and get the error as mentioned.

## Expected Behavior

truffle init command to just work

## Actual Results

Failed with messages "truffle: command not found"

## Environment

* Operating System: Mac Big Sur
* Ethereum client: Parity 2.7.2
* Truffle version (`truffle version`): 5.1.58
* node version (`node --version`): 12.18.0
* npm version (`npm --version`): 6.14.4

**Comment by colinsteidtmann** [comment]
Same problem for me, running macOS Catalina

**Comment by colinsteidtmann** [comment]
Oh, my bad. I figured it out. It's been a long time since I last did any programming. My npm packages were getting installed to my local folder instead of my Global NPM folder. This article solved things for me: http://blog.webbb.be/command-not-found-node-npm/.

**Comment by cds-amal** [comment]
@jsoneaday very strange. Is it possible your `npm root` folder was changed by the virtual JVM setup? What does the command `npm root -g` resolve to?

**Comment by jsoneaday** [comment]
Yes that's it. I get the path to Java instead. Can you tell me which environment variable is the culprit? Maybe PATH or JAVA_HOME?


TERM_PROGRAM=Apple_Terminal

SHELL=/bin/bash

TERM=xterm-256color

TMPDIR=/var/folders/5r/k3zy2k052355b1_qhhk1j8300000gn/T/

TERM_PROGRAM_VERSION=440

TERM_SESSION_ID=6BCFBAF7-F68F-4D17-B8FA-C4EE4DDE775C

USER=davidchoi

SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6QypbqC2oq/Listeners

PATH=/Users/davidchoi/.yarn/bin:/Users/davidchoi/.config/yarn/global/node_modules/.bin:/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

LaunchInstanceID=82227C6D-AA6C-4CC2-B201-60C6104E3C20

__CFBundleIdentifier=com.apple.Terminal

PWD=/Users/davidchoi

JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.2.0/Contents/Home

LANG=en_US.UTF-8

XPC_FLAGS=0x0

XPC_SERVICE_NAME=0

SHLVL=1

HOME=/Users/davidchoi

LOGNAME=davidchoi

SECURITYSESSIONID=186aa

_=/usr/bin/env

________________________________

**Comment by cds-amal** [comment]
@jsoneaday I'm unfamiliar with the JVM setup on your machine. I recommend consulting their documentation and forum for PATH related issues.

**Comment by jsoneaday** [comment]
So I removed the java path from the path environment variable and it seems to try and install to correct paths. But now when I try to install without using sudo I get 
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/truffle

When I use sudo then I get errors about permissions to my own paths
Error: EACCES: permission denied, open '/Users/davidchoi/.config/truffle/config.json'
You don't have access to this file.

**Comment by jsoneaday** [comment]
I decided to give up and install truffle on the local folder. Thanks guys.
________________________________

**Comment by haltman-at** [comment]
Doing issue maintenance... can we close this now?  Thank you!

**Comment by jsoneaday** [comment]
Yes thanks.
________________________________

**Comment by haltman-at** [comment]
OK, closing!

**Comment by Rahimjackass** [comment]
Hi 
I have the same issue, But didn't find any solution on above comments :(

**Comment by haltman-at** [comment]
@Rahimjackass If you're having a similar problem, could you perhaps file a new issue for it?  Thanks!
