### ISSUE TITLE
Error: PollingBlockTracker when running truffle console

### ISSUE THREAD

**Issue by Dmdv** [trufflesuite/truffle#3646]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

```
truffle(rinkeby)> Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:631:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1565:19)
    at TLSSocket.emit (node:events:388:22)
    at TLSSocket.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1305:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
    at PollingBlockTracker._performSync (D:\smartcontracts\crowdsales-experiments\node_modules\eth-block-tracker\src\polling.js:51:24)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

## Steps to Reproduce

1.  Initiated truffle env with default settings
2. Updated network and added rinkeby network to truffle-config
```
      rinkeby: {
          provider: () => new HDWalletProvider(
              mnemonic, `https://eth-rinkeby.alchemyapi.io/v2/${alchemyApiKey}`
          ),
          network_id: 4,
          gasPrice: 10e9,
          skipDryRun: true
      }
```

3. Run this

```bash
 npx truffle console --network rinkeby
```

4. It works for some time but fails randomly

## Environment

* Operating System: Windows 10
* Truffle v5.1.57 (core: 5.1.57)
* Solidity - 0.7.5 (solc-js)
* Node v15.5.0
* Web3.js v1.2.9

**Comment by haltman-at** [comment]
Hm, this may be related to Alchemy API's rate limiting.  We'll see if we can do anything about this, I suppose.  In the meantime, you may want to disable the confirmation listener as described [here](https://www.trufflesuite.com/docs/truffle/reference/configuration#networks).

**Comment by haltman-at** [comment]
Hi!  Is this still an issue?  Thank you!

**Comment by kevinbluer** [comment]
Closing this one for issue maintenance. Feel free to re-open / create a new issue if this one needs to be readdressed.
