### ISSUE TITLE
Vyper compiler needed if json file(s) are present.

### ISSUE THREAD

**Issue by aarlt** [trufflesuite/truffle#3647]
## Issue

Truffle tries to execute the vyper compiler, even if there are no vyper sources present. If truffle finds any `.json` file, it assumes that the project contains vyper code and tries to run the vyper compiler. 

@cameel did an analyses here: https://github.com/ethereum/solidity/pull/10672#issuecomment-749699412.

**Comment by eggplantzzz** [comment]
Hey @aarlt thanks for reporting this! Looks like `compile-vyper` shouldn't care about JSON files. I'll try and put in a fix for this this week!

**Comment by eggplantzzz** [comment]
Hmm actually it might be a bit more nuanced than that because Truffle currently has support for `vyper-json` which allows you to have input in JSON format. We'll have to figure out a different solution than just removing the detection of the "json" file extension.

**Comment by eggplantzzz** [comment]
A fix was created in https://github.com/trufflesuite/truffle/pull/3650

**Comment by cameel** [comment]
Thanks! [Seems to work fine with OpenZeppelin in our external tests](https://github.com/ethereum/solidity/pull/10672#issuecomment-757777256).
