### ISSUE TITLE
No Vyper import parser, so Vyper must recompile everything

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3666]
## Issue

Because we don't have a Vyper import parser, `compile-vyper` is forced to assume that everything could be a dependency.  So, the issue here is to write a Vyper import parser, and then to hook it up in `compile-vyper`'s `soucesWithDependencies` method (similar to how `compile-solidity` does things) so that Vyper only compiles what it needs to.  Note that hooking it up may require providing a few other function parameters?  I'm not entirely clear on how the profiler works but I gather it needs various functions passed in...

## Environment

* Truffle version (`truffle version`): 5.1.60

**Comment by gnidan** [comment]
Fixed in [v5.1.64](https://github.com/trufflesuite/truffle/releases/tag/v5.1.64)
