### ISSUE TITLE
There was an error when fetching your accounts.

### ISSUE THREAD

**Issue by woodhead001** [trufflesuite/truffle#367]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I run the webpack with testrpc，it remind me "There was an error when fetching your accounts"

## Steps to Reproduce

root@myvoice:~/truffledemo#truffle migrate
Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x0af196e93a93b5240aedad8dece54ab903b8afd2
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying ConvertLib...
  ConvertLib: 0xb0bf333ebcd5f9926464d68bf83e011f37cd97a5
  Linking ConvertLib to MetaCoin
  Deploying MetaCoin...
  MetaCoin: 0x744c623192850bc0f8149849d6b2e9db5fc26433
Saving successful migration to network...
Saving artifacts...
root@myvoice:~/truffledemo# truffle serve
Serving static assets in ./build on port 8080...

Then I open the webpage using IE，http://localhost:8080/index.html

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Truffle version:
* Ethereum client:
* node version:
* npm version:

**Comment by gengxuelei** [comment]
same err as:
https://github.com/trufflesuite/truffle/issues/108#issuecomment-358560594

**Comment by gnidan** [comment]
Closing for issue maintenance. Thanks!
