### ISSUE TITLE
Imported contracts not checked when re-compiling before migration.

### ISSUE THREAD

**Issue by HCharlanes** [trufflesuite/truffle#368]
## Issue
Using truffle 3+
When using truffle migrate after having changed a contract that is imported in another contract, the first one is recompiled but not the second one.

## Steps to Reproduce

Code a factory that import a standard contract
Migrate 
Change the standard contract
Migrate again, the standard contract will be recompiled but not the Factory.

**Comment by tcoulter** [comment]
Hi Hadrien,

Thanks for the bug report. Any chance you can create a small demo project
with exact commands to run? That'd make it a lot easier to reproduce.

Thanks!

**Comment by tcoulter** [comment]
This should be fixed in 3.4.3. Thanks!
