### ISSUE TITLE
Web3 not getting injected into truffle test js files

### ISSUE THREAD

**Issue by cjfarnold** [trufflesuite/truffle#3711]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

I am getting Reference error Web3 is not defined when I am using web3 functions in my truffle test cases

In my code I am using 
var web3 = new Web3();

Copying the action error message

xxxx@MacBook-Pro test % truffle test testbet.js
Using network 'development'.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

ReferenceError: Web3 is not defined

* Operating System: MacOS 10.15.7
* Ethereum client: Ganach 2.4.0
* Truffle version (`truffle version`): 5.1.49
* node version (`node --version`):12.18.3
* npm version (`npm --version`): 6.14.8

**Comment by fainashalts** [comment]
Hi @cjfarnold, you shouldn't need to instantiate a `new Web3()` here. You should be able to refer to the lowercase `web3` instance that is injected in the tests. Please let us know if that resolves your issue!

**Comment by davidmurdoch** [comment]
Closing for issue maintenance.
