### ISSUE TITLE
Truffle Kovan gas problem

### ISSUE THREAD

**Issue by JackBekket** [trufflesuite/truffle#372]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In Kovan testnet gas limition is 4.7 million gas, but trufffle default value is  ```4712388``` so your transaction with contract deployment never will pass and transaction stack of your ethereum account will be blocked by this transactions with all funds on them.

## Steps to Reproduce

start any node configured for ```kovan testnet``` for example ```parity --chain=kovan``` and try to deploy any contract with ```truffle migrate```.

## Expected Behavior

Contract deployed.

## Actual Results

Transaction is staked, and never will be pass through, also it blocks any other transaction with nonce value higher than that. Any further operation with account's will be blocked by this transaction.

## Suggestion how to solve problem

In first place we need to replace this blocking transaction with valid one. For this you need to connect to ethereum node through Java-Scritpc console and execute method ```web3.eth.sendTransaction``` with manually setted ```nonce``` which compare with nonce of broken transaction, like ```web3.eth.sendTransaction({from:accounts[0],value:5,to:accounts[1],nonce:0});``` where ```nonce``` is the same number as your bloked transaction.

As second - you need to set gas amount for deployment in file ```truffle.js``` which must be 4.7M or lower, like -
```
networks: {
  development: {
    host: "localhost",
    port: 8545,
    network_id: "*", // match any network
    gas:4700000
  }
```
And after that you can finely deploy contracts in Kovan network throught Truffle.

**Comment by hitchcott** [comment]
Notes: 

* We've now increased the gas limit on Kovan to 5 mil to get around this, so it shouldn't affect most users anymore
* The `new` method in `truffle-contract` should be using `estimateGas` before deploying if `gas` isn't set, which would solve this problem for other networks with gas lower than the default.

**Comment by tcoulter** [comment]
Hey all.

I'm going to close this ticket for housekeeping issues. `truffle-contract` will get a future overhaul, so we'll circle up on the `estimateGas` feature then.

Thanks!
