### ISSUE TITLE
Enable truffle contract abstractions to be used with external contracts. [Enhancement]

### ISSUE THREAD

**Issue by ccolorado** [trufflesuite/truffle#3723]
---------------------------

## Issue

Can't instantiate a truffle "contract abstraction" object with only the address and the ABI of a contract.
A  truffle generated build `.json` file is required.

I am using an extra truffle setup to deal with the deployment of a contract that is on a different solidity version than the rest of my project (e.g. dai token on solidity 5).

Having these instance will allow to make more robust migration scripts and facilitate testing. 
Short discussion @ https://gitter.im/ConsenSys/truffle?at=6008714e2cb18a437c2e8721

**Comment by eggplantzzz** [comment]
Hey @ccolorado, thanks for creating this issue. Could you clarify a little further what you want from this feature? You can already use `@truffle/contract` as a library and feed it the abi and address to create an object. Can you give an example of the kind of usage you would like? Thanks!

**Comment by gnidan** [comment]
Closing this for issue maintenance. @ccolorado this sort of thing is on our radar as a possible future enhancement, but definitely would need further requirements. Let us know if you'd like to participate in that discussion at all and we can re-open this. Cheers!
