### ISSUE TITLE
ReferenceError: artifacts is not defined

### ISSUE THREAD

**Issue by mlntr** [trufflesuite/truffle#3728]
- [x] I've asked for help in the Truffle Gitter before filing this issue.

## Issue
I'm able to run `truffle test` in the terminal fine, however when I try to run tests via [VSCode test explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) it outputs "ReferenceError: artifacts is not defined" while trying to load the tests. Am I able to do something to resolve this, like importing something or editing some setting?

## Steps to Reproduce
The line in test JS file leads to error: `const Contract = artifacts.require("Contract")`

## Expected Behavior
I expect the tests to run fine through VSCode test explorer (like how it works when [using Hardhat](https://hardhat.org/guides/vscode-tests.html))

## Actual Results
![image](https://user-images.githubusercontent.com/17552475/105233817-42c40f80-5b62-11eb-8289-0507a65ae2e8.png)

## Environment
* Operating System: W10
* Ethereum client: Ganache
* Truffle version: 5.1.58
* node version: 14.0.0
* npm version: 6.14.8

**Comment by 4math2379** [comment]
Have you provide something different in the  `testEnvironment` ? 
Look in your truffle config file.

**Comment by mlntr** [comment]
I've got a standard truffle-config.js and no other settings in my project, should I add something special in there?
```js
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*"
    },
  },
  mocha: {},
  compilers: {
    solc: {
      version: "0.8.0"
    }
  }
}
```

**Comment by eggplantzzz** [comment]
I'm not very familiar with the VSCode test explorer. You might check with them and report this issue. Sorry I can't be of more help!

**Comment by eggplantzzz** [comment]
@caleteeter Is there somewhere that you could recommend for @mlntr to ask about this issue?

**Comment by caleteeter** [comment]
@eggplantzzz @mlntr I believe this is caused because this extension you [referenced](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) is using mocha directly.  Truffle tests are a wrapper around mocha which sets up the provider, contract abstractions, not to mention the ganache instance to create a clean state for each test run.

I have been trying to setup this manually in the test and will post that here.

**Comment by edugrip** [comment]
Did you use yarn instead of npm for installing truffle globally?

**Comment by caleteeter** [comment]
NPM, not yarn @edugrip

**Comment by PatrickConrad** [comment]
Any luck, having this same issue

**Comment by edugrip** [comment]
I asssume that artifacts is a globally available package when you install truffle globally. If truffle is installed gloabally it should ideally work.

**Comment by cds-amal** [comment]
Hey @caleteeter, Not sure how to proceed here. Is there anything actionable on Truffle's side for this issue? Thanks!

**Comment by regmenriquez** [comment]
Any updates? Having the same issue here.

**Comment by Sungyuk1** [comment]
^ Same issue here

**Comment by aekiratli** [comment]
any update?

**Comment by chijudecode** [comment]
Pretty simple, Try using  truffle test instead of npm run start.

**Comment by thomasmodeneis** [comment]
would be great to get this one sorted at some point

**Comment by pranavvdesai** [comment]
Any updates on this issue? im facing the same

**Comment by mustafa-boorenie** [comment]
Same issue here! Ran it with truffle test, still didn't work :/

**Comment by TaYut** [comment]
same issues, any recommendation?

**Comment by pesh001** [comment]
had the same issue and  'npm install -g truffle'   fixed it

**Comment by MagentaSpruce** [comment]
Hello, if you still experience this issue please try the following which worked for me:

At the top of each migration file which contains the undefined artifact require the following -

const {artifact} = require("truffle");

Hope that helps!

Tristan Nettles

**Comment by MagentaSpruce** [comment]
Hello, if still having this problem please do following:

In each migration file with the undefined artifacts.require(), require the following at the top of the file --->

const { artifacts } = require("truffle");

Hope that helps!

**Comment by kirtilodha** [comment]
Not working

**Comment by pesh001** [comment]
Hello!!!!

I apologize for the delayed response.
However, Thanks a lot for the help!!!!

**Comment by dbsadik** [comment]
Same problem

**Comment by monish52** [comment]
> Hello, if still having this problem please do following:
> 
> In each migration file with the undefined artifacts.require(), require the following at the top of the file --->
> 
> const { artifacts } = require("truffle");
> 
> Hope that helps!

This worked for me

**Comment by JLiu1272** [comment]
> Hello, if still having this problem please do following:
> 
> In each migration file with the undefined artifacts.require(), require the following at the top of the file --->
> 
> const { artifacts } = require("truffle");
> 
> Hope that helps!

This worked for me too, but instead of using require, I did. Same thing just a different way to import.  

`import { artifacts } from "truffle"`

I guess it just wasn't able to find the artifact in that specific file in the VSCode.

**Comment by Asim12** [comment]
i have the same issue

**Comment by Hp1923** [comment]
i have the same issue...

**Comment by cds-amal** [comment]
@michaeljohnbennett , @kevinbluer any insights on this?

**Comment by JLiu1272** [comment]
What I found that you can still run the code. But its just an eslint error I suppose, so must be some VSCode config issue

**Comment by Taranmielec** [comment]
i have the same issue, i tried both way's of import and does't work
i sending pictures of terminal with and without import from above
![issue 2](https://user-images.githubusercontent.com/95530030/153386697-501ca306-dec6-4742-b239-9139f19edf41.png)
![issue 1](https://user-images.githubusercontent.com/95530030/153386699-7405fe47-b07c-490a-a9a1-733fff60d0a1.png)

**Comment by love-droid** [comment]
> Hello, if still having this problem please do following:
> 
> In each migration file with the undefined artifacts.require(), require the following at the top of the file --->
> 
> const { artifacts } = require("truffle");
> 
> Hope that helps!

worked for me too

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. @Hps21999 please reopen another issue if there is a problem with Truffle that we can help you with.

**Comment by firasbelhiba** [comment]
Guys try to npm install -g truffle
and re-open vsc and everything should be clear

**Comment by toluhikay** [comment]
> Hello, if still having this problem please do following:
> 
> In each migration file with the undefined artifacts.require(), require the following at the top of the file --->
> 
> const { artifacts } = require("truffle");
> 
> Hope that helps!

thank you for this

**Comment by abhi-sharma901** [comment]
> 

Thanks, it worked for me!!

**Comment by abhi-sharma901** [comment]
> Hello, if still having this problem please do following:
> 
> In each migration file with the undefined artifacts.require(), require the following at the top of the file --->
> 
> const { artifacts } = require("truffle");
> 
> Hope that helps!

Thanks, it worked for me!!

**Comment by edugrip** [comment]
after many years of experience, to me,  it turns out that using solc is a
far better choice :)

**Comment by hackvick** [comment]
Don't do anything just update the truffle 
Your error will be removed🥇
