### ISSUE TITLE
Uncaught Error: Callback was already called in async library.

### ISSUE THREAD

**Issue by Devilla** [trufflesuite/truffle#3729]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue :bug: 
```
Uncaught Error: Callback was already called.
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:1
```
## Steps to Reproduce

1. Compile the [code](https://github.com/Devilla/EthSwap/blob/master/src/contracts/EthSwap.sol) with Truffle v5.1.42
2. Migrate - shows the above error

## Expected Behavior :beetle: 

Uncaught Error: Callback was already called.

## Actual Results

Screenshot:
![image](https://user-images.githubusercontent.com/15603274/105498502-4b455300-5ce6-11eb-9003-93bea4317dc1.png)

## Environment

* Operating System: Linux (Ubuntu) 
* Truffle version : v5.1.42
* node version : v14.15.3
* npm version : 6.14.9

**Comment by eggplantzzz** [comment]
Hey @Devilla, we'll go ahead and try to reproduce this. If you update to the latest version of Truffle, do you still experience the error you reported? The current version is 5.1.63. Let us know if updating helps. Thanks!

**Comment by Devilla** [comment]
Yes, @eggplantzz I have tried updating to the latest yesterday and it solves the error for the latest version.

**Comment by gnidan** [comment]
Thanks @Devilla! Closing this!

**Comment by Devilla** [comment]
Cool. 👍
