### ISSUE TITLE
truffle init doesn't create App folder

### ISSUE THREAD

**Issue by ysfAskri** [trufflesuite/truffle#374]
![screenshot from 2017-03-15 08-51-03](https://cloud.githubusercontent.com/assets/6476224/23938520/fe05c5e2-095c-11e7-802d-11fcc88dc9fd.png)

thank you for help

**Comment by andre-zh** [comment]
As far as I know it won't create App folder like before.
http://truffleframework.com/docs/getting_started/project

**Comment by tcoulter** [comment]
It will not by default. The default project now only provides contracts,
migrations and tests.

You can get a default web app though, which does have an app folder, via
`truffle init webpack`.

**Comment by ysfAskri** [comment]
thank you :)

**Comment by nocb** [comment]
Note: The MetaCoin Truffle project used to be created by running truffle init. Now it exists as a Truffle Box.
v4.0.4
