### ISSUE TITLE
Feature Request: Return Total Gas Costs for a migration run

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/truffle#376]
Hey everyone, 

It would be useful to have the total gas costs of the entire ``` truffle migrate ``` returned.
Eventually also the sum of Wei passed along with all the migration steps.

Thanks a lot in advance ;)

**Comment by tcoulter** [comment]
On the list. Related to: #470

**Comment by gnidan** [comment]
This is part of Truffle v5. Closing for issue maintenance. Thanks!
