### ISSUE TITLE
Move @truffle/debugger out of Truffle bundle

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#3768]

**Comment by haltman-at** [comment]
To be clear, your intention with this issue is that it wouldn't be recompiled as part of the bundle, not that it wouldn't be included in the bundle?  Or how does this work exactly?  You mentioned webpack externals but I'm not familiar with how those work.

**Comment by gnidan** [comment]
@haltman-at it doesn't get recompiled currently. what happens is Truffle's webpack takes the already-compiled @truffle/debugger bundle and just inlines that into the Truffle bundle (i.e., when you do `require("@truffle/debugger")`, webpack looks inside the bundle itself for that module)

Webpack externals are modules that should **not** be inlined, but rather, when `require("@truffle/debugger")` happens in the code, it'll just resolve via Node's normal package resolution mechanism. So the work here is: make sure @truffle/debugger is a [regular] dependency of Truffle, and that it's listed as an external in webpack.config.js.

**Comment by haltman-at** [comment]
Oh I see!  That makes sense, thanks.
