### ISSUE TITLE
How to add support for a new EVM chain Conflux

### ISSUE THREAD

**Issue by Pana** [trufflesuite/truffle#3779]
Hey guys our team have develop a new EVM compatible blockchain Conflux, is online now. Which TPS is much higher than ethereum, we have fork truffle and create a Conflux-truffle, but we think if we can merge Conflux truffle back to truffle that will be awesome, is there any documentation about this ?

**Comment by gnidan** [comment]
Hi @Pana, we don't have documentation for this right now, nor do we have a good answer for you, sadly. If you could explain some of the technical differences that you've had to overcome in your fork, we might be able to start the conversation on how to make Truffle more forgiving to those differences.

Please let us know! Thanks for your interest.

**Comment by Pana** [comment]
Conflux is very like ethereum, but have a several difference:
1. Our RPC is not compatible with eth.
2. When creating transaction two new fields is needed: `epochHeight`, `storageLimit`
3. Our address is very different from eth hex40 address, is a base32 checksum address for example: cfxtest:ach727k1wt7kmj633hc1fcrrgbajmargkaxyycf6ee

**Comment by Pana** [comment]
For the differece 1 we can create a RPC bridge to convert Conflux RPC to eth RPC, which seems can cover most truffle used RPC:

* eth_blockNumber
* net_version
* eth_accounts
* eth_getBlockByNumber
* eth_getCode
* eth_call
* eth_estimateGas
* eth_sendTransaction
* eth_getTransactionReceipt
* eth_getTransactionByHash
* eth_getBalance

**Comment by Pana** [comment]
Do you have any suggestion about how to make Truffle support Conflux ?

**Comment by davidmurdoch** [comment]
It seems like this would require more work than Truffle's architecture can currently handle. We'd need to improve our plugin system in order to support the changes this would require. If you'd like to dive in to that let us know.

**Comment by akiraplusplus** [comment]
I have same issue with truffle and supporting conflux. Is there any better solutions available now?

**Comment by fainashalts** [comment]
Hi @Pana we're closing this for issue maintenance. We'd love to have a plugin system that could support Conflux in the future, so please stay tuned to our release notes!
