### ISSUE TITLE
Connecting to Energi Testnet

### ISSUE THREAD

**Issue by TobyKreiselmaier** [trufflesuite/truffle#3795]
- [ X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am with the Energi Core team. We operate our own blockchain which we aim to be 100% Ethereum compatible.
We use truffle and ganache-cli to develop, but can not figure out how to get migrations working with our test- and mainnet.

## Steps to Reproduce

In truffle-config I tried:

```
  networks: {
    development: {           
      host: '127.0.0.1',    
      port: 7545,            
      network_id: '*',       
      gas: 10000000
    },
    testnet: {
      provider: () => new HDWalletProvider({providerOrUrl: 'https://nodeapi.test.energi.network'}),
      network_id: 49797,
      from: '0x...' // owner of contracts. Must hold test NRG for gas.
    },
    mainnet: {
      provider: () => new HDWalletProvider({providerOrUrl: 'https://nodeapi.energi.network'}),
      network_id: 39797,
      from: '0x0000000000000000000000000000000000000000' // owner of contracts. Must hold NRG for gas.
    } 
```
## Expected Behavior

I expected Truffle to connect to the testnet so I can start the migration.

## Actual Results

Keep getting this:
TypeError: Cannot use 'in' operator to search for 'providerOrUrl' in https://nodeapi.test.energi.network.
Does this error indicate that I am using the wrong params on HDWalletProviders or do we have to reconfigure our testnet API?

## Environment

* Operating System: Win10
* Ethereum client: Ganache CLI v6.12.2 (ganache-core: 2.13.2)
* Truffle version (`truffle version`): v5.1.63
* node version (`node --version`): v14.15.4
* npm version (`npm --version`): v6.14.10

**Comment by eshaben** [comment]
@TobyKreiselmaier thanks for filing the issue. Is there anything we need to know about connecting to  https://nodeapi.test.energi.network?

**Comment by TobyKreiselmaier** [comment]
@eshaben As a matter of fact we had to renew some certificates on our testnet nodes. Now everything works fine. But thanks for reaching out.
