### ISSUE TITLE
Add sourcelist parameter to build artifacts

### ISSUE THREAD

**Issue by JoranHonig** [trufflesuite/truffle#3800]
## Description
Truffle compilation artefacts do not include source list information; this makes it impossible to resolve any locations from the compilation artefacts provided by Truffle back to the source code.

With this feature, any tool that interacts with contracts compiled by Truffle will give accurate source results.
These tools include:
- Binary security analysis tools
- Chain state introspection tools
- Debugging tools

### Proposed Implmentation

The solc compiler output includes a sources object (see [docs](https://docs.soliditylang.org/en/latest/using-the-compiler.html?highlight=combined-json#output-description)). 
This information must end up in Truffle's compilation artefacts to resolve entries in the bytecode source maps.

This extension could be implemented in two ways:
1. Add the sources object as reported by the compiler to the compilation artefacts reported by Truffle.
2. Parse the sources object as reported by solc and use it to construct a list of sources. 

```
"sources": ["contracts/ContractA.sol", "contracts/ContractB.sol"],
```
The position of each contract in the array would correspond to the identifier of the source as used in source maps.

**Comment by gnidan** [comment]
@JoranHonig since you and I are working closely on a solution to your problem using @truffle/db, I'm going to close this as wont-fix.
