### ISSUE TITLE
Response object from transaction execution is different with '--stacktrace'

### ISSUE THREAD

**Issue by JasperTimm** [trufflesuite/truffle#3817]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
(I've raised this in Spectrum, see link [here](https://spectrum.chat/trufflesuite/truffle/decoding-events-within-truffle-test-tx-receipt~7664990c-1e69-40e6-9139-75610fb31f80)
---------------------------

## Issue

Within a .js test run by 'truffle test', when running a transaction on a contract with Truffle contract abstraction, the response object is different depending on whether the '--stacktrace' option is used or not.

## Steps to Reproduce
Within a .js test within a Truffle project:

`const MyContract = artifacts.require('MyContract')
let cc = await MyContract.new()
let resp = await cc.myMethod()
console.log(resp)`

run with `npx truffle test` and then `npx truffle test --stacktrace`

## Expected Behavior

The results should be the same

## Actual Results

With --stacktrace: 
`{ to: '0x57Dae64f612f50D10381476fAafd625fB3552652', from: '0x821aEa9a577a9b44299B9c15c88cf3087F3b5544', contractAddress: null, transactionIndex: 0, gasUsed: BigNumber { _hex: '0x73df' }, logsBloom: '...', blockHash: '0xfb3050693a87cf8d9ab01d690036c769b7801805426bf1ae01f9bc77d1d090b8', transactionHash: '0xc084cac0c1b152406514758dfbc406eb8a9f07a96a33dcbb5cec5b508f87c9ab', logs: [], blockNumber: 17, confirmations: 1, cumulativeGasUsed: BigNumber { _hex: '0x73df' }, status: 1, byzantium: true }`

Without --stacktrace: 
`{ tx: '0xc084cac0c1b152406514758dfbc406eb8a9f07a96a33dcbb5cec5b508f87c9ab', receipt: { transactionHash: '0xc084cac0c1b152406514758dfbc406eb8a9f07a96a33dcbb5cec5b508f87c9ab', transactionIndex: 0, blockHash: '0x2a6cf25e8f749c2541d3acf95afa5a8d6f8aa0e39f31969e5e15d9b945be68a3', blockNumber: 17, from: '0x821aea9a577a9b44299b9c15c88cf3087f3b5544', to: '0x57dae64f612f50d10381476faafd625fb3552652', gasUsed: 29663, cumulativeGasUsed: 29663, contractAddress: null, logs: [], status: true, logsBloom: '...', rawLogs: [] }, logs: [] }`

## Environment

* Operating System: MacOS 10.15.7
* Ethereum client: Infura node
* Truffle version (`truffle version`):
`Truffle v5.1.66 (core: 5.1.66)
Solidity - 0.6.12 (solc-js)
Node v10.23.0
Web3.js v1.2.9`
* npm version (`npm --version`): 6.14.8

**Comment by haltman-at** [comment]
Aha, thanks for opening this!  The good news is I didn't wait for you to open this, and already went ahead and fixed this in #3816. :)  It'll go out in today's release.  Thanks again for the report!

**Comment by haltman-at** [comment]
This is released now, closing!
