### ISSUE TITLE
Create encoding and overload resolution interface for Truffle Codec

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3819]
## Issue

Create an encoding interface for Truffle Codec.  Truffle Codec currently has encoding functionality, but the input needs to be in the decoder output format.  The intent is to create a more usable wrapping and encoding interface that can take user input.  It should be able to take user input in a number of forms -- e.g., numbers should be enterable as `number`s, as numeric strings, as `BN`s, etc.  Enums should be enterable by numeric value or by name.  Etc.  It should support all currently supported input forms.  It should also support ENS resolution for address and contract types.

The intent of this encoding interface is that it will be used in the Truffle Contract rewrite, so it should also handle overload resolution as well.  This also means it has to be able to handle the presence of an `options` argument.

Related: #3506, #2868, #2679, #737.

**Comment by leeftk** [comment]
Issue was fixed with newest version of Truffle.
