### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by manishlamichhane** [trufflesuite/truffle#382]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

I am using Truffle Builder version 2.0 in Truffle 3.0. Everything builds well. When I go to the localhost:8080, there is an error message in browser console "Uncaught SyntaxError: Unexpected token import". 
I learned it has got something to do with Webpack V2 beta as mentioned here: https://github.com/webpack/webpack.js.org/issues/445

**Comment by jkcailteux** [comment]
Same problem. The webpack example is broken out of the box.

**Comment by manishlamichhane** [comment]
@jkcailteux any updates on this issue? Did you find any solution?

**Comment by ImSolitude** [comment]
+1

**Comment by gnidan** [comment]
This issue is pretty old, so I'm gonna close it. Feel free to comment with more information if it is still relevant to you. Thanks!
