### ISSUE TITLE
Support of solidity new overflow and divide by 0 error messages

### ISSUE THREAD

**Issue by sirhill** [trufflesuite/truffle#3873]
## Issue

Solidity are now preventing overflow and division by 0 errors which were previously managed by `SafeMath.sol` lib.
As stated by @chriseth, solidity should now returns nice error messages.

It's interesting to note that ganache support partially this as it may returns out-of-bounds in the case of positive overflows (both for `add` and `mul`).
 

## Steps to Reproduce

```
contract SafeMath {

  function mul(uint256 a, uint256 b) public pure returns (uint256 c) {
    return a * b;
  }

  function div(uint256 a, uint256 b) public pure returns (uint256) {
    return a / b;
  }

  function sub(uint256 a, uint256 b) public pure returns (uint256) {
    return a - b;
  }

  function add(uint256 a, uint256 b) public pure returns (uint256 c) {
    return a + b;
  }
}
```

## Expected Behavior

A nice error message saying the call or the transaction reverted due of an overflow error or a division by 0.

## Actual Results

In truffle (rpc@ropsten):

As a call:
```
truffle(goerli01)> safeMath.add(MAX_UINT, 1).then((x) => x.toString())
'35408467139433450592217433187231851964531694900788300625387963629091585785856'
```

As a transaction:
``` reason: undefined,
  hijackedStack: 'StatusError: Transaction: 0x......  exited with an error (status 0). \n' +
    '     Please check that the transaction:\n' +
    '     - satisfies all conditions set by Solidity `require` statements.\n' +
    '     - does not trigger a Solidity `revert` statement.\n' +
    '\n' +
    '    at Object.receipt (/home/node/.config/yarn/global/node_modules/truffle/build/webpack:/packages/contract/lib/handlers.js:128:1)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    '    at Function.start (/home/node/.config/yarn/global/node_modules/truffle/build/webpack:/packages/contract/lib/override.js:49:1)'
}
```

In Ganache
```
  1) Contract: SafeMath
       should prevent add overflow:
     AssertionError: Expected 'invalid opcode', got Error: value out-of-bounds (argument="a", value=-1, code=INVALID_ARGUMENT, version=abi/5.0.0-beta.153) instead
      at module.exports (test/helpers/assertJump.js:12:5)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at Context.<anonymous> (test/math/SafeMath.js:23:5)

  2) Contract: SafeMath
       should prevent sub overflow:
     AssertionError: Expected 'invalid opcode', got Error: Returned error: VM Exception while processing transaction: revert instead
      at module.exports (test/helpers/assertJump.js:12:5)
      at Context.<anonymous> (test/math/SafeMath.js:32:5)
```

## Environment

bash-5.1$ truffle version
Truffle v5.1.66 (core: 5.1.66)
Solidity - 0.8.1 (solc-js)
Node v14.15.4
Web3.js v1.2.9

**Comment by haltman-at** [comment]
Worth noting, we do support this in `truffle test --stacktrace`. :)  But I agree, it would be good to support this more generally!  Of course some of this is a Ganache matter, so I'll ping @davidmurdoch here.  Also some of this may have to wait as it may require rewriting quite a bit, so not all of this will be coming so soon...

**Comment by haltman-at** [comment]
In more detail -- the first problem you point out actually has nothing to do with the new panics; if you used a revert message there instead, you'd see that that also currently doesn't work properly!  Fixing that case is I'm hard I'm afraid, but we're working on it.

The second case, again, fixing that is also troublesome, but we're working on it.  At least, if I understand it correctly -- there's not a lot of detail there.  Like, I'm not clear on why you're looking at `hijackedStack`?  What about the actual main stacktrace?  (Not that you'll get a good error message there either, but it would seem to be the more relevant thing to look at?)

As for the last of these, with Ganache... I'm not entirely clear on what you're doing there, so I'm not entirely clear on what the issue is.  Still, you might want to file a separate issue [there](https://github.com/trufflesuite/ganache-core/) regarding whatever the problem is.  It is true that Ganache does not currently have handling for the new panics.

**Comment by sirhill** [comment]
This issue not urgent. It's neither business critical or blocking.
I've reported for general improvement as I think it shall improve the developer experience.

All the logs provided refers to the same issue but in different context.
In the first two, I am using truffle on goerli (ie through geth rpc)
1) is a call (the natural use since the function are pure),
2) is a force transaction to see how the transaction will be reverted. If desired I can definetely provide you with the Tx hash but the only interested part where there is the reason of what it fails is in the hijack part of the result.

The last one, is using ganache and chai on testcases of SafeMath.
My testcase was designed for 0.6.12 and hence expect the invalid opcode result.
You may find it here:
https://github.com/c-layer/contracts/blob/d2605ee58bc89941c1e2da61077d1f441914fe6f/common/test/math/SafeMath.js#L22
However here the same testcases are run against a 0.8.1 compiled contract which does not use the usual SafeMath assert.
What's interesting is that the exception is catched with a surprisingly `out-of-bounds exception` and return a specific message when the overflow is on the upper bound (`add` and `mul`). However, we only have a trivial VM Exception when the overflow is from the lower bound (`sub`) or when there is a divide by 0 (`div`)

I hope the context of the different logs are clearer now.

**Comment by haltman-at** [comment]
OK, thanks for the extra info!

**Comment by lsqproduction** [comment]
added in release v5.5.3
