### ISSUE TITLE
Can't compile contracts from another npm package

### ISSUE THREAD

**Issue by gagarin55** [trufflesuite/truffle#388]
## Issue

Can't compile contracts from /node_modules/_pkg_/contracts directory

## Steps to Reproduce

1. I've created new truffle init project and published it as git repository. (https://github.com/gagarin55/test1-contracts)
2. In another project I did `npm i -S https://github.com/gagarin55/test1-contracts.git`
3. In `truffle-config.js` I've added following settings:
```
contracts_directory: './node_modules/test1-contracts/contracts/'
```
4. Run `truffle compile`

## Expected Behavior

I expect compiled contracts in ./build directory

## Actual Results
```bash
$ truffle compile
Compiling ./node_modules/test1-contracts/contracts/ConvertLib.sol...
Compiling node_modules/test1-contracts/contracts/ConvertLib.sol...
Compiling node_modules/test1-contracts/contracts/MetaCoin.sol...
Compiling node_modules/test1-contracts/contracts/Migrations.sol...

node_modules/test1-contracts/contracts/ConvertLib.sol:3:1: Error: Library "ConvertLib" declared twice (will create ambiguities during linking).
library ConvertLib{
^
Spanning multiple lines.
The other declaration is here: /home/proj1/node_modules/test1-contracts/contracts/ConvertLib.sol:3:1: 
library ConvertLib{
^
Spanning multiple lines.
Compiliation failed. See above.
```

## Environment

* Operating System: Ubuntu 16.10

* Truffle version: Truffle v3.2.1

* node version: v6.10.1

* npm version:  3.10.10

**Comment by gagarin55** [comment]
Anybody here ?

**Comment by waglik** [comment]
@gagarin55 not sure if same issue but I had this problem because my contract was missing version pragma. I've added 
    pragma solidity ^0.4.4;

to my contract and it solved my problem.
