### ISSUE TITLE
Final txlog has intermediates that should be deleted

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3884]
## Issue

Sometimes a final txlog will have nodes with `waitingForFunctionDefinition` properties.  Those should all be deleted in the final txlog.  I'll have to see what's causing that.

Repro notes: @cds-amal `balance-core` repo, test `test/factory.js` yields some of these?

## Environment

* Truffle version (`truffle version`): 5.1.67

**Comment by cds-amal** [comment]
@haltman-at correct. there were 8 txlogs with `waitingForFunctionDefintion` properties. Interestingly, those were the transactions that had an internal tree node of type `callinternal` with without `functionName` with children (actions ) of other `callinternal` nodes.

**Comment by haltman-at** [comment]
Hey, @cds-amal, I can't seem to reproduce this via the specified means on current Truffle?

**Comment by haltman-at** [comment]
OK, I've finally managed to reproduce this!  (Totally by accident.)  I was using the `viz-test` example project in the `solidity-test-cases` repo, except that I commented out lines 26-44.  I then ran `VizTest.test(683)`, and indeed I saw a `waitingForFunctionDefinition` in the output!  So, I'll have to figure out what's up with that.

**Comment by haltman-at** [comment]
This should be fixed now.
