### ISSUE TITLE
truffle migration can not migrate my contracts to kovan 

### ISSUE THREAD

**Issue by chekuris** [trufflesuite/truffle#3886]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I am trying to migrate my contract to kovan testnet  and cannot migrate my contracts after they have successfully compiled. and deploying in development .

## Steps to Reproduce

truffle migrate —-network kovan   

## Expected Behavior

Should deploy in to kovan testnet
## Actual Results

 >$ truffle migrate —-network kovan

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Network up to date.

After this message nothing happens.No error message or nothing

## Environment

* Operating System: Mac OS 10.15.7
* Ethereum client: vscode

* Truffle version (`truffle version`): Truffle v5.1.67
* node version (`node --version`):v10.20.1
* npm version (`npm --version`): 6.14.4

- my truffle-config.js
- 
const HDWalletProvider = require('truffle-hdwallet-provider-privkey');
const privateKey = "keyphrace..xxxx";
const endpointUrl = "https://kovan.infura.io/v3/78f2375e307d459cxxxxxxxxxx";

module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "5777",
    },
    kovan: {
      provider: function() {
        return new HDWalletProvider(
          //private keys array
          [privateKey],
          //url to ethereum node
          endpointUrl
        )
      },
      gas: 5000000,
      gasPrice: 25000000000,
      network_id: 42
    }
  }
}

**Comment by eggplantzzz** [comment]
@chekuris I've experienced people having issues sometimes with some of these other wallet packages. Note that truffle-hdwallet-provider-privkey is not an official Truffle library. Can you try using @truffle/hdwallet-provider to create your provider and let me know if you still have issues?

**Comment by chekuris** [comment]
issue got solved.
thanks @eggplantzzz
