### ISSUE TITLE
Ensure proper use of `import type` in Typescript packages

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3908]
## Issue

Turns out that if you're just importing types, but you use ordinary `import` rather than `import type`, Typescript, well, treats it like an actual import.  We should go over the existing Typescript code and make sure it uses `import type` where possible in order to help keep bundle size down, etc.

## Environment

* Truffle version (`truffle version`): 5.2.3

**Comment by gnidan** [comment]
This change has been released in [Truffle v5.4.7](https://github.com/trufflesuite/truffle/releases/tag/v5.4.7).
