### ISSUE TITLE
Can't install Truffle on Mac OSX

### ISSUE THREAD

**Issue by GregoryFenn** [trufflesuite/truffle#391]
[errorsInInstallingTruffle.txt](https://github.com/trufflesuite/truffle/files/926552/errorsInInstallingTruffle.txt)

## Issue

**What the issue is, in broad strokes.**

'$npm install -g truffle' succeeds part-way then fails. 

## Steps to Reproduce

**Please provide the shortest amount of steps to reproduce your issue.**

   $ npm install -g truffle

## Expected Behavior

**What you expected to happen.**

Install truffle.

## Actual Results

**What actually happened. Please give examples and support it with screenshots, copied output or error messages.**

    SolidityProjects$ npm install -g truffle
npm WARN deprecated libp2p-ipfs@0.15.0: Renamed to libp2p-ipfs-nodejs
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/cli.js
/usr/local/bin/truffle-exec -> /usr/local/lib/node_modules/truffle/exec.js

> fsevents@1.1.1 install /usr/local/lib/node_modules/truffle/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/truffle/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> sha3@1.2.0 install /usr/local/lib/node_modules/truffle/node_modules/sha3
> node-gyp rebuild

  CXX(target) Release/obj.target/sha3/src/addon.o
c++: error: unrecognized command line option ‘-stdlib=libc++’
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/truffle/node_modules/sha3
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "-g" "truffle"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/GFenn/.npm/_logs/2017-04-17T19_41_07_911Z-debug.log

    SolidityProjects$ cat /Users/GFenn/.npm/_logs/2017-04-17T19_41_07_911Z-debug.log
92046 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/string_decoder
92047 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/stringstream
92048 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/strip-ansi
92049 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/string-width
92050 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/strip-json-comments
92051 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/rc
92052 silly finalize /usr/local/lib/node_modules/truffle/node_modules/fsevents/node_modules/supports-color
........
102543 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/truffle/node_modules
102544 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/truffle/node_modules
102545 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/truffle/node_modules
102546 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102547 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102548 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102549 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102550 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102551 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102552 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102553 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
102554 silly rollbackFailedOptional Finishing
102555 silly runTopLevelLifecycles Finishing
102556 silly install printInstalled
102557 verbose stack Error: sha3@1.2.0 install: `node-gyp rebuild`
102557 verbose stack Exit status 1
102557 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
102557 verbose stack     at emitTwo (events.js:106:13)
102557 verbose stack     at EventEmitter.emit (events.js:194:7)
102557 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
102557 verbose stack     at emitTwo (events.js:106:13)
102557 verbose stack     at ChildProcess.emit (events.js:194:7)
102557 verbose stack     at maybeClose (internal/child_process.js:899:16)
102557 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
102558 verbose pkgid sha3@1.2.0
102559 verbose cwd /Users/GFenn/Library/Mobile Documents/com~apple~CloudDocs/SolidityProjects
102560 error Darwin 16.5.0
102561 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "-g" "truffle"
102562 error node v7.9.0
102563 error npm  v4.2.0
102564 error code ELIFECYCLE
102565 error errno 1
102566 error sha3@1.2.0 install: `node-gyp rebuild`
102566 error Exit status 1
102567 error Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
102567 error Make sure you have the latest version of node.js and npm installed.
102567 error If you do, this is most likely a problem with the sha3 package,
102567 error not with npm itself.
102567 error Tell the author that this fails on your system:
102567 error     node-gyp rebuild
102567 error You can get information on how to open an issue for this project with:
102567 error     npm bugs sha3
102567 error Or if that isn't available, you can get their info via:
102567 error     npm owner ls sha3
102567 error There is likely additional logging output above.
102568 verbose exit [ 1, true ]
    SolidityProjects$ 

## Environment

* Operating System: OSX 10.12.4

* Truffle version: Most recent?

* Ethereum client: geth [? is this what you mean...]

    SolidityProjects$ geth
    INFO [04-17|20:56:36] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
    INFO [04-17|20:56:39] Initialising Ethereum protocol           versions="[63 62]" network=1

* node version: v7.9.0

* npm version: 4.2.0

**Comment by nickgs** [comment]
Hey Gregory, 

I've experienced this error in a few situations but not with this project. I am running your same environment and was able to install truffle without any issues.  

A few things you can look at: 

1. Make sure you have the Xcode command line tools installed. 
2. Make sure you have Python 2.7 in your path (above 3.0 if installed) 
3. If this above doesn't help try just installing `sha3` package, this may give you some more verbose error messages. 

Just a few thoughts... good luck!

**Comment by tcoulter** [comment]
Hi there. A new beta has been pushed out that should fix this issue. Details in the blog post [here](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). Can you give it a shot and report back?

**Comment by JMarcosSF** [comment]
@tcoulter `npm install -g truffle@beta` works fine for me running Mac OS Sierra v10.12.5

Now onto dev. Thanks!

**Comment by driscollco** [comment]
$ npm install truffle-contract
-bash: $: command not found

**Comment by lester-B-Cool** [comment]
same issue

> $ npm install truffle-contract
> -bash: $: command not found

same issue for me

**Comment by wpollock12** [comment]
> same issue
> 
> > $ npm install truffle-contract
> > -bash: $: command not found
> 
> same issue for me

I had the same issues until i realized i'd copied the whole line from the truffle GitHub repo.  Remove the "$"

**Comment by natysav** [comment]
> Hey Gregory,
> 
> I've experienced this error in a few situations but not with this project. I am running your same environment and was able to install truffle without any issues.
> 
> A few things you can look at:
> 
> 1. Make sure you have the Xcode command line tools installed.
> 2. Make sure you have Python 2.7 in your path (above 3.0 if installed)
> 3. If this above doesn't help try just installing `sha3` package, this may give you some more verbose error messages.
> 
> Just a few thoughts... good luck!

Had the same issue, fixed by installing Xcode. Thanks
