### ISSUE TITLE
Truffle not installing

### ISSUE THREAD

**Issue by dto26** [trufflesuite/truffle#3910]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

sudo npm install truffle -g

## Expected Behavior

Expected truffle to install

## Actual Results

[         .........] / idealTree: timing idealTree Completed in 18219ms

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Pauses about half way and fails with above error message

## Environment

* Operating System: Ubuntu 20.04
* Ethereum client:
* Truffle version (`5.2.3`):
* node version (`10.19.0`):
* npm version (`7.5.3`):

**Comment by eggplantzzz** [comment]
Hmm it looks like it is running out of memory for some reason. Do you happen to be on a machine with very little memory? Also, you shouldn't use `sudo` when installing Truffle as it can cause all sorts of permissions issues. You should probably use npm with a Node version manager like nvm which is what npm recommends. See [this npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

**Comment by gnidan** [comment]
Closing this for issue maintenance. If you're still running into this, please let us know and we'll be happy to re-open. Thank you.

**Comment by anoopmd** [comment]
Faced the same problem on Ubuntu 18. Running npm install without sudo worked !

**Comment by hadialqattan** [comment]
> Faced the same problem on Ubuntu 18. Running npm install without sudo worked !

Me too. Until I fixed the EACCES permissions errors (can't install anything globally without sudo). [The official fix](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).
