### ISSUE TITLE
Investigate Truffle's incompatibilities with Geth 1.10.0

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#3912]
It seems that since Geth updated to 1.10.1, Truffle's CI has been consistently failing. The main change that occurred in that release was that the Berlin hard-fork was enabled. See [the release notes](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.1). When Geth was pinned to 1.9.25 CI seemed to run successfully (see https://github.com/trufflesuite/truffle/pull/3911).

~Since the Berlin hard-fork is scheduled for mid-April, we need to investigate what Truffle needs to do to be compliant.~

**Update**: It turns out that the real incompatibility has to do with a functionality that Geth enabled in v1.10.0. As of that version they disallow transactions that are not compliant with EIP-115. This causes Truffle's transactions to fail.

**Comment by gabmontes** [comment]
@eggplantzzz I can confirm the incompatibility. It is easy to reproduce:

```js
const HDWalletProvider = require('@truffle/hdwallet-provider')
const Web3 = require('web3')

const provider = new HDWalletProvider({
  addressIndex: 0,
  mnemonic: "your 12 words",
  numberOfAddresses: 1,
  providerOrUrl: "http://a.geth.1.10.node.url"
})
const web3 = new Web3(provider)
const address = provider.getAddress(0)

web3.eth.sendTransaction({ from: address, to: address, gas: 21000, value: '1' })
  .then(console.log)
  .catch(console.error)
  .finally(function () {
    provider.engine.stop()
  })
```

That will result in an error saying `only replay-protected (EIP-155) transactions allowed over RPC`.

And by the way, it is EIP-155, enabled in https://github.com/ethereum/go-ethereum/pull/22339, not EIP-115.

**Comment by tcoulter** [comment]
Update as of 3/15: 

- We can get mainnet and major testnets quickly
- Dev versions of geth may take more work

Plan: 

- Get it working with Ropsten, etc.
- Figure out if we need anything extra for `--dev` (custom geth network).

**Comment by eggplantzzz** [comment]
See https://github.com/trufflesuite/truffle/pull/3923 for work resolving this. I believe this may also work for custom testnets as well.
