### ISSUE TITLE
How to support EIP155 transaction for truffle migrate?

### ISSUE THREAD

**Issue by lolieatapple** [trufflesuite/truffle#3922]
How to support EIP155 transaction for truffle migrate?

Ethereum new version doesn't support no chainId protect transaction any more.

I saw the code of @truffle/hdwallet-provider there is no chainId value when call signTransaction.

node_modules/@truffle/hdwallet-provider/dist/index.js  Line: 146, no chainId in txParam.

So how to support EIP155 transaction for truffle migrate?

**Comment by gnidan** [comment]
Follow this PR #3923 :)

Should be fixed this week

**Comment by lolieatapple** [comment]
Great! Thanks!
