### ISSUE TITLE
Got Type Error when executed - exec gas_estimates.js

### ISSUE THREAD

**Issue by brucedegar** [trufflesuite/truffle#3932]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
## Issue
I followed the tutorial on this - https://github.com/ethereumbook/ethereumbook/blob/develop/07smart-contracts-solidity.asciidoc

**I am stuck at this step:**
truffle(develop)> exec gas_estimates.js
Using network 'develop'.

TypeError: fn is not a function
    at Object.exec (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:127:1)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at bound exec (internal/util.js:296:12)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/exec.js:80:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)

## Steps to Reproduce
<img width="367" alt="image" src="https://user-images.githubusercontent.com/23182135/111853212-27ad2a80-896e-11eb-8b2f-c7d93773d478.png">

```
var FaucetContract = artifacts.require("Faucet.sol");
FaucetContract.web3.eth.getGasPrice(function(error, result) {
```
I've tried with 
artifacts.require("Faucet") OR artifacts.require("./Faucet.sol")

but still no luck.
## Expected Behavior
$ truffle develop

truffle(develop)> exec gas_estimates.js
Using network 'develop'.

Gas Price is 20000000000 wei
gas estimation = 31397 units
gas cost estimation = 627940000000000 wei
gas cost estimation = 0.00062794 ether

## Actual Results
TypeError: fn is not a function

## Environment
* Operating System: MAC OS Catalina
* Truffle v5.1.67 (core: 5.1.67)
* Solidity - 0.4.22 (solc-js)
* Node v14.15.4
* Web3.js v1.2.9

**Comment by eggplantzzz** [comment]
@brucedegar Can you provide us with a code example and some specific steps to help us try and troubleshoot this? Thanks!

**Comment by fainashalts** [comment]
Closing for issue maintenance. Please open a new issue of this problem persists. Thanks!
