### ISSUE TITLE
Contract deployed to mainnet, but not locally

### ISSUE THREAD

**Issue by collect-coder** [trufflesuite/truffle#3937]
- [no] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Contract was deployed to mainnet, but at the end I got an error that  **insufficient funds for gas * price + value**, and  deployment stopped. But the contracts were successfully created on the mainnet (the Migration, one Lib and one ERC721)

I was charged for the contract creations, and now migrate wants to redeploy them, what will charge me again. I did several dry runs to reach a comfortable gas price and amount, but in the end I was surprised by this. And I still had balance for the final complete call.

## Steps to Reproduce

There should be a combination of gas and balance that will pass on the dry-runs but still require some more in the end and cause this. I did this exact same deployment on Rinkeby twice and never had any problems. I noticed that my balance on the dry-runs were a little lower than my my actual balance, but still was enough for deployment, according to the dry-run.

Since I was able to see the contracts on the mainnet, I manually added the contract addresses to the local json build (copy networks structure from Rinkeby), and executed **setComplete(2)** with **MyCrypto**. After that, migrate does not try to re-deploy but also does not update the local json files. I was able to **verify** all the contracts, and **I can access** them from the truffle console.

Everything seems normal in truffle, but when I connect **Drizzle and MetaMask**, it does not connect to the mainnet. I'm posting this here instead of on drizzle, because it's clear that there's something missing on the truffle deployment. My drizzle store is working perfectly with Ganache and Rinkeby.

This is my network config...
```
    mainnet: {
      provider: function() {
        return new HDWalletProvider(
          `${process.env.INFURA_MNEMONIC}`, 
          `https://mainnet.infura.io/v3/${process.env.INFURA_ID}`,
          // `wss://mainnet.infura.io/ws/v3/${process.env.INFURA_ID}`,
          1 // Metamask 2nd connected account
        ) },
      gas: 100000, // for working on the console, was defaulted during deployment
      gasPrice: 110000000000, // 110 gwei
      networkCheckTimeout: 10000000,
      network_id: 1
    }
```

Drizzle fails to initialize with this..
```
TypeError: Cannot read property 'address' of undefined
    at getOrCreateWeb3Contract (drizzle-store.js?9126:13391)
    at Drizzle.addContract (drizzle-store.js?9126:13428)
    at runCallEffect (proc.js?0d31:513)
    at runEffect (proc.js?0d31:435)

```
..which leads here...
```
var getOrCreateWeb3Contract = function getOrCreateWeb3Contract(store, contractConfig, web3) {
  if (contractConfig.web3Contract) {
    return contractConfig.web3Contract;
  }
  var state = store.getState();
  var networkId = state.web3 && state.web3.networkId;
  var selectedAccount = state.accounts[0];
  var abi = contractConfig.abi,
      networks = contractConfig.networks,
      deployedBytecode = contractConfig.deployedBytecode;
  return new web3.eth.Contract(abi, networks[networkId].address, { // <<<<<< network is missing
    from: selectedAccount,
    data: deployedBytecode
  });
};

```
Looks like there is just a little thing missing to link the contracts to the network for drizzle....

## Expected Behavior

I expected that migrate could still use the deployed contracts and just rebuild the local json files. I don't want to lose the deployed contracts and all the gas that was used, and have multiple identical contracts deployed. 

Migrate should be able understand that the contracts were deployed successfully, and continue where it stopped on the nedt try.

Or a way to import an existing contract?

Or just update the local deployment? The source files and build have not changed after the failed deployment, all the necessary data should be right here. I was even able to verify!

I think this can happen also if the process stops with the 750 seconds timeout. It even says the transaction can be mined and completed. If it is, what then?

## Actual Results

Migrate wants me to deploy again a **perfectly working contract** it deployed.

## Environment

* Operating System: macOS 10.15.7
* Ethereum client: Infura
* Truffle v5.1.67 (core: 5.1.67)
* truffle/hdwallet-provider 1.2.3
* drizzle/store 1.5.3
* Solidity - 0.7.6 (solc-js)
* Node v15.10.0
* Web3.js v1.2.9
* npm version (7.5.6):

**Comment by collect-coder** [comment]
I have solved my drizzle problem, it was not related to this contract's deployment. There are some other undeployed contracts that it was trying to read and halting drizzle to properly initialize.

My fix editing the json files seems to be working so far. But anyway, the dry-run/migrate gave me some good headache.
All the problems I had with this deployment could be avoided if migrate could remember the contract addresses that were deployed successfully to the network.

**Comment by collect-coder** [comment]
And it happened again!
`insufficient funds for gas * price + value`
Sent 7000000 gas * 100 gwei, that's 0.7 ETH
Spent ˜6200000 gas, my balance of 0,97 ETH should be enough, but it isn't.
I do have funds, where is this math coming from?

**Comment by eggplantzzz** [comment]
Hey @collect-coder sorry for the delayed response. Sorry about the trouble, I'm not sure why that happened during the migration. If you want to get around running migrations you can load a contract from its address as follows:
```javascript
const MyContract = artifacts.require("MyContract");
const instance = MyContract.at("<addressOfDeployedContract>");
//... do stuff with instance
```

I don't know if this helps...sorry I can't give you more insight on the gas issues. During migrations it should give you some sort of report on gas usage etc.

**Comment by gnidan** [comment]
Closing this for issue maintenance. Happy to re-open if you get the chance to get back to us. Sorry that you ran into this problem!

**Comment by collect-coder** [comment]
Already happening back in #3888
