### ISSUE TITLE
Final Web3.js command

### ISSUE THREAD

**Issue by RobertoDonPedro** [trufflesuite/truffle#3938]
Is there a way to output or log the final web3.js call that truffle poduces when calling a smart contract function? 

E.g. Truffle:
```
    const myContract = await MySmartContract.deployed()
    const tx = await myContract.myFunction(param1 = "AA")
```

Final Web3 command:
```
  web3ContractInstance.methods.myFunction(param1 = "AA").send({from: 0x1212...}))
```

**Comment by eggplantzzz** [comment]
Hey @RobertoDonPedro, currently you can't do this. You want to just log the last contract method that was called? Under the hood Truffle uses `web3.eth.sendTransaction` when executing those contract methods. Is there more that you wanted to know about this?

**Comment by cds-amal** [comment]
Hi @RobertoDonPedro, closing this issue for maintenance. Please comment if it's still a problem. Thanks!
