### ISSUE TITLE
Error "Migrations" -- invalid sender when I deploy to BSC testnet

### ISSUE THREAD

**Issue by DutchJSDev** [trufflesuite/truffle#3939]
I have created a standard OpenZeppelin ERC721PresetMinterPauserAutoId NFT smart contract. I have tested locally and it works, and I am trying to deploy it to the public testnet now. But then I get the following error: "Migrations" -- invalid sender. I used the following tutorial: https://docs.binance.org/smart-chain/developer/ERC721.html

I hope somebody can help me : )

**Comment by shoenseiwaso** [comment]
Possible dupe of #3935, #3913

**Comment by gabriellee82** [comment]
using @truffle/hdwallet-provider V1.2.3 works for me.

**Comment by shoenseiwaso** [comment]
> using @truffle/hdwallet-provider V1.2.3 works for me.

@gabriellee82 which node provider/node version are you using?

**Comment by gabriellee82** [comment]
Hi, I am using the following on windows 10:

Truffle v5.2.5 (core: 5.2.5)
Solidity v0.5.16 (solc-js)
Node v15.11.0
Web3.js v1.2.9

on BSC testnet.

**Comment by shoenseiwaso** [comment]
Which BSC Testnet node provider (or your own node)? And do you know the BSC node version?

I realize now that these issues might not be linked - I have not looked at if the BSC fork has implemented the chain ID enforcement or not...

**Comment by jerrkill** [comment]
Obviously it is caused by **hdwallet-provider**, just switch hdwallet-provider back to **1.2.2**. It looks like below
```
...
"@truffle/hdwallet-provider": "1.2.2",
...
```

**Comment by gabriellee82** [comment]
> Which BSC Testnet node provider (or your own node)? And do you know the BSC node version?
> 
> I realize now that these issues might not be linked - I have not looked at if the BSC fork has implemented the chain ID enforcement or not...

This is my truffle-config.js

      provider: () => new HDWalletProvider(mnemonic, `https://data-seed-prebsc-1-s1.binance.org:8545`),
      network_id: 97,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: true

**Comment by gabriellee82** [comment]
> Obviously it is caused by **hdwallet-provider**, just switch hdwallet-provider back to **1.2.2**. It looks like below
> 
> ```
> ...
> "@truffle/hdwallet-provider": "1.2.2",
> ...
> ```

Yes, seems like v1.2.4 is not working.

**Comment by DutchJSDev** [comment]
Meanwhile I fixed it by downgrading, as mentioned by @gabriellee82 . @gabriellee82 could you tell me why this is 'obvious'? Usually when one has not upgraded it would seem obvious to me that something doesn't work, not downgrading : )
