### ISSUE TITLE
Ethereum.Quorum support

### ISSUE THREAD

**Issue by rohitgkr** [trufflesuite/truffle#394]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
It appears that Truffle doesn't have the grammar or facility to support private transactions. In the context of Quorum (J.P Morgan's private ethereum block chain) I would like to deploy a contract into the private state of the target node using the constellation node's public key via [PrivateFor]. When will Truffle add support for Quorum which is the driver for Ethereum consortium network?
Cheers.

**Comment by ajunge** [comment]
Have you tried adding the privateFor parameter on the deployer?

**Comment by rohitgkr** [comment]
Hi @ajunge. I haven't been able to figure out how to bootstrap private for using the deployer JS object. The parameters deploy() takes are arguments for the contract constructor. Can you please provide an example call or script that can potentially address this issue? The only way I can think of is to directly use web3 API from within the deployer code. For ex -
var c = web3.eth.contract(contract.interface);
c.new({
privateFor:<public key>
}); 

Is there an equivalent version of the above that can be integrated/customised in Truffle migrations scripts? Thanks.

**Comment by vjrantal** [comment]
@rohitgkr It looks like if you have a file like `2_deploy_contracts.js` in the `migrations` folder with contents like:

```
var Telemetry = artifacts.require('./Telemetry.sol');

module.exports = function(deployer) {
  deployer.deploy(Telemetry, {
    privateFor: ['ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=']
  });
};
```

Above seems to result in passing the `privateFor` property as expected when the contract is deployed.

Here is a screenshot from Wireshark that shows what above ends up sending over the wire towards the JSON-RPC endpoint:

<img width="617" alt="screen shot 2017-05-10 at 11 03 22" src="https://cloud.githubusercontent.com/assets/207474/25888863/68177bda-3570-11e7-8c58-979665e3253e.png">

**Comment by tcoulter** [comment]
We've launched official support for Quorum with a [tutorial here](http://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains). Cheers!

**Comment by wtam** [comment]
Truffle migrate stuck with Quorum only when using raft using the 7Nodes example.  Is it a bug in truffle?

**Comment by shiqinfeng1** [comment]
I guess its a bug.  I got errors: 
```
BigNumber Error: new BigNumber() not a number: [object Object]
      at raise (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:38210:25)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:38198:33
      at new BigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37226:67)
      at new BigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37236:25)
      at toBigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:4152:12)
      at Object.toTwosComplement (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:4163:21)
      at SolidityTypeUInt.formatInputInt [as _inputFormatter] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:22788:38)
      at SolidityTypeUInt.SolidityType.encode (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:25369:17)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:46902:29
      at Array.map (native)
```
