### ISSUE TITLE
"Migrations" -- transaction could not be decoded: could not recover secp256k1 key: calculated Rx is larger than curve P.

### ISSUE THREAD

**Issue by abcoathup** [trufflesuite/truffle#3940]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Migrations using Truffle 5.2.5 and Truffle HDWallet Provider 1.2.4 gives error `could not recover secp256k1 key`
Reverting to Truffle HDWallet Provider 1.2.3 can deploy with no error.

Reported in OpenZeppelin Community: https://forum.openzeppelin.com/t/migrations-transaction-could-not-be-decoded-could-not-recover-secp256k1-key-calculated-rx-is-larger-than-curve-p/6405

## Steps to Reproduce

Deploy Migrations contract to public testnet (using Truffle HDWallet Provider)
```js
const { alchemyApiKey, mnemonic } = require('./secrets.json');
const HDWalletProvider = require('@truffle/hdwallet-provider');

module.exports = {
  networks: {
    ropsten: {
      provider: () => new HDWalletProvider(mnemonic, `https://eth-ropsten.alchemyapi.io/v2/${alchemyApiKey}`),
      network_id: 3,       // Ropsten's id
      gas: 5500000,        // Ropsten has a lower block limit than mainnet
      confirmations: 2,    // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
    rinkeby: {
      provider: () => new HDWalletProvider(
        mnemonic, `https://eth-rinkeby.alchemyapi.io/v2/${alchemyApiKey}`
      ),
      network_id: 4,
      gasPrice: 10e9,
      skipDryRun: true
    }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.7.0",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  },
  db: {
    enabled: false
  }
};
```

```
$ npx truffle migrate --network ropsten --reset
```

## Expected Behavior

Migrations Contract should deploy

## Actual Results

```
$ npx truffle migrate --network rinkeby --reset

Compiling your contracts...
===========================
> Compiling ./contracts/Box.sol
> Compiling ./contracts/Migrations.sol
> Artifacts written to /home/abcoathup/projects/forum/bencong_he/build/contracts
> Compiled successfully using:
   - solc: 0.7.0+commit.9e61f92b.Emscripten.clang



Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 10000000 (0x989680)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- transaction could not be decoded: could not recover secp256k1 key: calculated Rx is larger than curve P.

    at /home/abcoathup/projects/forum/bencong_he/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.2.5 (core: 5.2.5)
Node v10.23.2
```

## Environment

* Operating System: WSL2 on Windows 10
* Truffle version (`truffle version`):
```
$ npx truffle version
Truffle v5.2.5 (core: 5.2.5)
Solidity - 0.7.0 (solc-js)
Node v10.23.2
Web3.js v1.2.9
```
Using Alchemy

**Comment by sbauch** [comment]
I can add some context here. This was mentioned to me in a private discord.

> We (go-ethereum) recently made the decision to disallow users from submitting transactions that are not signed with an eip155 signer. Infura has upgraded their infrastructure and disallows them now too. The problem is that truffle does not sign deployment transactions with an eip155 signer.
> Thus all deployment transactions are rejected by infura. Basically truffle needs to update their framework to use eip155 signers for deployments

**Comment by lopeselio** [comment]
I am facing the same issue. I tried updating all instantiations as shown in v1.2.5, but I still get the error

**Comment by PatrickAlphaC** [comment]
For the time being, you can set `"@truffle/hdwallet-provider": "1.0.40",`. This worked for me.

**Comment by lopeselio** [comment]
Thanks @PatrickAlphaC . It helped a lot.works fine with v1.2.1 as well.

**Comment by Robbiekruszynski** [comment]
Can confirm going from 1.2.4 to 1.2.2 worked for me

**Comment by ksdkamesh99** [comment]
Yes it worked me at v1.0.40

**Comment by aamirfarrukh** [comment]
"@truffle/hdwallet-provider": "1.0.40", 

is in package.json but still same error

I am using heroku, does the file needs to be pushed to github?

**Comment by aamirfarrukh** [comment]
> For the time being, you can set `"@truffle/hdwallet-provider": "1.0.40",` in your `package.json` This worked for me.

  "@truffle/hdwallet-provider": "1.0.40",
  in json file. same error

**Comment by eggplantzzz** [comment]
@abcoathup Is this still occurring on the most recent version of @truffle/hdwallet-provider (v1.2.6)?

**Comment by cds-amal** [comment]
Hi everyone, please try using `@truffle/hdwallet-provider` v1.4.0 to see if it resolves the issue.

**Comment by cds-amal** [comment]
Closing this for issue maintenance. Please comment if you'd like us to revisit
