### ISSUE TITLE
Got error etwork/artifact mismatch if no 2_deploy_contracts.js exist

### ISSUE THREAD

**Issue by tolak** [trufflesuite/truffle#3950]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Error: <MyContractr> has not been deployed to detected network (network/artifact mismatch)

## Steps to Reproduce

step1: Write a simple contract and unit test of the contract( just simply deploy it)
step2: Edit truffle-config.js, set port and networkid
step3: Execute ```truffle test```

* MAKE SURE NO 2_deploy_contracts.js EXIST*

## Expected Behavior

Test should be passed.

## Actual Results

Got error during deploy contract to the network as follows:

```sh
Error:<MyContract> has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:245:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:85:1)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (test/StakingTemplate.js:11:28)
```

## Environment

* Operating System: OSX 11.1
* Ethereum client: Ganache with hardfork Constantinople
* Truffle version (`truffle version`):
- Truffle v5.2.2 (core: 5.2.2)
- Solidity - 0.7.0 (solc-js)
- Node v14.4.0
- Web3.js v1.2.9

**Comment by eggplantzzz** [comment]
Can we see your test? Normally your contract would be deployed in the migration file that you referenced. Can you provide us with specific information about what you are doing here? Thanks!

**Comment by haltman-at** [comment]
More specifically, if you have a reproduction example we could check out, that would be helpful!

**Comment by cds-amal** [comment]
Hi @tolak, we're closing this for issue maintenance. Please comment if it's still an issue. thanks!
