### ISSUE TITLE
If tx is null, the deployment will be broken.

### ISSUE THREAD

**Issue by guanzhenxing** [trufflesuite/truffle#3960]
https://github.com/trufflesuite/truffle/blob/f669d4b5bb13aacd56e3601aab87cb0d2b6b0c40/packages/reporters/reporters/migrations-V5/reporter.js#L383

When I deploy contracts to Arbitrum Testnet, it often happens that tx is null. When tx==null, the deployment will run down!

This might happen on some nodes that use load balancing. The user is not connecting to the same node at the time of deployment as the node at the time of query, and the data on those nodes is out of sync.

I added `if (!tx) return this.postDeploy(data);` in my local area and it works fine, please evaluate if it can be modified in this way.

**Comment by eggplantzzz** [comment]
Hey @guanzhenxing, can you give us more info on how this fails?

**Comment by cds-amal** [comment]
Hi @guanzhenxing, we're  closing this for issue maintenance. Please comment if you'd like us to reopen. thanks!
