### ISSUE TITLE
Truffle migrate cannot handle a network ID different from the chain ID

### ISSUE THREAD

**Issue by shoenseiwaso** [trufflesuite/truffle#3961]
## Issue

@eggplantzzz @gnidan I think we found another corner case: no version of Truffle works if the chain ID is different from the network ID (i.e., I tried earlier versions than 5.3.0 as well).

Related/possibly related: #3935, #3957, #3953, #3949, #3946

## Steps to Reproduce

Follow the steps in the README in this repo. **Note that it has been updated for this issue since #3935 - please do a `git pull` if you had previously cloned it.**
https://github.com/curvegrid/truffle-eip155-issues

## Expected Behavior

Migration completes successfully.

## Actual Results

```
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- invalid sender.
```

## Environment

* Operating System: macOS 10.15.7
* Ethereum client: geth 1.10.1
* Truffle version (`truffle version`): Truffle v5.3.0 (core: 5.3.0)
* node version (`node --version`): v15.11.0
* npm version (`npm --version`): 7.0.14

**Comment by dasconnor** [comment]
This is a problem for compatibility with other EVM-based chains that use Truffle. I'm getting reports from users that the latest EIP-155 change broke compatibility with Avalanche and our Fuji testnet.

**Comment by Iffay3020** [comment]
Same Problem here but I get following message: 

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Wrong chainId.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by HankHoneymoon** [comment]
> Same Problem here but I get following message:
> 
> # `
> 1_initial_migration.js
> ## Deploying 'Migrations'
> Error: *** Deployment Failed ***
> 
> "Migrations" -- Wrong chainId.
> 
> ```
> at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
> at process._tickCallback (internal/process/next_tick.js:68:7)
> ```
> 
> `

Having the same problem. Definitely using the right chain ID (kovan:42) and tried both Aave v.1 and v.2 lendingpooladdressprovider addresses, but no dice.

**Comment by HankHoneymoon** [comment]
https://github.com/trufflesuite/truffle/issues/3946

HD-wallet seems to be an issue.

**Comment by Iffay3020** [comment]
> #3946
> 
> HD-wallet seems to be an issue.

Hmpf.. Im trying to migrate a contract since 3 days but not working..

**Comment by bitcoinbrisbane** [comment]
> > #3946
> > HD-wallet seems to be an issue.
> 
> Hmpf.. Im trying to migrate a contract since 3 days but not working..

Yeah same

**Comment by eggplantzzz** [comment]
There is a fix in [this PR](https://github.com/trufflesuite/truffle/pull/4019)

**Comment by eggplantzzz** [comment]
@truffle/hdwallet-provider version 1.4.0 has just been released and I think it will solve this issue. Can you try it out and confirm or deny that it fixes the problem? Thanks!

**Comment by bitcoinbrisbane** [comment]
> @truffle/hdwallet-provider version 1.4.0 has just been released and I think it will solve this issue. Can you try it out and confirm or deny that it fixes the problem? Thanks!

I can test today

**Comment by shoenseiwaso** [comment]
> @truffle/hdwallet-provider version 1.4.0 has just been released and I think it will solve this issue. Can you try it out and confirm or deny that it fixes the problem? Thanks!

Confirmed fixed using the [repro repo](https://github.com/curvegrid/truffle-eip155-issues), thanks!

**Comment by slhodak** [comment]
This fixed the 'wrong chainId" issue for me. Thank you very much!

**Comment by eggplantzzz** [comment]
Glad to hear it!
