### ISSUE TITLE
truffle compile - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by SwanDoggMillionaire** [trufflesuite/truffle#3964]
Hi there,

when I run 'truffle compile' I got the following, SyntaxError: Unexpected identifier and I don't know how to fix that now. I guess I need to change the compiler in some way?
The result is as below screenshot:

![image](https://user-images.githubusercontent.com/81987555/113611998-8b627380-964f-11eb-8b62-bbb5c7a87dbe.png)

Here is the truffle-config.js in case that helps:

![image](https://user-images.githubusercontent.com/81987555/113611745-3c1c4300-964f-11eb-9bb7-5f79733906b8.png)

Any support on this is much appreciated.

## Environment
* Operating System: MacOSX
* Ethereum client:
* Truffle version (`5.1.39`):
* node version (`10.16.3`):
* npm version (`6.9.0`):

**Comment by eggplantzzz** [comment]
Hey @SwanDoggMillionaire, you are just missing a comma at the end of line 14 in your `truffle-config.js`. Add one and you should be good to go!

**Comment by SwanDoggMillionaire** [comment]
Perfect, this worked. Thanks for the quick response and eagle eyes!

**Comment by eggplantzzz** [comment]
No problem! Glad you got it worked out! Closing this.
