### ISSUE TITLE
Error when i run npm install -g truffle

### ISSUE THREAD

**Issue by jeriezo** [trufflesuite/truffle#3968]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Expected to complete and give my machine the capability to complete commands like truffle init.but i get the below

information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ truffle init
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only 
the @mapbox scoped package will recieve updates in the future
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: web3@1.2.9 (node_modules\truffle\node_modules\@truffle\provider\node_modules\web3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...gpjs.org\r\n\r\nwsFcB'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @truffle/interface-adapter@^0.4.20 (node_modules\truffle\node_modules\@truffle\provider\nodenpm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ce-adapter/-/interfac'

npm ERR! Unexpected end of JSON input while parsing near '...gpjs.org\r\n\r\nwsFcB'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-04-07T14_43_20_346Z-debug.log
PS C:\Users\USER\Desktop\xxxxxxxxxxxx\blockchain> npm install -g truffle
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only 
the @mapbox scoped package will recieve updates in the future
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: web3@1.2.9 (node_modules\truffle\node_modules\@truffle\provider\node_modules\web3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...gpjs.org\r\n\r\nwsFcB'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @truffle/interface-adapter@^0.4.20 (node_modules\truffle\node_modules\@truffle\provider\nodenpm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ce-adapter/-/interfac'
npm ERR! Unexpected end of JSON input while parsing near '...gpjs.org\r\n\r\nwsFcB'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2021-04-07T14_47_55_463Z-debug.log

## Environment
VS Code

* Operating System:  Windows 10
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`v12.19.0`):
* npm version (`6.14.8):

**Comment by eggplantzzz** [comment]
Can you try running `npm cache clean --force` and afterwards try running `npm install -g truffle`? Do you get the same results? Thanks!

**Comment by jeriezo** [comment]
Thank you very much. it works perfectly
