### ISSUE TITLE
Truffle Migration fails on 5.1.50 with type error param.substring

### ISSUE THREAD

**Issue by lsqproduction** [trufflesuite/truffle#3977]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Migration deployment failed with TypeError: param.substring is not a function 

## Steps to Reproduce
```console
git clone https://github.com/sirenmarkets/core.git
cd core && npm install

truffle migrate
```

## Expected Behavior

mirgate successfully

## Actual Results

`TypeError: param.substring is not a function
`

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`5.1.50`):
* node version (`15.8.0"):
* npm version (`7.6.0`):

**Comment by eggplantzzz** [comment]
Hey @lsqproduction, does it still fail on the latest Truffle?

**Comment by lsqproduction** [comment]
Same error on latest 5.3.2

**Comment by leeftk** [comment]
We went through the git history on `https://github.com/sirenmarkets/core.git` and could not reproduce the issue so we are closing it.
