### ISSUE TITLE
truffle unbox error: certificate has expired

### ISSUE THREAD

**Issue by ruanbyao** [trufflesuite/truffle#3979]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
 I used the command truffle unbox webpack, but I was stuck on some questions:
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
RequestError: Error: certificate has expired
 
## Steps to Reproduce
npm install truffle -g
npm install -g webpack
truffle unbox webpack

## Expected Behavior

unbox successfully

## Actual Results

unbox failed.
![image](https://user-images.githubusercontent.com/39271671/115103390-17e03080-9f84-11eb-9ee4-a417b7582e89.png)

## Environment
Ubuntu 18.04LTS
Ethereum client:Geth
truffle version: v5.3.1
node version:14.16.1
npm version:6.14.12

**Comment by gnidan** [comment]
Hey @ruanbyao can you try this again? I have a feeling this might be intermittent and no longer a problem. Regardless, will try to reproduce on our side. Thanks for opening this issue!

**Comment by ruanbyao** [comment]
> Hey @ruanbyao can you try this again? I have a feeling this might be intermittent and no longer a problem. Regardless, will try to reproduce on our side. Thanks for opening this issue!

Actually, the problem remains.
![image](https://user-images.githubusercontent.com/39271671/115649090-3f0a7980-a359-11eb-85cf-374182fcd4c8.png)
My solution is to type git clone https://github.com/trufflesuite/truffle-init-webpack.git from command line
