### ISSUE TITLE
verbose stack Error: EPERM: operation not permitted, lchown '/usr/local/bin/sentinelctl'

### ISSUE THREAD

**Issue by skykingit** [trufflesuite/truffle#3982]
when i install truffle ,it has a error

the log is below
----------------------------------------------------------------------------------
8236 timing build:link:node_modules/truffle/node_modules/secp256k1/node_modules/node-gyp-build Completed in 13ms
8237 timing build:link:node_modules/truffle/node_modules/utf-8-validate/node_modules/node-gyp-build Completed in 13ms
8238 timing reify:rollback:createSparse Completed in 4397ms
8239 timing reify:rollback:retireShallow Completed in 0ms
8240 timing command:install Completed in 47100ms
8241 verbose stack Error: EPERM: operation not permitted, lchown '/usr/local/bin/sentinelctl'
8242 verbose cwd /Users/user
8243 verbose Darwin 19.6.0
8244 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "truffle" "-g"
8245 verbose node v14.16.1
8246 verbose npm  v7.9.0
8247 error code EPERM
8248 error syscall lchown
8249 error path /usr/local/bin/sentinelctl
8250 error errno -1
8251 error Error: EPERM: operation not permitted, lchown '/usr/local/bin/sentinelctl'
8251 error  [Error: EPERM: operation not permitted, lchown '/usr/local/bin/sentinelctl'] {
8251 error   errno: -1,
8251 error   code: 'EPERM',
8251 error   syscall: 'lchown',
8251 error   path: '/usr/local/bin/sentinelctl'
8251 error }
8252 error The operation was rejected by your operating system.
8252 error It is likely you do not have the permissions to access this file as the current user
8252 error
8252 error If you believe this might be a permissions issue, please double-check the
8252 error permissions of the file and its containing directories, or try running
8252 error the command again as root/Administrator.
8253 verbose exit -1

**Comment by cds-amal** [comment]
Closing this for issue maintenance. Please comment if you'd like us to revisit
