### ISSUE TITLE
Doe truffle supports data seeding like traditional databases

### ISSUE THREAD

**Issue by coolatmusic** [trufflesuite/truffle#3989]
I am looking for something similar to what we do in traditional databases, those who are familier would know we use seeding to seed initial data to the database to get it started. I am looking something similar in truffles, if we can do similar thing.
Thank you.

**Comment by gnidan** [comment]
@coolatmusic neat idea - having some kind of system for data fixtures could be useful.

Do you have some thoughts about what these would look like? Happy to entertain discussion about getting this as future feature enhancement. Let us know!

**Comment by gideongrinberg** [comment]
@coolatmusic Truffle doesn't, but you can write smart contracts to store data on the blockchain.

**Comment by zakpie** [comment]
We had a similar requirement, unfortunately, we had to roll out  a solution of our own, kindly have a look [https://github.com/LibertyPie/truffle-seeder](https://github.com/LibertyPie/truffle-seeder) if it suits your needs

**Comment by coolatmusic** [comment]
> We had a similar requirement, unfortunately, we had to roll out a solution of our own, kindly have a look https://github.com/LibertyPie/truffle-seeder if it suits your needs

Hey thanks, that is what I was looking for.

**Comment by cds-amal** [comment]
Closing this for issue maintenance. Please comment if you think this belongs in Truffle proper and would like to help us define requirements. Thanks!

cc: @kevinbluer

**Comment by kevinbluer** [comment]
Thanks for sharing `truffle-seeder` @big-zak, it looks awesome! We're in the process of aggregating a collection of plugins, extensions, utilities, etc that will likely live at trufflesuite.com/extensions (not yet live). We'd love to add this if you'd be open to it?

Thanks again 🙌

**Comment by big-zak** [comment]
Sure, I will be glad to do that .. let me know what to do next

**Comment by kevinbluer** [comment]
Awesome @big-zak, no action right now, although I'd love to share a preview of the new section when it's ready (any feedback, etc would be awesome)
