### ISSUE TITLE
How to migrate contract with address coming from Trezor 

### ISSUE THREAD

**Issue by redna11** [trufflesuite/truffle#3993]
My goal is to deploy a contract to Ethereum using truffle from an address in my Trezor device.

*** what I am doing now and it works ****

When trying to deploy to rinkeby with truffle and using a metamask address (with 3 test-ETH on it), I use the follwing code in "truffle-config.js":

`const HDWalletProvider = require('@truffle/hdwallet-provider');
const mnemonic = 'some words ....'

.
.

    rinkeby: {
      provider: () => new HDWalletProvider(
        mnemonic,
        'https://rinkeby.infura.io/v3/some_infura_key',
        0,
        1
      ),
      network_id: 4, //rinkeby
      skipDryRun: true
    },

`
Migrating with the command : truffle migrate --reset --network rinkeby  works well. After importing my Trezor address to Metamask, I change the accounts param from 0 (as above) to 1 so that it references that new Trezor address and try to deploy with the same command (that Trezor account has 3 test-ETH on it also). 

it throws ""Migrations" -- insufficient funds for gas * price + value."

My impression is that somehow it does not "connect" to the right address.

Is this the correct procedure to deploy using a hardware wallet, or is there a better one? thx.

**Comment by davidmurdoch** [comment]
Connecting your hardware wallet to MetaMask has no effect on the truffle migrate as we don't currently have a way of connecting to MetaMask. We strongly recommend _against_ using your hardware mnemonic within Truffle, or anywhere else (your mnemonic really shouldn't even be digitally stored anywhere).

There are a couple of alternative solutions:

 * https://github.com/Web3Modal/trezor-provider this is not maintained by truffle, so you'll need to do your own due diligence to ensure it is safe to use.
 * you could transfer a small amount of your testnet either from your Trezor wallet to one of the accounts created by the mnemonic you use in your truffle config.

Just to reiterate, you should never re-use your hardware mnemonic outside of the hardware wallet itself, as this really defeats the purpose of using it in the first place :-)

This is a known limitation of truffle and we don't have plans to implement a solution in the future, but nothing has been done as of yet.

**Comment by evgenynacu** [comment]
We created small util for using Trezor with Truffle: https://github.com/rariblecom/trezor-provider
It's a subprovider for metamask's web3-provider-engine

**Comment by eggplantzzz** [comment]
Thanks @evgenynacu for doing work in this area. We really appreciate community contributions and hope that your solution becomes accepted!

Hey @redna11, in the meantime we really haven't evaluated the utility that @evgenynacu created but we would encourage you to do your own research and look into it!

**Comment by eggplantzzz** [comment]
Hey @redna11, so we recently released a tool that you may find helpful. If you use MetaMask with your Trezor wallet you can use Truffle Dashboard for deployments. Check out [this blogpost](https://trufflesuite.com/blog/introducing-truffle-dashboard/) for more info. Basically it lets you use MetaMask to sign your transactions when doing deployments. Let us know if this works for you, thanks!

**Comment by cds-amal** [comment]
Closing for issue maintenance
