### ISSUE TITLE
Add support for Solidity custom errors in debugger/decoder

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#3996]
## Issue

Related to #3873.

Solidity 0.8.4 introduces custom errors.  We need to add support for this.  As wth `Panic`s, which we now support in the debugger and decoder (and things that use these, such as stacktracing in tests), we can start by adding support in the debugger and decoder.  Further support can come later.

Note that ideally that when decoding these in the debugger, we should make use of AST information to disambiguate ambiguous errors.  Of course, the decoder won't be able to do this!

## Environment

* Truffle version (`truffle version`): 5.3.2

**Comment by gnidan** [comment]
(Renaming this issue, since the "further support" remains unclear.)

Closing, released in [Truffle v5.3.10](https://github.com/trufflesuite/truffle/releases/tag/v5.3.10).
