### ISSUE TITLE
Not all packages' `package.json` files include `repository` field + `directory`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#3998]
NPM respects the `repository` field, and it allows us to specify subdirectory, i.e. for monorepo purposes!

All packages in this monorepo should probably have this populated, e.g.:
```javascript
{
  "name": "@truffle/core",
  /* ... */
  "repository": {
    "type": "git",
    "url": "https://github.com/trufflesuite/truffle.git",
    "directory": "packages/core"
  },
  /* ... */
}
```

(Raised by @haltman-at [here](https://github.com/trufflesuite/truffle/pull/3943#discussion_r617047761))

**Comment by Rishabhraghwendra18** [comment]
Hi . First timer this side . Is this issue open ?

**Comment by haltman-at** [comment]
Oops, no, this should be closed now!  Thanks for catching this!
