### ISSUE TITLE
Truffle fails to install with latest Nodejs

### ISSUE THREAD

**Issue by dilipkrbe** [trufflesuite/truffle#401]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Cannot install Truffle via npm install -g truffle command

## Steps to Reproduce
1. Latest Node js v7.10.0 and npm v3.10.6 is installed on my system (Win 8.1).
2. Issued npm install -g truffle command
3. Install fails with issue - Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.

## Expected Behavior

Expected to install the latest truffle globally using npm

## Actual Results

\\npm-cli.js" "install" "-g" "truffle"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dilip.r02\npm-debug.log
npm ERR! code 1

## Environment

* Operating System: Win 8.1
* Truffle version: v3.2.2
* node version: v7.10.0
* npm version: v3.10.6

**Comment by treste91** [comment]
try "npm install truffle@3.2.1 -g"
for me it worked today
the 3.2.2 version has some issues right now so go for the 3.2.1

**Comment by dilipkrbe** [comment]
Thanks Treste91

**Comment by frankcash** [comment]
Good call @treste91 , thanks!

**Comment by charles-cooper** [comment]
Does upgrading your node version help? https://github.com/trufflesuite/truffle/issues/413#issuecomment-305923926

**Comment by tcoulter** [comment]
Hi there. A new beta has been pushed out that should fix this issue. Details in the blog post [here](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). Can you give it a shot and report back?

**Comment by WorldCryptoCamp** [comment]
ran into the same issue today, the suggestion from Treste91 worked for me

**Comment by themandalore** [comment]
On Window, I used GitBash, first ran npm install --global --production windows-build-tools, then opened gitbash as an Administrator and ran the suggestion from Treste91... and voila, 6 hours since starting install, you should have a nice truffle command line

**Comment by tcoulter** [comment]
Please read the blog post for a quick, issue free installation on Windows:

http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past

**Comment by happyconcepts** [comment]
Per the blog post, truffle (beta) has successfully installed for me on Win7 with Python 2.7 using npm:
`$ npm install -g truffle@beta`

**Comment by tcoulter** [comment]
We've released a new version of Truffle making `beta` officially released to production. Closing this ticket. Thanks all!

**Comment by danielrussellLA** [comment]
I had a similar problem. I ran `npm i -g truffle` and then when I tried to run `truffle init` I got an error: `zsh: command not found: truffle`.  What solved it for me is to create a local `node_modules` with truffle installed in it, and then run that copy.

1. run `npm init` and make a new npm project
2. run `npm i truffle`
3. run `./node_modules/.bin/truffle init` and it should work!
