### ISSUE TITLE
how to run a personal blockchain like 'truffle dev' without geth or ganache but not in interactive mode?

### ISSUE THREAD

**Issue by SINOPW** [trufflesuite/truffle#4017]
- [✓] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

**Comment by gnidan** [comment]
You can just do `truffle develop --log` but it's about the same thing as running Ganache

**Comment by SINOPW** [comment]
sincerely thanks

**Comment by SINOPW** [comment]
> You can just do `truffle develop --log` but it's about the same thing as running Ganache

sincerely thanks
