### ISSUE TITLE
Deploying contracts to Avalanche results in an 'invalid sender' error

### ISSUE THREAD

**Issue by Klemah** [trufflesuite/truffle#4028]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My colleagues and I are completely unable to deploy any contract on the Avalanche testnet using Truffle.
The issue started occurring at the beginning of May.

The scripts I am using for deployment are the same I have always used, and they all started failing for me, my colleagues, as well as others, at the same time. We think this is linked to a recent update on Avalanche, the Avalanche Berlin update.

So far, most people who encountered this issue just decided to stop using Truffle and started using Hardhat or Remix instead, whether they like it or not, as no problem is occurring on their side. I cannot do the same, as this issue also occurs when using ChainBridge's `cb-sol-cli` commands.

[A similar issue happened for Ropsten back in March.](https://stackoverflow.com/questions/66735307/truffle-contract-deployment-failed-invalid-sender)

## Steps to Reproduce

The error you will get depends of what version of `@truffle/hdwallet-provider` or `truffle-hdwallet-provider` you use.

Try to deploy a basic ERC20 token contract to the Avalanche testnet using a basic NodeJS script, using Truffle's hdwallet-provider.

## Expected Behavior

I expect a successful token deployment.

## Actual Results

If using `@truffle/hdwallet-provider: 1.3.x` or newer: we get the `invalid sender` error.
If using `@truffle/hdwallet-provider: 1.2.x` or older, or any version of `truffle-hdwallet-provider`: the error will be either `cannot query unfinalized data` or `only replay-protected (EIP-155) transactions allowed over RPC` depending on the contract you want to deploy. Sometimes, you will even get both errors at the same time.

Before this error started occurring, I was using the latest version of `truffle-hdwallet-provider`.

## Environment

* Operating System: Windows 10
* node version (`node --version`): `10.24.0`
* npm version (`npm --version`): `6.14.11`

## More info

You can find more info [here](https://community.figment.io/t/error-invalid-sender-while-deploying-contracts-using-truffle/238).
Some of the posts suggested adding the chain ID to the hdwallet-provider constructor, but this does not fix the issue.

Trying to deploy bridge contracts on the Avalanche testnet using ChainBridge's `cb-sol-cli` commands also fails with the `invalid sender` error.

**Comment by rajranjan0608** [comment]
Yes. This issue started appearing eventually from the last few weeks, while deploying contracts using Truffle.

**Comment by eggplantzzz** [comment]
We released version 1.4.0 of @truffle/hdwallet-provider yesterday. We made some improvements that might fix your issue, can you upgrade and see if it fixes this issue? Thanks!

**Comment by Klemah** [comment]
> We released version 1.4.0 of @truffle/hdwallet-provider yesterday. We made some improvements that might fix your issue, can you upgrade and see if it fixes this issue? Thanks!

Hey, it fixes the issue indeed!

Thank you sir!
