### ISSUE TITLE
Explore better (more standard) integration with Mocha

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#403]
See this account of integrating IntelliJ Idea: https://charterhouse.github.io/2017/05/12/running-truffle-unit-tests-in-intellij-idea.html

**Comment by cedricwalter** [comment]
@tcoulter 
I've tried to follow the tutorial and it does not work (Intellij 2017.3). I would be happy to help on this one (Intellij) even helping writing a Karma-runner for truffle. What do you think?

**Comment by gnidan** [comment]
Closing this as wont-fix. I think there is more investigation to be done on generalizing/improving Truffle's test system. Will hopefully find a general solution meet this kind of need. Thanks!

**Comment by thomasmodeneis** [comment]
anyone knows if this was ever made better ?
