### ISSUE TITLE
Fail with error 'SafeERC20: low-level call failed'

### ISSUE THREAD

**Issue by rjbanna** [trufflesuite/truffle#4036]
Hello all,

I'm trying to implement flashloan using truffle flashloan box. I haven't modified any code in that and I ran as per the documentation in the console. But it is giving me "Fail with error 'SafeERC20: low-level call failed'" error. I have also sent 0.5 ether to the deployed contract to cover gas fees. I'm using kovan testnet.

**Comment by cds-amal** [comment]
Hi @rjbanna. This is likely an error in the application logic. Just so you know there's some other error you're not presented with. IIRC AAVE does not forward the underlying error details. I recommend reviewing your contracts and perhaps checking in with AAVE developers for more insight.

**Comment by gnidan** [comment]
Closing this for issue maintenance, but let us know if there's more we can do to support you here. Sorry you had to deal with this!
