### ISSUE TITLE
Truffle breakpoints fail if two contracts have the same name

### ISSUE THREAD

**Issue by 0xfoobar** [trufflesuite/truffle#4049]
## Issue

I'm debugging an external contract, and there are two contracts with the same name which both get called in the course of the transaction.

## Steps to Reproduce

Run a transaction that involves two contracts with the same name.

Then run `truffle debug -x $TXHASH` and enter `b ContractName:100` or whatever line number is valid.

## Expected Behavior

To be able to specify which contract I want to set a breakpoint in.

## Actual Results

![m4C6POmo](https://user-images.githubusercontent.com/83792390/118901474-39f10980-b8c8-11eb-898c-a523b4e5888f.png)

## Environment

* Operating System: macOS 10.15.7
* Ethereum client: ganache 6.12.1
* Truffle version (`truffle version`): 5.3.4
* node version (`node --version`): 15.5.1
* npm version (`npm --version`): 7.8.0

**Comment by fainashalts** [comment]
Hi @0xfoobar thank you for bringing this up! We are aware of this issue and in the process of implementing a fix that involves setting breakpoints in all matching contracts. We'll keep you posted!

**Comment by gnidan** [comment]
Closing, released in [Truffle v5.3.10](https://github.com/trufflesuite/truffle/releases/tag/v5.3.10).
