### ISSUE TITLE
Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol" not found: File import callback not supported

### ISSUE THREAD

**Issue by Sumair-Aslam** [trufflesuite/truffle#4067]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I am trying to compile the smart contract in truffle it throws this error, while it is perfectly compiling in remix

## Steps to Reproduce

made a smart contract and imported erc-1155
then run
truffle compile

## Expected Behavior
compiled successfully
What you expected to happen.

## Actual Results

ParserError: Source "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol" not found: File import callback not supported

## Environment

* Operating System: Ubuntu 18.04
* Ethereum client:
* Truffle version (`truffle version`): Truffle v5.3.7 (core: 5.3.7)
* node version (`node --version`): Node v14.17.0
* npm version (`npm --version`):  6.14.13

**Comment by gnidan** [comment]
Note that we probably don't want to support URLs that reference a branch name, since the file may change without your being aware.

**Comment by cds-amal** [comment]
Closing for issue maintenance, please feel free to let us know if you're still having problems
