### ISSUE TITLE
Does @truffle/hdwallet-provider support generating hardened keys?

### ISSUE THREAD

**Issue by WeihanWMW** [trufflesuite/truffle#4076]
Hi

Does @truffle/hdwallet-provider support generating hardened keys?

If so, please give an example on how to use hardened keys.

Thanks you.

**Comment by haltman-at** [comment]
Hi, could you explain what you mean by "hardened keys" here?  We're not familiar with this terminology in this context.

**Comment by cds-amal** [comment]
Closing this for issue maintenance, please feel free to let us know if you'd like to discuss.
