### ISSUE TITLE
Could not install truffle in ubuntu16.04

### ISSUE THREAD

**Issue by PierrePeng** [trufflesuite/truffle#4077]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Could not install truffle in ubuntu 16.04

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/23045104/120074624-43e8e880-c0d0-11eb-9b7a-604e8c752e12.png)

## Expected Behavior

Successfully to install truffle

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: ubuntu 16.04
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):v16.2.0
* npm version (`npm --version`): 7.13.0

**Comment by kcelestinomaria** [comment]
Hello, try using node --version v16.0.0 , just had the same errors at this time, just solved it right now by setting nvm install v16.0.0 and using it

**Comment by PierrePeng** [comment]
> Hello, try using node --version v16.0.0 , just had the same errors at this time, just solved it right now by setting nvm install v16.0.0 and using it

Thanks! It works for me.
