### ISSUE TITLE
"Migrations" could not deploy due to insufficient funds

### ISSUE THREAD

**Issue by pinajmr** [trufflesuite/truffle#4083]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't migrate to a test network, it does the migration correctly in ganache, but when I take it to a testnet with the same account (which has a sufficient balance of 100eth) it doesn't recognize the balance.

## Steps to Play

1. Take the test, it runs perfectly.
2. I migrate to truffle (my local node), perfectly and I can interact with my smartcontract, without problems.
3. I am going to migrate it to a testnet and it does not recognize the account balance, and due to lack of funds, it is not displayed.
 
## Expected Behavior

I've done it before, without any problem, with the same dependencies, nothing has changed.

## Actual Results
![Screenshot from 2021-05-31 09-28-54](https://user-images.githubusercontent.com/32434364/120211039-da1f2a80-c206-11eb-9f04-d2d0335bbe4e.png)

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): 5.3.8
* node version (`node --version`):10.14.0
* npm version (`npm --version`): 6.4.1

**Comment by eggplantzzz** [comment]
This kind of an error looks to me like you might not be instantiating wallet software correctly (with the appropriate accounts initialized). Can you show me what you are doing in your `truffle-config.js`? You should, of course, remove all sensitive info.

**Comment by pinajmr** [comment]
![Screenshot from 2021-06-08 14-45-03](https://user-images.githubusercontent.com/32434364/121232606-28b47080-c868-11eb-89fb-03a25c2149d3.png)


> This kind of an error looks to me like you might not be instantiating wallet software correctly (with the appropriate accounts initialized). Can you show me what you are doing in your `truffle-config.js`? You should, of course, remove all sensitive info.

**Comment by fainashalts** [comment]
Hi @pinajmr thank you for bringing this to our attention! This looks like an issue with the migrations dry-run. It appears that Truffle doesn't get the actual accounts you are trying to use with Kovan and instead spins up a new account that isn't funded. 

Can you confirm what `accounts[0]` is from this provider? It should be different from what you see in the error (0x46D6c629b06A3E5791462f17851865F3E60bad91), if our hunch is correct.

We will definitely look into this. In the meantime,  you should be able to add `--skip-dry-run` to your command to bypass this issue.

**Comment by pinajmr** [comment]
Hi @fainashalts . Yes, is the `accounts[0]`. 
I tried with `--ski-dry-run`, but I cannot deploy either.

**Comment by pinajmr** [comment]
Hi @eggplantzzz  at that time yes, but due to many unsuccessful tests, I restarted ganache, and that account was lost.

But thanks for the observation, now I make it from this account 0x128b13c88537ea482D318014720dd0De5aC0B22e
obtaining the same result.

**Comment by eggplantzzz** [comment]
That address also has no funds on Kovan. You need to use an address that has (test) ether in order to deploy. You will need to get some from an ether faucet or have someone send you some test ether. Otherwise the deployment will fail like you described due to insufficient funds.

**Comment by pinajmr** [comment]
I absolutely agree my dear friend @eggplantzzz , before I had implemented it in a direction that already had funds and I did not intend this step in this project or they take it for granted. I am really very grateful for your time and your help. I sent a tip with BAT thank so much.

**Comment by eggplantzzz** [comment]
No problem at all! Good luck and let me know if you have any other problems.

**Comment by opensourceDAO-Community** [comment]
still facing the same issue
