### ISSUE TITLE
Error install Truffle in Ubuntu 20.04

### ISSUE THREAD

**Issue by aimanLee** [trufflesuite/truffle#4086]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Firstly I got this error after I run a command 

> npm install --global truffle 

Error:

> npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR!     <https://npm.community>
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /.npm/_logs/2021-06-01T11_49_28_221Z-debug.log
> 
Error log can see here: [https://pastebin.com/XzUTt0cA](url)

Then I reinstall again with new command

> sudo npm install -g truffle

Then I got new error like this:

> npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in 

> certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
> npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
> npm WARN deprecated multicodec@0.5.7: stable api reached
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> npm WARN deprecated redux-devtools-core@0.2.1: Package moved to @redux-devtools/app.
> npm WARN deprecated redux-devtools-instrument@1.10.0: Package moved to @redux-devtools/instrument.
> npm WARN deprecated remotedev-serialize@0.1.9: Package moved to @redux-devtools/serialize.
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
> npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
> npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
> /usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/build/cli.bundled.js
> npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/4594/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> 
> > iso-constants@0.1.2 install /usr/local/lib/node_modules/truffle/node_modules/iso-constants
> > node build.js > index.browser.js
> 
> sh: 1: cannot create index.browser.js: Permission denied
> 
> > bufferutil@4.0.3 install /usr/local/lib/node_modules/truffle/node_modules/bufferutil
> > node-gyp-build
> 
> 2021/06/01 20:12:44.916563 cmd_run.go:1002: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/4594": mkdir /nonexistent: permission denied
> cannot create user data directory: /nonexistent/snap/node/4594: Permission denied
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iso-constants@0.1.2 (node_modules/truffle/node_modules/iso-constants):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iso-constants@0.1.2 install: `node build.js > index.browser.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 2
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bufferutil@4.0.3 install: `node-gyp-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bufferutil@4.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-06-01T12_12_52_526Z-debug.log

## Steps to Reproduce
Use another command

## Expected Behavior

Normal Install

## Actual Results

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bufferutil@4.0.3 install: `node-gyp-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bufferutil@4.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-06-01T12_12_52_526Z-debug.log

## Environment

* Operating System: Linux Ubuntu 20.04
* Ethereum client: 1.10.3-stable
* Truffle version (`truffle version`): N/A
* node version (`node --version`): v14.17.0
* npm version (`npm --version`): 6.14.13

**Comment by eggplantzzz** [comment]
I would recommend re-installing npm using a Node version manager like nvm. This resolves many permissions errors encountered while installing Truffle. Also note that you probably shouldn't use `sudo` to install Truffle. See [this npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more information.

**Comment by konradruiz** [comment]
have same problem ( same parametrs ) and I didin't use sudo ... Did you fix that ?

**Comment by cds-amal** [comment]
@konradruiz can you share the output of `truffle version`,  `npm --version` as well as Truffle's output of the problem? This will help us to diagnose the issue.

**Comment by cequattro** [comment]
I am having the same issue.

have you tried to apply this command? :
npm explore npm -g -- npm install node-gyp@latest


Environment
Operating System: Linux Ubuntu 18
Ethereum client: Ganache CLI v6.12.2
Truffle version (truffle version): N/A
node version: v14.0.0 runnning under nvm
npm version: 6.14.4

**Comment by cequattro** [comment]
Finally i could solve this issue with the following steps:

First install yarn with:

npm i -g yarn

Second you have to install truffle with yarn:

yarn global add truffle

I hope it helps

**Comment by ctatum20** [comment]
I am having the same issue with it telling me to upgrade to version 7 or higher. I'm not sure how to fix this issue. Also, the yarn remedy did not help me

**Comment by Claymoar** [comment]
I have this exact same issue. AimanLee, were you ever able to figure it out?

**Comment by cds-amal** [comment]
@konradruiz We've seen issues with npm 7. Are you able to fallback to version 6 of npm? `npm -g uninstall npm && npm -g install npm@6`?

**Comment by Claymoar** [comment]
> @konradruiz We've seen issues with npm 7. Are you able to fallback to version 6 of npm? `npm -g uninstall npm && npm -g install npm@6`?

Yes. Unfortunately that doesn't seem to be the issue. I'm using npm -v 6.14.13, but than you for the idea!

**Comment by pydevnepal** [comment]
Try adding sudo before the install command, `sudo npm install` -g truffle worked for me.

**Comment by pydevnepal** [comment]
Try adding `sudo` before the install command, `sudo npm install -g truffle` worked for me.

**Comment by pydevnepal** [comment]
Try adding `sudo` before the install command, `sudo npm install -g truffle` worked for me.
Before that `npm` is required to be upgraded to`v7` as stated in the err logs, so `sudo npm install -g npm@latest`

**Comment by haltman-at** [comment]
@khatriamit Please don't use `sudo` while installing; this can cause a number of permissions and security problems.

@Claymoar Do you have reproduction steps we could try?  Could you say more about your setup?  Would you mind showing us the precise error you got?  Thanks!

**Comment by cds-amal** [comment]
Closing for issue maintenance

**Comment by jennyedam** [comment]
I have installed truffle but when i am checking for version its showing below error
.

/usr/local/lib/node_modules/truffle/build/4986.bundled.js:329
  const isREPL = options?.isREPL ?? false; //default to not displaying REPL commands
                         ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.__webpack_require__.f.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:608:28)
    at Promise.all.Object.keys.reduce (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:538:40)
    at Array.reduce (<anonymous>)

**Comment by haltman-at** [comment]
@jennyedam That sounds like a new issue, could you file a new issue about that?  Thanks!
