### ISSUE TITLE
Feature Request: CLI command to get the solidity compiler version used by truffle

### ISSUE THREAD

**Issue by Janaka-Steph** [trufflesuite/truffle#409]
I would like to suggest a feature, having a CLI command to get the solidity compiler version used by truffle.
What do you think ?

**Comment by tcoulter** [comment]
Thanks for the suggestion! This has been added to the `beta` version of Truffle, which you can get by running:

```
$ npm install -g truffle@beta
```

This change will go out live in the next official (non-beta) version of Truffle. Output looks like this: 

<img width="541" alt="screen shot 2017-06-08 at 2 43 32 pm" src="https://user-images.githubusercontent.com/92629/26952134-f68f06ae-4c58-11e7-8104-9a599a9a4b44.png">

Thanks!

**Comment by Janaka-Steph** [comment]
Thanks to you, that's great!
