### ISSUE TITLE
Codec & debugger should read compiler version from CBOR when not present in artifact

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4093]
## Issue

Currently, codec & debugger, when they need to determine the Solidity version for a particular contract, rely on it being present in the input (artifacts or compilations).  For compilations of course we always have this, but it can be missing from artifacts.

However, in Solidity 0.5.9 and later, this information is included in the contract's CBOR, and we should use that if the information is missing from the artifact.  (We probably don't want to use it in preference to the one in the artifact, since the information in the CBOR is lower-resolution.)

One thing to beware of here: The information is stored differently depending on whether the contract was compiled with a release version of Solidity or a prerelease version.  Make sure you account for both cases.

(Further note: This will only work for Solidity contracts, of course, not Yul contracts, and certainly not other languages such as Vyper.  And as mentioned, this information was only added in 0.5.9.  The CBOR info itself was added in 0.4.7, but we currently don't support Solidity older than 0.4.9.)

## Environment

* Truffle version (`truffle version`): 5.3.9

**Comment by gnidan** [comment]
Closing, released in [Truffle v5.3.10](https://github.com/trufflesuite/truffle/releases/tag/v5.3.10).
