### ISSUE TITLE
Using `truffle debug --fetch-external` with dockerized solc doesn't work

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4096]
## Issue

PR #3605 was supposed to allow using Docker with `truffle debug --fetch-external`, but it turns out it doesn't actually work because if you set `docker: true` you also need to set the version differently!  Now, simple versions like `0.8.4` will work fine, but longer qualified versions won't, and those longer qualified versions are what you're likely going to get when downloading external sources off of say Etherscan.  So, these version strings will have to be transformed appropriately.  It's unclear at the moment whether it will be possible to make this work for both release and prerelease versions; it should be made to work for both if possible, but if not then we can just make it work for release versions.

## Environment

* Truffle version (`truffle version`): 5.3.9

**Comment by gnidan** [comment]
This is now fixed in [Truffle v5.3.10](https://github.com/trufflesuite/truffle/releases/tag/v5.3.10)!
