### ISSUE TITLE
TyperError: resolver.resolve is not a function

### ISSUE THREAD

**Issue by tolks11** [trufflesuite/truffle#4102]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce
Building truffle normally or cloning official truffle documentation

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.
Normal truffle actions such as migrate, compile, etc.  truffle init is the only current command that doesn't throw the error
## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
Whether building from scratch or directly cloning from truffle's github, running truffle migrate, compile, etc all throw this error.  

 TypeError: resolver.resolve is not a function
    at Profiler.<anonymous> (/opt/homebrew/Cellar/truffle/5.3.6/libexec/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/profiler.js:55:1)

<img width="774" alt="Screen Shot 2021-06-09 at 9 29 40 PM" src="https://user-images.githubusercontent.com/62411436/121450473-cf346a80-c969-11eb-882f-bba55d257e6c.png">

## Environment

* Operating System: macOS Big Sur
* Ethereum client: any 

* Truffle version (`truffle version`): 5.3.6
* node version (`node --version`): 16.2.0
* npm version (`npm --version`): 7.13.0

**Comment by betochf** [comment]
I just started with truffle, do you mind if I try to solve it?

**Comment by eggplantzzz** [comment]
Try upgrading to the latest version of Truffle. 

```
npm uninstall -g truffle
npm install -g truffle
```

I don't think Truffle fully supports Node 16 and npm version 7. Try downgrading to npm v 6.x.x and Node 14. Let me know if you still have the problem afterwards.

**Comment by tolks11** [comment]
uninstalled, reinstalled a few times over the past few days and nothing unfortunately.  This problem is recent and know that it was working with most up to date versions of npm and node as that's all I've used on the new laptop I've had for a few months.  How would I go about downgrading?  Each time on the specific project level?

**Comment by cds-amal** [comment]
Oh how interesting! I didn't know there was a brew formulae for Truffle! The [truffle formulae](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/truffle.rb#L17) depends on their [node formulae which specifies node 16](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/node.rb#L4)

It is possible truffle resolves to homebrew's install. Does `which truffle` resolve to brew's version or nvm's version?

**Comment by eggplantzzz** [comment]
@tolks11 Do you use a node version manager like nvm? Then you can just do something like `nvm use 14`. npm you can install using npm like `npm install -g npm@6`.

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but let us know if there's still a problem and we can reopen.  Thanks!
