### ISSUE TITLE
Feature Proposal- Merge Truffle Create Commands

### ISSUE THREAD

**Issue by JimLynchCodes** [trufflesuite/truffle#4108]
Currently, to scaffold a new contract users need to run THREE separate commands!

```
truffle create contract foo
truffle create migration foo
truffle create test foo
```

Do you think we have robot fingers or something?? 😅

My argument is that there is ***NEVER*** a good time to create a contract _without_ a migration file or a test file...

Therefore, all three of these files should be created from the `truffle create contract` command...

**Comment by cds-amal** [comment]
@JimLynchCodes The `create` command has 4th option, `all` which scaffolds all 3 pieces. This is more flexible and should support more development workflows.

## Help
<details>
<summary>$ truffle help create</summary>

```console
..t-create/my-killer-dapp  truffle help create

  Usage:        truffle create <artifact_type> <ArtifactName>
  Description:  Helper to create new contracts, migrations and tests
  Options:
                <artifact_type>
                    Create a new artifact where artifact_type is one of the following: contract, migration,
                    test or all. The new artifact is created along with one (or all) of the following
                    files: `contracts/ArtifactName.sol`, `migrations/####_artifact_name.js` or
                    `tests/artifact_name.js`. (required)
                <ArtifactName>
                    Name of new artifact. (required)
```
</details>

## Example
```
truffle init my-killer-dapp && cd $_
truffle create all VoodooFinance
pwd
tree .

```

<details>
<summary>Example output</summary>

```console
../2021/06/14/test-create $ truffle init my-killer-dapp && cd $_
truffle create all VoodooFinance
pwd
tree .



Starting init...
================

> Copying project files to my-killer-dapp

Init successful, sweet!

Try our scaffold commands to get started:
  $ truffle create contract YourContractName # scaffold a contract
  $ truffle create test YourTestName         # scaffold a test

http://trufflesuite.com/docs

contracts         migrations        test              truffle-config.js
/Users/cds/work/reproduce/2021/06/14/test-create/my-killer-dapp
.
├── contracts
│   ├── Migrations.sol
│   └── VoodooFinance.sol
├── migrations
│   ├── 1623682928_voodoo_finance.js
│   └── 1_initial_migration.js
├── test
│   └── voodoo_finance.js
└── truffle-config.js

3 directories, 6 files
```
</details>

**Comment by gnidan** [comment]
> Do you think we have robot fingers or something??

https://www.youtube.com/watch?v=wvpcsDQ-Jtw

**Comment by haltman-at** [comment]
Hm, it looks like this currently isn't documented on the website, though.  I'll go make a quick PR there for that.

**Comment by JimLynchCodes** [comment]
@cds-amal 🤯 wow, I was not aware of the all option!!

@haltman-at  thx for adding some documenation!

@gnidan - Lol...  😁

**Comment by JimLynchCodes** [comment]
Just another thing to point out- I instinctively tried `man truffle create` and `truffle create --help` but neither gave especially helpful output... 😢

![Screen Shot 2021-06-14 at 11 19 20 PM](https://user-images.githubusercontent.com/5354163/121987795-32a60a00-cd67-11eb-9179-d945f7431e4c.png)

**Comment by JimLynchCodes** [comment]
regular ole' `truffle` doesn't mention this "all" option for the `create` entry either...

![Screen Shot 2021-06-14 at 11 22 23 PM](https://user-images.githubusercontent.com/5354163/121987900-608b4e80-cd67-11eb-8be4-e22e4732701a.png)
