### ISSUE TITLE
How does one use the `fork` option? / Document the `fork` option

### ISSUE THREAD

**Issue by maximedupre** [trufflesuite/truffle#4114]
## Issue

My use case is running `truffle test` with a fork of the main/rinkeby chain.

## Steps to Reproduce

[It seems like one can specify a network with a `fork` option](https://github.com/trufflesuite/truffle/issues/3257), so I tried this:

```
module.exports = {
    networks: {
        development: {
            fork: "https://eth-rinkeby.alchemyapi.io/v2/{myKey}",
            network_id: 4
        },
    }
}
```

However, there seems to be something missing, since I get this error:

```
$ npx truffle test
> Something went wrong while attempting to connect to the network. Check your network configuration.

Could not connect to your Ethereum client.
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

Truffle v5.3.6 (core: 5.3.6)
Node v14.16.0
```

## Expected Behavior

Using the config above, I would expect the tests to run on a fork of the alchemy rinkeby node I provided.

## Environment

* Operating System: macOS 10.15.7
* Ethereum client: Using external node
* Truffle version (`truffle version`): v5.3.6 
* node version (`node --version`): v14.16.0
* npm version (`npm --version`): v6.14.11

**Comment by fainashalts** [comment]
Hi @maximedupre, thanks for bringing this to our attention! We probably need to update our documentation on this. We support this functionality for `truffle develop`. If you change the network name to `develop` and run `test` inside of `truffle develop`, you should get the behavior you want. Please let us know if that works!

Also a note as we're putting this in the backlog, to check the exact behavior of the `test` network with `truffle test` and update the documentation to reflect the state of that. @cds-amal tagging you as you expressed interest in following this issue!

**Comment by haltman-at** [comment]
OK, we've finally documented this on [the configuration reference page](https://trufflesuite.com/docs/truffle/reference/configuration/); the update hasn't gone up yet but it should soon!  Sorry for taking so long to get to this!
