### ISSUE TITLE
how do you add networkCheckTimeout: 1000000 on truffle config?

### ISSUE THREAD

**Issue by dee778** [trufflesuite/truffle#4117]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment]
Here are [the docs](https://www.trufflesuite.com/docs/truffle/reference/configuration#configuration) for setting up your `truffle-config.js`.

**Comment by haltman-at** [comment]
Hm, it looks like this setting [exists](https://github.com/trufflesuite/truffle/blob/develop/packages/provider/index.js#L36), but the docs for it are missing!  We'll need to document this.  Thanks for raising this.

**Comment by haltman-at** [comment]
Meanwhile, [here](https://forum.openzeppelin.com/t/if-you-have-a-slow-internet-connection-try-configuring-a-longer-timeout-in-your-truffle-config-use-the-networks-networkname-networkchecktimeout-property-to-do-this/5338) are some unofficial OpenZeppelin docs on the setting.  Sorry about that!

**Comment by eggplantzzz** [comment]
#1195 documents this config option
