### ISSUE TITLE
Suggestion: Restart TestRPC (optionally) after/before tests

### ISSUE THREAD

**Issue by XertroV** [trufflesuite/truffle#412]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

## Issue

This is a suggestion, and I'm posting this for the purpose of discussion.

In an effort to make truffle as resilient, deterministic, and newb friendly as possible, I'd suggest optionally restarting/starting testrpc after or before tests.

The justification for this is a non-deterministic issue that can arise from repeat testing:

When running a test suite that accidentally `throw`s or otherwise expends the balance of an account, running that test again (once corrected to avoid `throw`ing) results in trying to use an account with zero balance. The test fails with the following error:

`Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 471238800000000000 and the senders account only has: 0`

## Steps to Reproduce

* Run a test that `throw`s (due to bad parameters)
* Run the test again without those bad params.
* Test fails.

## Expected Behavior

It would be nice if the 'snapshotting' feature of testrpc extended to accounts.

## Actual Results

Test fails.

## Environment

* Operating System: macos 10.12
* Truffle version: v3.3.2
* Ethereum client: testrpc
* node version: 6.9.2
* npm version: 3.10.9

## Addendum

Can provide more details or an example if necessary.

**Comment by tcoulter** [comment]
Thanks for the issue! We'll be tracking this in issue #490. Let us know if you have any feedback.

**Comment by XertroV** [comment]
Sounds good, thanks for the update.
