### ISSUE TITLE
Unable to install truffle on Manjaro Linux

### ISSUE THREAD

**Issue by wimdetr** [trufflesuite/truffle#413]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am unable to install truffle on my machine.

## Steps to Reproduce

sudo npm install -g truffle

## Expected Behavior

Succesfull installation of truffle.

## Actual Results

Errormessage here: https://pastebin.com/aGEiKGU5

## Environment

* Operating System: Manjaro Linux 
https://pastebin.com/aGEiKGU5
* Truffle version: / 
* Ethereum client: /
* node version: v7.7.1
* npm version: v4.6.5

**Comment by charles-cooper** [comment]
I had the same issue today on Ubuntu 16.04.2. The solution for me was to upgrade to node v8.X.X.

**Comment by wimdetr** [comment]
The issue seemed to be have been solved by adding the -f flag; i'm not sure if upgrading to node v8.0.0 helped, but I did that aswell before trying force.

**Comment by tcoulter** [comment]
Hi there. A new beta has been pushed out that should fix this issue. Details in the blog post [here](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). Can you give it a shot and report back?

**Comment by wimdetr** [comment]
Hi @tcoulter,

Installing the beta works perfectly. I've tried some commands and have found this:

$ truffle init webpack
Downloading project...
Installing dependencies...
Error: Cannot find module "."
    at webpackMissingModule (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209703:61)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:209703:139
    at <anonymous>

Everything else seems to work well.

**Comment by tcoulter** [comment]
Hi there. Can you try the latest version - 3.4.3? Thanks!

**Comment by tcoulter** [comment]
I'm going to close this for housekeeping purposes. If you run into an issue in the future, please open a new ticket. Thanks!
