### ISSUE TITLE
"originalError": {     "code": "ESOCKETTIMEDOUT",     "connect": false   } 

### ISSUE THREAD

**Issue by shengwenzheng** [trufflesuite/truffle#4130]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by shengwenzheng** [comment]
Truffle version (truffle 5.3.11):
node version (node 12.22.1):
development: {
      provider: () => new HDWalletProvider(`moral predict wash pledge hybrid box virtual length clap volcano shadow notice`, 
    `http://47.111.130.98:8888/api/jsonrpc`),      
     gasPrice: 1000000000,
      timeoutBlocks: 10,
  },

**Comment by fainashalts** [comment]
Hi @shengwenzheng this seems like you are unable to connect to the network. There may be an issue with the node you are connecting to. Perhaps try to increase the `timeoutBlocks` value to see if it helps or gets you a more detailed error?

**Comment by shengwenzheng** [comment]
> Hi @shengwenzheng this seems like you are unable to connect to the network. There may be an issue with the node you are connecting to. Perhaps try to increase the `timeoutBlocks` value to see if it helps or gets you a more detailed error?

**Comment by shengwenzheng** [comment]
This problem has been solved. My colleague's blockchain failed to connect to the last one. Thank you for your answer @fainashalts
