### ISSUE TITLE
Add support for detailed decoding of multicalls in decoder

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4133]
## Issue

@gnidan has suggested that when decoding a multicall transaction, we should not just leave the individual bytestrings undecoded, but should also decode them and return that information.  We don't want to put that information on the `Value` object itself, so @gnidan has suggested this could go in an `interpretations` field (or something) on the overall transaction decoding.

We also need a new interface for decoding the return values for these.  @gnidan has suggested this could be a new interface that takes, instead of an ABI entry and a return value, a transaction object and a return value.

Note that this would be handled purely in `decoder`, this wouldn't involve adding anything new to codec.

## Environment

* Truffle version (`truffle version`): 5.3.11

**Comment by kevinbluer** [comment]
Available in [v5.6.18](https://github.com/trufflesuite/truffle/releases/tag/v5.5.18) 👍
