### ISSUE TITLE
`compile-solidity` package depends on an outdated solc-js version

### ISSUE THREAD

**Issue by cameel** [trufflesuite/truffle#4134]
## Issue
`compile-solidity` depends on solc-js 0.6.0. This is an old version that had a bug that is the cause of https://github.com/ethereum/solidity/issues/11489 / #4039. The bug has been fixed a year ago (https://github.com/ethereum/solc-js/pull/470) in 0.6.9 so an update to at least that version is needed. Preferably Truffle should always use the latest one.

Note that Truffle used to depend on the latest solc-js from 0.6.x series but looks like it was changed to strictly 0.6.0 in #3975.

**Comment by fainashalts** [comment]
Hi @cameel thanks for bringing this up! We have deliberately kept this version of solc-js to maintain our support for Node 10 (our tests failed when we tried to make the upgrade in the past). When we drop support for Node 10 in the near future, we will revisit this.

**Comment by cameel** [comment]
Maybe it would be a good idea to at least bump it back up to 0.6.9 to make it work with 0.8.2? Truffle used to use that (or higher) version due to `^0.6.0` up to 5.3.2.

By the way, what was the exact issue with node 10? We did have some yet unresolved issues with that version (https://github.com/ethereum/solidity/issues/9297) so I'm curious what that might be about.

**Comment by haltman-at** [comment]
I don't remember the exact issue, so I'm making a branch where we bump it back up to 0.6.9 and we can see!

**Comment by haltman-at** [comment]
OK, I put up #4136 and... it's actually passing just fine?  Huh.  I guess maybe there was no problem after all.

**Comment by haltman-at** [comment]
OK, closing this for now, now that the immediate problem has been addressed.  We likely should update further, though.  Feel free to let us know if you want us to reopen this, or just file a new issue.
