### ISSUE TITLE
Db.connect is not a function error when running truffle migrate without running truffle compile first

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#4141]
## Issue

It appears that when DB is enabled and one runs `truffle migrate` without running `truffle compile` first, you get this error. 

## Steps to Reproduce

1) create a truffle project, and enable db in the config
2) run `truffle migrate` with the network of your choice
3) behold!

## Expected Behavior

Since `truffle migrate` runs a compile if you haven't compiled, I would expect that this would not occur. 

## Actual Results

`Db.connect is not a function` error. 

<img width="1071" alt="Screen Shot 2021-06-24 at 3 49 22 PM" src="https://user-images.githubusercontent.com/8952139/123342005-c912c200-d503-11eb-8c82-9398694c7b6b.png">

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.3.11
* node version (`node --version`): 12.14.0
* npm version (`npm --version`): 6.14.5

**Comment by RealLau** [comment]
@fainashalts I got the same issue, did you resolve it?

**Comment by scald** [comment]
> I tried to run `truffle compile`(no error occurs) before `truffle migrate`, still got the same error.

same here. 

Truffle v5.3.13 (core: 5.3.13)
Solidity v0.5.16 (solc-js)
Node v14.14.0
npm 6.14.8

**Comment by eggplantzzz** [comment]
@fainashalts was a fix for this released? I cannot reproduce this error.

**Comment by eggplantzzz** [comment]
Does anyone here have specific steps to reproduce this error?

**Comment by cds-amal** [comment]
@RealLau , @scald are you still able to reproduce with the [latest version of truffle](https://github.com/trufflesuite/truffle/releases)?

**Comment by scald** [comment]
@eggplantzzz @cds-amal cannot reproduce with latest version. thanks!

**Comment by fainashalts** [comment]
I'm closing this issue as it appears to be resolved!
