### ISSUE TITLE
Typescript build crash

### ISSUE THREAD

**Issue by notnATrue** [trufflesuite/truffle#4143]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Typescript build crash

## Steps to Reproduce

npm run tsc

## Expected Behavior

Please, check this import

## Actual Results

tsc

node_modules/@truffle/hdwallet-provider/dist/index.d.ts:3:48 - error TS2307: Cannot find module 'web3/providers' or its corresponding type declarations.

3 import type { Callback, JsonRPCResponse } from "web3/providers";

## Environment

* Mac os Big Sur
* Ethereum client: local
* Truffle version (`truffle version`) : v1.4.1
* node version (`node --version`): v14.15.1
* npm version (`npm --version`): v6.14.8

**Comment by cds-amal** [comment]
Hi @notnATrue did you do a `yarn bootstrap` at the repo root?

**Comment by notnATrue** [comment]
Hi there, nope.

**Comment by cds-amal** [comment]
@notnATrue , are you trying to build truffle's monorepo, or a separate project using `@truffle/hdwallet-provider?` There's a [known issue](https://github.com/trufflesuite/truffle/issues/3777) with the latter you should be aware of

**Comment by notnATrue** [comment]
@cds-amal, thx, it resolves the problem.
