### ISSUE TITLE
Appending `box` to the end of our unbox

### ISSUE THREAD

**Issue by PatrickAlphaC** [trufflesuite/truffle#4148]
## Isssue

`truffle unbox` is appending an additional `box` on the command.

Running the following:
```bash
truffle unbox smartcontractkit/box
```
Results in this error:
```
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Truffle Box at URL https://github.com:smartcontractkit/box-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at /Users/patrick/.nvm/versions/node/v12.18.4/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:42:1
    at Generator.throw (<anonymous>)
    at rejected (/Users/patrick/.nvm/versions/node/v12.18.4/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Truffle v5.3.12 (core: 5.3.12)
Node v12.18.4
```

Steps to reproduce are above. 

## Expected Behavior
Previously, it would unbox the chainlink truffle starter kit located here: https://github.com/smartcontractkit/truffle-starter-kit
Now it does not. 

## Environment

* Operating System: OSX
* Ethereum client: N/A
* Truffle version (`truffle version`): Truffle v5.3.12 (core: 5.3.12)
* node version (`node --version`): Node v12.18.4
* Web3.js v1.3.6
* npm version (`npm --version`): 7.5.3

**Comment by gnidan** [comment]
This should now be fixed in [Truffle v5.3.13](https://github.com/trufflesuite/truffle/releases/tag/v5.3.13)!

Please let us know if the problem persists.
