### ISSUE TITLE
Strange compiler response for syntax error

### ISSUE THREAD

**Issue by illuzen** [trufflesuite/truffle#415]
Just thought I'd pass this along. If you don't put parenthesis around your return type in the function signature, for example like this

      function casth(bytes32 n) public returns uint256 {

you get this:

5
5

/usr/local/lib/node_modules/truffle/node_modules/solc/wrapper.js:48
        throw e;
        ^
abort(5) at Error
    at jsStackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19718)
    at stackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19901)
    at abort (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:19:15285)
    at Array.dXb (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:585101)
    at Array.tX (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:8:557453)
    at Array.eea (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:6:495332)
    at Object.wOb [as dynCall_ii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:540050)
    at invoke_ii (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:1275129)
    at Array.ixa (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:7:494308)
    at Object.bVb [as dynCall_viii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:577232)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

This will probably confuse noobs, which might be a good thing. It will make them stronger. It's not like there's anywhere else for them to go.

## Environment

* Operating System: OSX
* Truffle version: v3.2.4
* Ethereum client: testrpc v3.0.5
* node version: v7.7.4
* npm version: 4.6.1

**Comment by pimotte** [comment]
The same is displayed if you use "String" instead of "string" or use "type" as a variable name. I haven't actually seen a sane compiler error, so I don't even know if this functionality exists? (clearly, I'm one of the above-mentioned noobs).

**Comment by illuzen** [comment]
🤣  we should definitely strive for clear error messages. I've been meaning to dig into the compiler sauce, so maybe I'll make that my first project, make it spit out at least a line number or something. Whatever I have at /usr/local/bin/solc gives reasonable errors, so it's probably just a matter of passing them thru the javascript.

**Comment by marcabbink** [comment]
Yes I'm sure we're gonna save a lot of people a lot of time by checking for these things when compiling

**Comment by paulhauner** [comment]
This error is also generated if you happen to replace `contracts/Migrations.sol` with the code demonstrated here: http://truffle.readthedocs.io/en/beta/getting_started/migrations/

The actual `migrations.sol` code generated by `truffle init` is different to the code stated at the above link and does not build.

**Comment by tinder-dyakobian** [comment]
How the hell am I supposed to debug my code :(. I waited until writing 10 contracts to compile

**Comment by beether** [comment]
If it says: `Compiling ./contracts/MyContract.sol...` is it safe to assume the error is in MyContract.sol, or is it in the next (not printed) contract?

**Comment by beether** [comment]
Wow FFS you cannot even see which file is getting the compilation error

**Comment by GlenDC** [comment]
Might try to make time for this to help with this issue if no one is pushing any PR for this yet.

**Comment by illuzen** [comment]
@GlenDC I spent a little time on it, didn't figure out which layer it's occurring at, so have at it. 👍

**Comment by beether** [comment]
@illuzen @GlenDC I'm interested at taking a crack at it, but I can't find the source code for truffle other than the giant bundle.  Is there some other branch I can checkout?

**Comment by jjc12** [comment]
I'm getting this error too, it's annoying

**Comment by jjc12** [comment]
Honestly, I think it's because I'm trying to index a byte array, _and then overwrite it_. That is not allowed in Solidity; indexing is read-only.

**Comment by mezzomix1810** [comment]
Had the same problem. Took me very long to debug. Using linter-solidity for Atom helped. (in case u use Atom) https://atom.io/packages/linter-solidity

**Comment by illuzen** [comment]
@beether from the giant bundle's README: https://github.com/trufflesuite/truffle-core

**Comment by eugene-babichenko** [comment]
The same problem too. Just because of a typo in a variable name in an expression like `abc += 1`.

**Comment by tcoulter** [comment]
This is an error in Solidity. It will be fixed when we upgrade to Solidity 0.4.13. Please see #484 to track our progress. Thanks!

**Comment by dyba** [comment]
None of the answers helped me but adding [Solium](https://github.com/duaraghav8/Solium) to my tool chain and running the commands:

```
solium --init
solium --dir .
```

In the root of the project, helped pinpoint the errors in my `.sol` files. After I addressed the errors, running `truffle compile` and `truffle migrate` worked fine.

**Comment by tcoulter** [comment]
This issue has been fixed. Please upgrade to the latest version of Truffle. Thanks!
