### ISSUE TITLE
In-test debugging doesn't seem to work

### ISSUE THREAD

**Issue by spectre1989** [trufflesuite/truffle#4150]
On the docs page about debugging [here ](https://www.trufflesuite.com/docs/truffle/getting-started/debugging-your-contracts#in-test-debugging) it describes how to debug contracts using a test, this first example is with a transaction.

Then [here](https://www.trufflesuite.com/docs/truffle/getting-started/debugging-your-contracts#debugging-read-only-calls) it describes how to debug read-only calls.

Neither of these seems to work, I've got a tiny test project to show this [here](https://github.com/spectre1989/truffle-in-test-debugging-issue).

The debugger does start, but stepping or continuing won't work because no transaction is loaded. See output:

> PS C:\Users\joebe\Desktop\truffle-in-test-debugging-issue> truffle test --debug
> Compiling your contracts...
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\MyContract.sol
> Artifacts written to C:\Users\joebe\AppData\Local\Temp\test--2280-I6nyMXRAe2t2
> Compiled successfully using:
>    - solc: 0.5.16+commit.9c3226ce.Emscripten.clang
> 
> 
> 
>   Contract: MyContract
> 
>   ...
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>   Test run interrupted.
>   Debugging MyContract.setValue(100)
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 
> Starting Truffle Debugger...
> √ Gathering information about your project...
> 
> Commands:
> (enter) last command entered (step next)
> (o) step over, (i) step into, (u) step out, (n) step next
> (c) continue until breakpoint, (Y) reset & continue to previous error
> (y) (if at end) reset & continue to final error
> (;) step instruction (include number to step multiple)
> (g) turn on generated sources, (G) turn off generated sources except via `;`
> (p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
> (l) print additional source context, (s) print stacktrace, (h) print this help
> (q) quit, (r) reset, (t) load new transaction, (T) unload transaction
> (b) add breakpoint (`b [[<source-file>:]<line-number>]`; see docs for more)
> (B) remove breakpoint (similar to adding, or `B all` to remove all)
> (+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
> (?) list existing watch expressions and breakpoints
> (v) print variables and values, (:) evaluate expression - see `v`
> 
> debug(test)> i
> No transaction loaded.
> 
> debug(test)> c
> No transaction loaded.

**Comment by spectre1989** [comment]
oh man, sorry about that @haltman-at, thanks for moving it

**Comment by haltman-at** [comment]
OK, now that I look at this...

Unfortunately it looks like our documentation is simply incorrect here.  (So, I guess this did end up being a documentation issue after all!  Going to leave this on this repo though.)  I think that was added prematurely; we had intended to make in-test debugging work with calls, but actually doing this ran into problems and it was never done.  Somehow that made it into the documentation anyway; I hadn't noticed that.  Sorry about that.

In the meantime, you can work around this limitation by forcing the call to be a transaction instead.  You can use `instance.getValue.sendTransaction()` to force a transaction, and then you'll be able to debug that.

I'll go update the documentation to reflect this.  Again, sorry about the confusion.  It's also possible we need to produce a better error message if someone does attempt to use `debug` with a call...

**Comment by spectre1989** [comment]
That doesn't work either though, if you check the example repo I linked there's both a call and a transaction in there and neither work for me.

**Comment by haltman-at** [comment]
Oh, weird.  OK, I'll check out what's going on there then.

**Comment by haltman-at** [comment]
OK, I've confirmed it's not working.  How odd.  Well, I'm just going to have to figure out what's going wrong...

**Comment by haltman-at** [comment]
OK, found the problem, I've put up #4151 to fix this.  Also, it turns out that (with the fix) in-test debugging *does* work with calls and not just transactions...?  My mistake!  Sorry about that.

Anyway, the fix is pretty simple so you can expect it will go out in the next release.

**Comment by spectre1989** [comment]
Awesome, thanks so much @haltman-at

**Comment by haltman-at** [comment]
OK, this is out now!  Feel free to open a new issue if there are further problems with in-test debugging.
