### ISSUE TITLE
Add support for access lists

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4156]
## Issue

Web3 1.4.0 is out, and add supports for access lists.  I've already put up #4155 to update web3 to 1.4.0, but once that's done, we then need to add support for access lists.

Note that #3974 & #4142 will also presumably need considerable updating to handle access lists.

## Environment

* Truffle version (`truffle version`): 5.3.13

**Comment by haltman-at** [comment]
Hm, wondering if actually we want to wait on Ganache 7 for this.

**Comment by kevinbluer** [comment]
Closing as this is addressed in https://github.com/trufflesuite/truffle/releases/tag/v5.4.24
