### ISSUE TITLE
Potential vulnerability in the package

### ISSUE THREAD

**Issue by paimon0715** [trufflesuite/truffle#4158]
Hi, @haltman-at, @gnidan
### Issue

   1 vulnerability (high severity) is introduced in **_@truffle/contract-schema_**:
   Vulnerability **SNYK-JS-CRYPTOJS-548472** (high severity) is detected in package **_crypto-js_** (versions: <3.2.1,>=3.3.0 <4.0.0):  [ https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472]( https://snyk.io/vuln/SNYK-JS-CRYPTOJS-548472)
  The above vulnerable package is referenced by **_@truffle/contract-schema_** via:
` @truffle/contract-schema@3.4.1 ➔ crypto-js@3.3.0`

### Solution
Since **_@truffle/contract-schema 3.4.*_** is transitively referenced by **276** downstream projects (e.g., [@truffle/contract 4.3.19](https://www.npmjs.com/package/@truffle/contract) (latest version), [@chainlink/contracts 0.1.7](https://www.npmjs.com/package/@chainlink/contracts) (latest version), [truffle-contract 4.0.31](https://www.npmjs.com/package/truffle-contract)  (latest version), [@openzeppelin/test-helpers 0.5.11](https://www.npmjs.com/package/@openzeppelin/test-helpers) (latest version), [@nomiclabs/truffle-contract 4.2.23](https://www.npmjs.com/package/@nomiclabs/truffle-contract) (latest version)), 

If **_@truffle/contract-schema_** removes the vulnerable packages from the above versions, then its fixed version can help downstream users decrease their pain.

Could you help update packages in 3.4.*?

### Fixing suggestions

In **_@truffle/contract-schema 3.4.*_**, you can kindly perform the following upgrades :
`crypto-js ^3.1.9-1 ➔  ~3.2.1`;  

**Note:**
_>crypto-js@3.2.1，<3.3.0 have fixed the vulnerability SNYK-JS-CRYPTOJS-548472_

Thanks for your contributions to the npm ecosystem!

Best regards,
Paimon

**Comment by eggplantzzz** [comment]
@paimon0715 Thanks for bringing this to our attention! Looking at it I can't actually see where we use this library. I'll have to check with the rest of the team to see if they know why it is included in here but perhaps we can just remove it altogether.

**Comment by eggplantzzz** [comment]
Looks like there is a PR that removes this along with a lot of other unused dependencies https://github.com/trufflesuite/truffle/pull/4149

**Comment by paimon0715** [comment]
@eggplantzzz Thanks for your help!

**Comment by cliffoo** [comment]
Looks like this should be closed but slipped by! Thanks @paimon0715 for bringing this up
