### ISSUE TITLE
TypeError: Cannot read property '0' of null' on 'Truffle Console' with Rinkeby

### ISSUE THREAD

**Issue by dotnetspec** [trufflesuite/truffle#416]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Hi. I try the below with Rinkeby (the only public testnet that will (light) sync on my win 32 bit machine). I do get a 'Missing trie node' error on startup though (logged separately under #418). This may be the source of this issue? For now I have ignored it ...

I started the rpc blockchain manager before truffle init, compile and console in my project directory with:

geth --networkid=4 --datadir=$HOME/.rinkeby --syncmode=light --rpc --rpcapi db,eth,net,web3,personal --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*"--ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304

When I afterwards start 'truffle console' from the project directory in another PowerShell instance I get:

PS C:\Users\<user>\Ethereum Projects\truffleprojects\FullStackVoting> truffle console
C:\Users\<user>\AppData\Roaming\npm\node_modules\truffle\lib\environment.js:66
        config.networks[config.network].from = accounts[0];

'TypeError: Cannot read property '0' of null' 

(BTW - I have a Rinkeby account funded with ether on metamask - I perhaps need specify it somewhere/somehow(?))

P.S. If I connect to homestead the error goes away:
geth --rpc --rpcaddr="0.0.0.0" --rpccorsdomain="*" --rpcapi="db,eth,net,web3,personal,web3"

so this is a Rinkeby specific error

## Steps to Reproduce

As above with Rinkeby lightchaindata synced

I get this with:
                host: 'localhost', or
		host:   'http://127.0.0.1',

in truffle-config.js in the project dir

## Expected Behavior

I get console:
>truffle(development): 

## Actual Results

![screenshot 53](https://cloud.githubusercontent.com/assets/27340988/26478390/831468c2-41fe-11e7-9fb6-46717eadc11a.png)

## Environment

* Operating System: Win 10 32 bit
* Truffle version: v3.2.1
* Ethereum client: Geth 1.6.1-unstable
* node version: v7.9.0
* npm version: 4.6.1

**Comment by karalabe** [comment]
Seems that `accounts` is not defined, so when you try to index into it you get an error? I'm not familiar with truffle to answer what's happening here, but perhaps that's the issue? Do you have accounts on Rinkeby inside Geth? E.g. can you see them in the geth console if you type `eth.accounts`?

**Comment by tcoulter** [comment]
@karalabe @dotnetspec That is most likely the issue, one that Truffle isn't handling well. You'll have to specify at least one account in your Rinkeby geth client, or use a provider like the [truffle-hdwallet-provider](https://github.com/trufflesuite/truffle-hdwallet-provider) with Rinkeby that will manage an account for you. See `provider` option [here](http://truffleframework.com/docs/advanced/configuration#networks) for configuration.

**Comment by dotnetspec** [comment]
Thanks,
I installed 
truffle-hdwallet-provider 
and updated truffle-config.js in the project directory so it now specifies:

// Allows us to use ES6 in our migrations and tests.
require('babel-register')
var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "<mnemonic added>";
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*' // Match any network id
    },
	ropsten: {
      provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/"),
      network_id: 3
    },
	rinkeby: {
      provider: new HDWalletProvider(mnemonic, "https://www.rinkeby.io/"),
      network_id: 4
    }
  }
}

I try:
PS C:\Users\<user>\Ethereum Projects\truffleprojects\FullStackVoting> truffle console --network rinkeby
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<t .......

Following instructions under "connect yourself " on https://www.rinkeby.io/
I have an apparently synced Ethereum client running in a PS instance.

Should I open "Error: Invalid JSON RPC response: " as a separate issue?

Currently I'm no longer getting - "TypeError: Cannot read property '0' of null' "

**Comment by MaxFeldman1** [comment]
To anyone who is seeing this error I dealt with it for many hours only to realise that it was being caused by overloading. The program worked fine in the remix ide but when I called the overloaded function on localhost I got an error saying:
```
Cannot read property '0' of null
```
As soon as I gave the functions separate names the program started operating as expected. Hope this helps you all save some time.

**Comment by spaceh3ad** [comment]
I have same problem. Downgraded truffle from 5.4.6 to 5.3.0 still same error.

```
> Compiling @openzeppelin/contracts/utils/ReentrancyGuard.sol
TypeError: Cannot read property '0' of null
    at detectErrors (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:244:61)
    at run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:39:29)
    at Object.sourcesWithDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:95:58)
    at necessary (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:42:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:38:1
    at async Promise.all (index 0)
    at compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:28:1)
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:71:47)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:86:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)
Truffle v5.3.0 (core: 5.3.0)
Node v14.14.0
```
