### ISSUE TITLE
Direct imports from project directory do not have the `project:/` prefix

### ISSUE THREAD

**Issue by cameel** [trufflesuite/truffle#4161]
## Issue
When using [direct imports](https://docs.soliditylang.org/en/latest/path-resolution.html#direct-imports) (i.e. ones not starting with `./` or `../`) that reference files in project directory Truffle finds the file and includes it in JSON input for the compiler but without the `project:/` prefix (#4137). This results in the file being present in the input twice, under different paths which may lead to errors that seem inexplicable to users.

Since dropping the `project:/` prefix is not an option (I know that Truffle needs some prefix for internal reasons), the only solution I can suggest is to disallow such imports.

## Steps to Reproduce
Here's an example situation where this causes a real issue:
```bash
mkdir truffle-test/
cd truffle-test/
npm install truffle
npx truffle init
echo 'module.exports.compilers.solc.version = "0.8.6";' >> truffle-config.js

echo 'interface I {}' > contracts/I.sol
echo 'import "contracts/I.sol"; contract C is I {}' > contracts/C.sol
echo 'import "./C.sol"; import "./I.sol"; contract D is I, C {}' > contracts/D.sol
npx truffle compile
```

## Actual Results
```solidity
DeclarationError: Identifier already declared.
 --> project:/contracts/D.sol:1:19:
  |
1 | import "./C.sol"; import "./I.sol"; contract D is I, C {}
  |                   ^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
 --> contracts/I.sol:1:1:
  |
1 | interface I {}
  | ^^^^^^^^^^^^^^

Compilation failed. See above.
```

The `sources` dict in the JSON input contains these entries:
```json
"project:/contracts/C.sol": { "content": "import \"contracts/I.sol\"; contract C is I {}\n" },
"project:/contracts/D.sol": { "content": "import \"./C.sol\"; import \"./I.sol\"; contract D is I, C {}\n" },
"project:/contracts/I.sol": { "content": "interface I {}\n" },
"project:/contracts/Migrations.sol": { "content": "// SPDX-License-Identifier: MIT\npragma solidity >=0.4.22 <0.9.0;\n\ncontract Migrations {\n  address public owner = msg.sender;\n  uint public last_completed_migration;\n\n  modifier restricted() {\n    require(\n      msg.sender == owner,\n      \"This function is restricted to the contract's owner\"\n    );\n    _;\n  }\n\n  function setCompleted(uint completed) public restricted {\n    last_completed_migration = completed;\n  }\n}\n" },
"contracts/I.sol": { "content": "interface I {}\n" }
```

Compiler reports an error because it sees interface `I` defined in what seems to be two independent source units: `project:/contracts/I.sol` and `contracts/I.sol`. In effect there are two different interfaces that just happen to share the same name (which is fine unless they're imported from the same file without changing the name).

I think that this error would be very confusing to users.

## Expected Behavior
The above example would compile if we changed the content of `C.sol` to:
```solidity
import "./I.sol";
contract C is I {}
```

I would be reasonable to expect both to compile without errors but I don't think this can be achieved without rewriting imports or dropping the `project:/` prefix. Therefore my proposal would be for Truffle to report imports like `import "contracts/I.sol"` as errors and only support relative imports (i.e. `import "./I.sol"`) for files within project directory.

## Environment

* Operating System: Arch Linux
* Truffle version: both `5.3.14` and current `develop` (abfb3646eea9d57e0a6f9186c12bb51680c181d8)
* node version: `v16.4.2`
* npm version: `7.17.0`

**Comment by haltman-at** [comment]
Hm, I don't think there's any reasonable way to make this work.  We either have to just disallow such imports (you already weren't really supposed to be doing that, direct imports are for NPM and such!), or get rid of `project:/` (in which case we can make it work but I don't think @gnidan will like that :P ).

**Comment by gnidan** [comment]
Closing this as no-longer-relevant, as of Truffle v5.4.2 (see [release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.4.2)).

Thanks both of you!
