### ISSUE TITLE
Allow console.require scripts to access console globals

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4174]
## Issue

This issue is a follow-on to #2472.  That issue has been closed due to the merging of #4127, but not everything asked for in the original issue is yet possible.  So, I'm filing issues to cover what remains.

PR #4127 makes it possible to write scripts that will run at console startup... but it doesn't allow a lot of the things you'd want to do with such a script, because such scripts have no access to console globals (such as `web3`, `accounts`, and, most importantly, the various contract abstractions).  A lot of what you'd want to do with a console startup script involves the contract abstractions.  So, we should make console globals available in startup scripts to make such scripts more useful.

(Alternatively, we could just make `artifacts` or something similar available.)

## Environment

* Truffle version (`truffle version`): 5.4.0

**Comment by eggplantzzz** [comment]
As of [Truffle 5.4.5](https://github.com/trufflesuite/truffle/releases/tag/v5.4.5) console environment variables are available in scripts. Do note that `artifacts` is not available in the console environment or the scripts.

**Comment by hickscorp** [comment]
But that was the whole point of https://github.com/trufflesuite/truffle/issues/2472 - not having access to `artifacts` voids the point :)
Sorry to ask - I'm a bit lost with cross-references between issues - is there a way for the developer to have a script containing references to `artifacts` and using `await` sourced when Truffle console starts?
