### ISSUE TITLE
Failed to retrieve current release err="Missing trie node ....

### ISSUE THREAD

**Issue by dotnetspec** [trufflesuite/truffle#418]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Error on statring geth rpc which may be causing/related to other errors submitted earlier

## Steps to Reproduce

start geth with:
PS D:\ethereum\testnet\geth> geth --networkid=4 --datadir=$HOME/.rinkeby --syncmode=light --ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=eno
de://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=3030
4

## Expected Behavior

Geth will start without Errors

## Actual Results

Get error:
ERROR[05-26|12:03:20] Failed to retrieve current release       err="Missing trie node 881df3fc23b6741269ee7769a5903663f2003443bca07596e3493ea4ebd88b87"

## Environment

* Operating System: Win 10 32 bit
* Truffle version: v3.2.1
* Ethereum client: Geth 1.6.1-unstable
* node version: v7.9.0
* npm version: 4.6.1

**Comment by tcoulter** [comment]
This does not sound like an issue with Truffle. You should contact the go-ethereum team (CC @karalabe) or write the issue up on the [go-ethereum issues list](https://github.com/ethereum/go-ethereum/issues). 

I unfortunately have not seen that error from geth so won't be able to help.

**Comment by karalabe** [comment]
The release oracle is deployed only on mainnet, not on rinkeby. Curious though that it even tries to access it. Either way, you don't need to care about the that single instance or missing trie node, it just cannot find the release oracle contract, since it doesn't exist. I'll try to look into why it even warns about it on rinkeby.

**Comment by philpraxis** [comment]
+1

**Comment by milan-mitra** [comment]
👍
