### ISSUE TITLE
Using `deployProxy` from `@openzeppelin/truffle-upgrades` fails during a postDeploy reporter on the latest version of truffle (5.4.0).

### ISSUE THREAD

**Issue by ipatka** [trufflesuite/truffle#4183]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using `deployProxy` from `@openzeppelin/truffle-upgrades` fails during a postDeploy reporter on the latest version of truffle (5.4.0).

I was able to get around this by downgrading to 5.2.6

## Steps to Reproduce

Here is an example migration script: https://github.com/rariblecom/protocol-contracts/blob/master/tokens/migrations/2_initial_erc721.js

```
const { deployProxy } = require('@openzeppelin/truffle-upgrades');

const ERC721Rarible = artifacts.require('ERC721Rarible');

module.exports = async function (deployer) {
  await deployProxy(ERC721Rarible, ["Rarible", "RARI", "ipfs:/", ""], { deployer, initializer: '__ERC721Rarible_init' });
};
```

## Expected Behavior

Deploy and Postdeploy happen without errors

## Actual Results

   Deploying 'TransparentUpgradeableProxy'
   ---------------------------------------
   > transaction hash:    0x03bbd149e50268059e6d5f9a08c72a2aab5643290cb42626b6cafc9083209c05
   ⠴ Blocks: 0            Seconds: 12
TypeError: data.contract.interfaceAdapter.getTransactionCostReport is not a function

## Environment

* Operating System: macOS 11.4
* Ethereum client: Infura
* Truffle version (`truffle version`): 5.4.0
* node version (`node --version`): 14.16.1
* npm version (`npm --version`):  6.14.12

**Comment by zicofish** [comment]
I confirm this error also in  Truffle version 5.4.1

**Comment by eggplantzzz** [comment]
Thanks for reporting this @ipatka, we'll take a look into this!

**Comment by ayusht11** [comment]
Facing the same issue. Please fix this.

**Comment by anuragmath** [comment]
I m having same issue as well, but my truffle version is lower.

Truffle v5.3.10 (core: 5.3.10)
Solidity - 0.6.5 (solc-js)
Node v14.13.0
Web3.js v1.3.6

**Comment by mranoncoder** [comment]
I have the same error too!

**Comment by T4533N** [comment]
Is there any fix?

**Comment by bergarces** [comment]
So... It looks like `@openzeppelin/truffle-upgrades` uses an old version of `@truffle/contract` in which the interface adapter does not have the new reporting method (https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-truffle/package.json#L27)

Thus, using a version of Truffle in which the reporter requires that method will throw that error.

If someone could try to bump the `@truffle/contract` version of `@openzeppelin/truffle-upgrades` and check that there are no conflicts and it all works, that's pretty much the answer.

cc @eggplantzzz

**Comment by JUDOKICK** [comment]
Workaround also for this as @bergarces pointed out is to include

@truffle/contract : 4.3.26 in you package.json and reinstall packages with.

``rm -rf node_modules && rm package-lock.json && npm install``

**Comment by cds-amal** [comment]
@JUDOKICK can you verify the workaround is successful?

**Comment by cds-amal** [comment]
@JUDOKICK , @T4533N Is this still an issue?

**Comment by haltman-at** [comment]
Closing this for issue maintenance, but let us know if there's still a problem here and we can reopen!
