### ISSUE TITLE
This contract object doesn't have address set yet (Truffle React error)

### ISSUE THREAD

**Issue by Joncarre** [trufflesuite/truffle#4205]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Hello, I'm trying to access to `localhost:3000` using Truffle React box. When I execute `npm run start` I get this error:

> Unhandled Rejection (Error): This contract object doesn't have address set yet, please set an address first.

## Steps to Reproduce
Execute `npx truffle unbox react`. Then throw `truffle develop`, `compile` and `migrate` (I'm migrating to kovan network). In another terminal, execute `npm run start`, open your browser and try to access to `localhost:3000` (in my case).

## Expected Behavior
In theory I'm able to interact with the contracts in the project, which is `SimpleStorageContract.sol`, and the website should be this one:

![website](https://user-images.githubusercontent.com/25104806/127198256-29ffe3b2-8558-4c19-9abb-ab1c58e99316.png)

## Actual Results

Instead of that, the page shows a problem about the contract address. But the contract address has its address when it has been deployed to kovan network (I can see it everytime I execute `migrate --network kovan`). Am I missing something?

![Error](https://user-images.githubusercontent.com/25104806/127198477-37e8992c-8e8b-463d-96a2-0101c7443481.png)

## Environment

* Operating System: Linux Mint 20.1 Cinnamon
* Ethereum client: Infura (with Metamask wallet)
* Truffle version (`truffle version`): v5.4.2
* node version (`node --version`): v10.19.0
* npm version (`npm --version`): 6.14.4

**Comment by gnidan** [comment]
Could you run `truffle networks` to ensure that Truffle can find your deployed contracts after migrate?

If that command gives the information you'd expect, then it sounds like either a problem with the configuration in your frontend. We can try to reproduce on our side, but could you also please confirm that you are connected to Kovan on MetaMask? The behavior you report sounds like the same behavior as if MetaMask were connected to Mainnet (of course it might be something else entirely, but just trying to rule things out)

Please let us know! Would love to help you get this sorted out. Thanks!

**Comment by Joncarre** [comment]
Thanks for your answer! About Metamask, yes, I am connected to Kovan network with an address taken from Truffle (one of those 10 addresses that it gives executing `compile`).

![Screenshot from 2021-07-28 22-12-55](https://user-images.githubusercontent.com/25104806/127389576-098300d1-9fab-4939-a754-4671e9fa606a.png)

About the command `truffle network` I don't like the message... 

```
truffle(develop)> network
evalmachine.<anonymous>:0
network
^

Uncaught ReferenceError: network is not defined
    at evalmachine.<anonymous>:0:1
    at sigintHandlersWrap (vm.js:274:12)
    at Script.runInContext (vm.js:142:14)
    at runScript (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:329:1)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:344:1)
    at bound (domain.js:416:15)
    at REPLServer.runBound [as eval] (domain.js:427:12)
    at REPLServer.onLine (repl.js:819:10)
    at REPLServer.emit (events.js:375:28)
    at REPLServer.emit (domain.js:470:12)
```
But I don't understand it... My `truffle-config.js` is correctly configured (I guess):

```
const HDWalletProvider = require('@truffle/hdwallet-provider')
require('dotenv').config()

const mnemonic = "daughter deny can..."
const project = "9e26..."

module.exports = {
  networks: {
    kovan: {
      provider: () => {
        return new HDWalletProvider(mnemonic, "https://kovan.infura.io/v3/" + project)
      },
      network_id: '42',
      skipDryRun: true,
      networkCheckTimeout: 8000000,
      timeoutBlocks: 4000
    },
  },
  compilers: {
    solc: {
      version: '0.6.6',
    },
  },
}
```

**Comment by cds-amal** [comment]
There is a typo, the command is `truffle networks` with an `s`

**Comment by Joncarre** [comment]
@cds-amal hey mate, are you sure about that? The documentation says `network` without `s` 

https://www.trufflesuite.com/docs/truffle/reference/truffle-commands

**Comment by cds-amal** [comment]
@Joncarre Here's [the networks documentation](https://www.trufflesuite.com/docs/truffle/reference/truffle-commands#networks).

**Comment by Joncarre** [comment]
@cds-amal Oh, sorry! I didn't understand you. Yes, I can see my contract' address (also I could see it when I executed `migrate`). But then, why it doesn't work? :( Why my App.js can't "see" my contract' address? I haven't changed anything, just followed the steps in the documentation.

```
truffle(develop)> networks

Network: develop (id: 5777)
  No contracts deployed.

Network: kovan (id: 42)
  Migrations: 0x7e52d04C7043FA0... (intentionally deleted)
  SimpleStorage: 0xb608baa8f9F04d4b37... (intentionally deleted)
```

**Comment by Joncarre** [comment]
Done. After this piece of code:

```
      const instance = new web3.eth.Contract(
        SimpleStorageContract.abi,
        deployedNetwork && deployedNetwork.address,
      );
```

I've added this line:

`instance.options.address = "[my contract' address on kovan]"`

Working right now. Thanks for help guys! :)

**Comment by cds-amal** [comment]
Glad things are working @Joncarre, I'll go ahead and close this issue now.
