### ISSUE TITLE
Compilation Fails on Import Statements After Truffle Upgrade to 5.4.3

### ISSUE THREAD

**Issue by JF0001** [trufflesuite/truffle#4218]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

After upgrading truffle to version 5.4.3, the compilation fails on all Import statements (refer to example below). 

ERROR (for one import, but receiving the same error for all imports):
ParserError: Source "node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol" not found
 --> project:/contracts/CryptoAstres.sol:4:1:
  |
 import "../../node_modules/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

## Steps to Reproduce

Upgrade and compile contract.

## Expected Behavior

Successful compilation. 

## Actual Results

Please see above.

## Environment

* Operating System: Ubuntu 20.04, up to date
* Ethereum client: Ganache
* Truffle version (`truffle version`): 5.4.3
* node version (`node --version`): 14.17.4
* npm version (`npm --version`): 7.20.3

**Comment by haltman-at** [comment]
It looks like you're trying to import from an NPM package from outside your project directory.  To do that, you shouldn't be using a file path, but should rather use Truffle's builtin ability to import from installed NPM packages.  I.e., the thing to do here would be

```solidity
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
```

Hope that's helpful!

**Comment by JF0001** [comment]
Thank you @haltman-at The npm package is actually installed in my directory. This is how I was importing them before upgrading, and everything was working properly. If I use the syntax you are showing, VS Code is no longer finding the files.

**Comment by haltman-at** [comment]
Ah, I just guessed that the importing contract was in `contracts` (rather than something lower down), since you didn't specify.

So, to be clear, `node_modules` is inside the Truffle project directory?  Hm, it ought to work then.  Do you possibly have a reproduction example we could inspect?

I would still recommend just using the syntax I mentioned if you are using Truffle on its own, but I will admit I have no idea how it would interact with VS Code.

**Comment by JF0001** [comment]
Correct, the node_modules directory (which contains all my npm packages) is located directly in the root directory of my smart contract project (which also contains the package.json file). It has been working fine for a long time as such, until I upgraded earlier today. I unfortunately do not have a public reproduction anywhere. Yes, VS Code is complaining when I try to use the syntax suggested. Thank you again.

**Comment by JF0001** [comment]
Actually @haltman-at I got it to work by slightly changing the syntax importing the files (I realised that I was doing it awkwardly - never noticed this until today). It appears that the previous version of Truffle was more lenient. Thank you very much for your help!

**Comment by haltman-at** [comment]
Well, I'm still a little confused as to why it didn't work initially, but if you say there's no problem then I suppose we can leave this.  Thanks for the report!
