### ISSUE TITLE
Error: Invalid JSON RPC response for truffle console --network rinkeby

### ISSUE THREAD

**Issue by dotnetspec** [trufflesuite/truffle#423]
Issue

I addressed the same error in another issue but I now need this to work in rinkeby (the only public testnet I can get to sync so far)

Unable to get a truffle console when sync to Rinkeby testnet

Steps to Reproduce:
In one Powershell instance run geth:
geth --networkid=4 --datadir=$HOME/.rinkeby --syncmode="light" --rpc --rpcapi "db,eth,net,web3,personal" --cache=1024  --rpcport 8545 --rpcaddr "127.0.0.1" --rpccorsdomain "*"--ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304

In another Powershell instance:
type ' truffle console --network rinkeby' in the truffle project directory

Expected Behavior:

I get a truffle console:

    truffle(rinkeby):

Actual Results

PS C:\Users<dir>\Ethereum Projects\truffleprojects\FullStackVoting> truffle console --network rinkeby

events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html lang etc...
title>\n</head>\n<body>\n<pre>Cannot POST /</pre>\n</body>\n"etc....

Environment

    Operating System: Win 10 32 bit
    Truffle version: v3.2.1
    Ethereum client: Geth 1.6.1-unstable
    node version: v7.9.0
    npm version: 4.6.1

Thanks for any assistance ...

**Comment by tcoulter** [comment]
Thanks for the report. This is due to Truffle not being able to connect to your Ethereum client. We're going to make Truffle recognize this issue and provide a more useful error message. See #489. Thanks!
