### ISSUE TITLE
Events ignore quiet setting (so e.g. compilation warnings are displayed at inappropriate times)

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4237]
## Issue

The events system largely ignores the `quiet` setting.  This causes things to be printed to the console when they shouldn't be.  For instance, if you do `truffle debug --fetch-external`, and the downloaded contract has compilation warnings, you'll see those compilation warnings, even though the debugger makes sure to set `quiet: true` when performing compilation.

Now, if you look at the code in `events`, you'll notice that there are a number of checks of `this.quiet`.  These checks do work.  But the problem is, `this.quiet` is only set on events system startup!  And often `quiet` is set to true *after* the events system is initialized.  So in order for `quiet` to work, somehow the event system would have to know that `quiet` was now true!

Basically, the `quiet` option in the events system doesn't currently achieve the goal of letting us use `quiet: true` in the way we normally would.

A possible stopgap would be to add manual `quiet` checks before emitting such events, but obviously that's not a great solution.  (Or maybe it's the right solution after all?  IDK.)

Another thing we could do for now is to re-initialize the events system everywhere that we set `quiet: true` after the events system has been initialized. Whee. :-/

A third thing we could do for now would be to, everywhere we set `quiet: true` after the events system has been initialized, reach into the events system and manually set *its* `quiet` to true, assuming that's possible... :-/

So uh yeah none of this seems great but we ought to do *something* because right now starting up the debugger can show you compiler warnings.

## Steps to Reproduce

As an example, try debugging mainnet transaction 0x4e67f687fbec1989df366e3a4b6a25e8b62bca8db80afe90918dcc8fbe425ec7 (the same one from #4235) with `--fetch-external`.  You'll see compilation warnings displayed as the debugger starts up.  Those shouldn't be shown during debugger startup.

## Environment

* Truffle version (`truffle version`): 5.4.5

**Comment by eggplantzzz** [comment]
Thanks @haltman-at. Yeah, so the events system gets re-initialized every time a new config is loaded but, like you mentioned, it looks like the value of `quiet` must change without re-initializing a new config. The events system has a method for hooking into the settings called [`updateSubscriberOptions`](https://github.com/trufflesuite/truffle/blob/develop/packages/events/EventManager.js#L45-L49) that we can use to update the system. Fix incoming!

**Comment by eggplantzzz** [comment]
Actually I think there is a bug in the `with` method for @truffle/config. I don't think the values provided to `with` are getting set correctly in the Subscribers. I fixed this and pushed it up to the `fix/quiet-option` branch, is there any way you could test this out to see if it fixes your problem? Or are there other cases where `quiet` is set without the `with` method?

**Comment by haltman-at** [comment]
Good question!  I can only find places where it's set with `with`; I can't find any places where it's set directly.  I'll look a bit more but if I don't comment on the matter again you should assume I didn't find any.

**Comment by haltman-at** [comment]
OK yeah as best I can tell, the only places where it's set are all in `core` and all use `with`.

Specifically, there's one instance in `debug/compiler.js`, one in `testing/SolidityTest.js`, two in `testing/Test.js`, and one in `testing/TestRunner.js`.

**Comment by haltman-at** [comment]
So uh turns out I was mistaken and this works fine! >_>  Sorry about that...

**Comment by gnidan** [comment]
This is fixed in [Truffle v5.4.7](https://github.com/trufflesuite/truffle/releases/tag/v5.4.7). Thanks all!
