### ISSUE TITLE
replace global with globalThis

### ISSUE THREAD

**Issue by segersb** [trufflesuite/truffle#4238]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
The "global" variable should be replaced with the standardized "globalThis"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

## Steps to Reproduce

run `truffle develop`

truffle(develop)> let accounts = await web3.eth.getAccounts()
Uncaught ReferenceError: global is not defined
    at evalmachine.<anonymous>:2:19

global = globalThis

truffle(develop)> let accounts = await web3.eth.getAccounts()
undefined
truffle(develop)> accounts
[
  '0xc30567b10027c99C6b22d578B9dEB85990b954bE',
  '0xDCF9e2547212Ad204db456Af4B99a868e25293b0',
  '0xaAC71A7B59C83A67bF1d616F411C1570fC58029D',
  '0x7Aa3211e33D24eF45B42016d6c5B748657f477f2',
  '0x3B2D7Cc5bA1f7B9d2a711C0A1cBab28Ef0cB7B46'
]

## Expected Behavior

Truffle develop should work without using the "global = globalThis" workaround

## Actual Results

Truffle develop returns the error "global is not defined"

## Environment

* Operating System: Windows
* Ethereum client: Truffle develop

Truffle v5.4.5 (core: 5.4.5)
Solidity v0.5.16 (solc-js)
Node v14.17.4
Web3.js v1.5.1

**Comment by cds-amal** [comment]
Thanks for raising this issue @segersb . We're aware of it and have a proposed fix awaiting review. 
A temporary workaround is to explicitly define `global` in the REPL: 
```
global = this 
```
Note: `globalThis` is not available in node 10

**Comment by segersb** [comment]
Yeah, I found the workaround and I'm using the LTS version of Node.
The stable node version is 14 and I think the latest is 16, so I guess most people will be ok with a min version of 10.
I'll close the issue since it's already being handled.
Thanks
