### ISSUE TITLE
Truffle console context is incomplete

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#4239]
Truffle console is missing some definitions in its context.

| Truffle v5.3.9                       | Truffle v5.4.x                              |
|-------------------------------------|------------------------------------|
| truffle(develop)> Object.keys(this) | truffle(develop)> Object.keys(this)|
|  global                             |                                    |
|  clearInterval                      |                                    |
|  clearTimeout                       |                                    |
|  setInterval                        |                                    |
|  setTimeout                         |                                    |
|  queueMicrotask                     |                                    |
|  clearImmediate                     |                                    |
|  setImmediate                       |                                    |
|  __core-js_shared__                     |                                    |
|  @@any-promise/REGISTRATION         |                                    |
|  web3                               | web3                               |
|  interfaceAdapter                   | interfaceAdapter                   |
|  accounts                           | accounts                           |
|  ConvertLib                         | ConvertLib                         |
|  MetaCoin                           | MetaCoin                           |
|  Migrations                         | Migrations                         |

**Comment by eggplantzzz** [comment]
Fixed with https://github.com/trufflesuite/truffle/releases/tag/v5.4.6.
