### ISSUE TITLE
Ensure license files exist in all Truffle repositories

### ISSUE THREAD

**Issue by KadeMorton** [trufflesuite/truffle#424]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

There is no license in the truffle-contract repo. In the event there is no license listed the contents of the repo fall under copyright, meaning the contents cannot be used. I've made a pull request with the MIT license that's waiting to be merged in.

## Steps to Reproduce

Look at the truffle-contract repo.

## Expected Behavior

There should be a license file allowing people to use the contract.

## Actual Results

There is no license file in the repo, meaning it's under copyright. 

## Environment

* Operating System: All
* Truffle version: All
* Ethereum client: All
* node version: All
* npm version: All

**Comment by tcoulter** [comment]
Note: MIT for all Truffle repositories (except the website).
