### ISSUE TITLE
global is not defined error

### ISSUE THREAD

**Issue by zelindm** [trufflesuite/truffle#4246]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle console works with errors with node v12.

## Steps to Reproduce

Use node v12. Run truffle console. Compile. Migrate. try to interact with a contract. let contract = await Token.deployed(). Get the error.

## Expected Behavior

No errors

## Actual Results

Uncaught ReferenceError: global is not defined at evalmachine.<anonymous>:2:19

## Environment

* Operating System: MasOS
* Ethereum client: Ganache
* Truffle version (`truffle version`): v5.1.51 (core: 5.1.51)
* node version (`node --version`): v12.22.4
* npm version (`npm --version`): 6.14.14

**Comment by cds-amal** [comment]
Hi @zelindm , we're aware of this issue and working on a fix (#4242). A temporary work around is to run the following command in the REPL: `global = this`.

**Comment by eggplantzzz** [comment]
This is fixed in the [latest Truffle](https://github.com/trufflesuite/truffle/releases/tag/v5.4.6). Thanks for reporting this @zelindm!
