### ISSUE TITLE
Truffle Migrate

### ISSUE THREAD

**Issue by BarryHewitt** [trufflesuite/truffle#4247]
Good afternoon everyone

I am trying to do a truffle migrate to the BSC Test Net and when I write truffle migrate or truffle migrate --reset in the terminal the response i get is

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Fetching solc version list from solc-bin. Attempt #1

Here is my truffle-config file, all my sol files have the same compiler version, I've been at this all day so any help would be appreciate
```javascript
/**
 * Use this file to configure your truffle project. It's seeded with some
 * common settings for different networks and features like migrations,
 * compilation and testing. Uncomment the ones you need or modify
 * them to suit your project as necessary.
 *
 * More information about configuration can be found at:
 *
 * trufflesuite.com/docs/advanced/configuration
 *
 * To deploy via Infura you'll need a wallet provider (like @truffle/hdwallet-provider)
 * to sign your transactions before they're sent to a remote public node. Infura accounts
 * are available for free at: infura.io/register.
 *
 * You'll also need a mnemonic - the twelve word phrase the wallet uses to generate
 * public/private key pairs. If you're publishing your code to GitHub make sure you load this
 * phrase from a file you've .gitignored so it doesn't accidentally become public.
 *
 */

const HDWalletProvider = require('@truffle/hdwallet-provider');
//
// const fs = require('fs');
const mnemonic = require("./secrets.json").mnemonic

module.exports = {
  /**
   * Networks define how you connect to your ethereum client and let you set the
   * defaults web3 uses to send transactions. If you don't specify one truffle
   * will spin up a development blockchain for you on port 9545 when you
   * run `develop` or `test`. You can ask a truffle command to use a specific
   * network from the command line, e.g
   *
   * $ truffle test --network <network-name>
   */

  networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache-cli, geth or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    // development: {
    //  host: "127.0.0.1",     // Localhost (default: none)
    //  port: 8545,            // Standard Ethereum port (default: none)
    //  network_id: "*",       // Any network (default: none)
    // },
    // Another network with more advanced options...
    // advanced: {
    // port: 8777,             // Custom port
    // network_id: 1342,       // Custom network
    // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
    // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
    // from: <address>,        // Account to send txs from (default: accounts[0])
    // websocket: true        // Enable EventEmitter interface for web3 (default: false)
    // },
    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    bscTestnet: {
      provider: () => new HDWalletProvider(mnemonic, `https://speedy-nodes-nyc.moralis.io/bcf0017bb895dcaaa02ec143/bsc/testnet`),
      network_id: 97,       // Ropsten's id
      gas: 5500000,        // Ropsten has a lower block limit than mainnet
      confirmations: 10,    // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
    // Useful for private networks
    // private: {
    // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
    // }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "^0.8.7",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  },

  // Truffle DB is currently disabled by default; to enable it, change enabled:
  // false to enabled: true. The default storage location can also be
  // overridden by specifying the adapter settings, as shown in the commented code below.
  //
  // NOTE: It is not possible to migrate your contracts to truffle DB and you should
  // make a backup of your artifacts to a safe location before enabling this feature.
  //
  // After you backed up your artifacts you can utilize db by running migrate as follows: 
  // $ truffle migrate --reset --compile-all
  //
  // db: {
    // enabled: false,
    // host: "127.0.0.1",
    // adapter: {
    //   name: "sqlite",
    //   settings: {
    //     directory: ".db"
    //   }
    // }
  // }
};
```

**Comment by gnidan** [comment]
> ```javascript
>       /* ... */
>       version: "^0.8.7",    // Fetch exact version from solc-bin (default: truffle's version)
>       /* ... */
> ```

This might be a problem, since the latest Solidity version is 0.8.6

**Comment by BarryHewitt** [comment]
Thanks for the reply, i've changed it to 0.8.6 but still the same issue, really can't figure out what's going on, i've looked over everything so many times, the migration files are defiantly containing the correct sol file names, no errors anywhere, urgh, just want this sorting so i can go to sleep, really bugging me now

**Comment by gnidan** [comment]
Try `truffle migrate --reset --compile-all`

**Comment by gnidan** [comment]
oh wait Solidity 0.8.7 just released

**Comment by BarryHewitt** [comment]
same story with - truffle migrate --reset --compile-all

The **** is going on

**Comment by gnidan** [comment]
So it does compilation but then just stops? Could you screenshot your whole output?

**Comment by BarryHewitt** [comment]
so in the terminal I type - truffle migrate --reset --compile-all

And I get back this

truffle(bscTestnet)> truffle migrate --reset --compile-all

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

- Fetching solc version list from solc-bin. Attempt #1

truffle(bscTestnet)>

![image](https://user-images.githubusercontent.com/53466236/129078331-7e34370e-d1fc-4b20-ade7-bcd4feac5c5a.png)

**Comment by BarryHewitt** [comment]
![image](https://user-images.githubusercontent.com/53466236/129078649-fc3026fd-d7f0-4f2c-a1a4-e4f713b90793.png)

**Comment by gnidan** [comment]
It looks like your contracts are nested in two `contracts/` directories. Try moving all of those sol files up one directory.

**Comment by BarryHewitt** [comment]
if this is what you meant it hasn't worked either unfortunately :-/

![image](https://user-images.githubusercontent.com/53466236/129080900-43631832-57ec-4f11-add6-bf0a660f5518.png)

**Comment by gnidan** [comment]
Should be something like this:

- `contracts/Digipix.sol`
- `migrations/1_initial_migration.js`
- ... etc.

(So now you'll need to move the `.sol` files out of `build/contracts/` and into `contracts/`, and you'll need to move the whole `migrations/` directory out of `contracts/`)

**Comment by gnidan** [comment]
For instance, see the resulting file structure of a blank `truffle init`:

```
./migrations/1_initial_migration.js
./contracts/Migrations.sol
./truffle-config.js
```

**Comment by BarryHewitt** [comment]
Hi, cheers for trying to help me, i really do appreciate it, i've changed it around to what you advised but wasn't sure if I needed the ./ as well as I've seen other projects being compiled and migrated without it i'm sure, in any case right now i'm still having the same problem 

![image](https://user-images.githubusercontent.com/53466236/129083282-dbe922f8-cbf0-473e-9dd4-04c6d2af2896.png)

**Comment by gnidan** [comment]
Maybe try creating a fresh Truffle project and moving your files into the correct directories? You seem to have made a mess of things: only `.sol` files should be in `contracts/` (no subdirectories), only `.js` files should be in `migrations/` (also no subdirectories)

**Comment by gnidan** [comment]
(The `.` was just to show you the project root)

**Comment by jilongcui** [comment]
If I set solc version up to 0.8.0, it will compile nothing.

**Comment by haltman-at** [comment]
@BarryHewitt We're going to close this for issue maintenance, but please let us know if there's still a problem and we can take another look.  Thanks!
