### ISSUE TITLE
@truffle/codec is missing dependency on abi-utils

### ISSUE THREAD

**Issue by frangio** [trufflesuite/truffle#4251]
Received error `Cannot find module '@truffle/abi-utils'` triggered in `@truffle/codec/dist/lib/contexts/utils.js`. Note this happens when installing the individual package, not when installing the main `truffle` package. (In my case it was indirectly through installing `@truffle/contract`.)

Here abi-utils it is defined as dev dependency:
https://github.com/trufflesuite/truffle/blob/98ce8573623c1d1deb8d5eb65060bda8b70c2fb8/packages/codec/package.json#L41-L42

**Comment by haltman-at** [comment]
Yikes, thanks for catching that!  I'll go put up a PR.
