### ISSUE TITLE
Default compilerRoots reference deprecated source for solc binaries

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4252]
`https://ethereum.github.io/solc-bin/` is now deprecated; `https://binaries.soliditylang.org` is now the preferred way to download solc binaries.

The default `compilerRoots` in the VersionRange strategy should be updated to reflect this.

(**And** we should probably update relay.trufflesuite.com)

_Originally posted by @haltman-at in https://github.com/trufflesuite/truffle/pull/4222#r687287842_

**Comment by haltman-at** [comment]
Note: See @cameel's comment [here](https://github.com/trufflesuite/truffle/pull/4222#discussion_r689001206) for more information about what URLs to use.

**Comment by cds-amal** [comment]
This issue needs to be rewritten to account for @cameel 's comments.

**Comment by fainashalts** [comment]
Closing in favor of #4425
