### ISSUE TITLE
truffle version error on window 10

### ISSUE THREAD

**Issue by Ambrose-Tech** [trufflesuite/truffle#4259]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment]
Could you provide more details about the issue you are experiencing?

**Comment by cds-amal** [comment]
Closing this for issue maintenance. Please let us know if you're still having issues.
