### ISSUE TITLE
@truffle/compile-solidity's CompilerSupplier does too much manual retry logic

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4261]
The VersionRange loading strategy is most notably guilty of this. It (and any other instances) should be updated to use [axios-retry](https://www.npmjs.com/package/axios-retry), already used by the Docker strategy.

_Originally posted by @haltman-at in https://github.com/trufflesuite/truffle/pull/4222#discussion_r687292057_

**Comment by gnidan** [comment]
@haltman-at can you please summarize? That PR is a bit hard to catch up on

**Comment by haltman-at** [comment]
Basically, the thing there is that when the compiler supplier retries, it's not retrying with the same URL but with a different one.  That likely makes something like `axios-retry` inappropriate, since the point of that is to perform appropriate backoff when retrying against the same server.

**Comment by eggplantzzz** [comment]
So basically the whole flow needs to be retried which entails getting the list of available versions for the source, finding the correct one (if available), and then fetching it.

**Comment by gnidan** [comment]
Is it no longer true that the CompilerSupplier does too much manual retry logic? It sounds like the amount of retry logic is still too much.

Ah but this issue is specifically about moving to axios-retry or some other automated retry mechanism... and I concur that that's probably not feasible, considering the necessary behavior. Bam, I love using the close-button dropdown!
