### ISSUE TITLE
Deployment issue on kotti (ETC testnet) network

### ISSUE THREAD

**Issue by racetrack0616** [trufflesuite/truffle#4267]
While deploying via Remix no issue occurred but in truffle series of issues ocurred like:
1. Time out issue
2. PollingBlockTracker
3. Socket time out

**Comment by aster2709** [comment]
I'm also having these issues, I'm trying to deploy to bsc testnet, for me it says ```there was a timeout while attempting to connect to the network```

**Comment by racetrack0616** [comment]
Did you ever try remix?  I am sure it will work. There are lots of solution proposed over the years in the internet for this issue but none of them is the accurate one. It depends upon the network you are using.

**Comment by eggplantzzz** [comment]
Those errors are usually due to connection problems. You can try to change the `timeoutBlocks` configuration, [here are the config docs](https://www.trufflesuite.com/docs/truffle/reference/configuration#networks). Try upping the setting to wait longer.

**Comment by racetrack0616** [comment]
Thanks. Even if I keep `      timeoutBlocks: 2000000,` It is still throwing an issue.
```
: PollingBlockTracker - encountered an error while attempting to update latest block:
```
This is in kotti network.

**Comment by racetrack0616** [comment]
This is so frustrating .

**Comment by eggplantzzz** [comment]
Sorry that you're having problems. What is kotti network? I don't know if I've heard of it. You might also have a problem with your gas configuration if your amounts are not high enough. You could also try upping the amount of gas provided for your transaction.

**Comment by racetrack0616** [comment]
Its a ETC testnet [https://blockscout.com/etc/kotti/](https://blockscout.com/etc/kotti/). I did every possible steps that I could.

**Comment by cds-amal** [comment]
@eggplantzzz suggests the team should discuss how to handle supported chains

**Comment by leeftk** [comment]
Hey @racetrack0616, are you still having issues with this? If so I would recommend using a different RPC endpoint. I found this one here https://www.ethercluster.com/ that is different from the official one so maybe trying using that and let me know if that helps. Thanks.

**Comment by gnidan** [comment]
Closing this for issue maintenance. Please let us know if the problem persists and we will help in any way we can!
