### ISSUE TITLE
MS10/Linux Bash /execSync and /execSync/install.js module not found. 

### ISSUE THREAD

**Issue by AlexXiong97** [trufflesuite/truffle#428]
I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
deep file dependency issue.

> execSync@1.0.2 install /root/.npm-global/lib/node_modules/truffle/node_modules/execSync
> node install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/truffle/node_modules/execSync/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
[               ...] / install: info lifecycle execSync@1.0.2~install: Failed 

## Steps to Reproduce

sudo npm install -g truffle 

## Environment
* Operating System: MS (Linux bash)
* node version: 7.0.0
* npm version: 4.2.0

**Comment by tcoulter** [comment]
Hi there. A new beta has been pushed out that should fix this issue. Details in the blog post [here](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). Can you give it a shot and report back?
