### ISSUE TITLE
Is there a way to test the entire folder or all test files for a given wildcard?

### ISSUE THREAD

**Issue by 2608027102** [trufflesuite/truffle#4290]
- [√ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Is there a way to test the entire folder or all test files for a given wildcard?

## Steps to Reproduce

truffle test ./test/

truffle test ./test/flow*.js

## Expected Behavior
test the entire folder or all test files for a given wildcard.

## Actual Results
No test files were executed

## Environment

* Operating System: 
   Windows 10 x64
* Ethereum client:
* Truffle version (`truffle version`):
   v5.4.7
* node version (`node --version`):
  v14.17.3
* npm version (`npm --version`): 
  6.14.13

**Comment by eggplantzzz** [comment]
Truffle by default runs all the tests in your test folder. You can also pass it a path to a test file to run only a select few. Truffle also allows you to pass mocha's -g option that will grep test files. However, the wildcard character is not supported. Thanks for the suggestion!
