### ISSUE TITLE
truffle not recognize as external or internal command

### ISSUE THREAD

**Issue by vnxz** [trufflesuite/truffle#4291]
![Screenshot_1](https://user-images.githubusercontent.com/76085185/131353077-a96a6fea-a08e-45f4-ab7a-83dc85699459.png)

How can solve this 
I installed truffle to D folder and set at system enviornment path
But truffle not recognize as command

**Comment by MicaiahReid** [comment]
Hi @vnxz, are you using a node version manager to install nodejs as a prerequisite to truffle? We notice you're using Windows, you could try [this](https://github.com/coreybutler/nvm-windows) node version manager.

**Comment by haltman-at** [comment]
Closing this for issue maintenance.
