### ISSUE TITLE
Truffle Debug stops with the output "stepping"

### ISSUE THREAD

**Issue by tina1998612** [trufflesuite/truffle#4297]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I ran truffle debug and it halts with the output "stepping".

## Steps to Reproduce

I have a contract with this piece of code: 
```(bool success,) = msg.sender.call(
            abi.encodeWithSignature(
                "receiveFlashLoan(uint256)",
                amount
            )
        );
```
The tx failed near here. When I run truffle debug, it halts until this line. It works fine when debugging other txid. Only this specific txid has issues.

## Expected Behavior

It should let me continue entering `n` to keep inspecting.

## Actual Results
<img width="668" alt="Screen Shot 2021-09-03 at 1 56 30 AM" src="https://user-images.githubusercontent.com/19768276/131893468-2d9b78b4-8e63-47a4-b4bd-9157734bd317.png">

<img width="248" alt="Screen Shot 2021-09-03 at 1 56 06 AM" src="https://user-images.githubusercontent.com/19768276/131893420-c13f7417-9eb5-4b01-818d-11047caf5c94.png">

## Environment

* Operating System: Mac OS
* Ethereum client: Infura
* Truffle version (`truffle version`): 5.4.8
* node version (`node --version`): 16.7.0
* npm version (`npm --version`): 7.20.3

**Comment by gnidan** [comment]
Ooh, a bug! Thanks for reporting this. We'll look into it and hopefully have a fix quickly.

**Comment by tina1998612** [comment]
Update: The problem was solve after changing to Solidity version 0.8.7 😂

**Comment by gnidan** [comment]
But we gotta fix the bug! What version were you using? 😄 (glad you have a fix!)

**Comment by tina1998612** [comment]
I was using 0.8.0

**Comment by haltman-at** [comment]
Do you have a reproduction example we could check out?  It'll be hard to get to the bottom of this otherwise.  Thanks!

**Comment by haltman-at** [comment]
OK, we're going to just have to close this for issue maintence, I'm afraid. :-/ @tina1998612, please let us know if you have more information and we can reopen this!  I would very much like to get to the bottom of this, but I think we're just going to have to close it for now if there's no more information to work off of. :-/
