### ISSUE TITLE
Terminal Error no permission need assitance

### ISSUE THREAD

**Issue by cpakilla87** [trufflesuite/truffle#4298]
Newbie here stuck, was trying to get things rolling on terminal but keep getting this error below on my mac.
this is what I tried to set up  npm install -g truffle@5.0.5

 % npm install -g truffle@5.0.5 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/truffle
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/truffle'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:

**Comment by leeftk** [comment]
Hey @cpakilla87 thanks for reaching out! It looks like what you're experience is actually a permissions issue when trying to install node packages. The issue that is causing this is related to the fact that the folder NPM is trying to access/write to is not owned by the user that is executing the command. Take a look at the stackoverflow post that I linked below. I'm assuming you're attempting to install this on a Mac correct? If so the second response should help fix the issue. Let me know how that goes. Thanks!

https://stackoverflow.com/questions/51967335/npm-install-permission-denied-macos

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance, but please let us know if there's still a problem here.  Thanks!
