### ISSUE TITLE
Truffle migrate issue

### ISSUE THREAD

**Issue by bhavik-vala** [trufflesuite/truffle#4307]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

can not migrate and deploy contract using "truffle migrate"

## Steps to Reproduce
ran "truffle migrate" on the terminal after "truffle development" to deploy my contract but  getting an error

## Expected Behavior

The contract should be deployed

## Actual Results

truffle(develop)> truffle migrate
evalmachine.<anonymous>:0
truffle migrate
        ^^^^^^^

Uncaught SyntaxError: Unexpected identifier

## Environment

* Operating System: Windows 10
* Ethereum client: truffle development
* Truffle version (`truffle version`): v5.0.5
* node version (`node --version`): v7
* npm version (`npm --version`): 6.14.5

**Comment by bhavik-vala** [comment]
Hi there, I tried updating the node to v12.18.2  but unfortunately, i still get the same error.

**Comment by fainashalts** [comment]
Hi @bhavik-vala! A couple of things to try here. Are you using the command `truffle develop` followed by the command `truffle migrate`? I just wanted to confirm that we are talking about the same things. 

I have some suggestions to get to the bottom of this.  
-- do you get an error when running `truffle migrate` outside of the `develop` console? If not, please let me know as that may mean something is going on from the Truffle side. 
-- do you still get this error on the latest version of Truffle?
-- can you share your repo for us to test? 

Thanks for bringing this up!

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance, but please feel free to get back to us with more information and we can see about reopening this.  Thanks!
