### ISSUE TITLE
DB saving only works globally

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#4313]
## Issue

Developers should be able to save DB data in a directory of their choosing, and not have to default to the global `config/.db` if they don't want to. This used to work but seems to have broken. 

## Steps to Reproduce

1. `truffle init`
2. Uncomment the db enabling code and be sure to set db.enabled to true
3. `truffle compile` && `truffle migrate`
4. `truffle db serve` and search for all projects

## Expected Behavior

The project you have just migrated should appear in the search results.

What you expected to happen.

## Actual Results

The project does not appear. When the path for the db directory is removed and the steps above are otherwise followed, the project does appear.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by kevinweaver** [comment]
I followed the steps with @fainashalts and we cannot reproduce this anymore.

**Comment by kevinweaver** [comment]
I also stepped through this on @cds-amal 's machine and we were unable to reproduce.
