### ISSUE TITLE
Issue with truffle installation 

### ISSUE THREAD

**Issue by Shreekavithaa** [trufflesuite/truffle#432]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

npm install -g truffle never terminates and gave few warnings. I dont know how to solve them. Kindly look into it and help! thanks

## Steps to Reproduce

rum npm install -g truffle 

## Expected Behavior

Its expected to install truffle and I should be able to run truffle init and build contacts 

## Actual Results

![image](https://cloud.githubusercontent.com/assets/8644765/26821992/6143bcfe-4a5d-11e7-838b-f5c9065aeceb.png)

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: Not installed
* Ethereum client: Geth v1.6.5-stable
* node version: v5.12.0
* npm version: 3.8.6

**Comment by daveremy** [comment]
Having similar issue with Windows Linux Subsystem Bash same versions of other software.  However installation is terminated with:

npm ERR! code EINTEGRITY
npm ERR! sha1-Sl8bhoOpRBSi+67Ocr8at10LmsU= integrity checksum failed when using sha1: wanted sha1-Sl8bhoOpRBSi+67Ocr8at10LmsU= but got sha1-OfUkmzmU59tgRy5A/fxazxMcQV8=. (2506224 bytes)

**Comment by tcoulter** [comment]
This issue should be fixed in the latest version of Truffle. Please give the new version (`v3.4.4`) a try. If you run into more issues, please open then as a new ticket so we can address them individually. Thanks!
