### ISSUE TITLE
Truffle 5.4.11 gas exceeded the block limit on Optimism Kovan

### ISSUE THREAD

**Issue by matYang** [trufflesuite/truffle#4320]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When trying to deploy a new contract to Optimism Kovan with Truffle 5.4.11, I am consistently getting

```
Error:  *** Deployment Failed ***

"SimpleStorage" exceeded the block limit ...
```

If I do not set a gas limit manually, I get
```
"SimpleStorage" exceeded the block limit (using Truffle's estimate).
   * Block limit: 11000000 (0xa7d8c0)
   * Report this error in the Truffle issues on Github. It should not happen.
   * Try: setting gas manually in 'truffle-config.js' or as parameter to 'deployer.deploy'
```

If I set a gas limit manually, for example 4999999, I get
```
"SimpleStorage" exceeded the block limit (with a gas value you set).
   * Block limit:  11000000 (0xa7d8c0)
   * Gas sent:     4999999 (0x4c4b3f)
   * Try:
      + Sending less gas.
      + Setting a higher network block limit if you are on a
        private network or test client (like ganache).
```

## Steps to Reproduce

1. Go to https://github.com/truffle-box/optimism-box
2. Do truffle unbox optimism
3. Set `KOVAN_MNEMONIC` and `INFURA_KEY`
4. Run `truffle migrate --config truffle-config.ovm.js --network optimistic_kovan`
5. Observe contract is deployed successfully
6. Edit ./contracts/optimism/SimpleStorage.sol, change a few lines, e.g. change `storedData = x`; to `storedData = x + 1;`
7. Run `truffle migrate --config truffle-config.ovm.js --network optimistic_kovan` again
8. Observe failure as specified above

## Expected Behavior

Contract gets deployed successfully when Truffle is estimating gas, or at the very least, contract is deployed successfully with a gas limit set manually.

## Actual Results

Very confusing error message, how does 4999999 exceed block gas limit of 11000000

## Environment

* Operating System: Mac OS Big Sur
* Ethereum client: OVM ^0.7.6, also tried 0.6.12 same issue
* Truffle version (`truffle version`): 5.4.11
* node version (`node --version`): v14.17.3
* npm version (`npm --version`): 6.14.13

**Comment by matYang** [comment]
This may be related to https://github.com/ethereum-optimism/optimism/issues/1415

I was hoping Truffle 5.4.11 should have fixed the issue, because calling eth_estimateGas should just make gas limit work for Optimism, I've been using Remix & Metamask to deploy to Optimism Kovan without any issues, while Truffle fails

**Comment by fainashalts** [comment]
Hi @matYang there is one additional issue on the Optimism side regarding how they calculate the Optimistic Ethereum blockLimit. To bypass from the Truffle side, add `YourContract.gasMultiplier = 0.9` to your migration files. Optimism is coming out with changes in October that will hopefully fix this completely and remove the need for the `gasMultiplier` line.

Please let me know if that helps!

**Comment by matYang** [comment]
So I tried 

`SimpleStorage.gasMultiplier = 0.9;`

Not sure why but it is still giving me the same exceed block gas limit error

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance; @matYang, please let us know if there's still a problem here and we'll see what we can do.  Thanks!
