### ISSUE TITLE
[v2] HDWalletProvider; Execution Reverted when trying to 'setRecord' to claim ENS domain.

### ISSUE THREAD

**Issue by gsiros** [trufflesuite/truffle#4322]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this 

---------------------------
**IMPORTANT**; this is the same issue as [this](https://github.com/trufflesuite/truffle/issues/4308). The original issue was closed due to the `ttl` parameter in the `web3.eth.ens.setRecord` function being `0`. I've tried changing the parameter to any other positive integer, **but the result is the same**.

## Issue

Using Truffle's HDWalletProvider causes an error when trying to claim an ENS domain via the web3.js `web3.eth.ens.setRecord` function. The execution gets reverted.

## Steps to Reproduce

The process is very straight forward;
1. Create a provider instance for web3. (12word mnemonic + infura's rinkeby link)
2. Call the `web3.eth.ens.setRecord` function as;
`result = await web3.eth.ens.setRecord('blablabla.eth', accounts[0], "0xf6305c19e814d2a75429Fd637d01F7ee0E77d615",             
 10000000, { from: accounts[0] });`

## Expected Behavior

The expected outcome is some message of affirmation, that the domain has been claimed.

## Actual Results

The execution of the transaction gets reverted. The NodeJS terminal output is `{ code: -32000, message: 'execution reverted' }`

## Environment

* Operating System: macOS (10.15.7)
* Ethereum client: -
* Truffle's HDWalletProvider version `1.5.0`
* node version `14.17.3`
* npm version `6.14.13`

**Comment by gsiros** [comment]
@fainashalts Yes, i have used the  Web3's HttpProvider with Infura's endpoint. It does not work. An error message pops up sayig `eth_SendTransaction does not exist`. Any thoughts? Thanks!

**Comment by haltman-at** [comment]
So, `eth_sendTransaction` doesn't exist because that's used for sending unsigned transactions without a private key.  If you want to use web3 alone to test this, you'll want to use its [`web3.eth.accounts.wallet`](https://web3js.readthedocs.io/en/v1.5.2/web3-eth-accounts.html#wallet) feature.  Once you've created an account to the wallet, web3 will automatically sign for you any transactions sent from it.  Then you can test this out.

**Comment by gsiros** [comment]
@haltman-at thanks for the info. How do I import MetaMask's existing accounts to web3.eth.accounts.wallet?

**Comment by haltman-at** [comment]
I don't know much of anything about MetaMask, but assuming you have their private key, you can use [`web3.eth.accounts.wallet.add`](https://web3js.readthedocs.io/en/v1.5.2/web3-eth-accounts.html#wallet-add).

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance.  Let us know if there's still a problem here and we can perhaps reopen this.  Thanks!
