### ISSUE TITLE
Can't compile the contracts in the sample Quickstart guide for Truffle Tezos

### ISSUE THREAD

**Issue by gabrielxz** [trufflesuite/truffle#4325]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Can't compile the contracts in the sample Quickstart guide for Truffle Tezos

## Steps to Reproduce

Was following along your quickstart guide: https://www.trufflesuite.com/docs/tezos/truffle/quickstart
Got everything installed, created the unboxed the tezos-example project, tried to compile.

## Expected Behavior

To compile the sample contracts or at least provide an error message. All I see is "Compilation of ... failed. See above", but there's no error message other than a warning that "The old cli is deprecated"

## Actual Results

```
Compiling your contracts...
===========================
> Compiling ./contracts/Counter.ligo
> Compiling ./contracts/Migrations.ligo
> Compiling ./contracts/SimpleStorage.ligo
> Using entry point "main"
Warning: The old cli is deprecated, use `ligo --help` or `ligo man` to consult the new command syntax

Compilation of /home/gabriel/repos/tezos-example2/contracts/Counter.ligo failed. See above.
```

## Environment

* Operating System: 
Ubuntu
Truffle v5.5.0-tezos.4 (core: 5.5.0-tezos.4)
Node v12.21.0
npm 7.5.2

Thanks for the help!

**Comment by gabrielxz** [comment]
I didn't see the support ticket option. I'll post one of those.

**Comment by kimberlyadams** [comment]
Hey was this issue fixed? If so, whats the solution?

**Comment by gabrielxz** [comment]
I contacted support and they weren't able to solve it, so I posted another issue: https://github.com/trufflesuite/truffle/issues/4326

So far no traction on the new issue. Is this issue happening to you? I've tried it on 4 different systems now and get the same error each time.
