### ISSUE TITLE
No stack trace failure while running Truffle Compile on Tezos-Truffle. 

### ISSUE THREAD

**Issue by gabrielxz** [trufflesuite/truffle#4326]
- [X ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I tried following the Truffle Tezos Quickstart Guide on both a Windows machine and a Linux machine, and I get the same compilation error with no additional information. I filed a support request and they eventually said to file an issue here.

## Steps to Reproduce
I followed the guide here: https://www.trufflesuite.com/docs/tezos/truffle/quickstart
I made sure NodeJS and Docker were installed. I installed the Tezos version of Truffle. I unboxed the tezos-example project. Then I ran "truffle compile". On both systems (Linux/Windows) I get an identical error message.

## Actual Results

```
Compiling your contracts... 
=========================== 
> Compiling ./contracts/Counter.ligo 
> Compiling ./contracts/Migrations.ligo 
> Compiling ./contracts/SimpleStorage.ligo 
> Using entry point "main" 
Warning: The old cli is deprecated, use `ligo --help` or `ligo man` to consult the new command syntax 

Compilation of /home/gabriel/repos/tezos-example/contracts/Counter.ligo failed. See above. 
Truffle v5.5.0-tezos.4 (core: 5.5.0-tezos.4) 
Node v14.17.6 
```

I don't see any error message other than the warning about the "old cli...". When I do "ligo --help" or "ligo man" it's not recognized in either system. What is supposed to install the ligo cli?

## Environment

* Operating System:  Windows 10 and Linux (Ubuntu)
Truffle v5.5.0-tezos.4 (core: 5.5.0-tezos.4) 
Node v14.17.6 
npm v7.24.1
![Screenshot 2021-09-24 170912](https://user-images.githubusercontent.com/4461804/134740004-8b99da8f-f862-4f52-bffc-d5a36db9a0f8.png)

![Screenshot 2021-09-24 171722](https://user-images.githubusercontent.com/4461804/134740707-47fc3ea8-a735-4079-8f7f-3a7dd54f7c01.png)

**Comment by erivas** [comment]
This is an issue of incompatibility with the new CLI of the LIGO compiler.

In the `execLigo` function, the call to LIGO should become something like:
```
        var docker = child_process_1.spawn("docker", [
            "run",
            "-v",
            currentWorkingDirectory + ":/project",
            "--rm",
            "-i",
            "ligolang/ligo:next",
            "compile",
            "contract",
            fullInternalSourcePath,
            "--michelson-format",
            "json",
            "-e",
            entryPoint
        ]);
```

(althought it'd be good if warning messages in `stderr` would not be considered fatal errors anymore)

> I don't see any error message other than the warning about the "old cli...". When I do "ligo --help" or "ligo man" it's not recognized in either system. What is supposed to install the ligo cli?

If you want to run LIGO directly, you can run it via `docker`:
```
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:next man
```
(for Linux; similar for Windows, see here: https://ligolang.org/docs/intro/installation/#dockerised-installation-recommended)

**Comment by fainashalts** [comment]
Update: there has been some movement on this. We may have a path forward for updating the `truffle@tezos` experimental implementation. Stay tuned!

**Comment by Reudlak** [comment]
I just see this and this gives me hope although thats from december. Waiting patiently

**Comment by haltman-at** [comment]
Unfortunately, our team's current priorities no longer provide a path towards near-term Tezos support.  I'm afraid that we're going to close this, sorry for the inconvenience.

**Comment by BearCooder** [comment]
Hello @haltman-at & @fainashalts can you please make a statement as to why Tezos support is not a priority anymore? To be honest it leaves a bad taste after the big announcement od Tezos support in Truffle ([Twitter](https://twitter.com/trufflesuite/status/1250486441341304835) and [Blogpost](https://trufflesuite.com/blog/branching-out-announcing-tezos-support-in-truffle/)) over two years ago. The funny thing is the support didnt last long, less than a year later Truffle started to ghost all issues and update requests on github or stated to do it later.. why the sudden change back then?

At least make either make it official and announce that you are not supporting Tezos anymore or at least update Tezos Truffle to current protocol standard. I dont know maybe its a failure on the communication side, maybe Truffle @tcoulter and Tezos Foundation @drchrispinnock need to talk but the current state is unfortunate.
