### ISSUE TITLE
Truffle Contract - `ethereum.send(...)` is deprecated

### ISSUE THREAD

**Issue by ioapps-dev** [trufflesuite/truffle#4329]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

The new version of MetaMask produces the following warning message:

MetaMask: **'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.**
For more information, see: https://eips.ethereum.org/EIPS/eip-1193
send	@	inpage.js:1
**(anonymous)	@	truffle-contract.min-v4.3.36.js:1**
ZoneAwarePromise	@	zone-evergreen.js:1387
**get	@	truffle-contract.min-v4.3.36.js:1
start	@	truffle-contract.min-v4.3.36.js:1**
invoke	@	zone-evergreen.js:372
run	@	zone-evergreen.js:134
(anonymous)	@	zone-evergreen.js:1276
invokeTask	@	zone-evergreen.js:406
runTask	@	zone-evergreen.js:178
drainMicroTaskQueue	@	zone-evergreen.js:582
Promise.then (async)

## Steps to Reproduce

The warning appears when the user denies the operation using the MetaMask Reject button.

## Environment

* TruffleContract version: 4.3.36
* Web3 version: 1.5.3

**Comment by dongmingh** [comment]
Thanks for raising this.  We will look into this.

**Comment by eggplantzzz** [comment]
Hey @ioapps-dev, can you provide detailed steps on how to reproduce this?

**Comment by kevinweaver** [comment]
Hi @iosapps-dev, I'm going to close this for issue maintenance. Please re-open if you're able to provide some reproduction steps, thanks!

**Comment by wbt** [comment]
I've been getting the same issue a lot as well, and had just assumed it was being worked on.  It seems to happen more reliably when calling a function on a Truffle contract and then clicking Reject in MetaMask to prevent the transaction from going through.  


I can't always get a trace in DevTools, but was just able to capture one, and lined up hyperlinks to code (changing to the actually referenced lines in Reason as I wasn't running the latest): 

- send	@	inpage.js:1 (note: this is MetaMask code) 
- (anonymous)	@	[reason.js:105](https://github.com/trufflesuite/truffle/blob/0950040b2f51da552b910599402782d33e6abea2/packages/contract/lib/reason.js#L118)
- get	@	[reason.js:104](https://github.com/trufflesuite/truffle/blob/0950040b2f51da552b910599402782d33e6abea2/packages/contract/lib/reason.js#L117)
- start	@	[override.js:61](https://github.com/trufflesuite/truffle/blob/0950040b2f51da552b910599402782d33e6abea2/packages/contract/lib/override.js#L61)
- Promise.catch (async)		
- (anonymous)	@	[execute.js:242](https://github.com/trufflesuite/truffle/blob/0950040b2f51da552b910599402782d33e6abea2/packages/contract/lib/execute.js#L242)
- Promise.then (async)		
- (anonymous)	@	[execute.js:206](https://github.com/trufflesuite/truffle/blob/0950040b2f51da552b910599402782d33e6abea2/packages/contract/lib/execute.js#L206)

Points deeper in the stack are in application code, starting with the call to the contract's method.
