### ISSUE TITLE
truffle framework  combine with nodejs express framework

### ISSUE THREAD

**Issue by Katsu1991** [trufflesuite/truffle#433]
hi，all：
How truffle framework  combine with nodejs express framework ，then provide service like express framewok。For example，I want invoke smart contract as follow：
"
var express = require('express');
var app = express();
 
app.get('/a', function (req, res) {
// invoke a smart contract
   res.send(result);
})

app.get('/b', function (req, res) {
// invoke b smart contract
   res.send(result);
})

var server = app.listen(8081, function () {
 
  var host = server.address().address
  var port = server.address().port
 
  console.log("http://%s:%s", host, port)
 
})
"
The truffle framework I using  was downloaded from github。

**Comment by tcoulter** [comment]
Hi there. This would be the perfect use for a Truffle Box. See here: http://truffleframework.com/boxes/

We currently don't have a Truffle Box for Express, but please feel free to create one and submit your code to us -- we'll be happy to list it. CC @DiscRiskandBisque

**Comment by makoto** [comment]
I guess the question is more about how to co-exist pages rendered by express and ones served by truffle (with `npm run dev`)
