### ISSUE TITLE
js invoke contract

### ISSUE THREAD

**Issue by Katsu1991** [trufflesuite/truffle#434]
'use strict';
//var metaCoin = require(MetaCoin);
var express = require('./node_modules/express');
var apps = express();
var contract = require('truffle-contract');
var metaCoinJson= require('./build/contracts/MetaCoin.json');
var metaCoin = contract(metaCoinJson);

apps.get('/', function (req, res) {
  
//var account='0x994328ed6e15983f129a27d03b7efeb336bed343';
   var meta;
   var balance = "1";
   var account = '0x2428992c55f81596d964840e06db73ea6d6dcda6';
   metaCoin.deployed().then(function(instance) {
    console.log("flag");
      meta = instance;
      return meta.getBalance.call(account, {from: account});
    }).then(function(value) {
      
      balance = value.valueOf();

    });
  console.log(balance);
   res.send(balance);
})
 
 
 
var server = apps.listen(8089, function () {
 
  var host = server.address().address
  var port = server.address().port
 
  console.log(" http://%s:%s", host, port)
 
})

Use js file to invoke smart contract(truffle framework),
but I can't get the right balance value,  thanks for your idea。

**Comment by tcoulter** [comment]
Hi there. There are a ton of potential reasons why you may not be getting the balance you expect. Unfortunately, a github ticket isn't the right place to help.

Instead, you should check out our [gitter channel](http://gitter.im/Consensys/truffle) where you can chat with us and other community members who might be able to solve your problem. 

Good luck, and please find us on Gitter!
