### ISSUE TITLE
truffle migrate gives cryptic error message when node has no accounts

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle#435]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

- Run new geth instance with no accounts on it
- Run truffle migrate on some truffle project
You get: 

## Expected Behavior
An error message saying "your node has no accounts", or something better

## Actual Results
```
Error: Expected parameter 'from' not passed to function.
```

## Environment

* Operating System: Ubuntu
* Truffle version: 3.2.5
* Ethereum client: geth
* node version: 8.0.0
* npm version: 5.0.2

**Comment by kevin-smets** [comment]
Hmmm, mine has accounts on it (testrpc) and I also get this issue. Very cryptic indeed. Did adding accounts actually solve it for you?

**Comment by kevin-smets** [comment]
Seems to be some weird issue in node or something... https://gitter.im/ConsenSys/truffle?at=58d3fbe3caf143ab665362ee

A restart fixed it for me.

**Comment by alexpee** [comment]
I hit the similar error and fixed it after reinstalling the testRPC.

**Comment by sachabest** [comment]
Having the same problem with active accounts on top of a geth node with rpc turned on .Any idea how else to fix? I read the gitter conversation but restarting has not helped. Tried both node 6 and 7 (via docker image), same result.

**Comment by dellintosh** [comment]
I ran into this same issue when running the testrpc.  It turned out that I had geth running in another tab (connected to the testnet)... as soon as I stopped geth it was able to migrate without any issue!  Hope this saves others - turns out you can't have `geth` _and_ `testrpc` running at once (makes sense, really, since both bind to port 8545 and truffle probably doesn't know where you want to `migrate` to).

**Comment by infwonder** [comment]
Hi all, 

I also encountered the issue when running truffle migrate. I solved it my introducing a 'solc' entry in truffle.js:

`'solc': '/usr/local/bin/solc',`

HTH

**Comment by MacroChip** [comment]
I had the original issue that @maraoz had. It is fixed by opening a geth console and calling personal.newAccount()

**Comment by propercoil** [comment]
This error is due to testrpc being used by a third party instance such as `geth` or `parity` and when no accounts are present.

**Comment by eriklacson** [comment]
I'm getting this error on Ubuntu 16 running geth with an account created in Ethereum Wallet. Account has been unlocked on geth attach and I can even check the balance. Putting 'from: <account>' yields a 'Error: unknown account'
