### ISSUE TITLE
Debugger: Request for displaying Opcodes as a group

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#4353]
Currently the debugger shows the current opcode when stepping with `;`.  I would like to see the opcodes grouped for more insights. I'm not sure how this could be displayed, perhaps `p +instructions` ?

**Comment by haltman-at** [comment]
I don't know about `p instructions` (`p ins`?).  If we really want it to be a special thing it could be `p cod` or something.  But I think I'd just change the default opcode printout to show a display of, say, 3 behind and 3 ahead, in addition to the current one, much like our default view of the source code doesn't just show the particular line we're on.

If that's not enough we could maybe add something for seeing the full disassembly, but I'd start by just expanding what we show by default.

**Comment by gnidan** [comment]
This is done and now released in [Truffle v5.4.20](https://github.com/trufflesuite/truffle/releases/tag/v5.4.20). Thanks!
