### ISSUE TITLE
Unable to resolve module fs from /{projctfolder}/truffle-hdwallet-provider/dist/index.js: fs could not be found within the project.

### ISSUE THREAD

**Issue by AlexanderCui001228** [trufflesuite/truffle#4355]
## Issue
React native, android app, JavaScript bundling fails,
Unable to resolve fs from truffle-hdwallet-provider/dist/index.js

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

require('truffle-hdwallet-provider') in react-native project

## Expected Behavior

bundle success

## Actual Results

Unable to resolve module fs from /{projctfolder}/truffle-hdwallet-provider/dist/index.js: fs could

## Environment

* Operating System: macOS 11.5.2
* Ethereum client: ganache 6.12.2
* Truffle version (`truffle version`): 1.0.17
* node version (`node --version`): 16.10.0
* npm version (`npm --version`): 6.14.12

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if this is still a problem and we can reopen it.  Thanks!

**Comment by AlexanderCui001228** [comment]
Sorry for replying this late. The problem disappeared after I changed my project's architecture. The problem was more specific to bundling in React Native. Again, apologies for not responding on time.
