### ISSUE TITLE
Syntax errors on certain language features in solidity tests but not in solidity contracts

### ISSUE THREAD

**Issue by kieranelby** [trufflesuite/truffle#436]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

An item of valid solidity syntax (an omitted component in a destructuring assignment - see example foo function below) isn't recognised in solidity tests (even though it's compiled fine when it's in the contracts directory).

## Steps to Reproduce

1. run truffle init in empty directory to create starting project
2. edit the example solidity test contract in test/TestMetacoin.sol to add the following function that uses a destructing assignment with an omitted component (see e.g. http://solidity.readthedocs.io/en/latest/control-structures.html#destructuring-assignments-and-returning-multiple-values ):

```
	function foo(uint x, uint y, uint z) returns (uint) {
		var (,q,) = (x, y, z);
		return q;
	}
```

3. run truffle test
 
## Expected Behavior

I expected the tests to compile and run, since the function is valid solidity.

It's interesting that if I add the same foo function not to the tests, but to the code being tested (e.g. to contracts/Metacoin.sol), that it works fine - truffle can compile it. I think perhaps there's some other javascript (not solc) that parses the test contracts that doesn't like this - I notice it mentions PEG in the output?

## Actual Results

truffle test throws an error along the lines of:

```
SyntaxError: Expected identifier but "," found. Line: 26, Column: 8
    at peg$buildStructuredError (PATH_REDACTED\npm\node_modules\truffle\build\cli.bundled.js:184440:12)
    at Object.peg$parse [as parse] (PATH_REDACTED\npm\node_modules\truffle\build\cli.bundled.js:197026:11)
    at Object.parse (PATH_REDACTED\npm\node_modules\truffle\build\cli.bundled.js:76082:23)
    at PATH_REDACTED\npm\node_modules\truffle\build\cli.bundled.js:218574:32
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

## Environment

* Operating System: Windows 10 under git bash shell / MINGW64
* Truffle version: v3.2.7
* Ethereum client: TestRPC
* node version: v6.10.3
* npm version:  3.10.10

**Comment by cgewecke** [comment]
@kieranelby Have opened an issue in `solidity-parser` to get this fixed.

**Comment by cgewecke** [comment]
This should be resolved at [solidity-parser](https://github.com/ConsenSys/solidity-parser) now . . . just needs publication there / dependency updating here.

**Comment by cgewecke** [comment]
Closing this - possibly resolved at solidity-parser - but we're removing the last vestiges of SP anyway.
