### ISSUE TITLE
CLI debugger should allow customizing variables view

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4360]
Similar to how `p` allows `p <loc>`, `p +<loc>`, etc., `v` could allow the same, since possibly users might not want always to see the Solidity built-ins, or maybe someone wants to see specifically `v contract` or `v local` at a particular point.

(See [`p` docs](https://www.trufflesuite.com/docs/truffle/getting-started/debugging-your-contracts#-p-print-instruction))

**Comment by haltman-at** [comment]
> Similar to how `p` allows `p <loc>`, `p +<loc>`, etc., `v` could allow the same, since possibly users might not want always to see the Solidity built-ins, or maybe someone wants to see specifically `v contract` or `v local` at a particular point.
> 
> (See [`p` docs](https://www.trufflesuite.com/docs/truffle/getting-started/debugging-your-contracts#-p-print-instruction))

Opinion: This should probably mimic the `p` interface for consistency and simplicity.  I think that includes allowing things to be abbreviated to three characters -- so, `bui` (builtins), `loc` (locals), `con` (contract)?

**Comment by haltman-at** [comment]
> Leaving this out of the original comment, but I had the thought that `v` (and `p` for that matter) could be expanded to provide additional output along the lines of:
> 
> > Did you know you can do `p -mem` to remove memory from this display?
> > Read docs about this feature at https://...
> 
> But I suppose that's out of scope. Maybe worth a new issue about a hint system? I feel like that might provide value.

Definitely out of scope... but also, @gnidan you realize memory is *off* by default? :P

**Comment by haltman-at** [comment]
Oh hey looks like this was never closed.  Closing this!
