### ISSUE TITLE
There should be `DecodingInspector` analogous to `ResultInspector` (and test and db-kit should use it)

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4368]
## Issue

Currently we display decodings from Truffle Decoder / Codec in various ad-hoc ways in Truffle Test (events), db-kit (events and calldata), and the debugger (returndata).  There should be a `DecodingInspector` class that does for these what `ResultInspector` does for individual variables, and these should (at least mostly) be replaced by that.  Alternatively, the `ResultInpsector` class itself could be expanded to cover this case, but that seems more awkward.

(Also, I'm not *entirely* confident that the debugger's handling of return values makes sense to be unified with this; maybe it should, maybe it shouldn't, we'll have to see.)

## Environment

* Truffle version (`truffle version`): 5.4.15

**Comment by lsqproduction** [comment]
Addressed in v5.5.2.
