### ISSUE TITLE
truffle installation

### ISSUE THREAD

**Issue by acodercat** [trufflesuite/truffle#437]
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)

npm version: 5.0.3
node version: 8.0.0
system:windows 10

**Comment by tcoulter** [comment]
This should be fixed by version 3.4.3. Please upgrade your version of Truffle and open a new ticket if you run into any more issues.
