### ISSUE TITLE
Please help -  Fetching solc version list from solc-bin. 

### ISSUE THREAD

**Issue by Jabbasmith** [trufflesuite/truffle#4370]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

1.) npx truffle console
2.) migrate

See attached file for complete output.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

> Artifacts written to C:\Users\jimle\nft-demo\build\contracts
> Compiled successfully using:
   - solc: 0.8.9+commit.e5eed63a.Emscripten.clang

Unknown network "ganache". See your Truffle configuration file for available networks.
- Fetching solc version list from solc-bin. Attempt #1
- Fetching solc version list from solc-bin. Attempt #1

## Environment

* Operating System: Windows 10
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`): 
* 
Truffle v5.4.15 (core: 5.4.15)
Solidity - ^0.8.9 (solc-js)
Node v14.18.0
Web3.js v1.5.3
npm version of 6.14.1
[Errlog.txt](https://github.com/trufflesuite/truffle/files/7357997/Errlog.txt)
5

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but feel free to get back to us with more info and we can reopen this.  Thanks!

**Comment by FacundoBettella** [comment]
Hi! Iam having the same problem.
