### ISSUE TITLE
`truffle config ...` does not report anything after it is run

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#4379]
After you run `truffle config <something>`, it returns you to the prompt without any printout. This is very confusing and leaves the user not knowing whether running the command was successful or if it failed.

Try running `truffle config set analytics true` and you can see the process just ends without any confirmation.

**Comment by cds-amal** [comment]
It would be nice to add a `truffle config list` command to see current settings similar to npm's behavior.

**Comment by gnidan** [comment]
This is done and now released in [Truffle v5.4.20](https://github.com/trufflesuite/truffle/releases/tag/v5.4.20). Thanks!
