### ISSUE TITLE
Resolver.resolve should have access to compiler/version information for current compilation

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4384]
## Background

Basics:
- [abi-to-sol](https://www.npmjs.com/package/abi-to-sol) is a package that takes ABI JSON as input and produces Solidity code that compiles to that ABI JSON. It allows you to specify a Solidity version range, and will produce output that is compatible with that specified range.
- Truffle provides "experimental" support for making this super easy: you can have `.abi.json` files in your `contracts/` directory, import them in Solidity like `import "./Uniswap.abi.json";`, and it will be as-if you imported `interface Uniswap` with all the functions, etc., defined by that ABI.

Now, my [recent attempt to upgrade abi-to-sol](https://github.com/trufflesuite/truffle/pull/4365) fails CI because later versions of this dependency produce output that is compatible with only a narrow range of Solidity versions (default `>=0.7.0 <0.9.0`). Previously, this wasn't a problem our current version of that dependency does not change its output syntax at all, and the pragma it produced was overly broad.

abi-to-sol has gotten a lot more robust, in that it now produces valid Solidity output much, much more reliably, and so we could probably make this Truffle feature not-so-experimental, if only we could upgrade.

For the Truffle feature, we invoke abi-to-sol during `resolver.resolve()`, which in turn happens via the profiler. If the user imports a `.abi.json` file in their Solidity code, `resolver.resolve()` will recognize the file extension, read the corresponding ABI JSON from disk, and then call abi-to-sol to produce a Solidity source instead of this raw JSON

Ideally, when the user does this, the produced Solidity source should match whatever pragma it was imported by, and abi-to-sol output should be compatible with this pragma. So if you're in a file that has `pragma solidity ^0.4.24 || 0.8.9;`, and you import an ABI JSON file, then Truffle should tell abi-to-sol that it needs to produce output that's also got `pragma solidity ^0.4.24 || 0.8.9;`.

## Issue

The issue is: `resolver.resolve()` doesn't know anything about the language, compiler version, settings, etc. for which it's invoked! So there's no way for this functionality to specify the correct version to abi-to-sol (as per the background above), since it doesn't have this info at all.

And since this codepath is run via the profiler, we also need the profiler to know this information. Right now, the profiler also does not get information of this kind.

So maybe there's a clean way for compile-solidity, etc. to invoke the profiler with this information? And then this information could get passed along to `resolver.resolve()`? Hopefully this is not just asking for a giant mess.

(Side note: besides the background above, I imagine this information could be useful more generally - right now there's this weird `if` statement [here](https://github.com/trufflesuite/truffle/blob/develop/packages/resolver/lib/resolver.ts#L61-L63) that seems to exist for Vyper only. Maybe if we solve this information access problem, we can clean this up?)

**Comment by haltman-at** [comment]
> Ideally, when the user does this, the produced Solidity source should match whatever pragma it was imported by, and abi-to-sol output should be compatible with this pragma. So if you're in a file that has pragma solidity ^0.4.24 || 0.8.9;, and you import an ABI JSON file, then Truffle should tell abi-to-sol that it needs to produce output that's also got pragma solidity ^0.4.24 || 0.8.9;.

Do we want it to know about the pragma, or about the actual version?  Pragmas can be overly broad and as such can't necessarily be relied on (also they're optional).  Having it know about the actual version would be more reliable... except of course the current `compile-solidity` code isn't set up to allow anything like that.

> The issue is: resolver.resolve() doesn't know anything about the language, compiler version, settings, etc. for which it's invoked! So there's no way for this functionality to specify the correct version to abi-to-sol (as per the background above), since it doesn't have this info at all.

OK so here you seem to be suggesting it should be the actual version, not the pragma?  Which I think makes more sense.  Except...

> So maybe there's a clean way for compile-solidity, etc. to invoke the profiler with this information?

Unfortunately, I don't think there is.  Compile-vyper, maybe, but compile-vyper doesn't need this. :P  The problem is that compile-solidity is set up in such a way such that very little of the code knows what version is being used.  But, maybe we could change that...?  You'd probably want to talk to @eggplantzzz about that, it involves all the supplier stuff.  Or maybe it would be a good idea to finish the existing supplier rework first?  IDK, I'm not entirely clear offhand on exactly how all this relates.

> (Side note: besides the background above, I imagine this information could be useful more generally - right now there's this weird if statement here that seems to exist for Vyper only. Maybe if we solve this information access problem, we can clean this up?)

Hm, maybe!

**Comment by gnidan** [comment]
> Do we want it to know about the pragma, or about the actual version?

I think pragma would be nice because the generated Solidity would then match the pragma for user-supplied sources, but this is certainly not necessary.

> Unfortunately, I don't think there is. Compile-vyper, maybe, but compile-vyper doesn't need this. :P The problem is that compile-solidity is set up in such a way such that very little of the code knows what version is being used.

Mmmm, yeah. That's probably my fault originally, sorry!

> Or maybe it would be a good idea to finish the existing supplier rework first?

Well, I really want to upgrade abi-to-sol, so maybe that's the incentive I need to do supplier stuff :)

**Comment by gnidan** [comment]
This has been resolved in [Truffle v5.4.20](https://github.com/trufflesuite/truffle/releases/tag/v5.4.20)

**Comment by gnidan** [comment]
Oops, confused the merged PR for this fix with another PR. This is still unreleased.

**Comment by gnidan** [comment]
This has been resolved in [Truffle v5.4.22](https://github.com/trufflesuite/truffle/releases/tag/v5.4.22)
