### ISSUE TITLE
Needs documenting: Add support for customizing output directory for compiled contracts

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#439]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
As a developer, I'd like to provide a folder name where contracts(JSON) will be compiled.
## Expected Behavior

What you expected to happen.
In `truffle.js` I should be able to setup an output folder where contracts will be compiled

## Actual Results
No such way.

**Comment by tcoulter** [comment]
In fact, you *can* do this! Unfortunately, it's just undocumented. We should document it.

In your `truffle.js` file, add a new key called `contracts_build_directory` key to be whatever path you would like.

Leaving this open to remind us to document it.

**Comment by bmmpxf** [comment]
Docs added as of https://github.com/trufflesuite/trufflesuite.com/commit/1f4464af

See here: http://truffleframework.com/docs/advanced/configuration#contracts_build_directory

Thanks so much for the issue report! If you see any more things that need documenting, please bring it to our attention.
