### ISSUE TITLE
Calls type method code is calling getBlock() in the detect-network method which is not required

### ISSUE THREAD

**Issue by msoni89** [trufflesuite/truffle#4398]
- [ ] I've [opened a pull request ](https://github.com/trufflesuite/truffle/pull/4397) for this issue.

---------------------------

## Issue

Calls type method code is calling getBlock() in the detect-network method which is not required. 

## Steps to Reproduce

`const instance = await MyContract.deployed();
const result = await instance.myMethod.call()`

Observe network logs and you will find there is an extra getBlock method executed which is not required for calls type. 

## Expected Behavior

Calls are free (do not need gas cost)

## Actual Results

Please check network calls and you will see extra network calls for Calls type method.

**Comment by haltman-at** [comment]
The fix for this is released so I'm going to go ahead and close this (looks like @gnidan forgot to).  Thanks for bringing this up... and thanks for fixing this as well! :)
