### ISSUE TITLE
Contract.new() that would take an account parameter.

### ISSUE THREAD

**Issue by Zuchos** [trufflesuite/truffle#440]
It would be handy to be able to pass `account` parameter to `new()` function that is deploying contract and returning new instance of if.
I know that I may decide which account will be used in `config` but then this account will be used for all the contracts. It would be nice to have an option to select it during contract creation with new() function.

**Comment by tcoulter** [comment]
Hi there,

You can already do this! Check out the documentation [here](https://github.com/trufflesuite/truffle-contract#mycontractnewarg1-arg2--tx-params). You can use the `from` parameter to specify which account is making the transaction.

Cheers!
