### ISSUE TITLE
not install！！！！！！

### ISSUE THREAD

**Issue by acodercat** [trufflesuite/truffle#441]
node-pre-gyp ERR! Tried to download(undefined): https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for wrtc@0.0.61 and node@8.1.0 (node-v57 ABI) (falling back to source compile with node-gyp)
https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.61/Release/node-v57-linux-x64.tar.gz   error

please！！！！！！！！！！！！！！！！

**Comment by FugueWeb** [comment]
Similar problem

**Comment by FugueWeb** [comment]
http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past

This worked for me, great work as always Truffle Team!

**Comment by IAMtheIAM** [comment]
Thanks, node-gyp was not working for me, even with Python 2.7 and Windows 8.1 SDK installed. 

`npm install -g truffle@beta` worked instantly.

**Comment by tcoulter** [comment]
The beta has now been officially released. You can now install version 3.4.3 to fix this issue. Cheers!
