### ISSUE TITLE
`artifacts.require` dependency of dependency bug

### ISSUE THREAD

**Issue by S0AndS0** [trufflesuite/truffle#4410]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

> Truffle Ticket #479917 [Pending] `artifacts.require` dependency of dependency bug

> **Notice** I have found a workaround, however, I am still submitting this as an Issue due to framework behavior and error messag. For those only interested in solutions, skip to the "Attempts at Resolution" section and review steps `5` and `6` (second to last section of this OP)

---------------------------

## Issue

I'm running into an interesting bug when I introduce an `interface` to a project, that persists **even after** removal of the `interface`. To be clear, prior to introduction of an `interface` contract, Truffle has **no** issue finding and linking various dependencies.

Additionally this bug seems to be reproducible when linking a `library` that is a dependency of a development dependency. Because when adding an `interface` contract to a project that directly depends on an external `library` there are no issues.

______

## Steps to Reproduce

0. Clone `string-storage`

```bash
git clone https://github.com/solidity-utilities/string-storage.git
```

1. Check out `v0.0.1` tag

```bash
pushd string-storage

git checkout v0.0.1
```

2. Install NPM dependencies

```bash
npm ci
```

3. Run tests before adding `interface` file

```bash
npm test
```

4. Add `contracts/InterfaceStringStorage.sol` file, and re-run tests to generate persistent error

> Note, I've recently tested with an empty `interface` contract and similar errors are thrown.

```solidity
// SPDX-License-Identifier: AGPL-3.0
pragma solidity 0.8.7;

///
interface InterfaceStringStorage {
    ///
    function data(string memory) external view returns (string memory);
    ///
    function indexes(string memory) external view returns (uint256);
    ///
    function keys(uint256) external view returns (string memory);
    ///
    function owner() external view returns (address);
    ///
    function addAuthorized(address _key) external;
    ///
    function changeOwner(address _new_owner) external;
    ///
    function clear() external;
    ///
    function deleteAuthorized(address _key) external;
    ///
    function get(string memory _key) external view returns (string memory);
    ///
    function getOrElse(string memory _key, string memory _default) external view returns (string memory);
    ///
    function getOrError(string memory _key, string memory _reason) external view returns (string memory);
    ///
    function has(string memory _key) external view returns (bool);
    ///
    function indexOf(string memory _key) external view returns (uint256);
    ///
    function indexOfOrError(string memory _key, string memory _reason) external view returns (uint256);
    ///
    function listKeys() external view returns (string[] memory);
    ///
    function remove(string memory _key) external returns (string memory);
    ///
    function removeOrError(string memory _key, string memory _reason) external returns (string memory);
    ///
    function selfDestruct(address _to) external;
    ///
    function set(string memory _key, string memory _value) external;
    ///
    function setOrError(string memory _key, string memory _value, string memory _reason) external;
    ///
    function size() external view returns (uint256);
}
```

5. Remove `contracts/InterfaceStringStorage.sol` file, and re-run tests to continue generating persistent error

______

## Expected Behavior

I expect tests to continue to pass... well that is until I write something to explicitly break 'em.

______

## Actual Results

**Thrown Error**

```
Error: Could not find artifacts for LibraryMappingAddress from any sources
```

**Stack Trace**

```
Warning: ignored -> Cannot find module '@truffle/hdwallet-provider'
Require stack:
- /home/s0ands0/git/hub/solidity-utilities/string-storage/truffle-config.js
- /home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/original-require/index.js
- /home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/cli.bundled.js

> @solidity-utilities/string-storage@0.0.1 test
> truffle test

Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/Test_StringStorage.sol
> Compiling ./test/examples/Account.sol
> Compiling ./test/examples/Host.sol
> Artifacts written to /tmp/test--83899-w9eEJPWISKxO
> Compiled successfully using:
   - solc: 0.8.7+commit.e28d00a7.Emscripten.clang

Notice: detected network of development kind -> { network: 'development' }
Error: Could not find artifacts for LibraryMappingAddress from any sources
    at Resolver.require (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at module.exports (/home/s0ands0/git/hub/solidity-utilities/string-storage/migrations/99_development.js:13:43)
    at Migration._load (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration.run (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at Object.run (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:114:1)
    at Object.run (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:182:1)
    at Command.run (/home/s0ands0/git/hub/solidity-utilities/string-storage/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.18 (core: 5.4.18)
Node v16.11.0
```

> Note, to be absolutely clear this error only appears when an `interface` contract is added to `contracts/` directory of the `string-storage` project.
>
> Furthermore, this bug is persistent in that errors remain even after removing the `interface` contract.
>
> The similar project `address-storage` is built much the same, eg. it too has an `interface` contract, but has **no** such errors reported.

______

## Environment

* Operating System: Linux
* Ethereum client: ganache-cli 6.12.2
* Truffle version (`truffle version`): 5.4.18
* node version (`node --version`): v16.11.0
* npm version (`npm --version`): 8.0.0

______

## Attempts at Resolution

0. Defined `LibraryMappingAddress` as a development dependency, eg.

```bash
pushd ~/git/hub/solidity-utilities/string-storage

npm install --save-dev @solidity-utilities/library-mapping-address
```

1. Defined various paths to `LibraryMappingAddress`, eg.

```javascript
  /* ... */
  const LibraryMappingAddress = artifacts.require("@solidity-utilities/library-mapping-address/contracts/LibraryMappingAddress");
  /* ... */
  const LibraryMappingAddress = artifacts.require("@solidity-utilities/library-mapping-address/LibraryMappingAddress");
  /* ... */
  const LibraryMappingAddress = artifacts.require("library-mapping-address/LibraryMappingAddress");
  /* ... */
  const LibraryMappingAddress = artifacts.require("library-mapping-address/contracts/LibraryMappingAddress");
  /* ... */
  const LibraryMappingAddress = artifacts.require("../node_modules/@solidity-utilities/library-mapping-address/contracts/LibraryMappingAddress");
```

> Note, I tried each with and without the `.sol` file extension too

2. Ran tests via globally installed `truffle`, eg.

```bash
pushd ~/git/hub/solidity-utilities/string-storage

truffle test
```

3. Ran tests via NPX

```bash
pushd ~/git/hub/solidity-utilities/string-storage

npx truffle test
```

4. Ran tests via direct node modules path

```bash
pushd ~/git/hub/solidity-utilities/string-storage

node node_modules/truffle/build/cli.bundled.js test
```

5. Removed `build/` directory and re-ran tests

```bash
pushd ~/git/hub/solidity-utilities/string-storage

rm -rf build/

npm test
```

6. Linked all `library` contracts with all other `contract` files

```javascript
"use strict";

module.exports = (deployer, network, accounts) => {
  if (network !== "development") {
    return;
  }

  console.log("Notice: detected network of development kind ->", { network });

  const LibraryMappingAddress = artifacts.require("LibraryMappingAddress");
  const AddressStorage = artifacts.require("AddressStorage");

  const LibraryMappingString = artifacts.require("LibraryMappingString");
  const StringStorage = artifacts.require("StringStorage");

  const Account = artifacts.require("Account");
  const Host = artifacts.require("Host");

  const StringStorage__owner = accounts[0];
  const AddressStorage__owner = accounts[1];
  const Account__owner = accounts[2];
  const Host__owner = accounts[3];
  const Host__fee = 100;

  // LibraryMappingString.address = "0x0...";
  deployer.deploy(LibraryMappingString, { overwrite: false });

  // LibraryMappingAddress.address = "0x1...";
  deployer.deploy(LibraryMappingAddress, { overwrite: false });

  deployer.link(LibraryMappingAddress, [
    AddressStorage,
    StringStorage,
    Account,
    Host,
  ]);

  deployer.link(LibraryMappingString, [
    AddressStorage,
    StringStorage,
    Account,
    Host,
  ]);

  deployer.deploy(AddressStorage, AddressStorage__owner);
  deployer.deploy(StringStorage, StringStorage__owner);

  deployer.deploy(Account, Account__owner);
  deployer.deploy(Host, Host__owner, Host__fee);
};
```

... Up 'till "Attempts at Resolution" step `4` no joy though, and perhaps most bothersome is this bug persists even after removal of `contracts/InterfaceStringStorage.sol` file.

However, turns out that "Attempts at Resolution" step `5` combined with step `6` lossened things up such that tests began to compile, run, and pass!

______

## Links to Mentioned Repositories

- [GitHub -- `solidity-utilities/library-mapping-address`](https://github.com/solidity-utilities/library-mapping-address)

- [GitHub -- `solidity-utilities/address-storage`](https://github.com/solidity-utilities/address-storage)

- [GitHub -- `solidity-utilities/library-mapping-string`](https://github.com/solidity-utilities/library-mapping-string)

- [GitHub -- `solidity-utilities/string-storage`](https://github.com/solidity-utilities/string-storage)

**Comment by haltman-at** [comment]
So, the reason that the problem doesn't go away when you delete the interface and recompile is that Truffle doesn't currently delete artifacts of removed contracts upon a recompile; there's actually an open issue for this (#2724).

However, that leaves the question of why there's a problem in the first place.  That will still need to be investigated.

**Comment by eggplantzzz** [comment]
Hey @S0AndS0, thanks for providing such detailed steps for reproducing this! However, when I follow your steps all of the tests that fall under "Contract: test/examples/Account.sol" and "Contract: test/examples/Host.sol" fail. So I am unable to reproduce the error you are reporting. Do you have time to advise me?

**Comment by S0AndS0** [comment]
@haltman-at Thank you!  The number of times stale artifacts have caused odd bugs is, at this point, uncountable; so ya have saved me considerable time over these intervening months.

---

@eggplantzzz I'm a bit short on time, but my guess is maybe ya need to checkout the tagged version from the OP, eg.

```bash
git checkout v0.0.1
```

... But that is just a wild guess, as it has been many moons between posting and now.

---

@cds-amal Sure!  However please be aware my device has gone through _some_ changes.

```bash
grep -Ev '^#|^\s*$' /etc/fstab
#> UUID=<UUID>                 /boot/efi      vfat  umask=0077                 0 2
#> UUID=<UUID>                 /              ext4  defaults,noatime           0 1
#> tmpfs                       /var/cache     tmpfs defaults,noatime           0 0
#> tmpfs                       /var/log       tmpfs defaults,noatime,mode=0755 0 0
#> tmpfs                       /var/spool     tmpfs defaults,noatime           0 0
#> tmpfs                       /var/tmp       tmpfs defaults,noatime           0 0
#> tmpfs                       /tmp           tmpfs defaults,noatime           0 0
```

**Comment by eggplantzzz** [comment]
I actually checked out that branch to do my tests according to the instructions. Unfortunately I don't think it runs :(

**Comment by cds-amal** [comment]
@S0AndS0, do you have a working reproduction guide/repo? The above instructions didn't run.
