### ISSUE TITLE
Contract deploys on Mumbai but never mined on Mainnet regardless of gas price settings

### ISSUE THREAD

**Issue by 0x62** [trufflesuite/truffle#4418]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I'm able to deploy to Polygon Mumbai, but when trying to deploy to Mainnet it hangs at the migration contract and the transaction fails to be mined. I've tried increasing gas and different RPC endpoints.

Truffle config:
```
const mainnetUrl = `https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}`

// ...

networks: {
  mumbai: {
    provider: function() {
      return new HDWalletProvider(MNEMONIC, mumbaiUrl)
    },
    network_id: 80001,
    confirmations: 2,
  },
  matic: {
    networkCheckTimeout: 1000000,
    timeoutBlocks: 1000,
    gasPrice: 100000000000, // 100 gwei
    network_id: 137,
    confirmations: 2,
    provider: function() {
      return new HDWalletProvider(MNEMONIC, mainnetUrl)
    },
  },
},
```

Despite the block and network timeout settings it always fails at 750s. 

## Steps to Reproduce

Deploy contract

## Expected Behavior

The contract is deployed

## Actual Results

Deployment failed, not mined within 750 seconds.

```
1_initial_migrations.js
=======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x24c71088f63c1a4f390f3a66fdfdac39b1dff5fbd0bba6a8a51b487680d6555f

Error:  *** Deployment Failed ***

"Migrations" -- Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!.
```

I've made multiple attempts and none have worked. Transactions don't even appear on Polygonscan (they did for a few minutes and now 404). 

* 0x24c71088f63c1a4f390f3a66fdfdac39b1dff5fbd0bba6a8a51b487680d6555f
* 0x03fc4b1835addef524fe85c6566e879e9eade1fa8fbac350b2e09e83d5ee6cd7
* 0x4ebd04bf964b75918333f7f8ad4c9938176a491f7f65ec7b3e100bcaa87739c3

## Environment

* Operating System: macOS
Truffle v5.4.18 (core: 5.4.18)
Solidity - ^0.8.0 (solc-js)
Node v14.18.1
Web3.js v1.5.3

https://ethereum.stackexchange.com/questions/113292/truffle-deploy-on-testnet-successful-but-transaction-never-confirms-on-mainnet

**Comment by MicaiahReid** [comment]
Hi @0x62, thanks for the issue. We think this is due to a known issue with the dry runs that happen during migrations. As a workaround, you can try running `truffle migrate --skip-dry-run`. We'll be looking into fixing the root cause.

**Comment by kiknaio** [comment]
Same issue here. I was able to deploy contract on Mumbai without any issues, but on the Mainnet transactions are not validated.

**Comment by kiknaio** [comment]
Even with `truffle migrate --skip-dry-run` transaction is not mined.

**Comment by arbach** [comment]
Same here,  --skip-dry-run did not help.  any update on this ?

**Comment by mustafa-boorenie** [comment]
I'm having the same issue, is there at least any interim fixes to deploy contracts in the meantime?

**Comment by JohnSmitherens** [comment]
Same issue here, deploys on Mumbai but transaction not mined on Mainnet within a reasonable time frame. It does actually get mined, but about 10 hours later, so it is not possible to deploy since truffle times out.

![img](https://user-images.githubusercontent.com/97666526/149302198-bad5c1af-b980-459b-b21f-4941b7b1a026.jpg)

**Comment by rhamnett** [comment]
I'm having this same issue with an ERC721 contract using hardhat. ```await nft.deploy()``` never returns on mainnet. Has anyone found out any more information? I am using hardhat and have tried loads of diff RPC node URLs.

**Comment by svonian** [comment]
Same issue, have tried multiple RPCs, gas configurations, computers, --skip-dry-run, etc.

**Comment by Kenshiro-28** [comment]
Same here, any workaround?

**Comment by rhamnett** [comment]
This is definitely related to gas settings, if you persist you will eventually get it right. The documentation does not best help, I have to admit.

**Comment by svonian** [comment]
> This is definitely related to gas settings, if you persist you will eventually get it right. The documentation does not best help, I have to admit.

Could you share the gas settings that worked for you? I have executed the script at least 20 times with different gas combinations similar to the original poster as well and extremely generous ones as well and changing gasLimit.

**Comment by illing2005** [comment]
Same problem here.
Did anyone find a solution, yet?

**Comment by khidesha** [comment]
The problem appears in my case because I passed the big gas limit for transactions from my truffle-config.

So these transactions are stuck in mem-pool.

The workaround is making some transactions with the same nonce from the account u are using in truffle. Make it outside of truffle or with different RPC. Hope I helped

**Comment by Miladinho** [comment]
> The problem appears in my case because I passed the big gas limit for transactions from my truffle-config.
> 
> So these transactions are stuck in mem-pool.
> 
> The workaround is making some transactions with the same nonce from the account u are using in truffle. Make it outside of truffle or with different RPC. Hope I helped

what?!

**Comment by kevinweaver** [comment]
I wasn't able to reproduce this issue, likely due to low network usage at the time I tried. 

@0x62, please try removing the hard coded `gasPrice` value here, as Truffle will estimate an appropriate price based on current network conditions.
