### ISSUE TITLE
how to work with the custom data types from the contract?

### ISSUE THREAD

**Issue by PavelPolyakov** [trufflesuite/truffle#442]
Yes, I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
In my contract I have both `enum` and `struct` defined:
```
contract SmartKT {
    enum STATUS {SEEDING, FUNDING, PERFORMING, REPAID}

    struct State {
    STATUS status;
    uint balance;
    }

    State public state;
```

In my test I want to be able to validate that the `state`, for example, has the correct statue.

What I'm trying to do is:
```javascript
const Promise = require('bluebird');
const SmartKT = artifacts.require("./SmartKT.sol");
const {
    web3
} = SmartKT;
contract('SmartKT', function(accounts) {
    it("successful case", function() {
        return Promise.coroutine(function*() {
            const instance = yield SmartKT.deployed();
            console.log((yield instance.state.call()));
        })()
    });
});
```
What I see in the console is:
![image](https://user-images.githubusercontent.com/839290/27003751-ef9f4142-4dfc-11e7-9de4-1f604006ca33.png)

I understand this is my structure, but how can I work with it? like addressing the particular properties.

## Expected Behavior

* Receive the `object` with structure properties.
* be able to map back the `ENUM`

## Actual Results

I the array is returned.

## Environment

* Operating System: `macOS`
* Truffle version: `v3`
* Ethereum client: `testrpc`
* node version: `6.*`
* npm version:  `3.*`

**Comment by shdmitry2000** [comment]
+1
