### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:443 while unboxing metacoin or any other boxRequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by moribus-single** [trufflesuite/truffle#4426]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

When I trying to unbox any box, metacoin, pet-shop etc. I have a issue RequestError. When I installed truffle, I've got a lot of warn deprecates. Logs in screenshots. Maybe problem in a bunch of warns? How can I fix it?

![Снок](https://user-images.githubusercontent.com/70265720/141432429-282068ec-d233-47c2-8017-e68715d4b893.PNG)
![Снмок](https://user-images.githubusercontent.com/70265720/141432494-fa734a7f-3583-4e8f-8a8f-cd1cb7fb84cf.PNG)

Operating System: Windows 10
Ethereum client:
Truffle v5.4.19 (core: 5.4.19)
Solidity v0.5.16 (solc-js)
Node v16.13.0
Web3.js v1.5.3
RequestError: connect ECONNREFUSED 127.0.0.1:443
![dsafasdf](https://user-images.githubusercontent.com/70265720/141430704-3292f74f-09a3-4832-a838-ce7ac43e1ccd.PNG)

**Comment by cds-amal** [comment]
@moribus-single, there is a known issue with **npm v7+** which happens to be the default for **Node 16**. Can you fallback to **npm v6** (`npm -g install npm@6`) and try installing truffle again (`npm -g uninstall truffle && npm -g install truffle`)? 

Regarding the unbox, can you run and post the debug output of the following command? `DEBUG=* truffle unbox <the-box-you-tried>`

Thanks!

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. Please reopen or create another issue if this is still happening.
