### ISSUE TITLE
Can't compile solc version "^0.8.9"

### ISSUE THREAD

**Issue by thedarkknight197** [trufflesuite/truffle#4431]
Hello,
i am trying to deploy my smart contracts to my private ethereum blockchain. But when I start with truffle migrate --network live I receive this error: 

`Error: Could not find a compiler version matching ^0.8.9. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.`

My solidity smart contract have the declaration of solidity 0.8.9:
`pragma solidity ^0.8.9;`

Here is my truffle config: 

```
const Web3 = require("web3");
const web3 = new Web3();

require('babel-register');
require('babel-polyfill');


module.exports = {
    networks: {
        development: {
            host: "127.0.0.1",
            port: 7545,
            network_id: "*" // Match any network id
        },
        live: {
            host: "MyEndPointOfBlockchain",
            port: myport,
            network_id: "mynetworkID", // Match any network id
        },
    },
    contracts_directory: './src/contracts/',
    contracts_build_directory: './src/abis/',
    compilers: {
        solc: {
            version: "^0.8.9",
            optimizer: {
                enabled: true,
                runs: 200
            },
            evmVersion: "petersburg"
        }
    }
}

```
Thank you for your help

## Environment

* Operating System: MacOS 12.0
* Ethereum client:
* Truffle version (`truffle version`): v5.4.19 (core: 5.4.19)
* node version (`node --version`): v16.13.0
* npm version (`npm --version`): v8.1.0

**Comment by thedarkknight197** [comment]
If I use Remix and attach to my Web3 injected, connected to my blockchain the deploy of the contract work well

**Comment by gnidan** [comment]
Hm, interesting. If you've previously gotten this to work, you might try removing the `^`, since that causes Truffle to look for a later compatible version on the internet. I just tried this locally and it worked fine for me, so maybe this was just a temporary problem due to network conditions.

The other thing you could try is to set `docker: true` alongside `version: ...`, since that will have Truffle download the solc Docker container, rather than the JS-compiled distribution.

Sorry about this, and thank you for reporting this issue!

**Comment by gnidan** [comment]
(I do notice that [this PR of mine](https://github.com/trufflesuite/truffle/pull/4420) is failing for similar reasons, so I'll be looking into this one way or another)

**Comment by thedarkknight197** [comment]
Mmmh very strange, in my MacBook Pro 13 m1 work, in my 16 not.. I am not using docker with truffle.

Removing ^ I have the same problem:
"Error: Could not find a compiler version matching 0.8.9. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions."

**Comment by thedarkknight197** [comment]
The result of: truffle compile -list:

```
michele@MacBook-Pro-di-michele-2 SocialChainBackend % truffle compile --list
✔ Fetching solc version list from solc-bin. Attempt #1
[
 "0.8.10",
 "0.8.9",
 "0.8.8",
 "0.8.7",
 "0.8.6",
 "0.8.5",
 "0.8.4",
 "0.8.3",
 "0.8.2",
 "0.8.1",
 ".. and 83 more. Use `--all` to see full list."
]
michele@MacBook-Pro-di-michele-2 SocialChainBackend %
```

**Comment by pguso** [comment]
I am having the same issue. With the same code on my macbook pro 16 with intel chip its working, on my macbook air with m1 chip i get the same error ```Error: Could not find a compiler version...```

**Comment by thedarkknight197** [comment]
> I am having the same issue. With the same code on my macbook pro 16 with intel chip its working, on my macbook air with m1 chip i get the same error `Error: Could not find a compiler version...`

I in my MacBook Pro m1 with sudo no work, but is very strange, I think is a strange problem with permission @gnidan please check, thanks

**Comment by gnidan** [comment]
We're hard at work digging into this problem! Trying very hard to fix this in time for this week's release. Sorry everyone!

**Comment by gnidan** [comment]
@thedarkknight197 and @pguso can you try Truffle v5.4.18? We're having a hard time reproducing this issue (the failing PRs seem to be unrelated).

I'd recommend uninstalling Truffle first, just to be safe:
```console
npm uninstall -g truffle
npm install -g truffle@5.4.18
```

@pguso I don't know if you're also using babel in your truffle-config like that, but @thedarkknight197 maybe try commenting out those two lines and see if it works any better for you?

Also, does this only happen when you run `truffle migrate`, or does `truffle compile` also fail? (And I guess, is it only a problem if you're migrating to `--network=live`?)

Any additional information you can provide would be helpful! Thank you

**Comment by maks-p** [comment]
I'm having the same issue and just tried this fix (uninstalling and installing truffle), still not working for me.

Error:

```Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Downloading compiler. Attempt #1.
✔ Downloading compiler. Attempt #2.
Error: Could not find a compiler version matching ^0.8.0. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.
    at VersionRange.errors (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/LoadingStrategy.js:66:1)
    at VersionRange.getSatisfyingVersionFromCache (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js:87:1)
    at VersionRange.load (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/loadingStrategies/VersionRange.js:205:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CompilerSupplier.load (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/compilerSupplier/index.js:71:1)
    at loadParser (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:15:29)
    at Object.requiredSources (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/index.js:19:1)
    at Object.sourcesWithDependencies (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:139:45)
    at necessary (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:106:1)
    at /opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:35:1
    at async Promise.all (index 0)
    at compile (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:25:1)
    at Object.compile (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:68:47)
    at Object.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:77:1)
    at Command.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.18 (core: 5.4.18)
Node v17.0.1```

MacOS 12.0
MacBook Pro (14-inch, 2021) 
Apple M1 Max

**Comment by maks-p** [comment]
Some more information, to the extent it is helpful:

I originally was not able to `npm install -g truffle`, so I used `sudo`. On further reflection and reading about how one is *not* supposed to `sudo npm install`, I did my best to uninstall `node` and used `homebrew` to reinstall it.

There's a chance that original `sudo npm install -g truffle` command is still causing issues, so wanted to mention it.

**Comment by gnidan** [comment]
Oh! Could be that sudo is causing issues. Can you `ls -l ~/Library/Preferences/truffle-nodejs/compilers/node_modules/` please? That's where Truffle keeps its cache of compilers on Mac. It's possible that this directory got created owned by root, and now Truffle can't read from it.

**Comment by maks-p** [comment]
Yep, returns:

```
total 24216
-rw-r--r--  1 root  staff  12394706 Nov 13 13:15 soljson-v0.5.16+commit.9c3226ce.js
```

**Comment by gnidan** [comment]
Nice! Something to go off of. Try deleting Truffle's whole directory there:
```console
rm -rf ~/Library/Preferences/truffle-nodejs
```

You'll need to add `sudo` there, naturally :)

(and please never give Truffle super-user permissions, we don't want 'em!)

**Comment by maks-p** [comment]
That was it. Removed that directory and was able to compile.

I, and @thedarkknight197 as well possibly given their `config` is very similar to mine, was following a tutorial that literally said you may have an issue with `npm install` and to use `sudo` in this case. I did it without thinking. Now hoping I don't need to reinstall the OS lol.

**Comment by gnidan** [comment]
Bingo! I just reproduced the issue by `chown`ing that to `root`. Alright, @thedarkknight197 and @pguso please let us know if this fixes the problem for you as well.

Thanks for your help @maks-p and all.

(And stay tuned for a `truffle doctor` command ;)

**Comment by pguso** [comment]
> Bingo! I just reproduced the issue by `chown`ing that to `root`. Alright, @thedarkknight197 and @pguso please let us know if this fixes the problem for you as well.
> 
> Thanks for your help @maks-p and all.
> 
> (And stay tuned for a `truffle doctor` command, since @cds-amal just came up with the idea to automatically diagnose these sorts of issues ;)

Yes the command ```rm -rf ~/Library/Preferences/truffle-nodejs``` solves it for me. Thank you and the others helping to find a solution. I am happy that I can use truffle on my Air now.

**Comment by thedarkknight197** [comment]
I read now, when I am to pc I will update you.
Thanks to all 😄

**Comment by clarkshu1016** [comment]
> Nice! Something to go off of. Try deleting Truffle's whole directory there:
> 
> ```
> rm -rf ~/Library/Preferences/truffle-nodejs
> ```
> 
> You'll need to add `sudo` there, naturally :)
> 
> (and please never give Truffle super-user permissions, we don't want 'em!)

Error: Could not find a compiler version matching 0.8.10. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.
    at VersionRange.getSatisfyingVersionFromCache (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:134:1)
    at VersionRange.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:54:1)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:6:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.23 (core: 5.4.23)
Node v16.13.1


I face the same issue but I delete  Library/Preferences/truffle-nodejs ,everything works fine on me.

**Comment by haltman-at** [comment]
OK, it looks like the problem has been resolved; @thedarkknight197, please let us know if not and we can reopen this.  Thanks!

**Comment by Capcodes** [comment]
> ```
> ```
> rm -rf ~/Library/Preferences/truffle-nodejs
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

This worked for me im on a macbook air m1

**Comment by prakash6200** [comment]
you have to specify exact solidity version in your code, which is same as in truffle-config.js

**Comment by thedarkknight197** [comment]
> 

Work also for me :)
Thanks to all <3

**Comment by mscrodrigo** [comment]
I used the MAC M1 and fix using this command sudo rm -rf ~/Library/Preferences/truffle-nodejs
Tkx.

**Comment by shivammsingh** [comment]
work also for me thanks  :)

**Comment by eggplantzzz** [comment]
Just for a little bit more context, `~/Library/Preferences/truffle-nodejs` is the folder in which Truffle stores user settings and, more importantly, the cache of Solidity compilers. I'm not sure why this would fix your issue but glad it resolved it!

**Comment by CruzMolina** [comment]
Hi @eggplantzzz !

A colleague ran into this issue today and [this](https://github.com/trufflesuite/truffle/issues/4431#issuecomment-1108053572) ended up being the solution.

My hunch is that `truffle` was trying to read from the cache and needing `sudo` privileges to do so.

cc @gnidan @cds-amal

**Comment by revoltez** [comment]
i changed the ownership of ~/.config/truffle-nodejs and it worked
chown userName -R ~/.config/truffle-nodejs
in my case the problem was that the file was locked to use only by root even though i never installed truffle using sudo

**Comment by cds-amal** [comment]
Hi @CruzMolina !

> A colleague ran into this issue today and [this](https://github.com/trufflesuite/truffle/issues/4431#issuecomment-1108053572) ended up being the solution.
> 
> My hunch is that `truffle` was trying to read from the cache and needing `sudo` privileges to do so.
> 

Your hunch is correct. We've seen this with *nix systems  due to root privileges unnecessarily applied. For example, using sudo with node package managers or npm.

**Comment by cds-amal** [comment]
> i changed the ownership of ~/.config/truffle-nodejs and it worked 
> `chown userName -R ~/.config/truffle-nodejs` in my case the problem was that the file was locked to use only by root even though i never installed truffle using sudo

Truffle would use the privileges it inherited from the shell. I recommend you use [npm doctor](https://docs.npmjs.com/cli/v6/commands/npm-doctor) to verify its basic requirements are met.
