### ISSUE TITLE
Allow the numbers of instructions displayed in Truffle debugger to be configurable

### ISSUE THREAD

**Issue by dongmingh** [trufflesuite/truffle#4437]
## Issue

Truffle debugger p command displays a group of instructions: the current instruction, 3 previous instructions and 3 upcoming instructions, see PR #4412.  This is to request that the debugger will make the numbers of previous and upcoming instructions configurable.

## Environment

* Truffle version (`truffle version`): v5.4.11 does not support the group instructions display yet

**Comment by haltman-at** [comment]
A note, if someone is going to do this, I'd suggest making the `l` command similarly configurable.  (That might be easier to start with, honestly...)

**Comment by kevinbluer** [comment]
Closing as this is addressed in https://github.com/trufflesuite/truffle/releases/tag/v5.4.24
