### ISSUE TITLE
truffle compile does not recompile files that import a modified file

### ISSUE THREAD

**Issue by beether** [trufflesuite/truffle#444]
- [ x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If `Two.sol` has `import "One.sol"` and `One.sol` is edited, executing `truffle compile` will only recompile `One.sol` and not `Two.sol`... though `Two.sol` may need to be recompiled to work correctly.

## Steps to Reproduce

Create two files:

One.sol
```
contract One {}
```

Two.sol
```
import "One.sol";
contract Two{}
```

Execute `truffle compile`.

Edit `One.sol` in any manner.

Execute `truffle compile` again.  Notice, only `One.sol` gets recompiled, though `Two.sol` may require the changes.  (eg, you may have added a function in One.sol that Two.sol wants to use, or changed parameters, etc).

## Expected Behavior

It would be nice if `Two.sol` were recompiled, since it imports `One.sol`.  However, this can get quite complex, as recompiling `Two.sol` would entail also recompiling anything that has `import "Two.sol"`, and so forth.

## Actual Results

One `One.sol` is compiled.

## Environment

* Operating System: 
* Truffle version:
* Ethereum client:
* node version:
* npm version:

**Comment by beether** [comment]
It should be noted that even if a collision occurs with --compile-all, it may could still also occur from a normal `compile`.  Eg, if you edit `UsesOne.sol` and do compile, it will clobber One.json.  The ideal result is that it would still warn you or error out, even if the only thing being recompiled is `UsesOne.sol`

Ideally, the fix to this would ensure that even if you first create One.sol compile, then create UsesOne.sol, and compile, the collision will be detected.

**Comment by tcoulter** [comment]
This should be fixed in v3.4.3. Please open a new ticket if you run into any more issues.
