### ISSUE TITLE
Discuss Impacts of Imminent Ganache v7 Release

### ISSUE THREAD

**Issue by MicaiahReid** [trufflesuite/truffle#4441]
There are some [known changes](https://github.com/trufflesuite/ganache/issues/1327) in Ganache that are not properly handled by Truffle. We should discuss/plan for this and any other possible breaking changes.

**Comment by davidmurdoch** [comment]
Should we discuss this now @gnidan @eggplantzzz @MicaiahReid ?

**Comment by cds-amal** [comment]
This should be closed as Ganache v7 is out in the world, however we may want to do a postmortem to catch any insights

**Comment by MicaiahReid** [comment]
@cds-amal Can you schedule this meeting?

**Comment by cds-amal** [comment]
Added to team align meeting
