### ISSUE TITLE
Rinkeby migration fails with Incompatible EIP155-based V 0 and chain id 1 

### ISSUE THREAD

**Issue by kevinweaver** [trufflesuite/truffle#4442]
## Issue

Running a migration on rinkeby fails unless you skip dry run because it appears that ganache is attempting to hard code chain id 1.  The fact that this was resolved [here](https://github.com/trufflesuite/ganache/pull/532) makes me wonder if it's a versioning issue (though the newest stable release of ganache is pinned in truffle).

## Steps to Reproduce

`git clone git@github.com:truffle-box/bridge-box.git`
`git checkout add-message-script`
`truffle migrate --network=ethereum_rinkeby --f 1 --to 1`

This will fail with:
```
Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
at Transaction._validateV (/Users/kevinweaver/github.com/trufflesuite/truffle/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:370:13
```

 However if you run:
`truffle migrate --network=ethereum_rinkeby --f 2 --to 2 --skip-dry-run` 
it succeeds.

## Expected Behavior

This should succeed without skipping the dry run.

## Environment

* Operating System: MacOS 11.6 w/ M1 
* Truffle version (`truffle version`): 5.4.15
* node version (`node --version`): v14.18.0
* npm version (`npm --version`): 6.14.15

**Comment by MicaiahReid** [comment]
@kevinweaver, just adding a note here for you: can you update reproduction steps and see if this is still failing? Now that truffle is using Ganache v7, this could be fixed.

**Comment by kevinweaver** [comment]
Retried and it looks like this is now working!  Closing this issue.
