### ISSUE TITLE
[truffle test][TypeScript] SyntaxError: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by chriskrogh** [trufflesuite/truffle#4449]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

zendesk ticket number: 523516

---------------------------

## Issue

While writing tests for my contract using TypeScript, I want to import a type into my test file as follows:
```
import { DotTokenInstance } from '../generated';
```

However, I get the following error when running `truffle test`:

```
Using network 'development'.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

/Users/chriskrogh/dev/dot/token/test/DotToken.test.ts:1
import { DotTokenInstance } from '../generated';
^^^^^^

SyntaxError: Cannot use import statement outside a module
at compileFunction (<anonymous>)
at Object.compileFunction (node:vm:353:18)
at wrapSafe (node:internal/modules/cjs/loader:1039:15)
at Module._compile (node:internal/modules/cjs/loader:1073:27)
```

I have tried modifying the mocha config in `truffle-config.js` to be
```
mocha: {
  require: ['ts-node/register'],
}
```

and adding a `tsconfig.testing.json` with

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "include": ["test/**/*.test.ts"]
}
```

however this did not work. I also tried modifying the mocha config to include 

```
mocha: {
  require: ['@babel/register'],
}
```

and following the babel installation instructions here [babel](https://babeljs.io/en/setup?fireglass_rsn=true#installation), however that did not work either.

## Steps to Reproduce

- Create a new truffle project using `truffle init`
- Create a TypeScript test file `*.test.ts`
- Import a module into the test file using `import a from 'path/to/a'` syntax
- Run `truffle test`

## Expected Behavior

The test should run.

## Actual Results

The exception outlined above is thrown.

## Environment

* Operating System: 
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): Truffle v5.4.19 (core: 5.4.19)
* node version (`node --version`): v16.3.0
* npm version (`npm --version`): 7.15.1

**Comment by chriskrogh** [comment]
# Followup

I manually typed the variable instead of importing its type and I encountered another error:

```
/Users/chriskrogh/dev/dot/token/test/DotToken.test.ts:4
  let instance: { address: string };
              ^

SyntaxError: Unexpected token ':'
    at compileFunction (<anonymous>)
    ...
```

It seems like the issue here is the way that the TypeScript is being transpiled for the tests to run. I think the fix may be an update to the tsconfig being used for tests.

Alternatively, you could let developers modify this config themselves? Maybe developers can add their config to a `tsconfig.testing.json` and then specify the path to this config file somewhere in the `truffle-config.js`?

**Comment by eggplantzzz** [comment]
@chriskrogh The issue here is that Truffle does not natively support writing your tests in TypeScript. This is a feature that we plan on implementing at some point.

However I do believe there is some setup you can do to make this work. I think [this medium article](https://medium.com/ethereum-ts/typesafe-truffle-with-typescript-and-typechain-1773e5b733b4) talks about how you can do this though I have not actually done it myself. Maybe you'll find it helpful!

**Comment by haltman-at** [comment]
See: #4461, #3778.

**Comment by gnidan** [comment]
Seems like this is a duplicate issue of those two above? Anything else to add, or should we close this in favor of those?

Really sorry about this 😭

**Comment by chriskrogh** [comment]
Yep we can close this one as a dup of the others. Hope TS support for tests comes soon?😅  Thanks folks
