### ISSUE TITLE
deployer.deploy() passes no arguments to constructor

### ISSUE THREAD

**Issue by beether** [trufflesuite/truffle#446]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If `SomeContract` has a constructor that takes N arguments, and <N arguments are passed to `deployer.deploy()`, then **zero** arguments are passed to the constructor.

## Steps to Reproduce

Create a contract:

```
contract Foo {
   function Foo(uint one, uint two, uint three){
      require(one != 0);
   }
}
```
Deploy it, but do not pass enough arguments
```
deployer.deploy(Foo, 1, 2);
```
## Expected Behavior

one and two should be passed, but not three.

## Actual Results

No arguments are passed to the constructor.

THIS TOOK ME FOREVER TO FIGURE OUT.  Yet another reason to allow named params (eg: `deployer.deploy(Foo, {one: 1, two: 2})`, and/or to do validations on the client side.  This is what the ABI was meant for.

## Environment

* Operating System: 
* Truffle version:
* Ethereum client:
* node version:
* npm version:

**Comment by jjc12** [comment]
As a last suggestion,

In case you try `deployer.deploy(Foo, 1, 2)` and you're still getting the `BigNumber Error: new BigNumber() not a base 16 number: ` prompt, make sure to run the flag

`truffle migrate --reset`

and your contracts will be re-deployed to the test network.

**Comment by beether** [comment]
@jjc12 Sorry, `deployer.deployer` was a typo.  Fixed it.

I'm not getting `BigNumber Error` anywhere.

The problem is the first two arguments are not passed unless all three arguments are provided.

**Comment by jjc12** [comment]
Try this:
[contract Foo {
   function Foo(uint one, uint two) options (uint three){
      require(one != 0);
   }
}](url)

**Comment by beether** [comment]
@jjc12 You are missing the point of this issue.  It is a problem with `deployer.deploy()` not passing the first two arguments unless the third is present.

**Comment by jjc12** [comment]
You are missing the point of the solution. Add the `options` keyword to a function, such as `deploy()`, and you will allow parameters to be _optional._ 

That's how the Solidity language works; it's not specific to any one function, and that includes `deploy`.

**Deal with it.**

**Comment by beether** [comment]
Just to be clear, you _agree_ that the expected behavior of calling: `deployer.deploy(Contract, argOne, argTwo)` (when there are three required args) is to have _zero_ args be passed?

**Comment by beether** [comment]
Whatever.

**Comment by jjc12** [comment]
When there are three required args (because the `optional` keyword was not used), then the expected behavior is to have three args passed, if three args are passed. Otherwise, unexpected behavior occurs.

**Comment by jw4js** [comment]
I stumbled upon this from the internet, and I think the error reporting should be better. If it's going to check if there are enough arguments and pass zero arguments based on that, then it might as well just report an error.
