### ISSUE TITLE
Error: Could not find block - on Binance Smart Chain Migration

### ISSUE THREAD

**Issue by ditistijn** [trufflesuite/truffle#4466]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

`Error: Could not find block` on Binance Smart Chain Migration

## Steps to Reproduce

Create a new truffle project by doing `truffle init`
Set the network to bsc using these parameters in truffle-config.js
`    bsc: {
      provider: () => new HDWalletProvider(privatekeys, "https://bsc-dataseed1.binance.org"),
      network_id: 56,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: true
    },`
run `truffle migrate --network bsc`

## Expected Behavior

The contract will be migrated successfully to Binance Smart Chain

## Actual Results

Migration fails at random stages of migration with the error:
`/Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:163
        cb(null, null)
        ^
Error: Could not find block
    at /Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:62:28
    at afterRequest (/Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:163:9)
    at /Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:177:12
    at /Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:240:9
    at /Users/dev/Developer/solidity/node_modules/async/internal/once.js:12:16
    at replenish (/Users/dev/Developer/solidity/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/dev/Developer/solidity/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/dev/Developer/solidity/node_modules/async/eachLimit.js:43:36)
    at /Users/dev/Developer/solidity/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/dev/Developer/solidity/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:72:5)
    at Request.self.callback (/Users/dev/Developer/solidity/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/dev/Developer/solidity/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/dev/Developer/solidity/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
 `
Migration works if Binance Smart Chain testnet is used.

## Environment

* Operating System: MacOS Big Sur 11.2.3
* Ethereum client: 0.6.12 (solc-js)
* Truffle version (`truffle version`): Truffle v5.4.21 (core: 5.4.21)
* node version (`node --version`): Node v16.13.0
* npm version (`npm --version`): 8.1.0

**Comment by gnidan** [comment]
Hi @ditistijn, thanks for opening this. We're not very familiar with possible quirks on BSC; would it be possible for you to share with us a reproduction repo that we could try out? (Obviously please take out private keys ;)

(Does BSC have a testnet? Did you try that?)

Sorry to hear that you're running into this difficulty.

**Comment by ditistijn** [comment]
> Hi @ditistijn, thanks for opening this. We're not very familiar with possible quirks on BSC; would it be possible for you to share with us a reproduction repo that we could try out? (Obviously please take out private keys ;)
> 
> 
> 
> (Does BSC have a testnet? Did you try that?)
> 
> 
> 
> Sorry to hear that you're running into this difficulty.

I have indeed tried this with BSC Testnet. Results there are fine. I will create an example project once I get back to my computer.
Thanks for reaching out!

**Comment by ditistijn** [comment]
> Hi @ditistijn, thanks for opening this. We're not very familiar with possible quirks on BSC; would it be possible for you to share with us a reproduction repo that we could try out? (Obviously please take out private keys ;)
> 
> (Does BSC have a testnet? Did you try that?)
> 
> Sorry to hear that you're running into this difficulty.

https://github.com/ditistijn/truffleissue
This is the repository. Try running
`truffle migrate --reset --network bscmain`

**Comment by nhancv** [comment]
> > Hi @ditistijn, thanks for opening this. We're not very familiar with possible quirks on BSC; would it be possible for you to share with us a reproduction repo that we could try out? (Obviously please take out private keys ;)
> > (Does BSC have a testnet? Did you try that?)
> > Sorry to hear that you're running into this difficulty.
> 
> https://github.com/ditistijn/truffleissue This is the repository. Try running `truffle migrate --reset --network bscmain`

Yes, it's a suck. The issue comes from "@truffle/hdwallet-provider", this lib will be crashed after query block.
For temporary solution: 
- 1: You can flat the contracts and deploy manually via remix. Btw it's fine if you interact directly with Metamas
- 2: If you want continue with truffle, you need to older provider here: "truffle-hdwallet-provider" which response error too but no crash. =]]

**Comment by ditistijn** [comment]
Awesome. It's quite a few contracts and I'd love to use truffle for it so I will use the older provider for that. Deployment will still continue, even linking and deployment after that right?

**Comment by nhancv** [comment]
> Awesome. It's quite a few contracts and I'd love to use truffle for it so I will use the older provider for that. Deployment will still continue, even linking and deployment after that right?

yes, but one more thing I forgot to tell you that you can create new BSC mainnet api node at https://app.ankr.com/api. It's free. And replace to bscmainnet rpc in truffle config file. It should work without any error.

**Comment by ditistijn** [comment]
Thanks for the solution. I will just close the issue for now.
