### ISSUE TITLE
Truffle Ticket #521661: Unlock an account on archive fork

### ISSUE THREAD

**Issue by becomerare** [trufflesuite/truffle#4469]
I am trying to debug contracts with ganache-cli v6.12.2 (ganache-core: 2.13.2).

I've chosen (at random) this contract to debug: https://etherscan.io/address/0xb53A7255d1fBa335F759bbF963c8333a962e3148

I've forked an archive node with
`docker run trufflesuite/ganache-cli --fork <archive>@13596746 --secure --unlock "0xd938ffd144253d61ae7f26194e84fe9929de7b4b"
`
Where 13596746 is the block number before the contract was deployed by the creator.

Then, I try to "impersonate" the creator of the contract and deploy the contract with truffle migrate:

```
var TCAT_TO_VATOR = artifacts.require("TCAT_TO_VATOR");
module.exports = function(deployer) {
deployer.deploy(TCAT_TO_VATOR, {from: "0xd938ffd144253d61ae7f26194e84fe9929de7b4b"});
}
```

And I get this error **on both ganache v7 and ganache-cli stable**: sender account not recognized.
According to https://docs.nethereum.com/en/latest/ethereum-and-clients/ganache-cli/
I should be able to use --fork and --unlock to use the account without their private key.

**Steps to reproduce:**
1. Clone https://github.com/becomerare/sim
2. Add MORALIS_KEY to .env
3. Run "docker-compose down && docker-compose up --build"

I appreciate your help.

**Comment by fainashalts** [comment]
@becomerare thank you for bringing up this issue! We're going to dig further to figure out what might be going on. In the meantime, is there any chance you can check whether you have the same result using `@truffle/contract`? The code would look something like this:

```javascript
const instance = await MyContract.deployed() 
await instance.myFunction(..., {from:  ...});
```

**Comment by becomerare** [comment]
> 

This works.
