### ISSUE TITLE
win10 truffle error

### ISSUE THREAD

**Issue by acodercat** [trufflesuite/truffle#447]
In win10, after truffle init, enter truffle compile will open the current directory under the truffle.js file, because the win10 will automatically open the current directory and command the same file, conflict!!!!

**Comment by acodercat** [comment]
modify  \npm\node_modules\truffle\build\cli.bundled.js  line 1755 
```javascript
var DEFAULT_CONFIG_FILENAME = "truffle-config.js";
```
Modify the truffle.js file as truffle-config.js

**Comment by tcoulter** [comment]
Hi there. 

Renaming your `truffle.js` file to `truffle-config.js` should work without changing the underlying Truffle code. Give that a shot. Let us know if you have anymore issues.
