### ISSUE TITLE
Unable to install Truffle

### ISSUE THREAD

**Issue by varunponda** [trufflesuite/truffle#4470]
![1](https://user-images.githubusercontent.com/84200435/143667189-d2cb56e9-69b0-43b7-a0fa-3093f4557928.PNG)
![2](https://user-images.githubusercontent.com/84200435/143667197-55e551bd-cbb3-4169-92b3-0ea493129a71.PNG)
![3](https://user-images.githubusercontent.com/84200435/143667207-cb40cc30-959d-43d6-bc72-e482a90a709d.PNG)
(Please help me)
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`v16.13.0):
* node version (v8.1.4):
* npm version (`npm --version`):

**Comment by RobertoMSousa** [comment]
@varunponda , it seems that the package was installed.
Those are warnings with deprecated packages.
Cans you please run `truffle version` and and give back the result?

**Comment by fainashalts** [comment]
HI @varunponda, it does look like Truffle was installed, albeit with deprecation warnings. Can you confirm that this issue is resolved? Thanks so much!

**Comment by varunponda** [comment]
Hello, Yes truffles is installed, as I am a newbie I wasn't aware, But I
would like to Thank you for replying.

**Comment by eggplantzzz** [comment]
Thanks @varunponda! Closing this for issue maintenance.
