### ISSUE TITLE
Add detail log

### ISSUE THREAD

**Issue by wxy** [trufflesuite/truffle#4481]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue. （Ticket: 521615）

---------------------------

## Issue

I am using Truffle to deploy smart contracts to the main network. Unfortunately, I am experiencing a timeout issue during the deployment process. So, I would like to be able to add detailed logging so that errors can be troubleshot, or can be fixed manually to continue to completion.

## Steps to Reproduce

This happens when using slow links for deployment via Infura.

## Expected Behavior

Deployment success.

## Actual Results

The deployment was interrupted due to a timeout.

```
> confirmation number: 1 (block: 13651340)
> confirmation number: 2 (block: 13651341)

- Blocks: 0 Seconds: 0
- Saving migration to chain.
- Blocks: 0 Seconds: 0
- Blocks: 0 Seconds: 0
- Blocks: 0 Seconds: 0
- Saving migration to chain.

....../node_modules/request/request.js:816
var e = new Error('ESOCKETTIMEDOUT')
```

## Environment

* Operating System: MacOS
* Ethereum client: Truffle
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by fainashalts** [comment]
Hi @wxy thanks for bringing up this issue! We always want to provide more detailed logging where possible/appropriate. 

Can you clarify what "slow links for deployment via Infura" means? Do you mind also providing the information in the "Environment" section above?

I'm not sure what additional information we could add in logging here that would be helpful? What information would you have wanted to see here?

**Comment by wxy** [comment]
Thank you very much for your reply. This issue occurred when I deployed a smart contract through Infura. I'm in China, so connecting to Infura seems to be slow, especially when deploying contracts. I have no way to change to another network, and although I have increased the timeout parameters (`timeoutBlocks: 150` and `networkCheckTimeout: 999999`), it still times out after waiting for about 10 minutes, and the deployment is broken.

So after a deployment break, I don't know where the deployment is going and I can't fix it manually or continue. So I wanted to provide a detailed log so that I knew what was being done when the deployment was interrupted.

Of course, I later learned that I could modify it by adding some parameters to the Network file (cf. Rinkeby).

**Comment by kevinbluer** [comment]
Hey @wxy, thanks for all the additional detail! One thing you could try during the deployment is enabling Truffle's internal debug logging (note that this is something we use during development / troubleshooting)...example as follows:

```
DEBUG=“*” truffle migrate
```

Feel free to try it and see if it provides anything useful. If not, let us know and we look at other options.

**Comment by wxy** [comment]
@kevinbluer Thanks for your reply, I will try it later. 😃
