### ISSUE TITLE
Provides default configuration of the main network supporting EIP 1559

### ISSUE THREAD

**Issue by wxy** [trufflesuite/truffle#4482]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue. (Ticket: 521615)

---------------------------

## Issue

The default recommended configuration for mainnet is not provided in `truffle-config`, so it leads to misconfiguration.

I used the old style configuration parameter, gas/gasprice, which works fine for both the local development environment and the Rinkeby network. However, it now does not work on Mainnet with EIP 1559 support.

Using the gas/gasprice parameter, contract deployment can be done, but strange errors occur during console interactions, even for read-only function calls.

The only way to interact properly is to replace the parameters with maxFeePerGas/maxPriorityFeePerGas for Type 2 transactions.

So, I suggest to give the default mainnet configuration parameters in `truffle-config` , rather than just mentioning them in your online documentation.

Finally, one more suggestion: Due to the unstable gas state of the ethereum network, predefining a fixed amount of gas may cause network confirmation timeouts, so I suggest providing a fastest/most economical parameter so that Truffle can prioritize the fastest or most economical way to complete contracts when deploying them.

**Comment by fainashalts** [comment]
Hi @wxy just to clarify, you mean the default configuration in the `truffle-config.js` file that you get when you run `truffle init`, right? I think this is a great suggestion and we will add it to our backlog. This is also a great first issue, so feel free to jump in with a PR if you're interested or hoping this gets resolved sooner!

**Comment by wxy** [comment]
Thank you for your reply. I can indeed try to raise a PR rather than just a issue. I'll give it a try.
