### ISSUE TITLE
@truffle/fetch-and-compile should not require a @truffle/config object

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4485]
## Issue

The `fetchAndCompile` function accepts two arguments: an address and a TruffleConfig. The second argument **must** be a TruffleConfig because it relies heavily on that package's defined defaults for things like precedence order for which fetchers to use, supplying no defaults of its own.

This is fiddly. The interface here should be expanded to accept either the existing `config` object or a new options argument with the relevant parameters that are actually used in this flow. This alternate form should _strictly_ contain that which actually matters in this context (e.g. there's no need to allow configuring network name, network id, or anything about solc other than whether to use Docker – none of that "The `solc` option is an object of the form supplied to a `truffle-config.js` file's `compilers` configuration", I say! 🙌 )

**Comment by gnidan** [comment]
@haltman-at writes about the information that fetch-and-compile uses from the config:

> 1. `sourceFetchers` -- list of source fetchers to check, in what order; defaults as you know to `["etherscan", "sourcify"]`
> 2. `network_id` -- the network ID. of course as you know on an actual config this is a getter that returns `config.networks[config.network].network_id`
> 3. `etherscan`, `sourcify`, etc -- each fetcher name is taken as a config field w/options for that fetcher; currently only `etherscan` is currently used, it's where you can put your etherscan `apiKey` (of course you have noted that this sort of thing probably really belongs in user config rather than project config, but I don't think that's really relevant here and right now it's in project config)
> 4. `compilers.solc.docker` -- are you using docker for solc? (and possibly in the future a similar option might exist for `vyper`?? not clear how that'd work, like what the alternative would be)
> 5. (not checked deliberately by fetch-and-compile but I believe this accidentally has an effect... we should probably override this in fetch-and-compile to avoid issues, I should probably throw up a PR to fix this) it looks like `strict` gets passed through to compile-solidity and will cause errors on warnings (like I said, that's not deliberate and I should fix it)
>     
>     oh that one's probably meant to be an option rather than a config field though isn't it? so I guess actually I won't bother with that because people don't set that in the config (and it will not in fact make it through from the command-line options).

Thanks for this, @haltman-at!

**Comment by gnidan** [comment]
This being said, what about this:

```typescript
export interface FetchAndCompileOptions {
  network: {
    networkId: number;
  };
  fetch?: {
    sourceFetchers?: string[]; // eg. ["etherscan", "sourcify"]
    etherscan?: {
      apiKey?: string;
    };
    sourcify?: {
      /* empty for now */
    };
  };
  compile?: {
    docker?: boolean;
  }
}
```

**Comment by haltman-at** [comment]
Makes sense!  Note we have talked in the past about it possibly taking a provider for handling proxy contracts.  But I guess this could be expanded in the future with that?

The question to my mind is, how do we distinguish this from a config?  Or do we set it up so we don't need to?  (I guess the latter wouldn't be too difficult, although doing it in *Typescript* might be annoying.)

**Comment by gnidan** [comment]
> Note we have talked in the past about it possibly taking a provider for handling proxy contracts. But I guess this could be expanded in the future with that?

Yep, I left it out for now but figured we'd probably have to add it later.

> The question to my mind is, how do we distinguish this from a config? Or do we set it up so we don't need to? (I guess the latter wouldn't be too difficult, although doing it in _Typescript_ might be annoying.)

Right now, we only accept an actual TruffleConfig object, so maybe we can just go with the simple solution of doing an `instanceof` check! That way we don't need to do any sort of duck-typing matching :)

**Comment by haltman-at** [comment]
> Right now, we only accept an actual TruffleConfig object, so maybe we can just go with the simple solution of doing an `instanceof` check! That way we don't need to do any sort of duck-typing matching :)

Oh, I didn't even think of that!  Silly me... thanks!

**Comment by haltman-at** [comment]
Now done in #5054.
