### ISSUE TITLE
`fetchAndCompile()` should accept multiple addresses at a time.

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4486]
## Issue

@truffle/source-fetcher respects API request rate limits by introducing a delay between the requests it makes, keeping clock state on a per-invocation basis. @truffle/fetch-and-compile's `fetchAndCompile()` currently only provides a means of accepting one address at a time, and so it provides no means by which to take advantage of this underlying source-fetcher capability.

This effectively makes this package unsuitable for the use case of fetching-and-compiling in bulk. It's a real bummer cause sometimes transactions have lots of EVM logs from different addresses and you just want the compilations for all of them, like, y'know?

The interface for this function should be expanded to also accept lists of addresses, ideally including removing duplicates from lists of non-unique addresses, and the function should ensure that API request delays properly work between requests for addresses in that list.

**Comment by haltman-at** [comment]
Oh interesting, you want to overload the function?  I was assuming it would be a separate function.  I think that would make more sense so that you don't have to break the return type.

Note that much of what you're asking for would be automatically handled by `fetch.ts` so long as you can write an appropriate recognizer. :)

**Comment by gnidan** [comment]
Oh dang, you're right that it's hard to do this without breaking the interface. Maybe we should just do that now while the Codefi integration is fresh on everyone's mind. I'll ask internally if this is something they can be prepared to accommodate.

If we are okay with breaking the interface, then I think we should return what we have now but grouped by address in an object, as well as a convenient concatenation of all the `compilations` in a single array

**Comment by gnidan** [comment]
This is addressed and released in [Truffle v5.4.31](https://github.com/trufflesuite/truffle/releases/tag/v5.4.31).
