### ISSUE TITLE
git-clone-a1132401/.git: Permission denied after creating new keys and adding to settings in Git

### ISSUE THREAD

**Issue by abel1337** [trufflesuite/truffle#451]
---------------------------

## Issue

Im trying to install truffle and am running into a git issue not allowing me access
I created a new ssh key and added it to my settings in git
I ran it again and got the same error

## Steps to Reproduce

sudo npm install -g truffle

## Expected Behavior

Install truffle with no error

## Actual Results

```
fappycow@MikeG:~$ sudo npm install -g truffle
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/dignifiedquire/webcrypto-shim.git /home/fappycow/.npm/_cacache/tmp/git-clone-a1132401
npm ERR! /home/fappycow/.npm/_cacache/tmp/git-clone-a1132401/.git: Permission denied
```

## Environment

* Operating System: Linux Ubuntu 16.04
* Truffle version: won't install so Im not sure
* Ethereum client:
* node version: 6.11.0
* npm version: 5.0.3

**Comment by gokulkrishna01** [comment]
I'm also facing the above-mentioned issue in the same environment.

**Comment by gokulkrishna01** [comment]
@abel1337, maybe you can try following these steps which apparently fixed my problem:

```git clone https://github.com/ethereumjs/testrpc.git
cd testrpc
sudo npm install . ```

Source: https://ethereum.stackexchange.com/questions/16848/unknown-error-while-installing-testrpc-in-ubuntu

**Comment by abel1337** [comment]
Hey, thanks for the reply! When I do what you say gi clone seems to work, but when I do:

> cd test rpc

I get: 

> bash: cd: test: No such file or directory

**Comment by abel1337** [comment]
Thanks for the reply! Ok so when I do that and get to the last step, I get this error:
```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/debris/bignumber.js.git /home/fappycow/.npm/_cacache/tmp/git-clone-16fb1adc
npm ERR! /home/fappycow/.npm/_cacache/tmp/git-clone-16fb1adc/.git: Permission denied
npm ERR! 
```

**Comment by gokulkrishna01** [comment]
@abel1337 It seems you still have the git issue! Maybe you can contact the main guys!

**Comment by tcoulter** [comment]
Hi there. Please check out our two most recent blog posts. We've fixed most (if not all) installation issues for both Truffle and the TestRPC.

http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past
http://truffleframework.com/blog/removing-installation-issues-continued-testrpc

**Comment by abel1337** [comment]
Fixed!

**Comment by lucas7788** [comment]
@abel1337  how to solve your problem,I come across the same problem

**Comment by gslnzfq** [comment]
please run `sudo npm install webcrypto-shim -g` before execute `sudo npm install -g truffle`, it will help you.
