### ISSUE TITLE
Problems when using await in truffle test (but success with .then())

### ISSUE THREAD

**Issue by LIYANG-UST** [trufflesuite/truffle#4515]
## Issue

When I try to interact with my contract in the test file with await, it can not be fulfilled. 
However when I changed to use .then() I can run the test successfully.

I just test an ERC20 token's mint function. 

![image](https://user-images.githubusercontent.com/42539774/145371180-522473f0-4986-4eb6-9a08-066de42a942c.png)(degis is the contract instance initialized by .deployed())
(ether is my own function and it works well)

## Steps to Reproduce

truffle test <my-file> --network dev

## Expected Behavior

The test should pass.

## Actual Results

![image](https://user-images.githubusercontent.com/42539774/145370374-0bd134d8-cd7a-4005-b478-ce82ef6d9cf7.png)## Environment

* Operating System:  macOS 11.6
* Ethereum client: ganache-cli (7.0.0-beta1)
* Truffle version (`truffle version`): 5.4.23
* node version (`node --version`): 14.18.1
* npm version (`npm --version`): 8.1.0

**Comment by cds-amal** [comment]
Hi @LIYANG-UST , is it possible to share a repo with this problem so I can test it?

**Comment by haltman-at** [comment]
Closing this for issue maintenance, but let us know if there's still a problem and we can reopen this!
