### ISSUE TITLE
.DS_Store files cause 'truffle compile' to fail

### ISSUE THREAD

**Issue by StuartFarmer** [trufflesuite/truffle#452]
.DS_Store files automatically by MacOS file system cause truffle compile to fail with JSON parse at index 0 error.

Can be fixed with a recursive search bash script: find . -name ".DS_Store" -print0 | xargs -0 rm -rf

Should be added to 'truffle compile'.

**Comment by tcoulter** [comment]
CC #51

**Comment by gnidan** [comment]
Closing as duplicate
