### ISSUE TITLE
Internal issue: Most `resolverOptions` in resolver are now unnecessary and should be replaced by use of compiler info

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4521]
## Issue

Now that PRs #4420 and #4365 have been merged, the `translateJsonToSolidity` and `resolveVyperModules` resolver options are a redundant mechanism.

These options should be removed, and the checks that switch on them should instead look at the compiler version that was passed (`translateJsonToSolidity` should become, are we using Solidity, and `resolveVyperModules` should become, are we using Vyper).

Moreover, any code that passes these options in should changed back so that it no longer does so.

## Environment

* Truffle version (`truffle version`): 5.4.23

**Comment by leeftk** [comment]
This was resolved in the new release 5.4.27. Closing!
