### ISSUE TITLE
Installing truffle on Mac

### ISSUE THREAD

**Issue by lorepieri8** [trufflesuite/truffle#453]
---------------------------

## Issue

Not able to install Truffle on mac os 10.9

## Steps to Reproduce

npm install truffle -g

or

npm install truffle@3.2.1 -g
npm install truffle@3.2.2 -g

## Expected Behavior

Installation completed.

## Actual Results

npm install truffle -g
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/cli.js
/usr/local/bin/truffle-exec -> /usr/local/lib/node_modules/truffle/exec.js

> execSync@1.0.2 install /usr/local/lib/node_modules/truffle/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> fs-ext@0.6.0 install /usr/local/lib/node_modules/truffle/node_modules/fs-ext
> node-gyp configure build

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/lorenzo/anaconda/bin/python" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:195:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/truffle/node_modules/fs-ext
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> fsevents@1.1.2 install /usr/local/lib/node_modules/truffle/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/truffle/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> sha3@1.2.0 install /usr/local/lib/node_modules/truffle/node_modules/sha3
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/lorenzo/anaconda/bin/python" is v3.6.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:195:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/truffle/node_modules/sha3
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.6.0 (node_modules/truffle/node_modules/fs-ext):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-ext@0.6.0 install: `node-gyp configure build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "truffle" "-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sha3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lorenzo/npm-debug.log
npm ERR! code 1

## Environment

* Operating System: mac os 10.9
* Truffle version: latest and 3.2.1, 3.2.2
* node version: 6.11.10
* npm version: 3.10.10

I've tried even with:
* node version: 8.1.2
* npm version: 5.0.3

**Comment by tcoulter** [comment]
Hi there. Pleas read our recent [blog post](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). We've fixed these issues in `beta`. 
http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past

**Comment by lorepieri8** [comment]
Nice work devs! 
No errors, I did "truffle init" and I got the commands and the doc, so it seems working!

" And for most users, this sucks: getting hung up on installation is incredibly frustrating when you're usually just one error message or two away from creating your first Ethereum-enabled application. "

I totally agree!!!

PS: 
For me, even after "npm uninstall -g truffle", there were remnant of past installation, giving me this error:

```
$ npm install -g truffle@beta
npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "truffle@beta"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/bin/truffle
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/truffle: ../lib/node_modules/truffle/cli.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/truffle
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lorenzo/npm-debug.log
```

I solved by manually trashing some truffle files in the usr/bin folder.
