### ISSUE TITLE
Exceptions that @truffle/fetch-and-compile throws suppress underlying cause

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4538]
## Issue

@truffle/fetch-and-compile throws exceptions that are either "fetch" errors or "compile" errors, without providing detail about what the underlying failure condition was. This is problematic, and users of this package have asked for error information to be more detailed.

(See [relevant code](https://github.com/trufflesuite/truffle/blob/6d45d847cc1dc6d119becfc6b8e7ea69d7589754/packages/fetch-and-compile/lib/recognizer.ts#L47))

**Comment by haltman-at** [comment]
Assuming you just want this for `fetchAndCompile`, and not more detailed errors from the package as a whole ( :P ) I think this should be doable.
