### ISSUE TITLE
Feature Request: Having a "name" property attach to the contract instance

### ISSUE THREAD

**Issue by Janaka-Steph** [trufflesuite/truffle#455]
Hello,

I saw that we can get the name in `contract.constructor.contract_name`, so I am doing that
       
 contracts = deployedContracts.map((contract) => {
          name = contract.constructor.contract_name
          contract.name = name
          return contract
})

but it would be nice to have it out of the box.

**Comment by gnidan** [comment]
Is this a duplicate of #237? Is `name` something different than `contract_name`?

**Comment by eggplantzzz** [comment]
Closing this for maintenance, but please feel free to get back to us if you still want this. Thanks!
