### ISSUE TITLE
Truffle develop Error

### ISSUE THREAD

**Issue by younasm** [trufflesuite/truffle#4558]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I am using below version of Truffle
Truffle v5.4.17 (core: 5.4.17)
Solidity v0.5.16 (solc-js)
Node v16.13.0
Web3.js v1.5.3

## Steps to Reproduce

when I run 

`truffle develop`

it's giving me the following error message:

## Expected Behavior

I want to run the development environment

## Actual Results

Error: EACCES: permission denied, open '/Users/name/Library/Preferences/truffle-nodejs/config.json.tmp-0012602689412b3c'
    at openSync (node:fs:585:3)
    at attempt (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/atomically/dist/utils/retryify.js:33:1)
    at Object.writeFileSync (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/atomically/dist/index.js:136:1)
    at Conf._write (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/conf/dist/source/index.js:373:1)
    at Conf.set store [as store] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/conf/dist/source/index.js:295:1)
    at Conf.set (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/conf/dist/source/index.js:188:1)
    at Object.getOrGenerateMnemonic (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:27:1)
    at Object.getAccountsInfo (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:41:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/develop.js:64:44)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.17 (core: 5.4.17)
Node v16.13.0

## Environment

* Operating System:  Macbook Pro (M1 Pro Chip)
* Ethereum client: Ganache
* Truffle version (`5.4.17`):
* node version (`16.13.0`):
* npm version (`8.1.0`):

**Comment by lsqproduction** [comment]
Hello @younasm.
When installing Truffle, some users report receiving certain permissions errors if they used Sudo to install Truffle. 
Normally these can be resolved by using npm with a Node version manager like nvm. This is, in fact, what npm itself recommends. By using nvm, all of your globally installed npm packages get namespaced in a .nvm folder which helps to prevent permissions errors. See this [article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more information about installing and using npm with nvm.

**Comment by younasm** [comment]
i have installed with

`npm install -g truffle`

didn't use sudo and it was working before and also work with Ganache but when i want to run 

`truffle develop`

on terminal it show this error.

**Comment by ezeamaka2** [comment]
Are you on Windows or Mac??
Try downgrading node to version 12. This worked for me

**Comment by younasm** [comment]
I am on Mac. can you give some help how to downgrade to node 12 because currently I am using node 16.13.0

**Comment by ezeamaka2** [comment]
You can use nvm.... but, here is detailed guide on [how to downgrade node version](https://www.educative.io/edpresso/how-to-downgrade-node-version)

**Comment by younasm** [comment]
Ok thank you. I'll definitely try it and let you know.

**Comment by ezeamaka2** [comment]
Alright, I hope it works for you

**Comment by younasm** [comment]
I installed nvm and downgrade to node 14 but still can not run

`truffle develop `

**Comment by cds-amal** [comment]
@younasm can you try falling back to npm@6 (`npm -g install npm@6`)? There is a known issue with npm@7+

**Comment by younasm** [comment]
I did it too but still the same error...

**Comment by cds-amal** [comment]
@younasm can you try the steps suggested by [this thread](https://github.com/trufflesuite/truffle/issues/4431#issuecomment-969556553)?

**Comment by younasm** [comment]
I tried to use this command

`rm -rf ~/Library/Preferences/truffle-nodejs`

but it also give me this message

```
rm: /Users/name/Library/Preferences/truffle-nodejs/config.json: Permission denied
rm: /Users/name/Library/Preferences/truffle-nodejs/compilers/node_modules/soljson-v0.5.16+commit.9c3226ce.js: Permission denied
rm: /Users/name/Library/Preferences/truffle-nodejs/compilers/node_modules: Permission denied
rm: /Users/name/Library/Preferences/truffle-nodejs/compilers: Permission denied
rm: /Users/name/Library/Preferences/truffle-nodejs: Permission denied
```

when i run truffle version it shows the following versions.

```
Truffle v5.4.17 (core: 5.4.17)
Solidity v0.5.16 (solc-js)
Node v14.18.2
Web3.js v1.5.3
```

**Comment by cds-amal** [comment]
@younasm, you can try:
> sudo rm -rf ~/Library/Preferences/truffle-nodejs

That will give the command privileges to delete the folder.

**Comment by younasm** [comment]
thank you it worked for me just have to run this command

`sudo rm -rf ~/Library/Preferences/truffle-nodejs`
