### ISSUE TITLE
outputSelection does not work

### ISSUE THREAD

**Issue by ibaralf** [trufflesuite/truffle#4563]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Limiting the build JSON output by adding outputSelection in truffle-config does not work

## Steps to Reproduce

1) Add an outputSelection field in truffle-config.js
2) Compile your contract using $ truffle compile 
3) Check build JSON files

## Expected Behavior

Build JSON files should be limited to fields defined in outputSelection

## Actual Results

JSON build files are the same.

## Environment

* Operating System: 
  Mac OSX
* Ethereum client:
* Truffle version (`truffle version`):
  Truffle v5.4.16 (core: 5.4.16)
  Solidity - 0.6.12 (solc-js)
  Web3.js v1.5.3
* node version (`node --version`):
  Node v12.0.0
* npm version (`npm --version`): 
  6.9.0

**Comment by kevinweaver** [comment]
Hi @ibaralf, do you mind elaborating on your use-case? Currently, we do not support this because truffle components use all of the output that ends up in artifacts. We would need to determine if this is a capability we would want to add.  Thanks!

**Comment by eggplantzzz** [comment]
Closing for issue maintenance, if you want to elaborate more on your use-case then feel free to open a new issue or reply here. Thank you!
