### ISSUE TITLE
Internal issue: Inconsistent names for the build script

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4567]
## Issue

In most packages the command to build is `yarn build`, but in some instead it's `yarn compile` or `yarn prepare`.  We should make these consistent.

## Environment

* Truffle version (`truffle version`): 5.4.25

**Comment by lsqproduction** [comment]
do we want to stick with just `yarn build`? Was there a reason for when we used `compile` and `prepare`?

**Comment by kevinweaver** [comment]
Let's stick with `build` and make sure `prepare` steps are defined everywhere.

**Comment by gnidan** [comment]
This has been addressed in [Truffle v5.4.28](https://github.com/trufflesuite/truffle/releases/tag/v5.4.28). Closing!
