### ISSUE TITLE
Problem with the truffle compile command

### ISSUE THREAD

**Issue by galileo680** [trufflesuite/truffle#4575]
I have an issue with truffle compile command, when i run it the build folder is created but it is empty, there is no abi/bytecode inside. I tried to reinstall truffle but it doesnt help. In the terminal i can only see "Everything is up to date, there is nothing to compile"

**Comment by cds-amal** [comment]
Is it possible the [contracts_build_directory](https://trufflesuite.com/docs/truffle/reference/configuration.html#contracts_build_directory) in `truffle-config.js` defines a different location than `./build`?

**Comment by galileo680** [comment]
there is no  contracts_build_directory in my "truffle-config.js". The "build/contracts is created but it is empty inside.

**Comment by cds-amal** [comment]
Can you share your repo so I can better understand the problem?

**Comment by galileo680** [comment]
https://github.com/galileo680/eth-todo-list

**Comment by cds-amal** [comment]
When I ran `truffle compile` it both [compiled and stored artifacts in the build folder](https://asciinema.org/a/mlywSiOkTHOkTuBI72kqHetXI). 

Can you include your environment details?
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by galileo680** [comment]
Operating System: w10
Truffle version:  v5.4.26
node version: v16.13.1
npm version: 8.1.2
I tried to use also diffrent versions of node and truffle but without success.

**Comment by galileo680** [comment]
I think that truffle dont see my contratcs but dont know why

**Comment by cds-amal** [comment]
Oh dear! This is a long shot, but could you try falling back to `npm v6` (`npm -g install npm@6`)?

I don't have access to a windows 10 machine to debug this right now but will look into it next week. I did however try it on a windows 11 Pro which worked. 
<img width="886" alt="Screen Shot 2021-12-30 at 6 26 20 PM" src="https://user-images.githubusercontent.com/2529600/147794267-aea16529-f416-45ca-8e02-e2057db76db4.png">

```
Windows 11 Pro
C:\Users\amal\dev\eth-todo-list>truffle version
Truffle v5.4.26 (core: 5.4.26)
Solidity - ^0.5.0 (solc-js)
Node v16.13.1
Web3.js v1.5.3

C:\Users\amal\dev\eth-todo-list>npm --version
6.14.15
```

**Comment by galileo680** [comment]
I tried to compile this on my ubuntu virtual machine and everything works fine XD So there is something messed up with my windows set up.  I will try to update my windows to 11.

**Comment by galileo680** [comment]
thanks for your help <3

**Comment by kevinweaver** [comment]
Hi @galileo680 glad you were able to resolve your issue! Closing this out, feel free to open a new issue if you need help in the future.
