### ISSUE TITLE
CompilerError while using brownie followed by various TypeErrors

### ISSUE THREAD

**Issue by zakimzf** [trufflesuite/truffle#4577]
I tried compiling olympus-dao contracts using brownie framework it results in a Compiler error followed by a string of type errors :

![photo5940274988726728728](https://user-images.githubusercontent.com/67141555/147798339-7ff57ae5-2818-4eb9-b8cd-45a837b91bf1.jpg)
Here is the repo: https://github.com/AgentFUD/olympusdao-port-to-brownie this is the main branch which works fine!
There exists another branch in this repo named math-libraries-update , here it fails to compile and produces the above mentioned  error!
How do i fix this  @cds-amal 
ubuntu 20.0
compiler 0.8.9
brownie 1.17.2

**Comment by cds-amal** [comment]
Hi @zakimzf , This isn't a truffle issue. I see you've already asked on the [Brownie page](https://github.com/eth-brownie/brownie/issues/1390) so I'm going to close this. Good luck!
