### ISSUE TITLE
Npm install truffle tries to retrieve information from a .git that either moved or doesn't exist

### ISSUE THREAD

**Issue by Niknakflak** [trufflesuite/truffle#458]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

npmc install -g truffle is trying to retrieve information from a git repository that has moved or doesn't exist.
https://file.house/hIZf.png
![image](https://user-images.githubusercontent.com/5169683/27503872-bb40a538-5835-11e7-9e56-51a61bbfa9dc.png)

I tried this with both npm and npmc and neither worked.  This is on windows and I had no issues getting truffle to install on linux but for other reasons involving me messing up my npm installation on linux, I switched to windows and encountered this problem as well.

## Steps to Reproduce

1. Be on windows OS (I specifically was using 8.1)
2. npm install -g truffle
3. crash error

## Expected Behavior

truffle to install

## Actual Results

See above, it error'd out for the above reason, let me know if you need the log.

## Environment

* Operating System:  windows 8.1
* Truffle version: none, error during installation
* Ethereum client: None
* node version: 8.1.2
* npm version: 5.0.3 and 5.0.4 (canary)

**Comment by adonley** [comment]
Can confirm I'm having this issue on OS X as well:
`4145 silly fetchPackageMetaData error for bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2 exited with error code: 128
4146 verbose stack Error: exited with error code: 128
4146 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
4146 verbose stack     at emitTwo (events.js:125:13)
4146 verbose stack     at ChildProcess.emit (events.js:213:7)
4146 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
4147 verbose cwd /Users/andrew/Programs/kingsleykoin
4148 verbose Darwin 16.6.0
4149 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
4150 verbose node v8.1.0
4151 verbose npm  v5.0.3
4152 error exited with error code: 128
4153 verbose exit [ 1, true ]`

**Comment by dylanseago** [comment]
Issue is with an ethereum/web3 dependency, see https://github.com/ethereum/web3.js/issues/904

**Comment by Niknakflak** [comment]
oh ok, closing this then as it is not a truffle issue.
