### ISSUE TITLE
Allow for migrations to support TypeScript

### ISSUE THREAD

**Issue by martinmunillas** [trufflesuite/truffle#4587]
- [ ] I didn't [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue, because is a technical issue.

---------------------------

## Issue

The way the require package works is making impossible to me to get truffle migrations working with typescript without having to compile. if you go to the require package at `require.js` the way Require.file method(lines 19 to 99) work, makes it imposible to use ts-node to run typescript in place, if it was just a regular require it would be so easy to use typescript, i would be glad to improve this i just wanted to know why is it done like that, why do you need to do al that stuff in order to require the package?

## Expected Behavior

If i use ts-node to run truffle migrate, i should be able to run typescript migrations

## Actual Results

As typescript files are not actually being required as regular modules, ts-node/register cannot work properly therefore syntax errors comes up
<img width="646" alt="Screen Shot 2022-01-04 at 19 02 48" src="https://user-images.githubusercontent.com/65319051/148129919-3ca82424-4139-4a55-bc69-193d1087f7fb.png">

## Environment

* Operating System: MacOS
* Ethereum client: Ganache
* Truffle version (`5.4.26`):
* node version (`16.10.0`):
* yarn version (`1.22.17`):

**Comment by martinmunillas** [comment]
is all that stuff you are doing in the require package to inject the artifacts? if so i have a better idea to make it typescript compatible

**Comment by kevinweaver** [comment]
Truffle does not support writing your migrations with typescript, though it's something we'd like to support in the future. When we do implement this, we will want to do it in a way that doesn't require the user to invoke`ts-node`, which might be a substantial change.

**Comment by martinmunillas** [comment]
how can i start contributing to that?

**Comment by cds-amal** [comment]
I changed this to new issues to give it an appropriate status update, as well as link it to work that @benjamincburns is doing.

**Comment by benjamincburns** [comment]
This ticket seems to duplicate #3467, so I'm going to close it in favour of that one. I'll do my best to capture any details here that aren't already covered by that issue.

By way of status report, #5222 was merged last week, and it will go out with the next Truffle release. That PR contains the core changes necessary to support TypeScript migrations, but I'd consider this as being an initial "beta" feature. We are still working on fleshing out the other details of the feature, including docs (trufflesuite/trufflesuite.com#1276), VSCode integration (#5368) and initial TypeScript migrations when running `truffle init` (#5369), etc.
