### ISSUE TITLE
On windows 10  "truffle test" Compilation failed.

### ISSUE THREAD

**Issue by oluwafemi08** [trufflesuite/truffle#4589]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Source "truffle/Assert.sol" not found: File import callback not supported
Source "truffle/DeployedAddresses.sol" not found: File import callback not supported

"truffle test" returns Compilation failed

## Steps to Reproduce

create a smart contract
create a test for the smart contract, import the two global truffle files and the smart contract file 

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Background.sol";

Write a function that test the smart contract, pass the actual value, the expected value and a failure message (which gets printed to the console if the test does not pass) to Assert.equal()

## Expected Behavior
 all tests should pass

## Actual Results

$ truffle test
Using network 'test'.

Compiling your contracts...
===========================
> Compiling .\contracts\Background.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\test\TestBackground.sol
> Compiling truffle\Assert.sol
> Compiling truffle\AssertAddress.sol
> Compiling truffle\AssertAddressArray.sol
> Compiling truffle\AssertBalance.sol
> Compiling truffle\AssertBool.sol
> Compiling truffle\AssertBytes32.sol
> Compiling truffle\AssertBytes32Array.sol
> Compiling truffle\AssertGeneral.sol
> Compiling truffle\AssertInt.sol
> Compiling truffle\AssertIntArray.sol
> Compiling truffle\AssertString.sol
> Compiling truffle\AssertUint.sol
> Compiling truffle\AssertUintArray.sol
> Compiling truffle\DeployedAddresses.sol

TypeError: Member "equal" not found or not visible after argument-dependent lookup in type(library Assert).
  --> project:/test/TestBackground.sol:30:9:
   |
30 |         Assert.equal(
   |         ^^^^^^^^^^^^

Compilation failed. See above.
Truffle v5.4.26 (core: 5.4.26)
Node v12.17.0

## Environment

* Operating System: Windows 10
* Truffle version v5.4.26;
* node version v12.17.0:

**Comment by lsqproduction** [comment]
Hi, @oluwafemi08 Thank you for opening the issue. 
Can you please help to share a sample project with the necessary code to reproduce the errors mentioned above?

**Comment by oluwafemi08** [comment]
pragma solidity ^0.8.10;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Background.sol";


contract TestBackground {

    Background public background;

    // Run before every test function
    function beforeEach() public {
        background = new Background();
    }

    // Test that it stores a value correctly
    function testItStoresAValue() public {
        uint value = 5;
        background.storeValue(value);
        uint result = background.getValue(0);
        Assert.equal(result, value, "It should store the correct value");
    }
}

**Comment by lsqproduction** [comment]
Thank you for sharing that, @oluwafemi08 
If truffle was installed using `npm install -g truffle `, there's no need to import anything extra. 
There are some examples [here](https://trufflesuite.com/docs/truffle/testing/writing-tests-in-javascript.html) that show how  `assert.equal()` can be used in Truffle test.

**Comment by kevinweaver** [comment]
Hi @oluwafemi08, thank you for the code snippet!  Where in your truffle project does this code live? If you have a repo link, that would also be helpful.

**Comment by eggplantzzz** [comment]
Closing for issue maintenance!
