### ISSUE TITLE
unable to install Truffle Webpack

### ISSUE THREAD

**Issue by FugueWeb** [trufflesuite/truffle#459]
## Issue

Not sure how actively Truffle Webpack starter is being maintained, but as it is referenced in the [Truffle docs](http://truffleframework.com/docs/getting_started/project) (and there is no issues tab available in the truffle-init-webpack repo) I thought I would post this here. I'm unable to successfully install or `truffle compile` the Webpack version of Truffle.

## Steps to Reproduce

`truffle init webpack`

## Actual Results

`Downloading project...
Installing dependencies...
Error: Command failed: npm install babel-cli@^6.22.2 babel-core@^6.22.1 babel-eslint@^6.1.2 babel-loader@^6.2.10 babel-plugin-transform-runtime@^6.22.0 babel-preset-env@^1.1.8 babel-preset-es2015@^6.22.0 babel-register@^6.22.0 copy-webpack-plugin@^4.0.1 css-loader@^0.26.1 eslint@^3.14.0 eslint-config-standard@^6.0.0 eslint-plugin-babel@^4.0.0 eslint-plugin-mocha@^4.8.0 eslint-plugin-promise@^3.0.0 eslint-plugin-standard@^2.0.0 html-webpack-plugin@^2.28.0 json-loader@^0.5.4 style-loader@^0.13.1 truffle-contract@^1.1.6 web3@^0.18.2 webpack@^2.2.1 webpack-dev-server@^2.3.0`

Note, installing Babel globally is specifically not encouraged in the Babel docs. 

There also seems to no longer be a git file/repo for `bignumber.js`. I get this `bignumber` error also when trying to install `truffle-default-builder`.

`npm ERR! git fetch -a origin (https://github.com/debris/bignumber.js.git) remote: Repository not found.
npm ERR! git fetch -a origin (https://github.com/debris/bignumber.js.git) fatal: repository 'https://github.com/debris/bignumber.js.git/' not found`

## Environment

Truffle 3.2.8
Darwin 16.6.0
node v6.11.0
npm  v3.10.10

**Comment by FugueWeb** [comment]
https://github.com/npm/npm/issues/17413

Seems to be related to this issue

**Comment by kahwooi** [comment]
I am having the same problem.

**Comment by beaini** [comment]
As a workaround, move to beta:
`npm install -g truffle@beta`

**Comment by kahwooi** [comment]
@beaini yes, I am using truffle@beta

**Comment by tsouza** [comment]
I can install with `npm install -g truffle@beta` but yet `truffle init webpack` fails with same issue

**Comment by porfavorite** [comment]
The same problem here. Installed truffle@beta, didn't help. testrpc doesn't install as well, but testrpc@beta worked well. How long do we need to wait for the fix?

**Comment by dylanseago** [comment]
I was able to get mine installed locally.

Here are the changes I made to fix all the broken dependencies, in the order they need to be applied:
- https://github.com/ethereumjs/testrpc/pull/334
- https://github.com/raineorshine/solidity-sha3/pull/6
- https://github.com/trufflesuite/truffle-blockchain-utils/pull/4
- https://github.com/trufflesuite/truffle-provider/pull/3
- https://github.com/trufflesuite/truffle-contract/pull/32
- https://github.com/trufflesuite/truffle-artifactor/pull/53
- https://github.com/trufflesuite/ethpm-registry/pull/2
- https://github.com/trufflesuite/truffle-config/pull/3
- https://github.com/trufflesuite/truffle-init/pull/6
- https://github.com/trufflesuite/truffle-deployer/pull/3
- https://github.com/trufflesuite/truffle-require/pull/5
- https://github.com/trufflesuite/truffle-migrate/pull/2
- https://github.com/trufflesuite/truffle-compile/pull/12

I used `npm link` to hook up the dependency fixes locally and was able to successfully install [this](https://github.com/dylanseago/truffle/tree/web3-fix) patched version of truffle 3.2.5. But I ran into a bug in npm (https://github.com/npm/npm/issues/10343) which blocked me from properly testing the fix.

**Comment by tcoulter** [comment]
Closing as duplicate. Using trufflesuite/truffle#485 to track. Thanks!
