### ISSUE TITLE
Can't compile solc version "^0.8.10"

### ISSUE THREAD

**Issue by agupta1979** [trufflesuite/truffle#4597]
## Issue

Unable to make truffle compile a contract that wants to use 0.8.x .
Have installed truffle just now and it still gets Solidity 0.5.16 as its default version.

## Steps to Reproduce

I tried to do this on a clean machine.
I have setup a Ubuntu 20.04 on VM in VirtualBox and installed following software

1. Node and NPM - Followed the guidelines on nodejs.org website to install the latest LTS version as of 06-Jan-2022
2. truffle - `npm install -g truffle`
this didnt work so I had to use sudo 
              ` sudo npm install -g truffle`

After installation, if I check truffle version, I see it gives 0.5.16 as default..
```
trainer@trainer:~$ truffle version
Truffle v5.4.26 (core: 5.4.26)
Solidity v0.5.16 (solc-js)
Node v16.13.1
Web3.js v1.5.3
```

Question 1 - Why is it not getting the latest solidity?  Anyway,
3. I created a empty project called samples under mycode folder, using truffle init 
```
trainer@trainer:~/mycode/sample$ truffle version
Truffle v5.4.26 (core: 5.4.26)
Solidity - 0.8.10 (solc-js)
Node v16.13.1
Web3.js v1.5.3
```

Ofcourse I know that it is showing 0.8.10 as it is just getting this value from truffleconfig.js 
```
 // Configure your compilers
  compilers: {
    solc: {
      version: "0.8.10",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
```

d. But I am not able to actually compile the contract that uses 0.8.10

```
pragma solidity ^0.8.10;

contract Migrations {
```

```
trainer@trainer:~/mycode/sample$ truffle compile

Compiling your contracts...
===========================
✖ Fetching solc version list from solc-bin. Attempt #1
✖ Fetching solc version list from solc-bin. Attempt #2
✔ Fetching solc version list from solc-bin. Attempt #3
Error: Could not find a compiler version matching 0.8.10. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.
    at VersionRange.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:173:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:5:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.26 (core: 5.4.26)
Node v16.13.1
```

e. I installed Ganache and then did truffle compile --list 
trainer@trainer:~/mycode/sample$ truffle compile --list
✖ Fetching solc version list from solc-bin. Attempt #1
✖ Fetching solc version list from solc-bin. Attempt #2
✔ Fetching solc version list from solc-bin. Attempt #3
[
 "0.7.1",
 "0.7.0",
 "0.6.12",
 "0.6.11",
 "0.6.10",
 "0.6.9",
 "0.6.8",
 "0.6.7",
 "0.6.6",
 "0.6.5"

It is not showing any solidity from 0.8.x

## Expected Behavior
Latest truffle should get the latest version of solidity, and or, should be able to download it when requested as per truffleconfig.js

## Environment

* Operating System:  Ubuntu 20.04 LTS installed on VirtualBox 6.1
* Truffle version (`truffle version`): v5.4.26
* node version (`node --version`):v16.13.1
* npm version (`npm --version`): 8.1.2

**Comment by agupta1979** [comment]
I also tried installing truffle without sudo, following https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md
It worked.
And still, it shows solidity as 0.5.16 and in the truffle compile --list, it shows the same list as before (that is, without any 0.8.x versions)

**Comment by agupta1979** [comment]
I installed truffle on my windows machine..still solidity 0.5.16  !!
C:\WINDOWS\system32>truffle version
Truffle v5.4.27 (core: 5.4.27)
Solidity v0.5.16 (solc-js)
Node v14.17.1
Web3.js v1.5.3

**Comment by agupta1979** [comment]
I read somewhere that if truffle does not have a particular solidity version, it will download it.  But it is not doing in my case
![image](https://user-images.githubusercontent.com/45432076/148568663-c8392448-4183-4c95-999e-6cdfd65399ae.png)

I know that truffle compile --list is not returning 0.8.x.....what do I need to do to push it to have 0.8.x

**Comment by agupta1979** [comment]
Following https://ethereum.stackexchange.com/questions/17551/how-to-upgrade-solidity-compiler-in-truffle/47244, I tried installing Solidity 0.8.10 manually

![image](https://user-images.githubusercontent.com/45432076/148569913-bfdf1f23-806e-484d-ac69-3a56382aac3a.png)

Seems the installation worked.  But when I tried compiling it still gives same error.
![image](https://user-images.githubusercontent.com/45432076/148570202-bf9a2ee5-657c-445e-a60d-fb029c98c794.png)

**Comment by agupta1979** [comment]
I noticed that when installing Solidity 0.8.10, it was complaining about node version.  I did a reinstallation from scratch
Installed 
Node v16.13.1
npm 8.1.2
Truffle - 5.4.27

Then I tried installing Solidity 0.8.10
This time it failed with a different error.
![image](https://user-images.githubusercontent.com/45432076/148576485-2fec8723-5864-49c1-a514-c3e7fd0ed94b.png)

**Comment by agupta1979** [comment]
Read https://github.com/trufflesuite/truffle/issues/1711 where users mentioned that their network not connecting to particular site...
Even I am on a machine which is restricting access to 
https://solc-bin.ethereum.org/bin/list.json

Could this be the reason.
There is a fix suggested in https://github.com/trufflesuite/truffle/issues/1721.
Unfortunately, I could not find the said lines in node_modules/truffle/build/cli.bundled.js.  Maybe in the newer truffle, those hardcoded lines are not there.

So my simple question is this
1. How we can manually install 0.8.x in such a way that truffle recognizes it.
I dont want to take help of npm or any such tool...cant I simply put the compiler file somewhere.

2. I know that truffle tries to download the compiler version that is mentioned in the truffle-config.js.  As it is not working for me due to the restriction on my computer, is there any way around it.

**Comment by agupta1979** [comment]
Issue with the machine only.  Somehow my network security is restricting getting the latest Solidity version.  Tried on another computer and it downloaded the latest Solidity versions once truffle compile was run.

**Comment by jacksonwalker165** [comment]
i am having the same problem, please someone should help me out

**Comment by jacksonwalker165** [comment]
i am having the same exact issues 


PS C:\Users\HP> truffle compile --list
Could not find suitable configuration file.
Truffle v5.4.26 (core: 5.4.26)
Node v16.13.1

**Comment by CruzMolina** [comment]
In case anyone else is still running into this issue, [this](https://github.com/trufflesuite/truffle/issues/4431#issuecomment-1108053572) might help.
