### ISSUE TITLE
installation fails with error code: 128

### ISSUE THREAD

**Issue by mkno** [trufflesuite/truffle#461]
running npm -g install embark on node 8.1.2, ubuntu 16.04

Here's a dump of the error log, the last dozen of lines:

> 462 silly resolveWithNewModule spdx-correct@1.0.2 checking installable status
> 463 silly pacote range manifest for spdx-expression-parse@~1.0.0 fetched in 14ms
> 464 silly resolveWithNewModule spdx-expression-parse@1.0.4 checking installable status
> 465 http fetch GET 200 https://registry.npmjs.org/spdx-license-ids 4ms (from cache)
> 466 silly pacote range manifest for spdx-license-ids@^1.0.2 fetched in 6ms
> 467 silly resolveWithNewModule spdx-license-ids@1.2.2 checking installable status
> 468 http fetch GET 200 https://registry.npmjs.org/camelcase 4ms (from cache)
> 469 silly pacote range manifest for camelcase@^3.0.0 fetched in 6ms
> 470 silly resolveWithNewModule camelcase@3.0.0 checking installable status
> 471 http fetch GET 200 https://registry.npmjs.org/utf8 44ms (from cache)
> 472 http fetch GET 200 https://registry.npmjs.org/xmlhttprequest 43ms (from cache)
> 473 silly pacote range manifest for utf8@^2.1.1 fetched in 49ms
> 474 silly resolveWithNewModule utf8@2.1.2 checking installable status
> 475 silly pacote range manifest for xmlhttprequest@* fetched in 49ms
> 476 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
> 477 http fetch GET 200 https://registry.npmjs.org/xhr2 52ms
> 478 silly pacote range manifest for xhr2@* fetched in 55ms
> 479 silly resolveWithNewModule xhr2@0.1.4 checking installable status
> 480 http fetch GET 304 https://registry.npmjs.org/crypto-js 64ms (from cache)
> 481 silly pacote range manifest for crypto-js@^3.1.4 fetched in 66ms
> 482 silly resolveWithNewModule crypto-js@3.1.8 checking installable status
> 483 silly fetchPackageMetaData error for bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b$
> 484 verbose stack Error: exited with error code: 128
> 484 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/in$
> 484 verbose stack     at emitTwo (events.js:125:13)
> 484 verbose stack     at ChildProcess.emit (events.js:213:7)
> 484 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
> 485 verbose cwd /home/bc
> 486 verbose Linux 4.4.0-81-generic
> 487 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "embark"
> 488 verbose node v8.1.2
> 489 verbose npm  v5.0.3
> 490 error exited with error code: 128
> 491 verbose exit [ 1, true ]

**Comment by acrylix** [comment]
experiencing similar issue with bignumber.js

can we please have https://github.com/debris/bignumber.js.git back up? or use another dependency? seems like this repo is either changed to private or completely removed, which causes many things like testrpc and truffle-contract to fail to install

**Comment by zzzmanzzz** [comment]
you can try sudo npm install -g truffle@beta
it works for me on ubuntu 16.04LTS

**Comment by mik1893** [comment]
iti does install truffle but still when running 
truffle init webpack
you get the errors back

**Comment by mkno** [comment]
it just stays like this forever: 

Downloading project...
Installing dependencies...

**Comment by tcoulter** [comment]
I'm going to close this. The bignumber issue should be fixed. Also, please direct embark installation issues to the [embark-framework](https://github.com/iurimatias/embark-framework) repo. Thanks!
