### ISSUE TITLE
truffle is completely broken?

### ISSUE THREAD

**Issue by CaledoniaProject** [trufflesuite/truffle#4625]
## Issue

Hi there, where is truffle downloading the solc? It always fail on a good network. 
How can I output more debugging info? At least `truffle help test` does not show anything related.

```
Compiling your contracts...
===========================
✖ Fetching solc version list from solc-bin. Attempt #1
✖ Fetching solc version list from solc-bin. Attempt #2
✖ Fetching solc version list from solc-bin. Attempt #3
✖ Fetching solc version list from solc-bin. Attempt #1
✖ Fetching solc version list from solc-bin. Attempt #2
✖ Fetching solc version list from solc-bin. Attempt #3
> Everything is up to date, there is nothing to compile.
```

## Environment

* Truffle version (`truffle version`): v5.4.29
* node version (`node --version`): v14.18.3
* npm version (`npm --version`): 6.14.15

**Comment by CaledoniaProject** [comment]
Hi @eggplantzzz,

1. I believe the 503 error does not have anything to do with my internet. The server is broken somehow, please check the error logs
2. How can I modify the node modules to output more information? I want to know why it fails, connection reset, server error etc.

**Comment by cds-amal** [comment]
@CaledoniaProject you can enable the DEBUG environment variable from the command line, for example `DEBUG=* truffle compile`

**Comment by CaledoniaProject** [comment]
1. If I do `export http_proxy=XXX; export https_proxy=XXX`, it fails: [output.txt](https://github.com/trufflesuite/truffle/files/7897650/output.txt)
2. If I launch truffle with proxychains directly, it works fine

**Comment by kevinweaver** [comment]
Hi @CaledoniaProject, were you able to access this link? 

https://solc-bin.ethereum.org/bin/soljson-v0.5.4+commit.9549d8ff.js

**Comment by CaledoniaProject** [comment]
@kevinweaver I can access it with curl, with or without a proxy

![screenshot 2022-01-20 at 7 21 45 AM](https://user-images.githubusercontent.com/1357701/150235041-0bbbb9b3-08d9-411c-915e-def9786e526b.jpg)

**Comment by eggplantzzz** [comment]
So you are able to access that site and I have no problem accessing it, so I don't know why you got a 503...maybe it went down for a bit?

So what exactly happens regularly with this? It seems like the behavior changed for you.

Like @cds-amal said, enable the `DEBUG` environment variable and maybe you will get some more info that could help. Do `DEBUG="*" truffle compile`.

**Comment by eggplantzzz** [comment]
Closing for issue maintenance!
