### ISSUE TITLE
Mocha reporters defined in truffle.config no longer used by default (v5.4.25)

### ISSUE THREAD

**Issue by cgewecke** [trufflesuite/truffle#4627]
## Issue

Hello! I help maintain [eth-gas-reporter][1]. 

Am [cross-posting recent issues opened there][2] that v5.4.25 has changed expectations about how truffle loads 3rd party mocha reporters. 

Prior to that version, when someone defined a reporter in truffle.config.js's mocha options it was used by default.

With 5.4.25, the `--reporter` cli flag is the only way to select a reporter other than `spec`. 

A workaround for eth-gas-reporter users is to use the cli flag:
```
truffle test --reporter eth-gas-reporter
```

[1]: https://github.com/cgewecke/eth-gas-reporter
[2]: https://github.com/cgewecke/eth-gas-reporter/issues/268

## Steps to Reproduce
+ truffle unbox metacoin
+ yarn add eth-gas-reporter
+ configure `truffle.config.js` with:
  ```js 
  mocha: {
    reporter: "eth-gas-reporter"
  }
  ```
+ run `truffle test`

## Expected Behavior

There should be a table with gas readings for each deployment and method invocation at the end of the suite

## Actual Results

No table

## Environment

* Operating System: Mac OSX
* Ethereum client: ganache-cli latest
* Truffle version (`5.4.25`):
* node version (`14`):

**Comment by giuseppeg** [comment]
@cgewecke thank you, you saved my day. I have been trying to figure out why the reporter wouldn't work for a while.

**Comment by eggplantzzz** [comment]
Oh no, sorry for breaking this functionality. We'll try and get a fix out for this!

**Comment by haltman-at** [comment]
This should be fixed now!
