### ISSUE TITLE
Migrations ran out of gas (using a value you set in your network config or deployment parameters.)

### ISSUE THREAD

**Issue by hokugava** [trufflesuite/truffle#4631]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I can't deploy contracts to ropsten. I tried to set multiple different values for gas/gasPrice in my truffle-config.js but always getting that error. Also I tried to change infura connection type (wss/https). And finally I have no idea whats going wrong.

My truffle-config.js

```
ropsten: {
      provider: () => new HDWalletProvider(privateKeys, "https://ropsten.infura.io/v3/INFURA_PROJECT_KEY",addressIndex, pollingInterval),
      network_id: 3,
      gas: 7900000,
      gasPrice: '20000000000',
      websocket: false,
      confirmations: 2,
      timeoutBlocks: 50000,
      skipDryRun: false,
      networkCheckTimeout: 1000000
    }
```

## Expected Behavior

Deploy succeeds.

## Actual Results

Error:  *** Deployment Failed ***

"Migrations" ran out of gas (using a value you set in your network config or deployment parameters.)
   * Block limit:  8000000 (0x7a1200)
   * Gas sent:     7900000 (0x788b60)

## Environment

* Operating System:  Windows 10
* Truffle version (`truffle version`): 5.4.29
* node version (`node --version`): 16.13.2
* npm version (`npm --version`): 8.3.0

**Comment by kevinweaver** [comment]
Hi @hokugava, thanks for opening this!  You should be able to remove both `gas` and `gasPrice` from your truffle-config.js file.  Truffle will determine these values for you.  Please let us know once you've tried this.  Thanks!

**Comment by hokugava** [comment]
I did it. And got this error

```
Error:  *** Deployment Failed ***

"Migrations" -- Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!.
```

But I already increased `pollingInterval` to 8000.

**Comment by eggplantzzz** [comment]
Can you provide us with a demo repo so that we can try to reproduce your error? You should, of course, omit secret stuff like mnemonic and private keys.

**Comment by hokugava** [comment]
I managed to deploy contracts in rinkeby. But I will still try to implement a deploy in ropsten later. I think I just need to expose a very large `gasPrice`. And unfortunately I can not share the repository.

**Comment by eggplantzzz** [comment]
Maybe you just tried to deploy at a time when something weird was going on with the Node? You should be able to just omit the gas params and Truffle will calculate them for you.

**Comment by hokugava** [comment]
Maybe. Anyway everything is okay for now. Thanks 🙏
