### ISSUE TITLE
can't require anything in migrations' folder

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#464]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce
add 
`var web3 = require('web3');`
into `2_deploy_contracts.js` file
Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior
web3 should be looked up in `node_modules` folder
What you expected to happen.

## Actual Results
cannot find module

```
 e.code = 'MODULE_NOT_FOUND'; throw e; }());
Error: Cannot find module "."
```

## Environment

* Operating System:  OSX
Truffle v3.2.8, bundle version: 3.2.93
Solidity v0.4.11 (solc-js)
* Ethereum client: testrpc
* node version: v7.10.0
* npm version: 4.2.0

**Comment by tcoulter** [comment]
This should be fixed with Truffle 3.4.3. Thanks!
