### ISSUE TITLE
@truffle/fetch-and-compile provides no interface for reporting supported networks

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4643]
## Issue

How does one know what networks are supported? You can't! Would be nice to remedy this.

## Steps to Reproduce

1. Read @truffle/fetch-and-compile's interface
2. Look for a way to determine supported networks
3. Observe this doesn't exist

## Expected Behavior

I'd expect some kind of interface for listing supported networks.

## Actual Results

There exists no interface for listing supported networks.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.4.30
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by haltman-at** [comment]
Now it does!
