### ISSUE TITLE
Truffle  unit test is not working

### ISSUE THREAD

**Issue by danj12621** [trufflesuite/truffle#4646]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I get an error message when I run the test,
"Truffle  assert.equal is not a function"

## Steps to Reproduce
inside a unit test I have something like the following:

const result=0;
assert.equal(result, 0, "this should be valid");

## Expected Behavior

it should succeed, 
Note: if I comment (assert.equal(result, 0, "this should be valid")) the unit test succeed.

## Actual Results

Truffle  assert.equal is not a function

**Comment by gnidan** [comment]
Hi @danj12621, thanks for opening this! Could you please provide a repo or some other complete reproduction steps? Taking a quick look at the code, it's not clear what's going wrong without more info. Appreciate it! 🙏

**Comment by eggplantzzz** [comment]
Closing for issue maintenance!
