### ISSUE TITLE
Events is undefined. Unable to listen to events.

### ISSUE THREAD

**Issue by vinaykharayat** [trufflesuite/truffle#4655]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When I am using latest version of Truffle-Contracts.min and Web3.min I am unable to listen to events.
I am getting this error.
Uncaught (in promise) TypeError: instance.events is undefined
``` javascript
App.contracts.UkTokenSale.deployed().then((instance)=>{
      console.log(instance);
        instance.events.Sell({
            filter: {myIndexedParam: [20,23], myOtherIndexedParam: '0x123456789...'}, // Using an array means OR: e.g. 20 or 23
            fromBlock: 0
        }, function(error, event){ console.log(event); })
        .on('data', function(event){
            console.log(event); // same results as the optional callback above
        })
        .on('changed', function(event){
            // remove event from local database
        })
        .on('error', console.error);
});
```

Log for contract Instance ABI:-
```
[
  {
    "inputs": [
      {
        "internalType": "contract UkToken",
        "name": "_tokenContract",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_tokenPrice",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "_buyer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "name": "Sell",
    "type": "event",
    "signature": "0x5e5e995ce3133561afceaa51a9a154d5db228cd7525d34df5185582c18d3df09"
  },
  {
    "inputs": [],
    "name": "tokenContract",
    "outputs": [
      {
        "internalType": "contract UkToken",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function",
    "constant": true,
    "signature": "0x55a373d6"
  },
  {
    "inputs": [],
    "name": "tokenPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function",
    "constant": true,
    "signature": "0x7ff9b596"
  },
  {
    "inputs": [],
    "name": "tokensSold",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function",
    "constant": true,
    "signature": "0x518ab2a8"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_numberOfTokens",
        "type": "uint256"
      }
    ],
    "name": "buyTokens",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function",
    "payable": true,
    "signature": "0x3610724e"
  },
  {
    "inputs": [],
    "name": "endSale",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function",
    "signature": "0x380d831b"
  }
]
```

## Steps to Reproduce

1. Create event
2. Try to listen to event

## Expected Behavior

Event should trigger

## Actual Results

Got this error Uncaught (in promise) TypeError: instance.events is undefined

## Environment

* Operating System: Fedora
* Ethereum client: ganache-2.5.4
* Truffle version (`truffle version`): v5.4.29
* node version (`node --version`): v16.13.2
* npm version (`npm --version`): v1.5.3

**Comment by gnidan** [comment]
Thanks for opening this @vinaykharayat! We'll take a look at this soon and see what we can figure out.

**Comment by kevinweaver** [comment]
Hi @vinaykharayat, [web3 contracts](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-events) have an `events` namespace, where as truffle contracts do not. Instead of calling `instance.events.Sell()`, please try `instance.Sell()` directly.  Also, keep in mind that you can only subscribe to events using a websockets provider and not an HTTP provider.  More on the differences [here](https://web3py.readthedocs.io/en/stable/providers.html) and an example of using that with HDWalletProvider [here](https://ethereum.stackexchange.com/questions/35197/how-to-connect-truffle-using-hdwallet-provider-to-websocket-powered-node/74590). Please let me know if that works, thanks!

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
