### ISSUE TITLE
Getting help for a specific command

### ISSUE THREAD

**Issue by JustinDrake** [trufflesuite/truffle#467]
(I started playing around with truffle less than an hour ago. I'll be probably be posting a few "trivial" issues for things that I found strange.)

I am trying to get more information (e.g. command line flags) for the `truffle test` command. I tried doing `truffle test -h` but it seems the flag is ignored.

How can I get more information about the `truffle test` command?

**Comment by JustinDrake** [comment]
I found the options at http://truffleframework.com/docs/advanced/commands

**Comment by tcoulter** [comment]
Closing, as that documentation is the right place to go. Cheers!
