### ISSUE TITLE
Should Truffle support URL imports in Solidity?

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#4685]
Should we consider supporting the following kind of syntax in Truffle projects?

```solidity
pragma solidity 0.8.0;

import "https://myWebsite.com/mysource.sol";

contract ....
```

**Comment by gnidan** [comment]
Blech! That's a gaping security hole! What if "mywebsite.com" changes `mysource.sol` tomorrow?

**Comment by eggplantzzz** [comment]
Do you object to Remix supporting it? I think they do, right?

**Comment by gnidan** [comment]
I do think it's a bad idea that Remix supports it. It's just too risky!

**Comment by eggplantzzz** [comment]
Sounds good to me, closing this.
