### ISSUE TITLE
Occurs when you do the following "npm install -g truffle"

### ISSUE THREAD

**Issue by ukyo717** [trufflesuite/truffle#4692]
npm ERR! code 1
npm ERR! path C:\Users\UserName\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\bigint-buffer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! ���̃\�����[�V�������̃v���W�F�N�g�� 1 �x�� 1 ���r���h���܂��B���s�r���h��L���ɂ���ɂ́A"/m" �X�C�b�`��ǉ����Ă��������B
npm ERR!   bigint-buffer.c
npm ERR! c:\users\�_�R�E��\appdata\local\node-gyp\cache\17.4.0\include\node\node_api.h(12): fatal error C1083: include �t�@�C�����J���܂���B'js_native_api.h':No such file or directory [C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\bigint-buffer\build\bigint_buffer.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "C:\Users\UserName\AppData\Local\Programs\Python\Python38\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1778) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\UserName\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\@trufflesuite\\bigint-buffer\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\UserName\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\UserName\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\@trufflesuite\\bigint-buffer',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\@trufflesuite\\bigint-buffer\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\UserName\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\bigint-buffer
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by ukyo717** [comment]
after that. I Reinstalled Node.js, VScode.
but garbled characters Increased.
help me.
npm ERR! code 1
npm ERR! path C:\Users\UserName\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! ���̃\�����[�V�������̃v���W�F�N�g����x�� 1 ���r���h���܂��B���s�r���h��L���ɂ���ɂ́A"-m" �X�C�b�`��ǉ����Ă��������B
npm ERR!   builder.cc
npm ERR! C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\leveldb\port-libuv\port_uv.h(42,10): fatal error C1083: include �t�@�C�����J���܂���B'uv.h':No such file or directory [C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
npm ERR!   snappy-sinksource.cc
npm ERR!   snappy-stubs-internal.cc
npm ERR! C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\snappy\snappy\snappy-stubs-internal.h(1,1): warning C4819: �t�@�C���́A���݂̃R�[�h �y�[�W (932) �ŕ\���ł��Ȃ��������܂�ł��܂��B�f�[�^�̑�����h�����߂ɁA�t�@�C���� Unicode �`���ŕۑ����Ă��������B [C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\snappy\snappy.vcxproj]
npm ERR!   snappy.cc
npm ERR! C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\snappy\snappy\snappy-stubs-internal.h(1,1): warning C4819: �t�@�C���́A���݂̃R�[�h �y�[�W (932) �ŕ\���ł��Ȃ��������܂�ł��܂��B�f�[�^�̑�����h�����߂ɁA�t�@�C���� Unicode �`���ŕۑ����Ă��������B [C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\deps\snappy\snappy.vcxproj]
npm ERR!   win_delay_load_hook.cc
npm ERR!   snappy.vcxproj -> C:\Users\�_�R�E��\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown\build\Release\\snappy.lib
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Python310\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.32106.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\leveldown\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Local\\node-gyp\\Cache\\16.13.2\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\UserName\\AppData\\Local\\node-gyp\\Cache\\16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\UserName\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.2\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\leveldown',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\truffle\\node_modules\\ganache\\node_modules\\leveldown\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\UserName\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\leveldown
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

**Comment by eggplantzzz** [comment]
Hey @ukyo717, for now Truffle is only compatible with npm < 7. It looks like you are using version 8, could you try downgrading your npm and installing again?
You can do this by entering
```
npm install -g npm@6
```

**Comment by ukyo717** [comment]
Thanks to reply.
It's my answer.

**Comment by Silur** [comment]
@eggplantzzz what are the steps needed in order to support npm 8? Is there an issue for that?

**Comment by adeebabdulsalam** [comment]
I have similar issue

OS: windows 10 pro
node: 16.3.2
npm: used to be version 8 and them downgraded to 6.14.16 based on the comments

tried with yarn too

**Comment by JuanXavier** [comment]
I found ta solution that worked for me:

The node-gyp docs state that "node-gyp requires that you have installed a compatible version of Python, one of: v3.6, v3.7, v3.8, or v3.9.", and I had 3.10.2, as I notice you do. 

- Run `npm install --global windows-build-tools`. Since this installs some 2.7 Python version, i uninstalled it to do the next step.
- Install Python 3.9 (https://www.python.org/downloads/release/python-3910/)
- Install node-gyp: `npm install -g node-gyp`
- Clear npm cache: `npm cache clear --force`
- Finally hit `npm i -g truffle`

Hope it helps!

**Comment by RasenGUY** [comment]
> I found a solution that worked for me:
> 
> The node-gyp docs state that "node-gyp requires that you have installed a compatible version of Python, one of: v3.6, v3.7, v3.8, or v3.9.", and I had 3.10.2, as I notice you do.
> 
>     * Run `npm install --global windows-build-tools`. Since this installs some 2.7 Python version, i uninstalled it to do the next step.
> 
>     * Install Python 3.9 (https://www.python.org/downloads/release/python-3910/)
> 
>     * Install node-gyp: `npm install -g node-gyp`
> 
>     * Clear npm cache: `npm cache clear --force`
> 
>     * Finally hit `npm i -g truffle`
> 
> 
> Hope it helps!
> 
> By the way, Im running Windows 10, with Node 16.14.0 and npm 8.3.1

I have pythin 3.9 installed and had the same error. But on linux instead.

**Comment by monperrus** [comment]
I confirm that `npm install -g npm@6` solves the problem

**Comment by LlamameBugCode** [comment]
Confirmo solucion :  npm install -g npm@6

**Comment by vahidreza** [comment]
npm install -g npm@6 worked for me too but there should be a way we be able to use it with the latest npm also.

**Comment by zakrad** [comment]
npm install -g npm@6 workes fine

**Comment by MichaelMarano** [comment]
Thank you all guys, I was feeling lost about this issue and after a couple of tries everything worked just fine.
Installed npm@6 and downgraded python to 3.9.1.

Sweet!!

**Comment by RedBullWeb3** [comment]
Try few hours to find solutions and it's working finally! Thank you!

problem: wrong version of npm
solution: npm install -g npm@6
