### ISSUE TITLE
Function depth in debugger doesn't increase when entering function called from fallback/receive function in Solidity >=0.5.1

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4697]
## Issue

If you call the fallback or receive function of a contract written in Solidity 0.5.1 or greater, and that fallback or receive function calls another function `f`, then the debugger's function depth won't increment upon entering `f`.

This is because, since the contract is in Solidity >=0.5.1, the debugger applies the phantom call guard, and nullifies the depth increase from the first jump-in encountered; since fallback and receive functions don't have a jump-in marking of their own, instead that nullification gets incorrectly applied to the first function *called* from the fallback or receive function.

Note that constructors also don't have a jump-in marking, but this problem doesn't affect constructors because the debugger doesn't apply the phantom call guard when in a constructor.  It should also not apply the phantom call guard when a fallback or receive function is invoked, in order to solve this problem.

Presumably I decided earlier that this was acceptable because this failure to increment the function depth cannot result in any variable collisions, and thus I considered harmless.  However, I neglected to consider that the function depth is also used for stepping, and as such this may cause the debugger to step incorrectly.  As such, this problem with the function depth should be corrected.

## Environment

* Truffle version (`truffle version`): 5.4.32

**Comment by kevinbluer** [comment]
Fixed in https://github.com/trufflesuite/truffle/releases/tag/v5.5.0
