### ISSUE TITLE
Print gas usage

### ISSUE THREAD

**Issue by JustinDrake** [trufflesuite/truffle#470]
I am interested in knowing how much gas is consumed when my contracts are called, e.g. in tests. It would be cool if the gas consumed was appended next to the test results, e.g. 

```
  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (78ms, 1029402 gas)
    ✓ testInitialBalanceWithNewMetaCoin (54ms, 1234984 gas)
```

Can Truffle give me gas consumptions?

**Comment by elenadimitrova** [comment]
In future, do ask in gitter and check the docs first before submitting a large number of questions against the repo, and not just for this one. 
As an answer to your question, see documentation here
http://truffleframework.com/tutorials/upgrading-from-truffle-2-to-3#contract-abstractions-transaction-result-objects
you have the entire transaction object back where you can query lots of things, including gas used via `tx.receipt.gasUsed`

**Comment by JustinDrake** [comment]
Thanks @elenadimitrova. I've submitted a PR for the docs. Do you know how to test for gas usage from a Solidity test contract (as opposed to a JS test)?

**Comment by JustinDrake** [comment]
I also came across the `estimateGas` function of a contract function (alonside `call`, `sendTransaction` and `request`). I can't see where that is documented.

**Comment by gnidan** [comment]
You should be able to get this by using the [eth-gas-reporter](https://www.npmjs.com/package/eth-gas-reporter). Closing this, calling it out of scope for the time being (since there's that workaround). Thanks!
