### ISSUE TITLE
I encountered an incomprehensible error about "Something went wrong while attempting to connect to the network at http://127.0.0.1:8545. Check your network configuration."

### ISSUE THREAD

**Issue by ukyo717** [trufflesuite/truffle#4700]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/92012279/152748306-773c053f-b28e-4611-981c-29e832fdc17b.png">

Already I tried "truffle migrate --network development"

**Comment by lsqproduction** [comment]
Hello @ukyo717  👋 
This error indicates that http://127.0.0.1:8545 is not currently connected to an instance of the blockchain environment. You can try connecting [Ganache](https://trufflesuite.com/blog/introducing-ganache-7/) to it.

**Comment by hyde2000** [comment]
Ganache's default port is 7545. You can change `truffle-config.js` to use port 7545 or switch Ganache port to 8545.

**Comment by haltman-at** [comment]
@hyde2000 Sorry, my slight mistake -- the default for Ganache UI is indeed 7545.  I was thinking of the the command line `ganache`, but I guess "Ganache" is used to refer to both.  How confusing!  Sorry about that.

**Comment by ukyo717** [comment]
Hi, thank you to reply. I connected exactly to the ganache and made the port the same(8545)
But did not solve.
like this.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/92012279/153121821-79615c8f-ebcf-4f53-895d-f718f6c843f7.png">

**Comment by ukyo717** [comment]
Actually, when I tried ganache-cli, I can do migrate the project.
But [Ganache](https://trufflesuite.com/ganache/) does not succeed.

**Comment by haltman-at** [comment]
Could you give us some specific reproduction steps? Thanks!

**Comment by ukyo717** [comment]
alright.
The first, It is my development environment.

OS Ubuntu18.04 (actually I am windows user but 
I'm developing on Ubuntu18.04)
node.js ver 16.13.2
npm ver 6.14.16
VScode ver 1.64.1

truffle config.js
module.exports = {
  networks: {
     development: {
      host: "127.0.0.1",     
      port: 8545,            
      network_id: "*",       
     },
      test: {
        host: "127.0.0.1",     
        port: 7545,            
        network_id: "*",
      }
  },
  compilers: {
    solc: {
     version: "0.8.11",
    }
  },
};

**Comment by ukyo717** [comment]
Fortunately, the problem has been resolved when I tried change hostname.
I specified vEthernet(WSL) to HOSTNAME and it was successful.

**Comment by cds-amal** [comment]
Hi @ukyo717,

Thanks for the followup! Glad you solved the problem 🎉.  I didn't realize you are using WSL on Windows, can you share your Windows version, so we can recognize this issue in the future? Thanks!

**Comment by ukyo717** [comment]
It's windows 11 home. Thanks!

**Comment by safeparadise** [comment]
oh yeah  I changed my network to  vEthernet(WSL) is worked.how can? go to **ganache ->settings->server** and change the hostname to vEthernet(WSL) and next got to your project and change the file **truffle-config.js** and change the 
```
 development: {
      host: "172.23.112.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "5777",       // Any network (default: none)
     },
```
like this.beacause the vEthernet ip is 172.23.112.1 , I put it for the people may not found how to fix it.
