### ISSUE TITLE
Truffle Node-gyp rebuild failed 

### ISSUE THREAD

**Issue by engineerscodes** [trufflesuite/truffle#4708]
![WhatsApp Image 2022-02-09 at 7 36 44 PM](https://user-images.githubusercontent.com/68312849/153217537-ebd71e3a-1562-4fb1-bee5-27987a79f00a.jpeg)

# does not match this visual studio command Prompt mean??
I have installed visual studio 2022

![image](https://user-images.githubusercontent.com/68312849/153218280-d9cbdc57-4012-4050-9d0f-082d90eafb66.png)

## Environment

* Operating System:  Windows 11
* node version :16.13.0
* npm version :8.4.1

**Comment by cds-amal** [comment]
Hi @engineerscodes,

I'm not sure about the **vscode** compatibility issue, and can only go with what the Node documentation says. 

- Truffle is currently not compatible with **npm** >=v7.x. Please downgrade to **npm** v6.x (`npm -g install npm@6`) before proceeding to the next bullet
- it looks like your environment is not set up for node correctly. See [option 1 on this Microsoft guide](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration). 

Good luck, and please let me know how it goes.

**Comment by engineerscodes** [comment]
**Thank You @cds-amal** ,
**I fixed the Above Issue**.

1. uninstalled Node completely. 
2. Install Node with Install Additional Tools for Node.js (it will also install vsbuildtools2019).
3. Install npm version 6 - ```npm -g install npm@6```
4. Then try this ```npm install -g truffle```

**This Would fix the above issue** 
But I encounter another issue,
![image](https://user-images.githubusercontent.com/68312849/153251273-41ba3791-5370-41c6-8e0f-3e54dd85133a.png)

**Simply Just delete truffle.cmd file**
**repeat step 4,This Would fix this issue.**

![image](https://user-images.githubusercontent.com/68312849/153252526-c83dc53e-59f9-4eb4-99ac-9d4908cbeb5c.png)

**Comment by Bala320** [comment]
Thanks dude!! Issues rectified :-)
