### ISSUE TITLE
Where can I find the DeployedAddresses.sol file?

### ISSUE THREAD

**Issue by JustinDrake** [trufflesuite/truffle#471]
I cannot find the `DeployedAddresses.sol` file. It's not in the global truffle repo `/usr/local/lib/node_modules/truffle`. It's not in the folder created by `truffle init`. It's not in the Git repo https://github.com/trufflesuite/truffle.

Where can I find the `DeployedAddresses.sol` file?

**Comment by tcoulter** [comment]
Hi there,

This file is dynamically created at test time. When you run your tests. Truffle creates this file depending on which contracts are deployed. Its contents looks something like this:

```
contract DeployedAddresses {
  function MetaCoin() returns (address) {
    return 0x...; // address is hardcoded
  }
  // If there are more contracts deployed, they'll be included as well.
}
```

You include `DeployedAddresses.sol` in your tests by importing `truffle/DeployedAddresses.sol`. Here, `truffle` is a meta package that may include dynamically created contracts like `DeployedAddresses`. 

Let me know if this helps. Thanks!

**Comment by VoR0220** [comment]
@tcoulter what if I wanted to test a factory of contracts and pick and choose from which ones to run tests on? How would I best organize this?

**Comment by dmgarland** [comment]
Found the source generator in Truffle Core https://github.com/trufflesuite/truffle-core/blob/b3ad375993ec42bc622c7674258edc7614944482/lib/testing/deployed.js

**Comment by 0xfrost-wonder** [comment]
I also faced this kind of problem.
I can't find "DeployedAddresses.sol" file and there is no such a data in roaming folder at  my local storage
