### ISSUE TITLE
Dry-run public networks list is out of date

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4720]
## Issue

The [dry-run network whitelist](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/commands/migrate/determineDryRunSettings.js) has been sitting unmaintained for a long time.  It should probably be updated somehow; or, alternatively, we should find some other mechanism to replace it.

Now, this whitelist was introduced in #1028.  Going that PR, as well as the condition about `config.production` (which needs to be documented btw, but [that's its own issue](https://github.com/trufflesuite/truffle/issues/4721)), it sounds like the intention was for this to be a list of all public networks (as opposed to private development networks you might create with Ganache or similar).  But if that's the case, it's badly out of date!

We may need to start maintaining a more exhaustive list... our own version of the various `chains.json` files that [exist](https://github.com/ethereum/sourcify/blob/master/services/core/src/chains.json) out [there](https://chainlist.org/chains.json).  There's a little bit of this already in [source-fetcher](https://github.com/trufflesuite/truffle/blob/develop/packages/source-fetcher/lib/networks.ts), but that only covers the networks supported by at least one of Sourcify or Etherscan (or Etherscan's clones for other networks); it's not intended to cover *all* public networks.  And indeed, there are already networks on the dry-run whitelist that don't appear in source-fetcher, such as `99` (core), `7762959` (Musiccoin), and `61717561` (Aquachain).  So I don't think we can just use the list from source-fetcher!

(Although, if we are making our own `chains.json` or similar, then `source-fetcher` could use *that*, instead of having its own separate list!)

See also: #4768, #4769

## Environment

* Truffle version (`truffle version`): 5.4.33

**Comment by lsqproduction** [comment]
We decided to use the new Ganache feature.

**Comment by kevinbluer** [comment]
Available in [v5.6.18](https://github.com/trufflesuite/truffle/releases/tag/v5.5.18) 👍

**Comment by eggplantzzz** [comment]
Looks like this can be closed.
