### ISSUE TITLE
The `<network>.production` config option needs to be documented

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4721]
## Issue

Turned this up while writing up #4720.  Turns out this option exists, and forces migrations to a particular network to always dry-run.  (Which is to say, it's the opposite of `<network>.skipDryRun`, but that one is documented.)  I had no idea this existed; there's no documentation for it.  That'll need to be added.

## Environment

* Truffle version (`truffle version`): 5.4.33

**Comment by eggplantzzz** [comment]
#1196 adds this to the docs
