### ISSUE TITLE
Solidity tests on Solidity versions <0.7.6 can pass incorrectly and have useless warnings printed when they pass

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4722]
## Issue

This issue is being split off from #4696.  So I'm just going to copy the relevant text from that:

> But the thing that poses a real problem here is how this [#4696] interacts with Truffle's Solidity assertion library.
> 
> The smaller problem is that it means that if you use the Solidity assertion library with --show-events on, you'll get a bunch of warnings about undecodeable events, because passing TestEvents have "" as their message. These are supposed to be filtered out... but this relies on decoding them, which the decoder currently fails at.
> 
> The bigger problem is that it could result in Solidity tests passing incorrectly. If you use an assertion and give the message as "", and it isn't one of our assertions that automatically includes a message of some sort, then the decoder will fail to decode it and as such the test runner won't throw. Oops!
> 
> Fixing the underlying problem with the decoder seems hard [i.e. #4696], so we may want a stopgap solution to the TestEvent problem that can go out quicker. A simple way would be to just restore the old way of handling TestEvents, that didn't rely on @truffle/decoder.

## Environment

* Truffle version (`truffle version`): 5.4.33

**Comment by lsqproduction** [comment]
Addressed in the release v5.5.2.
