### ISSUE TITLE
Truffle Installation Error

### ISSUE THREAD

**Issue by tahaimran** [trufflesuite/truffle#4725]
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! leveldown@6.1.0 install: `node-gyp-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the leveldown@6.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-11T14_30_45_472Z-debug.log

**Comment by cds-amal** [comment]
Hi @tahaimran can you provide your environment details? as well as the result of `npm doctor`?

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by tahaimran** [comment]
node version 10
npm version 6

**Comment by cds-amal** [comment]
Truffle does not support node 10. Please try node 12, or node 14 with npm v6

**Comment by tahaimran** [comment]
DOne
