### ISSUE TITLE
Update/replace chromafi

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#4726]
---------------------------
## Issue
@truffle/contract depends on @truffle/debug-utils which depends on @trufflesuite/chromafi which depends on ansi-mark which is [vulnerable](https://github.com/F1LT3R/ansi-mark/issues/2), throws [warnings on every run](https://github.com/F1LT3R/ansi-mark/issues/3) (as does super-split, also a dependency of chromafi from the same developer), and isn't maintained.

It would be better if either:
A. Trufflesuite forks and maintains ansi-mark, updates the reference from chromafi, and issues an update on chromafi, or 
B. Truffle/debug-utils finds a way to drop chromafi.

**Comment by haltman-at** [comment]
Should be straightforward enough to strip out the `ansi-mark` dependency, since I'm pretty sure we're not even using that.  Heh, our fork of `chromafi` will get even further away from the original...

**Comment by haltman-at** [comment]
OK, I've put up trufflesuite/chromafi#7 to get rid fo that dependency, and once we merge/release that we can update debug-utils to use it.

**Comment by wbt** [comment]
@haltman-at Do you want to try doing the same for super-split, which has a similar issue and is also a chromafi dependency?

**Comment by haltman-at** [comment]
OK, PR for this is merged, it'll go out in this week's release.
