### ISSUE TITLE
Debugger's stacktraces show extra, non-existent stackframes

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4739]
## Issue

When you make an external function call, you get *two* stackframes instead of one.  One for the external call (with the address but no function name), and then another one for the function itself (but w/o the address).

These should be combined.  Originally they *were* combined (when they were added in #2965), but then I decombined them (in #2976) due to some problems with how fallback and receive functions are handled.  However, now that #4710 is merged, those problems shouldn't get in the way anymore, and it should be possible to combine them again.

## Environment

* Truffle version (`truffle version`): 5.4.33

**Comment by leeftk** [comment]
Fixed in latest release.
