### ISSUE TITLE
How to verify contracts on etherscan

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#475]
Lets say I have the following contact: 

```
pragma solidity ^0.4.11;

import "zeppelin-solidity/contracts/crowdsale/Crowdsale.sol";

contract RomanCrowdsale is Crowdsale {
    function RomanCrowdsale(uint256 _startBlock, uint256 _endBlock, uint256 _rate, address _wallet) Crowdsale(_startBlock, _endBlock, _rate, _wallet) {
    }
}
```

How would you verify this contract on etherscan? 
```
var RomanCrowdsale = artifacts.require("./RomanCrowdsale.sol");
module.exports = function(deployer, network, accounts) {
  deployer.deploy(RomanCrowdsale, web3.eth.blockNumber+5, web3.eth.blockNumber+1000000000000000, 1, accounts[1]);
};

```
Manually concatenated contract: 
https://gist.github.com/rstormsf/c8ffc93a8ddd9c9edfcc2014672a8f59 

Deployed: https://kovan.etherscan.io/verifyContract?a=0x9b0ec746d4b91742187071ad8d7c06dc7ba3a4c3

Should I copy/paste all inherited contracts that this contract is depended on?

**Comment by adklempner** [comment]
From [etherscan](https://kovan.etherscan.io/verifyContract):

> 3. Contracts that use "imports" will need to have the code concatenated into one file as we do not support "imports" in separate files

**Comment by interfect** [comment]
Contracts built with an unmodified Truffle can't be verified on Etherscan currently; we're waiting for Ehterscan to be updated to support a compiler option that Truffle passes.

See https://github.com/trufflesuite/truffle/issues/456#issuecomment-312476458

**Comment by tcoulter** [comment]
Dupe of #456. Closing for housekeeping.
