### ISSUE TITLE
Phantom call guard should not be set when entering a Yul contract

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4756]
## Issue

Oops, looks I haven't yet quite gotten function depth correct once and for all.  The phantom call guard will be set when entering a Yul contract, causing the next jump-in to be ignored.  That shouldn't happen; Yul contracts should not have the guard set.  Their first jump-in should take them to 1, not 0.

## Environment

* Truffle version (`truffle version`): 5.5.0

**Comment by lsqproduction** [comment]
Addressed in the release v5.5.2.
