### ISSUE TITLE
Truffle Dashboard's "Process" button doesn't provide feedback upon being clicked

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4758]
## Issue

When you hit "Process" on the Truffle Dashboard, it defers to MetaMask for handling the signature, but the button itself doesn't change text or become disabled. With complex flows (e.g. involving HD wallets), there can be a significant delay, and there's nothing in-page to show that Truffle Dashboard is waiting.

The behavior should likely be to disable the button and change the text to something like "Processing..."

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.5.0
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment]
This has been addressed and released with version 5.5.8 https://github.com/trufflesuite/truffle/releases/tag/v5.5.8
