### ISSUE TITLE
Contracts not under contracts cannot be compiled. The imported package contains Sol file cannot compile normally

### ISSUE THREAD

**Issue by twjjw** [trufflesuite/truffle#4766]
![image](https://user-images.githubusercontent.com/87476521/155125662-c9cca9a2-7083-4b44-ac31-a1a93c9841ca.png)
truffle(develop)> compile

Compiling your contracts...
===========================
> Compiling .\contracts\Authentication.sol
> Compiling .\contracts\Authentication.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\voting.sol
> Compiling .\contracts\zeppelin\lifecycle\Killable.sol
> Compiling .\contracts\zeppelin\ownership\Ownable.sol

ParserError: Source "@appliedzkp/semaphore-contracts/interfaces/IVerifier.sol" not found
 --> project:/contracts/Authentication.sol:4:1:
  |
4 | import "@appliedzkp/semaphore-contracts/interfaces/IVerifier.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

,ParserError: Source "@appliedzkp/semaphore-contracts/interfaces/IVerifier.sol" not found
 --> project:/contracts/voting.sol:7:1:
  |
7 | import "@appliedzkp/semaphore-contracts/interfaces/IVerifier.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compilation failed. See above.

truffle(develop)>

**Comment by dongmingh** [comment]
Hi, @twjjw, thanks for raising this.  Did you run `npm install` in your project directory?  Can you check if the node_modules directory exists in your project directory?  Could you provide steps to reproduce this issue?

**Comment by gnidan** [comment]
Closing this for issue maintenance since we haven't heard back from you @twjjw. Please let us know if you're still running into trouble with this, and we'll be glad to help you sort it out. Thank you!
