### ISSUE TITLE
Should Truffle have a unified `chains.json` or equivalent?

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4769]
## Issue

What with the dry-run public networks list (see #4720), and the networks list in source-fetcher, this raises the question: Should Truffle have a unified `chains.json` or equivalent, to be used by all of these?  And should it use its own, or should it import one from another project?

I think that #4720 suggests the answer should be "yes"; the minimal way of addressing #4720 is to just have a list, but @gnidan suggested it should include more information... at which point it's basically a `chains.json`.

That leaves the question of writing our own or importing one.

If we import one, we don't have to maintain it ourselves, which is nice.

If we write one ourselves, though, then we can put Truffle-specific information in it.  Like, for source-fetcher, we could mark which networks are supported by Sourcify (something even the sourcify chains.json doesn't mark -- or rather I think they mark it by having multiple ones, a larger one and a smaller one?), and what the Etherscan API URL is for each (something none of the ones I've found include).

That said, I worry that taking this approach could be a performance issue; if the sourcify and etherscan source-fetchers each need to filter this giant file for just the few particular networks they care about, that seems bad performance-wise.  So perhaps the answer is actually *no*, we shouldn't have a unified chains.json after all, and should address #4720 in a way that is not unified with source-fetcher.

Thoughts?

## Environment

* Truffle version (`truffle version`): 5.5.1

**Comment by lsqproduction** [comment]
We've decided to not unify chain.json and have dryRun use the new ganache feature https://github.com/trufflesuite/ganache/pull/2529
