### ISSUE TITLE
Issue while installing truffle on rhel7 server.

### ISSUE THREAD

**Issue by arun31101992** [trufflesuite/truffle#4770]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

npm ERR! code 1
npm ERR! path /home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory `/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak/build'
npm ERR!   CC(target) Release/obj.target/keccak/src/libkeccak-64/KeccakSpongeWidth1600.o
npm ERR!   CC(target) Release/obj.target/keccak/src/libkeccak-64/KeccakP-1600-opt64.o
npm ERR!   AR(target) Release/obj.target/keccak.a
npm ERR!   COPY Release/keccak.a
npm ERR!   CXX(target) Release/obj.target/addon/src/addon.o
npm ERR! make: Leaving directory `/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.5.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/svc-pcldint/.cache/node-gyp/17.5.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/svc-pcldint/.cache/node-gyp/17.5.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/svc-pcldint/.cache/node-gyp/17.5.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++17’
npm ERR! make: *** [Release/obj.target/addon/src/addon.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.53.1.el7.x86_64
npm ERR! gyp ERR! command "/home/svc-pcldint/.nvm/versions/node/v17.5.0/bin/node" "/home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/svc-pcldint/.nvm/versions/node/v17.5.0/lib/node_modules/truffle/node_modules/ganache/node_modules/keccak
npm ERR! gyp ERR! node -v v17.5.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/svc-pcldint/.npm/_logs/2022-02-22T22_16_29_313Z-debug-0.log
[svc-pcldint@usedbs25169 ~]$ gcc --versio
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

## Steps to Reproduce

please follow the steps you mentioned in this github repo for unix machine

## Expected Behavior

truffle must be installed and the command suit can be used/executed.

## Actual Results

getting the error message printed above

## Environment

* Operating System: rhel7
* Ethereum client: NA
* Truffle version (`truffle version`): didn't get installed
* node version (`node --version`): 17.5.0
* npm version (`npm --version`): 8.5.1

**Comment by dongmingh** [comment]
Hi @arun31101992, node 17 is not LTS (and not supported). Please reinstall truffle with node 16 and let us know if you still have any problems. Thanks!

**Comment by arun31101992** [comment]
Hi @dongmingh, I tried installing truffle with node 16.3.0 and i am facing the below issue now:

npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.13.0/lib/node_modules/truffle/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: node-gyp-build: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-23T19_19_04_893Z-debug.log

Can you let me know if there is anything that i am missing?

**Comment by arun31101992** [comment]
Also, when I execute node-gyp and node-gyp-build these are the below outputs:

[root@usedbs25174 ~]# node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `make` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates a Makefile for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@8.4.1  /root/.nvm/versions/node/v16.13.0/lib/node_modules/node-gyp
node@16.13.0
[root@usedbs25174 ~]# node-gyp-build
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.13.0 | linux | x64
gyp info find Python using Python version 3.6.8 found at "/bin/python3"
gyp info spawn /bin/python3
gyp info spawn args [
gyp info spawn args   '/root/.nvm/versions/node/v16.13.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.nvm/versions/node/v16.13.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v16.13.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /root) while trying to load binding.gyp
**gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v16.13.0/lib/node_modules/node-gyp/lib/configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 3.10.0-1160.53.1.el7.x86_64
gyp ERR! command "/root/.nvm/versions/node/v16.13.0/bin/node" "/root/.nvm/versions/node/v16.13.0/bin/node-gyp" "rebuild"
gyp ERR! cwd /root
gyp ERR! node -v v16.13.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok**

**Comment by eggplantzzz** [comment]
One other thing you can try is downgrading to npm 6. You would do `npm install -g npm@6`. Try that and see if it resolves your issue.

**Comment by MicaiahReid** [comment]
@arun31101992 I'd also recommend running `npm doctor`. It looks like you have npm installed in the root directory which can be problematic (and dangerous).

**Comment by cds-amal** [comment]
Closing for issue maintenance.
