### ISSUE TITLE
Truffle Contract should support `"BigInt"` as a `numberFormat` (for output)

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4777]
## Issue

Currently, in Truffle Contract, you can set `numberFormat` to `"BN"` (the default), `"String"`, or `"BigNumber"` (note this only affects the output; all of these, as well as `BigInt`s, are always supported as input).  It occurred to me that we ought to also have `"BigInt"` (possibly with different capitalization, but I'm sticking to the convention for the existing ones) as a possible `numberFormat` you can choose.

## Environment

* Truffle version (`truffle version`): 5.5.2

**Comment by Pobepto** [comment]
Hi @haltman-at, can I take this task? I ran through the code and I think I figured out what to do.

**Comment by leeftk** [comment]
Fixed this with newest release. Thanks!
