### ISSUE TITLE
Installing Truffle with Visual Studio 2022 on Windows 10 (64 Bit) : Unrecognized version: "-g"  

### ISSUE THREAD

**Issue by mdgolammafuz** [trufflesuite/truffle#4788]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
Unable to install Truffle from VS 2022. Getting the following error message:

Unrecognized version: "-g"  

![Screenshot (223)](https://user-images.githubusercontent.com/99055992/155941891-246c397e-7d0b-4679-a730-51b613fbcd41.png)

What the issue is, in broad strokes.

Tried to install it as an administrator. Same issue!

![Screenshot (224)](https://user-images.githubusercontent.com/99055992/155942459-0cf274b6-d51b-415c-a47a-54980573e1e1.png)

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows 10 (64 Bit)
* Ethereum client: Ganache (testnet)
* Truffle version (`truffle version`): Still trying to install
* node version (`node --version`): 16.14.0
* npm version (`npm --version`): Using Version Manager (  typing nvm instead of npm in Developer Powershell for VS 2022 )

**Comment by eggplantzzz** [comment]
Hey @mdgolammafuz, you don't use nvm to install Truffle. npm is the Node Package Manager which you use to install packages. nvm is "Node Version Manager" which manages running different versions of Node on your machine. So the command should be `npm install -g truffle`.

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance as this is not a problem with Truffle.
