### ISSUE TITLE
i am facing this issue . can some one help me ?

### ISSUE THREAD

**Issue by anas-2627** [trufflesuite/truffle#4792]
C:\Users\ANAS>truffle
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\ANAS\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)[39m
[90m    at node:internal/main/run_main_module:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by fergxnzalez** [comment]
same problem 
Versions:
  truffle: last
  npm: '8.3.1',
  node: '16.14.0'

**Comment by cds-amal** [comment]
Hi @fergxnzalez, are you also on Windows?

**Comment by cds-amal** [comment]
Closing for issue maintenance.
