### ISSUE TITLE
`truffle test --compile-none ./path/to/test/file` ignores specific test file and runs all tests

### ISSUE THREAD

**Issue by RatanRSur** [trufflesuite/truffle#4793]

**Comment by lsqproduction** [comment]
@RatanRSur thank you for opening this issue. We will work on reproducing this. 
May I also confirm does this also happens without --compile-none?

**Comment by gnidan** [comment]
Let's close this as duplicate of #5066, since that issue has slightly more detail that might be helpful in reproducing.

Thanks for opening this @RatanRSur!
