### ISSUE TITLE
Uncaught TypeError when debugging a migrate transaction

### ISSUE THREAD

**Issue by dongmingh** [trufflesuite/truffle#4803]
## Issue

When debugging a migrate transaction, after `Transaction completed successfully`, debugger shows `Uncaught TypeError`.
Below is an example of debugging the migrate transaction `Derived` from `solidity-test-cases/immutable-test`.

After migrate:
```
2_deploy_contracts.js
=====================

   Replacing 'ImmutableTest'
   -------------------------
   > transaction hash:    0xbb47353ad3d627fe42bf160ea30d37eb699dcdfa6a8f8ee053c02d1534815ccd
   > Blocks: 0            Seconds: 0
   > contract address:    0xaE64aE8EAF4e535B71e0B20ec81BC3B4BDCa3d2E
   > block number:        3
   > block timestamp:     1646418614
   > account:             0xA121ecC201FAAa7f3108057C30C1B0f0ec87Ef0c
   > balance:             99.997684903121893263
   > gas used:            389475 (0x5f163)
   > gas price:           3.179062087 gwei
   > value sent:          0 ETH
   > total cost:          0.001238165206334325 ETH


   Replacing 'Derived'
   -------------------
   > transaction hash:    0x5a50a8df3e91f7113af09e2b48fe75038abaea80a2209bf16e1a3b83d2b647b4
   > Blocks: 0            Seconds: 0
   > contract address:    0xd61bD99423bB20b3f67Ae95AbAc73c73A9e19920
```
issue command to debug the `Derived` migrate transaction: `debug 0x5a50a8df3e91f7113af09e2b48fe75038abaea80a2209bf16e1a3b83d2b647b4`

```
InheritanceTest.sol:

 9: }
10: 
11: contract Derived is Base {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(develop:0x5a50a8df...)> 
```

issue debug command `c` to complete the transaction and see the `Uncaught TypeError` message.

```
debug(develop:0x5a50a8df...)> c

Transaction completed successfully.

Uncaught TypeError: Codec.Export.ReturndataDecodingInspector is not a constructor
    at DebugInterpreter.interpreter (/Users/dongminghwang/truffle/packages/core/lib/debug/interpreter.js:546:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DebugPrinter.printReturnValue (/Users/dongminghwang/truffle/packages/core/lib/debug/printer.js:480:11)
debug(develop:0x5a50a8df...)>
```

## Steps to Reproduce

i- truffle develop
- compile
- migrate
- debug a migrate transaction
- issue debugger command `c`

## Expected Behavior

There should not have `Uncaught TypeError` message.

## Environment

* Operating System:  MacOS Big Sur 11.5.2
* Ethereum client:
* Truffle version (`truffle version`): 5.5.3
* node version (`node --version`): 16.10.0
* npm version (`npm --version`):  6.14.15

**Comment by haltman-at** [comment]
Closing this, the issue turns out not to exist after bootstrapping.
