### ISSUE TITLE
Errors installing Truffle

### ISSUE THREAD

**Issue by ArabianAce** [trufflesuite/truffle#4805]
Hi, I am getting following errors while installing truffle on my Visual studio:

![image](https://user-images.githubusercontent.com/95887192/156919312-e01f001c-3186-4a27-ab96-2a32aabb3c0f.png)

I am using Mac OS on Apple Macbook pro

What should be the solution?

**Comment by ArabianAce** [comment]
Node version 16.13.1
NPM version 8.1.2
Mac OS

**Comment by ClubPEC** [comment]
Hi I am using Windows 11 and have installed VS & Node JS latest versions still getting below error while downloading truffle 

npm ERR! code 1
npm ERR! path C:\Users\admin\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\bigint-buffer   
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.14.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/win-x64/node.lib
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\admin\AppData\Roaming\npm\node_modules\truffle\node_modules\ganache\node_modules\@trufflesuite\bigint-buffer
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2022-03-07T11_10_26_523Z-debug-0.log

Thank you

**Comment by Palmatum** [comment]
Hi @ArabianAce @ClubPEC , 
Uninstall node js and install it again but this time check the box to install the other necessary tools. 

![68096791-82350c00-fe89-11e9-8cfa-b4619ce96162](https://user-images.githubusercontent.com/87208791/157096552-8e5634c5-08e3-4c49-8d1f-244698ff8270.jpg)

And then try installing truffle with `npm i truffle -g`

**Comment by lsqproduction** [comment]
related to https://github.com/trufflesuite/ganache/issues/2535

**Comment by gigiMyFriend** [comment]
Same problem here. Tried re-installing node (both suggested and current versions) but no luck!

**Comment by Palmatum** [comment]
@gigiMyFriend did you install node js along with the "Tools for Native Modules"?

**Comment by eggplantzzz** [comment]
If anyone is using npm version 8, try downgrading to version 6 (`npm i -g npm@6`). Does it install successfully on 6?

**Comment by Palmatum** [comment]
> If anyone is using npm version 8, try downgrading to version 6 (`npm i -g npm@6`). Does it install successfully on 6?

That shouldn't be the case as I am using npm v8.3.1 and  node v16.4.0, and my truffle works completely fine.

**Comment by gigiMyFriend** [comment]
> @gigiMyFriend did you install node js along with the "Tools for Native Modules"?

There are no custom options when installing on mac. The installer just let you decide if you want to get node and npm or just one of the two. I haven't seen "tools for native modules" anywhere

**Comment by gigiMyFriend** [comment]
just a quick update: i've reinstalled node v 14, and then again v.16 and it now works, no idea what was the issue under the hood.

**Comment by eggplantzzz** [comment]
@Palmatum I've experienced some strange issues when using npm version 8. I couldn't successfully install with 8 on my local machine but a coworker could! Our hypothesis was that my out-of-date version of xcode (due to my OS being on an older version of macOS) was causing this. I'm not sure if that was correct but I do know that certain conditions seem to cause npm version 8 to fail when installing Truffle.

**Comment by Palmatum** [comment]
@eggplantzzz, @gigiMyFriend
My bad. I didn't consider macOS. I had this problem in my windows machine and I solved it by installing those tools from the node js setup.

**Comment by ArabianAce** [comment]
Well To everyone around here. I got it figured out. Truffle did install after I downgraded my NPM version to 6 however I kept using Node version 16. 

It had started working for me

**Comment by lsqproduction** [comment]
For those who are still experiencing this issue, please make sure you have python >= 3.6. NOTE we have also seen some issues with the MacOS Monterey where python is no longer bundled. https://www.idownloadblog.com/2022/01/28/python-macos-monterey-no-more/
We also have had luck with [pyenv](https://github.com/pyenv/pyenv) for installing & managing python versions.
