### ISSUE TITLE
bSC&ChainIDE 2022

### ISSUE THREAD

**Issue by Banging12** [trufflesuite/truffle#4806]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by lsqproduction** [comment]
@Banging12  Thank you, it looks like you opened a support ticket already, we will follow up with you there and close this issue for issue maintenance.
