### ISSUE TITLE
Setting Ganache options for `truffle test` and `truffle develop` should be consistent and correct

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4807]
## Issue

Follow-up to #3147.  It is now possible to set Ganache options for `truffle test` with the `test` network; however, the way this works is inconsistent with how `truffle develop` does it, and has some problems.  Moreover, the way that `truffle develop` does it also has problems.  The two of these should be made consistent with one another, and also better.  Specifically:

1. Currently, `truffle test` simply dumps all the options from the test network into the Ganache options (with one exception, to be discussed below).  We might want to possibly restrict these in some way, to only valid Ganache options?  Not sure of this.  (Will Ganache cause an error on getting options like `skipDryRun`?  Are there *valid* options that could cause problems as they have a different intention?)

2. By contrast, `truffle develop` only allows specific fields; we should check whether there are additional fields it should allow, and whether it should possibly (like `truffle test`) simply dump in all the options.

3. However, `truffle develop` also renames some fields.  One passes in `accounts` rather than `total_accounts`, `defaultEtherBalance` rather than `default_balance_ether`, `genesis_time` rather than `time`, and `gas` rather than `gasLimit`.  Let's ignore that last one for now as it's got its own problems.  For the others, both `truffle develop` and `truffle test` should accept *both* names for each of these; like, you should be able to pass in either `accounts` or `total_accounts` and have it work, both for `truffle develop` and for `truffle test`.

4. Actually, `truffle test` does accept *one* synonym... it accepts `genesis_time` as a synonym for `time`... *sort of*.  In reality, this doesn't work, because it looks at `config.genesis_time` rather than `config.networks.test.genesis_time` (and no, there's no getter for this that would cause it to work).  So, this bug should be fixed (and also the code should be moved to live with the rest of where the user settings are set; currently it's some distance away which is confusing).

5. Finally, in `truffle develop`, `gas` should **not** be accepted as a synonym for `gasLimit`.  This is because the `gas` field is supposed to set the default *transaction* gas limit, whereas Ganache's `gasLimit` option sets the *block* gas limit, an entirely different thing.  @fainashalts already fixed this bug in `truffle test` back in #4323; it should be fixed in `truffle develop` as well.

## Environment

* Truffle version (`truffle version`): 5.5.3

**Comment by sukanyaparashar** [comment]
@haltman-at , Can you please elaborate the 4th point regarding the difference between `config.genesis_time` and `config.networks.test.genesis_time`? And what should be the accepted parameter value in the managed **Ganache** network?

**Comment by haltman-at** [comment]
Sure.  `config.genesis_time` is a top-level field of the config.  `config.networks.test.genesis_time` is a field of the `test` network in the config.  Given the overall way we want this to work, we obviously want to look at the latter, not the former; users would be quite surprised to learn that they have to set `genesis_time` at top-level, rather than in the `test` network.

However, it is worth noting that Truffle Config objects often have getters that map `config.<exampleField>` to `config.networks.<currentNetwork>.<exampleField>`.  E.g., if you do `config.gas`, you'll get `config.networks.<currentNetwork>.gas`.  However, no such getter is set up for `genesis_time`; so doing `config.genesis_time`, at present, will *not* look at `config.networks.test.genesis_time`, but instead for a top-level field as it appears.

So, this problem could be addressed *either* by looking at `config.networks.test.genesis_time`... or by adding an appropriate getter to `config`, so that `config.genesis_time` maps to `config.networks.<currentNetwork>.genesis_time`.

(Of course I'm talking about `test` here, but all of this applies can be applied to `develop` as well.)

Does that clarify things sufficiently, or did I miss what you're actually asking about?

**Comment by haltman-at** [comment]
OK, should be fixed in 5.5.13.
