### ISSUE TITLE
Decode provider requests where applicable in Truffle Dashboard

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4809]
## Issue

Right now when you use Truffle Dashboard to sign a message or a transaction, the Web UI only presents the raw (encoded) form of this data. We should use Truffle's extensive support for decoding and make things pretty.

In order to render decoded values, there's probably two paths to take:
1. Initially, we may want to shim `util.inspect` for the browser and use the existing @truffle/codec inspector capabilities. This should work, but there's likely gotchas.
2. Long-term, we'll want to build on the work outlined by #4818 and use actual React.js components for displaying things nicely. This will allow us to provide little expand/collapse thingies for deeply structured data, along with other niceties.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.5.3
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cliffoo** [comment]
Completed in #5621. Closing.
