### ISSUE TITLE
truffle-upgrades  migrate error

### ISSUE THREAD

**Issue by Gods-good** [trufflesuite/truffle#4812]
i have a  NFT.sol  , I used the upgrade deployment of truffle  .But at the time of deployment, my main contract was not deployed.

![image](https://user-images.githubusercontent.com/39650584/157399064-f400b224-6f79-4789-8053-2b09b7eaca85.png)

![image](https://user-images.githubusercontent.com/39650584/157399211-64e8bd61-cab9-4193-b3fa-a5b03ebadb6c.png)

![image](https://user-images.githubusercontent.com/39650584/157399360-feb6f9c4-4cf9-4f60-859c-1d4b7d8bbb3a.png)

![image](https://user-images.githubusercontent.com/39650584/157399989-08bcc461-1b32-4e4c-8ba9-2989a77cbcac.png)

**Comment by Gods-good** [comment]
![image](https://user-images.githubusercontent.com/39650584/157399596-162d2abe-17b6-4d31-b1db-fa67f51f3c65.png)

**Comment by Gods-good** [comment]
![image](https://user-images.githubusercontent.com/39650584/157399861-c3c4c7cc-827b-433b-835f-324d7b50d6a6.png)

**Comment by fainashalts** [comment]
Hi @Gods-good, there hasn't been any activity on this issue for a while. Hopefully you have figured it out! I am closing this for issue maintenance but if something else comes up please feel free to open a new issue!
