### ISSUE TITLE
Connection issues during large migrations

### ISSUE THREAD

**Issue by venkatesh16031999** [trufflesuite/truffle#4814]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

1. We are using a upgradeable proxy contract in truffle suite to deploy and upgrade using proxy patterns, when we deploy new proxy contract it is getting successful, but when we upgrade any contract and try to deploy an upgraded contract, it is getting failed every time. 
2. We have tried deploying on both Polygon Mainnet and Testnet
3. We have also tried by changing the RPC. Nothing seems to work.

## Steps to Reproduce

1. Deploy a proxy upgradeable contract using Openzeppelin SDK
2. Update the contract code
3. Deploy the upgraded Proxy contract, error will thrown / [object Object] output will be displayed instead of deploying the contract

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Contract should be deployed and transaction hash and other summary should be resulted as output

What you expected to happen.

## Actual Results

Attaching the error logs for the reference
1. https://mclo.gs/29w2HoT
2. https://mclo.gs/lhsa0Id

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment
Windows Operating System Environment

* Operating System: 
* Ethereum client: Polygon | Web3.js
* Truffle version (`truffle version`): Truffle v5.4.16 (core: 5.4.16)
* node version (`node --version`): Node v14.17.4
* npm version (`npm --version`): 6.14.14

**Comment by MicaiahReid** [comment]
@venkatesh16031999 Do you have any additional information that could point to this being a problem with Truffle? People tend to have a hard time with deployments to Polygon mainnet, so this could be related to that. Also, we've seen similar errors to the one you're showing when people have connection issues.

Regardless, @tenthirtyone will do some investigating on this issue. Thanks for opening it!

**Comment by tenthirtyone** [comment]
@venkatesh16031999 Hey there, can you confirm if you are following the instructions [here](https://docs.polygon.technology/docs/develop/truffle). 

If not, can you please share your truffle network config you are using for matic? It will look similar to this:

```
matic: {
      provider: () => new HDWalletProvider(mnemonic, `https://rpc-mumbai.maticvigil.com`),
      network_id: 80001,
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: true
    },
```

I'd like to know what rpc endpoint you are using for your provider.

**Comment by tenthirtyone** [comment]
Update: I was able to replicate the error on both the matic instructions and using an infura endpoint.

To test:
1. init a truffle project
2. in the migrations script copy the deployer.deploy line 10 times
3. Run the migration for the matic network using the above network config (use the matic faucet for mumbai. Use polygons rpc endpoint or setup an infura project)
4. I was not able to get through all 10 contracts any time but the failure occurs randomly - see below. 

In the infura dashboard I noticed an anomaly that was strange. My `requests today` number was flying up very quickly. 

Starting number:
![image](https://user-images.githubusercontent.com/6285466/158985708-29e4091b-185e-4c26-a6d8-c707a3c70f2f.png)

1. I reduce my migration script to 1 just migration, 1 `deployer.deploy` 
2. I re-run `truffle migrate --network matic`

The single deployment succeeds but now:

![image](https://user-images.githubusercontent.com/6285466/158985760-aaba0907-69a2-4f55-b2b5-ed6f2518012b.png)

Deployment took approx 13 seconds and waited for 2 block confirmations but ~500 requests were sent to poll for blocks. This is inconsistent with the configuration in `hdwallet-provider` and the default settings of `meta-mask/eth-block-tracker`

There is a new major version for eth-block-tracker (hdwallet-provider uses 4, 5 is released) but this appears to be an issue with how we are firing off engine.run for the migration. I haven't finished debugging but wanted to update progress for dev sync.

**Comment by venkatesh16031999** [comment]
Hey @tenthirtyone <https://github.com/tenthirtyone>,

Thanks for your support, I can see so much progress in debugging the
errors, We are also facing the same behaviour similar to yours. We are
stuck at deployment as we cannot deploy the upgraded proxy smart contract
due to this issue. I hope this error will be identified soon and fixed. Let
me know if anything else is needed from our side.

Thanks again

**Comment by tenthirtyone** [comment]
@venkatesh16031999 Thanks for confirming.

If you are able to break your migration script up into parts it could be a temporary work around while this fix is in-flight. I will reach out to try and help get your contracts on chain in the mean time.

**Comment by tenthirtyone** [comment]
@venkatesh16031999  @eggplantzzz suggested setting:

```
disableConfirmationListener: true
```

in your truffle-config. I can confirm I saw the number of requests drop by half and I was able to migrate a more complex set of contracts (10+ contracts depending on each other's addresses in the constructors) to mumbai without getting the timeout error. 

I'll continue pursuing a fix to the high volume of requests but this may get you deployed in the mean time.

**Comment by venkatesh16031999** [comment]
> @venkatesh16031999 Hey there, can you confirm if you are following the instructions [here](https://docs.polygon.technology/docs/develop/truffle).
> 
> If not, can you please share your truffle network config you are using for matic? It will look similar to this:
> 
> ```
> matic: {
>       provider: () => new HDWalletProvider(mnemonic, `https://rpc-mumbai.maticvigil.com`),
>       network_id: 80001,
>       confirmations: 2,
>       timeoutBlocks: 200,
>       skipDryRun: true
>     },
> ```
> 
> I'd like to know what rpc endpoint you are using for your provider.

We are using the infura RPC endpoint and also the above configurations matches are same as ours

**Comment by venkatesh16031999** [comment]
Even after using an disableConfirmationListener: true in the truffle configuration, we are getting the same response in the terminal when deploying new proxy implementation contract ( updating the logic contracts ) to the polygon testnet.

Response observed:

2_deploy_contracts.js
=====================

[object Object]
Truffle v5.4.16 (core: 5.4.16)
Node v14.17.4

**Comment by gnidan** [comment]
If possible, could you please share your repo with us? We have some ideas on possible workarounds that we'd like to try. Thank you!

**Comment by leeftk** [comment]
There's some related work being done on this if you want to follow you can here (https://github.com/trufflesuite/truffle/pull/4958).

**Comment by gnidan** [comment]
Closing this for issue maintenance. If you'd still like for us to diagnose your specific issue here, please share your repo and we can re-open this! Thanks again!
