### ISSUE TITLE
Issue with truffle restallation

### ISSUE THREAD

**Issue by jiaxyan** [trufflesuite/truffle#482]
- [ ] I've asked for help in the [StackExchange:Ethereum](https://ethereum.stackexchange.com/questions/19533/error-cannot-find-module-truffle-expect-truffle-migrate) before filing this issue.

---------------------------

## Issue

when I try to solve 'Error: Cannot find module 'truffle-expect'' I was suggest to reinstall truffle to an older version, but it seems that I can't uninstall truffle completely -_- my truffle version is 3.3.2 (core 3.3.1)

## Steps to Reproduce

after running `npm un -g truffle` to uninstall & `npm i -g truffle@3.2.2` to reinstall 3.2.2 version. 
run command: `truffle version`
it still shows 3.3.2. (And I close and open the console window after installing)

## Expected Behavior

expecte to show
```
The program 'truffle' is currently not installed. You can install it by typing:
sudo apt-get install truffle
```

## Actual Results
```
Truffle v3.3.2 (core: 3.3.1)
Solidity v0.4.11 (solc-js)
```

## Environment

* Operating System: ubuntu14.04
* Truffle version: before uninstalling: 3.3.2
* Ethereum client: Go-Ethereum
* node version: v7.10.0
* npm version: 4.2.0

**Comment by tcoulter** [comment]
Putting this in triage. Will attempt to reproduce.

**Comment by tcoulter** [comment]
Closing as duplicate. #477. Thanks!

**Comment by jiaxyan** [comment]
alright, thanks
