### ISSUE TITLE
When using Truffle Dashboard, Truffle should show a message in the terminal when the browser is waiting for signature and delete the message after

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4824]
## Issue

Right now, when you use Truffle with Truffle Dashboard, you have to keep your eye on the Dashboard browser tab, since all signature requests go there.

This is a bit jarring, and some users (including @Pclaesen) have raised the concern that Truffle Dashboard should maybe steal focus or such, so they don't stare blindly at `truffle migrate` output, erroneously waiting for activity when they actually need to do something themselves. After some discussion, it seems the better course of action would be for the terminal to alert the user to the effect of "Hey, alt-tab your way over to Truffle Dashboard, cause it's waiting for you!".

This is a bit tricky because it requires:
- Truffle must know it's connected to Truffle Dashboard
- Truffle must know when the Dashboard is waiting for response and display a message at that point
- Ideally, Truffle would remove the message from the terminal when the user has processed the request, so Truffle must also know when that happens to do this console cleanup

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.5.3
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by MicaiahReid** [comment]
Some notes:
 - We probably need to add a new default subscriber to truffle that is used by truffle dashboard.
