### ISSUE TITLE
Truffle Dashboard should politely ask users if they'll graciously share anonymous usage data with us

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#4828]
## Issue

Truffle already provides an opt-in analytics system, but it requires running a specific command to turn it on. We know there are users who would be more than happy to let us collect these anonymous stats, but we haven't wanted to waste precious CLI screen real estate just to pester people about this.

Now, with Truffle Dashboard, there are likely unobtrusive ways to leverage the significantly increased display resolution and put this ask on-screen in a way that encourages users to opt-in without being annoying noodges about it. This would allow us to collect more information about how people use Truffle, what errors they commonly face, etc... ultimately giving us on the team the power to make informed decisions about what to work on next.

Couple thoughts:
- We should only ask the user once, or at most maybe once every six months. Maybe we could even check back with opted-in users, like, "hey, you still cool to share this data with us?"
- If a user declines to opt-in, could we ask a follow-up question, like, "would you mind if we phone home to say you did not opt-in?" I know some applications do telemetry to report this situation without user permission, but that's not really cool... it'd be nice to understand what the opt-in rate is, but not if it means loss of consent in the process.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.5.3
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by MicaiahReid** [comment]
Some notes:
 - Would need to add a message type to message bus
 - The front end would need to issue request to get the user config to see if they've responded before
   - (we may need to store user config info in local storage and deicde how to do that)
 - If user hasn't responded, somehow show a prompt asking them (politely) for their data
   - If yes, we issue a request to MB saying they've opted in, MB needs to shell out to tuffle that they've opted in (we're only using truffle's current analytics)
   - If no, there's no current opt-out in the truffle user config (either in or not responded). We need to modify the prompt to actually allow them to opt out

**Comment by cliffoo** [comment]
Done in [v5.7.3](https://github.com/trufflesuite/truffle/releases/tag/v5.7.3). Closing.
