### ISSUE TITLE
Hooks for test lifecycle

### ISSUE THREAD

**Issue by wbl** [trufflesuite/truffle#4832]
We'd like to write out the gas consumed by contract calls to a file.

To do this right we'd need a way to open and truncate the file at the start of the tests, and close it after the tests are run. Otherwise we have to do all the benchmarking in one file, or depend on subtle details of the module cache to make sure the truncation only happens once.

**Comment by haltman-at** [comment]
Hm, @eggplantzzz, do you know if it's possible to use the events system for this?

**Comment by cds-amal** [comment]
Interesting use case! @wbl have you taken a look at [eth-gas-reporter](https://www.npmjs.com/package/eth-gas-reporter)?

**Comment by eggplantzzz** [comment]
@haltman-at sure. Wherever we calculate the gas costs we could just add a new event that emits with that particular data. Then users can write their own subscribers that would handle it.

So the task here looks to be to find out where gas costs are calculated and to add an event or multiple events to emit the desired information. @wbl can you more explicitly define exactly what information you wish to obtain? Is it the gas costs from every transaction sent?

Just for reference, here are the [docs for Truffle's event system](https://trufflesuite.com/docs/truffle/advanced/event-system.html).

**Comment by fainashalts** [comment]
This seems like a very cool endeavor! @eggplantzzz @haltman-at should we move this into the backlog?

**Comment by haltman-at** [comment]
I guess?  It's still not entirely clear to me whether @wbl's problem is handled by eth-gas-reporter or not.

**Comment by fainashalts** [comment]
@wbl have you seen @haltman-at's comment above? Wondering if we can agree on a path forward here, thanks!

**Comment by sukanyaparashar** [comment]
Hi @wbl. Can you please confirm if eth-gas-reporter was able to handle your issue?

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
