### ISSUE TITLE
Can't access contract because the contract is not recognized as deployed by the client

### ISSUE THREAD

**Issue by lupacco** [trufflesuite/truffle#4833]
Hey guys i'm new at blockchain devopment and i'm doing some app tutorials to learn it. Currently, i'm developing a TodoList contract. I've been already compiled and migrated with trufffle. everything was doing great until i have to put the call of a promise into my script. it didn't worked the same way into the terminal. In truffle console i can save the promise/contract into a variable doing 'todoList = await TodoList.deployed()'. Into my app.js file at the loadContract function, when i do "App.todoList = await App.contracts.TodoList.deployed()" the browser console returns: Uncaught (in promise) Error: TodoList has not been deployed to detected network (network/artifact mismatch)

ps: I already made the setup of my truffle-config.js to match the ganache network

Why this is happening?

![image](https://user-images.githubusercontent.com/88516344/157747658-7f9e397d-5a42-4ea1-864a-4bb6d65d191b.png)
![image](https://user-images.githubusercontent.com/88516344/157747685-51d34ece-5eb7-411a-b714-f803fadd8bcf.png)
![image](https://user-images.githubusercontent.com/88516344/157747702-7bbba05d-d738-4bbd-8265-7131caf9ce15.png)
![image](https://user-images.githubusercontent.com/88516344/157747733-dd222e91-8453-4590-8e78-4abaa8c06418.png)

**Comment by eggplantzzz** [comment]
Hey @lupacco, so it is probably the case that whatever provider you are using in the browser is not configured to point to your Ganache instance. Make sure that provider is configured correctly, you will need to supply the url to that instance which will probably look something like "http://localhost:8545". Let me know how it goes!

**Comment by lupacco** [comment]
heyyy i already setup the ganache network on metamask but the error still apearing

**Comment by lupacco** [comment]
![image](https://user-images.githubusercontent.com/88516344/157971668-9083b80a-048c-4f9b-87cd-36081fdefb3a.png)

**Comment by eggplantzzz** [comment]
You also need to make sure you deploy your contracts to that Ganache instance. If you have steps and a repo on GitHub that I could use to reproduce your error I'll help you troubleshoot this. Let me know.

**Comment by leeftk** [comment]
Closing for issue maintenance.
