### ISSUE TITLE
Upgrade to solidity 0.4.13

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#484]
- [ ] upgrade `truffle-core`
- [ ] upgrade `truffle`
- [ ] How do we test it? (Are there errors introduced that we didn't expect?) 
- [ ] Update documentation / example code (re: throws, anything else?)
- [ ] Update Boxes (throws / pragma)
- [ ] Update tutorials (least important). What about that tutorial on throws specifically?
- [ ] Ensure syntax errors are correctly displayed (see ethereum/solc-js#113)

**Comment by Qqwy** [comment]
About 'how do we test it':

IIRC Writing something like this:

```
contract Foo {
    struct Bar {
        uint baz;
    }

    Bar[] bars;

    function qux() returns(bool) {
        Foo memory val;
        val.baz = 1;
        bars.push(val);
        return true;
    }
}
```

will crash on Solidity < 0.4.13 because the `memory` keyword is not supported fully.

**Comment by elenadimitrova** [comment]
Depreciating `throw` is a big one to test too.

**Comment by tcoulter** [comment]
Story points: 8

**Comment by cryst10** [comment]
I'd like to know when is the next Truffle release with fixes to `solc.js`? It would be good to get a rough idea. 
Meanwhile is monkey patching a good solution?

**Comment by 15chrjef** [comment]
Any ETA on this? Compilation error messages are indeterminate

**Comment by tymat** [comment]
Need to have truffle decoupled from Solidity so we can upgrade each separately.  Latest version is now 0.4.14 which resolves a major issue with ecrecover.

**Comment by dyba** [comment]
@15chrjef Using [Solium](https://github.com/duaraghav8/Solium) helped me to pinpoint the reason why the compilation wasn't successful.

```
solium --init
solium --dir .
```

**Comment by tcoulter** [comment]
This issue has been fixed. Please upgrade to the latest version of Truffle.
