### ISSUE TITLE
Add opt-out to truffle user config

### ISSUE THREAD

**Issue by MicaiahReid** [trufflesuite/truffle#4845]

**Comment by MicaiahReid** [comment]
Currently truffle only stores "opt-in" and "not responded" data for analytics. We don't want dashboard users to repeatedly have to opt-out, so we need to add that info to the truffle user config

**Comment by fainashalts** [comment]
I'm closing this as we do have a way to check whether a user has opted out, because analyticsEnabled will be false and setAnalytics will be true.
