### ISSUE TITLE
Truffle migrate hangs on `Replacing Migrations` on rinkeby

### ISSUE THREAD

**Issue by ocintnaf** [trufflesuite/truffle#4859]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I'm trying to deploy my contracts on rinkeby using another account because the default one got compromised somehow.
When i use the default to migrate it works fine but when i try to specify another account the deploying always hangs on `Replacing` Migrations
<img width="732" alt="Screenshot 2022-03-12 at 10 34 34" src="https://user-images.githubusercontent.com/79849332/158012649-5e40850b-b110-4b3e-af0d-5fa3fb4d184a.png">

This is my truffle config (i attached only the rinkeby settings):
``` 
rinkeby: {
      provider: () =>
        new HDWalletProvider(
          mnemonic,
          `https://speedy-nodes-nyc.moralis.io/${
            process.env.MORALIS_SPEEDY_NODES_KEY
          }/eth/rinkeby${process.env.ARCHIVE === true ? "/archive" : ""}`
        ),
      network_id: 4,
      skipDryRun: true,
    }
```

I tried to specify the specify the from account:

- in the deployment scripts
- in the truffle config 

but nothing works so far.

I'm sure everything is setup correctly because, as i said, everything works fine if i try using the default account.

## Environment

* Truffle version: v5.5.4 (core: 5.5.4)
* node version: v16.13.0
* npm version: v8.5.4

**Comment by Bolee95** [comment]
Hi @ocintnaf,
I see you closed the issue. What was problematic with this?

**Comment by ocintnaf** [comment]
I didnt solve this specific problem, i just created another metamask wallet with a different mnemonic
