### ISSUE TITLE
Improve solc optimizer support

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#486]
Ref: #456 

- [x] Default optimizer setting to `200`, à la:
<img width="360" alt="screen_shot_2017-07-10_at_2 11 16_pm_720" src="https://user-images.githubusercontent.com/151065/28040567-33a53f82-6594-11e7-8558-ff968142ea3b.png">

- [x] Additionally, expose truffle-config setting to enable optimizer setting override.

- [x] Add default compilation flags to documentation

**Comment by mezrin** [comment]
What is default optimization flag used by truffle 3.4.6 ?
Could not verify my contract on Etherescan...
