### ISSUE TITLE
get error install truffle suite on Mac 

### ISSUE THREAD

**Issue by Puppilshaw** [trufflesuite/truffle#4864]
![Skärmavbild 2022-03-13 kl  15 28 06](https://user-images.githubusercontent.com/101512981/158074831-d8bd7343-6936-4b22-9e66-575f21fce30f.png)

![Skärmavbild 2022-03-13 kl  15 28 38](https://user-images.githubusercontent.com/101512981/158074813-8407e9ef-9705-4d63-abbd-4f0a1a1442d2.png)

* node version: 6.14.15
* npm version: v.14.18.2

**Comment by benjamincburns** [comment]
It looks like you're using the version of nodejs that comes preinstalled on macos. The version of node you listed is quite old, and per https://endoflife.date/nodejs node v6 has been deprecated for quite a long time. I'd recommend installing the latest stable or LTS release of node using NVM.

For details on this, see https://github.com/nvm-sh/nvm

**Comment by eggplantzzz** [comment]
Hmm, it looks like maybe they just accidentally swapped npm and node versions.

If you are getting these kinds of permissions errors, I would recommend installing Node and npm using nvm. This is actually what npm recommends; it generally solves these types of errors. See [this npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more info on doing this.

**Comment by eggplantzzz** [comment]
Warnings like that do not prevent installation and shouldn't be a problem.

**Comment by leeftk** [comment]
Closing for issue maintenance.
