### ISSUE TITLE
Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by madhump** [trufflesuite/truffle#487]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I try to install truffle under new project

 truffle unbox react

with this command , system is showing this error. 

Downloading...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, rename 'C:\Users\xxx\testmp\1499776562456-8641822413139135\react-box-master' -> 'C:\Users\xxx\AppData\Local\Temp\tmp-84442B9tBgD7S263'

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Install correctly 

## Actual Results

Downloading...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, rename 'C:\Users\xxx\testmp\1499776562456-8641822413139135\react-box-master' -> 'C:\Users\xxx\AppData\Local\Temp\tmp-84442B9tBgD7S263'

## Environment

* Operating System: Windows 10
* Truffle version:  Truffle v3.4.3 (core: 3.4.1)
* Ethereum client: testrpc
* node version:
* npm version:  5.0.3

**Comment by gnidan** [comment]
This is now fixed in Truffle v3.4.4. Please open a new issue if you find any additional problems. Thanks a bunch!
