### ISSUE TITLE
Dashboard's `react-scripts` dependency should be updated to 5.0.0

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4874]
## Issue

Truffle Dashboard currently uses `react-scripts` 4.0.0.  As best I can tell, this is responsible for our one remaining critical security alert, which is `immer`.  If we upgrade to 5.0.0, it will use an up-to-date version of `immer` that will get rid of the security alert.

EDIT: Nevermind, turns out we can't immediately do this; react-scripts 5.0.0 requires Node 14.  So we can't do this while we still support Node 12.  See [release notes](https://github.com/facebook/create-react-app/releases/tag/v5.0.0).

## Environment

* Truffle version (`truffle version`): 5.5.4

**Comment by michaeljohnbennett** [comment]
https://wagmi.sh used to integrate wallet connect.

more testing needed but base web3 code has been refactored to use wagmi and walletconnect added.

**Comment by michaeljohnbennett** [comment]
https://github.com/trufflesuite/truffle/pull/4926

**Comment by michaeljohnbennett** [comment]
https://nodejs.org/en/about/releases/ node 12 EOLs on 30/04/22 so we will drop support about one month later so we can upgrade this post then.

We would also be able to upgrade our tailwind and Post CSS implementations as well to newer versions.

**Comment by haltman-at** [comment]
Seems this is now responsible for *another* critical security alert.  Fortunately we're dropping Node 12 support right about now! :)
