### ISSUE TITLE
When attempting to migrate, Truffle (nodeJS) waffles between two errors?

### ISSUE THREAD

**Issue by rts-2** [trufflesuite/truffle#488]
- [ ✔] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
*In addition to asking for help on StackOverflow
---------------------------

## Issue
I'm using truffle with a Node.js project, and when I attempt to migrate the project, I get the following error:
[Windows Script Host][1]

  [1]: https://i.stack.imgur.com/IIFIY.png

However, when I use the suggested fix, which is to rename the truffle.js file to something other than truffle.js (i.e. truffle-config.js), then I get a different error:

    Could not find suitable configuration file.

When I rename the configuration file back to "truffle.js", then I get the first error all over again.
The solutions I've tried have included using Windows Powershell to run the program and running the command `npm install --force -g truffle`, neither of which have worked. I've looked into the recommended solution (https://github.com/trufflesuite/truffle/issues/150), and none of the proposed solutions have worked so far.

## Environment

* Operating System: Windows 10
* Truffle version: v3.3.0
* node version:  6.11.0 

## Reproducing the Error
You must be using Windows 10, the project runs correctly with Linux. Run ```truffle migrate```. You will get an error from Windows Script Host that will say ```'module' is undefined```. Change the name of the truffle Javascript file to ```truffle-config.js```. Run ```truffle migrate``` again. You will get an error that says ```Could not find suitable configuration file```. Change the name of the truffle-config.js file back to truffle.js. Run ```truffle migrate``` and you will get the ```'module' is undefined``` error again.

**Comment by Frankie34** [comment]
start ganache
truffle compile + truffle migrate
that works for me

**Comment by gnidan** [comment]
Is this still an issue on Truffle v5? Thanks!
