### ISSUE TITLE
YOUR CODE IS INFECTED WITH MALICIOUS DEPENDENCY - node-ipc

### ISSUE THREAD

**Issue by lgg** [trufflesuite/truffle#4881]
Newest version of node-ipc delete all users's files from device. You should not use this dependency anymore!

You can learn more here: https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c

Check possible solution that already applied in `vue.js`: https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029

**Comment by gnidan** [comment]
Thanks for letting us know! We have a PR to fix this merged here: https://github.com/trufflesuite/truffle/pull/4880. This will be released tomorrow or the next day.

In the meantime, this does not affect Truffle users - it only affects people who download @truffle/environment (an internal package) directly.
