### ISSUE TITLE
Improve error reporting when Truffle fails to connect to JSON RPC

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#489]
## Issue

Currently, the error appears as `"Invalid JSON RPC response"` with very little representation of underlying problem

## Expected Behavior

The error should indicate that Truffle has trouble connecting to Ethereum node software.

## Specific Requirements

- Error message should include possible failure cases. Feel free to use an error message that has multiple lines and formatting, i.e., 

    ```
    Could not connect to your Ethereum client. Please check that your Ethereum client:

    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    ```

     And perhaps we can have the error message link to a FAQ or document that describes this (ignore this requirement if you can't find a useful document)

- The error itself should be wrapped in `truffle-error`. Note that [Truffle uses truffle-error as a "flag" to print out error messages nicely instead of showing a full stack trace](https://github.com/trufflesuite/truffle-core/blob/master/cli.js#L25).

(from https://github.com/trufflesuite/truffle-config/pull/4#issuecomment-315401206)

**Comment by dotnetspec** [comment]
Thanks. I realized that Truffle was not able to connect to the Ethereum client. However, I don't know why it wouldn't connect.

What steps can I take to make the connection happen?

Thanks,

**Comment by gnidan** [comment]
@dotnetspec Ensure that your client is running and your `truffle.js` file is configured correctly. Beyond that, the [Truffle gitter](https://gitter.im/Consensys/truffle) is probably the best place to go for troubleshooting. (Underlying issues can vary wildly)

**Comment by gnidan** [comment]
After wrapping the underlying web3 error, here's what it looks like:

<img width="1301" alt="screen shot 2017-07-17 at 1 10 41 pm" src="https://user-images.githubusercontent.com/151065/28280336-6e4e42ca-6af1-11e7-9be6-0a06c74d9aa2.png">
