### ISSUE TITLE
compile failed with multi solc version

### ISSUE THREAD

**Issue by Hasiwansui** [trufflesuite/truffle#4903]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

compile failed with multi solc version. I noticed in the source [truffle]packages/compile-solidity/src)/compileWithPragmaAnalysis.js.
Why need second match result instead first?

const getSemverExpression = source => {
  return source.match(/pragma solidity(.*);/)[1]
    ? source.match(/pragma solidity(.*);/)[1].trim()
    : undefined;
};

## Steps to Reproduce

truffle config
```
    compilers: {
        solc: {
            version: "pragma",    // Fetch exact version from solc-bin (default: truffle's version)
            // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
            // settings: {          // See the solidity docs for advice about optimization and evmVersion
            //  optimizer: {
            //    enabled: false,
            //    runs: 200
            //  },
            //  evmVersion: "byzantium"
            // }
        }
```

then truffle compile

## Expected Behavior

compiled success.

## Actual Results

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Downloading compiler. Attempt #1.
TypeError: Cannot read properties of null (reading '1')
    at getSemverExpression (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compileWithPragmaAnalysis.js:19:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compileWithPragmaAnalysis.js:78:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compileWithPragmaAnalysis.js:4:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.5.5 (core: 5.5.5)
Node v17.7.2

## Environment

* Operating System: ubuntu 20.0.4
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.5.5
* node version (`node --version`): 17.7.2
* npm version (`npm --version`): 8.5.2

**Comment by Hasiwansui** [comment]
Do I need to use some fixed version of compiler，I use kind of  “ pragma solidity ^0.8.0; ”statement.

**Comment by eggplantzzz** [comment]
You will get a different error if you have version conflicts. The error you are getting will occur if you have no pragma expression in one of your source files. Is your project on GitHub? If it is, can you link to it? We'll be happy to take a look to try and pinpoint the issue. Either way Truffle should probably error in a more helpful way when this problem occurs.

**Comment by eggplantzzz** [comment]
Ok, thanks @Hasiwansui! And just for reference, I have implemented a fix for the aforementioned issue [here](https://github.com/trufflesuite/truffle/pull/4930).

**Comment by Hasiwansui** [comment]
I reviewed my code and found there is no missing "pragma" statement.I will try to reproduce the situation.And my development environment is running in a docker container,maybe it will  cause some strange situation.

**Comment by eggplantzzz** [comment]
If you are able to link to your code that fails in the way you describe I would love to check it out to see if I can spot something amiss. Thanks!

**Comment by haltman-at** [comment]
Can you try this again with Truffle 5.5.6?  It includes a fix to the related code... could you tell us what the result is?  Thanks!

**Comment by Hasiwansui** [comment]
> Can you try this again with Truffle 5.5.6? It includes a fix to the related code... could you tell us what the result is? Thanks!

OK,please wait.

**Comment by fainashalts** [comment]
Hi @Hasiwansui I just wanted to check in on this -- did our fix address your issue? Thanks, please let us know!

**Comment by fainashalts** [comment]
Hello @Hasiwansui! We have not heard back from you, hopefully our suggestion was sufficient for your needs. I'm closing this for issue maintenance, but please feel free to open a new issue if this is not resolved or something else comes up!
