### ISSUE TITLE
`truffle init` points to 404 URL in comments

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#4912]
- trufflesuite.com/docs/advanced/configuration
- the link should have the protocol to allow editors to supply the appropriate action
- this link also appears in the metacoin box, and likely others as well.

**Comment by davidmurdoch** [comment]
Hey @sukanyaparashar I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/truffle-dev-5c67177dfd28fb7faae0855e/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by haltman-at** [comment]
This should be fixed now!
