### ISSUE TITLE
Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by stiv-yakovenko** [trufflesuite/truffle#492]
My config:

    module.exports = {   networks: {
        development: {
          host: "localhost",
          port: 8545,
          network_id: "*" // Match any network id
        }   } };

My geth running on the same port:

    C:\Users\steve\AppData\Roaming\Mist\binaries\Geth\unpacked\geth.exe --testnet --fast --ipcpath \\.\pipe\geth.ipc --rpccorsdomain * --rpcport 8545

I use Geth/v1.6.6-stable-10a45cb5/windows-amd64/go1.8.3

What's wrong?

**Comment by tcoulter** [comment]
Hi there. This error message means Truffle cannot connect to your Ethereum client. There are many reasons for this. For yours, it looks like you need the `--rpc` option for geth as well as your other options.

We have a ticket currently being worked on that will make this error message better. Please see #489. 

Cheers!

**Comment by stiv-yakovenko** [comment]
dear tcoulter, your recipe was correct, --rpc was missing. thanx you!

**Comment by pascal1990** [comment]
@stiv-yakovenko  Please where I should put the --rpc option ?I have the same problem

**Comment by stiv-yakovenko** [comment]
after geth.exe

**Comment by pascal1990** [comment]
@stiv-yakovenko  I use ganache-cli on windows it's possible to do that ?

**Comment by stiv-yakovenko** [comment]
I don't know what it is, ask its authors.

**Comment by prameshbajra** [comment]
I have this error in `ganache`. Did anyone experience similar error? How do I get it fixed?

@pascal1990  did you get it resolved? If yes, how?

**Comment by pascal1990** [comment]
Hi, @prameshbajra  do you have metamask on your browser and which app you tru to run, ganache is a node module
