### ISSUE TITLE
Unhelpful error when using pragma setting and source does not contain pragma expression

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#4928]
If you are using the "pragma" setting while compiling, Truffle will fail unhelpfully if a "direct source" (one supplied by the user in their `contracts` directory) does not contain a pragma expression. The error is something like 
```
TypeError: Cannot read properties of null (reading '1')
at getSemverExpression (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compileWithPragmaAnalysis.js:19:46)
```

Truffle should error, explaining to the user that their "direct sources" must contain pragma expressions while using this setting.

**Comment by haltman-at** [comment]
OK, this should be fixed in 5.5.6.
