### ISSUE TITLE
Contracts not Deploying with Truffle Dashboard

### ISSUE THREAD

**Issue by granthughes1999** [trufflesuite/truffle#4948]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I am trying to deploy a contract to Rinkeby using the truffle dashboard. The first time I ran 

truffle migrate --network dashboard
truffle console --network dashboard

the contract deployed perfectly. However, if I try to re-run these same commands without changing anything. I no longer get the option to process any requests in the dashboard. I simply get the following returned in the terminal 

Compiling your contracts...
> Everything is up to date, there is nothing to compile.
Network up to date.

truffle(dashboard)> 

## Steps to Reproduce

Successfully deploy a contract to Rinkeby one-time using truffle dashboard.
try to duplicate the same deployment without changing any part of any file. Deploy using the following commands. 

truffle dashboard
truffle migrate --network dashboard
truffle console --network dashboard

What you expected to happen.
============================

To see the option to process the deployment requests in the truffle dashboard 

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
=========

My Vscode terminal returns this

Compiling your contracts...
> Everything is up to date, there is nothing to compile.
Network up to date.

And the truffle dashboard has no change and no option to process any incoming requests. 

* Operating System: MacOS Monterey
* Ethereum client: ?
* Truffle version (`v5.5.6`): same issue with version v5.5.3 
* node version (`v14.17.3`): same issue with v16.14.2 
* npm version (`6.14.13`):

**Comment by eggplantzzz** [comment]
This is probably because Truffle sees that you have already deployed your contracts. Normally it checks to see what isn't yet deployed and will only deploy that part of your project. If you want to force a new deployment, you can use the `--reset` flag when running migrations. Let me know if this helps!

**Comment by granthughes1999** [comment]
> This is probably because Truffle sees that you have already deployed your contracts. Normally it checks to see what isn't yet deployed and will only deploy that part of your project. If you want to force a new deployment, you can use the `--reset` flag when running migrations. Let me know if this helps!

@eggplantzzz,

Thank you for the reply. My solution has been to delete the deployed contract.json files from the build/contracts folder..However, your solution appears to be the better way to go about this!

**Comment by eggplantzzz** [comment]
Glad to help! Closing for issue maintenance.
