### ISSUE TITLE
Investigate caching of getChainId responses in the dashboard.

### ISSUE THREAD

**Issue by dkillen** [trufflesuite/truffle#4949]

**Comment by dkillen** [comment]
SWR could be useful to wrap axios requests [https://swr.vercel.app/](https://swr.vercel.app/)

**Comment by eggplantzzz** [comment]
Can you be a little more specific about this issue? Are you referring to inside hdwallet-provider?

**Comment by dkillen** [comment]
@eggplantzzz, @michaeljohnbennett and I thought it might be useful to cache these responses in the dashboard. It's an observation that we made during our recent task force work. It seems that getChainId() could be called frequently. @michaeljohnbennett suggested that something like [https://swr.vercel.app/](https://swr.vercel.app/) would be appropriate.

**Comment by eggplantzzz** [comment]
So this is for caching the chain id while using the dashboard provider? What is causing the chain id to be fetched?

**Comment by michaeljohnbennett** [comment]
the hooks on the dashboard that get the chain name everytime you change networks will do an `axios.get` call.

I had also thought of using a cache of this chainid list to get block explorers or other data but it did seem huge blob of json to be grabbing. If react renders and that was in an effect there is a chance it could be reloaded, using SWR is an industry standard practice in Web2 to cache data like this that is long lived but updated infrequently.

**Comment by rupert1975** [comment]
I hope i how to do it
