### ISSUE TITLE
Migrate to ropsten failed

### ISSUE THREAD

**Issue by userjuan1** [trufflesuite/truffle#4959]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I have attempted to migrate my project to the ropsten network and in doing so, I get an error stating that I have an insufficient balance even though ganache-cli illustates that all accounts have a balance of 1000ETH. I then proceed to check that it is indeed the account being made use of by updating the truffle-config.js file only the get the same error. Any idea why this may be?

## Steps to Reproduce

Step.1 - Install and configure the petshop box.
Step.2 - Download, install and configure HDWalletProvider
Step.3 - Migrate to ropsten network

## Expected Behavior

Expected the migration to complete successfully.

## Actual Results

![ksnip_20220330-125634](https://user-images.githubusercontent.com/88763657/160805106-5edaa1aa-eea2-47ba-b44a-e540335188c6.png)
![ksnip_20220330-130355](https://user-images.githubusercontent.com/88763657/160806506-afc78ec3-8fdc-490a-b9fb-89177a111705.png)

## Environment

* Operating System: Ubuntu 20.04
* Ethereum client: 
* Truffle version (`truffle version`): v5.5.6
* node version (`node --version`): v16.14.2
* npm version (`npm --version`): 8.5.0

**Comment by lsqproduction** [comment]
Hi, @userjuan1 thank you for opening the issue. 
To look into this, can you help to provide us with access to your project repo or a minimal project sample, as well as the CLI commands you used to reproduce the error?

**Comment by userjuan1** [comment]
Hello,

The CLI commands I used are : 

- truffle migrate --network ropsten

Please see below, Migrations.sol sample : 

// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;

contract Migrations {
  address public owner = msg.sender;
  uint public last_completed_migration;

  modifier restricted() {
    require(
      msg.sender == owner,
      "This function is restricted to the contract's owner"
    );
    _;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }
}


And then my truffle-config.js : 

/**
 * Use this file to configure your truffle project. It's seeded with some
 * common settings for different networks and features like migrations,
 * compilation and testing. Uncomment the ones you need or modify
 * them to suit your project as necessary.
 *
 * More information about configuration can be found at:
 * 
 * https://trufflesuite.com/docs/truffle/reference/configuration
 *
 * To deploy via Infura you'll need a wallet provider (like @truffle/hdwallet-provider)
 * to sign your transactions before they're sent to a remote public node. Infura accounts
 * are available for free at: infura.io/register.
 *
 * You'll also need a mnemonic - the twelve word phrase the wallet uses to generate
 * public/private key pairs. If you're publishing your code to GitHub make sure you load this
 * phrase from a file you've .gitignored so it doesn't accidentally become public.
 *
 */

const HDWalletProvider = require('@truffle/hdwallet-provider');
//
const fs = require('fs');
const mnemonic = fs.readFileSync(".secret").toString().trim();

module.exports = {
  /**
   * Networks define how you connect to your ethereum client and let you set the
   * defaults web3 uses to send transactions. If you don't specify one truffle
   * will spin up a development blockchain for you on port 9545 when you
   * run `develop` or `test`. You can ask a truffle command to use a specific
   * network from the command line, e.g
   *
   * $ truffle test --network <network-name>
   */

  networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache-cli, geth or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    // development: {
    //  host: "127.0.0.1",     // Localhost (default: none)
    //  port: 8545,            // Standard Ethereum port (default: none)
    //  network_id: "*",       // Any network (default: none)
    // },
    // Another network with more advanced options...
    // advanced: {
    // port: 8777,             // Custom port
    // network_id: 1342,       // Custom network
    // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
    // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
    // from: <address>,        // Account to send txs from (default: accounts[0])
    // websocket: true        // Enable EventEmitter interface for web3 (default: false)
    // },
    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    ropsten: {
       provider: () => new HDWalletProvider(mnemonic, `https://ropsten.infura.io/v3/ALREADY-SIGNED-UP-WITH-INFURA.IO`),
       network_id: 3,       // Ropsten's id
    // gas: 5500000,        // Ropsten has a lower block limit than mainnet
    // confirmations: 2,    // # of confs to wait between deployments. (default: 0)
    // timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
    // skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    // },
    // Useful for private networks
    private: {
       provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
    // }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.8.13",      // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  },

  // Truffle DB is currently disabled by default; to enable it, change enabled:
  // false to enabled: true. The default storage location can also be
  // overridden by specifying the adapter settings, as shown in the commented code below.
  //
  // NOTE: It is not possible to migrate your contracts to truffle DB and you should
  // make a backup of your artifacts to a safe location before enabling this feature.
  //
  // After you backed up your artifacts you can utilize db by running migrate as follows:
  // $ truffle migrate --reset --compile-all
  //
  // db: {
    // enabled: false,
    // host: "127.0.0.1",
    // adapter: {
    //   name: "sqlite",
    //   settings: {
    //     directory: ".db"
    //   }
    // }
  // }
};

**The error I get when executing the above-mentioned command**(_truffle migrate --network ropsten_)

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
WARNING: Ganache forking only supports EIP-1193-compliant providers. Legacy support for send is currently enabled, but will be removed in a future version _without_ a breaking change. To remove this warning, switch to an EIP-1193 provider. This error is probably caused by an old version of Web3's HttpProvider (or ganache < v7)


Migrations dry-run (simulation)
===============================
> Network name:    'ropsten-fork'
> Network id:      3
> Block gas limit: 8000000 (0x7a1200)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
 *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0xCB74d81a6e735ae68DC1e2c842b05d36065065dC
   * Balance:  0 wei
   * Message:  insufficient funds for gas * price + value -- Reason given: Custom error (could not decode).
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.


Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.


Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0xCB74d81a6e735ae68DC1e2c842b05d36065065dC
   * Balance:  0 wei
   * Message:  insufficient funds for gas * price + value -- Reason given: Custom error (could not decode).
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at setupDryRunEnvironmentThenRunMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:68:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:36:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
Truffle v5.5.6 (core: 5.5.6)
Node v16.14.2


Your help will highly appreciated.
Thank you in advance :+1:

**Comment by userjuan1** [comment]
![ksnip_20220330-201424](https://user-images.githubusercontent.com/88763657/160893267-5a62a7be-847d-4c2f-9b2f-b25a7ee3277f.png)
![ksnip_20220330-201537](https://user-images.githubusercontent.com/88763657/160893387-023a12d6-bbe0-4450-a22e-03a591fea2b5.png)

**Comment by lsqproduction** [comment]
Thank you for sharing those @userjuan1.
It's preferable to have access to the project repo to confirm, but from looking at the information you provided so far I believe you're trying to migrate to the live Ropsten network using an account from the local ganache-UI. 
You may be following our pet shop tutorial (we are in the progress to update it).

If your intention is to actually migrate and deploy on ropsten, then you will need an account with funds on the public blockchain.

If you just want to use ganache for development purposes and test migration, then I would recommend checking out [ganache 7](https://trufflesuite.com/blog/introducing-ganache-7/#c-using-ganache-7-in-the-browser). You can fork the ropsten network by `ganache --fork.network ropsten` and then on a separate terminal window run `truffle migrate`. Let us know how that works out and if we can assist you further.

**Comment by userjuan1** [comment]
Hello again,

Thank you so much for you advice. Please see below output of the advice you have given me :

This is the command line output of : _ganache -h 127.0.0.1 -p 7545 --fork.network ropsten_

ganache v7.0.3 (@ganache/cli: 0.1.4, @ganache/core: 0.1.4)
Starting RPC server

Available Accounts
==================
(0) 0xf33e4BF81FF5a412A06156b3EA0DFce178283058 (1000 ETH)
(1) 0x78481f276bAe0B18dE5C08d9c292B638E0515eFc (1000 ETH)
(2) 0x0E67dC470DF5ff7d9a659c66df5066CdD1eEb9C6 (1000 ETH)
(3) 0x544ccc3Af3C17149632FC11945163349E5c93D14 (1000 ETH)
(4) 0xdb66f8AFB7535b73fd1596f0027F1FEBFB394269 (1000 ETH)
(5) 0xf49Fe0E6AC89B76FE1a22bA7126F63725D021398 (1000 ETH)
(6) 0x8956aa27BCc9486850c0FA0F946716956D2757D8 (1000 ETH)
(7) 0x61645922f8497DF8Cc7f302145C177a9E297274b (1000 ETH)
(8) 0x89E93f8B67c547CA8ecb1A597398c0C451731B38 (1000 ETH)
(9) 0x86E3BB31c65dA1f961Ed1a9040CB42475D709f40 (1000 ETH)

Private Keys
==================
(0) 0x9dc783e84691ec7b6d51f681ebbbeb07ca027b48aa506027204102c9a6654688
(1) 0x0070b4395f8f56e21903b8a6204b6ac66a997aa84ec1322818362b5df9380e45
(2) 0xdaeaca4775582c3f2f23f0326e9cfb80091d196c09dd953a939d03d69f1e1058
(3) 0x3689316291771bd5457fbd8da65783391eee3b7cf712b62fd46e4f7a78c286fb
(4) 0xdfd6404cfabea39119986be197af61ee9e9eb2aad17fc691afa5e855699e5cf0
(5) 0x6be06b6d87821a190e9e0407d0affad0ceaab366b6741a266b31ca2e2c940416
(6) 0x97cba09734592a15b78e310f09dcabc574192777b1c8f35613a0f2fe4deb68b4
(7) 0x3e178e121ac2fcb2c0bbe6ffef1601d8d2bcb71589e3c0d894f765b594fbcdfd
(8) 0xa6f9c2b61fd517c924979029c16c1369c9b30c5c76221abc90d1f7e8636e4342
(9) 0x507bd17129c2a08726e3b42d5fed330587c71d077cd910fa832ea785c5f545f2

HD Wallet
==================
Mnemonic:      initial castle resemble museum eye gentle tobacco hover machine vote garbage coach
Base HD Path:  m/44'/60'/0'/0/{account_index}

Default Gas Price
==================
2000000000

BlockGas Limit
==================
30000000

Call Gas Limit
==================
50000000

Forked Chain
==================
Location:        Ethereum Ropsten, via 丕Infura
Block:           12152099
Network ID:      3
Time:            Thu Mar 31 2022 19:32:42 GMT+0300 (Eastern European Summer Time)

Chain Id
==================
1337

RPC Listening on 127.0.0.1:7545
eth_blockNumber
net_version
eth_blockNumber
net_version
eth_blockNumber
net_version
eth_accounts
eth_accounts
eth_getBlockByNumber
eth_chainId
eth_getBlockByNumber
net_version
eth_getTransactionCount
eth_blockNumber
net_version
eth_accounts
eth_accounts
eth_getBlockByNumber
eth_chainId
eth_getBlockByNumber
net_version
eth_getTransactionCount

Apart from that I have updated my .secrets file as added good measure with the relevant priv key and/or mnemonic although when I issue truffle migrate, it just hangs, see below output:

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
WARNING: Ganache forking only supports EIP-1193-compliant providers. Legacy support for send is currently enabled, but will be removed in a future version _without_ a breaking change. To remove this warning, switch to an EIP-1193 provider. This error is probably caused by an old version of Web3's HttpProvider (or ganache < v7)


That's all I see. Please help!

**Comment by lsqproduction** [comment]
Can you help to inform me which one is your intention? To deploy on ropsten or just test locally on ganache? If you're wanting to test locally. No provider is needed as ganache is doing it for you already

**Comment by userjuan1** [comment]
I'd like to deploy on ropsten and then to respond to you latest message, is my project has always been up-to-date to compiled, so the build dir is not new. Please could you help me deploy to ropsten?

**Comment by userjuan1** [comment]
Alternative, what would be the best way to get my project migrated to a live blockchain?

**Comment by lsqproduction** [comment]
To deploy to ropsten, you will need an account with ropsten ETH instead of the ganache account. ( please note that ganache is a local blockchain environment and its eths are only useful for the local development and testing purpose.

**Comment by userjuan1** [comment]
Good day,

Thank you so much for your help. Please see below : 

![ksnip_20220401-103234](https://user-images.githubusercontent.com/88763657/161216705-34a55548-db39-4398-b63d-019f12b935bb.png)

![ksnip_20220401-103145](https://user-images.githubusercontent.com/88763657/161216748-e124cc8d-75a4-48ca-b034-c349e6c4aa59.png)


All checks out okay. Couldn't be more thankful for your help.

**Comment by lsqproduction** [comment]
Great to hear @userjuan1. Closing this issue now.
