### ISSUE TITLE
Indexed events cause Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Ericxgao** [trufflesuite/truffle#496]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to transfer funds (with or without metamask) on the truffle webpack demo causes an error with ethjs-abi decodeEvent - topics is undefined.

I have narrowed this issue down to something having to do with event indexing - if I remove the indexed parameters from the Transfer event in the MetaCoin contract, this issue does not occur.

## Steps to Reproduce

On Windows
Prompt1
truffle.cmd init webpack

Prompt2
testrpc

Prompt1
truffle.cmd compile
truffle.cmd migrate
npm run dev

Go to localhost:8080 and attempt to transfer funds to any address

## Expected Behavior

Fund transfer succeeds and website shows success status

## Actual Results
Transaction succeeds but console error is thrown on ethjs-abi decodeEvent - I'm not sure if it's an issue on their end or truffle's.

![image](https://user-images.githubusercontent.com/6610675/28185001-89d9afae-67ca-11e7-955e-d6996f57c7b7.png)

## Environment

* Operating System: Windows 10
* Truffle version: 3.3.0
* node version: 6.11.0
* npm version: 5.0.3

**Comment by ollivierv** [comment]
Same issue on truffle@3.4.4

**Comment by tcoulter** [comment]
Story points: 1

**Comment by tcoulter** [comment]
This one has also been reported at ethjs/ethjs-abi#6.

**Comment by tcoulter** [comment]
This has no been fixed. See my comment in ethjs/ethjs-abi#6. 

Cheers!
