### ISSUE TITLE
Create consistent Button elements for use across the UI

### ISSUE THREAD

**Issue by michaeljohnbennett** [trufflesuite/truffle#4971]
Add in a consistent react component or buttons to allow singular source of truth for button design across the UI.

Work done in other branch (pending tx views) extracted out into a single PR.

**Comment by cliffoo** [comment]
Resolved in the [newest Truffle release](https://github.com/trufflesuite/truffle/releases/tag/v5.5.19). Thanks @michaeljohnbennett!
