### ISSUE TITLE
vs code unable to resolve truffle command

### ISSUE THREAD

**Issue by BenZogia** [trufflesuite/truffle#4973]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by leeftk** [comment]
Hey @BenZogia , thanks for raising this. Would you mind sending over some reproduction steps and also giving us some information on your environment, specifically what version of Truffle you're using? Thanks!

**Comment by fainashalts** [comment]
Hi @BenZogia, we haven't heard back from you about this issue. Hopefully it is resolved! I'm closing this for issue maintenance, but please feel free to open a new issue if you still need assistance!
