### ISSUE TITLE
The test helper function `isAddress` always throw `TypeError: number.equals is not a function`

### ISSUE THREAD

**Issue by ASmallPotato** [trufflesuite/truffle#4992]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

the test helper function `assert.isAddress` seems to always throw an `TypeError: number.equals is not a function` error

## Steps to Reproduce

in a test case, using the `isAddress` assertion will throw the error. e.g.

```js
contract("SomeContractName", accounts => {
  it("should allow us to reproduce isAddress issue", () => {
    assert.isAddress(accounts[0])
  });
});
```

## Expected Behavior

it should pass when the input is a normal address, and report when the input is not an address. In no case should it report "TypeError: number.equals is not a function"

## Actual Results

using the function will report the following 
```
1) Contract: SomeContractName
       should allow us to reproduce isAddress issue:
     TypeError: number.equals is not a function
      at Assertion.<anonymous> (node_modules/truffle/build/webpack:/packages/core/lib/assertions.js:18:1)
      at Assertion.propertyGetter (node_modules/truffle/build/webpack:/node_modules/chai/lib/chai/utils/addProperty.js:62:1)
      at Reflect.get (<anonymous>)
      at Object.proxyGetter [as get] (node_modules/truffle/build/webpack:/node_modules/chai/lib/chai/utils/proxify.js:98:1)
      at Function.assert.isAddress (node_modules/truffle/build/webpack:/packages/core/lib/assertions.js:24:1)
      at Context.<anonymous> (test/store.js:29:12)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Extra Information

I didn't have experience with this repository (or it's dependency), but just from reading the stack trace and source code on github, the error seems to be coming from the following file [https://github.com/trufflesuite/truffle/blob/56d22d731bad43d4b945565af54a266cdf6b1723/packages/core/lib/assertions.js#L16-L18](https://github.com/trufflesuite/truffle/blob/56d22d731bad43d4b945565af54a266cdf6b1723/packages/core/lib/assertions.js#L16-L18)
which get the "number" from calling `toBN` from the package "web3-utils", which should return an `BN` instance from the package "bn.js". From reading the doc in it's readme, `BN` uses `eq` to test for equality instead of `equals`.

## Environment

* Operating System: Arch linux
* Ethereum client: ganache (cli)
* Truffle version (`truffle version`): v5.5.2 (core: 5.5.2)
* node version (`node --version`): v17.4.0
* npm version (`npm --version`): 8.3.1

**Comment by eggplantzzz** [comment]
Hey @ASmallPotato, `assert` comes from the npm package chai. `isAddress` is not a chai method and the concept of an Ethereum address has no meaning in JavaScript unless you are using a package specifically designed for this.

You may be trying to use Truffle's testing Solidity library `Assert.sol` which is only available if you are writing Solidity tests. That has some functionality where you can do something like `Assert.address(<someValue>)`. You can find some docs about using this library on our website [here](https://trufflesuite.com/docs/truffle/testing/writing-tests-in-solidity/).

**Comment by ASmallPotato** [comment]
Hi @eggplantzzz thank you for looking into this :)

I understand that `assert` is from chai, and yes, `isAddress` is not from/included in the chai package. However it seems to me that there is an `isAddress` function and it is injected by truffle into the `assert` object (as mention in the "Extra Information" section in the original comment/issue), and it always throw error :(

p.s. Test case in solidity is nice but isn't really the context of the original issue, thanks for the suggestion tho :)

**Comment by haltman-at** [comment]
Huh, it looks like we do actually add an `isAddress` method to chai!  Crazy.  OK, guess this will have to be fixed.

**Comment by haltman-at** [comment]
OK, I've put up PR #5033 which should fix this.

**Comment by eggplantzzz** [comment]
Thanks for reporting this @ASmallPotato!

**Comment by haltman-at** [comment]
The fix for this is now out!

**Comment by ASmallPotato** [comment]
Sorry I was on holiday for the past few days, but thanks everyone for fixing & looking into this :)
