### ISSUE TITLE
Deployment scripts with async/await

### ISSUE THREAD

**Issue by mezrin** [trufflesuite/truffle#501]
It is possible to configure test scripts to work with async/await. (JavaScript test scripts, of course).

It would be amazing to have the same for deployment scripts. Because all that `.then` really destroy readability of deployment scripts.

**Comment by travs** [comment]
I have my *tests* working with async/await right now, but I do have difficulty using async/await syntax in my *migrations* scripts for some reason. 
It seems like lines after the first await call get skipped sometimes.
Not sure if this is just my setup, or if anyone else experience the same thing.

Using Node v8.1.3.

**Comment by brynbellomy** [comment]
Happens to me as well, Node 8.1.3, Truffle 3.4.8.

**Comment by felixwatts** [comment]
+1

**Comment by elenadimitrova** [comment]
Same here, I had symptoms of #386 when trying to use async/await in migrations

**Comment by tcoulter** [comment]
When writing migrations, remember that your migration function *stages* deployment tasks -- it's not intended to run those takes at execution time of that function. This behavior and Promise structure was built in a time when `async/await` was less prevalent. 

We plan on making migrations work with `async/await` in the future. However, in the meantime, if you'd like to use `async/await` in your migrations, follow this pattern:

2_some_migration.js
```
var SomeContract = artifacts.require("SomeContract");

// An async function
const someAsyncFunction = async function someAsyncFunction() {
  // ...
};

// Your actual migration
module.exports = (deployer) => {
  deployer.deploy(SomeContract).then(() => someAsyncFunction())

  // Alternatively, just start a chain without a deployment
  deployer.then(() => someAsyncFunction())
}
```

This will ensure your `async` functions are executed at the right time, and those steps are added to the Promise chain.

Again, we will be revamping this in the future. Would love to hear your thoughts on how migrations could be made easier.

**Comment by tcoulter** [comment]
Edit: I wrote that code on the fly; didn't test it. Please correct me if there are any typos!

**Comment by rodiazet** [comment]
I'm trying to use this workaround but it seems that it doesn't have change to work. It's not possible to wrap call with await inside non-async function.  So `() => await someAsyncFunction()` won't work or I'm missing something important?

**Comment by shkfnly** [comment]
@rodiazet what he meant was 
```
  var SomeContract = artifacts . require ( " SomeContract " );

 // An async function
 const someAsyncFunction = async function someAsyncFunction () {
   // ...
 };

 // Your actual migration
 module . exports = ( deployer ) => {
   deployer . deploy (SomeContract). then (() => await someAsyncFunction ())

   // alternative, just start a chain without a deployment
   deployer . then (async() => await someAsyncFunction ())
 } 
```
I wrapped all this together like 

```
module.exports = function (deployer) {
  deployer.then(async () => {
    await deployer.deploy(Division)
    await deployer.link(Division, [DistributeToken, ProjectLibrary, ReputationRegistry, TokenRegistry, Project])
    await deployer.deploy(ProjectLibrary)
    await deployer.link(ProjectLibrary, [TokenRegistry, ReputationRegistry, ProjectRegistry])
    await deployer.deploy(TokenRegistry)
    await deployer.deploy(ReputationRegistry)
    await deployer.deploy(ProjectRegistry)
    await deployer.deploy(DistributeToken, TokenRegistry.address, ReputationRegistry.address)
    await deployer.deploy(PLCRVoting, TokenRegistry.address, ReputationRegistry.address, ProjectRegistry.address)

    let PRInstance = await ProjectRegistry.deployed()
    let TRInstance = await TokenRegistry.deployed()
    let RRInstance = await ReputationRegistry.deployed()
    return Promise.all([
      PRInstance.init(DistributeToken.address, TokenRegistry.address, ReputationRegistry.address, PLCRVoting.address),
      TRInstance.init(DistributeToken.address, ProjectRegistry.address, PLCRVoting.address),
      RRInstance.init(DistributeToken.address, ProjectRegistry.address, PLCRVoting.address)
    ])
  })
}
```
Hope this helps!

Shout out to http://y-nakajo.hatenablog.com/entry/2018/01/15/174743
and https://ethereum.stackexchange.com/questions/30572/truffle-post-deployment-actions
for the insight

**Comment by kigawas** [comment]
@shkfnly Thanks for sharing 👍

**Comment by code-brewer** [comment]
> It seems like lines after the first await call get skipped sometimes.

Yes, i encountered this issue with node v8.10.0, it look like await() don't return but the test flow exited normally. Finally i upgrade nodejs to 9.11.1.

**Comment by saeedjaafari** [comment]
hi dear
i gave this problem :

`    
truffle(develop)> var poe = await ProofOfExistence1.at(ProofOfExistence1.address)
Uncaught:
Error: ProofOfExistence1 has no network configuration for its current network id (5777).
    at evalmachine.<anonymous>:1:48
    at Function.getter (c:\Users\Apple\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\contract\constructorMethods.js:282:1)
    at Function.get (c:\Users\Apple\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\contract\properties.js:129:1)
    at Function.getter (c:\Users\Apple\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\contract\constructorMethods.js:285:1)
    at Function.network (c:\Users\Apple\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\contract\properties.js:108:1)`

how can i solved it??
thx
