### ISSUE TITLE
Truffle Dashboard showing error "truffle" not found in cmdlet, etc

### ISSUE THREAD

**Issue by SwapnilG1** [trufflesuite/truffle#5016]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
Hi, I was able to install yarn, node.js and npm correctly and was also able to check the version. Also I am able to install truffle globally with some vulnerabilities, but when I try to run the command 'truffle dashboard' it displays an error command not found. Please also note that I am using Visual Studio Code as an administrator and my system is Windows 10.

**Comment by eggplantzzz** [comment]
See [this issue](https://github.com/trufflesuite/truffle/issues/5013). In your case you should try using the Windows equivalent of nvm.

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
