### ISSUE TITLE
Look into using `solc`'s parser instead of `solidity-parser`, so we can stay up to date with language features.

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#502]

**Comment by tcoulter** [comment]
More info here: https://github.com/ethereum/solc-js/issues/5

**Comment by HaleTom** [comment]
This would be great... I've been trying to work out how to use `solc 0.4.17` and this issue explains why forcing the module to that version still doesn't work.

**Comment by gnidan** [comment]
Believe this is done. Will verify for next release by ensuring `solidity-parser` does not exist as a dependency in the bundle

**Comment by gnidan** [comment]
<img width="747" alt="screen shot 2017-11-02 at 1 41 24 pm" src="https://user-images.githubusercontent.com/151065/32341310-902c3460-bfd3-11e7-8065-e6414e54aaae.png">
Gone!
