### ISSUE TITLE
Truffle Config instantiates providers for all defined networks and sends API requests on deployment even if network is not selected.

### ISSUE THREAD

**Issue by tenthirtyone** [trufflesuite/truffle#5025]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Given the following `truffle-config.js`

``` javascript
matic: {
provider: () => {
        return new HDWalletProvider(
          maticMnemonic,
          `https://polygon-mumbai.infura.io/v3/MUMBAIKEY`
        );
      },

      network_id: 80001,
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true,
    },
   
      network_id: 3,
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true,
    },
    rinkeby: {
      provider: () => {
        return new HDWalletProvider(
          maticMnemonic,
          `https://rinkeby.infura.io/v3/RINKEBYKEY  `
        );
      },

      network_id: 4,
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true,
    },
```

While deploying Truffle will make RPC calls to all networks defined in config. Performing a deployment to Rinkeby will send requests to the mumbai project endpoint and vice versa for n number of defined networks.

## Steps to Reproduce

1. Signup for Infura
2. Create two projects, to receive two separate project keys. For this test I used Polygon Mumbai and Ethereum Rinkeby but you could use Rinkeby/Ropsten if you like or any combination.
3. Deploy a contract to one of the networks. 
4. Watch the dashboard, both project API call counts will increase

## Expected Behavior
Truffle should not consume unnecessary API calls, certainly not from networks that are unused.

## Actual Results

For 1 contract deployment
![image](https://user-images.githubusercontent.com/6285466/163442348-ca1f5184-7dc4-4b9f-87c0-7c9906268974.png)

For 4 contract deployments, same migration file.
![image](https://user-images.githubusercontent.com/6285466/163440514-74f8eb69-afc7-441f-b759-1adb5ff2848e.png)

Removing the function thunk and defining the provider outside of the config will help to mitigate by reducing the number of providers instantiated but does not solve the issue:

```
const hdt = new HDWalletProvider(
  maticMnemonic,
  `https://polygon-mumbai.infura.io/v3/MUMBAIKey`
);
matic: {
  provider: hdt,

  network_id: 80001,
  confirmations: 0,
  timeoutBlocks: 200,
  skipDryRun: true,
},
```

Results for 3 contract deploys: 34 -> Reduction in 1/3 of unnecessary calls to mumbai project API endpoint when deploying to Rinkeby

## Environment

* Operating System: UBUNTU
* Ethereum client:
* Truffle version (`truffle version`): 5.5.3 (confirmed in latest dev and in `provider-changes` branch)
* node version (`node --version`): 12.22.7
* npm version (`npm --version`):

**Comment by cds-amal** [comment]
I could not reproduce this behavior by with a `truffle-config` that has two thunked providers, `ganache1` and `ganache2` that resolve to two running ganache instances (serving port 8545 and 9545 respectively). Note, it is helpful to have both ganache terminals visible while executing the two tests below.

<details><summary>truffle-config.js</summary>

```javascript
const HDWalletProvider = require("@truffle/hdwallet-provider");
const mnemonic = "window twenty cat alone physical foam smoke annual collect pluck educate course";

module.exports = {
  networks: {
    ganache1: {
      provider: () => {
        return new HDWalletProvider( mnemonic, "http://127.0.0.1:8545");
      },
      network_id: "*",
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true,
    },
    ganache2: {
      provider: () => {
        return new HDWalletProvider( mnemonic, "http://127.0.0.1:9545");
      },
      network_id: "*",
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true,
    },
  },
  compilers: {
    solc: {
      version: "^0.8.0"
    }
  }
}
```
</details>

- [√] migrate to network ganache1 only resolves the ganache1 provider
   ```console
   $ truffle migrate --network ganache1 --reset
   ```
- [√] migrate to network ganache1 only resolves the ganache2 provider
   
   ```console
   $ truffle migrate --network ganache2 --reset
   ```

**Comment by tenthirtyone** [comment]
This one is on me. I was messing with providers trying to get the `Block Polling Error` to throw and had a provider in a project that was not part of truffle's source control. So when I was changed branches it was still in the project when I was doing the deployment and the extra hits I saw were from the provider checking in when it is created.
