### ISSUE TITLE
Truffle migration issue -Cannot read properties of undefined (reading 'replace') @trufflehd-wallet

### ISSUE THREAD

**Issue by Abhishek-M-Rao** [trufflesuite/truffle#5031]
## Issue

Truffle migration issue - TypeError: Cannot read properties of undefined (reading 'replace')

## Steps to Reproduce

I was following this video https://youtu.be/8ElPDw0laIo - this is at 45 mins when he starts to setup the smart contract connecting to the infura api using metamask - basically how the truffle-config.js is supposed to be set up. I have tried this thread (https://github.com/trufflesuite/truffle/issues/1989) returning a new hdwallet and I have an identical error. This is what I have right now.
![trufconfig](https://user-images.githubusercontent.com/70395274/163898198-8536257a-83ef-4da6-955f-a1da4c418a92.PNG)

## Expected Behavior

I want the truffle migrate --network rinkeby command to successfully deploy my contract using my infura api key - result should look like this 
![expected](https://user-images.githubusercontent.com/70395274/163898307-ae887d75-ead1-437f-a169-ab96ca61a9d9.PNG)

## Actual Results
![error messagee](https://user-images.githubusercontent.com/70395274/163897683-c507d1fb-05b1-47d3-b782-f55e64818f3a.PNG)

## Environment

* Operating System: Windows 10
@truffle/hdwallet-provider": "^2.0.6"
truffle version: v5.5.3
Node: v16.14.0
npm: 8.3.1

**Comment by eggplantzzz** [comment]
Hey @Abhishek-M-Rao! Can you verify that you have valid values for some of your variables? Can you log out the values for `private_keys` and `process.env.INFURA_API_KEY`? You just need to make sure you have an `.env` file that contains valid values for those variables. If you get a chance to check this then let me know how it goes!

**Comment by Abhishek-M-Rao** [comment]
@eggplantzzz Thank you so much for offering to help. It was a silly issue, I forgot the "()" next to "require("dotenv".config" on line 1 haha. When I did print out the variables they were undefined which led me to finding this issue. Thank you for the help again, I will let you know if I have any more issues. 
-Abhi
