### ISSUE TITLE
Can not install truffle successfully

### ISSUE THREAD

**Issue by Confucian-e** [trufflesuite/truffle#5043]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
![Screenshot from 2022-04-22 18-27-21](https://user-images.githubusercontent.com/46948182/164693969-4f7509c1-6662-43c3-9332-f353197e2adf.png)

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cds-amal** [comment]
Hi @Confucian-e, Truffle doesn't currently support Node v17 or v18. We're working on it and in the meantime you can try using Node v12, v14 or, v16.

**Comment by Confucian-e** [comment]
Got it !

**Comment by SamarpanCoder2002** [comment]
@cds-amal it's giving the same prb in the latest version of node... When that package will available for latest version of node???

**Comment by cds-amal** [comment]
> it's giving the same prb in the latest version of node... When that package will available for latest version of node???
@SamarpanCoder2002, do you mean Node 18?  Truffle supports node 12, 14 and 16. We are currently working on supporting node 18. 

Is it possible for you to use node 16?
