### ISSUE TITLE
help cant install truffle

### ISSUE THREAD

**Issue by samdupnamgyal** [trufflesuite/truffle#5052]
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/truffle
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'
npm ERR! [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle'] {
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'mkdir',
npm ERR! path: '/usr/local/lib/node_modules/truffle'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/sam/.npm/_logs/2022-04-24T13_42_37_145Z-debug-0.log
sam@SAMs-MacBook-Pro nft-erc721-collection-2.3.0 % root/Administrator
zsh: no such file or directory: root/Administrator
sam@SAMs-MacBook-Pro nft-erc721-collection-2.3.0 %

**Comment by cds-amal** [comment]
Closing for issue maintenance.
