### ISSUE TITLE
error while installing truffle please help

### ISSUE THREAD

**Issue by Nikhilkumarravula** [trufflesuite/truffle#5060]
## Issue

@LAPTOP-32743VDV:~/web3py$ sudo npm install -g truffle
[sudo] password for ravula:
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/truffle
npm ERR! dest /usr/local/lib/node_modules/.truffle-ojTgnptm
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/truffle' -> '/usr/local/lib/node_modules/.truffle-ojTgnptm'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-27T15_32_22_131Z-debug-0.log
@LAPTOP-32743VDV:~/web3py$

**Comment by eggplantzzz** [comment]
Hey @Nikhilkumarravula, using `sudo` while installing Truffle can cause permissions errors and should be avoided. My advice would be to re-install Node and npm using a Node version manager like nvm. This is what npm recommends, you can check out [this npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) about doing this. If you get a chance to try, then let us know how it goes!
