### ISSUE TITLE
`truffle console` should allow `--url` option like debugger does

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#5063]
## Issue

I've had some cases recently where this would be useful.  Basically just to get a console that connects to a specified url, potentially outside of a Truffle project, but with all the nice things that Truffle Console provides you for free (such as a `web3` object and `accounts`), except of course that if you're outside of a Truffle project there won't be any contracts.

## Environment

* Truffle version (`truffle version`): 5.5.11

**Comment by lsqproduction** [comment]
Added in [Truffle 5.5.20](https://github.com/trufflesuite/truffle/releases/tag/v5.5.20).
