### ISSUE TITLE
Switch truffle's default from "strict" to "eager" until WebSockets is the default communication mode.

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/truffle#5065]
Update to Ganache v7 should be faster than v6, but many users don't experience this in many (most?) cases as Truffle's web3 must poll for changes (example: https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/523).

If truffle updates to using WebSockets this polling behavior won't occur. In the meantime, I think we should switch our default mode to "eager" (which is also Ganache v7's default).

There _is_ a way to make Ganache behave as if it was in eager mode for messages sent over HTTP connections only, but doing it is very hacky and gross, as it makes the RPC logic change based on the connection kind. So I'd rather not do this (I actually [did do it already](https://github.com/trufflesuite/ganache/compare/3acc35e2e121e8ef2bcebbb3aa5eeec360fc58cf...8b15e3c1aebc4c99a217438fad3d1c208c662f5e), and it really is horrible).

**Comment by gnidan** [comment]
The issue here is that Web3.js's polling behavior means that with HTTP providers, **each transaction in `truffle test` takes _at least one-thousand milliseconds_**, oh my.

We'll want to reevaluate the need for the strict->eager switch after #4637 resolves

**Comment by kevinbluer** [comment]
Heads up that this is addressed in https://github.com/trufflesuite/truffle/pull/5407 👌
