### ISSUE TITLE
I AM HAVING TROUBLE DOWNLOADING TRUFFLE 

### ISSUE THREAD

**Issue by mexicanpepe** [trufflesuite/truffle#5069]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue  ** I AM HAVING TROUBLE DOWNLOADING TRUFFLE 5.1.39 

Josephs-MacBook:~ mexicanpepe$ npm install -g truffle@5.1.39
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
/Users/mexicanpepe/‘~/.npm-global’/bin/truffle -> /Users/mexicanpepe/‘~/.npm-global’/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.39 postinstall /Users/mexicanpepe/‘~/.npm-global’/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.1.39
added 20 packages from 7 contributors, removed 1110 packages, updated 46 packages and moved 4 packages in 35.593s

Josephs-MacBook:~ mexicanpepe$ node -v
v14.16.0
Josephs-MacBook:~ mexicanpepe$ npm -v
6.14.11
Josephs-MacBook:~ mexicanpepe$ truffle -v
-bash: truffle: command not found
Josephs-MacBook:~ mexicanpepe$ clear

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

Josephs-MacBook:~ mexicanpepe$ npm install -g truffle@5.1.39
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/debug-js/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
/Users/mexicanpepe/‘/.npm-global’/bin/truffle -> /Users/mexicanpepe/‘/.npm-global’/lib/node_modules/truffle/build/cli.bundled.js

truffle@5.1.39 postinstall /Users/mexicanpepe/‘~/.npm-global’/lib/node_modules/truffle
node ./scripts/postinstall.js

Fetching solc version list from solc-bin. Attempt https://github.com/trufflesuite/truffle/pull/1
truffle@5.1.39
added 20 packages from 7 contributors, removed 1110 packages, updated 46 packages and moved 4 packages in 35.593s
Josephs-MacBook:~ mexicanpepe$ node -v
v14.16.0
Josephs-MacBook:~ mexicanpepe$ npm -v
6.14.11
Josephs-MacBook:~ mexicanpepe$ truffle -v
-bash: truffle: command not found
Josephs-MacBook:~ mexicanpepe$ clear

I am trying to download Truffle and having errors
## Environment
MAC OS Monterey
* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`14.16.0):
* npm version (`6.14.11`):

**Comment by mexicanpepe** [comment]
I also tried to download via npm install -g truffle and its not working 
when i try  " truffle -v"
I get error message   -bash: truffle: command not found

**Comment by eggplantzzz** [comment]
Hey @mexicanpepe. Looks like there is something wrong with the way npm is configured. The directory where it installs globally-installed packages needs to be in your `$PATH` variable. I usually recommend re-installing npm and Node with a Node version manager like nvm which is what npm recommends. You can check out [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). This hopefully will correctly add the necessary director(y|ies). Let me know how it goes.

**Comment by YungKingz** [comment]
I'm Having the same problem... how can i fix this?

yungkingz@Yungs-MBP ~ % npm install truffle --g@5.1.39

> truffle@5.5.13 postinstall /Users/yungkingz/node_modules/truffle
> node ./scripts/postinstall.js

npm WARN saveError ENOENT: no such file or directory, open '/Users/yungkingz/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/yungkingz/package.json'
npm WARN yungkingz No description
npm WARN yungkingz No repository field.
npm WARN yungkingz No README data
npm WARN yungkingz No license field.

+ truffle@5.5.13
updated 1 package and audited 1909 packages in 8.614s

100 packages are looking for funding
  run `npm fund` for details

found 56 vulnerabilities (20 low, 16 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
yungkingz@Yungs-MBP ~ % truffle -v
zsh: command not found: truffle

**Comment by lsqproduction** [comment]
Hi @YungKingz, can you try the command `npm install -g truffle@5.1.39` if you're looking for specifically version 5.1.39.
Otherwise, you should be able to install the latest version of Truffle with `npm install -g truffle`. Let us know how these works out for you.
