### ISSUE TITLE
Truffle is not picking up latest solidity version from truffleconfig.js

### ISSUE THREAD

**Issue by priyochatterjee08** [trufflesuite/truffle#5073]
Added following snippet in truffle-config.js file:
```javascript
compilers: {
  solc: {
    version: "0.8.13",
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
```
I am getting the following error while compiling:
Error: Truffle is currently using solc 0.5.16, but one or more of your contracts specify "pragma solidity 0.8.13".
However, truffle compile --list is showing:
[
"0.8.13",
"0.8.12",
"0.8.11",
"0.8.10",
"0.8.9",
"0.8.8",
"0.8.7",
"0.8.6",
"0.8.5",
"0.8.4"
]
I have tried truffle compile --all , but getting same error
Please help

**Comment by eggplantzzz** [comment]
Hey @priyochatterjee08! Can you supply your entire `truffle-config.js`? Is your project on GitHub and can you provide a link to it? It seems likely that something is misconfigured in `truffle-config.js`.

**Comment by priyochatterjee08** [comment]
@eggplantzzz Thank you for your response. My truffle-config.js is attached. I am trying to implement the following project in 0.8.13 solidity version, and want to do necessary changes in smart contracts.

https://github.com/Calpoog/blockchain-ticketing

module.exports = {
  migrations_directory: "./migrations",
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" // Match any network id
    },
    compilers: {
      solc: {
        version: "0.8.13",              
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
   },
    gui: {
      host: "localhost",
      port: 7545,
      network_id: "*" // Match any network id
    }
  }
};

**Comment by eggplantzzz** [comment]
Your `compilers` specification is in the `networks` object. You need to put `compilers` at the top level of the exported object at the same level as `networks`. Then you should be good to go!

**Comment by priyochatterjee08** [comment]
Thanks a lot.
