### ISSUE TITLE
truffle test: Error: Cannot find module 'babel-runtime/core-js/object/entries'

### ISSUE THREAD

**Issue by dibi91** [trufflesuite/truffle#5074]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

`truffle test` command exception

## Steps to Reproduce

Create a simple truffle project and launch test:
1. `truffle init`
2. `truffle create contract TestBabelRuntimeException`
3. `truffle create test TestBabelRuntimeException`
4. `truffle test`

## Expected Behavior

Tests should be executed.

## Actual Results

Test command return an exception: `Error: Cannot find module 'babel-runtime/core-js/object/entries`

![Screenshot from 2022-05-03 16-15-58](https://user-images.githubusercontent.com/34476725/166470852-d382d7ff-f73c-45d4-9daa-f448159d68e1.png)

## Environment

* Operating System: ubuntu 20.04
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.5.12
* node version (`node --version`): 16.15.0
* npm version (`npm --version`): 8.5.5

## Additional infos
test command work as expected with 4.1.17 version, tried also v5.4.33 and got error too.

**Comment by hickscorp** [comment]
Having the same error when using the `debug 0x...` from the truffle console...

**Comment by athenayay** [comment]
This is due to the latest update - https://www.npmjs.com/package/truffle

is there a way to revert back to old version :)

A

**Comment by ngochiencse** [comment]
Me too. It seems to be wrong linking with package babel runtime.
Fortunately you can temporary fix this problem by running the following command:
`npm install -g babel-runtime`
In the meantime, we should fix this problem or at least update the documentation immediately.

**Comment by zj95120** [comment]
same problem

**Comment by YashNagiReddy7** [comment]
After a bit of continued testing it seems like you'll want to use truffle v5.1.39 as I was able to get that version to work, so you'll want to do:
<npm uninstall -g truffle>
<npm install -g truffle@5.1.39>

**Comment by dibi91** [comment]
> npm install -g babel-runtime

Nope, that version didn't work too.
Installed babel runtime globally as @ngochiencse suggested, work as a workaround.

**Comment by cds-amal** [comment]
Thanks for raising this @dibi91 !

I've confirmed the behavior on Ubuntu (20.04)/Truffle v5.5.12. We recently updated a dependency that should fix this in the next release. See [screencast.](https://asciinema.org/a/ATl5HBFxaI7rY9bx5XqN2dWXo)

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by ngochiencse** [comment]
It worked!

**Comment by haltman-at** [comment]
OK, can people try this again with Truffle 5.5.13?  Thanks!

**Comment by SebGazeau** [comment]
With 5.5.13 it works for me !

**Comment by cds-amal** [comment]
@dibi91 can you confirm Truffle v5.5.13 resolves the issue?

**Comment by dibi91** [comment]
> @dibi91 can you confirm Truffle v5.5.13 resolves the issue?

Yes, it's working perfectly! Thank you!
