### ISSUE TITLE
online truffle docs link to localhost:9000

### ISSUE THREAD

**Issue by Gustav-Simonsson** [trufflesuite/truffle#508]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

At http://truffleframework.com/docs/advanced/configuration there is a link to
`http://localhost:9000/docs/advanced/build_processes` and there's a few other such links.

## Steps to Reproduce

Navigate to online docs.

## Expected Behavior

Link pointing to actual host.

## Actual Results

Link points to localhost.

## Environment

Online Truffle docs.

**Comment by tcoulter** [comment]
Fixed, thanks!
