### ISSUE TITLE
Idk why Truffle is not downloading =(

### ISSUE THREAD

**Issue by YungKingz** [trufflesuite/truffle#5091]
yungkingz@Yungs-MBP ~ % npm install truffle@5.1.39
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 25 packages, removed 1038 packages, changed 45 packages, and audited 144 packages in 23s

44 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
yungkingz@Yungs-MBP ~ % truffle version
zsh: command not found: truffle

## Environment

* Operating System: Monterrey
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`v14.16.0`):
* npm version (`8.9.0`):

**Comment by YungKingz** [comment]
@eggplantzzz Thank you I was able to fix it by following the instruction luckily I found a video on youtube going through the process. 
<img width="1117" alt="Screen Shot 2022-05-09 at 9 27 41 PM" src="https://user-images.githubusercontent.com/105086241/167524549-938a8a06-6a8e-4d7b-bd76-c3df170744b9.png">

**Comment by eggplantzzz** [comment]
Glad to hear you got it resolved! Looks like you have an old version of Truffle, try upgrading to the latest which I think is version 5.5.13. `npm install -g truffle` should do it.

**Comment by YungKingz** [comment]
@eggplantzzz I'm doing a course that I purchase to learn blockchain and he said to download this version for the project I'm building but i'm sure ill use that version soon.
