### ISSUE TITLE
TypeError: Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by CVRD-Dev** [trufflesuite/truffle#5096]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

TypeError: Cannot read property 'layout' of undefined when trying to deploy contract for test using truffle-upgrades.deployProxy

## Expected Behavior
Contract is deployed to unit test

## Actual Results

An error is returned:
`TypeError: Cannot read property 'layout' of undefined` and the contract is not deployed

![Capture](https://user-images.githubusercontent.com/77033904/167651228-89db0b02-acd4-4d80-b292-e936a3afd414.PNG)

contract code
```
contract AeonERC1155 is Initializable, ERC1155Upgradeable, OwnableUpgradeable, PausableUpgradeable, ERC1155BurnableUpgradeable, ERC1155SupplyUpgradeable {
/// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    uint16 aeonPercentage;


    function initialize() initializer public {
        __ERC1155_init("");
        __Ownable_init();
        __Pausable_init();
        __ERC1155Burnable_init();
        __ERC1155Supply_init();
        //initialize the aeon percentage be 2.5%
         aeonPercentage = 250;
    }
}
```

test code
```
const AeonInstance = artifacts.require("AeonERC1155");
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');

describe('upgrades', () => {
  it('works', async () => {
    const instance =  await deployProxy(AeonInstance, [421]);
  });
});
```

Another thing to note is that I am able to successfully migrate this contract using the `truffle-upgrades.deployProxy` logic, but the same logic fails when trying to deploy for test.

migrate code
```
const Migrations = artifacts.require("Migrations");
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');
const AeonInstance = artifacts.require("AeonERC1155");

module.exports = function (deployer) {
  const instance =  deployProxy(AeonInstance, [42], { deployer });
};
```

## Environment

* Operating System: windows 10
* Truffle version (`truffle version`): v5.5.13
* node version (`node --version`): v14.17.6
* npm version (`npm --version`): 6.14.15

**Comment by CVRD-Dev** [comment]
also using the latest versions of `contracts-upgradeable` and `truffle-upgrades

**Comment by MicaiahReid** [comment]
Hi @CVRD-Dev, thanks for opening this issue! Are you seeing anything in particular to point this to being a truffle issue? The stack trace seems to be pointing to this originating in the `openzepellin/truffle-upgrades` package.

Also, are you able to share a repo that we could use to reproduce this? This would make it easier for us to reproduce compared to the form above.

**Comment by CVRD-Dev** [comment]
Hello @MicaiahReid my bad, I didn't realized I posted this on the truffle suite repo instead of the openzepellin/truffle-upgrades repo! I will move this issue over there. Thank you!

**Comment by MicaiahReid** [comment]
@CVRD-Dev No worries, good luck!
