### ISSUE TITLE
Truffle console REPL exits unexpectedly

### ISSUE THREAD

**Issue by cliffoo** [trufflesuite/truffle#5105]
---------------------------

## Issue

Truffle console REPL exits unexpectedly.

## Steps to Reproduce

```zsh
$  # :)
$ truffle console
truffle(development)> migrate # This is fine
truffle(development)> compile # This is fine too
# The following examples stop truffle console after execution,
# and send user back to shell (There are likely more examples):
truffle(development)> migrate --help
truffle(development)> compile --help
truffle(development)> compile --version
$  # :(
```

## Expected Behavior

Truffle console shouldn't exit for no reason. Exit only if `.exit`, `process.exit()`, something crashes, etc.

## Actual Results

Truffle console exits after evaluating certain command + args (valid) combinations.

## Environment

* Operating System: Monterey 12.3.1
* Ethereum client: Ganache 7.1.0
* Truffle version (`truffle version`): 5.5.13
* node version (`node --version`): 16.15.0
* npm version (`npm --version`): 6.14.17

**Comment by lsqproduction** [comment]
Closing as it has been fixed by #5395
