### ISSUE TITLE
truffle --version returns "1.0.0" or "unknown"

### ISSUE THREAD

**Issue by kevinweaver** [trufflesuite/truffle#5106]
## Issue

The `node`, `npm`, and `nvm` commands have a `--version` flag, but the truffle equivalent is `truffle version`.
If the user runs `truffle --version`, the output is unexpected. 

## Steps to Reproduce
Given truffle  v5.5.13 and
node 14:
```
> truffle --version
1.0.0
```

node 16:
```
> truffle --version
unknown
```

## Expected Behavior

`truffle --version` should be an alias of `truffle version` and return the expected output. Something like:
```
Truffle v5.5.13 (core: 5.5.13)
Ganache v^7.1.0
Solidity v0.5.16 (solc-js)
Node v16.9.1
Web3.js v1.5.3
```

## Actual Results

The user hurts itself in confusion! 

## Environment

* Operating System: MacOS 12.3.1
* Ethereum client:
* Truffle version (`truffle version`):  v5.5.13
* node version (`node --version`): 14 or 16
* npm version (`npm --version`):  8.10.0

**Comment by MicaiahReid** [comment]
Possibly related to #5105.

**Comment by swisstackle** [comment]
Is this still an issue? I have node version 16.14 and truffle version 5.5.15. When I run "truffle --version", I get 5.5.15 as the output.

**Comment by eggplantzzz** [comment]
Well actually `truffle --version` is not really officially allowed. Actually on 5.5.16 it is broken (from the bundling changes in the last release) and yields an error. We should probably write in some code to support some of these common formats for requesting the version and help info.
