### ISSUE TITLE
'Error: getaddrinfo' after trying to run 'truffle unbox react'

### ISSUE THREAD

**Issue by jiamijiang** [trufflesuite/truffle#5108]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

'Error: getaddrinfo' after trying to run 'truffle unbox react'

## Steps to Reproduce

After installing truffle globally `npm install -g truffle`, I'll make an empty folder and try to run `truffle unbox react`

I have the below versions of:

```
Truffle v5.5.10 (core: 5.5.10)

Ganache v^7.0.3

Solidity v0.5.16 (solc-js)

Node v12.18.3

Web3.js v1.5.3

npm 6.14.6
```

## Expected Behavior

I expected it to run normally and install the necessary packages to use truffle boxes. 

## Actual Results

I get the error message shown in the screenshot image here:

[https://i.stack.imgur.com/mE6YU.png](url)

```
Starting unbox...
=================

√ Preparing to download box
× Downloading
Unbox failed!
Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Truffle v5.5.10 (core: 5.5.10)
Node v12.18.3
```

## Environment

* Operating System: Windows 10 Home
* Ethereum client: n/a
* Truffle version (`truffle version`): v5.5.10 (core: 5.5.10)
* node version (`node --version`): v12.18.3
* npm version (`npm --version`): 6.14.6

**Comment by realcliffzhang** [comment]
Hi @jiamijiang, thanks for opening this! I'm able to recreate this issue when I'm not connected to the internet.
Could you check your connection and give it another try? Let me know how it goes, thanks!

**Comment by jiamijiang** [comment]
where do i find my `/etc/hosts` ?

**Comment by jiamijiang** [comment]
> Seems like others have had similar issue and GFW was where the problem came from. Could you try editing your `/etc/hosts` as suggested [here](https://github.com/trufflesuite/truffle/issues/2995#issuecomment-1048730590) and see if it works? Thanks.

where do i find `/etc/hosts` ?

**Comment by eggplantzzz** [comment]
`hosts` is a file found at `/etc/hosts` on your machine

**Comment by jiamijiang** [comment]
ok I've made the changes to `/etc/hosts`

but now when i try to run `truffle unbox react` again i'll get the below new error:

```
Starting unbox...
=================

√ Preparing to download box
× Downloading
Unbox failed!
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Truffle v5.5.10 (core: 5.5.10)
Node v12.18.3
```

**Comment by realcliffzhang** [comment]
@jiamijiang Glad it worked out 👍

**Comment by jiamijiang** [comment]
Although when trying to initialize a new `truffle unbox react`, I still run into connection errors such as the below:

```
Starting unbox...
=================

✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: connect ETIMEDOUT 151.101.56.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Truffle v5.5.10 (core: 5.5.10)
Node v12.18.3
```

That same IP address that was added in the filename `/etc/hosts` seems to be the issue sometimes with connecting.

Any thoughts?
