### ISSUE TITLE
install is stalling out

### ISSUE THREAD

**Issue by geofflangenderfer** [trufflesuite/truffle#5110]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I've tried this 10x and it always stalls out at multiaddr
```
❯ sudo npm install -g truffle
(####⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ idealTree:multiaddr: sill fetch manifest varint@^5.0.0


~ 17s
❯ npm --version
8.10.0

~
❯
```

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by lsqproduction** [comment]
Hi @geofflangenderfer. We do not recommend using `sudo` while installing Truffle.
May we know which Node version are you currently on? We recommend using either Node v14 or v16.
My advice would be to re-install Node and npm using a Node version manager like nvm. This is what npm recommends, you can check out [this npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) about doing this. 
Let us know if we can assist further.

**Comment by sukanyaparashar** [comment]
Closing this for issue maintenance. We hope that @lsqproduction's suggestion was helpful in solving this. @geofflangenderfer, please feel free to open a new issue if you still face problem in installing `Truffle`.
