### ISSUE TITLE
stuck in installing truffle

### ISSUE THREAD

**Issue by puffanddmx** [trufflesuite/truffle#5116]
## Issue
hi

when i do the command, npm install --save truffle, i got the below message and no more futher installation after that.

your package is trying to use the filecoin other libraries for the filecoin dapp which make truffle installation stuck.

```
npm WARN deprecated @nodefactory/filsnap-adapter@0.2.2: Package is deprecated in favour of @chainsafe/filsnap-adapter
```

## Environment

* Operating System: centos 8
* Truffle version (`truffle version`): latest
* node version (`node --version`):  12, 14 both same issue
* npm version (`npm --version`): 6.14.16

**Comment by eggplantzzz** [comment]
Are you sure it didn't install properly? The message you posted is actually a warning (not an error) which doesn't prevent installation.

**Comment by cds-amal** [comment]
I verified there is some delay processing `@nodefactory/filsnap-adapter@0.2.2`. @puffanddmx, according to the tests we're run, there is some latency processing that particular project. The solution is to wait. Thank you for your understanding!

**Comment by gkhaos** [comment]
@cds-amal did you find any way to reduce latency?

**Comment by dincho** [comment]
it's totally stuck for me

**Comment by cds-amal** [comment]
@gkhaos, @dincho Apologies for the inconvenience. We have a [PR](https://github.com/trufflesuite/truffle/pull/5135) that should sort this out. Expecting this to go out this week.

**Comment by davidmurdoch** [comment]
Good news, @puffanddmx, https://github.com/trufflesuite/truffle/pull/5135 was merged and will be released this week. Thanks for opening this issue and helping us get this resolved!

**Comment by haltman-at** [comment]
Hi, @puffanddmx, could you (or others) confirm whether this issue is now resolved on installing latest Truffle?  Thanks!

**Comment by puffanddmx** [comment]
yep, it is better now.
thanks for your work!!
good job bro!!!
