### ISSUE TITLE
Cannot edit gas limit for Optimistic Kovan

### ISSUE THREAD

**Issue by emilyJLin95** [trufflesuite/truffle#5120]
## Issue

When I try to deploy to Optimistic Kovan via Truffle dashboards, I cannot edit the gas limit.

## Steps to Reproduce

1. Add Optimistic Kovan to Metamask wallet and truffle config
2. `truffle migrate --network dashboards`

## Expected Behavior

Should be able to sign and deploy

## Actual Results

<img width="363" alt="Screen Shot 2022-05-17 at 2 59 28 PM" src="https://user-images.githubusercontent.com/17280653/168917058-bc8f5352-237e-487f-b900-9f66b15fede0.png">

gasLimit is not being properly specified
`TypeError: Cannot read properties of null (reading 'gasLimit')`

I think the problem is probably deeper with Optimism Kovan being finnicky, but the EDIT button isn't there regardless.

## Environment

* Operating System: MacOS
* Ethereum client: 0.8.13
* Truffle version (`truffle version`): v5.5.12
* node version (`node --version`): v16.14.2
* npm version (`npm --version`): 6.14.16

**Comment by kevinweaver** [comment]
@benjamincburns this is related to dashboard, do you have any insight on it? Thanks!

**Comment by cliffoo** [comment]
This issue still exists on the new dashboard, so it may be a Metamask issue, specifically an optimism kovan rpc url problem (I'm pointing at https://kovan.optimism.io) Maybe that endpoint isn't giving Metamask enough gas-related info?

**Comment by emilyJLin95** [comment]
@cliffoo I think Optimistic Kovan is deprecated. You should be using goerli instead (https://dev.optimism.io/kovan-to-goerli/)

**Comment by emilyJLin95** [comment]
@cliffoo separate to this, optimistic kovan has been deprecated in favor of goerli (https://dev.optimism.io/kovan-to-goerli/)

My suspicion before was that it was a MetaMask issue - perhaps it's not possible with self-added networks?

**Comment by cliffoo** [comment]
Oh I see. Yea that's not a limitation: It is possible with self-added networks. Actually I just tested on optimism goerli (I pointed it at https://goerli.optimism.io) and it lets me edit gas!

**Comment by cliffoo** [comment]
Closing as it's resolved and not specific to Truffle.
