### ISSUE TITLE
getChainId() does not work in truffle dashboard

### ISSUE THREAD

**Issue by CorpulentBrony** [trufflesuite/truffle#5123]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

The `getChainId()` function does not appear to work when using the truffle dashboard during a migration.  This makes it impossible to determine the network at migration time.

## Steps to Reproduce

In migration file:

```javascript
const chainId = await artifacts.require("Migrations").interfaceAdapter.web3.eth.getChainId();
```

Run `truffle migrate --network dashboard`

## Expected Behavior

The proper selected chainId in MetaMask should be returned.  When running migrations not using dashboard, this performs as expected.

## Actual Results

```
SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (node:internal/modules/esm/translators:147:18)
    at link (node:internal/modules/esm/module_job:64:21)
Truffle v5.5.12 (core: 5.5.12)
Node v16.2.0
```

## Environment

* Operating System: `5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Ethereum client:
* Truffle version (`truffle version`): v5.5.12
* node version (`node --version`): v16.2.0
* npm version (`npm --version`): 8.6.0

**Comment by kevinweaver** [comment]
Hi @CorpulentBrony, thanks for opening this. Do you mind trying the access the injected `web3` object instead of from the artifact?  It should be available in the migration context.

**Comment by CorpulentBrony** [comment]
It works, unless I try doing it from an external function.  Even if I pass the global web3 object as a parameter to a function required from an external js file, it fails with the same error.

Seems a bit odd, is this by design to only work from the migration file itself?

**Comment by CorpulentBrony** [comment]
I'm going to close this issue for now, I think there's some deeper issue going on and I'm going to do some regression testing to try and get to the bottom of it.  Thanks for your help.
