### ISSUE TITLE
Specify port when deploying to ganache

### ISSUE THREAD

**Issue by marcpre** [trufflesuite/truffle#5125]
- [ x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When running `sudo truffle migrate` I get the following:
```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
```
However, my `truffle.config` looks like the following:
```
const path = require("path");

module.exports = {
  contracts_build_directory: path.join(__dirname, "client/public/contract_abis"),
  networks: {
    develop: {
      host: "127.0.0.1",
      port: 7546,
      network_id: "*"
    }
  },
  compilers: {
    solc: {
      version: "^0.8.0",    // Fetch exact version from solc-bin (default: truffle's version)
    }
  }
};
```

## Expected Behavior

The migration should run effortlessly.

## Actual Results

When running `sudo truffle migrate` I get the following:
```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
```
This is my ganache:

![image](https://user-images.githubusercontent.com/30902582/169144438-0c5b6d17-8239-4e2d-a2ba-1d3b0da4a031.png)

## Environment

* Operating System: `Ubuntu 20.04.4 LTS`
* NPM: `8.5.5`
* Truffle/Solidity/Ganache/Node version (`truffle version`): ` `
```
Truffle v5.5.5 (core: 5.5.5)
Ganache v^7.0.3
Solidity - ^0.8.0 (solc-js)
Node v16.15.0
Web3.js v1.5.3

```

I appreciate your replies!

**Comment by kevinweaver** [comment]
Hi @marcpre, first, it's important not to use `sudo` when calling `truffle`. Second, it's possible that your network name `develop` is causing issues because you aren't specifying a network in your command.  To fix this, you could either add a `--network=develop` flag, or rename your network to `development`, which is the default network name.

**Comment by sukanyaparashar** [comment]
Hi @marcpre, just wondering if @kevinweaver's suggestion was helpful in solving your issue.
