### ISSUE TITLE
Can't get value from deployed contract

### ISSUE THREAD

**Issue by Zadorie** [trufflesuite/truffle#5130]
---------------------------

## Issue
I'm trying to use truffle and solidity for my first time, so I followed this tutorial - [Code Your Own CryptoCurrency](https://www.youtube.com/watch?v=XdKv5uwEk5A&list=PLS5SEs8ZftgWFuKg2wbm_0GLV0Tiy1R-n)

## Steps to Reproduce

1. truffle init
2. edit truffle-config.js
  ``
networks: {
     development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 7545,
      network_id: "*",       // Any network (default: none)
     },
}
``

3.create contract and then command truffle compile
4. create migrations/2_.

`` 
var DappToken = artifacts.require("./DappToken.sol");

module.exports = function(deployer) {
  
  deployer.deploy(DappToken)
};
``

5.deploy contract: truffle migrate

## Expected Behavior
According to tutorial, I should be able to get value from contract once my truffle migrate done-
``
truffle console
truffle(development)> DappToken.deployed().then(function(s) { totalSupply=s;; })
undefined
truffle(development)> token.totalSupply
BigNumber{ s: 1, e: 1, c: [ 1000000 ] }

## Actual Results
``
BN { negative: 0, words: [ 0, <1 empty item> ], length: 1, red: null }.
truffle(development)>totalSupply.toString()
'0'
``

## Environment

* Operating System: Windows
* Truffle version (`truffle version`):v5.5.14
* node version (`node --version`):v16.15.0
* npm version (`npm --version`): 8.5.5

**Comment by realcliffzhang** [comment]
I cannot say for sure without looking at the said tutorial myself. You'll need a valid reference to the contract to access its properties + methods. Inside Truffle Console, something like `const t = await YourToken.deployed()` will give you the reference you need. Hope this helps!

**Comment by realcliffzhang** [comment]
[This part of our docs](https://trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts/) may be useful @Zadorie

**Comment by Zadorie** [comment]
Thanks!! @realcliffzhang
