### ISSUE TITLE
DISABLE_ESLINT_PLUGIN: command not found

### ISSUE THREAD

**Issue by swisstackle** [trufflesuite/truffle#5134]
---------------------------
I figured I would transfer this problem to github issues because I dont believe that thats what the discussions are for.

## Issue
I am currently trying to build all packages on my local machine to contribute to truffle:

When yarn/lerna (yarn bootstrap) tries to build the truffle dashboard package, I am getting the error 'DISABLE_ESLINT_PLUGIN' is not recognized as an internal or external command, which is used in the package.json to run react-scripts without eslint.

According to react-scripts, this tag was added with the version 4.0.2, but the package.json in the dashboard package references version ^4.0.0 for react-scripts. This is a little bit confusing to me, because how could you guys build the dashboard package with this tag, if you guys use version ^4.0.0? But then again, the carrot makes sure that the latest version is installed, so the issue might clearly be on my side.

Here is the PR that added the 'DISABLE_ESLINT_PLUGIN' tag to react-scripts: https://github.com/facebook/create-react-app/pull/10170

## Steps to Reproduce

1. Clone the develop branch
2. run yarn bootstrap
## Expected Behavior

All packages are being built

## Actual Results

Error: ['DISABLE_ESLINT_PLUGIN' is not recognized as an internal or external command]

## Environment

* Operating System: Windows 10 (x64)
* Truffle version (`truffle version`): latest develop status
* node version (`node --version`): 16.14
* npm version (`npm --version`): 8.10.0

**Comment by cds-amal** [comment]
Hi @swisstackle, truffle dashboard [uses craco for script management](https://github.com/trufflesuite/truffle/blob/develop/packages/dashboard/package.json#L24-L32). See their [website for more information](https://github.com/gsoft-inc/craco).

**Comment by swisstackle** [comment]
I just installed craco globally, but I am still getting the same error. Technically that shouldnt make a difference anyways, because without having it installed globally, it should just use the craco that is being installed by yarn in the dashboard package.
Ill investigate further.

**Comment by cds-amal** [comment]
Thanks, @swisstackle. Please let me know what you discover.

**Comment by benjamincburns** [comment]
I think we should make the build work on Windows. We want people to be able to contribute code regardless of what OS they use.

@swisstackle do you happen to have a WSL install? If so, would you mind testing whether or not your changes also build correctly under WSL? If they do, I'd be really happy if you'd be willing to submit those changes as a PR to unbreak the build for Windows users.

**Comment by swisstackle** [comment]
I've just reproduced the same error on  a different (almost new) windows system. So yes, modt likely Windows is the problem.
Specificslly two things:

husky functionality and the didable_entlint thing.

Everything else worked when building.

**Comment by benjamincburns** [comment]
Yeah, you're correct about  the husky pre-commit hooks, but otherwise we'd be super happy for anything that you'd be willing to contribute that would otherwise improve the state of things on Windows.

That said there is an internal effort happening to bring about a Windows CI build, so that will probably improve things pretty dramatically when that drops.

**Comment by swisstackle** [comment]
@benjamincburns  I can make a PR for the .env file if you wish. It resolved the Dashboard issue I've had.

**Comment by benjamincburns** [comment]
That'd be awesome - thanks!

**Comment by cliffoo** [comment]
`cross-env` made it to Dashboard in [develop](https://github.com/trufflesuite/truffle/tree/develop). Thanks @swisstackle!

**Comment by amygoru** [comment]
Hello all
still show
PS C:\Users\Amitk\OneDrive\Desktop\data\toonb\love-toon-app> npm start

> /user@1.10.0 start
> DISABLE_ESLINT_PLUGIN=true react-app-rewired start

'DISABLE_ESLINT_PLUGIN' is not recognized as an internal or external command,
operable program or batch ### file.****
