### ISSUE TITLE
Pressing tab in truffle console recompiles contracts instead of auto completing

### ISSUE THREAD

**Issue by illuzen** [trufflesuite/truffle#514]
This is a new behavior I did not see before upgrading to 3.4.6

* Operating System: OSX 10.12.4
* Truffle version: 3.4.6
* Ethereum client: Geth/v1.5.9-stable-a07539fb/darwin/go1.8
* node version: v7.7.4
* npm version: 5.3.0

**Comment by TripleSpeeder** [comment]
Also happens here. Very confusing :-)

**Comment by thomasj02** [comment]
+1

**Comment by tcoulter** [comment]
See #519. A fix will be released Monday.

Thanks!
