### ISSUE TITLE
contributing.md out of date: Asking to work on it

### ISSUE THREAD

**Issue by swisstackle** [trufflesuite/truffle#5144]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

As I was trying to add a command, through debugging, I have noticed that yargs is looking for a meta module, not only a run module as described in contributing.md.
Then I looked at the other commands in \packages\core\lib\commands and I've noticed that every command has its own directory with an index.js, meta.js and run.js file.
In contributing.md it is described that it is only necessary to create a file (mycmd.js) with a run module instead of two modules (run and meta).

I am assuming that the contributing.md file is out of date and wanted to ask if I could work on updating it.

**Comment by swisstackle** [comment]
Opened up the PR: https://github.com/trufflesuite/truffle/pull/5145

**Comment by haltman-at** [comment]
Closing this now that the PR is merged and released.
