### ISSUE TITLE
Deprecate/remove eth-pm support

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#5160]
Our maintenance/dependency cost is quite high for an ecosystem that doesn't seem to have community support. We should deprecate/remove `truffle install` and `truffle publish`.

**Comment by cliffoo** [comment]
Fixed in [pull#5283](https://github.com/trufflesuite/truffle/pull/5283) and in the [latest release v5.5.22](https://github.com/trufflesuite/truffle/releases/tag/v5.5.22). Thanks @sukanyaparashar!
