### ISSUE TITLE
Update Ganache options from legacy style "namespaceless" options to the namespaced versions, e.g., `gasLimit` to `miner.blockGasLimit`

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#5161]
Ganache still accepts legacy-style options like `gasLimit`, but these have been deprecated as of v7.0.0. That specific example option is now `miner.blockGasLimit`. Truffle should be updated (primarily the tests) to start Ganache with the newer option style. Mostly this will look something like the following:

```
Ganache.provider({
  miner: {
    blockGasLimit: <x>
...
```

For a list of all options you can use `ganache --help`.

**Comment by cliffoo** [comment]
Resolved in the [latest Truffle release](https://github.com/trufflesuite/truffle/releases/tag/v5.5.19). Thanks @lsqproduction!
