### ISSUE TITLE
Officially drop support for Node v12 and add support for Node v18

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/truffle#5165]
Current blockers on this are @truffle/db's pouchdb's webSQL adapter dependency.

> It's all kinds of broken.
– @gnidan, 2022

Possible resolution is to skip the db tests on Node v18, as truffle db is option. Of course this isn't preferred, as we do want @truffle/db to work on all versions of Node we support.

We should look into Ganache's [custom script](https://github.com/trufflesuite/ganache/blob/5c57c22cae48df59f893ee76f19378b9594cceb9/scripts/require-engines.ts) that can [be used to skip tests](https://github.com/trufflesuite/ganache/blob/5c57c22cae48df59f893ee76f19378b9594cceb9/src/chains/filecoin/filecoin/package.json#L33) based on a package.json's `engines` semver range.

**Comment by cds-amal** [comment]
Fixed in [v5.6.0](https://github.com/trufflesuite/truffle/releases/tag/v5.6.0)
