### ISSUE TITLE
Nice to have: Multiple singletons of the same type of contract in migrations

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#517]
Potential new syntax:

```
deployer.deploy(A);    // => A.json
deployer.deploy(A, {as: "GoldToken"}); // => GoldToken.json
deployer.deploy(A, {as: "SilverToken"}); // => SilverToken.json 

deployer.deploy(C, GoldToken);    // How do we get this?
```

Unanswered question: How do you refer to GoldToken after it's created?

**Comment by travs** [comment]
Seems like a great feature to have.
Not sure if you're looking for syntax, but what about something like this?

```js
deployer.deploy(A, {as: 'GoldToken'}); // => GoldToken.json
GoldToken = deployer.resolve(A, {from: 'GoldToken'})
deployer.deploy(B, GoldToken);
```

Could also make a new ~~resolver~~ module

cc: #237

**Comment by pszabop** [comment]
factory patterns are quite common, I have 3 different use cases for this already...

**Comment by jbentke** [comment]
That is definitely needed :)

**Comment by jchittoda** [comment]
When can we expect this feature ?

**Comment by mryellow** [comment]
This issue presents alternative possible syntax.

https://github.com/trufflesuite/truffle/issues/237#issuecomment-252607611

Which I see @tcoulter has included here:

https://github.com/trufflesuite/truffle/issues/237#issuecomment-314233073

It could probably be closed as duplicate.

**Comment by mryellow** [comment]
Bot closing probably not good idea. This deployment system UX can be improved.

**Comment by mryellow** [comment]
Or.... Keep #237 and close this one?

**Comment by gnidan** [comment]
Closing this one in favor of #237, since it seems a duplicate. Thanks all!
