### ISSUE TITLE
Testing basic contract on truffle

### ISSUE THREAD

**Issue by pbirbarah** [trufflesuite/truffle#5179]
### Discussed in https://github.com/orgs/trufflesuite/discussions/5178

<div type='discussions-op-text'>

<sup>Originally posted by **pbirbarah** June  5, 2022</sup>
this is my first contract and I am using truffle with ganache for testing and I am facing some issues:
![image](https://user-images.githubusercontent.com/74081842/172054759-86219ae6-04ce-49b0-b160-e4208342dae2.png)

The contract is supposed to just send payment back to the person who contacts it.
How do I do that? I have the contract deployed, created an instance const my_contract = await Test_Payment.deployed()

when I try my_contract.test I get an error that this is not a function I am confused how to proceed. </div>

**Comment by kimanikelly** [comment]
Hi, @pbirbarah do you have a public repository or full code snippet of Test_Payment.sol? I would like to assist you with the blocker you're facing thank you.

**Comment by kimanikelly** [comment]
@pbirbarah Sounds great thank you, I will let you know what I find and we can go over the solution

**Comment by kimanikelly** [comment]
@pbirbarah How are you deploying your contract do you have a code snippet?

**Comment by pbirbarah** [comment]
I am using truffle console with ganache so it's different.

after deploying the contract on ganache, I can write this to double check it is deployed.
const my_contract = await Test_Payment.deployed()
then I try and define the sender address using 
address my_address = '0x56cFBBDB11D385da02db4eef2784E021435d6731' and I get an error
![image](https://user-images.githubusercontent.com/74081842/172468244-bb2e82cc-2e1e-440b-bb2a-b8a0a5fa92af.png)

**Comment by kimanikelly** [comment]
@pbirbarah Alright I will try with Truffle and let you know

**Comment by kimanikelly** [comment]
@pbirbarah Before I deployed the contract and invoked the `test` function on localhost through truffle console and ganache-cli I was able to successfully invoke `test` through the test suite by configuring a init test file and executing the ```truffle test``` command

```
const TestPayment = artifacts.require("TestPayment");

contract("TestPayment", (accounts) => {
  it("Should invoke the test() function", async () => {
    const testPayment = await TestPayment.deployed();

    await testPayment.test({ value: 1e15 });
  });
});
```

<img width="877" alt="Screen Shot 2022-06-07 at 4 38 27 PM" src="https://user-images.githubusercontent.com/42893948/172477959-ee90b567-bd17-41dd-b4b8-3e68f5589a1b.png">

**Comment by kimanikelly** [comment]
@pbirbarah I was able to successfully deploy TestPayment.sol locally with `truffle migrate` and `ganache-cli` then invoke the `test` function

<img width="953" alt="Screen Shot 2022-06-07 at 5 32 44 PM" src="https://user-images.githubusercontent.com/42893948/172486495-ff6dc664-9254-4d96-a370-372fd4e77a92.png">

**Comment by pbirbarah** [comment]
this is very helpful thank you. How can I specify which address to send from using the console? and can I check the balance on the address using the console?

**Comment by kimanikelly** [comment]
@pbirbarah The Truffle console supports the ```accounts``` variable and returns an array of public addresses connected to ganache-cli. You can specify which address invokes the `test` function by adding the ```from``` property to the function call and designating the index inside the ```accounts``` array.

<img width="953" alt="Screen Shot 2022-06-07 at 7 34 15 PM" src="https://user-images.githubusercontent.com/42893948/172500584-0c46447b-cf67-4111-85a6-6438cb4d5384.png">
c

**Comment by kimanikelly** [comment]
@pbirbarah Here is how you can check the ETH balance from one of the accounts

<img width="675" alt="Screen Shot 2022-06-07 at 7 38 20 PM" src="https://user-images.githubusercontent.com/42893948/172501030-c8b9875d-27df-4d13-a910-3ed1c1985770.png">

**Comment by pbirbarah** [comment]
that is perfect! thanks!

**Comment by kimanikelly** [comment]
@pbirbarah No problem take care
