### ISSUE TITLE
Nice to have: granular requests with HDwallet

### ISSUE THREAD

**Issue by Chococoin** [trufflesuite/truffle#5189]
## How to cast granulars requests to Infura with HDwallet-provider?

I saw that once @truffle/hdwallet-provider is required it with request to infura the eth_blockNumber every 2 seconds.
This is an undesirable behavior, my program doesn't need to overload the infura server for that info. Instead I would love to request to infura data as needed.

**Comment by dongmingh** [comment]
@Chococoin Could you provide steps to reproduce this issue?  Also you can try to disable web3's confirmation listener by setting `disableConfirmationListener: true` in your network configuration. Refer to network section in https://trufflesuite.com/docs/truffle/reference/configuration/.
