### ISSUE TITLE
Cannot declare variables in the console that begin with commands short aliases

### ISSUE THREAD

**Issue by spalladino** [trufflesuite/truffle#519]
## Issue

When trying to assign a variable in the console that begins with a command short name, such as `b` for `build`, the console attempts to execute the command and does not assign the variable. This did not happen in earlier versions of truffle.

## Steps to Reproduce

Spin up a truffle console in a brand new project, and run:
```
truffle(development)> boo = 10
```

## Expected Behavior

A variable named `boo` is defined with value 10.

## Actual Results

Truffle attempts to build.

```
Error building:

No build configuration specified. Can't build.

Build failed. See above.
```

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: 3.4.6
* node version: 8.2.1
* npm version: 5.3.0

**Comment by tcoulter** [comment]
Thanks for the report. Fixed [here](https://github.com/trufflesuite/truffle-core/issues/29). Will go out as a minor release next week. Cheers!

**Comment by spalladino** [comment]
Thanks for the quick response!!
