### ISSUE TITLE
Cannot find import file (similar to #400)

### ISSUE THREAD

**Issue by mxmauro** [trufflesuite/truffle#520]
## Issue

Hi, I'm experiencing the same issue than #400 with Truffle 3.4.6 on Windows 10. The code compiles fine on Ubuntu.

## Steps to Reproduce

1. Clone `https://github.com/aragon/aragon-core`
2. Run `npm.cmd install` to download dependencies. (Requires Python 2.7 and git to be in the PATH)
3. Ignore the Windows Script Host popup raised by script trying to run `truffle` instead of `truffle.cmd`
4. Run `truffle.cmd compile`

## Expected Behavior

To compile.

## Actual Results

```
Error: Could not find zeppelin\SafeMath.sol from any sources; imported from zeppelin/token/StandardToken.sol
    at C:\Lenguaje\Ethereum\NodeJS\node_modules\truffle\build\cli.bundled.js:49124:23
    at C:\Lenguaje\Ethereum\NodeJS\node_modules\truffle\build\cli.bundled.js:65257:16
    at next (C:\Lenguaje\Ethereum\NodeJS\node_modules\truffle\build\cli.bundled.js:75635:18)
    at C:\Lenguaje\Ethereum\NodeJS\node_modules\truffle\build\cli.bundled.js:49112:7
```

![image](https://user-images.githubusercontent.com/1683070/28734021-4b307b92-73b5-11e7-8beb-51bd5ae09df9.png)

You can see the system tries to locate the file in the wrong folder.

## Environment

* Operating System: Windows 10 x64
* Truffle version: 3.4.5 and 3.4.6
* Ethereum client: Geth 1.6.6
* node version: 6.11.0
* npm version: 3.10.10

Kind regards,
Mauro.

**Comment by mxmauro** [comment]
Reverted to 3.4.5 and works fine.

**Comment by Ste91** [comment]
Still getting the same issue "fails on import statements" on windows 10 using truffle@4.1.6
