### ISSUE TITLE
Implement Node 18 Support

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#5203]
We need to deprecate support for Node 12 soon, and we should be sure developers can upgrade to the newest Node, which is v18.

**Comment by haltman-at** [comment]
See also #5305.

**Comment by fainashalts** [comment]
Moving DB to its own repo, like preserves, seems reasonable to me. We can always move it back when it is being actively worked on. Or develop it as a plug-in instead perhaps.

**Comment by cliffoo** [comment]
Jest cannot be upgraded because they dropped support for node 12, and we might run into similar trouble with other dependencies since node 12 reach EOL > 4 months ago. Just adding a note here since #5507 closed.

**Comment by davidmurdoch** [comment]
Fixed by https://github.com/trufflesuite/truffle/pull/5543
