### ISSUE TITLE
I have encountered this error while running truffle migrate "Something went wrong while attempting to connect to the network at http://127.0.0.1:8545. Check your network configuration." ProviderError:  Could not connect to your Ethereum client with the following parameters:     - host       > 127.0.0.1     - port       > 8545     - network_id > *

### ISSUE THREAD

**Issue by sarthak550** [trufflesuite/truffle#5219]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
![image](https://user-images.githubusercontent.com/52045803/174637858-d8e962a5-913a-4f0e-bcb5-95f28ce0de80.png)

## Environment

Ubuntu 20.04.4
Truffle v5.5.17 (core: 5.5.17)
Node v14.19.3
npm v6.14.17

**Comment by sukanyaparashar** [comment]
Thank you for raising this, @sarthak550 . Can you please share your `truffle-config.js` file ?

**Comment by joeax** [comment]
I figured it out. When you define a network called `development` it tries to use that for testing. I confirmed that by looking at the code for the CLI here:
https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/commands/test/run.js

If I comment out the entire network section in the config it uses an internal Ganache instance.

The point I was trying to make was I have to comment/uncomment that section to run `truffle test` vs `truffle migrate`

**Comment by sukanyaparashar** [comment]
Yes, @joeax but there are some catches here. `truffle test` and `truffle migrate` both uses `development` as the default network if it is specified in the `truffle-config.js`. But `truffle test` starts a Ganache instance if no network is specified in the config. Whereas, `truffle migrate` needs a network specification in the config. For that, you can either give the network specification in the `development` network or you can specify your required network in the config and use the `--network` option with `truffle migrate` to deploy the contracts into that network, something like -
`truffle migrate --network <network_name>`

**Comment by dongmingh** [comment]
Hi, @sarthak550 we will close this issue for issue maintenance.  If you have any further questions, please open a new issue. Thanks.
