### ISSUE TITLE
"Error: Migration 2_initial_migration.js invalid or does not take any parameters", how should I edit the file 2_initial_migration.js to migrate contract?

### ISSUE THREAD

**Issue by jdcrew** [trufflesuite/truffle#524]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle migrate

## Steps to Reproduce

step 1, create mytoken.sol , 2_initial_migration.js like below:
```
mytoken.sol
pragma solidity ^0.4.2;
contract owned {
    address public owner;

    function owned() {...}

    modifier onlyOwner {...}

    function transferOwnership(address newOwner) onlyOwner {... }
}

contract tokenRecipient { function receiveApproval(address _from, uint256 _value, address _token, bytes _extraData); }

contract token {
    /* Public variables of the token */
    string public standard = 'Token 0.1';
    string public name;
    string public symbol;
    uint8 public decimals;
    uint256 public totalSupply;

    /* This creates an array with all balances */
    mapping (address => uint256) public balanceOf;
    mapping (address => mapping (address => uint256)) public allowance;

    /* This generates a public event on the blockchain that will notify clients */
    event Transfer(address indexed from, address indexed to, uint256 value);

    /* Initializes contract with initial supply tokens to the creator of the contract */
    function token(
        uint256 initialSupply,
        string tokenName,
        uint8 decimalUnits,
        string tokenSymbol
        ) {
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
        totalSupply = initialSupply;                        // Update total supply
        name = tokenName;                                   // Set the name for display purposes
        symbol = tokenSymbol;                               // Set the symbol for display purposes
        decimals = decimalUnits;                            // Amount of decimals for display purposes
    }

    /* Send coins */
    function transfer(address _to, uint256 _value) {..}

    /* Allow another contract to spend some tokens in your behalf */
    function approve(address _spender, uint256 _value)
        returns (bool success) {...}

    /* Approve and then communicate the approved contract in a single tx */
    function approveAndCall(address _spender, uint256 _value, bytes _extraData)
        returns (bool success) { ...}

    /* A contract attempts to get the coins */
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success) {...}

    /* This unnamed function is called whenever someone tries to send ether to it */
    function () {
        throw;     // Prevents accidental sending of ether
    }
}

contract MyAdvancedToken is owned, token {

    uint256 public sellPrice;
    uint256 public buyPrice;

    mapping (address => bool) public frozenAccount;

    /* This generates a public event on the blockchain that will notify clients */
    event FrozenFunds(address target, bool frozen);

    /* Initializes contract with initial supply tokens to the creator of the contract */
    function MyAdvancedToken(
        uint256 initialSupply,
        string tokenName,
        uint8 decimalUnits,
        string tokenSymbol
    ) token (initialSupply, tokenName, decimalUnits, tokenSymbol) {}

    /* Send coins */
    function transfer(address _to, uint256 _value) {...}


    /* A contract attempts to get the coins */
    function transferFrom(address _from, address _to, uint256 _value) returns (bool success) {...}

    function mintToken(address target, uint256 mintedAmount) onlyOwner {...}

    function freezeAccount(address target, bool freeze) onlyOwner {...}

    function setPrices(uint256 newSellPrice, uint256 newBuyPrice) onlyOwner {...}

    function buy() payable {...}

    function sell(uint256 amount) {...}
}
```
```
2_initial_migration.js
var MyToken = artifacts.require('./mytoken.sol');
var initTotal = 10000;
var symbol = "%";
var name = "tokens";
var decimal = 2;
module.export = function(deployer){
	deployer.deploy(MyToken , initTotal , name , decimal , symbol);
};
```
step2. truffle compile
step3. 
```
cd /root/of/truffle/project
 truffle migrate     
```

Actually I feel puzzled about how to edit 2_initial_migration.js 

## Expected Behavior

truffle migrate successful.

## Actual Results

"Error: Migration 2_initial_migration.js invalid or does not take any parameters"

## Environment

* Operating System: OS Sierra
* Truffle version: 3.4.5
* Ethereum client: geth 1.6
* node version: 6.11.1
* npm version: 5.3.0

**Comment by jdcrew** [comment]
I have editted 2_initial_migration.js like below
```
var token = artifacts.require("token");
var owned = artifacts.require("owned");
var tokenRecipient = artifacts.require("tokenRecipient");
var MyAdvancedToken = artifacts.require("MyAdvancedToken");

module.exports = function(deployer) {
    deployer.deploy(token,10000,'MyToken',2,'RMB');
    deployer.deploy(owned);
    deployer.deploy(tokenRecipient);
    deployer.deploy(MyAdvancedToken);
};
```
and it tips 
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.

May anybody help me to fix it?

**Comment by lucav** [comment]
+1 I have the same problem with tokenrecipient (i'm deploying on ropsten network, using parity).
This is my 2_initial_migration.js:

`var owned = artifacts.require("Owned");
var TokenRecipient = artifacts.require("TokenRecipient");
var Token = artifacts.require("Token");
var TestCoin = artifacts.require("TestCoin");

module.exports = function(deployer) {
  deployer.deploy(owned);
  deployer.deploy(TokenRecipient); <--------- error here
  // Take the deployed TokenRecipient address and link it to Token contract in bytecode
  deployer.link(TokenRecipient, Token);
  deployer.deploy(Token,1000000,'TestCoin',0,'TEC');
  deployer.link(Token, TestCoin);
  deployer.link(owned, TestCoin);
  deployer.deploy(TestCoin);  
};`

with this output:

`Using network 'development'.

Running migration: 2_deploy_contracts.js
  Deploying Owned...
  ... 0xd464117599ecf979922997d364c8366b23ef2633bb620793630c78b5fbe0b603
  Owned: 0x42099b0f7eba440427ef8f1c5844b11ea6d047cf
  Deploying TokenRecipient...
  ... 0x9aaf26f59267c1a531c3075904c380953ee8d6fd7cd9a8806496f0652acac255
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:222830:46)
    at d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:35149:25
    at d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:224768:9
    at d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:66971:11
    at d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundl
ed.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled
.js:67130:18)
    at XMLHttpRequest._setReadyState (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67420:
12)
    at XMLHttpRequest._onHttpResponseEnd (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67
575:12)
    at IncomingMessage.<anonymous> (d:\Users\xxx\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:67535:24
)`

**Comment by lucav** [comment]
@jdcrew 
Hi, i don't know if you have resolved this issue, but after i talked in the ethereum tutorials gitter chat (https://gitter.im/ethereum/tutorials) i have found that i need only to deploy the main contract and not other contracts in the tutorial. 

In my case, i have to use only this:
```
var TestCoin = artifacts.require("TestCoin");

module.exports = function(deployer) {

    deployer.deploy(TestCoin,1000000,'TestCoin',0,'TEC');  

}

```
And it works.
So, i think this is not a truffle's bug.

**Comment by tcoulter** [comment]
Thanks for looking this up everyone!

I'm glad you guys were able to get help. Since it's determined to not be a Truffle bug, I'm going to close this issue. However: If you find yourself with a similar issue in the future, don't hesitate to go to our Gitter or open a new issue so you can get some help.

Cheers!

**Comment by ArtoriaRen** [comment]
I encountered the same Error and solved it by just adding a newline at the end of  \"2_deploy_contracts.js".

**Comment by vmandal** [comment]
I too had the same error. It was because of a spell mistake. So re-check your code.

**Comment by moda20** [comment]
@ArtoriaRen What the heck ? how does that even make sense. It worked for me that way.

**Comment by Jaren831** [comment]
@ArtoriaRen Your suggestion worked for me as well. Strange...

**Comment by ArtoriaRen** [comment]
@moda20 @Jaren831 I googled newlines at the end of javascript files. It seems newlines prevent two instructions appearing in the same line when the preprocessor concatenates files. I am not sure about this. Here is the link https://evanhahn.com/newline-necessary-at-the-end-of-javascript-files/

**Comment by dipeshnuco** [comment]
> I encountered the same Error and solved it by just adding a newline at the end of "2_deploy_contracts.js".

this worked for me

**Comment by waycoolman619** [comment]
@ArtoriaRen Thanks worked for me I saw that it did not have an empty line but thought that would not do anything well I was wrong Thanks again

**Comment by manikhofort123** [comment]
if the code are correct and still get the error then. Please check whether you save the code or not. I think this is the main issue for most of the problem. You might have doubt why the Migration 1_initial_migration.js work. Its due to the code are saved already and the file comes along with the truffle init. But for the 2nd migration since it doesn't save so the issue....

**Comment by cryptovdev** [comment]
@ArtoriaRen Thanks it also worked for me to add a new line at the end. Was using upgreadable proxy from Open Zeppelin and thought I'd made a mistake in the code somewhere but it was a new line.

**Comment by prakharlohumi** [comment]
Weird but I was able to fix the same error by changing the path in my 2_deploy_token.js file
Instead of:
var MyToken = artifacts.require("./MyToken.sol");
I used:
var MyToken = artifacts.require("MyToken");
and it worked

**Comment by FOWnglp** [comment]
> 

hello,it doen't work
