### ISSUE TITLE
Truffle CI should update to latest GETH stable

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#5251]
Truffle had to pin GETH version because their [latest stable broke our CI](https://github.com/trufflesuite/truffle/pull/5250). We should get back on stable.

**Comment by lsqproduction** [comment]
Done in [Truffle 5.5.20](https://github.com/trufflesuite/truffle/releases/tag/v5.5.20)

**Comment by wbt** [comment]
The release notes for 5.5.20 say it's not done, but rather pinned at the prior version.

**Comment by sukanyaparashar** [comment]
This issue is resolved with this PR #5258 and released in [Truffle v5.5.21](https://github.com/trufflesuite/truffle/releases/tag/v5.5.21)
