### ISSUE TITLE
hdwallet-provider uses old ethereumjs-util

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#5260]
## Issue

@truffle/hdwallet-provider [specifies ethereumjs-util@6](https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/package.json#L29). This uses an older version of @types/bn.js which aren't compatible with the new types incorporated by #5177, a breaking change rolled out in [Truffle's latest patch-level release](https://github.com/trufflesuite/truffle/releases/tag/v5.5.20).

**Comment by haltman-at** [comment]
(Temporarily reopening this per our usual practice of close-on-release rather than close-on-merge.)

**Comment by eggplantzzz** [comment]
Did we not release this change?

**Comment by cds-amal** [comment]
> Did we not release this change?

Nope. The last release was Jul-08 and the associated PR (#5261) was merged on Jul-11, three days later.

**Comment by eggplantzzz** [comment]
Ah ok sorry, I thought this was released.

**Comment by cliffoo** [comment]
Fixed in [pull#5261](https://github.com/trufflesuite/truffle/pull/5261) and in the [latest release v5.5.22](https://github.com/trufflesuite/truffle/releases/tag/v5.5.22). Thanks @wbt and @eggplantzzz!
