### ISSUE TITLE
Solidity bug False compiler DeclarationError: Modifier already used for this function

### ISSUE THREAD

**Issue by jeromerousselot** [trufflesuite/truffle#527]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle 3.4.6 and 3.4.7 install solc 0.4.13 that introduces bug
https://github.com/ethereum/solidity/issues/2621
solved in 
https://github.com/ethereum/solidity/pull/2652

Current workaround is to install truffle@3.4.5 with solc 0.4.11.
Upstream fixed bug and could be included in solc 0.4.15.

## Steps to Reproduce

npm install truffle@3.4.7

write a contract with a modifier.
Define a function with two parameters and applies the modifier to both parameters.

modifier nonZeroAddress(address x) {
    require(x != 0);
    _;
  }

function X(address a, address b) 
nonZeroAddress(a)
nonZeroAddress(b)
{ ... }

## Expected Behavior

The contract should compile.

## Actual Results

The function will not compile.

 DeclarationError: Modifier already used for this function.
    updateAccount(_to) //update receivers rake before transfer as well, to avoid over-attributing rake

## Environment

* Operating System: 
* Truffle version: 3.4.7 and 3.4.6
* Ethereum client:
* node version: 8.2.1
* npm version: 5.3.0

**Comment by jeromerousselot** [comment]
should be already solved in solc 0.4.14.

**Comment by elenadimitrova** [comment]
I submitted https://github.com/ethereum/solidity/issues/2621 and I don't think it belongs in the truffle issue log. This is a matter of truffle upgrading to the latest solc, and not truffle having to fix anything.

**Comment by jeromerousselot** [comment]
I did reference your bug report and stated clearly that it was already resolved in latest solc.
I created the ticket to make truffle users and devs aware of it. I also discussed this in truffle gitter with the devs.
Next truffle release can mark this bug as solved!

**Comment by elenadimitrova** [comment]
Sure but I believe double logging bugs is anti-practice. If this were a thing, then we'll need to duplicate this issue all over the dependent on `solc` packages. This simply isn't a good practice.

**Comment by tcoulter** [comment]
Hi there. Thanks all for your investigation.

Truffle has been upgraded to Solidity v0.4.15. This appears to have fixed the issue.

I'm going to close this for housekeeping. Please open a new ticket if you run into trouble. Thanks all!
