### ISSUE TITLE
truffle compile  -->> killed

### ISSUE THREAD

**Issue by MarkSir** [trufflesuite/truffle#529]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle compile  -->> killed

## Environment

* Operating System:    linux 16.04
* Truffle version:     3.4.7
* Ethereum client:    ethereumjs-testrpc
* node version:    6.11.1
* npm version:   5.3.0

**Comment by branciard** [comment]
Hi, you can check your log in /var/syslog . Maybe you will see "Out of memory : kill process". If so increase the memory. I had this issue with 1024 m allocated on my vm. it works fine for me now with 2048m allocated.

**Comment by tcoulter** [comment]
This (memory) is usually the reason `truffle` gets killed when running `truffle compile`. I'd do as @branciard suggested.

I'm going to close this issue for housekeeping reasons. Please open a new ticket if you run into issues.

**Comment by adamskrodzki** [comment]
Is there really no way to reduce memmory consumption in truffle (increasing for example compiling time? ) 
I have vps with fixed memmory and cannot just resize

**Comment by kaba-official** [comment]
+1 for low memory usage and high compile/deploy time as a side-effect.

**Comment by FrankAst** [comment]
i had my vm with 2048 and still killed. Will try with 3072
