### ISSUE TITLE
Truffle installation Error

### ISSUE THREAD

**Issue by BCEivan** [trufflesuite/truffle#5294]
```
ivan@IvandeMacBook-Air ~ % npm install -g truffle
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/truffle
npm ERR! dest /usr/local/lib/node_modules/.truffle-ojTgnptm
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/truffle' -> '/usr/local/lib/node_modules/.truffle-ojTgnptm'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/truffle' -> '/usr/local/lib/node_modules/.truffle-ojTgnptm'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/local/lib/node_modules/truffle',
npm ERR!   dest: '/usr/local/lib/node_modules/.truffle-ojTgnptm'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ivan/.npm/_logs/2022-07-13T23_17_28_060Z-debug-0.log
```

**Comment by BCEivan** [comment]
how should i do with these problem, thx for helping in davance

**Comment by eggplantzzz** [comment]
Looks like there are some permissions errors, I would recommends re-installing Node and npm with a Node version manager like nvm and this is, in fact, what npm recommends. Usually this resolves these types of errors. See [this article from npm](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) for more information on doing this.

**Comment by Kipkurui-mutai** [comment]
@eggplantzzz I had the same issue during installation. Used that code and it worked.

**Comment by eggplantzzz** [comment]
@Kipkurui-mutai are you sure it was the same? did it say "permission denied"?

**Comment by Kipkurui-mutai** [comment]
@eggplantzzz mine was on windows, this one is probably on mac

**Comment by fainashalts** [comment]
Hi @Kipkurui-mutai it looks like we haven't heard from you on this issue in a while. Are you still experiencing an installation error? I am going to go ahead and close this for issue maintenance. If you encounter this or another error please feel free to open a new issue. Thanks!
