### ISSUE TITLE
Installed Truffle not fully compatible with Node 18

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#5305]
This issue is to keep track of some known issues with Truffle running in Node 18.

- when running `truffle develop`, I receive `Error: error:0308010C:digital envelope routines::unsupported` - this comes from ethereumjs-wallet and there is an open issue on that repo [here](https://github.com/ethereumjs/ethereumjs-wallet/issues/171)

**Comment by eggplantzzz** [comment]
https://github.com/ethereumjs/ethereumjs-wallet/issues/171

**Comment by haltman-at** [comment]
Note: This issue is closely related to #5203.  It's distinct in that this one is about *running* Truffle rather than *installing* it.

**Comment by davidmurdoch** [comment]
Closing in favor of #5203
