### ISSUE TITLE
Upgrade mocha npm dependency

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#531]
when I manually updated to the latest version, I was able to run this reporter:
https://www.npmjs.com/package/mochawesome
with current truffle's mocha version it doesn't compile

Steps:
1. `yarn add mochawesome -D`

in `truffle.js`

```
  mocha: {
    reporter: 'mochawesome'
  }
```

3. `truffle test`

**Comment by cgewecke** [comment]
We're on mocha 5 as of `4.1.12` @rstormsf. Just sweeping through the issues and closing this one for housekeeping. Hope you don't mind, thanks.
