### ISSUE TITLE
ReferenceError while migrate the contracts

### ISSUE THREAD

**Issue by eberkeaydin** [trufflesuite/truffle#5319]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I got ReferenceError while I was trying migrate the contract. 

I have got Wallet.sol for ERC20 wallet contract and Tokens.sol testing wallet with sample token with its constructor as : 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Link is ERC20 {
    constructor() ERC20("Chainlink", "LINK") public {
        _mint(msg.sender, 1000);
    }
}
```

2_wallet_migration.js:

```
const Migrations = artifacts.require("Wallet");

module.exports = function (deployer) {
  deployer.deploy(Wallet);
};
```

3_tokens_migration.js:

```
const Migrations = artifacts.require("Link");

module.exports = function (deployer) {
  deployer.deploy(Link);
};
```
## Error
2_wallet_migration.js
=====================

ReferenceError: Wallet is not defined
    at module.exports (/home/eba/authic/ethereum-201/eba-dex/migrations/2_wallet_migration.js:4:19)
    at Migration._load (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:53:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration.run (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:142:1)
    at Object.runFrom (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:107:1)
    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:91:1)
    at module.exports (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/runMigrations.js:10:1)
    at Object.module.exports [as run] (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:41:1)
    at runCommand (/usr/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1)

## Wallet.sol

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "../node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "../node_modules/@openzeppelin/contracts/utils/math/SafeMath.sol";
import "../node_modules/@openzeppelin/contracts/access/Ownable.sol";

contract Wallet is Ownable{

    using SafeMath for uint256;

    struct Token { // Basic token structure
        bytes32 ticker;
        address tokenAddress;
    }

    mapping(bytes32 => Token) public tokenMapping; // Token ticker -> Token struct
    bytes32[] public tokenList; // List of tokens


    mapping(address => mapping(bytes32 => uint256)) public balances; // Double mapping which is mapped address -> token symbol -> balance

    modifier tokenExist(bytes32 ticker){
        require(tokenMapping[ticker].tokenAddress != address(0), "Token does not exist.");
        _;
    }

    function addToken(bytes32 ticker, address tokenAddress) onlyOwner external { 
        tokenMapping[ticker] = Token(ticker, tokenAddress);
        tokenList.push(ticker);
    }

    function deposit(uint amount, bytes32 ticker) tokenExist(ticker) external {
        require(tokenMapping[ticker].tokenAddress != address(0));
        IERC20(tokenMapping[ticker].tokenAddress).transferFrom(msg.sender, address(this), amount);
        balances[msg.sender][ticker] = balances[msg.sender][ticker].add(amount);
    }

    function withdraw(uint amount, bytes32 ticker) tokenExist(ticker) external {
        require(balances[msg.sender][ticker] >= amount, "Balances not sufficient");

        balances[msg.sender][ticker] = balances[msg.sender][ticker].sub(amount);
        IERC20(tokenMapping[ticker].tokenAddress).transfer(msg.sender, amount);
    }
}
```

## Environment

* Operating System: Ubuntu 20.04
* Truffle version (`truffle version`): 5.5.21
* node version (`node --version`):16.16.0
* Solidity version (`solidity --version`): 0.8.15

**Comment by haltman-at** [comment]
The problem is here:

```
const Migrations = artifacts.require("Wallet");

module.exports = function (deployer) {
  deployer.deploy(Wallet);
};
```

You named the variable `Migrations`, but then you tried to deploy `Wallet`.

Hope that helps!
