### ISSUE TITLE
Truffle DB has outdated version of `ts-node-dev`

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#5322]
## Issue

The `@truffle/db` package currently uses `ts-node-dev` version `^1.0.0-pre.32`.  Yikes!  This is responsible for one of our dependabot alerts, namely, `trim-newlines`.  This package should be updated (or possibly just removed).  It does look to me like the latest version in the 1.x family would resolve in the alert, hopefully nothing should break on switching to that?

(...OK, OK, so the dependabot alert in question is almost certainly not an actual problem given the context that `ts-node-dev` is used in, but still...)

## Environment

* Truffle version (`truffle version`): 5.5.22

**Comment by eggplantzzz** [comment]
After a small bit of discussion, we decided that we can replace this package with `ts-node`. We might need to update some of the scripts as a part of this task.

**Comment by haltman-at** [comment]
Oh hey, this issue never got closed.  Well, this is gone now!
