### ISSUE TITLE
Not able to successfully do transactions of default MetaCoins(from Truffle) on local testnet on MetaMask

### ISSUE THREAD

**Issue by sauravs** [trufflesuite/truffle#533]
I have installed truffle and ran the default contract provided by truffle.I successfully compiled,migrate and put the default dapp on local testnet http://localhost:8080/.

I am able to see the dapp here.I have also synced the metamask account with testrpc using testrpc -m "mnemonics"But when I try to send metacoins to one of the account address present in MetaMask ,I do not see any confirmation pop-up of Metamask to Accept/Reject Transaction.Neither does the transaction details shows up in Metamask window. 

Though, whenever I try to send metacoins from http://localhost:8080 ,it suddenly displays message "Transaction Complete" without any confirmation or any coin amount deducted from main balance.

Truffle version : 3.4.6 
npm version : 5.3.0     EthereumJS TestRPC v4.0.1  , OS:xubuntu 64bit

Please help.

**Comment by acrigney** [comment]
I have the same problem and I did not know that I had to run the testrpc -m "with my mnemonics"
