### ISSUE TITLE
Resolver cannot find `Timelock` contract

### ISSUE THREAD

**Issue by jinxlo** [trufflesuite/truffle#5332]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I'm trying to run https://github.com/dappuniversity/governance However I keep running into this issue when I deploy the contracts

I'm running everything out the box without making any changes at all

~/Desktop/governance-master$ truffle migrate --reset

Compiling your contracts...
Everything is up to date, there is nothing to compile.

Starting migrations...
Network name: 'development' Network id: 1658331962840 Block gas limit: 6721975 (0x6691b7)

1_initial_migration.js
Deploying 'Migrations'
transaction hash: 0xbcfe7f2a4bd6f17a6ac4335bdf2ccf94f4b4765ccac837e3d9e40b2a53cc35d7 Blocks: 0 Seconds: 0 contract address: 0x6E5f031e9a36BfA85E7709bC3cBEA471c498061e block number: 1 block timestamp: 1658331987 account: 0x333D0cC98205eB50052782A9b2bF8Fa3f04039d3 balance: 99.99502316 gas used: 248842 (0x3cc0a) gas price: 20 gwei value sent: 0 ETH total cost: 0.00497684 ETH

Saving migration to chain. Saving artifacts

Total cost: 0.00497684 ETH

2_deploy_contracts.js
/usr/local/lib/node_modules/truffle/build/4889.bundled.js:21755 throw new Error("Could not find artifacts for " + import_path + " from any sources"); ^

Error: Could not find artifacts for Timelock from any sources at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:60:1) at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:165:1) at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1) at /home/jinxlo/Desktop/governance-master/migrations/2_deploy_contracts.js:2:28 at Script.runInContext (vm.js:130:18) at Script.runInNewContext (vm.js:135:17) at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:94:1) at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:42:1) at processTicksAndRejections (internal/process/task_queues.js:97:5) at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1) at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:142:1) at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:107:1) at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:111:1) at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:84:1) at module.exports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/runMigrations.js:10:1) at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:41:1) at runCommand (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1) Truffle v5.5.22 (core: 5.5.22) Node v12.22.9

## Steps to Reproduce

1. Clone/Download the Repository
2. Install Dependencies:
`$ npm install`

3. Start Ganache

4. Migrate Smart Contracts
`$ truffle migrate --reset`

## Expected Behavior

everything to compile correctly
## Actual Results

/usr/local/lib/node_modules/truffle/build/4889.bundled.js:21755 throw new Error("Could not find artifacts for " + import_path + " from any sources"); ^

Error: Could not find artifacts for Timelock from any sources at Resolver.require 

## Environment

* Operating System: Ubuntu 22.04 LTS
* Ethereum client: ganache v7.3.2
* Truffle version (`truffle version`):v5.5.22 (core: 5.5.22)
* node version (`node --version`):12.22.9
* npm version (`npm --version`): 8.5.1

**Comment by cliffoo** [comment]
Hey @jinxlo thanks for opening this issue, it looks like the resolver cannot find the timelock contract. I followed the reproduction steps but I was actually able to get the contracts deployed successfully.

I guess you could check two things?
1. Did you modify the [dappuniversity/governance](https://github.com/dappuniversity/governance) repo after clone? Is the timelock contract actually there?
2. Your npm version _may_ be why this is happening. Try `npm install -g npm@6`, reinstall truffle and ganache, and try again.

Let me know! Good luck.

```
╭─ ~/Buffer/dappuni-gov ‹node-16.15.0›  (master*) 
╰─ $ truffle migrate --reset

Compiling your contracts...
===========================
✓ Fetching solc version list from solc-bin. Attempt #1
✓ Downloading compiler. Attempt #1.
> Compiling ./contracts/Governance.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Timelock.sol
> Compiling ./contracts/Token.sol
> Compiling ./contracts/Treasury.sol
> Compiling @openzeppelin/contracts/access/AccessControl.sol
> Compiling @openzeppelin/contracts/access/IAccessControl.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/governance/Governor.sol
> Compiling @openzeppelin/contracts/governance/IGovernor.sol
> Compiling @openzeppelin/contracts/governance/TimelockController.sol
> Compiling @openzeppelin/contracts/governance/extensions/GovernorCountingSimple.sol
> Compiling @openzeppelin/contracts/governance/extensions/GovernorTimelockControl.sol
> Compiling @openzeppelin/contracts/governance/extensions/GovernorVotes.sol
> Compiling @openzeppelin/contracts/governance/extensions/GovernorVotesQuorumFraction.sol
> Compiling @openzeppelin/contracts/governance/extensions/IGovernorTimelock.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol
> Compiling @openzeppelin/contracts/token/ERC20/extensions/draft-IERC20Permit.sol
> Compiling @openzeppelin/contracts/utils/Address.sol
> Compiling @openzeppelin/contracts/utils/Context.sol
> Compiling @openzeppelin/contracts/utils/Counters.sol
> Compiling @openzeppelin/contracts/utils/Strings.sol
> Compiling @openzeppelin/contracts/utils/Timers.sol
> Compiling @openzeppelin/contracts/utils/cryptography/ECDSA.sol
> Compiling @openzeppelin/contracts/utils/cryptography/draft-EIP712.sol
> Compiling @openzeppelin/contracts/utils/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/utils/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/utils/math/Math.sol
> Compiling @openzeppelin/contracts/utils/math/SafeCast.sol
> Artifacts written to /Users/cliff/Buffer/dappuni-gov/build/contracts
> Compiled successfully using:
   - solc: 0.8.9+commit.e5eed63a.Emscripten.clang


Starting migrations...
======================
> Network name:    'development'
> Network id:      1657653370550
> Block gas limit: 30000000 (0x1c9c380)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x59ae6cec7d377dc4f6f371a899014e0556b7ccb043549f6351c643fe04cb2cf9
   > Blocks: 0            Seconds: 0
   > contract address:    0xE9b5449f7B07100b77aCE985887Cd3abD002c7a2
   > block number:        36
   > block timestamp:     1658337391
   > account:             0x76E4eFAD592aDC8c6e28f24f02a9a63719cf9A0E
   > balance:             999.988423563425118759
   > gas used:            250142 (0x3d11e)
   > gas price:           2.508490828 gwei
   > value sent:          0 ETH
   > total cost:          0.000627478912697576 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:     0.000627478912697576 ETH


2_deploy_contracts.js
=====================

   Deploying 'Token'
   -----------------
   > transaction hash:    0x2e5cf3f8152cd5e40232e98457b24ae444f7e12f961e4aebfbed26184ecc7c5d
   > Blocks: 0            Seconds: 0
   > contract address:    0x19c7f53563Bd40738A09dE7286adb72ed7845898
   > block number:        38
   > block timestamp:     1658337391
   > account:             0x76E4eFAD592aDC8c6e28f24f02a9a63719cf9A0E
   > balance:             999.979851471040231294
   > gas used:            3373989 (0x337ba5)
   > gas price:           2.506519127 gwei
   > value sent:          0 ETH
   > total cost:          0.008456967962787603 ETH


   Deploying 'TimeLock'
   --------------------
   > transaction hash:    0xa121e7121ebe3ceb4c0b2d56b9ddeca75bdcf0f76715b26158f582fb23780ffd
   > Blocks: 0            Seconds: 0
   > contract address:    0x27153db75E0bEf31BE1e33865CbaB3CaD37A4990
   > block number:        44
   > block timestamp:     1658337391
   > account:             0x76E4eFAD592aDC8c6e28f24f02a9a63719cf9A0E
   > balance:             999.972290097912906798
   > gas used:            2735392 (0x29bd20)
   > gas price:           2.503027984 gwei
   > value sent:          0 ETH
   > total cost:          0.006846762723209728 ETH


   Deploying 'Governance'
   ----------------------
   > transaction hash:    0x0239cdc0d51a0ac185d7d0e206f89d8c92e407cab632bbcfd7ccab5b901a0ab7
   > Blocks: 0            Seconds: 0
   > contract address:    0xA64c052227CeBa0eFB077Fa16698Da59F31953cB
   > block number:        45
   > block timestamp:     1658337392
   > account:             0x76E4eFAD592aDC8c6e28f24f02a9a63719cf9A0E
   > balance:             999.961782646983943563
   > gas used:            4198415 (0x40100f)
   > gas price:           2.502718509 gwei
   > value sent:          0 ETH
   > total cost:          0.010507450928963235 ETH


   Deploying 'Treasury'
   --------------------
   > transaction hash:    0x0afe60c62ef67d73dd44e79f618a8acf03c76d5d1e2b4c041b2e28d6bf251754
   > Blocks: 0            Seconds: 0
   > contract address:    0xF8546B18a8A232cC9661aA2B4bD4D7843466F7cB
   > block number:        46
   > block timestamp:     1658337392
   > account:             0x76E4eFAD592aDC8c6e28f24f02a9a63719cf9A0E
   > balance:             974.960452271848239371
   > gas used:            531624 (0x81ca8)
   > gas price:           2.502473808 gwei
   > value sent:          25 ETH
   > total cost:          25.001330375135704192 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:     25.027141556750664758 ETH

Summary
=======
> Total deployments:   5
> Final cost:          25.027769035663362334 ETH
```

**Comment by jinxlo** [comment]
Hey thank you for your time on helping me solve this issue. 

- [* ] 1. Did you modify the [dappuniversity/governance](https://github.com/dappuniversity/governance) repo after clone? Is the timelock contract actually there?   
- No i did not modify the [dappuniversity/governance](https://github.com/dappuniversity/governance) repo and yes the timelock.sol is contract is there
- [ *] 2. Your npm version may be why this is happening. Try npm install -g npm@6, reinstall truffle and ganache, and try again.
ive updated npm using `npm install -g npm@6`

i've reinstalled everything yet i seem to be having the same issue

**Comment by cliffoo** [comment]
Hm weird not sure why you had to manually rename it, the lower|upper case should be consistent. It migrated fine for me without changing anything.

Anyway glad it's resolved for you! Cheers.
