### ISSUE TITLE
truffle installation error

### ISSUE THREAD

**Issue by TheCodeInjection** [trufflesuite/truffle#5337]
![instessss](https://user-images.githubusercontent.com/97714325/180124802-b197bc03-4f7f-47b4-9666-205683503e9f.PNG)
idk whats the problem...

**Comment by molecula451** [comment]
there is no issue here so far, truffle should be already installed, you may ignore these npm warning but you can still use truffle run a command <code> npx truffle --help </code>

**Comment by benjamincburns** [comment]
@TheCodeInjection I don't see any error in the screenshot that you posted. In the future please copy and paste the actual error text into the issue, and please be sure to follow the issue template when reporting a problem.

**Comment by benjamincburns** [comment]
Closing this as there isn't enough information here to solve your problem. Please open a new issue with the information requested if you are still having an issue.
