### ISSUE TITLE
Feature request: Add compiler version into the contract object

### ISSUE THREAD

**Issue by JosefJ** [trufflesuite/truffle#539]
## Description
Add the 'version' variable from `solc/wrapper.js` to the contract JSON. 

## Reason
For debugging and backtracking of contract creation it would be useful to maintain a compiler version and build together with the contract bytecode in the built JSON. 

For instance while validating an older contract with etherscan or trying to do self-verification of older compiled contracts, one has to rely on storing the version somewhere else.

**Comment by phiferd** [comment]
I'd like to see this also.

**Comment by gnidan** [comment]
This has been released in v4.0.0. Thank you!
