### ISSUE TITLE
On android react native bug invalid integer

### ISSUE THREAD

**Issue by Haianh9999** [trufflesuite/truffle#5403]
When importing truffle/hdwallet-provider I get an error invalid integer on android but ios work fine
- @truffle/hdwallet-provider(2.0.13)
- Node version (16.15.0)

**Comment by cliffoo** [comment]
Hey @Haianh9999 thanks for opening this. Could you share the full error message? Also, do you have some reproduction steps (RN / expo CLI? Anything other than installing and importing hdwallet-provider?) that we can follow to help you debug? A repo would work!

**Comment by Haianh9999** [comment]
@cliffoo error message is invalid integer 0x420000000. I’ve been install @truffle/hd-walletprovider then import this. When restart app i catch the error on android

**Comment by cliffoo** [comment]
Could you share the full error message with stacktrace please? That would help us in trying to pinpoint where the error is coming from. Thanks.

**Comment by Haianh9999** [comment]
@cliffoo Sorry i only see error: INVALID INTEGER 0x4200000

**Comment by cliffoo** [comment]
Okay. Are you using expo or react native CLI? And what version of hdwallet-provider are you using? If it's not the latest version `2.0.13`, could you try installing `@truffle/hdwallet-provider@latest` and see if there's still problems?

**Comment by Haianh9999** [comment]
@cliffoo i use react-native cli. Version off @truffle/hdwallet-provider is latest version. I still got the error INVALID INTEGER on android, ios work normally

**Comment by Haianh9999** [comment]
@cliffoo Could you help me to solve this problem?

**Comment by cliffoo** [comment]
I'm actually getting import errors related to hdwallet-provider's dependencies, not the invalid integer error you're getting... I guess there are two things you can do:
1. Are you sure there's no more to the error message than `INVALID INTEGER ...`? When you're running the app and something goes wrong, the metro server should complain with meaningful error messages.
2. Can you create a minimum RN project that consistently recreates the error? Or link me to your project if you're comfortable with that.

**Comment by Haianh9999** [comment]
@cliffoo Sorry I investigated and know the error is with other library not @truffle/hdwallet-provider. Thank you for your help 🙇

**Comment by fainashalts** [comment]
Thanks for the update @Haianh9999! I'll close this issue for maintenance but please open a new issue if you encounter any problems using Truffle!
