### ISSUE TITLE
Non-deterministic deploy errors when project includes a file containing only abstract contracts

### ISSUE THREAD

**Issue by brynbellomy** [trufflesuite/truffle#541]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If a truffle project imports a file containing only abstract contracts (used as interfaces in other contracts ... let's call it Interfaces.sol), several issues occur:

1) Truffle always seems to need to recompile Interfaces.sol regardless of whether changes have been made.
2) Truffle often throws the error "The contract code couldn't be stored, please check your gas amount" unless I make sure to `rm -rf build` and `truffle migrate --network blah --reset`.  Sometimes it still fails when I follow this procedure, but the failures seem to be less frequent.
3) If Truffle _does_ successfully deploy, it still sometimes fails to add the deployed addresses to the JSON contract artifacts (the `address` key is missing entirely).

When I move the abstract contracts into the .sol file that refers to them, and remove Interfaces.sol entirely, all of the deployment issues seem to disappear.

It's worth mentioning that none of my migration scripts attempt to deploy the abstract contracts — they're just used as state variables in other contracts.  So this isn't a dupe of #476.

## Steps to Reproduce

Reproducing this issue can be difficult, as it seems to be sort of non-deterministic.  However, I have a setup like the following:

Interfaces.sol
```
contract Shape {
    function numSides() returns (uint);
}
```

MyContract.sol
```
import "./Interfaces.sol";

contract MyContract {
    Shape shape;

    function setShape(address _shape) {
        shape = Shape(_shape);
    }
}
```

Shape.sol
```
contract Shape {
    function numSide() returns (uint) {
        return 123;
    }
}
```

In order to rectify the issue, I can simply move the abstract contract version of `Shape` into MyContract.sol, while leaving the real `Shape` in Shape.sol.  So maybe it's an issue where identically-named contract artifacts are overwriting one another, even though one of them is never deployed (nor even deployable)?

This doesn't seem like intended behavior, and isn't ideal for various use cases.

## Expected Behavior

Truffle should consistently deploy the contracts without an error.  Also, it shouldn't require a `rm -rf build` and without requiring the `--reset` flag for `truffle migrate` (although to be fair, these techniques only mitigated the problem rather than eliminating it).

Or at the very least, it should fail the same way every time, and preferably should give a helpful error message.

## Actual Results

`truffle migrate` frequently throws the error "The contract code couldn't be stored, please check your gas amount".  Sometimes it even does so _after_ deploying the contract that requires the interfaces (so to use the above example, it deploys MyContract without an error, then attempts to deploy Shape, and dies with the "check your gas" error).

## Environment

* Operating System: macOS Sierra 10.12.5 (although this is reproducible when running against a Dockerized Ubuntu geth)
* Truffle version: 3.4.8
* Ethereum client: geth 1.6.6-stable-10a45cb5
* node version: 8.1.3
* npm version: 5.0.3

**Comment by illuzen** [comment]
+1

**Comment by shdmitry2000** [comment]
+1

**Comment by critesjosh** [comment]
+1

**Comment by Sokel** [comment]
+1

**Comment by brynbellomy** [comment]
I found some evidence to suggest that part of the problem may be related to the abstract contracts being named identically to the real contracts that they represent.  A possible fix (other than requiring contract writers to always use unique names) might be to avoid generating JSON artifacts for abstract contracts.

Can't say with 100% certainty that this fix takes care of the entire bug, but might be worth trying for those of you who +1'd.

**Comment by roderik** [comment]
I ran into the same error. My issue was that I forgot to implement an abstract function.

**Comment by GreenFomo** [comment]
Think I'm probably having the same issue. For me it always seems to throw " Error: The contract code couldn't be stored, please check your gas amount." if what i'm deploying inherits from an abstract contract. Any idea @tcoulter ? Thanks!

**Comment by gnidan** [comment]
Hi all, thanks for raising this concern.

Unfortunately, the work required to fix this issue at its root will have to be prioritized for a later release. In the meantime, recommended workaround is to not re-use contract names.

**Comment by illuzen** [comment]
> In the meantime, recommended workaround is to not re-use contract names.

This appears to be a deeper problem. There are several mentions of these symptoms in similar issues. I believe they are related. Either that or this error is used as a catch all of some sort.

**Comment by evgen-povt** [comment]
Have the same issue.
But my interface has the name differencing from the contract name.
And the contract inherits the interface:
`
contract Shape is ShapeIf {
...
}
`
