### ISSUE TITLE
Getting Errors on running truffle command: Cannot find module '@truffle/db-loader'

### ISSUE THREAD

**Issue by CleoPatra2772** [trufflesuite/truffle#5414]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------
I had several problems when downloading truffle -g. I had Error: EACCES: permission denied error. On my final attempt, I used  sudo chown -R $USER /usr/local/lib/node_modules, and was able to download it successfully. 

## Issue

After downloaded Truffle, when I ran the command "truffle init" , I get an error that says command not found. Then I ran the command 
"npx truffle init" 
truffle inits successfully. But when I cd into my project folder and do "npx truffle init", I get an error 
Error: Cannot find module '@truffle/db-loader'

## Environment

* Operating System: MacOS
* Ethereum client:
* Truffle version (`truffle version`): Truffle v5.5.25 (core: 5.5.25)
Ganache v7.4.0
* node version (`node --version`): v16.15.1
* npm version (`npm --version`): 8.11.0

**Comment by eggplantzzz** [comment]
Oh yeah, don't use `sudo` when installing Truffle. The best thing to do is re-install npm and Node using a Node version manager which is what npm recommends. This resolves these types of permissions errors. Using `sudo` can cause problems later on down the line and it is likely that is what you are experiencing here. Check out this article from npm which elaborates a bit more on using nvm. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by CleoPatra2772** [comment]
I re-installed npm and Node.js. I was able to download truffle globally. But then, when I tried to run "truffle compile", I get the "zsh: command not found: truffle" error

**Comment by cds-amal** [comment]
>I re-installed npm and Node.js. 

Since you're still having issues, can you try using the `npm doctor` diagnostic command? It is a good way to check the status of your node/npm setup.

>I was able to download truffle globally. 

:thinking: Do you mean you installed truffle globally with npm? Can you share the output if is the case?

**Comment by CleoPatra2772** [comment]
> > I re-installed npm and Node.js.
> 
> Since you're still having issues, can you try using the `npm doctor` diagnostic command? It is a good way to check the status of your node/npm setup.
> 
> > I was able to download truffle globally.
> 
> 🤔 Do you mean you installed truffle globally with npm? Can you share the output if is the case?


Yea, I was able to install -g truffle without Error: EACCES:, When I run the command like `truffle compile`, I get `zsh: command not found: truffle `

But when I ran `npx truffle compile`, it worked. so hooray! I can finally work on my project
