### ISSUE TITLE
Turn off Solidity optimizer by default

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#543]
See here: 
https://github.com/trufflesuite/truffle-compile/pull/5

Note for users navigating here: To get the previous optimization settings, add the following to your `truffle.js` configuration. 

```json
optimizer: {
  "enabled": true,
  "runs": 200
}
```

See the [solc configuration value](http://truffleframework.com/docs/advanced/configuration#solc) for more.

**Comment by gnidan** [comment]
This likely involves increasing the gas limit, as tests are likely to fail.

**Comment by gnidan** [comment]
Potential problems, turning optimizer off:
- Assert is too big
  Potential solution: Increase block gas limit for testing.
- Ensure `"test"` and `"develop"` networks both respect the config gasLimit

**Comment by gnidan** [comment]
Optimizer was previously set to:
```json
optimizer: {
  "enabled": true,
  "runs": 200
}
```

New setting sets enabled to `false` (and keeps `runs` at 200 for default)

**Comment by elie222** [comment]
Why was this switched off?

**Comment by elie222** [comment]
Ah I see the issue at the top. Anyone know how much extra gas things cost without optimization?
