### ISSUE TITLE
[Bug in dependency] Introducing HDWalletProvider causes responses to get mixed up

### ISSUE THREAD

**Issue by abrindam** [trufflesuite/truffle#5440]
- [ x ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I wanted to make you aware of the following issue which I have just filed: https://github.com/MetaMask/web3-provider-engine/issues/418

This is a bug in one of your dependencies, not in your own code, but it initially looked like a Truffle problem to me, so I wanted to make sure it was on your radar. In my opinion, it is fairly serious as it is effectively a data corruption issue.

I also saw that "web3-provider-engine" may be deprecated soon, so it may be possible they won't fix this issue. If you're considering moving off of it due to this proposed deprecation, I wanted to give you one more data point!

## Steps to Reproduce

Please see the linked issue.

## Expected Behavior

Please see the linked issue.

## Actual Results

Please see the linked issue.

## Environment

Please see the linked issue.

**Comment by gnidan** [comment]
Thanks for bringing this to our attention! We'll triage this and figure out next steps and post our next steps here on this issue.

**Comment by cliffoo** [comment]
Related issue: https://github.com/trufflesuite/truffle/issues/5068

**Comment by lsqproduction** [comment]
Thank you @abrindam, we are closing this issue as it is related to #5068. Please follow the changes there.

**Comment by abrindam** [comment]
Thanks you folks for the quick response.

I wanted to provided some frank but hopefully constructive feedback. This issue is particularly disturbing to me, for two reasons. 

First, the issue results in data corruption, with the effect that a blockchain query can seemingly result in completely incorrect and made-up data. There are numerous scenarios in which is this would be a major problem. While the issue is intermittent, it occurs fairly regularly with sustained use, so I would expect anyone using this framework to encounter this problem at one point or another.

Second, the issue occurs in a very fundamental part of the stack, which is the network transport layer, and represents, in my opinion, a pretty basic error in something as simple as request-response correlation. This kind of bug really shatters my confidence in the library as a whole.

As a result of the above, I will likely be dropping the use of this library and moving to an alternative.

Again, hopefully you find the feedback above constructive!
