### ISSUE TITLE
Truffle test doesn't reinitialize accounts[0] balance after re-running passing test suite 

### ISSUE THREAD

**Issue by Janaka-Steph** [trufflesuite/truffle#545]
## Issue
Truffle test doesn't reinitialize accounts[0] balance after re-running a passing test suite a second time. 
In tests, each `contract()` will reinitialize accounts[0] balance to 100 ethers, but imagine the test suite finish with accounts[0] balance at 80, when you rerun the tests then accounts[0] balance will always be reinitialized to 80. 

## Steps to Reproduce
Rerun passing test suite 2 times

## Expected Behavior
Always start with 100

## Environment

* Operating System: Mac
* Truffle version: v3.4.9 
* Ethereum client: Testrpc v4.0.1
* node version: v8.2.1

**Comment by sh4ka** [comment]
Hello @Janaka-Steph is it possible that it might be because the accounts reside in the network and not in the contract? If you want to achieve the desired behavior you should start with a clean fresh network every time you run the tests.
