### ISSUE TITLE
Not able to debug transaction in hardhat project

### ISSUE THREAD

**Issue by tomasz90** [trufflesuite/truffle#5459]
## Issue

Not able to debug transaction in hardhat project.

## Steps to Reproduce

1. Run node at localhost using hardhat
2. Make any transaction
3. Grab the hash
4. Try to debug this transaction using accuired hash

## Expected Behavior

I am able to debug transaction

## Actual Results

Not able to debug transaction, error:

```
SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/from-hardhat/dist/src/ask-hardhat.js:91:1)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
Truffle v5.5.27 (core: 5.5.27)
```

## Environment

* Operating System: MacOS Monterey
* Hardhat version: 2.10.1
* Truffle version: 5.5.27
* node version: 14.20.0
* npm version: 6.14.17

**Comment by gnidan** [comment]
Oh no! Thanks for reporting this. I haven't seen this before. I don't suppose your project is open source so I can try to reproduce locally? Or if there's any additional information you can provide?

**Comment by gnidan** [comment]
(In the meantime, I'll add some extra error logging and release a dist tag later today for you to try.)

**Comment by tomasz90** [comment]
> Oh no! Thanks for reporting this. I haven't seen this before. I don't suppose your project is open source so I can try to reproduce locally? Or if there's any additional information you can provide?

yep, unfortunately the project is not open source :(

I can add that when I call "truffle debug" without hash I am getting similar message:

`SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/from-hardhat/dist/src/ask-hardhat.js:91:1)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12)
Truffle v5.5.27 (core: 5.5.27)`

**Comment by gnidan** [comment]
How do you normally run Hardhat? Do you follow their recommendation and install it locally (`npm install --save-dev hardhat`) and then run it via `npx hardhat`?

**Comment by gnidan** [comment]
Alright, I just published a dist-tag release that should hopefully provide more error information. Could you try installing `truffle@hardhat-error`, e.g.:

```console
npm uninstall -g truffle
npm install -g truffle@hardhat-error
```

... and then let me know what `truffle debug` gives you? Clearly I made some false assumption when I implemented this 😭

**Comment by tomasz90** [comment]
Thanks for your quick response!

Yep, I I have hardhat installed locally and when I run node, I use "npx hardhat node"

Here is my latest error message:
```
{"defaultNetwork":"localhost","networks":{"hardhat":{"hardfork":"arrowGlacier","blockGasLimit":30000000,"gasPrice":"auto","chainId":31337,"throwOnTransactionFailures":true,"throwOnCallFailures":true,"allowUnlimitedContractSize":false,"mining":{"auto":true,"interval":0,"mempool":{"order":"priority"}},"accounts":{"initialIndex":0,"count":20,"path":"m/44'/60'/0'/0","passphrase":"","mnemonic":"test test test test test test test test test test test junk","accountsBalance":"10000000000000000000000"},"loggingEnabled":false,"gasMultiplier":1,"minGasPrice":"00","chains":{},"gas":30000000,"initialDate":"2022-08-21T17:16:30.814Z"},"localhost":{"accounts":"remote","gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":40000,"url":"http://localhost:8545"},"mainnet":{"accounts":["0x3f72b427768a6134b7315d95914e108be939c1d52895f8d35f1e982468530407","0xa4ad8a69cd0588380f0d7c6a81a82712482ef49b851e43498c527b329bf2329e"],"gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":20000,"chainId":1,"url":"https://eth-mainnet.alchemyapi.io/v2/SHeOs67mFsCW92Z9oWgcH01bDKEkcINC"},"goerli":{"accounts":["0x3f72b427768a6134b7315d95914e108be939c1d52895f8d35f1e982468530407","0xa4ad8a69cd0588380f0d7c6a81a82712482ef49b851e43498c527b329bf2329e"],"gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":20000,"chainId":5,"url":"https://eth-goerli.alchemyapi.io/v2/SHeOs67mFsCW92Z9oWgcH01bDKEkcINC"},"kovan":{"accounts":["0x3f72b427768a6134b7315d95914e108be939c1d52895f8d35f1e982468530407","0xa4ad8a69cd0588380f0d7c6a81a82712482ef49b851e43498c527b329bf2329e"],"gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":20000,"chainId":42,"url":"https://eth-kovan.alchemyapi.io/v2/SHeOs67mFsCW92Z9oWgcH01bDKEkcINC"},"rinkeby":{"accounts":["0x3f72b427768a6134b7315d95914e108be939c1d52895f8d35f1e982468530407","0xa4ad8a69cd0588380f0d7c6a81a82712482ef49b851e43498c527b329bf2329e"],"gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":20000,"chainId":4,"url":"https://eth-rinkeby.alchemyapi.io/v2/SHeOs67mFsCW92Z9oWgcH01bDKEkcINC"},"ropsten":{"accounts":["0x3f72b427768a6134b7315d95914e108be939c1d52895f8d35f1e982468530407","0xa4ad8a69cd0588380f0d7c6a81a82712482ef49b851e43498c527b329bf2329e"],"gas":"auto","gasPrice":"auto","gasMultiplier":1,"httpHeaders":{},"timeout":20000,"chainId":3,"url":"https://eth-ropsten.alchemyapi.io/v2/SHeOs67mFsCW92Z9oWgcH01bDKEkcINC"}},"solidity":{"compilers":[{"version":"0.8.12","settings":{"optimizer":{"enabled":false,"runs":200},"outputSelection":{"*":{"*":["abi","evm.bytecode","evm.deployedBytecode","evm.methodIdentifiers","metadata"],"":["ast"]}}}}],"overrides":{}},"etherscan":{"apiKey":""},"gasReporter":{"enabled":true,"showMethodSig":true,"showTimeSpent":true},"abiExporter":[{"path":"./abis","runOnCompile":true,"clear":true,"flat":true,"only":[],"except":[],"spacing":2,"pretty":false,"format":"json"}],"contractSizer":{"alphaSort":true,"disambiguatePaths":false,"runOnCompile":true,"strict":false,"only":[],"except":[]},"typechain":{"outDir":"typechain","target":"ethers-v5","alwaysGenerateOverloads":false},"subgraph":{"name":"10c-labs-blockchain-nfts","product":"subgraph-studio","allowSimpleName":true,"indexEvents":true},"paths":{"subgraph":"./subgraph","root":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain","configFile":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/hardhat.config.ts","sources":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/contracts","cache":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/cache","artifacts":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/artifacts","tests":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/test"},"mocha":{"timeout":40000},"dodoc":{"include":[],"exclude":[],"runOnCompile":true,"testMode":false,"outputDir":"./docs","templatePath":"/Users/tomaszkulig/Projects/10c-labs-blockchain-nfts/blockchain/node_modules/@primitivefi/hardhat-dodoc/dist/src/template.sqrl"},"spdxLicenseIdentifier":{"overwrite":false,"runOnCompile":false},"tracer":{"enabled":false,"logs":false,"calls":false,"sstores":false,"sloads":false,"gasCost":false,"opcodes":[],"nameTags":{},"_internal":{}}}

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/from-hardhat/dist/src/ask-hardhat.js:95:1)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12)
Truffle v5.5.28-hardhat-error.0 (core: 5.5.28-hardhat-error.0)
Node v14.20.0
```

**Comment by gnidan** [comment]
Thanks for the info @tomasz90! I just reached out to you on Telegram as per your link in your GH readme to help you debug this.

**Comment by gnidan** [comment]
@tomasz90 I just put out a new dist-tag release ([`truffle@5.5.28-hardhat-error.1`](https://www.npmjs.com/package/truffle/v/5.5.28-hardhat-error.1)).

Unfortunately, the log dump you shared didn't confirm my hypotheses, but I made a change that hopefully makes things more robust. Would you mind trying that new version and letting me know what happens?

**Comment by gnidan** [comment]
Wait, is that the entire error message? It doesn't say show this? `Error reading information from Hardhat console. Expected valid JSON, got: ${output}`

**Comment by tomasz90** [comment]
Sorry to be specific:

Error: Error reading information from Hardhat console. Expected valid JSON, got: No need to generate any newer typings.
✅ Generated documentation for 24 contracts
 ·---------------------------|--------------|----------------·
 |  Contract Name            ·  Size (KiB)  ·  Change (KiB)  │
 ····························|··············|·················
 |  Address                  ·       0.084  ·                │
 ····························|··············|·················
 |  console                  ·       0.084  ·                │
 ····························|··············|·················
 |  Counters                 ·       0.084  ·                │
 ····························|··············|·················
 |  ERC20                    ·       4.602  ·                │
 ····························|··············|·················
 |  ERC721                   ·       8.382  ·                │
 ····························|··············|·················
 |  ERC721NFT                ·      13.576  ·                │
 ····························|··············|·················
 |  ERC721Util               ·      18.544  ·                │
 ····························|··············|·················
 |  Marketplace              ·       9.040  ·                │
 ····························|··············|·················
 |  MarketplaceObjects       ·       0.062  ·                │
 ····························|··············|·················
 |  MetaTransactionExecutor  ·       5.259  ·                │
 ····························|··············|·················
 |  Strings                  ·       0.084  ·                │
 ····························|··············|·················
 |  WETH                     ·       4.762  ·                │
 ·---------------------------|--------------|----------------·
[["localhost","http://localhost:8545"],["mainnet","https://eth-mainnet.alchemyapi.io/v2/XXXXXXXXXXXXXXXXX"],["goerli","https://eth-goerli.alchemyapi.io/v2/XXXXXXXXXXXXXXXXX"],["kovan","https://eth-kovan.alchemyapi.io/v2/XXXXXXXXXXXXXXXXX"],["rinkeby","https://eth-rinkeby.alchemyapi.io/v2/XXXXXXXXXXXXXXXXX"],["ropsten","https://eth-ropsten.alchemyapi.io/v2/XXXXXXXXXXXXXXXXX"]]

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/from-hardhat/dist/src/ask-hardhat.js:95:1)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
Truffle v5.5.28-hardhat-error.1 (core: 5.5.28-hardhat-error.1)
Node v14.20.0

**Comment by gnidan** [comment]
Oh! Now that's interesting!

So it seems like `npx hardhat console` is automatically generating typings, and then printing this on stdout? Do you know how I can make this behavior happen locally so I can figure out a workaround?

**Comment by tomasz90** [comment]
This project is using typechain, so the table might be generated by it.

**Comment by gnidan** [comment]
Hm, I thought I had that turned on in my test project. I will play around and see if I can't figure it out. Stay tuned... thank you for this crucial missing piece of information!

**Comment by tomasz90** [comment]
Do I have to have some additional configuration except hardhat? I am running node on localhost:8545 
Then I generate testing data against this node and grab tx hash of this transaction. Please let me know :)

**Comment by gnidan** [comment]
> Do I have to have some additional configuration except hardhat? I am running node on localhost:8545
> Then I generate testing data against this node and grab tx hash of this transaction. Please let me know :)

It should just work with no extra config. I'll figure out how to handle this situation with TypeChain and then hopefully check with @alcuadrado about other, similar possible situations where `npx hardhat console` will print to stdout unprompted.

**Comment by gnidan** [comment]
In the meantime, if you can turn off TypeChain temporarily, hopefully that's a valid workaround.

**Comment by gnidan** [comment]
Hm... I'm not sure how to make that table appear. I just confirmed that my test project **does** have TypeChain turned on, but I don't see that output. Is there something you're doing in your hardhat.config.ts?

**Comment by gnidan** [comment]
Can you share the list of HH plugins you're using?

**Comment by gnidan** [comment]
Got one more build for you to try, taking a slightly different approach. 🤞 I think this will do it: [`truffle@5.5.29-hardhat-error.0`](https://www.npmjs.com/package/truffle/v/5.5.29-hardhat-error.0).

Please let me know if this fixes things for you, and then I'll clean up the changes to get reviewed for our next release!

Thanks for your help!

**Comment by tomasz90** [comment]
@gnidan 
This time I am getting:
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:114:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/lib/index.js:98:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:48)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Truffle v5.5.29-hardhat-error.0 (core: 5.5.29-hardhat-error.0)

But after I provided parameter --network localhost, I was able to debug my transaction :)
So it seems that truffle can't detect proper network since I am runinng node on 8545 port.

**Comment by gnidan** [comment]
> This time I am getting:

Ah! @tomasz90 You'll need to pass `--network localhost`, same as you would via `npx hardhat run --network localhost. This doesn't work with the built-in `hardhat` network, sorry.

**Comment by gnidan** [comment]
Oh I didn't even get to the end of your unhandled exception to see that you got this working :D 

Yeah, will have to clean up the error messaging! Thanks for following up!

**Comment by tomasz90** [comment]
Yep, but this message was very helpful ;)
I tested debugging once again using official truffle release, but same problem. So this fix wasn't released yet? :)

**Comment by gnidan** [comment]
> Yep, but this message was very helpful ;)
> I tested debugging once again using official truffle release, but same problem. So this fix wasn't released yet? :)

Nope, not yet... wanted to get your test results first with that build. ConsenSys gave everyone this week off, so next week when the team is back, I'll get those changes into a PR for a stable release. Let's leave this issue open until that's live.

In the meantime, feel free to keep using that dist-tag version :) Thank you!

**Comment by gnidan** [comment]
@tomasz90 (and anyone else following this)... #5510 is good to go and this issue should be fixed in the next stable release, sometime during the middle of next week.

**Comment by haltman-at** [comment]
This should be fixed now in the latest release!
