### ISSUE TITLE
In tests, events are not printed when tests are passing

### ISSUE THREAD

**Issue by Janaka-Steph** [trufflesuite/truffle#546]
Hello,

If my tests are failing the logs are printed in a pretty format, one log per line.
Example:
```
Events emitted during test:
    ---------------------------
    LogString(str: Fallback Start)
    LogString(str: Fallback Start)
    LogBool(res: false)
    LogString(str: Fallback End)
    LogBool(res: true)
    LogString(str: Fallback End)
    LogBool(res: true)
```
On the contrary, if my tests are passing the logs are not printed. I can get the logs from the tx receipt but I need to format the result myself in order to have something pretty.

**Comment by hacktar** [comment]
That's unfortunately still true! 
Events emitted during test are printed only in case of assertions failed.
