### ISSUE TITLE
Truffle debugger & decoder should handle new-style internal function pointers

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#5466]
## Issue

So, if you compile Solidity with `viaIR` turned on, it uses a different representation for internal function pointers.  Instead of them containing actual program counter values, internal functions are now represented by an abstract index.

Fortunately, this index isn't hard to compute.  The order that the functions are given in is just the order they appear in the contract's source, and if they're inherited, base contracts appear before derived contracts.  Note that functions marked `external` are skipped, and so are functions marked `private` if they're in a base contract.  Indexing starts at 1, as 0 is used for the designated invalid function.

(Thought: I just realized I didn't account for free functions.  Crud.  I'll have to determine how those work; hopefully those don't screw this up too much.  I should probably also test whether internal library functions affect things in any way.  I'm hoping I don't end up having to file issues with Solidity...)

(They're still 8 bytes, thankfully, even though that was excessive even with the old format and especially excessive now.  Guess they wanted to limit the breakage.)

Anyway, debugger and decoder should have functionality for handling these.  Note that the main difference will not be in Codec itself, seeing as internal function pointers are decoded with a passed-in lookup table; it's constructing that table that will be different.  (Possibly much of the new code will go in source-map-utils... or maybe Codec's AST utils, it could go there too.)  However, I think we'd also probably want to revise the output format for internal function pointers, which previously assumed that internal function pointers would necessarily be given in terms of PC value.  This would of course be a breaking change to the output format, but since I don't think much external to us is thinking about internal function pointers, I don't think it'd be a big problem.

## Environment

* Truffle version (`truffle version`): 5.5.27

**Comment by haltman-at** [comment]
So, this has turned out to be more of an issue than I realized -- it turns out that indices are only assigned to functions that get pointed to, which is substantially harder to determine.  We may have to wait for https://github.com/ethereum/solidity/issues/13425 before properly addressing this, although determining that isn't necessarily *impossible*, just a bunch of work.  Still, I'm putting aside for now the problem of finding a proper solution to this.

**Comment by Smithbull001** [comment]
> ## Issue
> So, if you compile Solidity with `viaIR` turned on, it uses a different representation for internal function pointers. Instead of them containing actual program counter values, internal functions are now represented by an abstract index.
> 
> Fortunately, this index isn't hard to compute. The order that the functions are given in is just the order they appear in the contract's source, and if they're inherited, base contracts appear before derived contracts. Note that functions marked `external` are skipped, and so are functions marked `private` if they're in a base contract. Indexing starts at 1, as 0 is used for the designated invalid function.
> 
> (Thought: I just realized I didn't account for free functions. Crud. I'll have to determine how those work; hopefully those don't screw this up too much. I should probably also test whether internal library functions affect things in any way. I'm hoping I don't end up having to file issues with Solidity...)
> 
> (They're still 8 bytes, thankfully, even though that was excessive even with the old format and especially excessive now. Guess they wanted to limit the breakage.)
> 
> Anyway, debugger and decoder should have functionality for handling these. Note that the main difference will not be in Codec itself, seeing as internal function pointers are decoded with a passed-in lookup table; it's constructing that table that will be different. (Possibly much of the new code will go in source-map-utils... or maybe Codec's AST utils, it could go there too.) However, I think we'd also probably want to revise the output format for internal function pointers, which previously assumed that internal function pointers would necessarily be given in terms of PC value. This would of course be a breaking change to the output format, but since I don't think much external to us is thinking about internal function pointers, I don't think it'd be a big problem.
> 
> ## Environment
> * Truffle version (`truffle version`): 5.5.27

**Comment by cliffoo** [comment]
Resolved in [v5.10.1](https://github.com/trufflesuite/truffle/releases/tag/v5.10.1)
