### ISSUE TITLE
Remove `truffle build` command

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#5472]
Is the `truffle build` command widely used? If not, we should consider removing it in order to reduce maintenance workload.

Note: This was captured from an internal session where we discussed **potential** future breaking changes for major releases. Until the team assigns this ticket, this is merely a proposal, and not a commitment to make this specific change.

**Comment by dongmingh** [comment]
closing as duplicate #3226

**Comment by benjamincburns** [comment]
@dongmingh this issue was captured to remove this command. #3226 only captures the need to deprecate it. Given that a deprecation notice has been added, I'm not sure why #3266 is still open.
