### ISSUE TITLE
Remove the `truffle watch` command

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#5473]
Is the `truffle watch` command widely used? If not, we should consider removing it in order to reduce maintenance workload.

Note: This was captured from an internal session where we discussed **potential** future breaking changes for major releases. Until the team assigns this ticket, this is merely a proposal, and not a commitment to make this specific change.

**Comment by dongmingh** [comment]
closing as duplicate #3227

**Comment by benjamincburns** [comment]
@dongmingh this issue was captured to remove this command. #3227 only captures the need to deprecate it. Given that a deprecation notice has been added, I'm not sure why #3227 is still open.
