### ISSUE TITLE
`truffle migrate` `--save` flag doesn't work and is not documented

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#5495]
While digging through migrations code, we found out that there is the undocumented option `save`. If you set this to `false`, Truffle will omit saving the set migrations on chain. This option should probably be documented on the website and in the Truffle help.

Additionally there is a bug with this option. If you pass it as a flag (`--save`) on the command line, it gets parsed as a string and will not work correctly. We should tell yargs that this option is a boolean so that it will get parsed properly and work.

**Comment by lsqproduction** [comment]
Addresses in [Truffle v5.5.32]( https://github.com/trufflesuite/truffle/releases/tag/v5.5.32).
