### ISSUE TITLE
Add `after_deploy` callback parameter to truffle.js config file

### ISSUE THREAD

**Issue by danfinlay** [trufflesuite/truffle#550]
Per [this provider-engine issue](https://github.com/MetaMask/provider-engine/issues/176#issuecomment-325559955), some users want to use things like provider engine to deploy their contracts in a custom way, and provider engine requires a `.stop()` call to deallocate some event listeners.

Truffle could add an optional `after_deploy` key on the `truffle.js` exports that would be called after contracts were deployed, where devs could do cleanup like this.

**Comment by tcoulter** [comment]
It sounds to me like the `engine` is keeping the process open, perhaps with a timer that's not properly dereferenced? Once the deploy has finished, Truffle attempts to quit -- or at least it should, if nothing keeps the process open. Timeouts and intervals can keep the process open in Node. 

If this is the case for the provider engine, perhaps you can use [timeout.unref()](https://nodejs.org/api/timers.html#timers_timeout_unref) to ensure it doesn't keep the process going:

```
var timeout_id = setTimeout(function() {...}, 1000);

// Check for the existence of `unref` so code is portable to the browser.
if (timeout_id.unref) {
  timeout_id.unref();
}
```

This will ensure the process doesn't stay open after deploys.

**Comment by krabradosty** [comment]
@tcoulter I'm sorry, but it's not a solution.

**Comment by Levino** [comment]
This should be reopened. If one is using https://github.com/MetaMask/provider-engine with truffle it will never stop.

**Comment by cgewecke** [comment]
@Levino How are you using the provider engine? Through a Wallet Provider? 

At the moment we address this within truffle by running `process.exit` at the end of a command. And Web3 1.0 has [just added](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.36) a way of closing the provider in `beta.36` so that should be available soon for Truffle V5 as well.
