### ISSUE TITLE
Installed Truffle using npm install ; Getting self certificate error

### ISSUE THREAD

**Issue by sfcadhiraj** [trufflesuite/truffle#551]
I installed Truffle using:
npm install -g truffle@beta
But, while executing truffle init, I am getting following error:

events.js:160
throw er; // Unhandled 'error' event
^

Error: self signed certificate in certificate chain
at Error (native)
at TLSSocket. (_tls_wrap.js:1092:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

Please suggest!
Note: I am using cmd , since there is a limitation on using powershell.

**Comment by javaing** [comment]
for example
mkdir demo-video
cd demo-video
truffle init
=>It's wrok!  , Itjust need a clear directory

**Comment by tcoulter** [comment]
Hi there. This looks like one weird issue. As /u/javaing pointed out, those steps should work. 

Based on the error message received, my guess is it has something to do with `npm`; it's likely that some SSL certificate got mangled along the way while it attempted to download the right packages. (Note: Truffle has no control over how `npm` structures their service).

This doesn't seem to be a Truffle error, so I'm going to close it for housekeeping issues. However, if you figure out the issue, please document it here as it might be of help to others. Thanks!

**Comment by husky-parul** [comment]
Has anyone figured out how to fix this issue?
