### ISSUE TITLE
Feature request: global registry for events

### ISSUE THREAD

**Issue by cag** [trufflesuite/truffle#555]
Suppose there are two contracts: `A.sol` and `B.sol`. `A` has a method which does a delegatecall to an arbitrary contract. `B` has a method which logs some events. Since `A` doesn't have the event declaration, the contract artifact doesn't get the event info when the migration is run, and as a result, B's event log doesn't get parsed by A's `truffle-contract` if A delegatecalls B. However, `truffle test` _does_ catch and parse the B's event log when A delegatecalls B. Furthermore, if B's event declaration gets copied into A, A will catch and parse the event log when it delegatecalls B.

To solve this, I propose a global registry for events which automatically add the parsing metadata for contracts as they get initialized so that those logs can be parsed even when they are produced in a different contract's context.

**Comment by snario** [comment]
As proxy contract schemes like what Gnosis does [here](https://github.com/gnosis/gnosis-safe-contracts/tree/master/contracts) become more common, this will be quite helpful.

**Comment by elenadimitrova** [comment]
This is a problem for us at Colony too where events in called contracts aren't surfaced in the transaction logs. We've solved this for `A` and `B` in the example above being the Interface and actual contract implementation. For different contracts however this is still a problem, see `Colony.addGlobalSkill` calls `ColonyNetwork.addSkill` which  emits `SkillAdded` that never surfaces in the transaction log of the `Colony.addGlobalSkill` call https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/Colony.sol#L112

**Comment by cgewecke** [comment]
@elenadimitrova Coincidentally saw a possible solution to this yesterday [here](https://github.com/zulhfreelancer/truffle-events). 

It's a library that decodes logs for what the author calls 'deep events', using the data on the receipt and knowledge of what contracts are interrelated. Usage looks like this (from their docs):
```javascript
var truffleAssert = require('truffle-assertions');
var truffleEvent  = require('truffle-events');

// code omitted for brevity

it("Foo#doSomethingExtra", async function(){
  var fooScope = await f.doSomethingExtra(b.address);
  var barScope = truffleEvent.formTxObject('Bar', 1, fooScope);

  truffleAssert.eventEmitted(fooScope, 'LogNumber', (ev) => {
    return ev.number == 100;
  });

  truffleAssert.eventEmitted(barScope, 'LogAlphabet', (ev) => {
    return ev.word == "Hello!";
  });
});
```

We've talked about developing a global registry within Truffle and it's seemed like the appropriate place is at the artifact level. A rewrite of that is scheduled for late summer / fall so it will be a while before there are any real developments there.

**Comment by jdkanani** [comment]
We are using following code to decode logs:

```js
// File: helpers/log-decoder.js 

import ethers from 'ethers'

export default class LogDecoder {
  constructor(abis = []) {
    this._methodIDs = {}
    abis.forEach(abi => {
      const methodInterface = new ethers.Interface(abi)
      Object.keys(methodInterface.events).forEach(evtKey => {
        const evt = methodInterface.events[evtKey]
        const signature = evt.topics[0]
        this._methodIDs[signature] = evt
      })
    })
  }

  decodeLogs(logs) {
    return logs.map(log => {
      const evt = this._methodIDs[log.topics[0]]
      return {
        address: log.address.toLowerCase(),
        event: evt.name,
        signature: evt.signature,
        args: evt.parse(log.topics, log.data)
      }
    })
  }
}
```

**Usage:**

```js
const decoder = new LogDecoder(abis)
const result = decoder.decodeLogs(receipt.logs)
// result will be the decoded log array
```
