### ISSUE TITLE
Error: PollingBlockTracker - encountered an error while attempting to update latest block

### ISSUE THREAD

**Issue by son-of-win** [trufflesuite/truffle#5555]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I have tried to fix the error on my website with the suggestion in [issue 3356](https://github.com/trufflesuite/truffle/issues/3356)
* replace 'https' in the provider url with 'wss', but i still got the same error.  
Hope it helped!
```testnet: {
  provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
  network_id: 97,
  confirmations: 10,
  timeoutBlocks: 200,
  skipDryRun: true
}```  
What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cliffoo** [comment]
Hey @son-of-win could you try connecting to other bsc endpoints as listed [here](https://docs.bnbchain.org/docs/rpc/)? Do you encounter the same error?

**Comment by cliffoo** [comment]
Closing for issue maintenance.
