### ISSUE TITLE
Assert.sol throwing errors on 'truffle test' on Truffle version v3.4.6

### ISSUE THREAD

**Issue by andrewrd** [trufflesuite/truffle#556]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Assert.sol is throwing errors when running truffle.test. I installed the previous version of truffle(3.4.3) and these errors do not appear. 

## Steps to Reproduce

Install latest version of truffle. Run a test with assert and the errors will appear. 

## Expected Behavior

Tests run, with no error codes. 

## Actual Results

Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/EventCreator.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/SafeMath.sol...
Compiling ./contracts/Topic.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

truffle/Assert.sol:114:20: Warning: This declaration shadows an existing declaration.
    function equal(string A, string B, string message) constant returns (bool result) {
                   ^------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:137:23: Warning: This declaration shadows an existing declaration.
    function notEqual(string A, string B, string message) constant returns (bool result) {
                      ^------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:206:20: Warning: This declaration shadows an existing declaration.
    function equal(bytes32 A, bytes32 B, string message) constant returns (bool result) {
                   ^-------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:226:23: Warning: This declaration shadows an existing declaration.
    function notEqual(bytes32 A, bytes32 B, string message) constant returns (bool result) {
                      ^-------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:286:20: Warning: This declaration shadows an existing declaration.
    function equal(address A, address B, string message) constant returns (bool result) {
                   ^-------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:305:23: Warning: This declaration shadows an existing declaration.
    function notEqual(address A, address B, string message) constant returns (bool result) {
                      ^-------^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:403:20: Warning: This declaration shadows an existing declaration.
    function equal(bool A, bool B, string message) constant returns (bool result) {
                   ^----^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:426:23: Warning: This declaration shadows an existing declaration.
    function notEqual(bool A, bool B, string message) constant returns (bool result) {
                      ^----^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:451:20: Warning: This declaration shadows an existing declaration.
    function equal(uint A, uint B, string message) constant returns (bool result) {
                   ^----^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:474:23: Warning: This declaration shadows an existing declaration.
    function notEqual(uint A, uint B, string message) constant returns (bool result) {
                      ^----^
truffle/Assert.sol:64:5: The shadowed declaration is here:
    uint8 constant A = uint8(byte('a'));
    ^---------------------------------^

,truffle/Assert.sol:497:22: Warning: This declaration shadows an existing declaration.
    function isAbove(uint A, uint B, string message) constant returns (bool result) {
                     ^----^
truffle/Assert.sol:64:5: The shadowed declaration is here

## Environment

* Operating System: MACOSX 
* Truffle version: 3.4.6
* Ethereum client: testrpc 
* node version: v6.11.1
* npm version: 3.10.10

**Comment by dwalintukan** [comment]
I get the same issue with 3.4.6.

**Comment by nieldlr** [comment]
Experiencing same issue as @aaronmboyd with these versions on MacOS Sierra:

Truffle v3.4.9 (core: 3.4.8)
Solidity v0.4.15 (solc-js)
Node v7.10.1

**Comment by baldwinjj** [comment]
Same issue:
* Ubuntu 16.04.2
* Truffle v3.4.9
* Solidity v0.4.13
* Node v7.4.1

**Comment by slash686** [comment]
Experiencing same issues:

- macOS 10.12.6 (16G29)
- Truffle v3.4.9
- solc-js v0.4.15
- Node v7.0.0

**Comment by charltonh** [comment]
Experiencing same issues trying to run truffle test on rinkeby testnet.

I've discovered that Assert.sol generates an EVM binary that is just too big to be deployed without it choking.  I ended up manually editing Assert.sol and taking out a couple of funcs that I wasn't using.

Now the EVM binary is slightly smaller and deploys on rinkeby, and my tests complete successfully.

**Comment by acidfreako** [comment]
Windows 10 64 bit
Truffle v3.4.9 (core: 3.4.8)
Solidity v0.4.15 (solc-js)
node v6.11.3


experience same issue as @aaronmboyd

**Comment by aaronmboyd** [comment]
Confirmed also that reverted to *truffle@3.4.3* and warnings were removed. Nonetheless they appear to be warnings only, and didn't affect the outcome of my unit tests.

**Comment by tcoulter** [comment]
This has been fixed on Truffle v4.0.0-beta.0. Will go out with the final release. Hop on the beta if you'd like to check it out. See the [Release notes](https://github.com/trufflesuite/truffle/releases/tag/v4.0.0-beta.0).

Cheers!
