### ISSUE TITLE
getPair call via Ethers.Contract does not return a pair address

### ISSUE THREAD

**Issue by Samboy76** [trufflesuite/truffle#5567]
### Discussed in https://github.com/orgs/trufflesuite/discussions/5566

<div type='discussions-op-text'>

<sup>Originally posted by **Samboy76** September 26, 2022</sup>
Hi,

When I call following **getPair** under uniswapFactory contract I created via ethers.Contract in my javascript it doesn´t return any pair address.

```
const UniswapV2Factory = require("./build/contracts/IUniswapV2Factory.json");

uniswapFactory = new ethers.Contract(
		'0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f', // uniswap v2 factory address in Etherscan mainnet
		UniswapV2Factory.abi, wallet
	);

	const pairAddress = await uniswapFactory.getPair(wethAddress, otherAddress);
  	const pair = new Contract(pairAddress, UniswapV2Pair.abi, wallet);
	console.log("yeah2!");
```
Strange thing is if I removed `await `keywork it returns _Promise { <pending> }_.

However, if I run `await uniswapFactory.getPair(wethAddress, otherAddress);`  directly under Truffle console it resolves the pair address correctly.

Any suggestions would be greatly appreciated as it´s been bugging me also for a very long time.

Thank you</div>

**Comment by gnidan** [comment]
Hey @Samboy76 could you please share what you actually do get for `pairAddress`? It's weird that the behavior is different for `truffle console` vs. inside a JS file.

Could you also please share the output of `ethers.version` (or `require("ethers").version` if you want a one-liner), both via `truffle console` and via this JS script?

Just trying to figure out what's going on here. Thanks!

**Comment by Samboy76** [comment]
Hi @apdan510, at the end I tried also using `@uniswap-sdk` library so here´s the actual code snippet, which still generates the same issue, along with the output Truffle console commands demonstrating the expected results.

```
const { ChainId, Token, Fetcher, WETH, Pair, TokenAmount, FACTORY_ADDRESS, INIT_CODE_HASH } = require ('@uniswap/sdk');

const provider = new ethers.providers.JsonRpcProvider(process.env.INFURA_URL);
const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);
const otherAddress = '0x111111111117dC0aa78b770fA6A738034120C302'; // Etherscan 1INCH mainnet

const OTHER = new Token(ChainId.MAINNET, otherAddress, 18);
const uniswapPair = await Fetcher.fetchPairData(OTHER, WETH[OTHER.chainId], provider,);
```
**Output Truffle console commands**

_truffle(mainnet_fork)> const { INFURA_URL, METAMASK_ADDRESS } = process.env;
undefined
truffle(mainnet_fork)> const { ChainId, Token, Fetcher, WETH, Pair, TokenAmount, FACTORY_ADDRESS, INIT_CODE_HASH } = require ('@uniswap/sdk');
undefined
truffle(mainnet_fork)> const provider = new ethers.providers.JsonRpcProvider(process.env.INFURA_URL);
undefined
truffle(mainnet_fork)> const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);
undefined
truffle(mainnet_fork)> const otherAddress = '0x111111111117dC0aa78b770fA6A738034120C302';
undefined
truffle(mainnet_fork)> const OTHER = new Token(ChainId.MAINNET, otherAddress, 18);
undefined
truffle(mainnet_fork)> const uniswapPair = await Fetcher.fetchPairData(OTHER, WETH[OTHER.chainId], provider,);
undefined
truffle(mainnet_fork)> console.log("uniswapPair ", uniswapPair);
uniswapPair Pair {
liquidityToken: Token {
decimals: 18,
symbol: 'UNI-V2',
name: 'Uniswap V2',
chainId: 1,
address: '0x26aAd2da94C59524ac0D93F6D6Cbf9071d7086f2'
},
tokenAmounts: [
TokenAmount {
numerator: [JSBI],
denominator: [JSBI],
currency: [Token],
token: [Token]
},
TokenAmount {
numerator: [JSBI],
denominator: [JSBI],
currency: [Token],
token: [Token]
}
]
}
undefined
truffle(mainnet_fork)> console.log("uniswapPair.reserve0 ", uniswapPair.reserve0);
uniswapPair.reserve0 TokenAmount {
numerator: JSBI(3) [ 909525627, 1065416368, 151027, sign: false ],
denominator: JSBI(2) [ 660865024, 931322574, sign: false ],
currency: Token {
decimals: 18,
symbol: undefined,
name: undefined,
chainId: 1,
address: '0x111111111117dC0aa78b770fA6A738034120C302'
},
token: Token {
decimals: 18,
symbol: undefined,
name: undefined,
chainId: 1,
address: '0x111111111117dC0aa78b770fA6A738034120C302'
}
}
undefined
truffle(mainnet_fork)> console.log("uniswapPair.reserve1 ", uniswapPair.reserve1);
uniswapPair.reserve1 TokenAmount {
numerator: JSBI(3) [ 1072296449, 41327450, 69, sign: false ],
denominator: JSBI(2) [ 660865024, 931322574, sign: false ],
currency: Token {
decimals: 18,
symbol: 'WETH',
name: 'Wrapped Ether',
chainId: 1,
address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
},
token: Token {
decimals: 18,
symbol: 'WETH',
name: 'Wrapped Ether',
chainId: 1,
address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
}
}
undefined_

truffle(mainnet_fork)> truffle version
Truffle v5.5.31 (core: 5.5.31)
Ganache v7.4.3
Solidity - >=0.5.0 <0.9.0 (solc-js)
Node v16.17.0
Web3.js v1.7.4

I have tried both methods via uniswap v2 sdk method above and through `ethers.Contract `as shown in below code snippet

```
// SDK´s off-chain method of getPair function
	const uniswapEthOtherAddr = getCreate2Address(
		uniswapFactory.address,
		keccak256(['bytes'], [pack(['address', 'address'], [otherAddress, wethAddress])]),
		INIT_CODE_HASH
	);
	uniswapEthOther = new ethers.Contract(
		uniswapEthOtherAddr,
		UniswapV2Pair.abi, 
		provider
	);

        const reserves = await uniswapEthOther.functions.getReserves();
```

Neither code method works. If I remove `await `keyword in both it always returns with _Promise { <pending> }_. If I put it back in, it doesn´t print any output or get resolved. It just calls the callback() function and halts JS execution.

I´m desperate as it seems under Truffle runtime, it fails on making certain on-chain ethers.Contract calls to certain functions such as getReserves() which I need to perform for my script.

Could it be that under Truffle runtime even though I´ve installed @ethers package correctly and making the right method calls on ethers.Contract in the JS code that it still insists on web3js.Contracts as what I am finding out, truffle works best with web3js by default. Could this be ultimately the problem why I am failing to make ANY on-chain calls on ethers.Contract method?

Thanks for your help. Much appreciated!

**Comment by Samboy76** [comment]
truffle(mainnet_fork)> ethers.version
'ethers/5.7.1'

**Comment by Samboy76** [comment]
When I run `await uniswapFactory.getPair(wethAddress, otherAddress);` it calls the `callback()` method and doesn´t return any value when I run this through the console.

**Comment by cliffoo** [comment]
@Samboy76  ^

**Comment by cliffoo** [comment]
Closing for issue maintenance.
