### ISSUE TITLE
truffle develop/console does not exclude `console` or `develop` commands

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#5578]
When this condition is hit, you have to enter multiple `.exit`s to leave the REPL.

## Reproduction steps
- `reprod`
- `truffle init`
- `truffle develop`
- `console`
- `console`
- `console`
- You will need to enter `.exit` 4 times to leave the REPL

**Comment by gnidan** [comment]
I've also observed this behavior with bash and zsh ;)

**Comment by cds-amal** [comment]
> I've also observed this behavior with bash and zsh ;)

`truffle develop` behaves differently than Node's REPL.  Is this the expected behavior @gnidan?

```console
$ node
Welcome to Node.js v16.17.1.
Type ".help" for more information.
> console
Object [console] {
  log: [Function: log],
  warn: [Function: warn],
  dir: [Function: dir],
  time: [Function: time],
  timeEnd: [Function: timeEnd],
  timeLog: [Function: timeLog],
  trace: [Function: trace],
  assert: [Function: assert],
  clear: [Function: clear],
  count: [Function: count],
  countReset: [Function: countReset],
  group: [Function: group],
  groupEnd: [Function: groupEnd],
  table: [Function: table],
  debug: [Function: debug],
  info: [Function: info],
  dirxml: [Function: dirxml],
  error: [Function: error],
  groupCollapsed: [Function: groupCollapsed],
  Console: [Function: Console],
  profile: [Function: profile],
  profileEnd: [Function: profileEnd],
  timeStamp: [Function: timeStamp],
  context: [Function: context]
}
> .exit

$ truffle develop
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Truffle Develop started at http://127.0.0.1:9545/

< -- SNIP Accounts header -- >

truffle(develop)> console
truffle(develop)> .exit
truffle(develop)> .exit
╭─amal@faifai  ~/dev/scratch/2022/09/29/test-nesting ‹node-16.17.1› ‹truffle-core›
╰─$

**Comment by gnidan** [comment]
It used to be that Truffle wouldn't let you run `console` or `develop` from within its repl. We should probably go back to that behavior.

**Comment by cds-amal** [comment]
I missed that. Somehow, by the time we filter `excludedCommands`, the `truffle-command`, that should be excluded, [is already executing](https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/commands/console/run.js#L23-L27). I suspect this may be related to the `meta/run/help` refactor.

**Comment by sukanyaparashar** [comment]
This should be fixed in the new release https://github.com/trufflesuite/truffle/releases/tag/v5.6.3
