### ISSUE TITLE
Pass network parameter in truffle test

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#559]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

As a developer,
I'd like to have network parameters being passed along with accounts to a test suite, similar to what we have in migrations: `deployer, network, accounts`.
We don't need deployer, but having network - would be great. 
As a workaround, I use `web3.version.network` to get `networkId`
## Steps to Reproduce
Run JS based test suite:
```
contract("Contribution", (
  [ miner, 
    owner],
  network) => { 
 console.log(network) //undefined
});
```
## Expected Behavior

network should show the name of the network under which `truffle test --network NAME` was ran.
## Actual Results

`undefined`

## Environment

* Truffle version: 3.4.9

**Comment by mandys** [comment]
+1

**Comment by dt665m** [comment]
+1

**Comment by fabianem** [comment]
+1

**Comment by iisaint** [comment]
+1

**Comment by brianmcmichael** [comment]
+1
