### ISSUE TITLE
There is a dependency cycle involving db

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#5600]
@truffle/db has a devDependency on @truffle/migrate even though it is not listed in the package.json. See [this](https://github.com/trufflesuite/truffle/blob/develop/packages/db/src/project/test/integration.spec.ts#L9).

When you add @truffle/migrate to the devDependencies for @truffle/db, lerna complains about the dependency cycle. We should get rid of this somehow.

**Comment by lsqproduction** [comment]
released in truffle [v5.6.4](https://github.com/trufflesuite/truffle/releases/tag/v5.6.4)
