### ISSUE TITLE
Cannot add compilation to `ProjectDecoder` instance

### ISSUE THREAD

**Issue by cliffoo** [trufflesuite/truffle#5602]
Current workaround is to re-instantiate when new compilations come. It would be nice if I can keep feeding that one instance.

```
truffle -v
5.6.0
```

**Comment by haltman-at** [comment]
Question, which of the three decoder classes is this referring to?  Just the `ProjectDecoder`?  All of them?

**Comment by cliffoo** [comment]
Yea only `ProjectDecoder` for this one. I don't know if the same need will arise for contract and contract instance decoders; if they do I guess I'll open issues separately.

**Comment by haltman-at** [comment]
OK cool, if it's just `ProjectDecoder` I don't think this should be too hard.

**Comment by dongmingh** [comment]
Close the issue since this is fixed in Truffle v5.6.6.
