### ISSUE TITLE
Error better when using <bad_cmd> inside of truffle console

### ISSUE THREAD

**Issue by lsqproduction** [trufflesuite/truffle#5619]
## Issue

Currently, Truffle produces a not-so-pretty error message when <bad_cmd> is entered inside of a Truffle REPL.
This can be either a user trying to use an invalid Truffle command or some bad javascript.

## Steps to Reproduce
`truffle develop` inside of a truffle project.
`bad_cmd`

## Expected Behavior
returns a less scary error like how Node handles it.
`Uncaught ReferenceError: bad_cmd is not defined`

## Actual Results

```truffle(develop)> bad_cmd
evalmachine.<anonymous>:0
bad_cmd
^

Uncaught ReferenceError: bad_cmd is not defined
    at evalmachine.<anonymous>
    at sigintHandlersWrap (node:vm:276:12)
    at Script.runInContext (node:vm:139:14)
    at runScript (/Users/dongminghwang/work/trufflesuite/truffle/packages/core/lib/console.js:394:21)
    at Console.interpret (/Users/dongminghwang/work/trufflesuite/truffle/packages/core/lib/console.js:409:21)
    at bound (node:domain:433:15)
    at REPLServer.runBound [as eval] (node:domain:444:12)
    at REPLServer.onLine (node:repl:902:10)
    at REPLServer.emit (node:events:513:28)
    at REPLServer.emit (node:domain:489:12)
```

**Comment by eggplantzzz** [comment]
Hmm, I'm not sure we want to deviate from the results that Node gives you. This is what occurs in the Node console when you enter something random in the Node console and hit enter. `truffle develop`/`truffle console` is a Node console with "extra Truffle stuff" after all. :)

**Comment by eggplantzzz** [comment]
Ah yeah, good point!

**Comment by Pobepto** [comment]
@lsqproduction @eggplantzzz 
Hi all, I can help if you tell me what needs to be done :)

**Comment by eggplantzzz** [comment]
Hey hey @Pobepto! Sure, you'll notice that if you open up a normal Node terminal, enter some random text, and then hit enter you will receive a message that reads something like "Uncaught ReferenceError: someText is not defined". This should be what you get if you do the same thing in the Truffle console (try running `truffle develop` inside the directory for a Truffle project and you will be given a JS terminal). However, as @lsqproduction posted above, you will receive some extra output, namely the stacktrace.

We would like for users to receive the exact same result as the normal Node repl. Offhand I'm not sure what exactly needs to be done as some investigation is necessary. Are you thinking of trying to take this on?

**Comment by Pobepto** [comment]
Yeah, I think I can figure it out 🤔
Anyway, I'll get to work and if there's any news I'll let you know

**Comment by Pobepto** [comment]
@eggplantzzz, yeah, it's okay, I've already created a couple of PR's here 🙂

**Comment by sj00coder** [comment]
Hey @Pobepto , @eggplantzzz , Is anyone up on this issue? I want to contribute. Let me know if I could do anything. 
Thanks

**Comment by shubhamshd** [comment]
Hi @lsqproduction @eggplantzzz @Pobepto any update please?
is this issue still active?
and would you allow me to take this on ??

**Comment by cds-amal** [comment]
@shubhamshd 

This issue has already been resolved. 

```console
truffle(develop)> bad_cmd
Uncaught ReferenceError: bad_cmd is not defined
truffle(develop)>
```

**Comment by shubhamshd** [comment]
great thanks @cds-amal  for informing, appreciated!!!
