### ISSUE TITLE
Upgrade `webpack` init repo to use Web3 v0.20.0 or above.

### ISSUE THREAD

**Issue by rohithpr** [trufflesuite/truffle#562]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm running Metamask on Chrome.

When I run the following in the developer console on a random page or even Etherdelta Metamask prompts me to sign a message and this is the expected behaviour.

`web3.personal.sign('0x68656c6c6f', web3.eth.accounts[0], console.log)`

However, when I try to run the same in the dev console on the basic Dapp created by `$ truffle init webpack` I get an error saying:

Uncaught TypeError: web3.personal.sign is not a function

web3.personal does not have a function "sign" but has only `["_requestManager", "newAccount", "unlockAccount", "sendTransaction", "lockAccount", "listAccounts", "getListAccounts"]` on the truffle dapp but has the following on other sites `["_requestManager", "newAccount", "importRawKey", "unlockAccount", "ecRecover", "sign", "sendTransaction", "lockAccount", "listAccounts", "getListAccounts"]`.

Note: `web3.eth.sign(web3.eth.coinbase, '0x68656c6c6f', console.log)` still works though.

## Steps to Reproduce

Steps to reproduce the issue:

1. Create the basic truffle dapp by running the following commands:
  - truffle init webpack
  - truffle compile
  - truffle migrate
  - npm run dev

2. Open http://127.0.0.1:8081 in Chrome
3. Run `web3.personal.sign('0x68656c6c6f', web3.eth.accounts[0], console.log)` in the Chrome dev console.

## Expected Behavior

Metamask should prompt me to sign the message "hello".

## Actual Results

An error is thrown because `sign` is `undefined`.

## Environment

* Operating System: OSX
* Truffle version: 3.2.8
* Ethereum client: Metamask on Chrome
* node version: 6.11.1
* npm version: 3.10.10

**Comment by tcoulter** [comment]
Hi there.

You're using the `webpack` init boilerplate. That boilerplate is slightly old. We need to upgrade it to use the latest web3. You can do this yourself by editing the `package.json` file after running `truffle init webpack`. Simply change the web3 version it looks for to `^0.20.0` and rerun `npm install`.

Thanks for reporting this. Appreciate it.

**Comment by DiscRiskandBisque** [comment]
Web3 has been upgraded! Closing this for housekeeping, but please re-open if the problem persists.

Commit here: https://github.com/truffle-box/webpack-box/commit/c67956e2db79053e071097d84b91f04b87659394
