### ISSUE TITLE
Error better when only `truffle` is entered inside of a REPL

### ISSUE THREAD

**Issue by lsqproduction** [trufflesuite/truffle#5620]
## Issue

Unclear error messaging is used when only `truffle` is entered inside of a Truffle REPL.
This can be because the user forgets to enter a valid truffle command or is not sure how to use Truffle REPL.

## Steps to Reproduce

`truffle develop` inside of a truffle project
`truffle`

## Expected Behavior
Prompt the user to use `--help | help` to display the full list of valid truffle commands. And provide an URL link to read up more on the documentation for `truffle console` and `truffle develop`

Possibly block by #5312

What you expected to happen.

## Actual Results
results from #5579 
```
truffle(develop)> truffle
"ℹ️ : 'truffle undefined' is not a valid Truffle command"
```

**Comment by cds-amal** [comment]
This was resolved in #5579
