### ISSUE TITLE
Unable to deploy to Goerli

### ISSUE THREAD

**Issue by quantix-nft** [trufflesuite/truffle#5623]
Unable to understand a working configuration to deploy to Goerli.
I've tried a few but the migration remains pending and after 750 sec is aborted.

My current config is:
```
goerli: {
     networkCheckTimeout:10000,
     provider: () => new HDWalletProvider(mnemonic,'wss://goerli.infura.io/ws/v3/'+process.env.INFURA_KEY), 
     network_id: 5,
     networkCheckTimeout: 1000000,
     timeoutBlocks: 2000,
     skipDryRun: true,
     gasPrice:0,
     gas:0,
     maxFeePerGas:2500000001,
     maxPriorityFeePerGas:2500000001,
     confirmations:0,
     websockets:false,
     setTimeout:500000000
}
```
impossible to set EIP-1559 too, please help !

**Comment by eggplantzzz** [comment]
I'm not sure what is going on but it could be something related to your configuration options. To start with, try a more simple configuration like 
```
networks: {
  goerli: {
    provider: () => new HDWalletProvider(mnemonic,'wss://goerli.infura.io/ws/v3/'+process.env.INFURA_KEY), 
    network_id: 5
  },
  // ...rest of config
```

Does this simpler version work? Do note that `gas`/`gasPrice` and `maxPriorityFeePerGas`/`maxFeePerGas` are mutually exclusive.

**Comment by quantix-nft** [comment]
with a simpler configuration (like that one you've suggested) the result is the same.
The deploy stucks and  after 750 secs fails . I'm desperate

**Comment by earizon** [comment]
Same problem for me.  I can deploy to Goerli from remix online IDE, using the metamask plugin and transactions are committed in about 10-15seconds.

Not sure if this is a truffle or infura "gateway" problem. 

Is there any debug flag to help dig into the problem and provide better bug reports?

**Comment by eggplantzzz** [comment]
Hmm, I just used @truffle/hdwallet-provider to deploy a test toy project to Goerli successfully. If you want to link me a project on GitHub I can try and use your configuration (minus your Infura key of course) to deploy and troubleshoot this. Let me know if you have a public project you can link for me to use!

**Comment by earizon** [comment]
@eggplantzzz Can you share the output of `npm list`. I think my problem is related to some wrong version in truffle of hdwallet.

**Comment by cliffoo** [comment]
^ @quantix-nft

**Comment by cliffoo** [comment]
Closing for issue maintenance. @quantix-nft feel free to re-open if you're still having trouble deploying to goerli (and please provide minimal reproduction steps with it!) Thanks!
