### ISSUE TITLE
Add Ethers provider support to Truffle

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#5659]
In our efforts to support various L2s, we have found that many of these protocols rely on ethers definitions for things like signers and providers. Truffle does not seem to deeply support ethers, defaulting in many cases to web3.js. We need to fix this!

- [ ] Audit everywhere the Truffle code relies on web3js
- [ ] Scope out the changes needed to support ethers in addition
- [ ] Implement

**Comment by fainashalts** [comment]
@benjamincburns are you working on this? I believe Kevin had planned to pass this work to you to complete but wanted to check in!

**Comment by benjamincburns** [comment]
I'm not working on it per se, I just had a conversation with Kevin about it prior to his departure.

Unfortunately I don't have much to add beyond what he already captured in the HackMD document linked from issue #5131

**Comment by gnidan** [comment]
>  Audit everywhere the Truffle code relies on web3js

Note that we do have to distinguish "relies on Web3.js" from "exposes Web3.js to our users". Obviously we're not going to rework the internals of Truffle for an external concern.

**Comment by haltman-at** [comment]
Note we already have issue #5138.  Is this one intended to be broader?  If so you might want to change the titles to clarify the difference.

**Comment by fainashalts** [comment]
I think we can close this issue in favor of #5138. Thanks!
