### ISSUE TITLE
issue while installation

### ISSUE THREAD

**Issue by sinoysiby** [trufflesuite/truffle#566]
## Issue

Truffle cant not be installed using npm or yarn. Getting error

## Steps to Reproduce

yarn- command:    **yarn global add truffle**
npm- command:   **npm install -g truffle**

## Expected Behavior

Truffle should get isntalled

## Actual Results

while using yarn  : **error Received malformed response from registry for undefined. The registry may be down.**

while using npm: **npm ERR! registry error parsing json**

## Environment

* Operating System: windows 7x64
* Truffle version: 
* Ethereum client:
* node version: 7.10.0
* npm version:  4.2.0
* yarn version: 0.23.4

**Comment by tcoulter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [We need to get THIS done (see how I attached it to some random ticket?)](https://trello.com/c/558L1B7b/1-we-need-to-get-this-done-see-how-i-attached-it-to-some-random-ticket)

**Comment by tcoulter** [comment]
This sounds like a network error. i.e., for some reason, `npm` and `yarn` can't talk to the npm servers to figure out which packages to install. This doesn't appear to be a Truffle issue.

I'm going to close for housekeeping issues. Please try reinstalling Truffle again, and if needed, connect to another network. Also look into whether or not the npm repository is blocked on your domain or network.

Cheers!
