### ISSUE TITLE
The help command for `truffle console` doesn't mention the `--network` option

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [trufflesuite/truffle#5662]
## Issue

The help command for `truffle console` doesn't mention the `--network` option.

## Steps to Reproduce

Run `truffle console --help`, you'll see the following output:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3990373/198902947-ffe4b571-704e-489f-8908-ec08b8b99acc.png">

In this screenshot you'll also note I successfully use the `--network` option in the proceeding command.

## Expected Behavior

A description of the `--network` options as it relates to `truffle console`.

## Actual Results

The `--network` option isn't mentioned.

## Environment

* Operating System: macOS 12.6
* Ethereum client: Any
* Truffle version (`truffle version`): 5.6.2
* node version (`node --version`): 18.12.0
* npm version (`npm --version`): 8.19.2

**Comment by gnidan** [comment]
Good catch!

**Comment by lsqproduction** [comment]
Yeah, That's because on the command's meta.js. The help and builder objects have different info. `--help` uses the information from the `builder` object.  in this case, it is missing those.  Going to put in a fix for this.
