### ISSUE TITLE
`truffle help` version command mismatches implementation

### ISSUE THREAD

**Issue by jeffsmale90** [trufflesuite/truffle#5681]
- [x] I've discussed with @haltman-at before filing this issue.

---------------------------

## Issue

`truffle help` shows incorrect instructions for accessing the version information.

## Details

`truffle help` shows `truffle --version` but returns:

```
`truffle --version` is not a valid truffle command. Please see `truffle help` for available commands.
```

`truffle version` is the actual command to show version information

## Environment

* Operating System: MacBook pro
* Ethereum client: Ganache v7.3.2
* Truffle version (truffle version): 5.5.22
* node version (node --version): 16.14.2
* npm version (npm --version): 8.5.0

**Comment by lsqproduction** [comment]
Hi @jeffsmale90 Was this inside `truffle develop` or `truffle console`?

**Comment by cliffoo** [comment]
Hey @jeffsmale90 were you trying `truffle --version` in a truffle REPL? Try `truffle --version` on the latest version.

**Comment by fainashalts** [comment]
Hi @jeffsmale90 this issue is about to go stale so I wanted to draw your attention to it in case it is still something that needs our attention. Thanks!

**Comment by lsqproduction** [comment]
Closing for issue maintenance.

**Comment by cds-amal** [comment]
This issue is resolved. Tested against truffle v5.7.2
