### ISSUE TITLE
Validating the arguments of an overloaded function fails due to having a different number of parameters than the base function

### ISSUE THREAD

**Issue by GreenFomo** [trufflesuite/truffle#569]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

As the title says, attempting to call an overloaded function from e.g. a JS test fails, since the validation for the number of function parameters fails, not taking into account that there might be 2 functions with the same name.

## Steps to Reproduce
In a contract:

```
function theFn(string p1) {}

function theFn(string p1, string p2) {}
```

In a test:
`
instance.theFn.call('first param', 'second param')
`

will fail, since the validator in `cli.bundled.js` (see full stacktrace below) doesn't take into account that there could be multiple functions with the same name, but different number of parameters.

It's important to call the function that is defined last, that's the one ignored by the validator (calling the first version of the function, with only 1 param, works fine).

## Expected Behavior

I would expect to be able to call an overloaded function from js tests, since it's valid Solidity. 

## Actual Results

```
 Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (/usr/lib/node_modules/truffle/build/cli.bundled.js:37282:16)
      at SolidityFunction.validateArgs (/usr/lib/node_modules/truffle/build/cli.bundled.js:223127:22)
      at SolidityFunction.toPayload (/usr/lib/node_modules/truffle/build/cli.bundled.js:223143:10)
      at SolidityFunction.call (/usr/lib/node_modules/truffle/build/cli.bundled.js:223184:24)
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:212184:16
      at Promise (<anonymous>)
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:212175:18
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Environment

* Operating System: CentOS 7
* Truffle version: v3.4.9
* Ethereum client: EthereumJS TestRPC v4.1.1 (ganache-core: 1.1.2)
* node version: v8.4.0
* npm version: 5.3.0

**Comment by wphan** [comment]
Ran into this issue while testing an implementation of [ERC223](https://github.com/ethereum/EIPs/issues/223) which overloads `transfer()` from ERC20.

**Comment by rudolfix** [comment]
I fixed this in our truffle fork here
https://github.com/Neufund/truffle-contract/commit/ecae09942db60039f2dc4768ceeb88776226f0ca
You call overloaded functions web3 style
```
const tx = await token.transfer["address,uint256,bytes"](address, initialBalance, data, { from: fromAddr });
```
I can provide PR to `truffle-contract` if maintainers are interested

**Comment by elenadimitrova** [comment]
I'm sure maintainers @tcoulter and @gnidan would be interested in a PR @rudolfix :)

**Comment by rudolfix** [comment]
Here it is: https://github.com/trufflesuite/truffle-contract/pull/75

**Comment by DeRain** [comment]
As an option, we could call overloaded methods via web3 directly, i've created an article with details https://beresnev.pro/test-overloaded-solidity-functions-via-truffle/

**Comment by MidnightLightning** [comment]
> It's important to call the function that is defined last

No, that's not how the function "overloading" works in Solidity; it's not that the last-defined function with that name is the "real" one, but rather ***all*** functions with the same name are valid, if they have different input parameters.

From the example in the original post, if a contract has the functions:

```
function theFn(string p1);
function theFn(string p1, string p2);
```

The ABI would include something like:
```
[
  {
    name: 'theFn',
    type: 'function',
    inputs: [
      { "name": "p1", "type": "string" }
    ]
  },
  {
    name: 'theFn',
    type: 'function',
    inputs: [
      { "name": "p1", "type": "string" },
      { "name": "p2", "type": "string" }
    ]
  }
]
```

It would be valid to call either function, since the signature for the two is different (`theFn(string)` vs. `theFn(string,string)`).

In this case, the Truffle testing infrastructure needs to know how to parse out:

```js
instance.theFn.call('first param', 'second param'); // call theFn(string,string)
instance.theFn.call('first param'); // call theFn(string)
instance.theFn.call('first param', { from: accounts[3] }); // call theFn(string), using account[3]
instance.theFn.call('first param', 'second param', { from: accounts[3] }); // call theFn(string,string), using account[3]
```
Namely, it needs to do some introspection on the last argument given, to see if it's an options object or some other type of input.

Or, go away from using an extra parameter to define additional options and go with a "builder" type interface like:

```js
instance.theFn
  .options({ from: accounts[3]})
  .call('first param'); // <== clearly the intent is to call the method that only has one argument since only one argument is provided
```

Or, in addition to the convenience methods defined on the contract instance (e.g. `instance.theFn()`), to also provide a means to explicitly give the function signature to call:

```js
instance.method('theFn(string,string)') // <== clearly the intent is to call the method with two arguments
  .call('first param', 'second param', { from: accounts[3] })
```

**Comment by MartinKral** [comment]
> instance.theFn.call('first param', 'second param'); // call theFn(string,string)
> instance.theFn.call('first param'); // call theFn(string)

How would I call a function overload with the same number of parameters, but different types (string and uint)?

**Comment by gnidan** [comment]
Closing this, as Truffle v4 basically had no support for overloaded functions. This is now resolved in Truffle v5. Please see the v5 release notes about [overloaded functions](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0#user-content-what-s-new-in-truffle-v5-interacting-with-your-contracts-overloaded-solidity-functions). Thanks!
