### ISSUE TITLE
"Could not decode event" - decoding 3rd party contract events

### ISSUE THREAD

**Issue by kaber2** [trufflesuite/truffle#5698]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I'm trying to write test for a contract which internally interacts with various other pre-existing contracts. Both for debugging and for testing these interactions, I would like to decode events emitted by these contracts. However after reading through a lot of documentation, requests of people trying to do the same, some of the code, I am not getting any closer to actually make this work. 

It seems to me this should be a rather simple thing, I have the contracts interfaces available, but I can't seem to figure out how to make truffle use them to decode events and/or associating them with addresses.

## Steps to Reproduce

Deploy contract which makes Uniswap transaction, neither Uniswap- nor Token-events are decoded.

## Expected Behavior

There should be some way to either tell Truffle to use all the interfaces I have for event decoding or at least associate their ABIs with addresses.

## Actual Results

"Could not decode event" for all events of third party contracts.

## Environment

* Operating System: Linux
* Ethereum client: Ganache
* Truffle version (`truffle version`): Truffle v5.6.5 (core: 5.6.5)
* node version (`node --version`): Node v16.14.0
* npm version (`npm --version`): 8.3.1

**Comment by kaber2** [comment]
Thanks for your response. I'll try to put something together tomorrow.

**Comment by fainashalts** [comment]
Hi @kaber2, any progress putting together a production repo? Thanks!

**Comment by lsqproduction** [comment]
Closing for issue maintenance. Please feel free to open a new issue with the reproduction repo.  Thank you.
