### ISSUE TITLE
web3.eth getter functions hang in the console in v4 beta

### ISSUE THREAD

**Issue by albertc44** [trufflesuite/truffle#570]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Console hangs when running any `web3.eth` getter functions such as `web3.eth.accounts`.

## Steps to Reproduce

1) run `truffle develop`
2) in truffle(develop) console run `web3.eth.accounts`

## Expected Behavior

List all the accounts in the development blockchain.

## Actual Results

Terminal hangs on the command.

![screen shot 2017-09-14 at 12 58 31 pm](https://user-images.githubusercontent.com/1314187/30443140-8dac1ad2-994c-11e7-9830-7286e3336c81.png)

## Environment

* Operating System: macOS Sierra 10.12.6
* Truffle version:  v4.0.0-beta
* Ethereum client: The new ganache-core development blockchain that comes with v4
* node version: 5.4.1
* npm version: 8.2.1

**Comment by smoove** [comment]
Can confirm, the process uses 100% CPU. Ctrl + c does nothing, kill <pid> kills the process.

OS: Ubuntu 16.04

**Comment by gnidan** [comment]
This should be fixed and going out in the next beta.
