### ISSUE TITLE
networks section in build artifacts is blank after deploy

### ISSUE THREAD

**Issue by melnikaite** [trufflesuite/truffle#573]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

networks section in build artifacts is blank after deploy

## Steps to Reproduce

`truffle deploy --reset`

## Expected Behavior

json files in build folder should be updated with new addreses

## Actual Results

`"networks": {},`

## Environment

* Operating System: os x sierra
* Truffle version: 4.0.0-beta.0
* Ethereum client: testrpc 4.1.3
* node version: 7.10.1
* npm version: 4.0.5

**Comment by melnikaite** [comment]
Workaround is adding to migration the following code

```
module.exports = (deployer, networks, accounts) => {
    return deployer
        .deploy(FirstContract)
        .deploy(SecondContract)
        .then(() => {
          [
            'FirstContract',
            'SecondContract',
          ].forEach((name) => {
            const artifact = artifacts.require(`${name}.sol`);
            const metaDataFile = `${__dirname}/../build/contracts/${name}.json`;
            const metaData = require(metaDataFile);
            metaData.networks[deployer.network_id] = {};
            metaData.networks[deployer.network_id].address = artifact.address;
            fs.writeFileSync(metaDataFile, JSON.stringify(metaData, null, 4));
          });
        })
```

**Comment by RickyCook** [comment]
I'm having the same issue... Traced it back to `Artifactor.prototype.saveAll`

```javascript
  if (Array.isArray(objects)) {
    var array = objects;
    objects = {};

    array.forEach(function(item) {
      objects[item.contract_name] = item;
    })
  }
```

This is problematic if you have 2 contracts with the same `contract_name`, even if you aren't using them! For example, if you have `zeppelin-solidity` installed via NPM, it has a `Migrations` contract, and you might have a `Migrations` contract as well.

In this case, one of these contracts have `.networks` sections like this:

`zeppelin-solidity/contracts/lifecycle/Migrations.sol`:
```
{ '5777':
   { events: {},
     links: {},
     address: '0x...' } }
```

`./Migrations.sol`:
```
{}
```

When the array is flattened to an object, they both have the name `Migrations`, thus only the second one is ever acted upon.

I'm not sure that this is correct?

**Comment by Artod** [comment]
Same issue... Works only with the @melnikaite 's workaround:

```
const MyToken = artifacts.require('MyToken')
const MyContract = artifacts.require('MyContract')
const fs = require('fs')

module.exports = async (deployer, network, accounts) => {
  await deployer.deploy(MyToken)

  await deployer.deploy(MyContract, MyToken.address)

  const metaDataFile = `${__dirname}/../build/contracts/MyContract.json`
  const metaData = require(metaDataFile)
  metaData.networks[deployer.network_id] = {}
  metaData.networks[deployer.network_id].address = MyContract.address
  fs.writeFileSync(metaDataFile, JSON.stringify(metaData, null, 4))
}
```

**Comment by cgewecke** [comment]
Tracking this at #713, thanks for opening.
