### ISSUE TITLE
Add line numbers to TestRPC / Ganache runtime exceptions

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#574]
Will have to use the underlying debugger tech to do so (and perhaps modularize that out).

**Comment by illuzen** [comment]
+1

**Comment by owocki** [comment]
hey @tcoulter -- i'm on a call with @gnidan trying to figure out whether we want to place a bounty on this.  is this still active?  would you mind commenting to describe what this is a little more?
