### ISSUE TITLE
Encoder doesn't specify any easy way to encode create transactions

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#5749]
## Issue

@truffle/encoder's `ContractEncoder` and `ContractInstanceEncoder` currently provide a means of encoding creates via their `encodeTxNoResolution`, which requires specifying the constructor ABI entry. Since the encoder already has this information, and since the caller very well might not :), there ought to be an easier way!

(Aside: would we also want to provide an easy way to do `CREATE2`?)

## Steps to Reproduce

Look through @truffle/encoder docs.

## Expected Behavior

Find method to make it easy to encode a create transaction.

## Actual Results

Find only `encodeTxNoResolution`, which works, but requires that you pass the ABI around along with the encoder.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.6.8
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by haltman-at** [comment]
> (Aside: would we also want to provide an easy way to do `CREATE2?`)

`CREATE2` isn't something you can do as a transaction; it only exists as an opcode.

**Comment by gnidan** [comment]
> `CREATE2` isn't something you can do as a transaction; it only exists as an opcode.

You can if you do it as a `CREATE` transaction that deploys a contract that invokes `CREATE2` :)

**Comment by haltman-at** [comment]
OK but that is obviously not a concern for the encoder...

**Comment by gnidan** [comment]
I wouldn't say "obviously". Arguably it's not, but I think there's an argument that it could be!

**Comment by haltman-at** [comment]
Released in 5.7.0.
