### ISSUE TITLE
truffle not able to download box using "truffle unbox". 

### ISSUE THREAD

**Issue by iamgauravpant** [trufflesuite/truffle#5751]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

**truffle not able to download box using "truffle unbox".** 
## Steps to Reproduce

I wrote truffle unbox in terminal 

## Expected Behavior

truffle unbox command gives a boilerplate code to work on .

## Actual Results

Error thrown , 
PS C:\Users\Gaurav\Desktop\Access Control> truffle unbox

Starting unbox...
=================

✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: connect ETIMEDOUT 49.44.79.236:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Truffle v5.6.3 (core: 5.6.3)
Node v16.14.2

## Environment

* Operating System: Windows
* Ethereum client: Geth
* Truffle version (`truffle version`): 5.6.3
* node version (`node --version`): 16.14.2
* npm version (`npm --version`): 8.5.0

**Comment by eggplantzzz** [comment]
Hey @iamgauravpant, looks like you might have some issue with your internet connection. The error seems to indicate that there was some kind of timeout error, does this consistently happen? Have you tried a different internet connection? Is there something odd about your network setup?

**Comment by iamgauravpant** [comment]
@eggplantzzz I am new to solidity , therefore I mainly code in Remix but I was told by my senior to start using VS Code for writing smart contracts . I set up Truffle and Ganache previous month only . Then "truffle unbox" used to work just fine . But when I tried today I got this error multiple times . I checked if everything is installed but I am still getting this error .  How can it be network error when I am able to play videos at 1440p smoothly ?

**Comment by iamgauravpant** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/64788558/205347224-ca1ac6ec-bd3e-44d8-b944-24b025185b0d.png)

**Comment by eggplantzzz** [comment]
Well it may not be simply an issue related to connection speed. Maybe something is up with your network configuration that would mess with the connection to GitHub (which is where the standard Truffle Boxes live). Have you tried using a different internet connection on another network?

**Comment by iamgauravpant** [comment]
Hi @eggplantzzz . I don't know how but this got resolved miraculously . 
Both "truffle unbox" and "truffe init" are working now .
![Screenshot (112)](https://user-images.githubusercontent.com/64788558/206123698-68b1bc4a-ca5d-42b5-ab9b-f243affd5bca.png)

**Comment by ravikumarp278** [comment]
Hi Gaurav,
I am also facing same issue , could you please provide steps you followed to resolve this issue
Starting unbox...
=================

✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: connect ETIMEDOUT 49.44.79.236:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Truffle v5.6.9 (core: 5.6.9)
Node v16.17.0

**Comment by Ashokanandhu** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/119148713/208297009-d426265e-74ff-4bf0-aff4-a35c177d7630.png)
I am also facing the same issue

**Comment by Ashokanandhu** [comment]
> Hi @eggplantzzz . I don't know how but this got resolved miraculously . Both "truffle unbox" and "truffe init" are working now . ![Screenshot (112)](https://user-images.githubusercontent.com/64788558/206123698-68b1bc4a-ca5d-42b5-ab9b-f243affd5bca.png)

how you solved this buddy can you help me

**Comment by iamgauravpant** [comment]
Hi @ravikumarp278 , @Ashokanandhu my issue got resolved on its own . Looking at the error it feels that it is a network error but I had fast network connection . Only maintainers of this project can tell what went wrong .

**Comment by iamgauravpant** [comment]
In  the meanwhile you both can initialize your project with truffle init command . 
First run truffle --version in terminal to check if everything is installed properly .

**Comment by modelomaker812** [comment]
same thing on my box, here is my attempt with versions of node,npm, and truffle as requested.. 


` ╰─λ truffle unbox trufflesuite/rsk-plant-box
Downloading...
Error: Truffle Box at URL https://github.com/trufflesuite/rsk-plant-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/home/hacker/.nvm/versions/node/v19.9.0/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/home/hacker/.nvm/versions/node/v19.9.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/hacker/.nvm/versions/node/v19.9.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/hacker/.nvm/versions/node/v19.9.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

 ╭─hacker@devbox in ~/Desktop/my-app/new as 🧙 took 1s
[🔴] × node -v
v19.9.0

 ╭─hacker@devbox in ~/Desktop/my-app/new as 🧙 took 8ms
 ╰─λ npm -v
9.6.3

 ╭─hacker@devbox in ~/Desktop/my-app/new as 🧙 took 250ms
 ╰─λ truffle --version
Truffle v4.1.15 - a development framework for Ethereum
`

**Comment by rahulraj22** [comment]
I don't know why for the first time running ```truffle init``` showed the same error as above. However, after second try it worked fine for me.
