### ISSUE TITLE
Truffle unable to deploy to polygon mumbai

### ISSUE THREAD

**Issue by iamgauravpant** [trufflesuite/truffle#5762]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

****truffle deploy --network matic is not able to deploy contracts .****
## Expected Behavior

truffle deploy should deploy my contracts to polygon mumbai .
## Actual Results

I've attached Screenshots . 
## Environment

* Operating System: Windows 10
* Ethereum client: Geth
* Truffle version (`truffle version`): v5.6.3 (core: 5.6.3)
* node version (`node --version`): v16.14.2
* npm version (`npm --version`): 8.5.0
![Screenshot (110)](https://user-images.githubusercontent.com/64788558/206120775-d71c8530-93d4-4c1d-9a87-85d56ccf4289.png)
![Screenshot (111)](https://user-images.githubusercontent.com/64788558/206120801-a36fe6ac-ab56-441d-a2ec-906e73fb808d.png)

**Comment by iamgauravpant** [comment]
removed unnecessary screenshot

**Comment by fainashalts** [comment]
Hi @iamgauravpant, thanks for opening this issue! Periodically we do see this endpoint have trouble when traffic is high. You may wish to try again. But you can also try with the Infura endpoint: 
```https://polygon-mainnet.infura.io/v3/" + infuraProjectId```

Please let me know if that helps!

**Comment by iamgauravpant** [comment]
Hi @fainashalts , the endpoint you provided works . Thank You !

**Comment by lsqproduction** [comment]
Hi @iamgauravpant. Glad to know that helped. 
Closing this issue now for issue maintenance.
