### ISSUE TITLE
Error with incorrect nonce

### ISSUE THREAD

**Issue by Leocete** [trufflesuite/truffle#5779]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Hi guys! 
I'm creating a decentralized exchange as a part of my Solidity course and am stuck because of the following error:

> **Error: Returned error: VM Exception while processing transaction: the tx doesn't have the correct nonce. account has nonce of: 28 tx has nonce of: 27 (vm hf=london -> block -> tx) -- Reason given: Custom error (could not decode)**

It appears on this part of the code:
```js
await token.approve(dex.address, amount, {
      from: trader,
    });
```
When I try to run `truffle migrate --reset` with the following migration:

```js
const Dai = artifacts.require('mocks/Dai.sol');
const Bat = artifacts.require('mocks/Bat.sol');
const Rep = artifacts.require('mocks/Rep.sol');
const Zrx = artifacts.require('mocks/Zrx.sol');
const Dex = artifacts.require('Dex.sol');

const [DAI, BAT, REP, ZRX] = ['DAI', 'BAT', 'REP', 'ZRX'].map((ticker) =>
  web3.utils.fromAscii(ticker)
);

const contractsList = [Dai, Bat, Rep, Zrx, Dex];

module.exports = async function (deployer, network, accounts) {
  const [trader1, trader2, trader3, trader4, _] = accounts;

  // Deploy all contracts
  await Promise.all(contractsList.map((contract) => deployer.deploy(contract)));

  // Сreating and getting instances of our contracts
  const [dai, bat, rep, zrx, dex] = await Promise.all(
    contractsList.map((contract) => contract.deployed())
  );

  // Add tokens to the exchange
  await Promise.all([
    dex.addToken(DAI, dai.address),
    dex.addToken(BAT, bat.address),
    dex.addToken(REP, rep.address),
    dex.addToken(ZRX, zrx.address),
  ]);

  const amount = web3.utils.toWei('1000');
  const seedTokenBalance = async (token, trader) => {
    await token.faucet(trader, amount);
    await token.approve(dex.address, amount, {
      from: trader,
    });
    await dex.deposit(amount, web3.utils.fromAscii(token.name()), {
      from: trader,
    });
  };

  await Promise.all(
    [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader1))
  );
  await Promise.all(
    [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader2))
  );
  await Promise.all(
    [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader3))
  );
  await Promise.all(
    [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader4))
  );
};
```

I am trying to add several mocked tokens to the exchange users, here is how my mocked token looks like:

```solidity
//SPDX-License-Identifier: MIT

pragma solidity 0.8.17;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Bat is ERC20 {
    constructor() ERC20("Brave browser token", "BAT") {}

    function faucet(address to, uint256 amount) external {
        _mint(to, amount);
    }
}
```

Does anyone have an idea how I could fix this error? I've spent 2 days searching for a solution - no success.
I will appreciate any help very much :pray:

**This is my repo with the code:**
https://github.com/Leocete/dex

## Steps to Reproduce

1. Download a repository
2. Run `npm install`
3. Run `truffle develop`
4. In a truffle console, execute `migrate --reset` command

## Expected Behavior

Migration run successfully

## Actual Results

> **Error: Returned error: VM Exception while processing transaction: the tx doesn't have the correct nonce. account has nonce of: 28 tx has nonce of: 27 (vm hf=london -> block -> tx) -- Reason given: Custom error (could not decode)**

## Environment

* Operating System: **Mac OS 12.0.1**
* Ethereum client: local
* Truffle version (`truffle version`): 5.6.4
* node version (`node --version`): 14.17.0
* npm version (`npm --version`): 8.19.3

**Comment by cds-amal** [comment]
Hrm, if you're using MetaMask, you can try resetting your account to clear out your transaction history under Settings/Advanced/Reset.

**Comment by Leocete** [comment]
> Hrm, if you're using MetaMask, you can try resetting your account to clear out your transaction history under Settings/Advanced/Reset.

I'm not using Metamask, I run the migration locally on the local Truffle network

**Comment by Leocete** [comment]
I found a reason of this error - it was cause by this part of a code: 

```js
await Promise.all( [dai, bat, rep, zrx].map((token) => seedTokenBalance(token, trader1)) );
```
After I changed it to a for-loop, everything worked:

```
for (const token of [dai, bat, rep, zrx]) { 
  await seedTokenBalance(token, trader1); await seedTokenBalance(token, trader2); 
  await seedTokenBalance(token, trader3); await seedTokenBalance(token, trader4); 
}
```

Probably that was because of Promise.all - it tries to execute all promises at a same time, look like first it executed transaction with nonce 15, and later tried to execute transaction with nonce 14
