### ISSUE TITLE
Run tests with `--debug` flag fails

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/truffle#5783]
- [x] I've discussed with @gnidan before filing this issue. https://github.com/trufflesuite/truffle/pull/5782 might solve this issue.

---------------------------

## Issue

I’m trying to start the debugger using `truffle test --debug` as described in [1]. I have created a test case that calls `debug`, run it with `truffle test --debug` but I get

```sh
  1) Contract: HelloBlockchain
       should succeed debugging:
     TypeError: Cannot read properties of undefined (reading 'currentRunnable')
      at /opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/prepareConfigAndRunTests.js:23:1
      at Context.<anonymous> (test/TestHelloBlockchain.js:20:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Steps to Reproduce

Create a new box

```sh
truffle unbox vscode-starter-box
```

and add the following test to `test/TestHelloBlockchain.js`, notice the `debug` magic function that allows you to debug tests

```js
  it("should succeed debugging", async function () {
    const helloBlockchainInstance = await HelloBlockchain.deployed();
    await debug(helloBlockchainInstance.SendRequest("Hello Blockchain", { from: accounts[0] }));
  });
```

then run it with

```sh
ganache # in another terminal
truffle test --debug
```

## Expected Behavior

> Truffle will interrupt the normal test flow and start the debugger[1]

## Environment

* Operating System: macOS Ventura `13.0.1`
* Ethereum client: `Ganache v7.5.0`
* Truffle version (`truffle version`): `Truffle v5.6.6 (core: 5.6.6)`
* node version (`node --version`): `Node v16.18.0`
* npm version (`npm --version`): `8.19.2`

----

[1] https://trufflesuite.com/docs/truffle/how-to/debug-test/use-the-truffle-debugger/#in-test-debugging

**Comment by eggplantzzz** [comment]
fixed in v5.7.0
