### ISSUE TITLE
ettimedout 

### ISSUE THREAD

**Issue by Ashokanandhu** [trufflesuite/truffle#5799]
![Screenshot (6)](https://user-images.githubusercontent.com/119148713/208297690-c644f09d-97d5-4a8a-afa8-f0e854e551cc.png)
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by Ashokanandhu** [comment]
√ Preparing to download box
× Downloading
Unbox failed!
Error: connect ETIMEDOUT 49.44.79.236:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
Truffle v5.7.0 (core: 5.7.0)
Node v16.17.0

i am facin this issue in gitbash

**Comment by lsqproduction** [comment]
Hi @Ashokanandhu. thank you for raising this. 
Can you help to run ` $ DEBUG=unbox truffle unbox metacoin` and share the output with us?

**Comment by Ashokanandhu** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/119148713/209197024-cb5c9b23-afca-4aa5-a2f3-06d9865f14fb.png)

**Comment by eggplantzzz** [comment]
You may want to try this on a different connection. It looks like some kind of TCP error, I cannot duplicate this on my machine. Is there anything odd about your metwork connection?

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.

**Comment by hegdenischay** [comment]
Just wanted to chime in because I saw this issue while google searching for [that](49.44.79.236) IP.

This is the Blackhole IP for [Reliance Jio](https://en.wikipedia.org/wiki/Jio), which means that raw.githubusercontent.com gets redirected to it, since raw.githubusercontent.com is blocked in India for some godforsaken reason (while GitHub itself isn't).
