### ISSUE TITLE
Truffle doesn't deploy some smart contracts to private Ethereum network!

### ISSUE THREAD

**Issue by Alireza1994x** [trufflesuite/truffle#5803]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

There are some contracts that we should deploy to a PoA based private Ethereum by Truffle. Some of them are deployed easily but some others cannot be deployed. Truffle message is "Contract registering failed" but it doesn't explain the issue clearly. I put truffle config and the contract migration code here but I can't share the contract code, Because the project is private.

truffle-config.js:

```
const Web3=require("web3");

<Network name>:{
      provider:function(){
        return new Web3.providers.WebsocketProvider("ws://<ip>:<port>");
      },
      network_id:"1234",
      gas: 7000000,
      gasPrice:3375000000
     }
```

migration.js:

```
const MyContract = artifacts.require("./<contract>.sol");
const Web3=require("web3");
const web3=new Web3(new Web3.providers.WebsocketProvider("ws://192.168.10.27:8551"));
      web3.eth.personal.unlockAccount(<sender>,...,...);

module.exports = function(deployer,network,accounts) {
  let A=<value>;
  deployer.deploy(MyContract, A,{from:<sender>});
};
```

## Expected Behavior

I expect Truffle deploys all my contracts not just some of them.

## Actual Results

Some contracts are deployed easily by Truffle but for some others this error throws:

```
Error:  *** Deployment Failed ***

    <contract> hit a require or revert statement with the following reason given:
       * Contract registering failed!
    
        at C:\...\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:330:1
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
## Environment

* Operating System: Windows Server 2019
* Ethereum client: Geth v1.10.23
* Truffle version (`v5.5.31 (core: 5.5.31)`):
* node version (`v16.17.1`):
* npm version (`8.19.2`):

**Comment by haltman-at** [comment]
Notice that this error message is coming from the contracts themselves, not from Truffle -- the contract has hit a revert or require statement that caused the deployment to fail.  It's not clear that this is a Truffle issue; it would appear offhand to be an issue with your contracts, or perhaps with how you've deployed them.

Similarly, it's not possible for Truffle to more clearly explain the error here, because the error is originating from your contracts and not from Truffle.

**Comment by Alireza1994x** [comment]
@haltman-at 
Yes, you're right. This was because of the contract source code and I fixed it.

**Comment by haltman-at** [comment]
OK, great!
