### ISSUE TITLE
How to define a contract in Truffle that deployed by another Ethereum node?

### ISSUE THREAD

**Issue by Alireza1994x** [trufflesuite/truffle#5804]
## Issue

I set Truffle to my private network. Now, I need to interact to a contract (C1) that deployed by another node of this network and I need to do that by Truffle. As I understood, I should define C1 to Truffle so that Truffle knows C1 deployed before. How should I do that? What do I need for that?

## Expected Behavior

When I try this command on Truffle console:

`C1.deployed().then(fucntion(ins){c1=ins})`

This error doesn't be throwed:

`Error: C1 has not been deployed to detected network (network/artifact mismatch)`

## Actual Results

The above error throwed and I can't interact with C1.

## Environment

* Operating System: Windows Server 2019
* Ethereum client: Geth v1.10.23
* Truffle version (`v5.7.0`):
* node version (`v16.17.1`):
* npm version (`v8.19.2`):

**Comment by cds-amal** [comment]
You can use [your Contract abstraction's `at` method](https://trufflesuite.com/docs/truffle/reference/contract-abstractions/#mycontractataddress) to connect to an already deployed address.
```javascript
knownContract = await C1.at("0xaddressOfDeployedContract")
```

**Comment by Alireza1994x** [comment]
@cds-amal 
I tried these commands on Truffle console:

`truffle(PrivEth)> const c1=await artifacts.require("C1")`

`truffle(PrivEth)> const C1=await c1.at('0x42C564EF81c9DF9338a62c13056FFEc84285a3DC')`

But this error throwed:

```
Uncaught:
Error: Cannot create instance of C1; no code at address 0x42C564EF81c9DF9338a62c13056FFEc84285a3DC
```

I don't know am I trying the commands by a correct way or not? Please provide the correct way, Thanks.

This is the Truffle config:

```
const Web3=require("web3");
module.exports = {
      networks: {
          development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*",
     },
     develop:{
      port:8545
     },
     PrivEth:{
      provider:function(){
        return new Web3.providers.WebsocketProvider("ws://<ip>:8551");
      },
      network_id:"1111"
     }
 },
compilers: {
    solc: {
      version: "0.8.0",
    }
  }
```

**Comment by Alireza1994x** [comment]
I resolved this issue here:
https://github.com/orgs/trufflesuite/discussions/5808#discussioncomment-4496733
