### ISSUE TITLE
Constructor Parametr from user.!!

### ISSUE THREAD

**Issue by FaizulMustafiz** [trufflesuite/truffle#581]
can it be done ???
var Test= artifacts.require('./Test.sol');
var testType= document.getElementById('testType');
var type= parseInt(testType);

module.exports = function (deployer) {
deployer.deploy(Test, type)
}

i am having trouble with this ... when i am trying to migrate its saying that document is not defined- [ ] I've asked for help in the  [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Truffle version:
* Ethereum client:
* node version:
* npm version:

**Comment by tcoulter** [comment]
Hi there. 

It looks like you're trying to write browser-based JavaScript in Node.js. Node.js is "server side" JavaScript, which means it doesn't run in the browser; `document.getElementById()` is provided to code that solely runs in the browser.

If you'd like to write browser-based automated tests, consider writing [headless automated tests with PhantomJS](http://phantomjs.org/headless-testing.html).

Cheers!
