### ISSUE TITLE
Can't verify contracts on Etherscan using Truffle

### ISSUE THREAD

**Issue by metadimensions** [trufflesuite/truffle#5811]
Hello,

I can’t verify the Smart contracts on the Etherscan mainnet.  First I tried verifying directly on Etherscan but got import errors then I flattened the contract but it says the Bytecode was not matching.

<img width="1440" alt="Screenshot 2022-12-30 at 2 53 17 PM" src="https://user-images.githubusercontent.com/17061316/210076116-76d02c92-fc0c-45b7-802d-428f698f3e27.png">

Using Truffle the error says fail - **unable to verify failed to verify 1 contract(s):**

<img width="749" alt="Screenshot 2022-12-30 at 2 43 38 PM" src="https://user-images.githubusercontent.com/17061316/210076166-8dc799b9-bec4-4836-a2b7-00620b6b792f.png">

**Comment by eggplantzzz** [comment]
hey @metadimensions, thanks for reporting this! I presume you are using truffle-plugin-verify which is actually maintained by our friend @rkalis. maybe you could consider posting this in [his repo](https://github.com/rkalis/truffle-plugin-verify) as it seems like it might be related to the plugin and not Truffle generally.  let us know if you find anything out about this issue!

**Comment by metadimensions** [comment]
Hello @eggplantzzz  thanks for the reply! will check this out
