### ISSUE TITLE
Documentaion side is dead

### ISSUE THREAD

**Issue by wa1one** [trufflesuite/truffle#5822]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.
404
---------------------------

## Issue

404

## Steps to Reproduce

Open: 
https://trufflesuite.com/docs/truffle/how-to/install/

## Expected Behavior
Open site

What you expected to happen.
Seeing opened site

## Actual Results
404

## Environment
Macos
* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by tibi77** [comment]
Works for me as well. Could you maybe try using a VPN?

**Comment by eggplantzzz** [comment]
Closing this as the page seems to be fine. If you think I'm in error here, please comment and I'll do another investigation.
