### ISSUE TITLE
I`m try to deploy me truffle in gcloud as App Engine

### ISSUE THREAD

**Issue by tonymanpro** [trufflesuite/truffle#583]
I`m try to deploy me truffle in gcloud as App Engine, but  how can i use the command  "testrpc" and "truffle migrate"

* Operating System:  Ubunto 16.04
* Truffle version: 3.0
* Ethereum client: testrpc
* node version: 7.x
* npm version:  3.11

**Comment by cgewecke** [comment]
@tonymanpro Thanks for opening, I'm closing this for housekeeping. We're a full version ahead of 3.0 now, and your issue relates to running in a cloud - we routinely run on CI services like Travis and Circle without issue - not sure what's special about App Engine.
