### ISSUE TITLE
Truffle REPL does not respect `""` in a string with spaces

### ISSUE THREAD

**Issue by sukanyaparashar** [trufflesuite/truffle#5838]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

While testing `truffle call` command in `develop` and `console`, I ran into this issue. For example, when a contract function is called with `call <contract_name> <function_name> <string_argument>` which returns the string with spaces, it throws an error that function argument is invalid. The parsing of the string within `""` in the REPL interferes with the spaces and does not treat the whole string as one.

**Comment by haltman-at** [comment]
Could you give an example here?

**Comment by sukanyaparashar** [comment]
For example, when I run `call <contract_name> <function_name> <args>` in the REPL (`develop` or `console`) that takes a string with two words separated by a space, as an argument, the arguments array shows two strings instead of one like the screenshot below-
<img width="469" alt="functionargs" src="https://user-images.githubusercontent.com/25079663/212981120-741fd908-5e20-42b2-948a-4e6834e11ec9.png">

On the other hand, the same call outside of REPL works fine like the screenshot below-
<img width="785" alt="functionargs" src="https://user-images.githubusercontent.com/25079663/212981321-9189fa8f-f383-4987-beea-9da4815644bf.png">

**Comment by haltman-at** [comment]
Oh, yikes!  That's definitely a problem for this...

**Comment by haltman-at** [comment]
OK, I think we can likely handle this with the [shell-quote](https://www.npmjs.com/package/shell-quote) library.

**Comment by gnidan** [comment]
This is now fixed in [Truffle v5.7.6](https://github.com/trufflesuite/truffle/releases/tag/v5.7.6). Thanks all!
