### ISSUE TITLE
No option to prevent Truffle from running Mocha with the --exit argument.

### ISSUE THREAD

**Issue by ajeetd** [trufflesuite/truffle#5839]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

Yes ticket #986905

---------------------------

## Issue

Truffle runs Mocha with the --exit argument appended (Mocha argument reference here: `https://mochajs.org/)`. You can find it in the code base wherever Mocha is called. This changes the behavior of Mocha to not wait for async operations in reporters before exiting. We need an option in Truffle to override this. No Mocha reporters that perform async operations (usually at the end) will function otherwise. Since Truffle (doesn't appear) to expose a separate reporting interface, this is critical to have an option for.

## Steps to Reproduce

Use a Mocha test reporter that includes an async function operation for the 'end' event. Mocha exits (ends the process) without waiting for the function to complete.

I became aware of this when having issues reporting results to Tesults with Truffle but not Waffle with the Tesults Mocha Reporter
Npm package: `https://www.npmjs.com/package/mocha-tesults-reporter`
Documentation: `https://www.tesults.com/docs/mocha`

## Expected Behavior

This is not a bug, it seems to be by design because Truffle uses the --exit command with Mocha. The issue is we need an option for Truffle not to do that (i.e. omit the --exit command or add the --no-exit (which is default for Mocha)).

## Actual Results

See expected behavior above, this is not a bug so the expected/actual template here does not apply.

## Environment

* Operating System:  Tested with Mac OS
* Ethereum client: N/A
* Truffle version (`truffle version`): Tested with 5.7.2
* node version (`node --version`):  Tested with 16.3.0
* npm version (`npm --version`): Tested with 8.1.0

**Comment by eggplantzzz** [comment]
Hey @ajeetd, thanks for the report! Truffle does use the `--exit` flag with Mocha but I think this is only for Truffle's test suite. I don't think Truffle uses this option when `truffle test` is run. If you are having issues, could you link us to a test repo so that we can try and reproduce it?

**Comment by ajeetd** [comment]
@eggplantzzz I believe it is using the --exit flag even when running truffle test.I discovered this when trying to determine whether the Mocha framework reporter for Tesults would 'just work' with Truffle, I expected it would but discovered it does not due to this flag. Here is a temporary repo I've setup to demonstrate the issue: https://github.com/ajeetd/temporary-truffle-test

Run `npm install` and then `npm test`

You will find that in the console output, at the end you see 'Tesults results upload... (TEST)' which is output in tesults-reporter.js (the custom mocha reporter) but the Mocha process exits before the callback can complete, we would expect to see console output from lines 228-235 in tesults-reporter.js if the callback were to complete.

The best solution to this would be to offer an option to have a way for Truffle to omit the --exit flag when running.

**Comment by eggplantzzz** [comment]
For `truffle test` Truffle runs mocha programmatically. It creates an instance [here](https://github.com/trufflesuite/truffle/blob/develop/packages/test/src/Test.ts#L200) and invokes the `run` method [here](https://github.com/trufflesuite/truffle/blob/develop/packages/test/src/Test.ts#L189-L192). Unless it is some kind of default behavior for mocha I don't see how it would be run as you are describing.

I have to say that I'm not familiar with tesults and don't really know how that is supposed to work with mocha.

**Comment by ajeetd** [comment]
I can't follow exactly where you're running the mocha command itself but a search for the `--exit` arg shows it's being passed in a few places in the codebase. Tesults is somewhat irrelevant here, any callback/async would not be waited for, it was just an example.

**Comment by eggplantzzz** [comment]
Yes, but we only pass the `--exit` flag in Truffle's test suite. We do not pass it when we run the mocha test runner. As I mentioned, [this is the code in Truffle](https://github.com/trufflesuite/truffle/blob/develop/packages/test/src/Test.ts#L189-L192) that is responsible for running mocha. You can see that no `exit` option is passed.

**Comment by kevinbluer** [comment]
Hey guys, going to close this one for issue maintenance. Feel free to re-open / create a new issue if you want to dig bag into this.
