### ISSUE TITLE
Upgrade web3 to v0.20.2 or higher

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle#584]
See https://github.com/ethereum/web3.js/issues/1043#issuecomment-330827077

**Comment by tcoulter** [comment]
This is done (doesn't actually require any code changes). We just need to release a new version of Truffle; `npm`'s semver will do the rest.

**Comment by makoto** [comment]
@tcoulter Hello. Any plan on when this gets released? I have a branch depending on this change so wondering if I should revert if it won't be released for a while.

**Comment by tcoulter** [comment]
Hey there. It's alright released! :) Looks like this ticket didn't get taken care of. Download the latest Truffle and you should have a fix in place.

Cheers!

**Comment by makoto** [comment]
I see. I was using 4.0.0 beta but had to downgrade to main. Looks like it's not back ported yet https://github.com/trufflesuite/truffle/blob/v4.0.0-beta.0/package.json#L25

**Comment by k26dr** [comment]
I still occasionally get this error and can solve it every time by deleting the `build/` folder
