### ISSUE TITLE
const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)

### ISSUE THREAD

**Issue by Dania001** [trufflesuite/truffle#5848]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
whenever im trying to migrate using truffle migrate --network goerli.............im getting this error

here is my truffle.config.js file

const HDWalletProvider = require('@truffle/hdwallet-provider');
const MNEMONIC =  "panther soccer common jelly prefer cricket noise unfold cricket enemy alien dawn";
const projectId = "29a9d50a47b24948959bf0463f0c5a64";

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
       goerli: {

       provider: () => new HDWalletProvider(MNEMONIC, `https://goerli.infura.io/v3/${projectId}`),
       network_id: 5,       // Goerli's id
       chain_id:5,
       gas: 5500000,
       confirmations: 2,    // # of confirmations to wait between deployments. (default: 0)
       timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
       skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
     },

//    development: {
//      host: "127.0.0.1",
//      port: 7545,
//      network_id: "*" // Match any network id
//    },

    develop: {
      port: 8545
    }
  },
  compilers:{
  solc:{
  version:'0.5.16'
  },
  },

};

* Operating System: 
Truffle v5.7.1 (core: 5.7.1)
Node v16.16.0

please can someone help me

**Comment by cliffoo** [comment]
@Dania001 Your mnemonic is compromised, meaning you shouldn't fund any account derived from it, especially on mainnet. Please get a new mnemonic and be sure to not share it publicly.

**Comment by eggplantzzz** [comment]
Usually that kind of error means there is some problem with your internet connection or the endpoint you are using. Could you try this on a different network connection and see if you get the same results?

**Comment by Dania001** [comment]
hey i tried migrating this on a differnet network but i am getting the same error

**Comment by Dania001** [comment]
> @Dania001 Your mnemonic is compromised, meaning you shouldn't fund any account derived from it, especially on mainnet. Please get a new mnemonic and be sure to not share it publicly.

**Comment by eggplantzzz** [comment]
What happens if you try migrating on a different test net? Do you still get the problem? If you still do, I could try and reproduce your error if you can link me to a GitHub project to use to try and repro this. Let me know!
