### ISSUE TITLE
Improve error message for syntax errors

### ISSUE THREAD

**Issue by smoove** [trufflesuite/truffle#586]
When keywords are misspelled in contracts, the error output is not very helpful for new users, i saw two cases of this being a problem in the truffle gitter today.

Example:

Someone misspelled `pragma` as `pramga` and the resulting error message reads:

`Error parsing /path/Contract.sol: Expected "contract", "import", "interface", "library", "pragma", "using", comment, end of input, end of line, or whitespace but "p" found`

The message would be a lot more helpful if it printed the whole word.

**Comment by cgewecke** [comment]
@smoove With `4.0.6`, Truffle's using solc to parse all solidity files. These mysterious messages should no longer appear :) 

Thanks for opening.
