### ISSUE TITLE
DX Improvement: Default Testing Env

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [trufflesuite/truffle#5897]
## Issue

When starting a new project, not touching the config, and running `truffle test`; I would expect Truffle to spin up a `truffle develop` instance without any networks supplied. Instead, it throws.

We could improve new developer DX by adding this functionality.

## Steps to Reproduce

1. `truffle init <any_name>`
2. Add a smart contract and corresponding test
3. `truffle test` throws, noting the contract hasn't been deployed to the given network

## Expected Behavior

Truffle will automatically use a `truffle develop` instance to run the tests.

## Actual Results

`truffle test` throws, noting the contract hasn't been deployed to the given network

## Environment

* Operating System: macOS Ventura 13.1
* Ethereum client: N/A
* Truffle version (`truffle version`): 5.7.5
* node version (`node --version`): 18.12.0
* npm version (`npm --version`): 9.1.1

**Comment by cds-amal** [comment]
Did you also create a migration script?

**Comment by OnlyOneJMJQ** [comment]
![image](https://user-images.githubusercontent.com/3990373/219460060-3531bd7e-ea0b-4312-a2b7-e2019da72590.png)
This is what I get for working on vacation.

**Comment by cds-amal** [comment]
I think this could be an error better. What do you think?
