### ISSUE TITLE
How to get transaction hash and block number in migration function

### ISSUE THREAD

**Issue by gzliudan** [trufflesuite/truffle#5917]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/1002405) before filing this issue.

---------------------------

## Issue

When using migration script to deploy contract, the console reports information about the deployed contract, such as:

```text
transaction hash:    0xdf01fdc83e3656e2ab8c72e58fa08e1557aeb16d82539c4845440071e77551dd
contract address:    0x5AD34831c0014151E271d67375d2Ee4B6A295F88
block number:        45553132
```

How to get hash and block number about deploy transaction in migration function:

```js
module.exports = async (deployer, network, addresses) => {
    // ......
}
```

**Comment by eggplantzzz** [comment]
Hey @gzliudan you might find some of these docs useful https://trufflesuite.com/docs/truffle/reference/contract-abstractions/

So there are a couple of ways you can do this. One is by using `then` syntax in your migrations. So something like
```
deployer.deploy(MyContract)
  .then(instance => instance.address);
```

Another way that avoids `then`s is doing something like the following:
```
await deployer.deploy(MyContract);
const instance = await MyContract.deployed();
console.log("the address for the newly deployed contract is ", instance.address);
```

I hope that helps!

**Comment by gzliudan** [comment]
How to get transaction hash and block number ?  instance  has no such property.

**Comment by gzliudan** [comment]
I got the answer:

```js
module.exports = function(deployer) {
  const MyContract = artifacts.require("MyContract");
  await deployer.deploy(MyContract);
  const instance = await MyContract.deployed();
  contractAddress = instance.address;
  const txHash = MyContract.transactionHash;
  const blockNumber = (await MyContract.web3.eth.getTransaction(hash)).blockNumber;
};
```

Maybe someone has better solution.

**Comment by eggplantzzz** [comment]
Oh, I read your question and answered a different one! Sorry about that! But yes, it seems like you found the answer. I'm glad you did even though I wasn't much help.
