### ISSUE TITLE
Compiling Truffle project using Solang compiler 

### ISSUE THREAD

**Issue by joshuacheong** [trufflesuite/truffle#5929]
- [ X ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

As a developer on new blockchain stacks I want to develop the ability to compile solidity for Solana and Substrate (Polkadot, Astar network, and many more). This will help developers like myself reach a much bigger market for my solidity smart contract deployment.

As a result I have to used the [Solang](https://github.com/hyperledger/solang) compiler.

Truffle has made majority of the deployment work across multiple files extremely easy, especially when these files have address inputs that are dependencies upon other files being deployed upon creation.

- Would there be any interest to include Solang compiler instead of Solc for deployment?
- What would be the best way to include Solang?

**Comment by eggplantzzz** [comment]
Hey @joshuacheong! Currently I'm not sure about whether we'll be able to include native Solang support in Truffle, I can't speak for the entire team here but it would definitely have to be discussed. Something that you may find interesting, however, is that Truffle actually has some infrastructure for "custom compiler setup". It requires some manual tweaking but it seems like there may be a chance you'd find it useful. And, you know, I like helping people hack :)

Check out [this section of the Truffle docs on external compilers](https://trufflesuite.com/docs/truffle/reference/configuration/#external-compilers).

**Comment by cds-amal** [comment]
Closing for issue maintenance.
