### ISSUE TITLE
02.24.2023 // 0x17DED751ea73585DB79174b5F4f78F2dfC6011dc Is altering my code when i run the command `sudo truffle migrate --reset --network goerli`

### ISSUE THREAD

**Issue by Jhintao** [trufflesuite/truffle#5932]
Deploying 'BRETH'
   -----------------
   > transaction hash:    0x7d58a169be08112f593bc2873d6b309a4a63721e4e3fe560043b3c0afd2e0a4a
   ✖ Blocks: 2            Seconds: 24
 *** Deployment Failed ***

"BRETH" -- Cannot create instance of BRETH; no code at address 0x17DED751ea73585DB79174b5F4f78F2dfC6011dc.

Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.

Error:  *** Deployment Failed ***

"BRETH" -- Cannot create instance of BRETH; no code at address 0x17DED751ea73585DB79174b5F4f78F2dfC6011dc.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:330:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Truffle v5.7.6 (core: 5.7.6)
Node v18.14.0

**Comment by cliffoo** [comment]
Hey @Jhintao thanks for opening the issue. There isn't enough information here to debug, can you link us your project (stripped of mnemonics) that we can use to try reproducing this? Thanks!

**Comment by cliffoo** [comment]
Also you shouldn't be using `sudo` with Truffle commands. If you're getting permission errors without sudo then please reinstall Truffle with `nvm`. See installation guides [here](https://github.com/orgs/trufflesuite/discussions/categories/installation?discussions_q=nvm+category%3AInstallation)
