### ISSUE TITLE
How to use truffle console to test my faucet deployed on Goerli net?

### ISSUE THREAD

**Issue by zydjohnHotmail** [trufflesuite/truffle#5937]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I can not send tokens (goerli ETH) to another wallet.

## Steps to Reproduce

I followed a tutorial to deploy a faucet smart contract on Goerli net, and I see everything looks OK.
I setup my MetaMask wallet as the source of funds (ETH on Goerli net).
Then I used truffle console to connect with Goerli net, and  try to send some tokens to 
my Coinbase wallet, I can see the transaction hash, it looks OK.
But when I opened my MetaMask wallet, I can't see any transactions.

## Expected Behavior

When I opened my MetaMask wallet, I should see any transactions.

## Actual Results
But when I opened my MetaMask wallet, I can't see any transactions.

```

truffle(goerli)> let send2 = instance.requestTokens('0x19000CC8bda1D3E8E7c6185F8977085ac82beDa4')
undefinedactionHash: '0x0039ed7ac73730755a1a39e2f9cb2826f6a7113f9483ac4f2ec57fae61333d71',
truffle(goerli)> Uncaught:
    type: '0x2',
    at evalmachine.<anonymous>
    at sigintHandlersWrap (node:vm:270:12)
    at Script.runInContext (node:vm:139:14)
    at runScript (C:\Users\John\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:505:1)
    at Console.interpret (C:\Users\John\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:520:1)
    at bound (node:domain:433:15)
    at REPLServer.runBound [as eval] (node:domain:444:12)
    at REPLServer.onLine (node:repl:902:10)
    at REPLServer.emit (node:events:513:28)
    at REPLServer.emit (node:domain:489:12)
    at REPLServer.[_onLine] [as _onLine] (node:internal/readline/interface:422:12)
    at REPLServer.[_line] [as _line] (node:internal/readline/interface:892:18)
    at REPLServer.[_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1270:22)
    at REPLServer.self._ttyWrite (node:repl:997:9)
    at ReadStream.onkeypress (node:internal/readline/interface:270:20)
    at ReadStream.emit (node:events:513:28)
    at ReadStream.emit (node:domain:489:12)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36) {
  name: 'StatusError',
  tx: '0x797c4073d013d303a359de3229534c6c255cb7b027a6cb28bf7c0592c7733ae0',
  receipt: {
    blockHash: '0x0d7ccaac3475b7c81f1f44b21c8562cc331c2b7c61adcd9ff1a5defe42536ae5',
    blockNumber: 8572977,
    contractAddress: null,
    cumulativeGasUsed: 949841,
    effectiveGasPrice: 103377350233,
    from: '0x4257f40a3c6b41605831032be91948cacf9a1861',
    gasUsed: 24263,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0xa70d703ae85875c733cbbf58f6d61a2427805e9f',
    transactionHash: '0x797c4073d013d303a359de3229534c6c255cb7b027a6cb28bf7c0592c7733ae0',
    transactionIndex: 19,
    type: '0x2',
    rawLogs: []
  },
  reason: undefined,
  hijackedStack: ''
}
```

## Environment

* Operating System: Windows 10
* Ethereum client: ?
* Truffle version (`truffle version`): 
* node version (`node --version`):
* npm version (`npm --version`): 

D:\Truffle\FaucetProject>truffle version
Truffle v5.7.8 (core: 5.7.8)
Ganache v7.7.5
Solidity - ^0.8.0 (solc-js)
Node v18.14.2
Web3.js v1.8.2

D:\Truffle\FaucetProject>

**Comment by cliffoo** [comment]
@zydjohnHotmail fyi MetaMask's transaction history won't include any transaction that isn't processed via MetaMask (whether or not they failed).

Just for clarification, is this issue about that? Or is it about the fact that your transaction [failed](https://goerli.etherscan.io/tx/0x0039ed7ac73730755a1a39e2f9cb2826f6a7113f9483ac4f2ec57fae61333d71)?

**Comment by zydjohnHotmail** [comment]
Hello:
This issue is that I don't quite understand the data flow.  
If I use truffle console to transfer some funds, do I still have to use MetaMask to approve and make transaction? 
Or if I can use truffle console to transfer some funds, which the funds are not under the control of MetaMask, then I can use the console to transfer funds without MetaMask?
Please advise,
Thanks,

**Comment by cliffoo** [comment]
So MetaMask is only involved if you use Truffle Dashboard. When you target any network that isn't `dashboard`, Truffle will use that network's provider and mnemonic you provide; if you target the `dashboard` network, it will use MetaMask for all requests (in this case, `eth_sendTransaction` to transfer ether)

**Comment by cds-amal** [comment]
Closing for issue maintenance.
