### ISSUE TITLE
Timeout while migrating

### ISSUE THREAD

**Issue by chuacw** [trufflesuite/truffle#594]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Timing out when doing a "truffle migrate --network ropsten"

## Steps to Reproduce

1. Add the ropsten network to truffle.js. Do this by copying an existing network, such as development, then modify the network_id to be 3 instead of *.
2. Run the command: truffle migrate --network ropsten

## Expected Behavior

Successful completion without errors.

## Actual Results

D:\Development\Ethereum2>truffle.cmd migrate --network ropsten
Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\contracts\Migrations.sol...
Writing artifacts to .\build\contracts

Using network 'ropsten'.

Running migration: 2_deploy_contracts.js
  Deploying ConvertLib...
  ... 0xbc491b31a5f761723a64e9ef3b4f0fb78ab972c279e09fcc3992d09a28008469
  ConvertLib: 0x1299ba1c272d58654c2809eac8e030d3842bd53e
  Linking ConvertLib to MetaCoin
  Deploying MetaCoin...
  ... 0x36b2ccdb59e5a98b9979ff9dc36ac9ef4f050265d33d29aa3411a02bceec1956
  MetaCoin: 0x10eb81c0f4d70a521baaa29d131c6de29aecb636
Saving successful migration to network...
  ... 0x638c5d1c446cc9913c722e7fe6c1a6f6f6bb98bfdb9bba8ab198b0f650a85027
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Transaction 0x638c5d1c446cc9913c722e7fe6c1a6f6f6bb98bfdb9bba8ab198b0f650a85027 wasn't processed in 240 seconds!
    at Object.callback (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:326547:35)
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:40072:25
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:359610:9
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:86262:11
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:322668:9
    at XMLHttpRequest.request.onreadystatechange (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:324093:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71245:18)
    at XMLHttpRequest._setReadyState (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71535:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71690:12)
    at IncomingMessage.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71650:24)
## Environment

* Operating System:  Windows 2008 R2
* Truffle version: v4.0.0-beta.0
* Ethereum client: 1.7.0-stable-6c6c7b2a
* node version: v6.11.2
* npm version: 3.10.10

**Comment by chuacw** [comment]
Is there a way to increase the number of blocks to wait?
I deployed a contract around 10:25, and it only showed up at 11:24. Nearly 1 hour later!

**Comment by DeRain** [comment]
Same issue here - can't deploy to the live.

**Comment by JackPickering** [comment]
Has this issue been solved by anyone?
Does increasing gasPrice help with this?

**Comment by cgewecke** [comment]
@chuacw @DeRain @JackPickering Truffle had a bug that accidentally limited the wait time to 4 minutes. It's fixed in the latest release. 

Unfortunately, while looking into this issue, it's been discovered that that `web3` has it's own hardcoded wait limit: 50 blocks. (Code [here](https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L105-L115)). 

For the moment anyway, to be mined via `web3` (which Truffle uses), you'll have to set your deployment gas price high enough to get picked up within 50 blocks.

Closing, thanks for reporting.
