### ISSUE TITLE
Error: invalid sender using truffle migrate with geth rpc

### ISSUE THREAD

**Issue by phroiland** [trufflesuite/truffle#595]
Cannot get truffle migrate to work with geth rpc:

$ geth --datadir ~/simplewallet/ --rpc --rpcport 8545 --rpcaddr "localhost" --rpcapi "eth,net,web3"

$ geth --rpc attach ~/simplewallet/geth.ipc
 > personal.newAccount()
 > personal.unlockAccount(eth.accounts[0])
 > miner.start()

$ truffle migrate
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: invalid sender
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:224765:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66971:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
    at emitNone (events.js:110:20)
```

Contract should deploy and I should be able to interact with it. It works just fine running:
$ testrpc
$ truffle migrate
$ npm run dev

Ubuntu 16.04
Truffle v3.4.9 (core: 3.4.8)
Solidity v0.4.15 (solc-js)
Geth Version: 1.7.0-stable
Node v8.5.0
NPM 5.4.2

**Comment by tarassh** [comment]
Have exactly the same problem
Truffle v3.4.11 (core: 3.4.11)

**Comment by tarassh** [comment]
in order to fix it, you should define in genesis file your chainid and this chain id should be equal to your network id 

`"config": {
        "chainId": 1010,
        "homesteadBlock": 1,
        "eip155Block": 0,
        "eip158Block": 0
    },`

`$ geth --datadir ~/simplewallet/ --rpc --rpcport 8545 --rpcaddr "localhost" --rpcapi "eth,net,web3" --networkid 1010`

**Comment by andy-mcewan-aventus-io** [comment]
I have the same problem. Matching chainid and network id doesn't work for me.

**Comment by juanfer** [comment]
Wow!, fixed it for me. Have been dealing with this problem for 2 days, and finally starting local node using the same networkid as genesis chainId param, made it work. Which is the reason? Also have to say that seems to happen since a system update, but can't precise which one (made several updates in the last weeks)
