### ISSUE TITLE
Error: Cannot find module 'C:\...\node_modules\truffle\build\cli.bundled.js' after installation done!

### ISSUE THREAD

**Issue by AlirezaEthDev** [trufflesuite/truffle#5965]
## Issue

I installed the latest version of truffle by `npm install -g truffle`. The installation done and this is the last few lines of the result on PowerShell:

```
npm ERR! code 1
npm ERR! path C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\node_modules\bufferutil
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! The process cannot access the file because it is being used by another process.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Local\npm-cache\_logs\2023-03-10T14_51_51_312Z-debug-0.log
```
And I tried `truffle --version` to check if it was installed successfully or not, but this is the result:

```
PS C:\Users\lenovo> truffle --version
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0
```

I started this process once again by `npm install -g truffle@5.8.0` but the result was the same as in the previous process.

This error throwed because `cli.bundled.js` module can't be found in the given directory:

`Error: Cannot find module 'C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'`

As I checked, There is not any `truffle` folder in that directory and so the mentioned module can't be found there. It seems Truffle installation should create `truffle` folder in that directory but it don't. Is the installation incomplete or it creates that folder in another directory?

## Expected Behavior

Truffle installed successfully and its version appears on the PowerShell!

## Actual Results

The mentioned error appears!

## Environment

* Operating System: Windows 10
* Ethereum client:
* node version (v18.13.0):
* npm version (8.3.0):

**Comment by gnidan** [comment]
Thanks for raising this. Truffle uses POSIX-style command line arguments, which differs a bit from the PowerShell style. If you want to see Truffle's version, you should use `truffle --version` or the `truffle version` command. Generally speaking, full-word flags use `--flag` with short-form `-F` aliases. Understand that this might be a divergence from what PowerShell does, but I'm not sure it's worth the effort to support two styles of command line parsing.

Surely you encounter this with other CLI tools, since POSIX style has been around a lot longer than PowerShell?

**Comment by AlirezaEthDev** [comment]
> Thanks for raising this. Truffle uses POSIX-style command line arguments, which differs a bit from the PowerShell style. If you want to see Truffle's version, you should use `truffle --version` or the `truffle version` command. Generally speaking, full-word flags use `--flag` with short-form `-F` aliases. Understand that this might be a divergence from what PowerShell does, but I'm not sure it's worth the effort to support two styles of command line parsing.
> 
> Surely you encounter this with other CLI tools, since POSIX style has been around a lot longer than PowerShell?

I just tried it by PowerShell. I tried both `truffle --version` and `truffle version` but that same error was resulted.

**Comment by gnidan** [comment]
Oh I'm sorry, I misunderstood the issue. It's not that `truffle -version` doesn't work, but something went wrong and you haven't installed Truffle at all!

I'm not super familiar with the potential gotchas when installing Truffle on Windows. Maybe @eggplantzzz or someone else can provide some guidance on what's going wrong here and help you out.

Apologies that you're running into this!

**Comment by AlirezaEthDev** [comment]
> Oh I'm sorry, I misunderstood the issue. It's not that `truffle -version` doesn't work, but something went wrong and you haven't installed Truffle at all!
> 
> I'm not super familiar with the potential gotchas when installing Truffle on Windows. Maybe @eggplantzzz or someone else can provide some guidance on what's going wrong here and help you out.
> 
> Apologies that you're running into this!

You're welcome. I edited the question title to make more clear my issue.

**Comment by eggplantzzz** [comment]
@cds-amal do you have any insight into what might be going on?

**Comment by AlirezaEthDev** [comment]
This error throwed because `cli.bundled.js` module can't be found in the given directory:

`Error: Cannot find module 'C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'`

As I checked, There is not any `truffle` folder in that directory and so the mentioned module can't be found there. It seems Truffle installation should create `truffle` folder in that directory but it don't. Is the installation incomplete or it creates that folder in another directory?

**Comment by AlirezaEthDev** [comment]
### **The cause of the problem:**

**1)** As I said in the question, `truffle` folder doesn't exist in the both directories mentioned by the errors:

`C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\node_modules\bufferutil`

And

`C:\Users\lenovo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js`

And the installation is incomplete. Because we shouldn't install truffle by the latest version of npm, we should install it by version 6 of npm.

**2)** There is an error in the last few lines of installation process (There is in the question):

`npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build`

That says `node-gyp-build` module doesn't work or doesn't exist. [node-gyp](https://www.npmjs.com/package/node-gyp) is a cross-platform command-line tool written in Node.js for compiling native addon modules for Node.js. [node-gyp-build](https://www.npmjs.com/package/node-gyp-build) is a build tool and bindings loader for `node-gyp` that supports prebuilds. It seems the system that is installing truffle lacks the both them.

### **Solution**:

1. Uninstall Truffle: `npm uninstall -g truffle`.
2. Delete all Truffle's files and folders. Some directories like `C:\Users\lenovo\AppData\Roaming\npm`, `C:\Users\lenovo\AppData\Roaming\npm\node_modules`, `C:\Users\lenovo\AppData\Roaming` and so on, may have Truffle's files and folders.
3. Delete all files associated to `node-gyp` and `node-gyp-module` if you have some of them. Some directory like `C:\Users\lenovo\AppData\Roaming\npm` may have them.
4. Delete node_modules folder from `C:\Users\lenovo\AppData\Roaming\npm`.
5. Change the version of npm to 6: `npm install -g npm@6`.
6. Install node-gyp: `npm install -g node-gyp`.
7. Install node-gyp-build: `npm install -g node-gyp-build`.
8. Install canvas: `npm install -g canvas`.
9. Install Solidity compiler: `npm install -g solc`.
10. Install Truffle: `npm install -g truffle`.
11. Change the version of npm to the latest: `npm install -g npm@latest`.
