### ISSUE TITLE
Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by dongfangrui** [trufflesuite/truffle#5978]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
Error: VM Exception while processing transaction: revert

## Expected Behavior
Set an error randomly in the sol file. After reporting an error, follow the previous tutorial to use truffle development -- the transaction ID can be seen in the log. 

## Actual Results
However, the current situation is that after reporting an error, the transaction ID cannot be seen. Without this ID, one-step debugging cannot be performed. What is the reason?
What you expected to happen.

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

Truffle v5.8.1 (core: 5.8.1)
Ganache v7.7.7
Solidity - 0.8.19 (solc-js)
Node v19.4.0
Web3.js v1.8.2

* Operating System: 
ubuntu

* Ethereum client:Ganache v7.7.7
* Truffle version (`truffle version`):Truffle v5.8.1 (core: 5.8.1)
* node version (`node --version`):Node v19.4.0
* npm version (`npm --version`):

**Comment by gnidan** [comment]
Hi @dongfangrui,  thanks for opening this.

Could you please provide more information that could help us reproduce this problem?

Just a thought: have you tried observing the Ganache output? Ganache should tell you the transaction hash ("transaction ID"), if you're running Ganache separately.

**Comment by dongfangrui** [comment]
For example, in the set function of a simple example file, storage.sol, I define a while loop, or define an assert (x==1), enable truffle development -- log, and then enable truffle development. Call the set function. Once an error is reported, such as let instance=await Storage.deployed(), instance. set (1). In the truffle development terminal, I intelligently see an error and cannot see the transaction id. In the truffle development -- log terminal, "I can't see the transaction ID, and without it, I can't debug it. This kind of error can be debugged in Remix. What I want to ask is, what caused this? Is it my configuration issue or version issue?

**Comment by dongfangrui** [comment]
For example, in the set function of a simple example file, storage.sol,
 I define a while loop, or define an assert (x==1),
 enable truffle development -- log, and then enable truffle development.
 Call the set function. Once an error is reported, such as let instance=await Storage.deployed(), instance. set (1).
 In the truffle development terminal, I intelligently see an error and cannot see the transaction id. 
In the truffle development -- log terminal, "I can't see the transaction ID, 
and without it, I can't debug it. This kind of error can be debugged in Remix. 
What I want to ask is, what caused this? Is it my configuration issue or version issue?

**Comment by dongfangrui** [comment]
truffle(develop)> xx.get()
BN { negative: 0, words: [ 0, <1 empty item> ], length: 1, red: null }
truffle(develop)> xx.set(1)
Uncaught:
Error: VM Exception while processing transaction: revert -- Reason given: Panic: Failed assertion.
    at evalmachine.<anonymous>:0:4
    at sigintHandlersWrap (vm.js:273:12)
    at Script.runInContext (vm.js:142:14)
    at runScript (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:505:1)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:520:1)
    at bound (domain.js:421:15)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:909:10)
    at REPLServer.emit (events.js:400:28)
    at REPLServer.emit (domain.js:475:12)
    at REPLServer.Interface._onLine (readline.js:434:10)
    at REPLServer.Interface._line (readline.js:791:8)
    at REPLServer.Interface._ttyWrite (readline.js:1136:14)
    at REPLServer.self._ttyWrite (repl.js:1004:9)
    at ReadStream.onkeypress (readline.js:265:10)
    at ReadStream.emit (events.js:400:28)
    at ReadStream.emit (domain.js:475:12)
    at emitKeys (internal/readline/utils.js:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1270:36) {
  code: -32000,
  data: {
    hash: null,
    programCounter: 366,
    result: '0x4e487b710000000000000000000000000000000000000000000000000000000000000001',
    reason: null,
    message: 'revert'
  },
  reason: 'Panic: Failed assertion',
  hijackedStack: 'Error: VM Exception while processing transaction: revert -- Reason given: Panic: Failed assertion.\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:25:1\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:165:1\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/lib/index.js:127:1\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)'
}

**Comment by dongfangrui** [comment]
truffle develop --log 

 develop:ganache eth_getBlockByNumber +11s
  develop:ganache eth_call +3s
  develop:ganache eth_getBlockByNumber +4s
  develop:ganache eth_estimateGas +7ms

**Comment by dongfangrui** [comment]
thanks，
