### ISSUE TITLE
truffle not working

### ISSUE THREAD

**Issue by RSviatoslav** [trufflesuite/truffle#5984]
What's going on? I installed truffle via npm and -g truffle, when I want to run truffle init or at least truffle -v, I get the error -bash: /usr/local/bin/truffle: No such file or directory.
The command which truffle says that the package is installed in another location /usr/bin/truffle, how to fix it?
<img width="429" alt="Знімок екрана 2023-04-02 о 11 34 40" src="https://user-images.githubusercontent.com/124620520/229342050-b9deb462-0ed1-47f9-a9f2-0c6fb6045b60.png">

**Comment by RSviatoslav** [comment]
A few hours later, it went away on its own

**Comment by eggplantzzz** [comment]
Hmm I'm not sure what happened here for you. Can we close this issue @RSviatoslav?

**Comment by RSviatoslav** [comment]
> Hmm I'm not sure what happened here for you. Can we close this issue @RSviatoslav?
yes
