### ISSUE TITLE
Unknown arguments format passed to new HDWalletProvider. Please help me fix this error.

### ISSUE THREAD

**Issue by aniket-bansode2311** [trufflesuite/truffle#5991]
### Discussed in https://github.com/orgs/trufflesuite/discussions/5989

<div type='discussions-op-text'>

<sup>Originally posted by **aniket-bansode2311** April 10, 2023</sup>
![Screenshot 2023-04-07 at 10 02 30 PM](https://user-images.githubusercontent.com/118480165/230895727-143844ea-c62c-412a-8e79-7379f89f32ed.png)
</div>

**Comment by eggplantzzz** [comment]
I'm going to go ahead and close this in favor of troubleshooting in the discussion. Thanks for raising this, let's wait until we determine this is a bug to open an issue :)
