### ISSUE TITLE
4.0.0 beta: issues with the console

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/truffle#607]
Hi

I'm using the 4.0.0 beta version on my macOS environment.

I have some issues with the Truffle console.

For example, if I type "web3.eth.accounts" (I know the syntax is not correct) and press enter, the console is locked. I tried to press CTRL-C without any success. The only way I found was to close my terminal window.

Same problem if I try to exit from the console with ".exit". The console doesn't close. But here a ^C is possible.

Are these problems already identified on your side?

Thanks

Said

**Comment by gnidan** [comment]
Hi @eloudsa. This should be fixed in the newest beta. Turns out our initial implementation caused the console to hang when users did this.

Feel free to re-open if I'm wrong and the problem persists!
