### ISSUE TITLE
Decoder should allow `bigint` or `string` in place of `number` in input fields for logs & transactions

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#6080]
## Issue

Right now these are assumed to be numbers, bigints should be allowed as well.

Edit: Strings as well, apparently.

## Environment

* Truffle version (`truffle version`): 5.9.4

**Comment by cliffoo** [comment]
Addressed in [v5.10.2](https://github.com/trufflesuite/truffle/releases/tag/v5.10.2)
