### ISSUE TITLE
BSC-Truffle-Starter-Box Deployment Failed

### ISSUE THREAD

**Issue by CocoStarZ** [trufflesuite/truffle#6094]
<img width="754" alt="image" src="https://github.com/trufflesuite/truffle/assets/136423077/e021ac8b-cc3c-419f-87a9-8a5b910476cc">
## Issue

Got error when deploying the contract.
Error:  *** Deployment Failed ***

"SimpleStorage" hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:330:1
Truffle v5.7.4 (core: 5.7.4)
Node v18.16.0

## Steps to Reproduce
truffle compile --config=truffle-config.bsc.js -all
npm run migrate:bsc --network bscTestnet

## Expected Behavior

Contract deployed.

## Actual Results

Error prompts

**Comment by eggplantzzz** [comment]
Hey @CocoStarZ! Actually that box (https://github.com/bnb-chain/BSC-Truffle-Starter-Box) is not officially maintained by Truffle. Only boxes tagged "official" are maintained by Truffle. I would suggest creating an issue on that repo.

**Comment by CocoStarZ** [comment]
which repo should i use? Also you don't really test the box posted on your official site as an example?

**Comment by haltman-at** [comment]
The repo to file an issue on would be https://github.com/bnb-chain/BSC-Truffle-Starter-Box, as linked above.

Yes, the breakage of the box is unfortunate... at present, we only test community-submitted boxes on submission, we don't currently do periodic retests.  Sorry!

By the way, although this isn't a Truffle issue per se, it seems to me to be worth saying something about that particular error.  That error is one you can get if you compile a contract for one hardfork, but then deploy it using a client that only supports an older hardfork.  If you want to know how to deal with the problem yourself before the box is fixed, I would suggest updating your client if possible, and, if not, setting your compilation options to target the older hardfork your client supports.

Hope that's helpful!

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.

**Comment by tichita7** [comment]
Faced the same issue. Can somebody tell how to fix it?

**Comment by BroLetsCodeIt** [comment]
![image](https://github.com/trufflesuite/truffle/assets/113767803/6d4788be-b880-4d0c-af41-b625d679eee5)
I have changed the version and it works for me

**Comment by umarsandhu397** [comment]
> ![image](https://private-user-images.githubusercontent.com/113767803/285281924-6d4788be-b880-4d0c-af41-b625d679eee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjE2NjQsIm5iZiI6MTcwMzM2MTM2NCwicGF0aCI6Ii8xMTM3Njc4MDMvMjg1MjgxOTI0LTZkNDc4OGJlLWI4ODAtNGQwYy1hZjQxLWI2MjVkNjc5ZWVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxOTU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2UyMTRlZWY5NDYxODQwNTVmZWVkY2U1YWY5N2Y2M2E1OGFlYzlmZDQxZWEzZmVjYjMwZDc0OTI4YjExNzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Lqb_H1JdAiyARYxmoo9-ID39PB7J_QUpmjqVziiWuM) I have changed the version and it works for me

am thankful ... its works
