### ISSUE TITLE
Not able init on Ubuntu

### ISSUE THREAD

**Issue by SyedImam1998** [trufflesuite/truffle#6108]
I have installed Truffle on Ubuntu-22.04.1 and where i tried to init I am gettig this error. and I am using node version v12.22.9

![WhatsApp Image 2023-06-19 at 5 44 28 PM](https://github.com/trufflesuite/truffle/assets/52135949/01ea79bf-ad62-4a02-963d-d207400c850c)

**Comment by haltman-at** [comment]
Unfortunately, we don't support Node 12 anymore.  Truffle currently requires Node 14, 16, or 18 (and note that we expect in the near future to add Node 20 support and drop Node 14 support).  So, we're going to close this issue; please upgrade your Node version if possible.  Sorry!
