### ISSUE TITLE
`artifacts.require("Migrations")` does not work properly

### ISSUE THREAD

**Issue by amachino** [trufflesuite/truffle#611]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`artifacts.require("Migrations")` does not work properly as described in the doc.

> The name specified does not have to match the filename of your contract source files. Instead, it should match the name of the contract definition within that source file.
http://truffleframework.com/docs/getting_started/migrations

## Steps to Reproduce

1. Run `truffle init`
2. Change `artifacts.require("./Migrations.sol")` to `artifacts.require("Migrations")`  in `migrations/1_initial_migration.js`
3. Run `truffle migrate`
4. Run `truffle migrate` again

## Expected Behavior

At step 4, following messages should appear.

```
$ truffle migrate
Using network 'development'.

Network up to date.
```

## Actual Results

Existing contracts are deployed again.

```
$ truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x9e8c47b0637c1f2deab543b6840253c56a33dbaa7b9c75c411a7ea14e5f34e34
  Migrations: 0x75966466a4899a9c97ffe252b5a2b54dcab70ee0
Saving successful migration to network...
  ... 0x0aab81dd554bdd02c8533f00822f75475ae4d4c6f1f3b2eb73b6c79a9cfa9bba
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing ConvertLib...
  ... 0xa4a01a51cc4146ff3366a06d354504e5c134cce4055d70c8ed6ebb413f7c8eec
  ConvertLib: 0xddec2d9170797f26771430747d3768ff49a1051a
  Linking ConvertLib to MetaCoin
  Replacing MetaCoin...
  ... 0xe654a857a6b19df54b4593f57742f496ddd66c51e1b9ce0e11eb0526c486a120
  MetaCoin: 0xfc97eac0c4eb73ffde9a8f481608de725e0eaa29
```

## Environment

- macOS Sierra
- Truffle v3.4.11 (core: 3.4.11)
- Solidity v0.4.15 (solc-js)
- TestRPC/v1.1.3/ethereum-js
- Node.js v8.6.0
- npm 5.4.2

**Comment by davidperrenoud** [comment]
I've got the same problem. The steps `Saving successful migration to network...` are not done if one uses the syntax `artifacts.require("Migrations")`.

**Comment by eggplantzzz** [comment]
I could not duplicate this issue with the most recent version of truffle, is it still an issue?  If not I will close this in a few days.

**Comment by davidperrenoud** [comment]
Still an issue with Truffle v4.1.14. To reproduce you need to start with a brand new project where you haven't run `truffle migrate`.

Here is the error I get now:
```
Running migration: 1_initial_migration.js
fs.js:122
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:509:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)
    at FS.getContractName (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:101724:10)
    at FS.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:101698:28)
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:59966:25)
    at Object.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:69602:36)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:197047:32)
    at /Users/pea/tend/smart-contracts-test/migrations/1_initial_migration.js:1:30
    at Script.runInContext (vm.js:130:20)
    at Script.runInNewContext (vm.js:136:17)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:101639:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by davidperrenoud** [comment]
Can anyone test this again?

**Comment by eggplantzzz** [comment]
Truffle will accept a filename currently in the `artifacts.require()`. The correct way to do this (and avoid confusion) is to use the contract type name.
