### ISSUE TITLE
tx fails on Sepolia for visual debugger

### ISSUE THREAD

**Issue by eggplantzzz** [trufflesuite/truffle#6113]
The following tx produces an error while attempting to debug with the visual debugger:

(on Sepolia)
0x84f82b79b516aa64f38797f204e09a49e821f7f9353723545dfd600e99b60955

**Comment by eggplantzzz** [comment]
Turns out this is actually an issue with Ganache.

**Comment by haltman-at** [comment]
Specifically, it's https://github.com/trufflesuite/ganache/issues/4450
