### ISSUE TITLE
Truffle compile does not import remote sources

### ISSUE THREAD

**Issue by rhlsthrm** [trufflesuite/truffle#613]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When trying to `import` remote sources (i.e. from GitHub), `truffle compile` fails.

## Steps to Reproduce

1. Write contract importing a library, for example:
```
import "github.com/Arachnid/solidity-stringutils/strings.sol";

contract Contract {
    using strings for *;

    // ...
}
```
2. Run `truffle compile`.

## Expected Behavior

Contract compiles.

## Actual Results

Error message:
```
Error: Could not find github.com/Arachnid/solidity-stringutils/strings.sol from any sources; imported from /Users/Rahul/Desktop/ethereum-social-identity/ethereum-social-identity/contracts/SocialIdentityLinker.sol
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:49111:23
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:60660:16
    at next (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:69109:18)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:49099:7
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:96498:5
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:69014:16
    at replenish (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60630:25)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60620:17)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:60660:16
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:96494:14)
```

## Environment

* Operating System: macOS
* Truffle version: v3.4.9
* Ethereum client: Parity
* node version: v8.6.0
* npm version: 5.4.2

**Comment by gnidan** [comment]
I don't believe that is supported by Solidity natively. Solidity documentation [indicates](http://solidity.readthedocs.io/en/develop/layout-of-source-files.html?highlight=import#use-in-actual-compilers) that it is possible to remap "github.com"-style paths to a local directory, but that is not supported by Truffle at this time.

In order for Truffle to support this, it would require a new feature to fetch contract sources via a URL. In the meantime, Truffle provides integrations with [NPM](http://truffleframework.com/docs/getting_started/packages-npm) and [EthPM](http://truffleframework.com/docs/getting_started/packages-ethpm) that may help some use cases.

If you'd like, please file a new issue for such a feature. PRs also welcome :), although anyone who wishes to look into such an effort may want to contact one of the core Truffle devs first.

Thank you!
