### ISSUE TITLE
Intermittent "Invalid opcode" exceptions when running tests

### ISSUE THREAD

**Issue by jaddison** [trufflesuite/truffle#614]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running tests, they 'sometimes' (ie intermittently, seemingly randomly) fail with an "invalid opcode" exception, using `node_modules/.bin/testrpc`.

## Steps to Reproduce

It's intermittent, so there aren't any consistent steps for reproduction.

I simply run:
```
node_modules/.bin/truffle test
```

## Expected Behavior

Tests would always execute cleanly and consistently.

## Actual Results

```
~/projects/proj/token-sale (master)$ node_modules/.bin/truffle test
Compiling ./contracts/IRefundHandler.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/MySale.sol...
Compiling ./contracts/MyToken.sol...
Compiling ./test/helpers/MockSale.sol...
Compiling ./test/helpers/MockToken.sol...
Compiling zeppelin-solidity/contracts/lifecycle/Pausable.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling zeppelin-solidity/contracts/token/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...


  Contract: MySale
    1) "before all" hook


  0 passing (210ms)
  1 failing

  1) Contract: MySale "before all" hook:
     Error: VM Exception while processing transaction: invalid opcode
      at Object.InvalidResponse (node_modules/truffle/build/cli.bundled.js:37312:16)
      at node_modules/truffle/build/cli.bundled.js:220420:36
      at node_modules/truffle/build/cli.bundled.js:204149:9
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/cli.bundled.js:205574:13)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/cli.bundled.js:73069:18)
      at XMLHttpRequest._setReadyState (node_modules/truffle/build/cli.bundled.js:73359:12)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/cli.bundled.js:73514:12)
      at IncomingMessage.<anonymous> (node_modules/truffle/build/cli.bundled.js:73474:24)
```
If I restart `testrpc`, I don't *usually* see the issue - but it certainly can and has happened immediately after the restart. The problem is exacerbated if I have multiple .js test files; sometimes the first will work, while other times the first one fails but the 2nd one works. Sometimes they all fail.

And yes, the failures happen without any code changes. I know the test cases are all green and working.

## Environment

* Operating System: macOS 10.13 (happens on 10.12 too); also happens on Ubuntu 16.04
* Truffle version: Truffle v3.4.11 (core: 3.4.11); Solidity v0.4.15 (solc-js)
* Ethereum client: EthereumJS TestRPC v4.1.3 (ganache-core: 1.1.3)
* node version: v8.4.0
* npm version: 5.4.2

**Comment by jaddison** [comment]
Closing. Found a race-condition type of issue. Apologies for the noise.

**Comment by 7sedam7** [comment]
@jaddison can you provide the solution that solved your problem, please?

**Comment by jaddison** [comment]
I don't recall specifically - but it wasn't `truffle` or `testrpc` related. It was definitely my contract/deployment logic. I think it was likely with how I was deploying to `testrpc` in my migrations - maybe it wasn't waiting for contracts to deploy before calling contract functions? Something along those lines.
