### ISSUE TITLE
An error occurred while initializing the debugger. 

### ISSUE THREAD

**Issue by PtahSeven** [trufflesuite/truffle#6150]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
An error occurred while initializing the debugger. Often errors can be caused by being connected to the incorrect network for a specific transaction. Ensure you have MetaMask connected to the appropriate network for your transaction. See the error below for more information.
base fee exceeds gas limit (vm hf=shanghai -> block -> tx)

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results
![屏幕截图 2023-07-22 124524](https://github.com/trufflesuite/truffle/assets/126786904/b76ea4d8-439c-46c2-a242-6f7a9b4cdb37)

## Environment

* Operating System:  Windows 11 
* Ethereum client:
* Truffle version (`truffle version`):  v5.11.0
* node version (`node --version`): v18.16.1
* npm version (`npm --version`): 9.5.1
* Ganache v7.9.0
* Solidity v0.5.16 (solc-js)
* Web3.js v1.10.0
* Chain version : Arbitrun

**Comment by eggplantzzz** [comment]
Hey @PtahSeven, could you please provide us with more information about how you received this error? If you could provide detailed steps for how you received this error we'll help you troubleshoot it!
