### ISSUE TITLE
Warning: No Visibility specified on ConvertLib.sol sample contract

### ISSUE THREAD

**Issue by cyberience** [trufflesuite/truffle#616]
Running the defaul contracts, truffle init, migrate and then compile I get warnings encountered.

## Steps to Reproduce
truffle compile

## Expected Behavior

Clean build

## Actual Results

Warning: No visibility specified.

## Environment

* Operating System: Mac OS sierra
* Truffle version: v4.0.0-bea.2
* Ethereum client:TestRPC v4.1.3 (ganache-core: 1.1.3)
* node version:v8.6.0
* npm version: 5.4.2

**Comment by onetom** [comment]
The issue should be solved by updating https://github.com/trufflesuite/truffle-init-default to be compliant with the latest Solidity version (0.4.17).

I filed an issue for it in that repo:
https://github.com/trufflesuite/truffle-init-default/issues/5

**Comment by gnidan** [comment]
Thanks for filing this issue!

As part of the Truffle 4 release, `truffle init` is switching to accept no arguments, instead initializing a bare Truffle project. See #617 for more information.

Closing this, as `truffle-init-default` will no longer be used. For compatibility problems like this one in individual boxes, please open a ticket in the corresponding box. Thank you!
