### ISSUE TITLE
Add command for creating a bare project

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#617]

**Comment by bmmpxf** [comment]
In v3, the command `truffle init bare` would create a bare bones project, while `truffle init` has a MetaCoin project inside it.

In v4, `truffle init` is deprecated in favor of `truffle unbox`, but there is no corresponding `truffle unbox bare`.

**Comment by tcoulter** [comment]
Good observations. This should be broken down into the following pieces of work:

* Create a bare truffle box (whether we advertise the bare box is a different story)
* Create a Metacoin truffle box
* Make `truffle init` an alias for `truffle unbox bare` and remove all other `truffle init` functionality

**Comment by kevinhughes27** [comment]
I was actually confused by these commands - my assumption was that I would run both `truffle init` and then `truffle unbox` with my chosen box. This doesn't work since `unbox` won't run in an existing directory. I was actually going to open an issue about this but if `init` is being deprecated then there is no point.

**Comment by gnidan** [comment]
@tcoulter:

> - Create a bare truffle box (whether we advertise the bare box is a different story)

Considering #621, perhaps we ought to hardcode what it means to be a "bare" Truffle project, so that `truffle init` just creates the `contracts/`, etc. directories and a blank `truffle.js`.

> - Create a Metacoin truffle box (advertised)

This would be be the default for `truffle unbox`?

> - Make truffle init an alias for truffle unbox bare and remove all other truffle init functionality

:+1:

**Comment by gnidan** [comment]
This is now the behavior for `truffle init`

**Comment by fdouglis** [comment]
I realize this has been closed, but as a new user, it seemed like a good place to point out that the truffle tutorial still acts like metacoin is available as a side effect of init.  On [this](http://truffleframework.com/docs/getting_started/project) page it points out that has changed, but all the other places that refer to it should be updated too.

**Comment by bmmpxf** [comment]
Hi @fdouglis . We've caught most of the old MetaCoin behavior in our docs, we think, but if you see other instances, please create tickets at https://github.com/trufflesuite/trufflesuite.com/issues and we'll take care of them. Thanks!
