### ISSUE TITLE
truffle init should make a .gitignore

### ISSUE THREAD

**Issue by ajunge** [trufflesuite/truffle#62]
It would be nice. I always need to add one for every new project.

proposed content:

```
# Logs
logs
*.log

# Directories used by tools like mocha & istanbul
coverage
shippable

# Dependency directory
node_modules

# Generated files
config/development/contracts.json
config/development/*.sol.js
config/test/contracts.json
build
dist



```

**Comment by harlantwood** [comment]
I'm new to truffle, but it looks like 0.3.1 generates:

```
environments/development/contracts/*.sol.js
```

which should probably be gitignored.

**Comment by larspensjo** [comment]
If it does, I think it should be optional. There are a lot of version management tools, and they all have different ignore mechanisms.

**Comment by PeterBorah** [comment]
Would appreciate a way to do this. First thing I do after `truffle init` is make this .gitignore:

`environments/*/contracts/**`

But I can never remember exactly what it should be, so I have to go find it in another repo. Would be nicer to just go, `truffle init --with-gitignore`.

**Comment by andy-mc** [comment]
Yeap I end up here looking for a template for a .gitignore for truffle but not all think is a good idea so a flag option would be great :) !!

**Comment by tcoulter** [comment]
We've now launch [Truffle Boxes](http://truffleframework.com/boxes) as of a week ago. This will be dependent on the individual boxes. Soon `truffle init` will be converted to its own box. Cheers! Please file a new issue if this continues to be a problem.
