### ISSUE TITLE
https://truffle.readthedocs.io/ broken

### ISSUE THREAD

**Issue by HaleTom** [trufflesuite/truffle#620]
---------------------------

## Issue

Docs links are broken

## Steps to Reproduce

Browse to: https://truffle.readthedocs.io/

Or try any link (except beta) at:
https://readthedocs.org/projects/truffle/

## Expected Behavior

To see the docs

## Actual Results

```
      \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
...
```

**Comment by gnidan** [comment]
Hi @HaleTom. truffle.readthedocs.io was an outdated version of the Truffle documentation. Please refer to [truffleframework.com/docs](http://truffleframework.com/docs/) for the most up-to-date Truffle documentation. Thank you!
