### ISSUE TITLE
Can't re-migrate a contract with truffle develop

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#622]

**Comment by bmmpxf** [comment]
Using 4 beta 1.

Working with a contract that I've deployed using `truffle develop`. After migration, I made a change to the contract, and wanted to redeploy it. I compile the contract again and then run `truffle migrate` but the console says "network up to date". I even tried `truffle migrate --reset`, but same output. Is this intentional?

**Comment by gnidan** [comment]
@bmmpxf just tested `migrate --reset` inside the Develop console, and that works. I guess our fears were for nought!

(Closing this)

**Comment by arielgabizon** [comment]
`migrate --reset` worked for me; but I think truffle should be able to recognize the contract code changedb
