### ISSUE TITLE
Truffle Develop should display the mnemonic

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#627]
Chosen mnemonic: `candy maple velvet cake sugar cream honey rich smooth crumble sweet treat`

**Comment by bmmpxf** [comment]
When you run `testrpc`, it displays both addresses, private keys, and the mnemonic. 

Since `truffle develop` is meant to be a replacement for using `testrpc`, we should mimic this behavior. At the very least, it should display the mnemonic, as there is no other way to determine it from within the console.

**Comment by gnidan** [comment]
Done!
