### ISSUE TITLE
Truffle migrate / test process doesnt end

### ISSUE THREAD

**Issue by DaneWiid1** [trufflesuite/truffle#629]
Running truffle test --network local,  hangs at the end of the process after updating the /build/contracts directory. Same issue when running a deploy, script just hangs after saving artifacts

**Comment by cgewecke** [comment]
@DaneWiid1 I think this might be a duplicate of #624, and am going to track the issue there. If you're still having problems running tests and you're not using Geth / Parity, please re-open. Thanks!
