### ISSUE TITLE
Truffle 4 beta.1: contracts installed from EPM do not properly deploy on test network (reproducible)

### ISSUE THREAD

**Issue by skmgoldin** [trufflesuite/truffle#630]
## Issue

Contracts installed using `truffle install` do not properly deploy on the test network when run with `truffle test`.

## Steps to Reproduce

```
git clone git@github.com:skmgoldin/dead-mans-switch.git
cd dead-mans-switch
git checkout truffle4-bug
npm i
npm run compile
npm run test
```

Notice the `HumanStandardToken has not been deployed to detected network (network/artifact mismatch)` error (ignore any other errors, they're unrelated, this branch is from a WIP repo).

If you change the token imports in `migrations/3_token.js` and `test/dead.js` to `const Token = artifacts.require('./tokens/HumanStandardToken.sol');` (prepending a `./`, using the local copies in the `contracts` directory instead), that error goes away.

## Expected Behavior

Contracts in the `installed_contracts` directory should be deployed on the test network.

## Actual Results

They are not deployed on the test network.

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: beta.1
* Ethereum client: Truffle internal test RPC
* node version: 8.7.0
* npm version: 5.4.2

**Comment by tcoulter** [comment]
@skmgoldin Sweet bug man. Thanks for the report.

We've identified the issue and will plan a fix for it, likely for after Truffle 4.0 is released. In the meantime, there's a very simple workaround. On [this line](https://github.com/skmgoldin/dead-mans-switch/blob/truffle4-bug/test/dead.js#L5) you have the following code:

```
const Token = artifacts.require('tokens/HumanStandardToken.sol');
```

To circumvent the issue (for now), change it to this:

```
const Token = artifacts.require('HumanStandardToken');
```

For technical reasons (I can go into detail if you like), this will still pull the `HumanStandardToken` contract you were expecting.

Fixing this issue for good will require some rework, as it identifies an EPM use case we didn't think about (and no one else seems to have exercised yet). Thanks for bringing this to our attention, and we'll let you know when it's fixed for good.

Thanks again!

**Comment by skmgoldin** [comment]
Thanks Tim! That workaround is fine.

**Comment by tcoulter** [comment]
Chatted with @skmgoldin about why this issue occurs. Putting the response here for posterity: 

> It has to do with the (we'll call it) artifact pipeline. When you compile/deploy an EPM contract, it actually creates an artifact for it in `./build/contracts` (it mingles with the artifacts of your own contracts). When you need to use it in your tests, we were supposed to then return that artifact, but instead we were returning an artifact from the package itself. 
> 
> Now, the quick fix is to just return _our_ artifact. But that's going to cause issues for your app, because _our_ artifact doesn't contain addresses for deployed versions that might exist in the package itself; that is to say, if you don't have the mainnet artifact you're expecting for certain types of EPM packages, you're going to have a bad time (the `token` package isn't one of these types; but I digress). So the real solution is to merge the artifacts the package has with the artifacts you create locally, essentially creating a "master artifact" that will work in all cases.

**Comment by skmgoldin** [comment]
Here's another place you can reproduce it if you desire: https://github.com/ConsenSys/PLCRVoting/tree/f9edfd5edcf409b075c63952e9dea5ff56f8783b

```
git clone git@github.com:ConsenSys/PLCRVoting.git
cd PLCRVoting
git checkout epm
git checkout f9edfd5edcf409b075c63952e9dea5ff56f8783b
npm i
npm run compile
```
