### ISSUE TITLE
Struct Testing

### ISSUE THREAD

**Issue by SawanKumarJindal** [trufflesuite/truffle#639]
## Issue
**Hello, I have been doing some truffle testing and I wanted to test some struct's but even after reading through the whole Assert.sol, I couldn't find anything on that. Can anyone help me?

I am creating that struct from a constructor.**

## Environment

* Operating System: Ubuntu
* Truffle version: v3.4.11
* Ethereum client: testrpc
* node version: v6.11.4
* npm version: 3.10.10

**Comment by sabhiram** [comment]
I am fairly new to solidity, but the `Assert` contract only gives you helper functions to validate specific types that are common. A struct is a plain-ol-data construct, the definition of which is left to the developer. Therefore, it would not make sense to have common helper functions for custom structures. 

What is it that you are trying to validate? Your contract will typically have accessors which are public to fetch various pieces of your structure - you would call those functions, fetch the underlying types and `Assert` (for example) against those. Does that make sense?
