### ISSUE TITLE
[Multi Repo PR] Expose the natspec documentation to DAPP developers through Truffle

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#640]
The [Ethereum Natural Specification Format aka natspec](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) is a way to document both developer and user hints on the usage of Solidity smart contracts. 

The solc-compiler will extract this information into a `userdoc` and `devdoc` variable. While created to allow solidity developers to give more information to DAPP developers and users of the smart contracts, it is not possible to use this information since Truffle does not expose this information.

I'll link 3 PR's across 3 components that extract, store and expose this information for use in a DAPP environment.

While exposing is step one, I do have some fears on the usability of the information. It exposes this info in an object structure where the key is eg. myFunctionName(bytes32). In an optimal setting this would be linked to the function in truffle-contract like so: myContract.myFunctionName.userdoc(). Any idea's on how to get there?

**Comment by macalinao** [comment]
Bump. This is something that's super useful.
