### ISSUE TITLE
beta2: `truffle migrate` and `truffle test` do not fire up default test environment

### ISSUE THREAD

**Issue by SCBuergel** [trufflesuite/truffle#643]
I am running the truffle beta2 on MacOS. I started with the default project:
```
truffle init
truffle compile
truffle migrate
truffle test
```
The last two commands give me the following error output:
```
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```
I expected this to behave in the same way as `migrate` and `test` inside the `truffle develop` console - which works without a problem in the very same folder.

**Comment by brianedelman** [comment]
Did you change your networks to 9545 in the truffle.js?

**Comment by leTrice** [comment]
Hi @brianedelman , just checked this with port 9545 and with port 8546. Same behaviour as described by @SCBuergel . It seems that migration and test scripts are only running under development console (truffle develop).

**Comment by brianedelman** [comment]
Ah yes. I have been running `truffle develop --log` to basically give me the same output as testrpc used to. Migrate and test are done with this running on 9545

**Comment by leTrice** [comment]
Hi @brianedelman , this is exactly the missing piece for me, now i can use it like ethereumjs-testrpc before. Just start another terminal and fire `truffle develop --log` and in another terminal, you can run `truffle migrate` or `truffle test` as before.

**Comment by oaojesse** [comment]
Will `truffle test` run an in memory testrpc by default as described in #490?

**Comment by jessebmiller** [comment]
Will truffle test run an in memory testrpc by default as described in #490?

**Comment by shuji-koike** [comment]
Test written in solidity seems to be working as expected, but js tests are not?

I wrote some same tests as solidity and js.
And as far I can tell, on my environment...

* if testrpc or ganache is running, both tests passes
* if `development` network is defined in config file but testrpc is **not** running, both tests fails
* if `development` network is **not** defined and testrpc is **not** running, solidity tests passes but is js tests fails

BTW I'm newbie in truffle and ethereum, hope my info hepls.

**Comment by GodwinAdam** [comment]
https://medium.com/etherereum-salon/eth-testing-472c2f73b4c3 follow these steps.

**Comment by Fariha1123** [comment]
Its port 8545 on which testrpc runs, so specify that in your truffle.js. Moreover, in another powershell window just initiate test rpc via this command : testrpc. Hope this works !

**Comment by dongw00** [comment]
It seems to difference with your ethereum client (such as geth, ganache). check your ethereum client's port. you have to match port num in truffle-config.js file.
![image](https://user-images.githubusercontent.com/32030234/52531764-daf1d100-2d5d-11e9-891e-f79cb0a3738d.png)
