### ISSUE TITLE
Feature request: Manually specify already-deployed contract addresses

### ISSUE THREAD

**Issue by Arachnid** [trufflesuite/truffle#651]
Not all apps need to deploy all of the contracts they interact with from scratch; some rely on interacting with already-deployed contracts on public chains, such as ENS and token contracts.

It'd be great if Truffle let you specify, in a migration, that it should record a particular contract as deployed at a particular address, without taking any onchain action. This would allow for specifying well-known addresses of existing contracts in a migration and being able to interact with them from JS just like any other contract.

**Comment by cemdev** [comment]
+1
