### ISSUE TITLE
Truffle Develop doesn't show private keys

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#653]
Users have been reporting the need to see private keys for use with MetaMask.

(We need to ensure that the mnemonic is in fact not sufficient and plan to include private key output)

**Comment by eloudsa** [comment]
This feature will be really appreciated because right now I have to import accounts on Metamask and I don't know where to find the private keys generated by Truffle.

**Comment by NedYork** [comment]
I've made a PR on truffle-core which hard-codes the corresponding private keys and logs them. If there's any request to make the public key dynamically generated from a hard-coded private, I'd be happy to implement such feature.

**Comment by eloudsa** [comment]
Can we expect this feature on 4.0.2?

**Comment by iamchrissmith** [comment]
Until this gets merged, here are the private keys in text format so anyone can copy them into metamask. (Note: I OCR'ed an image from @NedYork in the PR. I verified the first one, but have not made sure the others came through correctly):
Private Keys: 
(0) c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3 
(1) ae6a2826ccbfb04590405997ee2d52d2b330726i37b875053c36d94e974di62f 
(2) Odbbe8e4a2425a6d2687fia7e3bai7bc98c673636790fib8adgii93c05875efi 
(3) c88b703fb08cbea894b6aeff5a544fb92e78ai8ei98i4cd85da83b7if772aa6c 
(4) 388c684f0balef50177i6adb5d2ia053ea8e90277d0868337519f97bede61418 
(5) 659cbb0e2411a44db63778987bie22153c086a95ebobi8bdf89de078917abc63 
(6) 82d052c865f5763aad42add438569276c00d3d88a2d062d36b2bae9i4d58b8c8 
(7) aa368od5d48a8283413f7a108367c7299ca73f553735860a87bo8f39395618b7 
(8) Of62d96d6675f32685bbdb8aci3cda7c23436f63efbb9d07700d8669ffi2b7c4 
(9) 8d5366i23cb560bb606379f90a0bfd4769eecc0557fib362dcae90i2b548bie5

**Comment by onetom** [comment]
Why would you want to copy these keys one by one into MetaMask?

Just pasting the mnemonic into MetaMask, then clicking the Create Account menu a few times would recreate them within MetaMask automatically, since they are derived from the mnemonic.

Is it about convenience, so you can mix these in with your other keys you have already added to MetaMask?

Is it even a good idea to do so?

**Comment by arielgabizon** [comment]
@onetom  that would be convenient. But I don't see a place to past the phrase in metamask

**Comment by arielgabizon** [comment]
@iamchrissmith some of the keys work and some do not - e.g. (5)

**Comment by albertc44** [comment]
@arielgabizon you need to "logout" of metamask by hitting "Lock" and then below where you enter your password is the "restore from seed phrase" link

![screen shot 2017-11-17 at 9 08 48 pm](https://user-images.githubusercontent.com/1314187/32975971-a554107e-cbdb-11e7-9392-021d48726aa9.png)

**Comment by richmcateer** [comment]
Some of the keys @iamchrissmith posted didn't work for me.

The correct keys can be found here (and pasted below): https://github.com/trufflesuite/truffle-core/blob/ab4281ff3363da4810168b750de6f525da20fd17/lib/commands/develop.js#L68

    var privateKeys = [
      'c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3',
      'ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f',
      '0dbbe8e4ae425a6d2687f1a7e3ba17bc98c673636790f1b8ad91193c05875ef1',
      'c88b703fb08cbea894b6aeff5a544fb92e78a18e19814cd85da83b71f772aa6c',
      '388c684f0ba1ef5017716adb5d21a053ea8e90277d0868337519f97bede61418',
      '659cbb0e2411a44db63778987b1e22153c086a95eb6b18bdf89de078917abc63',
      '82d052c865f5763aad42add438569276c00d3d88a2d062d36b2bae914d58b8c8',
      'aa3680d5d48a8283413f7a108367c7299ca73f553735860a87b08f39395618b7',
      '0f62d96d6675f32685bbdb8ac13cda7c23436f63efbb9d07700d8669ff12b7c4',
      '8d5366123cb560bb606379f90a0bfd4769eecc0557f1b362dcae9012b548b1e5'
    ];

**Comment by tcoulter** [comment]
This will go out in the next release. Cheers!

**Comment by sarbogast** [comment]
If you restore the Metamask vault from the default seed phrase used by Truffle, doesn't it create a huge security problem when you create new accounts from Metamask on the main net? Anyone would be able to find the private key for this account, wouldn't they?

**Comment by onikajnu** [comment]
Can you please tell me which key generation algorithm is used by truffle suite for generating these keys?

**Comment by gnidan** [comment]
@onikajnu you can see the implementation here: https://github.com/trufflesuite/truffle/blob/develop/packages/core/lib/mnemonics/mnemonic.js#L22-L33
