### ISSUE TITLE
Prompt `truffle(develop)>` not appear when `--log`

### ISSUE THREAD

**Issue by katopz** [trufflesuite/truffle#657]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Prompt `truffle(develop)>` not appear when `--log`

## Steps to Reproduce

```
$ truffle develop --log
```
![image](https://user-images.githubusercontent.com/97060/32314946-be7b06ee-bfdc-11e7-94a3-e7a9816e1e86.png)

## Expected Behavior

`truffle(develop)>` appear for input

## Actual Results

`truffle(develop)>` missing

## Environment

* Operating System: macOS 10.12.6 (16G29)
* Truffle version: 4.0.0
* Ethereum client: ?
* node version: 8.9.0
* npm version: 5.5.1

**Comment by gnidan** [comment]
You have found a "feature"! 😄

We decided to make the `--log` console be **only logs**, no prompt. The idea being, in one terminal, do `truffle develop --log`, and then use a second terminal with `truffle develop` for the prompt.

Others have reported confusion around this, so we may discuss changing this behavior or making things clearer. Thanks for opening an issue and bringing it more to my attention!

Leaving this open to follow-up after the release simmers a bit.

**Comment by ngan** [comment]
Hi @gnidan, just curious...why not just automatically log out to a log file, say `log/testrpc.log`? That way you can just tail the log file. I find it super cumbersome to restart my develop environment when I have both log and prompt open. You have to stop both then start both back up.

**Comment by gnidan** [comment]
@ngan We considered that, but decided against it for various reasons, including the disk space that the log would consume.

As of right now, I don't have a good sense for what I'd consider to be the "best" solution to this problem. I'll bring it up with the rest of the Truffle team in the coming week and see about the various options to compare. I'll relay those here to proceed with the discussion.

Thanks for identifying this issue!

**Comment by fkirc** [comment]
I am running into the problem that `truffle develop --log` terminates immediately (please see https://github.com/trufflesuite/truffle/issues/846 for more details).
I understand that `--log` is not intended as a develop-prompt, but I expected `--log` to remain open in order to observe a develop-session from a separate terminal window.

**Comment by cds-amal** [comment]
Hi @fkirc There's a known issue with `truffle develop --log` that we're working on. As a workaround you can start ganache-cli separately and use `truffle console --network development`. 

For example if truffle-config contains a network definition like:
```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
    },
  }, 
  // --- snip ---
}  
```
Start ganache in one terminal: `ganache-cli -p 8545`
Start the console in another: `truffle console --network development`

**Comment by fkirc** [comment]
Thank you for the quick response, the approach in #3909 works for me.
Actually, I am not even sure whether this is a workaround or a preferred approach.
Because what is the point of using `truffle develop` if `ganache-cli` can do the same job better (the job of launching a local blockchain via a CLI)?
I am still new to Truffle so this is just a learning process for me, but it seems that there exists a large amount of feature-duplication between `truffle develop` and `ganache-cli`?

**Comment by cds-amal** [comment]
No worries @fkirc. Glad the alternative works for you. `ganache-cli` is a standalone test-net. `truffle develop` and `truffle console` are different interfaces for ganache or another provider.`truffle develop` manages an in-memory ganache provider and `truffle console` connects to another provider.  [More info on the two console options here](https://www.trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console#why-two-different-consoles-)

**Comment by NoContext-halp** [comment]
I don't understand how #3909 is a work around to the `truffle develop --log` immediately terminating. I cannot figure out how to use `truffle console` to get logs.
