### ISSUE TITLE
truffle develop => truffle dev

### ISSUE THREAD

**Issue by ngan** [trufflesuite/truffle#661]
Would it be possible to rename or alias `truffle develop` to `truffle dev`.  I found that typing `truffle develop` over and over again was getting painful. "develop" is long and I find myself typing "development" then going oops and deleting "ment" a lot...

Maybe it's just me :-/

**Comment by gnidan** [comment]
@ngan This already works!

<img width="734" alt="screen shot 2017-11-03 at 11 05 38 am" src="https://user-images.githubusercontent.com/151065/32380660-fc626c0e-c086-11e7-8b2a-acaa636350c8.png">

Closing this - let me know if it doesn't work for you and I'll re-open.

**Comment by ngan** [comment]
![Mind blown](http://www.reactiongifs.com/r/2013/10/tim-and-eric-mind-blown.gif)
