### ISSUE TITLE
Truffle develop now requires babel register for import statements to work in tests

### ISSUE THREAD

**Issue by brianedelman** [trufflesuite/truffle#664]
## Issue

Using 4.0.1 of Truffle, `truffle test` returns this error after compiling.
```
import ether from './helpers/ether';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
```
This is the first import line in one of my js test files.

I ran into this issue in the beta and added `require('babel-register')` to my truffle.js file. This fixes the import error and tests run.

## Steps to Reproduce

With 4.0.1, run truffle test with new development network that is generated (or with old way). Make sure the test has an import statement at the top.

## Expected Behavior

Adding babel require seems to fix the issue.

## Environment

* Operating System: 10.12.6
* Truffle version: 4.0.1
* Ethereum client:
* node version: 8.4.0
* npm version: 5.5.1

**Comment by mancze** [comment]
I think this has nothing to do with the actual truffle framework since the erroneous line is in your test file. You have used ES6 module loading syntax which is not supported in v8.4.0 of nodejs (your version) nor in v9.2.0 (current latest).

The only way to make ES6 modules work is by using transpiler/compiler like `babel`.

**Comment by tcoulter** [comment]
Hi there,

@brianedelman, you said this: 

> I ran into this issue in the beta and added require('babel-register') to my truffle.js file. This fixes the import error and tests run.

This is currently the only way to support the import statement, as mentioned by @mancze. 

I'm going to close this issue as you're already aware of the workaround. Cheers!

**Comment by jacktang** [comment]
I have the same issue about it https://github.com/truffle-box/react-box/issues/49

**Comment by pospi** [comment]
I think registering load hooks within the module system won't work around this issue anymore. All scripts now seem to be loaded through [truffle-require](https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-require/require.js), and this imports `original-require` which gets a handle on `require` prior to any code in `truffle.js` being executed.

End result is any changes you make to the module loading system will no longer be reflected by scripts that truffle loads in.

**Comment by timothywangdev** [comment]
the solution is not working anymore. Agree with @pospi
