### ISSUE TITLE
Test suite runs out of gas before finishing

### ISSUE THREAD

**Issue by ngan** [trufflesuite/truffle#666]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have a very large test suite that tests my contract very thoroughly. It also tests invalid calls, so when those tests run, ALL the gas for that transaction gets used up. Eventually, after a certain number of tests, the whole suite fails because of not enough gas to even start the next transaction. Is there a way to be able to have very large and expensive test suites finish completely? Is there a way to Ether to the default generated addresses? Is there a way to lower the gas price to 0 or something very very small automatically?

**Comment by VladWulf** [comment]
I suggest using testrpc with a large gas limit parameter:
`testrpc --gasLimit 300000000` the default is 9000
If that is still a problem, put a high value (but lower than the one above) for the gas field in the truffle.js inside your project.

**Comment by tcoulter** [comment]
Are you running Solidity tests or Javascript tests?

In both Solidity and Javascript tests suites, tests are made up of many transactions -- not just one transaction. If your tests are running out of gas, it means your transactions are running out of gas (a bad thing; you should figure out why). 

Note that the only exception here is Solidity tests, in that you can you can write a single Solidity test that fills up the gas limit in a single transaction. To get around this, use the [available hooks](http://truffleframework.com/docs/getting_started/solidity-tests#before-after-hooks) in your solidity test suite break up your tests into multiple transactions.

**Comment by ngan** [comment]
Hi @tcoulter I'm using javascript tests. I think what's happening is I'm testing error cases, and upon error the entire gas limit is used up for that transaction (even though I'm using `require` to stop the transaction). I thought in the latest Ethereum client specs, transactions are prorated when `require` throws an error instead of consuming all the gas.
