### ISSUE TITLE
Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by NateDev100** [trufflesuite/truffle#667]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I've created a simple Token.sol file, and a simple TokenCrowdsale.sol file, as well as a 2_deploy_contracts.js file. By simple, I mean I haven't changed much from the default that I imported, and I followed this guide mostly: https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6

My issue is when I run truffle migrate --network development as I've defined in truffle.js, it gives me the error in the title. I've also set gas in truffle.js to 5000000. I'm using testrpc.

## Steps to Reproduce

Follow this guide: https://blog.zeppelin.solutions/how-to-create-token-and-initial-coin-offering-contracts-using-truffle-openzeppelin-1b7a5dae99b6
Run truffle compile
Set up a testrpc network
Set gas in truffle.rpc to 5000000
Run truffle migrate

## Expected Behavior

Truffle migrate should complete without errors, and successfully deploy my Smart Contract to my testrpc network.

## Actual Results

It failed to run the command with this error:
`truffle migrate --network development
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts
Using network 'development'.
Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x0fcfb99e1aabd106464c74ab56180d086472d1bfb5955a55cbdef00cde55e31f
  Migrations: 0xfc2e6fbeacf68cfe910f02dfcc53a61db55777aa
Saving successful migration to network...
  ... 0xa80ecb06702cc81d525331c996d8039305e5335ab209d86803f314bdc92406ab
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying EonTokenCrowdsale...
  ... 0xbf89a4c6238feb52246f8c4ccad59bc2ebbe2ff2b08742f88c8daeb980aa0f0e
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/lib/node_modules/truffle/build/cli.bundled.js:329221:46)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:39618:25
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:331159:9
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:175492:11
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:70564:24)`

## Environment

* Operating System: Ubuntu 16.04 LTS
* Truffle version: 4.0.1
* Ethereum client: Testrpc?
* node version: 6.11.5
* npm version: 3.10.10
* Solidity Version: 0.4.18

**Comment by sputnik77** [comment]
You can also get this error message when trying to deploy an abstract contract. Perhaps you changed the signature of a function in any of your base contracts that could be "abstracting" the contract you are actually trying to deploy. So in fact, it may turn out to be not a matter of "checking your gas amount", as the error message suggests, but a matter of checking that you are not deploying an abstract contract.

**Comment by stone212** [comment]
@sputnik77 I am having this problem also.  Can you define what you mean by an "abstract contract"?

**Comment by sputnik77** [comment]
Have a look to documentation [here](http://solidity.readthedocs.io/en/develop/contracts.html#abstract-contracts)

**Comment by adrianmcli** [comment]
I'm getting this error as well. @NateDev100 did this ever resolve for you?

**Comment by NateDev100** [comment]
Nope :(

**Comment by adrianmcli** [comment]
@NateDev100 This helped me resolve my problem, not sure if it'll help you: https://github.com/trufflesuite/truffle/issues/660#issuecomment-343066784

**Comment by SSPgg** [comment]
I am also facing the same issue in truffle 4. While trying to migrate a basic ICO smart contract.

**Comment by microdesign** [comment]
Same here on: 

Truffle v4.1.0 (core: 4.1.0)
Solidity v0.4.19 (solc-js)

**Comment by ccpwcn** [comment]
I'm using the framework  zeppelin-solidity,  I have the same errors

and I have two contracts, one is extended CappedToken

`pragma solidity ^0.4.18;

import "../node_modules/zeppelin-solidity/contracts/token/ERC20/CappedToken.sol";

contract GustavoCoin is CappedToken {
    string public name = "GUSTAVO COIN";
    string public symbol = "GUS";
    uint256 public decimals = 2;
    uint256 public INITIAL_SUPPLY = 10000 * (10 ** decimals);

    function GustavoCoin() 
        public
        CappedToken(INITIAL_SUPPLY) {
    }
}`

And an other is crowd contract:
`pragma solidity ^0.4.18;

import "./GustavoCoin.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/Crowdsale.sol";
import "../node_modules/zeppelin-solidity/contracts/token/ERC20/StandardToken.sol";
// import "../node_modules/zeppelin-solidity/contracts/crowdsale/emission/MintedCrowdsale.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/validation/TimedCrowdsale.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/validation/CappedCrowdsale.sol";


contract GustavoCoinCrowdsale is Crowdsale, TimedCrowdsale, CappedCrowdsale {
    function GustavoCoinCrowdsale(
        uint256 _openingTime,
        uint256 _closingTime,
        uint256 _rate,
        uint256 _cap,
        address _wallet,
        StandardToken _token
    ) public 
    Crowdsale(_rate, _wallet, _token)
    TimedCrowdsale(_openingTime, _closingTime)
    CappedCrowdsale(_cap) {
    }
}`

deploy javascripts content:
`const GustavoCoin = artifacts.require('./GustavoCoin.sol');
const GustavoCoinCrowdsale = artifacts.require('./GustavoCoinCrowdsale.sol');

module.exports = async (deployer) => {
    // 设定参数，此处的参数即使传入合约构造方法的参数，与合约保持一致
    const beneficiary = '0xC0AE3D68Ce5df82aD0594B547Db6D5b2fbEFfaEd';
    const startTime = Math.round((new Date(Date.now() - 86400000).getTime())/1000); // Yesterday
    const endTime = Math.round((new Date().getTime() + (86400000 * 20))/1000); // Today + 20 days
    const rate = 100;
    const cap = 3000;
    const tokenAddress = '0x784dc9e81d2f8dcb8f960baf6384387fdbadc5f4';
    deployer.deploy(GustavoCoinCrowdsale, 
        web3.toBigNumber(startTime), 
        web3.toBigNumber(endTime), 
        web3.toBigNumber(rate), 
        web3.toBigNumber(cap),
        beneficiary,
        tokenAddress
    );
};
`

truffle version information:
Truffle v4.1.11 (core: 4.1.11)
Solidity v0.4.24 (solc-js)

error informations:
`Running migration: 4_deploy_contracts.js
  Replacing GustavoCoinCrowdsale...
  ... 0x931ea70ab49f385ddf0babc22053374a9b02bdcd66cfe75796a382822007bccd
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by microdesign** [comment]
@ccpwcn 

My deployment was changed in order to work as follow:

```
const startTime = Math.round((new Date(Date.now() - 86400000).getTime())/1000); // Yesterday
    const endTime = Math.round((new Date().getTime() + (86400000 * 28))/1000); // Today + 28 days
    var exchangeRate = 2500; // 1 LEON = 0.0025 ETH or 1 ETH = 2500 LEON

    return deployer
        .then(() => {
            return deployer.deploy(LeonardianToken);
        })
        .then(() => {

            return deployer.deploy(
                LeonardianCrowdsale,
                startTime,
                endTime,
                exchangeRate,
                "wallet adddress",
                LeonardianToken.address
            );
        })
        .then(() => {

            var token = LeonardianToken.at(LeonardianToken.address);

            token.transferOwnership(LeonardianCrowdsale.address);
        });
```

**Comment by ccpwcn** [comment]
@microdesign 
I have already modify my deploy scripts when I receivied your reply:
```
const GustavoCoin = artifacts.require('./GustavoCoin.sol');
const GustavoCoinCrowdsale = artifacts.require('./GustavoCoinCrowdsale.sol');

return deployer.then(() => {
    return deployer.deploy(GustavoCoin);
}).then(() => {
    // 设定参数，此处的参数即使传入合约构造方法的参数，与合约保持一致
    const beneficiary = '0xC0AE3D68Ce5df82aD0594B547Db6D5b2fbEFfaEd';
    const startTime = Math.round((new Date(Date.now() - 86400000).getTime())/1000); // Yesterday
    const endTime = Math.round((new Date().getTime() + (86400000 * 20))/1000); // Today + 20 days
    const exchangeRate = 100; // 1 GUS = 0.001 ETH or 1 ETH = 100 GUS
    const cap = 3000;
    return deployer.deploy(GustavoCoinCrowdsale, 
        startTime, 
        endTime, 
        exchangeRate, 
        cap,
        beneficiary,
        GustavoCoin.address
    );
}).then(() => {
    var token = GustavoCoin.at(GustavoCoin.address);
    token.transferOwnership(GustavoCoinCrowdsale.address);
});
```
BUT The script has a syntax error:
```
Running migration: 4_deploy_contracts.js
E:\code\solidity\tutorialToken\migrations\4_deploy_contracts.js:4
return deployer.then(() => {
^^^^^^

SyntaxError: Illegal return statement
    at Object.createScript (vm.js:80:10)
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-require\require.js:96:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by microdesign** [comment]
You miss some lines 


```
module.exports = function(deployer, network, accounts) {
    
    const startTime = Math.round((new Date(Date.now() - 86400000).getTime())/1000); // Yesterday
    const endTime = Math.round((new Date().getTime() + (86400000 * 28))/1000); // Today + 28 days
    var exchangeRate = 2500; // 1 LEON = 0.0025 ETH or 1 ETH = 2500 LEON

    return deployer
        .then(() => {
            return deployer.deploy(LeonardianToken);
        })
        .then(() => {

            return deployer.deploy(
                LeonardianCrowdsale,
                startTime,
                endTime,
                exchangeRate,
                "wallet",
                LeonardianToken.address
            );
        })
        .then(() => {

            var token = LeonardianToken.at(LeonardianToken.address);

            token.transferOwnership(LeonardianCrowdsale.address);
        });
};
```

**Comment by ccpwcn** [comment]
@microdesign 
Thank you very mush, your scripts is running well, and I still have an error, as a matter of fact, I've seen this mistake many times before, but I don't know why.
```
Running migration: 4_deploy_contracts.js
  Running step...
  Replacing GustavoCoin...
  ... 0x90e4ed09904ac9dc6f98dc60bd1d4833e41205e2142e493fcda0c457a28fa6d7
  GustavoCoin: 0x5657e26deed4899e34e57e66d7bd4f91e8fc802f
  Replacing GustavoCoinCrowdsale...
  ... 0x81c9640c7f1188c58fef21cc84b11c28641722082c3e287fd78566c56524ffc0
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
As you can see, Total two contracts, the first named ```GustavoCoin``` succeeded, but the second ```GustavoCoinCrowdsale``` failed.

This error is importent for me, Thank you very much for helping me solve these difficulties. Thank you again.

**Comment by microdesign** [comment]
@ccpwcn No problem - I`m happy you solve your problem. Good luck with what you going to build.

**Comment by ccpwcn** [comment]
@microdesign 

So, I sincerely ask you, what happened to my code that caused the following error?
```
Running migration: 4_deploy_contracts.js
  Running step...
  Replacing GustavoCoin...
  ... 0x90e4ed09904ac9dc6f98dc60bd1d4833e41205e2142e493fcda0c457a28fa6d7
  GustavoCoin: 0x5657e26deed4899e34e57e66d7bd4f91e8fc802f
  Replacing GustavoCoinCrowdsale...
  ... 0x81c9640c7f1188c58fef21cc84b11c28641722082c3e287fd78566c56524ffc0
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Thank you again for guiding me to solve these problems. Thank you.

**Comment by microdesign** [comment]
@ccpwcn  I cant see your full code maybe making a repo or something. And we can eventually be blocked by a version problem which I was having one time.

**Comment by microdesign** [comment]
I think you must remove Crowdsale

`contract GustavoCoinCrowdsale is Crowdsale, TimedCrowdsale, CappedCrowdsale {`

because CappedCrowdsale extends already the Crowdsale contract.

so write it this way 

`contract GustavoCoinCrowdsale is CappedCrowdsale, TimedCrowdsale {`

This is just a suggestion but lets try it

**Comment by ccpwcn** [comment]
@microdesign When I modified the codes:
```
pragma solidity ^0.4.19;

import "./GustavoCoin.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/Crowdsale.sol";
// import "../node_modules/zeppelin-solidity/contracts/token/ERC20/StandardToken.sol";
// import "../node_modules/zeppelin-solidity/contracts/crowdsale/emission/MintedCrowdsale.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/validation/TimedCrowdsale.sol";
// import "../node_modules/zeppelin-solidity/contracts/crowdsale/validation/CappedCrowdsale.sol";


contract GustavoCoinCrowdsale is TimedCrowdsale {
    function GustavoCoinCrowdsale(
        uint256 _openingTime,
        uint256 _closingTime,
        uint256 _rate,
        address _wallet,
        ERC20 _token
    ) public TimedCrowdsale(_openingTime, _closingTime) {
        rate = _rate;
        wallet = _wallet;
        token = _token;
    }
}
```
And deploy scripts:
```
const GustavoCoin = artifacts.require('./GustavoCoin.sol');
const GustavoCoinCrowdsale = artifacts.require('./GustavoCoinCrowdsale.sol');

module.exports = function(deployer, network, accounts) {
    const name = 'GUSTAVO TOKEN';
    const symbol = 'GUS';
    const totalSupply = 10000;
    return deployer.then(function () {
        return deployer.deploy(GustavoCoin,
            name,
            symbol,
            totalSupply
        );
    }).then(function () {
        // 设定参数，此处的参数即使传入合约构造方法的参数，与合约保持一致
        const beneficiary = accounts[0];
        const startTime = Math.round((new Date(Date.now() - 86400000).getTime())/1000); // Yesterday
        const endTime = Math.round((new Date().getTime() + (86400000 * 20))/1000); // Today + 20 days
        const exchangeRate = 100; // 1 GUS = 0.001 ETH or 1 ETH = 100 GUS
        return deployer.deploy(GustavoCoinCrowdsale, 
            startTime, 
            endTime, 
            exchangeRate, 
            beneficiary,
            GustavoCoin.address
        );
    }).then(function () {
        var token = GustavoCoin.at(GustavoCoin.address);
        token.transferOwnership(GustavoCoinCrowdsale.address);
    });
}
```
The errors still exists:
```
Running migration: 4_deploy_contracts.js
  Running step...
  Deploying GustavoCoin...
  ... 0x518b71dc716437ce149904aa496530889ad01c3de5cb4a88f0830d9faa2dabf5
  GustavoCoin: 0x1a61350cbf81eb4275cbcbed01d87f1288331899
  Deploying GustavoCoinCrowdsale...
  ... 0xb1386d791c4f3ce737c554e6f94905ff2f0a55e8a30a05d251eb4311dc3db422
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\web3\lib\web3\contract.js:147:1)
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\web3\lib\web3\method.js:142:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\web3\lib\web3\requestmanager.js:89:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-migrate\index.js:225:1
    at C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\.-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\mslw_\AppData\Roaming\npm\node_modules\truffle\build\webpack:\Users\gnidan\src\work\truffle\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
The truffle.js networks section:
```
development: {
      host: "127.0.0.1",
      port: 7545,
      from: "0xf3E57ab00bD9b225A1F35304F49eb812A2B6AD09",
      network_id: "*" // Match any network id
    }
```

**Comment by ccpwcn** [comment]
@microdesign Thank you very much, My question has been solved
```
pragma solidity ^0.4.19;

import "./GustavoCoin.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/Crowdsale.sol";
import "../node_modules/zeppelin-solidity/contracts/crowdsale/validation/TimedCrowdsale.sol";


contract GustavoCoinCrowdsale is Crowdsale, TimedCrowdsale {
    function GustavoCoinCrowdsale(
        uint256 _openingTime,
        uint256 _closingTime,
        uint256 _rate,
        address _wallet,
        address _tokenAddress
    ) public Crowdsale(_rate, _wallet, GustavoCoin(_tokenAddress)) TimedCrowdsale(_openingTime, _closingTime) {
    }
}
```

**Comment by microdesign** [comment]
@ccpwcn your code is not like I told you 

MY 
`contract GustavoCoinCrowdsale is CappedCrowdsale, TimedCrowdsale {`

YOUR
`contract GustavoCoinCrowdsale is TimedCrowdsale {`

**Comment by microdesign** [comment]
@ccpwcn OK happy to hear this.
