### ISSUE TITLE
After adding solc options in truffle configuration, contracts are not automatically recompiled

### ISSUE THREAD

**Issue by Jake-Gillberg** [trufflesuite/truffle#670]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Adding solc options in truffle configuration `truffle.js`, does not trigger a recompile of contracts upon `truffle migrate`.
## Steps to Reproduce

1. compile project
2. update `truffle.js` to toggle solc optimization
3. notice truffle migrate migrates contracts compiled in `1.`

## Expected Behavior

Just as when you edit a solidity file, the contract is recompiled upon `truffle migrate`, I expected the change in solc parameters to trigger recompilation of the project upon `truffle migrate`.

## Environment

* Operating System: Debian GNU/Linux 9
* Truffle version: 4.0.1
* Ethereum client: testrpc 6.0.1
* node version: 8.9.0
* npm version: 5.5.1

**Comment by tcoulter** [comment]
Hi there,

Truffle does not monitor for changes to your configuration file. It's theoretically possible, but not without excess engineering work for a small benefit. If you change your configuration and would like your contracts recompiled, run `truffle compile --all`. 

We'll reevaluate this if we can come up with a simpler solution with less drawbacks.

Cheers!
