### ISSUE TITLE
solidity in console works unpredictable.

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [trufflesuite/truffle#673]
Hello, mentioned below code does not add elements to the array.
```
pragma solidity ^0.4.0;


contract TestContract {
  struct TT {
  uint number;
  }

  TT  [] arr;

  function setT1(uint num) returns (uint result){
    TT t;
    t.number = num;
  
    arr.push(t);
    result = arr.length;

  }

  function getLen()returns (uint){
    return arr.length;

  }

  function getS(uint index) public returns (uint){
    return arr[index].number;
  }


}

```

**Comment by onetom** [comment]
Can you provide instructions about how are you testing it, please?

**Comment by vitaliy-kuzmich** [comment]
starting testrpc:
`testrpc -u 0 -u 1 -u 2 -u 3 -u 4 -u 5 -u 6 -u 7 -u 8 -u 9 --seed 0`
after entering console:
`truffle console`
declare  deployed contract :
`var t; TestContract.deployed().then(rs=>t = rs)`
Checking len:
` t.getLen.call()
BigNumber { s: 1, e: 0, c: [ 0 ] }`

Lets say I want to add few 100500 number to the arr variable in struct  of TT type:
```
truffle(development)> t.getLen.call()
BigNumber { s: 1, e: 0, c: [ 0 ] }
truffle(development)> t.setT1.sendTransaction(100500)
'0x87b5ff0be908ab933dc26573cb5a144a410727a80a229c289090e16ce78e4391'
truffle(development)> t.getLen.call()
BigNumber { s: 1, e: 5, c: [ 100501 ] }
truffle(development)> t.setT1.sendTransaction(100500)
'0xae68f34856c2621dcc67c2d11f59bd24b50b30584d110bc52f767ff40ba56d31'
truffle(development)> t.getLen.call()
BigNumber { s: 1, e: 5, c: [ 100501 ] }
truffle(development)> t.setT1.sendTransaction(100500)
'0xe7809b7ebd45accac1c3df64e3f66e76ce3db18cfcb460769e1f58605d5ee4ca'
truffle(development)> t.getLen.call()
BigNumber { s: 1, e: 5, c: [ 100501 ] }

```
for some reasons, it does weird impact on the length of the arr storage variable.

**Comment by philurlaub** [comment]
Same problem here!

**Comment by philurlaub** [comment]
Have a look at this example: http://solidity.readthedocs.io/en/develop/frequently-asked-questions.html#what-is-the-memory-keyword-what-does-it-do

**Comment by tcoulter** [comment]
Hi all,

This appears to be a question about Solidity. Although I'd love to help with Solidity issues, we have too many tickets open in order to debug each one.

I'd recommend you hop on over to the [Solidity gitter](https://gitter.im/ethereum/solidity/) and ask users there. I'm sure they'll be able to help debug. 

If you still believe this to be a Truffle issue, please open a new bug with a highly paired down version of the code that exposes the error. 

Thanks!
