### ISSUE TITLE
Create tutorial for deploying a smart contract to Ropsten

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#674]
At the end of the Pet Shop tutorial, there is a teaser about deploying to Ropsten. It's a good idea, so let's follow through with it.

Finished product will be a tutorial posted here: http://truffleframework.com/tutorials/

**Comment by jonnyhsy** [comment]
My truffle migration to ropsten network through infuro with hdwallet always hang on:
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ....0x.....

Step 2 is never reached and deployed, don't know how to fix this....

**Comment by bmmpxf** [comment]
Hi @jonnyhsy . Please create a separate ticket for your issue, including complete steps to reproduce, and we'll see what we can do. Thanks!

**Comment by skyh24** [comment]
so why do this happen？ wait for a long time, and i cannot see the contract on etherscan
