### ISSUE TITLE
Write easy-to-understand content about what a mnemonic is

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#675]
There isn't a good non-jargony description of what a mnemonic is that we can find.

The authoritative description is here: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

But that doesn't really help most people.

We should remedy this.

**Comment by onetom** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki actually has an image which gives some sense of the hierarchical nature of these accounts, but the concise description of what a mnemonic is can be found here: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

I haven't found any better documentation either.
