### ISSUE TITLE
JS test hangs when solidity method is named 'toString' 

### ISSUE THREAD

**Issue by dwalintukan** [trufflesuite/truffle#678]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have this utility function 
```
library ByteUtils {
    function toString(bytes32[10] _data) internal pure returns (string) {
        bytes memory allBytes = new bytes(10 * 32);
        uint length;
        for (uint i = 0; i < 10; i++) {
            for (uint j = 0; j < 32; j++) {
                byte char = _data[i][j];
                if (char != 0) {
                    allBytes[length] = char;
                    length++;
                }
            }
        }

        bytes memory trimmedBytes = new bytes(length + 1);
        for (i = 0; i < length; i++) {
            trimmedBytes[i] = allBytes[i];
        }

        return string(trimmedBytes);
    }
}
```
that hangs when trying to test. I created a wrapper mock class to test it since it is `internal`:
```
contract ByteUtilsMock {
    function toString(bytes32[10] _data) public pure returns (string) {
        return ByteUtils.toString(_data);
    }
}
```

Here is my test class:
```
contract('ByteUtils', function(accounts) {
    const blockHeightManager = new BlockHeightManager(web3);

    let instance;

    beforeEach(blockHeightManager.snapshot);
    afterEach(blockHeightManager.revert);

    beforeEach(async function() {
        instance = await ByteUtilsMock.new();
    });

    describe('toString', async function() {
        it('should return the string', async function() {
            var test = ["Who will be the next president i", "n the 2020 election?"];
            assert.equal(await instance.toString(test), test.join(''), 'test 2 does not match');
        });
    });
});
```

It just stops at this test and nothing happens after that (and eventually times out). Please note I have another contract/tests that uses `ByteUtils` directly as a library and those tests pass with no issues.

## Steps to Reproduce

Copy my utility function `toString()` and make a wrapper contract class. Then `truffle test`

## Expected Behavior

Test should pass and not hang.

## Actual Results

Doing `truffle test` all the other tests pass up to this test then it just hangs and stays there.

## Environment

* Operating System: Mac OSX 10.12.6
* Truffle version: 4.0.1
* Ethereum client: cpp-ethereum
* node version: 8.8.0
* npm version: 5.4.2

**Comment by onetom** [comment]
You said your ethereum client is cpp-ethereum, but you haven't mentioned its version or configuration.
You haven't mentioned your test setup in `truffle.js`, so I assume you are running against the built-in TestRPC (aka ganache-core) of Truffle, so the cpp-ethereum version and config is irrelevant.
But then I'm not sure why do you need that `blockHeightManager` gymnastics?
Truffle handles reverting the test chain between tests, but you have 1 test anyway.

**Comment by dwalintukan** [comment]
Yes I am using the Truffle's built-in TestRPC instance. You are right, I don't need the `blockHeightManager` for these tests. I do use it in other tests for simulating mining and increasing the block count.

I have removed the `blockHeightManager`, but regardless the test still hangs.

**Comment by cgewecke** [comment]
Hi @dwalintukan - I know this issue is from a while ago, apologies for the delay in responding.

I've reproduced this by naming any solidity function `toString` and trying to await it's resolution in javascript. Not sure what the mechanics of the hang are, but `toString` is a prototype property of JS objects so there's some kind of naming conflict here as we cross the boundary from one language to another. 

Hope you don't mind but I'm re-naming your issue to reflect the underlying problem.

**Comment by dwalintukan** [comment]
Ah I get the issue! Thanks for getting back to me. I can fix the tests accordingly 👍  Thank you @cgewecke

**Comment by Elaniobro** [comment]
Is this issue still open? I see it on [gitcoin.co](https://gitcoin.co/funding/details?url=https://github.com/trufflesuite/truffle/issues/678) but its marked closed by @dwalintukan

**Comment by dwalintukan** [comment]
@Elaniobro I've tested the fix and it works so it should be closed. I didn't create that one on gitcoin.co.
