### ISSUE TITLE
Truffle develop static network id interferes with MetaMask

### ISSUE THREAD

**Issue by pimotte** [trufflesuite/truffle#681]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using `truffle develop` a constant network id is used. When shutting down a truffle develop session, the transactions in the testrpc will disappear, but MetaMask will remember them. This will result in errors of the form: 'Error: tx doesn't have the correct nonce'. The corresponding MetaMask issue is here: https://github.com/MetaMask/metamask-extension/issues/1999

Unless there is a good reason to have the static network id, I feel it would be really useful to signal that the blockchain in question is a *different* blockchain, by virtue of it having a different network id (and possibly chain id).

## Steps to Reproduce

1. Unbox and start the react box using `truffle develop`.
2. Open localhost:3000 and Accept the transaction
3. Close `truffle develop` (make sure the process has stopped)
4. Run `truffle develop`, compile, migrate.
5. Open localhost:3000 and Accept transaction

## Expected Behavior

The transaction in step 5 succeeds, by virtue of no prior transactions being in MetaMask, because the second `truffle develop` generated a new network id.

## Actual Results

The transaction in step 5 fails, due to 'Error: tx doesn't have the correct nonce'

## Environment

* Operating System: Ubuntu 16.05
* Truffle version: v4.0.1
* Ethereum client: ---
* node version: v6.11.5
* npm version: 5.3.0

**Comment by robmyers** [comment]
Importing fresh seeds fills up Metamask with old addresses in my experience.

IMO it would be better for this to be fixed by Metamask as part of their nonce handling improvements.

**Comment by pimotte** [comment]
What do you mean with that first sentence? Reimporting the seed is a workaround?

In any case, the metamask issue says they are not looking to bend over backwards to detect differences between private networks. Doesn't it make sense to use a new network or chain id when you're starting from scratch?

**Comment by robmyers** [comment]
I tried it and importing a new seed doesn't work now. :-(

I just tried with a new network ID in Ganache and that doesn't work either.

Between testrpc and Ganache not working with Metamask without a complete reinstall, and failing in Mist with "Account not found" when trying to send transactions I'm not sure what to use to test UI.

**Comment by pimotte** [comment]
The MetaMask issue speaks of an undocumented chainId option in testrpc. Can we use that in Ganache to force MetaMask to re-read the transactions?

I'm of the opinion that this is actually an issue on both sides (i.e. truffle develop should be using random id's, unless pinned by an argument, and metamask should be caching less aggressively)

**Comment by tcoulter** [comment]
Hi all. 

Metamask is currently trying to fix this on their end. Bug here: https://github.com/MetaMask/metamask-extension/issues/1999

We believe their fix should be all that's needed. I'm going to close this ticket in favor of theirs. Cheers!

**Comment by wanderingstan** [comment]
Metamask has indefinitely postponed fixing this on their end: https://github.com/MetaMask/metamask-extension/issues/1999#issuecomment-354012719

For now, `truffle develop` with Metamask is a no-go, and I think the documentation should be updated:
http://truffleframework.com/docs/advanced/truffle-with-metamask#using-metamask-with-truffle-develop
