### ISSUE TITLE
Truffle serve, doesn't serve the app directory

### ISSUE THREAD

**Issue by bobmcdouble3** [trufflesuite/truffle#683]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I execute truffle serve, it says "Cannot get /" in the browser

## Steps to Reproduce

Truffle compile, migrate, then serve. App directory structure: 
app/
    --javascripts/
    --stylesheets/
    --index.html
## Expected Behavior

Serve the static webpage.

## Actual Results

Once visited in the browser, it prints "Cannot get /"

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: 3.2.1
* Ethereum client: testrpc
* node version: 8.1.4
* npm version: 5.3.0

**Comment by tcoulter** [comment]
Hi there, 

`truffle serve` is on its way out, as it was built a long time ago for a rigid, narrow build system (full disclosure, I wrote the code). If you're still using `truffle serve`, you should look into migrating your project to a more well supported build system. You can check out our [Truffle Boxes](http://truffleframework.com/boxes/) for some good examples.

Closing this ticket, as we're unlikely to make any more support for `truffle serve`. Cheers!
