### ISSUE TITLE
Compile within truffle development console provides wrong ABI

### ISSUE THREAD

**Issue by rhlsthrm** [trufflesuite/truffle#685]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

I am using the `truffle develop` console to run contract tests. When I change my contract code and re-run the test, it recompiles before the test, which sometimes generates an incorrect ABI. I get errors saying `Error: Invalid number of arguments to Solidity function`, and then when I check the ABI (in the `build/contracts` directory), I can see that it is messed up (wrong function inputs). If I exit the develop console and then run `truffle test` from the same directory, the proper ABI is generated in the build directory. Strange!

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

1. Create Solidity contract.
2. Run `truffle develop` to open console.
3. Use `compile` command from the console.
4. Sometimes, the wrong ABI will be generated.

## Expected Behavior

What you expected to happen.

Proper ABI is generated.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

Wrong ABI is generated.

## Environment

* Operating System: macOS High Sierra Version 10.13.1
* Truffle version: v4.0.1
* Ethereum client: truffle develop
* node version: v8.6.0
* npm version: 5.5.1

**Comment by onetom** [comment]
Deleting the `build` directory, then running `test` again without leaving the `truffle develop` console succeeds and allows continuing work without a console restart, but that's obviously not any better than running `truffle test` independently.

# Environment
Operating System: macOS Sierra 10.12.6
Truffle version: v4.0.1
Ethereum client: truffle develop
node version: v8.9.1
npm version: 5.5.1

**Comment by MacroChip** [comment]
@rhlsthrm @onetom Did either of you have more than one contract in a file? That may have been my issue (or it contributed).

**Comment by rhlsthrm** [comment]
@MacroChip yes I do have more than one contract in a file. It should still work though.

**Comment by MacroChip** [comment]
@rhlsthrm Yes it should but I was just trying to diagnose the issue. Try pulling each contract out to another file, deleting your build directory, `migrate --reset` and see if it is fixed.

**Comment by andiwinata** [comment]
Got the same issue, not just in `truffle develop` but also in `truffle console` while running `ganache-cli`.

So I downgraded my `truffle` to `4.0.0` and it has the correct ABI now, same to the one produced from  https://remix.ethereum.org

**Comment by rffl** [comment]
It seems like clearing the abi property from the generated contract.json file and recompiling also does the trick (for anyone who has network values they want to keep).  

I believe this repro'd for me when I made changes to a base class, and my inheriting class became corrupted.

**Comment by bitboyz** [comment]
@andiwinata 
How did you compare the remix ABI with the generated ABI? Where can I find both files, not sure where to look..

**Comment by bitboyz** [comment]
@rffl Should clearing the ABI and recompiling generate a new ABI in the JSON? Nothing changed for me..

**Comment by bijeebuss** [comment]
For me I can fix it by going into my artifact json file and deleting the abi section then running "truffle compile --all" . That way I don't lose other information by nuking the build folder

**Comment by bwheeler96** [comment]
@bijeebuss thanks for posting this. Maybe I can dig into the source later and find out where this bug is actually happening. I have a suspicion you have just cracked one of the bigger puzzles so far though

**Comment by bwheeler96** [comment]
@bijeebuss where is the artifact.json file?

**Comment by bijeebuss** [comment]
For example if i changed the contract called MyContract.sol I would go to build/contracts/MyContract.json and delete the abi section then recompile

**Comment by bwheeler96** [comment]
Oh... yeah that will do, but I wish that helped identify the part in the build process that gets messed up :(

**Comment by bijeebuss** [comment]
Yea its not much help for fixing it but at least that way you wont get your migrations all messed up by deleting the entire build folder

**Comment by saurfang** [comment]
Running `migrate --reset --all` seems to rewrite `build` directory for me so I was able to stay in `truffle develop` console.

**Comment by ericwooley** [comment]
I'm getting an old ABI as well, on 4.0.6

After running `truffle compile --all`, the abi is correct.

using truffle develop:

Sometime during `truffle migrate --reset --all` the ABI reverts to a different version of the contract. I don't know how or why, or where it's even pulling the old ABI from, but it's driving me insane.

I published my repo, here is my basic setup:
https://github.com/ericwooley/EtherAds/tree/516952316c1b2262d62e8e600b7dd3368d214c14/packages/ad-factory

with `compile --all`
https://github.com/ericwooley/EtherAds/blob/516952316c1b2262d62e8e600b7dd3368d214c14/packages/ad-factory/contracts/AdLogFactory.sol#L25 
is included in the file. 

after `migrate` it is reverted to some other state.

**Comment by ericwooley** [comment]
Tried this with the latest version, migrate is missing a bunch of the ABI.

**Comment by cgewecke** [comment]
@rhlsthrm Believe this is fixed with `4.1.5`. Please re-open if you continue see it happen.

**Comment by SvenMeyer** [comment]
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
I actually spent a couple of days researching why my JavaScript UI using web3  complains about non existing solidity functions, although they were there. I found that these function names were missing in the json.
I would have to reproduce this to provide further evidence unless somebody else has the same problem and can share some files.

**Comment by wbt** [comment]
I suspect this issue may be the same as the one reported [here](https://github.com/ethereum/solidity/issues/6977), with Truffle v5.0.14, especially the original report about wrong function inputs.  In that case, additional inputs were observed being copied up from three functions below, despite having not been there even in any previously compiled version of the contract.
