### ISSUE TITLE
Network id 4447 causes issues for signing transactions

### ISSUE THREAD

**Issue by ngan** [trufflesuite/truffle#687]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I seem to be having trouble signing transactions when the network id is 4447. Specifically, I'm using this library: https://github.com/se3000/ruby-eth. I'm not sure if the problem is with ruby-eth or what, but when I hack things and change the network_id to something small (e.g. anything between 1-100) everything works just fine. Just wondering why 4447 was chosen specifically.

## Environment

* Truffle version: 4.0.1

**Comment by tcoulter** [comment]
Hi @ngan. I'd bring this up with ruby-eth. It seems to me that you've identified a network id limit (i.e., between 1 and 100), although there's no spec defining 100 as the upper limit. 4447 isn't special in its own right, but it needs to be consistent; that said, we won't want it getting confused with an official chain, so the larger the better. 

I'm going to close this issue. Let me know if the response from ruby-eth. Cheers!
