### ISSUE TITLE
Contract Address / Network Information not written into artifacts when using web3 function in migration script

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/truffle#688]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In Truffle 4, the whole "networks": {} field stays empty, in Truffle 3, the address of the contract is not saved in the artifacts. Both resulting in the error "contract not deployed to this network" when calling it from the truffle console.

## Steps to Reproduce

**truffle.js**

```
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*', // Match any network id
      gas: 6500000
    }
  }
}
```

**2_deploy_contracts.js**
```
var blocknumber;

module.exports = function(deployer, network, accounts) {
  web3.eth.getBlock("latest", function(error, result){ 
    if (result) {
      blocknumber = result.number;
      var someValue = blocknumber + 20 ;
      deployer.deploy(MyContract, someValue);
    }})
};

```
## Expected Behavior

Contract artifacts are correctly created with all information neccessary to interact with the contract.

## Actual Results

As described above, in 3 the address is missing, in 4 the whole "networks" field. All works fine when added manually btw. 

## Environment

* Operating System: Ubuntu 16
* Truffle version: @3 / 4 latest
* Ethereum client: testrpc v6
* node version: Tested with 6.4 and 8.x
* npm version: 5.5.1

**Comment by tcoulter** [comment]
Hi @nikita-fuchs. Unfortunately there's no way the code above could work. Calling out to web3 makes the migration function asynchronous, and in your code you have no way of telling the migration system that your migration is finished. Side note here: Migrations only *stage* deployments at run time; they don't actually run the transactions immediately.

To tell the migration system that you'd like to do something asynchronous, you need to add a promise to the deployment chain. You can do this by using `.then()`: 

```
deployer.then(function() {
  return new Promise(function(accept, reject) {
    web3.eth.getBlock("latest", function(err, result) {
      if (err) return reject(err);
      accept(result);
    });
  })
}).then(function(block) {
  if (block) {
    // do your thing
    return deployer.deploy(...); // make sure to return here as that's a promise
  }
})
```

**Comment by tcoulter** [comment]
I'm going to close this issue. Let us know if you run into anything else!
