### ISSUE TITLE
Fine-tuned gasPrices during migration

### ISSUE THREAD

**Issue by robbiehanson** [trufflesuite/truffle#689]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

First, I'd just like to say: Thank you for an amazing project. I was really struggling with Ethereum development before I found Truffle. This is the first project I've found that puts everything together in a cohesive manner.

Question / Feature Request: Is there a way to control the gasPrice in a more fine-tuned way ?

From what I can tell, the only way to control the gasPrice is via the (one setting) in truffle.js, which will control the gasPrice for every operation within the migration. For example, if I'm deploying a single contract, then the single gasPrice would be used for:

- deploying the Migrations contract
- invoking Migrations.setCompleted(1)
- deploying my contract
- invoking Migrations.setCompleted(2)

It would be handy to be able to specify the gasPrice for each of these operations independently. For example, I would like to set the deployment of the Migrations contract to an average gasPrice. Since I know the contract is small, I know that won't cost very much. And I'd like to get it mined fairly quickly. I'd want to set the gasPrice for invoking Migrations.setCompleted() to a high gasPrice, since I know it will be cheap, and I'd like it to get mined very quickly. And then when deploying my own contract, which is much larger, I'd be interested in setting the gasPrice pretty low. I don't mind if it takes a long time, and I don't want to pay $25 for it.

**Comment by chuacw** [comment]
Robbie,

You can set gas price when deploying.
Here's my migration file, 1_initial_migration.js

var Migrations = artifacts.require("./Migrations.sol");
var Scream = artifacts.require("./Scream.sol");

module.exports = function(deployer) {
  deployer.deploy(Migrations, {gas: 800000, from: "0x...."});
  deployer.deploy(Scream);
};

**Comment by robbiehanson** [comment]
That's excellent news, thank you. However, the [documentation](http://truffleframework.com/docs/getting_started/migrations) didn't really explain this. (So I've submitted a pull request to update it.)

First, I saw this example:

```
// Deploy A, then deploy B, passing in A's newly deployed address
deployer.deploy(A).then(function() {
  return deployer.deploy(B, A.address);
});
```

Which I understood as: "OK, so the ARGS are for the contract, as it gets invoked during contract creation on the blockchain"

Then I saw this in the documentation:

    DEPLOYER.DEPLOY(CONTRACT, ARGS…, OPTIONS)
    Additionally, the last argument is an optional object that observes a single key, overwrite. If overwrite is set to false, the deployer won't deploy this contract if one has already been deployed. 

Which I understood as: "OK, so one can also pass an options object, which is just used by the deployer code to determine which path it should take."

If I'm understanding this correctly, you're saying that the `options` is actually used by both the deployer, and by the 'send transaction' stuff.

Here's the pull request I submitted to improve the documentation:
https://github.com/trufflesuite/trufflesuite.com/pull/35

**Comment by robbiehanson** [comment]
I just realized this doesn't really fix all the fine-grained options:

- deploying the Migrations contract  <- Fixed
- invoking Migrations.setCompleted(1) <- Not fixed
- deploying my contract  <- Fixed
- invoking Migrations.setCompleted(2) <- Not fixed

Is there a way I can specify the gasPrice when invoking `Migrations.setCompleted(x)` ?

**Comment by tcoulter** [comment]
Hi @robbiehanson. The Migrations contract -- and interacting with it -- is special to Truffle. Since Truffle performs the `setCompleted` calls during migrations, there's no way to set the gas price other than by setting it within your `truffle.js` file. That said, assuming you don't want different gas prices for calling `setCompleted(1)` and `setCompleted(2)`, you should now have all your bases covered; that's because any gas price set in the transaction (e.g., the gas price set when deploying your contract) will overwrite the gas price in the `truffle.js` file. 

I'm going to close this for now as you should have everything that you need. Cheers!
