### ISSUE TITLE
How to run Truffle application Using Ip?

### ISSUE THREAD

**Issue by rakibgalib** [trufflesuite/truffle#694]
i have developed an application like metacoin. It's running on my pc through localhost:8080.

How can i run this application trough ip address like 172.168.5.1:8080 ?

**Comment by wouterbruinings** [comment]
Your problem is unrelated to truffle. As you are speaking about metacoin I assume you are using webpack. Take a look at this: https://github.com/webpack/webpack-dev-server/pull/263

**Comment by tcoulter** [comment]
Thanks for the response @wouterbruinings. Closing for housekeeping.
