### ISSUE TITLE
Getting int256 upper than or equal to 2^252 seems to bug

### ISSUE THREAD

**Issue by vrolland** [trufflesuite/truffle#697]
## Issue

Trying to get an int256 from a contract don't return the good value

## Steps to Reproduce
Create a truffle project with this contract : 
```
pragma solidity 0.4.18;

contract Test {

    int256 public testSignedInteger;

    event Log(int256 testSignedIntegerBefore, int256 testSignedIntegerAfter, int256 amount );

    function addition(int256 _amount)
        external
    {   
        testSignedInteger = 0;
        
        int256 testSignedIntegerBefore = testSignedInteger;

        testSignedInteger = testSignedInteger + _amount;

        Log(testSignedIntegerBefore, testSignedInteger, _amount);
    }
}
```
and this test : 
```
var Test = artifacts.require("./Test.sol");
var BigNumber = require('bignumber.js');

contract('Test', function(accounts) {
	it("test", async function () {
		var test = await Test.new();

		var n = await test.addition(new BigNumber(2).pow(252).minus(1));
		console.log("------------------------");
		console.log("addition new BigNumber(2).pow(252).minus(1) ");
		console.log(n.logs[0].args);
		console.log("------------------------");
		console.log("------------------------");		
		var testSignedInteger = await test.testSignedInteger.call();
		console.log("testSignedInteger new BigNumber(2).pow(252).minus(1) ");
		console.log(testSignedInteger);
		console.log("------------------------");

		var n = await test.addition(new BigNumber(2).pow(252));
		console.log("------------------------");
		console.log("addition new BigNumber(2).pow(252)");
		console.log(n.logs[0].args);
		console.log("------------------------");
		console.log("------------------------");		
		var testSignedInteger = await test.testSignedInteger.call();
		console.log("testSignedInteger new BigNumber(2).pow(252)");
		console.log(testSignedInteger);
		console.log("------------------------");
	});
});
```

## Expected Behavior

The second "test.testSignedInteger.call();" should return :
> BigNumber {
>      s: 1,
>      e: 75,
>      c:
>       [ 723700,
>         55773322622139,
>         73186563042994,
>         24082937404160,
>         25352524660990,
>         494570602496 ] }

## Actual Results

It actually returns : 

> BigNumber {
>   s: -1,
>   e: 77,
>   c:
>    [ 10855508,
>      36599839332095,
>      97798445644913,
>      61244061062403,
>      80287869914850,
>      7418559037440 ] }

Beside, if I retrieve "testSignedInteger" by my own (script nodejs with web3@1.0.0-beta.24) : 
```
var testContractABI = [...];
var _contractInstance = new web3.eth.Contract(testContractABI, "0x6195590213bf0434450f2f61a90fb36597db4009");
_contractInstance.methods.testSignedInteger().call(function(err,data) {
	console.log(data);
});
```
I get the right value :
"7237005577332262213973186563042994240829374041602535252466099000494570602496"

## Environment

* Operating System: Windows10 (sadly..)
* Truffle version: Truffle v4.0.1 (core: 4.0.1)
* Ethereum client: EthereumJS TestRPC v6.0.3 (ganache-core: 2.0.2)
* node version: 8.9.0
* npm version:  5.5.1

**Comment by mryellow** [comment]
It seems to be in the conversion between `int256` and `BigNumber`. 

The number is correct inside Solidity however incorrect in CLI event log and Javascript.

An off-by-one here somewhere? Gets overflowed back to the negative end of the binary?

**Comment by mryellow** [comment]
Oh it passes because there are no assertions only logging.
