### ISSUE TITLE
I keep needing to clobber the build directory

### ISSUE THREAD

**Issue by bwheeler96** [trufflesuite/truffle#698]
- [ X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I get `Error: Invalid number of arguments to Solidity function`. Then I run `rm -rf build/contracts && truffle compile --all` and the issue is fixed.

## Steps to Reproduce

I'm working on this. I'll come up with a step to reproduce eventually, but for now this bug is pretty obtuse.

I've noticed it gets caused by method signatures getting jacked up in the contract `json` after certain solidity refactors

## Expected Behavior

Not having to manually clobber `build` to get working builds.

## Actual Results

`Error: Invalid number of arguments to Solidity function`

## Environment

* Operating System: OS X Sierra
* Truffle version: 4.0.1
* Ethereum client: testrpc/ganache
* node version: v8.6.0
* npm version: 5.6.0

**Comment by VoR0220** [comment]
Same exact friggin issue, except mine isn't even working after clobbering it.

**Comment by bwheeler96** [comment]
@VoR0220 try running `truffle compile --all` outside of the `truffle develop` console.

As for me, I got so sick of this shit I just created a whole new workspace with a truffle-independent build and test process. If you keep using truffle, get used to it

**Comment by tcoulter** [comment]
Hi all,

Thanks for the responses. We're currently working on fixing this issue.
Thank you for your patience.

Tim

**Comment by bwheeler96** [comment]
@tcoulter do you have any leads on the cause? I switch to a separate build process using `solc` and have had no issues of this sort. Truffle abstracts a lot of configuration away, and that is awesome, but this lack of determinism was a complete dealbreaker for the time being.

**Comment by VoR0220** [comment]
I actually realized in my case that Truffle was actually correct, I was actually passing in an undefined value...so that was actually good on its part.

**Comment by inflector** [comment]
Here is a reproducible case of contracts (with "build" directory) which have the problem, in case you don't have any:

[truffle bug.zip](https://github.com/trufflesuite/truffle/files/1547790/truffle.bug.zip)

Running `python3 test_agent_functions.py` will give you the error.

**Comment by gnidan** [comment]
@inflector Trying to reproduce using your zipfile - it seems I need `addresses.json`?

**Comment by gnidan** [comment]
Hello all, a bug that caused this problem has been fixed in v4.0.4.

Please upgrade and let us know if the problem persists for you! Thank you!

(Release notes: https://github.com/trufflesuite/truffle/releases/tag/v4.0.4)

**Comment by cgewecke** [comment]
Believe this is really fixed in `4.1.5`. Closing, please re-open if you see this again.
