### ISSUE TITLE
Docs mention a Solidity test included with truffle init which doesn't actually happen

### ISSUE THREAD

**Issue by JohnAllen** [trufflesuite/truffle#702]
See here: http://truffleframework.com/docs/getting_started/solidity-tests#example

Truffle init does not create that test.

**Comment by cgewecke** [comment]
Thanks for reporting this @JohnAllen - should be fixed in the docs with [this PR](https://github.com/trufflesuite/trufflesuite.com/pull/65). The MetaCoin project has migrated to its own box and is installed with: `truffle unbox metacoin`. 

`init` is just a clean, blank project template now.
