### ISSUE TITLE
.node-xmlhttprequest-sync-XXXX not being removed in case of CTRL+C

### ISSUE THREAD

**Issue by clesaege** [trufflesuite/truffle#703]
## Issue

When you run tests (truffle test) and want to stop them prematurely (generally if your tests are about multiple files and you've seen the results of the test in the concerned files), a .node-xmlhttprequest-sync-XXXX may stay in your repository and will not be deleted.
Since Truffle, have a "Terminate batch job (Y/N)?" when you CTRL+C, it would be better to have it terminating without cluttering the directory.

## Steps to Reproduce

Run truffle test, press CTRL+C when tests are running. Answer "y" to the "Terminate batch job (Y/N)?" prompt.

## Expected Behavior

It should clean the .node-xmlhttprequest-sync-XXXX when answering "y" to the prompt.

## Actual Results

Some .node-xmlhttprequest-sync-XXXX files stay in the directory and are never cleaned.

## Environment

* Operating System: Windows.
* Truffle version: 4.0.1
* Ethereum client: testrpc
* node version: 9.2.0
* npm version: 5.5.1

**Comment by tcoulter** [comment]
Good catch. Please see the comment I left [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1019#issuecomment-403171251)

Generally, if you're getting these files, it means you're using synchronous http requests, which is a no no. You shouldn't do that, for this effects and other reasons. Please check your code for synchronous requests and remove them.

If you see Truffle code that uses synchronous requests, please let us know.

**Comment by clesaege** [comment]
It seems to be fixed now. Anyone still having the issue?

**Comment by AndyWatt83** [comment]
I still see this occasionally. I've not been able to reliable reproduce.

**Comment by clesaege** [comment]
Yeah, this came back to me once. Now it seems to appear randomly (before it was systematic).
