### ISSUE TITLE
How to test modifiers or requires in Solidity tests? 

### ISSUE THREAD

**Issue by JohnAllen** [trufflesuite/truffle#708]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

How to test modifiers or requires in Solidity tests?  Otherwise things that throw -- how to catch errors in Solidity? 

Looked through this Assert library but didn't find anything.  

https://github.com/trufflesuite/truffle/blob/beta/lib/testing/Assert.sol

**Comment by cgewecke** [comment]
Hi @JohnAllen - apologies for the delay in addressing this interesting issue. One way to do this is to write a small fixture which executes methods that throw conditionally within Solidity as a `call`. For example, if Truffle's MetaCoin example looked like this:

```javascript
contract MetaCoin {
	uint maxSend = 5000;
        ... etc ...

       function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
		require(amount <= maxSend);
                ... etc ...
       }
}
``` 

You could test that `sendCoin` errors when `amount > 5000` using mocks in `TestMetcoin` as below:
```javascript
// A little utility that runs a wrapped method invocation as an internal Solidity call
// Returns true if the underlying call succeeds and false if it throws.
function execute(string signature) internal returns (bool){
    bytes4 sig = bytes4(keccak256(signature));
    address self = address(this);
    return self.call(sig);
  }
 
// Wrap the call to sendCoin. Wrapping lets you perform complex setups for arbitrarily 
// parameterized methods while keeping a simple function signature to pass to 
// `execute` above
function sendLimitExceeded() public {
    MetaCoin meta = MetaCoin(DeployedAddresses.MetaCoin());
    meta.sendCoin(address(0), 5500);
}

// Test the failure case
function testSendLimitExceeded() public {
   Assert.isFalse(execute('sendLimitExceeded()'), "Should be over limit");
}
```

There's a good discussion of `.call` at Ethereum StackExchange [here](https://ethereum.stackexchange.com/questions/8270/what-does-soliditys-call-function-mean). It might be helpful to add some notes about this topic to the advanced solidity testing documentation at Truffle.

**Comment by cgewecke** [comment]
There's also a link to a great [blog post](http://truffleframework.com/tutorials/testing-for-throws-in-solidity-tests) about this topic by Simon De La Rouviere in the [advanced solidity testing](http://truffleframework.com/docs/getting_started/solidity-tests#testing-for-exceptions) section of the docs. His approach is slightly different and more elegant than the one above - well worth a read. 

Closing because it looks like the docs cover this question.
