### ISSUE TITLE
Async/await test ISSUE vs promise chaining 

### ISSUE THREAD

**Issue by jorgeog96** [trufflesuite/truffle#709]
- [ Yes] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I´m trying to call a mapping variable from my contract: 

    mapping(address => uint[29]) balanceOf;

In order to get that, know that mapping can´t be returned, I´ve created my own getter function. 

    //TESTING purposes
    function getSlots() public returns (uint[]) {
        slots.length = 0;
        for(uint k = 0; k <= 28; k ++) {
            slots.push(balanceOf[msg.sender][k]);
        }
        return slots;
    }
    
However, when i´m calling that function on my test, works perfectly using promise chaining but doesn´t work if I use async/await. 
## Steps to Reproduce

1)Promise chaining (part of the code):

            return ovxet.getSlots.call({from: accounts[0]});
        }).then(function(balances) {
            console.log("Owner balance slots " + balances);

2)Returns me:

          Owner balance slots 1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

If I use the other way:

1)Async/await:

        var balanceArray = await instance.getSlots({from: accounts[0]});
        console.log(balanceArray);
2)Returns me:

{ tx: '0x709a622b9d10a1803cdbf4485670576e71a1778a7bc955a94661fedc7df0b212',
  receipt:
   { transactionHash: '0x709a622b9d10a1803cdbf4485670576e71a1778a7bc955a94661fedc7df0b212',
     transactionIndex: 0,
     blockHash: '0x54a1333857c7187ebc0fb359083a1d1bc63577344fe4985de03c5b1e1f515f0e',
     blockNumber: 127,
     gasUsed: 389349,
     cumulativeGasUsed: 389349,
     contractAddress: null,
     logs: [],
     status: 1 },
  logs: [] }

3)   I´ve also tried adding JSON.Stringify().tx javascript method...but returns:

                 undefined
## Expected Behavior

Owner balance slots 1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
in async/await code

## Actual Results

{ tx: '0x709a622b9d10a1803cdbf4485670576e71a1778a7bc955a94661fedc7df0b212',
  receipt:
   { transactionHash: '0x709a622b9d10a1803cdbf4485670576e71a1778a7bc955a94661fedc7df0b212',
     transactionIndex: 0,
     blockHash: '0x54a1333857c7187ebc0fb359083a1d1bc63577344fe4985de03c5b1e1f515f0e',
     blockNumber: 127,
     gasUsed: 389349,
     cumulativeGasUsed: 389349,
     contractAddress: null,
     logs: [],
     status: 1 },
  logs: [] }

or

Undefined

## Environment

* Operating System: Windows 10 using Ubuntu Subsystem for Windows
* Truffle version: v4.0.1
* Ethereum client: ganache-cli
* node version: v9.2.0
* npm version: v5.5.1

**Comment by pabloruiz55** [comment]
The problem is that you haven't marked your function as view/constant in solidity, so when you do `await instance.getSlots(.....)` without the .call(), Truffle assumes it is a transaction that intends to modify the state, so it executes it and gives you the transaction hash instead of the return value.

adding "view" to function getSlots() should fix it.

```
function getSlots() public view returns (uint[]) {
...
}
```

**Comment by jorgeog96** [comment]
You´re right using the second way can work without problems: 

        var balanceArray = await ovxet.getSlots.call();
        console.log(balanceArray.toString());

Don´t forget to add the .toString() to handle the BigNumber´s...
And also I´ve change the state of the mapping BalanceOf to public. 

Thanks!!
