### ISSUE TITLE
When running truffle JS tests against ganache-cli, it creates a new snapshot at the beginning of tests, but never reverts

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#710]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running truffle JS tests against ganache-cli, it creates a new snapshot at the beginning of tests, but never reverts.

## Steps to Reproduce

Haven't tried creating a minimal repro, but in my repo I presently have one JS test exercising a contract I've written. I'd think any trivial JS test which kicks off a transaction should exhibit this behavior.

## Expected Behavior

Given that I write JS tests using `contract` and `it` statements and run them against ganache-cli, 

1. `truffle test` should make the RPC call `evm_snapshot` before running a `contract` block
2. `truffle test` should make the RPC call `evm_revert` once testing is completed for a `contract` block.

## Actual Results

1. `truffle test` did make the RPC call `evm_snapshot` before running a `contract` block
2. `truffle test` **did not** make the RPC call `evm_revert` once testing is completed for a `contract` block.

## Environment

* Operating System: OS X High Sierra
* Truffle version: v4.0.1
* Ethereum client: ganache-cli v6.0.3
* node version: v9.0.0
* npm version: 5.5.1

**Comment by tcoulter** [comment]
Looks like it makes a revert if there are new tests to run: https://gist.github.com/tcoulter/d68342811e64bd3d111df2cf038f7d58

**Comment by tcoulter** [comment]
(search in page for `evm_revert`)
