### ISSUE TITLE
Getting VM Exception when running any test

### ISSUE THREAD

**Issue by stefanionescu** [trufflesuite/truffle#711]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Got a nasty bug when testing any contract with or without ganache-cli.

## Steps to Reproduce

Using even a simple test like this:

https://gist.github.com/stefanionescu/fa935d9d55927f8fee40fdcc4812774b

I get a VM error.

## Expected Behavior

The test used to work two weeks ago but now it doesn't.

## Actual Results

I always get the error "Error: VM Exception while processing transaction: revert" when I run any test.

## Environment

OS: Win 7
Node version: 8.7.0
Truffle: 4.0.1
Ganache: 6.0.3
npm: 5.6.0

**Comment by JackPickering** [comment]
Is your start block specified as a block in the past? Usually this error comes from a revert in your contracts constructor.

I.e. require(startBlock > currentBlock);

**Comment by cgewecke** [comment]
@stefanionescu This issue has been open for a while and looks like it's specific to your crowdsale implementation rather than something going wrong at Truffle as such. Closing for house-keeping but please feel free to re-open if you continue to have problems with this. Thanks!
