### ISSUE TITLE
JavaScript test finishes before all futures are completed

### ISSUE THREAD

**Issue by fabricetriboix** [trufflesuite/truffle#712]
- [Yes] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

JavaScript test in the form of 

        Dummy.deployed().then(function(instance) {
            dummy = instance;
            return web3.eth.getBalance(address);

        }).then(function(balance) {
            balance_before = balance;
            console.log("Balance before:", balance.toString());
            return dummy.store({from: address, value: amount});

        }).then(function(result) {
            console.log("'store' transaction finished; tx=", result.tx);
        });
        console.log("First test finished");

Finishes before all the futures are completed.

## Steps to Reproduce

Download the attached toy example tarball and:

    $ tar xf eth-dummy.tar.gz
    $ cd eth-dummy
    $ truffle develop
    truffle(develop)> compile
    truffle(develop)> test

## Expected Behavior

First, all futures finishes, then the test itself finishes.

## Actual Results

Test finishes before all futures are completed. This is what I can see on my machine:

```
eth-dummy$ truffle develop
Connected to existing Truffle Develop session at http://localhost:9545/

truffle(develop)> compile
Compiling ./contracts/Dummy.sol...
Compiling ./contracts/Migrations.sol...
truffle(develop)> Writing artifacts to ./build/contracts

truffle(develop)> test
Using network 'develop'.



  Contract: Dummy
First test finished
    ✓ Should send and get 10 Ether
Balance before: 59420666200000000000


  1 passing (205ms)

truffle(develop)> 'store' transaction finished; tx= 0x9eb93861f0a70155fb6700d777a443796fb9d6a00cc115f2959a45170aa3c0b7
```

## Environment

* Operating System: Fedora 27
* Truffle version: Truffle v4.0.1 (core: 4.0.1), Solidity v0.4.18 (solc-js)
* Ethereum client: truffle develop
* node version: N/A
* npm version: 5.5.1
[eth-dummy.tar.gz](https://github.com/trufflesuite/truffle/files/1553111/eth-dummy.tar.gz)

**Comment by cgewecke** [comment]
@fabricetriboix Hi. Here's a [guide](http://tobyho.com/2015/12/16/mocha-with-promises/) to using asynchronous methods in Mocha. I think you should be able to get the correct execution if you return the promise to mocha, as below:

```javascript
it('waits for everything to resolve', function(){
  return myAsyncMethod().then(function(){
      return anotherAsyncMethod().then( .... etc .. 
})
``` 

Another approach is to use Mocha's `done` function, which can be passed to the test like this:
```javascript
it('waits for done to be called', function(done){
  myAsyncMethod().then(function(){
     console.log('hello!');
     done();
  });
})
```

**Comment by cgewecke** [comment]
@fabricetriboix Closing this for housekeeping, it's been open a while. Please feel free to re-open if you're still seeing this problem. Thanks!
