### ISSUE TITLE
Using typescript for migrations

### ISSUE THREAD

**Issue by stpoa** [trufflesuite/truffle#717]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

How to make truffle migration using ts-node without transpiling to JavaScript?

**Comment by Xaber20110202** [comment]
I tried a way is like that:
```
./node_modules/ts-node/dist/bin.js /Users/XXXXX/.nvm/versions/node/v9.3.0/bin/truffle migrate --network kovan
```

But the specific thing is that truffle.js or truffle.config.js must be a js file.

So, we need to add a field `allowJs: true` to `tsconfig.json`
