### ISSUE TITLE
artifacts.require not detecting files in tests 

### ISSUE THREAD

**Issue by kc1116** [trufflesuite/truffle#730]
## Issue

Whenever i run truffle tests some .sol files from installed projects are not found even though they are there. I npm install a truffle project, then use artifacts.require to use a contract from that project in my tests but I always get the Could not find artifacts error. artifacts.require works fine when I run truffle compile and truffle migrate.
## Steps to Reproduce
Open a truffle project. 
Npm install a different truffle project
Use artifacts.require in a test to get access to that modules contract

## Expected Behavior

Contract to be required properly
## Actual Results

Error: Could not find artifacts for BadgeLibrary/contracts/Verifier.sol from any sources

## Environment

* Operating System: MacOS Sierra
* Truffle version: 4.0.4
* Ethereum client: ganache-cli
* node version: 8.5
* npm version: 5.3.0

**Comment by kc1116** [comment]
After adding some console logs to the cli build file inside the Resolver.prototype.require function I can see truffle creates some directories under /var/folders/ I inspected these directories and it looks liek the json ABI file I need is inside one of them but the require function is getting called with the seatch_path of one of the directories that does not contain that specific json file. How does truffle decide to put json files where ?

**Comment by kc1116** [comment]
I am getting the same problems with truffle compile now, when trying to import this module that artifacts.require can not find.

**Comment by cgewecke** [comment]
@kc1116 Apologies for the delay in responding. Truffle only generates artifacts for contracts in the `contracts` folder and (when running `truffle test`) the `test` folder. It's common to `npm install` projects like zeppelin-solidity in order to import base contracts into your own solidity files as below:
```javascript

// Sample import statements in a Solidity file located at: contracts/<filename>.sol
import "../node_modules/zeppelin-solidity/contracts/Bounty.sol";

// This would also work:
import "zeppelin-solidity/contracts/Bounty.sol";
```

If you'd like to access the installed contracts directly, you could move them to the `contracts` folder after you download them from npm. 

Closing for housekeeping - please re-open if I've misunderstood your issue, or if you're still facing difficulties with this.

**Comment by kc1116** [comment]
Hi @cgewecke  I will not re-open but I don't think truffle behaves that way. When I use the import statement you have above truffle will indeed create a .JSON ABI file for the Bounty.sol. If I wanted to artifact.require the Bounty.sol file it should work. But sometimes it does not.

**Comment by kunalb16** [comment]
I have the same issue as pointed by  @cgewecke. Truffle test does not work with contracts outside the contracts folder. 
I am having the same behaviour and i don't think his hack should be the best way to solve this. 

This error comes only when using "truffle test", but not with "truffle deploy". 


// Sample import statements in a Solidity file located at: contracts/<filename>.sol
import "../node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol";

**Comment by kunalb16** [comment]
And I have created the tests using solidity http://truffleframework.com/docs/getting_started/solidity-tests

**Comment by cgewecke** [comment]
@kunalb16 Could you provide a little more detail? 
+ In your file system, where is the contract which contains the import statement?
+ Where is the contract you want to import?

**Comment by kunalb16** [comment]
So my Project folder looks like:
Project
--node_modules/zeppelin/contracts/ownable.sol
--TruffleInitFolder/contracts/mycontract.sol //This contract has reference to the ownable contract via "../../node_modules/zeppelin/contracts/ownable.sol"
--TruffleInitFolder/test/Test_mycontract.sol

Now, when I use truffle test, it fails. But, truffle deploy is working flawlessly.

I get the error
"before all" hook: prepare suite for "should assert true"

**Comment by kunalb16** [comment]
Just tested by moving the zeppelin folder within the contracts folder and the tests run. So there is definitely a bug.

**Comment by cgewecke** [comment]
@kunalb16 - below is a typical file structure for a truffle project:
```
contracts /
  - KunalbToken.sol
  - KunalbSafeMath.sol
node_modules /
  - zeppelin-solidity /
test /
  - etc
truffle.js
```

If your project is organized in this way, you don't even need to use relative paths to access files installed with NPM (or EthPM). Truffle will resolve their location for you. So:
```javascript
import "zeppelin-solidity/contracts/Bounty.sol"; // <-- Works
```
Could you check your paths? `node_modules/zeppelin/contracts/ownable.sol` is not the path to Ownable.sol at Zeppelin. It's stored under the `ownership` folder and the first letter of the file is capitalized.

**Comment by kunalb16** [comment]
Well that was a good explanation, that helped me debug why my tests were failing and find a fix.
Takeaway,
Truffle test work only if you have a contract inside truffle root directory

So if you are using zeppelin-contracts. Make sure they are installed in truffle root directory, if you are using workspaces in yarn and truffle directory is one of your several workspaces, there is a no-hoist feature in yarn/learna that can help you do that.

**Comment by raininja** [comment]
I'm having this issue and I am using the standard file setup.  Is there some other error that would cause this behavior?


```
contracts /
  - MIgrations.sol
  - bContract.sol
node_modules /
  - openzeppelin-solidity /
truffle.js

**Comment by cgewecke** [comment]
@kc1116 If you have a chance could you post the import paths in your code as well?

**Comment by cgewecke** [comment]
@raininja  If you have a chance could you post the import paths in your code as well?
