### ISSUE TITLE
Contracts not Compiling

### ISSUE THREAD

**Issue by sarthakmis** [trufflesuite/truffle#731]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

On running **truffle compile** within the project folder, where the contracts are present, it shows error stating "ENOENT: no such file or directory, stat 'G:\contracts'
    at Error (native)"

## Expected Behavior

Successful Compilation

## Actual Results

ENOENT: no such file or directory, stat 'G:\contracts'
    at Error (native)

## Environment

* Operating System: Windows 10 
* Truffle version:4.0.1
* Ethereum client:Mist
* node version:6.11.1
* npm version: 5.4.0

**Comment by Remi-Burgel** [comment]
Hi, could you share the code that does not compile please ?

**Comment by cgewecke** [comment]
Hi @sarthakmis! And thanks @Remi-Burgel! 

Closing because there's too little information in this issue to know what's causing the problem here. @sarthakmis please feel free to reopen if compilation still isn't working for you.
