### ISSUE TITLE
No matching version found for require-from-string@^1.1.0 on npm install

### ISSUE THREAD

**Issue by MaxBlaushild** [trufflesuite/truffle#739]
## Issue

I am unable to npm install truffle globally. When I try, I receive the error: 'No matching version found for require-from-string@^1.1.0'

My npm version: 5.6.0
My node version: 7.6.0

## Steps to Reproduce

1. Set npm version to 5.6.0
2. Set node version to 7.6.0
3. Run 'npm install -g truffle'

## Expected Behavior

I would expect Truffle to install globally

## Actual Results

I receive the error message listed above

## Environment

* Operating System: Sierra
* Truffle version: N/A
* Ethereum client: N/A
* node version: 7.6.0
* npm version: 5.6.0

**Comment by emaG3m** [comment]
I'm getting this too. seems to be coming from solc, full error:

```
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/ecwilliams/.nvm/versions/node/v6.11.3/bin/node" "/Users/ecwilliams/.nvm/versions/node/v6.11.3/bin/npm" "install" "truffle"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'solc'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ecwilliams/npm-debug.log
```

**Comment by tovinayv** [comment]
Facing same issue
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/node" "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/npm" "--registry" "http://build-artifactory.eng.vmware.com:80/artifactory/api/npm/npm" "i"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

**Comment by matiasmansilla1989** [comment]
I was facing the same issue yesterday but it's working ok now.

**Comment by cgewecke** [comment]
Thanks @MaxBlaushild! Looks like this was a dependency issue at solc-js and has been [resolved there](https://github.com/ethereum/solc-js/issues/175). 

Closing for house-keeping. Please re-open or comment if you still see this error.
