### ISSUE TITLE
react-auth-truffle  invalid json rpc response: ""

### ISSUE THREAD

**Issue by pascal1990** [trufflesuite/truffle#742]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

- install the truffle react-auth-truffle Unbox
- configuratre the truffle.js 
module.exports = {
  migrations_directory: "./migrations",
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
 
I using "ganache-cli" on the same port, but I try to downloag "geth.exe --rpc" and run on the same port 8545 but still not workin

// Get current ethereum wallet.
I thinks the problem was here in this function 
web3.eth.getCoinbase((error, coinbase) => {
        // Log errors, if any.
        if (error) {
          console.error(error);
        }

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

the login and signup should work 

What you expected to happen.

## Actual Results : inside the console

Error: Invalid JSON RPC response: ""
Stack trace:
InvalidResponse@http://localhost:3000/static/js/bundle.js:54327:17
HttpProvider.prototype.sendAsync/request.onreadystatechange@http://localhost:3000/static/js/bundle.js:59498:26
SignUpFormActions.js:27
Error: Invalid JSON RPC response: ""
errors.js:35

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: windows 
* Truffle version: last version
* Ethereum client:
* node version:
* npm version:

**Comment by nikhilshekhawat** [comment]
Inside utils/getWeb3.js change line 24 to: (edited)
var provider = new Web3.providers.HttpProvider(‘http://127.0.0.1:8545’)

There is a typo there for the port number

**Comment by cgewecke** [comment]
@pascal1990 Apologies for the delay responding to this issue. I'm going to close this and re-open it at the `react-auth-box` repository [here](https://github.com/truffle-box/react-auth-box/issues/33) where other people using the box can find it. We'll try to address it there.
