### ISSUE TITLE
Never failing Solidity unit testing 

### ISSUE THREAD

**Issue by GNSPS** [trufflesuite/truffle#745]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Solidity unit testing in Truffle doesn't work (no tests fail) unless you invoke any method of Truffle's `Assert` library.

Found this while doing unit testing with an assertion library of my own which complies with Truffle's `TestEvent` firing.

## Steps to Reproduce

Run the tests from this repo: 

https://github.com/GNSPS/solidity-bytes-utils

But remove this line:

https://github.com/GNSPS/solidity-bytes-utils/blob/master/test/TestBytesLib1.sol#L45

Which is the fix for the affliction I mentioned.

## Expected Behavior

For the test to run independent of calling a method from `Assert.sol`

## Actual Results

All tests were passing irregardless of wether they were firing false `TestEvent`s or not.

## Environment

* Operating System: macOS
* Truffle version: 4.0.4
* Ethereum client: ganache-cli
* node version: 8.9.1
* npm version: 5.6.0

**Comment by cgewecke** [comment]
Hi @GNSPS. It seems like the underlying issue might be a quirk relating to `libraries` and `events`.  Everything about the way `AssertBytes` mimics Truffle's `Assert` is correct and seems like it should work. 

However, if the only defined `TestEvent` is located in a library, the transaction result that Truffle inspects for failing event logs always has an empty logs arrary.  The events fire but they aren't decoded at the `web3` level, which is what Truffle expects. 

Jorge Izquierdo at Aragon has written a nice Medium [post](https://blog.aragon.one/library-driven-development-in-solidity-2bebcaf88736) about libraries and says there:
> as of right now, the contract ABI does not reflect the events that the libraries it uses may emit. This confuses clients such as web3, that won’t be able to decode what event was called or figure out how to decode its arguments.

> There is a quick hack for this, defining the event both in the contract and the library will trick clients into thinking that it was actually the main contract who sent the event and not the library.

So one fix would be to additionally define `TestEvent` in the test suite contracts, which would allow you to remove the fake test. If that solution works for you, maybe we should rename this issue a little - it's an unexpected problem that other people might run into as well.

**Comment by cgewecke** [comment]
Looking at this more i wonder if linking the AssertBytes library and the test suite contracts in a migrations step is what really needs to be done here. The comment above has the glaring flaw that Assert is also a library, so . . . why does it work ok?

**Comment by cgewecke** [comment]
@GNSPS This should be fixed in the latest release. Please re-open if continue to see this problem, or the patch doesn't work for any other reason. Thanks!

**Comment by GNSPS** [comment]
Thank you so much @cgewecke!! 🙌 And sorry for the delay in the response! Appreciate your prompt response!
