### ISSUE TITLE
Outdated truffle documentation in README.md (also npm website)

### ISSUE THREAD

**Issue by didac-pf** [trufflesuite/truffle#751]
## Issue

Outdated documentation in npm website

## Steps to Reproduce

Go to https://github.com/trufflesuite/truffle or https://www.npmjs.com/package/truffle

## Expected Behavior

See **ganache** package named instead of old **testrpc**

## Actual Results

**testrpc** is named instead of its new name **ganache**

**Comment by TedtheDev** [comment]
I saw some pull requests that I think resolve this issue. 

These are the two that I found:
1. https://github.com/trufflesuite/truffle/pull/776
2. https://github.com/trufflesuite/truffle/pull/813

I don't know how to link PR's but I think that would be helpful for someone that is looking to work on this issue or an update. Is this correct?

**Comment by cgewecke** [comment]
@TedtheDev Thanks! I think we'll pull in #813 today and schedule it for the next patch release - There was some discussion there last week about how it should be worded and we were waiting for the opener to respond. But this is important so . . .

**Comment by TedtheDev** [comment]
@cgewecke Awesome! Saw that one had more discussion.

**Comment by cgewecke** [comment]
Fixed with #813 thanks to @robinboening.
