### ISSUE TITLE
using pragma experimental ABIEncoderV2 throws syntax error when running truffle test

### ISSUE THREAD

**Issue by vdrg** [trufflesuite/truffle#753]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using `pragma experimental ABIEncoderV2;` works when running `truffle compile`, but when running `truffle test` it doesn't (Syntax Error).

## Steps to Reproduce

Create any contract and add `pragma experimental ABIEncoderV2` after `pragma solidity...`. Then run `truffle test`.

## Expected Behavior

It should run the tests with no errors.

## Actual Results
```
SyntaxError: Expected "solidity", comment, end of line, or whitespace but "e" found. Line: 2, Column: 8
    at peg$buildStructuredError (/home/vdrg/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:293559:12)
    at Object.peg$parse [as parse] (/home/vdrg/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:306145:11)
    at Object.parse (/home/vdrg/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:306198:23)
    at /home/vdrg/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:203866:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```
## Environment

* Operating System: Arch Linux
* Truffle version: 4.0.4
* Ethereum client: integrated truffle client
* node version: 9.4.0
* npm version: 5.6.0

**Comment by cgewecke** [comment]
@vdrg Hi. There's a [pending fix](https://github.com/trufflesuite/truffle-core/pull/89) for this bug - Solidity files in the `test` directory are being parsed by an older parser. Probably the file you want to run is test written in Solidity, but if not you could move it to the `contracts` folder and it should compile ok there. 

Sorry about this - should be resolved in one of the upcoming releases.

**Comment by vdrg** [comment]
Yes, it is a file in the test dir, thanks! Feel free to close this.

**Comment by cgewecke** [comment]
Ok thanks @vdrg.
