### ISSUE TITLE
No clean room environment between tests when using Parity

### ISSUE THREAD

**Issue by yondonfu** [trufflesuite/truffle#760]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

According to http://truffleframework.com/docs/getting_started/testing#clean-room-environment, when running against Ethereum clients like Geth or Parity, Truffle should re-deploy all of a project's migrations at the beginning of every test file to ensure each test file starts with clean contract state. In practice, when running a test suite with multiple test files, I am not seeing state being reset via a re-deploy between test file runs when using Parity. The tests run fine with ganache-cli.

The project for reproducing is here: https://github.com/yondonfu/truffle-clean-room-repro. The contract is `contracts/Hello.sol` and the tests are in `test/integration`.

## Steps to Reproduce

1. `docker pull livepeer/parity-dev`
2. `docker run -d -p 8545:8545 --name parity-dev livepeer/parity-dev`
3. `git clone http://github.com/yondonfu/truffle-clean-room-repro`
4. `cd truffle-clean-room-repro`
5. `truffle compile`
6. `truffle test --network parity`

## Expected Behavior

All tests should pass.

## Actual Results

The test in `Hello2.js` fails. The test checks if `foo` is set to 0. If the contract was re-deployed and the test file started with clean contract state, `foo` should be 0. However, `foo` is instead 5 which is the value it was set to in `Hello1.js`

If I instead use Truffle's built-in development chain by running `truffle test`, all the tests pass.

## Environment

* Operating System: Mac OSX
* Truffle version: Truffle v4.0.1 (core: 4.0.1)
* Ethereum client: Parity
* node version: v8.5.0
* npm version: 5.3.0

**Comment by benjamincburns** [comment]
> The tests run fine with ganache-cli
What version of ganache-cli are you working with?

**Comment by yondonfu** [comment]
ganache-cli v6.0.3

And just to clarify the tests run fine both when using ganache-cli and when using Truffle's test blockchain environment. The lack of clean room environment seems to just be for other clients like Parity

**Comment by cgewecke** [comment]
Thanks so much @yondonfu! Your fix for this published with `4.0.6`.
