### ISSUE TITLE
JS promises not always rejected when require()/assert() conditions not met.

### ISSUE THREAD

**Issue by rickbatka** [trufflesuite/truffle#761]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have a reproducible example of a contract with 2 functions with require() clauses as their first line of code. I call the 2 functions one after another from my js tests. If the conditions are not met for the first require(), the promise is rejected (as expected) and I can access the rejected promise to see what went wrong. However, if I pass the first function's require() test, and subsequently fail the second one, I can see that the second method is not executed - **but the promise is not rejected.** It seems dependent on there being multiple calls to functions with require() or assert(), because in my tests if I comment out one or the other, the behavior works as expected and then one that remains will cause a promise rejection.

See my attached example project. Relevant code snippets below.

As I understand it, truffle js tests should reject promises if the web3 call results in a thrown exception. Am I wrong? Is there some place where this behavior is thoroughly documented?

## Steps to Reproduce

Relevant snippets from attached project:

**Contract definition**:
```
...
function TruffleBug() public payable {
        require(msg.value > 0);
        owner = msg.sender;
    }

    function doSomethingForMoney() public payable returns (bool) {
        require(msg.value > 0);
        return true;
    }

    function ownerDoSomething() public payable returns (bool) {
        require(msg.sender == owner);
        return true;
    }
...
```

**One of the failing test cases**:
```
 ...
it('FAILURE CASE 2: illustrates another example where "require" is ignored', async function(){
        let tb1 = await (TruffleBug.new({value: 1, from: accounts[0]}));
        assert.equal(1, web3.eth.getBalance(tb1.address));

        let workHappened = false;
        let thrown = false;
        try{
            // SHOULD throw, because we are not the owner
            workHappened = await tb1.ownerDoSomething({value: 1, from: accounts[1]});
        } catch (e) {
            thrown = true;
        }
        // balance is still 1, because the call to tb1.ownerDoSomething() failed and the funds were refunded...
        assert.equal(1, web3.eth.getBalance(tb1.address));

        // Incorrect behavior, test fails - ... the promise was not rejected, despite the rollback.
        assert.isTrue(thrown);
    });
...
```

## Expected Behavior

If a require() or assert() condition is not met and a rollback occurs, I expect the JS promise to be rejected.

## Actual Results

If multiple require() or assert() calls happen one after another, _and the first one passes_, the subsequent ones won't trigger a promise rejection even when the function calls are rolled back / refunded.

Please see attached project. First test case illustrates expected behavior working correctly, second and third cases illustrate what happens when multiple functions with require() are called back to back and the first passes, but the second fails.

## Environment

* Operating System: Windows 10
* Truffle version: 4.0.5
* Ethereum client: Ganache
* node version: 8.9.1
* npm version: 5.5.1
[truffle-bug.zip](https://github.com/trufflesuite/truffle/files/1657040/truffle-bug.zip)

**Comment by cgewecke** [comment]
@rickbatka Hi, thank you for providing such an easy way to reproduce this issue. Unfortunately, when I run your code on Truffle `4.0.5` using the `truffle test` command, it behaves as expected - e.g `thrown` is set to true in the example above. All the tests in the zip file pass. 

How are you executing the tests?

**Comment by rickbatka** [comment]
Hmm, I’m just running “truffle test” (on windows, using ganache). Is there
anything else that might factor into it, besides truffle version? What
about solidity compiler version? I noticed there is a newer minor version
than what I was using, maybe tomorrow I will try updating that and see if I
get the same results.

**Comment by cgewecke** [comment]
@rickbatka if you've been running the ganache beta recently it's possible you would see this behavior, although I believe the latest version would pass your tests. Ganache has added a mode that replicates the way the geth and parity report errors and there's been a little uncertainty about how to manage that at Truffle / set the defaults at ganache.

**Comment by rickbatka** [comment]
Thanks @cgewecke for taking the time to look into this! Sure enough, changing Ganache versions fixed it.

Hopefully this helps any Googlers out there running into the same problem:

**Problem:** Promises intermittently not being rejected (exceptions not being thrown) when require() or assert() conditions are not met. 

**Symptom:** Execution is rolled back, but no exception is raised / promise is not rejected (no way to tell if the code executed successfully without checking for known side effects or looking at transaction log).

**Solution:** As of today, the latest release of Ganache (1.1.0-beta.0) (also labelled 1.2.0-beta.0 Candy Apple) exhibits this bug. Uninstalling it and installing v1.0.2 "Heart Surgery" fixed it for me.

I will see about reporting this over at Ganache when I get some more time to work on this.
