### ISSUE TITLE
Update Truffle to support solc 0.4.19

### ISSUE THREAD

**Issue by paulbarclay** [trufflesuite/truffle#762]
## Issue

Truffle doesn't support the latest solc version. Is there progress/a timeline on that support?

**Comment by linusnorton** [comment]
This is especially pressing as the experimental ABI seems totally broken in 0.4.18

**Comment by celeduc** [comment]
Why is version "0.4.18" specifically used instead of "^0.4.19"? As [semantic versioning is allegedly used](http://solidity.readthedocs.io/en/develop/layout-of-source-files.html#version-pragma), that means bugfix releases should be allowed.

**Comment by cgewecke** [comment]
Latest release `4.0.6` ships with solc `0.4.19.` Closing, thanks all!
