### ISSUE TITLE
when I use Truffle to deploy contract,and I want to change the transaction params

### ISSUE THREAD

**Issue by cristicmf** [trufflesuite/truffle#768]
when I use Truffle to deploy contract, and I want to change  transaction params. 
Where is the structure of the transaction?
thanks ~

**Comment by cgewecke** [comment]
@cristicmf You can modify the params for each deployment by adding a transaction object as below:
```javascript
deployer.deploy(MyContract, {gas: 250000, from: "0xabc..def"});
```

You can also set custom deployment defaults per network in the [truffle.js](http://truffleframework.com/docs/advanced/configuration#configuration) configuration file:
```javascript
module.exports = {
  development: {
    special: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*",
      gas: 6700000,
      from: "0xabc...edf"
    }
  }
};
```

Does the information above answer your question?

**Comment by cgewecke** [comment]
@cristicmf I'm closing this for house-keeping, hope this resolved your issue. I see you've found more help over at issue #219 but please re-open if you're still having difficulties with this.
