### ISSUE TITLE
Missing Files when Running "truffle init"

### ISSUE THREAD

**Issue by SeaWolfX** [trufflesuite/truffle#775]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am trying out Truffle on Linux Mint for the first time, but I am having trouble with the "truffle init" command. It seems like it is only creating some of the files in the target directory.

## Steps to Reproduce

Installing truffle  using `npm install -g truffle`. Running `truffle init` command in target directory.

## Expected Behavior

Files and folder to be created in target directory.

## Actual Results

All folders seems to be created, but several files are missing. E.g. 2_deploy_contracts.js and ConvertLib.sol is missing.

## Environment

* Operating System: Linux Mint 18.1
* Truffle version: 4.0.5
* Ethereum client: 
* node version: 6.9.5
* npm version: 4.2.0

**Comment by cgewecke** [comment]
@SeaWolfX MetaCoin recently got its own box. Truffle init now downloads a blank template. Running
```
truffle unbox metacoin
```
should get you ConvertLib and everything else. Closing but please reopen if this doesn't resolve your issue. Thanks!
