### ISSUE TITLE
Solo Migrations contract deployment fails and networks object is empty

### ISSUE THREAD

**Issue by mjhm** [trufflesuite/truffle#777]
## Issue

Just deploying the standard Migrations contract by itself fails using `truffle migrate`.  I've observed other more complicated cases where the Migration contract hasn't deployed as well.  

## Steps to Reproduce

Here's a failing test which is a variation of the preceding happy_path test:
https://github.com/trufflesuite/truffle/compare/develop...mjhm:solo_migration_deploy_bug

Please provide the shortest amount of steps to reproduce your issue:

Merge my branch, and run `mocha test/scenarios/happy_path/`

## Expected Behavior

Expect test to pass, and also expect the resulting  `Migrations.json` artifacts file to have a non empty `networks` object. 

## Actual Results

Test fails with: 
```
Error: Migrations has not been deployed to detected network (network/artifact mismatch)
```
and  `Migrations.json` has `networks: {}`

## Environment

* Operating System: MacOS 10.3
* Truffle version: 4.0.5
* Ethereum client: ganache-cli
* node version: 8.9.3
* npm version: 5.6.0

**Comment by marcosc90** [comment]
I'm having the same issue, network object is empty in `MyContract.json`, and is failing with: `has no network configuration for its current network id`

**Comment by eggplantzzz** [comment]
Closing as I believe this issue has been resolved.  If I'm mistaken please feel free to re-open this issue!
