### ISSUE TITLE
How to debug "Insufficient funds" - cannot tell what required funds are?

### ISSUE THREAD

**Issue by quantumproducer** [trufflesuite/truffle#782]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

Wrote a simple contract. Attempting to deploy to testnet and get error.

eth --testnet --fast --rpc --rpcapi eth,net,web3,personal

truffle.js config:

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    },
    ropsten: {
      network_id: 3,
      host: "127.0.0.1",
      port: 8545,
      from: "0xd060fa165f3ff5f506c5391aa07bc57599d053c7",
      gas: 4000000
    }
  }
};
```

then cd into my directory, truffle migrate --network ropsten

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
```

How do I debug what the delta between my funds & required funds for deployment is?

Why is "network status unknown" showing?

* Operating System: 
* Truffle version: v4.0.04
* Ethereum client: ??
* node version: 8.9.1
* npm version: 5.6.0

**Comment by cgewecke** [comment]
@quantumproducer There's a mocha reporter utility called [eth-gas-reporter](https://github.com/cgewecke/eth-gas-reporter) that plugs into Truffle and could be helpful for this. (Full disclosure, I wrote it :)

It won't capture the gas costs of your migrations as such, but if you write a test that simulates your deployment, for example:
```
it('deployment simulation', async function(){
   instanceA = await contractA.new();
   instanceB = await contractB.new();
})
```
It will give you the per contract deployment costs in a chart at the end of your test suite, in addition to total gas usage per test.

**Comment by quantumproducer** [comment]
Cool, it prints the gas requirement into the log?
IT looks likes my problem is Ropsten network is dead and I"m working on switching to parity... the release crashes on startup so I'm compiling parity from source

**Comment by cgewecke** [comment]
@quantumproducer It prints a table at the end of the tests, as part of the test output.

**Comment by cgewecke** [comment]
Hi @quantumproducer, thanks. Closing for house keeping.

**Comment by elie222** [comment]
I just banged my head against this issue with Rinkeby. I had to remove gas and gasPrice from the truffle config file to make it work.

**Comment by quantumproducer** [comment]
Sounds like truffle automatically computed it then? Have you tried deploying to mainnet?

**Comment by hadv** [comment]
@elie222 I also have the below problem even I try many config for gas and gasPrice. Can you share me how to config on the truffle to deploy contract to Rinkeby testnet? thank you so much

```
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
```

**Comment by elie222** [comment]
Try this with Infura (update API key):

```
    rinkebyInfura: {
      provider: function() {
        return new HDWalletProvider(
          process.env.SECRET_MNEMONIC,
          'https://rinkeby.infura.io/XXX',
          1
        )
      },
      network_id: 4,
      // remove these if they cause issues:
      gas: 6612388, // Gas limit used for deploys
      gasPrice: 20000000000, // 20 gwei
    },
```

**Comment by hadv** [comment]
ah, okay thanks!

I found that I have the problem because my from address's balance is 0; I rectify  the address and get fund then everything is working fine.

**Comment by gerchicov-bp** [comment]
@cgewecke 
All the cases described are for Infura:
```
gas: 4500000,
gasPrice: 25000000000,
```
```
truffle migrate --network ropsten --reset
(node:34455) ExperimentalWarning: The fs.promises API is experimental
Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
```
```
gas: 6612388, // Gas limit used for deploys
gasPrice: 2700000000000,
```
```
truffle migrate --network ropsten --reset
(node:34461) ExperimentalWarning: The fs.promises API is experimental
Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
exceeds block gas limit
```

In the same time rinkeby seems to be ok for a case with lower gas and gasPrice but very very slow and doesn't work with higher gas/gasPrice
