### ISSUE TITLE
truffle unbox metacoin pastes contents in current directory, expected to mkdir

### ISSUE THREAD

**Issue by quantumproducer** [trufflesuite/truffle#785]
I ran `truffle unbox metacoin` expecting to `cd metacoin`, similar to how `git clone` works.

**Comment by mjhm** [comment]
FYI I recently wrote [`create-react-dapp`](https://github.com/mjhm/create-react-dapp) which is intended to take a more up-to-date approach to creating starter templates.

**Comment by cgewecke** [comment]
@quantumproducer @mjhm Agree this behavior departs from the pattern of `git clone` and can catch people off guard. I hope you don't mind but I'm going to close this and begin tracking the topic at #786 where there's additional discussion from the rest of the community.
