### ISSUE TITLE
Error: [ethjs-abi] while decoding address data, invalid address data, invalid byte length 32

### ISSUE THREAD

**Issue by webslesar** [trufflesuite/truffle#792]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I tries to call method "transfer" in erc20Token from another contract i am getting error: 
Error: [ethjs-abi] while decoding address data, invalid address data, invalid byte length 32

Interesting facts: 
1) in Solidity remix everything works fine.
2) When I go to erc20Token implementation and comment event line like this:
```
  function transfer(address _to, uint256 _value) public returns (bool) {
    require(_to != address(0));
    require(_value <= balances[msg.sender]);

    // SafeMath.sub will throw if there is not enough balance.
    balances[msg.sender] = balances[msg.sender].sub(_value);
    balances[_to] = balances[_to].add(_value);
    //Transfer(msg.sender, msg.sender, _value);
    return true;
  }
```
everything works fine.

## Steps to Reproduce

ERC20 token is implementation from Zeppeline.

erc20Token - just ERC20 Contract 
B - Simple contract with function like:
    ```
function create(address user) onlyOwner public {
     erc20Token.transfer(user, 10);
}
```
When I try to call function "create" in my truffle tests I catch that error in my terminal.

## Expected Behavior

Contract B will send 10 tokens to "user"

## Actual Results

I am getting error:
Error: [ethjs-abi] while decoding address data, invalid address data, invalid byte length 32
    at Object.decodeAddress [as decode] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:229574:13)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:184385:26
    at Array.forEach (<anonymous>)
    at decodeParams (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:184378:9)
    at Object.decodeEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:184423:10)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:316763:41
    at Array.map (<anonymous>)
    at Object.decodeLogs (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:316731:19)
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:316859:35)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:37991:25

## Environment

* Operating System: 
mac OS X 10.13.3
* Truffle version:
Truffle v4.0.6 (core: 4.0.6)
Solidity v0.4.19 (solc-js)
* Ethereum client:
* node version:
* npm version: 
npm: '5.6.0',

**Comment by webslesar** [comment]
User is from acconts. If you need i can provide sample code

**Comment by cgewecke** [comment]
@webslesar Yes, it would be helpful if you could provide an example test to reproduce this error. 
Out of curiosity, is it your intention to implement the Transfer event as shown above, with `msg.sender` passed in as the value for the `_to` parameter?
```
Transfer(msg.sender, msg.sender, _value);
```

**Comment by cgewecke** [comment]
@webslesar Going to close this for house-keeping but if you're able to provide a reproducible example please feel free to re-open and we'll be more than happy to investigate. Thanks!

**Comment by nklipa13** [comment]
Hey, I had same issue with this and I think that I figured out what was the problem, so basically problem is if you have event with same name in your contract (i.e. Transfer) Truffle gives you that error message. So just try changing name of your event to TransferA and it should work
