### ISSUE TITLE
out of gas Error trying to run Unit Test for Buy Token Function of Decentralised Exchange contract using Ganache CLI

### ISSUE THREAD

**Issue by ltfschoen** [trufflesuite/truffle#793]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

i'm looking for help on some solidity code for a DEX i've been coding https://github.com/ltfschoen/dex. If I try and add anymore code to the `buyToken` function https://github.com/ltfschoen/dex/blob/master/contracts/Exchange.sol#L348, then when I run my Unit Tests I get an `Error: VM Exception while processing transaction: out of gas`, which is associated with the transaction to the `buyToken` https://github.com/ltfschoen/dex/blob/master/test/09_exchange_trading_buy_tokens_creates_market_buy_order_test.js#L50. I've tried explicitly setting the largest Gas Price possible but it doesn’t help.
I didn't get this error when I debugged the whole workflow of that Unit Test file in Remix IDE. I've tried changing the Gas Price / Gas Limit in truffle.js, but that didn't help.
Even if I add something silly somewhere in the `buyToken` function like the following it still triggers the `out of gas` error:
```
if (true == false) {
 require(uint(1) > uint(0));
}
```
i’ve attached above a summary of my progress asking questions to the authors of the Udemy course i've been doing to try and find out if they can help me overcome the error.

 [![out_of_gas_error_question.pdf](https://files.gitter.im/ConsenSys/truffle/xvW1/thumb/out_of_gas_error_question.jpg)](https://files.gitter.im/ConsenSys/truffle/xvW1/out_of_gas_error_question.pdf)

## Steps to Reproduce

* Open a new Terminal window
  * Clone https://github.com/ltfschoen/dex
  * Install dependencies
```
npm install -g truffle;
npm install -g ganache-cli;
```
* Open a 2nd Terminal window and run Ganache TestRPC
```
ganache-cli --port="8500" --mnemonic "copy obey episode awake damp vacant protect hold wish primary travel shy"
```
* Migrate the contracts in the original 1st Terminal window 
```
truffle migrate --network development
```
* Run unit tests. Observe that only one test fails as expected (because I'm emitting and extra event for debugging purposes)
```
truffle test
```
* Add the following code somewhere in the `buyToken` function to demonstrate that adding even code that won't get run is triggering the `out of gas` error.
```
if (true == false) {
 require(uint(1) > uint(0));
}
```
* Run the unit tests again and observe how it gives error `Error: VM Exception while processing transaction: out of gas`

## Expected Behavior

I want to be able to uncomment and use more lines of my code (i.e. such as this line of code https://github.com/ltfschoen/dex/blob/master/contracts/Exchange.sol#L405) in my `buyToken` function without it causing my Unit Tests producing error `Error: VM Exception while processing transaction: out of gas`

## Actual Results

When I run the Unit Tests with more lines of code even if it's valid code, it gives me error `Error: VM Exception while processing transaction: out of gas` and in the Ganache TestRPC window it displays:
```
...
eth_sendTransaction

  Transaction: 0x47a34e196f220abf534a2b40d36ce204781700327450c617ff4b9edcac96a2c1
  Contract created: 0x4947869c6b59621b6aa3bcb0c0562f07d39152ce
  Gas usage: 4712388
  Block Number: 5
  Block Time: Sun Feb 11 2018 21:31:58 GMT+1100 (AEDT)
  Runtime Error: out of gas
```

## Environment

* Operating System: macOS 10.12.6
* Truffle version:
Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)
* Ethereum client: Parity v1.8.9-stable
* node version: v8.7.0
* npm version: 5.5.1
* Ganache CLI v6.0.3 (ganache-core: 2.0.2)

**Comment by cgewecke** [comment]
@ltfschoen Your contract consumes more gas to deploy than the limit you've specified. At the time of this comment, mainnet's limit is 7984452 so you have quite a bit of room to expand while remaining within deployable reality.  

Could you try raising the `gasLimit` of your ganache-cli instance as well as the `gasLimit` specified in your `truffle.js`?

**Comment by ltfschoen** [comment]
@cgewecke Thank you that worked!
I found the latest Gas Limit and Gas Price used by Mainnet at https://ethstats.net/, as you mentioned.
I need to updated truffle.js with a larger Gas Limit as you mentioned:
```
module.exports = {
  networks: {
    development: {
      ...
      gas: 7984452, // Block Gas Limit same as latest on Mainnet https://ethstats.net/
      gasPrice: 2000000000, // same as latest on Mainnet https://ethstats.net/
...
```
It was also necessary to specify a matching Block Gas Limit in Ganache CLI flags as follows:
```
ganache-cli \
  --port="8500" \
  --mnemonic "copy obey episode awake damp vacant protect hold wish primary travel shy" \
  --verbose \
  --networkId=3 \
  --gasLimit=7984452 \
  --gasPrice=2000000000;
```

**Comment by cgewecke** [comment]
@ltfschoen Oh good - closing this for housekeeping. 

Please feel free to re-open if you feel there are other issues to resolve here.
