### ISSUE TITLE
Unable to deploy an Interface when it is in a separate .sol file  

### ISSUE THREAD

**Issue by ltfschoen** [trufflesuite/truffle#796]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In my repository https://github.com/ltfschoen/dao. I want move the `Token` Interface out of the [TokenInterface.sol file](https://github.com/ltfschoen/dao/blob/master/contracts/TokenRecipient.sol) and into its own file called Token.sol with contents:
```
pragma solidity ^0.4.19;

interface Token {
    function transferFrom(address _from, address _to, uint256 _value) public returns (bool success);
}
```
And then import Token.sol into TokenInterface.sol with `import "./Token.sol";`

I then want to updated [this file that deploys my contracts and links to libraries and interfaces](https://github.com/ltfschoen/dao/blob/master/migrations/2_deploy_contracts.js) to link the Token.sol interface to TokenRecipient prior to deploying TokenRecipient, by importing `const Token = artifacts.require("./Token.sol");`, and then linking Token to TokenRecipient before deploying TokenRecipient and Congress by adding `deployer.link(Token, TokenRecipient);`, so 2_deploy_contracts.js would become:
```
const Owned = artifacts.require("./Owned.sol");
const Token = artifacts.require("./Token.sol");
const TokenRecipient = artifacts.require("./TokenRecipient.sol");
const Congress = artifacts.require("./Congress.sol");

module.exports = (deployer) => {
    // Deploy library Owned, Token, and TokenRecipient
    deployer.deploy(Owned);
    deployer.deploy(Token);
    // Link Token to TokenRecipient before deploying Congress
    deployer.link(Token, TokenRecipient);
    deployer.deploy(TokenRecipient);
    // Link Owned and TokenRecipient to contract Congress before deploying Congress
    deployer.link(Owned, Congress);
    deployer.link(TokenRecipient, Congress);
    // Deploy contract Congress
    deployer.deploy(Congress, 0, 0, 0);
};
```
However, after making these changes, I then start Ganache CLI as usual with:
```
ganache-cli \
  --port="8500" \
  --mnemonic "copy obey episode awake damp vacant protect hold wish primary travel shy" \
  --verbose \
  --networkId=3 \
  --gasLimit=7984452 \
  --gasPrice=2000000000;
```
But when I try to deploy the contracts by running `truffle migrate --network development`, it gives me error:
```
$ truffle migrate --network development
Compiling ./contracts/Congress.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Owned.sol...
Compiling ./contracts/Token.sol...
Compiling ./contracts/TokenRecipient.sol...
Writing artifacts to ./build/contracts

Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x39217f6841bbdaef54fc759d3a6ff2b4e6455eaa02e417839c4d5826bb696129
  Migrations: 0x5b80e4653adbc5e8e2387474d4de0eeed34779ea
Saving successful migration to network...
  ... 0x910366905fa49da62c436bbb01f32f676063ed63e4988fad270122c625dd3192
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Owned...
  ... 0x9d76b243b694da1765146293224ce2d100935692e66428a54e868c52a875edaa
  Owned: 0x4cdb6ac6c502d9dca1a0b70fdc1cd7e64f89e1bf
  Deploying Token...
  ... 0xf4b996e65b518f8c87190bfb7d596629d6e8c3fe01a0fb1bd5607fa9d2af1737
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/Ls/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
```

Note: For information about Interface, see the docs here: http://solidity.readthedocs.io/en/develop/contracts.html?highlight=interface#interfaces

## Steps to Reproduce

* Clone repository https://github.com/ltfschoen/dao
* Install dependencies: `npm install -g truffle ganache-cli`
* Switch to branch [refactor-token](https://github.com/ltfschoen/dao/compare/refactor-token) where I have made the changes that result in the error
* Run Ganache CLI in a separate Terminal window
```
ganache-cli \
  --port="8500" \
  --mnemonic "copy obey episode awake damp vacant protect hold wish primary travel shy" \
  --verbose \
  --networkId=3 \
  --gasLimit=7984452 \
  --gasPrice=2000000000;
```
* Remove /build directory `rm -rf build/`
* Run the migrations to deploy the contracts to the Test network of Ganache CLI
```
truffle migrate --network development
```
* Observe the error that gets produced, as mentioned previously
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
```

## Expected Behavior

I expect to be able to move an Interface into a separate file and link it to other contracts that depend upon it

## Actual Results

See section "Steps to Reproduce"

## Environment

* Operating System: macOS 10.12.6
* Truffle version:
Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)
* Ethereum client: Parity v1.8.9-stable
* node version: v8.7.0
* npm version: 5.5.1
* Ganache CLI v6.0.3 (ganache-core: 2.0.2)

**Comment by cgewecke** [comment]
@ltfschoen It looks like the issue here might be that `interface` is an abstract contract which is meant to be used with the inheritance pattern. Could you see if removing the interface deployments / linkages from the migrations and substituting them with something like the following in your Solidity contract definitions achieves what you're aiming for?
```
import "./Token.sol"

contract TokenRecipient is Token {
   ... etc ...
}
```

**Comment by cgewecke** [comment]
@ltfschoen Hi this has been open for a bit. Closing for house-keeping but please feel free to re-open if I've misunderstood your issue or you're still facing difficulties with it. Thanks!

**Comment by cgewecke** [comment]
@violalbi91 Interfaces aren't deployable, they're inheritable. 

A more detailed discussion of how to use interfaces and abstract contracts can be found [here](https://ethereum.stackexchange.com/questions/26674/deploying-abstract-contracts-and-interfaces).

**Comment by violalbi91** [comment]
@cgewecke After debugging deep what I found is that my problem is not related to Interfaces even if the Error Stack is the same.
Contracts implementation is almost the same as the one suggested<a href="https://blog.colony.io/writing-more-robust-smart-contracts-99ad0a11e948"> here.</a>
So I will use the same contracts to explain.

Let's say I have the Ownable.sol, ExternalStorage.sol and the SecurityLibrary.sol as the example.
The error occurred when I use the function of the library inside the constructor when writing Organisation.sol

`import "ProposalsLibrary.sol";
import "SecurityLibrary.sol";

contract Organisation
{
  using SecurityLibrary for address;
  address public eternalStorage;

  function Organisation(address _eternalStorage, address _admin) {
    tokenLedger = ITokenLedger(_tokenLedger);
    eternalStorage = _eternalStorage;

    eternalStorage.addAdmin(_admin);//ERROR OCCUR WHEN I ADD THIS LINE.
   //addAdmin is a function inside the SecurityLibrary.sol
  }
  [...]
}`

Any Idea why this is happening?
Should I open a new Issue?
Thanks in advance!

**Comment by ltfschoen** [comment]
@violalbi91 I'd suggest creating a new issue.

I found that for the current issue #796, if I only import the dependent interfaces that a contract uses 
```
import "./Token.sol";

contract TokenRecipient is Token {
  ...
}
```
and I remove the deployment and linkages of the interface contract (i.e. removing the following code)
```
deployer.deploy(Token);
deployer.link(Token, TokenRecipient);
```
then it compiles successfully.

I also discovered that in the latest project I'm working on https://github.com/ltfschoen/benzcoin, if I change `contract ERC20Interface {` to `interface ERC20Interface {` instead, then it still compiles successfully.

**Comment by cgewecke** [comment]
@violalbi91 Can you verify that EternalStorage exists at the time this contract is deployed? One difference between your implementation and Colony's is that they're [instantiating the storage contract in the constructor](https://gist.github.com/elenadimitrova/7c14df8eee1ed56aa554020874a010bb#file-simple-organisation-constructor). What does your `migrations.sol` look like?

**Comment by violalbi91** [comment]
@cgewecke you are right the contract is not instantiated. I am referring to <a href="https://gist.github.com/elenadimitrova/609418919159bdf80ece48b65a44ad8e"> this contract from Colony</a> where the EternalStorage address is passed through the constructor. If I use `externalStorage = new EternalStorage() ` the error goes away but the externalStorage has a different address from the one I deployed I guess. Is there a way to create a new instance of the contract related to the address where it has been deployed?

My migration.sol is like this : 
```
contract Migrations {
  address public owner;
  uint public last_completed_migration;
  modifier restricted() {
    if (msg.sender == owner) _;
  }
  function Migrations() {
    owner = msg.sender;
  }
  function setCompleted(uint completed) restricted {
    last_completed_migration = completed;
  }
  function upgrade(address new_address) restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
```

**Comment by violalbi91** [comment]
My 2_deploy_contracts.js is : 
```
deployer.deploy(EternalStorage).then(function () {
  deployer.deploy([[SecurityLibrary, EternalStorage.address]]).then(() => {
     deployer.link(SecurityLibrary, Organisation);
       deployer.deploy(Organisation, EternalStorage.address, accounts[0]).then(function () {
       });
  });
});

```

**Comment by cgewecke** [comment]
@violalbi91 The migrations look good - I think you just have to get the contract instance at the address you're passing into your constructor. Does this work?

```javascript
`import "SecurityLibrary.sol";

contract Organisation
{
  using SecurityLibrary for address;
  EternalStorage public eternalStorage;

  function Organisation(address _eternalStorage, address _admin) {
     tokenLedger = ITokenLedger(_tokenLedger);
     eternalStorage = EternalStorage(_eternalStorage);

     eternalStorage.addAdmin(_admin);//ERROR OCCUR WHEN I ADD THIS LINE.
     //addAdmin is a function inside the SecurityLibrary.sol
  }
```

**Comment by cgewecke** [comment]
@violalbi91 Oh yes, good catch about `using SecurityLibrary.`At this point I would try some different things with the migrations. Should this be double arrayed?
```
deployer.deploy([[SecurityLibrary, EternalStorage.address]])
```
What about `tokenLedger`? Where is that coming from and why is it there? 

I'm really sorry, I'm kind of out ideas. If you put everything into a git repo I can clone, I'd happily help debug later today :).

**Comment by violalbi91** [comment]
@cgewecke  I was making a new project from scratch to put it in a repository and I found out where the error was. The problem was not really related to the constructor but ExternalStorage had an inheritance with an Ownable.sol which one had a modifier that is used to accept call just if the msg.sender is the owner, and in the constructor the owner of ExternalStorage wasn't the Organisation Contract. Here is the Ownerable.sol

```

contract ExternalStorage is Ownable {
   ...
}
```

```
contract Ownable {

    address public owner = msg.sender;

    /// @notice check if the caller is the owner of the contract
    modifier onlyOwner {
        require (msg.sender == owner) ;
        _;
    }

    /// @notice change the owner of the contract
    /// @param _newOwner the address of the new owner of the contract.
    function changeOwner(address _newOwner)  onlyOwner {
        require(_newOwner != 0x0) ;
        owner = _newOwner;
    }
}
```
So following what Colony did I deleted the call to the addAdmin inside the constructor in Organisation.sol and added a new parent contract where I can instantiate both ExternaleStorage and Organisation and call the addAdmin.
Adding the changeOwner now the owner of the contract is Organisation.

```
contract CreateOrganisation {

    function createOrganisation(address _admin){

        var externalStorage = new ExternalStorage();

        var organisation = new Organisation(externalStorage, _admin);

        externalStorage.changeOwner(organisation);

        organisation.addAdmin(_admin);

    }

}
```
As soon as I can I'll post the link to the repo if you like by the way.
Thank you very much!!

**Comment by cgewecke** [comment]
Ahhh! That makes sense. Thanks for showing your solution too - I searched a little yesterday and couldn't find any other examples of someone doing what you're trying to do so this very useful. Much appreciated.
