### ISSUE TITLE
unexpected token : in JSON at position 15566 on truffle migrate

### ISSUE THREAD

**Issue by Paasmer** [trufflesuite/truffle#797]
---------------------------

## Issue

I am trying to deploy new contract on rinkeby test network through my node application. When I run truffle migrate command ' truffle migrate --reset --network rinkeby', I end up with following exception
**Unexpected token : in JSON at position 15566**

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Contract should get deploy successfully.

## Actual Results

Unexpected token : in JSON at position 15560

## Environment

* Operating System: Amazon Linux
* Truffle version: 4.0.6
* Ethereum client: rinkeby
* node version: 6.10.3
* npm version: 3.10.10

**Comment by cgewecke** [comment]
@Paasmer If you have a chance could you post the stack trace you get with this error so we can locate its source?

**Comment by Paasmer** [comment]
@cgewecke  

SyntaxError: Unexpected token : in JSON at position 15566

    at Object.parse (native)

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/truffle-compile/profiler.js:79:1

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:1126:1

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:473:1

    at iteratorCallback (/home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:1050:1)

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:958:1

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:1123:1

    at /home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules/truffle/build/webpack:/~/truffle-compile/profiler.js:72:1

    at tryToString (fs.js:456:3)

    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)

**Comment by cgewecke** [comment]
@Paasmer Sorry for the delay getting back to you. Your error originates in a section of code that reads a contract artifact stored as a JSON object in the folder `build/contracts`. For some reason that file is getting corrupted but it's not clear why. 

+ Could you open the file that fails, look at position 15566 in a text editor (the character should be a colon) and report back what's there? 
+ Are you able to migrate using ganache-cli? 
+ Is there anything unusual about the way you're building your project? Any additional information you can provide might be helpful here. 

Thanks.

**Comment by cgewecke** [comment]
@Paasmer I'm going to close for house-keeping since it's been a few days it seems like you might have resolved this on your own? If not please re-open - will continue to watch this issue in case anyone else starts seeing this error crop up. Thanks for reporting!

**Comment by Sander-Voogt** [comment]
I've almost the same error but on position 3253552. The contract is wrong compiled. The image below displays where the error occurs.

 
<img width="1187" alt="schermafbeelding 2018-05-06 om 23 57 30" src="https://user-images.githubusercontent.com/8642727/39691010-5c0d60aa-51dc-11e8-9ca5-89515f82b42f.png">

**Comment by GaoGGGQY** [comment]
you should edit the truffle-config.js file in your project path first if you wanna deploy the smart contracts. 
such as:
module.exports = {
    networks: {
        development: {
          host: "localhost",
          port: 8545,
          network_id: "*"
        }
    }
};

I hope that could help you~
