### ISSUE TITLE
Option to default to block gas limit of connected network

### ISSUE THREAD

**Issue by JohnAllen** [trufflesuite/truffle#798]
Often users of Truffle have to trial and error the right `gas` value in truffle.js.  But shouldn't there just be a default option to have gas be the current block gas limit of the network?

**Comment by gnidan** [comment]
@JohnAllen note that  you likely do not want to set your transaction gas limit to be the block gas limit: on mainnet, miners will have no way of knowing ahead of time that your transaction will use anything less than the full limit, and so it will take a long time for a miner to include the transaction (thinking that the transaction will be the only one in the block—no room for other, smaller transactions with potentially higher gas price)

**Comment by JohnAllen** [comment]
@gnidan had the same thought.  

The vast majority of deploys are not on mainnet though, and many people determine the gas their contracts will cost during dev and testing and hard code that number in truffle.js once they go to deploy to mainnet.

**Comment by cgewecke** [comment]
@JohnAllen Small update: automated fueling of deployments and method calls have been added to [truffle-contract 95](https://github.com/trufflesuite/truffle-contract/pull/95). Believe this should accomplish what you're aiming for here. Unfortunately it won't be available until the release that upgrades to `web3 1.0` comes out. 

Thanks for pushing for this.

**Comment by gnidan** [comment]
This has been released as part of v5. Thank you!

**Comment by SidSethi** [comment]
To clarify, truffle v5 now allows you to default the gas limit to network block gas limit on all TX? or only deploys/migrations
