### ISSUE TITLE
migrate --reset in 'truffle develop' doesn't update the contract changes

### ISSUE THREAD

**Issue by Aniket-Engg** [trufflesuite/truffle#799]
## Issue

migrate --reset in 'truffle develop' doesn't reset build folder

## Steps to Reproduce

```
truffle develop
truffle(develop)> migrate --reset
```

## Expected Behavior

It should perform the migration from beginning

## Actual Results

It doesn't update the migrations. I have to delete the build folder and then re-run the migration to get the contracts changes in the effect.

## Environment

* Operating System: Ubuntu 16.04 LTS
* Truffle version: 4.0.4
* node version: 8.9.3
* npm version: 5.6.0

**Comment by cgewecke** [comment]
@Aniket-Engg Thanks for reporting. We're currently tracking this topic at #685. If you have a chance could you see if modifying your command to `truffle migrate --reset --all` results in the correct behavior?

Closing as duplicate.

**Comment by Aniket-Engg** [comment]
@cgewecke Yes that works. Thanks.

**Comment by PaulRBerg** [comment]
I encountered this behaviour in truffle 5.0.15. Sometimes, `--reset` doesn't redeploy the contracts, but instead it just performs a silent dry-run (without even telling me). I speculate it's a dry run because I double checked that the contracts are not deployed on the Ganache node.

**Comment by significance** [comment]
> I encountered this behaviour in truffle 5.0.15. Sometimes, `--reset` doesn't redeploy the contracts, but instead it just performs a silent dry-run (without even telling me). I speculate it's a dry run because I double checked that the contracts are not deployed on the Ganache node.

+1 - downgrading to 5.0.0 seems to fix
