### ISSUE TITLE
Issue in contract creation using sendRawTransaction?

### ISSUE THREAD

**Issue by mariam-crissi** [trufflesuite/truffle#804]
## Issue

I am trying to create a new contract using sendRawTransaction().

          pragma solidity ^0.4.18;
          contract MultiSigWallet {
                          function MultiSigWallet(address[] _owners) public {
                                      for (uint i = 0; i < _owners.length; i++) {
                                                 if (isOwner[_owners[i]] || _owners[i] == 0)
                                                          revert();
                                                 isOwner[_owners[i]] = true;
                                      }
                                     owners = _owners;
                       }
                             /*** Remaining Functions ***/
         }

I have array as parameters in my MultiSigWallet contract.

I am using truffle framework for the development.I am trying to get the data param in rawTransaction.For this ,I have written the following code to get the data param in my js.

                        var MultiSigWallet = contract(MultiSigWallet_artifacts);
                        var setData = MultiSigWallet.new.getData([adminAddress,fromAddress,toAddress],{
                                data: MultiSigWallet.unlinked_binary
                       });
                          var rawTx = {
                                                "from":fromAddress,  //from Address
                                                "data":setData,
                                                "gas":3000000,
                                                "nonce":nonce
                                              }  

But it returns the following error:-

            (node:15438) UnhandledPromiseRejectionWarning: TypeError: MultiSigWallet.new.getData is not a function

How can I get ```data``` param for contract creation using ```getData``` function?

## Expected Behavior

Expects the deployed address for the contract ```MultiSigWallet```

## Actual Results

      (node:15438) UnhandledPromiseRejectionWarning: TypeError: MultiSigWallet.new.getData is not a function

## Environment

* Operating System: Ubuntu 16.04
* Truffle version: Truffle v4.0.5 (core: 4.0.5)
* Ethereum client: Version: 1.8.0-unstable
* node version:v9.3.0
* npm version: 5.6.0

**Comment by cgewecke** [comment]
@mariam-crissi The `truffle-contract` wrapper doesn't directly expose `getData`. However you can access a TruffleContract's underlying web3 object and interact with it through the`contract` property. In your case this would look like: `MultiSigWallet.contract.someMethod.getData`

**Comment by mariam-crissi** [comment]
@cgewecke I am trying to create a new contract instance..Is it possible to use ```MultiSigWallet.contract.new.getData(params)```?

**Comment by mariam-crissi** [comment]
@cgewecke   I have tried,but it also generates the following issue
```
(node:5357) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'new' of undefined

```

**Comment by cgewecke** [comment]
Sincere apologies @mariam-crissi I didn't read your example closely enough. I think you will need to manage this using web3 directly, although the necessary components (the binary and the ABI) are available on the artifact. If you look [here](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcontract) at the web3 docs, you should be able to string the calls you need together. Then once you have a deployed web3 contract instance, you can generate a `TruffleContract` version of it using `MultisigWallet.at(<contractAddress>). 

Will that work for your case?

**Comment by mariam-crissi** [comment]
@cgewecke  As you mentioned,Shall I try with the following code?

```
                       var MyContract = web3.eth.contract(MultiSigWallet.abi);
                                          var contractData = MyContract.new.getData([adminAddress,fromAddress,toAddress], {data: MultiSigWallet.unlinked_binary});
                                          console.log(contractData);
```

**Comment by mariam-crissi** [comment]
@cgewecke It worked fine...Thank you for your help.
