### ISSUE TITLE
Identify file which causes compilation error such as UnimplementedFeatureError

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#805]
## Steps to Reproduce & Actual Results
I have the following code:

**RecordsLib.sol**:

    pragma solidity ^0.4.0;
    library RecordsLib {
        struct Data {
            uint timestamp;
            uint score;
        }
        function updateRecord(Data storage self, uint newTimestamp, uint newScore) public {
            self.timestamp = newTimestamp;
            self.score = newScore;
        }
    }

**Leaderboard.sol**:

    pragma solidity ^0.4.0;
    import "./RecordsLib.sol";

    contract Leaderboard { //keeps track of last score, not highest
        struct Competitor {
            RecordsLib.Data currentEntry;
            uint numAttempts;
        }

        mapping(address => Competitor) public competitors;

        function updateRecord(address addr, uint newTimestamp, uint newScore) public {
            //competitors[addr].numAttempts++; //eliminated to simplify example
            RecordsLib.updateRecord(competitors[addr].currentEntry, newTimestamp, newScore);
        }
    }

When I compile using `truffle compile`, I get the following output (last line in red):

    Compiling .\contracts\Leaderboard.sol...
    Compiling .\contracts\RecordsLib.sol...

    UnimplementedFeatureError:
    Compilation failed. See above.

## Expected Behavior

Remix gives the following error and specifies that it is on Leaderboard.sol.

    UnimplementedFeatureError: Only in-memory reference type can be stored.

This additional detail, and identifying specifically which file the error is associated with, is much more helpful for debugging. 

## Environment

* Operating System: Windows 10
* Truffle v4.0.4 (core: 4.0.4)
* Solidity v0.4.18 (solc-js)

**Comment by cgewecke** [comment]
@wbt This looks very similar to a bug at Solidity that's being addressed [here](https://github.com/ethereum/solidity/issues/3546). If you have a chance, could you close here and re-open there? Your example is slightly different and be might relevant to their efforts to resolve the problem.

**Comment by wbt** [comment]
@cgewecke Thanks for the pointer! I think the underlying compilation failure might be a Solidity bug, but haven't yet fully convinced myself the bug is not in my code.  In either case, I think Truffle should pass along the error message with as much detail as Remix, and that's the focus of this Issue which seems properly filed on Truffle.

**Comment by cgewecke** [comment]
@wbt Ah I understand. I think the difference might a difference in compiler version? Is that possible?

**Comment by wbt** [comment]
@cgewecke Ah, yes, in part.  Changing Remix to use compiler `v0.4.18+commit.9cf6e910.Emscripten.clang`, I see that the error message is less specific, matching what I see in Truffle.  However, Remix still does at least identify the specific file which triggered the error, which is a step up over Truffle's current output.

**Comment by cgewecke** [comment]
@wbt Ok fair enough, will look into this. . .

**Comment by cgewecke** [comment]
@wbt I agree this error is not helpful enough and is missing critical information. However, Truffle passes back all the information it gets from solc and typically this contains detailed file/line info. Ex:
```
Error parsing /example/contracts/RecordsLib.sol: ParsedContract.sol:6:5: ParserError: Expected token Semicolon got 'RBrace'
    }
    ^
```
Because Remix compiles files individually rather than as a batch, it's able to communicate that a given compilation attempt failed.  Truffle batches and so relies on `solc`'s error reporting. My view is that this issue belongs at `solidity` and is probably transitory - as soon as they resolve the underlying question about nested structs the error will likely normalize.

**Comment by wbt** [comment]
Parse errors show up like that, but you can see the output in Comment 0 above for this kind of error: no file identification, let alone line or column.
When a compilation fails and does not produce a file-identifying error, could Truffle try again without batching and report the specific file?

Also, I don't think `solidity` is going to solve that issue about nested structs anytime soon.  The "intended behavior" for the getter is unclear, there probably has to be _some_ depth limit, and the EVM's limitations on being able to return dynamically sized types eliminate a lot of options for sensible defaults.  I think that issue will probably eventually be closed, with what I posted there as a "workaround" becoming a more permanent solution (and hopefully, a more informative error message to guide developers to it).

**Comment by cgewecke** [comment]
@wbt I've looked through some of the code at `solidity` (but just focused on the error handling), and it seems likely that their intention is to provide location data but for some reason it isn't propagating. For example [here](https://github.com/ethereum/solidity/blob/70790d4729a8cee7d587bf274ed1733b255b2120/libsolidity/interface/StandardCompiler.cpp#L410-L420):
```c
catch (UnimplementedFeatureError const& _exception)
{
     errors.append(formatErrorWithException(
	    _exception,
	    false,
	    "UnimplementedFeatureError",
	    "general",
	    "Unimplemented feature (" + _exception.lineInfo() + ")",
	     scannerFromSourceName
	));
}
``` 
What do you think about helping to diagnose and fix that (if possible)? It would be a nice PR.

**Comment by cgewecke** [comment]
@wbt I'm going to close this for housekeeping. There's merit on both sides here but in the end I think Solidity intends to provide the error info. The simplest solution is to a) tell them this is happening (they already know) and b) if possible help them fix it.
