### ISSUE TITLE
`truffle install` should allow updating ethpm.json, similar to `npm install`

### ISSUE THREAD

**Issue by dmihal** [trufflesuite/truffle#807]
---------------------------

## Issue

Truffle & EthPM seem to be designed to function similar to NPM. `truffle install <package>` installs the package to the `installed_contracts` directory, similar to how `npm install <package>` installs a NPM package to the `node_modules` directory.

Also, `truffle install` will install any dependencies from the `ethpm.json` file, similar to how `npm install` installs any dependencies from `package.json`.

One feature that seems missing is a command analogous to `npm install -s <package>`, which installs a package and adds the dependency to `package.json`.

## Proposal

A feature would be added to the Truffle CLI to allow installing new dependencies and saving the dependency to `ethpm.json`. Keeping in line with NPM, this could be added with a `-s` flag, so `truffle install -s <package>`.

If the `ethpm.json` file doesn't exist, a new file could be automatically generated.

**Comment by dmihal** [comment]
I'm interested in developing this feature, does anybody have any thoughts or comments before I dive into the code?

**Comment by lazaridiscom** [comment]
if `-s` is free, that this would introduce new **optional** behaviour, so its a non-breaking addition.

Your elaborations sound rational, so I (personally) would just go on with it.

how does ethpm handle this?

**Comment by cgewecke** [comment]
@dmihal Yes. If you'd like to work on this please do. `-s` looks free to me.

**Comment by dmihal** [comment]
@lazaridiscom EthPM.js doesn't have any mechanism for writing to ethpm.json, except for `ETHPM.init()`, which copies the template ethpm.json file.

I was thinking truffle could use `ETHPM.init()` if the user uses the `-s` flag, but hasn't created an ethpm.json file yet.

**Comment by lazaridiscom** [comment]
(I just now realized that ethpm-js is under truffles control, which is of course a good thing)
