### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#808]
This reopen https://github.com/trufflesuite/truffle/issues/803
I have problem configuring the chainID. Do not can use genesis.json.
https://github.com/ethereum/go-ethereum/issues/16137

**Comment by cgewecke** [comment]
@freshonline I don't understand - it seems like you were advised to remove the `--dev` flag and start over with a standard geth installation for a private network. Why is that not a good solution? This does not appear to be a problem you're having with Truffle but rather with your Geth configuration.

**Comment by cgewecke** [comment]
@freshonline Closing as a duplicate of #803. Feel free to raise any questions you have there and if it merits re-opening because there's something in the Truffle code that needs to change, we'll be happy to do that.
