### ISSUE TITLE
'truffle create' shouldn't overwrite existing files

### ISSUE THREAD

**Issue by dmihal** [trufflesuite/truffle#809]
---------------------------

## Issue

The command `truffle create` overwrites existing files with empty boilerplate files without warning.

## Steps to Reproduce

1. Run `truffle create contract TestContract`
2. Modify `contracts/TestContract.sol`
3. Run `truffle create contract TestContract` again
4. All changes to `contracts/TestContract.sol` have been reverted without warning

This behavior occurs when creating contracts, migrations and tests.

## Expected Behavior

The CLI should produce a warning that the file already exists.

Optionally, a `-f` flag can be used when a user wishes to overwrite the file.

## Actual Results

All changes to `contracts/TestContract.sol` have been reverted without warning.

I'm happy to create a PR if people support changing this

**Comment by cgewecke** [comment]
@dmihal Gladly take a PR! There's a guide to setting up the project for contributions [here](https://github.com/trufflesuite/truffle/blob/develop/CONTRIBUTING.md). Feel free to ping this issue if you need any help. 

Thanks so much.

**Comment by cgewecke** [comment]
@dmihal If you're taking this on, #790 could be within scope too. Or not, your call. :)

**Comment by dmihal** [comment]
Created a PR for the overwriting issue, looking at #790 now

**Comment by cgewecke** [comment]
This is fixed on 4.0.7 - thanks @dmihal!
