### ISSUE TITLE
Error: contract constructor expected 1 arguments, received 0

### ISSUE THREAD

**Issue by lazaridiscom** [trufflesuite/truffle#811]
## Issue

Truffle version 4.0.6 introduces a bug, similar to #596. When I switch to 4.0.5, the bug disappears

## Steps to Reproduce

I've no isolated reproduction case. The bug appeared during work on GridPlus/cryptobridge-contracts/issues/11

The relevant contract:

https://github.com/GridPlus/cryptobridge-contracts/blob/master/contracts/Bridge.sol#L517

## Environment

* windows 10 native, bash on ubuntu 16.04 on windows (WLS), Hyper-V ubuntu 16.04
* version Parity/v1.8.10-unstable-4bfabb675-20180215/x86_64-windows-msvc/rustc1.23.0
* P:\sand\cryptobridge\cbc>node -v v8.9.3
* P:\sand\cryptobridge\cbc>npm -v 5.5.1

# Update

I've isolated the cause and solved this on my side.

**Comment by lazaridiscom** [comment]
I've isolated the cause and solved this on my side.

**Comment by cgewecke** [comment]
@lazaridiscom Is this closable? Does it seem like the constructor argument validation is working correctly?

**Comment by lazaridiscom** [comment]
seeing #596, I think this should stay open. Possibly during further work I find out what triggered this and can be sure its not truffle.

**Comment by cgewecke** [comment]
@lazaridiscom Is the error you saw correct? i.e for some reason the constructor was called without arguments? If so we should close this because it's un-related to #596 - that's a re-compilation bug.

**Comment by lazaridiscom** [comment]
@cgewecke , its "similar to #596", not 100% sure if related. Placed this just for info. I cannot verify this at this moment, the error exists (although its something else what triggers it, possibly command-line handling). For sure: there **is** something wrong. And until someone pinpoints it, this should stay open.

**Comment by cgewecke** [comment]
@lazardis - Where / when is the error being triggered? We just recently added this constructor error message in order to address silent failures caused by the ability to instantiate a contract that requires constructor arguments without actually specifying them. The error you're seeing is definitely from Truffle (rather than web3) and intentional. 

Don't you get a line number for the error? Does it originate in migrations or a test?

**Comment by lazaridiscom** [comment]
@cgewecke , I reported this, but sorry, I'm not available at this point to dig deeper. Will revisit though in the next days.

**Comment by lazaridiscom** [comment]
haha! @cgewecke , should have read your message. But you know how it is when you've a cloud in your brain, and information/questions come to you!

Confirmed, not your fault, its a "good" error.

In the initial migration:

```js
    deployer.deploy(Bridge);
```
But there this is the constructor

```sh
  // Staking token can only be set at instantiation!
  function Bridge(address token) {
    admin = msg.sender;
    stakeToken = token;
  }
```

bad 4.0.5 did not catch. 

Good 4.0.6 catches.

All fine!

-

sidenote: still unmerged/unreviewed: trufflesuite/truffle-core/issues/87

**Comment by cgewecke** [comment]
@lazaridiscom Thanks for the reminder about the EthPM, will look at that shortly.

**Comment by jbarros35** [comment]
Error: Ballot contract constructor expected 1 arguments, received 0
that's the same contract in tutorial website.
please can you help me find a solution?

**Comment by cgewecke** [comment]
Hi @FabiolaBusch  If you're passing `Listing` to the `deploy` method, you'll also need to specify the values of its constructor parameters. For example:
```javascript
address = "0xabc.......";
id = 5;
title = web3.fromAscii("Hello!");

deployer.deploy(Listing, address, id, title);
```

There's more info about the deployer API in the docs [here](http://truffleframework.com/docs/getting_started/migrations#deployer).

**Comment by FabiolaBusch** [comment]
@cgewecke Thanks a lot, that helped me!
