### ISSUE TITLE
Running Mist and truffle develop: got 400 Bad Request

### ISSUE THREAD

**Issue by W-B-S** [trufflesuite/truffle#821]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

400 Bad Request

## Steps to Reproduce

 Run Truffle Develop by typing the following into a terminal:

truffle develop
This will run the client on http://127.0.0.1:9545. 

## Expected Behavior

show the blockchain data

## Actual Results

400 Bad Request
## Environment

* Operating System: MAC OSX 10.13.4 Beta (17E160e)
* Ethereum client: mist
* Truffle version (`truffle version`):
Truffle v4.0.7 (core: 4.0.7)
Solidity v0.4.19 (solc-js)
* node version (`node --version`):
v9.6.1
* npm version (`npm --version`): 
5.6.0

**Comment by cgewecke** [comment]
@W-B-S I just got the latest Mist client, fired up `truffle develop`, then ran (I'm on a Mac) in a separate terminal window.
```
/Applications/Mist.app/Contents/MacOS/Mist --rpc http://127.0.0.1:9545
```

Works. Is there any other info you could provide to help reproduce this error?

**Comment by cgewecke** [comment]
@W-B-S Closing for housekeeping but please re-open if you continue to see this error and can identify a way of reproducing it.
