### ISSUE TITLE
Debugging unit tests

### ISSUE THREAD

**Issue by aleybovich** [trufflesuite/truffle#822]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Debugging JS unit tests

## Steps to Reproduce

Do you know if there is a way to debug JS unit tests for smart contracts? I use VS Code for development, and when I try to run a Mocha debugger it complains that `artifacts` is not defined. I briefly looked at truffle code, it looks like it adds `artifacts`, `contract` and some other global js variables when it runs the unit tests. Is there a way for me to add those explicitly in the JS unit test file so I could debug that unit test file? 

## Expected Behavior

Be able to debug js unit tests

## Actual Results

Not able to debug unit tests as `artifacts`, `contracts` and other JS objects injected by truffle are not present when running the debug session
 
## Environment

* Operating System: Mac OSX 
* Ethereum client: Ganache
* Truffle version (`truffle version`): 4.0.7
* node version (`node --version`): 7.7.3
* npm version (`npm --version`):  4.0.3 
* IDE: VS Code

**Comment by lazaridiscom** [comment]
Your lucky day (had to solve this few days ago):

See that you have `truffle-core` locally in your project. if not, do:

`npm install truffle-core`

Then use this configuration similar to this: ( Debug -> Open Configurations )

```js
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "truffle test (debugable)",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}\\node_modules/truffle-core/cli.js",
            "args": [
                "test"
            ]

        }
    ]
}
```

Or add a new one (simple "node"  launch, the edit it)

Unless your code does not spawn another node process (brings trouble which are essentially an node.js bug), you should be good.

**Comment by aleybovich** [comment]
@lazaridiscom You are my hero - this is gonna save me hours of pulling my hair! I am going to post this question on ethereum.stackexchange.com and if you are on there you can post this answer and get points, or if you don't use it I will post the answer, so the community can use it. I know several people who were looking for this as well.

**Comment by lazaridiscom** [comment]
Actually i wanted to ask myself some questions, so... possibly I should get some reputation there... go on, i see to it to reply.

**Comment by aleybovich** [comment]
@lazaridiscom sure, go ahead and answer this: https://ethereum.stackexchange.com/questions/41094/debugging-js-unit-tests-with-truffle-framework-in-vs-code

**Comment by aleybovich** [comment]
Issue resolved, thanks to @lazaridiscom

**Comment by serebrov** [comment]
Just for reference - the same solution above can be used to start the debugger from command line and debug in [node inspector](https://nodejs.org/en/docs/inspector/) (in Chrome dev tools):

```
npm install truffle-core
node --inspect-brk ./node_modules/truffle-core/cli.js test test/test_to_debug.js
```

- Open `chrome://inspect` page and click the "Open dedicated DevTools for Node" link.
- We should see the `cli.js` file with execution paused on the first line.
- Add the test sources into the inspector: click the "Filesystem" on the left and then "Add folder to workspace".
- Browse to the folder with tests and add it.
- Open the file with the test to debug and set the breakpoint, continue the execution until it reaches the breakpoint
- Now you can step through your test, inspect variables, etc

**Comment by tjanson** [comment]
I’m not sure if Truffle’s folder / project structure changed, but in any case the CLI runner is present at this path now: `node_modules/truffle/build/cli.bundled.js`
