### ISSUE TITLE
Error: CONNECTION ERROR: Couldn't connect to node http://127.0.0.1:8545.

### ISSUE THREAD

**Issue by launchico** [trufflesuite/truffle#828]
---------------------------

## Issue

ganache-cli is up and running, web3 is able to connect to it, but truffle can't deploy, saying that it is not able to connect to it. Also, stack trace is not working, here's what appeared in the console in the place where the stack trace should've be appeared: '_`^  this.stack = (new Error(message)).stack;`_'

## Steps to Reproduce

1. ganache-cli -u 0 --gasLimit 6721975 --gasPrice 100000000000
2. truffle compile
3. truffle migrate --network development --reset 

## Environment

* Operating System:  **ubuntu**
* Truffle version **v4.1.0 (core: 4.1.0)**:
* node version **v9.4.0**:
* npm version **5.6.0**:

**Comment by launchico** [comment]
That was a strange bug that disappeared by itself :p

**Comment by smurf123444** [comment]
i had same issue, was due to timeout of ganache after throwing a lot of transactions at it during a test. Currently in the middle of "restarting" it now

**Comment by aaronmgdr** [comment]
been fighting with this for a few days myself. ganache is clearly running but tests keep not being able to connect

**Comment by samuelmanzanera** [comment]
I got the same behavior but I have to restart a couple times, which is really annoying. 
Any particular reason for this thing to happen ?
