### ISSUE TITLE
Debug transaction on mainnet or ropsten with truffle

### ISSUE THREAD

**Issue by woniesong92** [trufflesuite/truffle#833]
Is it possible to debug a tx on ropsten with truffle?
I wanted to do something like this:

```
truffle debug <tx_number> --network ropsten
```

**Comment by gnidan** [comment]
This should work out of the box, provided the node you are using supports `debug_traceTransaction`. If you're running geth locally, you'll need to use the `debug` RPC API.

**Comment by EralpB** [comment]
@gnidan what are the public nodes that support this? Does infura support it? I'm getting an error but I'm not sure if that's the cause.
