### ISSUE TITLE
Sending balance from contract to contract fails with revert

### ISSUE THREAD

**Issue by carlosero** [trufflesuite/truffle#834]
## Issue

Sending balance from one contract to a second contract's fallback function (`function () external payable`) fails.

I have two contracts, FirstContract and SecondContract, when sending balance to a payable external function in FirstContract it works, but then sending from FirstContract to SecondContract returns error with revert. There is absolutely no require/assert validations at all.

I did a repository with the issue for ease of reproducing it.

I did search for it but everyone seems to have a different problem than this.

I'm very sorry if this is trivial and everyone knows how to fix it, but this is driving me crazy. First time I've ever submitted an issue somewhere.

## Steps to Reproduce

1. Clone https://github.com/carlosero/truffle-issue
2. Run `truffle test`
3. Will return error "revert".

## Expected Behavior

SecondContract receives the balance from FirstContract.

## Actual Results

SecondContract rejects the transaction (fallback external transaction).

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: --
* Truffle version (`truffle version`): Truffle v4.0.7 (core: 4.0.7)
* node version (`node --version`): v7.10.0
* npm version (`npm --version`): 4.2.0

**Comment by carlosero** [comment]
Closing this myself. This was rather simple. Solution if anyone has the same issue ever:
When transfering from a contract to another using .transfer, and using fallback function, gas by default will be 2300, which will revert any kind of operation that uses more gas than that.

https://consensys.github.io/smart-contract-best-practices/recommendations/#keep-fallback-functions-simple

**Comment by cgewecke** [comment]
@carlosero Yes exactly. Thanks for producing such a clear example repository - this is a model bug report for what it's worth :) Glad you solved it.
