### ISSUE TITLE
Modifying a base contract doesn't trigger recompilation of derived contracts.

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#839]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Modifying a base contract doesn't trigger recompilation of derived contracts.

## Steps to Reproduce

1. Copy `Alpha.sol` and `Beta.sol` from https://github.com/ethereum/solidity/issues/3675 to a new Truffle project's `contracts` directory.
2. In the project directory, `truffle compile`.  
3. To Alpha.sol, add the following before the final closing curly brace: 

        function newFunctionInBaseContract(uint newValue) public {
            secondField = newValue;
        }

4. In the project directory, `truffle compile` again, as many times as you want.  
5. Inspect ABI of `Beta` in `build/contracts/Beta.json`.

## Expected Behavior

The output from `truffle compile` should be:   

> Compiling .\contracts\Alpha.sol...
> Compiling .\contracts\Beta.sol...
> Writing artifacts to .\build\contracts

ABIs in `Alpha.json` and `Beta.json` should both contain `newFunctionInBaseContract`.

## Actual Results

The output from `truffle compile` is:   

> Compiling .\contracts\Alpha.sol...
> Writing artifacts to .\build\contracts

and while `Alpha.json` contains the ABI including `newFunctionInBaseContract`, `Beta` does not.

## Environment

* Operating System: Windows 10
* Ethereum client: N/A 
* Truffle version (`truffle version`): Truffle v4.0.4 (core: 4.0.4)
* solidity version: Solidity v0.4.18 (solc-js)
* node version (`node --version`): v9.3.0
* npm version (`npm --version`): v5.6.0

**Comment by cgewecke** [comment]
@wbt Excellent thank you. Will write a regression test for this and look for a fix.

**Comment by wbt** [comment]
Whoops, on slightly closer inspection this should be on truffle-compile.  I moved it there. https://github.com/trufflesuite/truffle-compile/issues/47
