### ISSUE TITLE
When trying to deploy to a node that is not fully synced, get error: exceeds block gas limit

### ISSUE THREAD

**Issue by litch** [trufflesuite/truffle#840]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The error message when trying to deploy to a geth node that is not fully synced yet is incorrect:

`Error: exceeds block gas limit`

This led me to spend a couple hours trying to dig and research about what could by wrong with my gas settings, trying lots of gas settings, confirming that I could deploy on testrpc and rinkeby, and then being confused that I still couldn't deploy on mainnet.

## Steps to Reproduce

- Start a geth node syncing (maybe rename your chaindata directory first)
- Try to deploy any contract (I was trying to just deploy `Migrations.sol` in this case)

## Expected Behavior

Success, or an error message about needing to wait for the node to sync

## Actual Results

```
truffle migrate --network mainnet
Using network 'mainnet'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: exceeds block gas limit
```

## Environment

* Operating System: Mac OS X
* Ethereum client: geth 1.8.2
* Truffle version (`truffle version`): v4.1.0 (core: 4.1.0) & v4.1.3 (core: 4.1.3)
* node version (`node --version`): 8.9.1
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@litch This error comes from the client and Truffle reports it. Agree that it's not helpful but Truffle's current ability to evaluate the client state is limited to faithfully reflecting the signals it emits. For what it's worth, there's confusion over this response everywhere - [here's a case](https://github.com/ethereum/mist/issues/1660) at Mist.  

Thank you for opening this - it will make it much easier for someone searching the error to figure out what might be going on in their local environment. 

That said, I'm going to slightly rename the issue and begin tracking this over at `truffle-migrate` where we are in the planning stages of a major upgrade.  More helpful error management will be a core focus.
