### ISSUE TITLE
 Java smart contract wrappers

### ISSUE THREAD

**Issue by OfStone** [trufflesuite/truffle#842]
Hi,
i've a problem to generate the wrapper code using web3j’s command line tools.

I compile the smart contract using solc, and then i use 
web3j solidity generate /path/to/<smart-contract>.bin /path/to/<smart-contract>.abi -o /path/to/src/main/java -p com.your.organisation.name
as shown in the documentation.
someone can explain me the procedure in a simple way? I'm a beginner.

thank you

**Comment by cgewecke** [comment]
@OfStone What documentation are you referring to?

**Comment by OfStone** [comment]
@cgewecke https://docs.web3j.io/smart_contracts.html#smart-contract-wrappers
I just managed to create the wrapper code. This is the problem now. I want to interact with my smart contract deployed on Ganache. Do you know if it possible? The method " .load() " wants five arguments, one of this is "Credential". To create credential i have to insert the path of the Ethereum wallet and the password; but Ganache' accounts have not password, and i don't need an Ethereum wallet.

**Comment by cgewecke** [comment]
@OfStone I think this issue is best pursued at `web3j`. There are a number of open requests for help about wrapping Truffle contracts in that repository [here](https://github.com/web3j/web3j/issues?utf8=%E2%9C%93&q=truffle).
