### ISSUE TITLE
Zeppelin Tutorial token balance is zero on Rinkeby

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#843]
I deploy http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin
But have problem: Zero balance.
![alt text](http://www.picshare.ru/uploads/180312/6UHx9s7VQG.jpg)
I use rinkeby network.
```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
```
* Operating System: Ubuntu 16.04
* Ethereum client: geth 1.8.2
* Truffle version v4.1.0 
* node version (`v9.4.0`):
* npm version (`5.7.1`):

**Comment by freshonline** [comment]
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x17f6fc30d628ed0db65d3ab926383920e891a3632ff092612e9e3fc72488de3a
  Migrations: 0x4222ed30cfe1417b23a83130059476dd4b2f8a65
Saving successful migration to network...
  ... 0x02847b0f2f081a9f4458e0240de02f942de9b10cc658b26d642f7e84c93cb0c4
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing TutorialToken...
  ... 0x74af3a3916968f9a5ddbc08396963af7c37f842d9b6d1e62f6c2ff0c485110e6
  TutorialToken: 0x1232e0aa7a542b1daeabd4890a4566286a621d02
Saving successful migration to network...
  ... 0x5874809821192b79c415aff12d9ad81658da3cb001b3fec35ab8de038c178666
Saving artifacts...
```

**Comment by freshonline** [comment]
Why? Is this my fault or a bug?
cat TutorialToken.sol
```
pragma solidity ^0.4.18;

import 'zeppelin-solidity/contracts/token/ERC20/StandardToken.sol';

contract TutorialToken is StandardToken {

string public name = 'TutorialToken';
string public symbol = 'TT';
uint8 public decimals = 2;
uint public INITIAL_SUPPLY = 12000;

function TutorialToken() public {
  totalSupply_ = INITIAL_SUPPLY;
  balances[msg.sender] = INITIAL_SUPPLY;
 }

}

```

**Comment by dlldll** [comment]
hello，have you solved your problem?I got the same issue

**Comment by freshonline** [comment]
No, problem do not solved.

**Comment by tyndallm** [comment]
I suspect you maybe deploying to a local ganache test network instead of Rinkeby. Typically you would configure your truffle.js config file to have multiple networks, creating a separate "rinkeby" entry alongside "development": http://truffleframework.com/docs/advanced/configuration#networks You can also specify `network_id: '4'` which is Rinkeby

If you are running Geth locally on port 8545 is it connected to Rinkeby? Does the Geth console show your contract being deployed? Is your Geth account "unlocked"?

Alternatively if you don't want to run Geth locally, you could use Infura but that requires a bit of extra setup. The config would look something like this:
```
rinkeby: {
    provider: function() {
      return new HDWalletProvider(mnemonic, "https://rinkeby.infura.io/");
    },
    network_id: '4',
  },
```

**Comment by freshonline** [comment]
This rinkeby:
```
geth --rpc --rinkeby --rpcapi db,eth,web3,net,admin,miner,personal --fast --datadir /home/testnet/rinkeby --keystore /home/testnet/.ethereum/keystore --mine --minerthreads 1 --unlock 0xd97147e5663e83adeb103c84de3ee1a6d19e54fa --password /home/testnet/pass
```
```
netstat -lptun | grep 8545
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      700/geth
```
How can i check my contract in geth console?

**Comment by cgewecke** [comment]
@tyndallm Thanks so much for helping @freshonline. 

@freshonline: Did @tyndallm's suggestion resolve things for you? Did you get this to work with Ropsten a few weeks ago? 

> How can i check my contract in geth console?

A guide to using the geth console can be found [here](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console)

**Comment by cgewecke** [comment]
Closing for housekeeping / lack of response. Thanks all.

**Comment by nbunruh** [comment]
If you deployed via Ganache, be sure to import the private key that belongs to the account you deployed the contract with into Metamask. Once imported, just refresh the page and you should see the 12000 TT balance.

**Comment by zhaozhiming** [comment]
Same problem. Have any progress?

**Comment by zhaozhiming** [comment]
@freshonline I find the problem reason. I think you make the same mistake like me.
Your token contract is `0x1232e0aa7a542b1daeabd4890a4566286a621d02`, not the `0x4222ed30cfe1417b23a83130059476dd4b2f8a65`.  
You can find your rinkeby token here: https://rinkeby.etherscan.io/token/0x1232e0aa7a542b1daeabd4890a4566286a621d02.
It's perfectly no problem.

```js
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x17f6fc30d628ed0db65d3ab926383920e891a3632ff092612e9e3fc72488de3a
  Migrations: 0x4222ed30cfe1417b23a83130059476dd4b2f8a65
Saving successful migration to network...
  ... 0x02847b0f2f081a9f4458e0240de02f942de9b10cc658b26d642f7e84c93cb0c4
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing TutorialToken...
  ... 0x74af3a3916968f9a5ddbc08396963af7c37f842d9b6d1e62f6c2ff0c485110e6
  TutorialToken: 0x1232e0aa7a542b1daeabd4890a4566286a621d02
Saving successful migration to network...
  ... 0x5874809821192b79c415aff12d9ad81658da3cb001b3fec35ab8de038c178666
Saving artifacts...
```
