### ISSUE TITLE
Is it possible to avoid re-running migration scripts on every test?

### ISSUE THREAD

**Issue by ivica7** [trufflesuite/truffle#847]
I have time-consuming migration scripts, which take some time to deploy. 

The documentation says:
> Truffle will re-deploy all of your migrations at the beginning of every test file to ensure you have a fresh set of contracts to test against.

However, most of my tests are pure unit tests of single contract instances, which are separately deployed in the test itself, hence, they do not have any dependencies to contracts deployed via the migration scripts.

**Question**: Is there a way to avoid migration scripts being (re-)run on test?

**Comment by ngyam** [comment]
I am also interested in something like this
