### ISSUE TITLE
in tests Conract.deployed() not returning the test-specific instance deployed in the migration of the test

### ISSUE THREAD

**Issue by ivica7** [trufflesuite/truffle#848]
Step 1. ``truffle migrate``
... Contract.deploy() called in the migration script ...

Step 2. ``truffle test``
... migration scripts are rerun, but in test code Conract.deployed() returns the instance from the first step...

Is this working as designed? I thought every test will run in isolation.

* Operating System: macos 10.13.3
* Ethereum client: ganache-cli 6.1.0
* Truffle 4.1.3
* node 8.10.0
* npm 5.6.0

**Comment by Pedro-vk** [comment]
I've seen the error in other situation:
- Clean `build` folder.
- Using `truffle test` run a `ContractName.deployed()`.
