### ISSUE TITLE
`truffle test` uses old sources for /contracts

### ISSUE THREAD

**Issue by ScJa** [trufflesuite/truffle#851]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running `truffle test` old sources for smart contracts are being used. If this happens, the old build is still used if running `truffle compile -all`. Only way to fix it I have found is deleting the build folder.

E.g. if I add an additional event, emit it and add a test for the event, the test will fail because the event does not exist. This happens to me about 1 in 10-20 times when changing contracts and running tests afterwards.

What might be important to note is that for my tests I don't use deployed contracts and I have no migrations implemented. I test all smart contracts by created them like so `SmartContract.new()`.

## Steps to Reproduce

Issue is not reliably reproduce-able and only happens every 1 in 10-20 times.

1) Have a successful test which uses smart contract function.
2) Run `truffle compile -all`.
3) Delete said smart contract function from source file.
4) Run `truffle test`.

## Expected Behavior

Testing should produce an error because the function does not exist anymore.

## Actual Results

The test sometimes still passes because the old source is still used. If this happens, even running `truffle compile -all` again then test again will not fix the issue.

## Environment

* Operating System: ubuntu 16.04 LTS
* Ethereum client: Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* Truffle version (`truffle version`): Truffle v4.0.0 (core: 4.0.0)
* node version (`node --version`): v6.13.0
* npm version (`npm --version`): 3.10.10

**Comment by ScJa** [comment]
Issue also present in v4.1.3 and on a Windows operating system.

**Comment by fdouglis** [comment]
I'm a bit confused by this bug report, because I was told by a truffle developer that "truffle test" compiles a new version and ignores anything you may previously have done with "truffle compile" or "truffle migrate".  Maybe that only applies to solidity tests rather than JS?

**Comment by ScJa** [comment]
If you run truffle compile once before, truffle test (tries) to re-compile only the .sol files which have had changes since the last test run.
If you have never run truffle compile before, truffle test will always re-compile every .sol file - even completely unrelated once.

This is at least the behaviour judging by the console output, actual might be different.

**Comment by fdouglis** [comment]
ScJa, perhaps things have changed since I last installed truffle  2-3 weeks ago, but I definitely saw "test" recompiling things regardless of whether I'd explicitly compiled.  And similarly, running "migrate" made no difference, because it'd deploy a fresh version for the test.

**Comment by ScJa** [comment]
Thanks for bringing it up, I have tested the exact behaviour again and found out it is different than to what I described. I found out three different cases.

1.  If you run `truffle compile` and afterwards run `truffle test` with NO file changed in between only the Migrations.sol file will be re-compiled.
2.  If you run `truffle compile` and afterwards run `truffle test` with ONE file changed in between all .sol files which are used in the test cases will be re-compiled, but not saved in the build folder. This means it will always re-compile even if there are no changes afterwards.
3.  If you don't run `truffle compile` and have no build folder (or an empty one),  `truffle test` will re-compile every single .sol file (also ones which are not used by any tests) and save nothing in the build folder. 

Overall the behaviour 2 and 3 seem inconsistent to me and can lead to a lot of unnecessary compiling, but I'm not sure how this all relates to my original issue.

**Comment by cgewecke** [comment]
@ScJa We think this bug is fixed with `4.1.5`.  Current behavior should be that if a file has been changed, `test` will compile all the files that are connected to that file in an inheritance chain. Hoping to minimize this set in an upcoming release, but at the moment, the current compilation level is necessary.

Closing, please re-open if you continue to have problems with this.
