### ISSUE TITLE
Can't deploy to the mainnet, with the same config as Ropsten, and succeeds with dry-run

### ISSUE THREAD

**Issue by andrisole92** [trufflesuite/truffle#855]
- yes, I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't deploy to the mainnet. Always getting errors such as:
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
or
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
.

## Steps to Reproduce

I have the same config for Ropsten and mainnet:
```
ropsten: {
            provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/" + infura_apikey),
            network_id: 3,
            gasPrice: 3000000000,
            gas: 4500000

        },
        live: {
            provider: new HDWalletProvider(mnemonic, "https://mainnet.infura.io/" + infura_apikey),
            network_id: 1,
            gasPrice: 2000000000,
            gas: 6000000
        },
```
The same contract can be deployed to Ropsten, but can't to Mainnet. It also succeeds on `--dry-run`
## Expected Behavior

I expect the contract to be deployed.

## Actual Results
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
or
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.

## Environment

* Operating System: MacOS
* Ethereum client: MainNet Infura Api Key
* Truffle version (`v4.1.0-beta.0`):
* node version (`6.1.12`):
* npm version (`5.7.1`):

**Comment by cgewecke** [comment]
@andrisole92 Could you try this again after wrapping both of your provider declarations in a function call as suggested [here](http://truffleframework.com/tutorials/using-infura-custom-provider#configure-your-truffle-project)? e.g:
```javascript
live: {
  provider: function() {
     return new HDWalletProvider(mnemonic, "https://mainnet.infura.io/" + infura_apikey)
  },
  network_id: 1,
  gasPrice: 2000000000,
  gas: 6000000
},
```

**Comment by cgewecke** [comment]
@andrisole92 Closing this for housekeeping. Please re-open if you continue to see this after wrapping the provider as shown above.

**Comment by andrisole92** [comment]
Hey guys, 

Sorry, it is really bizarre, but I have managed to deploy the contract. And not sure what was wrong?

Probably gas estimations were not very good... I always had some dollars in my address and was not able to deploy, so sometimes it was burning 5-6 dollars. 

But finally, it cost me around 3-4 dollars for successful deployment.
