### ISSUE TITLE
Invalid JSON RPC response: "" (truffle-wallet-provider)

### ISSUE THREAD

**Issue by vrogojin** [trufflesuite/truffle#858]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I get this pretty standard non-informative error when trying to test or console with truffle Invalid JSON RPC response: ""
Yesterday it worked perfectly fine. But today it does not. I did not change any configuration in truffle.js. And yes, I runt testrpc.
and yes, truffle DOES connect to testrpc.
I have logs from testrpc that confirm connection
Account unlock does not help
I did call testrpc with testrpc --account= ... -p 7547 --unlock 0
I can telnet to testrpc port with no problem

## Steps to Reproduce

In one terminal run
` testrpc --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e1c, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e11, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e12, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e13, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e14, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e15, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e16, 1000000000000000000000000" --account="0xf84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e17, 1000000000000000000000000" --account="0x9644f68b5697da9a4c05b3c9707ce2dcc9be56313ff4f2b043a5150f809aa6d8, 1000000000000000000000000" --account="0xc4d1466786fcb0b9b827b344ad5bab14c8cb1787dc22889ac886852a6be2182c, 1000000000000000000000000" --account="0x5d114d3e6bf7a6d9159f105bba99ae7297b1fed5e1629ba5391dfbcc2d176cd0, 1000000000000000000000000" --account="0xc3734876efbaf2c49a03720bde9277d64ff4b216954be7c001860f0f816f4a84, 1000000000000000000000000" --account="0x1de98ba4bdc07bf3f067b0fe8686307572ab2025fdc92ee35515eb9665bfff7c, 1000000000000000000000000" --account="0xbcaf0aee0ee511a707757972ba9c14c50fb600ee3ce5c6b4b31cffe91e22105a, 1000000000000000000000000" -p 7547`
In another terminal run `truffle test` or `truffle console`

## Expected Behavior

It should test or go to console respectively

## Actual Results

instead, truffle generates the error message
`truffle console
truffle(development)> /home/vrogojin/truffle/build/cli.bundled.js:128857
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_I

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/myproject/node_modules/truffle-wallet-provider/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/home/myproject/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/myproject/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/myproject/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/home/myproject/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/home/myproject/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
`
testrpc generates

`EthereumJS TestRPC v6.0.3 (ganache-core: 2.0.2)

Available Accounts
==================
(0) 0x0249f55a1294105933bf8fd88160bb022440dd6a
(1) 0x95fe7c3bc8ca2b08bc12c903322bdfb37a506247
(2) 0x29d885b0cbcc949460b646a4c94b1d9501a4b841
(3) 0x0f95593d1b94ac8cb31ba353d9b35f42bd95e378
(4) 0x542f28a57f4e8c21037d6d1e1a3bf6b85d130f19
(5) 0xba267301728d86e1e43bd7a0e979590e9008fa09
(6) 0xdb449c910e0b5098e7a33f1c29cfdcfbb54f4586
(7) 0xeb7d2e6778f8b6b7291f225f3a45adfc2f41e163
(8) 0xd12fc390435a8ea75efb64d6de5a7a4671d2e7b9
(9) 0x3c4358f12f442d3afa217bc8009020bdec43c431
(10) 0x2b4c79f21ec06a8c44b86b5687bb6807125ee60a
(11) 0xa811205dc71cf6973882a75d448f376f7fff30fb
(12) 0xc041dfb212bd2bd661ee82e5b8b3a0caae6a98ec
(13) 0x5afad58d966111181e81f3600696f2338adc69ac

Private Keys
==================
(0) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e1c
(1) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e11
(2) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e12
(3) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e13
(4) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e14
(5) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e15
(6) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e16
(7) f84e9b54634b7a970ea64e11443b466758d33ae7ef3f9066b52457fc27a37e17
(8) 9644f68b5697da9a4c05b3c9707ce2dcc9be56313ff4f2b043a5150f809aa6d8
(9) c4d1466786fcb0b9b827b344ad5bab14c8cb1787dc22889ac886852a6be2182c
(10) 5d114d3e6bf7a6d9159f105bba99ae7297b1fed5e1629ba5391dfbcc2d176cd0
(11) c3734876efbaf2c49a03720bde9277d64ff4b216954be7c001860f0f816f4a84
(12) 1de98ba4bdc07bf3f067b0fe8686307572ab2025fdc92ee35515eb9665bfff7c
(13) bcaf0aee0ee511a707757972ba9c14c50fb600ee3ce5c6b4b31cffe91e22105a

Listening on localhost:7547
net_version
`
## Environment

* Operating System: Ubuntu 14.04.5 LTS
* Ethereum client: EthereumJS TestRPC v6.0.3 (ganache-core: 2.0.2)
* Truffle version (`truffle version`): v4.0.6 (core: 4.0.6)
* node version (`node --version`): v8.10.0
* npm version (`npm --version`): 5.6.0

**Comment by vrogojin** [comment]
Update: the issue seems to be cause by truffle-wallet-provider

**Comment by cgewecke** [comment]
@vrogojin Could you close here and open this over [there](https://github.com/crypedit/truffle-wallet-provider). Their engineer might have a better sense of what the problem might be. 

Feel free to re-open if you believe this problem definitely originates at Truffle & can be reproduced using `truffle-hdwallet-provider` rather than a 3rd party fork.

**Comment by cgewecke** [comment]
@vrogojin Going to close for housekeeping - please re-open if you still need help with this. Thanks!
