### ISSUE TITLE
Truffle migration bug - Intrinsic gas too low

### ISSUE THREAD

**Issue by ProphetDaniel** [trufflesuite/truffle#864]
Because the original [issue](https://github.com/trufflesuite/truffle/issues/857) was inadvertedly closed by @cgewecke, I'm writing it back here again.

**Comment by ProphetDaniel** [comment]
This time to compensate contributor's laziness I will follow strictly instructions and present the canonical code from [here](http://truffleframework.com/tutorials/using-infura-custom-provider).

**Comment by ProphetDaniel** [comment]
> Could you explain what is happening here in your truffle.js?

This is a function that returns the following:
```javascript
new HDWalletProvider(process.env.MNEMONIC, process.env.MAINNET_ENDPOINT+`eth-api`, 0, 1, process.env.PASSWORD);
```

where the following parameters are defined within .env file:
- MNEMONIC
- MAINNET_ENDPOINT
- PASSWORD

In my setup MAINNET_ENDPOINT is a custom geth running endpoint which I have privately set for my project. 

---

In order to allow people to reproduce the problem exactly as I currently face I changed `truffle-config.js` to use Infura's endpoint as can be seen [here](https://github.com/ClassicDelta/Smart-Contracts/blob/master/truffle-config.js).

So now provider renders:
```javascript
new HDWalletProvider(process.env.MNEMONIC, `https://mainnet.infura.io/${process.env.INFURA_API_KEY}`, 0, 1, process.env.PASSWORD);
```

And the following parameters need to be defined within .env file:
- MNEMONIC
- INFURA_API_KEY
- PASSWORD

According to the following example:
```
# configure your infura api key (not technically required)
INFURA_API_KEY=xXxXxXxXxXxXxXxXxXxX

# change the mnemonic that your hd wallet is seeded with
MNEMONIC="example example example example example example example example example example example example"

# change the password with the password you have encrypted your hd wallet with
PASSWORD="passwordExample"
```

> Is it possible there is some problem with the way `truffle-safe-hdwallet-provider` is working?

Mos likely not. Because the same problem happens when utilizing `truffle-hdwallet-provider` for unencrypted mnemonic phrase and exactly as presented by [tutorial](https://infura.io/docs/gettingStarted/chooseaNetwork).

---

> One way to debug this might be to use the default truffle-wallet deploying to a testnet and see if that succeeds?

Yes, and it works flawlessly.
After starting `truffle develop` in one terminal and `truffle migrate` in another, here is the successful result:

```bash
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xe1b191ce722bc3ec922071c396a627365f16ca69c0b2a7d2ce5830d4f1e6881a
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing ClassicDelta...
  ... 0x66988f39a95507976ee6362a55d66c11dd7513e2818af0bd127f79aa17979f66
  ClassicDelta: 0xf12b5dd4ead5f743c6baa640b0216200e89b60da
Saving artifacts...
```

**Comment by cgewecke** [comment]
@ProphetDaniel Could you check or post your `genesis.json`? There's a report similar to yours [here](https://stackoverflow.com/questions/42589091/ethereum-truffle-metacoin-fails-with-intrinsic-gas-too-low) where the underlying issue was the gas limit in the client config.

**Comment by ProphetDaniel** [comment]
@cgewecke As I said I have tested with truffle develop testnet and also with my own private net which I started with the following genesis block:

```javascript
{
    "nonce": "0x0000000000000042",
    "difficulty": "0x4000",
    "alloc": {
        "d1900da6020324e24327c7b5b16526f201929fe3": {
            "balance": "5000000000"
        },
        "9eeb4dce9837e6a4461e3797abe3d10a8a5bdbb5": {
            "balance": "5000000000"
        }
    },
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0xd1900da6020324e24327c7b5b16526f201929fe3",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x",
    "config": {
        "eip155Block": 0,
        "eip158Block": 0,
        "homesteadBlock": 0,
        "chainId": 23
    },
    "gasLimit": "0x8000000"
}
```

**Comment by chengtaowan** [comment]
# 本月要做的任务

- [ ] 完成图片

- [x] 完成部署工具的设置

**Comment by cgewecke** [comment]
cc: @ProphetDaniel did you ever resolve this?

**Comment by cgewecke** [comment]
Closing due to lack of response. @ProphetDaniel Please feel free to re-open if you're still facing this or post your solution here if you found one so other users facing this error can benefit from your work.
