### ISSUE TITLE
migration only saves first deployed contract address

### ISSUE THREAD

**Issue by okwme** [trufflesuite/truffle#868]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My migration deploys a few contracts in a row. The json files get createded with ABI and bytecode, but only the first contract deployed gets the deployed address saved under the network in the artifacts.

## Steps to Reproduce
```
var FirstContract = artifacts.require("./FirstContract.sol");
var SecondContract = artifacts.require("./SecondContract.sol");

module.exports = async function (deployer, helper, accounts)  {
  try {
    await deployer.deploy(FirstContract)
    let firstContract = await FirstContract.deployed()

    await deployer.deploy(SecondContract, firstContract.address)
    let secondContract = await SecondContract.deployed()
  } catch (error) {
    console.log(error)
  }
}
```

## Expected Behavior

I expect for the artifacts created at `./build/contracts/FirstContract.json` and `./build/contracts/SecondContract.json` to contain the deployed address under the `networks` key like:
```
...,
  "networks": {
    "5777": {
      "events": {},
      "links": {},
      "address": "0x24383b21d4a08c8c835fd192e410299bcf141ad6"
    }
  },
...
```
## Actual Results

This only occurs for `FirstContract.json`

## Environment

* Operating System: Mac OS 10.12.5 (16F73)
* Ethereum client: Ganache 1.1.0-beta.1
* Truffle version (`truffle version`): v4.0.6
* node version (`node --version`): v7.6.0
* npm version (`npm --version`): 5.6.0

**Comment by okwme** [comment]
Figured it out:
```
var FirstContract = artifacts.require("./FirstContract.sol");
var SecondContract = artifacts.require("./SecondContract.sol");

module.exports = async function (deployer, helper, accounts)  {
  deployer.then(async () => {
    try {
      await deployer.deploy(FirstContract)
      let firstContract = await FirstContract.deployed()

      await deployer.deploy(SecondContract, firstContract.address)
      let secondContract = await SecondContract.deployed()
    } catch (error) {
      console.log(error)
    }
  })
}
```

**Comment by Pedro-vk** [comment]
@okwme Why did you closed? I have the same problem. Do you know any solution?

**Comment by marsrobertson** [comment]
@Pedro-vk check this out: https://forum.openzeppelin.com/t/deploying-2-identical-contracts-and-referencing-them-in-the-future-upgrades/5287/3?u=marsxr

(2.5 years later)
