### ISSUE TITLE
Quorum : private deployment fails 

### ISSUE THREAD

**Issue by paliwalg** [trufflesuite/truffle#877]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Trying to deploy a contract privately specifying 13 constellation public keys of 13 nodes. 
If fails with error message as "Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: illegal base64 data at input byte 8" 

It works fine with smaller(2-3) number of constellation public keys.

Also I am able to deploy the same contract privately to all the nodes using custom written deployer script.

## Environment

* Operating System: Ubuntu 
* Ethereum client: geth 1.7
* Truffle version (`truffle version`): v4.1.3
* node version (`node --version`): v6.9.1
* npm version (`npm --version`): 4.5.0

**Comment by cgewecke** [comment]
@paliwalg Thanks for opening and for isolating the issue so clearly. 

I think this should be raised at Quorum. `illegal base64 data at input byte 8` comes from the client and as far as I can tell has no antecedents outside this issue, other than [here](https://github.com/tendermint/tendermint/issues/536#issuecomment-312788905) at Tendermint. It's just not something truffle can do anything about.

**Comment by cgewecke** [comment]
@paliwalg Apologies, how did you end up resolving the issue in #863? It seems like you were able to migrate successfully for some cases? If you could add some feedback there that would be great :)

**Comment by paliwalg** [comment]
Seems like timing issue, if I run the truffle deployer from the machine I am submitting transaction to, it works. Seems more of timing issue.

**Comment by paliwalg** [comment]
I am able to successfully perform the same steps and get the expected out with the web3.js deployer script. So I thought it should be truffle issue.

**Comment by cgewecke** [comment]
@paliwalg Ah ok! Are you using web3 1.0?
