### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by hskang9** [trufflesuite/truffle#880]
I would like to collaborate in the translation of the documentatiom in Korean as well as #801. Is it already done?

**Comment by cgewecke** [comment]
@hskang9 No, it's not done. At the moment we have no official translations and additionally we don't have infrastructure in place to support multi-lingual docs. This will require installing a [metal-smith](https://www.npmjs.com/package/metalsmith-multi-language) localization package.

I will ping you back here when this becomes possible. Thanks for opening!

**Comment by hskang9** [comment]
Great! I will make a pull request with translation using that module!

**Comment by flytux** [comment]
Much appreciated if I could collaborate with Korea translation as well.
