### ISSUE TITLE
Error: VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by chenwenwen11** [trufflesuite/truffle#884]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
I am just following the tutorial to create a very simple token and crowdsale contract with `Truffle` and `zeppelin-solidity`. When I try to migrate locally to Ganache client, I've encountered this issue which I do not know how to debug with this error message.
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```
I tried to search online, but the error message seems too generic for me analyse the cause.

## Steps to Reproduce
1. Clone this repository https://github.com/chenwenwen11/TestCrowdsale.git
2. terminal run: npm install -g truffle
3. cd to the TestCrowdsale
4. terminal run: npm install zeppelin-solidity
5. terminal run: npm install truffle-hdwallet-provider
6. Open Ganache
7. terminal run: truffle compile
8. terminal run: truffle migrate

## Expected Behavior

Contract successfully migrated to Ganache 

## Actual Results
<img width="1023" alt="screen shot 2018-04-04 at 11 09 51 pm" src="https://user-images.githubusercontent.com/38068764/38316437-536b87d0-385d-11e8-818a-76be5cefefd6.png">

## Environment

* Operating System: macOS High Sierra
* Ethereum client: web3
* Truffle version (`truffle version`): v4.1.3
* node version (`node --version`): v9.8.0
* npm version (`npm --version`): 5.6.0
* solidity version: v0.4.19
* zeppelin-solidity version: 1.7.0
* Ganache version: 1.0.2

**Comment by cgewecke** [comment]
@chenwenwen11 `revert` in a migration usually means that a condition you've set using a `require` in the contract's constructor isn't being met. In this case, TestCrowdsale has a `require` that says:
```
require(_goal <= _cap);
```
The values being passed in are: cap: 2 ETH, goal: 500 ETH. 

More on how `require` works can be found at the Solidity docs [here](https://solidity.readthedocs.io/en/v0.4.21/control-structures.html#error-handling-assert-require-revert-and-exceptions)

**Comment by chenwenwen11** [comment]
@cgewecke Thank you so much for your reply. I did not notice I have misplace the values for input parameters. It works now! Thank you for your help!

**Comment by PopTudor** [comment]
lol @cgewecke thank you too!
