### ISSUE TITLE
Migrations -f argument is ignored

### ISSUE THREAD

**Issue by craigwilliams84** [trufflesuite/truffle#886]
## Issue

Migrations -f argument is ignored (works in 4.1.3 but not 4.1.4/5)

## Steps to Reproduce

- Run `truffle migrate -f 2` in a project with multiple migrations files.

## Expected Behavior

Only migration script 2 should be run.

## Actual Results

All migration scripts are run.

## Environment

* Operating System: MacOS 10.13.2
* Ethereum client: ganache-cli 6.0.3
* Truffle version (`truffle version`): 4.1.5
* node version (`node --version`): 8.7.0
* npm version (`npm --version`): 5.6.0

**Comment by craigwilliams84** [comment]
The code isn't currently public, but I have created a simple dummy project that reproduces the issue.

[](https://github.com/craigwilliams84/truffle-test)

**Comment by cgewecke** [comment]
@craigwilliams84 Have opened a [PR](https://github.com/trufflesuite/truffle-core/pull/127) fixing this. 

Unfortunately I don't see a great interim workaround - a PR for `4.1.5` created a conflict in the way the options are interpreted and `-f` is currently only being parsed as a boolean.  

Thanks so much for reporting and for providing a reproduction case.

**Comment by craigwilliams84** [comment]
No problem at all, thanks for looking into it so quickly.

**Comment by gnidan** [comment]
That linked PR been released in Truffle v4.1.6. Let us know if this solves the problem! Thanks!

**Comment by fawrn** [comment]
truffle version
Truffle v4.1.6 (core: 4.1.6)
Solidity v0.4.21 (solc-js)
Same issue still ignoring

**Comment by cgewecke** [comment]
@fawrn Have just tested `4.1.6` against the example @craigwilliams84 produced for this issue above and `-f` is working as expected. If you have a chance could you run that and a) see if it works on your machine, b) identify any differences between that case and yours? 

I'm on OSX.
