### ISSUE TITLE
Is debugging mainnet transactions with Infura possible?

### ISSUE THREAD

**Issue by chapati23** [trufflesuite/truffle#890]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Can't debug mainnet transactions using infura

## Steps to Reproduce

```js
// truffle.js
const HDWalletProvider = require('truffle-hdwallet-provider')

module.exports = {
  networks: {
    mainnet: {
      provider: new HDWalletProvider(
        'some randomly made up mnemonic',
        'https://mainnet.infura.io/'
      ),
      network_id: '1'
    }
  }
}
```

## Expected Behavior

```sh
truffle debug <tx-id>  --network mainnet
```

should have debugged my transaction

## Actual Results

Got an error

![screen shot 2018-04-11 at 12 24 09](https://user-images.githubusercontent.com/117495/38611189-4f1a8a7a-3d83-11e8-816e-2f1efc057e11.png)

## Environment

* Operating System: MacOS 10.13.4
* Ethereum client: Infura
* Truffle version (`truffle version`): v4.1.5
* node version (`node --version`): v9.8.0
* npm version (`npm --version`): v5.6.0

**Comment by cgewecke** [comment]
@chapati23 AFAIK Infura doesn't support the geth's debugging API, possibly for security reasons. The debugger requires that the client implement the [debug_traceTransaction](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction) endpoint and geth allows that method to pass arbitrary JS code in as an option and run it on the client as a trace processor. It would be risky for a public facing service to allow anyone to do that.
 
However, you should be be able to debug mainnet transactions via a local geth node by running `truffle debug 0x... --network mainnet`.

**Comment by chapati23** [comment]
@cgewecke thanks, that's what I feared. been syncing for a few hours already…

would it work with `geth --fast` (syncing only tx receipts and current state DB as far as i understand the docs) or do i need a _full_ full node locally?

**Comment by cgewecke** [comment]
@chapati23 It looks like it depends which transaction you want to inspect. There's a nice overview of this subject at the Geth docs [here](https://github.com/ethereum/go-ethereum/wiki/Tracing:-Introduction).

**Comment by chapati23** [comment]
Thanks @cgewecke, will give it a read and report back here after my local geth node is fully synced.

**Comment by chapati23** [comment]
Haven't finished syncing yet but I guess this paragraph from the docs answers my question:

> In order for an Ethereum node to reexecute a transaction, **it needs to have available all historical state accessed by the transaction**:
> * Balance, nonce, bytecode and storage of both the recipient as well as all internally invoked contracts.
> * Block metadata referenced during execution of both the outer as well as all internally created transactions.
> * Intermediate state generated by all preceding transactions contained in the same block as the one being traced.

This sounds like it'd only work with a full geth node which sadly is too big for a normal dev machine these days. Guess the best alternative would be to have a full geth node running on AWS.

**Comment by chapati23** [comment]
Can confirm for sure now. In fully synced `geth --fast` node, i get `Error: required historical state unavailable` when trying to run `debug.traceTransaction(<tx-id>)`.

was worth a shot.
