### ISSUE TITLE
Update Assert.sol to 0.4.21 and avoid compilation warnings 

### ISSUE THREAD

**Issue by luisfidelis** [trufflesuite/truffle#891]
## Issue

The contract Assert.sol within truffle's test environment has deprecated things according to solidity 0.4.21. Maybe it happens in other contracts too. 

## Steps to Reproduce

Create a test in solidity, import "truffle/Assert.sol" and run the test. 

## Actual Results

* Warning: Use of the "var" keyword is deprecated.
* Warning: Invoking events without "emit" prefix is deprecated.

## Environment

* Truffle version: 4.1.5

**Comment by snehasatya** [comment]
How to Update Assert.sol to 0.4.21

**Comment by luisfidelis** [comment]
Hey. 
To avoid the first warning, about the use of "var", you have to introduce the types on tuple assignments...
use 
`address a;
 uint256 b;
 address c;
 (a,b,c) = myFunction();
`
Instead of 
`var (a, b, c) = myFunction()`

To avoid the second warning, about the keyword "emit", just type it when fire contract events. For example: 
`emit LogSomething(var1, var2, ..., varN)`

**Comment by vzts** [comment]
Just for note, this already has been fixed and merged into truffle-core, but seems like it's not included in official build yet. See https://github.com/trufflesuite/truffle-core/pull/131

**Comment by cgewecke** [comment]
@luisfidelis Still a few warning in there sorry, they're new to `0.4.23` - sorry. But lots are gone. Going to close this, but we'll continue to revisit this.
