### ISSUE TITLE
Stop generating two config files

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#895]
I'd like to suggest that we remove the `truffle-config.js` file from our templates (Truffle boxes and the output of the `truffle init` command). It was only ever relevant on Windows, and we now have multiple documented workarounds such that it's not necessary.

http://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows

Also, it seems to confuse people, who don't understand why it's there.

I figure that if Truffle continues to accept the existence of a `truffle-config.js` in projects, but just doesn't ship one with new projects, then we can implement this without any breaking changes.

**Comment by tomcbean** [comment]
Why not just eliminate truffle.js and only recognize truffle-config.js? Works on all supported OSes.

**Comment by gnidan** [comment]
@tomcbean I would be in favor of that direction if there is broad community interest.

I think it's probably the way to go, since it avoids the collision altogether, but I worry about how much it would trip projects up, since `truffle.js` is so widespread.

Thoughts, any/all?

**Comment by bmmpxf** [comment]
Or a third option, which is to create a new file name entirely, such as `config.js` and grandfather everything in. Shorter and non-conflicting.

(I have a small bias against the length and redundancy of `truffle-config.js`, but I won't push against it if that's what we decide on.)

**Comment by gnidan** [comment]
@bmmpxf I'm not in favor of removing `truffle` from the name because many projects often have multiple tools' config files in the same directory. There's also a benefit looking at the source for a project, `truffle.js` immediately indicates that it's a Truffle project, so you know what you're looking at.

**Comment by bmmpxf** [comment]
@gnidan For sure, makes sense. I am much more in favor of retaining `truffle.js` anyway.

**Comment by axic** [comment]
Two alternative suggestions:
- `truffle/config.js`
- `truffle.config.js`

Does any of that clashes with Windows?

**Comment by bmmpxf** [comment]
@axic Both of those would be fine. The conflict is with the `truffle.cmd` file, the script that runs all of the Truffle commands. On Windows, `.js` has priority over `.cmd` by default when the extension isn't specified and both are on the path.

**Comment by axic** [comment]
@gnidan was this solved in the end?
