### ISSUE TITLE
Upgrade to solc v0.4.23

### ISSUE THREAD

**Issue by TovarishFin** [trufflesuite/truffle#897]
I know that the new version was just released today but I just wanted to check if there are any estimates on when a new version will be released supporting this. I ask because I have some frequently called functions that will cut gas costs in half with features in the new solc version.

We are also going to have a large set of contracts audited in 2 to 3 weeks. It would be great to be able to use the new features!

Side Note: Does anyone know if there are any breaking changes from `solc@0.4.21` if I were to just install `solc@0.4.22` directly in truffle?

Thanks!

**Comment by tomcbean** [comment]
Solc 0.4.22 also adds error reason strings for revert and require. This is a feature I've been waiting for a long time. Would be great to have truffle suite support soon.

**Comment by cgewecke** [comment]
@TovarishFin We opened PRs for bumping this morning. There's a small issue with `0.4.22` breaking the `truffle-debugger` which we have to resolve, but goal is to publish a patch w/ 0.4.22 ASAP - in the next couple of days hopefully.

**Comment by k06a** [comment]
`0.4.23` just released with fix:
> If a contract has both a new-style constructor (using the constructor keyword) and an old-style constructor (a function with the same name as the contract) at the same time, one of them will be ignored. There will be a compiler warning about the old-style constructor, so contracts only using new-style constructors are fine.

**Comment by cgewecke** [comment]
@k06a Ok great - we'll release with `0.4.23` this afternoon as long as everything runs clean and they list the release on Github [here](https://github.com/ethereum/solidity/releases).

**Comment by kingjerod** [comment]
@cgewecke Looks like it got released 🎉 😃

**Comment by cgewecke** [comment]
Thanks all! Thanks @TovarishFin for opening. Upgraded in `4.1.7`
