### ISSUE TITLE
Contracts are nor recompiled after enabling optimizer

### ISSUE THREAD

**Issue by melnikaite** [trufflesuite/truffle#899]
## Issue

Contracts are not recompiled after enabling optimizer. I know about `--all` but it'd be nice to recompile contracts after enabling/disabling optimizer or changing `runs`.

## Steps to Reproduce

`truffle compile`

Check length of `bytecode` in artefacts.

Add to config:
```
    solc: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
```
`truffle compile`

## Expected Behavior

Length of `bytecode` less than before

## Actual Results

Length of `bytecode` the same as before

## Environment

* Operating System: OS X
* Truffle version (`truffle version`): Truffle v4.1.6 (core: 4.1.6) Solidity v0.4.21 (solc-js)
* node version (`node --version`): v9.2.1
* npm version (`npm --version`): 5.8.0

**Comment by cgewecke** [comment]
@melnikaite Thanks for this idea. At the moment we don't keep track of the optimization level in the artifact but I believe this will be addressed in the next major release.
