### ISSUE TITLE
bug: contracts from npm packages cannot be found during migration

### ISSUE THREAD

**Issue by pkieltyka** [trufflesuite/truffle#901]
since truffle v4.1.4+, truffle-migrate introduced a bug that broke migrations for contracts from another npm package, below is an explanation and fix:

https://github.com/trufflesuite/truffle-migrate/pull/25

**Comment by gnidan** [comment]
Thanks for the digging on this @pkieltyka! It'll go out with the next release

**Comment by cgewecke** [comment]
Published w/ `4.1.7`
