### ISSUE TITLE
Migrate multiple contracts in truffle

### ISSUE THREAD

**Issue by katkol** [trufflesuite/truffle#903]
Hi,

I am using truffle v4.1.0 and I would like to deploy multiple contracts. I have 3 contracts named PublishService.sol, strings.sol and SafeMath.sol. The last two are libraries and the first contract uses these two libraries. Hence, the strings and safemath contracts should be deployed before publishservice contract. I tried to do it this  way

```
const string_lib = artifacts.require('strings.sol');
const safemath_lib = artificats.require('safemath.sol');
const PublishService_contract = artifacts.require('PublishService.sol');

module.exports = function(deployer) {
    deployer.then(async () => {
        await deployer.deploy(string_lib);
        await deployer.deploy(safemath_lib);
    });
    deployer.deploy(PublishService_contract);
    deployer.link(string_lib, PublishService_contract);
    deployer.link(safemath_lib, PublishService_contract);
};
```
But I get an error, 

deployer.then(async () => { 
                                ^
SyntaxError: Unexpected token (

can you suggest the correct way to do this?

I tired the below way, and it worked. 

```
const string_lib = artifacts.require('strings.sol');
const safemath_lib = artifacts.require('SafeMath.sol');
const PublishService_contract = artifacts.require('PublishService.sol');

module.exports = function(deployer) {
    deployer.deploy(string_lib).then(() => {
        deployer.deploy(safemath_lib).then(() => {
            deployer.deploy(PublishService_contract).then(()=>{
                deployer.link(string_lib, PublishService_contract);
                deployer.link(safemath_lib, PublishService_contract);
            });

        });
    });
};
```

but the thing here is safemath also waits until string contract is deployed, which is not needed and they both should be deployed parallely as they are independent.

**Comment by gnidan** [comment]
@katkol what's your node version (`node -v`)?

**Comment by katkol** [comment]
Hi,

I was using v6.0.. earlier and it didn't work. After seeing your comment I tried with v9... and it worked. Thanks.
