### ISSUE TITLE
Error: VM Exception while processing transaction: out of gas

### ISSUE THREAD

**Issue by sahar-fehri** [trufflesuite/truffle#911]
## Issue

hello guys, i am trying to deploy my contracts with truffle and ganache.
Here is the command i used to configure my ganache accounts: 
![ganacheacc](https://user-images.githubusercontent.com/10994169/39134424-7e8dbd7e-470e-11e8-97db-86defbd5c786.PNG)
Here is my truffle.js file :  I added the gas parameter based on the fact that by default block gas limit in ganache is = 6712390 

  networks: {
    development: {
      host: "localhost",
      port: 8546,
      gas: 6612390,
      network_id: "*" // Match any network id
    }
  }

when i do : truffle migrate --reset this is the result on the console 
![tx](https://user-images.githubusercontent.com/10994169/39134507-b36aefd0-470e-11e8-9be3-3ea71045cf8c.PNG)

and here is the error: : 
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: out of gas

The thing is : It deploys the first contract and the second fails.
What drives me crazy is that i did the same work on my partners computer and it worked like a charm, howerver on mine i got stuck with it.
I am using windows 10
Truffle v4.1.7
Ganache CLI v6.1.0

I would really appreciate it if anyone has any clue. Thank you

**Comment by cgewecke** [comment]
@sahar-fehri Could you check that there are no other clients running on `8546`? You can do this by running: `lsof -i` and killing any processes on that port. You could also try changing the port ganache launches on and updating the port in your `truffle.js`.

If that doesn't work, raise the default limit on `ganache-cli` by adding the option:
```
--gasLimit 8000000
```
and increasing your `truffle.js` gas as well.

**Comment by sahar-fehri** [comment]
@cgewecke  
First thank you for your reply.

I have added the flag --gasLimit 8000000 and in my truffle js i put the exact same amount , i have changed the port to 8547. But still no chance with it:
Now im getting : 

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Exceeds block gas limit

HUH ....

**Comment by sahar-fehri** [comment]
@cgewecke  no sorry it is still an out of gas error  ...

**Comment by sahar-fehri** [comment]
Somehow it seems like no matter how much i put in the parameter gasLimit , the " Gas usage" in the log will show the exact same amount... and the second transaction for deploying the second contract never goes through ..

**Comment by cgewecke** [comment]
@sahar-fehri If you link to the project I will take a look. Is that possible?

**Comment by sahar-fehri** [comment]
@cgewecke  If you don't mind i could send it to your email address .. i believe it is : christophergewecke@gmail.com =)

**Comment by cgewecke** [comment]
@sahar-fehri Perfect thanks!

**Comment by cgewecke** [comment]
@sahar-fehri Looks like you resolved this, going close but please ping if that's not the case.

**Comment by Zou-XueYan** [comment]
@sahar-fehri How did you fix this ?  Need HELP friend 😢

**Comment by sahar-fehri** [comment]
@Zou-XueYan , i just didn't noticed that the account i was sending the transaction from actually doesn't have any tokens. Which is unlikely to be the same problem you have if your contract is not manipulating tokens. Check your gas limit, perhaps your transaction costs more gas,, and check again your smart contract function, perhaps you are writing some " require(....) " that is actually raising that error... cause from what i know, the error " out of gas" doesn t necessarily mean that you should raise the gas limit, as i said it could be a problem in your function... I hope it helps..
