### ISSUE TITLE
Error with `from` in tests

### ISSUE THREAD

**Issue by auser** [trufflesuite/truffle#914]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running tests with the `{from: account}` is ignored in tests. I have debugged it through the `SolidityFunction.prototype.sendTransaction` function where there are _two_ options objects with the argument I pass in the test and the default options (I assume).

Regardless, the `{from: account}` is ignored (see the github repo below).

More debugging. I updated the `sendTransaction()` function with a `console.log`:

```javascript
SolidityFunction.prototype.execute = function () {
    var transaction = !this._constant;

	console.log('execute ------->', transaction, Array.prototype.slice.call(arguments))

    // send transaction
    if (transaction) {
        return this.sendTransaction.apply(this, Array.prototype.slice.call(arguments));
    }

    // call
    return this.call.apply(this, Array.prototype.slice.call(arguments));
};
```

This results in: ![](https://d.pr/i/2eyiQF.png)

Notice the second `{from}` options object. The first `{from}` options object contains the address I am passing in while the second one contains the `accounts[0]` address.

## Steps to Reproduce

```bash
git clone https://github.com/auser/truffle-bug
npm install
```

In one terminal, run `ganache`:

```bash
npm run ganache
```
In another, run the test:

```bash
./node_modules/.bin/truffle test --network development test/multisig/testMultiSig.js
```

## Expected Behavior

I expect the `msg.sender` address to be the address I pass in instead of the default account (`accounts[0]`). 

## Actual Results

The `msg.sender` value is the default account (`accounts[0]`) instead of the address I pass in using the `from` option.

## Environment

* Operating System: OSX High Sierra
* Ethereum client: truffle test
* Truffle version (`truffle version`):
Truffle v4.1.5 (core: 4.1.5)
Solidity v0.4.21 (solc-js)
* node version (`node --version`):
v9.5.0
* npm version (`npm --version`): 5.8.0

**Comment by auser** [comment]
If you clone the repo, the issue occurs in there and it’s been reproduced by @emmonspired in the gitter channel. 

Did you see the screenshot from above describing the issue? It seems the second from object overwrites the first.

**Comment by cgewecke** [comment]
@auser Why are there two `from` objects? I'm having trouble understanding where this problem originates. The `truffle-contract` behavior seems correct.  Could you try to reproduce this using the simplest possible example so we can isolate the source of the issue?

**Comment by auser** [comment]
@cgewecke I'm not sure why there are two from objects... that was from me digging into the compiled/bundled source of truffle to try to find out what is going on.

There is a single contract in the repo with a test case that demonstrates the issue (https://github.com/auser/truffle-bug/blob/master/contracts/multiSig/MultiSig.sol#L152).

**Comment by cgewecke** [comment]
> Could you try to reproduce this using the simplest possible example so we can isolate the source of the issue?

There isn't a shortcut here I'm sorry - you have a simple example in my response above. Modify it to reproduce, thank you.

**Comment by auser** [comment]
@cgewecke okay, I created a branch called `simplification` (https://github.com/auser/truffle-bug/tree/simplification) that reproduces the behavior. The contract method:

```solidity
pragma solidity ^0.4.18;

contract MultiSig {
    event MultiSigSigned(uint index, address signer);

    function sign(uint index)
        public
    {
        emit MultiSigSigned(index, msg.sender);
    }
}
```

The javascript test:

```javascript
const th = require('../lib/testHelper');
const should = th.should();
const {assertThrows} = th;

const MultiSig = artifacts.require('./MultiSig');

contract('MultiSig', ([owner, user1, user2, user3, user4, user5, user6]) => {
  const threeAccounts = [owner, user1, user2];
  const threeInvalidAccounts = [owner, user1, 0x0];
  let multisig;

  before(async () => await th.advanceBlock());
  beforeEach(async () => {
    multisig = await MultiSig.new();
  });

  describe('events', async () => {

    it('fires MultiSigSigned when signed', async () => {
      const {logs} = await multisig.sign(0, {from: user1, test: true});
      logs.length.should.equal(1);
      logs[0].event.should.equal('MultiSigSigned');
      logs[0].args.index.should.be.bignumber.equal(0);

      console.log(logs[0].args, user1);

      logs[0].args.signer.should.equal(user1);
    });

  });
});
```

**Comment by cgewecke** [comment]
@auser Thanks! That looks good - it's going a bit before I can get back to this, this morning. Apologies

**Comment by auser** [comment]
@cgewecke okay... anything I can look at while you're gone. This is really kind of a blocker for me right now :(

**Comment by auser** [comment]
Yeah, I'm running ganache as a server (https://github.com/auser/truffle-bug/blob/master/ganache.js and https://github.com/auser/truffle-bug/blob/master/scripts/ganache-cli.js) with deterministic addresses as well. Hm.

**Comment by auser** [comment]
I think the error really has to do with the fact that _two_ objects are being passed in as `arguments`. 

The output of `Array.prototype.slice.call(arguments)` is:

```javascript
/**
SolidityFunction.prototype.execute = function () {
    var transaction = !this._constant;

	console.log('execute ------->', transaction, Array.prototype.slice.call(arguments))

    // send transaction
    if (transaction) {
        return this.sendTransaction.apply(this, Array.prototype.slice.call(arguments));
    }

    // call
    return this.call.apply(this, Array.prototype.slice.call(arguments));
}; 
**/
execute -------> true [ 0,
  { from: '0x6704fbfcd5ef766b287262fa2281c105d57246a6' },
  { from: '0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39',
    gas: 6721975,
    gasPrice: 100000000000 },
  [Function: callback] ]
```

And the `sendTransaction()` payload:

```javascript
{ from: '0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39',
  gas: 6721975,
  gasPrice: 100000000000,
  to: '0xa6421a7f48498cee3aeb6428a8a2dd5faa3ace2f',
  data: '0x2fb1b25f0000000000000000000000000000000000000000000000000000000000000000' }
```

Notice the `{from: address}` resolves to the latter object vs. the one I passed in (I think the latter object is like default options?).

**Comment by cgewecke** [comment]
@auser That makes sense, but it's just not clear how you're getting into that state. Your test case seems to run ok. . .

**Comment by auser** [comment]
Also, @cgewecke is the non-bundled source open-source?

**Comment by auser** [comment]
@cgewecke yeah, I'm not sure... why would there be _two_ objects being passed in as `arguments`? Is that intentional?

**Comment by cgewecke** [comment]
Yes everything's open-source, the bundle is just a webpack of the entire project. I think you're looking at the wrong level. You've modified the source somewhere, but another person with a clean truffle can't reproduce your problem with your test. Rip out truffle and put it back in again?

**Comment by auser** [comment]
@cgewecke I know, I was digging through it to try to find the issue.

**Comment by auser** [comment]
@cgewecke I've removed my `node_modules/` and reinstalled. I've also copied and pasted your test code over mine and the issue is still happening. Could this be a ganache issue?

![](https://d.pr/i/wUYx4O.png)

I know it's working for you, but definitely not working for me (cleaned truffle install).

**Comment by auser** [comment]
@cgewecke I think I found an issue? When I remove the line:

```javascript
BigNumber.config({ ERRORS: false, ROUNDING_MODE: BigNumber.ROUND_UP })
```
from my `test/lib/testHelper.js` it works... what the heck? Why would that break it?

Apologies... I'm not sure why that would have any affect? Thanks for your help... I'm so confused. Why would `BigNumber` in chai have any non-sense with how arguments are received in truffle contracts... 

I'll close this due to the fact that it's a local setup issue. I think?

**Comment by cgewecke** [comment]
Oh yeah that's super weird! No worries, glad it worked.

**Comment by emmonspired** [comment]
Very confusing why the line with BigNumber would have any effect @auser - was there any more clarity that came from this @cgewecke ?

**Comment by cgewecke** [comment]
@emmonspired No, I'm not sure what's going on here. If you discover something please report. It's possible there's a compatibility issue between `chai-bignumber` (at some version) and truffle. Zeppelin is [using](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/package.json#L47) them in combination without any obvious issues. They're at:
```
truffle: 4.1.5
chai-bignumber: ^2.0.0
```
