### ISSUE TITLE
truffle-contract does not type-check parameters

### ISSUE THREAD

**Issue by aspeziale** [trufflesuite/truffle#917]
- [√ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## truffle-contract does not type-check parameters

When I've a contract constructor accepting a specific parameter my tests don't not fail if I pass to the constructor something not expected.

## Steps to Reproduce

Create a simple contract like:
```
contract Contract {
    bool paused;
    function Contract(bool _status) {
        paused = _status
    }
}
```
and try on the tests to do something like that:
```
// I expected it would fail but it isn't
    it("should not be created passing strange value to constructor", async () => {
         try {
             const c = await Contract.new('hello')
         } catch(e) {
             console.error(`Error: ${e}`)
         }
     })
```
## Expected Behavior

Catch any kind of error

## Actual Results

Tx receipt

## Environment

* Operating System: macosx
* Ethereum client: truffle develop
* Truffle version (`truffle version`): Truffle v4.1.5
* node version (`node --version`): v9.10.1
* npm version (`npm --version`): 5.8.0

**Comment by cgewecke** [comment]
@aspeziale This is a good observation. Hope you don't mind - I'm going to change the title of your issue to be more specific about what a wrong parameter is.

**Comment by aspeziale** [comment]
@cgewecke Thanks for the support. No problem at all. 
About the reported issue I don't know if I'm doing something wrong or something is going wrong on truffle-contract side.

I've notice that passing as argument:
```
- 0 the paused status is false
- 1 the paused status is true
- a string the paused status is true
```

Thanks all.

**Comment by cgewecke** [comment]
@aspeziale It's just the way Javascript is - you're not doing anything wrong. A string with length is 'truthy'. The underlying issue is that Solidity is strongly typed and JS is not.
