### ISSUE TITLE
Issue in truffle/assest.sol and deployedaddresses

### ISSUE THREAD

**Issue by vidhyaramani** [trufflesuite/truffle#918]
am getting the error of source truffle/ asset.sol and deployedaddresses.sol is not found.

I have uninstalled the truffle and installed it again.

apart from this, codes are fine.

## Environment

* Operating System: Windows
* Ethereum client:ganache-cli
* Truffle version (`truffle version`):4.1.7
* node version (`node --version`):9.9.0
* npm version (`npm --version`): 5.8.0

**Comment by cgewecke** [comment]
@vidhyaramani  Are you using VSCode?

**Comment by vidhyaramani** [comment]
Yes, for working with solidity

**Comment by cgewecke** [comment]
@vidhyaramani This appears to be a bug in VSCode, discussed in #756. The solution appears to require that the VSCode project (not truffle) be [deleted and recreated](https://github.com/trufflesuite/truffle/issues/756#issuecomment-359206765) for VSCode to recognize the files.

Closing as duplicate of #756

**Comment by nukec** [comment]
this is still an issue, and recreating doesn't work
