### ISSUE TITLE
Why open the truffle.js when I truffle compile?

### ISSUE THREAD

**Issue by lancesf** [trufflesuite/truffle#922]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Why open the truffle.js when I truffle compile? and why is there no web page? 

## Steps to Reproduce

No matter what command I use, in the folder generated by init, the truffle.js will be opened automatically.
and I tried other versions of truffle. Js, every time.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

The operating system： windows10
* Operating System: 
* Ethereum client: testrpc
* Truffle version 3.2.1:
* node version 8.11.1:
* npm version 6.0.0:

**Comment by cgewecke** [comment]
Thanks @saradotramli :)

@lancesf There's also more window's specific help in the Truffle documentation [here](http://truffleframework.com/docs/advanced/configuration#resolving-naming-conflicts-on-windows).

Closing since this issue is duplicate / addressed by the docs.
