### ISSUE TITLE
Truffle Tests Spanning Multiple Nodes(Networks) with Quorum

### ISSUE THREAD

**Issue by saradotramli** [trufflesuite/truffle#923]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
No response received there and hence posting here
---------------------------

## Issue

I am working on a Dapp with private smart-contracts + quorum. Does truffle's testing framework support connecting to multiple networks from within the test code (not from the command-line)? The tutorial here: http://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains does that from the truffle console, but I would like to do the same (execute contract calls as different nodes - by connecting to different 'networks') from within a test method. Possible?

## Steps to Reproduce

NA

## Expected Behavior

Ability to specify network names from within a test method for both contract deployments and other transactions

## Actual Results

Not sure if it is possible today. Might be an enhancement

## Environment

* Operating System: Windows 10
* Ethereum client: Quorum 2.0.2
* Truffle version (`truffle version`): Truffle v4.1.6 (core: 4.1.6)
* node version (`node --version`): v8.11.1
* npm version (`npm --version`):  5.6.0

**Comment by cgewecke** [comment]
@saradotramli Is this close-able?

**Comment by cgewecke** [comment]
Closing for house-keeping, please ping if the comments above don't resolve this for you.
