### ISSUE TITLE
Problems running truffle with Ionic3

### ISSUE THREAD

**Issue by sahar-fehri** [trufflesuite/truffle#929]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Good morning guys,
I am trying to create an application using Ionic3 and truffle and whenever i try invoking my smart contracts it gives me an error concerning the "truffle-contract" package. I have tried downgrading it's version but it's not working.

If anyone has already tried working with ionic3 and truffle  and has a boilerplate project i could start with i would really appreciate it.

Thank you guys,

**Comment by cgewecke** [comment]
@sahar-fehri Could you post the error?

**Comment by cgewecke** [comment]
@sahar-fehri Closing due to lack of response, please feel free to ping if you're still facing this issue.
