### ISSUE TITLE
Update package.json dependency lodash: "3.10.1" --> lodash: "4.0.0"

### ISSUE THREAD

**Issue by dominicwilliams** [trufflesuite/truffle#93]
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash.padleft@3.1.1: This package has been renamed. Use lodash.padstart@^4.0.0.
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.

**Comment by tcoulter** [comment]
FYI: This line is due to a dependency using a really old verison of lodash:
```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
```
Whereas this one is specifically related to Truffle:
```
npm WARN deprecated lodash.padleft@3.1.1: This package has been renamed. Use lodash.padstart@^4.0.0.
```

All of these warnings should be looked at, however.

**Comment by tcoulter** [comment]
Partially fixed here: https://github.com/ConsenSys/truffle/commit/be33f1bf38e5b7bcf7cf903c4ef509239fd8a740

**Comment by tcoulter** [comment]
I've fixed some of these issues, but this can't be fully fixed until Truffle v0.5.0. Reasoning:

* Truffle uses `truffle-default-builder` as the default build system.
* The default builder provides sass through `node-sass`
* `node-sass` requires `gaze`
* `gaze` requires `globule` which requires a super old version of lodash.

Truffle requires `gaze` as well -- for the next 10 minutes or so -- and I'm wapping that out for `chokidar`. But we can't be fully rid of these errors until we pull the default builder out of Truffle completely, which has been planned for v0.5.0.

**Comment by tcoulter** [comment]
More updates here: https://github.com/ConsenSys/truffle/commit/3d7ce69f762dae6e74f0f4794875435521c95b61

**Comment by tcoulter** [comment]
Looks fixed. Closing.
