### ISSUE TITLE
Cannot input byte array properly to a function from truffle test in javascript.

### ISSUE THREAD

**Issue by kimyd** [trufflesuite/truffle#930]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Cannot input bytes array properly to a function. 

## Steps to Reproduce

I defined byte array and try to input a function in my contract. But something is wrong. The bit order is strange. As you can see [here](https://ethereum.stackexchange.com/questions/47309/how-to-input-byte-array-to-a-function)

## Expected Behavior

Correctly input my byte array to the function.

## Actual Results

0x01, 0x02, 0x03, 0x1f  is passed to the function as 0x10, 0x20, 0x30, 0x1f

## Environment

* Operating System: ubuntu 16.04
* Ethereum client: testrpc 
* Truffle version (`truffle version`):  v4.1.7 
* node version (`node --version`): v9.11.1
* npm version (`npm --version`): 5.6.0

**Comment by kimyd** [comment]
First I though it is solidity problem, but it works fine with Remix, something wrong with the ABI encoder of truffle.

**Comment by cgewecke** [comment]
@kimyd If you quote the byte values does that result in correct formatting? 
```javascript
var myData = [0x01, 0x02, 0x03, 0x1f];         // <-- Example
var myData = ['0x01', '0x02', '0x03', '0x1f']; // <-- with quotes
```

For reference, [thread](https://ethereum.stackexchange.com/questions/13483/how-to-pass-arbitrary-bytes-to-a-function-in-remix) on this topic at StackExchange.

**Comment by kimyd** [comment]
Yes, you are right. It works fine with quotes. Thank you.
