### ISSUE TITLE
Outdated solidity version in `migration.sol` 

### ISSUE THREAD

**Issue by Aniket-Engg** [trufflesuite/truffle#931]
## Issue/Feature Request

`truffle init` setup project with a file named `migration.sol` with solidity version `0.4.17`

## Steps to Reproduce

`truffle init`

## Expected Behavior

Migration.sol file should have updated version of Solidity

## Actual Results

It dispaly Solidity version as `0.4.17`

## Environment

* Operating System: Ubuntu 16.04
* Truffle version (`truffle version`): 4.1.5
* node version (`node --version`): 8.9.3
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@Aniket-Engg Thanks for raising this. Unfortunately updating the `Migrations.sol` to latest solc would be a breaking change for users running `truffle init` with earlier versions of truffle. The template for a bare-box project sits [here](https://github.com/truffle-box/bare-box) and is strongly decoupled from truffle itself. At present the best work-around for users is to update that file following the warnings their solc version provides - there's just a couple things.  

We probably need to implement [truffle-core 117](https://github.com/trufflesuite/truffle-core/issues/117) to manage this requirement appropriately. Another approach that's been discussed is removing `Migrations.sol` from bare projects altogether and having truffle manage that feature 'magically' behind the scenes.

**Comment by Aniket-Engg** [comment]
@cgewecke ok, I got it. Looks like we can have a permanent solution later in future, till then we can go with the updating file manually.

**Comment by Aniket-Engg** [comment]
Latest truffle is putting `Migrations.sol` with version 0.4.23. Thanks for considering the update.
