### ISSUE TITLE
Handling of byte types by either truffle or web3 seems to be incorrect

### ISSUE THREAD

**Issue by barakman** [trufflesuite/truffle#932]
## Issue

Handling of [byte types](http://solidity.readthedocs.io/en/develop/types.html?highlight=bytes1#fixed-size-byte-arrays) by either truffle or web3 seems to be incorrect.

## Steps to Reproduce

On-Chain:
```
contract MyContract {
    function func(bytes4 x) public pure returns (bytes4) {
        return x;
    }
}
```
Off-Chain:
```
contract("Test", function() {
    it("test", async function() {
        let myContract = await artifacts.require("MyContract.sol").new();
        let retVal = await myContract.func(0x00012345);
        console.log(retVal);
    });
});
```

## Expected Behavior

Print 0x00012345

## Actual Results

Print 0x12345000

It seems that every leading zero digit in hexadecimal format (i.e., every leading chunk of 4 zero bits) is forced to become trailing somehow.

This happens on client side for sure (you may confirm it by adding `require(x == 0x12345000)` inside the on-chain function above.

It seems to be the case for other byte types as well (e.g. `bytes1`, `bytes2`, etc).

## Environment

* Operating System: Windows 10
* Ethereum client: ganache-cli: 6.1.0
* truffle version: 4.1.3
* node version: 8.9.3
* npm version: 5.5.1

**Comment by cgewecke** [comment]
@barakman If you quote the bytes when you pass them into the function
```javascript
await myContract.func("0x00012345");
```
does that resolve it? Think JS is interpreting the input as a number rather than bytes and Solidity formats these differently. It looks like `uint` is left-aligned in the word, `bytes` right-aligned, based on  encodings docs at over at solidity [here](https://solidity.readthedocs.io/en/develop/abi-spec.html#examples).

**Comment by barakman** [comment]
@cgewecke:
Yes it does, thank you.
Though it is not really clear to me why I should pass an ASCII string where the compiler would expect an integer (or an array of 1-byte integers).
Perhaps it is my lack of understanding of the 'byte' types.

**Comment by cgewecke** [comment]
@barakman Honestly not sure why this is either - it might be related to the issue of different byte type sizes and the way they are padded. Have just been looking at this topic this morning  and there's a StackExchange thread about it [here](https://ethereum.stackexchange.com/questions/11347/bytes-quotes-or-not)

**Comment by cgewecke** [comment]
@barakman Is it ok if I close this?  Seems like quotes is just how web3 manages bytes.

**Comment by barakman** [comment]
@cgewecke:
Yes, thank you for clarifying it!
