### ISSUE TITLE
Default version of Solidity set where?

### ISSUE THREAD

**Issue by quantumproducer** [trufflesuite/truffle#938]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

I upgraded geth and truffle through npm, after running npm i npm.

Created new folder, truffle init. The default Migrations contract has "pragma solidity ^0.4.17;"
I have v0.4.19 Solidity installed and afaik Solidity is in the 20s.

Why does truffle use an older version?

## Environment

* Operating System:  OSX
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)
* node version (`node --version`): v9.11.1
* npm version (`npm --version`): 5.6.0

**Comment by tomcbean** [comment]
“truffle version” will show the solc version you are on. The Migrations contract with that pragma line will compile to the version of solidity used by your truffle version, as long as it’s less than 0.5.0.

**Comment by cgewecke** [comment]
Thanks @tomcbean :) 

@quantumproducer At the moment, the solc version is tightly coupled with the truffle version. See the [releases](https://github.com/trufflesuite/truffle/releases) to get the one you need. 

`Migrations.sol` is maintained as part of a separate `truffle-box` and needs to work with multiple versions of the compiler, so we're letting it float lower than latest solc. See #931 for more detail on this.
