### ISSUE TITLE
Deployment on private net fails.

### ISSUE THREAD

**Issue by cmaliwal** [trufflesuite/truffle#945]
**Issue**
Trying to deploy a contract on private chain but, It fails with error message as "Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
"

**Step to Produce :** 

1. Create a genesis.json file : 

```
{
  "config": {
    "chainId": 58342,
    "homesteadBlock": 0,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "nonce": "0x0000000000000033",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x8000000",
  "difficulty": "0x100",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {}
}
```

**2. initialise the blockchain :** 
`geth --datadir privchain init genesis.json`

**3. Start a node :** 

`geth --port 3000 --networkid 58342 --nodiscover --datadir="privchain" --maxpeers=0 autodag --rpc --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --rpcapi "eth,net,web3" --rpcvhosts="*" --ipcapi "eth,net,web3"
`

**4. attach to the geth console**

`geth attach ipc:/home/rails/projects/blockchain-work/practise-work/geth/privchain/geth.ipc`

**5. create account :** 
`> personal.newAccount('password')`

6. un**lock account :** 
`> personal.unlockAccount(web3.eth.coinbase, "password", 15000)`

**7. start mining :**  

`> miner.start()`

**8. create a basic truffle project with this project structure :** 

── build
│   └── contracts
│       ├── Migrations.json
│       └── UserDetails.json
├── console.log
├── contracts
│   ├── Migrations.sol
│   └── UserDetails.sol
├── genesis.json
├── instructions.txt
├── migrations
│   ├── 1_initial_migration.js
│   └── 2_UserDetails.js
├── privchain
│   ├── geth
│   │   ├── chaindata
│   │   │   ├── 000002.ldb
│   │   │   ├── 000003.log
│   │   │   ├── CURRENT
│   │   │   ├── LOCK
│   │   │   ├── LOG
│   │   │   └── MANIFEST-000004
│   │   ├── lightchaindata
│   │   │   ├── 000001.log
│   │   │   ├── CURRENT
│   │   │   ├── LOCK
│   │   │   ├── LOG
│   │   │   └── MANIFEST-000000
│   │   ├── LOCK
│   │   ├── nodekey
│   │   └── transactions.rlp
│   ├── geth.ipc
│   └── keystore
│       └── UTC--2018-05-15T12-30-08.339767305Z--2f80519b335e43564f2761470044a296bfd65281
├── test
├── truffle-config.js
└── truffle.js

9. Compile contract : 
**> truffle compile**

**10. Update truffle.js :** 

```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*",
    }
  }
};
```

**11.  migrate the contract :** 
`> truffle migrate `

```
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```

**Environment**

- Operating System: Ubuntu
- Ethereum client: geth 1.8.2
- Truffle version (truffle version): v4.1.6
- node version (node --version): v8.10.0
- npm version (npm --version): 5.6.0

**Comment by cgewecke** [comment]
@cmaliwal [This tutorial](https://medium.com/@s4saif.121/demystifying-ethereum-private-blockchain-74f78ddf76fb) is a really good resource. Not sure exactly why you're not able to connect to but I see a mix of rpc / ipc in your geth launch script, and you're also using using APIs like `miner` and `personal` in the console without listing them. With private net it's often helpful to do everything explicitly:

Other possibilities:
+ set a network id in the client launch and in the truffle config
+ specify the network you are migrating to: `truffle migrate --network development`
