### ISSUE TITLE
This account has been hacked. This issue was not opened by the account owner. Please ignore.

### ISSUE THREAD

**Issue by AwesomePenguin** [trufflesuite/truffle#946]
This account has been hacked. This issue was not opened by the account owner. The account owner is currently working to reclaim this account. Please ignore this issue.

Sorry for any inconvenience, and thank you for your support.

**Comment by cgewecke** [comment]
@AwesomePenguin The debugger needs to match source code and compilation products like the bytecode and source map to the opcodes generated by a transaction. You don't have to have **actually** deployed the contract, but you need all that meta data, compiled with the same compiler as the deployed version, listed under the same network key your build folder.
