### ISSUE TITLE
npm install truffle -g not working

### ISSUE THREAD

**Issue by ricochen** [trufflesuite/truffle#947]
I did `npm uninstall truffle -g` to uninstall truffle.
Then I did `npm install truffle -g` to reinstall it but it is stuck at:
`⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ rollbackFailedOptional: verb npm-session e7a9c4f0579f523`

## Environment

* Operating System: macOS High Sierra 
* Ethereum client:
* Truffle version: none
* node version: v8.8.1
* npm version: 5.6.0

**Comment by cgewecke** [comment]
@ricochen Wasn't able to reproduce this. Truffle seems to be installing normally - also on OSx, npm `5.6.0`...

Are you still having this problem?

**Comment by ricochen** [comment]
All of a sudden installing using npm for anything has this issue. It is forever stuck at rollbackFailedOptional.

**Comment by ricochen** [comment]
After removing all my old node/npm files which was installed using nvm, and reinstalling using the regular way (downloading from the website). I found that post and tried the 2 commands.

`npm config get proxy` now returns null. Then I had to follow npm's instructions on allowing global installs and I was able to `npm install -g truffle`.

However, I uninstalled and reinstalled truffle in the first place because I was running into an issue:
`Unknown network "rinkeby". See your Truffle configuration file for available networks.`

`truffle.js`:
```module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*" // Match any network id
        }
    },
    rinkeby: {
        host: "localhost",
        port: 8545,
        network_id: "4", // Rinkeby ID 4
        from: "0xf6e9dc98fe5d2951744967133b3c31765be657c1" // account from which to deploy
    }
};
```

`truffle.config.js`:
```
module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*" // Match any network id
        }
    },
    rinkeby: {
        host: "localhost",
        port: 8545,
        network_id: "4", // Rinkeby ID 4
        from: "0xf6e9dc98fe5d2951744967133b3c31765be657c1" // account from which to deploy
    }
};
```

**Comment by cgewecke** [comment]
@ricochen - The different networks should be listed together under the `networks` key.
```javascript
module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 8545,
            network_id: "*" // Match any network id
        },
        rinkeby: {
             host: "localhost",
             port: 8545,
             network_id: "4", // Rinkeby ID 4
             from: "0xf6e9dc98fe5d2951744967133b3c31765be657c1" // account from which to deploy
        }
    },
};
```

**Comment by ricochen** [comment]
Oh shoot! Didn't see that, silly mistake haha thanks!

**Comment by kenshyx** [comment]
I'm having the same issue, it gets stuck at `rollbackFailedOptional: verb npm-session 44c72d20e8035c2`. I'm using `node v8.10.0` and `npm 6.0.1 ` on ` Linux Mint 18.1 Serena 64-bit`

**Comment by cgewecke** [comment]
@kenshyx I think the upgrade to npm 6 is a little buggy. Are you able to install *any* packages globally? Recently did this and had to completely re-install nvm / npm.

**Comment by kenshyx** [comment]
@cgewecke I had to remove previous version of truffle and It worked in the end.

**Comment by spritetest** [comment]
> @cgewecke I had to remove previous version of truffle and It worked in the end.

how to remove previous version?
