### ISSUE TITLE
Could not find artifacts for Solidity tests (Windows, v4.1.8)

### ISSUE THREAD

**Issue by bambalaus** [trufflesuite/truffle#952]
- [ X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

 truffle.cmd test TestMetacoin.sol generates: "Error: Could not find artifacts for ./TestMetacoin.sol from any sources" 
possible regression for #885?

## Steps to Reproduce

fresh install from command line (no IDE) truffle 4.1.8

run:
truffle.cmd test TestMetacoin.sol
or
truffle.cmd test

## Expected Behavior

completion of test suit

## Actual Results

Error as described above

## Environment

* Operating System: windows 10 x64
* Truffle version (`truffle version`): 4.1.8
* node version (`node --version`): 8.4.0
* npm version (`npm --version`): 5.3.0

**Comment by cgewecke** [comment]
@bambalaus Could you provide more detail about how you're setting up your truffle project? Have you run `truffle unbox metacoin`? Have you modified it at all?

**Comment by bambalaus** [comment]
yes, i did `truffle unbox metacoin`, and modified the code to comply with the  solc version 4.23 (chancing constructor sintax and added `emit` to the event).

I just tried a further option on a fresh installation:
` truffle.cmd test test\TestMetacoin.sol`. this seems to work further, as it fails due to the old event sintax in Assert.sol (so the import seems to work).

'Compilation warnings encountered:

truffle/Assert.sol:1563:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _itoa(value, 10);
        ^------^
,truffle/Assert.sol:1580:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _utoa(value, 10);
        ^------^
,truffle/Assert.sol:1597:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _ltoa(value);
        ^------^
,/C/bambalaus/Metacoin2/contracts/MetaCoin.sol:23:3: Warning: Invoking events without "emit" prefix is deprecated.
                Transfer(msg.sender, receiver, amount);
                ^------------------------------------^
,truffle/Assert.sol:1347:13: Warning: Invoking events without "emit" prefix is deprecated.
            TestEvent(true, "");
            ^-----------------^
,truffle/Assert.sol:1349:13: Warning: Invoking events without "emit" prefix is deprecated.
            TestEvent(false, message);
            ^-----------------------^
 

It is the first time I use truffle, so I might be doing something silly

**Comment by cgewecke** [comment]
Oh good, I'm glad the imports are working. The messages you are seeing all look like compiler warnings which you can safely ignore them for that library - it just provides utilities for the testing framework. Are the tests executing correctly?

**Comment by cgewecke** [comment]
@bambalaus I'm going to close because it looks like original problem is resolved. Please ping if you continue to have problems with this.
