### ISSUE TITLE
Can use truffle init/unbox into a non-empty folder

### ISSUE THREAD

**Issue by hefgi** [trufflesuite/truffle#953]
I'm asking for a feature request.

If we want to add truffle to an existing project, we need to copy/paste files manually because of this error :
```
$ truffle init                                                                                                                                                            
Downloading...
Error: Something already exists at the destination. Please unbox in an empty folder. Stopping to prevent overwriting data.
    at /Users/fjalcaraz/.nvm/versions/node/v8.11.1/lib/node_modules/truffle/build/webpack:/~/truffle-box/lib/utils/unbox.js:22:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

It would be great if truffle checked if files are going to be overwritten, if not, it can init, if yes, show this error message.

**Comment by cgewecke** [comment]
@hefgi Agree this would be nice, especially for truffle init. Cross referencing to [truffle-core 117](https://github.com/trufflesuite/truffle-core/issues/117) which would solve several other issues as well.

**Comment by eggplantzzz** [comment]
This feature has been added in version 5!
