### ISSUE TITLE
Compiling contracts only in subfolder due to limitation of repo structure

### ISSUE THREAD

**Issue by nukec** [trufflesuite/truffle#956]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Unable to compile only selected subfolder

## Steps to Reproduce

Go into folder with contracts, and run truffle compile

## Expected Behavior

Compile only contracts in current folder.

## Actual Results

It compiled all contracts outside of subfolder.

Is there actually a way to compile only contracts in subfolder?

**Comment by cgewecke** [comment]
@nukec Unfortunately no. We're tracking this as a feature request at #827 and will hopefully include it in the next major release of Truffle. 

Thanks for opening, closing as duplicate of #827.
