### ISSUE TITLE
Feature request: "truffle migrate" for multiple contracts simultaneously?

### ISSUE THREAD

**Issue by gerchicov-bp** [trufflesuite/truffle#959]
If I have multiple contracts which are not linked between themselves then why not to allow to deploy these contracts simultaneously? According to the log currently truffle deploys them one by one

**Comment by cgewecke** [comment]
@gerchicov-bp This should be possible using a library that parallelizes promise execution. [This one](https://www.npmjs.com/package/async-await-parallel) looks like it might work nicely for migrations. It would look something like this:
```javascript
const parallel = require('async-await-parallel');

module.exports = function (deployer) {
  deployer.then(async () => {
    return parallel(
      await deployer.deploy(MyContract1),
      await deployer.deploy(MyContract2)
    )
  })
}
```

**Comment by cgewecke** [comment]
@pubkey Ah yes `Promise.all is parallel`. Thank you.

**Comment by cgewecke** [comment]
Going to close this since it seems like this doesn't require any special features - JS alone is adequate. Please ping if you're still having trouble with it.
