### ISSUE TITLE
Truffle @4.1.10 cannot be installed

### ISSUE THREAD

**Issue by nukec** [trufflesuite/truffle#960]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Version 4.1.10 not found on npm

## Steps to Reproduce

npm install -g truffle@4.1.10

## Expected Behavior

Installs 4.1.10

## Actual Results

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for truffle@4.1.10
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   '-g',
> 1 verbose cli   'truffle@4.1.10' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.11.1
> 4 verbose npm-session 30155d61697d61d8
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/truffle 63ms (from cache)
> 8 silly registry:manifest no matching version for truffle@4.1.10 in the cache. Forcing revalidation
> 9 http fetch GET 304 https://registry.npmjs.org/truffle 15ms (from cache)
> 10 silly fetchPackageMetaData error for truffle@4.1.10 No matching version found for truffle@4.1.10
> 11 verbose type version
> 12 verbose stack truffle: No matching version found for truffle@4.1.10

## Environment

* Operating System: Win 10
* Ethereum client:
* Truffle version (`4.1.8`):
* node version (`v8.11.1`):
* npm version (`5.6.0`):

**Comment by cgewecke** [comment]
@nukec Thanks for reporting. It looks like the npm had [serious problems](https://github.com/npm/registry/issues/327) Monday night. Some packages published during the outage got lost in the registry. 

Republishing in the next hour at a new tag.

**Comment by cgewecke** [comment]
Believe this is fixed now. Please ping if you continue to have problems getting the latest. 
```shell
$ truffle version
> Truffle v4.1.11 (core: 4.1.11)
> Solidity v0.4.24 (solc-js)
```
