### ISSUE TITLE
Asynchronous tests break with Babel

### ISSUE THREAD

**Issue by michaeldel** [trufflesuite/truffle#963]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Asynchronous tests break when adding Babel (`babel-register` and `babel-polyfill`) to project (`this` is set `undefined` in test sections).

## Steps to Reproduce
_A minimal example is attached here: [example.tar.gz](https://github.com/trufflesuite/truffle/files/2033183/example.tar.gz) or [example.zip](https://github.com/trufflesuite/truffle/files/2033191/example.zip)_

Init a new project with `truffle init`, create file `test/Foo.test.js`, with this content:
```js
contract('Foo', accounts => {
  beforeEach(async () => {
    this.x = 0
  })

  it('simple test', async () => {})
})
```
This should run with no issue when executing `truffle test`.

Now imagine you need to import a function from somewhere else, like OpenZeppelin's `assertRevert` testing utility function, one would add these to `test/Foo.test.js ` after having installed OpenZeppelin module (`npm install --save openzeppelin-solidity`):
```js
import assertRevert from 'openzeppelin-solidity/test/helpers/assertRevert'

// CommonJS alternative, which would fail the same way
const assertRevert = require('openzeppelin-solidity/test/helpers/assertRevert')

// rest of your tests...
```
Now running `truffle test` should fail because of unexpected `import` token (or `export` (which is in OZ's `assertRevert.js` file) if you used `require`). Fine, let us fix that by adding Babel:
```
npm --save-dev babel-register babel-polyfill babel-preset-env
```
Now let us add these at the top of `truffle.js` (or `truffle-config.js` in case you are using that one):
```js
require('babel-register')({
  ignore: /node_modules\/(?!openzeppelin-solidity\/test\/helpers)/
})
require('babel-polyfill')

// rest of truffle config...
```
And configure Babel through a new `.babelrc` file:
```json
{
    "presets": ["env"]
}
```
Here we are, we can run `truffle test` again.

## Expected Behavior

Imports should work and test should pass like before.

## Actual Results

Imports are indeed fixed and now work properly. However, test fails, telling that `this` is `undefined` (within `beforeEach` section), which is quite of an issue.
I also noticed that this problem only happens for asynchronous tests (like I have written above).

## Environment

* Operating System: Archlinux
* Ethereum client: [Ganache](https://github.com/trufflesuite/ganache) (version `1.1.0-1`)
* Truffle version (`truffle version`): `Truffle v4.1.11 (core: 4.1.11)`
* node version (`node --version`): `v10.1.0`
* npm version (`npm --version`): `6.0.1`

**Comment by cgewecke** [comment]
[mocha's weirdness about `this`](https://github.com/mochajs/mocha/issues/2018), the ES6 arrow function with non-binding `this` and babel transpilation is the Bermuda  Triangle of `this`.

Could you see if everything is ok if you rewrite the arrow functions as conventional functions? e.g:

```javascript
contract('Foo', accounts => {
  beforeEach(async function(){
    this.x = 0
  })

  it('simple test', async function(){})
})
```

**Comment by michaeldel** [comment]
@cgewecke this indeed seems to solve the problem, too bad having to add code-style/linting exceptions for such "should not even be a thing" issues though. Thank you!

**Comment by kyriediculous** [comment]
This is intended javascript behaviour, though can be a bit annoying.
You can pass the context in arrow functions explicitly as well.
```

const mocha = require('mocha')
mocha.describe('my test', (suite) => {
  suite.it('does something', async () => {
  //test something
})
})
```
