### ISSUE TITLE
On Windows 10, truffle/Assert.sol is not found..

### ISSUE THREAD

**Issue by chainchaser** [trufflesuite/truffle#968]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

On Windows 10, 
cannot import some global lib like below.

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";

## Steps to Reproduce

i just followed pet-shop example from truffle.(http://truffleframework.com/tutorials/pet-shop)
i wanted to make TestAdoption.sol
but there is reference errors.

## Expected Behavior

how to import correctly Assert.sol?

## Actual Results

truffle/Assert.sol is not found.

## Environment

* Operating System: windows 10
* Ethereum client: ganache1.1.0
* Truffle version (`truffle version`): 4.1.11
* node version (`node --version`): 8.11.2
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@chainchaser This seems to be an issue with VSCode, please see #756. I'm leaving an additional note there requesting more clarity about how/why box installation goes wrong with that IDE, but it looks like you should be able to work around it by re-initializing the project in VSCode.
