### ISSUE TITLE
Compatibility with yarn workspaces

### ISSUE THREAD

**Issue by 4000D** [trufflesuite/truffle#977]
## Issue

I use yarn workspaces and each package's `node_modules` is located in root directory, not in the package directory.

When trying to run `truffle compile` in a package directory with using openzeppelin-solidity, truffle cannot resolve the path of `node_modules/openzeppelin-solidity` because it searches wrong directory.

[Findup](https://www.npmjs.com/package/findup)-like behavior may fix it.

## Steps to Reproduce

Use yarn workspaces. It may seem like
```
/root
└─node_modules
       └─ openzeppelin-solidity
└─packages
        └─ sampleProject # using openzeppelin-solidity
               └─ node_modules
 ```

and run
```bash
$ truffle compile
```

## Expected Behavior

compiled without errors

## Actual Results

cannot resolve openzeppelin-solidity

## Environment

* Operating System: maxosX

```
Truffle v4.1.11 (core: 4.1.11)
Solidity v0.4.24 (solc-js)

node.js v8.11.1
npm 5.6.0
```

**Comment by cgewecke** [comment]
Hi @4000D Thanks for opening.

We're currently tracking this issue at #958 and a fix should be included in the next patch release (ETA 1.5 - 2 weeks). In the interim, the engineer who opened #958 left some notes about a work-around using the `nohoist` option that might be helpful.

Closing as duplicate.
