### ISSUE TITLE
Error info generic-  Ambiguous Error, truffle compile 

### ISSUE THREAD

**Issue by raky35** [trufflesuite/truffle#979]
Hi Team , 
During compilation of multiple contracts using "truffle compile" if there is any error in contract,  it  throws a common error without sharing the name of contract. It would be great if truffle throws error with exact information of contract.

$ truffle compile
Invalid input source specified.
Compilation failed. See above.

Truffle v4.1.7 (core: 4.1.7)
Solidity v0.4.23 (solc-js)
npm: '6.1.0',
 node: '8.9.4',

Thanks, 
Kind Regards
raky

- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cgewecke** [comment]
@raky35 Closing for housekeeping, please ping if you continue to see this, or can provide reproduction steps.
