### ISSUE TITLE
How can I view the values of storage variables/properties in a debug session?

### ISSUE THREAD

**Issue by roschler** [trufflesuite/truffle#982]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When I'm debugging a transaction with the debug command, is there a way to have it dump out the contract storage variables? I know you can show the current memory variables with the **v** command, but I want to see the storage variables like the owner property for a contract that inherits from the Open Zeppelin **Ownable** contract, which has a public _address._ property named **owner**.  I've tried using the evaluate expressions debug command (i.e. - the colon ':'), but I can't figure out what syntax/interface that feature accepts.  It doesn't seem to support the web3.js interfaces like _eth.Contract_, etc and statements like ": owner" or ": this.owner" don't work.

Also, does anybody know of any docs for the NetBeans/Truffle debugging plugin? I'm not sure how to create a new project in NetBeans that will work with it.

**Comment by cgewecke** [comment]
@roschler Thanks for opening. Is it ok if I close here and we track this at [truffle-debugger 77](https://github.com/trufflesuite/truffle-debugger/issues/77)?

**Comment by roschler** [comment]
@cgewecke Sure, thanks.
