### ISSUE TITLE
Web3 error when trying to compile code using truffle

### ISSUE THREAD

**Issue by sai4788** [trufflesuite/truffle#986]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

Using web3 detected from external source. If you find that your accounts don't appear or you have 0 MetaCoin, ensure you've configured that source properly. If using MetaMask, see the following link. Feel free to delete this warning. :) http://truffleframework.com/tutorials/truffle-and-metamask
(anonymous) @ app.js:28251

What the issue is, in broad strokes.

Trying to create sample hello world application
Installed 
metamask
node js
truffle,ethereum js
when trying to integrate the app with metamask and the money in metamask should be displayed on the ui but I am getting the error mentioned above.

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results -- The amount in metamask should be displayed in UI.

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows 7 enterprise
* Ethereum client: 
* Truffle version (`truffle version`):  v4.1.11
* node version (`node --version`):v8.11.2
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@sai4788 In the top left hand corner of metamask there is a network tab. Make sure it's connected to the correct local test network / ganache client.

For more please check out the ganache docs [here](http://truffleframework.com/docs/ganache/using) and if you run into further problems getting these two components to work together, the ganache repository is located [here](https://github.com/trufflesuite/ganache).
