### ISSUE TITLE
Console crashes when it runs a long time

### ISSUE THREAD

**Issue by 4000D** [trufflesuite/truffle#991]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle console exits with below error messages when I run console more than 5 minutes
```
node_modules/web3-provider-engine/index.js:231
    return cb(null, resultObj)
           ^
TypeError: Cannot read property 'number' of undefined
```

## Steps to Reproduce

Run
```bash
$ truffle console
```

and wait for about 10 mins.

## Expected Behavior

Console lasts forever

## Actual Results

Console exits with below error message
```
node_modules/web3-provider-engine/index.js:231
    return cb(null, resultObj)
           ^
TypeError: Cannot read property 'number' of undefined
```

## Environment

* Operating System: maxosX
* Ethereum client: ganache-cli v6.1.0
* Truffle version (`truffle version`): v4.1.11
* node version (`node --version`): v8.11.1
* npm version (`npm --version`):  v5.6.0

**Comment by cgewecke** [comment]
@4000D Thanks for reporting - the console is going to have some work done on it soon so will flag this as something to look into.
