### ISSUE TITLE
Permission denied error when trying to use the github protocol link in Contributing.md

### ISSUE THREAD

**Issue by roschler** [trufflesuite/truffle#993]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

When I try to use the `github` link suggested in the Contributing.md document here:

https://github.com/trufflesuite/truffle/blob/develop/CONTRIBUTING.md

```git clone git@github.com:trufflesuite/truffle.git```

I get the following error:

```sh
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

I'm going to try the "https://" protocol link from the CLONE OR DOWNLOAD button.

**Comment by roschler** [comment]
No luck.  I _can_ download the main repository with the "https://" link, but the dependent repos are downloaded by the "meta" tool and that tool uses the git protocol for link.s

**Comment by cgewecke** [comment]
@roschler I also had this problem once and I think ended up having to change all the `git` prefixes to `https` in [this](https://github.com/trufflesuite/truffle/blob/develop/.meta) meta config.

**Comment by roschler** [comment]
@cgewecke It turns out it's due to the lack of an SSH key being registered with GitHub.   I needed to set up a proper RSA key for GitHub, which I did using these two documents. Now the git@github.com links work for the main repo and in meta:

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by roschler** [comment]
@cgewecke Pardon the drive-by question.  I want to add a "loadjson" command to the console.  This command will load the JSON content of a particular json file and JSON.parse() it to the variable given.  For example:

```truffle(local)> jsonparse ./contracts/Proxy.json abiProxy```

This command would `fs.readSync()` the content of the file given and assign it to the variable `abiProxy` in the global Javascript namespace.  Can you tell me what repos I need to focus my efforts on in the two two topical areas shown below, in order to accomplish this modification?:

1) Adding a new command to the Truffle REPL shell that executes some code I create; similar to the way you can call `migrate`, etc. from the console?
2) Working with the Javascript VM (core engine) so I can figure out how to push a variable into the global namespace active during a Truffle console session?

There's quite a few projects in the main repo dependencies list (sub-repos) and If I knew what sub-repos to concentrate it, it would be a big help.

BTW, I found it a little strange that the Contributing.md document tells you to do all the main repo and meta/sub-repo stuff _before_ you fork the library.  I would have thought that you should fork the library _first_ and then execute those steps?

**Comment by cgewecke** [comment]
@roschler I like that jsonParse idea :)

I *think* that could all be done in `truffle-core`, which makes things a little simpler from a dev standpoint. Two things to note:
+ It looks like we are very close to a big change in the project architecture - all the modules will go into a single repo and be managed with a tool called [Lerna](https://github.com/lerna/lerna). This has implications for pull-requests in the near term because the transition might be a little awkward.
+ Believe @gnidan is planning to do some upgrade work to `truffle console` quite soon as well - he might be a good person to co-ordinate with and ping ideas off of.

**Comment by cgewecke** [comment]
@roschler Is it ok if we close here? This ishould be resolved by the new lerna setup.

**Comment by roschler** [comment]
Sure.
