### ISSUE TITLE
Error while migrating Metacoin example

### ISSUE THREAD

**Issue by tbenny** [trufflesuite/truffle#995]
truffle migrate Using network 'development'.

**Running migration: 1_initial_migration.js Deploying Migrations... Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: Migrations contract constructor expected 1 arguments, received 0 at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:390:1**

** Solidity File(Migration.sol)**

pragma solidity ^0.4.17;

contract Migrations {
  address public owner;
  uint public last_completed_migration;

  modifier restricted() {
    if (msg.sender == owner) _;
  }

  constructor(Migrations) public {
    owner = msg.sender;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
**  Migration file 1_initial_migration.js**

var Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer) {
  deployer.deploy(Migrations);
};

**2_deploy_contracts.js**

var ConvertLib = artifacts.require("./ConvertLib.sol");
var MetaCoin = artifacts.require("./MetaCoin.sol");

module.exports = function(deployer) {
  deployer.deploy(ConvertLib);
  deployer.link(ConvertLib, MetaCoin);
  deployer.deploy(MetaCoin);
};

truffle version Truffle v4.1.11 (core: 4.1.11) Solidity v0.4.24 (solc-js)
Operataing Sytem : Ubuntu 18.04
Ethereum Client : testrpc

**Comment by cgewecke** [comment]
Hi @tbenny - it looks like your Migrations constructor has a small editing error. This:

```javascript
constructor(Migrations) public {
  owner = msg.sender;
}
```
should look like this:
```javascript
constructor() public {
  owner = msg.sender;
}
```

Closing but please ping if you continue to have issues with this.

**Comment by tbenny** [comment]
The issue is fixed thanks for your help , the metacoin.sol is alos modified to 
pragma solidity ^0.4.23;

import "./ConvertLib.sol";

// This is just a simple example of a coin-like contract.
// It is not standards compatible and cannot be expected to talk to other
// coin/token contracts. If you want to create a standards-compliant
// token, see: https://github.com/ConsenSys/Tokens. Cheers!

contract MetaCoin {
	mapping (address => uint) balances;

	event Transfer(address indexed _from, address indexed _to, uint256 _value);

	constructor() public {
		balances[tx.origin] = 10000;
	}

	function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		emit Transfer(msg.sender, receiver, amount);
		return true;
	}

	function getBalanceInEth(address addr) public view returns(uint){
		return ConvertLib.convert(getBalance(addr),2);
	}

	function getBalance(address addr) public view returns(uint) {
		return balances[addr];
	}
}
