### ISSUE TITLE
truffle can't build on mac cause error pna.nextTick is not a function

### ISSUE THREAD

**Issue by 978740431** [trufflesuite/truffle#996]
![wenti](https://user-images.githubusercontent.com/11803404/41167157-b401c5ce-6b74-11e8-870d-2a530d80a67d.png)
<img width="586" alt="xinxi" src="https://user-images.githubusercontent.com/11803404/41167274-05c452b4-6b75-11e8-9d5a-4c173f458b35.png">

![wanzheng](https://user-images.githubusercontent.com/11803404/41167535-c2d7ef64-6b75-11e8-9763-e687e301e577.png)

how can I solve this error?

**Comment by cgewecke** [comment]
Closing since this seems like it's not specific to Truffle - if anyone discovers otherwise or knows more about this please ping.
