### ISSUE TITLE
darq-truffle@next debugger not working

### ISSUE THREAD

**Issue by RobertoC27** [trufflesuite/truffle#998]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using the debug command is not working with `darq-truffle`, it exits the debug mode automatically. Trying the same command with ```truffle``` is actually working.

## Steps to Reproduce

```darq-truffle debug txhash``` enters debuging mode and then it closes it without user interaction.

## Expected Behavior

Expected to be able to debug using ```darq-truffle```

## Actual Results

Debugger exits automatically.
```darq-truffle debug thxash``` 
![image](https://user-images.githubusercontent.com/8262009/41203489-f3de0f4c-6c94-11e8-8b2d-d3dfcdd28a2d.png)

Had to use ```truffle debug txhash``` instead to debug
![image](https://user-images.githubusercontent.com/8262009/41203510-3c9d66e2-6c95-11e8-8dde-f7c8acb9b22d.png)

## Environment

* Operating System:  Windows 10
* Ethereum client: Ganache CLI v6.1.0 (ganache-core: 2.1.0)
* darq-truffle version (`darq-truffle version`):  Truffle v4.1.4-next.8 (core: 4.1.8)
* Truffle version (`truffle version`): Truffle v4.1.8 (core: 4.1.8)
* node version (`node --version`): v8.11.1
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@RobertoC27 Thanks! Will check this out.

**Comment by cgewecke** [comment]
Update: This turned out to be a publishing error. The debugger is a built project and the way we've been publishing `darq-truffle` failed to take that into account.  

It looks like starting Monday we'll be publishing anything/everything from this repository since we've moved all the modules here and have Lerna installed. This bug should be fixed then and `darq-truffle` will just be called `truffle@next`. 

Will ping this issue when that happens.

**Comment by RobertoC27** [comment]
Just to clarify, i should prepare to use `truffle@next` from Monday on.

**Comment by cgewecke** [comment]
@RobertoC27 Sorry for the delay. Just published `truffle@next`. If you have a chance to report back about whether the debugger works that would be great, thanks!

**Comment by RobertoC27** [comment]
@cgewecke sorry for the delay, i'm a bit short on time but will try to do it during the weekend. Any installation instructions that may have changed? or just `npm install truffle@next`

**Comment by cgewecke** [comment]
@RobertoC27 No worries at all :)  Please take as much time as you need. Yes, that installation line should work.

**Comment by RobertoC27** [comment]
@cgewecke btw, when invoking instructions from this new package. Should it be `truffle@next init` or will it collide with my current truffle global install?

**Comment by RobertoC27** [comment]
@cgewecke being kind of new to this managing my dependencies and scripts stuff, seems like this learning scripts is going to take more time, to really understand what I'm configuring. Sure gonna miss that part of `darq-truffle` :(

**Comment by RobertoC27** [comment]
@cgewecke running the debug statement produces the issue on #1051 
executed command `"./node_modules/.bin/truffle debug 0x7002c8a8eb2706d74bd8b4834b910c9d528be37776c9bacae93f4b996cf769b3"`

![image](https://user-images.githubusercontent.com/8262009/41813739-abcb6920-76f8-11e8-8e49-4f81903fbb51.png)
Notice how it is searching for a path related to your user, is that expected behavior?

**Comment by cgewecke** [comment]
Ah thanks @RobertoC27 - that's a bug - actually now I realize it's also affecting the normal release. 

We're having some teething problems with the new structure and it looks like webpack is not building the debugger correctly. We'll have another release for everything early next week to fix this stuff.

**Comment by cgewecke** [comment]
@RobertoC27 Sorry - this took forever it seems like . . . `5.0.0-next.1` should have fixed the debugger build so `npm install truffle@next` might work.

**Comment by RobertoC27** [comment]
@cgewecke I'm not bearing good news, debugger crashed again. https://gist.github.com/RobertoC27/5b3532b82277b28e880ab8f511fe4f42 a gist with the error output

**Comment by cgewecke** [comment]
Thanks so much @RobertoC27 - there's another report of this at #1051 which affects the non-next build. Hope you don't mind I'm going to close here and track the problem here, adding a link to your gist to the discussion.
