### ISSUE TITLE
darq-truffle not updating sender account for transaction

### ISSUE THREAD

**Issue by RobertoC27** [trufflesuite/truffle#999]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

During unit testing a contract, ran into the issue that the sending account for a transaction was not the same as specified when creating it. Changing the default account for a transaction is not working.

## Steps to Reproduce
Created a contract specifically to test this issue, is in this [gist](https://gist.github.com/RobertoC27/63cbdf3ac598d84da9bcbb8d80f09629)

Executing the commands below should result in passing tests.
`darq-truffle develop`
`test`

## Expected Behavior

Sending account for a given transaction would be the same as specified when creating it.

## Actual Results

![image](https://user-images.githubusercontent.com/8262009/41205186-d81d120a-6cab-11e8-9990-314be1ff3b44.png)

![image](https://user-images.githubusercontent.com/8262009/41205223-742129e8-6cac-11e8-8717-289a5f3d9af3.png)

## Environment

* Operating System:  Windows 10
* Ethereum client: Ganache CLI v6.1.0 (ganache-core: 2.1.0)
* darq-truffle version (`darq-truffle version`):  Truffle v4.1.4-next.8 (core: 4.1.8)
* Truffle version (`truffle version`): Truffle v4.1.8 (core: 4.1.8)
* node version (`node --version`): v8.11.1
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment]
@RobertoC27 Nice find and thanks so much for the reproduction cases. Have opened a PR fixing this and will republish after it's reviewed, probably tomorrow.

**Comment by cgewecke** [comment]
@RobertoC27 This should be fixed in `darq-truffle@4.1.4-next.9`. Closing but please ping if that doesn't resolve it.

**Comment by RobertoC27** [comment]
Yes, issue was fixed. Thanks!
